### ISSUE TITLE
[MU4 and Muse Sounds] Notes overlap in some subdivisions

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#14220] opened 2022-10-31 16:56 UTC
In some groupings the notes overlap for a brief moment. Particularly the next note starts on the tail of the preceding. I have no idea how to pin down the issue because I have experienced this both with legato and staccato groupings and with different rhythms and subdivisions. However, quicker passages don't show this issue as much as 'mid-tempo' subdivisions. In the attached score, the worse are 1/4 note triplets, then 1/8 notes, 1/8 triplets and 1/16. Quintuplets of 16ths seem to be played correctly instead

[Test overlapping.zip](https://github.com/musescore/MuseScore/files/9903183/Test.overlapping.zip)

**Comment by Tantacrul** [comment] 2022-11-01 17:38
With the update to woodwinds and the latest nightly, I'm hearing the problem only on these tuplets.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/21022311/199300470-b1e9df47-83ed-4c45-8c38-8c2c1279416a.png">

Perhaps _slightly_ also in bar one, beats 3 & 4.

**Comment by sberla365** [comment] 2022-11-01 18:23
Today I tested this score on a Hackintosh and I noticed it sounds way better than on my fedora install. Playback seems overall worse in Linux since I tested also in Ubuntu and the results are the same as Fedora. Also in relation to my other issue where the saxophone sounds are blurry and played glissando, on Mac the experience is superior. It seems on Linux payback is way behind other systems

1 nov 2022 18:38:57 Tantacrul ***@***.***>:

**Comment by sberla365** [comment] 2022-11-01 18:32
Maybe worth to know that both Linux and Hackintosh installs run on the very same machine and I have the same issue on my laptop both with fedora and Ubuntu, so I doubt the issue is hardware related

1 nov 2022 18:38:57 Tantacrul ***@***.***>:

**Comment by MarcSabatella** [comment] 2022-11-01 20:04
I can reproduce what I think is probably the same issue just using MS Basic - I don't think it's about Muse Sounds at all.

Try the following, for Bb trumpet, using MS Basic:

![image](https://user-images.githubusercontent.com/1799936/199328718-718fa435-e0b1-42e4-b95f-7204cfd23f4b.png)

I get overlaps on the first triplet.  The second triplet has the opposite propblem - notes cut short (including the whole note, which is played as a staccato quarter).

**Comment by MarcSabatella** [comment] 2022-11-01 20:08
The fact that an overlap causes the subsequent note to get cutoff prematurely is a serious issue in itself, but separate - see https://github.com/musescore/MuseScore/issues/13853

**Comment by sberla365** [comment] 2022-11-01 21:16
Indeed this happens also with MS Basic! Great point @MarcSabatella! It happens to a different degree than with Muse Sounds though; with MS basic seems less pronounced and sometimes cleaner on some passages that with Muse Sounds. But yes, an issue with playback not with Muse Sounds

**Comment by Tantacrul** [comment] 2022-11-01 21:56
Thanks @MarcSabatella. I'm adding @vpereverzev and also assigning it as an MPE issue. If we confirm it is, I'll remove it from Muse Sounds.

**Comment by cbjeukendrup** [comment] 2022-11-16 22:55
The new issue #14559 is possibly a duplicate of this one

**Comment by alago197** [comment] 2022-11-16 22:58
> The new issue #14559 is possibly a duplicate of this one

Yep, it seems so also to me, after reading and checking this issue with Basic , too. Feel free to close #14559 @cbjeukendrup

**Comment by cbjeukendrup** [comment] 2022-11-20 19:31
I think it's been caused by https://github.com/musescore/MuseScore/commit/a0b856cd6860d9788db3253156d1cfab0bd0d859#diff-7d6c04e45fd69d6cf31c1e4f23d1fe096ea5b24fbcf2693f2576f9b66e683f43L107 (but that's only a somewhat educated guess)

**Comment by Tantacrul** [comment] 2022-11-24 12:41
Upgrading to P1 because we have a suspicion this is tied to the 'tuplets clearly not rhythmically correct' issue

**Closed** 2022-11-27 17:42 UTC
Labels: P1

**Comment by sberla365** [comment] 2022-11-29 12:11
@cbjeukendrup 's PR fixes it!
