### ISSUE TITLE
musescore not installing on arch latest as of 8/15/2023 

### ISSUE THREAD

**Issue by XxBigguy3xX** [musescore/MuseScore#19062] opened 2023-08-15 19:38 UTC
### Issue type

Choose option...

### Bug description

I assume that there is a typo in the path at= "share/locale/CMakeFiles/lrelease.dir/all ". Is there supposed to be an L in lrelease?

### Steps to reproduce

1. git clone musescore on arch Linux kernel 6.4.10-zen2-1-zen 
2. cd into MuseScore (I realized it has to be a capital S)
3. download cmake if haven't already (i used yay and downloaded from the Arch User Repositories [that could be my problem])
4. run cmake with these flags "-P build.cmake -DCMAKE_BUILD_TYPE=Release"
5. the error should come up in the command line
6. i also installed it before using the gnome software center so that could be it too.

### MuseScore Version

musescore 4.1

### Regression

No.

### Operating system

arch linux with zen kernel version 6.4.10-zen2-1-zen

### Additional context

cmake -P build.cmake -DCMAKE_BUILD_TYPE=Release
QMake version 3.1
Using Qt version 5.15.10 in /usr/lib
-- QT_LOCATION: /
-- QT_VERSION: 
-- QT_COMPILER: usr
-- SOURCE_PATH:       /home/andrew/MuseScore
-- BUILD_PATH:        /home/andrew/MuseScore/builds/Linux-Qt-usr-Make-Release
-- INSTALL_PATH:      /home/andrew/MuseScore/builds/Linux-Qt-usr-Make-Release/install
-- MSCORE_EXECUTABLE: /home/andrew/MuseScore/builds/Linux-Qt-usr-Make-Release/install/bin/mscore
-- CPUS: 12
-- GENERATOR: Unix Makefiles
-- BUILD_TYPE: Release

~~~~ Actualizing Build step ~~~~

Man pages have been compressed ready for installation.
Creating symlink alias for man pages.
Symlink alias: musescore.1.gz -> mscore.1.gz
[  0%] Built target big_resources_fonts_FreeSans
[  0%] Built target big_resources_fonts_Campania
[  0%] Automatic MOC and UIC for target gtest
[  0%] Generating /home/andrew/MuseScore/share/locale/musescore_en_US.qm
[  1%] Built target big_resources_fonts_Gootville
[  2%] Automatic MOC and UIC for target opus
[  2%] Automatic MOC and UIC for target global
[  2%] Built target big_resources_fonts_Bravura
[  2%] Built target big_resources_fonts_Leland
[  2%] Built target big_resources_fonts_Edwin
[  2%] Built target big_resources_fonts_FreeSerif
/bin/sh: line 1: Qt5::lrelease: command not found
make[2]: *** [share/locale/CMakeFiles/lrelease.dir/build.make:74: /home/andrew/MuseScore/share/locale/musescore_en_US.qm] Error 127
make[1]: *** [CMakeFiles/Makefile2:2196: share/locale/CMakeFiles/lrelease.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target manpages
[  2%] Built target gtest_autogen
[  2%] Built target big_resources_fonts_FinaleBroadway
[  2%] Built target big_resources_fonts_Petaluma
[  2%] Built target big_resources_fonts_MuseJazz
[  2%] Built target big_resources_fonts_MScore
[  2%] Built target big_resources_fonts_FinaleMaestro
[  2%] Automatic MOC and UIC for target kddockwidgets
[  2%] Built target big_resources_fonts_Tabulature
[  2%] Built target opus_autogen
[  2%] Built target global_autogen
[  2%] Built target kddockwidgets_autogen
make: *** [Makefile:146: all] Error 2
CMake Error at build.cmake:249 (message):
  Build step failed with status 2.  See output above for details.

**Comment by cbjeukendrup** [comment] 2023-08-15 22:40
So actually, the issue is a build failure rather than anything else. The reason seems to be that you haven't installed Qt's lrelease tool. I believe it's part of Qt Linguist, so you might need to install/build that.

**Comment by bkunda** [comment] 2023-08-18 13:29
@cbjeukendrup if you think you've found the root cause of this one, please feel free to close/pursue the issue as required. Thanks!

**Comment by cbjeukendrup** [comment] 2023-08-18 13:34
I think we can close it, since it's not an issue on our side. But @XxBigguy3xX, feel free to add more comments to this thread if you have further questions; I'll try to help.

**Closed by cbjeukendrup** 2023-08-18 13:34 UTC
Labels: needs info
