### ISSUE TITLE
Playback and Export with Muse Sounds is lagging massively, causing dropped notes and large rhythmical problems

### ISSUE THREAD

**Issue by Ariakim-Taiyo** [musescore/MuseScore#13936] opened 2022-10-23 19:41 UTC
**Describe the bug**

When using muse sounds, especially strings and woodwinds, there are consistent playback and export issues, such as:
Playback misses notes and loops over itself
Playback plays notes twice
Playback does not articulate correctly
Playback misses rhythms consistently

Screenshots
Playback Issue demo:

https://user-images.githubusercontent.com/79466778/197414296-cc89a00e-e2bc-4781-9e5b-8cb3caa07c20.mp

**File**
Here is the specific musescore file in the demos, but I have experienced these issues consistently with every file I try.
https://drive.google.com/file/d/1VQacgc1WcK5pj5xXKAYeXNQ1flGZQdf9/view?usp=sharing

**Expected behavior**
Rhythmically speaking, MS Basic plays back the sound of the file below much more accurately than Muse Sounds does.

Exported file: https://drive.google.com/file/d/1npMEBH18FCljJKEuK5JzEWBH4naBHlSt/view?usp=sharing

**Platform information**
 - OS: Windows 10, Version 21H2, Build 19044.2006
 - Hardware: AMD Ryzen 5600G, 16GB RAM, RTX 3060

**Comment by Ariakim-Taiyo** [comment] 2022-10-23 19:48
also my buffer size is 2048

**Comment by Tantacrul** [comment] 2022-10-23 19:49
OK, so there is a lot of good stuff here but I have to emphasise that we cannot solve all these issues at once, so we are going to have to split it into different issues.

For now, the stuttering / slowness issue is already known, so I'll remove that from the description here. What is very much reproducible for me is the really bad oboe playback, which keeps missing notes and is very rhythmically off. I'm going to focus this issue on that.

As for the crashing bug, can you please log that separately?

**Comment by Tantacrul** [comment] 2022-10-23 20:03
Also, can you send us an example of the bad export you mentioned too?

**Comment by Tantacrul** [comment] 2022-10-23 20:06
@DmitryArefiev - these issues are clearly going to be the ones we need to focus on the most. Can you possibly see if you can get more info and possibly begin collating a list of commonly affected OS versions / machines.

I see an AMD Ryzen 5600G. This is a bit lower spec than my Ryzen 3900x (where I have no problems with playback - also using windows 10)

**Comment by Ariakim-Taiyo** [comment] 2022-10-24 02:10
> Also, can you send us an example of the bad export you mentioned too?

Here is the export of the same project above: https://drive.google.com/file/d/1npMEBH18FCljJKEuK5JzEWBH4naBHlSt/view?usp=sharing
The audio doesn't start for around a minute.


> @DmitryArefiev - these issues are clearly going to be the ones we need to focus on the most. Can you possibly see if you can get more info and possibly begin collating a list of commonly affected OS versions / machines.
> 
> I see an AMD Ryzen 5600G. This is a bit lower spec than my Ryzen 3900x (where I have no problems with playback - also using windows 10)

I don't think that it's necessarily a CPU problem, since task manager shows about 7% CPU usage.
I have since updated windows to build 19044.2130 (most recent available to me) and it seems to have fixed some of the issues. (Unless you changed something on your end in the meantime, I was at work so I couldn't check sooner.) 
Now, the crashing issue is gone, but the other issues are almost reversed;
The playback is about double the tempo I select and the pitch is an octave higher than written even though I have not transposed anything. I sounds like the entire playback is just being sped up x2, which is altering the pitch as well. The export is sounding correct now, however. The playback is reasonably smooth as well.

My conclusion here is that it may have been due to the older version of Windows 10 I was using, but again, I'm not sure if you've changed anything on the software side.

Once thing that I'm not sure about is if my peripherals may be causing the issue, since I have a MIDI controller as well as an audio interface plugged in via USB. I doubt this is an issue but i'll check.

**Comment by Ariakim-Taiyo** [comment] 2022-10-24 02:18
Alright, after unplugging all peripherals aside from my headphones, keyboard, and mouse and restarting, it appears that Musescore 4 has reverted back to the initial state it was in 7 hours ago.
It appears that the program only starts crashing if I close Musescore and open it again. First run is usually fine in terms of crashing.

If there's any specific info you need feel free to ask me about it and provide instructions if necessary and I will do my best to provide the requested details.

**Comment by Ariakim-Taiyo** [comment] 2022-10-24 02:44
A few things that might be useful after a bit of digging:
Here's the log file that it gave me after one of the crashes: 
[MuseScore_221023_222420.log](https://github.com/musescore/MuseScore/files/9848359/MuseScore_221023_222420.log)
Upon a bit of light investigation, it looks like for some reason it's calling to the youtube API and exceeding some quota: 
```
{
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}
```
I've also analyzed the most recent memory dump file and found the following info:
```
ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

. . .

SYMBOL_NAME:  MuseSamplerCoreLib+10cf0f

MODULE_NAME: MuseSamplerCoreLib

IMAGE_NAME:  MuseSamplerCoreLib.dll

STACK_COMMAND:  ~96s; .ecxr ; kb

FAILURE_BUCKET_ID:  INVALID_POINTER_WRITE_c0000005_MuseSamplerCoreLib.dll!Unknown

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {5cd775d8-9437-f477-a34a-7c30edfe08be}

Followup:     MachineOwner
```
I can send the rest of the dump file in raw format if that would be useful as well, but from what I can tell it's likely very system-specific info referencing physical memory addresses.

**Comment by Tantacrul** [comment] 2022-10-24 08:16
We are noticing a lot of issues from those with certain kinds of sound card setup, as well as other devices such as your headphones. That's very helpful. Thanks.

**Comment by Ariakim-Taiyo** [comment] 2022-10-24 15:23
Audio setups can sure be a pain to deal with lol. If there’s anything else you want me to send you then feel free to ask, I’d be more than happy to help you all.

**Comment by Zanctarian** [comment] 2022-10-26 01:17
Adding on to this, as I believe my issue connects to this one. When using MuseSounds, not Basic, notes have a tendency to not separate, like they're all tied together essentially. This doesn't appear to be instrument specific, and only happens when using MuseSounds (refer to the video)

https://user-images.githubusercontent.com/44514121/197911722-0a50830f-c140-4117-a088-cbfdf5f8e41a.mp4

Platform info:
- OS: Windows 11 Enterprise, Version 21H2, Build 22000.1098
- Hardware: Intel i5-10400, 16gb DDR4, RTX 3070 Ti

**Comment by Tantacrul** [comment] 2022-10-26 08:03
> Adding on to this, as I believe my issue connects to this one. When using MuseSounds, not Basic, notes have a tendency to not separate, like they're all tied together essentially. This doesn't appear to be instrument specific, and only happens when using MuseSounds (refer to the video)
> 
>  2022-10-25.20-08-48.mp4 
> Platform info:
> 
> * OS: Windows 11 Enterprise, Version 21H2, Build 22000.1098
> * Hardware: Intel i5-10400, 16gb DDR4, RTX 3070 Ti

This feels like a separate issue, which I have logged on your behalf here: https://github.com/musescore/MuseScore/issues/14051

It would be **really** helpful if you could link us to the score. If you don't want to share it publicly, then I'd appreciate if you sent it to info.tantacrul@gmail.com, so I can check myself

**Comment by Tantacrul** [comment] 2022-11-22 18:01
@Ariakim-Taiyo could you please test this build:
https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

It includes a lot of performance improvements. We have another major improvement coming soon but it would be massively helpful if you'd try this one out.

Try 1024 as a buffer. Please also try the other settings with your headphones too. Tell us if anything is still causing problems.

Thanks for all your help!

**Comment by vpereverzev** [comment] 2022-11-28 10:09
@Tantacrul @DmitryArefiev I suggest simply close this since we've done tons of testing in that area already. If @Ariakim-Taiyo will appear with the same problems at some point, we can re-open this issue

**Comment by Tantacrul** [comment] 2022-11-28 11:59
I agree, since the remaining issues are dropped notes during fast tempi, which is logged separately.

**Closed by Tantacrul** 2022-11-28 11:59 UTC
Labels: P0
