### ISSUE TITLE
Playback with MuseSounds falls completely silent after a certain point.

### ISSUE THREAD

**Issue by tiamottu** [musescore/MuseScore#17384] opened 2023-04-28 13:09 UTC
### Issue type

Muse Sounds bug

### Bug description

I have a MuseScore file where I keep note of interesting bits of music I find, so it's basically a single file with dozens of very short movements. I keep running into this problem where after a certain number of bars, usually at about 800, MuseSounds just gives up working. It doesn't freeze or crash the software or anything like that, actually the playback cursor often keeps on going, but the audio falls silent. Even the mixer doesn't register any sound, it shows silence on all the tracks.
I've attached a link to the file down below so you can download it and check it out for yourself; it occurs about four bars to the end in the final passage, that one from Graupner.
With MS Basic and online on musescore.com it works fine, btw. I've tried changing instrument, ex. using the harpsichord or guitar packaged with MuseSounds, but no such luck.
I don't know if what overwhelmes MuseSounds is the number of measures (I don't think so, I've seen thousands-of-pages 19th century symphonies on musescore.com), the number of changes in dynamics, in tempo, ecc... Maybe it's just Windows 11, dunno.
It's not actually that big of an inconvenience, I can just use MS Basic instead. I wanted to bring this to people's attention more so because I think it'd be a shame if a bug in one of the major selling points of the new MuseScore release went unaddressed and killed the hype in some people (not a risk with me though :)).

Sorry for the long description and thanks in advance!

P.S. You can also probably notice there's a high note in the voice held at some point in that same file. That kind of "permanence" of past notes in the playback, like a ghost note but not the jazz kind, is another bug I've seen; I think I'll report that too some time.

### Steps to reproduce

1. Open a somewhat large MuseScore file, above 800 measures. Take for example this https://musescore.com/user/31541077/scores/10672141/s/8AFi1P?share=copy_link.
2. Change the playback setup to MuseSounds.
3. Start playback, from the start or from about that 800 mark doesn't matter.
4. MuseSounds falls silent at some point around that.

### MuseScore Version

4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2023-04-30 00:30
This looks like a duplicate of https://github.com/musescore/MuseScore/issues/15768. I'll close this one in favour of the other. If I remember correctly, the MuseScore side of the fix was already included in MuseScore 4.0.2, but the Muse Sounds side still has to be released.

**Closed by cbjeukendrup** 2023-04-30 00:30 UTC
Labels: muse sounds
