### ISSUE TITLE
(Continuous View) Adding Bugged Tie with Random Notes

### ISSUE THREAD

**Issue by JacobPicking** [musescore/MuseScore#21001] opened 2024-01-14 03:16 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

- Only occurred in random places in my score
- Deleting or moving the bugged tie stretches the measure it was in. (repeatable too) 
- Seems to be an issue in continuous view only: Placing the tie works normally in page view, but breaks once switching to continuous. Switching to page view and back after deleting the tie and experiencing a "stretch" in the measure makes the measure look normal again.
- Restarting Musescore does not fix the issue.

### Steps to reproduce

1. Click a note (not sure why this note specifically) in continuous view
2. Add a tie to a neighboring note
3. Receive a bugged tie that is visually wrong and that is towards the wrong direction.
4. Delete the tie 
5. Measure is stretched
6. Switch to page view
7. Switch back to continuous 
8. Reverted to normal (though tie still does not work the next time)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/156558407/d3bdad04-dcf6-4140-89f1-e2290e26cfd7

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2024-01-14 08:43
Duplicate of https://github.com/musescore/MuseScore/issues/20551, fixed in 4.2.1

**Closed by oktophonie** 2024-01-14 08:43 UTC
Labels: engraving
