### ISSUE TITLE
[MU4 Issue] High tempo causes dynamics to differ from note to note

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#14378] opened 2022-11-07 00:27 UTC
**Describe the bug**
Relating to #13902, when you have a high tempo with an increasing dynamic later in the score, not only will it get gradually louder, but notes sound like they also have differing velocities between each other.

**To Reproduce**
1. Create a score using Muse Sounds
2. Set dynamic to mp
3. Set dynamic later in score to f
4. Start score slow then change to quicker tempo (ex. quarter = 220)
5. Hear differing dynamics in notes

**Expected behavior**
The dynamic should be the same for all the notes

**Video**
Comparing with tempo change to without
https://user-images.githubusercontent.com/34029777/200204085-882f02e1-d1fe-47c7-822b-ae7594287bb0.mp4

**Platform information**
 - OS: Windows
 - Build: Nightly 11-06-22

**Comment by Tantacrul** [comment] 2022-11-21 18:46
This actually is not due to the tempo. There is a known issue where two dynamic markings will gradually transition into each other even though there is no cresc. line in this instance. It's getting louder because it starts mezzo piano there is a forte mark at the end.

**Comment by Tantacrul** [comment] 2022-11-21 18:47
Duplicate of https://github.com/musescore/MuseScore/issues/13902

**Closed by Tantacrul** 2022-11-21 18:47 UTC
