### ISSUE TITLE
Score crashes on save to cloud, export and mp3.

### ISSUE THREAD

**Issue by PyrdePavkki** [musescore/MuseScore#18160] opened 2023-06-24 18:15 UTC
### Issue type

Crash or freeze

### Bug description

Crashes when putting it to mp3 in any way. PDF works.

Uses muse sounds, did work previously but now has suddenly decided not to work. Playback works fine, export does not.

### Steps to reproduce

1. Download the file linked
2. Make sure you have all the specific muse sounds
3. Export mp3 (incl. save to cloud)

You will notice a crash

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10

### Additional context

File: [https://musescore.com/user/41597853/scores/11265574/s/Vx1G0D?share=copy_link](https://musescore.com/user/41597853/scores/11265574/s/Vx1G0D?share=copy_link)

**Comment by PyrdePavkki** [comment] 2023-06-24 18:18
Note: Worked previously until I changed some things in the sheet music (added a lot of stuff). Can provide old version too: [here (4 days ago)](https://musescore.com/user/41597853/scores/11209717/s/cF7yno?share=copy_link)

**Comment by zacjansheski** [comment] 2023-06-28 17:35
I am unable to reproduce this issue.  I am on Windows 11 with MuseSounds Beta.  Perhaps updating to the beta version would resolve this?  

Uninstall MuseHub, then download the Beta at the bottom of https://www.musehub.com/

**Comment by zacjansheski** [comment] 2023-07-21 19:39
Closing, not reproducible

**Closed by zacjansheski** 2023-07-21 19:39 UTC
Labels: needs info, crash
