### ISSUE TITLE
Measure numbers render below top staff instead of below entire system when set to be placed below

### ISSUE THREAD

**Issue by CerealSSBU** [musescore/MuseScore#23608] opened 2024-07-13 22:45 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score with multiple staves/instruments.
2. Format->Style->Measure Numbers
3. Set Vertical Placement to Below
Expected behavior: Measure numbers are placed at the bottom left of each system.
Current behavior: Measure numbers are placed at the bottom left of the top staff.

The staff which the measure numbers are anchored to should change from the top staff in a system to the bottom staff in a system when the vertical placement is set to "Below", but the measure numbers currently remain anchored to the top staff.

### Supporting files, videos and screenshots

![expected behavior](https://github.com/user-attachments/assets/5c96ced6-1818-4692-aead-5143e33b610c)
![current behavior](https://github.com/user-attachments/assets/f4422d27-0e0b-4117-abba-d3b1533cac39)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Windows 10

### Additional context

While the desirable outcome is possible to produce, doing so is extremely tedious on a larger scale. For a large-scale orchestral work, to put measure numbers below the system and number every measure requires disabling auto-place and individually moving every single measure number to the exact desired location, taking an extreme amount of time on a 1000+ measure score. This cannot be done by simply designating a vertical offset in the Style either, since staves appearing and disappearing throughout the score will vary the amount of vertical space between the top and bottom of systems.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-07-14 09:36
Duplicate of https://github.com/musescore/MuseScore/issues/17127

**Closed by oktophonie** 2024-07-14 09:36 UTC
Labels: engraving
