### ISSUE TITLE
Note gets stuck on when putting in notes quickly using MuseSounds

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17792] opened 2023-05-30 16:40 UTC
### Issue type

General playback bug

### Bug description

Please see the video as this is difficult to reproduce / explain in text.

I am able to do this on both my mac and pc.  I add multiple instruments and click add notes quickly.

### Steps to reproduce

1. Create a new score, add a few notes
2. Add multiple instruments with MuseSounds (I add all the woodwinds in the video)
3. click to add two notes on various staves.
4. If you do not reproduce the issue, try to delete the instruments and start over.

Eventually one of the notes inputted will be stuck on.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/488d0bda-090c-496f-961c-1b2006f81635

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231500302, revision: github-musescore-musescore-e96b96f

### Regression

I don't know

### Operating system

Windows 11 and Mac OS 11.6.5

### Additional context

Please let me know here if there is a more straightforward way to reproduce this.

**Comment by zacjansheski** [comment] 2023-05-31 13:58
Could be related to https://github.com/musescore/MuseScore/issues/12523 or https://github.com/musescore/MuseScore/issues/12669 but it is not a VST
Could be related to https://github.com/musescore/MuseScore/issues/12324 (closed) but it is not produced with MIDI keyboard.

**Comment by zacjansheski** [comment] 2023-06-01 18:44
I am unable to replicate with MS Basic instruments

**Comment by bmarwell** [comment] 2023-06-01 20:53
It is easier to reproduce with keyboard. I input notes using my keyboard and it happens to me all the time (Manjaro Linux user here).

**Comment by RomanPudashkin** [comment] 2023-11-24 12:55
@iamtesch could you please help with this issue? It seems that the issue is on the MuseSampler side (at least I can't find what can cause it on the MuseScore side)

**Comment by konradglas** [comment] 2024-04-30 06:50
@RomanPudashkin did you find any easier way to reproduce this issue? I am having a hard time. All I can do until now is getting the Mixer Meters stuck (sound is ok though)

**Comment by DmitryArefiev** [comment] 2024-04-30 15:15
@konradglas Oh, it's easy. Using PC keyboard, just input quickly: C-D-C-D.. etc. 
Or input C+D together


https://github.com/musescore/MuseScore/assets/90187801/172f5296-c86c-44b9-8ba2-e84a5ea5240b

**Comment by DmitryArefiev** [comment] 2024-05-15 09:25
Fixed on muse sampler side. 

Tested in 4.3 and 4.4 with musesampler **0.6.2.194** on Win10, Mac13.6, LinuxUbuntu22.04 - **FIXED**

**Closed** 2024-05-15 13:19 UTC
Labels: P1, playback, muse sounds
