### ISSUE TITLE
[MU4 Task] Being able to export scores as MuseScore files

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16518] opened 2023-02-24 01:06 UTC
For some reason, you can no longer export scores as MuseScore files, which was possible in MuseScore 3, thus making this a regression. This is especially important as there are plenty of times where I want to export a specific part from a full score as its own MuseScore file so that I can edit that part while having the full score unaffected by the changes made.

**Comment by oktophonie** [comment] 2023-02-24 08:34
Duplicate of https://github.com/musescore/MuseScore/issues/15582

**Closed by oktophonie** 2023-02-24 08:34 UTC
