### ISSUE TITLE
MuseHub cant start MuseScore download on Windows 11

### ISSUE THREAD

**Issue by amminadabz** [musescore/MuseScore#14316] opened 2022-11-05 01:15 UTC
Running on Windows 11 Home 21H2 on a Dell XPS 13 9300.

Installed MuseHub from the beta announcement page. Opened, appears to have downloaded all of the MuseSounds upon request, but trying to install MuseScore from the hub results in a spinning wheel but never seems to start downloading (notice the lack of ETA or download speed).

![Screenshot (1)](https://user-images.githubusercontent.com/51542239/200094523-541e6552-f282-4f8b-9630-54fd558f5603.png)
[logs.zip](https://github.com/musescore/MuseScore/files/9942654/logs.zip)

**Comment by amminadabz** [comment] 2022-11-05 02:52
After restarting windows, it seems to be working now. Still worth looking into, as I imagine this is the first thing anyone will do after installing hub.

**Comment by iamtesch** [comment] 2022-11-05 06:12
Sorry for the issue here -- I think this was caused by an intermediate update that caused some issues.  I'll leave this open for now to see if this happens for anyone else.

**Comment by Jojo-Schmitz** [comment] 2022-11-05 09:09
I had the same issue, Restarting Windows 11 did not resolve it.

**Comment by iamtesch** [comment] 2022-11-08 15:47
@Jojo-Schmitz -- can you let me know which version of Muse Hub you are currently on?

Also, can you try alt-clicking to stop the MuseScore download, then trying this again?

**Comment by Jojo-Schmitz** [comment] 2022-11-08 17:25
I've resolved my issue by uninstalling MuseScore 4 and Muse Hub, removing the entire C:\ProgramData\MuseHub and C:\ProgramData\MuseSampler and reinstall Muse Hub from scratch

**Comment by Haru00007** [comment] 2022-11-10 11:43
I have the same problem with Windows10 Home x64.
As Jojo-Schmitz said, I've uninstalled and reinstalled Musehub many times.
I couldn't download and install it. When Musehub tried to install Musescore, it said "Unable to download/install Musescore" like the image below.
I've tried this issue for 3 days, but I could not.
How can I solve this problem? (I am Japanese, so my English might not be good. Sorry.)
![スクリーンショット 2022-11-10 204037](https://user-images.githubusercontent.com/39019007/201081871-f700a6be-f69f-457e-8c59-5ca088700832.jpg)
![スクリーンショット 2022-11-10 204027](https://user-images.githubusercontent.com/39019007/201081873-75447c1a-75aa-44e4-b2dc-90defb414a6a.jpg)

**Comment by Jojo-Schmitz** [comment] 2022-11-10 11:54
Your English is very certainly better than my Japanese ;-)
Did you also remobe all of C:\ProgramData\MuseHub and C:\ProgramData\MuseSampler?

**Comment by Haru00007** [comment] 2022-11-10 12:08
> 

(In fact, I often use Google translate lol)
Yeah, I did.
I tried this way:
1, uninstall Musehub
2, remove all MuseHub and MuseSampler
3, download the musehub installer at musehub.com
4, download and install musehub
5, when I try to download musescore, like the video below. I waited for this thing for a day, but it doesn't happen.
https://drive.google.com/file/d/1wWTMaJRDzz-bLoBp5mcqO-4c2bxtWJ40/view?usp=sharing
musehub version: 0.9.9.515(x64)

**Comment by Haru00007** [comment] 2022-11-11 09:37
Hmm.
I can download and install everything without musescore...
I think musescore has problems.

**Comment by Haru00007** [comment] 2022-11-12 01:02
I saw the service_log, Exit code is 1618. (Another installation is being processed)
So, I may solve this problem.

**Comment by Haru00007** [comment] 2022-11-14 08:15
I did the troubleshooting of installing/uninstalling the program, I finally install it!

If there is a person who has the same problem, please try this:
1, Remove all of C:\ProgramData\MuseHub and C:\ProgramData\MuseSampler
2, Go to https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d , and download troubleshooting tool.
3, Run it and click "next".
4, If you came to this screen which is like below, choose the Musescore 4 (the image language is Japanese, sorry...)
![スクリーンショット 2022-11-14 171227](https://user-images.githubusercontent.com/39019007/201608556-0b2f9955-9285-4787-9133-d270784e3889.jpg)
5, If it ends, install Muse Hub and Musescore.
6, You can install musescore! done!

**Comment by iamtesch** [comment] 2022-12-06 16:11
Closing as resolved, as an uninstall/reinstall fixed the issue and it appears that it is a non-issue on the newer version.

Please reopen if this occurs again!

**Closed by iamtesch** 2022-12-06 16:11 UTC
Labels: P0
