### ISSUE TITLE
Search dynamics by name

### ISSUE THREAD

**Issue by jscd** [musescore/MuseScore#19032] opened 2023-08-11 21:49 UTC
### Your idea

You should be able to search for dynamics by name, e.g. "forte" or "pianissimo."

### Problem to be solved

I believe this to be expected functionality. It makes some sense with the more crazy ones ("ffffff" is pretty unambiguous), but currently if you just search "f" you get many undesired results and nothing when you just type "forte."

**Comment by oktophonie** [comment] 2023-08-14 10:59
Duplicate of https://github.com/musescore/MuseScore/issues/12905

**Closed by oktophonie** 2023-08-14 10:59 UTC
Labels: duplicate, feature request
