### ISSUE TITLE
Musescore 4 playback issue (instruments won't stop playing, a high note comes in and won't go away)

### ISSUE THREAD

**Issue by gerhardschneider1** [musescore/MuseScore#18355] opened 2023-07-02 22:23 UTC
### Issue type

General playback bug

### Bug description

I just downloaded Musescore 4 and imported my composition for large ensemble. I have two problems with the playback function.

On a certain spot in the composition the orchestra plays together, then everybody stops playing but the choir.
But in Musescore4 the accordion just continues to play, even though there is nothing written for it but rests.
Also on the singer tracks there is some high pitch note, that won't go away for the rest of the composition (another 7 minutes) and gets louder. Sounds like some kind of feedback.

I isolated the part from the composition in this mscz file here "bug GitHub".

When you listen from the beginning, you see that in bar 6 there should just be the singers, but there is also a accordion chord, and also this high pitch note on all of the singer tracks. Nothing is written there.

And second:
When clicking on a note or a bar and pressing the spacebar, in musescore3 the playback would start every time. Now in musescore it sometimes won't start at all and just the blue vertical line appears and is stuck and sometimes only one instrument is playing. Selecting one bar vertically in all instruments and then playing space seems to work fine, but this is just a new small disturbance which really takes away your workflow especially when writing big scores.

I really hope somebody can help, right now I am simultaneously opening musescore 3 and 4, to allow some kind of workflow, which is not really effective obviously. I will change back to musescore 3 for the next composition, if these problems can't be fixed.

Thanks!
[bug github .mscz.zip](https://github.com/musescore/MuseScore/files/11931605/bug.github.mscz.zip)

### Steps to reproduce

1. open the "bug GitHub.mscz" file in musescore 4
2. play the song from the beginning
3. in bar 6 there is accordion and a high pitch notes in the singers, even though not written in the score.
it should be just the quiet "deep" voices.

### MuseScore Version

4.02

### Regression

No.

### Operating system

macOS ventura 13.4.1.

**Comment by bkunda** [comment] 2023-07-03 13:09
Hi @gerhardschneider1,
Thanks for reporting this. Do you also experience these problems using the 4.1 beta?

**Comment by gerhardschneider1** [comment] 2023-07-03 13:42
Hello bkunda, thanks for replying. 
Yes, the same problem also occurs with 4.1 beta!

**Comment by gerhardschneider1** [comment] 2023-07-03 14:00
I deleted the pedal lines and the accordion stoped playing where it should! That's great!
But what's with the high c not stopping in the 4 voice tracks? This is the high c from measure 2, which stops playing hearable where it should but then continues quietly afterwords never stoping for the whole composition. And it gets louder with time like a feedback. 

I changed the notehead from a cross to normal, now the glissando voice figure suddenly won't play as beautiful (as intended), but also the continuous high c is away... 

This seems to be a bug with the cross noteheads, maybe in combination with glissandi, where the high note won't stop playing and gets louder with time. And also a bug with the pedal lines, making the instrument to continue playing endlessly.


Also: Do you have an idea why sometimes I can click on a note and press the spacebar, and a normal tutti playback plays, sometimes I click on a note and press the spacebar and nothing happens, sometimes only one voice plays, and sometimes I need to mark the whole measure in all instruments and press space for the playback to come?

Thank you!

**Comment by MarcSabatella** [comment] 2023-07-04 16:03
The issue with cross noteheads is probably https://github.com/musescore/MuseScore/issues/16389

For the rest if your support questions, please refer back to your forum thread.

**Comment by bkunda** [comment] 2023-07-05 10:06
Yes it seems the voice-sustaining issue in this score is connected to the notehead, for which we already have an issue (duplicate of #16389). 

The pedal lines with the accordion does indeed present a problem. I confess I am unsure about whether pedal lines are typical (or required) for accordion music – if they are, then it would be best if this were first tested for reproducibility, then raised as a separate issue. 

Your other questions about the spacebar and playback should certainly find responses in the support forum over on musescore.org (there is a set behaviour for what gets played back depending on what you have selected).

I hope this resolves these issues. Closing this issue now but happy to reopen if there is something else we've inadvertently missed. 

Thank you @gerhardschneider1!

**Closed by bkunda** 2023-07-05 10:06 UTC
Labels: playback
