### ISSUE TITLE
Notes prematurely cut off during playback

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18349] opened 2023-07-02 13:25 UTC
### Issue type

Playback bug

### Bug description

A bug causing the premature cutting off of note playback was apparently fixed in #13853. However the example shown below may be related.

### Steps to reproduce

Open the attached file and play measure 6:
[notes_cut_off.zip](https://github.com/musescore/MuseScore/files/11929605/notes_cut_off.zip)

![notes_cut_off](https://github.com/musescore/MuseScore/assets/87246583/3ca76f0e-7e91-4120-ae83-38f0ace9895e)

RESULT: The half notes in voice 2 are abruptly cut off.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231830502, revision: github-musescore-musescore-89b5a47

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment] 2023-07-03 13:14
@rgreen5 does this happen with MuseSounds only or with MS Basic too?

**Comment by MarcSabatella** [comment] 2023-07-03 13:25
This is guitar, so definitely not Muse Sounds.  I can reproduce in MS Basic.  But I think it's a not a new regression - it's been broken since 4.0.  The issue is the repeated note after the arpeggio, and as such it's presumably a duplicate of https://github.com/musescore/MuseScore/issues/11936

**Comment by rgreen5** [comment] 2023-07-03 16:07
> The issue is the repeated note after the arpeggio, and as such it's presumably a duplicate of #11936

Agreed.

**Comment by bkunda** [comment] 2023-07-05 10:28
happily! 
Thanks @rgreen5 🙂

**Closed by bkunda** 2023-07-05 10:28 UTC
Labels: regression_ms3
