### ISSUE TITLE
[MU4 Issue] Very high CPU utilization in QSGRenderThread compared to MU3

### ISSUE THREAD

**Issue by theofficialgman** [musescore/MuseScore#15982] opened 2023-01-20 00:54 UTC
**Describe the bug**
In MU3 when during playback the CPU utilization was low (QSGRenderThread was at about 2-10%). In MU4 when during playback of the same score CPU utilization is very high (QSGRenderThread was at about 90+% even on a very high end CPU). Tested and confirmed on multiple linux systems (though it is probably also and issue on MacOS and Windows as well)

( edit: related issue posted by another user on the forum after this https://musescore.org/en/node/342753 )

**To Reproduce**
1. Playback any score in MU4
2. use `htop` and enable `custom thread names` to see the thread name for QSGRenderThread
3. observe very high cpu usage of one thread

**Expected behavior**
CPU utilization is near to MU3

**Screenshots**
MU3 (3.6.2) - cpu is at very low clocks and utilization is low. playback cursor moves smoothly
![image](https://user-images.githubusercontent.com/28281419/213594652-aa7d9069-4aa9-4455-8eed-27f83e0c394d.png)

MU4 (4.0.1)- cpu is boosting to maximum clock speed and utilization is high. playback cursor does not move smoothly (on low end/normal systems)
![image](https://user-images.githubusercontent.com/28281419/213594815-61fc4d41-31e8-4494-ab75-dd743fe49b71.png)

**Platform information**
 - OS: Linux

**Comment by cbjeukendrup** [comment] 2023-01-20 11:51
It looks like QSGRenderThread is related to QML; in that case, the increase seems very understandable: in MS3, only the palettes were written in QML, while MS4 is completely written in QML.

**Comment by cbjeukendrup** [comment] 2023-01-20 12:00
But wait, you're saying that it's during playback specifically... then the problem is maybe that in MS4 we try to make the playback cursor move smoothly and therefore we're redrawing the whole score (not even just the playback rectangle, but the whole viewport) after every tick that is played. That's quite suboptimal indeed...

**Comment by theofficialgman** [comment] 2023-01-20 12:43
Yes only during playback there is a difference. CPU usage is low when idle and high when moving the cursor around on the sheet in both versions.

Especially on my low power system the CPU can't keep up with redrawing so the cursor actually moves very non-smoothly. Mu3 had a smooth cursor movement.

My high power desktop the cursor moves smoothly but that won't be most people's experience because it literally is taking a CPU with nearly the top single core performance out there to do so.

**Comment by theofficialgman** [comment] 2023-01-31 13:26
related issue found on the issues forum: https://musescore.org/en/node/342753

**Comment by DmitryArefiev** [comment] 2023-03-13 13:34
Fixed in #16399

**Closed** 2023-03-13 13:39 UTC
Labels: P2
