### ISSUE TITLE
Musescore crashes when I try to export this score as a MIDI

### ISSUE THREAD

**Issue by Eddy67716** [musescore/MuseScore#21200] opened 2024-01-25 07:36 UTC
### Issue type

Import/export issue

### Bug description

When I try to export the file attached below, it crashes and the MIDI file is incomplete

### Steps to reproduce

1. Open enclosed file,
2. Export as MIDI
3. It crashes and the MIDI file is incomplete
[logs.zip](https://github.com/musescore/MuseScore/files/14048174/logs.zip)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by Eddy67716** [comment] 2024-01-25 07:37
[Koopa_Road.zip](https://github.com/musescore/MuseScore/files/14048204/Koopa_Road.zip)

**Comment by bkunda** [comment] 2024-01-26 14:33
@zacjansheski pls investigate

**Comment by zacjansheski** [comment] 2024-01-26 16:16
The problem is with this "Orchestra hits" instrument
One of those files  where the instrument name does not appear in the instrument panel.
There is no crash if you the instrument or replace with piano and reassign to orchestra hits

<img width="698" alt="Screenshot 2024-01-26 at 11 13 11 AM" src="https://github.com/musescore/MuseScore/assets/69917893/ff77e08a-09b6-4c5b-9a08-bdbdf9ef1647">

**Comment by zacjansheski** [comment] 2024-01-26 17:05
@Eddy67716 do you have any idea how the score got into that state with the missing instrument name?

**Comment by Eddy67716** [comment] 2024-01-26 20:57
> @Eddy67716 do you have any idea how the score got into that state with the missing instrument name?

I think it happened when MuseScore 4 came out.

**Comment by MarcSabatella** [comment] 2024-01-27 00:29
There was a bug early on where starting to replace an instrument then canceling could leave things stranded kind of like this…

**Comment by zacjansheski** [comment] 2024-01-29 21:16
Luckily the score is easy fix.  Unfortunately there is not much else we can do here, thank you!

**Closed by zacjansheski** 2024-01-29 21:16 UTC
Labels: needs review, corruption, crash, MIDI

**Comment by cbjeukendrup** [comment] 2024-01-30 00:21
For the record, I still did some investigation. Thanks very much @MarcSabatella for that hint; the issue you mean is #14303. The mscx file looks exactly like what you get when you do "Replace instrument" without selecting an instrument and then saving, closing, re-opening and re-saving. That combined with the fact that the file seems to have a long history (because of the `<Synthesizer>` tag) makes it very likely that this is indeed what happened. The good news is that that bug was fixed a few updates ago, so it won't happen again for not-yet-broken scores!
