### ISSUE TITLE
Incorrect behavior when using local time signatures

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25090] opened 2024-10-08 17:01 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

I will try to be extremely objective and briefly describe what troubles I have recently encountered.
I recently tried to rewrite the 1st movement [Élégie] of Tchaikovsky's 3rd Suite (opus 55) in MuseScore Studio. I could not do this, because I had to face a lot of errors, which unfortunately could not be fixed and circumvented.

So let's start in order. The 1st movement has interchangeable meters (the main 6/8 is interchangeable with 2/4). Moreover, they are interchangeable irregularly. 
Local time signatures seem to work in MuseScore Studio. Well, let's try to make sure of that. 
I usually rewrite the full score from the bottom up (starting with double basses and ending with flutes).
1. I start with the bass. At this stage, I have no problems with local time signatures.

https://github.com/user-attachments/assets/3c11486d-022c-4992-bcf0-18b7c513f276

2. Let's move on. Now I need to notate the violins. Pay close attention to what you see now:

https://github.com/user-attachments/assets/a58fe02d-cc74-4fd9-9484-d57c351b2b28

As soon as I added the local time signature, the time signature was immediately duplicated on all the staffs in the bar where the local time signature was first added (in double basses). Let's say I don't pay attention to it, I move on. But how do I go further if I need to notate the bars in 2/4, and not in 6/8, which is duplicated on all the staffs? The most interesting thing is that for some reason these duplicated time signatures cannot be deleted.

3. Let's say I can replace the duplicated time signature with another local time signature so that I can further notate the bars in 2/4. That's what I'm doing. But then it gets even more interesting. After I added another local clock size, I can't add 6/8!

https://github.com/user-attachments/assets/016846c7-9b5f-48be-91a1-f59d9562b744

4. However, local time signatures can still be added, but there is one caveat: you can no longer delete them.

https://github.com/user-attachments/assets/a74b9a5e-6c5d-499a-bc36-08dca454ae8a

5. If you try to enter something in the bass, the file will be corrupted: 

https://github.com/user-attachments/assets/719d0e26-fac4-4871-8a9a-012803630ea2

Although it's not about the bass at all, but something else (I don't know exactly what causes errors in the file, but I can assume that in some bars the local time signature "infects" an adjacent bar and there is a discrepancy in terms of metre compliance).

### Supporting files, videos and screenshots

I've notated everything I could. The score, in which I tried to rewrite the 2nd movement of the Suite, is attached below[^1]. You can open this score and test the behavior. As the main problems: it is impossible to add 6/8 between local time signatures, it is impossible to remove duplicated time signatures. At the beginning of the score, you won't be able to add either 2/4 or 6/8 at all.
[Suite № 3, Tchaikovsky (favorite excerpt).zip](https://github.com/user-attachments/files/17296572/Suite.3.Tchaikovsky.favorite.excerpt.zip)

[^1]: Only from the 142nd bar (but this is quite enough to reproduce the problem).

### What is the latest version of MuseScore Studio where this issue is present?

 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

I believe that the successful notation of the 2nd movement [Élégie] of Tchaikovsky's 3rd Suite (opus 55) in MuseScore Studio (without workarounds) would mean a solution to this issue.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-10-08 17:05
Duplicate of https://github.com/musescore/MuseScore/issues/23411

**Closed by oktophonie** 2024-10-08 17:05 UTC
Labels: UX/interaction

**Comment by Dima-S-Jr** [comment] 2024-10-08 17:08
Oh, I didn't pay attention to that.
But in any case, it is also worth paying attention to and testing along with what is in #23411.

**Comment by Dima-S-Jr** [comment] 2024-10-09 16:23
I also ask you to pay attention that for some reason I don't understand, the tremolo signs are incorrectly positioned in some bars: 
![Снимок экрана (645)](https://github.com/user-attachments/assets/d9f038c7-81ce-4f8a-b159-8744a2b252de)
