### ISSUE TITLE
[MU4 Issue] Playback popup in Properties > General has incorrect vertical spacing

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11501] opened 2022-05-02 12:15 UTC
**Describe the bug**
Horizontal spacing lines are not showing in the Playback popup (Properties > General). In addition (or as a result), the vertical padding between sections is too small.

<img width="306" alt="Screenshot 2022-05-02 at 10 13 09 pm" src="https://user-images.githubusercontent.com/86290556/166231730-e4dff0ab-8e51-49b1-9319-2c78a66e2abb.png">

**Expected behavior**
Horizontal spacing lines should be implemented, and padding should be as specified in the design spec: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=169%3A246

<img width="302" alt="Screenshot 2022-05-02 at 10 13 22 pm" src="https://user-images.githubusercontent.com/86290556/166231754-cc1bad1c-5325-4ab8-a99e-445c3210e338.png">

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by quinnouyang** [comment] 2022-05-02 15:36
@bkunda I don't have access to the Figma, could you specify the padding specs? Also, I presume we should do the same for the Dynamics popup too?
<img width="277" alt="image" src="https://user-images.githubusercontent.com/90884224/166262710-db7a7dfe-e366-4edf-9b65-4d96034f6fa9.png">

**Comment by bkunda** [comment] 2022-05-03 11:17
@quinnouyang yes you're right, this would also apply to the "Dynamics" panel.

I think these are the main specifications you need to know:

<img width="703" alt="Screenshot 2022-05-03 at 9 14 02 pm" src="https://user-images.githubusercontent.com/86290556/166443634-ae36fb88-56b4-4296-b306-9c3d56623a5f.png">

The horizontal spacer lines already exist elsewhere in the UI. Let me know if you require any further measurements/info and I'd be very happy to oblige!

**Comment by quinnouyang** [comment] 2022-05-04 02:03
@bkunda 
Just adding the lines and changing the column `spacing` from `4` to `12` produces this:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/90884224/166613451-9e17ca2a-0794-410e-a497-cfea41805d3b.png"> 

**Issue (?):** The space between the title of each dropdown and its first element (if it's text) looks larger than in your design. I notice the same issue in practically every other similar dropdown, e.g. between "Arpeggio" and "Spread delay", and between "Text" and "Font" in the general Properties panel:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/90884224/166613582-fede6ac3-0dcd-4006-9f3e-11e06c1f1225.png">

I've toyed around a bit with spacing and margins with little luck, not sure how to head from here, assuming we want to address this.

**Comment by bkunda** [comment] 2022-05-04 07:31
Thanks for your work @quinnouyang!

Yes we do need to get this right. @cbjeukendrup can you please advise @quinnouyang as to the correct spacing between dropdown header and subheadings as shown in the above images? I have provided what I can see in Figma, but I suspect my points of reference don't match up to what is required in the code. I'm sure there are examples of this elsewhere in the code that can be found to validate the correct spacing.

Thanks!

**Comment by cbjeukendrup** [comment] 2022-05-06 23:28
@quinnouyang So the problem is that the header takes more space than it needs, and therefore it looks like there is too much spacing. 
To fix this, I would propose to do the following in ExpandableBlankSection.qml (which is the file for the header):
- in `expandSectionRow`, add `height: titleLabel.implicitHeight`
- in `expandButton`, add `anchors.verticalCenter: parent.verticalCenter`

This will make sure that the height of the header is calculated based on the height of the text, and then centers the icon vertically according to that height. 

If that does not work, then the problem may be in those sub-headers (like "Font" in the last image); I suspect that the '...' button is taking some vertical space.

**Comment by quinnouyang** [comment] 2022-05-07 21:06
@cbjeukendrup The icons take up that vertical space rather than (just) the text, so your fix doesn't seem to work.
@bkunda The Figma templates don't have these icons and we don't notice the true dimensions of these buttons, so it's easy to focus on the gap. On a broader note, I'm doubtful of the validity of the design goal: closing the gap seems nice, but I'm guessing it'll make some buttons touch/overlap awkwardly with the bottom of the above/parent element. Notice the space that the buttons take from their hover highlighting:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/90884224/167271577-d28a8ed6-20a9-4054-88e6-1fdeeee9d870.png">
<img width="151" alt="image" src="https://user-images.githubusercontent.com/90884224/167271596-d1926fdc-bf1b-4611-8d60-e754e940d958.png">

**Comment by cbjeukendrup** [comment] 2022-05-09 22:37
@quinnouyang What I meant was that we could force the space added by the icons to be ignored, so that only the required space for the text counts. 

But it seems that the problem is not in the header as I guessed initially, but in the contents. So I have created #11583 to make the button in the content smaller, which should help. (We had already agreed long ago that the button should be 20x20, not 30x30 as it was currently.)

A debugging trick that sometimes works, is putting a `Rectangle` QML element inside some other element, give it a shiny color like `"yellow"`, and add `anchors.fill: parent`. This way, you will see the bounding box of the element containing the rectangle, which will help you understand where the spacing comes from.

**Comment by quinnouyang** [comment] 2022-05-20 23:11
@bkunda Tweaking some spacing with the button shrink from #11583 gets us this:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/90884224/169623163-9efee53a-43fb-4ddf-8515-8d0b354e9205.png">
Looks a lot better IMO

**Closed** 2022-06-04 16:40 UTC
Labels: P2, community
