### ISSUE TITLE
MuseScore crashes when searching for "text" in the palettes search bar

### ISSUE THREAD

**Issue by NotSoCommonSense** [musescore/MuseScore#18428] opened 2023-07-06 02:26 UTC
### Issue type

Crash or freeze

### Bug description

This bug occurs when one does a palette search. For me, because I use staff text a lot, it happens often when I search for "text" in the search bar. This bug also usually only occurs shortly after opening a MuseScore project, however it can happen some time into a session.

### Steps to reproduce

1. Open a project
2. Open the palette search bar
3. Search for 'text'

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 10

### Additional context

[MuseScore_230705_212234.log](https://github.com/musescore/MuseScore/files/11963529/MuseScore_230705_212234.log)
Ryzen 5 5600X
RX 6700XT
Windows 10
16GB DDR4 RAM
M.2 SSD

**Comment by Jojo-Schmitz** [comment] 2023-07-06 07:42
It certainly is a regression, as Mu3 doesn't crash on this.
But it doesn't crash for me in 4.0.2 either, MuseScore 4.ß.2, Windows 11
Oops, yes it does, not reliably though...
Can you check whether the latest 4.1.0 nighly build still crashes for you?

**Comment by rgreen5** [comment] 2023-07-06 09:02
A related issue perhaps: #12753?

**Comment by DmitryArefiev** [comment] 2023-07-06 14:50
**Can reproduce** on my side (Windows10, **4.1** nightly build/**4.0.2** release build), mostly when **typing quickly right after opening a score**

https://github.com/musescore/MuseScore/assets/90187801/0eb3e549-d066-45d0-81c3-b3def694a5e4

**Comment by cbjeukendrup** [comment] 2023-07-06 16:56
Is this not just the same problem as #16849?

**Comment by NotSoCommonSense** [comment] 2023-07-06 22:20
> It certainly is a regression, as Mu3 doesn't crash on this. But it doesn't crash for me in 4.0.2 either, MuseScore 4.ß.2, Windows 11 Oops, yes it does, not reliably though... Can you check whether the latest 4.1.0 nighly build still crashes for you?

My bad, I wasn't quite sure what regression meant.

**Comment by NotSoCommonSense** [comment] 2023-07-06 22:21
> **Can reproduce** on my side (Windows10, **4.1** nightly build/**4.0.2** release build), mostly when **typing quickly right after opening a score**
> 
>  bandicam.2023-07-06.17-47-30-237.mp4

Yes, exactly this is happening. I tend to type pretty fast which is why it's been crashing on me.

**Comment by Eism** [comment] 2023-07-12 12:53
@NotSoCommonSense 
Please check this build https://github.com/musescore/MuseScore/suites/14224115091/artifacts/798402440

Maybe fixed in https://github.com/musescore/MuseScore/pull/17864

**Comment by DmitryArefiev** [comment] 2023-07-13 11:55
Tried this in **latest 4.2 master** (which contains #17864) on Win10 and LinuxUbuntu22.04 - **doesn't crash** anymore

@NotSoCommonSense Please reopen if you will be able to reproduce this crash again

**Closed** 2023-07-13 11:55 UTC
Labels: P1, crash, regression_ms3

**Comment by cbjeukendrup** [comment] 2023-07-13 13:18
> How is this "Done" for/in the 4.1.1 project?

Because GitHub does that automatically when you close an issue. We do need to be careful about that...
