### ISSUE TITLE
[MU4 Task] Design Consideration: Instrument Settings not reachable through the Instruments tab

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14331] opened 2022-11-05 13:40 UTC
The only way to reach the Stave/part properties of an instrument right now is by clicking on the stave or instrument name in front of it. Being able to get there through the instruments tab would be welcome addition.

**Comment by Tantacrul** [comment] 2022-11-21 15:57
Yes, we want to make Stave/Part properties much more easy to access and use - and we're very much planning on incorporating much of its functionality into the Instruments panel. Thanks!

**Comment by cbjeukendrup** [comment] 2023-03-08 20:30
Duplicate of #13328

**Closed by cbjeukendrup** 2023-03-08 20:30 UTC
Labels: P2, feature request
