### ISSUE TITLE
Allow "Move selected note to staff above/below" shortcut to be used on a range selection

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25319] opened 2024-10-26 10:42 UTC
### Your idea

![1](https://github.com/user-attachments/assets/2ddf732f-af1d-41d0-8bca-4401ba3a5589)
Improve the shortcut to allow this kind of engraving.

### Problem to be solved

Atm it's not possible (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367).

https://github.com/user-attachments/assets/949eb529-625e-443e-a965-0c434638e76e

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-10-26 11:59
Duplicate of https://github.com/musescore/MuseScore/issues/15544

**Closed by oktophonie** 2024-10-26 11:59 UTC
Labels: feature request
