### ISSUE TITLE
[MU4 Issue] Note input can start at location not on screen

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11494] opened 2022-05-02 03:16 UTC
EDITED BY @Tantacrul 

We want to retain the 'no jumping' rule from MuseScore 3 when a user resumes Note Input mode. There are two points (which I've demonstrated in the video below):

1. When a user triggers note input mode, if the previous position where the user last inputted notes is out of view, **do not jump back to to that view** (This is by far the more important point. **_When this is achieved, we may close the issue_**)

2. If the previous position is not in view, then move the note input cursor to the **top-left visible stave**. If this is too hard / not achievable, we should discuss whether a delay until 4.x is the right move.

https://user-images.githubusercontent.com/21022311/174475265-41bd0179-6bb1-42da-8aa5-4e082ce015c0.mov

**Comment by Tantacrul** [comment] 2022-05-02 09:30
To summarise, the rules Marc is suggesting are:

1. When triggering Note Input mode, jump to the measure where the user was last inputting notes (this is what we do now) - **but** only if that measure is visible in the current view
2. If it is not visible, start note input mode in the top-left most visible measure in the current view

@bkunda - we should start user testing score creation on existing MS3 users in the next week to see whether these rules need to be re-added with urgency. I'll set that up. Remind me! :D

**Comment by Tantacrul** [comment] 2022-05-02 09:30
Added P1. Design need to validate.

**Comment by MarcSabatella** [comment] 2022-05-02 14:15
FWIW, while I do feel strongly we should figure this out before release, to me it's also not that high priority to nail perfectly right away - there's no harm in continuing to refine it over time.  Whereas anything involving UI changes or that affects how we document an action would seem more important to solidify sooner rather than later.

**Comment by wizofaus** [comment] 2022-05-02 22:16
I don't know what the exact behaviour in v2 or earlier was that generated so many user complaints, but having the score "jump" back to where you last entering data seems to be exactly right to me, as I noted, what nearly all other apps - including your web browser - do.
In fact the behaviour now is basically the same regardless of whether you exit note input mode (you can use the mouse-wheel to scroll elsewhere in the score while still in note input mode), or then subsequently deselect the last entered note. The only difference is that after exiting note input mode, whatever note you add next replaces the last added note.

**Comment by MarcSabatella** [comment] 2022-05-03 12:59
(agreed regarding moving the discussion)

**Comment by wizofaus** [comment] 2022-06-19 06:55
This is P1 but can I confirm we're still waiting on a design decision from @bkunda and/or @Tantacrul ?

**Comment by Tantacrul** [comment] 2022-06-19 09:44
@wizofaus - thanks for the pointer. I'm going to edit the summary of the bug and add a video for clarity. This close to a release, I think it is dangerous to experiment and the current MS3 behaviour is clearly better than the MS4 behaviour, so I think we should stick with that for now.

**Comment by wizofaus** [comment] 2022-06-19 10:32
There's no trivial way to implement the v3 behaviour, and it's basically unpredictable. The code in v3 can't be used as is.

**Comment by MarcSabatella** [comment] 2022-06-19 18:58
I'm not sure in what cases MU3 doesn't start with the top left measure, but that's certainly what the algorithm in MU3 is *supposed* to do, and does in all of my own tests.  Be sure you are actually only testing cases where there is a selection or where the last note input position is not currently in view.  If the last note input position *is* in view, then yes, that location gets chosen, and that's really the only reason I can think why you'd see a measure being chosen that is fourth from top or a note that is not beginning of measure.  Only if there is no selection and the last note input position is not in view should this algorithm be kicking in.

In any case, regardless of whether MU3 gets this right all the time or not, I wouldn't recommend emulating any particular oddities of MU3 here - just aim for the top left like I *tried* to in MU3.  If your aim is better than mine was, great!  I would personally recommend aiming for top left "fully visible" to avoid the need for any jumping at all, but that's not always feasible of course if you're zoomed in and nothing is fully visible.

If there is no visible notation at all, it's hard to imagine a user entering note input at that point, but if they did, clearly a jump will be required.  I'd recommend the *next* measure, top staff, but if that's hard to determine, I'd probably just fall back to the last note input position if available.

**Comment by wizofaus** [comment] 2022-06-19 20:10
In the testing I was doing with a large orchestral score, I would say at best 50% of the time did it start note entry at the top-left-most visible measure.  And the code that tries to determine this is insanely complicated.
I'd also say I hope there is a command to return to where you were last entering notes even if you've scrolled it out of view as I am still firmly in the camp of wanting MuseScore to behave like text editing software in this regard.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by wizofaus** [comment] 2022-06-19 20:13
(Btw I suspect some of the unexpected behavior was because I had "accidentally" selected something while panning the score around. But it's actually very difficult to avoid doing this on a crowded score)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MarcSabatella** [comment] 2022-06-19 23:34
If you have no selection, Shift+L re-establishes a selection at the location of the most recent selection.  In some cases, that might not be the last note input position - like if you did some other editing operation after the last note input operation.  I have nothing against another command to specifically re-establish last note input position.

I'm quite confident you are correct that you had selected something and that's why note input started there.  It's of course completely correct to start note input at the selection.

**Comment by wizofaus** [comment] 2022-06-20 03:27
Shift+L isn't working for me in v4. Works in v3. Will log.

**Comment by DmitryArefiev** [comment] 2022-08-13 18:44
Fixed in #12824

**Closed** 2022-08-15 08:16 UTC
Labels: P1
