### ISSUE TITLE
[MU4 Issue] Some notes play louder as should

### ISSUE THREAD

**Issue by Grillzombie** [musescore/MuseScore#12830] opened 2022-08-12 15:51 UTC
**Describe the bug**
Score from 3.6.2. On playback in MU4 nightly, some notes are played louder as other notes, maybe related to notes with staccato dots.

**To Reproduce**
1. Open attached file 
[Danse_a_deux.mscz_FILES.zip](https://github.com/musescore/MuseScore/files/9323981/Danse_a_deux.mscz_FILES.zip)

2. Click play

**Expected behavior**
Notes should have the same loudness, even there is a staccato dot on it.

**Platform information**
 OS: Linux Mint 20.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2844416344, revision: github-musescore-musescore-ae252cd

**Comment by Tantacrul** [comment] 2022-08-31 20:54
Yeah, it sounds quite noticeable on the 4th beat in this example:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/21022311/187780150-3d87288a-6a02-4dcf-a3df-568afc89955b.png">

The staccato should be of consistent volume.

Can't reproduce on new scores, however.

**Comment by abariska** [comment] 2022-09-12 19:47
Duplicate of https://github.com/musescore/MuseScore/issues/12790

**Closed** 2022-09-12 20:27 UTC
Labels: P1
