### ISSUE TITLE
Muse Sampler didn't update at all on my end! (Mac)

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#17991] opened 2023-06-15 07:38 UTC
### Issue type

Other type of issue

### Bug description

So of course I did install the beta version of Muse Hub, and the latest MuseScore 4 Nightly build.

However, when I tested back a score I'm currently working on, there's STILL reverb added in the Muse Sounds. I did check the Muse Sampler in the MuseScore app, though it DIDN'T update to 0.4.2 or later, and just stuck to v0.3.2!!!

What's the cause of this bug to happen on my end, and how can I update the sampler?!!!!!

### Steps to reproduce

1. Installed the beta version of Muse Hub
2. Installed MuseScore Nightly
3. Checked the Muse Sampler in the MuseScore app

### Screenshots/Screen recordings

![Screen Shot 2023-06-15 at 3 34 59 AM](https://github.com/musescore/MuseScore/assets/32210900/bbadfec6-9b67-4663-bd74-e314c88c1de2)
![Screen Shot 2023-06-15 at 3 35 42 AM](https://github.com/musescore/MuseScore/assets/32210900/fbd1d663-70f9-402d-9330-a6daaedf3924)

### MuseScore Version

4.1 latest nightly

### Regression

I don't know

### Operating system

Mac OS Monterey, v12.6.6

**Comment by cbjeukendrup** [comment] 2023-06-15 10:38
The reason is that the Muse Hub team have not yet updated the macOS beta link on the website...

**Comment by bkunda** [comment] 2023-06-16 13:18
We have isolated the cause of this problem, and I have it confirmed now that it has been fixed by the MuseHub team. 
Will re-open if the problem persists.

**Closed by bkunda** 2023-06-16 13:18 UTC
Labels: P1, needs review
