### ISSUE TITLE
Deleting bar 1 loses exported key signature

### ISSUE THREAD

**Issue by brianavid** [musescore/MuseScore#20043] opened 2023-11-16 08:44 UTC
### Issue type

File corruption

### Bug description

Deleting the first bar with a key signature **appears to keep that key signature**. But **it is lost on saving**, export to MusicXML and on upload to MuseScore.com. I discovered this when publishing to MuseScore.com.

### Steps to reproduce

- Create a simple score with a non-empty key signature including one or more sharps or flats
- Add some simple notes
- Delete bar 1 - the key signature remains in the "new" bar 1
- Export to MusicXML or publish to MuseScore.com - the key signature is lost
- Alternatively save to mscz and reload - - again the key signature is lost

### Screenshots/Screen recordings

Screen shot of MS4:
![Screenshot 2023-11-16 083814](https://github.com/musescore/MuseScore/assets/5159216/e8647dee-81d7-403e-8b6f-25ab9db43729)

Saved MSCZ file:
[Losing Key Sig.zip](https://github.com/musescore/MuseScore/files/13374310/Losing.Key.Sig.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-11-16 09:03
Duplicate of https://github.com/musescore/MuseScore/issues/19063 (now fixed in master, happily)

**Closed by oktophonie** 2023-11-16 09:03 UTC
Labels: corruption

**Comment by brianavid** [comment] 2023-11-16 09:38
Thanks - Sorry I missed the duplicate. I did search, but obviously not thoroughly enough :-)
