### ISSUE TITLE
[MU4 Issue] Some bugs and weird behaviours

### ISSUE THREAD

**Issue by goznalo-git** [musescore/MuseScore#15878] opened 2023-01-14 17:41 UTC
Hi there, 

I have been trying Musescore 4 for a couple of week sand I have a list of small bugs or weird behaviors (not sure they are intended) noted down. Please let me know if I should split them into different issues, I assume it's okay placing them here.

1.  Even though I changed in the settings the project folder location, every time I open the app it creates the folder under `$HOME/Documents/Musescore4`. Nevertheless, the scores are saved in the correct location, it is just that the Documents/Musescore4 keeps spawning.
2. If continuous view is toggled on, then when exporting it to pdf it is exported as a continuous pdf. I think this is not intended, it should be separated: one probably wants to "view" but not "export" continuously.
3. Sometimes clicking on the "tied note" button crashes the app. I can't provide steps for this, as it happened to me a handful of times for unknown reasons (and even having other tied notes in the same score functioning properly).
4. UI changes made with the "Customize toolbar" dialog do not remain after restarting the app.
5. I tried to use the "Explode" tool to move a voice in a staff to the staff below. However, the upper staff had a linked tablature below, and it didn't allow it. I had to remove the tablature linked staff, then explode, then add the linked staff back. This does not seem like correct behaviour. 

Anyway, thanks for the work you're putting in!

**Platform information**
 - OS: Linux (Manjaro 5.15) with desktop environment GNOME 43.1

**Additional context**
- I am using the AppImage version.

**Comment by cbjeukendrup** [comment] 2023-01-14 18:22
Hi! Issues mentioning several problems like this are a bit difficult to work with for us, since they usually need to be fixed one at a time. For some of the problems you mention, there is already a dedicated issue:

1. came up in #15567
2. came up in #14929
3. maybe this is related to one of there: #15421, https://github.com/musescore/MuseScore/issues/15345, #15490
Or the file you are using might be corrupted. In any case it would be great if you could upload that file for us to investigate (you need to wrap it in a ZIP file so that GitHub allows you to upload it)
4. This has the same underlying problem as https://github.com/musescore/MuseScore/issues/13837; I will log a task about this root problem, and mention that it affects toolbars too.

So I will close this issue, and it would be great if you could:
- upload the score for the tie problem here
- create a new issue specifically for the "explode" problem.

Thanks!

**Closed by cbjeukendrup** 2023-01-14 18:22 UTC

**Comment by goznalo-git** [comment] 2023-01-15 00:43
Here is one of the files that crashes. Specifically, if one adds a C note (3rd fret on the 5th string) on the 40th measure, and tries to make a tied note from that same note on the 39th measure, it crashes every time, at least for me.
[acrossthestars-starwars.zip](https://github.com/musescore/MuseScore/files/10419169/acrossthestars-starwars.zip)

**Comment by cbjeukendrup** [comment] 2023-01-15 11:09
Thanks for this! I can indeed reproduce the crash. It looks like this file is somehow a little bit corrupted, even though there is no warning when you open it. I'll investigate this.
