### ISSUE TITLE
[MU4 Issue] Reset to default command deletes some default shortcuts in Shortcuts preferences

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10594] opened 2022-02-17 10:33 UTC
TO DO..

**Describe the bug**
A short and clear description of what the bug is.

https://user-images.githubusercontent.com/90187801/154457858-df3d6121-92a6-41a1-bdef-f7634365e474.mp4

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by duanjr** [comment] 2022-02-20 10:35
looks like we just didn't set default shortcuts for these commands
similar with file open, save, etc.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/71218187/154838528-441cba94-f160-44b8-a56d-3fe0f626f92f.png">

**Comment by duanjr** [comment] 2022-02-20 10:36
Do I need add default shortcut for them?

**Comment by HemantAntony** [comment] 2022-02-20 10:39
If your fix works, it should be ok. But, Dmitry has assigned the issue to himself, so I think the issue is in progress (Also the To Do on the top part in the issue desc.)

**Comment by duanjr** [comment] 2022-02-20 10:46
> 

Sorry, I'm new to open source, so I may be misunderstanding what "assign" means, I thought it just means that Dmitry is primarily responsible for the problem, not that he will definitely do the task. Now I understand it :)

**Comment by HemantAntony** [comment] 2022-02-20 10:53
Oh Dmitry is not a developer. He tests MU4 (Quality assurance). Usually when PRs are assigned to him, it means that the said PR is to be tested by him which is why I thought this issue is not complete yet (Probably more details will be provided). But, its not assigned to a developer yet

**Comment by duanjr** [comment] 2022-02-20 10:55
> 

Thanks for your explanation

**Closed** 2022-03-09 08:18 UTC
Labels: P2
