### ISSUE TITLE
[MU4 Issue] Musescore crashes when I try to change instrument in guitar tab to standard notation 

### ISSUE THREAD

**Issue by stand13** [musescore/MuseScore#15756] opened 2023-01-08 14:12 UTC
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by MarcSabatella** [comment] 2023-01-08 14:14
In order for someone to be able to investigate, please edit your description to provide the requested details

**Comment by cbjeukendrup** [comment] 2023-01-08 15:34
Duplicate of #15757

**Closed by cbjeukendrup** 2023-01-08 15:34 UTC
