### ISSUE TITLE
[MU4 Issue] Format > Style and other commands not working when in edit mode

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12218] opened 2022-06-29 22:30 UTC
**Describe the bug**
If an element is selected in "edit mode", Format > Style and other commands are either disabled or enabled but not working.

**To reproduce**
1. Open score
2. Select an element and enter "edit mode" (note that for some markings like crescendos, this happens immediately when you select them)
3. Try to use Format > Style

Nothing happens; in the console, a message like `no one can handle the action:` is printed.

**Expected behavior**
These commands should always be available and working when a score is opened. 

**Platform information**
 - OS: At least macOS

**Additional context**
See also #12250, which is closed as a duplicate, but shows another instance of this problem.

**Comment by wizofaus** [comment] 2022-06-29 23:32
Can't reproduce on Windows, hard to see what might trigger that?

**Comment by cbjeukendrup** [comment] 2022-06-30 00:19
It apparently only happens when the selected element is in "edit mode". With hairpins and text lines, those are in edit mode automatically if you select them, so therefore I though it happens always when selecting an element.

**Comment by wizofaus** [comment] 2022-06-30 00:24
In that case it's as per v3, except that in v3 lines aren't in edit mode "by default", even though selecting edit mode appears to do nothing (other than disable various toolbar/menu commands).
This was definitely due to the way I implemented it and I'm aware it's not ideal but the whole UX around edit mode is problematic.

**Comment by Tantacrul** [comment] 2022-07-08 11:37
There is also a similar annoying issue that when you select a text element, it also disables Format/Style... but **worse** prevents you entering Note Input mode too.

**Comment by wizofaus** [comment] 2022-07-08 13:17
Are you sure it's different between v4 and v3?
There's no particular reason Format/Style needs to be disabled in edit mode,  but we need a clear indication of what behavior is wanted here. It was always my preference to simply get rid of edit mode (but not for v4.0 at this stage).

**Comment by wizofaus** [comment] 2022-07-10 20:18
@Tantacrul can you confirm you're happy to simply allow all these commands even when in edit mode?  I don't know what good reason there is for the current behaviour (inherited from v3), though there's possibly one or two commands where it might be necessary to keep them disabled.

**Comment by Tantacrul** [comment] 2022-07-12 15:30
@wizofaus - yes, for sure. It seems to be an oversight as far as I'm concerned. If it turns out there's some **really good, hidden reason**, we can always revert it.

**Comment by wizofaus** [comment] 2022-07-12 19:35
Not an oversight,  it was coded that way deliberately to mimic v3's behavior.

**Comment by wizofaus** [comment] 2022-07-12 20:52
So the question is how to determine which commands/actions should still remain disabled in edit mode, there's a lot:
* all the various "note input" modes (including activating note input mode at all)
* changing note duration (0-9)
* changing note pitch using A-G
* forming a chord by adding a note (ctrl+ A-G)
* navigating to the next/previous element/track/measure/system etc. (lots of variations of this)
* adding various items to the score (melismas, accidentals etc.)
* changing to a tuplet
* toggling visibility 
* keyboard "nudges" of elements (changing pitch etc.)
* double/half duration, adding dots etc.
* flip direction
etc.
   
Given edit mode is primarily about making micro-position/shape adjustments using the keyboard, I think allow maybe everything except commands that change the pitch/duration/position of the currently selected note?

**Comment by DmitryArefiev** [comment] 2022-07-14 12:15
Fixed in #12368

**Closed** 2022-07-14 12:15 UTC
Labels: P1
