### ISSUE TITLE
When using "Add palette" there is no UI element (e.g. OK) for closing dialog

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11881] opened 2022-06-03 15:26 UTC
**Describe the issue**

When you open "Add palette", there seems to be no "cue" to the user as to how to close the dialog after use. Using [Esc] or clicking on a blank area of the program window does the trick, but should there also be an "OK" button (or similar).

**To Reproduce**

1. Creat a new score, say.
2. Click on "Add palette" in the Palettes sidebar.
3. Click any + button.

RESULT: The dialog stays open. The user has to click [Esc] or click on a blank area of the program to close the dialog.

**Expected behavior**

Ditto, but with an additional button, e.g. "OK", to close the dialog.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2432394363, revision: github-musescore-musescore-1ff2049

**Comment by mxmou** [comment] 2022-06-03 15:46
Clicking "Add Palettes" again closes the popup which is the usual behavior for dropdowns, so this might not be a bug.

**Comment by cbjeukendrup** [comment] 2022-06-03 22:11
Indeed, this thing is a popup, not a dialog, so it has no close button but closes when you click outside it. 

I think @Tantacrul has purposefully designed it so that the popup won't close after clicking a `+` button, because it's quite annoying if you need to reopen the popup again and again if you want to add multiple palettes in one go. 

(However, my personal experience is that it is more likely that I want to add only one palette at a time, namely just the one I need, rather than that I go to the popup to see what it has in store and then add some palettes in one go. So we might revise this design choice.)

Closing for now as 'by design', but @Tantacrul if you indeed want to revise this choice, feel free to reopen.

**Closed by cbjeukendrup** 2022-06-03 22:11 UTC

**Comment by Tantacrul** [comment] 2022-06-04 07:58
I do actually have a light redesign of this popup in mind. Should be an easy fix for 4.X
