### ISSUE TITLE
[MU4 Issue] Four measure repeat symbol when played back only repeats last measure of the previous four measure section

### ISSUE THREAD

**Issue by toneflake** [musescore/MuseScore#15511] opened 2022-12-22 13:38 UTC
**Describe the bug**
Four bar repeat symbol when played back only repeats last bar of the previous four bar section. Also does so by playing the last bar in the second bar of the grouped 4-bar repeat section.

**To Reproduce**
1. Insert notes and musical information in 4 freely selected measures.
2. Then insert a "4 measure repeat" symbol in the next measure after the previously inserted 4 measure section.
3. Then click on "Play"

**Expected behavior**
I would expect the 4 measure repeat symbol to play back the previously inserted 4 bars in its entirety. 

**Screenshots**
Listen to the error here! Pay attention to how the repeat should begin after the 4th measure is done playing but it only begins after 1 measure delay and how it is also limited to just 1 measure (the last measure of the selected 4) instead of the entire 4 bar section. 
https://drive.google.com/file/d/1lRRp9ERw1iKoajKqf5eXUxXbbDKmFnD5/view?usp=share_link
![image](https://user-images.githubusercontent.com/121237324/209140906-ddea449b-fb0e-4b67-9be7-1b47c6468b55.png)

**Platform information**
 - OS: Windows 10 Pro

**Additional context**

**Comment by Jojo-Schmitz** [comment] 2022-12-22 13:52
Duplicate of #10922

**Comment by cbjeukendrup** [comment] 2022-12-24 00:49
Indeed; closing as a duplicate.

**Closed by cbjeukendrup** 2022-12-24 00:49 UTC
