### ISSUE TITLE
[MU4 Issue] MuseScore4 crashes when pressing 0 in staccato mode

### ISSUE THREAD

**Issue by simon14264** [musescore/MuseScore#14322] opened 2022-11-05 11:14 UTC
**Describe the bug**
MuseScore4 crashes when pressing 0 in staccato mode.

**To Reproduce**
1. Press N
2. Press shift+s
3. Press 0

**Expected behavior**
Crash

**Platform information**
 - OS: Windows

**Additional context**
Was on Viola and eigth notes.

**Comment by cbjeukendrup** [comment] 2022-11-05 13:54
I think this is a duplicate of #13740, which has been fixed meanwhile. Could you please try again in the latest beta version (in Muse Hub, check for updates) or the latest Nightly build (https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds)?

**Comment by RomanPudashkin** [comment] 2022-11-17 09:29
Please reopen the issue if you can still reproduce the crash

**Closed** 2022-11-17 09:28 UTC
