### ISSUE TITLE
Note visibility can have ill effects on ledger lines and stems

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#17460] opened 2023-05-04 06:05 UTC
### Issue type

Engraving bug

### Bug description

Show>Closed Eye can hide needed ledgers and also result in excessive stem length.

See attached score.

### Steps to reproduce

See attached score

### MuseScore Version

MS 4.0.2

### Regression

No

### Operating system

MacOS 13.3.1

### Additional context

[Hide invisible - has ill effect on ledger lines and stem length.mscz.zip](https://github.com/musescore/MuseScore/files/11394118/Hide.invisible.-.has.ill.effect.on.ledger.lines.and.stem.length.mscz.zip)

**Comment by oktophonie** [comment] 2023-05-04 06:24
Duplicate of https://github.com/musescore/MuseScore/issues/14994

**Closed by oktophonie** 2023-05-04 06:24 UTC
Labels: feature request, engraving
