### ISSUE TITLE
[MU4 Issue] 1/2 note tempo as 1/4 note tempo after creating a new score

### ISSUE THREAD

**Issue by nakhwanmaul** [musescore/MuseScore#19343] opened 2023-09-09 12:06 UTC
### Issue type

General playback bug

### Bug description

1/2 note tempo should be doubling the 1/4 note tempo but in playback still a normal 1/4 note tempo

### Steps to reproduce

1. Create a new score
2. Choose instrument(s) or from template
3. Set time signature to 2/2 or cut time (optional but better)
4. Set tempo on 1/4 note, and then change it to 1/2 note

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/130434857/8f852425-e2de-43f9-ad51-660e830e47da

### MuseScore Version

4.1.1.232071203

### Regression

I don't know

### Operating system

Windows 10 64-bit

### Additional context

Or it's just a Unicode character bug, so the tempo doesn't care about that.

(If this is duplicated, you can leave a comment for an actual issue. Pardon me for bad English)

**Comment by cbjeukendrup** [comment] 2023-09-09 12:34
This is indeed a duplicate of #14678. I've updated the title of that issue, hoping to make it better findable :)

**Closed by cbjeukendrup** 2023-09-09 12:34 UTC
Labels: playback

**Comment by nakhwanmaul** [comment] 2023-09-10 03:19
> This is indeed a duplicate of #14678. I've updated the title of that issue, hoping to make it better findable :)

Thank you! :)
