### ISSUE TITLE
[MU4 Issue] Systematic crash when opening score

### ISSUE THREAD

**Issue by Baol77** [musescore/MuseScore#14774] opened 2022-11-26 11:29 UTC
**Describe the bug**
Systematic crash when opening the attached score.

**Attached files**
Score: [Canzoncina_di_Natale_2022.zip](https://github.com/musescore/MuseScore/files/10096096/Canzoncina_di_Natale_2022.zip)
Logs file: [MuseScore_221126_122402.log](https://github.com/musescore/MuseScore/files/10096109/MuseScore_221126_122402.log)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155

**Comment by Tantacrul** [comment] 2022-11-28 17:09
I'm able to open it on MacOS.

Was this created in an earlier version of MS4?

Could you download this latest nightly build (which includes a lot of fixes) and let me know if it solves your issues? https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-x86_64.7z

**Comment by Baol77** [comment] 2022-11-29 11:05
The file was created straight in MS4.

It crashes the same even on the nightly build you've provided.

Here is the log file:
[MuseScore_221129_120204.log](https://github.com/musescore/MuseScore/files/10112387/MuseScore_221129_120204.log)

**Comment by Tantacrul** [comment] 2022-11-29 11:23
> The file was created straight in MS4.

- Do you mean you created it in the most recent version and then tried to export audio?
- Or was the file created in an older version of MS4 (like the beta)

The reason we're asking is that there have been changes to the file format in the last two weeks. We're trying to isolate the issue.

**Comment by Baol77** [comment] 2022-11-29 11:29
The version reported in the ticket was exactly the one where the file was created:

-  MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155

I suggest to open it with on Windows as well.

**Comment by Tantacrul** [comment] 2022-11-29 22:37
> I'm able to open it on MacOS.
> 
> Was this created in an earlier version of MS4?
> 
> Could you download this latest nightly build (which includes a lot of fixes) and let me know if it solves your issues? https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-x86_64.7z

I'll try a third time: can you please install this version and create a new score in it and then tell us whether you are still having this problem? Only follow these instructions and please do not invent new ones yourself. If you can't do this, I'm going to be forced to close the issue.

**Comment by Tantacrul** [comment] 2022-11-29 23:11
There's no need to log those other 2 issues. They'll be fixed by the end of the week. All our mapping problems will be. Thanks anyway.

**Comment by opExe** [comment] 2023-03-03 11:08
Reproduced on Win11 after changing the playback profile to Muse Sounds.

**Comment by Tantacrul** [comment] 2023-03-03 12:50
@opExe - thanks!

What build did you test on? Was it 4.0.1?

Could you possibly try the release candidate for 4.0.2? If the issue is still there, I'll get it bumped to a much higher priority.

- WIN - https://github.com/musescore/MuseScore/suites/11278379367/artifacts/578408840

**Comment by Tantacrul** [comment] 2023-03-03 12:51
(Note: I personally cannot reproduce this, so it might very well be specific to certain machines)

**Comment by Jojo-Schmitz** [comment] 2023-03-03 12:53
Opens just fone for me on OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230601206, revision: github-musescore-musescore-48ac167

**Comment by Tantacrul** [comment] 2023-03-03 12:55
@Jojo-Schmitz - to be sure, did you change the instrument to use Muse Sounds and play it?

The issues - as far as I understand - is that this is how we're meant to reproduce the crash.

**Comment by Jojo-Schmitz** [comment] 2023-03-03 13:11
Oops. no.

And indeed, as soon as I switch to Tubilar Bells, it crashes

**Comment by Tantacrul** [comment] 2023-03-03 13:27
Excellent! We have it. Thanks @Jojo-Schmitz and @opExe !

I'll close this and leave https://github.com/musescore/MuseScore/issues/16642 open.

**Closed by Tantacrul** 2023-03-03 13:27 UTC
Labels: needs info, crash
