### ISSUE TITLE
Tenor Saxophone Ignores Decrescendo Marking on Dotted Half Notes

### ISSUE THREAD

**Issue by btvarious** [musescore/MuseScore#18561] opened 2023-07-13 07:49 UTC
### Issue type

General playback bug

### Bug description

When writing a line using the tenor saxophone instrument, if you use a decrescendo in the last measures of the line, and the line ends in a value of at least a dotted half note, the held note at the end will sound at a louder dynamic compared to the rest of the preceding line, and will completely ignore the written dynamic marking. I haven't tried this on anything outside of the tenor sax, but I imagine it could be an issue with other instruments as well. This occurs with both Musesounds and VST, so likely is a programming issue. See attached files for an example line that exhibits this issue. This example was created in a brand new project file and nothing else was written beyond what you see in the picture. Mixer settings are at default.

### Steps to reproduce

1. Open a score and add a tenor saxophone. 
2. Compose a multi-measure line in 3/4 time that ends in a dotted half note
3. Highlight the last four bars of the measure and add a decrescendo (the hairpin markings, not the text one)
4. This is most noticeable at the mp and mf dynamics

### Screenshots/Screen recordings

![tenorsackslol](https://github.com/musescore/MuseScore/assets/139440717/60694cd2-08f3-4c95-8600-5f7f85e26532)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921402

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

Whatever build was last live before 4.1.0 did not have this issue. I don't remember the version number but I know for a fact it was not an issue then.

**Comment by btvarious** [comment] 2023-07-13 07:50
Ope, realized I submitted a screenshot instead of a video file. Regardless: that last note - too loud. Does not listen to dynamic markings. Should get the same result if you reproduce exactly

**Comment by bkunda** [comment] 2024-05-29 08:50
Cannot reproduce on macOS using 4.3.1. 
Cross-checking the above example in a DAW, the waveforms show a clear diminuendo in effect on the dotted-half note (albeit a somewhat subtle one). 

https://github.com/musescore/MuseScore/assets/86290556/7b5631c2-4ad1-418b-9450-067aa1f9e2a1

Closing for now, but happy to reopen if this can be reproduced.

**Closed by bkunda** 2024-05-29 08:50 UTC
Labels: P2, regression, playback
