### ISSUE TITLE
[MU4 Issue] Cannot Tab between blanks (Title, Composer, Subtitle, etc.) when making a new score

### ISSUE THREAD

**Issue by AlexAndPedro** [musescore/MuseScore#11174] opened 2022-04-13 05:56 UTC
**Describe the bug**
When tabbing on one blank when making a new score, the text cursor does not go to the next blank.

**To Reproduce**
1. Open up Musescore
2. Click **New Score**
3. Add a piano instrument
4. Click Next
5. Enter a Title
6. Press Tab. The cursor does not go the **Optional** blank for the Composer.

**Expected behavior**
When pressing Tab when in the Title blank, I expected the text cursor to go to the Composer.
In the Composer blank, I expected pressing Tab will send the text cursor to go to Subtitle.
Similarly, from Subtitle to Lyricist, and Lyricist to Copyright.

**Screenshots**
![image](https://user-images.githubusercontent.com/73212448/163109659-fc410105-a3f3-4521-be9b-699d1e832cc1.png)

**Platform information**
 - OS: Windows 10

**Comment by HemantAntony** [comment] 2022-04-13 11:17
Duplicate of #10919

**Closed** 2022-04-13 11:46 UTC
