### ISSUE TITLE
[MU4 Issue] (RC) Selecting two voltas will result in deletion of text and "repeat list" number, leading to score is not playable anymore

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#14968] opened 2022-12-05 19:57 UTC
**Describe the bug**
When you place two Voltas like in the video, selecting both simultaneously will delete the "repeat list" number and the text. When you play the score, the "play line" will go invisible when it reaches the volta and there is no sound anymore.

**To Reproduce**
1. Create a score like in the video.
2. Select both voltas simultaneously (Windows: STRG + left click)

**Expected behavior**
Voltas should stay normal, and nothing should change when an item is selected.
**Screenshots**

https://user-images.githubusercontent.com/55204261/205730835-bda7dcdd-ee27-40c2-8553-5520c0f45c01.mp4

**Platform information**
 - OS: Windows 11
 - Release Candidate

**Comment by Tantacrul** [comment] 2022-12-06 12:07
I have witness the text disappearing issue but not the playback issue. Putting into **Release** for assessment on how risky it is to fix this.

**Comment by Tantacrul** [comment] 2022-12-06 12:09
@oktophonie - I doubt the engraving team are the right folk to tackle this but I thought I'd get your opinion.

**Comment by jeetee** [comment] 2022-12-06 12:12
The playback stopping is caused by the repeatlist being emptied (the real bug here).

**Comment by Tantacrul** [comment] 2022-12-06 12:12
Incidentally, the reason it isn't playing back is because the 'Repeat List' field in the Properties panel is cleared when you select both Voltas.

**Comment by Tantacrul** [comment] 2022-12-06 12:12
> The playback stopping is caused by the repeatlist being emptied (the real bug here).

Snap

**Comment by oMrSmith** [comment] 2022-12-06 12:22
(This is a duplicate of #13194)

**Closed** 2022-12-07 14:50 UTC
Labels: P1
