### ISSUE TITLE
[MU4 Issue] Dynamic is not changed when dynamic marks are are applied and VST instrument used in score

### ISSUE THREAD

**Issue by hicani123** [musescore/MuseScore#11040] opened 2022-03-31 17:28 UTC
**To Reproduce**
- Open a piano score (or create)
- Connect VST (Spitfire LAB glass piano)
- Put some dynamic marks to the score
- Play the score, and play staccato notes

**Screenshots**

https://user-images.githubusercontent.com/101250347/161255169-7f75885f-a93c-471e-b3f7-6172b36430fd.mov

**Platform information**
 - OS: MacOS

**Comment by boryskuzmenko** [comment] 2022-04-01 09:53
@hicani123 Could you please provide screen capture with the VST bugs?

**Comment by boryskuzmenko** [comment] 2022-04-01 11:33
Closed as a duplicate of https://github.com/musescore/MuseScore/issues/10915

**Closed by boryskuzmenko** 2022-04-01 11:33 UTC
