### ISSUE TITLE
hitting enter should apply like clicking ok in add bars dialog.

### ISSUE THREAD

**Issue by Ash-86** [musescore/MuseScore#24645] opened 2024-09-11 18:14 UTC
### Your idea

Apply add bars by pressing enter in the "add bars" dialog.

### Problem to be solved

You currently have to click "ok" to add bars.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by MarcSabatella** [comment] 2024-09-11 18:23
Thanks for reporting, but this a duplicate of https://github.com/musescore/MuseScore/issues/12222

A workaround for keyboard use, btw, is to Tab to the OK button, then Enter works.

**Closed** 2024-09-11 18:28 UTC
Labels: feature request
