### ISSUE TITLE
[MU4 Issue] Entered notes are heard staccatissimo rather than at reasonable default duration

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12273] opened 2022-07-05 11:12 UTC
**Describe the bug**

In Note input mode, when you enter notes (from the computer keyboard) they should be audible at a reasonable default duration (as in MS3). However in MS4 they are being heard staccatissimo.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2613746296, revision: github-musescore-musescore-b70aa9b

**Comment by cbjeukendrup** [comment] 2022-07-05 11:24
Maybe interesting: for VST instruments it seems to work OK, it only happens for Fluid.

**Comment by cbjeukendrup** [comment] 2022-07-07 11:11
@vpereverzev I think this is because AbstractEventSequencer::eventsToBePlayed does not take nextMsecs into account when handling offStreamEvents.

**Comment by DmitryArefiev** [comment] 2022-08-04 14:03
Tested in latest master (after merging)

@Tantacrul  Now entered notes are not sound staccatissimo (FIXED), but there are still two differences between MU3 and MU4

1. During note input, the duration is a little bit longer in MU4
2. When clicking note with a mouse, in MU3 there are two variant of duration depending on when you release the mouse button, in MU4 the duration is always the same and equal to the duration during note input

https://user-images.githubusercontent.com/90187801/182865455-25f1fbed-70d8-4775-9317-7805fe800ca6.mp4


All two issues should be fixed (MU3 and MU4 behavior should correspond)?

**Comment by Tantacrul** [comment] 2022-08-04 14:35
If this is the only remaining disparity then I think you can make it a new issue and give it a P1 + assign it to Beta2.

**Comment by DmitryArefiev** [comment] 2022-08-11 15:05
The issue is back

**Comment by DmitryArefiev** [comment] 2022-08-18 09:03
@vpereverzev There is a related issue to note duration during input - **Bug 1** from  #12695

**Comment by lyrra** [comment] 2022-08-31 16:20
regression in commit d83d2c7e5dc84eedfc5ee0abc90c417f802f7ed6

**Comment by lyrra** [comment] 2022-08-31 20:53
Perhaps tweak this:
```
src/engraving/libmscore/mscore.cpp
void MScore::init()
{
    static bool initDone = false;
    if (initDone) {
        return;
    }

    defaultPlayDuration = 300;        // ms   
```

**Closed** 2022-09-01 22:19 UTC
Labels: P0

**Comment by DmitryArefiev** [comment] 2022-09-02 11:12
Tested in master on Win10, Mac12, LinuxMint 20.2 - **FIXED**
