### ISSUE TITLE
[MU4 Issue] Trombone and Trombones a3 Cannot Play Above C5

### ISSUE THREAD

**Issue by FL2070** [musescore/MuseScore#15980] opened 2023-01-19 20:34 UTC
**Describe the bug**
The Muse Sounds instruments "Trombone" and "Trombones a3" cannot any note above a C5.

**To Reproduce**
1. Create a new score with a trombone
2. Assign the trombone to the "Trombone" or "Trombones a3" Muse Sounds instrument.
3. Enter a C#/Db5 note for the trombone to play.
4. Observe that it cannot play the note.

**Expected behavior**
The "Trombone" and "Trombones a3" instruments should be able to play a C#/Db5 and a D5, and possibly a D#/Eb5.

**Screenshots**
Notes that the trombone cannot play are marked in red:
![image](https://user-images.githubusercontent.com/15292203/213553134-ca88aa67-1aac-47b2-b15f-acae4f27af5b.png)

**Platform information**
Not relevant to issue.

**Additional context**
Discovered while attempting to score Ravel's Bolero (the trombone cannot play its solo from that piece)

**Comment by Fristover** [comment] 2023-01-19 20:51
Ranges are limited on all the instruments, see #13894 
Possibly a duplicate of that?

**Comment by FL2070** [comment] 2023-01-19 22:14
@Fristover By technicality, one could say that this issue is covered by #13894, but that issue basically just says "instruments ranges are too limited". It's very vague, no actual pinpointed issue to solve; only in the comments did people begin to mention specific instruments.

It's sort of like someone made a bug report saying only "there are things that don't work!", and then nobody can make any more bug reports, because by technicality, the first bug report covered all things in the program that don't work, so all other bug reports are """duplicates""" of that one. It also makes the issues a lot easier to track, because you can track by each individual instrument which needs its range extended.

So, I wouldn't consider this a duplicate, but of course, that's up to the people who manage these issues.

**Comment by s11141827** [comment] 2023-01-22 18:34
It needs updates

**Closed** 2023-01-27 23:02 UTC
