### ISSUE TITLE
[MU4 Issue] Custom formatting of text objects lost in copy and paste operations

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12756] opened 2022-08-10 10:32 UTC
**Describe the bug**

When a text object is copied and pasted, and it contains a SPACE with a custom font-size, the space disappears! Same thing happens if you save and reopen the file without copying the object

**To Reproduce**

1. Open a score
2. Click on a note say, then press Ctrl + T to add staff text.
3. Enter the characters "Greater than", SPACE, "Less than" (i.e. "< >")
4. Copy the text object to another fretmark, say.
RESULT: All font properties are preserved as expected.
5. Select the space in the text object and increase its font-size to 30, say. Then copy the object again.
RESULT: The space has disappeared.

**Expected behavior**

All font-properties, whether object-level or character-level, should be preserved during cut/copy/paste operations (and any other operations such as saving to a palette, or saving the file).

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2829968415, revision: github-musescore-musescore-2d21253

**Comment by rgreen5** [comment] 2022-08-12 10:13
**Additional issue**
There is also an allied problem with lost formatting when copying text objects in _imported MS3 files_.

1. Open the attached MS3 file in MS4. [harmonics.zip](https://github.com/musescore/MuseScore/files/9315524/harmonics.zip)
2. Copy and paste a harmonic _symbol_ (not the fretmark) from one of the existing fretmarks in measure 1 onto a _corresponding_ fretmark in measure 2.
RESULT: Custom formatting is lost during the operation and the harmonic symbol no longer fits the fretmark.

**Expected result**

All style and character formatting should be preserved during operations.

**Comment by oktophonie** [comment] 2022-09-19 09:19
Something else I have found triggers a reset of custom formatting: resetting (unrelated) styles to default. See video. I have, however, not been able to reproduce this consistently.

https://user-images.githubusercontent.com/20604032/190986882-ef84a406-ccc7-41f6-8143-d4c8c1482fbf.mp4

**Comment by bkunda** [comment] 2022-09-26 10:51
I can add to this issue that custom offsets for page numbers are reset to 0 when a file is closed and re-opened.

**Comment by MarcSabatella** [comment] 2022-09-26 13:48
Actually, unless something has changed since MU3, it's not meant to be possible to directly modify any properties of page numbers at all, since page numbers aren't saved with the score - they are generated on the fly during layout.  I can see that the MU4 inspector shows you properties, but unless there was also code added to handle how the modified page number would be saved, it's not surprising it wouldn't work.  Probably best to just disable the Properties for page numbers unless it really is meant to be supported and there's just a bug preventing it from working as intended.

**Comment by bkunda** [comment] 2022-09-28 13:54
You're right @MarcSabatella. Indeed, page numbers in MS4 should _not_ be modifiable from the properties panel at all. 
In terms of our release timeline, we are unfortunately well past the point of implementing an elegant solution to this now (i.e. making the properties panel show something sensible when a page number is selected), so I think the most straightforward solution in the immediate-short term is to make sure they are not selectable in the first place. 
I'll raise this as a separate issue.

**Comment by MarcSabatella** [comment] 2022-09-28 15:13
Agreed.  For most of MuseScore's existence, page numbers were not selectable, and there's nothing at all you can do with them once selected (at least in MuseScore 3), so no great loss.  I believe the only reason they end up being selectable at all is that code was added for one of the relatively recent 3.x releases to allow you to double-click the page number (or anything else in the header) to jump directly to the header style setting.

BTW, the one thing I notice you *can* attempt to do with a page number after selecting it in MuseScore 3 is press "V" to make it invisible.  Which then has the same issue as here - it looks like it worked (once you deselect it anyhow), but that's lost on save/reload, because page numbers aren't actually saved at all.

**Comment by cbjeukendrup** [comment] 2022-11-20 14:42
It looks like this issue got even worse recently: now _any_ kind of formatting is lost on copy paste. This seems to be caused by the `styleChanged` call that @mike-spa added in `Score::undoAddElement`. 

So I've researched this a bit and found that there are two problems here:
- `styleChanged()` erases all formatting (this is why currently all formatting is lost, and probably also the cause of the variant that Simon found)
- There is a bug inside `XmlReader::readXml()` which causes that the space character is lost, as mentioned in the original issue. This seems not to be caused by `XmlReader::readXml()` itself, because the space character is not seen in that method, so it must be lost deeper inside `XmlStreamReader`. (Also, note that the space character is not only lost when copy-pasting, but also when saving+reopening.)

To solve problem 1, we need a way to determine when to reset the formatting and when not. In MuseScore 3, it seems like things work completely differently, namely formatting can be set in multiple ways: (1) in the Inspector, there is a "base formatting" that applies to the whole text object until the character where you have applied special formatting; (2) you can also override the formatting per character. The relation between these two is not entirely clear to me; it seems that when the "base formatting" is unmodified (i.e. bound to the style value) _and_ you have _never_ made any per-character changes, _only then_ the formatting will be reset when the style changes. That doesn't hold in all cases though... 
Anyway, that was better than what MS4 does now, so I'll attempt to bring back that behaviour to some extent. 

To solve problem 2, we need to dive deep into `XmlStreamReader`. I believe that's mainly @igorkorsukov's area...

**Comment by mike-spa** [comment] 2022-11-21 09:05
What surprises me is that `styleChanged()` only acts on STYLED properties, i.e. properties which follow the score general style. Normally, when an item is customized, the connected property becomes marked as UNSTYLED so it shouldn't be involved in styleChanged(), hence the user customization should be preserved. So I would assume that the problem is that, when modifying text formatting, we forget to set the connected property as UNSTYLED. 
I can look into that. One thing I can definitely do, for now, is restrict the call to styleChanged() in `Score::undoAddElement` to the case where the origin score is different than the target score (i.e., we're cloning to/from an excerpt). This at least will solve the problem of lost formatting when copy-pasting within the same score.

**Comment by MarcSabatella** [comment] 2022-11-21 14:00
I suspect this is also connected to https://github.com/musescore/MuseScore/issues/14557.  I reported that as, size adjustments being lost on save/reload.  But I can confirm they are also lost on copy / paste, which makes sense since they use the same basic read/write code I believe.  For chord symbols, though, the problem is both on copy/paste and save/reload, whereas for other text, it seems only save/reload.

**Comment by mike-spa** [comment] 2022-11-21 17:42
So, I've been looking into it. It seems that part of the problem(s) comes from here: https://github.com/musescore/MuseScore/blame/master/src/engraving/libmscore/textbase.cpp#L2296-L2297 @wizofaus could you explain why that particular change was made?
We are intentionally excluding some property tags from the xlm. Let's say I create a staff text and make it bold. This is the resulting xml we get now:
<img width="215" alt="withoutLabel" src="https://user-images.githubusercontent.com/93707756/203120583-f860801a-968f-430c-8ae6-0149bbd250eb.png">
and this is the resulting xml if I remove the exclusions and let those properties be written.
<img width="239" alt="withLabel" src="https://user-images.githubusercontent.com/93707756/203120313-c0f41b9f-1363-476a-9516-6a639410e933.png">
You could say that in the second case the "bold" information is duplicated, as it is both written as a global property of the object _and_ within the xlm string itself. But that global `<bold>` tag lets Musescore know that that property has been user-modified, which lets the rest of the program handle it properly. 
This appears to solve the copy-pasting problem, the additional problem reported by @oktophonie, and also #14557 reported by @MarcSabatella. But before I go ahead and do the fix I want to make sure that this wouldn't cause nuclear accidents elsewhere

**Comment by MarcSabatella** [comment] 2022-11-21 18:13
FWIW, I assume it relates to the original issue https://github.com/musescore/MuseScore/issues/8652 and you'd want to check that it doesn't break that.  But, I think it's already partially broken again as per https://github.com/musescore/MuseScore/issues/13344.

**Comment by wizofaus** [comment] 2022-11-21 19:15
The text formatting code is rather fragile unfortunately - are you able to find the pull request associated with that change?
Essentially though we got rid of object- level formatting properties - they all only apply at the character level now.

**Comment by cbjeukendrup** [comment] 2022-11-21 19:28
> Essentially though we got rid of object- level formatting properties - they all only apply at the character level now.

But that sounds scary! These properties are still controlled by style settings, using the usual system with `Pid` and `PropertyFlags` and all that. So if the properties have been (apparently partly) removed but the style settings still try to control them, we can expect strange situations.

**Comment by wizofaus** [comment] 2022-11-21 20:09
Yes, there were definitely some issues with styles, but there were worse such issues in v3.6.
I found the PR here https://github.com/musescore/MuseScore/pull/8815 but unfortunately it didn't shed any light on what exact problem I was solving with that modification, but I definitely wouldn't have included it if it weren't needed!
At any rate, it seems to me if there's already sufficient information in the xml, then the fix to should be the logic that's currently not working rather than adding extra redundant info to it.

**Closed** 2022-12-01 14:58 UTC
Labels: P2
