### ISSUE TITLE
MacOS MuseScore 4.4.2 crashes when loading MS 3.6.2 score with hidden instruments

### ISSUE THREAD

**Issue by JesWagner** [musescore/MuseScore#24802] opened 2024-09-18 15:40 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

Load the MS 3.6.2 score in MS 4.4.2. It crashes immediately

Attached file: 04_Wie_des Abends.mscz.zip

### Supporting files, videos and screenshots

[04_Wie_des Abends.mscz.zip](https://github.com/user-attachments/files/17046471/04_Wie_des.Abends.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: 3130f97

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 14.6,1 Arch.: arm64

### Additional context

See: https://musescore.org/en/node/368929#comment-1258916

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-09-18 16:33
On Windows it doesn't crash in 3.6.2 nor in 4.4.2, but it does crash in 3.7, when starting playback.
It seems related to a) the score having hidden staves )no crash woth those unhidden) and b) to the extra voltas on the 2nd staff, the stack trace hints at there being an issue. See https://github.com/Jojo-Schmitz/MuseScore/pull/647 for an attempt to fix that.

**Comment by zacjansheski** [comment] 2024-09-19 13:30
Score opens in 4.4.0
Crashes in 4.4.1 and current 4.4.3

**Comment by RomanPudashkin** [comment] 2024-09-24 09:44
@zacjansheski I can't reproduce it using the latest 4.4.3 nightly (but I can reproduce it using 4.4.2)

**Comment by zacjansheski** [comment] 2024-09-24 15:01
Confirmed, fixed in Nightly

**Closed by zacjansheski** 2024-09-24 15:01 UTC
Labels: P1, needs testing, regression MS4, crash

**Comment by Jojo-Schmitz** [comment] 2024-09-24 15:27
Do we know which change fixed it?
