### ISSUE TITLE
Supporting All Open Source Contribution Types

### ISSUE THREAD

**Issue by jeremy-donson** [musescore/MuseScore#11535] opened 2022-05-05 14:22 UTC
I live in NYC and represent dozens of music educators at a wide variety of institutions.

They hope to do the following with v4.x:
- Demonstrate how to contribute to this open source project in a variety of ways. => WE ARE HERE
- Show their students how to to use the software, including upgrading and testing existing 3.x files.
- Show their students how to collaborate with the software (likely via a web site).
- Discuss open source tools and proprietary tools, with fluency about trade-offs.

To this end, my goal is to improve open source project contributor support.

Several types of contributions to the museScore project are listed [here](https://musescore.org/en/contribute):
- development (there ought to be a note about web site and mobile apps NOT being open source?)
- testing (separate tech testing from edu testing?)
- docs
- user support
- design and usability
- translations
- plugins
- marketing

In each case, an example contribution would be a good start.
Furthermore, onboarding contributors ought to be a paved road in each case.
Where appropriate, proposing issue templates/labels/review process that correspond can be extremely helpful.

Next steps:
- Review issue templates and labels.
  - [Issues Templates](https://github.com/musescore/MuseScore/tree/master/.github/ISSUE_TEMPLATE)
  - [Labels](https://github.com/musescore/MuseScore/labels)
  - [How to write a good bug report: step-by-step instructions](https://musescore.org/en/node/309537)
  - [Contributing Guidelines](https://github.com/musescore/MuseScore/blob/4606756761edaa50482cf5b28db2bb57ad465df0/CONTRIBUTING.md)

Gleaned from jeetee via discord:
- https://musescore.org/en/forum/6
- https://musescore.org/en/node/309537 which is under the "Testing" contrib type
- https://github.com/musescore/MuseScore/wiki/Contributing
- https://musescore.org/en/node/331750
- https://musescore.org/en/faq#faq-23637

Questions Raised:
- Feature and tech test issues come first.  What tech tests are currently in need of better support right now in 4.x release?
- There ought to be a note about web site and mobile apps NOT being open source on contributor page?
- How do we separate tech testing from edu testing?  (seems we dont?)
- How might some templates and labels be proposed?
- How do we support existing organic dev team processes?
- How might automation improve those processes?
- Is there any released outline of the 4.x docs?

**Comment by jeremy-donson** [comment] 2022-05-05 14:37
I was asked to clarify the terms of technical testing vs edu testing.

Technical testing:  Goes to how to ensure that the software app is working as desired.
=> The goal here is excellent tech collab when building the tools together.

Edu testing:  This would focus on techniques for how musicians and teachers to use the software, in particular for collaboration.  Simplest examples are indispensable for this kind of thing.  One edu testing track would be for legacy 3.x users.  Another track would be for 4.x users who dont have legacy skills.
=> The goal here is to support collaboration by musical educators and students.

**Comment by jeremy-donson** [comment] 2022-05-05 15:14
The structure of a tutorial needs some work:
https://musescore.org/en/tutorials

**Comment by Tantacrul** [comment] 2022-05-05 16:16
Just closing this issue because it is not a bug and not actionable. However, welcome!

I think we're going to turn on GitHib discussions and then move this there, since it's obviously a better place.

**Comment by jeremy-donson** [comment] 2022-05-05 16:17
Github discussions are MUCH better fr this.  Thx!

**Closed by Tantacrul** 2022-05-05 16:16 UTC

**Comment by Tantacrul** [comment] 2022-05-05 16:29
> 

Please don't whine at us on GitHub. Discussion on Discord please.

**Comment by shoogle** [comment] 2022-05-05 16:31
Hi @jeremy-donson, so many questions! It's great that you are keen to help. The best way to do so is to try to work things out for yourself as much as you can, and where you cannot, try to raise a straightforward question or propose a single actionable point.

**This point is actionable:**

> There ought to be a note about web site and mobile apps NOT being open source on contributor page?

I'm happy to add this note. I have now done so at https://musescore.org/en/contribute under the Development heading.

**This question is straightforward:**

> Is there any released outline of the 4.x docs?

Documentation for MuseScore 4 is being drafted by our internal team here: https://musescore.org/en/draft-handbook-mu4

**Remaining questions:**

These are more open ended and require more time to respond. I'll just pick a few for now.

> What tech tests are currently in need of better support right now in 4.x release?

We don't have a list and we don't have time to make one for you. You'll need to check for yourself in the code or see if any are mentioned in issues. If there are none mentioned then it probably means the problems (if any) are not considered big or urgent enough to be worth acting upon.

>The structure of a tutorial needs some work: https://musescore.org/en/tutorials

This point is not actionable. You haven't said what the problem is or suggested a way to solve it.

> Please ping me if/when discussions are enabled?

We haven't said we are going to do this, and in fact we probably don't want to as it would just create another avenue of communication in addition to our Forums, Discord server, and this issue tracker.

> How do we support existing organic dev team processes?

Firstly, please take the time to understand those processes. We don't have time to explain everything to each new person that arrives, so read the existing documentation and observe how our other contributors interact. You'll get the hang of it soon enough!

**Comment by shoogle** [comment] 2022-05-05 16:35
Hi @jeremy-donson, so many questions! It's great that you are keen to help. The best way to do so is to try to work things out for yourself as much as you can, and where you cannot, try to raise a straightforward question or propose a single actionable point.

**This point is actionable:**

> There ought to be a note about web site and mobile apps NOT being open source on contributor page?

I'm happy to add this note. I have now done so at https://musescore.org/en/contribute under the Development heading.

**This question is straightforward:**

> Is there any released outline of the 4.x docs?

Documentation for MuseScore 4 is being drafted by our internal team here: https://musescore.org/en/draft-handbook-mu4

**Remaining questions:**

These are more open ended and require more time to respond. I'll just pick a few for now.

> What tech tests are currently in need of better support right now in 4.x release?

We don't have a list and we don't have time to make one for you. You'll need to check for yourself in the code or see if any are mentioned in issues. If there are none mentioned then it probably means the problems (if any) are not considered big or urgent enough to be worth acting upon.

>The structure of a tutorial needs some work: https://musescore.org/en/tutorials

This point is not actionable. You haven't said what the problem is or suggested a way to solve it.

> How do we support existing organic dev team processes?

Firstly, please take the time to understand those processes. We don't have time to explain everything to each new person that arrives, so read the existing documentation and observe how our other contributors interact. You'll get the hang of it soon enough!

**Comment by Tantacrul** [comment] 2022-05-05 16:35
@shoogle - we didn't actually discuss this, so sorry for the sudden change but @vpereverzev and I have been thinking for a while that Discussions should be opened so we can move non-actionable issues there and also provide another place for open discussion.

I think discussions are better for initiatives that we want to keep track of, whereas Discord is often better for general immediate chat.

However, we don't want to direct the form it takes too much. Anyway, Discussions is now open.
