### ISSUE TITLE
[MU4 Issue] Guitar bends do not play back

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13544] opened 2022-09-30 00:28 UTC
**Describe the bug**
Guitar bends do not play back

**To Reproduce**
1. Score for electric guitar
2. Add a whole note
3. Add a full bend from the Guitar palette
4. Play
5. Hear error: no bend

**Expected behavior**
Pitch should bend up a whole step

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/193165368-472b5096-2cbb-49ee-900a-05d7e1ddad1f.png)

**Platform information**
 - OS: Linux

**Additional context**
Another issue found in the MuseScore Cafe theme (in the bass part) - https://musescore.com/user/2975/scores/6656770

**Comment by Tantacrul** [comment] 2022-10-12 17:44
Unfortunately not. This one has been left until 4.x because the mechanism for getting them to follow the graph in the inspector needs to be completely rewritten. We just can't use the older system at all. I'll bump to 4.x for now. Will reopen when 4.0 is out.

Thanks!

**Comment by MarcSabatella** [comment] 2022-10-12 17:54
Understood; I guess that's a similar reason as why glissando/portamento no longer has the ease in/out controls.  Neither is a huge deal to me personally

**Comment by erinic04** [comment] 2022-12-17 02:16
@Tantacrul 4.0 is out now lol

**Comment by atirut-w** [comment] 2023-01-18 13:08
It's been a month nsince 4.0 released, according to @erinic04. Reopen when?

**Comment by Tantacrul** [comment] 2023-01-18 13:17
Do bear in mind, we have a lot of comments to get through :)

We are currently discussing the next steps for guitar bends, dives, improvements to notation and tab, as well as new sounds too :)

Our short term focus for this year will be both Guitar and Percussion.

**Comment by NilsFrederking** [comment] 2023-04-09 12:05
Hi Tantacrul, thanks for the great work: 
1.) in Musescore 3 the graph editor for the bend was only for upwards bends, it would make a lot of sense to have the possibility to bend in both directions (up + down)
2.) some people need octave bends others microtonal bends, it would be great if the resolution could be adjusted, as for example Logic Pro does for pitch bend.
3.) the system with x/y (time/pitch) axis and the ability to insert points was great.

**Comment by Tantacrul** [comment] 2023-04-09 12:28
Yes. This is a really big one on our radar. We're going to be tackling this in 4.2 I would say. In 4.1, we're hitting a few other guitar issues first.

Don't worry though - it's coming this year.

**Comment by henry7182** [comment] 2023-08-05 13:17
Yu can easily make a down bend.   Say you want a full bend down, then move the note down a full note on the score.  Click on the note and F8.  In the bend graph  drag the start  blue dot  a full note above the bottom axis .   Then  go across to right and make  the end blue dot on the bottom axis.  If you want a 2 note bend, then move the note in the score down  two notes  and make the start blue dot up two notes, and put the end blue dot on the bottom axis.

**Comment by bkunda** [comment] 2023-12-12 09:06
I'm going to close this issue now that the new bends system has been implemented.

**Closed by bkunda** 2023-12-12 09:06 UTC
Labels: P1, needs design, guitar

**Comment by Pixelz22** [comment] 2024-11-27 16:51
I've been having some trouble with guitar bends recently. For some reason, the first two in this image won't play unless I start the playback on those measures. The third one always plays. Every other guitar bend in the song plays correctly, I'm using the SC Lead sound from Muse Guitars with a Drop D tuning. I've tried deleting and rewriting the bends, deleting and rewriting the notes, deleting the measures and redoing them from scratch. It's always just those first two that have a problem. Any suggestions?

![image](https://github.com/user-attachments/assets/0739170c-46b8-44a9-920f-a1c4ea450d1c)

**Comment by cbjeukendrup** [comment] 2024-11-27 17:31
It's probably best to open a topic about this at https://musescore.org/en/forum/6. People there can help you narrowing down the cause of the problem. If it is determined that there is an actual reproducible bug, then they will advise you about how to report it.
