### ISSUE TITLE
[MU4 Issue] Zooming and scrolling in one part affects all parts

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7879] opened 2021-04-03 00:12 UTC
**Describe the bug**
Zooming and scrolling in one part affects all parts

**To Reproduce**
1. Create a score
2. Create a part
3. Zoom in (or scroll) on a main score
4. Open previously created part

**Expected behavior**
Zoom in / out works separately for main score and every part

**Screenshots**

**Desktop (please complete the following information):**
Linux Ubunty

**Additional context**

**Comment by cbjeukendrup** [comment] 2021-04-03 10:20
Related to https://github.com/musescore/MuseScore/issues/7820#issuecomment-810421235

**Comment by wizofaus** [comment] 2021-06-15 04:29
Confirmed - it seems there's one NotationPaintView shared between all open scores/parts, and that holds the current zoom/pan position, which seems very odd indeed, and obviously not trivial to fix, not really quite sure what the thinking was here?

**Comment by wizofaus** [comment] 2021-09-15 21:34
@vpereverzev @igorkorsukov I've had a bit more of look at this one and the problem seems to be that while Pan/Zoom are stored as properties of NotationPaintView, allowing them to be different between the Score and Publish views, because one NotationPaintView is used for all scores/parts opened within each of those views, they must all have the same current Pan/Zoom. But the current view/layout mode (Page View/Continuous View) has the *opposite* problem - it's effectively a property of the Notation object (in fact, stored within the score itself), and can't be different between Score and Publish view, which would actually be very useful (indeed the meaning of "pan" is dependent on what view you're looking at anyway, as the content rectangle is totally different shape).

One possibility is to simply store all three as properties of a Notation object directly, but then use a different Notation object for the Score and Publish views (both pointing to the same underlying Score object though).

If you're OK with this I'm happy to put up a PR...

**Comment by wizofaus** [comment] 2021-09-15 21:36
Actually sorry I see that @cbjeukendrup you've already proposed the same thing (except for having a different Notation object for Publish and Score view), happy to leave it to you, maybe somebody could assign this to you?

**Comment by DmitryArefiev** [comment] 2021-12-13 17:37
**Still occurs** in latest master build (Win10, Mac12)

**Comment by Tantacrul** [comment] 2022-04-30 11:24
This issue is still ongoing. Adding a P2 and assigning.

**Comment by cbjeukendrup** [comment] 2022-04-30 11:33
There is already a PR, and it just needs a review :)

**Comment by DmitryArefiev** [comment] 2022-05-06 18:29
Fixed in #10757

**Closed** 2022-07-13 07:56 UTC
Labels: P2
