### ISSUE TITLE
[MU4 Issue] Getting Started dialog has generic/unknown application icon

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11003] opened 2022-03-31 05:39 UTC
**Describe the bug**
The very first dialog presented to the user on installing is "Getting Started" and on Windows it's showing the generic/"unknown" application icon that's usually what you might see for new applications generated by Visual Studio or similar that haven't been configured properly with icons etc.

**To Reproduce**
1. Install & start up MuseScore for the first time
2. Notice generic/"unknown" application icon in top-left corner of Getting started dialog
 
**Expected behavior**
Getting started dialog should show proper MuseScore icon in top-left corner.

**Screenshots**
![image](https://user-images.githubusercontent.com/5364225/160984050-8504cec2-e6d2-4ab1-9d5d-cf08bd264ae4.png)

**Platform information**
Windows 10

**Additional context**
Fresh install of "official" Alpha build
Same problem happens in other dialogs, "Do you want to save changes?"

**Comment by HemantAntony** [comment] 2022-03-31 06:42
Related to #10597

**Comment by RobFog** [comment] 2022-03-31 07:53
Yeah, probably a duplicate of #10597

**Closed** 2022-03-31 10:01 UTC
