### ISSUE TITLE
Breath mark (comma) is played like a fermata

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20836] opened 2024-01-05 00:08 UTC
### Issue type

General playback bug

### Bug description

Breath mark (comma) is played like a fermata, which should not be the case. If a fermata increases the sound in time, then the Breath mark (comma) should pause.

### Steps to reproduce

-

### Screenshots/Screen recordings

![Снимок экрана (97)](https://github.com/musescore/MuseScore/assets/134041121/25ddd564-4c91-4e53-8189-0539c88eac0f)

https://github.com/musescore/MuseScore/assets/134041121/adb086e6-b8d8-42f5-a330-46930d6945c4

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I suspect that this bug works on all types of pauses that exist in the current version of Musescore, not only on the Breath mark (comma) (at least I did not check all types of pauses)

**Comment by MarcSabatella** [comment] 2024-01-05 00:14
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/20669 - definitely a (very serious) regression versus 4.1.1

**Comment by Dima12357** [comment] 2024-01-05 00:26
> I believe this is a duplicate of #20669 - definitely a (very serious) regression versus 4.1.1

There is no sound in the attached video files, so I do not know

**Comment by MarcSabatella** [comment] 2024-01-05 00:40
There's also no video, and more importantly no sample score, here :-).  But the descriptions are basically identical, and it's been reported at least a dozen times on the forums and elsewhere as well, so definitely a known issue.  Feel free to ZIP and attach your score, and a video with sound, to that earlier issue, to keep the relevant info in one place and make it easier to track.

**Comment by Dima12357** [comment] 2024-01-05 02:02
> There's also no video, and more importantly no sample score, here :-). But the descriptions are basically identical, and it's been reported at least a dozen times on the forums and elsewhere as well, so definitely a known issue. Feel free to ZIP and attach your score, and a video with sound, to that earlier issue, to keep the relevant info in one place and make it easier to track.

I have attached a screenshot and a video recording.

**Comment by MarcSabatella** [comment] 2024-01-05 02:36
Thank you, those confirm beyond all doubt this is indeed a duplicate (not that while the original post didn't include a video, my comment later did).  So please follow that earlier issue for further updates.

**Closed** 2024-01-05 08:44 UTC
Labels: playback
