### ISSUE TITLE
[MU4 Issue] Forte Piano dynamic does not play some of the time.

### ISSUE THREAD

**Issue by matts5323** [musescore/MuseScore#14471] opened 2022-11-11 01:22 UTC
Forte Piano (fp) dynamic does not play some of the time.

Add a forte piano to many extended wind notes in using Muse Sounds.
I Playback a couple of times, the same ones for me would always playback or not play back. I could not fix the issue by deleting the forte pianos, crescendos, or other elements.

Forte piano should always playback as shown in MU3, but in MU4 some just don't work.

 - OS: Windows 11

https://user-images.githubusercontent.com/58175783/201239657-b8891018-930a-46eb-b119-94f3d44a7b64.mp4

**Comment by erinic04** [comment] 2022-11-11 18:42
#13543

**Comment by cbjeukendrup** [comment] 2022-11-11 18:54
Duplicate of https://github.com/musescore/MuseScore/issues/13543

Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-11 18:54 UTC
