### ISSUE TITLE
Tab input shortcut no longer working

### ISSUE THREAD

**Issue by Aztecslug** [musescore/MuseScore#20687] opened 2023-12-24 10:42 UTC
I'm a guitar teacher who uses Musescore to transcribe pieces and exercises for my students.

Yesterday when trying to write out an exercise I could no longer input fret numbers on my tab by using the number keys on my keyboard. Before the update to 4.2 I could just use 'shift' + number key (I'm on Mac) to input the fret number but this no longer works, and I have to manually use my 'up' key until I reach the desired fret.

There's no issue with my keyboard, as I can type in numbers on any other program including Musescore 3. 

I tried restarting Musescore and my laptop but neither yielded a result.

I've uninstalled and reinstalled Musescore and that didn't help either.

The shortcuts haven't changed or been corrupted, they are listed identically to the shortcuts in Musescore 3 where Tab input works fine.

I've checked other forums and it seems like this isn't a common issue, but I can't efficiently use the program for my work and don't know what to do.

I'm on macOS Ventura 13.6.1, and tab inputs were working fine before the 4.2 update.

**Comment by MarcSabatella** [comment] 2023-12-24 14:36
This works fine for me and others users, so there must be something unique/unusual about your system configuration that is getting in the way.

You say the tab shortcuts are listed the same as before,e but did you try redefining them?  Also, do the letter keys still work?  What happens if you do Help / Revert to factory settings?

Also, check to be sure no new programs have been installed recently that could be interfering with keyboard processing.  Programs that implement macros are a common culprit that cause similar issues.

Also please ZIP and attach a specific score you are having trouble with and give precise steps to reproduce the problem.  Could be the issue is related to the configuration of the staff itself.  Even if this seems unlikely, since no one else can reproduce this, we need all the info we can to understand what might be going on.

**Comment by cbjeukendrup** [comment] 2023-12-24 17:53
Closing in favour of #20688

**Closed by cbjeukendrup** 2023-12-24 17:53 UTC
