### ISSUE TITLE
[MU4 Issue] Nonexistent notes played with repeat

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14263] opened 2022-11-02 05:08 UTC
**Describe the bug**
When play a repeat consisting of two measures, note that are not in the score are rendered.

**To Reproduce**
Instrument: Flute (doesn't matter whether it's Muse Sounds or MS Basic)
![image](https://user-images.githubusercontent.com/10248807/199402597-356abba1-edfa-4e87-9798-df48f4ff1a4f.png)
Play and observe that there are extra notes, which are not in the score, being rendered during the second pass.

**Expected behavior**
No extra notes should be rendered.

**Platform information**
 - OS: Windows 11
 - Build: MuseScoreNightly-202211010451-master-97bad50-x86_64

**Comment by cbjeukendrup** [comment] 2022-11-02 12:50
This looks like another duplicate of #13811. Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-02 12:50 UTC
