### ISSUE TITLE
[MU4 Issue] Hide empty staves within systems does not work with multi rest

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#16089] opened 2023-01-26 21:27 UTC
**Describe the bug**
The **hide empty staves within system** feature does not work within multi-rest. 

**To Reproduce**
1. create a piano score from the template
2. on streble staff, create a few notes, a few empty measures, and again a few notes
  (alternatively download this example https://musescore.com/user/28745487/scores/9642358 )
3. Make sure Format--> style -->  hide empty staves within system is ticked
<img width="631" alt="image" src="https://user-images.githubusercontent.com/2691085/214952186-677afce7-5542-42e7-bd13-4dbbc8e84757.png">

5. press m to toggle multi measures rest
6. See error, bass staff appears when multi measures rests are on 

**Expected behavior**
Empty staff should be hidden, even when multi-rest are on. 

**Screenshots**
<img width="997" alt="image" src="https://user-images.githubusercontent.com/2691085/214954091-0bc7008e-9795-4ca8-ba18-44f95d2c9e23.png">

**Platform information**
 - Musescore 4.0.1
 - OS: [macOS]

**Comment by oktophonie** [comment] 2023-01-26 21:39
Duplicate of https://github.com/musescore/MuseScore/issues/15368 (fix coming in 4.0.2)

**Closed by oktophonie** 2023-01-26 21:39 UTC
