### ISSUE TITLE
Color always changes to black when clicking "Cancel" in a color picker

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#17716] opened 2023-05-24 14:50 UTC
### Issue type

Other type of issue

### Bug description

When changing the color of any object in the properties panel, clicking the "Cancel" button in the pop-up color picker window will always change the color to black instead of keeping the current color. See the screen recording for demonstration.

### Steps to reproduce

1. Select some note or text objects on the staff.
2. Open a color picker window from the properties panel (**General > Appearance > Colour** and for text frames, **Text > More... > Border** or **Fill colour**).
3. Click the "Cancel" button or the top right "×" to close the color picker window.
4. The color changes to black.

Expected behaviour: The color should remain unchanged.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/70313425/6539b257-fed2-4111-b21f-61ddc0f0ffad

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2023-05-24 22:32
This is a duplicate of #15467, which has been fixed in the master branch (long ago already, but the fix was not included to 4.0.2). It will be included in the next update, 4.1.

**Closed by cbjeukendrup** 2023-05-24 22:32 UTC
Labels: needs review, regression_ms3
