### ISSUE TITLE
[MU4 Issue] Set duration of notes with Numpad. (Like all life)

### ISSUE THREAD

**Issue by clsard** [musescore/MuseScore#15364] opened 2022-12-19 08:36 UTC
With MS3 and earlier, you set the length of notes with the numpad. Not now and it can't be redefined in keyboard shortcuts either. The number keys and the number pad are not differentiated.

**Expected behavior**
Differentiating between the numeric keypad and the numeric keys helps to enter notes using the keyboard.

**Screenshots**
![Captura de pantalla 2022-12-19 093336](https://user-images.githubusercontent.com/2716821/208382334-5883d3bf-721a-4fa0-9e23-14a820240e9c.png)

**Platform information**
 - OS: Windows

**Additional context**
It helps a lot to have well-defined right-hand number keys for left-hand note input.

**Comment by jeetee** [comment] 2022-12-19 14:06
Duplicate of https://github.com/musescore/MuseScore/issues/12791

**Comment by cbjeukendrup** [comment] 2022-12-19 14:29
Closing as a duplicate

**Closed by cbjeukendrup** 2022-12-19 14:29 UTC
