### ISSUE TITLE
希望musescorce4支持播放五线谱时，钢琴键盘按键同步显示颜色，并支持在播放时显示敲击的midi键盘，可参考musescorce3的钢琴键盘功能

### ISSUE THREAD

**Issue by shvsjtrGitHub** [musescore/MuseScore#22972] opened 2024-05-25 16:03 UTC
### Your idea

希望musescorce4支持播放五线谱时，钢琴键盘按键同步显示颜色，并支持在播放时显示敲击的midi键盘，可参考musescorce3的钢琴键盘功能

### Problem to be solved

目前musescorce4播放五线谱时，钢琴键盘按键不会显示颜色，仅支持在播放时显示敲击的midi键盘

**Comment by cbjeukendrup** [comment] 2024-05-25 23:56
Duplicate of https://github.com/musescore/MuseScore/issues/14428

(I cheated by using a machine-generated translation. In the future, please write on GitHub only in English, so that we can understand it without having to rely on machine translations. Thanks!)

**Closed** 2024-05-25 23:56 UTC
Labels: feature request

**Comment by shvsjtrGitHub** [comment] 2024-05-26 03:52
> Duplicate of #14428
> 
> (I cheated by using a machine-generated translation. In the future, please write on GitHub only in English, so that we can understand it without having to rely on machine translations. Thanks!)



> Reference in new issue

Thank you for your suggestions and understanding, and for guiding me to the corresponding link.
At the same time, I have used a tool to translate, there might be some grammatical issues.
