### ISSUE TITLE
MusicXML import shows red notes when <midi-program> is set to guitar

### ISSUE THREAD

**Issue by guiv42** [musescore/MuseScore#21742] opened 2024-02-28 21:55 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When importing a MusicXML file with following properties, some notes appear in red unexpectedly:
```
<midi-instrument id="P1-I1">
    <midi-channel>1</midi-channel>
    <midi-program>26</midi-program>
</midi-instrument>
```

midi program 26 is a steel string guitar.
See example file attached below, with one single A3 note: it appears red, while it fits correctly in guitar's amplitude.
After deleting <midi-instrument> node (and child nodes), note appears correctly in black

### Steps to reproduce

1. Open attached MusicXML file
[test.zip](https://github.com/musescore/MuseScore/files/14440267/test.zip)

### Screenshots/Screen recordings

![Screenshot_20240228_223330](https://github.com/musescore/MuseScore/assets/129443524/79b548c6-a437-4538-8446-3bc7d8204805)

### MuseScore Version

OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-, revision: github-musescore-musescore-

### Regression

I don't know

### Operating system

Linux OpenSUSE tumbleweed (rolling release)

**Comment by oktophonie** [comment] 2024-02-29 07:25
An import matter, not engraving. The note is red because it's considered out of range; the problem is that the instrument is being identified as a cavaquinho:
![image](https://github.com/musescore/MuseScore/assets/20604032/adcac49d-bd1f-4a3e-89d1-7614374e90ba)

**Comment by Jojo-Schmitz** [comment] 2024-02-29 10:44
Cavaquinho happens to be the 1st entry in instruments.xml using `<midi-program>26</midi-program>`, Acoustic Guitar being the 2nd. Seems the matching ignores the (octave) ranspositioning?

**Comment by Jojo-Schmitz** [comment] 2024-02-29 11:01
In Mu3's instruments.xml Cavaquinho too turns up before Acoustic guitar. but the 1st entry for this MIDI/program, value is the Bouzouki, still Acoustic guitar is taken on import, so the order doesn't seem to be the (only?) reason

**Comment by shoogle** [comment] 2024-03-05 14:17
> I don't see any reason why Cavaquinho should be before Acoustic Guitar, but Bouzouki after?

It's because the Cavaquinho plays in a higher range than the Acoustic Guitar. Instruments are ordered by minimum playable pitch, which is how you would expect to see them in the score. We can't change this ordering to fix a MusicXML import problem.

During MusicXML import, instruments are identified [here](https://github.com/musescore/MuseScore/blob/340bd2f3c1dfc7fecce9b1054175612c87a573bb/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp#L489-L525). First it searches MuseScore's instrument database for a matching instrument by MusicXML instrument ID. If it doesn't find a matching ID then searches by name. If it doesn't find a matching name then it searches by MIDI program.

The search functions are defined [here](https://github.com/musescore/MuseScore/blob/340bd2f3c1dfc7fecce9b1054175612c87a573bb/src/engraving/dom/instrtemplate.cpp#L740-L812). In particular, the name search only returns a result if the name in the MusicXML [exactly matches](https://github.com/musescore/MuseScore/blob/340bd2f3c1dfc7fecce9b1054175612c87a573bb/src/engraving/dom/instrtemplate.cpp#L764-L766) a trackName, longName, or shortName of one of our instruments. This code should probably be updated to allow a fuzzy text match, and return the instrument that has the highest fuzzy match strength, or nothing if the fuzzy match strength is below a certain threshold value (which would be determined through experimentation).

At the moment, only exact matches are considered. The instruments are searched in order, hence if it gets to the [MIDI program search](https://github.com/musescore/MuseScore/blob/340bd2f3c1dfc7fecce9b1054175612c87a573bb/src/engraving/dom/instrtemplate.cpp#L804-L806), the first instrument with a matching MIDI program is returned. Ideally we would fix the name search so that it never gets to the MIDI search. However, we could also maintain a list of MIDI program numbers and the instruments that they most commonly represent, so that MIDI program 25 (26 in the MusicXML) would always return an acoustic guitar rather than searching our instrument database for the first instrument with this number.

**Comment by Jojo-Schmitz** [comment] 2024-03-05 14:45
Ah, I see. Here the XML has `<instrument-name>Steel String Acoustic Guitar</instrument-name>`, but there's no such track-, long- or shortName in instruments.xml, so it falls back to the MIDI program number.

The diff between Mu3 and Mu4 seems to be in the 'cleverness' of `searchTemplateForInstrNameList()`, Mu3's is much simpler.

**Comment by shoogle** [comment] 2024-03-05 15:48
No doubt MU4's search function was made cleverer to avoid some other problem with instrument detection, so the solution would be to make it even clever rather than reverting to MU3's function.

**Comment by Jojo-Schmitz** [comment] 2024-03-05 15:53
I didn't want to imply otherwise.
Also my claim thnat changing the order would fix it was not meant to be the real fix, sorry

**Comment by shoogle** [comment] 2024-03-05 16:14
That's fine. I wasn't trying to criticise you, but we do need to say what the right solution is for the sake of anyone reading who might want to fix it.

**Comment by Jojo-Schmitz** [comment] 2024-03-05 16:14
Sure

**Comment by pacebes** [comment] 2024-10-22 09:53
Hi
I am trying to deal with this issue looking into `combinedTemplateSearch `function.

I had some initial problems because I didn't notice my language setting was "Spanish". Every long and short name in instruments.xml is translated to the local language so, importing an XML exported in another language could also generate problems because text would not match. I don't know if it could be better to export and import them always in English (part-name, instrument-name, part-abbreviation ...).

A potential proposal could be:
- Keep a list of every instrument with the bigger matchStrength
- If there is more than one instrument use the Levenshtein algorithm (I have been looking in internet and it appears in several searches, but I would be happy if you have a better proposal) to determine which name is closer 
- If there are several with the same punctuation, choose the first (or last o r...)

I think this could be a way to avoid collateral damage.

**Comment by pacebes** [comment] 2024-10-22 15:10
I have made some tests with Levenshtein algorithm (Wikipedia Version) and the "distance"  with "Steel String Acoustic Guitar" would be: 
- Acoustic Guitar: 13
- Guitar:  22
- Cavaquinho:  25

Therefore in this specific case using long Names it would have worked because "Acoustic Guitar" is the closest. 
I have asked a friend about this options and he suggested to me using embeddings. 

I would appreciate any suggestion. I could create a pull request with the Levenshtein algorithm that would work in this specific case. Please, give me any feedback

**Comment by Jojo-Schmitz** [comment] 2024-10-22 15:43
I'd say: go ahead, that Levenshtein algorithm is a fuzzy search like @shoogle suggested

**Comment by pacebes** [comment] 2024-10-23 06:59
I don't know if I should have been assigned to this issue before creating the pull request. 
Please, give me any feedback in the pull request.

**Comment by pacebes** [comment] 2024-11-04 16:24
HI

I would like to know if there are some news about this issue and/or the related Pull request ( https://github.com/musescore/MuseScore/pull/25281 )

**Comment by pacebes** [comment] 2024-11-13 16:44
I'm looking for a new issue to work on checkin https://github.com/orgs/musescore/projects/30/views/1. I have seen that this issue is still labelled as labeled as "available".

As long as the changes in this issue have been approved (https://github.com/musescore/MuseScore/pull/25281 ) . Shouldn't it be labelled as "Tentatively in progress" or "In progress" ?

**Comment by Jojo-Schmitz** [comment] 2024-11-13 16:58
It should be assigned to you

**Comment by pacebes** [comment] 2024-11-13 17:02
Ok. who is in charge of assigning it ?

**Comment by Jojo-Schmitz** [comment] 2024-11-13 17:03
anyone from the internal team

**Closed** 2024-11-25 15:58 UTC
Labels: community, MusicXML

**Comment by guiv42** [comment] 2024-11-26 17:51
thanks!
