### ISSUE TITLE
Follow the system's dark preference

### ISSUE THREAD

**Issue by Kekun** [musescore/MuseScore#16966] opened 2023-03-22 08:17 UTC
### Your idea

MuseScore 4.0 offers a dark mode, and that's great! Some Linux systems also offer a dark mode with a well standardized API, what about following it? :)

### Problem to be solved

It's one thing less to ask the users on the first launch dialog, and it makes the app better integrate with the system.

![Capture d’écran du 2023-03-22 09-00-34](https://user-images.githubusercontent.com/2536339/226838055-2579a8b5-4578-4f83-8372-90dff299ea5c.png)
![Capture d’écran du 2023-03-22 09-00-39](https://user-images.githubusercontent.com/2536339/226838061-261394f1-367b-4d7e-8739-5cc4fec85a03.png)
![Capture d’écran du 2023-03-22 09-01-03](https://user-images.githubusercontent.com/2536339/226838066-b2bd6207-312a-4af6-b591-75437c9868aa.png)
![Capture d’écran du 2023-03-22 09-01-09](https://user-images.githubusercontent.com/2536339/226838071-05037b56-e78d-46c9-87dc-2e060529abe3.png)

### Prior art

You can check how it's done in GNOME's UI library (libadwaita) here: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-style-manager.c

It's probably somewhat easy to transpose this in a somewhat generic Qt UI, but I have no idea how to do so, maybe the KDE devs will know.

Some history:
- https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/
- https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/
- https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Dark-Style-Preference

Somewhat related but not quite, and definitely not ready yet but it's likely worth knowing for you: there is ongoing work to integrate a color scheme preference like in your dialog, see https://mamot.fr/@alexm@crab.garden/110065445138196603

### Additional context

I am running Musescore 4.0 from Flathub on Fedora 37, with GNOME 43.3.

**Comment by cbjeukendrup** [comment] 2023-03-22 10:15
Hi! This is a duplicate of #14377. Thanks for the suggestion anyway, and thanks for the links with info!

**Closed by cbjeukendrup** 2023-03-22 10:15 UTC
Labels: feature request
