### ISSUE TITLE
[MU4 Issue] "Insert special character" shortcut doesn't work.

### ISSUE THREAD

**Issue by Coxev** [musescore/MuseScore#15386] opened 2022-12-19 16:02 UTC
**Describe the bug**
Pressing the key assigned to the command "Insert special character" doesn't open the special character window. 

**To Reproduce**
1. Go to Edit > Preferences > Shortcuts.
2. Assign a shortcut for the command "Insert special character".
3. Go back to a score, click on an element.
4. Press the key assigned to the shortcut.
5. Nothing happen.

**Expected behavior**
When pressing the shortcut, the special character window should open in order to insert a special character without having to create a text.

**Platform information**
 - OS: Windows

**Comment by MarcSabatella** [comment] 2022-12-19 16:27
I think you may be misunderstand what this does.  It is only defined for inserting characters within text.  For attaching symbols directly to notes or other elements, instead you use the Symbols palette (found on the Master palette).

**Comment by cbjeukendrup** [comment] 2022-12-19 16:44
Indeed, the special characters window is only relevant when editing a text element on the score. That's by design. 

However, I did notice that if you set a custom keyboard shortcut for the special characters dialog, this custom shortcut doesn't always work; only the default shortcut works. This should be better after #15081.

**Comment by Coxev** [comment] 2022-12-19 16:47
Oh ok, I thought it was to open the symbols palette. I didn't see that the shortcut to open this palette was not yet added, I should have looked in the post on features not yet implemented, sorry.

**Comment by cbjeukendrup** [comment] 2023-01-09 14:29
I think that we can close this now, since the issue with custom shortcuts was indeed fixed by #15081 and for the rest this issue turned out to be a misunderstanding.

**Closed by cbjeukendrup** 2023-01-09 14:29 UTC
