### ISSUE TITLE
Space disappears in tempo text when score closed and reopened

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16903] opened 2023-03-18 11:33 UTC
### Issue type

Engraving bug

### Bug description

If you create a space in tempo text, as you might do between tempo text and its accompanying metronome mark, the space disappears when the score is closed and reopened.

### Steps to reproduce

1. Open attached MS4 specimen score 
[tempo_text_bug.zip](https://github.com/musescore/MuseScore/files/11008376/tempo_text_bug.zip)
2. In measure 7, insert a space between the tempo text and the metronome mark.
3. Save
4. Close and reopen the score

ACTUAL RESULT: The space disappears.
EXPECTED RESULT: The space should remain.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment] 2023-03-18 11:48
Duplicate of [#15629](https://github.com/musescore/MuseScore/issues/15629)

**Closed by oktophonie** 2023-03-18 11:48 UTC
Labels: engraving
