### ISSUE TITLE
Crash when trying to input on  drumset

### ISSUE THREAD

**Issue by Johan-v** [musescore/MuseScore#19953] opened 2023-11-06 18:09 UTC
### Issue type

Crash or freeze

### Bug description

Crash when input on drumset

### Steps to reproduce

Start new score and select drumset as instrument.
Start input
Crash

### MuseScore Version

(64-bit): 4.2.0-233100304, revision: github-musescore-musescore-59e727b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by zacjansheski** [comment] 2023-11-06 18:56
This is a duplicate of https://github.com/musescore/MuseScore/issues/19516

**Closed by zacjansheski** 2023-11-06 18:56 UTC
Labels: regression, crash
