### ISSUE TITLE
[MU4 Issue] BBC Symphony Dynamics and Articulation Does Not Work At All

### ISSUE THREAD

**Issue by hicani123** [musescore/MuseScore#12415] opened 2022-07-15 01:25 UTC
**Describe the bug**
When using the BBCSO VST, any dynamic and articulation changes does nothing to the sound. This includes Tremolo, Pizzicato, and Spiccato.

**To Reproduce**
1. Install and Setup BBCSO
2. Open Score and Setup Instruments
3. Change Dynamics or Articulations
4. Play Music

**Expected behavior**
A change in dynamics or articulation within the software should reflect a change in the VST menu and the audio. 

**Platform information**
 - OS: Windows 10

**Comment by Tantacrul** [comment] 2022-07-19 07:56
This is being worked on by @vpereverzev. I can confirm that there's a lot of improvement, which will be merged soon.

**Comment by Tantacrul** [comment] 2022-09-20 23:28
Articulations can not be mapped automatically by MuseScore. However, you can easily trigger key switches for temolo, pizz, etc, which is how the plugin was intended to be used.

Dynamics are now working well, so I'm closing this issue.

**Closed by Tantacrul** 2022-09-20 23:28 UTC
Labels: P1
