### ISSUE TITLE
[MU4 Issue] Unable to run Nightly AppImage directly on Wayland

### ISSUE THREAD

**Issue by Macr0Nerd** [musescore/MuseScore#15263] opened 2022-12-17 06:37 UTC
**Describe the bug**
I had come to report a bug about the menu position on Sway, but following guidelines decided to test on the Nightly build. I am unable to start the AppImage on Arch Linux running Sway due to the wrong QT_QPA_PLATFORM.

**To Reproduce**
1. Download Nightly build on Arch Linux running Sway
2. Choose `Run Once` option (does not affect result, just doesn't move to ~/Applications)
3. Open with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)
4. If opened in terminal, see error

**Expected behavior**
Nightly portable build would run fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/16966836/208228892-6edc9560-3605-4af8-8c36-e7bbe30a65f4.png)

**Platform information**
 - `uname -a`: `Linux BackpackTARDIS 6.0.12-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 21:04:34 +0000 x86_64 GNU/Linux`
 - OS: Arch Linux x86_64
 - Kernel: 6.0.12-hardened1-1-hardened
 - Window Manager: sway version 1.7
 - MuseScore Version: [MuseScoreNightly-223510506-4.0_rc-5485621-x86_64.AppImage](https://ftp.osuosl.org/pub/musescore-nightlies/linux/4x/nightly/MuseScoreNightly-223510506-4.0_rc-5485621-x86_64.AppImage)

**Additional context**
The `musescore` package on Arch works great, just on Wayland, the menus always appear in the middle of the screen and not on the cursor and disappear if the cursor is moved away from the menu button, forcing the user use the arrow keys to navigate.

**Comment by Eism** [comment] 2022-12-21 10:17
Thanks for reporting!

Looks like it is a duplicate of #11244

**Closed by Eism** 2022-12-21 10:17 UTC
