### ISSUE TITLE
[MU4 Issue] When creating a new score, the default soundfont isn't Muse Sounds unless manually turned on

### ISSUE THREAD

**Issue by Just-your-average-Github-user** [musescore/MuseScore#14050] opened 2022-10-26 05:43 UTC
**Describe the bug**
Unless manually turned on, after creating a new score, the default soundfont is not Muse Sounds, even though it is installed.

**To Reproduce**
1. Create a new score with an instrument that is supported by Muse Sounds.
2. Open the mixer.
3. See error.

**Expected behavior**
The default soundfont should be Muse Sounds.

**Screenshots**

**Platform information**
 - OS: Windows 10

**Additional context**
The issue persists on both the beta and the latest nightly.

**Comment by Grillzombie** [comment] 2022-10-26 11:51
Do you have MuseSound activated in View -> Playback setup (as default)?

**Comment by Just-your-average-Github-user** [comment] 2022-10-26 15:03
Sorry, the wording wasn't clear. What I meant was that, unless turned on manually, Muse Sounds doesn't become the default soundfont after installation. Just like Musescore 4 is set as the default to open scores, I also think Muse Sounds should become the default.

**Comment by cbjeukendrup** [comment] 2022-11-21 19:54
I'll close this in favour of https://github.com/musescore/MuseScore/issues/14634, which is a duplicate of this issue. Although you were earlier with this report, I'll close this one and leave the other one open, since that one is a little bit more clear. Hope you don't mind. Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-21 19:54 UTC

**Comment by Just-your-average-Github-user** [comment] 2022-11-22 15:14
As long as the issue is solved, it doesn't really matter.
