### ISSUE TITLE
Impossible to adapt an position property of several selected elements without affecting their other position properties

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#21235] opened 2024-01-26 15:22 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When modifying a position property of a group of selected elements (such as Texts), all their position properties are reset to the same values. 

### Steps to reproduce

1. Select 2 elements with different values for OffsetX and OffsetY. 
2. Modify the OffsetY value
3. The 2 elements will have their OffsetX set too, while this was not requested.

### Screenshots/Screen recordings

![issuePosition](https://github.com/musescore/MuseScore/assets/50494/c40a7ef1-94c7-4423-8e7e-dbd18630c5f6)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows10

**Comment by oktophonie** [comment] 2024-01-26 15:46
Duplicate of https://github.com/musescore/MuseScore/issues/15452

**Closed** 2024-01-26 15:46 UTC
Labels: duplicate, UX/interaction
