### ISSUE TITLE
Playback jumps to bar 1

### ISSUE THREAD

**Issue by Okruidhof** [musescore/MuseScore#18340] opened 2023-07-01 14:29 UTC
### Issue type

General playback bug

### Bug description

After a few (random number) playback actions, playback starts at bar 1, and keeps starting at bar 1, no matter reposition the cursor. This happens also after using loop playback. 

### Steps to reproduce

Hard to reproduce since number of playbacks needed before it jumps to bar 1 varies.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 11 Build 22621.1848

**Comment by bkunda** [comment] 2023-07-03 13:19
Can you please attach a screen recording and/or score file so we can verify and reproduce this problem?

**Comment by zacjansheski** [comment] 2023-09-13 19:02
I think this is a duplicate of https://github.com/musescore/MuseScore/issues/19259

We will refer to that report moving forward, thank you!

**Closed by zacjansheski** 2023-09-13 19:02 UTC
Labels: needs info, playback
