### ISSUE TITLE
Change the little icons on the menus

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#24454] opened 2024-09-04 14:58 UTC
### Your idea

I think it would be aesthetically pleasing if these icons, in all the menus they appear, can be replaced, maybe with MS logo.

![1](https://github.com/user-attachments/assets/bfce615d-d469-4671-b131-71e3160b97a4)

### Problem to be solved

Change the current icons with something better.

### Prior art

![2](https://github.com/user-attachments/assets/2960a980-1472-46d0-921b-0bc32fd506db)

This, for example, is from OBS.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-09-04 15:10
Duplicate of https://github.com/musescore/MuseScore/issues/10597

**Closed by oktophonie** 2024-09-04 15:10 UTC
Labels: feature request
