### ISSUE TITLE
playback too fast - pitch too high

### ISSUE THREAD

**Issue by ale47p** [musescore/MuseScore#19311] opened 2023-09-07 07:37 UTC
### Issue type

General playback bug

### Bug description

I know it's a known bug for some drivers, I don't know if the ESI U86 XT is on the list.
I just bought this audio device. with the old one (ssl2) it worked properly. it still works fine with internal audio card of the pc

### Steps to reproduce

open
wait for the samples to load
play

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

win 10

**Comment by DmitryArefiev** [comment] 2023-09-07 08:40
@ale47p Can you try the latest master please? https://github.com/musescore/MuseScore/actions/runs/6104900292

We have fixed some related issues recently

**Comment by ale47p** [comment] 2023-09-07 08:56
tried, same issue

**Comment by MarcSabatella** [comment] 2023-09-07 13:04
As a workaround, have you tried changing the changing the sample rate of your audio device?  Usually 44.1 or 48 kHz works best.

**Comment by cbjeukendrup** [comment] 2023-09-07 16:05
Possible duplicate of https://github.com/musescore/MuseScore/issues/17648

**Comment by bkunda** [comment] 2023-09-08 13:20
As this device is a multi-channel device, it seems it is indeed a duplicate of https://github.com/musescore/MuseScore/issues/17648.
Closing for now.

**Closed by bkunda** 2023-09-08 13:20 UTC
Labels: needs info, playback
