### ISSUE TITLE
[MU4 Issue] multirest size too small

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#16015] opened 2023-01-23 05:28 UTC
**Describe the bug**
sometimes the horizontal length of the multirest is too small in parts

**To Reproduce**
1. make multiple resting bars (maybe with time signatures with 16 as the bottom number?)
2. activate multirests
3. see how long the bar is

**Expected behavior**
multirest bars should be the size of a regular bar

**Screenshots**

![image](https://user-images.githubusercontent.com/120861729/213971358-48f3abf0-3920-4672-b07f-88ac0835df34.png)

**Platform information**
windows

**Additional context**
it seems to happen when the bottom number is 16 in this example

**Comment by Vykoiazon** [comment] 2023-01-23 05:30
did not check if it also happens in additive signatures like 3/8+3/4

**Comment by cbjeukendrup** [comment] 2023-01-23 17:01
This looks like a duplicate of #15561, which should be resolved by https://github.com/musescore/MuseScore/pull/15778. Thanks for reporting though!

(You can try out the test version from https://github.com/musescore/MuseScore/pull/15778 following these instructions: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#Downloading-Builds-from-Pull-Requests)

**Closed by cbjeukendrup** 2023-01-23 17:01 UTC
