### ISSUE TITLE
Menu drop-down position wrong on Wayland

### ISSUE THREAD

**Issue by Freakness109** [musescore/MuseScore#19261] opened 2023-09-03 15:02 UTC
### Issue type

UI bug

### Bug description

When opening a drop-down menu on the menu-bar, the menu is positioned in the middle of the screen instead of below the corresponding item. This is especially an issue with nested drop-downs, they end up stacked. Maybe related: tool-tips are also positioned incorrectly.

### Steps to reproduce

1. Launch Musescore
2. Click a menu item

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/7904246/d666290e-d5c6-417d-b7f3-3c9a9d5b147d

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Arch Linux

### Additional context

Full version string: OS: Arch Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-, revision: github-musescore-musescore-
Desktop environment: Hyprland v0.28.0 (Wayland window manager)

**Comment by cbjeukendrup** [comment] 2023-09-03 16:40
Duplicate of https://github.com/musescore/MuseScore/issues/15285. Thanks for reporting!

**Closed by cbjeukendrup** 2023-09-03 16:40 UTC
Labels: UI
