### ISSUE TITLE
Loop playback isnt working

### ISSUE THREAD

**Issue by wolfred24** [musescore/MuseScore#18266] opened 2023-06-29 06:08 UTC
### Issue type

General playback bug

### Bug description

Loop playback isnt working, it is just not playng the loop section in a "loop" pls look at the following test evidence video.

[Screencast from 2023-06-29 00-02-44.webm](https://github.com/musescore/MuseScore/assets/25995755/f292053d-6ff6-4bf4-846d-5fcf21df53d4)

### Steps to reproduce

- Start a loop
- Press play button
- Musescore is not following the loop

### Screenshots/Screen recordings

[Screencast from 2023-06-29 00-02-44.webm](https://github.com/musescore/MuseScore/assets/25995755/5987baf2-0578-4224-9b8a-55f08fed19cc)

### MuseScore Version

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Debian 12

### Additional context

Im using AppImage version

**Comment by zacjansheski** [comment] 2023-06-29 13:25
I'm unable to watch the uploaded video

<img width="788" alt="Screen Shot 2023-06-29 at 9 24 59 AM" src="https://github.com/musescore/MuseScore/assets/69917893/a61ca947-c1e9-48da-b17b-62255dd7996c">

**Comment by zacjansheski** [comment] 2023-06-30 01:17
If you change it to a .zip file you can upload it (compress or rename)

**Comment by wolfred24** [comment] 2023-06-30 02:16
[Air_from_Orchestral_Suite_No._3_BWV_1068_in_D_Major__Bach.zip](https://github.com/musescore/MuseScore/files/11912050/Air_from_Orchestral_Suite_No._3_BWV_1068_in_D_Major__Bach.zip)

Done

**Comment by zacjansheski** [comment] 2023-06-30 17:01
Confirmed, volta and repeats break loop functionality.

This is a duplicate of https://github.com/musescore/MuseScore/issues/16875

Closing as a duplicate and referring to the other log, thank you!

**Closed by zacjansheski** 2023-06-30 17:01 UTC
Labels: needs info, playback, regression_ms3
