### ISSUE TITLE
Dialogue windows won't open.

### ISSUE THREAD

**Issue by matj1** [musescore/MuseScore#22961] opened 2024-05-24 07:51 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When I open a dialog window, it shows the window but black for a short time, and then the window closes. This applies to time signature properties, staff properties and “Select/More…”, but not measure properties and style.

### Steps to reproduce

1. Have a sheet open.
2. Right-click on a time signature.
3. Select “Time Signature Properties” (or similar; I translate this from a different language).
4. Check that the properties window is black and closes after a short time.

similarly for other mentioned dialogue windows

### Screenshots/Screen recordings

[Trying to show time signature properties](https://github.com/musescore/MuseScore/assets/22873928/d0bad3f4-8eb8-43e3-b660-ac8d736ea73e)
[Trying to select more](https://github.com/musescore/MuseScore/assets/22873928/db6cd595-aa05-4265-8b0a-b738d717877a)

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

NixOS and Arch Linux

### Additional context

I reproduced this on NixOS in the Flatpak distribution and in the Nix package distribution. I remember that it was like that on Arch Linux too before I switched to NixOS recently.

I don't know in which version it started to happen, but it has been like that for at least several months.

The terminal output doesn't show anything when the dialogue window closes.

**Comment by Magnus26** [comment] 2024-05-24 10:35
I can't reproduce this issue on Q4OS.

**Comment by MarcSabatella** [comment] 2024-05-24 12:56
Can you reproduce this using the official supported AppImage obtained directly from MuseScore?  Third party builds provided by others often have hard-to-diagnose errors like this.  If the issue only occurs with their builds, you’d need to report the problem to them.

Also note Wayland isn’t well supported right night; you’ll want to run under X11.

**Comment by cbjeukendrup** [comment] 2024-08-23 17:55
This looks very much like https://github.com/musescore/MuseScore/issues/18608. That issue is closed, because the conclusion was that it is not a MuseScore issue but most likely a GNOME `mutter` issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/2820
That issue has been fixed, but I cannot really assist in acquiring the fixed version of `mutter`. Hopefully you can find information about that elsewhere. 

Besides, Wayland support has been improved in 4.4, for which the release candidate can be downloaded at https://musescore.org/en/node/367322. When you run the AppImage with the `QT_QPA_PLATFORM=wayland` environment variable set, the app runs via Wayland instead of `xcb`/XWayland, which might also solve this. 

I will close this issue now for these reasons; but if neither updating `mutter`, nor running MuseScore Studio 4.4 with `QT_QPA_PLATFORM=wayland` solves it, we can reopen it.

**Closed by cbjeukendrup** 2024-08-23 17:55 UTC
Labels: community, regression MS4, UX/interaction, os: linux
