### ISSUE TITLE
[MU4 Issue] Ties are ignored in playback if there is also a slur

### ISSUE THREAD

**Issue by Johnj1995** [musescore/MuseScore#14501] opened 2022-11-12 20:56 UTC
**Describe the bug**
Ties are ignored in playback if there is also a slur

**To Reproduce**
Playback the test score: 
[Slur test.zip](https://github.com/musescore/MuseScore/files/9995894/Slur.test.zip)
The tied note is played twice.
Delete the slur and play the score again. The tied note is not repeated.

**Expected behavior**
The tied note should play normally.

**Platform information**
Windows 11

**Additional context**
Note: This only occurs with the MS Basic soundfont and not with MuseSounds.

**Comment by cbjeukendrup** [comment] 2022-11-12 21:51
This is a duplicate of #14137, which has been fixed. Please check the latest nightly build (https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds). Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-12 21:51 UTC
