### ISSUE TITLE
grace note intersects with eighth note beams

### ISSUE THREAD

**Issue by goldstargloww** [musescore/MuseScore#23887] opened 2024-08-03 22:49 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. make some eighth notes that beam, stems pointing up
2. create a grace note whose pitch is sufficiently higher than the eighth notes, such that the grace note's stem and flag intersect with the eighth notes' beam

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/d4aacecc-709b-47b0-aa12-7cac5fd362fb)
![MuseScore4_d5cHHg2qda](https://github.com/user-attachments/assets/30ed5131-ef21-4b78-b021-2ac9783064a0)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-04 11:28
Duplicate of https://github.com/musescore/MuseScore/issues/11013

**Closed by oktophonie** 2024-08-04 11:28 UTC
Labels: engraving
