### ISSUE TITLE
[MU4 Issue] Offsets (of fingering) not updated by "Save as default style" (in Properties panel)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13475] opened 2022-09-24 10:51 UTC
**Describe the bug**

If you place a series of fingering on notes, then adjust the offset of one and press "Save as default style", all the fingerings of that class should update—but they don't.

It seems that for offsets, at any rate, the "Save as default style" button is inoperative.

**To Reproduce**

1. Open the attached score. 
[style_not_updated.zip](https://github.com/musescore/MuseScore/files/9638514/style_not_updated.zip)

2. Click on a fingering number and change the vertical offset, say, in the "Appearance" section of the Properties panel.
3. Now click on the ellipsis above the property and select "Save as default style for this score."

RESULT: Nothing happens. The offsets for the other fingerings remain unchanged.

**Expected behavior**

The offsets of the other fingerings of the same class should be immediately updated.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3117031689, revision: github-musescore-musescore-bd3e1bb

**Comment by MarcSabatella** [comment] 2022-09-25 13:36
Probably a duplicate of, or at least very related to, https://github.com/musescore/MuseScore/issues/13077

**Comment by cbjeukendrup** [comment] 2023-03-04 19:44
@rgreen5 This seems to be working for me now. Could you please recheck?

**Comment by rgreen5** [comment] 2023-03-05 10:46
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230640504, revision: github-musescore-musescore-769b3af

OK.

**Comment by cbjeukendrup** [comment] 2023-03-05 12:21
Thanks, then I'll mark it as completed.

**Closed by cbjeukendrup** 2023-03-05 12:21 UTC
Labels: needs info
