### ISSUE TITLE
Keyboard note entry adds notes out of the instrument's range

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#23409] opened 2024-07-01 00:13 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The keyboard note entry adds notes out of the instrument's range when trending in that direction.  A better UI/UX interaction would be adding the nearest note (higher) within the instrument's range.
This happens in violin.  Didn't try other instruments, but suspect this behavior would occur.

### Steps to reproduce

1. Create a new score for violin solo.
2. Press "N" to enter note entry mode
3. Press CTRL + Down Arrow to move to middle C4
4. Press B, A, G - notes are correct
5. Press F - note is now out of range for violin.
6.a Press E, D, C, etc. - notes continue out of violin range 

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137847641/4bdc417d-a9b7-49dc-a534-35e473c4dbb6)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by MarcSabatella** [comment] 2024-07-01 00:50
This seems to be a duplicate of https://github.com/musescore/MuseScore/issues/20989.  I’m not a personally fan of the idea for the reasons ger iven in that oththread, but of course it’s not my decision to make.

**Comment by seisfeldt** [comment] 2024-07-01 04:01
I agree - the argument for above the range is valid, but unless there is scordatura (or subharmonic) you cannot play lower than an F## on a violin :-)
This really only would apply to the algorithm that automatically adds new notes based on what seems like if you are ascending or descending during note entry.  You could always override this if there was some very unusual need for notes below the valid range.

**Closed** 2024-07-01 06:54 UTC
Labels: duplicate, UX/interaction
