### ISSUE TITLE
Playback gets transposed by 3 semitones

### ISSUE THREAD

**Issue by yes15202** [musescore/MuseScore#21813] opened 2024-03-04 20:26 UTC
### Issue type

General playback bug

### Bug description

I am using the MuseSounds strings (Bass-Violin 1) sounds, and occasionally the playback will be transposed down 3 semitones for no obvious reason. When I open and close the program it usually fixes it, but it sometimes happens again the next time I launch Musescore.

### Steps to reproduce

1. Open a file that uses the MuseSounds strings sound (unknown if this is the cause)
2. Change audio source through disconnecting the current output?
3. Click on a note to play it, or press the play button

### MuseScore Version

4.2.1.2.240230937

### Regression

I don't know

### Operating system

Windows 11

**Comment by dcorson-ticino-com** [comment] 2024-03-04 21:36
Sound like maybe your audio devices are not running at the same frequency.
Check in their settings and be sure they are all using the same sampling frequency, such as 48,000Hz for example.

**Comment by zacjansheski** [comment] 2024-03-05 16:10
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/17877

**Closed by zacjansheski** 2024-03-05 16:10 UTC
Labels: needs info, playback
