### ISSUE TITLE
[MU4 Issue] "Applies to" does not work for dynamics

### ISSUE THREAD

**Issue by mxmou** [musescore/MuseScore#12876] opened 2022-08-16 08:34 UTC
**Describe the bug**
The "applies to" option in Properties has no effect and always acts as if it was set to "Single instrument".

**To Reproduce**
1. Enter the following:
![image](https://user-images.githubusercontent.com/51849865/184834647-f0de1433-e987-4a08-b7e5-7fd3230b9527.png)
2. Set "Playback → Dynamics → Applies to" to "Staff" or "All instruments".

**Expected behavior**
If "Staff" is selected, the playback of this particular score would not be affected by the dynamic marks because the staff only contains rests. If "All instruments" is selected, both instruments would be affected.

**Platform information**
 - OS: Windows

Can reproduce in Alpha 2 and in the latest nightly.

**Comment by MarcSabatella** [comment] 2022-09-13 20:19
Confirmed - @Tantacrul this is also affecting "Reunion" (or at least, my attempts to work around other bugs affecting that score).

**Comment by Tantacrul** [comment] 2022-10-08 15:09
I actually think we should consider retiring this setting. What kind of score would use one dynamic, which applies to everything else? Choral music? Is it a jazz thing?

**Comment by Tantacrul** [comment] 2022-10-08 15:10
I'm moving to Beta 1 because we should never have a setting that does nothing.

- If we can't make the setting work, we hide it and fix it later
- Or we fix the setting so it does work
- Or we agree the setting should be retired

@bkunda / @oktophonie - thoughts?

**Comment by Tantacrul** [comment] 2022-10-08 15:38
Removing comments questioning the feature. No need for that discussion. Let's just fix the bug. :)

**Comment by Tantacrul** [comment] 2022-10-08 17:32
OK after speaking to @vpereverzev - we feel the right answer is to hide the option for now. We will need to reimplement the feature in later releases. Once that is done, we should move this issue to 4.X.

**Comment by MarcSabatella** [comment] 2022-10-08 19:43
If at all possible to make it work for the very common case of independent Rh and LH dynamics for piano, while not worrying about the less common case of a single dynamic affecting multiple instruments, that would still be useful.  Failing that, then making the velocity property for individual notes work would be that much more useful.

**Closed** 2022-10-10 14:28 UTC
Labels: P1
