### ISSUE TITLE
[MU4 Issue] No playback for snap/Bartok pizz

### ISSUE THREAD

**Issue by invisi-splat** [musescore/MuseScore#15224] opened 2022-12-16 11:32 UTC
**Describe the bug**
Notes for string instruments articulated with a snap/Bartok pizz are not played back correctly.

**To Reproduce**
1. Create score with "Violins 1".
2. Input notes.
3. Add "Snap pizzicato above" from the "Articulations" palette onto a note.

**Expected behavior**
The note with the "Snap pizzicato above" articulation to be played back with snap/Bartok pizz.

**Screenshots**
https://user-images.githubusercontent.com/48893229/208088510-ee2ce3ee-1a3d-4814-a338-801c2ddae51e.mp4

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64
 - MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Additional context**
The same occurs for all other string instruments, as far as I can tell.

**Comment by bkunda** [comment] 2024-10-21 12:25
Duplicate of https://github.com/musescore/MuseScore/issues/19051

**Closed by bkunda** 2024-10-21 12:25 UTC
