### ISSUE TITLE
Editing title header freezes Musescore

### ISSUE THREAD

**Issue by monsoma** [musescore/MuseScore#18492] opened 2023-07-09 17:47 UTC
### Issue type

Crash or freeze

### Bug description

Editing title header and press RETURN freezes Musescore. When finishing editing the title by clicking outside of the header, everything works well.

system info: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: [dbe7c6d](https://github.com/musescore/musescore/commit/dbe7c6d)

When doing the same on my Laptop, everything works well. Hitting RETURN when editing title inserts a newline.

system info (same): OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: [dbe7c6d](https://github.com/musescore/musescore/commit/dbe7c6d)

Some differences (which sometimes leads to comparably obscure problems) between the two systems - my PC has:
- AMD CPU (AMD Ryzen 5 5600G with Radeon Graphics, 3901 MHz, 6 Kern(e), 12 logische(r) Prozessor(en))
- 4K display

### Steps to reproduce

- create a new score
- choose any one instrument and click "create"
- in the new document double click in title header
- press RETURN
--> MuseScore freezes

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2023-07-09 18:05
There have been a handful of other reports of this but it seems rare and system-dependent - so far no one has figured out how to reproduce the problem.  See for instance https://github.com/musescore/MuseScore/issues/17006

**Comment by oktophonie** [comment] 2023-07-10 07:01
Duplicate of https://github.com/musescore/MuseScore/issues/17006

**Closed by oktophonie** 2023-07-10 07:01 UTC
Labels: crash, regression_ms3
