### ISSUE TITLE
[MU4 Issue] Playback is sped up/faster: tempo and pitch are doubled for two-channel playback independent of sample rate

### ISSUE THREAD

**Issue by ageneric** [musescore/MuseScore#23769] opened 2024-07-25 12:59 UTC
### Issue type

General playback bug

### Description with steps to reproduce

1. Set audio drivers to any sample rate (e.g. 44.1 kHz or 48 kHz)
2. Start MuseScore Studio
3. Open any score in MuseScore Studio
4. Play the score and listen to the beautiful sounds

Actual behaviour vs. expected:
Playback is twice as fast, so the tempo is twice as fast and pitch is doubled. Perhaps someone with working playback can check if the sounds decay twice as fast (see supporting videos).

### Supporting files, videos and screenshots

44.1 kHz:
<video src="https://github.com/user-attachments/assets/735866e6-f002-4d29-ad50-04af0ba35b05">

48 kHz:
<video src="https://github.com/user-attachments/assets/f504dd6c-6e0a-4a64-878a-f43f3a1b6dd1">

It's probably faster to write this score than download it:
[test score sound issue.zip](https://github.com/user-attachments/files/16377800/test.score.sound.issue.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 19045 (x64-based)

### Additional context

Audio driver: Cirrus Logic CS4206B (AB40). (This is the latest update my laptop supports.)

This is unlikely to be a duplicate of #17648 as the speakers are stereo and as far as I am aware Surround WASAPI is not in use. This is not a duplicate of #19931 as the issue persists regardless of whether 'Exclusive Mode' is enabled or disabled.

Experienced this issue since MuseScore 4.0.2. Not tried in 4.0.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment] 2024-07-25 13:03
@ageneric could you please attach your diagnostic files? Diagnostic -> Save diagnostic files

**Comment by RomanPudashkin** [comment] 2024-07-25 13:04
Also, please try this build:
https://github.com/musescore/MuseScore/actions/runs/9969308796/artifacts/1709471472

Is it better or worse?

**Comment by zacjansheski** [comment] 2024-08-21 20:08
Closing, no response

**Comment by ageneric** [comment] 2024-08-23 22:37
Apologies, I missed the response.

The linked build seems to have identical (double speed) "Play" mode playback, but severe stuttering on note input playback, which did not occur on previous versions for me.
https://github.com/user-attachments/assets/f60c0540-ca7c-4fac-8608-2607b0b23259

Diagnostic files for a run with MuseScore-4.3.2
[diagnostics_MU4_4.3.2_23769.zip](https://github.com/user-attachments/files/16734173/diagnostics_MU4_4.3.2_23769.zip)

Diagnostic files for a run with MuseScore-4.4.0.241990630 build as linked
[diagnostics_MU4_23769.zip](https://github.com/user-attachments/files/16734165/diagnostics_MU4_23769.zip)

**Comment by ageneric** [comment] 2024-08-23 22:49
I can confirm I still experience the same playback behaviour as described in the original issue in 4.4 Release Candidate (obtained from https://musescore.org/en/node/367322).

May I request for this issue to be re-opened? Or, please let me know if a new issue should be created.

**Comment by rienheuver** [comment] 2024-08-26 19:53
I'm running into this as well. It happens when I use MuseScore with my headset (Logitech G533) and it's fine when I switch the audio to the speakers of my display monitor (iiyama PL3467WQ). I also tried setting the bitrate to 44.1kHz but that didn't help.

Not sure if relevant: when I change the bitrate of my headset in Windows (11), Musescore won't play back at all anymore until I restart it. Please let me know if I need to add diagnostic info or whatever, I'm willing to help (and have a background in computer science, so am fine with running terminals for example).

**Comment by RomanPudashkin** [comment] 2024-08-27 07:47
>If it's still relevant, I reproduced the issue on the linked build. It's worse - it seems to have identical playback behaviour when in "Play" mode, but additionally has severe stuttering on note input playback.

@rienheuver please try to manually increase the buffer size in Preferences / Audio & MIDI

**Comment by RomanPudashkin** [comment] 2024-08-27 10:12
@ageneric after looking at your logs, I can confidently say that your issue is another case of [this one](https://github.com/musescore/MuseScore/issues/17648), but less obvious:

1. we're trying to run on 2 channels
2. but your system refuses and starts using 4 channels instead
3. MuseScore only supports 2 channels, so you get a high-pitched sound

Unfortunately, fixing this problem is not easy. But maybe we should just try to use [this workaround](https://github.com/musescore/MuseScore/issues/17648#issuecomment-1554433697) (@cbjeukendrup FYI) until we refactor the audio engine properly

**Comment by rienheuver** [comment] 2024-09-02 20:23
I just downloaded MuseScore 4.2, removed the old versions and installed 4.2 because I need to get on with a project and I can't really with this bug. But as it appears it's  broken there too. Any suggestions on what to do @RomanPudashkin ?

**Comment by las3r** [comment] 2024-09-15 14:21
I have the same issue, and everywhere Iread about it, it's people mentioning logitech. I have this when my Logitech G560 speakers are set as output. If I turn on my headset (bluetooth) or my monitor speakesr the issue dissappears. In the first builds of MU4 this issue was _not_ present.

**Comment by cbjeukendrup** [comment] 2024-09-15 17:39
I think we should close this as a duplicate of https://github.com/musescore/MuseScore/issues/17648, as it is essentially the same problem. We're planning to address that issue (at least in a temporary manner) in version 4.4.3.

**Closed by cbjeukendrup** 2024-09-15 17:39 UTC
Labels: P1, playback, regression MS3
