### ISSUE TITLE
Laissez-vibrer articulation should attach to all notes in a chord

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24698] opened 2024-09-13 16:26 UTC
### Your idea

When the laissez-vibrer articulation is attached to a chord, attach a curved line of appropriate length to each note in the chord. Whether this should continue as an articulation or as an extension of tied notes is a point for discussion.

### Problem to be solved

The current laissez-vibrer articulation in MuseScore works quite well for single notes. It works decently for single notes in multiple voices. But it does not work at all for chords. When adding the l.v. articulation(s), it should

- add an l.v. symbol on every note in every chord in every voice.
- adjust the length so that regardless of where the ties start in relation to the notehead, they all end the same place.

### Prior art

With Dorico it is a property checkbox of the note/chord.
With Finale, there are various approaches. One is an articulation or expression. I wrote a plugin that uses legacy slurs (attached to beats rather than notes) to produce excellent looking l.v. ties.
I prefer the Dorico approach, but right now their l.v. ties look bad. The MuseScore articulations look much better, if only they could be made to address the bullet points above.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-09-13 17:00
Duplicate of https://github.com/musescore/MuseScore/issues/16726

**Closed by oktophonie** 2024-09-13 17:00 UTC
Labels: feature request
