### ISSUE TITLE
[MU4 Issue] Takes a long time to open Format > Style

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14177] opened 2022-10-30 03:43 UTC
**Describe the bug**
It takes a very long time to open the Format > Style dialog.

**To Reproduce**
1. Create a new score with only one instrument (any will do) and accept all default options.
2. On the main menu, select Format > Style.
3. See how long it takes for the dialog box to show up. On my PC, which is a very decent developer box, it takes 5 seconds.
4. Also observe that CPU usage remains highly elevated for the whole duration until the dialog box appears.

The problem gets much worse for larger scores, e.g., it takes more than 1 minute for a short symphony orchestra piece.

Other actions such as selecting a measure with a mouse and entering notes using computer keyboard are also not very responsive.

**Expected behavior**
The Format > Style dialog box should open more responsively.

**Platform information**
 - OS: Windows 11

**Comment by oktophonie** [comment] 2022-10-30 07:43
I have noticed this specific problem (opening the Style dialog) on one installation (Surface Pro 7) but on other installations, both relatively high- and low-powered, it is more or less instantaneous.

**Comment by cbjeukendrup** [comment] 2022-10-30 12:39
Duplicate of #13193

Thanks for reporting!

**Closed by cbjeukendrup** 2022-10-30 12:39 UTC
