### ISSUE TITLE
[MU4 Issue] Assertion failure when entering a chord symbol in a just created/opened score (crash in debug builds)

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13602] opened 2022-10-03 21:43 UTC
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
NOTE: The crash will only occur in Debug builds, so not in any build created on GitHub Actions.
1. Create a score
2. Select the first measure rest
3. Press Cmd/Ctrl+K
4. Type "C"
5. **Press Enter** <- this specifically causes the assertion failure (if you just click on empty space to finish editing the chord symbol, it works fine)
-> Assertion failure: `(curCmd == 0), function reopen, file undo.cpp, line 475.`.

**Platform information**
 - OS: reported on macOS

**Additional context**
Might not be limited to chord symbols and newly created scores

**Comment by lyrra** [comment] 2022-10-05 09:48
duplicate of? https://github.com/musescore/MuseScore/issues/13105

**Closed** 2022-12-02 10:21 UTC
