### ISSUE TITLE
Extend "Repeat previous chord" shortcut's behaviour to not reset when adding/selecting rests

### ISSUE THREAD

**Issue by alecas93** [musescore/MuseScore#25682] opened 2024-11-29 11:04 UTC
### Your idea

While in "Insert note" mode, avoid resetting stored chord if the new insertion/selection is a rest.

### Problem to be solved

Currently, you can press "R" button to repeat previous chord while in "Insert note" mode.
This doesn't work in cases where you write a chord, then you add a rest, then you repeat last chord. (see figure)
The shortcut itself seems to do nothing in this case, so this extension shouldn't create any conflict.
![Figure](https://github.com/user-attachments/assets/0ab46d95-3707-4179-866d-8e2162bc576a)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Jojo-Schmitz** [comment] 2024-11-29 11:35
Stems from https://musescore.org/en/node/372238

**Comment by FrancRos31** [comment] 2024-11-29 12:54
I think this is a duplicate of #16644.

**Comment by Jojo-Schmitz** [comment] 2024-11-29 13:16
OOps, yes, it is

**Closed** 2024-11-30 13:30 UTC
Labels: duplicate, feature request
