### ISSUE TITLE
Adding natural to trill kills slur

### ISSUE THREAD

**Issue by bmarwell** [musescore/MuseScore#21671] opened 2024-02-24 22:55 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Setting the standard trill (just »**_tr_**« above a note) to major when the note is slurred will break the rendering in an odd way.

See screenshots

### Steps to reproduce

1. Create two eight notes
2. add a slur between them
3. add a trill
4. set the trill to anything creating an accidental

### Screenshots/Screen recordings

Standard rendering, which looks beatuful

![2024-02-24T235029_screenshot](https://github.com/musescore/MuseScore/assets/1413391/30206fee-d9df-4a25-87bd-0a8079cffb45)

When setting to "Major" to get a natural, the slur and the natural are way off.

![2024-02-24T235042_screenshot](https://github.com/musescore/MuseScore/assets/1413391/15839053-19fe-4a8c-928d-05eaef0b7dbf)

### MuseScore Version

OS: Manjaro Linux, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-, revision: github-musescore-musescore-46fe6ad

### Regression

I don't know

### Operating system

Linux (Manjaro)

**Comment by cbjeukendrup** [comment] 2024-02-25 20:34
Looks very much like a duplicate of #20170, which will be fixed in 4.3.

**Closed by cbjeukendrup** 2024-02-25 20:34 UTC
Labels: duplicate, engraving
