### ISSUE TITLE
[MU4 Issue] "Configure snap to grid" causes desktop crash, program instability and may slow down PC (Linux)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13133] opened 2022-09-02 10:43 UTC
**Describe the bug**

Pressing "Configure snap to grid" causes the Cinnamon desktop to crash, and the system may slow to a crawl, requiring a PC restart.

**To Reproduce**

1. Select some staff text, say.
2. Select "Snap to grid".
3. Click on "Configure snap to grid"

RESULT: The dialog is very slow to open, then the desktop crashes (but recovers with a dialog box allowing you to relaunch it). The program may be unusable after this, as may the PC due to a slowdown in performance.

**Expected behavior**

The dialog should open and allow trouble-free adjustment.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2976658522, revision: github-musescore-musescore-4f39fdd

**Comment by rgreen5** [comment] 2022-09-05 08:26
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2990798632, revision: github-musescore-musescore-5d26e7f

I can reproduce this reliably. The desktop may crash several times even after you relaunch it, until eventually the program crashes as well.

**Comment by RomanPudashkin** [comment] 2022-11-17 09:31
@rgreen5 could you please check it again on the last master?

**Comment by Tantacrul** [comment] 2022-11-22 17:39
I can't replicate this on MacOS. @rgreen5, is it still happening on your machine?

**Comment by oktophonie** [comment] 2022-11-22 18:27
I can replicate this still (on Linux).

**Comment by DmitryArefiev** [comment] 2022-11-23 10:45
@rgreen5 I've installed Linux Mint 21 (Cinnamon Version 5.4.12) and **can't reproduce** the crash.

Can you try Factory reset again?

**Comment by oktophonie** [comment] 2023-02-23 11:21
@rgreen5 Does this problem persist in 4.0.1? I know we addressed some similar issues prior to the MU4 release.

**Comment by rgreen5** [comment] 2023-02-23 12:52
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230540504, revision: github-musescore-musescore-78ab24f

Exactly the same problem. System freezes for a while and Cinnamon desktop crashes (requiring reload).

**Comment by Eism** [comment] 2023-07-12 09:07
@rgreen5 @oktophonie 
I can't reproduce it on my machine, so I need your help 
Do crash or freeze occur if you click 
1. on Style setting for Instrument Name or
2. on Time signature properties for Time signature?

Also please send the crash dump

**Comment by oktophonie** [comment] 2023-07-12 09:11
I can no longer reproduce this myself (either in 4.0.2 or 4.1)

**Comment by rgreen5** [comment] 2023-07-12 10:04
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231930502, revision: github-musescore-musescore-2e3a93a

No problems here either. Looks OK to close.

**Comment by Eism** [comment] 2023-07-12 10:29
Can I close this issue?

**Closed** 2023-07-12 10:30 UTC
Labels: P0, crash
