### ISSUE TITLE
[MU4 Issue] Wrong pitch in exported audio file after changing Export sample rate settings (changing settings doesn't apply properly)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14662] opened 2022-11-22 15:23 UTC
**To Reproduce**
1. Export MP3 with 44100Hz
2. Open audio file and check sound pitch
3. Export MP3 with 48000Hz
4. Open audio file and check sound pitch - **the sound pitch has changed and file properties shows 44100 instead of 48000** 

https://user-images.githubusercontent.com/90187801/203352325-4ad2d615-ac13-4cc4-bdfa-e57fa3d02d6c.mov

**Platform information**
 - macOS, Windows
 (didn't check Linux)

**Comment by Tantacrul** [comment] 2022-11-24 17:34
Is this MS Basic or Muse Sounds @DmitryArefiev ?

I fancy it's MS Basic but can't be sure.

**Comment by DmitryArefiev** [comment] 2022-11-24 19:51
@Tantacrul Yes, it's regular MS Basic

**Comment by cbjeukendrup** [comment] 2022-11-24 19:54
Actually it's not a duplicate of https://github.com/musescore/MuseScore/issues/13938 then. But probably related.

**Comment by RomanPudashkin** [comment] 2022-11-25 08:05
> But probably related.

It's not. They have different causes

**Comment by DmitryArefiev** [comment] 2022-11-28 17:53
Fixed in #14799

**Closed** 2022-11-28 17:53 UTC
Labels: P1
