### ISSUE TITLE
[MU4 Issue] On muse sounds, playing two same notes that overwrites the duration of first note delays the second note

### ISSUE THREAD

**Issue by d70040O2** [musescore/MuseScore#15916] opened 2023-01-16 14:38 UTC
**Describe the bug**
the title says it all. if there are two note that intersects each other while the first note's duration isn't finished, then it automatically delays the second note. 

**To Reproduce**
1. Place the two notes that intersects each other (see screenshots for examples.)
1-1. Changing the tempo midway the notes also can delay the second due to difference of tempos.
2. Playback, and see how notes are delayed and not being properly played on where it should be.
2-1. manipulating and abusing voice function does not solve this problem.

**Expected behavior**
it should be playing the notes on the right place, not being affected by previous note's duration.

**Screenshots**
Following screenshots are examples of "delayed notes". blue notes are ones that are problematic.

![notesoverlapping](https://user-images.githubusercontent.com/122434616/212702494-6acd25cd-1ee4-4f06-87eb-72e52284b965.PNG)

![notesoverlappingtriplet](https://user-images.githubusercontent.com/122434616/212702542-35c5d3c7-7174-4232-ae5a-1da01eb3baa1.PNG)

![notesoverlappingtriplet 2](https://user-images.githubusercontent.com/122434616/212702587-003eb99d-fd84-45d3-b5ca-9b4fe4f38b24.PNG)

**Platform information**
Os: Windows 10

**Additional context**
I think when two notes are intersecting, first note being played to full duration is set on priority, it is not a problem in soundfont (.sf2) files, as it just plays over notes being played.

**Comment by MarcSabatella** [comment] 2023-01-16 15:36
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/15306 (which is itself a duplicate of an issue that was closed when fixed for soundfont playback).

**Comment by cbjeukendrup** [comment] 2023-06-18 12:47
This is indeed a duplicate of #15306, so I'll close it.

**Closed by cbjeukendrup** 2023-06-18 12:47 UTC
