### ISSUE TITLE
[MU4 Issue] Playback of banjo's tremolo is strings' tremolo

### ISSUE THREAD

**Issue by headboy2002** [musescore/MuseScore#14608] opened 2022-11-19 04:32 UTC
**Describe the bug**
Playback of banjo's tremolo is strings' tremolo.

**To Reproduce**
1. Create a sheet with instrument Banjo.
2. Add a whole note, and add a tremolo sign on it.
3. Press "play" button.

**Expected behavior**
The playback should be banjo's tremolo, but not strings' tremolo.

**Screenshots**
![](https://s1.ax1x.com/2022/11/19/zufz1H.png)

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment] 2022-11-19 13:16
This looks like a duplicate of https://github.com/musescore/MuseScore/issues/14061, which has a fix pending in #14583. I'll close this for now, but correct me if I'm wrong :)

**Closed by cbjeukendrup** 2022-11-19 13:17 UTC
