### ISSUE TITLE
Measures with custom duration cause incorrect tempo behavior

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#24570] opened 2024-09-09 03:44 UTC
### Issue type

General playback bug

### Description with steps to reproduce

1. Create a score as per liking.
2. Set a desired tempo on one measure.
3. Set a custom duration after that measure (preferably a shorter one than the set time signature).
4. Set another different tempo on the third measure (from the initial measure; preferably a faster one).
5. See error (The second measure takes the tempo of the third measure rather than supposedly the first).

### Supporting files, videos and screenshots

Following the instructions above:

https://github.com/user-attachments/assets/cfa1a8cd-01cf-48c4-b2a0-cce8e371d76d

And with an actual example from which I found the bug:

https://github.com/user-attachments/assets/57e2311b-fc7f-4485-ac40-799503197f32

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

- The only workaround I've found with this is setting another tempo with same value as the previous one on that measure with custom duration. Otherwise, there's that.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cgpqci** [comment] 2024-09-09 03:45
Oops, I think this is supposed to be General playback bug, not UX. My bad haha

**Comment by cbjeukendrup** [comment] 2024-09-09 21:35
Another example of this is found at https://musescore.org/en/node/368293. 

Caused by https://github.com/musescore/MuseScore/pull/23656 (@mikekirin FYI)

**Comment by DmitryArefiev** [comment] 2024-09-12 10:53
Fixed in #24643

**Closed** 2024-09-12 10:53 UTC
Labels: P2, regression MS4, playback
