### ISSUE TITLE
[MU4 Issue] Playback is sped up and pitched up after installing the new RC1

### ISSUE THREAD

**Issue by AdamAViolist** [musescore/MuseScore#14921] opened 2022-12-03 21:04 UTC
**Describe the bug**
All my scores have been playing at 4x speed and pitched up two octaves since installing the new RC1. This happened to me before as well but I fixed it by uninstalling the MuseScore app shown in MuseHub. Now, I only have the RC1 installed, and the bug is happening again.

**To Reproduce**
1. Open MuseScore
2. Open any score
3. Click play or press spacebar
4. Listen to the beautiful sounds

**Expected behavior**
Should play back as normal.

**Screenshots**
Videos: https://drive.google.com/drive/folders/1QCMyEjdaEtKv0RTaxmbsyyX1NKcr-OZx?usp=sharing

**Platform information**
 - OS: Windows 11, 64-bit x64-based processor
 - CPU: 11th Gen Intel Core i7-11800H @ 2.30 GHz
 - GPU: NVIDIA GeForce RTX 3060 Laptop
 - RAM: 16 GB
 - Audio Card: Realtek
 - Audio Device: Elo 7.1 Air @ 48 kHz, 16-bit

**Additional context**
Scores shown in video: 
[Stone and Mortar SCORE Letter.zip](https://github.com/musescore/MuseScore/files/10147376/Stone.and.Mortar.SCORE.Letter.zip)
[Sonata No. 3 ORCH.zip](https://github.com/musescore/MuseScore/files/10147377/Sonata.No.3.ORCH.zip)
//Note that "Stone and Mortar SCORE Letter.mscz" shows up as corrupted, the score is fine, the parts are corrupted and I don't know how to fix it either.

**Comment by Tantacrul** [comment] 2022-12-06 13:00
This is a duplicate of https://github.com/musescore/MuseScore/issues/14921. Thanks for reporting though!

We believe the issue has been fixed. @DmitryArefiev - could you direct @AdamAViolist to the right build to confirm this?

**Closed by Tantacrul** 2022-12-06 13:00 UTC

**Comment by DmitryArefiev** [comment] 2022-12-06 14:27
> This is a duplicate of #14921. Thanks for reporting though!


@Tantacrul Sorry, what issue your mean as duplicate? (14921 it's the current issue)

**Comment by DmitryArefiev** [comment] 2022-12-06 14:28
@AdamAViolist Can you try this build please? https://github.com/musescore/MuseScore/actions/runs/3628335001

**Comment by AdamAViolist** [comment] 2022-12-06 19:25
> @AdamAViolist Can you try this build please? https://github.com/musescore/MuseScore/actions/runs/3628335001 

The issue still seems to happen for me on this build. However, it now is only twice as fast instead of 4x. :)

**Comment by AdamAViolist** [comment] 2022-12-06 19:27
@DmitryArefiev It seems to be normal on my speakers now. My headset (Roccat Elo 7.1 Air) is the only thing that still has issues.

**Comment by AdamAViolist** [comment] 2022-12-06 19:31
> @DmitryArefiev It seems to be normal on my speakers now. My headset (Roccat Elo 7.1 Air) is the only thing that still has issues.

Upon further testing, my wired headphones are now playing 1/2 speed. This won't affect me since I'll be using my headset anyway, but just wanted to point that out.

**Comment by PebProductions** [comment] 2022-12-08 16:23
Hello. I am experiencing this issue as well, but I have only ever received updates from MuseHub. I am not familiar with how to interact with builds as linked above. Is there a guide on how to install/access these?

**Comment by PebProductions** [comment] 2022-12-08 17:20
Hello. I am experiencing this problem as well, and the build did not solve the issue. I also have some additional info. While the above is true that it plays back 4 times as fast and it sounds two octaves higher, they are in fact related. It acts as if the playback is processed and then separately sped up. I twice confirmed this by taking a screen capture and slowing down the video to 0.25x speed, and by exporting a .wav of the score and speeding it up by 300%. I should clarify that this does mean that .wav exports sound as they are supposed to, as do .mp3 and .mid files. Evidence to support this also includes the in-app clock, which keeps time with what the tempo should be and is also sped up. I have included a screen cap video as well as that same video slowed down to sound as it is supposed to.

https://user-images.githubusercontent.com/120121888/206519315-64fbee97-228e-4b5f-b48e-23b1671596e3.mp4


https://user-images.githubusercontent.com/120121888/206519344-0cccf5fe-6fdf-4779-bd60-781e6e133027.mp4

**Comment by Tantacrul** [comment] 2022-12-09 13:35
> Hello. I am experiencing this problem as well, and the build did not solve the issue. I also have some additional info. While the above is true that it plays back 4 times as fast and it sounds two octaves higher, they are in fact related. It acts as if the playback is processed and then separately sped up. I twice confirmed this by taking a screen capture and slowing down the video to 0.25x speed, and by exporting a .wav of the score and speeding it up by 300%. I should clarify that this does mean that .wav exports sound as they are supposed to, as do .mp3 and .mid files. Evidence to support this also includes the in-app clock, which keeps time with what the tempo should be and is also sped up. I have included a screen cap video as well as that same video slowed down to sound as it is supposed to.
> 
>  MuseScore.4.Speeding.Up.Issue.mp4 
>  MuseScore.4.Speeding.Up.Issue.-.Slowed.Down.mp4

Would you mind raising this as a new issue. Can you specifically tell us what audio device(s) you are using as part of that? We are now going to have to firefight each issue individually. This one is closed because we largely solved it. We don't want to reopen it, which would really confuse any developer having to read through all this text.

Thanks for your investigations!

**Comment by PebProductions** [comment] 2022-12-12 16:53
I will get right on that since I have also discovered some new information.
