### ISSUE TITLE
5.1 surround mode makes playback too fast and tone too high

### ISSUE THREAD

**Issue by Pokerness** [musescore/MuseScore#22764] opened 2024-05-11 07:11 UTC
### Issue type

General playback bug

### Bug description

Since the latest releases, I can't stay in 5.1 surround mode because playback run too fast and tone is too high.
It's needed to configure the sound device in stereo mode and restart Musescore to play normaly.
Change sampling rate or buffer size parameters has no effect. 
Apparently, It wasn't needed to change son mode with previous releases.

### Steps to reproduce

Start playback

### Screenshots/Screen recordings

To change the mode of sound device :
![image](https://github.com/musescore/MuseScore/assets/63100929/39fddfda-9c9e-4d8b-b858-09315c205965)
![image](https://github.com/musescore/MuseScore/assets/63100929/1af30d7c-d18c-4bae-91fb-9cfb932a19de)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2024-05-11 15:44
Duplicate of #17648, but thanks for reporting this!

**Closed by cbjeukendrup** 2024-05-11 15:44 UTC
Labels: playback, regression_ms3

**Comment by lyrra** [comment] 2024-05-11 21:37
Possible PR fix: https://github.com/musescore/MuseScore/pull/17669

**Comment by madbrain76** [comment] 2024-05-29 05:17
I have the exact same problem with my Audiofire 8a. Everything plays insanely fast with the surround sound mode (7.1). But if I change the card to 4 x 2 channels, Musescore plays at the right tempo again.
