### ISSUE TITLE
[MU4 Issue] Portamento locks the note

### ISSUE THREAD

**Issue by RFycard** [musescore/MuseScore#14164] opened 2022-10-29 12:29 UTC
When using a Portamento (any of the palette), the note sounds at maximum volume and remains locked.
The chromatic glissando works well but produces the same problem if you change the "chromatic" parameter to "portamento".

**To Reproduce**
1. Go to 'Arpeggios and glissandi..' Palette
2. Click on one note
3. Select a Portamento
4. play the bar, the note sounds louder and remains blocked

The problem remains with the latest Nightly version I download yesterday
MuseScore 4.0.0.3342764775 Nightly
 
**Platform information**
 - OS: MacOs 12.6 with MacBook Pro M1 Pro

**Comment by Tantacrul** [comment] 2022-11-01 12:23
Can you explain what you mean by 'locked' and 'blocked'? I'm also unable to reproduce any problems with persistent dynamics.

I think we'll need clearer repro steps because I really can't figure out what the issue is from this. Closing until I get a response.

**Closed by Tantacrul** 2022-11-01 12:23 UTC

**Comment by RFycard** [comment] 2022-11-01 16:41
Hi Tantacrul
Excuse my English, I translate from French!
"Locked or Blocked" means that the note doesn't stop ringing until I stop the playback. when I remove the portamento sign, everything becomes normal

**Comment by Tantacrul** [comment] 2022-11-01 17:08
OK, that's useful. Could you also show the way it's notated (and what instrument you are trying it on)?

Or even better, can you provide a .zip of the score?
