### ISSUE TITLE
[MU4 Issue] Regression: Missing starting barline in measure following invisible measure.

### ISSUE THREAD

**Issue by SnyBr** [musescore/MuseScore#11645] opened 2022-05-15 18:38 UTC
Making a measure invisible (rightclick > Measure Properties > untick Visible) causes the next measure's starting barline to disappear, which is not the case in MuseScore 3. I'm unable to re-add the missing barline.

![image](https://user-images.githubusercontent.com/105515763/168488554-636a0ffa-6cfe-4b9a-bb86-18a82da3604a.png)

**Comment by MarcSabatella** [comment] 2022-05-16 04:11
FWIW, same with cutaway staves.  See https://musescore.org/en/node/281639.  I *believe* the story is, the barlines were also missing in older versions of MuseScore, and this was fixed 3.6, but somehow the fix never made it into MuseScore 4.  Here's what I think is PR where this was implemented: https://github.com/musescore/MuseScore/pull/6461

**Comment by SnyBr** [comment] 2022-08-05 18:07
The bug also causes clefs before barlines to disappear:
![MS3](https://user-images.githubusercontent.com/105515763/183135399-59643264-fb5c-4885-aa5c-eefc3aa1da7b.png)
![MS4](https://user-images.githubusercontent.com/105515763/183135409-e76350e0-4234-4ef2-9cca-63ac5e57ddda.png)
.

**Comment by Tantacrul** [comment] 2022-09-01 21:45
It's unclear to me exactly how much of a regression this really is but for the moment, I've popped it in Beta 1.

If the engraving team can fix it, then perhaps it'll make it into the next release. Depends on complexity of course!

**Comment by MarcSabatella** [comment] 2022-09-01 22:07
I looked over the code in the original PR that fixed this a couple of years ago for MU3 - https://github.com/musescore/MuseScore/pull/6461 - and compared to the code in master.  Oddly, it looks like *some* of the code was already merged into master, but other parts weren't.  Not sure how that happened.  Maybe some other PR that dependend on this code *did* get merged for master, and pulled some of this code along with it?  Probably makes sense to also look at https://github.com/musescore/MuseScore/pull/7196 and https://github.com/musescore/MuseScore/pull/7306, which also relate to this.

Anyhow, just a few dozen lines that were missed, and the code surrounding them doesn't seem to have changed appreciably, so in theory it would be a simple matter to reuse the code from the original fixes.  From what little I remember of this, it probably makes sense to look at all three PR's together.

**Closed** 2022-09-05 19:59 UTC
Labels: P2
