### ISSUE TITLE
MuseScore crashes when clicking Undo while still in <Part Name> 

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#22729] opened 2024-05-09 02:06 UTC
### Issue type

Crash or freeze

### Steps to reproduce

1. Go to Top menu>Add>Text>Part name.
2. While in the part name, click Undo control.
3. Musescore crashes.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/be3003fb-ddd8-4d51-817a-f17bf967bc26

### MuseScore Version

4.3

### Regression

Doesn't crash in MS3.6.2

### Operating system

Windows 10

**Comment by DmitryArefiev** [comment] 2024-05-09 11:19
I **can't reproduce** with Backspace, but **can crash** with **Undo**


https://github.com/musescore/MuseScore/assets/90187801/be3003fb-ddd8-4d51-817a-f17bf967bc26

**Comment by Violoncellotenorclef** [comment] 2024-05-09 11:41
> I **can't reproduce** with Backspace, but **can crash** with **Undo**
> 
>  bandicam.2024-05-09.14-18-41-877.mp4

Oh sorry, I meant undo :/

**Comment by DmitryArefiev** [comment] 2024-05-09 12:25
Ah, cool :) Thanks for clarification!

**Comment by DmitryArefiev** [comment] 2024-07-22 13:46
Fixed in #23675

**Closed** 2024-07-22 13:46 UTC
Labels: P1, crash, regression MS3
