### ISSUE TITLE
[MU4 Issue] Crash after using remove selected range

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9145] opened 2021-09-16 01:33 UTC
**Describe the bug**
After using "remove selected range" or "remove empty trailing measures" on a score and selecting notes/rests app crashes

**To Reproduce**
1. Create a new empty score (treble clef)
2. Select all but the first measure
4. Use Ctrl+Backspace (or Tools|Remove selected range) to delete
5. Now select the remaining rest - app will likely crash. If not, try a few other iterations of similar actions.

Alternative steps:
1. Create new empty score
2. Add a note to first measure
3. Use Tools|Remove empty trailing measures
4. Click on the note

**Expected behavior**
Not a crash

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10

**Additional context**

 	MuseScore4.exe!std::vector<Ms::MStaff *,std::allocator<Ms::MStaff *>>::operator[](const unsigned __int64 _Pos) Line 1575	C++
>	MuseScore4.exe!Ms::Measure::measureRepeatCount(int staffIdx) Line 308	C++
 	MuseScore4.exe!Ms::Measure::isMeasureRepeatGroup(int staffIdx) Line 310	C++
 	MuseScore4.exe!Ms::Measure::firstOfMeasureRepeatGroup(int staffIdx) Line 3511	C++
 	MuseScore4.exe!Ms::Measure::measureRepeatElement(int staffIdx) Line 3528	C++
 	MuseScore4.exe!Ms::MidiRenderer::renderStaffChunk(const Ms::MidiRenderer::Chunk & chunk, Ms::EventMap * events, const Ms::MidiRenderer::StaffContext & sctx) Line 1150	C++
 	MuseScore4.exe!Ms::MidiRenderer::renderChunk(const Ms::MidiRenderer::Chunk & chunk, Ms::EventMap * events, const Ms::MidiRenderer::Context & ctx) Line 2536	C++
 	MuseScore4.exe!mu::notation::MasterNotationMidiData::renderMsEvents(const unsigned int fromTick, const unsigned int toTick) Line 405	C++
 	MuseScore4.exe!mu::notation::MasterNotationMidiData::loadEvents(const unsigned int fromTick, const unsigned int toTick) Line 362	C++
 	MuseScore4.exe!mu::notation::MasterNotationMidiData::retrieveEvents(const std::vector<unsigned char,std::allocator<unsigned char>> & midiChannels, const unsigned int fromTick, const unsigned int toTick) Line 117	C++
 	MuseScore4.exe!mu::notation::MasterNotationMidiData::buildMidiStream::__l12::<lambda>(const unsigned int fromTick, const unsigned int toTick) Line 257	C++

**Comment by DmitryArefiev** [comment] 2022-01-18 11:51
Tested in latest master build (Win10, Mac12) - FIXED (no longer occurs)

Closing


@wizofaus Please reopen if you will able to reproduce it. Thanks!

**Closed** 2022-01-18 11:52 UTC

**Comment by DmitryArefiev** [comment] 2022-04-21 14:53
@Pauloolt Thank you for catching the crash! I've logged it separately #11283 because steps are different
