### ISSUE TITLE
Instrument Panel:  Parts say "not selected" and are difficult to find options (NVDA)

### ISSUE THREAD

**Issue by jmwmusic** [musescore/MuseScore#19927] opened 2023-11-04 09:06 UTC
### Issue type

UI bug

### Bug description

When arrowing down the parts list in the instrument panel a screen reader hears "Part 2 not selected".  This makes them think they need to select this somehow with space, enter etc to get to the options.  Moving with a right arrow onto those options works but is an unusual way to get there, it should really be select the part and tab to options.  However, this could be easily fixed if it announced "part 2 selected - press right arrow for options". 

### Steps to reproduce

1.  Go to instrument panel
2. Tab on to the parts list.
3. Press down arrow to hear "not selected" after each item.
4. Press tab to jump forward missing all the options.

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10 with NVDA

**Comment by bkunda** [comment] 2023-11-07 14:55
@DmitryArefiev pls check if duplicate

**Comment by DmitryArefiev** [comment] 2023-11-09 10:30
Yes, it's duplicate of #15521

**Closed** 2023-11-09 10:30 UTC
