### ISSUE TITLE
Bend not visible in articulations palette

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20012] opened 2023-11-13 15:17 UTC
### Issue type

UI bug

### Bug description

Bend does not appear in articulations palette

### Steps to reproduce

1. Search palettes
2. Type "bend"
3. The articulation palette will appear, but empty.

### Screenshots/Screen recordings

<img width="303" alt="Screenshot 2023-11-13 at 10 16 17 AM" src="https://github.com/musescore/MuseScore/assets/69917893/e96f400f-e92c-4c3b-bb0f-6425b14cb9c7">

As opposed to how it is visble in 4.1.1
<img width="153" alt="Screenshot 2023-11-13 at 10 15 59 AM" src="https://github.com/musescore/MuseScore/assets/69917893/37ff92ef-e6bf-420f-9d92-f443716518ed">

### MuseScore Version

OS: macOS 14.0, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by bkunda** [comment] 2023-11-14 14:19
I'm going to suggest we simply remove bends from the Articulations palette. 
They aren't really an articulation, and my guess as to why there is still that old palette element in the Articulations palette is because there – until recently – wasn't a "Guitar" palette to put it in.

**Comment by bkunda** [comment] 2023-11-14 14:21
Actually I just tried adding this bend using a recent dev build and it caused a crash. 
The old element should just be removed.

**Comment by DmitryArefiev** [comment] 2023-11-14 16:08
> Actually I just tried adding this bend using a recent dev build and it caused a crash.

@bkunda I can't reproduce the crash on Roman's latest build and master as well

**Comment by DmitryArefiev** [comment] 2023-11-22 16:39
Fixed in #20128

**Closed** 2023-11-22 16:38 UTC
Labels: P1, UI, regression
