### ISSUE TITLE
[MU4 Issue] Setting MIDI device in preferences breaks playback - no option for no device

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#12782] opened 2022-08-11 07:22 UTC
When a MIDI keyboard is enabled, playback does not work correctly.

1. Assign MIDI input to a device 
2. Play a score
3. Playback gets stuck at the beginning and loops the opening 1ms or so
4. Cannot choose to have no MIDI input once a device is selected.
5. Unplug the MIDI device (or disable MIDI input in playback settings cog).
6. Playback works again.
7. Plug in device and restart MuseScore (or just reenable MIDI input).
8. Playback broken again.

**Expected behavior**
Playback should play normally, even when MIDI input is accepted.

**Platform information**
 - OS: Windows
 - MU4 Alpha 11/08/2022
 - Novation Launchkey 49

**Comment by Eism** [comment] 2022-08-11 07:34
duplicate of #12594 ?
@boryskuzmenko FYI

**Comment by mccoydtromb** [comment] 2022-08-11 07:53
Sorry, didn't check for duplicates. Yup, looks the same.

**Closed** 2022-08-11 07:54 UTC
