### ISSUE TITLE
Fontlist: A-Z should scope/navigate the list, not, e.g., insert a note

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#21228] opened 2024-01-26 03:08 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1.) Add chord symbol to new score, select it, then open panel to change font
2.) Open font list
3.) Press, for example, F 

Expected behavior: select first font item starting with F
Result: An F was applied to the score

2024-01-26

### Screenshots/Screen recordings

The above steps performed on an XFCE based Linux system:

https://github.com/musescore/MuseScore/assets/7139517/07f17d28-5714-477d-b97d-be47e1104248

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

XFCE-based Linux

**Comment by XiaoMigros** [comment] 2024-01-26 05:51
Duplicate of #16508

**Closed** 2024-01-26 07:41 UTC
Labels: regression_ms3, UX/interaction
