### ISSUE TITLE
Playback does not play ties

### ISSUE THREAD

**Issue by dockalen** [musescore/MuseScore#19755] opened 2023-10-17 21:02 UTC
### Issue type

General playback bug

### Bug description

Playback is playing ties as if they are slurs. (MacOS)

### Steps to reproduce

In Note entry mode, Enter note from keyboard
select note length
hit the "T" to enter tie.

Then on playback the tied note is played separately.

### MuseScore Version

MS4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

MacOS 13.2.1

**Comment by MarcSabatella** [comment] 2023-10-17 21:05
Ties work fine ineneral, but it could be something about the samples being used for the specific passage in question.  Please ZIP and attach a score that demonstrates the problem, and be sure to  exactly which note is giving you trouble.

**Comment by dockalen** [comment] 2023-10-17 21:15
[Hero's Journey.mscz.zip](https://github.com/musescore/MuseScore/files/12960465/Hero.s.Journey.mscz.zip)
Any and all tied notes. The sounds are from pallet of instruments within MS4, not VST.

**Comment by dockalen** [comment] 2023-10-17 21:51
It seems to mostly be the distorted guitar sounds at the beginning. straight guitar later plays correctly, Flutes and Bass are correct.

**Comment by MarcSabatella** [comment] 2023-10-17 21:55
Indeed, there is a known issue specific to guitar distortion and other effects - see https://github.com/musescore/MuseScore/issues/16968

**Comment by Jojo-Schmitz** [comment] 2023-10-18 09:31
So it is a duplicate I guess

**Comment by cbjeukendrup** [comment] 2023-10-18 11:32
Yes, let's close this as a duplicate of #16968

**Closed by cbjeukendrup** 2023-10-18 11:32 UTC
Labels: playback, regression_ms3
