### ISSUE TITLE
[MU4 Issue] Crashes when splitting a rest into shorter ones

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14606] opened 2022-11-19 00:10 UTC
**Describe the bug**
MuseScore crashes when splitting a half rest into two quarter rests.

**To Reproduce**
1. Download [this score](https://musescore.com/user/55169571/scores/9017174). Its contents are show below.

![image](https://user-images.githubusercontent.com/10248807/202823040-178db7ff-a69a-4738-8d74-5619603cee53.png)

2. Click on the half rest in bar 2.
4. Press 5 on computer keyboard to split it into two quarter rests.
5. Observe that MuseScore crashes, terminates itself immediately.

These steps reproduce the bug 100% of the time on my computer.

**Expected behavior**
MuseScore should split the rest without crashing.

**Platform information**
 - OS: Windows 11
 - Build: MuseScoreNightly-223220403-master-fd02c8d-x86_64

**Comment by oktophonie** [comment] 2022-11-21 14:26
Duplicate of https://github.com/musescore/MuseScore/issues/14200 (but we'll use this example file as a test to confirm any fix)

**Closed** 2022-11-21 14:26 UTC
