### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by UnaidedButton86** [musescore/MuseScore#11768] opened 2022-05-26 14:39 UTC
I've seen a few workarounds and multiple more issues, but I'm writing more tomorrow.

I tried making a little song in ms4 alpha and those things i directly noticed and were really annoying (if im wrong and these just moved, please tell me):
**Advanced workspace**
~~This is a must-have for me: I use a double augmentation dot very much (sometimes even triple) and that isnt in the toolbar. Also voice 3 & 4 aren't there, but the shortcuts for those still exist.~~
Edit: I saw all the options of the workspace and it's amazing! Customizing everything was one of the nice things! Only it's nice to have options "Advanced workspace", "Basic workspace" as standard. And with these come "Reset workspace"

**Musescore 3 import**
This is an image from a little bit of Musescore 3 imported into Musescore 4 (little part of a piece)
![image](https://user-images.githubusercontent.com/87303800/170501692-9e8a6723-672e-48e3-a1f4-10c73afcd9c9.png)
And this is the original (don't mind the last 3 chords, i accidentally put them away on the last one)
![image](https://user-images.githubusercontent.com/87303800/170502561-08735582-6ec0-4a8e-bc6d-5cbe0e14df02.png)

Problems I've already noticed:
- Cross staff notation messed up: The lines are starting from above/under the measure. There's a workaround by stretching every line. 

~~- Spread out very much: With some staves the notes are very much spread out. On Musescore 3 i am sometimes already 15 mins busy with all options of getting measures on 1 stave, but here it's all reset or the minimum is even higher! I think a great solution (that many people want already) is force into 1 measure.~~
Edit: I saw that the options just werent saved for the other program. Maybe fix this.

**Comment by HemantAntony** [comment] 2022-05-26 14:42
Please give the issue a better title (preferably in the form of '[MU4 Issue] ...' for consistency). Also one problem per one issue (in case you didn't know). It helps the team organize, fix

**Comment by UnaidedButton86** [comment] 2022-05-26 14:48
> Please give the issue a better title (preferably in the form of '[MU4 Issue] ...' for consistency). Also one problem per one issue (in case you didn't know). It helps the team organize, fix better :)
> 
> Also see #11057 for the advanced workspace issue

Im trying to give a better title per issue tommorow (its getting late), but what do you mea

**Comment by HemantAntony** [comment] 2022-05-26 14:52
I meant bugs. There are two problems in this issue- One with the Advanced Workspace and the other about the MuseScore3 import. They should be two separate issues.

But you should read #11057. It deals with the same problem about the Advanced Workspace

**Comment by cbjeukendrup** [comment] 2022-05-26 15:03
Regarding the file imported from MuseScore 3: the good news is that there has already been a lot of improvement since the first alpha release. If you want, you can try the latest "nightly build" from https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D, to see if the problem is indeed solved.

**Comment by Tantacrul** [comment] 2022-05-26 17:24
I'm going to close this since the issue has been raised based on the alpha version (which we have since improved a lot).

I'd advise you to check @cbjeukendrup's link: then import the same MS3 score again and show us any problems you find. We'll then assign accordingly.

**Closed** 2022-05-26 17:25 UTC
