### ISSUE TITLE
[Inspector] Unable to change stem direction in Properties after applying flip direction with X from keyboard to the group of notes

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9779] opened 2021-11-18 11:53 UTC
Unable to change stem direction in Properties after applying flip direction command with X from keyboard

https://user-images.githubusercontent.com/90187801/142410623-cb10c5eb-3e5b-4505-8629-d52da1935d46.mp4

**Desktop:**
Win10/Mac12/LinuxMint20

**Additional context**
Occurs in **MU3** as well

**Comment by Jojo-Schmitz** [comment] 2021-11-18 11:57
Isn't that a duplicate of #9650 and such fixed along with #9774?

**Comment by DmitryArefiev** [comment] 2021-11-18 12:31
> 
> 
> Isn't that a (more or less) duplicate of #9650 and such fixed along with #9774?

Don't think so. The steps are different and not fixed with #9774.
The current issue is about how flip command (from keyboard) locks stem direction from editing from Properties even if applied only to the first note of group

**Comment by Jojo-Schmitz** [comment] 2021-11-18 12:32
OK, I see

**Comment by LovCAPONE** [comment] 2021-11-18 20:19
Since this issue isn't assigned to anyone I'll fix it and make a PR.

**Closed** 2021-11-20 08:31 UTC
Labels: P3

**Comment by DmitryArefiev** [comment] 2021-11-20 14:26
Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED

Thanks!
