### ISSUE TITLE
Multi-measure repeats do not play back properly

### ISSUE THREAD

**Issue by eduardo-svg** [musescore/MuseScore#16634] opened 2023-03-03 01:20 UTC
### Issue type

General playback bug

### Bug description

Multi-measure repeats only play back the one previous measure, not the correct number of measures before.

2-measure repeats play back the one previous measure over their first measure.
4-measure repeats play back the one previous measure over their second measure.

This occurs both with MuseSounds and MS Basic. I am not able to test VSTs.

### Steps to reproduce

1. Insert a multi-measure repeat
2. Play back the written music; only one measure will repeat, and it is always the single measure previous to the repeat.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/59342442/222607322-76ffd560-7183-43fd-a4ea-a2180b80ba75.mov

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

macOS 13.1

**Comment by cbjeukendrup** [comment] 2023-03-03 07:08
Duplicate of #10922. Thanks for reporting!


> Yes, this used to work in Musescore 3.x and now is broken

I believe in MS3, multi-measure repeats did not exist yet, did they?

**Closed by cbjeukendrup** 2023-03-03 07:08 UTC
Labels: regression, playback

**Comment by Jojo-Schmitz** [comment] 2023-03-03 10:44
No, thed indeed didn't exist in Mu3, so not a regression.
Well, maybe a regression vs. an earlier development build, as they did work at some point

**Comment by eduardo-svg** [comment] 2023-03-03 17:19
My mistake–it was not implemented in 3.x, thank you all.
