### ISSUE TITLE
[MU4 Issue] Excessive timelag between key-press and instrument sound in "preview mode"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14911] opened 2022-12-03 11:58 UTC
**Describe the bug**

If you click on a music staff you can play an instrument from a MIDI keyboard or the on-screeen piano. However, there is a significant timelag in MS4 between keypress and sound, compared to the immediate responsiveness of MS3 (under ALSA) – at least on this Linux MInt setup.

**To Reproduce**

1. Connect a MIDI instrument before opening MS3.
2. Create a drumkit score, say.
3. Click on the staff in normal mode.
4. Play a simple rhythm using a bass drum and snare for example..

RESULT: The timelag between keypress and sound is virtually imperceptible.

5. Now open the same score in MS4 and repeat steps 3 and 4.

RESULT: There is a significant soundlag between pressing the keys and hearing them. In effect this defeats the purpose of the preview facility, and stops the user being able to use it to try out new ideas etc. This also applies to the on-screen piano.

**Expected behavior**

The timelag should be virtually imperceptible, as it was in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223370506, revision: github-musescore-musescore-d050fb0

**Comment by Tantacrul** [comment] 2022-12-06 13:06
Duplicate of https://github.com/musescore/MuseScore/issues/14942

Thanks for loggging!

**Closed by Tantacrul** 2022-12-06 13:06 UTC
