### ISSUE TITLE
[MU4 Issue] Num pad not responding for duration selection

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#12791] opened 2022-08-11 11:29 UTC
**Describe the bug**
Using num pad no longer works for selecting durations. I have checked Num Lock (makes numpad into arrows which navigate around buttons or notes). The problem started after I had been experimenting with using MuseScore with a MIDI keyboard. To remove the MIDI keyboard from the input slot I also clicked "Reset Preferences", so it may be due to that.
I tried re-adding the numbers as shortcuts, but that didn't do it.
Interesting point is that the numpad dot still selects dotted note, and + for ties and / for acciaccaturas still work.

I can only guess that Reset Preferences does this, but haven't been able to test from a starting point again.

**Expected behavior**
Use num pad numbers same as number row to select durations

**Platform information**
 - OS: Windows 10
 - MuseScore 4 Alpha

**Comment by HemantAntony** [comment] 2022-08-11 11:31
I forgot. Did you try reset to factory settings. You can find that in the Help menu

**Comment by mccoydtromb** [comment] 2022-08-11 13:04
Great idea. Just tried it, still no joy. Reinstall also didn't change anything.

**Comment by critchie** [comment] 2022-08-11 13:15
I noticed this a while back. For the Num Pad to work the shortcut must register as NumPad. For example, “Num+4”, and not just “4”. The shortcuts dialog is not picking up this distinction when editing the shortcut. As a work around I exported the shortcuts and manually added the NumPad shortcuts in the proper places and then imported them back into MuseScore. It worked but this is definitely not a long term solution and can be dangerous as it by passes the applications validations.

Here is my thread on the MuseScore forum:
https://musescore.org/en/node/333674

**Comment by henkdegroot** [comment] 2022-08-11 15:37
Interesting, as in MS3 and MS4 the shortcut definition seems to be similar for these keys:

MS3:
![image](https://user-images.githubusercontent.com/13550012/184172069-44a5f618-db77-4c35-80b1-141abd68309a.png)

MS4:
![image](https://user-images.githubusercontent.com/13550012/184172378-b0fa7c3b-9845-4e7e-86b7-6b5a8cd05ac7.png)

Obvious note the slight different on the NumPad text in MS3 vs Num in MS4.
However it does seem the "NumPad" keys are assigned to other functions, but still in MS3 they can be used to select the duration. Would definitely like this functionality to be standard in MS4.

**Comment by critchie** [comment] 2022-08-11 15:56
Yeah… clearly something is different between the two versions. When I export the shortcuts and edit the XML to this:

`
<SC>
    <key>pad-note-8</key>
    <seq>4</seq>
    <seq>Num+4</seq>
</SC>
`
Then import it back in the NumPad works.

**Comment by henkdegroot** [comment] 2022-08-11 17:44
Well you should not have to define any shortcut. For a regular staff, the "keyboard" numbers and "numpad" numbers should be treated as the same key. If it was not required in MS3, then it should be possible to get the same behaviour in MS4.

**Comment by MarcSabatella** [comment] 2022-08-11 17:51
It was always very system-dependent in MU3 - worked out of the box on some systems, not on others.  of the one where it didn't work out of the box, some could be fixed by manually setting the shortcut, others were not so lucky.  Seems the same situation exists in MU4 except for the specifics of which systems are in which category.  Not sure it's even technically possible to get it to always work correctly out of the box for all systems - different OS's, different keyboard layouts, different language settings, different device drivers, etc.  But it's reasonable to hope that manually setting the shortcut will work "almost always".

**Comment by henkdegroot** [comment] 2022-08-11 17:59
Understand what you are saying, but that does not explain the different behaviour between MS3 and MS4 on the SAME laptop and thus using the same OS. It might just be something missed when transferring the code to the new MS4 structure (at least that is my guess).

However, as mentioned by @critchie manual setting the "numpad" key in shortcuts is not even possible.

**Comment by MarcSabatella** [comment] 2022-08-11 18:07
Different versions of Qt, different ways of processing that input within MuseScore - I'm sure that explains the difference.  I believe others have said they *can* set the numpad via the dialog, which is why it seems to me the situation is the same as MU3 - works on some systems, not on others.  Maybe I imagined that?  Anyhow, I don't have a numpad available to test with.  I just want to add some clarifying info that this was *always* a problem in MU3 on some systems.

**Comment by critchie** [comment] 2022-08-11 18:27
It seems to me the issue is in the Edit Shortcut dialog. When I press 4 on the NumPad, MuseScore must enter Num+4 and not just 4. It needs to look at the key event and use the proper key value from the Key enum. It has to distinguish between NumPad4 and D4.

When I edit the exported XML and manually add the Num+4 MuseScore handles the shortcuts properly. If I hit the NumPad 4 or the keyboard 4 the duration changes to an eighth note. So the application reacts properly once the shortcut is setup.

**Comment by mccoydtromb** [comment] 2022-08-11 18:39
Interesting, because I've been using the Numpad for all my testing of nightlies, but suddenly not happening in the alpha.

**Comment by Roman251** [comment] 2022-08-12 09:24
I have the same problem. A piece of information that may be irrelevant: when I try to add new shortcut and try to use (for testing) Ctrl + Numpad keys it shows in MU4 as "Ctrl+Pause". That being said, it has the same behavior in MU3 and numpad works correctly there (Win 10)

**Comment by daeavelwyn** [comment] 2022-08-14 12:05
Hi guys,

Same issue here with MuseSCore 4 (OS: Windows 10 Version 1809, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2844400529, revision: github-musescore-musescore-abc123456)

Neither default shorcut nor manually change shortcuts work on my side.

**Comment by sikamber** [comment] 2022-09-02 19:27
I have the same issue (in alpha 2, just downloaded). I am not able to fix it in the dialogue (when I press "4" on the numpad, it just sets the shortcut to "4", but when working in the score, pressing "4" on the numpad does not trigger the shortcut).

So it seems that at least for me, the shortcut menu and the main program interprets the same keypress in two different ways. I am using a logitec "LogiLink" external keypad with default windows drivers, if that matters.

Exporting the shortcut file and manually editing it (like Critchie described) worked.

**Comment by sammik** [comment] 2022-09-07 16:18
For me numpad works (latest nightly OS: Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2990798632, revision: github-musescore-musescore-5d26e7f)

**Comment by daeavelwyn** [comment] 2022-09-07 23:55
Hi folks,

I first removed all my previous preferences (documents, appdata in local and roaming)

I just tested once more with OS: Windows 10 Version 1809, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3005078110, revision: github-musescore-musescore-abc123456 and got the same issue. French AZERTY keyboard

The numpad just doesn't work and the numbers on the alphanumeric part of the keyboard work (shift + number) except the number 6...). I also tried ctrl+number and it seems to work except for the 6.... So I tried with another keyboard but got the same result.

I've tried to remove 'kind of' dupplicate entries I found in the default shortcut map (example : 6 is use also for tab) but it still doesn't work.

Any tests I could do to help solving this ?

**Comment by napochanIsMe** [comment] 2022-11-17 01:38
I see similar problems with MU4-alpha2 with ties not working as in MU3 and with shortcuts, both as downloaded and after attempting to edit the shortcuts. I tried editing in the app and offline with an XML editor and neither approach worked. Clicking the tie command in the tool bar works as expected.
System info: Win11, v10.0.22621, 64-bit

**Comment by MarcSabatella** [comment] 2022-11-17 02:45
The tie command has changed to “T” :/)

**Comment by napochanIsMe** [comment] 2022-11-17 22:04
> The tie command has changed to “T” :-)

Thanks Marc. I just need some retraining to learn the new shortcut!

**Comment by trevorspecht** [comment] 2022-12-18 02:16
Using a Mac and Apple computer keyboard, I too am not able to use the numeric keypad to enter note durations. Even if I go to settings/shortcuts and use the keypad to alter the shortcut for a note duration, it still won't recognize the keypad for note durations, only the number row across the top of the keyboard.

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by trevorspecht** [comment] 2022-12-18 02:44
As mentioned before, exporting the shortcuts as an XML file and editing it, then importing it back, will fix the problem if you do it as in the example screenshot below (screenshot doesn't show all the keypad numbers, but is a good enough example)

Export and Import are right here:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/29611310/208278812-2eae83ef-4b09-4f35-b92b-cea3980a45ff.png">


<img width="342" alt="Screen Shot 2022-12-17 at 9 40 18 PM" src="https://user-images.githubusercontent.com/29611310/208278789-f585183e-f366-4690-8e5f-051da75d48dd.png">

**Comment by KatrinaHahn1** [comment] 2022-12-18 09:00
ah, now I see where the problem lies. The numpad only works for me if I am entering note values in the TAB staff. But I do not understand the logic behind some numpads working and some not (unless a guitar tab is being used.).

**Comment by daeavelwyn** [comment] 2022-12-18 19:44
Hello folks,

I just installed the first stable release of musescore 4 and the problem still remains. And I'm now using a new laptop (lenovo t460) still using windows 10 enterprise 1809. 

To reproduce :
-Create a simple score with, for example a flute staff
-Enter the input mode (using N shortcut)
-I can change rhythm values with number from 1 to 5 with my azerty laptop keyboard. The number 7 also works.
BUT the number 6 doesn't work....

i tried the suggested workaround in previous post but it doesn't work.  Any ideas ?

**Comment by DonW-Music** [comment] 2022-12-21 15:03
Please don't forget about Mac users!

Numpad not working to set note duration on wired extended Apple Mac keyboard.

Using production MuseScore 4 that I downloaded directly from the webpage.

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621


Mac OS: 12.6.1
Mac Mini (mid 2018)
3.0 Ghz 6 Core Intel i5
32 G RAM

**Comment by ivanobom** [comment] 2023-01-07 16:17
I just downloaded the official stable release from musescor.org website and I can confirm that the problem still persists. It is much easer to type notes and pauses durations using numpad, so while this issue is not solved, I'll have to keep using Musescore 3. I really hope this problem to be solved soon.
Thanks

**Comment by MarcSabatella** [comment] 2023-01-07 17:26
The problem seems to affect some numpads but not others, meanwhile there is a very simple workaround.  Just download  [this file](https://musescore.org/sites/musescore.org/files/2022-12/musescore_shortcuts_edited_0.xml) then go to Edit / Preferences / Shortucts, hit the Import button, and open the file you downloaded.

**Comment by mccoydtromb** [comment] 2023-01-07 17:33
There's a fairly easy workaround that was passed on by Marc Sabatella,
involving importing an xml file for shortcuts. Would be good to have that
link on this discussion for everyone who finds it until the fix arrives.

**Comment by daeavelwyn** [comment] 2023-01-07 19:59
@MarcSabatella and @mccoydtromb thanks for your reply but this workaround doesn't work for my problem.

That's a very strange issue as many other software use keyboard shortcuts without facing the problem mentioned in this thread, so maybe it would be possible for devs to look around open sources projects they don't have such an issue ?

**Comment by MarcSabatella** [comment] 2023-01-07 22:04
The fact that this method doesn’t work for you when it does for almost everyone else - and the fact that not everyone has this problem in the first place - demonstrates that it just isn’t that simple.  There are tons of different keyboard designs out there, and it’s a mistake to assume that some other program works with literally every single keyboard.  But indeed, it’s possible to do better than we currently do.

**Comment by daeavelwyn** [comment] 2023-01-08 13:46
@MarcSabatella Sorry my previous post wasn't clear, I wanted to say your xml solution works for the keypad, but I still can"t assign my "6" number from the alphanumeric keyboard to be recognized, BUT it works for other numbers. I've tried with 2 other keyboards (still AZERTY so it may be the problem source). So thank you for your workarround about the keypad but I just still wanted to point that keyboard assignation/learn doesn't work for my specific problem.

**Comment by MarcSabatella** [comment] 2023-01-08 14:13
I think issues with being keys *other* than the numpad on AZERTY, and in particular, with being able to *assign* keys, are not related to this issue.  But perhaps you are seeing the effects of a separate issue - either https://github.com/musescore/MuseScore/issues/15204 and/or https://github.com/musescore/MuseScore/issues/14539

**Comment by Eism** [comment] 2023-01-10 15:05
Actually, I don't see the difference between, for example, pad-note-8 and pad-note-8-TAB in the code. Both shortcuts call padNote method.

So can we do the following
1. remove all pad-note-N-TAB from the shortcuts file
2. treat number input and NumPad+number as equivalent

Did I understand the problem correctly?

**Comment by henkdegroot** [comment] 2023-01-10 18:28
Not a developer, so just replying from a user perspective here.

I believe the pad-note-8-TAB entry is triggered when using the numbers while working with a Tablature staff. As numbers in this case are selecting a fret mark. Whille SHIFT+number selects the Note Duration. At the same time, pressing the number in the NumPad section of the keyboard is also selecting the note duration.

While in a non-Tablature staff, the pad-note-8 entry is triggered and in this case a number (either being in the located in the NumPad section or at the top keyboard row) selects the note duration.

So if your point 1 correct, I don't know. Point 2 would depend on the staff type.

@MarcSabatella, as you also have developer experience, can you share your input please?

**Comment by MarcSabatella** [comment] 2023-01-10 18:46
I have development experience yes, but relatively limited experience with tablature, and none of my keyboard have numpads, nor do I know much about the internals of how keyboard processing works in MU4.  So I'm not sure there is anything meaningful I could contribute here.

**Comment by cbjeukendrup** [comment] 2023-01-10 22:54
What Henk said matches exactly my understanding. On TAB staves, the number keys are already used for entering free numbers, so users will need to set a different shortcut for duration selection while entering notes on TAB staves. 
Because of this, there are two actions that call the same code, but their "shortcut context" is different, so that the shortcut for the TAB variant will only work on TAB staves, and the shortcut for the normal variant can be used otherwise.

**Comment by shoogle** [comment] 2023-01-11 00:45
@cbjeukendrup, ah yes, you're right. It's specifically in _note input mode_ on a tab staff, the number keys are used to enter fret numbers, so then shift+number is used to change to a different duration instead of just the number keys, hence the need for "Set duration" and "Set duration (TAB)" actions.

**Comment by Eism** [comment] 2023-01-11 11:04
Okay, let's apply the solution that Marc suggests for now.
The solution I suggested doesn't work for Tabulature staff and needs a lot of changes.

**Comment by Eism** [comment] 2023-01-11 11:51
Could somebody test the build from this PR https://github.com/musescore/MuseScore/pull/15819?

(need first reset the preferences if you changed the shortcuts file)

**Comment by MarcSabatella** [comment] 2023-01-11 17:10
FWIW, I'm not sure what I actually suggested :-), but I gather the solution being pursued is to hard-code the duplicates into the defaults file, which is fine.

However, I *do* have an additional suggestion to consider.  I know it's a controversial topic as to whether MuseScore should allow end users to define multiple shortcuts for the same command.  Without revisiting that, I would like to point out that it is reasonable to expect one could redefine "0" or Enter or whatever to be the shortcut for some command, and have that *automatically* apply to both versions of these keys.  After all, we don't have to separately specify LeftCtrl+K and RightCtrl+K as separate shortcuts for chord symbols, it just works.  The fact that 0 and Numpad0 are seen as different keys internally probably doesn't matter to the average user - they likely expect them to always behave identically.  At least, that's what I might naively think as someone who hasn't used a keyboard with a numpad in years.

So, what if we added code to detect an attempt to assign one, and then just automatically went ahead and assigned the other as well?

**Comment by MarcSabatella** [comment] 2023-01-11 20:27
That sounds logical to me, although again, not having used a numpad in many years, I don't have a good sense of what users expect.  I'm just happy to see this being addressed, as it's easily the #1 problem reported most often by users.

**Closed** 2023-01-12 12:21 UTC
Labels: P1

**Comment by Lumi618** [comment] 2023-01-17 00:10
I just updated to 4.0.1, and I still can't use the numpad to select note durations. I have made sure that num lock is on, and looked in the preferences to change the note duration definitions, but still cannot get them to work. Is there something else I need to do to fix this?

**Comment by MarcSabatella** [comment] 2023-01-17 01:48
@Lumi618 you will need to reset your shortcuts, either in edit / preferences / shortcuts, or via help / revert to factor settings.

**Comment by scorster** [comment] 2024-11-05 23:28
This appears to have reared its head again in MS 4.4.3, though AFAIK  it's only been reported and confirmed on MacOS

https://musescore.org/en/node/371297#comment-1266682
