### ISSUE TITLE
Crashes when opening a specific score 

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25708] opened 2024-12-03 14:46 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

Try to open this score (attached below). 
In earlier versions of MuseScore Studio, it opened, and now the program crashes when you try to open it.

Unfortunately, I can't determine the reasons why the crash is happening.

### Supporting files, videos and screenshots

[crash after open.zip](https://github.com/user-attachments/files/17994638/crash.after.open.zip)

[logs.zip](https://github.com/user-attachments/files/17994738/logs.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

Yes, this used to work in ****MuseScore** 4.0.0**

### Operating system

Windows 11

### Additional context

It may be necessary to rename this issue in the future when the cause of the crash becomes known (if at all).

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-12-03 14:55
It seems to be a 4.4.1 regression, 4.4.0 doesn't crash

**Comment by DmitryArefiev** [comment] 2024-12-03 17:02
Tested on Win10.  Interesting crash..
The initial score **crashes** in **4.4.1-4.5**
I switched the score to **Page View** orientation 
[Life (PAGE VIEW) is a Highway (Rascal Flatts).zip](https://github.com/user-attachments/files/17996458/Life.PAGE.VIEW.is.a.Highway.Rascal.Flatts.zip) and now it **doesn't crash** in **4.4.2-4.5** (but **crashes in 4.4.1**)

**Comment by Dima-S-Jr** [comment] 2024-12-03 17:14
> Tested on Win10. Interesting crash.. The initial score **crashes** in **4.4.1-4.5** I switched the score to **Page View** [Life (PAGE VIEW) is a Highway (Rascal Flatts).zip](https://github.com/user-attachments/files/17996458/Life.PAGE.VIEW.is.a.Highway.Rascal.Flatts.zip) and now it **doesn't crash** in **4.4.2-4.5** (but **crashes in 4.4.1**)

Apparently, it's not about continuous viewing there. I just opened the score from your file. Look what happened after I started scrolling to the right:

Uploading Video_241203201139.mp4…

**Comment by Jojo-Schmitz** [comment] 2024-12-03 17:19
So it crashes on trying to render a certain page?

**Comment by DmitryArefiev** [comment] 2024-12-04 13:02
Fixed in #25726

**Closed** 2024-12-04 13:03 UTC
Labels: regression MS4, crash
