### ISSUE TITLE
[MU4 Issue] Extra notes heard on playback when MS3 is open at same time

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12312] opened 2022-07-08 10:03 UTC
**Describe the bug**
_A very new bug_ (AFAIK). If you try to play back a score in MS4, _and_ there is any score open in MS3 at the same time, spurious extra notes are heard during playback.

**To Reproduce**

1. Open "ms3_file.mscz" in MS3. Open "ms4_file_for_playback.mscz" in MS4. 
[ms_files.zip](https://github.com/musescore/MuseScore/files/9070976/ms_files.zip)
2. Now playback the MS4 file, set to repeat.
RESULT: You may hear spurious extra notes in the playback.
3. If you don't hear this effect try selecting a measure in MS3. 

**Expected behavior**

If both programs are open at the same time, playback should be independent, and there should definately not be any spurious playback effects.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2633864232, revision: github-musescore-musescore-1f88df6

**Comment by cbjeukendrup** [comment] 2022-07-08 12:39
Also, I think it's questionable whether MIDI events for the Fluid Synth should be sent to the MIDI output port too. I must say that doesn't make a lot of sense to me. At least it is inconsistent to send them only for Fluid and not for VST. 
(See commit https://github.com/musescore/MuseScore/pull/12027/commits/fea5db2b10a98e30c7b6002165e15ef2cba24743)

@vpereverzev What is the reason that we do this?

**Comment by cbjeukendrup** [comment] 2022-07-08 15:54
Small update on this: if MU3 is also playing notes that you don't see on the score, those notes come from the metronome. Even when the metronome is muted, its events are processed by FluidSynth, and thus sent to MIDI output. So that's fortunately has a logical explanation.

I also noticed that not all "note off" events are properly sent to MIDI out (or they are not received by the receiving port...), which results in infinite notes not in MuseScore but in the receiving device.

**Comment by Tantacrul** [comment] 2022-07-08 16:01
Would that second one be a possible explanation for the horrendous 'eternal sustain' problem I sometimes encounter? If so, we should isolate it as a task and tackle it as a top priority.

**Comment by cbjeukendrup** [comment] 2022-07-08 17:46
@Tantacrul It might be, but to say something sensible I'd need to know better in what circumstances that problem occurs. 

Anyway, in this case, the cause is the following: when stopping playback, a special "all notes off" signal is sent to Fluid, but this is _not_ sent to the MIDI output, so the MIDI device will never be notified to stop the notes that were playing at the moment that the user pressed "stop".

**Comment by cbjeukendrup** [comment] 2023-02-18 22:06
@rgreen5 Is this still actual? If so, any comments on what I said above (about potential MIDI loops on your system)?

**Comment by rgreen5** [comment] 2023-02-19 10:58
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230500504, revision: github-musescore-musescore-8c85e6c

When I repeat the steps to reproduce in the OP I get absolutely no playback of the notes in MS4 whatsoever. Only the chord symbols sound.

**Comment by cbjeukendrup** [comment] 2023-02-19 13:09
That is because this file is so old that it still has the `MuseScore_General` SoundFont selected, but that doesn't exist anymore because it has been renamed to MS Basic. If you select MS Basic in the Mixer, is should work again.

**Comment by rgreen5** [comment] 2023-02-19 14:46
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230500504, revision: github-musescore-musescore-8c85e6c

Ok, got it. No problems to report. Sounds fixed.

**Comment by cbjeukendrup** [comment] 2023-02-20 11:36
Thanks for checking! I'll close it then.

**Closed by cbjeukendrup** 2023-02-20 11:36 UTC
Labels: P3
