### ISSUE TITLE
Hairpin dynamics

### ISSUE THREAD

**Issue by brandonbrookspercussion** [musescore/MuseScore#20194] opened 2023-11-25 23:10 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Hairpin dynamics are not carrying over to parts from the score. This is an issue I ran into with the previous version of MuseScore as well.

Attempted corruption repair. No corruption found. 

### Steps to reproduce

The only real steps to reproduce this are completion of score note entry. Next add dynamics and hairpin dynamics.

Hairpins don’t carry over to any parts from the score. If I delete the hairpin dynamic from the score and re-enter it, it will show up on the part.

In doing this, I have to go through and individually delete every single hairpin dynamic, and then re-enter them.

### MuseScore Version

4.1.1.232071203

### Regression

No.

### Operating system

macOS Sonoma 14.1.1

### Additional context

Using MuseSounds mostly.

**Comment by cbjeukendrup** [comment] 2023-11-25 23:20
This is another case of #19852 and #20086, which are really frustrating issues because judging from the number of reports they occur quite often but literally nobody has any usable clue about how to reproduce the problem deterministically, which means that it is impossible to fix it. 

I will close this version of the issue as a duplicate, because one open issue per problem is enough.
However, it might still be useful if you could upload the score where this happened. The score file will most likely not tell us _why_ the hairpins have disappeared, so won't directly help us solving the problem; but I thought if we collect many scores where this problem has occurred, we might spot a pattern, which might lead to a way to reproduce the problem. Thanks in advance!

**Closed by cbjeukendrup** 2023-11-25 23:20 UTC
Labels: engraving

**Comment by brandonbrookspercussion** [comment] 2023-12-05 00:39
Where should I upload the score? 

I am also trying to upload a different score pertaining to a new (yet an old issues in MS3). The mscz file won't upload.

**Comment by cbjeukendrup** [comment] 2023-12-05 00:41
To upload the score, you can rename the file by adding `.zip` at the end (so after the `.mscz`), and then GitHub will accept it.
