### ISSUE TITLE
Musescore 4: Corrupted Score Issue

### ISSUE THREAD

**Issue by kkslider9999** [musescore/MuseScore#16826] opened 2023-03-14 21:18 UTC
There is a corruption issue on the score and I don't know what is wrong with the measures specified (23-24 in staff 3).

[College Best Friends Forever - Guitar - Copy.zip](https://github.com/musescore/MuseScore/files/10973778/College.Best.Friends.Forever.-.Guitar.-.Copy.zip)

**Comment by MarcSabatella** [comment] 2023-03-14 21:22
See this article for suggestions https://musescore.org/en/node/54721 - and if you need further assistance, please use the Support forum.  But if you ever figure out what steps led to this corruption, that would be good information to report here in the issue tracker on GitHub.

**Comment by kkslider9999** [comment] 2023-03-14 21:57
Figured it out, and it was resolved by copying, deleting, then readding/pasting the measure contents. Thanks!

**Comment by cbjeukendrup** [comment] 2023-03-16 21:19
Closing, since it was resolved for this score and without further information it isn't really actionable for us. However, judging from the content of the score file, it is likely that it has been caused by https://github.com/musescore/MuseScore/issues/15844, which has been fixed in 4.0.2, so if you have installed the update it shouldn't happen again.

**Closed by cbjeukendrup** 2023-03-16 21:19 UTC
