### ISSUE TITLE
Disabling 'show barlines' leads to measures of incorrect width

### ISSUE THREAD

**Issue by vallieplushie** [musescore/MuseScore#24058] opened 2024-08-15 19:55 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Make a new score with a piano
2. Right-click treble staff > Staff Properties, and disable 'Show barlines'
3. Already, you can see weird emptiness at the end of the system
4. Add a fixed stave spacer, and just change the distance between the staves. Eventually you end up with a zero-width bar

This *can* be undone by re-enabling 'show barlines', but it is a bizarre bug.

### Supporting files, videos and screenshots

Extra space at end of system after disabling 'Show barlines'
<img width="1822" alt="Screenshot 2024-08-15 at 20 48 46" src="https://github.com/user-attachments/assets/44decc20-6194-4b5b-87eb-ade0c7ae93e6">

The odd behaviour of the stave spacer:
https://github.com/user-attachments/assets/ef26abd4-0c62-4c25-9488-fd748825eba7

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.2, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

MacOS 14.2

### Additional context

Practically, it's not hugely critical, since barlines can be manually hidden. However, this is very odd behaviour that probably needs to be fixed at some point.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-08-15 20:50
FWIW, I cannot reproduce.  Could there be some other non-default setting you have enabled that triggers this?  Can you ZIP and attach a score that demonstrates the issue?

**Comment by sammik** [comment] 2024-08-15 20:58
It used to be an issue, but seems to be fixed already (in master).

**Comment by vallieplushie** [comment] 2024-08-15 21:36
Oh right! I didn't find any issues about this, sorry if I've created a duplicate.

**Comment by oktophonie** [comment] 2024-08-16 07:47
Duplicate of https://github.com/musescore/MuseScore/issues/21680

**Closed by oktophonie** 2024-08-16 07:47 UTC
Labels: engraving, regression MS3
