### ISSUE TITLE
score wont open, no error message 

### ISSUE THREAD

**Issue by Jumphawk88** [musescore/MuseScore#18892] opened 2023-08-02 19:07 UTC
### Issue type

Crash/corruption

### Bug description

My musescore 4 file will not open, I have made a copy of it and it still does not open. all other musescore files open but not this one. I suspect it might be the size of the file but I don't know.

### Steps to reproduce

have a big file?

### MuseScore Version

Muse score 4

### Operating system

windows 

### Additional context

It wont support my file but you can open it here
https://musescore.org/en/node/353141#comment-1201868

**Comment by cbjeukendrup** [comment] 2023-08-02 20:20
As Marc says here: https://musescore.org/en/node/353141#comment-1201891 there is a small corruption in one of the parts, which causes MuseScore to crash. But the full score is still intact; see Marc's comment.

Hopefully we will be able to find the cause of the corruption, so that it won't happen again, and at least we can prevent a crash.

**Comment by bkunda** [comment] 2023-09-15 13:38
@cbjeukendrup is this potentially representative of a bug we can fix, or is this issue isolated to this score only?

**Comment by cbjeukendrup** [comment] 2023-09-15 13:50
Apparently it is not a widespread problem; this is the only case I've seen. Of course, it would be great to know what went wrong, but often that is difficult to find out. Given that only one case is known, I don't think this needs to be a priority, and it'd even be fine to close it.

**Closed** 2023-09-15 13:50 UTC
Labels: P1, corruption, crash
