### ISSUE TITLE
Ties not working as intended when deleting notes

### ISSUE THREAD

**Issue by BryanIsntDead** [musescore/MuseScore#18717] opened 2023-07-20 04:54 UTC
### Issue type

General playback bug

### Bug description

If you have multiple tied notes directly following one another and delete any note that isn't the first one, it plays that phrase as if you never deleted anything. It also happens when you try to add a note to the end of a tie. If you try to add a note and tie the previous note to it, it is played back as if you never added that note. This is a bug also present in the MS Basic soundfont and isn't restricted to Muse Sounds. I discovered the bug in a version of 4.0 but it's still present in Muse 4.1. Restarting the app does fix it, but not 100% of the time, and I wasn't able to find out why restarting doesn't sometimes work.

### Steps to reproduce

1. Add multiple notes (more than 2) of any length directly following one another (no rests in between and all the same pitch)
2. Tie all the notes together (either by selecting them all and pressing the tie button or move from **right to left** and tie each note to the next one)
3. Delete any note that isn't the first note of the tie
4. Playback that sample starting from the beginning of the tie or anywhere before

OR

1. Add multiple notes (more than 2) of any length directly following one another (no rests in between and all the same pitch)
2. Tie all the notes together by moving from **left to right** and tie each note to the next one
3. Playback that sample starting from the beginning of the tie or anywhere before

OR 

1. Add multiple notes (more than 2) of any length directly following one another (no rests in between and all the same pitch)
2. Tie all the notes together (either by selecting them all and pressing the tie button or move from **right to left** and tie each note to the next one)
3. Add any number of notes after the tie that are the same pitch with no rests in between
4. Tie those notes to the original tie (any way you do it will create a playback bug but they may not all sound the same depending on which method you choose to tie them)
5. Playback that sample starting from the beginning of the tie or anywhere before

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/117679071/f6065b90-7336-4472-89ac-f8a3838cc017

### MuseScore Version

4.1

### Regression

Yes, this used to work in **MS3.6.2**

### Operating system

Windows 10

**Comment by bkunda** [comment] 2023-09-15 13:45
Closing as duplicate of https://github.com/musescore/MuseScore/issues/15914

**Closed by bkunda** 2023-09-15 13:45 UTC
Labels: P1, playback, regression_ms3
