### ISSUE TITLE
Count in for playback

### ISSUE THREAD

**Issue by gotofritz** [musescore/MuseScore#18475] opened 2023-07-07 22:14 UTC
### Your idea

There is no count-in functionality in Musescore 4. 

### Problem to be solved

There is no count-in functionality in Musescore 4. 

### Prior art

There was count-in functionality in Musescore 3.

**Comment by cbjeukendrup** [comment] 2023-07-08 08:18
Duplicate of #9183. Thanks!

**Closed** 2023-07-08 08:18 UTC
Labels: feature request
