### ISSUE TITLE
[MU4 Issue] MuseSampler/MuseHub doesn't recognize already installed instruments

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14986] opened 2022-12-06 13:11 UTC
https://user-images.githubusercontent.com/90187801/205921647-e0c92dae-f803-42b4-8d0e-d2d365de5f85.mp4

**Platform information**
Windows10

**Additional context**
Works in build from Nov 30

**Comment by DmitryArefiev** [comment] 2022-12-06 14:23
@vpereverzev Doesn't help after sounds update.. Let's reopen

**Comment by vpereverzev** [comment] 2022-12-06 14:45
Update:

I've started to experience the same issue on Win with the latest update of MuseSounds/Hub.

1. It doesn't recognize that I already have these instruments installed, although I'm using them in MuseScore without any problems
![image](https://user-images.githubusercontent.com/57620349/205940160-8b2b8ee2-bb03-41e3-b6f8-b4e90c668619.png)

2. MuseSampler doesn't see MuseKeys for some weird reason, although I have this downloaded a few days ago:
![image](https://user-images.githubusercontent.com/57620349/205940781-b7a8aa7b-d2b3-4309-8b25-74668e189e26.png)
![image](https://user-images.githubusercontent.com/57620349/205940880-f1d2534c-1e3e-4003-86ae-061ba06d9468.png)

3. I clicked "get" button on all of the MuseSounds packages and almost all of them got instantly recognized as already installed, expect of MuseKeys, which is now in infinite downloading process (which I can't pause)
![muse_keys](https://user-images.githubusercontent.com/57620349/205942950-eaa448ab-cf61-43ba-b0e8-8cf2b71f0a93.gif)

**Comment by erinic04** [comment] 2022-12-06 21:00
Same thing happened with me for brass (#14960)

**Comment by DaforLynx** [comment] 2022-12-07 01:47
I have the same thing. Not that big of a deal I guess, because MS4 seems to recognize them fine.
![image](https://user-images.githubusercontent.com/13303368/206067478-ea857075-e1e5-4942-95de-09954be0a3ed.png)
![image](https://user-images.githubusercontent.com/13303368/206067506-f4702277-5aba-4191-ad96-0c9bdcd7068a.png)

**Comment by iamtesch** [comment] 2022-12-07 19:04
It looks like there are a couple different issues here -- the first one from @DmitryArefiev I believe is indicating an issue with Muse Sounds not showing up in the RC, but showing up in a Nov 30 build. (@vpereverzev -- I think the original title matches better for this).  For this issue:
- could you see what version of MuseSampler is recognized in each case (MS diagnostics menu)?
- do the mixer dropdowns (that currently show "MS Basic") show "Muse Sounds" as an option in the RC option?
- where were the RC and Nov 30 build downloaded or built from?  Could this have been a configuration issue there?

The other issues are with Muse Hub not recognizing installed sounds.  This is something that I am working on; it is difficult to reliably reproduce, but I have an idea what is going on.  Hopefully I'll have a fix soon!

**Comment by erinic04** [comment] 2022-12-07 19:19
The sounds do work for me in Musescore, they just don't switch to Muse Sounds automatically like what happened with Keys above. I even got the eternal loading like they did.

**Comment by vpereverzev** [comment] 2022-12-07 21:35
I believe that one is already fixed by the latest MuseHub/Sounds update, at least it solved problems in my case. @DmitryArefiev can you confirm?

**Comment by DmitryArefiev** [comment] 2022-12-12 20:11
> I believe that one is already fixed by the latest MuseHub/Sounds update, at least it solved problems in my case. @DmitryArefiev can you confirm?

@vpereverzev Yes, all good now. I reinstalled Muse Hub on my Windows 10 and now it works fine with latest RC

**Comment by cbjeukendrup** [comment] 2023-04-19 13:05
@DmitryArefiev Is this issue still actual?

**Closed** 2023-08-08 12:45 UTC
Labels: P1, Muse Hub
