### ISSUE TITLE
Numpad not working to select notes

### ISSUE THREAD

**Issue by flyingrabbitgb** [musescore/MuseScore#12944] opened 2022-08-21 07:41 UTC
The numpad keys are not working to select note durations for input - the numbers above the letters on the keyboard have to be used. This was working fine in Musescore 3. Even after changing the shortcuts in Preferences this doesn't work - it doesn't seem to see a difference between keyboard and numpad.

**Comment by critchie** [comment] 2022-08-21 11:25
See #12791

**Comment by cbjeukendrup** [comment] 2022-08-21 11:51
Closing as a duplicate of #12791. Thanks for reporting!

**Closed by cbjeukendrup** 2022-08-21 11:51 UTC
