### ISSUE TITLE
[MU4 Issue] Vocal Parts Get Assigned the Wrong Muse Sound Parts 

### ISSUE THREAD

**Issue by DaffodilAura** [musescore/MuseScore#14028] opened 2022-10-25 15:38 UTC
**Describe the bug**
When switching back and forth between MS Basic and MuseSounds via "Playback Setup" under "View", Muse Sounds vocal parts get assigned to the wrong instrument parts.

**To Reproduce**
1. Create a Score using MS Basic as the default sounds
2. Insert Soprano, Mezzo-Soprano, Alto, Tenor, Baritone and Bass choir parts.
3. Go into the mixer and change the parts manually to Muse Sounds- specifically, assign "Soprano" vocals to the Soprano part, "Alto" vocals to the Mezzo-Soprano and Alto parts, "Tenor" vocals to the Tenor and Baritone parts, and "Bass" vocals to the Bass part.
4. Add additional instruments in MS Basic and convert them to their respective Muse Sounds versions.
5. Convert all the sounds back to MS Basic via "Playback Setup" under "View", then test instruments.
6. Convert all the sounds back to Muse Sounds via "Playback Setup" under "View" without setting Muse Sounds as the Default.
7. Go into mixer and see that all vocal parts except the Bass get erroneously assigned the "Alto" vocals.

**Expected behavior**
All vocal parts should be automatically assigned their respective vocals in Muse Sounds regardless of how they get switched over- Mezzo-Soprano and Baritone parts ultimately need their own vocal samples, but for now, they should be assigned "Alto" and "Tenor" vocals respectively.

**Screenshots**
Video will come later.

**Platform information**
 - OS: Windows 10, Windows 11

**Additional context**
Be mindful of playback errors when testing Muse Sounds

[Test in Lydian.zip](https://github.com/musescore/MuseScore/files/9862321/Test.in.Lydian.zip)

**Comment by zacjansheski** [comment] 2023-06-29 20:17
Unable to reproduce, closing.

**Closed by zacjansheski** 2023-06-29 20:17 UTC
