### ISSUE TITLE
tremolo placement over noteheads

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#20166] opened 2023-11-24 04:16 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

if a tremolo is put on multiple notes after the number of staff lines changed, it can overlap the noteheads

### Steps to reproduce

1. start with a one line staff
2. change it to a 5 line staff
3. create a chord of many notes in the staff
4. put a tremolo on the chord

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/2f02da18-bd32-4eed-a184-3d7d1339a1ac)

### MuseScore Version

5.1.1-232071203

### Regression

I don't know

### Operating system

windows 11

**Comment by oktophonie** [comment] 2023-11-24 08:09
Duplicate of https://github.com/musescore/MuseScore/issues/19039

**Closed by oktophonie** 2023-11-24 08:09 UTC
Labels: engraving
