### ISSUE TITLE
Staves/systems overflowing right margin

### ISSUE THREAD

**Issue by fp22june** [musescore/MuseScore#23507] opened 2024-07-08 10:17 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

![ms42overflow](https://github.com/musescore/MuseScore/assets/107966765/e352b258-f2ea-4b3c-8ae7-f970191eb4c6)

Musescore 4.3.2
Musescore 4.2.0

### Steps to reproduce

1. New score. Piano grand staff
2. In Page settings windwo > set right margin = 0
3. Select the 1st measure. In Measure properties window > set to 6/4
4. Enter a dotted minim onto the 3rd beat of m1
5. Add a breath mark
6. Either
 a. Under Instruments panel, close Bass clef's eye to hide staff, or
 b. in Bass clef's Staff/Part properties window > set Hide when empty = always

### MuseScore Version

4.3.2

### Regression

Yes. Used to work on Musescore 3.x and now it's broken.

### Operating system

Windows 11 and Linux (Ubuntu 22.04LTS)

**Comment by Jojo-Schmitz** [comment] 2024-07-08 10:21
Stems from https://musescore.org/en/node/365969, and came up before in https://musescore.org/en/node/365879

**Comment by fp22june** [comment] 2024-07-08 10:32
About Regression:
The steps are for musescore 4.
On musescore 3, layout overflowing is present although following these steps do not create it.

**Comment by Jojo-Schmitz** [comment] 2024-07-08 10:49
For Mu3 pease report it at https://github.com/Jojo-Schmitz/MuseScore/issues/new/choose, along with steps to reproduce

**Comment by cbjeukendrup** [comment] 2024-07-08 21:06
Reminds me a little bit of https://github.com/musescore/MuseScore/issues/23441, although that's a bit of a long shot

**Comment by fp22june** [comment] 2024-07-09 16:29
correction: this particular issue does not happen on musescore 3. Overflowing (musescore3) I mentioned in an earlier post could be mostly likely due to misuse of lyrics object (lots of blankspaces), which should be unrelated to this issue.

**Comment by wizofaus** [comment] 2024-08-28 09:31
I'm pretty sure this is fixed by https://github.com/musescore/MuseScore/pull/22135 which was to fix https://github.com/musescore/MuseScore/issues/7819

**Comment by cbjeukendrup** [comment] 2024-08-28 23:13
https://github.com/musescore/MuseScore/pull/22135 would only fix the on-screen drawing though, and not the underlying layout problem. When the right margin is 0, the system should end _at_ the edge of the page, and not beyond. 
Whether it is _drawn_ beyond the edge or clipped, is a different issue and ultimately doesn't matter a lot because for pdf/png export the result will be equally bad either way.

**Comment by wizofaus** [comment] 2024-08-29 06:51
True, but it still shouldn't draw off the edge of the page!

**Closed** 2024-10-21 15:07 UTC
Labels: P2, engraving
