### ISSUE TITLE
Arpeggio plays for too long on shorter durations and causes a staccato on the next note (MS Basic)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11936] opened 2022-06-08 14:44 UTC
**Describe the bug**
When the arpeggio is applied to a shorter duration (in the video below, a 16th), it lasts longer than a 16th duration, which then cuts off the playback of other notes. In the video below I've compared this to MS3.6.

- **In 3.6** the time it takes to play an arpeggio is sped up to make sure all notes fit within the duration. The shorter the duration, the faster the arpeggio. 
- **In 4.0** the duration extends and causes later notes to not be heard

**See video**

https://user-images.githubusercontent.com/21022311/172645878-b218cef2-c87a-4d7c-a8bc-9e07f0178444.mov

**Unexpected staccato**
When an arpeggio plays regularly, it can cause the following note to be shortened, as if it was a staccato. I've compared MS4 and MS3.6 here to demonstrate.

https://user-images.githubusercontent.com/21022311/172645752-61e853ae-407a-419c-8051-cf498727d475.mov

--

[See other video](https://github.com/musescore/MuseScore/issues/11936#issuecomment-1584350128)

[See other video](https://github.com/musescore/MuseScore/issues/11936#issuecomment-1592869536)

**Comment by MarcSabatella** [comment] 2022-10-07 18:41
I just checked, and although a couple of other arpeggio-related issues have been fixed, the ones in this issue remain.

**Comment by xsrvmy** [comment] 2023-02-23 06:37
Is a fix for the staccato issue coming? It seems that the problem is that the release is also being arpeggiated causing the next note to be incorrectly released.

**Comment by DmitryArefiev** [comment] 2023-06-09 10:25
The staccato issue happens with the same notes in the next chord


https://github.com/musescore/MuseScore/assets/90187801/4038203e-f747-4d65-a6bc-7953a4988f2d

A little bit different but similar issue with MuseSounds  #16917

**Comment by zacjansheski** [comment] 2023-07-12 16:33
I tried out the staccato issue today and I am getting the opposite issue, the following chord is also played as arpeggio

https://github.com/musescore/MuseScore/assets/69917893/71a56423-11aa-4b34-89e3-c8570c8b99c3

**Comment by DmitryArefiev** [comment] 2023-11-29 15:17
Fixed in #20243

**Closed** 2023-11-30 13:46 UTC
Labels: P1, regression_ms3
