### ISSUE TITLE
Automatic slur placement occasionally collides with notes

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15317] opened 2022-12-18 10:44 UTC
**Describe the bug**
Adding a slur can cause it to collide with notes.

**To Reproduce**
https://user-images.githubusercontent.com/120861729/208293889-43cd2036-4bde-49c2-8fa2-1ea45157c97b.mp4

**Expected behavior**
The new slur should be away from other objects.

**Platform information**
windows

**Additional context**
This does not always happen, but I do not know what causes it to happen in some situations.

**Comment by mike-spa** [comment] 2022-12-21 17:45
Should be fixed by the linked PR. When the issue is so case-specific, please remember to share the file where the problem occurs. In this case I got it from your other PR 😉

**Closed** 2023-03-20 10:58 UTC
Labels: P3, engraving
