### ISSUE TITLE
[MU4 Issue] fp doesn't work as intended

### ISSUE THREAD

**Issue by savagestrawberryxd** [musescore/MuseScore#14594] opened 2022-11-18 17:13 UTC
I usually use fp if I want a long sustained note or timpani roll to be loud on the first strike then turn soft. That was in MS3. In MS4, the fp marking on the timpani roll of my score no longer does the same. It just plays soft

**Comment by erinic04** [comment] 2022-11-18 17:20
#13543

**Comment by cbjeukendrup** [comment] 2022-11-18 19:03
Duplicate of #13543

**Closed by cbjeukendrup** 2022-11-18 19:03 UTC
