### ISSUE TITLE
Links in Class page of Learn tab do not open

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#17973] opened 2023-06-13 19:43 UTC
### Issue type

UI bug

### Bug description

The links in Home / Learn / Classes do not open, as of recent nightly builds (works in 4.0.2).  I see why; PR forthcoming.

### Steps to reproduce

1. Go to Home / Learn / Classes
2. Click "Open Mastering MuseScore"

Result: nothing happens

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231640304, revision: github-musescore-musescore-d9e8f71

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

**Comment by MarcSabatella** [comment] 2023-06-13 19:45
See https://github.com/musescore/MuseScore/pull/17970 for fix

**Comment by cbjeukendrup** [comment] 2023-06-13 23:24
For the record: regression caused by a1e795c8031324f10f121c834bde24662d239628

**Comment by DmitryArefiev** [comment] 2023-06-14 10:11
Fixed in #17970

**Closed as completed** 2023-06-14 10:11 UTC
Labels: P2, UI, regression MS4
