### ISSUE TITLE
Cross staff seconds collide

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#20104] opened 2023-11-20 11:50 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

“Reported” (i. e. someone was looking for a workaround) at https://musescore.org/de/node/356937

There is the possibility of note head collisions when using cross staff notation. For details see screenshot below.

### Steps to reproduce

1. Write some beamed notes in both staves of a two-staff instrument that are only a second apart.
2. Move a note from the upper staff down.
3. Try different stem directions and voices: If both are voice 1 and stem up, the note heads don’t collide (but the stems do), else the note heads collide.

### Screenshots/Screen recordings

Selection shows differently colored voices.
![Bildschirmfoto vom 2023-11-20 12-41-54](https://github.com/musescore/MuseScore/assets/7814361/e85647a6-ec7c-424f-877a-8547ba7a18b5)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Manjaro Linux

**Comment by oktophonie** [comment] 2023-11-20 12:48
Duplicate of https://github.com/musescore/MuseScore/issues/19669
Fixed in 4.2/master

**Closed by oktophonie** 2023-11-20 12:48 UTC
Labels: duplicate, engraving

**Comment by mmeyn** [comment] 2023-11-20 16:30
Thanks for the hint. I had searched for “second” instead of “2nd” before submitting this ;)
