### ISSUE TITLE
[MU4 Issue] Notes not being played

### ISSUE THREAD

**Issue by ghost** [musescore/MuseScore#15656] opened 2022-12-30 22:32 UTC
**Describe the bug**
Notes have been dropping in random instruments, seemingly at random.

**To Reproduce**
1. Create a score with an oboe.
2. Place 2 8th notes followed by a quarter note with the pitches F, C, C.
3. Tie the 2nd 8th note to the quarter note.
4. Apply a mezzo forte dynamic.
5. Observe that the second note does not play.

**Additional Observations**
If forte dynamic is used, playback is as expected and the note plays.
If the tie is removed, all 3 notes play correctly.
If the figure below is made, the first c will play as expected, but the second will not.
![image](https://user-images.githubusercontent.com/121003668/210115774-41e098f4-f360-4110-8778-c9db9a8b57e7.png)

**Expected behavior**
Regardless of dynamics or ties all notes should play.

**Screenshots**
Measure used to replicate issue.
![image](https://user-images.githubusercontent.com/121003668/210115650-8066f7ef-b74e-4e1d-b159-b751f3109fd2.png)

**Platform information**
 - OS: Windows 11, 64 bit.

**Additional context**
Oboe is not the only instrument this has been demonstrated on, I've also noticed it several times on piccolo, as demonstrated, things like dynamics and other notes in the bar impact the issue, it's very bizarre.

**Comment by Mick45678** [comment] 2023-02-01 17:16
The trombone especially has some notes being dropped at times.

**Comment by DmitryArefiev** [comment] 2023-09-08 14:11
I **can't reproduce** it (4.2 master, Win10) 

@GoodMannSamm Can you try it again please?

**Comment by MarcSabatella** [comment] 2023-09-13 17:57
The cases in the score above are not related to the original example here.  These are specific to Muse Sounds and the overlapping notes in this particular score.

The first circled note - the B - is being played while a B in the second voice is still being sustained.  This should indeed replay the B but currently doesn't, and is already reported as https://github.com/musescore/MuseScore/issues/15306

The second circle note - the G - is being played immediately after a note of the same pitch in the other voice.  Here there is no actual overlap but somehow a similar bug is triggered.  This is related to and probably a duplicate of https://github.com/musescore/MuseScore/issues/14746

**Comment by zacjansheski** [comment] 2024-09-01 20:07
Closing as stale

**Closed by zacjansheski** 2024-09-01 20:07 UTC
Labels: needs info
