### ISSUE TITLE
[MU4 Issue] Sporadic corruption where main MSCX file is not at the root of the MSCZ file but at `Users/name/…/….mscx`

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16338] opened 2023-02-12 20:47 UTC
**Describe the bug**
We have seen two reports now of a corruption where the main MSCX file inside the MSCZ file is not at the root level of the zip container, but for example at `/Users/perfc/Downloads/Carol of the Bells.mscx`. It looks as if MuseScore took the full path instead of the filename when deciding the name of the MSCX file.

This makes that MuseScore cannot find it and thinks the score is empty. 

In both reports, the files contain `<metaTag name="platform">Microsoft Windows</metaTag>`, suggesting that this happened on Windows.

It is not yet known how to reproduce this.

Here is one report, originally from https://musescore.org/en/node/340775: [`Carol of the Bells.mscz`](https://musescore.org/sites/musescore.org/files/2022-12/Carol%20of%20the%20Bells.mscz)
The other report was sent privately to Martin so I don't think I'm allowed to share the file here, but it's just more of the same.

**Comment by bkunda** [comment] 2023-05-10 13:28
This has been investigated and nobody is yet able to reproduce it. 
Closing for now, but we can reopen if we learn how to reproduce it.

**Closed by bkunda** 2023-05-10 13:28 UTC
Labels: needs info, P2, corruption

**Comment by cbjeukendrup** [comment] 2023-05-10 15:52
Wasn't https://github.com/musescore/MuseScore/pull/17462 related to this? (In which case we can consider this issue fixed)

**Comment by bkunda** [comment] 2023-05-10 18:55
I'm actually not sure @cbjeukendrup. @Eism @RomanPudashkin?

**Comment by Eism** [comment] 2023-05-10 18:58
Yes, looks like I fixed this issue in https://github.com/musescore/MuseScore/pull/17462
