### ISSUE TITLE
Flatpak official support

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#21751] opened 2024-02-29 12:21 UTC
### Your idea

Official Flatpaks for MuseGroup apps

### Problem to be solved

Can the Musescore team handle the [Flatpaks](https://flathub.org/apps/org.musescore.MuseScore) for Muse Score, MuseHub (you'll have to list it as proprietary unless you're planning on changing that), etc.. Leaving it up to random volunteers leads to occasional [viruses](https://www.gamingonlinux.com/2024/02/snap-store-from-canonical-ubuntu-hit-with-another-crypto-scam-app/).

**Comment by cbjeukendrup** [comment] 2024-03-01 23:43
Closing as a duplicate of these:
1. FlatPak format support: https://github.com/musescore/MuseScore/issues/19722
2. FlatHub distribution: https://github.com/musescore/MuseScore/issues/20459

(Well, one detail is that this issue is about all Muse apps while the mentioned two are about MuseScore specifically, but the other apps are outside our control so having an issue for them in this repo isn't really useful.)

Currently we don't have the resources to build FlatPak support ourselves, but if people want to help us with that, we'll probably be open to that.

**Closed by cbjeukendrup** 2024-03-01 23:43 UTC
Labels: feature request, os: linux

**Comment by RustoMCSpit** [comment] 2024-03-02 02:18
> Currently we don't have the resources to build FlatPak support ourselves, but if people want to help us with that, we'll probably be open to that.

it's free and open source? what do you mean

**Comment by shoogle** [comment] 2024-03-02 02:22
He means we have limited time, and we have chosen to spend that time maintaining an AppImage rather than a Flatpak.

**Comment by cbjeukendrup** [comment] 2024-03-02 08:08
And even if someone built it for us (which anyone is free to do indeed), we'd still have the burden of maintaining and testing it, which is why I would personally not make hard promises about whether we'll be able to merge it.

**Comment by dimaugh** [comment] 2024-03-06 12:53
You're having to work on the RPM version of MuseSounds, solving distro specific bugs... Flatpak would probably result in less work.

**Comment by RustoMCSpit** [comment] 2024-03-06 13:28
> You're having to work on the RPM version of MuseSounds, solving distro specific bugs... Flatpak would probably result in less work.

i dont think these people are that familiar with linux lol

**Comment by Jojo-Schmitz** [comment] 2024-03-06 13:32
Less work than AppImage? Less work than __switching__ from the __existing and working__ method (AppImage) to a new one (FlatPak)?
Not sure about the former, but pretty sure about the latter.

**Comment by cbjeukendrup** [comment] 2024-03-06 13:51
I think the "less work" remark was about Muse Sounds Manager, which is distributed as RPM and I believe something else too; in that case, using AppImage or FlatPak may be less work.

**Comment by shoogle** [comment] 2024-03-06 15:37
Muse Sounds Manager is made by a different team. They had their own reasons for choosing DEB + RPM. Probably because it originally relied on a root daemon (it doesn't any more) and because it has to install libraries to `/usr/local/lib` (or somewhere like that) so that MuseScore can access them.

Regarding MuseScore as a Flatpak, by design Flatpak restricts access to the filesystem, dynamic libraries, and audio APIs. There are workarounds, but these undo the benefits of sandboxing, and it's another layer of things to go wrong.

AppImage is simpler and more convenient for downloading builds of pull requests, etc. Even if we had a Flatpak for releases, we would probably still need to maintain an AppImage in order to get those pull request builds.

**Comment by dimaugh** [comment] 2024-03-06 16:00
> Less work than AppImage? Less work than **switching** from the **existing and working** method (AppImage) to a new one (FlatPak)? Not sure about the former, but pretty sure about the latter.
> 
Well, of course it would be more work at first, but after that you'd have far less to worry about.
Flatpaks are becoming the packaging standard in Linux and have a much bigger team behind.
Also, Linux users rarely install things from a website.

> Regarding MuseScore as a Flatpak, by design Flatpak restricts access to the filesystem, dynamic libraries, and audio APIs. There are workarounds, but these undo the benefits of sandboxing, and it's another layer of things to go wrong.
> 
This was covered in this post, in the part about Extensions:
https://github.com/musescore/MuseScore/issues/19722#issuecomment-1806410787

**Comment by shoogle** [comment] 2024-03-06 16:28
Like I said, there are workarounds, but the point is that Flatpak requires its own set of solutions to problems that we have already solved with the AppImage. The AppImage is more like what what we are doing for Windows and macOS, and it allows us to create builds from pull requests that we can test on lots of systems without installing additional dependencies.

**Comment by igorkorsukov** [comment] 2024-03-06 19:30
> Well, of course it would be more work at first, but after that you'd have far less to worry about. Flatpaks are becoming the packaging standard in Linux and have a much bigger team behind. Also, Linux users rarely install things from a website.

The most popular distribution is Ubuntu. They promote Snap. Doesn't this mean that if we abandon appimage, we will have to make assemblies for both flatpak and snap?

Overall, as stated above, this is an open source application, we follow the Linux philosophy, everyone can simply improve what they think needs to be improved on their own.

**Comment by RustoMCSpit** [comment] 2024-03-06 21:26
> The most popular distribution is Ubuntu. They promote Snap. Doesn't this mean that if we abandon appimage, we will have to make assemblies for both flatpak and snap? (instead of one appimage).

for the love of god do not use snap, i could rant for hours like any linux users but it's absolute garbage. you can look it up yourself cause theres great videos on why. tl;dr: it's ubuntus attempt at enshittification

**Comment by igorkorsukov** [comment] 2024-03-06 21:46
> for the love of god do not use snap, i could rant for hours like any linux users but it's absolute garbage. you can look it up yourself cause theres great videos on why. tl;dr: it's ubuntus attempt at enshittification

So, you're proposing to make life harder for Ubuntu users (which is the majority) in order to give a "better" solution for other Linux users?

**Comment by igorkorsukov** [comment] 2024-03-06 21:54
It looks like it still needs Snap support for Ubuntu users (they can't be ignored; asking them to install a flatpak to use MuseScore is rather iffy if they have their own app store), and Flatpak for users of other distros..., and Appimage for those who have neither one nor the other...

**Comment by RustoMCSpit** [comment] 2024-03-06 23:00
> > for the love of god do not use snap, i could rant for hours like any linux users but it's absolute garbage. you can look it up yourself cause theres great videos on why. tl;dr: it's ubuntus attempt at enshittification
> 
> So, you're proposing to make MuseScore harder to use for Ubuntu users (which is the majority) in order to offer a "better" solution for other Linux users?

ubuntu users can use flatpak??? very easily in fact

**Comment by shoogle** [comment] 2024-03-07 01:32
It is possible to use Flatpak on Ubuntu. It's just not installed by default, unlike on other distros.

Flatpak is becoming more popular and it does have advantages (as well as disadvantages). It's worth considering for the future, but it's not a priority compared to other things we have planned.
