### ISSUE TITLE
Notes being dropped during playback and mp3 export with MuseSounds

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#15206] opened 2022-12-15 18:15 UTC
**Describe the bug**
When I use the Grand Piano from MuseSounds to play back this piece, I am unable to hear some of the notes (the eighth note in measure 1, all the Ds in m2 and the half note in m4).  When I use MS Basic, the notes are all heard.

This also affects export to mp3 where these notes are also being dropped.
[2022-12-14-melody.zip](https://github.com/musescore/MuseScore/files/10239635/2022-12-14-melody.zip)

**To Reproduce**
Play the attached score.

**Expected behavior**
All notes should be heard, particularly when exported to mp3.

**Platform information**
Windows 10

**Comment by MarcSabatella** [comment] 2022-12-15 19:31
That's because the note overlaps with a note on the other staff.  So, a duplicate of https://github.com/musescore/MuseScore/issues/13853.  That was closed because it's mostly fixed for MS Baisc, but definitely still a very serious problme for Muse Sounds.

**Comment by cbjeukendrup** [comment] 2022-12-22 20:55
I think I'll close this in favour of #15306, which describes the issue more specifically (namely that it relates to overlapping notes in different staves).
Thanks for reporting!

**Closed by cbjeukendrup** 2022-12-22 20:55 UTC
Labels: P2
