### ISSUE TITLE
[MU4 Issue] "Text style" options (Properties" sidebar) are available even in edit mode

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12251] opened 2022-07-03 13:28 UTC
**Describe the bug**

In MS3, a **text style** can only be applied to a _complete_ text object, and is inapplicable to selected characters in edit mode.

However, in MS4 the "Text style" dropdown can also be used to apply character formatting to selected characters _within_ a text object. AFAIK, this is inapplicable and should not be allowed.

**To Reproduce**

1. Open a score. 
2. Create some staff text, say.
3. Go into edit mode and select a few characters with the cursor.
4. In the properties sidebar, select "More" and then "Expression" (for example) from the "Text style" dropdown.

RESULT: The text style is applied to the characters

**Expected behavior**

The "Text style" dropdown should only apply to the text object _in its entirety_. Even in edit mode, and even if characters are selected, the application should still be to the _whole_ text object.

**Platform information**
 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2603809362, revision: github-musescore-musescore-c83d663

**Additional context**

Apart from this, there is an additional issue with the "Text style" dopdown. If you select a text style accessible only through scrolling upwards, the "More" section closes without applying anything.

**Comment by MarcSabatella** [comment] 2022-07-04 15:29
My impression is that this is by design, and is a deliberate improvement - no more need for a separate "text toolbar" that reproduce the controls from the Inspector.

**Comment by cbjeukendrup** [comment] 2022-07-04 16:39
It was certainly by design that the font family/size/style etc. options were moved from the text toolbar to the inspector. But I do slightly doubt about the "More" > "Text style" dropdown specifically, because I'm not sure that this setting is (technically) suitable to be applied to single characters rather than the whole thing. If it works, then I have nothing against it, but I think it deserves at least some testing.

**Comment by Tantacrul** [comment] 2022-07-08 11:55
The idea of assigning styles to individual characters was not **exactly** specified, although it is consistent with the overall idea of the design, which, to put it bluntly, can be described as 'work like Microsoft Word / Google Docs works'.

I'm going to close this until a specific issue is discovered.

**Closed by Tantacrul** 2022-07-08 11:55 UTC
