### ISSUE TITLE
Freeze/crash when editing Title or Arranger fields (when Text cursor indicator is turned on, Windows only)

### ISSUE THREAD

**Issue by EricBishton** [musescore/MuseScore#17006] opened 2023-03-25 02:30 UTC
### Issue type

Crash or freeze

### Bug description

When editing score Title, Arranger, (and probably other) fields in the WYSIWYG editor (not the properties pane), The editor locks up when you press Enter or try to exit the editing mode to do something else.

### Steps to reproduce

1. In Windows settings, turn on text cursor indicator (see the attached video to find)  
2. Open score
3. Start editing the score (add parts, etc.)
4. Try to edit the Title (or go to Add->Text->Title) and enter a few letters.
5. Press Enter OR exit the field by clicking outside of it.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/6a09a4d8-6931-42da-ac31-8cf8e2148279

### MuseScore Version

4.0.2.230651553

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

This occurred in two different scores for me.  In each case, I first tried to edit the Title, etc. via the properties dialog.  That didn't however, update the score in the WYSIWYG editor.

**Comment by DmitryArefiev** [comment] 2023-06-04 20:32
@EricBishton I can't reproduce it in latest master. Can you try it again please? 

If yes, please attach the video capture. Thanks!

**Comment by EricBishton** [comment] 2023-06-04 23:18
https://github.com/musescore/MuseScore/assets/12093217/e9104ee5-c736-492a-9af0-ab981d485678

For this video, I started with the about box opened, to verify the version.  Then I opened up a song, clicked in the title, added a space and pressed the Enter key.  After a few moments, you can see that MuseScore is no longer responding.

**Comment by DmitryArefiev** [comment] 2023-06-05 15:10
@EricBishton Thanks for the video! But I still can't reproduce it on my side. Can you attach the score please? (if possible)

**Comment by DmitryArefiev** [comment] 2023-06-06 10:42
> [Revelation Song for Small Ensemble.zip](https://github.com/musescore/MuseScore/files/11657478/Revelation.Song.for.Small.Ensemble.zip)
> 
> It happens for me on any score, and on two different computers. Both are running Windows 11 Home 22H2.

Very strange.. I've tried on my Windows10/Windows11 and **still can't get** that result


https://github.com/musescore/MuseScore/assets/90187801/b1b878f5-feb3-41bd-8450-0058a294fb25

**Comment by DmitryArefiev** [comment] 2023-06-06 10:45
@EricBishton Can you try this build please? https://github.com/musescore/MuseScore/actions/runs/5184141476

You should unzip, then unzip 7z folder (use can use 7-zip, it's free) and then run **MuseScore4.exe** from **bin** folder

**Comment by EricBishton** [comment] 2023-06-06 16:21
No difference, even with a new score.  When it goes unresponsive, my CPU fans kick into high gear.  It takes about 1 CPU's worth (0.9~1.2) of computing power.  No change in half an hour.  

I guess I'll have to build it and run it inside of a debugger to see where the infinite loop is.  You folks use the gcc toolchain, right?  (I hate gdb; maybe I can load it up under CLion and get a decent debugging experience.)

**Comment by Eism** [comment] 2023-06-08 07:17
I tried to build the project using CLion on Windows but couldn't set it up correctly to make it work. Although I develop on CLion on macOS (but it required spending time on configuration and fixing issues).

You can try using CLion on Windows, but we recommend QtCreator(https://github.com/musescore/MuseScore/wiki/Compile-in-Qt-Creator) since you shouldn't encounter any issues there.

**Comment by monsoma** [comment] 2023-07-10 20:16
(Sorry. Accidentally opened this duplicate, because I didn't found this one.)

Nearly the same for me. One difference is that MuseScore freezes only when pressing RETURN while editing the title. Clicking outside of the title doesn't do any harm.

This happens to me only on one of my PCs but not on two others. Most noticable difference is that it has a AMD processor and graphics and is connected to a 4K Laptop. I attach the zip file created by the diagnosis menu.

Hope this helps.
[musescore-diagnose.zip](https://github.com/musescore/MuseScore/files/12006268/musescore-diagnose.zip)

**Comment by EricBishton** [comment] 2023-07-10 21:37
My problem is occurring on i7 machines, BUT they BOTH have high-end graphics cards.  Might be a clue; might not.

**Comment by MarcSabatella** [comment] 2023-08-14 16:06
@DmitryArefiev It seems someone may have found a good clue.  I am able to reproduce this sort of crash on my Window machine if I go to the Windows accessibility settings and enable "Text cursor indicator".  Then if I try to edit any text and press Enter, it hangs.

This also seems like it may have an impact on the time required to open the Format / Style dialog on some systems.  See https://github.com/musescore/MuseScore/issues/13193 and the recent comments there.

**Comment by EricBishton** [comment] 2023-08-14 17:01
Yes!!  I use that feature on all my computers.  I just turned it off to test and hitting the enter key works properly.

As far as I'm concerned, I have a reasonable workaround.  (Turn off the setting when I use MuseScore.)  It's a bit annoying, but I'm happy to have that!

**Comment by monsoma** [comment] 2023-08-17 08:08
+1. Turning the setting off also turns the freezing off.

Thx for this workaround!

**Comment by DmitryArefiev** [comment] 2024-06-20 12:14
> @DmitryArefiev It seems someone may have found a good clue. I am able to reproduce this sort of crash on my Window machine if I go to the Windows accessibility settings and enable "Text cursor indicator". Then if I try to edit any text and press Enter, it hangs.
> 
> This also seems like it may have an impact on the time required to open the Format / Style dialog on some systems. See #13193 and the recent comments there.

@MarcSabatella Thanks! I **can reproduce** it if to check "Turn on text curso

https://github.com/musescore/MuseScore/assets/90187801/6a09a4d8-6931-42da-ac31-8cf8e2148279

r indicator" option

**Comment by MarcSabatella** [comment] 2024-06-20 13:02
One thing,m though - the user in #23301 says he *doesn’t* have that option enabled.  So there could be some other system setting that *also* triggers the same problem.  But hopefully the same solution - whatever that turns out to be - would apply in both cases.

**Comment by DmitryArefiev** [comment] 2024-07-11 12:19
Fixed in #23574

**Closed** 2024-07-11 12:19 UTC
Labels: P1, crash, regression_ms3, os: windows
