### ISSUE TITLE
[MU4 Issue] Transparent app border on Windows

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#8270] opened 2021-06-07 16:30 UTC
A transparent frame is visible around the app window and buttons are visually offset so you have to click above and to the left of each button to activate it.

Occurs on Windows in the nightly builds as well as in self-compiled builds.

https://user-images.githubusercontent.com/11011881/129974508-7a22e869-fa00-43e2-9b18-3ca787cfe2bf.mp4

**Desktop:**
 - OS: Windows 10, when compiled outside Qt Creator (e.g. Nightly builds, or with the [build.cmake](https://github.com/musescore/MuseScore/wiki/Compile-on-the-command-line#Using-buildcmake-recommended) script)
 
**System specs:** (it's a MacBook Pro running Windows in a dual-boot setup)

![image](https://user-images.githubusercontent.com/11011881/122230147-49587800-ceb1-11eb-9341-a1cc659ea73f.png)

**Comment by shoogle** [comment] 2021-06-09 11:06
Report from a community member:
> The transparent frame only appears when I run the Musescore NightlyBuilds via the processor's own Intel graphics, but not via the NVidia graphics card...

**Comment by wizofaus** [comment] 2021-06-14 20:38
Any progress on this? It makes working with MU4 just to test my own changes seriously painful...and I can't figure out what's causing it either, something buried inside Qt itself it seems.

**Comment by cbjeukendrup** [comment] 2021-06-14 20:41
@Eism is working on Windows-titlebar related things (see https://github.com/musescore/MuseScore/issues/8221#issuecomment-860063040) so I guess he will fix this one too.

**Comment by Eism** [comment] 2021-06-14 21:00
@cbjeukendrup
I also hope so :)

**Comment by RomanPudashkin** [comment] 2021-06-15 07:29
@shoogle @wizofaus 

I can't reproduce this issue on my laptop with windows 10 (it has only integrated Intel UHD Graphics 620). It would be great to add to the description of the issue more details about your hardware

**Comment by wizofaus** [comment] 2021-06-15 07:32
How did you build it? My understanding is that it doesn't happen when built with QtCreator. @RomanPudashkin 
This is just an ASUS laptop with Intel HD Graphics 530 and NVIDIA GForce GTX as display adapters. I don't know how to run an app using a particular adapter.

**Comment by RomanPudashkin** [comment] 2021-06-15 07:34
> How did you build it? My understanding is that it doesn't happen when built with QtCreator

Yes, I have built it using QtCreator

**Comment by wizofaus** [comment] 2021-06-15 07:35
If you build just with MSVC or use the nightly Windows build does it happen?

**Comment by RomanPudashkin** [comment] 2021-06-15 07:38
My QtCreator already uses MSVC

**Comment by Mystic-Slice** [comment] 2021-06-15 07:40
I tried building with both QtCreator and Visual Studio.
In QtCreator the transparent frame problem does not occur. Only in Visual Studio.
I think the problem might be tied to the embedding of top menu items(File, Edit, View, etc..) within the title bar. QtCreator, for some reason, does not do that and so, works fine.

**Comment by wizofaus** [comment] 2021-06-15 07:55
> My QtCreator already uses MSVC

*Uses* it yes, but obviously something in the build process is different. And it's not cmake - I tried building from the command line using Qt's cmake and got the same same problem.

**Comment by shoogle** [comment] 2021-06-16 13:48
@RomanPudashkin, @Eism, I added information about hardware and setup to the description.

**Comment by wizofaus** [comment] 2021-06-18 21:00
Changing WS_CAPTION to WS_BORDER in WinFramelessWindowController::init fixes the mouse offset problem, but not the transparent frame.

**Comment by wizofaus** [comment] 2021-06-23 04:53
TBC, I don't intend to put up a PR for this as I don't think it's the right fix, and I don't know what the thinking was behind the original code. Nor do I understand how it could possibly be different when built using QtCreator.  But I'm using these changes locally just so I can at least use the version I build.

**Comment by Tantacrul** [comment] 2021-08-13 10:33
I've bumped this to P0.

Hearing it come up quite a bit.

**Comment by Jojo-Schmitz** [comment] 2021-08-13 10:47
I'd have asumed 0 meaning no priority at all ;-)

**Comment by Tantacrul** [comment] 2021-08-13 12:03
> I'd have asumed 0 meaning no priority at all ;-)

Yeah... I think P1 is usually the highest... but anyway, we have this system where P0 means 'critical'. So for crashes or anything that makes the app fundamentally unusable.

**Comment by Tantacrul** [comment] 2021-08-13 12:04
Incidentally, we are establishing a process where all crashes should be assigned to @vpereverzev, who will assign them to one of our internal dev team.

**Comment by Eism** [comment] 2021-08-18 14:50
@shoogle @wizofaus please, check this solution on your devices
#8872

**Comment by shoogle** [comment] 2021-08-18 21:40
I've added a screen capture to the description. @Eism's fix didn't work for me or @wizofaus, unfortunately, but the problem does seem to be related to OpenGL. See https://github.com/musescore/MuseScore/pull/8872#issuecomment-901428414.

**Closed** 2021-08-19 12:19 UTC
Labels: P0
