### ISSUE TITLE
[MU4 Task] [GP] Display gradual tempo changes

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10377] opened 2022-01-25 15:30 UTC
**Task description**
Display gradual tempo changes:
- Rallentando (rall.)
- Accelerando (accel.)

**Current state:**
![Screenshot 2022-01-25 at 18 27 43](https://user-images.githubusercontent.com/24373905/151006358-0f816190-b0ab-4b49-999d-97e91f5db91e.png)

**Expected:**
![Screenshot 2022-01-25 at 18 27 12](https://user-images.githubusercontent.com/24373905/151006259-ca5cf59b-71a2-40d2-b737-c1ca9b8b83dd.png)

**Comment by Jojo-Schmitz** [comment] 2022-01-25 15:51
I guess first https://musescore.org/en/node/9383 needs to get implemented

**Comment by alexpavlov96** [comment] 2022-01-25 16:03
@Jojo-Schmitz I'm working now on guitar experience especially. What about simply showing the text from imported data, so the guitarists can see?

You mean to implement playing the melody with acceleration/slowing down?

**Comment by Jojo-Schmitz** [comment] 2022-01-25 16:17
yes

**Comment by Jojo-Schmitz** [comment] 2022-01-26 14:35
See #10383, which seems at least a 1st step towards proper playback of these

**Comment by alexpavlov96** [comment] 2022-01-26 18:01
@Jojo-Schmitz thank you, I will track, not working with this in the near future

**Comment by boryskuzmenko** [comment] 2022-04-19 18:18
**Reopened**
The issue is partly fixed. Two more points should be fixed also:
- Rallentando (rall.) and Accelerando (accel.) shouldn't be rendered over the TAB staff if notation staff is displayed (according to the consistency)
- Rallentando (rall.) and Accelerando (accel.) should be applied to all parts in a score

https://user-images.githubusercontent.com/101250347/164069305-7c66e607-7458-40e7-a166-4cbd9f5771d9.mov

**Comment by boryskuzmenko** [comment] 2022-05-23 20:28
**FIXED**

**Closed by boryskuzmenko** 2022-05-23 20:28 UTC
Labels: P2
