### ISSUE TITLE
[MU4 Issue] Part Score Part Name won't hide

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#14124] opened 2022-10-28 01:28 UTC
**Describe the bug**
In part scores, when you make a second part viewable, and then hide it, the part name does not go back to being hidden. That is even when I tried toggling the part name viewable with only one part option. (i.e on a trumpet one part, making it so it shows trumpet 1 and 2. Then hiding trumpet 2, but the part name stays and you cant hide it.)

**To Reproduce**
1. Go to a part score
2. In the instruments panel toggle another part to make it viewable on that part score.
3. Toggle it back so there is only one part.

**Expected behavior**
I expect the part name to go away when there is only one part on the page.

Below is an example from a commission I did that I'm playing around with in MS4
*
Before
<img width="2557" alt="Screen Shot 2022-10-27 at 9 27 15 PM" src="https://user-images.githubusercontent.com/103294056/198439297-4acbc98d-3a65-4ca7-884c-d5f486320c97.png">

<img width="1215" alt="Screen Shot 2022-10-27 at 9 27 24 PM" src="https://user-images.githubusercontent.com/103294056/198439358-3679e1b1-9e83-4690-81b4-d980acdd5006.png">

After
<img width="1531" alt="Screen Shot 2022-10-27 at 9 27 32 PM" src="https://user-images.githubusercontent.com/103294056/198439384-7a39fcb4-ab3e-4674-94ef-188fbcbeec31.png">

**Platform information**
 - OS: macOS

**Comment by mike-spa** [comment] 2022-10-28 12:13
Closing as duplicate of #11211. Will be fixed by #14133

**Closed by mike-spa** 2022-10-28 12:13 UTC
Labels: P2, duplicate, engraving
