### ISSUE TITLE
Tempo mark applied by shortcut causes mismatch between audio playback and cursor position

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19641] opened 2023-10-06 10:53 UTC
### Issue type

General playback bug

### Bug description

There seems to be some mismatch between a tempo applied by shortcut and a similar one applied from the palette.

### To reproduce

1. Play back the attached score first without a tempo mark.
[tempo_mark_and_playback.zip](https://github.com/musescore/MuseScore/files/12830185/tempo_mark_and_playback.zip)
3. Then apply the default tempo mark to the first note using the shortcut Alt+Shift+T. Play it back.
4. Stop and delete the tempo mark,  then apply the same tempo mark from the palette and play back again. 
5. Repeat if nothing unexpected happens.

You should find a problem at some point with playback out of synch with the score notation. The problem is fixed if you subsequently manually alter the tempo mark.

Possibly some connection with #14678?

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by bkunda** [comment] 2023-10-06 13:06
Pls investigate @DmitryArefiev

**Comment by MarcSabatella** [comment] 2023-10-06 13:11
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/13662.

**Closed** 2023-10-06 15:50 UTC
