### ISSUE TITLE
[MU4 Issue] Crashes on drum set note input / when opening Drum Map (Windows 10)

### ISSUE THREAD

**Issue by eitanmuir** [musescore/MuseScore#15267] opened 2022-12-17 10:11 UTC
**Describe the bug**
Musescore 4.0.0 installed today, updated from Beta pre-release (which also shared the issue.) MuseScore crashes when I enter Note Input mode on any Unpitched Percussion instrument staff.

**To Reproduce**
1. Create or open any score and add Drum Set or Auxiliary Percussion instrument
2. Click on the first symbol in the bar (Full Bar Rest) and start entering notes / OR / click 'Edit Drum Map'
3. Musescore crashes

N.B  I have not seen recent evidence of this issue yet - is it possibly a problem with my system?

**Expected behavior**
Keymapped percussion notes should be created on the staff / Edit Drum Map should open the drum map.

**Platform information**
 - OS: Windows 10 Home w/ latest updates
 - Dell XPS 9380 (2019)

**Comment by MarcSabatella** [comment] 2022-12-17 18:58
I can't reproduce this problem.  Can you attach the specific score giving you problems, and be more specific about the steps- how *exactly* you are trying to enter the notes?  to attach a score, you need to ZIp it first, or just rename it to end in ".zip"

**Comment by eitanmuir** [comment] 2022-12-18 00:34
> I can't reproduce this problem. Can you attach the specific score giving you problems, and be more specific about the steps- how _exactly_ you are trying to enter the notes? to attach a score, you need to ZIp it first, or just rename it to end in ".zip"

Thanks for your reply Marc! The issue for me is across all scores (including brand new blank new scores), and occurs with all 'Unpitched Percussion' instruments. Pitched percussion instruments (e.g. Vibraphone) are fine. 

On unpitched staffs, I can select bars and rests without a problem, but MU4 instantly freezes for 1-2 seconds before crashing when I try any manual note input methods: using either keyboard shortcuts (e.g. pressing 'A' key), or by mouse (selecting duration) and click on the staff.

Current workaround: Copy + Paste notes from a non-percussion instrument kind of works, but I'm not using this at the moment because in the Beta this started introducing corrupted bars into my file.

As of this morning I've actioned as many system and OS updates as possible on my device, reinstalled Muse Hub and Musescore (so as to rule out my custom shortcuts and default Style and Workspace), and issue is still present.

Example score is below anyway - I'm currently using a modified Timpani staff (for Kendang) in place of drum set. Try adding a drum set to the score and see how you go?

[Eitan Muir - Gamelan Piece 3 [2022-12-17].zip](https://github.com/musescore/MuseScore/files/10252962/Eitan.Muir.-.Gamelan.Piece.3.2022-12-17.zip)

**Comment by Nachtzug1** [comment] 2022-12-20 11:46
I also have this problem, but it doesn't occur in the Beta.
To specify: Win10, MS 4.0: Note Input works on all instruments, **except unpitched percussion**.
As soon as I select N or click the pencil icon, MS chrashes. This happens with percussion as a solo score or on a score with mutliple instruments.

To replicate an example:
1) create a piano score, try note input.
2) add instrument: unpitched percussion (doesn't matter which one, snare drum, bass drum, mixed percussion...)
3) try note input
4) MS chraches



I have re-installed MuseHub and MS multiple times, deleted all MuseSounds etc.
It only happens with unpitched percussion note input. (which is particularly frustrating, as I use MS almost exclusively for drum notation)

**Comment by eitanmuir** [comment] 2022-12-20 12:35
> Win10, MS 4.0: Note Input works on all instruments, **except unpitched percussion**. As soon as I select N or click the pencil icon, MS chrashes. 

Sorry to hear you're having this problem too, but also good to know it's not just me - I was a bit nervous when there were no other documented cases! Hopefully the MS team finds a solution for us soon 🙏

**Comment by Nachtzug1** [comment] 2022-12-20 12:44
Yeah, but I truly don't understand. It worked in the Beta (for me at least) and it works for all other instruments.
I just tried it on the last Nightly I had installed (30.11.2022) and it works.

@MarcSabatella any ideas? It works on your system? Is it a Win10 problem?

**Comment by zacjansheski** [comment] 2023-07-28 19:49
Is this still an issue?  (I hope not!)

In the score the non-pitched instruments are actually assigned to timpani, I wonder if this has anything to do with it.

**Comment by eitanmuir** [comment] 2023-08-02 06:39
> Reference

Forgot to check this as I haven't needed to write drum parts for a while - fixed in 4.1.1 on my system specs! Yay!

And using timpani (i.e. pitched percussion) was my workaround for note input at the time - that is, note entry worked for timpani, but my preference would have been to use an unpitched percussion staff if possible for this project. But it's all water under the bridge now :)

**Closed** 2023-08-02 08:55 UTC
Labels: needs info, crash

**Comment by Nachtzug1** [comment] 2023-12-27 12:48
Sadly with 4.2. the problem is still **not resolved.** This is so frustrating. The crash still happens every time when hitting N or clicking the pencil icon. Ostensibly this is not a problem for most, but for me it is, as I use MS almost exclusively for drum notation. 
@eitanmuir does it now work on your system?

**Comment by cbjeukendrup** [comment] 2023-12-28 01:52
[Just for the record, let's put a link to https://github.com/musescore/MuseScore/issues/20725 here 🙂]
