### ISSUE TITLE
[MU4 Issue] Save-as dialog doesn't have focus for keyboard Return/Enter

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#11859] opened 2022-06-02 00:09 UTC
Checking in to see the status of MS4 (Every couple months I do that for fun y'know :) If this was logged already, apologies
First Minute checkup:

**Describe the bug**
1) Save As dialogue for local file
2) Press enter, nothing happens. 
Press tab to switch to OK... focus goes to main MS screen. Enter should also work after typing in filenames.
This is on a linux distro

Video demonstrates:

https://user-images.githubusercontent.com/7139517/171521173-d423d87e-2fb5-47b3-8fff-c0f9320d5f9f.mp4

**Comment by MarcSabatella** [comment] 2022-06-02 04:28
FYI, this is a known issue with the specific variant of file dialog used on Linux - see https://github.com/musescore/MuseScore/issues/10836.  I'm assuming the plan is to switch to the native dialog and this problem would go away.

**Comment by Eism** [comment] 2022-06-02 05:12
I agree, this is a duplicate of  https://github.com/musescore/MuseScore/issues/10836

**Closed by Eism** 2022-06-02 05:12 UTC

**Comment by DmitryArefiev** [comment] 2022-06-21 15:24
Fixed in #12111 (should be in the next master)
