### ISSUE TITLE
Crash on remove VST3 plugin from master effects section

### ISSUE THREAD

**Issue by zob** [musescore/MuseScore#16692] opened 2023-03-07 22:10 UTC
### Issue type

Crash or freeze

### Bug description

When I try to remove a master effect (VST3) the app crashes. When it restores the session upon restart, the plugin is still there.

Plugin is Waves WaveShell1 VST3 12

Score is a choral SATB

I have attached a log file. If I understand it correctly, it seems to throw an error en trying maybe to remove the plugin but can't find it??

### Steps to reproduce

1. Create new sheet (maybe Choral SATB from template)
2. Create some music
3. Add a VST3 Master effect
4. Try to remove this effect again
5. Crash?

I tried to attach the .mscz file (I don't know if that is of any help), but attachment of that filetype is not supported here.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Windows 10

### Additional context

[MuseScore_230307_225330.log](https://github.com/musescore/MuseScore/files/10914289/MuseScore_230307_225330.log)

**Comment by zacjansheski** [comment] 2023-08-23 19:28
Is this still actual?
Does it only occur for you with the Waves VST?  We would need licenses to test.

**Comment by DmitryArefiev** [comment] 2023-08-25 14:47
@zacjansheski  I propose to close this one since another crash with Waves was logged as #17389
And also, there is another issue with Waves UI which was reverted (reopened) #15968. So we can't test it with several Waves plugins in the bundle (only one plugin)

I've tried two Waves plugins (CLA-76, Waves Tune) in 4.2 master on Win10 - **no crash**



https://github.com/musescore/MuseScore/assets/90187801/941fb3b3-a4c0-4f13-8598-df24365c37b4

**Comment by DmitryArefiev** [comment] 2023-08-25 14:48
@zob Please reopen if you will be able reproduce in 4.2 (Nightly builds)

**Closed by DmitryArefiev** 2023-08-25 14:48 UTC
Labels: needs info, needs testing, crash
