### ISSUE TITLE
Score plays pauses for some seconds when there is a section break

### ISSUE THREAD

**Issue by pacebes** [musescore/MuseScore#24637] opened 2024-09-11 11:40 UTC
### Issue type

General playback bug

### Description with steps to reproduce

Steps to reproduce:
1. Open the attached  file with MuseScore
2. Play the Score
3. Check that the play pauses for some seconds between (page 1) measure 6 and measure 3 when repeating (it also pauses between measure 6 of the page 1 and measure 1 of the page 2)
4. It does not pause if you remove the "section break"

Current behaviour:
- Play pauses before repeating the section when there is a section break at the end of the page

Expected behaviour 
- Play does not pause before repeating the section when there is a section break at the end of the page

### Supporting files, videos and screenshots

[Test musescore section break.zip](https://github.com/user-attachments/files/16963012/Test.musescore.section.break.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

No.

### Operating system

Windows 11

### Additional context

It also happens with the nightly build OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242530503, revision: github-musescore-musescore-17a8f8e

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-09-11 12:49
Duplicate of #14262

**Closed** 2024-09-11 13:15 UTC
Labels: duplicate
