### ISSUE TITLE
[MU4 Issue] Crash after adding a note, saving, then changing its pitch (with Screen Reader enabled)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13159] opened 2022-09-04 03:21 UTC
**Describe the bug**
Current MuseScore 4 builds crash for me reliably if I add a note, save, then try to change the pitch of the note just entered

**To Reproduce**
1. Open any score - or create a new one with treble clef template
2. Select first measure
3. Add a single note quarter note C5 ("N 5 C")
4. Press Esc to leave note input mode
5. Save
6. Press Down to move the pitch of the note down

** Result **
Crash

**Expected behavior**
Note should simply change pitch, no crash

**Screenshots**
![save crash](https://user-images.githubusercontent.com/1799936/188321674-02b7d22f-2585-4515-81d9-c10efe263574.gif)

**Platform information**
 - OS: Linux, Windows

**Additional context**
It was quite the process to track this down, but in the end, it's exactly this simple - on both my Linux and Windows systems.

Note, actually entering (or at least changing pitch of) a note before the save is important.  Merely editing text or adding other markings and then saving won't trigger a crash on the next pitch change.  Has to be an operation involving pitch - either adding one or changing pitch of an existing one.

Also, it's not just up/down that triggers the crash - anything that changes pitch, like adding an accidental, or dragging the note up or down.  But other operations work fine after saving - you can add notes, change duration of existing notes or move them between voices, add articulations, etc.  And these operations often temporarily fix the problem - changing pitch after doing one of these other "safe" operations causes the pitch change to work.  Until the next save, then a pitch change will again crash.

**Comment by MarcSabatella** [comment] 2022-09-04 03:58
I am now completely convinced autosave is involved.  If I start MuseScore from the command line (AppImage), the console log shows me that the autosave *does* occur after only a minute.  At least most of the time - sometimes it takes longer.  make it's based on the last autosave operation, not the last change?

Anyhow, for 100% reproducible results, then, wait for the autosave message to appear on the console.

**Comment by wizofaus** [comment] 2022-09-04 08:30
I'm not convinced at all, I sat there adjust a note pitch with the arrow key continually right through several auto-saves (during which it noticeably pauses) and not a single crash.  But I've had quite a number of crashes doing things unrelated to changing note pitch, including just selecting "edit element" from the right-click content menu.

**Comment by MarcSabatella** [comment] 2022-09-04 13:47
Could be there are other variables involved - by continuously changing pitch, you're clearly not following my original steps, so something about what you are doing differently might be preventing the crash.  It's also possible you were being deceived about autosave kicking in - autosave seems to happen less often when actively editing.  It could also be that there are *other* steps that will trigger this same crash, and yes, of course,e there are almost certainly other unrelated crashes waiting to be pinned down with steps to reproduce.

Anyhow, here is a "smoking" gun.  I did a screen recording showing the console window and MuseScore side by side while I change pitch over and over.  You can clearly see the crash occurring on the very first pitch change after the autosave:

https://user-images.githubusercontent.com/1799936/188316148-0b1d7b9a-4bc9-4cae-9fb8-ccdde6ca558e.mp4

The one thing that makes it not as clear as it otherwise would be are all the "[5996:5996:20220904,072227.684500:ERROR elf_image_reader.cc:116] no preferred header address" and similar messages that litter the console as the crash happens.  Not sure if this is a clue to the cause, or more just an effect, some normal part of the crash handling process.

But in any case there is still *any* doubt, here is the relevant excerpt from the console log:

Could be there are other variables involved - by continuously changing pitch, you're clearly not following my original steps, so something about what you are doing differently might be preventing the crash.  It's also possible you were being deceived about autosave kicking in - autosave seems to happen less often when actively editing.  It could also be that there are *other* steps that will trigger this same crash, and yes, of course,e there are almost certainly other unrelated crashes waiting to be pinned down with steps to reproduce.

Anyhow, here is a "smoking" gun.  I did a screen recording showing the console window and MuseScore side by side while I change pitch over and over.  You can clearly see the crash occurring on the very first pitch change after the autosave:

https://user-images.githubusercontent.com/1799936/188316148-0b1d7b9a-4bc9-4cae-9fb8-ccdde6ca558e.mp4

The one thing that makes it not as clear as it otherwise would be are all the "[5996:5996:20220904,072227.684500:ERROR elf_image_reader.cc:116] no preferred header address" and similar messages that litter the console as the crash happens.  Not sure if this is a clue to the cause, or more just an effect, some normal part of the crash handling process.

But in any case there is still *any* doubt, here is the relevant excerpt from the console log:

`07:22:22.918 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:23.583 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:24.239 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:24.927 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:25.571 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:26.227 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:26.893 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
07:22:27.322 | INFO  | main_thread | NotationProject | doSave: success save file: "/home/marcsabatella/.local/share/MuseScore/MuseScore4Development/new_project.mscz" 
07:22:27.552 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: pitch-down
[5996:5996:20220904,072227.684500:ERROR elf_image_reader.cc:116] no preferred header address
[5996:5996:20220904,072227.688369:ERROR process_reader_linux.cc:520] no module mappings 0x7d63190ec000
[5996:5996:20220904,072227.693090:ERROR elf_image_reader.cc:116] no preferred header address
[5996:5996:20220904,072227.693122:ERROR process_reader_linux.cc:520] no module mappings 0x7d6314e23000`

You can see it clearly - a series of perfectly normal pitch-down operations (there were dozens more before this), followed by the "doSave" operation, followed by one more pitch-down, and then the cascade of errors accompanying the crash.

No doubt whatsoever, even if there are other variables that can prevent the crash from occur, this is absolutely what is happening here.

**Comment by wizofaus** [comment] 2022-09-04 20:18
Sorry, that doesn't work for me, at least not using a debug build built from latest source.

**Comment by MarcSabatella** [comment] 2022-09-04 20:23
Could be debug builds won't show it - like if it's an unititialized variable and debug builds set things up differently.  Try the actual nightlies.  Both Linux AppImage and Windows 7z packages fail in the same way for me

**Comment by wizofaus** [comment] 2022-09-04 20:54
No luck with a regular build either.  But your repro steps only work as described if you've already saved with a name at least once (otherwise it would prompt for a name to save to etc.) - I tried that too but still no crash.  Where are you saving to? Is it worth attaching the score?

**Comment by rgreen5** [comment] 2022-09-05 08:14
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2990798632, revision: github-musescore-musescore-5d26e7f

Can't reproduce with this build either.

**Comment by DmitryArefiev** [comment] 2022-09-05 08:54
@MarcSabatella I **can't reproduce** it on Windows and Linux using latest master builds (https://github.com/musescore/MuseScore/actions/runs/2990782650 https://github.com/musescore/MuseScore/actions/runs/2990798632)

https://user-images.githubusercontent.com/90187801/188409568-3422bcdb-817e-48b4-9f60-5d8d741b8f9a.mp4

Can you try again on your side please with the latest master?

**Comment by boryskuzmenko** [comment] 2022-09-05 10:11
Can't reproduce on macOS, also

**Comment by MarcSabatella** [comment] 2022-09-05 13:57
Very frustrating!  For me, it's completely reproducible and was leading to dozens of crashes a day.  Now that I know what's going on, I can disable autosave (because that also triggers the crash) and try to be careful about what I do after saving, to work around the crash.  But most people encountering this are going to perceive this as just, the program is incredibly unstable.  In addition to the actual GitHub issues, there have also been several forum and Discord reports of people saying the program often crashes on pressing the arrow key, so even if it doesn't happen for everyone, I'm afraid it's not that rare of a problem.

Is there some way to get a "core" file out of an AppImage crash, or otherwise get some sort of crash report out of the Windows nightly builds?

I haven't set up a build environment in a long time, but if no one else can reproduce this, I guess maybe I should try that to see if I can get it to crash under the debugger.

Also, at one time it was possible to build with an "address sanitizer" enabled, that would report on uninitialized variables etc.  Is that still a thing?

**Comment by MarcSabatella** [comment] 2022-09-05 14:42
Looks like @Jojo-Schmitz has identified the crash as coming from  reference to "item->accessiblePropertyChanged()" where "item" is garbage.  And @Eism can reproduce.

**Comment by wizofaus** [comment] 2022-09-05 20:17
> Looks like @Jojo-Schmitz has identified the crash as coming from reference to "item->accessiblePropertyChanged()" where "item" is garbage. And @Eism can reproduce.

Yeah the accessibility stuff definitely introduced quite a few crashes early on, anyway sounds like it's something we should get a fix for pretty quickly, fingers crossed.

**Comment by DmitryArefiev** [comment] 2022-09-06 12:08
Fixed in #13186

**Comment by DmitryArefiev** [comment] 2022-09-06 12:14
@MarcSabatella Can you check please on your side please (in master, when fix will be merged), if it solves all related crashes?

Thanks!

**Comment by MarcSabatella** [comment] 2022-09-06 13:32
Definitely, looking forward to it!  I could be wrong, but I'm guessing there are quite a few other cases of crashes this might solve too.

**Comment by DmitryArefiev** [comment] 2022-09-06 15:28
Yes. Let's hope!

**Comment by MarcSabatella** [comment] 2022-09-06 15:34
Hmm, I see the title on the issue was changed, but I need to be clear - you don't have to have the screen reader enabled at all to see this bug.

**Comment by DmitryArefiev** [comment] 2022-09-06 16:18
> Hmm, I see the title on the issue was changed, but I need to be clear - you don't have to have the screen reader enabled at all to see this bug.

Yes I know, but enabling screen reader is the only one case when I (and others) was able to repro the crash. And Elnur found that a screen reader is involved in crash. 
That's why I asked you to recheck it on your environment. And if you will be able to repro the crash again we just reopen the issue.

**Comment by Jojo-Schmitz** [comment] 2022-09-06 16:56
And can't anymore now, with the artifact from that PR

**Comment by Jojo-Schmitz** [comment] 2022-09-06 16:57
But the unit tests are not happy with the change it seems

**Comment by MarcSabatella** [comment] 2022-09-06 18:09
I can also confirm the PR seems to fix the problem, although the test failures are troubling.

BTW, again, I wasn't running a screen reader when the crash occurred, but - I *have* run screen readers on these systems in the past (not for at least a week, with several reboots in the interim).  But I wonder if somehow having run a screen reader in the past drops some breadcrumbs somewhere that the accessibility system picks up on?

**Closed** 2022-09-12 16:04 UTC
Labels: P1
