### ISSUE TITLE
Bold font in captions

### ISSUE THREAD

**Issue by mike-lev** [musescore/MuseScore#24558] opened 2024-09-08 12:22 UTC
### Your idea

I find the readability of bold font used for captions worse than a normal font.
![Screenshot 2024-09-08 140758](https://github.com/user-attachments/assets/3c2d5ef1-382a-46fa-8c28-bb00ad3e63c5)
The characters are too tight.

### Problem to be solved

It doesn't seem to appear in previous versions.
It could be a nice feature to allow user to assign a font for captions.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-09-08 12:39
Duplicate of https://github.com/musescore/MuseScore/issues/23430

**Closed by oktophonie** 2024-09-08 12:39 UTC
Labels: feature request
