### ISSUE TITLE
[MU4 Issue] Trills, tremolos and rolls do not last for whole length of tied notes

### ISSUE THREAD

**Issue by Tem3dy** [musescore/MuseScore#14576] opened 2022-11-17 19:57 UTC
**Describe the bug**
Timpani rolls in MuseSounds only last for 4 beats, if a roll longer than that is written, the sound stops playing (it seems they cannot play longer than a single measure)

**To Reproduce**
1. Make a new score
2. Make a long timpani roll (longer than 4 beats in 4/4)
3. The sound will stop playing after the first measure

**Platform information**
 - Windows 10

**Comment by cbjeukendrup** [comment] 2022-11-17 22:38
This turns out to be a lot more general:
- it not only affects Muse Sounds Timpani, but all other instruments too, and MS Basic too
- it applies not only to rolls, but also trills and tremolos
- it is caused by ties; the second and subsequent notes in a tie chain where such an articulation is applied do not produce any sound.

**Comment by Tantacrul** [comment] 2023-05-13 11:40
I would love to see this tackled in 4.2. It's really very bad.

**Comment by zacjansheski** [comment] 2023-07-12 15:41
I believe this is no longer an issue, can we close this?

[TimpTremTrill.mscz.zip](https://github.com/musescore/MuseScore/files/12029800/TimpTremTrill.mscz.zip)

**Comment by zacjansheski** [comment] 2023-08-01 15:54
Closing, no response

**Comment by MarcSabatella** [comment] 2023-08-01 21:08
I can confirm it works in that file, but not in others.  Maybe it's unpitched vs pitched, since for timpani that trill is really justa  tremolo?  But for instance, it fails in a simple case of two whole notes tied and tirlled for flute:

![image](https://github.com/musescore/MuseScore/assets/1799936/9cc00096-19c2-4ef6-bc86-c44a84e7758a)

[trill-tie.zip](https://github.com/musescore/MuseScore/files/12234013/trill-tie.zip)

Playback just stops after the first four beats.

**Comment by Tantacrul** [comment] 2023-08-02 09:21
Is there an issue for tremolo on timpani @MarcSabatella? Is it a constant problem for that instrument? I have a feeling that can be fixed quite quickly. (Not at my machine right now to check myself)

**Comment by MarcSabatella** [comment] 2023-08-02 13:34
For me timpani tremolo works fine currently.  It's regular pitched trills that still don't play correctly for tied notes in MU4.  As noted by @cbjeukendrup above, this was true in the beta for MS Basic as well as Muse Sounds, and remains true in 4.1.1 for both MS Basic and Muse Sounds.

**Comment by Tantacrul** [comment] 2023-08-02 13:51
OK, then we need to reopen this issue then? @zacjansheski ?

The tied trill issue would be really great to fix.

**Comment by zacjansheski** [comment] 2023-08-02 14:34
The trill in Marc's score does play both bars when the trill is not on the last bar ( in issue https://github.com/musescore/MuseScore/issues/17646 )

https://github.com/musescore/MuseScore/assets/69917893/e5aff333-5b4d-48d9-bcba-f6d03ef3318e

**Comment by MarcSabatella** [comment] 2023-08-02 15:07
Wow, that's interesting - but it's not the whole story either.  I can still reproduce this problem in other scores where it's *not* the last bar.  For instance, this one - 
[trill-tie-2.zip](https://github.com/musescore/MuseScore/files/12241594/trill-tie-2.zip).  So I'm not sure what exactly triggers it, but yeah, works sometimes, doesn't work other times.

**Comment by Tantacrul** [comment] 2023-08-02 15:09
@zacjansheski - I'll leave it with you. If you think this bug is covered elsewhere, then I guess we can re-close this issue... or if Marc's most recent example warrants keeping it open, then do what you need!

**Comment by zacjansheski** [comment] 2023-08-02 15:18
That last example is an issue when using MS Basic only.  It is covered in this issue https://github.com/musescore/MuseScore/issues/18676
Let's close this one and refer to that one.

**Closed by zacjansheski** 2023-08-02 15:18 UTC
Labels: P1

**Comment by s11141827** [comment] 2024-03-10 18:39
Musescore needs to be updated so trills would play across barlines & the ties wouldn't need to be removed anymore.
