### ISSUE TITLE
[MU4 Issue] Secondary (right) click loses list selection

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#11008] opened 2022-03-31 07:52 UTC
**Describe the bug**
Not being able to secondary click an element while retaining a list selection loses the ability of MU3 to "Add to/Remove from" the selection using the select dialog.

**To Reproduce**
1. Select more than one score element using Ctrl/Cmd+click
2. Right click an element
Notice the list selection is lost

**Expected behavior**
List selection is maintained

**Additional context**
I kind of understand dropping the list selection *if* only one other item was selected; but would advocate for not dropping it to allow more advanced filtering of selected items when using the selection dialog as was possible in MU3.

**Comment by jeetee** [comment] 2022-03-31 08:12
relates to (root cause of) #10698

**Comment by wizofaus** [comment] 2022-03-31 08:13
I don't have a problem with the selection being lost if you don't have CTRL/CMD held down, but if you do, right-clicking shouldn't change the selection.  I'm not sure what the standard behaviour in other Mac apps is, but most Windows apps I've tried work that way.

**Comment by wizofaus** [comment] 2022-03-31 10:23
Ok to clarify, the expected behaviour, going by other applications etc. is:

a) if there's a list selection, and you right-click on a *selected* element, the selection should NOT change
b) if there's a list selection, and you right-click on something else, then a) if CTRL is held down, the selection should not change, otherwise b) if CTRL is not held down, the existing selection is cleared, and if you've right-clicked on an element, that becomes the new selection
c) if there's a range selection, and you right-click inside the bounds of the range selection, the selection is not change (existing behaviour)
d) if there's a range selection and you right-click OUTSIDE the bounds of the range selection, then the selection is cleared, and if you've right-clicked on an element, that becomes the new selection (not quite the existing behaviour - currently it doesn't clear the selection if you right-click on empty space outside the range rectangle).
 
This is pretty simple fix, only requires modifying a few lines of code, just want to confirm that's what we want.
@Tantacrul

**Comment by wizofaus** [comment] 2022-03-31 10:40
Actually...it's a bit more complicated than that, because at least in File Explorer and many other Windows apps, the selection doesn't clear until you *release* the mouse button.  I'm not sure why that makes sense though...

**Comment by wizofaus** [comment] 2022-03-31 10:57
...aaaand even *more* complex - in fact if you use CTRL+left-click to select multiple items, then hold down the left button on one of the selected items, whether or not the others get deselected on mouse release depends on whether you've moved the mouse or not!  And that turns out to be quite important.

**Comment by Tantacrul** [comment] 2022-03-31 11:04
> This is pretty simple fix, only requires modifying a few lines of code, just want to confirm that's what we want.
@Tantacrul

Yep. Agreed. I'll let you suggest your preferred solutions to the two complexities you pointed out and will happily test them.

**Comment by wizofaus** [comment] 2022-03-31 11:27
Ok, have put up a PR that addresses the major issues.  You can now click & drag or right-click on a selected element in a list selection and it will behave as expected.  There are still some cases that aren't perfect but are no worse than v3 at least.

**Comment by Tantacrul** [comment] 2022-03-31 19:41
Lookin' good!

**Comment by wizofaus** [comment] 2022-03-31 20:39
Alternative is to go for perfection and release some time in 2047? :-P

**Comment by RomanPudashkin** [comment] 2022-04-11 19:16
Fixed in https://github.com/musescore/MuseScore/pull/11114

**Closed by RomanPudashkin** 2022-04-11 19:16 UTC
