### ISSUE TITLE
[MU4 Issue] cant reach windows-toolbar if maximized window

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#12901] opened 2022-08-17 07:58 UTC

**Comment by mattblo** [comment] 2022-08-17 08:38
I don't know if this is exactly what you mean, but my guess is this: If you set the taskbar in Windows to "auto-hide", it will no longer appear automatically when Musescore 4 is open.

**Comment by lyrra** [comment] 2022-08-17 08:40
Exactly this. Thanks for clarifying!

**Comment by Tantacrul** [comment] 2022-10-08 15:25
Can you please provide a visual to show what the issue is? @DmitryArefiev / @jessjwilliamson - do either of you know this issue?

**Comment by cbjeukendrup** [comment] 2022-11-16 14:09
Duplicate of #10958

**Closed by cbjeukendrup** 2022-11-16 14:09 UTC
Labels: P2

**Comment by Skelbti** [comment] 2022-12-22 17:25
This behaviour still happened for me with the latest release.

**Comment by DmitryArefiev** [comment] 2022-12-26 14:44
> This behaviour still happened for me with the latest release.

Yes, #10958 is not fixed yet. Also occurs in the latest master in my side.

Thanks!
