### ISSUE TITLE
[MU4 Issue] Opening MU3 Scores with Offset Velocity Type Notes

### ISSUE THREAD

**Issue by zrksyd** [musescore/MuseScore#15239] opened 2022-12-16 20:19 UTC
**Describe the bug**
Opening a score made in MuseScore 3 that use notes with Velocity Type of Offset do not translate correctly in MuseScore 4.

**To Reproduce**
1. Create a score in MuseScore 3.
2. Create a note and change its Velocity Type.
3. Save score and open it in MuseScore 4.

**Expected behavior**
Velocity should be recalculated from Offset to User rather than using the raw Offset value.

**Screenshots**
![image](https://user-images.githubusercontent.com/6856627/208181961-cc234981-0d98-41bf-b792-f035e852c5a3.png)

**Platform information**
 - OS: Windows

**Additional context**
This was mainly noticeable with negative values, but I think positive values also yield the same issue.

**Comment by cbjeukendrup** [comment] 2022-12-16 20:26
The velocity options in MS3 are a bit of a work in progress, unfortunately. There will be a much better system in a future update, but currently it's a bit broken. Now you have one control, which basically _is_ an offset control, but _pretends_ to be an absolute control:
- 64 means "use the default"
- 64 + something means "use the default plus something" (i.e. 70 would be 6 louder than the default)
- 64 - something means "use the default minus something" (i.e. 50 would be 14 louder than the default)

**Comment by zrksyd** [comment] 2022-12-16 21:26
The reason I had opted to use Offset rather than User in MuseScore 3 is because with Offset, I still got the influence from dynamics. Like 0 in Offset was different when the dynamic is pianissimo vs forte.

**Comment by MarcSabatella** [comment] 2022-12-16 22:21
@cbjeukendrup but independently of that, it's just a bug that MU3 files don't translate velocity to be based on 64 instead of 0.  On reading of a MU3 file, all "offset" velocities should have 64 added (and then capped at 127) so that they sound the same in MU3.  This is going to negatively impact a lot of scores.

Fixing up "user" velocity would be trickier - would need to find the current dynamic and rebase according to it.  not worth it as far as I'm concerned.  But fixing offset would be important, and simple - add 64, min vs 127.

This is already reported as https://github.com/musescore/MuseScore/issues/14768

**Comment by zrksyd** [comment] 2022-12-16 23:54
Was Offset additive or multiplicative? I thought it was multiplicative, as in -100 = completely silent

**Comment by erinic04** [comment] 2022-12-17 02:02
I'm pretty sure it was additive

**Comment by MarcSabatella** [comment] 2022-12-17 19:00
Offset was definitely additive.  -100 is indeed completely silent *if* the dynamic marking was 100 or less, because then subtracting 100 leaves you at zero (there are no negative velocities).  But if the velocity was 101-127, then an offset of -100 would still be audible, if very quiet.

**Comment by RomanPudashkin** [comment] 2023-09-08 07:15
Duplicate of https://github.com/musescore/MuseScore/issues/14768

**Closed by RomanPudashkin** 2023-09-08 07:15 UTC
Labels: duplicate
