### ISSUE TITLE
Note does not play if being sustained in other piano staff

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#17881] opened 2023-06-06 16:29 UTC
### Issue type

Muse Sounds bug

### Bug description

When piano notes are being sustained in one staff, they aren't able to be played in the other. It only happens when using Muse Sounds

### Steps to reproduce

1. Put C4 whole note in treble staff of piano while using Muse Sounds
2. Put C4 quarter notes in bass staff
3. Only hear whole note in treble clef, quarter notes don't get played

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/34029777/baf2b6e3-b12e-428f-abac-b3c08e41d064

![Screenshot 2023-06-06 112534](https://github.com/musescore/MuseScore/assets/34029777/d49543d7-3210-4c38-a378-15a8d50337c3)

### MuseScore Version

4.0.2-230651553, revision: dbe7c6d

### Regression

No.

### Operating system

Windows 11

**Comment by xman2156** [comment] 2023-06-06 16:43
Also tested in nightly build 4.1.0-231570309, revision: 279de6d

**Comment by MarcSabatella** [comment] 2023-06-06 17:38
Thanks, this is also reported already in https://github.com/musescore/MuseScore/issues/15306 and several others] issues.

**Comment by cbjeukendrup** [comment] 2023-06-06 23:04
Duplicate of https://github.com/musescore/MuseScore/issues/15306. Thanks for reporting!

**Closed by cbjeukendrup** 2023-06-06 23:04 UTC
Labels: muse sounds
