### ISSUE TITLE
Pedal Marking rendering error when publishing to MuseScore.com

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#16687] opened 2023-03-07 14:40 UTC
### Issue type

Other type of issue

### Bug description

Expected behavior:
Pedal markings render correctly, like they used to in MU3

Actual behavior:
Pedal markings are much thicker and blocky than they used to be

Issue showed up in https://musescore.com/groups/improving-musescore-com/discuss/5178841

Pedal markings seem to render as polygons rather than as lines on MuseScore.com, but only on pages 2+
This is a borderline case as to whether it's a MuseScore.org or MuseScore.com issue, but it was advised to try here regardless.

Examples:
https://musescore.com/user/14923616/scores/9887770
![image](https://user-images.githubusercontent.com/20604032/223671751-19507616-3dd1-489f-b2a1-7ea8c61e637f.png)

https://musescore.com/user/33605901/scores/9931330
![image](https://user-images.githubusercontent.com/20604032/223671909-a4c22d90-cab0-4b24-9099-c68c3103042b.png)

### Steps to reproduce

1. Add pedal markings to a MU4 score, make sure the markings are on page 2
2. Publish the score to MuseScore.com (whether through the program itself or MuseScore.com's upload button)
3. Result: Pedal Lines where the whole shape is filled in instead of just the line

### MuseScore Version

4.0.1

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment] 2023-06-19 14:09
Probably resolved by #18041

**Comment by Jojo-Schmitz** [comment] 2023-06-19 17:14
And the affected score having been re-uploaded...

**Comment by DmitryArefiev** [comment] 2023-06-20 11:05
Fixed on musescore.com backend (when publish scores from **MuseScore 4.0.2**)

Closing as dupe of #15680

**Closed by DmitryArefiev** 2023-06-20 11:05 UTC
