### ISSUE TITLE
Muse Guitars - glissandi play differently on repeats

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#21703] opened 2024-02-26 18:15 UTC
### Issue type

Muse Sounds bug

### Bug description

When using Muse Guitars "Electric LP - Clean" sound, some glissandi play differently between repeats.  It seems the first time through, there is a subtle (but effective) sample of a finger sliding on the string, whereas the second time it is a full chromatic gliss.

### Steps to reproduce

1. new score for electric guitar, all defaults
2. verify sound is Electric LP - Clean
3. enter two whole notes: E above the staff, E on top space
4. add a glissando from the palette (using default chromatic playback)
5. play

Result: a subtle string slide sound

6. add an end repeat after the second bar
7. play

Result: first time through we hear the subtle finger slide; the second time we hear the full chromatic glissando

To be honest, I am not sure what I expect - maybe a less subtle finger slide sound? - but I definitely don't expect it different between the first and second time.  If you switch to the Electric LP - Lead sound, though, you hear the full chromatic gliss both times.  "Same with Electric SC - Clean".  I didn't test the others.

### Screenshots/Screen recordings

[Screen recording 2024-02-26 11.13.32 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/d23b4fe1-8560-4e8f-a3eb-7eeffd86fe24)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

### Additional context

I am calling this a regression even though Muse Guitars is new, simply because the default playback is now very different than prior to Muse Guitars.  That is, a score using default playback worked normally in 4.1 and no longer does in 4.2.

**Comment by bkunda** [comment] 2024-02-27 14:14
@RomanPudashkin @matthewreadbass not sure which one of you is right for this fix so tagging you both :-)

**Comment by matthewreadbass** [comment] 2024-04-15 09:29
I've just had a look at this, but the issue isn't as it would initially seem.

I am able to recreate the bug, but this behaviour isn't coming from the Portamento not playing after the first repetition. If the Glissando playback style is set to "Portamento", you will get a portamento on both repetitions. However, to recreate the issue you need to set the Glissando playback style to "Chromatic".

So the issue isn't that the portamento only plays once, but rather that the portamento plays at all despite the Glissando playback style being set to "Chromatic".

I imagine that this is one for @RomanPudashkin

I have recorded a video to show the issue, but even at top speed it takes about a minute to show and the video appears to be too big to upload. I will try again...

**Comment by matthewreadbass** [comment] 2024-04-15 10:09
Strangely enough, this issue only seems to affect guitars

**Comment by DmitryArefiev** [comment] 2024-07-25 09:45
I think (can't check with old MuseSounds Guitars and old musesampler), it was always with MuseSounds Guitars. Deleting regression label

**Comment by bkunda** [comment] 2024-07-29 07:49
> So the issue isn't that the portamento only plays once, but rather that the portamento plays at all despite the Glissando playback style being set to "Chromatic".

From memory, I think the muse guitars were given some special treatment in this regard; i.e. the "portamento" was hardcoded to be their default (at the library end). This might have been deemed necessary for bends?? @sampleeditor may be able to confirm this. 

If this is true though, then it seems the portamento override at the library end is not being triggered on repeats. 

This would also confirm @DmitryArefiev's observation, that this issue was always present with MuseSounds Guitars. 

Given there is a workaround (manually set the glissando playback option to "portamento"), and our 4.4 timeline, I think we'll need to bump this one unfortunately.

**Comment by sampleeditor** [comment] 2024-08-01 13:00
@bkunda We did add legato_phase=glissando to the guitars to make them default to samples on glissandi. Interesting that the repeat puts it back to chromatic. I'll check if we can remove the code without affecting bends, but the default will likely be MIDI generated slides and the sampled slides will be less discoverable.

**Comment by sampleeditor** [comment] 2024-08-02 14:22
Latest beta 0.9.9 in Hub 2.0 should solve and close this issue.

**Closed by sampleeditor** 2024-08-02 14:22 UTC
Labels: P2, playback, muse sounds

**Comment by Iurig** [comment] 2025-02-23 13:38
I found an issue that might be related to this. When using soundfonts and sliding into a note on a repeat, the second repeat doesn't play the slide or the note. 

Wondering if I should open another issue or if this goes here.
