### ISSUE TITLE
[MU4 Issue] MS4 takes considerably longer than MS3 to open long scores

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14056] opened 2022-10-26 11:20 UTC
**Describe the bug**

On my PC, the attached score opens, and is available for playback, in MS3 within 5 secs of double-clicking on it in the "Open" window. In MS4 it takes at least 18 secs from clicking on the "conversion" dialog; more than 3 times as long.

[beethoven_sym6.zip](https://github.com/musescore/MuseScore/files/9868903/beethoven_sym6.zip)

**Expected behavior**

A score should open, and be available for playback, in MS4 in a time frame comparable to MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3326178321, revision: github-musescore-musescore-cea74a0

(Intel Pentium CPU 2020M @ 2.40GHz × 2 / 3.7 Gb RAM.)

See also, #11035.

**Comment by RobFog** [comment] 2022-10-26 11:40
See also #11392.

**Comment by Tantacrul** [comment] 2022-10-27 21:47
This is a known issue that (as @RobFog points out) is already logged. We have to do a bit of extra interpretation when brining in older scores, although we're trying to get the wait down (and have done so... but need to do more).

Closing as a duplicate.

**Comment by Tantacrul** [comment] 2022-10-27 21:47
Duplicate of https://github.com/musescore/MuseScore/issues/11392.

**Closed by Tantacrul** 2022-10-27 21:47 UTC
