### ISSUE TITLE
[MU4 Issue] Moving selection gets deselected

### ISSUE THREAD

**Issue by Giadima44** [musescore/MuseScore#11302] opened 2022-04-22 13:36 UTC
**Describe the bug**
Selecting a large cluster or selecting multiple bars and clicking on something within selected measures to move everything, deselects selected, and moves only the thing I have selected

**To Reproduce**
1. Shift+LMB on a large number of measures
2. Click and hold on a random entity( a single note for instance)
3. Selected measures will be deselected, and selected note will be the only thing selected.

**Expected behavior**
Selecting a large number of measure or entities will allow me to click and drag everything and move them in different directions.

**Platform information**
 - OS: Manjaro KDE, Arch Linux

**Comment by MarcSabatella** [comment] 2022-04-22 14:03
To be clear: there is no such feature; this is working as intended.  Cut and paste is the way to move range selections.  But, a new feature to allow drag to used as an alternative could certainly be considered.

**Comment by Giadima44** [comment] 2022-04-26 22:42
I think my explanation might have been a little vague, I am talking specifically about selecting a large group of notes and changing pitch.

**Comment by Tantacrul** [comment] 2022-04-29 18:38
If fixed, then I'll close this.

**Closed by Tantacrul** 2022-04-29 18:38 UTC
