### ISSUE TITLE
[MU4 Issue] "Define" shortcut button becomes disabled after clearing a shortcut

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9088] opened 2021-09-09 06:24 UTC
This issue is demonstrated at 01:26 in this video: https://www.dropbox.com/s/q5vmcre91bkzhrv/define-shortcut-issues.mov?dl=0

**To replicate:**
1. Click on a shortcut action item in the Preferences > Shortcuts menu
2. Press the "clear" button
3. Click on any other shortcut action item
4. Click back to the initial shortcut action item (the one just cleared). 
The "Define" button is now greyed out

**Expected behaviour:**
The "Define" button should never become disabled.

MacOS 11.5.2 on MacBook Air M1

**Background context**
Scope of this issue redefined in light of discussion below

**Comment by wizofaus** [comment] 2021-09-09 06:26
dupe of https://github.com/musescore/MuseScore/issues/8890 ?

**Comment by bkunda** [comment] 2021-09-09 06:27
#8890 is both closed and has to do with crashes, which is not the issue here.

**Comment by wizofaus** [comment] 2021-09-09 06:28
Oops, sorry, https://github.com/musescore/MuseScore/issues/8898
I'd be interested if you had the problem that defining a new shortcut sequence for an action didn't seem to take affect until you restarted the app in particular (which I only mentioned in the comment on that issue, but arguably is the biggest issue there).

**Comment by bkunda** [comment] 2021-09-09 06:33
You are right on both fronts: the issue definitely seems connected to the search filter, and shortcut commands do not seem to work unless the app is restarted. 
The issue of the disabled "define" button persists for me, evening without any active search filters.

**Comment by wizofaus** [comment] 2021-09-09 06:53
Yes, that's not related to whether you have a search filter.  But yeah the whole thing is pretty broken, there's actually an even bigger problem which is that it's missing 100s of the possible actions that MU3 supported too, which I've been working on.
But I suspect it's even missing many of the actions that MU4 does support but there just happens not to be any shortcuts defined for by default.

**Comment by bkunda** [comment] 2021-09-09 07:05
Absolutely. Please let me know how you get on with those additional actions, as (at some point) it would be good to ensure they all confirm to a consistent naming convention (such as that I've proposed in #8746).

**Comment by Tantacrul** [comment] 2022-05-01 14:08
The specific issue mentioned here looks to be working now. @bkunda - can you confirm? If I'm wrong, please reopen.

Incidentally, I created an uber issue for remaining issues with this Shortcuts panel. https://github.com/musescore/MuseScore/issues/11474

**Closed by Tantacrul** 2022-05-01 14:08 UTC
Labels: P2

**Comment by bkunda** [comment] 2022-05-02 04:29
> The specific issue mentioned here looks to be working now. @bkunda - can you confirm? If I'm wrong, please reopen.
> 
> Incidentally, I created an uber issue for remaining problems with this Shortcuts panel. #11474

Yes, this is now working.
