### ISSUE TITLE
Allow placing player numerals vertically after their instrument labels in single staves

### ISSUE THREAD

**Issue by yuki0035** [musescore/MuseScore#24338] opened 2024-08-31 03:50 UTC
### Your idea

Instrument player numerals are placed vertically after their instrument labels in some editions. Right now you can only simply place them horizontally side by side.
![3](https://github.com/user-attachments/assets/ba3b23a9-aba3-4847-a892-eb8b7dc46a28)
![21](https://github.com/user-attachments/assets/74fe0f94-0066-4cf5-b42d-4c6cf35bc508)

### Problem to be solved

By utilising this feature, you can use more label styles and saving horizontal space.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Dima-S-Jr** [comment] 2024-08-31 06:19
Duplicate of #18775

**Closed** 2024-08-31 06:23 UTC
Labels: duplicate, feature request
