### ISSUE TITLE
Add an option to disable selection-based instrument playback

### ISSUE THREAD

**Issue by 12joan** [musescore/MuseScore#18819] opened 2023-07-27 10:59 UTC
### Your idea

Add an option in preferences to disable the behaviour added in https://github.com/musescore/MuseScore/pull/11187.

I'd be happy to attempt a PR for this if it's something we decide we want. I noticed there are currently very few preferences affecting playback, which I suspect is an intentional design decision to limit complexity, so I wanted to ask first. But if it's a choice between adding an option and adding a separate playback control (which was one suggested alternative), I think adding an option is the simpler solution for both users and developers.

### Problem to be solved

As @MarcSabatella noted when this feature was first suggested in https://github.com/musescore/MuseScore/issues/10795, the new behaviour of soloing instruments based on a selected measure is difficult to adapt to, since it conflicts with the previous ability to set the playback position by clicking a measure.

I still haven't adjusted. In fact, I'm more likely to click a measure and then click outside it to negate the selection. I think the reason for this is [Fitts's law](https://en.wikipedia.org/wiki/Fitts's_law). Selecting a single note takes longer than selecting a measure because the touch target is so much smaller. Setting the playback position by clicking a measure was far better UX in most situations.

### Prior art

See the discussion in https://github.com/musescore/MuseScore/issues/10795

### Additional context

CC @Tantacrul @RomanPudashkin

**Comment by MarcSabatella** [comment] 2023-07-27 13:35
FWIW since I was mentioned - I am *not* in favor of adding an option to *disable* this very useful feature.  That's the wrong solution.  I simply want to find a way to have my cake and eat it too - to make it so I can solo a selection easily when I want, and also want to be able to do "normal" playback more easily.

For the record, I currently am in the habit of clicking something other than a note - like a click or rehearsal mark or whatever - which works well.  Or selecting the measure then pressing Esc, which clears the selection but leaves the playback point selected.  So I'm more or less over it myself, but I still recognize it's an issue for others.

There have been a number of other discussions where alternatives have been proposed, but I don't see a currently open issue here on GitHub, so I guess this as good a place as any right now.  Then the discussion can be moved elsewhere if it's considered more appropriate.

My previous suggestion that soloing should require something *other* than just a single measure of a single staff is still a possibility.  So selecting *multiple* staves, or multiple measures on a single staff, could still trigger the soloing.   I won't claim this is great design, but it's very simple, and as I mention, similar to how we treat clef, key, or time signature change.

The other suggestion I've made elsewhere is that there be two different commands - one that solos the selection and one that doesn't.  One could be assigned to Space, the other Shift+Space, and you could also customize the toolbar to show either or both buttons as you prefer.  We could leave everything as is for the sake of discoverability of the soloing feature, but then if someone wishes to reverse the assignment of Space and Shift+Space to do the non-soloing version more easily, that's simple within the existing framework.

Or a related suggestion, have a single command as far as the UI goes, but have a toggle button to control whether the default operation is soloing or non-soloing, and whichever way the toggle is, make it so pressing Shift provides the other behavior (so internally there are presumably still two comm.  So basically, it's similar to an option to disable the soloing, except that it is never *truly* disabled in that you can always get the soloing by pressing Shift.  Again, not necessarily great design, but somehow does seem practical.

A complicating factor to consider: another common request is for a special version of the play command that doesn't continue where playback left off if selection hasn't changed but that always returns to the selection.  So it might be nice to consider designs that allow for that as well.  Like maybe *three* versions of the play command...

**Comment by 12joan** [comment] 2023-07-27 13:45
@MarcSabatella Thanks for explaining your position. Upon reflection, perhaps having multiple commands wouldn't be too bad. Especially if the command for the current behaviour was branded as "Play with selected instruments soloed" and reused as much of the other command's logic as possible. Going foward, we could define a sort of inheritance tree of play commands, each adding its own unique twist, but sharing the same core logic to prevent the behaviour of each command from diverging unintentionally.

I searched for but couldn't find any other issues discussing this (it was all I could do to find the PR that added the behaviour). If you can link them here, or edit my original post to add them under "Prior art", I'd be very interested to read what others have said on the matter.

**Comment by ShibuyaCyana** [comment] 2023-08-11 10:40
@12joan I'm using the method of selecting a measure and then click somewhere blank, like between staffs, then press play - then MS4 would play the whole system from the selected measure, much like in MS 3.x, with only a click (on a huge target) away. I was having the same issue for a few minutes when switched to MS4, then find out this quite satisfying method with a much handier solo solution.

**Comment by cbjeukendrup** [comment] 2024-04-30 13:29
Closing as superseded by #22634.

(One could argue that #22634 is a duplicate of this issue and thus should be closed instead, but this one has a lot of discussion and that one is small and clean.)

**Closed by cbjeukendrup** 2024-04-30 13:29 UTC
Labels: feature request
