### ISSUE TITLE
"Enter" key does not close "Add measures"

### ISSUE THREAD

**Issue by irwir** [musescore/MuseScore#20997] opened 2024-01-13 14:37 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In Windows dialogs commonly tie `Esc` key to `Cancel` button and `Enter` key to `Ok`. For example, file open dialog in MuseScore.

`Add `> `Measures` dialogs cannot be closed with `Enter` key even when `Ok` button has input focus (space bar will close) - this is the main reason for using a bug report , not a feature request.

### Steps to reproduce

Try to add measues in any score (I used one stave scores).

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2024-01-13 15:23
Duplicate of #12222. Thanks for reporting!

**Closed by cbjeukendrup** 2024-01-13 15:23 UTC
Labels: UX/interaction
