### ISSUE TITLE
Measure Properties for Multiple Bars

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#23601] opened 2024-07-12 15:29 UTC
### Issue type

Choose option...

### Description with steps to reproduce

I want to change the real numbers of counts in several bars, but when I change it, just the selection's first measure's props are changed.

### Supporting files, videos and screenshots

![grafik](https://github.com/user-attachments/assets/cbeecff5-e105-4dd8-9f3c-08c35e3265ed)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment] 2024-07-16 13:22
Just to be clear, are you wanting to change the measure properties for a selected range of measures (all at the same time)?

**Comment by bkunda** [comment] 2024-07-16 13:25
It looks like you already raised this here https://github.com/musescore/MuseScore/issues/17197
It also seems Seems related to (perhaps even a duplicate of) https://github.com/musescore/MuseScore/issues/22128
The latter seems to contain the most helpful information, so we will need to close these other ones as duplicates.

**Closed by bkunda** 2024-07-16 13:25 UTC
Labels: needs info, waiting reply from user

**Comment by Lenbus** [comment] 2024-07-16 16:05
> It looks like you already raised this here #17197 It also seems Seems related to (perhaps even a duplicate of) #22128 The latter seems to contain the most helpful information, so we will need to close these other ones as duplicates.

Haha, completely forgot about that 😜 Sorry for bringing that up again… 🫣
