### ISSUE TITLE
[MU4 Issue] MuseScore playback causes crashing at a certain measure of the score.

### ISSUE THREAD

**Issue by Zanctarian** [musescore/MuseScore#14757] opened 2022-11-25 20:05 UTC
**Describe the bug**
With one of my scores, MuseScore crashes every time I try to play a certain measure. It has happened every time I tried it.

**To Reproduce**
1. Download the score and open it
2. Go to measure 66 or 67 (a few measure before the trouble measure)
3. When it hits **measure 71**, MuseScore crashes.

**Note:** _It often crashes just by clicking measure 66._

**Expected behavior**
MuseScore doesn't crash when handling playback.

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223291259, revision: github-musescore-musescore-**3eb4117** (aka discord announcement multithread version)
^ auto generated from MuseScore

Actual OS installed on PC: **Windows 11 Enterprise | Version 21H2 | Build 22000.1219**

**Videos**
In this video -> I show it crashing when I click a measure. Measure 66 specifically.
https://user-images.githubusercontent.com/44514121/204049822-8d5c68c2-5250-4f64-902e-baefcc7d534f.mp4

In this video -> I wait for the audio samples to load before playing from measure 67, where it crashes when it reaches measure 71.
https://user-images.githubusercontent.com/44514121/204049825-7b6d02e4-db4c-4603-8024-1bf8a4c83e14.mp4

**Downloads**
The trouble score:
https://cdn.discordapp.com/attachments/666512423318192141/1045789734162673855/The_Plagues_-_copy.mscz

**Comment by erinic04** [comment] 2022-11-26 06:44
I've reported this in issue #14181. Thanks for reporting though! The additional score might help to fix it

**Comment by cbjeukendrup** [comment] 2022-11-29 23:26
@Zanctarian I cannot reproduce this issue tonight on macOS, so maybe it is fixed by the latest updates. Could you please check if it's fixed for you too?

**Comment by erinic04** [comment] 2022-11-30 04:54
My other scores with this problem are also fixed so I think it's good now

**Comment by erinic04** [comment] 2022-12-02 06:16
It's not good, at least on Windows

**Comment by CodeSpoof** [comment] 2023-01-30 20:08
Have got the same problem with my score, but on Ubuntu 22.04. In my score, it completely depends on the Timpani instrument being switched to MuseSounds, without that, playback works.
<details>
  <summary>Log</summary>
  
  This is what I get:
  
  ```javascript
  20:50:19.992 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: play
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
20:50:19.994 | INFO  | 140314081744448 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
munmap_chunk(): invalid pointer
[1462091:1462091:20230130,205021.685272:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.685907:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.685925:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db49f9000
[1462091:1462091:20230130,205021.685994:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686005:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db49f2000
[1462091:1462091:20230130,205021.686184:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686197:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db49ea000
[1462091:1462091:20230130,205021.686360:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686384:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db49e4000
[1462091:1462091:20230130,205021.686447:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686459:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db43d2000
[1462091:1462091:20230130,205021.686534:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686557:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db43be000
[1462091:1462091:20230130,205021.686658:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686677:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3ecf000
[1462091:1462091:20230130,205021.686746:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686760:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db49de000
[1462091:1462091:20230130,205021.686824:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686844:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3ebf000
[1462091:1462091:20230130,205021.686943:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.686958:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3eb3000
[1462091:1462091:20230130,205021.687047:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687065:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db43b6000
[1462091:1462091:20230130,205021.687237:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687249:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3ea4000
[1462091:1462091:20230130,205021.687317:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687327:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3e84000
[1462091:1462091:20230130,205021.687384:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687391:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3e6d000
[1462091:1462091:20230130,205021.687445:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687452:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db3abf000
[1462091:1462091:20230130,205021.687811:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687818:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db36b9000
[1462091:1462091:20230130,205021.687932:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687939:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db17a9000
[1462091:1462091:20230130,205021.687986:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.687992:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db2ddc000
[1462091:1462091:20230130,205021.688040:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.688047:ERROR process_reader_linux.cc:520] no module mappings 0x7f9db2db2000
[1462091:1462091:20230130,205021.688542:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.691149:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.691376:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.691550:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.691603:ERROR elf_image_reader.cc:116] no preferred header address
[1462091:1462091:20230130,205021.691613:ERROR process_reader_linux.cc:520] no module mappings 0x7f9da5cd8000
[1462091:1462091:20230130,205021.694601:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.694707:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.694800:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695111:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695284:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695530:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695626:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695725:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695821:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.695920:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696014:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696089:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696172:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696248:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696353:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696468:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696563:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696656:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696740:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696818:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696894:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.696970:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697046:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697120:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697236:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697426:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697517:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697596:ERROR elf_dynamic_array_reader.h:61] tag not found
[1462091:1462091:20230130,205021.697678:ERROR elf_dynamic_array_reader.h:61] tag not found
/tmp/.mount_MuseScvTF4jV/AppRun: Zeile 26: 1462078 Abgebrochen             (Speicherabzug geschrieben) "${APPDIR}/bin/mscore4portable" "$@
  ```
  
</details>

**Comment by Bekreth** [comment] 2023-03-04 10:50
I'm also experiencing this issue.  I'm running Ubuntu 22.04 with MuseScore 4.0.1.  I've been working on a piece for a while now with about a dozen instruments and wasn't having any issues until I started doing note input for a Tuba at measure 64.  Now I'm unable to edit or click any measures 64 or greater without crashing the program.  Is it just a coincidence that my score keeps crashing at such a round number?

**Comment by Jojo-Schmitz** [comment] 2023-03-04 11:15
The intially reported crash doesn't seem to happen with  4.0.2 pre-release, but that does something to the score, it modifies it it, shortly after opening it, seems it attempts to fix something.

So for @CodeSpoof's and @Bekreth's issue we'd need the scores.

**Comment by Bekreth** [comment] 2023-03-04 11:29
I was able to fix my primary score by deleting the offending measures and re-notating them (previously I'd been doing some pretty heavy copy/pasting of similar parts which seems to have corrupted them in some way).  I did isolate down the offending section in a separate score.

I'm able to consistently able to get this score to crash by 
* Loading the score and waiting for the audio samples to load
* Clicking measure 12 on the tuba line

[crash_test.mscz.zip](https://github.com/musescore/MuseScore/files/10888164/crash_test.mscz.zip)

**Comment by Jojo-Schmitz** [comment] 2023-03-04 11:33
No crash here, as said in a 4.0.2 prerelease

**Comment by zacjansheski** [comment] 2023-07-13 21:20
I am not able to reproduce on any OS at this time (on Windows or elsewhere).

Closing

**Closed by zacjansheski** 2023-07-13 21:20 UTC
