### ISSUE TITLE
4.0.2 (prerelease) seems to modify some scores directly after load

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#16656] opened 2023-03-04 11:28 UTC
### Issue type

UI bug

### Steps to reproduce

1. Open scores that didn't open properly or crashed in 4.0.1
2. See that they do open (and not crash) in 4.0.2
3. Notice that shortly after loading it, there's an asterisk next to its name, indicating that it has been modified (and if you wait long enough it vanished, after having created an autosave file)
4. Close it and notice that you're asked to save changes
5. Save those changes
6. Open with 4.0.1 and notice that the score previously not opening now does, o previously crashing not doesn't anymore

### Screenshots/Screen recordings

File sizes before:
![image](https://user-images.githubusercontent.com/1786669/222897969-d2fae7f1-e22e-4bd9-a5a1-6ea0a2ba2751.png)
and after
![image](https://user-images.githubusercontent.com/1786669/222898042-c9911d5b-e2a1-4b0f-9b75-b6dfb6bc6fa4.png)
So a huge loss of data, some 2/3 for the score and the parts

### MuseScore Version

4.0.2-230601206

### Regression

Yes, this used to work in a previous version of Musescore 4.x  (Well, those didn't open them or crashed on them, but didn't modifiy them)

### Operating system

Windows 11

### Additional context

Fixing corruptions on load is fine, but the user should **explicitly** be told about it

One sample score can be found at https://github.com/musescore/MuseScore/issues/14757#issue-1464898111, actually https://cdn.discordapp.com/attachments/666512423318192141/1045789734162673855/The_Plagues_-_copy.mscz

**Comment by cbjeukendrup** [comment] 2023-03-04 12:14
We don't do any automatic corruption fixing yet, as far as I know. However, what we have always done in 4.0.x, is loading the sounds, and if some sounds cannot be loaded, use replacement sounds, which marks the file as unsaved. In MuseScore 4.1, we are planning to add some messaging about that, and to give some options about what to do.

I don't immediately have an explanation for the file size difference, I'm looking into that now.

**Comment by Jojo-Schmitz** [comment] 2023-03-04 12:16
Also the fact that after that these score do load and wirk just fine in 4.0.1?

**Comment by cbjeukendrup** [comment] 2023-03-04 12:58
The problem with this file is that it was created in an unreleased version of 4.0.0, which still had a different file format with regard to excerpts. Therefore, any released version of MuseScore 4 is unable to read this file properly. I think it does not make much sense to reason about this score, since it is invalid for that reason.

However, I can confirm that the reason that the file is marked as unsaved is indeed that it switches to MS Basic while loading the sounds. The reason that it does that, is probably that something changed in the audio settings file format. I seem to remember that there have been some changes before the release of 4.0.0. 
Anyway, the switch to MS Basic is probably indeed the reason that the score does not crash in 4.0.1 anymore after opening it in 4.0.2.

The file size loss is caused by the different file format for excerpts; when opening this score in any released version, it can't read the excerpts, although it does see that the excerpts must have existed. That results in strange empty excerpts, which are saved to the file instead of the original excerpts that had the old format.

So, all mysteries solved :)
I think we can close this issue, since adding a message about missing sounds is planned already anyway.

For what it's worth, here is a copy of the score that does use Muse Sounds and should work fine in 4.0.1: 
[The_Plagues_-_copy_copy.mscz.zip](https://github.com/musescore/MuseScore/files/10888370/The_Plagues_-_copy_copy.mscz.zip)
I have removed the old-formatted excerpts from it.

**Closed by cbjeukendrup** 2023-03-04 12:58 UTC
Labels: UI, regression

**Comment by Jojo-Schmitz** [comment] 2023-03-04 13:20
OK, thanks for the investigation and sorry for the noise
