### ISSUE TITLE
[MU4 Issue] Scores from MS 3.6.2 don't play their first notes

### ISSUE THREAD

**Issue by SeaSon7ary** [musescore/MuseScore#14863] opened 2022-12-01 12:41 UTC
**Describe the bug**
The first note of a score created in MS 3.6.2 won't play, regardless whether I'm using MS Basic or Muse Sounds. Making changes on the first notes will solve problem. Scores from MuseScore 2.x don't have this bug.

**To Reproduce**
1. Open a score from MS 3.6.2
2. Click play and hear the first note being skipped
3. Make change to the first note (e.g. alter its pitch)
4. Hear the first note being played

**Expected behavior**
The first note should play normally without needing me to change anything.

**Video**

https://user-images.githubusercontent.com/102852987/205054898-fecb6e94-f1f7-4abb-8d9e-79b0fc7ceb87.mp4

**Platform information**
 OS: Windows 11 21H2

**Comment by DmitryArefiev** [comment] 2022-12-01 13:09
It should be fixed already. I can't reproduce in latest master (RC build)

Can you try on this build please?

https://github.com/musescore/MuseScore/actions/runs/3591290846

**Comment by SteveBlower** [comment] 2022-12-01 13:29
Seems a duplicate of #14387

My testing confirms the problem is fixed in the latest nightlies.

**Comment by DmitryArefiev** [comment] 2022-12-01 20:55
@SteveBlower Thanks for testing! 

@SeaSon7ary Please reopen if it still occurs

Closing

**Closed** 2022-12-01 20:55 UTC
Labels: needs info
