### ISSUE TITLE
Wrong placement of grace notes in upgraded MS3 file.

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#17061] opened 2023-03-29 10:44 UTC
In a [MS3 score](https://github.com/musescore/MuseScore/files/11099626/grace-notes.zip) there are two, similar, notes in voices 1 and 2 and these notes have grace notes:
![Screenshot_20230329_124153](https://user-images.githubusercontent.com/48352523/228509291-ef3631c8-1c08-41ae-9f3d-c298b89fbfaf.png)

When opening this file in MS4 the grace notes are moved:
![Screenshot_20230329_120805](https://user-images.githubusercontent.com/48352523/228501257-bbecd75b-215f-4bb9-b183-6e5b480a0e5f.png)

(I seems to be a regression to me :wink:)

BTW, this example comes from the clarinets 1 and 2 in Hoe-Down.

**Comment by oktophonie** [comment] 2023-03-29 10:56
It's "by design" in the sense that the previous MU3 behaviour happened accidentally. The grace notes wouldn't be aligned if the second voice were an octave lower, for example (because of extra space created by the ledger lines). The behaviour is different now because grace notes are no longer allowed to overlap each other, which brings other spacing benefits but appears as a regression in this instance.

We still need a way of specifying whether grace notes should align in different voices or not though, so this is effectively a feature request.

**Comment by njvdberg** [comment] 2023-03-30 10:29
So I suppose a solution will take some time (as in more then a few months)?
In that case I will find another solution for the particular case. But if the solutions can be expected I can wait.

**Comment by oktophonie** [comment] 2023-03-30 10:34
Indeed it will.

**Comment by oktophonie** [comment] 2024-08-15 13:57
Closing as covered by https://github.com/musescore/MuseScore/issues/15326

**Closed by oktophonie** 2024-08-15 13:57 UTC
Labels: P2, feature request, engraving
