### ISSUE TITLE
Text lines: Text properties are missing from the Text section

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18730] opened 2023-07-20 15:13 UTC
### Description

In the transition from MS3 to MS4, the text properties of Text lines have been lost from the __Text__ section of the __Properties__ panel. i.e.

![text_properties](https://github.com/musescore/MuseScore/assets/87246583/ec47aaea-cca8-4753-a4f6-7837d1ff3d34)

This means that the text properties of text lines are now controlled by _only one style_, i.e. "Text line" (Format > Style > Text styles). 

But text-lines may be of various types. In the guitar world, for example, you may have Capo lines, Fingering lines (three different types with different font properties), harmonics lines, and more besides.

These were all possible in MS3 because each textline had its own text properties in the Inspector. This facility has been lost in MS4.

The full range of text properties needs to be reintroduced into the __Properties__ panel for textlines.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

**Comment by oktophonie** [comment] 2023-07-20 15:31
See #18638 (now closed) for a possible alternative.
See also the related issue https://github.com/musescore/MuseScore/issues/17074

**Comment by cbjeukendrup** [comment] 2023-07-20 16:01
Isn't this a duplicate of #14238?

**Comment by oktophonie** [comment] 2023-07-20 16:02
Even better!

**Closed by oktophonie** 2023-07-20 16:02 UTC
Labels: P2, UI, feature request, regression_ms3
