### ISSUE TITLE
Can't open mscz files whose paths contain non-ascii characters in explorer

### ISSUE THREAD

**Issue by CarlGao4** [musescore/MuseScore#24258] opened 2024-08-28 11:36 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Rename an existing mscz file to a string containing non-ascii characters 
![IMG_2079](https://github.com/user-attachments/assets/2d8985d5-eb4b-4020-9fa0-f033d42811a9)
2. Double-click it in Windows Explorer. And the loading window shows a different name (Actually, it is the original name encoded with UTF-8 then decoded with coding of current code page) 
![ADC457F81C96BC6E540812A3F4D70786](https://github.com/user-attachments/assets/0d0a537a-89ea-4f12-bc2b-58b20e079d78) ![IMG_2082](https://github.com/user-attachments/assets/dabfe60d-a7df-42fa-b114-2bab457fa539)

This only affects the process of double-clicking in explorer. These files can be opened by the open dialog or from home page in MU4.4. So I assume that this is a bug that command parameters parser uses wrong coding.

### Supporting files, videos and screenshots

See above

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment] 2024-08-28 11:38
Duplicate of https://github.com/musescore/MuseScore/issues/23811. It will be fixed soon

**Closed by RomanPudashkin** 2024-08-28 11:38 UTC
Labels: regression MS4, crash

**Comment by JesseZ332623** [comment] 2024-08-28 13:00
Yes, the same problem happens to me, but opening non-ASCII named files from within the software is no problem. (LOL)
