### ISSUE TITLE
No bend in playback when the bend starts from the tied note

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#25159] opened 2024-10-14 12:02 UTC
**Steps**
1. Open the score
2. Play it 
3. Pay attention to there's no bend in playback

Reproducible on both MS Basic and Musesounds 

**Screencast**

https://github.com/user-attachments/assets/dbc8336f-ed7c-4eb6-83db-bb67363c96f5

Tested on macOS, MS Studio 4.4.3

**Comment by RomanPudashkin** [comment] 2024-10-14 12:03
Duplicate of https://github.com/musescore/MuseScore/issues/21345

**Closed by RomanPudashkin** 2024-10-14 12:03 UTC
Labels: P1
