### ISSUE TITLE
[MU4 Issue] (Metronome) "Enable count-in when playing" not working

### ISSUE THREAD

**Issue by RobH1964** [musescore/MuseScore#14511] opened 2022-11-14 01:41 UTC
**Describe the bug**
"Enable count-in when playing" not working (for the metronome)

**To Reproduce**
1. Start a score
2. Put in some notes
3. Enable "count in-when playing"
4. Listen to it not count in

**Expected behavior**
A one-bar metronome count in (an optional two-bar count in would be better!)

**Platform information**
 - OS: Linux Mint

**Comment by cbjeukendrup** [comment] 2022-11-14 07:20
Duplicate of #9183. Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-14 07:20 UTC

**Comment by scorster** [comment] 2024-02-08 05:21
>> Duplicate of https://github.com/musescore/MuseScore/issues/9183. ???

Not sure I follow. [Issue 9183](https://github.com/musescore/MuseScore/issues/9183) pertains to museScore 3.

To me it's shocking that this feature was dropped. And more so that it's designated as "not planned." 

Can that possibly be true?

**Comment by jeetee** [comment] 2024-02-08 07:42
> Not sure I follow. [Issue 9183](https://github.com/musescore/MuseScore/issues/9183) pertains to museScore 3.

It doesn't. Open issues all pertain to MuseScore 4. It was entered when the initial state of 4.0 development still looked like MS3, but it very much remains an open request for MS4.

**Comment by scorster** [comment] 2025-03-22 19:50
Not planned ...? 

Maybe 2.5 years later is a good time to add it to the plan.

Meanwhile users on .org log requests for count-in for MuseScore Studio. There were two just this week. Check item 3 in this post:

     https://musescore.org/en/node/376647


The lack of 4.x count-in is a deal breaker for many. 

     https://musescore.org/en/node/363896
     https://musescore.org/en/node/364838
     https://musescore.org/en/node/357779
     https://musescore.org/en/node/342257
     https://musescore.org/en/node/345780

**Comment by cbjeukendrup** [comment] 2025-03-22 21:10
> Not planned ...?

See my comment; it is a duplicate of https://github.com/musescore/MuseScore/issues/9183, and this issue is from the time that GitHub had no dedicated "close as duplicate" button yet.
