### ISSUE TITLE
Dialog with single input field does not respond to enter or return key

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#18642] opened 2023-07-16 14:16 UTC
### Issue type

UI bug

### Bug description

Input dialogs with a single field already use autofocus (good!), and pressing the Enter or Return key (those are two different keys) should submit my input and close the dialog successfully. Instead, keyboard focus disappears, which proves that the keyboard input is handled by *something*, but not in the right way.

### Steps to reproduce

Steps to reproduce:
- Open Musescore
- Select the end of a bar
- Navigate the menu "Insert > Bars > After selection" (I'm guessing the English texts, the actual German labels are: "Hinzufügen > Takte > Nach der Auswahl einfügen…")
- Sanity check: A new dialog has opened, asking for the amount of bars to be inserted, with autofocus already on the only input field of the dialog (good!)
- Enter a number, for example 8
- Press either the "Enter" or "Return" key on your keyboard

Expected behavior: MS4 interprets the final key press as affirmation that I'm done inputting the number, closes the dialog window, and uses the number to insert that many new bars into the sheet.

Actual behavior: The dialog window remains open, the music sheet does not change, but keyboard focus is lost.

As a side note, the dialog window could probably have a better window name than "MuseScore4". I suggest "MuseScore4 Input Dialog", that would be an improvement.

### Screenshots/Screen recordings

![Bildschirmfoto_2023-07-16_16-03-51](https://github.com/musescore/MuseScore/assets/2690845/9ef1afaa-0121-41a3-9d0b-7e22e7db1696)

If you really insist, I can also make a screenrecording showing that MuseScore4 does not react to pressing Enter or Return, but that seems silly.

### MuseScore Version

OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Debian Bookworm

### Additional context

The following appeared in the log, which seems relevant:

```
16:04:50.650 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: insert-measures-after-selection
16:04:50.665 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/NotationScene/SelectMeasuresCountDialog.qml:51: TypeError: Cannot read property 'enabled' of null
16:04:50.665 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/NotationScene/SelectMeasuresCountDialog.qml:51: TypeError: Cannot read property 'enabled' of null
16:04:50.665 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/NotationScene/SelectMeasuresCountDialog.qml:97: TypeError: Cannot read property 'enabled' of null
16:04:50.665 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/NotationScene/SelectMeasuresCountDialog.qml:97: TypeError: Cannot read property 'enabled' of null
```

**Comment by MarcSabatella** [comment] 2023-07-16 19:51
Thanks for reporting; this is also reported as https://github.com/musescore/MuseScore/issues/12222.  As far as I know this and the Print dialog are the only ones where this true, but let us know if you discover this in others as well.

**Comment by cbjeukendrup** [comment] 2023-07-16 23:07
Closing as a duplicate of #12222. The log warnings seem unrelated; this functionality is simply not implemented.

**Closed by cbjeukendrup** 2023-07-16 23:07 UTC
Labels: UI
