### ISSUE TITLE
[MU4 Issue] Factory Settings - No restart on Revert to Factory Settings 

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11353] opened 2022-04-25 14:43 UTC
**Describe the bug**
There is no user prompt or application restart on Revert to Factory settings. Revert is only fully-applied when user manually closes application and restarts, but there is no prompt or instruction to the user.

**To Reproduce**
1. Go to "Help > Revert to Factory Settings"
2. Click on 'Yes'
4. See issue

**Expected behavior**
A prompt should appear with something like "Revert to Factory Settings requires application restart. Restart now?" 

**Screenshots**

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by the-next-ceo** [comment] 2022-04-25 15:08
i will try to implement it.

**Comment by Tantacrul** [comment] 2022-04-25 15:52
I agree exactly with the proposed wording and functionality. Thanks @lengthwave!

@the-next-ceo - let us know how you get along with that.

**Comment by the-next-ceo** [comment] 2022-04-25 19:49
> I agree exactly with the proposed wording and functionality. Thanks @lengthwave!
> 
> @the-next-ceo - let us know how you get along with that.

yeah thanks
I'll try my best and I hope the desired output will come.

**Comment by Eism** [comment] 2022-04-26 06:02
@lengthwave @Tantacrul @the-next-ceo 

We don't need to restart the program.
In MU3, a restart was required to solve particular problems, this is more of an implementation error.
The architecture of MU3 and MU4 is different. In MU4, everything works through channels: consumers subscribe to data using channels, when data changes, channels notify consumers about data changes, consumers update their states.

This architecture allows to update the programme state automatically, without restarting the program.
If something doesn't reset its state, then it's a bug and needs to be fixed.

**Comment by lengthwave** [comment] 2022-04-26 06:31
@Eism I see that the colors are changed on revert and some aspects of modifications to a workspace are reset, but if you have created custom workspaces these are currently not removed/reset until restarting the application.

**Comment by Eism** [comment] 2022-04-26 07:05
@lengthwave 
Yes, I can reproduce this bug. Should be registered as a separate bug :)

**Comment by Tantacrul** [comment] 2022-04-26 07:16
> @lengthwave @Tantacrul @the-next-ceo
> 
> We don't need to restart the program. In MU3, a restart was required to solve particular problems, this is more of an implementation error. The architecture of MU3 and MU4 is different. In MU4, everything works through channels: consumers subscribe to data using channels, when data changes, channels notify consumers about data changes, consumers update their states.
> 
> This architecture allows to update the programme state automatically, without restarting the program. If something doesn't reset its state, then it's a bug and needs to be fixed.

Perfect! That would be much better then. Sorry, we didn't realise and assumed the MS3 way was the only way.

**Comment by Tantacrul** [comment] 2022-04-26 07:17
> @lengthwave Yes, I can reproduce this bug. Should be registered as a separate bug :)

@lengthwave Agreed!

**Comment by Eism** [comment] 2022-06-27 10:58
Okay, there are several reasons(see #11987 and the bugs I found while fixing this issue in #11390 and the reason why I haven't merged the PR yet) why we currently cannot continue without a restart.
So, let's restart the app.

Martin, what message should we show the user?

**Comment by Eism** [comment] 2022-06-28 05:26
Implemented application restart. You can see how it works in https://github.com/musescore/MuseScore/pull/11390.

**Comment by DmitryArefiev** [comment] 2022-07-04 16:18
Fixed in #11390

**Closed** 2022-07-04 16:20 UTC
Labels: P2
