### ISSUE TITLE
Font choicess don't scroll when pressing a letter

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21637] opened 2024-02-22 15:09 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When opening the P**roperties** window and trying to choose a font by pressing a letter the list of fonts doesn't scroll and the focus goes back to the select text 

### Steps to reproduce

1. Open the Properties Window
2. Select some text
3. Click on the Font list
4. Enter the first letter of the font that you are searching for

### MuseScore Version

4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2024-02-22 15:29
This is a duplicate of https://github.com/musescore/MuseScore/issues/16508 - thanks for reporting, though!

**Closed** 2024-02-22 16:30 UTC
Labels: duplicate, regression_ms3, UX/interaction
