### ISSUE TITLE
Unexpected numbers background color for tablature staff in the invert score mode

### ISSUE THREAD

**Issue by andriisivak** [musescore/MuseScore#18924] opened 2023-08-04 18:55 UTC
### Issue type

UI bug

### Unexpected numbers background color for tablature staff in the invert score mode

_Expected result_: same background color, as the main page.
_Actual result_: light background color. It's unable to see the numbers in this case - see the screenshot.

Windows 10, Musescore 4.1.1.

![Screenshot_1](https://github.com/musescore/MuseScore/assets/13085837/a224eda8-48cc-407b-977c-c7dcf69fb414)

### Steps to reproduce

1. create the tablature
2. switch Musescore to the invert mode in Settings.
3. see the result

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Windows 10

**Comment by andriisivak** [comment] 2023-08-04 19:08
also in the "normal" white mode there is always white background color for numbers
![image](https://github.com/musescore/MuseScore/assets/13085837/073dc900-d21b-491d-a935-9403d2b3bbad)

**Comment by rgreen5** [comment] 2023-08-04 19:22
See also #12501.

**Comment by andriisivak** [comment] 2023-08-04 19:28
> See also #12501.

but why is it closed? was it already fixed?

**Comment by MarcSabatella** [comment] 2023-08-04 19:41
That issue was about drag & drop behavior when using the palette, not about tablature, and that much was fixed.  But see https://github.com/musescore/MuseScore/issues/11570

**Comment by cbjeukendrup** [comment] 2023-08-04 19:47
Closing as a duplicate of #11570. But thanks anyway!

**Closed by cbjeukendrup** 2023-08-04 19:47 UTC
Labels: UI
