### ISSUE TITLE
Mixer Doesn't Open on Linux

### ISSUE THREAD

**Issue by callumjohnspiller** [musescore/MuseScore#25401] opened 2024-11-01 22:42 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Install musescore using NixOs config (unstable channel currently uses musescore 4.4.2)
2. Open a score
3. Try to open the mixer, either through the toolbar or keyboard shortcut
4. observe that the mixer doesn't open and you can't edit sounds

### Supporting files, videos and screenshots

[Screencast from 2024-11-01 22-38-36.zip](https://github.com/user-attachments/files/17604642/Screencast.from.2024-11-01.22-38-36.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2 (4.4.3 not yet available on NixOS package manager)

### Regression

I was unable to check

### Operating system

NixOS: 24.11.20241025.18536bf (Vicuna)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-11-01 23:01
Third party builds like those created and supported by distribution maintainers often have issues that prevent them from working correctly.  have you tried the official 4.4.3 build (AppImage) that you can download and optionally install directly from musescore.org?

**Comment by cbjeukendrup** [comment] 2024-11-02 00:13
Duplicate of https://github.com/musescore/MuseScore/issues/24866

**Closed by cbjeukendrup** 2024-11-02 00:13 UTC
Labels: UX/interaction
