### ISSUE TITLE
[MU4 Issue] Wayland Backend not working on Linux

### ISSUE THREAD

**Issue by a-lameira** [musescore/MuseScore#15466] opened 2022-12-21 03:54 UTC
The Wayland backend is not working on Linux, the program simply won't open. On a Wayland session, the only way to run the program is under Xwayland.

1. On a Wayland session, open the AppImage or Flatpak package using the Wayland backend

**Expected behavior**
Until version 3.36.2, the program should run under native Wayland

**Platform information**
 - Linux 6.0, Debian Sid, GNOME 43.1, Wayland

**Additional context**

**Comment by Eism** [comment] 2022-12-21 10:17
Thanks for reporting!

Looks like it is a duplicate of #11244

**Closed by Eism** 2022-12-21 10:17 UTC
