### ISSUE TITLE
Corrupted file - can't open

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#17657] opened 2023-05-20 15:04 UTC
### Issue type

File corruption

### Bug description

MU4 doesn't open the file after recieving corrupted file message.
The file was created using MU4.

### Steps to reproduce

1. open file from musescore

### MuseScore Version

Nightly latest

### Regression

I don't know

### Operating system

macOS 13.2.1

### Additional context

[Crash corrupted file.pdf](https://github.com/musescore/MuseScore/files/11522609/Crash.corrupted.file.pdf)

**Comment by cbjeukendrup** [comment] 2023-05-20 15:08
That crash report looks familiar. This crash will be fixed soon. 

But what is the relation between the crash report and the rest of this issue (which mentions a corruption and not a crash)?
We will need the score file in question to investigate. To upload the score, put it in a ZIP file (or rename .mscz to .zip) and upload the ZIP file here on GitHub.

**Comment by amijaishalev** [comment] 2023-05-20 15:47
[Downstream - June 1 - crashed.mscz.zip](https://github.com/musescore/MuseScore/files/11522677/Downstream.-.June.1.-.crashed.mscz.zip)

Thanks, here is the file.
The other crashes happened with other files, so probably unrelated.

I managed to open the corrupted file on MU4 latest (not nightly). Nightly just crashes with it.

Looking forward to the fix!

**Comment by zacjansheski** [comment] 2023-06-02 17:18
I am able to open that file in the current nightly, has this been resolved?

**Comment by cbjeukendrup** [comment] 2023-06-07 00:02
For me the file opens just fine too. @amijaishalev Could you please test the latest nightly? If it still crashes, we will need the exact score and steps that are required to reproduce the crash reliably multiple times.

**Comment by cbjeukendrup** [comment] 2023-06-28 21:40
Closing because:
- we can't reproduce any problem with the attached file (no crash nor corruption)
- the attached crash report turns out to be the same issue as #18155 
- there has not been any activity here recently

**Closed by cbjeukendrup** 2023-06-28 21:40 UTC
Labels: needs info, corruption
