### ISSUE TITLE
MU4 won't open, crash on splashscreen (4.0.2)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16947] opened 2023-03-20 18:27 UTC
### Bug description

From 4.0.2 user:

> As we've spoken in Twitter, I'm experiencing problems with Musescore 4. No matter what I try, it crashes when I start the program. Is just the blue rectangle for about a second, and then it closes with any trace left in the task manager. I've tried the Muse hub, the native .msi archive, etc. Clean instalation, deleting first any archive related to Musescore 3.6. Lots of times.

--

> I've installed again Musescore 4, in order to have "clean" information. As soon as I try to start the program, a "dump" folder appears. There is the requested content, in a zip file. I attach too a .dmp file that the program creates.

[MuseScore4.zip](https://github.com/musescore/MuseScore/files/11021656/MuseScore4.zip)
[MuseScore4.exe.41608dmp.zip](https://github.com/musescore/MuseScore/files/11021659/MuseScore4.exe.41608dmp.zip)

> I'm going now to try this two builds that you've sent me. I'll let you know.

--

> Well, I've tried the MU4_230760507_Win_4.0.2 version that you sent me (after uninstalling again the published one), and it's just working on the first attempt!!!!:

### Steps to reproduce

1. Clean installation of 4.0.2 from MuseHub or musescore.org (msi)

### MuseScore Version

4.0.2 release build

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10 pro

Environment:
Is a desktop PC.
Windows 10 pro.
Motherboard: Asus ROG Crosshair VIII Hero WiFi
CPU: AMD Ryzen 9 5950X 4.9Ghz
RAM: Crucial Ballistix Black 64GB DDR4 3.6 GHz
GPU: MSI GeForce RTX 3090 SUPRIM X
Disc 1: Samsung SSD 980 PRO 500 GB
Disc 2: Samsung 970 Evo Plus 2TB
Disc 3: 16TB 3.5"

### Additional context

Can be related to #15235

**Comment by bkunda** [comment] 2023-04-24 12:30
Closing as seems like a duplicate of #15235

**Closed by bkunda** 2023-04-24 12:30 UTC
Labels: P1, regression
