### ISSUE TITLE
[MU4 Issue] Staff properties dialog ignores "change instrument" events

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8587] opened 2021-07-10 06:28 UTC
**Describe the bug**
In MU3 the staff/part properties dialog shows information about whatever instrument happens to be active at the point you select (actually if you have notes/rests selected both sides of a "change instrument" event it's not 100% clear which time point it uses).
But in MU4 it only ever shows information about the instrument initially assigned to the staff/part.

**To Reproduce**
1. Create a new score (default template, treble clef/piano)
2. Adding "Change Instrument" event in measure 2, for "Horn in F"
3. (NB Expected: key signature change should be created at this point, but it isn't in MU4)
4. Select measure 2 or later, right click and select "staff/part properties"
5. Instrument/transpose information is for piano

**Expected behavior**
Based on MU3, Instrument/transpose information should be for Horn in F
Note however MU3 seems inconsistent here because "Staff Change" events don't affect what's shown in the "Staff Properties" at the top of the Staff/Part properties dialog.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, built with MSVC

**Additional context**

**Comment by DmitryArefiev** [comment] 2021-09-16 11:45
Hi @wizofaus , Can you try again on master build please?  It seems to be fixed now:
![Change Instrument](https://user-images.githubusercontent.com/90187801/133606332-50119e3b-6a12-416d-b87e-e5f778eaccb6.gif)

**Comment by wizofaus** [comment] 2021-09-16 20:22
Better, but choosing a different instrument still affects the whole staff rather than just from where the last "Change Instrument" element was. Note that v3 doesn't update the *text* of the change instrument element, only what the actual instrument is - unless you do it via access the context menu then "Select instrument", which is missing in v4).

**Comment by Tantacrul** [comment] 2022-04-30 17:55
I've just tested this. This seems to have been inadvertently fixed at some point in the last year. @wizofaus, can you confirm?

If not, I'll reopen.

**Closed by Tantacrul** 2022-04-30 17:55 UTC
Labels: P2

**Comment by wizofaus** [comment] 2022-06-07 23:46
No, still looks the same as it was when Iast tested - the basic problem described in the bug is fixed, but when you use the Staff properties dialog to replace the instrument in the measure where a change instrument event is placed, it changes the whole part rather than just that Change Instrument event.  So if I'd added "Change to Horn in F" then decided I wanted to be "Change to Saxhorn" instead, I can't use "replace instrument", rather I'd have to delete the change instrument event and re-add it (thus losing whatever other configuration changes I'd made).
@Tantacrul

**Comment by Tantacrul** [comment] 2022-06-08 10:38
@wizofaus - I _think_ I understand what you mean, and if so, functionality you are describing was not known to me: that the 'replace instrument' option in Staff properties is contextual. If you can raise the issue about that (I'd do it but I'm not 100% sure I know exactly what the issue is) and tag me, I'll add a priority.

**Comment by wizofaus** [comment] 2022-06-08 10:58
Done

**Comment by MarcSabatella** [comment] 2022-06-08 13:45
For the record, all changes in the bottom half of the Staff/Part Properties dialog (the "part" as opposed to "staff" properties) are meant to be contextual in this way.  This was done mostly to allow you to customize the staff name for just the affected range.  Right now it seems changing *transposition* here does work, but changing "short instrument name" does not - the change does not take at all, so similar to the change instrument.

So whatever the issue is here is probably in the setting up of the context to begin with more so than in the handling of the instrument change per see.

But for me, the change instrument command in staff/part properties *does* work, in the test I just did.  And certainly, the dialog does show me the correct context.

**Comment by MarcSabatella** [comment] 2022-06-08 14:51
To be clear, here is a screenshot of a score with a change from oboe to soprano sax.  You can see I've selected the measure containing the change, and Staff/Part Properties is correctly showing me those properties:
![image](https://user-images.githubusercontent.com/1799936/172647087-72fb14bf-bdd5-42c6-ba62-8f060b6f0322.png)
Here now I've used "Replace instrument" to change to alto sax then hit OK, then brought the dialog back up:
![image](https://user-images.githubusercontent.com/1799936/172647356-08358786-9112-40fb-8d6b-b85b60d10195.png)
And now here I've changed the short instrument name to alto and pressed OK - this time it worked:
![image](https://user-images.githubusercontent.com/1799936/172647693-d1256ed5-696d-41f5-99eb-4e7027658151.png)

**Comment by MarcSabatella** [comment] 2022-06-08 14:59
I missed the new issue - https://github.com/musescore/MuseScore/issues/11929.  I can confirm that it does indeed seem to be true that the cases where things work well as the ones where I start by right-clicking the measure containing the change, and the cases where it doesn't work as well are if I start from a later measure.
