### ISSUE TITLE
Change layer location after scaling

### ISSUE THREAD

**Issue by Vypadenie** [musescore/MuseScore#20418] opened 2023-12-11 19:08 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

I'm engraving a piano piece and using 2 layers with both hands. 
When I change the scale of the score from 100 to 120 percent, the layers move. The notes are no longer on top of each other. The 2nd layer is located slightly in front, and the 1st behind it. 
This happens throughout the score in both hands.

### Steps to reproduce

1. insert notes in two layers
2. then go to Staff/Part properties
3. change Scale from 100 to 120 percents
4. click Ok
5. layers move

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/153545403/520ceb02-c0f7-476b-a73d-e0f248c725e5

### MuseScore Version

4.1.1-232071203

### Regression

I don't know

### Operating system

macOS 13.5

### Additional context

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by MarcSabatella** [comment] 2023-12-11 22:33
This is a known long-standing bug - see https://github.com/musescore/MuseScore/issues/18643.  It happens only if you try changing scale via staff properties rather than via page settings.  Also only when increasing rather than decreasing staff size.

Since your goal seems to be to increase the overall size of the score, you shouldn't be using the staff properties anyhow - page settings is easier and more appropriate, and it also scales thing that fail to scale when you do it a staff at a time.

**Comment by oktophonie** [comment] 2023-12-12 09:12
Closing as duplicate of the abovementioned issue https://github.com/musescore/MuseScore/issues/18643

**Closed by oktophonie** 2023-12-12 09:12 UTC
Labels: engraving
