### ISSUE TITLE
Musescore 4 crashes and doesn't reopen when other application managing a different audio driver is opened.

### ISSUE THREAD

**Issue by iasonkoutsoulis** [musescore/MuseScore#17663] opened 2023-05-21 07:33 UTC
### Issue type

Crash or freeze

### Bug description

What the title says, and in addition:

1. Tried with ASIO4ALL, so far, so no external sound-card. 
2. Tried with my DAW, Ableton, running A4A, and some standalone VSTs, such us kontakt and Massive.
3. Musescore 3 doesn't shut down after the steps seen below.

### Steps to reproduce

1. Set the audio preferences of the application you will be using to test into the external driver (consider doing it for ASIO4ALL), and close it.
2. In Playback properties, please have enabled exclusive mode. If the mode is not exclusive, the DAW will not make a sound - notice that it also won't crash, unlike Musescore. 
3. Open Musescore 4 (maybe a score as well).
4. Open the application you are testing against.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

**Crash log:**

Faulting application name: MuseScore4.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2913, time stamp: 0xa1c3e870
Exception code: 0xe06d7363
Fault offset: 0x000000000002cf19
Faulting process id: 0x3604
Faulting application start time: 0x01d98b6656ca48d7
Faulting application path: C:\Program Files\MuseScore 4\bin\MuseScore4.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 70cd79e0-8849-4c65-bda1-5e851c91bde3
Faulting package full name: 

**Specs**

Processor Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz 2.90 GHz
Installed RAM 8.00 GB (7.88 GB usable)
System type 64-bit operating system, x64-based processor
Edition Windows 10 Home
Version 22H2

**Comment by cbjeukendrup** [comment] 2023-05-21 12:28
This looks similar to a crash that has been fixed in the latest nightly builds. Can you try those? https://musescore.org/en/nightly-builds

**Comment by iasonkoutsoulis** [comment] 2023-05-21 16:33
Yes, I think that ought to be enough, as it at least brings back existing functionality of Musescore 3. I'll check out the nightly build, but I am thinking I wait until it is frozen/stable in 4.1, as it may be a bit of a hassle to take all precautionary measures necessary to test out only this one bug with the nightly build.

I think the etiquette now is that I close the issue and if the new build does not resolve it, I reopen it?

**Comment by MarcSabatella** [comment] 2023-05-21 17:36
You don’t need any precautions to test a nightly build; they don’t install and can exist side by side with a standard release.  Would be good to test this *before* the release in case it turns out your particular situation isn’t covered yet and still needs work.

**Comment by zacjansheski** [comment] 2023-06-01 18:19
I reproduced in 4.02 Windows 11
I was unable to reproduce in the current nightly Windows 11.  I will echo the recommendation to try the nightly with your environment to ensure the issue is resolved.  I will now close this, thank you!

**Closed by zacjansheski** 2023-06-01 18:19 UTC
Labels: needs info, crash, regression_ms3
