### ISSUE TITLE
Menu Doesn't Display in Fullscreen

### ISSUE THREAD

**Issue by napochanIsMe** [musescore/MuseScore#13940] opened 2022-10-23 20:23 UTC
Sorry, I'm not sure if this is the correct place to report issues with the Beta version, but here goes...

Windows 11, MuseScore 4 Beta (downloaded 10/23), two (2) HD displays with "Extend these displays" set.

The top-level menus (File, Edit, ...) do not display when MU4 is displayed fullscreen. They do display when NOT fullscreen. This happens on the primary monitor (2560x1440) only. The menus display properly on the 2nd monitor (3840x2160) in fullscreen.

**Comment by oktophonie** [comment] 2022-10-23 20:56
It surely is the right place :)
I have encountered this too, also with a dual monitor setup. When MU4 is full screen, the menus appear, but at the wrong position (too high, and always on the far left). Half of the 'File' menu shows up - perhaps as it's taller - but some of the other menus seem to not appear at all.

<img width="1920" alt="Screenshot 2022-10-23 215352" src="https://user-images.githubusercontent.com/20604032/197417893-2ef7e664-41b5-479a-9226-01ca8ce898ca.png">

(Beta build, Win 11)

**Comment by napochanIsMe** [comment] 2022-10-23 21:07
Thanks for confirming this behavior. In fullscreen mode I don't see the top-level menus at all, but I do see the behavior you describe when selecting the Sound menu in the mixer. In that case, the menu pops-up above and to the left, as you described. For now, it's no problem operating without fullscreen.
![image](https://user-images.githubusercontent.com/115959059/197418189-3994ffed-cd52-44d1-b450-912ce8c828e2.png)

**Comment by FiveTD** [comment] 2022-10-27 08:26
Confirming this behavior and adding additional information: As a dual monitor user, MS4 exhibits this behavior on my primary monitor, but not my secondary. My primary monitor is a 29" 1440p144hz monitor, while my secondary is a 24" 4k60hz monitor. Menus are chopped, disjointed, and otherwise misplaced in fullscreen on my primary, while they appear in the correct locations when not in fullscreen, or in fullscreen on my secondary 4k. If I had to hazard a guess, MS4 is placing the menus based on where they would be on my 4k monitor by pixel distance, including on my 2k monitor.

Attached are two screenshots of clicking the File menu, first on my primary 2k monitor, and second on my secondary 4k monitor.

![image](https://user-images.githubusercontent.com/12143463/198231501-28429798-b4a4-4215-a251-9a9d82f9af3a.png)
![image](https://user-images.githubusercontent.com/12143463/198231661-f19ea8b7-0a13-4621-9584-d6478c8911bf.png)

**Comment by oktophonie** [comment] 2022-11-08 08:45
According to https://github.com/musescore/MuseScore/issues/14405 also affecting some pop-ups such as 'Add Palettes'.

**Comment by Eism** [comment] 2022-12-13 17:35
@napochanIsMe @oktophonie 
Please check https://github.com/musescore/MuseScore/suites/9843549657/artifacts/474421381
Actually, I can't reproduce, but this build can fix this issue.

**Comment by oktophonie** [comment] 2022-12-14 13:53
This build hangs on the splash screen for me, so I couldn't test it. (That's likely an entirely unrelated issue.)

**Comment by DmitryArefiev** [comment] 2022-12-16 17:08
Should be fixed in #15151

@napochanIsMe Please recheck on your side (and reopen if still happens). 

Thanks!

**Closed** 2022-12-16 17:11 UTC
Labels: P1

**Comment by Eism** [comment] 2022-12-16 22:33
@oktophonie 
I think, this issue is about your problem https://github.com/musescore/MuseScore/issues/15029

So, check your selected i/O device and try again

**Comment by DmitryArefiev** [comment] 2023-03-10 14:49
Retested on Win10 with 4.0.2 RC build - **Doesn't occur**
