### ISSUE TITLE
[MU4 Issue] MuseScore is crashed when interacting with Native Instruments Raum VST reverb

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11086] opened 2022-04-04 15:46 UTC
**Describe the bug**
The app crashes when:
- muting the Raum in its plugin slot
- changing track volume and opening Raum
- deleting Raum from the slot

**Expected behavior**
MuseScore is not crashed due to any activities with VST plugins

**Screenshots**

https://user-images.githubusercontent.com/101250347/161581428-77931185-7da3-4896-ac48-50f3c224fd36.mov

**Platform information**
 - OS: macOS

**Comment by Tantacrul** [comment] 2022-06-07 16:01
@boryskuzmenko - is this issue still happening with this specific plugin?

Are you able to replicate the issue with a free plugin? (I'll check for free NI plugins now to see if I can replicate)

**Comment by boryskuzmenko** [comment] 2022-06-07 16:22
Can't reproduce with another plugins, even NI plugins. It relates only to Raum a I see

**Comment by Tantacrul** [comment] 2022-06-07 16:25
Yeah, I just tried with other NI plugins too. OK, bumping to beta.

**Comment by DmitryArefiev** [comment] 2022-10-19 11:30
Fixed in #13714

**Closed** 2022-10-19 11:31 UTC
Labels: P1
