### ISSUE TITLE
Properties Pop-up inaccessible when opening 'show more' tab

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#21282] opened 2024-01-29 20:58 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When clicking on the pop-up buttons in properties, 'Show More' doesn't readjust the position of the pop-up so the new contents is off-screen.

### Steps to reproduce

1. Select notes and e.g. rests
2. In properties, click the 'Notes' button, then 'Show more'

### Screenshots/Screen recordings

| Before                               | After                               | 
| ----------------------------------- | ----------------------------------- |
| ![image](https://github.com/musescore/MuseScore/assets/116587995/6cd761de-6cb3-48d0-9cc0-08854c550ab2) | ![image](https://github.com/musescore/MuseScore/assets/116587995/94aa832b-9c88-4887-9cf5-7a81e71ef7e9) |

### MuseScore Version

Master

### Regression

I don't know

### Operating system

Windows 10

**Comment by Eism** [comment] 2024-01-30 07:13
Duplicate of #21044. Thanks for reporting!

**Closed by Eism** 2024-01-30 07:13 UTC
Labels: UI
