### ISSUE TITLE
[MU4 Issue] Palettes icons gone after docking it to Notation

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8182] opened 2021-05-26 22:31 UTC
**Describe the bug**
Palettes icons gone after docking it to score

**To Reproduce**
1. Create a score
2. Open Palettes tab in the left Instruments Panel
3. Dock any palette to the score

**Expected behavior**
Palettes icons should be presented always

**Screenshots**
https://user-images.githubusercontent.com/71372310/119739586-1e1ed200-be8b-11eb-911b-8c79e5a46470.mp4

**Desktop (please complete the following information):**
Windows 10
MacOS

**Additional context**
Icon returns after switching Instrument Panels

**Comment by cbjeukendrup** [comment] 2021-05-27 17:02
"docking" → "dragging"?

I think this is related to (if not a duplicate of) https://github.com/musescore/MuseScore/issues/8035.
It seems it just depends on how quickly you drag how far the item moves off, and when you drag quickly enough, it moves outside the visible area of the palette.

By the way, confirmed on macOS too.

Also, it would be great if we could modify the Palettes code in such way that it is possible to have one "stand-alone" palette without a palettes tree. We will need this when rewriting the Master palette (or some replacement that contains only the functionality that's not elsewhere in the UI) and the Key Signature Creator (which contains an Accidentals Palette) from QWidgets to QML.

**Comment by vshalkevich** [comment] 2021-05-27 23:32
@cbjeukendrup 
Thanks for reply.
Bugs seems similar but I think they are different. Need to check both of them after fixing one of them.

**Closed** 2021-06-18 09:08 UTC
Labels: P1
