### ISSUE TITLE
[MU4 Issue] Saves mscz when mscx is selected in Save As dialog

### ISSUE THREAD

**Issue by JohanSpaedtke** [musescore/MuseScore#25315] opened 2024-10-25 20:02 UTC
### Issue type

Opening/saving issue

### Description with steps to reproduce

# Description
If you select mscx from the Save As dialog the application still saves mscz files sometimes

# Steps to reproduce
1. Create new score
2. File -> Save As
3. Save to computer
4. Select `Uncompressed MuseScore folder (experimental) (*)` from the dropdown
5. IMPORTANT Click directly on `Save`

# Expected behavior
A new uncompressed folder containing a .mscx file and other folders should be created in the default Score folder

# Actual behavior
A .mscz file is created in the defaul Score folder

# Workaround 
If you click anywhere in the Save As dialog so that the dropdown looses focus before you hit `Save` it works. 

### Supporting files, videos and screenshots

Not really a GUI issue so a screenshot doesn't do much. Can provide a screen recording if requested in the future but it's almost as fast to reproduce it as to watch the video. 

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

macOS 14.6, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-10-30 13:13
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/11615 (and/or the other issues mentioned at https://github.com/musescore/MuseScore/pull/18645)

**Closed by cbjeukendrup** 2024-10-30 13:13 UTC
Labels: duplicate
