### ISSUE TITLE
Editing makes trailing notes muted (one score)

### ISSUE THREAD

**Issue by Vaida12345** [musescore/MuseScore#20582] opened 2023-12-20 04:49 UTC
### Issue type

General playback bug

### Bug description

When editing a note, under certain conditions, the notes after the edited note are not played during playback. However, notes in the later measures are played correctly.
Closing the score and reopening it would temporally solve this issue.

### Steps to reproduce

Open [Nightfall.mscz.zip](https://github.com/musescore/MuseScore/files/13722998/Nightfall.mscz.zip)
Toggle the visibility (press V) of the only visible reset in measure 13. 
Play measure 13

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/563028e4-0b48-4d22-be94-ff93a3fee012

### MuseScore Version

4.2.0, latest

### Regression

I don't know

### Operating system

macOS 14.2/Win10

### Additional context

OS: macOS 14.2, arm, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c
In my other music project, editing a note would cause the later notes not being played properly.

**Comment by Vaida12345** [comment] 2023-12-20 04:51
Okay, deleting any note in measure 13 will stop the later notes from being played properly.

**Comment by DmitryArefiev** [comment] 2023-12-20 09:12
@Vaida12345 I can reproduce it, but did you have the same bug in other scores? Can you reproduce it from scratch?

**Comment by Vaida12345** [comment] 2023-12-20 09:17
Hey. Thank you for your reply. Reproducting from scratch could be tricky, but I’m sure it has nothing to do with the file itself. After observing this issue, I created a new file and pasted the notes from the old file, the problem persists. On Dec 20, 2023, at 5:12 PM, DmitryArefiev ***@***.***> wrote:﻿
@Vaida12345 I can reproduce it, but did you have the same bug in other scores? Can you reproduce it from scratch?

**Comment by DmitryArefiev** [comment] 2023-12-20 10:49
I pasted the notes to a new file and can't reproduce it 

https://github.com/musescore/MuseScore/assets/90187801/f0794e09-984c-4fba-be34-8d63a2f30d3a

**Comment by DmitryArefiev** [comment] 2023-12-20 10:52
To understand how serious the issue we should understand how easy to recreate the bug.

Did you input all notes in note input mode or export the main part from xml file?

**Comment by Vaida12345** [comment] 2023-12-20 10:54
It seems the problem is cause by the repetitions on the first line. If you remove the repetitions in the original file, the error disappears.

**Comment by ShibuyaCyana** [comment] 2023-12-21 02:59
Should be related to this: #19119
This behavior strangely rely on previous editing steps, I can't reproduce exactly the same case as OP, but can if I create a score with same structure as OP's score, then use the steps in my post above:

https://github.com/musescore/MuseScore/assets/39703247/dd0a6095-acff-4271-b794-893ac5224cf9

the original case also happens if you delete some notes in bass clef in measure 13, or replace the first invisible 16th rest with a note.

**Comment by zacjansheski** [comment] 2024-04-24 15:21
Fixed by https://github.com/musescore/MuseScore/pull/22522

**Closed by zacjansheski** 2024-04-24 15:21 UTC
Labels: needs info, P1, playback
