### ISSUE TITLE
[MU4 Issue] Unable to publish score/upload score to cloud inside the app

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#14246] opened 2022-11-01 14:59 UTC
**Describe the bug**
Unable to publish a score online from the app despite having account already logged in. Due to this, the score isn't able to be uploaded with MuseSound audio.

**To Reproduce**

https://user-images.githubusercontent.com/90231404/199261553-2b484b62-0b89-4cab-b429-254905904826.mp4

**Expected behavior**
"Save to cloud" and "Publish to Musescore.com" function should be usable once the account has been logged in order to upload scores online.

**Platform information**
 - OS: Windows 10
 - Version: 4.0.0.222931342 (released early public beta)

**Note**
- The "score isn't able to be uploaded with MuseSound audio" part was me trying to import the score file directly to musescore.com. It successfully uploaded, but it defaulted to MS Basic audio, but I guess that should've been apparent.
- I've also tried reinstalling the app and logging out my account again, but none of them worked.

**Comment by Tantacrul** [comment] 2022-11-01 18:31
OK, that's very strange.

Can you try one thing to help: can you go to the 'Home' tab and click on 'Account' and try to sign in that way?

<img width="841" alt="image" src="https://user-images.githubusercontent.com/21022311/199310709-4a25b736-21a3-4251-ade9-30d99f9f9161.png">

**Comment by cbjeukendrup** [comment] 2022-11-01 22:52
Hm... case number 3 of #14144???

@cgpqci Could you please check if you see any videos on the Home > Learn page? If you see "sorry we can't load these videos" even while you have an internet connection, then we probably know what's going on; your computer is missing a certain system dll file that is depended on by MuseScore's OpenSSL library (which is required to make https connections). You can install this missing DLL file from Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=26999
Please let us know if this fixes the problem.

**Comment by cgpqci** [comment] 2022-11-02 06:17
**For @Tantacrul**
I've tried as well, but it didn't work either

https://user-images.githubusercontent.com/90231404/199411704-19558b4e-2718-42ce-a74b-88201a2be465.mp4

**For @cbjeukendrup**
I checked that is in fact the case. I installed the `vcredist_x64.exe` program and I've successfully logged my account in. However, since you've asked about the videos in the _Learn_ tab, if there are videos that are supposed to pop up afterwards, then there's none.

![image](https://user-images.githubusercontent.com/90231404/199412180-b6a5fe83-8335-4584-abd4-88f6819ea37a.png)

Thank you for your assistance!

**Comment by cgpqci** [comment] 2022-11-02 09:36
I'm also going to add this as I'm working with my score. Remind me if this is a separate issue then I'll raise another one.

I've been trying to publish my score to the site, and I've been waiting for hours, and the audio's still not being exported.
Here's my latest attempt below. I've been waiting for an hour for this one and nothing's happening.

![image](https://user-images.githubusercontent.com/90231404/199452006-138c35ba-1358-4215-b14d-862360f5cf92.png)

I could only get out of this by forcibly ending the app via _Task Manager_ which I've done a couple of times already. This action would result to this. I haven't tried restoring the score through here, though.

![image](https://user-images.githubusercontent.com/90231404/199453991-10992487-538c-489f-b71b-0c7f8ea822bc.png)

Similarly, I'm able to save my score to cloud without exporting the MuseSound audio. Since this is not the result I want, I would followingly delete it. As a result, the duplicate score in the cloud is gone, but it would persist on the Scores Tab. (_See below_)

![image](https://user-images.githubusercontent.com/90231404/199454774-6da967e9-bac0-4567-8fad-5d0e133387c3.png)

**Comment by Tantacrul** [comment] 2022-11-02 09:45
@cgpqci - thanks for all this. But to avoid the problem of this conversation going in multiple different directions, can you please log those as two separate issues? It would be really appreciated. Thanks for testing this particular side of the app. It's extremely useful.

**Comment by Tantacrul** [comment] 2022-11-02 09:47
Since we know the culprit (reported 3 times now I think?), which is already logged here: https://github.com/musescore/MuseScore/issues/14144

I'm going to close this issue. Thanks very much @cgpqci !

**Comment by Tantacrul** [comment] 2022-11-02 09:48
Duplicate of https://github.com/musescore/MuseScore/issues/14144

**Closed by Tantacrul** 2022-11-02 09:47 UTC
Labels: P0
