### ISSUE TITLE
[MU4 Issue] Images cannot be moved via drag or keyboard

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12587] opened 2022-07-28 22:13 UTC
**Describe the bug**
Cursor keys should nudge elements, and do for most (sometimes requiring edit mode), but for images, no nudging seems possibility.  This is a regression from MU3.

**To Reproduce**
1. In an empty, paste an image (that you capture to your clipboard elsewhere) onto the first rest
2. Try to move it via keyboard or mouse
3. See error - the image resizes rather than moves

**Expected behavior**
Image should resize if you drag it explicitly, or select a handle to adjust by keybaord, but default operation of both drag and cursor keys should be nudge.  Or, if a conscious choice is being made that resizing should be the default, then there should be an obvious way to move instead.  But edit mode doesn't work, nor does deselecting then dragging.

**Platform information**
- Linux

**Additional context**
I was able to drag by right-clicking - actually, to be more accurate, by dragging with two fingers on my touchpad.  This is entirely non-obvious and probably a bug in itself.

**Comment by wizofaus** [comment] 2022-07-29 02:13
Images behave pretty weird in v3 too though - seems the cursor keys only ever resize (up/down only - left/right appear to do nothing), rather than reposition, and in edit mode, even just clicking in the middle of the image and dragging causes it to resize (which is what you'd normally expect if clicking & dragging the resize handles).  What's the intended behaviour?

**Comment by MarcSabatella** [comment] 2022-07-29 03:29
Indeed, looks like MU3 isn't good about keyboard nudge either.  I guess it's just so easy to use the offset fields in MU3 I had forgotten I needed to do that rather than just nudge.  Anyhow, drag works in MU3 but not MU4, so that much is a regression.

The right-click was a bit of a fluke but is reproducible on my system.  Start with the image unselected - that's an important part of it.  Then, tap two fingers on the touchpad, press until it clicks, and leave the fingers down.  The context menu appears (because this is the right-click action), but then I can drag.  Can't see what I'm doing very well because the context menu is in the way, which is why it seems like a bug.

**Comment by wizofaus** [comment] 2022-08-14 01:56
@Tantacrul  do you think it at least makes sense to ensure we can allow using the mouse to move images, even if it means treating images slightly non-conventionally (if they had a 2nd grip handle in the middle that was the default grip, it would work automatically, but that's a bigger change).  Atm it's very difficult to adjust the position of an image.

**Comment by Tantacrul** [comment] 2022-08-15 21:08
This seems to simply just be broken right now, since you should be able to click on the image itself to move it. Is that issue logged elsewhere, does anyone know? If so, for me that should be a separate bug to this, which is a bit different.

**Comment by wizofaus** [comment] 2022-08-15 22:27
They're more or less the same issue, though the problem with not being able to drag with the mouse at all is partly because of the change I introduced a long while back to automatically assume "edit" mode in such cases (noting that in v3, in edit mode, you can't drag images with the mouse either).
But I agree that fixing dragging with the mouse is more important than fixing being able to use the keyboard (as you *can* use the keyboard in the inspector offset fields).
Like I said, I have a sort of fix, but it's more of a stop-gap fix, and I can't guarantee it won't potentially cause issues with other types of elements.

**Comment by Tantacrul** [comment] 2022-08-16 18:58
Dragging in MS3 works on MacOS for me, incidentally. Anyway, let me know when you want testing.

**Comment by wizofaus** [comment] 2022-08-16 20:18
Not in edit mode,  it only resizes.
I don't mind putting up a PR for a partial fix that at least enables using the mouse to drag (you'll still be able to resize if you drag the bottom right grip handle), but it won't fully fix the issue here.

**Comment by Tantacrul** [comment] 2022-08-16 20:20
FWIW, I don't think keyboard nudging is massively important here. Currently, you can't drag them at all.

You know my opinions about 'Edit Mode' for MS3 :)

**Comment by DmitryArefiev** [comment] 2022-08-23 10:28
Fixed in #12910

**Closed** 2022-08-23 10:29 UTC
Labels: P1
