### ISSUE TITLE
Spacing error with stacked 69 chord symbols

### ISSUE THREAD

**Issue by RobH1964** [musescore/MuseScore#23888] opened 2024-08-03 23:14 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

The vertical space between the 6 and 9 in major and minor chord symbols is problematic (Edwin font, 10 pt. default):

- Start a new score
- Add a major 69 or minor 69 chord symbol
- Notice the huge (ugly) vertical space between the 6 and 9
- As you increase the size of the chord symbol, the 6 and the 9 smash into each other and then actually overlap (see attached)

### Supporting files, videos and screenshots

![Chordtest](https://github.com/user-attachments/assets/82607331-9d12-49fd-b112-538578eaf7a3)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Linux Mint (LMDE6)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-04 09:29
Duplicate of https://github.com/musescore/MuseScore/issues/20101

**Closed by oktophonie** 2024-08-04 09:29 UTC
Labels: engraving
