### ISSUE TITLE
[MU4 Issue] commands not implemented (including "Toggle Create Multimeasure Rest")

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8819] opened 2021-08-09 11:44 UTC
From cmd.cpp, most are not currently implemented:

         "mirror-note",
         "add-trill",
         "add-up-bow",
         "add-down-bow",
         "reset-style",
         "clef-violin",
         "clef-bass",
         "sharp2-post",
         "sharp-post",
         "nat-post",
         "flat-post",
         "flat2-post",
         "add-audio",
         "transpose-up",
         "transpose-down",
         "pitch-up-diatonic-alterations",
         "pitch-down-diatonic-alterations",
         "full-measure-rest",
         "toggle-insert-mode",
         "pitch-up",
         "pitch-down",
         "pitch-up-octave",
         "pitch-down-octave",
         "pad-note-increase",
         "pad-note-decrease",
         "pad-note-increase-TAB",
         "pad-note-decrease-TAB",
         "toggle-mmrest",
         "toggle-hide-empty",
         "set-visible",
         "unset-visible",
         "relayout",
         "toggle-autoplace",
         "autoplace-enabled",

Some additional unimplemented commands also discovered along the way.
These are implemented in https://github.com/musescore/MuseScore/pull/8908:

pitch-up-diatonic 
pitch-down-diatonic
top-staff
empty-trailing-measure 
select-similar-range
edit-element
next-segment-element
prev-segment-element

These are not...

fotomode
playback-position　
apply-current-palette-element
insert-fretframe　　（apparently this is "experimental"!)
fbeam1
fbeam2
toggle-midiimportpanel  (are we keeping the midi import panel?)
toggle-fileoperations (hide/show "file" toolbar, which MU4 doesn't have at this point, not sure if it should?)
toggle-imagecapture (this command exists in the toolbar shown while in the "Publish" tab, but does nothing. How is it different to fotomode?)
toggle-feedback - will this toolbar be included in MU4 - seems overkill to have a separate toolbar just for this one command.  Note that the "feedback" command itself is in the Help menu and does work.
toggle-workspaces-toolbar - again, will MU4 have this toolbar?
toggle-selection-window - selection filter panel, was implemented recently but hooked up via a new different named action "toggle-selection-filter", which doesn't have a shortcut key assigned to it.
create-new-workspace - currently can only do this from the "configure workspaces" dialog
mag - called "Zoom canvas" in the shortcuts dialog, it actually crashes MU3! (there's no code to implement it)
play-prev-chord
play-next-chord
play-prev-measure
play-next-measure
seek-begin       (NB default 'Home' key maps to this, but also maps to command 'page-top', which scrolls the canvas so that the top-left corner of the first page is in view.  So this needs to do one thing while in 'playback' mode and another while not.  But I don't understand how "seek-begin" is different to "rewind"?  But "rewind" has no shortcut key by default.
seek-end
(debugger   - not normally available)
mark-irregular   (it's on the View menu but does nothing!)
find -  there's code to support it but the search popup isn't appearing
edit-harmony - "experimental" in Mu3, requires "e" command line option. I believe something like this is being worked on as a gsoc project? NB it's called "Edit chord symbols style" in the shortcuts preferences, 
follow
split-h  - menu item exists, not implemented
split-v
revision - create new revision, can't quite work out what this does in MU3 yet (has Ctrl+F11 assigned by default)
realtime-advance
advance-longa    (this and the following 6 are used while inserting chord symbols or figured bass, see https://github.com/musescore/MuseScore/issues/9118)
advance-breve
advance-1 ...  advance-64
prev-measure-TEXT
next-measure-TEXT
prev-beat-TEXT
next-beat-TEXT
hraster
vraster
config-raster  (this has since been implemented)
media   (experiment feature, requires -e)
album  (album manager, this does actually sort of work, but seems to crash a lot and doesn't seem to do anything useful?)
layer (experimental feature, requires -e)
next-score   (3 different shortcuts assigned to this, including "Forward", no idea what that means? But for MU4 this would have to switch between different top-level windows/MuseScore processes, strangely there don't seem to be any actions for "next-excerpt"/"previous-excerpt")
previous-score (see above)
zoom-*-pre  -  piano roll editor zoom commands, I believe @blackears is working on this 

Note however that "select-similar-range" is a special case, as it only works from the context-menu for an element (as it requires a range to be selected *and* a particular element to be used as a reference point).  In MU3 it appears as an action that can be mapped to a shortcut but it doesn't work - in principle it *could* work based on what element is under the mouse when it's used, which would allow it to work regardless of whether the context menu was used. 

@Tantacrul unfortunately I seem to keep discovering more and more of these commands/actions, and definitely won't be able to implement them all myself in a timely fashion. Some of them don't seem to behave sensibly in MU3 at all, so I think we can safely drop, but it definitely needs some discussion.

**Comment by cbjeukendrup** [comment] 2021-08-09 12:03
Related to #7946 (but that one's list is not actual anymore, because only the author of the issue and people with repo write access can tick those checkboxes).

**Comment by wizofaus** [comment] 2021-08-21 07:27
mirror-note - see comment in https://github.com/musescore/MuseScore/issues/7946

     add-trill / add-up-bow / add-down-bow - perhaps NotationInteraction should have addArticulation?

     reset-style - not hooked up at all, should be straightforward

     clef-violin / clef-bass - see comment in https://github.com/musescore/MuseScore/issues/7946

     sharp2-post /  sharp-post / nat-pos / flat-post / flat2-post - NotationInteraction::addAccidentalToSelection( ) should do this, and existing addAccidentalToSelection( ) renamed to toggleAccidentalForSelection( ) (actually I don't know why we need "selection" in the names of the functions, isn't that implied?)

     add-audio - does nothing in MU3 (!), no need to port I guess

     transpose-up / transpose-down - via new function NotationInteraction::transposeSemitone( ) ?

     pitch-up-diatonic-alterations / pitch-down-diatonic-alterations  - via new function NotationInteraction::transposeDiatonicAlterations( ) ?
     
     full-measure-rest   - via new function NotationInteraction::makeFullMeasureRest( ) ? Behaviour is a bit unexpected, it seems to do the same as regroup rhythms, except that it preserves text etc. attached to rests (even fermatas are preserved, attached to hidden segments I think?). So why doesn't regroup rhythms do this?
 
     toggle-insert-mode - new function NotationInteraction::toggleInsertMode

     pitch-up, pitch-down - these do seem to be implemented, need to check some edge cases

TBC
     "pitch-up-octave",
     "pitch-down-octave",
     "pad-note-increase",
     "pad-note-decrease",
     "pad-note-increase-TAB",
     "pad-note-decrease-TAB",
     "toggle-mmrest",
     "toggle-hide-empty",
     "set-visible",
     "unset-visible",
     "relayout",
     "toggle-autoplace",
     "autoplace-enabled",

**Comment by wizofaus** [comment] 2021-08-22 02:10
So @igorkorsukov I've been thinking quite a lot about the best way to implement all the remaining actions.

MuseScore 3 supports 453 of these named actions.  All of them can be mapped to shortcut keys and importantly all of them can be used by the plugin engine.

In MU3, every action instigated via a menu, shortcut key sequence or via the plugin "cmd" function goes through ScoreView::cmd( ).

A large number of these are handled directly by ScoreView via a string->lambda map (actually a vector).

A number of them (select-next-chord/select-prev-chord...select-staff-below) forward the action name on to Score::selectMove( ), which has internal logic to handle these.

A further set "next-chord"/"prev-chord"...."top-staff" have some additional handling at the ScoreView level if a single text element is selected, in which case "prev-chord"/"next-chord"/"prev-measure"/"next-measure" are "reinterpreted" as "horizontal offset modification" commands (nudging the text element right/left - this is actually a pretty ugly kludge but we can fix that later), otherwise forward the action name to Score::move( ), which has internal logic to handle these operations which don't "move" anything, but rather change which element is currently selected (and where the input cursor should go if in note entry mode).

Lastly, any command that is NOT handled by ScoreView is passed as is to Score::cmd( ). 
Internally this has its own table of command names to lambda functions, which all have a nice simple implementations, generally calling a single public function. The one exception is "toggle-insert-mode" which accesses the private _is member however this can easily be changed to use the public inputState() function.

As I see it there's no good reason to preserve Score::cmd( ) in the Score class, as it requires no private access. I.e. the "action name" -> code look up/execution should be handled at a higher level.
I would say the same for Score::selectMove( ) and Score::move( ), though there is a bit more implementation detail in those functions, especially Score::move( ), which as implemented currently also makes use of private access to the "input state" field (again, easily changed).  Note that the only difference I can determine between "selectMove" and "move" actions is that former never change the input cursor in note entry mode (and in fact I don't believe are permitted in that mode).

The question is where should all this logic go in MU4, because currently NotationActionController is the main thing doing the action-name resolution - but is the intention for the plugin-engine to be able to dispatch actions to the controller? (NB not just NotationActionController, some commands are handled by other controllers).
And what about the usefulness of these commands to a standalone application that links with just the MuseScore engraving library?

Also even as it stands currently while NotationActionController maps action names to functions/strongly typed parameters etc. in NotationInteraction, in some cases these are mapped *back* to action names in NotationInteraction, which are then passed to the above-mentioned Score::selectMove() or Score::move() functions.

But even allowing that NotationActionController is the right place to keep all command name lookup, the issue is then how to avoid excessively bloating the INotationInteraction interface, which essentially acts as a wrapper around Score( ) for actions that can be trigger by a user (or a plugin script). 
To have a separate function for almost every possible action on a score (maybe 430, allowing that 20 or so actions aren't score-interaction functions) seems excessive, and while some "groups" of actions all logically do the same thing just with a different parameter (e.g. the 7 "add note" commands for a-g), in other cases it's less obvious - e.g. I implemented "toggleBold", "toggleUnderline" and "toggleItalic" as 3 separate functions, but then internally in NotationInteraction they all use the same implementation function with a parameter to specify which style flag is being changed.
Perhaps the guideline should be that if it at the INotationInteraction level it makes sense to implement multiple actions with a single function, then that's how the public interface should be too? But would you expect any types used for parameters in INotationInteraction to be part of mu::notation, or can they come directly from Ms (e.g. Ms::FontStyle::Bold)?
 
The next thing I note that is many of the NotationActionController functions just forward calls on to NotationInteraction. 
We could significant reduce amount of code needed at the NotationActionController level by simply having a version of registerAction that auto-forwards to currentNotationInteraction(), not by passing the action name, but a member function pointer, e.g.:

registerLyricsAction("next-lyric", &NotationActionController::nextLyrics); 

would either be replaced with or implemented just as

registerAction("next-lyric", &NotationInteraction::nextLyrics, &NotationActionController::isEditingLyrics);

Such that registerAction constructs a lambda that calls the member function pointer on currentNotationInteraction().

Likewise we can provide template versions taking 1 or 2 parameters as necessary.

Even then quite a lot of the score modification actions in NotationInteraction will follow a simple pattern:

	startEdit();
	score()->cmdXXXXX();
	apply()
	notifyAboutNotationChanged( )

So I'm thinking this could be done via a template helper function, e.g.

	NotationInteraction::addArticulation(SymId articulation)
	{
		modifyScore(&Score::addArticulation, articulation)
	}

or, more flexible but a bit more verbose:

	NotationInteraction::addArticulation(SymId articulation)
	{
		modifyScore([this](articulation) { score()->addArticulation(articulation); });
	}

You could even do it something like

	NotationInteraction::addArticulation(SymId articulation)
	{
		ScoreModification modification(this);
		score()->addArticulation(articulation);
	}
	
Then, for example, to register "add-trill", we just need something like

registerAction("add-trill", &INotationInteraction::addArticulation, Ms::SymId::ornamentTrill, &NotationActionController::isNoteSelected);

in NotationActionController.

Essentially I'd like to get to the point that it's clear where particular responsibilities lie and that it's relatively simple to add new action handlers as needed.

**Comment by wizofaus** [comment] 2021-08-22 07:23
BTW I know the above post is rather long, but just confirming that the following commands are not working either:

pitch-up/pitch-down when just a single Rest or Lyric is selected

In Mu3 these cause the rest to be shifted up and down the stave, or for lyrics, for the lyric to be "swapped" into another verse.

pitch-up-octave/pitch-down-octave/next-chord/prev-chord/next-measure/prev-measure if just a single lyric is selected - in Mu3 this causes the lyric to be "nudged" vertically or horizontally, as per other text elements

My preference is to actually create new actions for these commands whose enabled state depends on what's selected.  They would then appear as their own commands in the shortcut preferences dialog etc., and could be assigned different shortcut keys.  Currently they show as, e.g. "Go to previous chord or move text left".  In fact "Pitch up octave" is just described as that, despite it having a different meaning if a text element is selected.
Note the logic is such that these "secondary" commands only work if the *only* thing selected is a single element.  E.g. if you select a single text element, the left arrow nudges it left, but if you select *two* text elements, left arrow selects whatever note/rest the text element that was selected last is attached to, which is actually just the "prev-chord" action.

**Comment by wizofaus** [comment] 2021-08-22 21:26
@Tantacrul - one thing I've noticed that's different between MU3 and MU4 is that the "add-marcato"/"add-staccato"/"add-tenuto"/"add-accent" commands work a bit differently, in that a) they actual trigger note entry mode if nothing's currently selected and b) when in note entry mode, they actually toggle whether the *subsequent* notes entered take on those articulations, whereas in MU3 they only toggle articulations on currently selected notes (which MU4 does when not in note entry mode).
I'm assuming this is by design, and if so, we'd want the same for "add-trill"/"add-up-bow"/"add-down-bow"?

**Comment by Tantacrul** [comment] 2021-08-22 23:25
@wizofaus - Yes, the items in the top bar have different rules to things in palettes. I think about the top bar like a place for 'first class citizens': functions you are likely to want often enough that they are justified being there.

There are a lot of things we can do to improve Palettes but I felt it was best not to fiddle with it too much for MS4 so users could get used to the other changes without the core of the app changing too much. To answer your question, I've not given much thought to how certain objects in Palettes could work while you are in note input mode. I'm sure there are loads of nice little additional conditions we can set for various objects which depend on the mode you are in.

**Comment by wizofaus** [comment] 2021-08-23 03:15
To be clear what I'm working on has nothing to do with palettes - adding elements form palettes doesn't even go through the "named action" mechanism (which allows mapping shortcuts, and using from plugin scripts), which I think is something we should ultimately address, but that's for another day. And adding via a mouse drag action is something else again entirely!

I can see now that those 4 commands do in fact have icons in the notation-toolbar (they didn't in MU3), so on that basis I'm hoping it's OK that the add-trill/add-up-bow/add-down-bow commands need not behave the same way, and can just work as they did in MU3 where they only add articulations/ornaments to currently selected notes.

**Comment by wizofaus** [comment] 2021-08-23 05:15
Just found another anomaly re input mode - in MU3 the commands "Enter rest" and "Note input: <x> rest" automatically trigger note input mode as necessary, but in the current MU4 implementation it only works for notes/accidentals/dots/some articulations, but not rests.

**Comment by Tantacrul** [comment] 2021-08-23 07:45
> To be clear what I'm working on has nothing to do with palettes - adding elements from palettes doesn't even go through the "named action" mechanism 

Right. Got it.

**Comment by wizofaus** [comment] 2021-08-23 21:13
NB there's also pitch-up-diatonic/pitch-down-diatonic, which are different from the versions with "-alterations" (these were implemented by ScoreView::cmd( ) in MU3, but just call Score::upDown( ), anyway they're simple to add).

**Comment by wizofaus** [comment] 2021-08-23 21:33
Progress so far: have hooked up all actions listed above (including pitch-up-diatonic/pitch-down-diatonic).
Note there are challenges testing some of them as the shortcuts dialog isn't working properly (reported here https://github.com/musescore/MuseScore/issues/8898), currently requires manually editing shortcuts.xml to assign shortcuts to commands that have none currently, and we can't yet use plugins.
PR coming soon.

**Comment by wizofaus** [comment] 2021-08-24 07:10
Was able to get `select-similar-range` working by enhancing NotationSelection to be able to keep track of the 'last hit' element.
That even allows, for instance, selecting a range by any means, then holding down control to click on an element (which doesn't deselect the range), then activating "select-similar-range" by a shortcut.  It works "as expected", though the fact you get no visual feedback on what the last hit element and the fact it requires the mouse to use I'd say was something we should improve in future.  And yes, it works via the context menu too, though if you select a range then use SHIFT+F10 for the context menu, it generally doesn't do anything useful (in MU3 it's disabled in that case).

**Comment by wizofaus** [comment] 2021-08-28 01:44
Ok I have "edit element" mode working pretty well for the most part, but there's a subtle difference with MU3, in that for an element with grip handles (lines, brackets etc.), you're in "edit" mode if any of the individual grip handles are selected (by any means). The only difference this really makes is that a) various other actions (note input etc.) are NOT available and b) you have to hit Escape twice to deselect the element.  In MU3 you can select a, e.g., a slur, select a grip handle and adjust its position without even entering edit mode, and all the while all other note input/score modification actions are available (if you do choose to enter edit mode, it just selects the "end" grip then disables those actions, but otherwise behaves the same).
BTW implementing this required quite a few changes to how keystrokes etc. are handled, particularly Tab which Qt was automatically processing.  But there's quite a lot of scope for improvement, e.g. instead of special-case handling for the Tab and cursor keys, we could actually have an action meaning "next-grip" and map a shortcut key sequence to that, likewise "nudge-left"/"nudge-right" etc. etc.

**Comment by MarcSabatella** [comment] 2021-08-28 15:40
> Not sure to what extent it relates to accessibility

The specific way I know of is that currently I. 3.6.2, it’s impossible for a blind user to access the Inspector for lines or bar lines, because Tab - which would normally do the job for any other selected element - is locked in a cycle between the grips.  That’s a regression versus the old behavior where the handles didn’t appear until you entered edit mode.  But trivial to overcome, such as by making sure F6 is active to jump directly to the Inspector or whatever other sub-window is next in the tab order.

**Comment by wizofaus** [comment] 2021-08-28 20:12
Currently accessing the inspector via the keyboard in MU4 is not straightforward.  But having tab work to switch windows/panels when a lounge/slur/ element with grip handles makes sense - I'm tempted to think we should just require edit mode to be explicitly activated if you want to manipulate individual grip handles with the keyboard (including Tab). Cursor keys could still be used to reposition the whole slur (equivalent to the middle or "drag" handle being selected).
I have to say the thought of a completely blind user being able to typeset musical notation to the extent they'd want to make subtle adjustments to the shapes of slurs seems hard to get my head around,  but even for the sake of fully abled users I'm strongly of the view everything should be possible purely by the keyboard too.

**Comment by MarcSabatella** [comment] 2021-08-28 21:43
Indeed, adjusting handles is much less relevant for a blind users than accessing the Inspector, as that’s where you set things line dotted lines, double bars, etc.

But I’d rather not lose the ability to adjust handles by keyboard directly without the need for edit mode - that much was a welcome enhancement.  What’s wrong with just making sure F6 does it’s job?

**Comment by wizofaus** [comment] 2021-08-28 21:49
F6 is "toggle selection filter" - at least, it still is in the factory MU3 shortcuts file, it's not currently working as that in MU4 because the underlying action name was changed.
But if there's an agreement that F6 should always switch to the inspector/properties panel, I'm fine with that (and we come up with another default shortcut for the selection filter).  I certainly agree we should stick to what people are used to using in other apps where possible (presumably for F6 to be truly useful for blind users, enough info has to be supplied to any screen reading technology to give feedback on the currently selected window/panel).

**Comment by cbjeukendrup** [comment] 2021-08-28 21:51
In MU4, F6 is meant to jump between big UI sections:
- Main Toolbars
- Note Input Toolbar
- Left panels
- Score
- Right panels
- Statusbar

**Comment by wizofaus** [comment] 2021-08-28 21:55
Understood, but being able to get to the inspector/properties panel for the currently selected element with a single keystroke would be worthwhile too surely (in MU3 "Tab" does that for all elements except those with grip handles).

**Comment by MarcSabatella** [comment] 2021-08-28 21:55
Right, and as far as I know this was implemented for MU4 some times ago.  If it’s no longer working it should be fixed.

F6 was chosen because it’s a semi-standard shortcut for moving between sub-Windows or tab groups within a window.

**Comment by wizofaus** [comment] 2021-08-28 21:57
F6 is still working to cycle between windows/panels, it's "toggle selection filter" that it's not working for.

**Comment by MarcSabatella** [comment] 2021-08-28 21:58
I see.  So to me all is well.  A dedicated “go to Inspector” shortcut could be nice, but no more so than a dedicated “go to palette” or “go to mixer” etc.  The shortcut for toggling the visibility of these windows does “sometimes” set focus there as well, and I know some use this for that purpose.

**Comment by wizofaus** [comment] 2021-08-28 22:05
(BTW on the topic of shortcut keys, I'm a bit surprised you can't assign shortcut keys to palette items - there's a few "special case" commands like "clef-violin" etc. that allow inserting certain types of items via shortcut keys, but the ability to set up a shortcut key for any palette item would seem super useful - unless I'm missing something, adding items from the palettes with the keyboard in MU4 seems especially tricky - from the 'search' field you need to hit tab *twice* to select the first palette category, then Tab to the right category, then use the right arrow once, then the down arrow to select the specific element!)

**Comment by MarcSabatella** [comment] 2021-08-28 22:53
It’s a long standing request to be sure.  There was actually an implementation for GSoc a few years ago but for no particularly good reason it never got merged.  Now the palette code has been rewritten in QML so the old PR is not that useful.

The main challenge is the fact that unlike regular commands which are fixed and k own at compile time, palettes can be customized by the user, so we need to manage the list of shortcuts dynamically.  We already do that for plugins, though.

**Comment by wizofaus** [comment] 2021-08-28 23:13
The list of actions is dynamic though, nothing's technically "fixed" at compile time, though obviously the main set are initialized according to a hard-coded list.  I can think of a number of fairly straightforward ways it could be done, but will need to look into how palettes are implemented a bit more closely.

**Closed** 2021-12-03 16:41 UTC
