### ISSUE TITLE
Dropdown menus only appearing on 2nd monitor

### ISSUE THREAD

**Issue by UnchartedDemon** [musescore/MuseScore#24359] opened 2024-09-01 17:04 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Whenever I open a dropdown menu on my first/main screen, it only opens on my second monitor.
If I use Musescore on my second monitor, I don't have issues.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/847822b4-530e-407d-8f32-e7434c87eadc)

### What is the latest version of MuseScore Studio where this issue is present?

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-09-01 17:41
Duplicate of https://github.com/musescore/MuseScore/issues/24232

**Closed by oktophonie** 2024-09-01 17:41 UTC
Labels: UI, regression MS4

**Comment by Hephestorius** [comment] 2024-09-15 21:54
Same thing is happening to me: I have two monitors. 
Musescore (ver 4.4) is on the left monitor, the menu items is on the other monitor. I have no way to drag them to them back in place.
![20240915_144837a](https://github.com/user-attachments/assets/0306865e-67cc-4692-bcf8-daa4d1b61f28)
