### ISSUE TITLE
[MU4 Issue] Cracks when playing scores without Mixer window open

### ISSUE THREAD

**Issue by Flying-Roger** [musescore/MuseScore#15838] opened 2023-01-12 15:03 UTC
*** Bug description ***
When playing a score with Musescore 4.0.0, cracks and small delays are audible if the mixer Window is closed or deanchored.

*** To Reproduce the problem: ***
1. Open score
2. Click on the play button
3. Click on the Mixer button (or press F10) to close th Mixer window
or
3b Click on the Mixer menu button ("...") and select "de-anchor"
=> cracks/delays are heard
4. Repeat 3 or 3b to get the Mixer window visible and anchored
=> sound returns to normal

**Expected behavior**
Normal sound without Cracks.

**Screenshots**
Image N/A
Appending an Mp3 file to illustrate the cracks/delays problem is unfortunately not supported by github. I appended a video screen capture. Sorry for some quality issue in the capture app, but it shows anyway the impact of closing/opening the Mixer Window.

**Platform information**
 - OS: Windows 10 Home edition

**Additional context**
update: I recently installed MuseHub and the sound packages.
After that, loading scores is slower (waiting while the mixer sets up), but the problem is no longer present. Maybe MuseHub installation had an impact on the Musescore sounds system setup.

https://user-images.githubusercontent.com/74730149/212101517-d09cc6f4-e7ca-4a15-a076-4fdeb9531fff.mp4

**Comment by jeetee** [comment] 2023-01-25 09:56
4.0.1 should have fixed the mixer impact on playback performance. I believe this can be closed for now.

**Comment by sikamber** [comment] 2023-02-19 18:02
> 4.0.1 should have fixed the mixer impact on playback performance. I believe this can be closed for now.

I still have this issue in 4.0.1. There is both a repeating echo and significant time distortion if I do any sort of playback (playing the score or just clicking a note) without the mixer open.

**Comment by Flying-Roger** [comment] 2023-02-19 18:41
I confirm that the problem is still there in v4.0.1. 
Caution that MuseHub might also have a positive impact (like the mixer).
I have recently deinstalled it and the cracks reappeared (when F10 not in the main window).

**Comment by RomanPudashkin** [comment] 2023-08-01 08:18
Duplicate of https://github.com/musescore/MuseScore/issues/12968

**Closed by RomanPudashkin** 2023-08-01 08:18 UTC
