### ISSUE TITLE
[MU4 Issue] Shortcuts assignment dialog doesn't detect attempt to assign the same key to multiple commands

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11521] opened 2022-05-04 22:24 UTC
**Describe the bug**
While there is logic to detect that a key combination was previously assigned to a command before bringing up the dialog, once inside the shortcuts assignment dialog you can assign the same key combination to multiple commands without any warnings.

https://user-images.githubusercontent.com/86290556/166860997-d940d2cc-15c3-4bdd-9d08-2fea78b86bbf.mov

**To Reproduce**
1. Go to Edit|Preferences|Shortcuts
2. Double click on the first action in the list (for me, 128th note...)
3. Type 'T'
4. Click "Add" or "Replace"
5. Double click on the second action in the list ("16th note advance...")
6. Type 'T'
7. Click "Add" to "Replace"
8. NB no warning was ever given to the user that T had already been assigned to another action.

**Expected behavior**
Dialog should not allow a shortcut to be assigned to more than one action.
UI should display this text line beneath the header: "Shortcut conflicts with X"

<img width="532" alt="Screenshot 2022-05-05 at 1 46 19 pm" src="https://user-images.githubusercontent.com/86290556/166861095-b18f1c01-2bdf-42d3-a686-409add813764.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by bkunda** [comment] 2022-05-05 03:49
@wizofaus I have updated the issue description with a video to show this issue, as well a visual illustrating the "expected behaviour".

**Comment by wizofaus** [comment] 2022-08-01 20:57
Is this still something we plan to fix for v4.0? Happy to look at it. @Tantacrul @bkunda

**Comment by Tantacrul** [comment] 2022-08-01 21:23
There have been a lot of changes to the shortcuts panel last month and I recall an issue like this being solved. There's now a much more rigid system of warning, where the user is now given the option to switch a shortcut from one action immediately.

There are quite a few other changes made to make the whole thing more comprehensible too. I do wonder if this issue might need revising altogether, since much of the UX is quite different.

**Comment by DmitryArefiev** [comment] 2022-08-26 14:52
Tested in the **latest master** on Win10, Mac12, LinuxMint 20.2 - **no longer occurs**

Closing

**Closed** 2022-08-26 14:52 UTC
Labels: P1, needs testing
