### ISSUE TITLE
[MU4 Issue] Restore button causes whole Window to disappear

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#13135] opened 2022-09-02 12:46 UTC
The same button you use to maximise, but in this case it's restore (make windows smaller). When doing this sometimes it causes the Window to disappear to the side to the point it becomes unreachable. The only way to maximise it again is to Shift+right click on MS4 icon then click maximise. Once that's done then the restore/maximise behaves more normally. Yes this also happens in different scalings as well (100%, 150% etc)

https://user-images.githubusercontent.com/71656189/188148798-4e7218b2-02d1-4b0b-95e6-78307cf83e09.mp4

**Platform information**
 - Windows

**Comment by DmitryArefiev** [comment] 2022-09-08 14:02
@jessjwilliamson I also encountered with that problem sometimes on my Windows laptop with QHD display and 125%, but I never found the right way to reproduce.. And now I found the right steps and what causing it!!!

The steps on my machine:
1. Open MU and Revert to factory settings (for 100% reproducibility) 
2. Restart and close
3. Open and close **6 times!**
4. Open and click on Restore down button 

https://user-images.githubusercontent.com/90187801/189140150-31576d51-a781-4e37-85db-4842cebf44cb.mp4

**Comment by DmitryArefiev** [comment] 2022-09-08 14:03
And the reason for that strange steps is because of MU calculates wrong position of window in restore down state for each next open/close session 


https://user-images.githubusercontent.com/90187801/189142633-c9681fd5-e50f-4632-884b-810640ed5ef1.mp4

**Comment by DmitryArefiev** [comment] 2022-09-22 10:53
@Tantacrul I've changed to P1 Beta1 because in some cases  (Windows with QHD, 4FullHD displays) it **may lead user to inability to restore MU4 window from minimize state** without deleting hidden Preferences folder.
 It worth trying to fix it during Beta1.

https://user-images.githubusercontent.com/90187801/191728568-c18f9a06-333d-4e63-ab56-5de91fc723f0.mp4

**Comment by Tantacrul** [comment] 2022-09-22 11:07
@DmitryArefiev - OK.

**Comment by DmitryArefiev** [comment] 2022-10-03 07:55
Fixed in #13552

**Closed** 2022-10-03 07:56 UTC
Labels: P1

**Comment by DmitryArefiev** [comment] 2022-10-03 09:43
@jessjwilliamson Can you check on your Windows side as well (in master)? To make sure is all fixed now.

Thanks!
