### ISSUE TITLE
Beaming changes via 'Time Signature Properties' are not applied throughout all instruments of a score (Linux)

### ISSUE THREAD

**Issue by ttheng3810** [musescore/MuseScore#18815] opened 2023-07-27 08:40 UTC
### Issue type

UX/Interaction

### Bug description

When trying to edit the beaming pattern of a time signature (e.g. changing the rhythm grouping of a 7/8 time signature from 3+2+2 [MuseScore default] to 2+2+3) via 'Time Signature Properties', the change is only applied to one instrument for which the corresponding time signature is selected, instead of the entire score.

One has to edit the settings manually for each individual instrument, which is pretty troublesome especially when working on large orchestral scores.

### Steps to reproduce

1. Create a new score (either by manually adding instruments or by choosing a template file), preferrably multiple instruments.
2. Change the time signature by dragging a time signature element from the palette to the score (7/8 chosen in the video).
3. Right-click the time signature for one of the instruments in the score (e.g. Piccolo in the attached video) and select 'Time Signature Properties' via the right-click menu.
4. Edit the beaming pattern from the 'Time Signature Properties' settings.
5. Observe that the change is only applied to the one instrument in question (i.e. Piccolo in the video), but other instruments are unaffected.

[Opening 'Time Signature Properties' menu via the 'Properties' panel returns the same result, as demonstrated in the video.]

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/81245678/3b809277-5430-4b4b-a823-ee14d30acac8

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Pop!_OS 22.04 LTS, Arch.: x86_64

### Additional context

Creating a custom time signature with a different beaming pattern (e.g. 7/8 with 2+2+3 grouping instead of the default 3+2+2) and then dragging it into the score doesn't help.

**Comment by oktophonie** [comment] 2023-07-27 08:50
Duplicate of https://github.com/musescore/MuseScore/issues/16406, but thanks for the report!

**Closed by oktophonie** 2023-07-27 08:50 UTC
Labels: duplicate
