### ISSUE TITLE
[MU4 Issue] Measure count counts too long

### ISSUE THREAD

**Issue by Grillzombie** [musescore/MuseScore#15245] opened 2022-12-16 23:05 UTC
**Describe the bug**
If you play back a score, the measure count (upper right) counts too long.

**To Reproduce**
1. Open attached score
2. Play it back
3. Recognise, that there are only 6 measures, but the measure count extends to 8.3

**Expected behavior**
In this score, the measure count should only go until 6.4

**Platform information**
 - OS: OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

[MeasureCount.mscz.zip](https://github.com/musescore/MuseScore/files/10249915/MeasureCount.mscz.zip)

**Comment by cbjeukendrup** [comment] 2022-12-18 03:09
Duplicate of #13683. Thanks for reporting!

**Closed by cbjeukendrup** 2022-12-18 03:09 UTC
