### ISSUE TITLE
[MU4 Issue] Parts - Cannot Delete Part

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11349] opened 2022-04-25 13:44 UTC
**Describe the bug**
Cannot delete selected part. Trash can icon and "Delete" text option remain greyed out.

**To Reproduce**
1. Select Parts from top menu 
2. Select an individual part
3. Try to click on trash can when part is selected
5. With part selected, click on three dot menu for selected part and try to click on "Delete"
6. See error

**Expected behavior**
Trash can menu should be in active state and clickable when part is selected. Delete option under three dot menu should be in active state and clickable when part is selected. When either delete option is clicked on, a delete confirmation prompt should appear. If confirmed, part should be deleted.

**Screenshots**
<img width="843" alt="Screen Shot 2022-04-25 at 4 38 51 PM" src="https://user-images.githubusercontent.com/30370609/165101416-2ce510ec-2d07-4d4c-8a4b-156c4361dbd9.png">
<img width="529" alt="Screen Shot 2022-04-25 at 4 39 48 PM" src="https://user-images.githubusercontent.com/30370609/165101462-cba7a467-aceb-4040-89c0-6b06aac50edf.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment] 2022-04-25 14:03
@Tantacrul  - FYI

**Comment by Tantacrul** [comment] 2022-04-25 14:10
I've added a P1 for this. I assume this is an oversight. I think the preferred solution should be (in order of priority):

1. We allow users to delete part scores
2. Of there is some awful technical issue, then we just remove the option to delete (please let me know if this is needed)

**Comment by sammik** [comment] 2022-05-13 20:41
There is disabled `Delete`, because in fact part doesnt exist yet.

See

https://user-images.githubusercontent.com/1646034/168386370-aff40769-8df4-4d62-867c-26a7a06b4781.mp4

**Comment by wizofaus** [comment] 2022-06-19 07:04
There's definitely a UX issue here.
If I open a score that *does* have a part created, I can see it in the list, and delete it - and it disappears from the Parts dialog. But if I then reopen the Parts dialog, the part is shown again as though is still exists. "Rename" is the only command available but it doesn't actually work (after closing and re-opening the original name is shown).
So what are these non-existent parts that are shown (one for each instrument) - they don't seem to serve any purpose?

But having dialog come up blank might be quite off-putting for users too.

Also if you use "Create New Part", then close the Parts dialog and re-open - it's gone! So what did you actually create?

Essentially it seems the only thing's useful is to use "Open" to *actually* create the part.

Also there's a mismatch between "Close" and "Open" - the former closes the dialog and the latter just the selected part.

All in all, very confusing...can you point me to the design document that describes how it's actually supposed to work @Tantacrul  and/or @bkunda ?

**Comment by sammik** [comment] 2022-06-19 11:21
Problem is, IMHO, that parts are in fact created just when user click "Open".

But in dialog, it behaves (well, try to beheave), as if they were already created, but they are not. In dialog, that is only some kind of meta info used / prepared for creating part (which didnt happen yet).

So probably silmpest solution would be, that parts will really be created right after user opens dialog first time, and, also "Create New Part" should create real part, not just meta info, like it does now.

**Comment by HemantAntony** [comment] 2022-06-19 11:27
What about if the score has a lot of parts. Won't it have an effect on performance?

**Comment by wizofaus** [comment] 2022-06-19 11:28
Hmm, just opening a dialog shouldn't cause actions that modify the score.
I have plenty of ideas about how this dialog *could* work, but I'm pretty sure @Tantacrul & @bkunda have already come up with a good design, it just hasn't been implemented properly yet.

**Comment by bkunda** [comment] 2022-06-20 12:44
@wizofaus see #11420 and #11858 for the fixes we have proposed. I think these fixes should address some of the issues you've raised, particularly with regard to closing/reopening the dialog and the behaviour of the "open" and "close" buttons (on this latter issue, we actually polled users to assess the anticipated functionality of these buttons in the new design, so we're reasonably confident that this will be an improvement).  

The issue with "delete" is that, from the user's POV, the parts dialog shows them the _available_ parts in their score (remember it's completely immaterial to the user whether these parts have been "created" or not – in their minds, they can "see" the part so it must exist). Making it possible to delete these parts means they are no longer "available", meaning they won't be retrievable if deleted unless we design something extra to expose them again.

Rather than further compounding the design, I think a simple solution for now would be to remove the "delete" (trashcan) icon entirely, and to expose the "delete" context menu option only for parts that the user has created or duplicated themselves. Parts that appear by default as "available" in the UI would not have this "delete" option available in the context menu.

@RomanPudashkin this is the fix I would propose to add to your PR #11858. @Tantacrul if you agree with this solution, I'll also amend the design document accordingly.

**Comment by wizofaus** [comment] 2022-06-20 20:59
So to confirm if I have, for instance, a score for double choir and small ensemble, I can't get rid of the individual voice parts? I don't think I've ever worked with a choral score that had such parts...

**Comment by Tantacrul** [comment] 2022-06-20 21:06
You just don't print them.

**Comment by wizofaus** [comment] 2022-06-20 21:56
Yeah, it's definitely not the end of the world, just noting there are situations where the auto-generated parts might not be wanted and would just clutter up the dialog etc.

**Comment by sammik** [comment] 2022-06-20 22:44
Is it intended, that "available parts" should be unremovable, or it is just "servicable solution at the moment"?

If it is intended, than OK, sorry for spamming.

But if not, belove is possible description:

If I am right, major problem of this Parts dialog is, that it contains combined list. 
1. list of created parts + 2. list "available parts" (which is in fact just list of score instruments / staves)

Once second list (list of "available parts") would be removed from Parts dialog, most of bugs would be gone.

Only thing todo would be to create parts at time
1) when new score is created (@wizofaus you are right, creating them by opening dialog was wrong idea)
2) when new instrument(s) are added to score
3) when user clicks "Create new part" (and not when he clicks "Open")

**Comment by wizofaus** [comment] 2022-06-20 22:55
There are performance and storage reasons why only actually fully instantiating the parts at the point they're explicitly needed makes sense.  But I think it's fine to hide that from users, so long as it doesn't mess with their mental model of what they've actually "created".  The problem is currently it's poorly hidden, and does mess with that model.

**Closed** 2022-07-04 15:04 UTC
Labels: P1

**Comment by wizofaus** [comment] 2022-10-11 07:58
To clarify then,  if I have a score for, say, double choir and small ensemble, there'd be no way to delete the 8 individual choir voice parts? I'm not sure I've ever seen a choral score that would have such individual parts...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cadiz2** [comment] 2024-03-17 22:14
Reported again, see discussion on forum: https://musescore.org/en/node/361886

**Comment by DmitryArefiev** [comment] 2024-03-21 15:57
> Reported again, see discussion on forum: https://musescore.org/en/node/361886

FYI @bkunda @avvvvve

**Comment by Ratspeed** [comment] 2024-12-12 04:51
Total thumbs up on this issue!

The ability to delete parts but keep the instrument is needed. The "Delete" button is not present if the part is a default part auto-generated by MuseScore, but the Delete button is there if it's a part I made myself.

Default part - Delete button not present:
![image](https://github.com/user-attachments/assets/554c512b-dd9d-47c6-a3fe-2cd41073e3bf)

Part I created - Delete button present:
![image](https://github.com/user-attachments/assets/3282e63f-2877-4e0b-863e-6cf8f0a6804f)

There was somewhat of a laborious argument on the forum regarding whether this feature was needed. The case seems very simple to understand and valid in my opinion: If people don't want to generate and/or print a part for a staff / instrument they don't want, they should be able to delete the part so it doesn't show up on the Export window. Else, the "Select All" button in Export can't be used for quick part export selections.

Hopefully this is an omission like Tantacrul said it might be in 2022. According to the OP in the forum thread, this feature was present in MuseScore 3.

**Comment by Jojo-Schmitz** [comment] 2024-12-12 08:29
Please reopen this, a real delete option is really needed.

**Comment by cbjeukendrup** [comment] 2025-03-02 16:19
> Please reopen this, a real delete option is really needed.

Better open a fresh new issue, with a complete, concise, and precise description of the problem.

(Sorry for the 3 months later reply, I found this post while cleaning up my inbox)

**Comment by Jojo-Schmitz** [comment] 2025-03-02 16:22
I don't see how the initial post is not a _complete, concise, and precise description of the problem._

**Comment by cbjeukendrup** [comment] 2025-03-02 16:34
Okay, I'll take care of it myself.

**Comment by cbjeukendrup** [comment] 2025-03-02 17:18
See https://github.com/musescore/MuseScore/issues/26877. Perhaps not much more concise, but at least it identifies the root cause of the problem and doesn't have dozens of back-and-forth comments.

**Comment by Jojo-Schmitz** [comment] 2025-03-02 17:23
Thanks!

**Comment by MarcSabatella** [comment] 2025-03-02 17:34
I am commenting here rather than in the new issue to keep that issue "clean".

There is one very important aspect to this request that I don't see addressed in the new issue.  It's only barely alluded to in this one, but it comes up fairly often in forum discussions etc.

While in an ideal world the "reset" option would be completely sufficient to get one of the pre-generated parts back to its initial state, the fact is that this is simply not true.  There are a number of things that you just cannot fix once a part has been generated, even after a reset.  Of course, I know the next question should be, "like what?" and unfortunately I cannot think of an example.  I also can't be entirely sure the answer wouldn't be to enhance the reset command.  But I'm hoping to trigger anyone else's memory of what I might be talking about.  I can certainly try ask on the forum if no one here has any immediate insight.

I *think* it is something like, some particular feature like local time signatures not being available for a score that has parts already generated.  I know that particular issue is already fixed for 4.5, but I have a feeling there was more to it than that.

**Comment by Jojo-Schmitz** [comment] 2025-03-02 17:38
Once it is generated, like by changint some aspect of it, even a reset doesn't get rid if it, it's still stay in the mscz under Exceprts. So it still increases the file size and without any need.

**Comment by MarcSabatella** [comment] 2025-03-02 17:41
This is true, but I was remembering something more significant than just filesize / saving speed - some actual functionality that was affected by the inability to delete parts.  Local time signatures was one but I believe there was more.  So I just want to be sure that whatever solution is chosen handles all such cases.

**Comment by Jojo-Schmitz** [comment] 2025-03-02 17:43
Yes, my remark was (meant as) an addition

**Comment by cbjeukendrup** [comment] 2025-03-02 18:30
Good point, I created a separate issue about it: https://github.com/musescore/MuseScore/issues/26878

However, besides local time signatures and file size (etc) reduction, I can't really think of other situations where "Reset" might not be enough. Maybe in very crazy corruption cases where there's something wrong with an `Excerpt`'s `m_parts`, because that is copied by the copy constructor of `Excerpt`... but I can hardly imagine that something like that would happen.

**Comment by MarcSabatella** [comment] 2025-03-02 18:37
Thanks for creating that issue!  It's entirely possible local time signatures was the only thing and it just came up often enough that I was thinking there was more.  I will see if I can find other references.
