### ISSUE TITLE
Color of brackets is not saved

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#22763] opened 2024-05-10 23:04 UTC
### Issue type

Opening/saving issue

### Bug description

If a bracket is colored and the score is saved, the bracket is black again when the score is reopened

### Steps to reproduce

1. Open score
2. Mark bar
3. Create bracket in palettes
4. Mark bracket
5. open Properties/Appearance
6. Change color of brackets
7. save score
8. open score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/103463374/51cd4627-4ba1-4eb0-9e9d-cdb6d8cfb41d

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

No.

### Operating system

macOS 14.4.1

**Comment by cbjeukendrup** [comment] 2024-05-11 00:43
Duplicate of https://github.com/musescore/MuseScore/issues/20932, but thank you for reporting this!

**Closed by cbjeukendrup** 2024-05-11 00:43 UTC
