### ISSUE TITLE
[MU4 Issue] - crash on pasting into text elements within frames

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12833] opened 2022-08-12 20:17 UTC
**Describe the bug**
program crashes when pasting text from outside source into text elements within frames

**To Reproduce**
1. copy text from outside source
2. paste into text element within a frame (in my case, Lyricist prompt)
3. initiates crash

**Expected behavior**
text will copy/paste as expected into text elements

**Platform information**
 - Windows 11

**Comment by Wim4rk** [comment] 2022-08-12 20:55
Tried to reproduce, got the expected behavior. Ubuntu 20,04.

**Comment by MarcSabatella** [comment] 2022-08-12 21:25
Works for me too, both on Linux and Windows 11.  You mean, the input field within the new score wizard, not any particular score, right?

Maybe it's specific to the text, or where you copied it from.  More precise steps to reproduce would help.

**Comment by drbirkenstocks** [comment] 2022-08-12 21:54
Here's a video of my process—crashes every time.

https://user-images.githubusercontent.com/111152765/184449663-2d62c776-80d2-4202-ba33-f9b4768e38ce.mp4

**Comment by MarcSabatella** [comment] 2022-08-12 22:17
OK, so you're *not* taking about the input field in the wizard, but are talking about the text in the frame itself.  Now I can reproduce.  Seems true of title etc as well.  I recommend updating the title of this issue to be description of the actual problem - "crash on pasting into text elements within frames".

**Comment by drbirkenstocks** [comment] 2022-08-12 22:21
Thanks, Marc—updated. I'm brand new to the whole GitHub thing, so I appreciate your guidance on reporting some of these items. :)

**Comment by Tantacrul** [comment] 2022-08-31 20:59
Can't reproduce on Mac myself, so I'm wondering if it is Linux only?

**Comment by MarcSabatella** [comment] 2022-08-31 21:42
I can't reproduce on a *current* build on Linux or Windows, but I can with the *alpha* on both systems.  So it could be it was fixed somehow already.

**Comment by Tantacrul** [comment] 2022-08-31 21:43
OK, well I'll tentatively close this for now then, since we've both covered all OS's in the latest nightly.

**Closed by Tantacrul** 2022-08-31 21:43 UTC
Labels: P2
