### ISSUE TITLE
[MU4 Issue] Clicking multiple times in ties when on Playback crashes MU4

### ISSUE THREAD

**Issue by maestroharmony** [musescore/MuseScore#14256] opened 2022-11-01 18:45 UTC
**Describe the bug**
When clicking multiple times in a tie when on Playback in MU4 it crashes.

**To Reproduce**
1. Download the zip file.
2. Open the score
3. Start playback
4. Click the notes with ties
5. Crash

**Expected behavior**
No crash on MU4 when selecting a tie multiple times on Playback

[Click Crash Bug.zip](https://github.com/musescore/MuseScore/files/9913165/Click.Crash.Bug.zip)

https://user-images.githubusercontent.com/104784996/199313184-f779717b-466f-4036-aaf4-b2439497be3f.mp4

**Platform information**
 - OS: Windows 11, R7 3700x, 32 Gb RAM

**Comment by zacjansheski** [comment] 2023-05-26 20:35
Unable to reproduce, closing this issue.

**Closed by zacjansheski** 2023-05-26 20:35 UTC
Labels: needs info
