### ISSUE TITLE
Sound preview when using MIDI Keyboard not working

### ISSUE THREAD

**Issue by JosephZayoun** [musescore/MuseScore#12319] opened 2022-07-08 12:52 UTC
(Edited by Dmitry Arefiev)

**Describe the bug**
Sometimes it doesn't work perfect in MU3.. but it doesn't work at all in MU4

**To Reproduce**
1. Open a score
2. Add some notes 
3. Esc
4. Select bar again
5. Play something on MIDI Keyboard - you should here the instrument sound

**Platform information**
 macOS, Windows, Linux]

**Additional context**
Doesn't occur in MU3

https://user-images.githubusercontent.com/103273970/177995481-6520b9eb-de80-40f6-8e0a-ed9040f29f96.mp4

**Comment by DmitryArefiev** [comment] 2022-07-08 17:25
@Tantacrul It doesn't work perfect in MU3.. But it doesn't work at all in MU4. 
Putting this to Beta1 with P1

**Comment by rgreen5** [comment] 2022-07-08 17:39
Looks like a duplicate of #11234?

**Comment by Tantacrul** [comment] 2022-07-08 17:58
> Looks like a duplicate of #11234?

Yes. It looks to be. Closing in favour of the original issue.

**Closed by Tantacrul** 2022-07-08 17:58 UTC
Labels: P1
