### ISSUE TITLE
Changing the 'sound' field in the mixer during playback resets the playback offset for that instrument to where it was when playback started

### ISSUE THREAD

**Issue by Starwort** [musescore/MuseScore#17316] opened 2023-04-22 12:51 UTC
### Issue type

General playback bug

### Bug description

If you change the sound assigned to an instrument while listening to the score (something I've done lots in MU3 to check precise instrument choices) via these buttons (![image](https://user-images.githubusercontent.com/16487249/233785462-693e63d8-010a-4c15-af8e-24ee6de604de.png)) then playback *for that instrument only* will jump back to the original playback point, leading to (possibly very) desynced playback

### Steps to reproduce

1. Create or open a score (preferably with at least two instruments in it)
1. Select a start point (or leave it as the beginning of the score)
1. Open the mixer
1. Start playback
1. Change the sound for one of the instruments to something else (e.g. from muse sounds to MS Basic, ~~or from MS Basic to muse sounds~~ in my last test this did not trigger the bug; perhaps a VST → sound font issue?)
1. The instrument you have changed will be desynced from both the playback position indicator line, and the playback of the other instrument(s)

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

Choose option...

### Operating system

OS: Ubuntu 22.04.1 LTS, Arch.: x86_64

**Comment by cbjeukendrup** [comment] 2023-04-24 12:02
I think this is a duplicate of [#15047](https://github.com/musescore/MuseScore/issues/15047). Thanks for reporting!

**Closed by cbjeukendrup** 2023-04-24 12:02 UTC
Labels: playback
