### ISSUE TITLE
Unable to change volta text font in Style editor

### ISSUE THREAD

**Issue by Velikyi** [musescore/MuseScore#12811] opened 2022-08-11 23:28 UTC
**Describe the bug**
Not able to change font for voltas. In the Style editor, it lets me change it, but reverts back to Edwin when closing, regardless of clicking "Ok" or "Cancel". Also won't show font selection in the left-hand object editor when selecting the volta, only the text field which you can edit, but no font selector like in MuseScore 3.

**To Reproduce**

1. Create a volta
2. Go to 'Style editor'
3. Click on 'Text styles'
4. Scroll down to 'Volta'
5. Change font
6. Click "Ok"
7. Notice the font hasn't changed
8. Go back to the style editor, and see it has reverted back to Edwin (default)
9. Click on volta
10. In the left-hand object editor click "Text"
11. Notice you can change the text, but not the font (like you could earlier)

**Expected behavior**
When performing the steps above, I would expect that the font for the voltas actually changed to the one I selected, and not revert back to default without changing anything. Also I would expect there to be a menu to change the font individually independent from the style editor, like there was in previous version.

**Screenshots**
<img width="935" alt="Skjermbilde 2022-08-12 kl  01 26 30" src="https://user-images.githubusercontent.com/11480173/184258854-e6f694ad-bd99-42b0-ba46-50150350b2bc.png">
![Bilde_2022-08-12_012722294](https://user-images.githubusercontent.com/11480173/184258913-2f3356ac-c737-4582-89cc-85a89b77c953.png)

**Platform information**
 - macOS 12.1 on MB Pro 14" M1 Pro

**Comment by HemantAntony** [comment] 2022-08-12 02:41
Please give this issue a good title (on the top)

**Comment by HemantAntony** [comment] 2022-11-12 12:58
@Tantacrul check this one please: #14494 :)

**Comment by cbjeukendrup** [comment] 2022-11-12 17:58
This issue turns out to be a duplicate of https://github.com/musescore/MuseScore/issues/13420, which already had a fix pending in #13292. Very unfortunate situation.

**Comment by Tantacrul** [comment] 2022-11-12 18:44
Yes. Unfortunate indeed. However, since we're so busy - @cbjeukendrup, please close the duplicate issue and PR you think makes the most sense (with out apologies).

**Comment by cbjeukendrup** [comment] 2022-11-12 21:19
Okay. Let's start by closing this issue as a duplicate of #13420. For the PRs, we'll try to choose the best one. 

(I normally read all issues and try to remember as many as possible so that I can flag duplicates directly when they come in, but I must have missed this one.)

**Closed by cbjeukendrup** 2022-11-12 21:19 UTC
Labels: P2
