### ISSUE TITLE
[MU4 Issue] Musescore crashes when selecting particular elements

### ISSUE THREAD

**Issue by OttoKaaij** [musescore/MuseScore#15440] opened 2022-12-20 15:12 UTC
**Describe the bug**
When interacting with this file, different interactions can cause musescore to crash.

**To Reproduce**
1. Open attached file in musescore
2. Select the half bar rest in the second half of bar 27, in the oboe part
3. Musescore crashes.

**Expected behavior**
Musescore shouldn't crash when selecting rests.

**Platform information**
 - OS: Ubuntu 22.04, using the AppImage and muse hub sounds.

**Additional context**
Stability has been a real issue. Musescore crashes every couple bars, so it has been pretty much unusable. This is just one example, but the only one I managed to steadily reproduce. This file was written from scratch in MS 4.

[crash.zip](https://github.com/musescore/MuseScore/files/10269592/crash.zip)

**Comment by miwelte** [comment] 2022-12-20 15:23
Confirmed. Similar effects in: [15443](https://github.com/musescore/MuseScore/issues/15433) or in other tested scores.
Crashes also when selecting several various individual elements twith the aim of changing properties.

**Comment by OttoKaaij** [comment] 2022-12-20 15:36
Issue does not happen for me if I go view -> playback setup and select Musescore Basic.
If I reselect muse sounds and select the rest again, it breaks again.

Does this happen for you too?

**Comment by KleinkMusic** [comment] 2022-12-24 00:02
Can confirm. I have the same issue with one of my scores.

**Comment by cbjeukendrup** [comment] 2022-12-24 00:19
Might be related to #15512 and #15463

**Comment by zacjansheski** [comment] 2023-07-31 18:15
Is this still actual?

I just tried on the current master, Ubuntu 20.04.6, with Muse Sounds profile and could not reproduce.

**Comment by zacjansheski** [comment] 2023-08-15 20:55
Closing

**Closed by zacjansheski** 2023-08-15 20:55 UTC
Labels: needs info, crash
