### ISSUE TITLE
[MU4 Issue] [TAB] Placing notes with a beam breaks tablature

### ISSUE THREAD

**Issue by Majora320** [musescore/MuseScore#11526] opened 2022-05-05 01:00 UTC
To replicate:
- Create a score and add an instrument with tablature, e.g. Electric Guitar (tablature)
- Select a note duration that will create a beam
- Place several notes next to each other

The beam will be offset above the notes by an increasing amount relative to the number of notes placed.

https://user-images.githubusercontent.com/16787503/166849909-b7af7a9e-eeb1-431a-83a4-912060ff7211.mp4

This bug was introduced with 0e333277bfbdeec9747d0d29a5920fdde4dc092f, it doesn't appear before this commit.

**Additional context**
Related to #11092 changes

**Comment by Tantacrul** [comment] 2022-05-05 16:26
Weird. I'm unable to replicate this on MacOS.
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/21022311/166968940-30cd48fc-acee-49d2-92ca-7a9ca3fb77e2.png">

**Comment by bosshog223** [comment] 2022-05-05 16:34
![image](https://user-images.githubusercontent.com/102619153/166970491-cf572925-dd28-4be9-8b4c-fed75cd73b32.png)

im unable to replicate in windows 10

**Comment by Majora320** [comment] 2022-05-05 16:43
I'm on Linux, maybe it's platform specific? Also make sure whatever build you're using has 0e33327, I'm not sure if that commit has made it into the nightly yet.

**Comment by Tantacrul** [comment] 2022-05-05 16:48
Perhaps @DmitryArefiev or @shoogle could see if they can replicate it?

**Comment by HemantAntony** [comment] 2022-05-05 16:56
@Tantacrul I can reproduce on Windows 11

**Comment by boryskuzmenko** [comment] 2022-05-05 16:56
It's reproducible on Linux

**Comment by Tantacrul** [comment] 2022-05-05 17:00
Can you specify the exact steps? What instrument did you add, etc?

I feel I should be able to reproduce this.

**Comment by boryskuzmenko** [comment] 2022-05-05 17:02
Use the last master build
https://user-images.githubusercontent.com/101250347/166975099-9bce3d7f-57d6-4487-85e6-bd0e7e326740.mov

**Comment by Tantacrul** [comment] 2022-05-05 18:37
OK, confirmed in the latest master:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/21022311/166997335-cf63d209-cf8b-4b58-af70-b9c534cfab27.png">

**Comment by boryskuzmenko** [comment] 2022-07-12 16:21
🟢 **Can't reproduce**. Closing
Tested on macOS 12, Win 11, Ubuntu 20

**Closed by boryskuzmenko** 2022-07-12 16:21 UTC
Labels: P1
