### ISSUE TITLE
Articulation is doubled (marcato-staccato) when adding a second note.

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#18573] opened 2023-07-13 15:27 UTC
### Issue type

Engraving bug

### Bug description

MU doubles de articulation (marcato staccato) when adding a second note using Shift +.

Doesn't seem to happen with adding an interval or adding more notes.

### Steps to reproduce

1. new score, add piano
2. enter note (D)
3. toggle marcato and staccato on the note
4. shit+d (add another note) = should show double articulation
5. delete the upper note = should leave two articulation on one note

### Screenshots/Screen recordings

[marcato staccato bug.zip](https://github.com/musescore/MuseScore/files/12041045/marcato.staccato.bug.zip)

### MuseScore Version

4.1 (but had the same issue with previous nightly)

### Regression

I don't know

### Operating system

macOS 13.4.1 (22F82)

**Comment by zacjansheski** [comment] 2023-07-13 16:21
I am not seeing this, am I following the steps correctly?


https://github.com/musescore/MuseScore/assets/69917893/a16fc915-912d-4172-a0ce-a57e4887966b

**Comment by zacjansheski** [comment] 2023-07-13 16:30
I still am not able to reproduce
https://github.com/musescore/MuseScore/assets/69917893/5a72962b-9156-4464-95e9-6c6d7ac60a24

**Comment by MarcSabatella** [comment] 2023-07-13 17:43
I can reproduce although it took a bit of experimentation.  Try this:

1) press N for note input mode
2) type C
3) press Esc to leave note input mode
4) click the marcato & staccato buttons on the toolbar to add the markings
5) Press Esc to deselect the note
6) Click the note to reselect it
7) press Shift+E to add an E to the chord

Now you'll get the doubled marking.  This isn't the only path to that result, but it's one that is reproducible for me.

A possibly related issue can be seen staying in note input mode:

1) press N for note input mode
2) click the marcato buttons
3) type C to enter a C with marcato applied
4) press Shift+E to add an E

This results in the original marcato being removed.

THe possible relationship here is that in both cases, I think somehow we are looking at the toolbar to decide what we should do when really, Shift+letter should probably ignore that and just add the note.

**Comment by oktophonie** [comment] 2023-07-14 09:37
I encountered the second issue here recently and it's very annoying. It happens also outside note input mode, if you are selecting existing notes with articulations and want to add notes to them with Shift+<letter> to make chords. Also it's a regression on 4.0.2.

This may well have been introduced in https://github.com/musescore/MuseScore/pull/17303 or a related PR.

**Comment by zacjansheski** [comment] 2023-09-27 18:38
The second bug in @MarcSabatella 's comment is resolved by https://github.com/musescore/MuseScore/pull/19434

The first issue is still present.  (Deselect, reselect then add note with articulations on)

https://github.com/musescore/MuseScore/assets/69917893/f4cea9c4-2bf0-401d-82ee-37be5e27d737

**Closed** 2023-10-04 11:33 UTC
Labels: P2, regression, engraving, UX/interaction
