### ISSUE TITLE
Fermata ignores tempo change lines

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#22139] opened 2024-04-02 02:41 UTC
### Issue type

General playback bug

### Bug description

1. The playback tempo of notes with fermatas is calculated based on the tempo before the tempo change is applied.
2. After the note with fermata finishes playing, the tempo will revert to the tempo before the tempo change was applied.

### Steps to reproduce

1. Input notes, a tempo change line, and a fermata
2. Start playback

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102702868/bb50e1f7-7b2e-4922-b47b-d5c48fcd5c09

### MuseScore Version

MuseScore 4.2.1, Nightly from master

### Regression

No.

### Operating system

Windows 11 Pro 23H2

**Comment by CoolSpy3** [comment] 2024-04-02 04:01
I think this is a duplicate of #15674 .

**Comment by zacjansheski** [comment] 2024-04-02 12:44
Closing as duplicate

**Closed by zacjansheski** 2024-04-02 12:44 UTC
Labels: playback
