### ISSUE TITLE
tied notes play seperately 

### ISSUE THREAD

**Issue by iamjames101** [musescore/MuseScore#21136] opened 2024-01-22 03:31 UTC
### Issue type

Muse Sounds bug

### Bug description

the second note of a tied pair is played separately, as if the tie didn't exist. both notes are getting articulated fully instead of being tied together with only one initial articulation while using the violin solo musesound 

### Steps to reproduce

select violin (solo) as your sound, notate a half note in a 4/4 measure tied to an eighth note. play back and listen for double articulation 

### MuseScore Version

4.2

### Regression

Choose option...

### Operating system

Windows 11

**Comment by DaddyLudwig** [comment] 2024-01-22 03:38
Are you sure that you inputted a tie and not a slur? Cause if you inputted a slur, it would articulate twice. I get a sustained note with 1 articulation if I insert a tie.

Video demonstrating how the tie sustains and the slur articulates each note:

https://github.com/musescore/MuseScore/assets/6530761/a781f4ff-df4b-4535-b928-bd8ceb8d2292

**Comment by iamjames101** [comment] 2024-01-22 03:40
Yeah I made sure of that. My guess is that the violin solo muse sound
accounts for the limited bow length of a violin and creates that extra
articulation after a certain duration, only problem being that a good
violinist can change bow directions in a way that’s almost impossible to
hear so it’s even more unrealistic than just sustaining

**Comment by iamjames101** [comment] 2024-01-22 03:44
If it’s working for you my computer and musescore install is probably just
bugged a little I could try reinstalling maybe

**Comment by zacjansheski** [comment] 2024-01-29 21:22
Unable to reproduce.  Closing unless new evidence of this issue surfaces.

**Closed by zacjansheski** 2024-01-29 21:22 UTC
Labels: needs info, muse sounds
