### ISSUE TITLE
Make Fine tune position difference (now 0.5) 0.1

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#19022] opened 2023-08-11 10:58 UTC
### Your idea

A value of 0.5 is too large for fine tuning, this forces manual typing of  the value, and that does not work friendly with the mouse (Windows).
It is Difficult to select the displayed value, in order to type a new value.

(For offset  - leading space etc.)

### Problem to be solved

See abive

**Comment by oktophonie** [comment] 2023-08-11 11:39
Duplicate of https://github.com/musescore/MuseScore/issues/16862

**Closed by oktophonie** 2023-08-11 11:39 UTC
Labels: feature request
