### ISSUE TITLE
[MU4 Issue] Incorrect Implementation of Fortepiano (symbol: fp) dynamics for Piano playback

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#15234] opened 2022-12-16 18:44 UTC
**Describe the bug**

"fp" is incorrectly implemented as "staff volume down".  This is incorrectly decreasing the audio for the original long sustained (whole) notes played as forte (f), along with the subsequent notes played as piano (p).

**To Reproduce**

Attached score (mscz), mp3, and/or image (png)

**Expected behavior**

"fp" should be implemented by note velocity only, or *not* decrease the volume for the originally played forte notes.

**Screenshots**

**Platform information**

MS4/4.0 Windows 10/64 on 2022.12.16
Fails with MSBasic Soundfont, and extrnal Piano VST (EastWest Opus)

**Additional context**

Did not test with MuseSounds Piano, or any other instruments

![ms4-fp-20221216](https://user-images.githubusercontent.com/116447844/208167195-d6a88530-1525-4c4e-9055-e3ad0f3c62b5.png)
[ms4-fp-20221216.zip](https://github.com/musescore/MuseScore/files/10248267/ms4-fp-20221216.zip)

**Comment by cbjeukendrup** [comment] 2022-12-16 19:26
For piano, you're absolutely right; for instruments that can do single-note-dynamics, the current behaviour is absolutely desired.

This issue is more general than the fp dynamic, and is logged here: #13877

So I'll close this one as a duplicate of #13877. Thanks for reporting anyway!

**Closed by cbjeukendrup** 2022-12-16 19:26 UTC
