### ISSUE TITLE
[MU4 Issue] The view window doesn't scroll horizontally in lines when notation goes off the view window

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14483] opened 2022-11-11 19:18 UTC
**Describe the bug**
When the current note goes off the side of the view window, it doesn't scroll to put it back in the view window (playback, note input)

**To Reproduce**
1. Create a score
2. Resize view window so it doesn't cover a whole line
3. Navigate to the end of the line
4. See that the window doesn't move

**Expected behavior**
The view window should always move so the current selection is in view

**Screenshots**

**Platform information**
 - OS: Mac

**Additional context**

**Comment by MarcSabatella** [comment] 2022-11-11 22:10
Normally it should work.  Is it possible you've turned off the "Pan score automatically" option (see settings icon on playback toolbar)?  If not, please attach you score and say which measures specifically you are having problems with - a video wouldn't help as well.

**Comment by erinic04** [comment] 2022-11-12 00:39
The view still scrolls to new lines, it just doesn't scroll to the end of lines

**Comment by MarcSabatella** [comment] 2022-11-12 00:51
It does for me, so as mentioned, a clearer description of how to reproduce this would be useful I'm sure.

One interesting issue I discovered while working on another aspect of the view positioning code today - it won't always reposition if you're zoomed too far in.

**Comment by erinic04** [comment] 2022-11-12 00:55
Seems to only happen for me on Mac; on Windows it does it just fine. I'll do some testing and see what might be causing it

**Comment by erinic04** [comment] 2022-11-12 00:58
Strange; it doesn't happen anymore, even on the same nightly and same score

**Comment by Tantacrul** [comment] 2022-11-22 12:43
I'm going to close this since it seems the issue can't be reproduced by anyone (including me). Will reopen if needed.

**Closed by Tantacrul** 2022-11-22 12:43 UTC

**Comment by erinic04** [comment] 2024-05-12 06:04
FWIW I believe this is because if you fullscreen Musescore and then un-fullscreen it on a small enough monitor (or scaled up too much) then musescore thinks that the view is larger than it is sincethe minimum height and width is larger than the screen size
