### ISSUE TITLE
[MU4 Issue] Muse Sounds Violin 1 - long notes rearticulate often

### ISSUE THREAD

**Issue by Reedbeta** [musescore/MuseScore#16340] opened 2023-02-12 21:18 UTC
**Describe the bug**
Using the Muse Sounds "Violin 1" sound, when holding a long note it very audibly re-articulates it every couple of seconds.

An example score is attached here: [violin sustain bug.zip](https://github.com/musescore/MuseScore/files/10717319/violin.sustain.bug.zip).

The issue doesn't occur with the Violin 2 sound, or the MS Basic soundfont. It seems to be specific to Violin 1.

**To Reproduce**
1. Create a score with a violin staff.
2. Add a whole note.
3. Set the tempo to something slow, so that the note lasts several seconds.
4. Playback using Muse Sounds Violin 1.
5. Hear the note re-articulate as if it were several separate notes.

**Expected behavior**
Long notes should sound like a single long note without audible re-articulation.

**Platform information**
- OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by arfgab** [comment] 2023-02-15 22:58
Possibly related problems with Violin 1 - weirdly in first repeat only, that long notes did not stop playing and final minim note had horrible warble when crescendo apply (1st time only).

**Comment by Dima-S-Jr** [comment] 2024-09-05 14:15
Why hasn't anyone been assigned yet? The problem is still relevant, the re-bow is still audible: 

https://github.com/user-attachments/assets/478b1492-e4d3-403f-aa3b-8851a17f8842

**Comment by MarcSabatella** [comment] 2024-09-05 14:23
Muse Sounds issues are now to be reported in their own issue tracking system via Muse Hub.  So, best to submit this issue there to be sure that team sees it.  It's certainly possible they might have logged it internally already, but it's unlikely they'd be updating the status of this or other "orphaned" issues on GitHub,

**Comment by cbjeukendrup** [comment] 2024-09-09 02:24
Closing as per the comment above; please report this via Muse Hub, so that it is received by the people who are responsible for it. Thanks!

**Closed by cbjeukendrup** 2024-09-09 02:24 UTC
Labels: muse sounds
