### ISSUE TITLE
[MU4 Issue] Tuplet brackets and numbers appearing in the wrong places

### ISSUE THREAD

**Issue by contrabassoon** [musescore/MuseScore#14348] opened 2022-11-05 17:55 UTC
**Describe the bug**
Tuplets appear in the wrong places in parts

**To Reproduce**
1. Open a score created in musescore 3 that contains tuplets and multiple parts
2. Open parts and make the instruments visible

**Expected behavior**
It is expected that the tuplet numbers and brackets appear above or below the notes that they apply to

**Screenshots**
![image](https://user-images.githubusercontent.com/117535530/200134172-0113e91a-b5b4-4ffb-a910-9455e39d6851.png)
![image](https://user-images.githubusercontent.com/117535530/200134192-d4d964dd-c801-407e-a7d5-0f102f17aeaa.png)

**Platform information**
 - OS: Windows 11

**Additional context**
This issue happens in all views of the parts, but not the score

[Esprit_De_Corps.zip](https://github.com/musescore/MuseScore/files/9944420/Esprit_De_Corps.zip)

**Comment by cbjeukendrup** [comment] 2022-11-05 18:21
Strange enough, I can't reproduce this. The tuplets appear fine for me. But according to the contents of the file, you _are_ using the latest beta...

Could you maybe also upload the original MS3 score?

**Comment by cbjeukendrup** [comment] 2022-11-05 18:33
Oh, now I can. What I did:
1. Export the given file to MusicXML, and open it in MS3
2. Generate parts in MS3
3. Save the score in MS3
4. Open the saved score in MS4beta1
5. Open parts in MS4beta1
-> the parts from MS3 are duplicated, but that's a separate issue
6. Save the score in MS4beta1
7. Open the score in MS4beta2
8. Open parts in MS4beta2 
-> the parts have been duplicated again, so now I have 3 copies of each part; two from MS4beta1, and one new generated by MS4beta2; but that is also a known issue because of the beta1/beta2 incompatibility
9. Two of the copies are empty; in one of them, make one of the instruments visible. This should reproduce the issue.

**Comment by cbjeukendrup** [comment] 2022-11-05 19:03
Also, when I open the MS3 score (that is, the one I generated by exporting MusicXML in MS4beta2 and importing it in MS3) directly in MS4beta2, then I have no issues:

MS3->MS4beta1->MS4beta2: problems
MS3->MS4beta1->MS4beta2->MS4beta2: problems fixed
MS3->MS4beta2: no problems

So this issue seems to be caused by the incompatibility between MS4beta1 and MS4beta2. Since this issue only involves scores from a pre-release version, we are probably not going to fix this.

**Comment by Tantacrul** [comment] 2022-11-21 16:33
With that in mind, @cbjeukendrup - I think we should close this issue since we won't be fixing compatibility issues between alpha and beta builds.

**Comment by Tantacrul** [comment] 2022-11-21 16:33
Also, great detective work @cbjeukendrup !

**Closed by Tantacrul** 2022-11-21 16:33 UTC
