### ISSUE TITLE
[MU4 Issue] Head and Beam in Properties have blank tab

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9254] opened 2021-09-23 16:27 UTC
**Describe the bug**
Head and Beam in Properties have blank tab

**To Reproduce**
1. Create a score
2. Add note 
3. Open Properties tab
4. Select Head or 

**Expected behavior**
Stem elements should be visible instead of blank tab but
for Head and Beam, Stem elements should be grayed out

**Desktop (please complete the following information):**
Windows 10 
MacOS

**Comment by DmitryArefiev** [comment] 2021-11-01 15:21
Tested the on latest master build on Win10, Mac11, LinuxMint 20 - CAN'T REPRODUCE Head and Beam blank tabs in Properties 

Closing

**Closed** 2021-11-01 15:22 UTC
Labels: P3
