### ISSUE TITLE
Missing characters with use of font "skia" on mac

### ISSUE THREAD

**Issue by risottodirk** [musescore/MuseScore#25231] opened 2024-10-19 17:35 UTC
### Issue type

Other type of issue

### Description with steps to reproduce

When using the font skia for title or instrument names the letters o, u, i, p, and j (only lower case) are replaced with apostrophe.
This doesn't happen with the older version 4.3.2. See attached screenshots.

### Supporting files, videos and screenshots

![musescore 4 3 2](https://github.com/user-attachments/assets/db51686e-3a2e-4bbc-ba0f-729ce25124eb)
![musescore 4 4 2](https://github.com/user-attachments/assets/2c0dfc2b-7b14-4ce4-a045-2087d15b3323)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

mac os Sonoma 14.7

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment] 2024-10-21 10:36
Original issue from the forum [here](https://musescore.org/en/node/370485).

**Comment by cbjeukendrup** [comment] 2024-10-22 12:08
I seem unable to reproduce this (on macOS 15). Does it happen in a specific score? Or could you try uploading any score where this happens?

**Comment by cbjeukendrup** [comment] 2024-10-22 12:10
In any case, you could try if this is still reproducible with the builds from https://github.com/musescore/MuseScore/pull/25016
(see [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) for how to download it)

**Comment by risottodirk** [comment] 2024-10-22 13:06
Hoi Caspar, thank you. I've just installed the latest "nightly" 
![Bildschirmfoto 2024-10-22 um 14 56 54](https://github.com/user-attachments/assets/1bfab123-f0d9-4ac6-b416-ab00f6895213)

Here is a test file
[test-skia.mscz.zip](https://github.com/user-attachments/files/17476554/test-skia.mscz.zip)

an a screen shot how it looks on my computer 
![Bildschirmfoto 2024-10-22 um 15 04 49](https://github.com/user-attachments/assets/cf9680cf-e116-45a3-a38d-044bb8a48d83)


The effect is still there. Attached is a zip file from a test score. It happens always, no matter if I start a new file or open an existing file from an older version of muse score

**Comment by cbjeukendrup** [comment] 2024-10-23 18:49
It's strange, but it really looks fine for me. So we must be using different versions of the Skia font. I'm using the one that comes built-in with macOS. Did you install it from any other source? 

If you open the Font Book app on your Mac (enter that name into Spotlight; the localised name of that app may be different, like "Lettertypecatalogus" in Dutch), and then search for Skia, you can Control-Click on its tile, and choose "Show in Finder". That should give you a Finder window, from where you can drag your Skia.ttf file to GitHub to upload it.

**Comment by risottodirk** [comment] 2024-10-23 19:57
do I need to do anything to close this issue?

**Comment by FrancRos31** [comment] 2024-10-23 20:53
You can do it yourself (click Close button next to Comment) or wait for the devs to do it.

**Comment by cbjeukendrup** [comment] 2024-10-23 21:07
Mystery solved! Glad it's working now.

(It looks like `dfont` is an older format. Are you by chance using an older Mac, or might it have been transferred from an old Mac to your current one?)

**Closed by cbjeukendrup** 2024-10-23 21:07 UTC
Labels: needs info, P3, UI, regression MS4, Qt-next

**Comment by risottodirk** [comment] 2024-10-23 21:13
my mac mini is from 2019. And yes, it might be a leftover from a former mac mini (2010) or even from a G5 (2003)
