### ISSUE TITLE
Improved design of party names

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20470] opened 2023-12-14 08:32 UTC
### Your idea

My idea is as follows. I have attached 2 screenshots. The first screenshot shows how you can currently specify the number of instruments for a single staff/part
![1](https://github.com/musescore/MuseScore/assets/134041121/ba69e645-b2ce-4dbe-983c-4a99f4d5e706)
![2](https://github.com/musescore/MuseScore/assets/134041121/5ec7db75-e980-4a82-8f1b-3981a73aeb6c)
. The second screenshot shows how I would like to see it in a different design. The bottom line is that the instrument numbers should be designed not along a horizontal line, but along a vertical one.
In order to implement this idea, you may need to ask the score editor for information about how many instruments are recorded on one staff. And the most important thing! If there is only one instrument (for example, Oboe 1), then by default the notes for this instrument should be written in the first voice. The notes for the second instrument (for example, Oboe 2), recorded on the same staff, must be written in a second voice. The same applies to the French Horn part (1-2, 3-4, 5-6, respectively). But if one instrument is indicated on the staff of the party (for example, Trumpet 3), then the notes for it should be written with 1 voice (not the third and not the second), since only one instrument is recorded on the note carrier

### Problem to be solved

This idea would help the reader/performer to better understand which staff the instruments with certain numbers are recorded on. That is, the instrument numbers (one or more) will be displayed opposite each staff

**Comment by cbjeukendrup** [comment] 2023-12-15 22:38
Isn't this a duplicate of #18775?

**Comment by Dima12357** [comment] 2023-12-15 23:07
> Isn't this a duplicate of #18775?

You could say that. It's just that here I added more information about the voice number and the methods of choosing it depending on the instrument number.

**Closed** 2023-12-16 06:32 UTC
Labels: feature request
