### ISSUE TITLE
import note velocity from MS version 3 to Version 4 does not work for relative velocities

### ISSUE THREAD

**Issue by mountbest** [musescore/MuseScore#17865] opened 2023-06-06 03:17 UTC
### Issue type

General playback bug

### Bug description

MS version 4 ignores relative (negative) note velocity values when MS3 score is opened in MS4.

MS4 only interprets POSITIVE values of note velocities.
I hesitate opening any of my MS3 scores in MS4 because correcting relative note velocities can be quite laborious.

MS4 should re-compute relative note velocity values from MS3 on import.

### Steps to reproduce

1. using MS4 - open file created with MS3 that contained relative (negative) note velocity values
2. Examine note velocity for these notes after opening the file.
3. Negative note velocity values are imported by MS4, but totally ignored during playback
4. It takes some experimenting to adjust MS3 relative note velocities to the ABSOLUTE scale used by MS4. No information is provided about comparing these scales. Are they linear? Logarithmic?
5. There should be a function to scan the score and re-compute note velocity values on import from MS3

### MuseScore Version

4.02 latest

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by MarcSabatella** [comment] 2023-06-22 12:52
As I understand it, this is a duplicate of https://github.com/musescore/MuseScore/issues/14768, which I agree would have been very nice to have done and can still be done for future updates if there are to be any before the even newer velocity systems is implemented.

**Closed** 2023-06-22 14:12 UTC
Labels: needs info, playback, regression_ms3
