### ISSUE TITLE
Ties spanning line breaks don't move to new staff on <ctrl-alt-down>

### ISSUE THREAD

**Issue by mmtrebuchet** [musescore/MuseScore#20794] opened 2024-01-01 22:44 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Minor bug, hopefully just an oversight that doesn't require rewriting the engraving system. I'm writing one voice on a grand staff because it has a very large range I'd like to have cross-staff beams when the notes change from the treble to bass clef, and I found that I can select notes on the treble staff and to move them to the bass. If I have a tied note that spans a line break, when I use to move it to the bass clef, the note heads move correctly, and most of the ties move correctly, but the first tie on the first measure of the second line stays on the upper clef. If I try to drag the incorrect tie down, the note heads scoot out of the way so it's impossible to get the tie in the right position.

In the attached minimal example, mark A shows the original notes on the treble clef, and mark B shows the effect of selecting those notes and pressing . Note the random tie in the first measure on the treble clef.

If I select the last note on the first line and press `t` to break the tie and then `t` again to recreate it, it recreates the tie on the wrong staff. If I write the notes on the lower staff in the first place, ties work correctly.

The demo is starting from the "grand staff" template. This also happens if I have an existing piece and add a new staff to an instrument and move the notes with there. This happens both on the automatic line breaks as well as if I add a manual system break from the Layout palette.

### Steps to reproduce

1. Open a grand staff template. 
2. On the treble clef, add the same note immediately before and after a line break.
3. Use the tie button to tie those notes together
4. Select those notes and press <ctrl-alt-down> to move them to the other staff.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/1676281/5af6e9aa-7f6b-480d-a3fd-89fc0f2ad90c)

### MuseScore Version

MuseScore 4.2.233521125, rev eb8d33c on Linux

### Regression

I don't know

### Operating system

Fedora 39, Linux 6.6.8-200.fc39.x86_64

### Additional context

[tieMessup.pdf](https://github.com/musescore/MuseScore/files/13806209/tieMessup.pdf)

**Comment by oktophonie** [comment] 2024-01-02 10:00
A duplicate of https://github.com/musescore/MuseScore/issues/20747 (essentially)

**Closed by oktophonie** 2024-01-02 10:00 UTC
Labels: engraving
