### ISSUE TITLE
[MU4 Issue] Synthesizers - Several synthesizer instruments default to use piano sound

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#22757] opened 2024-05-10 15:16 UTC
### Issue type

General playback bug

### Bug description

When the Choir Synthesizer is used to setup a new score, the sound default to piano.
Same is happening for:
Bowed Synthesizer
Halo Synthesizer
Metallic Synthesizer
New Age Synthesizer
Poly Synthesizer
Saw Synthesizer
Sine Synthesizer
Square Synthesizer
String Synthesizer
Sweep Synthesizer
Warm Synthesizer

In 4.2, the expected Space Voice from the MS Basic soundfont was used when Choir Synthesizer was selected.

### Steps to reproduce

Start a new score
Select the Choir Synthesizer instrument
Listen to the sound

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I did perform a Factory Reset, but that did not make any difference.

**Comment by MarcSabatella** [comment] 2024-05-10 15:49
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/22744

**Comment by henkdegroot** [comment] 2024-05-10 16:05
Looks like you are correct Marc. Will close this one.

**Closed** 2024-05-14 07:06 UTC
Labels: regression, playback

**Comment by GiacomoOakenstand** [comment] 2024-05-27 10:20
I would like to mention that the theremin in musescore...isn't playing a theremin. It's playing an ocarina instead.

**Comment by Jojo-Schmitz** [comment] 2024-05-27 10:52
Same in Mu3 BTW. I guess there is no Theremin sound defined in General MIDI and so Ocarina got picked as the closest match?

**Comment by GiacomoOakenstand** [comment] 2024-05-27 11:01
That might be why... Still I'm sure there are sound libraries out there that have a free version of the Theremin soundfont that could've been used. Ah well, at least we can do it ourselves...I hope.

**Comment by MarcSabatella** [comment] 2024-05-27 12:47
Yes, you can download and use any soundfont you like in order to get sounds for non-GM instruments.  If you need help with this, please the support forum on musescore.org for questions about how to use MuseScore.
