### ISSUE TITLE
Diatonic transposition is wrong for octave-transposing instruments (also causes wrong ornament intervals)

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18011] opened 2023-06-15 23:30 UTC
### Issue type

Other type of issue

### Bug description

Copying and pasting custom trill to contrabass instrument.  Only the "Auto (Diatonic)" trills do not copy over correct, should be an octave up.

### Steps to reproduce

1. Create a custom trill with an "auto" (diatonic) base.
2. Copy and paste into a Contrabass staff

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/213b3846-c746-4ef9-a085-77066b0c9d1d

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231660302, revision: github-musescore-musescore-7db8bc7

### Regression

Choose option...

### Operating system

OS: macOS 11.6

**Comment by mike-spa** [comment] 2023-06-19 17:17
https://github.com/musescore/MuseScore/assets/93707756/cbb7dcd3-e958-4660-8da5-70fb7ca9cdbc


Interestingly, this is not an ornament-related issue. It is a deeper bug of the diatonic transposition logic (which is also used by ornaments in "auto" mode). I'm gonna have to dig deeper tomorrow

**Comment by mike-spa** [comment] 2023-06-19 17:19
Also: the bug is present also when entering the trill directly on the contrabass staff, not just when copypasting, so I'm changing the title if that's ok

**Comment by mike-spa** [comment] 2023-06-20 08:21
@sammik it turns out that the cause of this issue (particularly the one I've shown in the last comment) is in [these lines of code](https://github.com/musescore/MuseScore/blob/master/src/engraving/libmscore/staff.cpp#L718-L721). Could you explain the context of why that was needed in the first place? In this case it is causing the contrabass to transpose down 2 octaves instead of 1

**Comment by mike-spa** [comment] 2023-06-20 16:06
Thanks so much!

**Comment by DmitryArefiev** [comment] 2023-06-21 12:36
Fixed in #18069

**Closed** 2023-06-21 14:51 UTC
Labels: P1
