### ISSUE TITLE
Method of gradually increasing tempo from one BPM to another

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23384] opened 2024-06-27 23:41 UTC
### Your idea

When editing a "gradual tempo change" playback properties, allow specifying a specific "end tempo" (in BPM), rather than just a percentage.

### Problem to be solved

Currently you can use the gradual tempo change playback "amount" field to specify an integer percentage that is supposed to define how much the tempo changes from the beginning of a "gradual tempo change" to the end.  However that often a) requires some easy-to-get-wrong calculations to work out what the percentage should be to ensure an expected tempo is reached by the end b) only allows integer percentages which aren't always enough and c) from the testing I did didn't reliably get you from tempo A to tempo B anyway (but close enough that it just requires explicitly specifying the tempo at some point after the tempo change spanner ends and it still sounds smooth).

### Additional context

If this could easily be done via a plug-in it might be OK too.  I believe such a plug-in may have existed for v3.6.

**Comment by oktophonie** [comment] 2024-06-28 06:58
Duplicate of https://github.com/musescore/MuseScore/issues/18359

**Closed by oktophonie** 2024-06-28 06:58 UTC
Labels: feature request
