### ISSUE TITLE
[MU4 Issue] Cursor does not align with links and hovers

### ISSUE THREAD

**Issue by AlexAndPedro** [musescore/MuseScore#11189] opened 2022-04-13 19:03 UTC
**Describe the bug**
After moving the software to another monitor, the cursor does not align with links and hovers. It can be corrected by dragging the top part of the software and drag to adjust the height of the software. This bug was produced with two monitors.

**To Reproduce**
1. Open Musescore.
2. Drag the software to another monitor.
3. Move the cursor to one of the buttons/links (say **Score**). The area the cursor hovers does not align to the highlight and the link.

**Expected behavior**
You can click the links in the expected position of the cursor.

**Screenshots**

https://user-images.githubusercontent.com/73212448/163251499-1c26a42e-ad8f-4a58-a448-b9f979b08a84.mp4

**Platform information**
 - OS: Windows 10

**Comment by VanSHOE** [comment] 2022-04-13 19:07
I think that this and https://github.com/musescore/MuseScore/issues/9968 should be combined

**Comment by Tantacrul** [comment] 2022-06-20 17:52
@AlexAndPedro - are you still encountering this?

**Comment by Tantacrul** [comment] 2022-06-20 17:53
Closing because (as @VanSHOE has pointed out) the issue is already covered here https://github.com/musescore/MuseScore/issues/9968

**Closed by Tantacrul** 2022-06-20 17:53 UTC
