### ISSUE TITLE
[MU4 Issue] No way to set the start hook, unlike what Simon said...

### ISSUE THREAD

**Issue by BetonBrut69** [musescore/MuseScore#15065] opened 2022-12-09 07:03 UTC
Not a bug, but unlike what Simon said in the last post's response,
I am not able to set a "beginning hook" to a plain, normal line.
as you can see the picture below, only "Ending hook" is available.

1. Go to 'Lines
2. Click on 'properties'
3. See there is no option for beginning hook

**Expected behavior**
I would expect this:
<img width="752" alt="Line" src="https://user-images.githubusercontent.com/105449568/206644107-5de24ce5-1c5d-4ec6-9b34-15781d5d6526.png">

but all I get is this
<img width="1021" alt="Screenshot 2022-12-09 at 3 52 46 PM" src="https://user-images.githubusercontent.com/105449568/206644462-0709ed6e-25de-4a5d-8260-7859efa8d84f.png">

**Platform information**
 - macOS (venture)

**Comment by BetonBrut69** [comment] 2022-12-09 07:09
In hindsight, I think that is not yet implemented, only planned....

**Comment by oktophonie** [comment] 2022-12-09 07:29
Correct, this is not yet implemented; https://github.com/musescore/MuseScore/issues/14209 is the task for it :)
Closing as duplicate of https://github.com/musescore/MuseScore/issues/13653

**Closed by oktophonie** 2022-12-09 07:29 UTC
