### ISSUE TITLE
[MU Hub] MuseSampler | Muse Hub was unable to find the required configuration

### ISSUE THREAD

**Issue by eg0n1984** [musescore/MuseScore#14323] opened 2022-11-05 11:39 UTC
**Describe the bug**
Muse Sampler is unable to be updated from Muse Hub
Muse Hub 0.9.9.512

**To Reproduce**
1. Change Muse Hub language to PT-PT
2. Start Muse Sampler update
3. See error

**Screenshots**
![Muse_odhLC53jOA](https://user-images.githubusercontent.com/28876087/200117801-ec787768-52ef-4b7b-bfbd-ba6988e42915.png)

**Platform information**
 - OS: 
Edição	Windows 10 Pro
Versão	21H2
Instalado em	‎19/‎06/‎2022
Compilação do SO	19044.2075
Experiência	Windows Feature Experience Pack 120.2212.4180.0

[user_settings.txt](https://github.com/musescore/MuseScore/files/9943663/user_settings.txt)
[client_log.txt](https://github.com/musescore/MuseScore/files/9943664/client_log.txt)
[service_log.txt](https://github.com/musescore/MuseScore/files/9943673/service_log.txt)

**Comment by cbjeukendrup** [comment] 2022-11-05 14:00
This looks a lot like a duplicate of #14317, so I'll close this one in favour of the other. See especially this comment: https://github.com/musescore/MuseScore/issues/14317#issuecomment-1304419737, which states that it should be fixed now.

**Closed by cbjeukendrup** 2022-11-05 14:00 UTC
