### ISSUE TITLE
Version 4.1 OSX crashes on attempt to add tuplet on staff with linked tab

### ISSUE THREAD

**Issue by chipshorter** [musescore/MuseScore#18637] opened 2023-07-16 11:08 UTC
### Issue type

Crash or freeze

### Bug description

Any attempt to add a tuplet either via keyboard short cut (cmd 4) or via menu Add > Tuplets completely crashes MuseScore 4.1 on OSX if there is a linked

### Steps to reproduce

1. Create new score - Acoustic Guitar
2. Create Linked stave type Tab 6-str. common
3. Add > Tuplet > Triplet (crashes)

### MuseScore Version

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921401, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

MacOS Monterey Version 12.6.7

### Additional context

<img width="588" alt="Screenshot 2023-07-16 at 10 32 12" src="https://github.com/musescore/MuseScore/assets/13019354/bc6e949b-838b-4ce9-a1a3-0042486f87ad">

**Comment by RomanPudashkin** [comment] 2023-07-16 17:01
It's a duplicate of https://github.com/musescore/MuseScore/issues/18595. This crash will be fixed in 4.1.1 very soon

**Closed by RomanPudashkin** 2023-07-16 17:01 UTC
Labels: crash
