### ISSUE TITLE
[MU4 Issue] Horizontal frame - Properties - "Display key, brackets and braces" should also mention "clef"

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#15684] opened 2023-01-02 11:32 UTC
**Describe the bug**
In properties of Horizontal panel, there is tick named "**Display key, brackets and braces**". 
Should be "**Display clef, key, brackets and braces**".

**To Reproduce**
1. Insert horizontal panel to score
2. Click Properties panel

**Expected behavior**
Also "clef" should be mentioned

**Screenshots**

https://user-images.githubusercontent.com/1646034/210225712-6c5ea744-6c3e-4207-88ec-51ec9f016da5.mp4

**Comment by cbjeukendrup** [comment] 2023-01-02 12:05
Maybe we should make clear that this checkbox is about the next measure: 
**Display clef, key and brackets before the next measure**
(and I think "brackets" can be used as a general term to include "braces", so we can drop "braces".)

**Comment by sammik** [comment] 2023-01-02 16:11
May be "in the next measure" instead of "before the next measure"?
Or change it to oposite "Hide clef, key and brackets"?

**Comment by maddy020** [comment] 2023-01-03 05:03
Hey @sammik 
I would love to work on this issue
Please assign it to me

**Comment by sammik** [comment] 2023-01-03 07:46
@cbjeukendrup, please ^^^

**Comment by cbjeukendrup** [comment] 2023-01-03 13:20
Reg. the conclusion for what the text should be: I would propose that we go for: 
**Display clef, key and brackets in the next measure**

Everyone happy with that?

**Comment by octopols** [comment] 2023-01-21 21:57
@cbjeukendrup if the issue is not fixed can you assign it to me?

**Comment by octopols** [comment] 2023-01-22 14:51
For translations should I use google translate or should I just mark them unfinished for now?

**Comment by cbjeukendrup** [comment] 2023-01-22 15:22
You don't need to worry about translations at all :)

You only need to make the string translatable by writing it like `qsTrc("inspector", "<the string goes here>")`. Then, at some point, we will run a program that extracts all translatable strings from the source code, and sends them to a translation platform called Transifex. There, they will be translated by volunteering MuseScore users from all countries. At the moment of the release, we download the translations from Transifex, and package them with the app.

**Comment by octopols** [comment] 2023-01-22 15:40
> You don't need to worry about translations at all :)
> 
> You only need to make the string translatable by writing it like `qsTrc("inspector", "<the string goes here>")`. Then, at some point, we (the "in-house" team) will run a program that extracts all translatable strings from the source code, and sends them to a translation platform called Transifex. There, they will be translated by volunteering MuseScore users from all countries. At the moment of the release, we download the translations from Transifex, and package them with the app.

So, I only need to make changes to the HorizontalFrameSettings.qml file and leave the language files (.ts)  the way they are right?

**Comment by cbjeukendrup** [comment] 2023-01-22 15:41
Yes, that's right!

**Comment by Jojo-Schmitz** [comment] 2023-01-22 16:48
Hmm, If we'd use "Display brackets, clef and key in the next measure" the order in the text matches the order of the elements in the score?

**Comment by Jojo-Schmitz** [comment] 2023-01-22 16:55
And isn't it `key signature` rather than just `key`

**Comment by octopols** [comment] 2023-01-22 17:24
> And isn't it `key signature` rather than just `key? Already led me to a wrong German translation (Taste <-> key <-> Schlüssel <-> clef, but key signature <-> Tonart)

I don't know a lot about music theory, whatever fits right I'll update the string to that.

**Comment by cbjeukendrup** [comment] 2023-01-22 17:56
Yes, I agree with @Jojo-Schmitz. Also, probably clef**s** (plural) is more correct. So that would give us: _Display brackets, clefs and key signature in the next measure_

**Comment by Jojo-Schmitz** [comment] 2023-01-22 18:04
It is either only one clef or key signatures

**Comment by Jojo-Schmitz** [comment] 2023-01-22 18:06
Ah, no. In case of more than one staff it'd be multiple clefs

Multiple key signatures are also possible in case of local ones

**Comment by cbjeukendrup** [comment] 2023-01-22 18:09
Not sure if I agree... I'm inclined to regard the key signature as one object for all staves together, while clefs are clearly distinct elements on each staff. @oktophonie what's your opinion?

**Comment by Jojo-Schmitz** [comment] 2023-01-22 18:10
Even with local keysigs?

**Comment by Jojo-Schmitz** [comment] 2023-01-22 18:11
What about time signatures, shouldn't those be shown (and them get mentioned) too?

**Comment by Jojo-Schmitz** [comment] 2023-01-22 18:17
To shorten the string somewhat, we could pprobably drop the 'the'

**Comment by oktophonie** [comment] 2023-01-22 18:59
> Not sure if I agree... I'm inclined to regard the key signature as one object for all staves together, while clefs are clearly distinct elements on each staff. @oktophonie what's your opinion?

Sounds best to me to have them all plural, but it's not a big deal.

**Comment by octopols** [comment] 2023-01-22 19:52
> Yes, I agree with @Jojo-Schmitz. Also, probably clef**s** (plural) is more correct. So that would give us: _Display brackets, clefs and key signature in the next measure_

Should I update the string with this and make it 'key signatures' instead?

**Comment by cbjeukendrup** [comment] 2023-01-22 19:59
Yes, let's go for that!

**Comment by octopols** [comment] 2023-01-22 20:17
Changed the string
https://github.com/musescore/MuseScore/pull/16008/commits/30a0c43b8c447238b2f25ba85c955f670dd5f4f4

**Closed** 2023-01-22 21:23 UTC
Labels: strings, good first issue
