### ISSUE TITLE
[MU4 Issue] Insert Horizontal Frame option is missing in Vertical Frame Add menu 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12930] opened 2022-08-19 11:06 UTC
**Describe the bug**
This is the part from #11982 which was not fixed because needs some clarification 

> Right-clicking on a horizontal or vertical frame in MuseScore 3 revealed a context menu with options to add text and images. **There was also an option to add horizontal frames inside vertical frames to create a table structure.** 

![173132288-514a8cca-4098-42a8-8f7f-0318c356c62d](https://user-images.githubusercontent.com/90187801/185605813-6ce2aa6e-3d57-411c-8570-209e1120e1fd.png)

**Expected behavior**

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment] 2022-08-19 11:41
@shoogle Together with @RomanPudashkin we found that the feature requires some additional rework (how it behaves in MU3)

When adding horizontal frame using vertical frame submenu, it creates a frame with the same borders as initial frame and **user don't see if he creates something or not** (except a handle)

https://user-images.githubusercontent.com/90187801/185608646-d79220f1-0133-4118-b3bb-d33d605991f9.mp4

1. Should we change the borders of the second added frame? (the right border)

Another inconsistency behavior: When selecting a vertical frame and adding a horizontal frame **but from Add>Frame top menu**, it creates horizontal frame **NOT inside selected vertical frame**


https://user-images.githubusercontent.com/90187801/185609432-cd67dd9f-658e-41b2-8e66-b542005427ec.mp4

2. Maybe change a name for the command in vertical frame submenu ? or Do the same thing regardless of from what menu the command is triggered?

**Comment by MarcSabatella** [comment] 2022-08-19 12:50
Definitely the ability to create table structure is important to many users, but horizontal frames are not really the best way to do that anyhow.  It's usually simpler to just add multiple text elements to the frame and position them as desired.  And that's what I always recommend.  So personally, I'm not so worried about any of this.

Anyhow, the fact that the newly inserted frame is hard to see is indeed slightly annoying, but the people who use this feature at all are used to it.  Since the main use for the frame is to create two columns of text, probably the sensible default would be to have it half the width of the vertical frame.

Also, I *think* it should be expected that Add / Frame from the top menu would not insert within the selected frame - after all,  the other entries in that menu insert before or after, not within.

**Comment by DmitryArefiev** [comment] 2022-08-19 13:55
@MarcSabatella Good. Thanks for additional details!

**Comment by shoogle** [comment] 2022-08-22 09:30
I agree with @MarcSabatella. MuseScore 3 behaviour is a bit strange regarding frames within frames. I wouldn't be sorry to see that feature disappear in MuseScore 4. It's really a question for @Tantacrul and @bkunda about how they see this feature working in the longer term.

If we want to drop it then now is the right time to do so, but we would need a way to import those scores from MuseScore 3, probably by converting the inner frame text to separate text elements in the outer frame. The feature is only used very rarely though so we could wait until 4.x to implement the upgrade path.

**Comment by Tantacrul** [comment] 2022-10-08 17:44
> Definitely the ability to create table structure is important to many users,

I'm going to put forward the opinion that only a tiny fraction (probably only our community developers) know this function exists and that we should remove it entirely. We should establish sensible options in future. Right clicking on frames to add more frames is unforgivable UX.

**Comment by shoogle** [comment] 2022-10-08 18:27
Sounds like we can close this issue then, or rename it to cover the future task of coming up with a replacement for this functionality.

**Closed** 2022-10-08 18:48 UTC
Labels: P2

**Comment by Jojo-Schmitz** [comment] 2023-04-07 19:57
It is a serious regression that more than just one perseon knows about and uses

See also https://musescore.org/en/node/339977

**Comment by shoogle** [comment] 2023-04-07 20:21
@Jojo-Schmitz, this [comment](https://github.com/musescore/MuseScore/issues/12930#issuecomment-1220639317) from @MarcSabatella still applies:

> Definitely the ability to create table structure is important to many users, but horizontal frames are not really the best way to do that anyhow. It's usually simpler to just add multiple text elements to the frame and position them as desired.

The multiple elements method was powerful enough to create the table structures at the beginning of [this score](https://musescore.com/openscore/scores/5673458):

![image](https://user-images.githubusercontent.com/11011881/230673018-00269021-3540-4a81-9afa-edc21b4bcf71.png)

It would be difficult to achieve something like this using the nested frames feature as it was implemented in MuseScore 3.

**Comment by Jojo-Schmitz** [comment] 2023-04-08 11:12
It still is an issue, at least with backwards compatibility there's no way to manipulate Mu3 frames in frames (delete, move, resize, add text or image) in Mu4. Modifing and deleting existing text is about the only thing that does work. And deleting the vertical frame to delete the contained horizontal one...

**Comment by MarcSabatella** [comment] 2023-04-08 14:58
I'd recommend simply fixing this on import.  Elements within nested frames should be reparented to the main frame, and their offset recalculated as the original element offset plus the frame offset (or the corresponding calculation for center or right aligned text).

**Comment by MarcSabatella** [comment] 2023-04-08 17:28
FWIW, a little experimenting shows it's actually still possible to import and edit MU3 scores that use this technique.  You can't directly click to select the inner frame, but you can navigate to it via Alt+Left/Right, or you can click to select if you first send the vertical frame to the back of the stacking order using Properties.  And once you do that it seems the same capabilities exist as before.  At least, I haven't found any limitations yet.

So it might not even be necessary to do the conversion on import.  Maybe we could just adjust the stacking order to make the inner frames easier to select, or special case the select behavior (as was gone for images within frames).  And hopefully also bring back Ctrl+click for selecting elements stacked under others as per https://github.com/musescore/MuseScore/issues/10225

**Comment by Jojo-Schmitz** [comment] 2023-04-08 18:38
Oh, interesting indeed. So a bad UX got replaced by a worse UX ;-)
