### ISSUE TITLE
[MU4 Issue] Falls and Doits disappear in part scores after closing and reopening score

### ISSUE THREAD

**Issue by bhymusic** [musescore/MuseScore#15888] opened 2023-01-15 10:19 UTC
**To Reproduce**
1. Create a score with some notes with Falls or Doits
2. Open the parts - everything is ok
3. Save, close, and reopen the score
4. Open the parts again
5. Falls and Doits disappear even when deleted and recreated
6. The playback is ok but you can not see the Falls and Doits.

**Expected behavior**
should be displayed in part scores

**Platform information**
testet on windows 10 and linux zorin (appimage)

**Comment by oktophonie** [comment] 2023-02-21 12:22
Closing as duplicate of https://github.com/musescore/MuseScore/issues/15888

**Closed by oktophonie** 2023-02-21 12:22 UTC

**Comment by RobFog** [comment] 2023-02-21 12:41
This is a duplicate of which issue?
