### ISSUE TITLE
[MU4 Task] Change templates to make guitar clef as Treble Clef (but sounded an octave down) as opposed to Treble Clef 8va bassa

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16521] opened 2023-02-24 02:00 UTC
It is objectively incorrect to write Treble Clef 8va bassa for Guitars as opposed to just Treble Clef but sounded down an octave. This is standard convention everywhere, not only in a majority of published music, but also in other notation softwares. Think about how Acoustic Bass instruments are written in Bass Clef but sounded down an octave as opposed to written in Bass Clef 8va bassa. It's the exact same principle, so it's simply inconsistent and has been a problem since the dawn of MuseScore.

**Comment by BoBogus** [comment] 2023-02-24 06:56
It's easy enough to make that change manually when you add it.  Just drag a treble clef symbol on there from the palette, then go to the Staff/Part properties and tell it to transpose down an octave.

**Comment by oktophonie** [comment] 2023-02-24 08:36
Duplicate of https://github.com/musescore/MuseScore/issues/15556, where it was also expressed with less self-righteous indignation, so I'll close this one.

**Closed by oktophonie** 2023-02-24 08:36 UTC
Labels: duplicate
