### ISSUE TITLE
[MU4 Issue] Middle Click + Drag moves note even if mouse isn't over

### ISSUE THREAD

**Issue by HarryAllen1** [musescore/MuseScore#12589] opened 2022-07-29 06:44 UTC
**Describe the bug**
When a note is selected and middle click is dragged, even if the mouse isn't over the note/rest, it will drag it.

**To Reproduce**
1. Create a new score
2. Insert a new note
3. Select the note
4. Middle click and drag
5. See error

**Expected behavior**
The page moves

**Platform information**
 - OS: Windows 11

**Additional context**
Once, when middle clicking and dragging with a note selected, MuseScore crashed.

**Comment by cbjeukendrup** [comment] 2022-07-29 12:01
Related to (but not really a duplicate of) #11656. "Greatest common divisor" of both issues is that middle mouse button should always only pan the canvas, and never touch any score elements.

**Comment by DmitryArefiev** [comment] 2022-12-12 09:55
Fixed in #15037

**Closed** 2022-12-12 10:09 UTC

**Comment by bkunda** [comment] 2023-03-06 10:45
🟢Re-tested in 4.0.2. on Windows. Remains FIXED.
