### ISSUE TITLE
Score crashes when opening the 'style' page

### ISSUE THREAD

**Issue by lee039784** [musescore/MuseScore#16489] opened 2023-02-22 16:16 UTC
[Symphony No. 1 in Eb Major.zip](https://github.com/musescore/MuseScore/files/10806013/Symphony.No.1.in.Eb.Major.zip)

**Describe the bug**
When going to format -> style, the score crashes before it loads. 

**To Reproduce**
1. Open the score
2. Go to 'Format'
3. Click on 'Style'

**Expected behavior**
MS4 should open the 'style' page so I can edit individual elements of the score.

**Screenshots**
![image](https://user-images.githubusercontent.com/103335609/220687115-1b3131d7-d742-4f92-af56-00a8c4eae442.png)

**Platform information**
 - OS: Windows

**Comment by DaddyLudwig** [comment] 2023-02-22 16:19
Yeah, I'm wondering that too. Cause for me, it just takes a while to open, but the score doesn't crash.

**Comment by oMrSmith** [comment] 2023-02-22 16:22
On Windows 10, I can't reproduce this either. I'm just getting a small delay.

**Comment by lee039784** [comment] 2023-02-22 16:23
@DaddyLudwig How long did it take for you to open?

**Comment by lee039784** [comment] 2023-02-22 16:27
I don't understand why it takes so long to open.

**Comment by DaddyLudwig** [comment] 2023-02-22 16:29
@lee039784 About 10 seconds on a simple piano score and about 21 seconds on my largest orchestral score so far(that being a transcription of Wellington's Victory at 32 staves)

**Comment by oktophonie** [comment] 2023-02-22 16:30
Nobody understands properly yet, that's why it's an issue :)
So, is it actually crashing for you, or is it just taking a very long time to open?

**Comment by lee039784** [comment] 2023-02-22 16:38
Ah, it has opened now. I think I was clicking on the score and that was what caused the crash. Any reason why it takes so long?

**Comment by oktophonie** [comment] 2023-02-22 16:40
See the discussion on https://github.com/musescore/MuseScore/issues/13193. I am closing this as a duplicate.

**Closed by oktophonie** 2023-02-22 16:40 UTC
Labels: duplicate
