### ISSUE TITLE
Key signature changes are not updated on next pages.

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#18490] opened 2023-07-09 12:02 UTC
### Issue type

Engraving bug

### Bug description

For example, a score that starts in D Major will switch to C Major in the next measures/pages. If I select C Major, A Minor button from the palette and put it in the **second** measure of the **second** page, 2 sharps still appear on the next pages. This issue only happens on C Major, A Minor button. 
As I understand it, this only happens with multi-instrument scores, and it happens after page two.
I made a video so it can be better understood from it.

### Steps to reproduce

1. New Score / Create From Template / Orchestral / Clasiccal Orchestra / Next
2. Key Signature / D Major / Done
3. Palettes / Key Signature / C Major, A Minor place in the **second** measure of the **second** page
4. still looks sharp in front of the next page/pages

### Screenshots/Screen recordings

https://youtu.be/7KWrsRJPBTc

### MuseScore Version

MuseScore 4.1 RC

### Regression

I don't know

### Operating system

Windows 10, Linux Mint 21.1

**Comment by mercuree** [comment] 2023-07-09 12:30
I can confirm this. And also something is wrong with undo behaviour 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231890909, revision: github-musescore-musescore-5057202

https://github.com/musescore/MuseScore/assets/919446/a7aadf91-50b1-4354-aaf8-2c05cfbdbd39

**Comment by oktophonie** [comment] 2023-07-10 07:17
This appears to also be fixed by #18500.
In the 4.1 RC the problem exists as described, though it seems that it corrects itself as soon as a note is added after the C major key signature change.

**Comment by sammik** [comment] 2023-07-10 08:10
@oktophonie I dont think, this "next page ks" issue is related #18500 

I tried latest master (without #18500), and it works also there.

But strenge ks after undo seems to be fixed by #18500.
I say this, just to know, that adding only #18500 into 4.1 potencialy wouldnt fix major issue "next page".

**Comment by DmitryArefiev** [comment] 2023-07-10 09:39
> I can confirm this. And also something is wrong with undo behaviour OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231890909, revision: github-musescore-musescore-5057202
> undo_key_bug.mp4

That's covered in this huge bug #17718

**Comment by DmitryArefiev** [comment] 2023-07-10 09:54
> @oktophonie I dont think, this "next page ks" issue is related https://github.com/musescore/MuseScore/pull/18500
> 
> I tried latest master (without https://github.com/musescore/MuseScore/pull/18500), and it works also there.

I can confirm. The "next page ks" issut is **fixed in latest nightly master (4.2)** and **still occurs in latest 4.1 nightly build**



> But strange ks after undo seems to be fixed by #18500.

Nope, unfortunately **still happens** in #18500 builds too

**Comment by oktophonie** [comment] 2023-07-10 14:12
Would love to find what's fixed this in master and cherry-pick for 4.1.1 then!

**Comment by RomanPudashkin** [comment] 2023-07-19 11:36
fixed in https://github.com/musescore/MuseScore/pull/18697

**Closed** 2023-07-19 11:36 UTC
Labels: P1, engraving
