### ISSUE TITLE
Menu appears far away from menu bar (AppImage / Fedora 38 / Wayland)

### ISSUE THREAD

**Issue by edbaskerville** [musescore/MuseScore#19151] opened 2023-08-23 18:33 UTC
### Issue type

UI bug

### Bug description

I downloaded the MuseScore 4.1.1.232071203 AppImage, did an AppImage install, opened it up, and clicked the File menu.

The menu appeared far away from the menu bar, in the middle of the window—see screenshot.

I'm running Fedora 38 with Wayland on a Framework laptop (Intel 12th gen).

### Steps to reproduce

1. Install MuseScore AppImage on Fedora 38 
2. Open MuseScore
3. Click the File menu

expected: the menu appears in the usual place, right below the menu bar item in question

actual: the menu appears far away, in the middle of the window

### Screenshots/Screen recordings

![Screenshot_20230823_112454](https://github.com/musescore/MuseScore/assets/2105312/ffefa069-b653-4974-9ec3-8cda1d9a156d)

### MuseScore Version

4.1.1.232071203

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Fedora 38

### Additional context

(see screenshot)

**Comment by cbjeukendrup** [comment] 2023-08-23 18:53
This seems a duplicate of #15285. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-08-23 18:53 UTC
Labels: UI, regression
