### ISSUE TITLE
[MU4 Issue] Selecting multiple Voltas with CTRL Click will delete nominal Volta numbers

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13194] opened 2022-09-06 10:44 UTC
https://user-images.githubusercontent.com/78870770/188615434-f3617e58-80e1-4956-bb07-05afb653773c.mp4

**Comment by oMrSmith** [comment] 2022-09-06 10:47
(Doesn't happen with MU3)

**Comment by rgreen5** [comment] 2022-10-06 11:30
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3194503368, revision: github-musescore-musescore-46fece3

Confirmed. Open the attached score. Click on volta 1, then volta 2. The volta numbers disappear.
[volta_issue.zip](https://github.com/musescore/MuseScore/files/9724355/volta_issue.zip)

**Comment by Tantacrul** [comment] 2022-12-06 12:46
Closing as a duplicate: https://github.com/musescore/MuseScore/issues/14968#issuecomment-1339230399

(Since we've already triaged that issue and understood the problem better in the comments there)

Thanks very much!

**Closed by Tantacrul** 2022-12-06 12:46 UTC
