### ISSUE TITLE
Audio panning not taken into account when using reverb

### ISSUE THREAD

**Issue by spoopw** [musescore/MuseScore#25523] opened 2024-11-15 00:56 UTC
### Issue type

General playback bug

### Description with steps to reproduce

Kind of hard to explain.

When using the mixer to pan and reverb an instrument, the reverb seems to "reverberate" in both ears, regardless of the panning settings. 

![image](https://github.com/user-attachments/assets/a35a6e63-d04b-4d95-a941-3499072128a8)

For instance: in this screenshot, the piano is panned 100% to the right. Reverb is at max. In the instrument, the sound is properly all the way to the right. However, you can see in the master how the sound is coming out of the left as well as the right. 

To me, it makes sense that this behavior is not how it should be. I believe the reverb should also be panned in the same way as the instrument. I may be wrong tho maybe this is just how reverb is always done 😑

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a8a2fc49-42b4-453b-b5f4-a617086bfb52

### What is the latest version of MuseScore Studio where this issue is present?

Version 4.4.3.242971445

### Regression

No.

### Operating system

Windows 10

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment] 2024-11-15 15:20
This is by design, reverb is managed in the aux channel.  

![Screenshot 2024-11-15 100320](https://github.com/user-attachments/assets/2cc56aaf-95ad-4822-ae84-3e989b40ada2)

**Comment by zacjansheski** [comment] 2024-11-15 15:22
Closing as by design,

**Closed by zacjansheski** 2024-11-15 15:22 UTC
Labels: needs review, playback
