### ISSUE TITLE
[MU4 Issue] Crash on creating new score after closing previously created new score

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10465] opened 2022-02-06 10:25 UTC
**Describe the bug**
Right after you create a new score, close it. Then open the create new score dialog. It will crash after a few seconds.

**To Reproduce**
1. Create a new score
2. Immediately close the issue preferably by the Ctrl + W shortcut
3. Create a new score quickly preferably by the Ctrl + N shortcut
4. You don't need to click anything else. Just wait for a couple of seconds.

**Expected behavior**
MuseScore should not crash

**Screenshots**

https://user-images.githubusercontent.com/88136054/152676590-774e075e-3c65-435b-9404-104ebd3c0960.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
You need to be quick
Also, I'm beginning to suspect that you have to select a large amount of instruments

**Comment by rzvxa** [comment] 2022-02-06 18:16
@HemantAntony Hey there, I'm trying to fix this issue but sadly i can't reproduce it, is it possible that this crash happening on your system because of some configuration error or maybe it's a windows 11 thing? it would be great if u have windows 10 on hand and can check if you can reproduce it there.
also it would be awesome  if you could share logs with us

**Comment by HemantAntony** [comment] 2022-02-07 01:40
Hello, thank you for attempting this issue. Like I said you have to be really quick. The time between creating the second score and first score should be around 1 second (That's how I do it). Use shortcuts. This is a portion of the log. Tell me if you want the entire thing:
![image](https://user-images.githubusercontent.com/88136054/152711867-745d2f3c-fdde-4a8c-8aa0-b5c8d3dcd66c.png)
I do not have Windows 10. I suspect the reason behind this is the loading of instruments of the previous score as you can see the log. Again, be as fast as you can (to be safe)

**Comment by rzvxa** [comment] 2022-02-07 11:43
@HemantAntony 
I'm not sure if it's specifically caused by doing it too fast, I've tried doing what you did and still no chance with reproducing it.
First i did it manually like you did(using shortcuts)

https://user-images.githubusercontent.com/3788964/152780510-7c3c07b4-6675-49de-a153-c6e63170533c.mp4

But i thought maybe I'm doing it too slow so i also did it via a macro recorder

https://user-images.githubusercontent.com/3788964/152780740-4cc61362-c3a4-4cf4-84c7-d71e60a593f6.mp4

It still can be a problem with speed or even trade racing but my system state is not same as yours so it does not happen. We have to trace it to find the root of the problem, it would be nice if you send me the full log of this run, We have a time zone difference so it's better if you just send it even if it's unnecessary so in case that it's needed we don't wait a full day for other person to get online.
It can also be helpful but not necessary to give us full information of your system, like how much ram you have, the compiler that you use and the build chain of yours(For example version of CMake, Qt, MinGw, ect).
I will try to check the codes in section that caused the error for any hint of unexpected behavior or bugs.

**Comment by HemantAntony** [comment] 2022-02-07 14:18
Hey, I was busy. I have attached the log.
![#10465 2](https://user-images.githubusercontent.com/88136054/152804836-e3cf8566-531f-4355-a5cc-5ef0f906aad6.jpg)
 
![#10465 3](https://user-images.githubusercontent.com/88136054/152804848-b4666c7b-ec2e-4682-8901-e85c3b820b79.jpg)

![#10465 4](https://user-images.githubusercontent.com/88136054/152804853-b0b954a6-e89f-45ed-abb9-1845865cf16c.jpg)

I used MSVC with Qt. Qt 5.15.2, CMake 3.21.3
[Log.txt](https://github.com/musescore/MuseScore/files/8015920/Log.txt)

**Comment by Jojo-Schmitz** [comment] 2022-02-07 14:22
If you're in MSVC, can't you run it in debug and get a stack trace? And from there reproduce where it goes wrong?

**Comment by HemantAntony** [comment] 2022-02-07 14:36
I'm a bit new at this. I thought stack trace meant the log, which I just learned isn't. But what @cbjeukendrup said makes sense. I saw in the application log that the instruments were just being loaded. I suspected it was probably this

**Comment by HemantAntony** [comment] 2022-02-07 14:43
Me too under debug. But, if that's true, then ironically I seem to have found another crash

**Comment by rzvxa** [comment] 2022-02-07 19:49
@HemantAntony I can reproduce it under debug, turn out my playback wasn't working right(it was searching for it's sounds in wrong directory). so now that i sorted that out i can consistently reproduce it.

@vpereverzev is it possible that you assign this task to me? I'm looking forward to join the core team for building mscore4, I'm already working on it and making progress.

**Comment by rzvxa** [comment] 2022-02-11 14:27
@vpereverzev  I'm working on it, give me a few days, There are 5 dangling shared_ptr s of `MasterNotation ` class so it's not getting destructed (and therefore Those events are getting invoked after `NotationProject` is destructed).
I'm new to this project had to follow every symbol to get familiar with the structure of the project and with little time i had in past couple of day i only found one of those dangling shared_ptr so there is 4 leaks to find, I can work on it at nights after my day job, so i would appreciate it if you guys can assign it to me and let me find others and make a PR. Friday and Saturday are days I'm off work so i can put more time into it.

**Comment by RomanPudashkin** [comment] 2022-02-11 14:41
@rzvxa I strongly discourage you from fixing this crash. The audio system (including MasterNotationMidiData, which causes this crash) will be significantly redesigned soon

**Comment by rzvxa** [comment] 2022-02-11 14:56
@RomanPudashkin Thanks for quick reply, what will happen to `IMasterNotation `class itself? because it may leaking in other places too, i suspect there is one leak in `NotationSwitchListModel::listenNotationSavingStatus` function where it passes `MasterNotation` shared_ptr (inside a lambda capture) to `MasterNotation::needSave()` causing a cycling shared_ptr which can be fixed with capturing a weak_ptr instead.
If it's getting refactored completely then i should pick some other issues to work on.

**Comment by RomanPudashkin** [comment] 2022-02-11 15:04
@rzvxa nothing will happen to this class :) If you find any memory leaks related to it, you can try to fix them

**Comment by DmitryArefiev** [comment] 2022-03-16 11:13
Tested  in latest master build (Win10, Mac12, LinuxMint 20.2) - CAN'T REPRODUCE NOW

Closing

**Closed by DmitryArefiev** 2022-03-16 11:13 UTC
Labels: P0
