### ISSUE TITLE
Incorrect auto-placement of measure numbers

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20471] opened 2023-12-14 09:03 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The numbers of the measure in this case are located above the staff. But these numbers are at the same time located above the articulation! And they completely merge with the lines! In this case, the measure numbers are centered. And they should automatically be placed strictly above all notes, lines, articulations, etc. It should not be such that the articulation is placed above the measure number, as shown in the screenshot

### Steps to reproduce

1. In the style of the score, I number each measure and align the numbering in the center
2. I enter notes, add articulation and lines

### Screenshots/Screen recordings

![Снимок экрана (64)](https://github.com/musescore/MuseScore/assets/134041121/1eb2793f-f5cb-4c97-b134-2c4e4fa55a23)
![Снимок экрана (65)](https://github.com/musescore/MuseScore/assets/134041121/d24c986c-0527-4d1e-94ae-6cf2c4fb1fb4)
![Снимок экрана (67)](https://github.com/musescore/MuseScore/assets/134041121/e40b1562-6bd2-46f7-ba7c-ae38c4f0963e)
![Снимок экрана (68)](https://github.com/musescore/MuseScore/assets/134041121/80e8a4ed-6c8a-478c-9d8e-84d56d513f65)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-12-14 09:32
Duplicate of https://github.com/musescore/MuseScore/issues/12955 and https://github.com/musescore/MuseScore/issues/20009

**Closed by oktophonie** 2023-12-14 09:32 UTC
Labels: engraving
