### ISSUE TITLE
Looping bounds ignored if you click a meausre after defining looping region

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14917] opened 2022-12-03 16:01 UTC
**Describe the bug**
After defining a looping region, if you change the selection afterward the looping boundary is ignored.

**To Reproduce**
Open a score with multiple measures.
Select several contiguous measures
Click the loop playback button in the toolbar to define a looping region.
Press play.  The playback will correctly loop within the region you have defined.
Click another measure while playback is engaged.  Now the playhead jumps to the selected measure and ignores the looping boundaries.  Even pressing stop and starting play again does not return you to the previously defined looping area.

**Expected behavior**
When loop is enabled, playback should be restricted to the looping region.

**Platform information**
Windows 10

**Additional context**
This also happens if you select a different measure when playback is not engaged.

**Comment by cbjeukendrup** [comment] 2024-08-19 15:07
This seems a duplicate of https://github.com/musescore/MuseScore/issues/12875. I have copied the relevant information from this issue to that one.

**Closed by cbjeukendrup** 2024-08-19 15:07 UTC
Labels: P2
