### ISSUE TITLE
Adding a tie to an already tied chord adds unwanted notes to the existing chords.

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#21830] opened 2024-03-05 16:22 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

If you have two chords tied together adding a further tie adds unwanted notes to the existing chords.

Note that this only occurs when trying to add to an already tied chord (with more than one note).  An already tied single note is not affected unless already tied to a chord.

### Steps to reproduce

In note entry mode, 4/4 time signature.
1. enter half note C
2. Press T to create a tie to another C
3. Press Shift + C to add an octave higher C to the second note
4. Press T to create a tie to another C octave cord in the next measure,
5. Note that an octave C has been added to the first chord and is tied to a duplicated C in the second chord.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/60138048/f88e3445-6a8e-49c4-8731-9f7d3007db6b

### MuseScore Version

 MuseScore version (64-bit): 4.2.1-240230937, revision: d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

May be related to #17579 which is reported as fixed in V 4.1

**Comment by mathesoncalum** [comment] 2024-03-05 16:29
Dupe of #21133? (@oktophonie)

**Closed** 2024-03-05 17:00 UTC
Labels: duplicate, engraving, regression_ms3

**Comment by SteveBlower** [comment] 2024-03-05 17:15
Dupe? Yes!
Missed that one!
