### ISSUE TITLE
Remember selected pane in Style dialog

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#20017] opened 2023-11-13 18:00 UTC
### Your idea

When closing and re-opening the Style dialog (Format > Style...), often one is making changes to related sets of properties, so the dialog should remember which pane was previously selected and open with that still selected for the duration of the user's session (i.e., on application restart, it opens at Score again).

### Problem to be solved

At present, I find myself often going back to tweak the same properties after a bit of editing of the score, and it's tedious to keep clicking on an entry in the list on the left to make them visible again.

**Comment by MarcSabatella** [comment] 2023-11-13 19:04
This is already implemented for 4.2 and available for testing in the nightly builds.

**Comment by oktophonie** [comment] 2023-11-13 19:11
Duplicate of https://github.com/musescore/MuseScore/issues/13242

**Closed by oktophonie** 2023-11-13 19:11 UTC
Labels: duplicate, feature request
