### ISSUE TITLE
[MU4 Issue] Hiding treble clef staff results in instrument label being removed from the score

### ISSUE THREAD

**Issue by DavesCodeMusings** [musescore/MuseScore#16759] opened 2023-03-13 00:59 UTC
When an instrument spans both treble and bass clef, switching off visibility of the treble clef staff will remove the instrument label from the score.

Expected behavior: The instrument label should remain, like it does when only the bass clef visibility is turned off.

Steps to reproduce:
1. Add an instrument that has treble and bass clef.
2. On the Instruments tab, click the instrument to expand staff selections.
3. Toggle the visibility on the treble clef staff for the instrument.
4. Notice how the instrument label disappears from the score.

In the screenshot, I have Bass Synthesizer with the **treble clef** staff hidden. The instrument label is missing from the score. I also have Atmosphere Synthesizer shown with the **bass clef** staff hidden. The instrument label is shown as expected. The problem seems to only happen when treble clef is hidden.

![image](https://user-images.githubusercontent.com/61114342/224585232-09ba8a2c-b02f-4897-bc8a-797d49bfe621.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by oktophonie** [comment] 2023-03-13 08:27
Duplicate of https://github.com/musescore/MuseScore/issues/16569 (fixed in master)

**Closed by oktophonie** 2023-03-13 08:27 UTC
