### ISSUE TITLE
Crash inserting measure at beginning of score

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#21049] opened 2024-01-17 15:47 UTC
### Issue type

Crash or freeze

### Bug description

Inserting a measure at the beginning of a score (any score) crashes current 4.2.1 - this is a regression vs 4.2

### Steps to reproduce

1. new score, treble template
2. select first measure
3. press Insert

Result: crash

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240170504, revision: github-musescore-musescore-9e59c8a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

### Additional context

No useful info on console - it shows that the command was successfully initiated, then it crashes

As far as I can tell the crash happens for any score.  Works fine in 4.2, so it's a pretty recent regression @bkunda

**Comment by DmitryArefiev** [comment] 2024-01-17 18:05
I **can't reproduce** it just with one Insert command (Win10/LinuxUbuntu22.04)

I **can reproduce the crash** but only with these steps (and this crash occurs in 4.2 and 4.1.1 as well):
1. Open Treble clef template
2. Select first measure
3. Press **Insert** for about 10 times
4. Undo all actions (it's better to press and hold Ctr+Z)


 

https://github.com/musescore/MuseScore/assets/90187801/b375a859-3aa1-4ad5-80b1-864eba6d5901

**Comment by MarcSabatella** [comment] 2024-01-17 18:38
I have two different Linux systems, and the crash is always reproducible on one, but never with the other.  Also, only with the insert shortcut, not using other methods of inserting.

I'll keep investigating since it's clearly not universal,m and hopefully not common either...

**Comment by MarcSabatella** [comment] 2024-01-17 18:57
Stranger, the crash only happens if I use the default Insert key combination on my keyboard, which is actually Shift+Meta+Backspace.  If I redefine the "Insert measure before selection" shortcut to be some other key, there is no crash.  Which would make me think it was something about the keyboard interaction.  Except, why only at the start of a score?

Also, if I run from the command line with "-d" there is a small bit of additional info:

> 11:41:36.422 | DEBUG | main_thread     | ShortcutsController::activate | Ins
> 11:41:36.423 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: insert-measure
> 11:41:36.434 | DEBUG | main_thread     | Score::endCmd   | Undo stack current macro child count: 14

The "try call action" was the only info originally.  But this shows me the crash doesn't happen until the endCmd, presumably processing the undo stack.  Which might also tie into why it can be made to crash on undo.

Not sure what this tells us, but anyhow, again, hopefully not a common problem.  I will still continue to poke around, but fingers crossed that it's unique to my keyboard (and redefining the shortcuts gives me a workaround, so I'm not worried for my own sake).

**Comment by DmitryArefiev** [comment] 2024-01-18 08:56
> I have two different Linux systems, and the crash is always reproducible on one


@MarcSabatella Can you also attach a log+dump files for that os with crash please?

**Comment by bkunda** [comment] 2024-01-18 09:22
I'm unable to reproduce this on macOS (using Shift+Option+B).

**Comment by bkunda** [comment] 2024-01-18 10:10
So three of us have been unable to reproduce this now (on repeated attempts). 
As such, let's postpone this for a later release, especially as it doesn't seem to have universal applicability (hopefully it is peculiar to your setup @MarcSabatella, and glad there is a workaround too!). 
Thanks all.

**Comment by MarcSabatella** [comment] 2024-01-18 14:16
Agreed that since this seems to be a rare problem that so far affects one of my systems only, no sense holding up 4.2.1 for it.  It wasn't obvious that would the case when I first reported it, of course!

FWIW, I can still reproduce (using the default Insert key as the shortcut) in last night's build, but *not* in the RC.  Which is also strange, but I'm not complaining.  I checked the nightly in both "developer" and "release" mode (using the triple-click-about-dialog trick) and it crashes the same either way, so that's not the differentiator.  Could be something about different build flags I guess.

Anyhow, I have attached the diagnostics:

[insert-crash.zip](https://github.com/musescore/MuseScore/files/13977584/insert-crash.zip)

I don't see anything there I didn't already see on the console, but I'm not really sure what to look at other than the log files.

**Comment by RomanPudashkin** [comment] 2024-04-12 09:46
@MarcSabatella please try again with the latest master

**Comment by MarcSabatella** [comment] 2024-04-12 14:47
Unfortunately, the system where this crashed is now dead, so I can't reproduce this even in 4.2.1 or 4.3 latest.  Also, I can't currently run master builds due to a library issue - missing libOpelGL.so.0.  I haven't yet investigated whether this is something I need to deal with on my end or something that should actually be included in the AppImage.

**Comment by RomanPudashkin** [comment] 2024-04-15 07:14
We suspect this may have been fixed in https://github.com/musescore/MuseScore/pull/22279. I'm going to close this issue, please reopen it if it's still happening. Thanks!

**Closed by RomanPudashkin** 2024-04-15 07:14 UTC
Labels: needs info, regression, crash
