### ISSUE TITLE
Splitting off the last note of a beamed group doesn't update its beam direction

### ISSUE THREAD

**Issue by kapostamas** [musescore/MuseScore#25835] opened 2024-12-14 15:36 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Enter a beamed group of notes so that the last note should be oriented differently than the others. E.g.: G, A, B sixteenths in treble clef.
2. Select the last note and set its beaming to either _No beam_ or _Break beam left_.

The note should flip to its natural stem direction, but it stays as it was while beamed to the others.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/2c26b2b5-4d7b-4d6f-90f1-1f6c49bd0e75)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242971445, rev. eb6b367

### Regression

I was unable to check

### Operating system

OS: Ubuntu 24.04.1 LTS, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-12-14 16:44
Duplicate of https://github.com/musescore/MuseScore/issues/25835

**Closed by oktophonie** 2024-12-14 16:44 UTC
Labels: engraving

**Comment by FrancRos31** [comment] 2024-12-14 16:50
> Duplicate of #25835

@oktophonie, you just cited this issue as a duplicate of itself.
