### ISSUE TITLE
[MU4 Issue] Score breaks if we select note and double click on empty score space

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7675] opened 2021-03-06 05:18 UTC
**Describe the bug**
Score zoom out and notes zoom in  (video attached)

**To Reproduce**

1. Create a score 
2. Add notes
3. Click on a note to select it
4. Double click left mouse button on empty space on a score

**Expected behavior**
Note deselected

**Screenshots**

https://user-images.githubusercontent.com/71372310/110196280-92ca0d80-7e54-11eb-8d27-6d8e9c7f52e6.mp4

**Desktop (please complete the following information):**

**Additional context**
Bug Reproduces with this score
https://github.com/musescore/MuseScore/blob/master/vtest/scores/lyrics-8.mscx

**Comment by wizofaus** [comment] 2021-06-17 09:48
Can't reproduce with a new blank score and an added note, but yes, can reproduce with this one, investigating.

**Comment by wizofaus** [comment] 2021-06-17 11:08
Ok all I've been able to figure out is that when the inspector tries to update itself to show "custom" page size in the dropdown, the score width/height ends up getting set to -1 (via a currentPageSizeIdChanged event), which screws everything else up.  You can see the same problem with other scores if you manually select "custom" page size in the inspector.

**Comment by wizofaus** [comment] 2021-06-17 11:58
I'd suggest perhaps @Tantacrul should suggest what behaviour is wanted here if "Custom" is explicitly chosen in the inspector dropdown.  We can pick some random size like 6 by 7 inches and just use that, which they would then need to change in the Page Settings dialog.  But that would be an independent change to this fix. NB the -1 width/height for Custom appear to come from Qt.

**Comment by Tantacrul** [comment] 2021-06-17 12:56
I'm actually (now) of the opinion that the page size settings should not be in the inspector because they really are a one-off setting. I do think that we should keep the button that opens the page settings dialog.

What do you think of that as a first step?

As for the other issue: the behaviour of 'Custom'. I agree that we should pick some initial setting, like A4 to begin with.

**Comment by cbjeukendrup** [comment] 2021-06-17 13:09
I suggest that when you have a non-custom size selected and then switch to "custom", the width and height should initially be those of the previously selected size (regardless of whether that was A4 or Letter or whatever).

**Comment by wizofaus** [comment] 2021-06-17 19:20
My initial fix was just that - don't change the size if custom is selected but it felt very unsatisfactory,  there are too many actions in MuseScore that apparently do nothing as it is.
Perhaps the page size could be shown as a read only field in the inspector? I'm not sure why page settings aren't part of the score styles dialog (internally they're scored together).

**Comment by Tantacrul** [comment] 2021-06-17 20:06
It is debatable how we should eventually reconcile / change both 'Styles' and the 'Page settings' in future. However, for now, we should keep them as is and just make fixes to obvious problems. I want to overhaul both in later releases.

I also definitely think we can lift out the 'page settings' options from the inspector. I think Casper's solution makes sense... as long as we remove the options from the inspector. They clearly shouldn't be there (my bad)

**Comment by wizofaus** [comment] 2021-06-17 20:44
The inspector for the page currently looks like this:
![image](https://user-images.githubusercontent.com/5364225/122469425-4a4bef80-d000-11eb-8d85-4e3dd7b3c616.png)
Are you saying you want it like this?
![image](https://user-images.githubusercontent.com/5364225/122469595-7bc4bb00-d000-11eb-888e-c07aa3b3f9c4.png)

I can then remove all the logic around handling page size changes etc. which will also fix the issue here.
The issue of what happens when you DO select Custom size in the Page Settings dialog should be fixed separately.
(I don't mind if it initially puts the size/height as 0 but I wouldn't expect it should allow you to save it in that state).

**Comment by wizofaus** [comment] 2021-06-17 20:50
BTW the staff spacing/staff distance settings do nothing if the option "Enable vertical justification of staves" is selected, which is actually the default at least for some templates, so it's not clear why we're showing these here either? Also I don't quite understand why "staff distance" maxes out at 10.

**Comment by Tantacrul** [comment] 2021-06-17 20:58
> The inspector for the page currently looks like this:
> ![image](https://user-images.githubusercontent.com/5364225/122469425-4a4bef80-d000-11eb-8d85-4e3dd7b3c616.png)
> Are you saying you want it like this?
> ![image](https://user-images.githubusercontent.com/5364225/122469595-7bc4bb00-d000-11eb-888e-c07aa3b3f9c4.png)
> 
> I can then remove all the logic around handling page size changes etc. which will also fix the issue here.
> The issue of what happens when you DO select Custom size in the Page Settings dialog should be fixed separately.
> (I don't mind if it initially puts the size/height as 0 but I wouldn't expect it should allow you to save it in that state).

Yes :)

**Comment by Tantacrul** [comment] 2021-06-17 21:00
> BTW the staff spacing/staff distance settings do nothing if the option "Enable vertical justification of staves" is selected, which is actually the default at least for some templates, so it's not clear why we're showing these here either? Also I don't quite understand why "staff distance" maxes out at 10.

Oh, good point. The new inspector was actually designed before the changes to 3.6.2 were proposed, so that's why some of the options are so redundant. I think we should remove 'Staff spacing' and 'Staff distance' from here too.

**Comment by Tantacrul** [comment] 2021-06-17 21:01
In general, the 'new' inspector is ancient. About 18 months old, which is why I need to go back over it and clean the thing up more. There are far too many super niche options (like stem width) which should not be exposed at this level.

**Comment by wizofaus** [comment] 2021-06-17 21:03
So then it'll just be...

![image](https://user-images.githubusercontent.com/5364225/122471943-3fdf2500-d003-11eb-8794-54e3ba092801.png)

**Comment by Tantacrul** [comment] 2021-06-17 21:13
Looks good to me!

To be finicky... why is the text for 'page settings' off centre compared to 'Style settings'?

(also the 'p' in page should be capitalised, not that that's relevant to this discussion at all)

**Comment by wizofaus** [comment] 2021-06-17 21:15
That was a hack job in MS paint, that's all! Obviously would be centred and with capital P.

**Comment by Tantacrul** [comment] 2021-06-17 21:17
> That was a hack job in MS paint, that's all! Obviously would be centred and with capital P.

When using MS paint, look over to the top right at the button that says 'open in Paint 3D'. That's my sole contribution to that app :)

**Comment by wizofaus** [comment] 2021-06-17 21:17
Also the menu text and the dialog has the S in settings capitalised too, nor is "Style settings" used anywhere else except in this inspector (vs just "Style")...

**Comment by Tantacrul** [comment] 2021-06-17 21:18
> Also the menu text and the dialog has the S in settings capitalised too, nor is "Style settings" used anywhere else except in this inspector (vs just "Style")...

I need to write up a new style guide. Sentence case everywhere!

**Closed** 2021-06-24 16:41 UTC
Labels: P2
