### ISSUE TITLE
[MU4 Issue] Multiple grace note ledger lines overlap

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9988] opened 2021-12-06 16:16 UTC
**Describe the bug**

When there are multiple grace notes on a note, the ledger lines all overlap. There should be space around each note's ledger lines.

<img width="565" alt="Screen Shot 2021-12-06 at 8 16 13 AM" src="https://user-images.githubusercontent.com/5659171/144881840-ee7f47ab-af15-4133-88b8-2935c69999bd.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Additional context**
Related: https://github.com/musescore/MuseScore/issues/9987

**Comment by oktophonie** [comment] 2021-12-06 16:22
Duplicate of #9868

**Closed by oktophonie** 2021-12-06 16:22 UTC
