### ISSUE TITLE
Copy error

### ISSUE THREAD

**Issue by robioptic** [musescore/MuseScore#21866] opened 2024-03-09 03:33 UTC
### Issue type

Other type of issue

### Bug description

When selecting a score with tempo. It copies the notes but never the tempo. The empo looks selected- but never copies to a new location- which kills me because i sue it a lot :)

### Steps to reproduce

Score with tempo ie note=80 
Have any score below.
Select in any way you like. Bar, select highlight whatever...
Copy and paste ... and nothing ie. no tempo sign
![1](https://github.com/musescore/MuseScore/assets/162772506/279d6464-e2e9-49da-b4d8-43da9588a3d0)
![2](https://github.com/musescore/MuseScore/assets/162772506/79370231-5f7b-4b48-b28c-0ed122832b22)
![1](https://github.com/musescore/MuseScore/assets/162772506/b5fcb42d-4ced-4ca2-a604-197eb4980412)
![2](https://github.com/musescore/MuseScore/assets/162772506/e4eafd5c-3152-4281-b8fa-196fbc244cbd)

### MuseScore Version

LATEST AS OG 9-3-23 CAN'T FIND ABOUT ???

### Regression

I don't know

### Operating system

WIN11 

### Additional context

![1](https://github.com/musescore/MuseScore/assets/162772506/3363a261-0f87-4e36-8631-c5ca83ca1fd2)
![2](https://github.com/musescore/MuseScore/assets/162772506/7a2d9837-ac07-4d27-9a80-32df30c157f7)

**Comment by TeeDeeY** [comment] 2024-03-09 23:22
Musescore doesn’t copy tempos when copying other stuff.  If you only need to copy a single tempo multiple times, I find it easy to 1) select the tempo notehead before “=“, 2) press control c to copy, then 3) select an individual note to tell which beat to start, then 4) press control v to paste.  You can’t paste into the measure as a whole.  An individual note should be selected.   

If you have a group of tempos to copy, please try my plug-in TempoCP as listed on Musescore.org ;-).

**Comment by robioptic** [comment] 2024-03-10 12:27
Super!!!  :)
Many thanks foe your help!!! :)

Sent from Yahoo Mail on Android 
 
  On Sun., 10 Mar. 2024 at 10:23, ***@***.***> wrote:   


Musescore doesn’t copy tempos when copying other stuff. If you only need to copy a single tempo multiple times, I find it easy to 1) select the tempo notehead before “=“, 2) press control c to copy, then 3) select an individual note to tell which beat to start, then 4) press control v to paste. You can’t paste into the measure as a whole. An individual note should be selected.

If you have a group of tempos to copy, please try my plug-in TempoCP as listed on Musescore.org ;-).

**Comment by bkunda** [comment] 2024-03-12 14:33
@DmitryArefiev pls investigate

**Comment by MarcSabatella** [comment] 2024-03-12 15:17
To be clear, this is by design - system-level elements like tempo and rehearsal marks, also things like key and time signatures, barlines, and other "structural" elem ents - do not copy.  Or more accurately, they copy, but do not paste.  
There are some technical reasons why this could be difficult (eg, what should happen to key or time signatures or barlines if pasting to a different beat position than the original).  Also some reasons why it isn't necessarily desirable (copying the first measure of a score somewhere else should rarely duplicate its key or time signature or tempo).  But of course, there are other cases where one *would* want this.  It is a very long-standing request to allow control over this.

**Comment by DmitryArefiev** [comment] 2024-03-12 16:21
> BTW - the tempo looks selected because it is selected, and will respond to things like "V" to toggle visibility.

Yes, and when the measure with Tempo mark is selected, it's also available for editing in Properties. 
The **only thing we can do** I think is **to mark System text with another color** (when using the range selection) to show user this will not be copied-pasted.

@MarcSabatella Thanks for explanation!

Closing as by design

**Closed by DmitryArefiev** 2024-03-12 16:21 UTC
Labels: needs review

**Comment by robioptic** [comment] 2024-03-12 23:14
Thanks for the tip! 

Sent from Yahoo Mail on Android 
 
  On Wed., 13 Mar. 2024 at 3:21, Dima ***@***.***> wrote:   



BTW - the tempo looks selected because it is selected, and will respond to things like "V" to toggle visibility.


Yes, and when the measure with Tempo mark is selected, it's also available for editing in Properties.
The only thing we can do I think is to mark System text with another color (when using the range selection) to show user this will not be copied-pasted.

@MarcSabatella Thanks for explanation!

Closing as by design

**Comment by robioptic** [comment] 2024-03-12 23:16
Thanks for clarification! 

Sent from Yahoo Mail on Android 
 
  On Wed., 13 Mar. 2024 at 2:17, Marc ***@***.***> wrote:   


To be clear, this is by design - system-level elements like tempo and rehearsal marks, also things like key and time signatures, barlines, and other "structural" elem ents - do not copy. Or more accurately, they copy, but do not paste.
There are some technical reasons why this could be difficult (eg, what should happen to key or time signatures or barlines if pasting to a different beat position than the original). Also some reasons why it isn't necessarily desirable (copying the first measure of a score somewhere else should rarely duplicate its key or time signature or tempo). But of course, there are other cases where one would want this. It is a very long-standing request to allow control over this.
