### ISSUE TITLE
Incorrect portamento-style glissando playback

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#20611] opened 2023-12-20 23:04 UTC
### Issue type

Muse Sounds bug

### Bug description

This bug only works on "Muse Sound" sounds!
Two bugs. 
1. in portamento-style glissando, sliding to the next sound does not occur linearly, but closer to the exit (below is a screenshot with an approximate graph of sound sliding). In "MS Basic", sound sliding occurs linearly.
2.  the portamento-style glissando does not sound if I uncheck the box next to "Play" the note to which this glissando should sound (there is also a screenshot attached below, which shows the sound scheme).

Thus, the portamento on Bowed string instruments is almost inaudible (more precisely, it is not audible at all) and it is very sad.

### Steps to reproduce

gliss.: Properties > Playback > Style > Portamento
note: Properties > Play (uncheck the box)
![Снимок экрана (941)](https://github.com/musescore/MuseScore/assets/134041121/9230786b-5c15-417e-8d74-00799de67546)
![Снимок экрана (93)](https://github.com/musescore/MuseScore/assets/134041121/17e97686-9472-463c-94ff-1122191d1a6b)
![Снимок экрана (911)](https://github.com/musescore/MuseScore/assets/134041121/81e2fcd4-7fd8-4caf-83fc-f72bca44616a)

### Screenshots/Screen recordings

![Снимок экрана (94)](https://github.com/musescore/MuseScore/assets/134041121/f5ea162b-6b7f-4c11-a9e8-2f64cbaec024)

https://github.com/musescore/MuseScore/assets/134041121/0f417783-b047-4a9f-b388-c2a82bc3bbbd

https://github.com/musescore/MuseScore/assets/134041121/2e0c4cce-5a58-4e6c-9ba4-5b1fea1da3fc

https://github.com/musescore/MuseScore/assets/134041121/8cb0a353-a4d4-4d99-ba56-3be67bb09d94
[portamento-style gliss.zip](https://github.com/musescore/MuseScore/files/13733328/portamento-style.gliss.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by bkunda** [comment] 2023-12-21 14:53
I imagine we would need to provide curve adjustment settings ("ease in", "ease out", etc.) to accommodate this kind of request, which would bring us into feature request territory. 
@davidwhearn @sampleeditor do you have any thoughts on this?

**Comment by ChapeauCanotier** [comment] 2023-12-22 10:35
The latest musesounds/musescore (not a clue which one) update seems to have more or less destroyed glissando playback for almost all the musesounds instruments (brass, strings, woodwinds, though not piano); it's horribly fractured to the point that the glissandos are unusable. Installing the old version (4.1) of MS4 doesn't seem to fix this, I don't know why and I don't understand computers/software at all but this is all very frustrating

**Comment by bkunda** [comment] 2024-07-01 10:17
Duplicate of #20925

**Closed by bkunda** 2024-07-01 10:17 UTC
Labels: needs info, duplicate, muse sounds
