### ISSUE TITLE
Crash when trying to move the slur.

### ISSUE THREAD

**Issue by TanishqSadanala** [musescore/MuseScore#25139] opened 2024-10-13 06:36 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. open any file with slur.
2. try to move(position) the slur up or down with the mouse.
3. It crashes instantly.
4. Expected to reposition the slur(this is working with key arrows).

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/edfe8e6e-0c5f-4ca6-81aa-72ab8a45932b

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment] 2024-10-13 11:02
Duplicate of #24726. Try the last 4.4.3 build, it is fixed in there.

**Closed** 2024-10-13 15:57 UTC
Labels: crash
