### ISSUE TITLE
The Mixer menu does not size properly when displayed, if the Virtual Piano menu is also active

### ISSUE THREAD

**Issue by fsgregs** [musescore/MuseScore#18893] opened 2023-08-02 20:58 UTC
### Issue type

General playback bug

### Bug description

In MS 4, many folks can activate the virtual Piano and place its menu docked on the bottom (see image 1 below).  Now, if the Mixer menu is then turned on using F10, it will overlay the score and the Piano menu both, BUT, the top of the Mixer menu will be missing.  There will be no "Sound" line visible, showing what MuseSounds or Soundfonts were chosen for each instrument (see image 2 below).  To correct this, a user must locate the top of the Mixer menu & drag it upward to display the Sound line.  However, when the Mixer is then closed (using F10), and then reopened, the same sizing issue occurs.  The top of the menu is again missing.  The error correction is not saved.

![image](https://github.com/musescore/MuseScore/assets/133777637/49f35593-74f1-405f-9351-3cc2524b6292)

![image](https://github.com/musescore/MuseScore/assets/133777637/8494c396-0bad-4ab2-9550-e11ada4de8a1)

The mis-sizing of the Mixer menu when the virtual keyboard menu is also active, needs to be fixed ASAP so that the top "Sound" line is visible when F10 is pressed.

### Steps to reproduce

1. Open any score
2. Turn on the Virtual Piano by pressing "P" on the keyboard or use the "View" tab
3. Manually size the keyboard so it is docked at the bottom of the score
4. Now press the F10 keys to turn on the Mixer menu.  The new menu will display but the top line (Sound) will be missing
5. Fix the problem manually by locating and dragging the top of the Mixer menu up so that Sound is now displayed.
6. Close the Mixer menu via F10, then reopen it.  The original problem will reappear. 

### Screenshots/Screen recordings

Screenshots are included above

### MuseScore Version

4.1.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by zacjansheski** [comment] 2023-08-04 12:59
Related to https://github.com/musescore/MuseScore/issues/17634

**Comment by cbjeukendrup** [comment] 2023-08-04 13:08
This looks like a duplicate of #11335 and #15856. I don't think it really needs design; it's just a bug that will need to be fixed anyway, regardless of the upcoming design changes.

**Closed by cbjeukendrup** 2023-08-04 13:08 UTC
Labels: UI, regression_ms3
