### ISSUE TITLE
[MU4 Issue] Style window takes very long to appear

### ISSUE THREAD

**Issue by peppidesu** [musescore/MuseScore#15403] opened 2022-12-19 23:24 UTC
**Describe the bug**
The style window (and some other pop-up windows too, but this one in particular) takes very long to load, to the point that windows thinks musescore is not responding.

**To Reproduce**
1. Open a score
2. Click on 'Format', then 'Style ...'
3. Pop-up takes up to 40 seconds to appear, during which musescore hangs.

**Expected behavior**
The pop-up should appear faster, or should appear with a loading wheel and load the contents asynchronously.

**Platform information**
 - OS: Windows 10 21H2

**Comment by miwelte** [comment] 2022-12-20 12:52
Confirmed. Same here.

**Comment by Jojo-Schmitz** [comment] 2022-12-20 12:55
I believe that had been report before, several weeks ago

**Comment by oktophonie** [comment] 2022-12-20 13:51
Duplicate of https://github.com/musescore/MuseScore/issues/13193

**Closed by oktophonie** 2022-12-20 13:51 UTC
