### ISSUE TITLE
[Crash] Closing timeline causes crash (and sometimes causes crashes on open too)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10092] opened 2021-12-14 14:44 UTC
**Describe the bug**
Having the Timeline and navigator option open by default can lead to two different crashes.

1. Closing the timeline option crashes the app (Reproduce: often)
2. Opening a new score with Mixer, Timeline & Navigator open by default can lead to crashes too (Reproduce rarely. Hard to confirm exactly what is causing it. Might be wrong.)

**To Reproduce**
Steps to reproduce:
1. Create a new Score
2. Turn on the Mixer, Navigator and Timeline
3. Enter a note on the score to mark it dirty
4. Save the file (this then tells MuseScore to remember to keep the mixer+timeline+navigator open the next time the app boots)
5. Close the app and re-open it
6. Create a new score (I tested with 1x Horn and 1x Trombone)
7. Click on the '...' button on the timeline and choose 'Close' from the context menu
8. App crashes (see video)

**Note**
This crash seems to only happen when the navigator is open. When I close the navigator, I have not yet noticed this same crash.

**Video**

https://user-images.githubusercontent.com/21022311/146020375-a1d60e71-1a44-4f0a-a30e-a6b97126a202.mov

**Desktop (please complete the following information):**
 - OS: Mac Catalina

**Comment by Jojo-Schmitz** [comment] 2021-12-14 14:49
Somehow related to https://musescore.org/en/node/317511, maybe ?

**Comment by vpereverzev** [comment] 2021-12-15 09:59
@Tantacrul none of us can reproduce this crash. Are you sure that you were using the latest version?

**Comment by Tantacrul** [comment] 2021-12-17 09:31
Yes. I just grabbed the latest nightly build now and the issue is still happening.

It's important that you create a new score first and then open the navigator and timeline - then save the score and reopen the app. That then causes the navigator and timeline to be open by default. It's at this point that closing the timeline causes a crash.

I've not tested this on Windows yet.

**Comment by VanSHOE** [comment] 2022-02-04 17:04
I am unable to reproduce this on Windows, could you provide a score file on which this is happening?

**Comment by Tantacrul** [comment] 2022-02-05 16:19
I've just tested this on my new laptop (M1 mac this time) and the problem is not happening.

**Comment by Tantacrul** [comment] 2022-02-05 16:22
@DmitryArefiev - what do you think? Shall we close this and see if it resurfaces?

**Comment by DmitryArefiev** [comment] 2022-02-05 20:09
@Tantacrul - Sure! Let's close it. We can reopen if someone can reproduce it again.

Can't reproduce this on **Win10/Mac12.2** (latest master). Closing

**Closed by DmitryArefiev** 2022-02-05 20:09 UTC
Labels: P0
