### ISSUE TITLE
[MU4 Issue] Playing with Midi Keyboard

### ISSUE THREAD

**Issue by RafaelLiebermann** [musescore/MuseScore#11480] opened 2022-04-30 18:55 UTC
Assigning play button in MIDI mappings causes broken 'Play' functionality.

Steps to reproduce the behaviour:
See @jessjwilliamson's video in the comments down below. This demonstrates the problem perfectly.

Windows 11 Pro 22h2 Dev build 22593

**Comment by Tantacrul** [comment] 2022-04-30 19:54
Are you able to play in the way you expect in MuseScore 3?

**Comment by RafaelLiebermann** [comment] 2022-05-01 08:56
No. It simply don't start.

**Comment by Tantacrul** [comment] 2022-05-01 09:16
What I mean is: does the problem you are describing happen in both MuseScore 3 AND MuseScore 4?

**Comment by RafaelLiebermann** [comment] 2022-05-01 12:10
No it only happens in musescore 4

**Comment by rgreen5** [comment] 2022-05-01 13:33
Looks similar to #11234, External MIDI keyboard unable to play MuseScore instruments

**Comment by RafaelLiebermann** [comment] 2022-05-01 14:49
Well that also happens to me but this is different. I don't know if it's just me but when you press the play button on the keyboard (image below) instead of star playing the cursor appears and stays in the same place just like if I was pressing the button multiple times.
![305a50bf-9c39-4803-9f7e-2c0e3ce6d8c9](https://user-images.githubusercontent.com/76731756/166151155-b90fed6d-a7bb-4022-bcd2-1cf9ea848c79.jpg)

**Comment by RafaelLiebermann** [comment] 2022-05-01 14:49
Forgot to mention it also happens in my other keyboards

**Comment by Tantacrul** [comment] 2022-05-01 15:22
@bkunda - can you investigate this one? Curious to know whether there's a more serious uber-bug in this.

**Comment by bkunda** [comment] 2022-05-02 11:31
@jessjwilliamson I don't actually have a MIDI keyboard with integrated playback controls. Do you have one and, if so, could you test this issue please?

**Comment by jessjwilliamson** [comment] 2022-05-11 12:15
@RafaelLiebermann Hi, so have you ever assigned the play button with your keyboard in Musescore 3 before? By going to Preferences>Note Input>MIDI Remote control. I don't know if Musescore 3 can automatically recognise any devices and assign to some buttons automatically, but from you, it sounds like it has already been assigned manually?

**Comment by RafaelLiebermann** [comment] 2022-05-11 12:34
Yes it is
________________________________

**Comment by jessjwilliamson** [comment] 2022-05-11 12:37
Great. I think the MIDI Device Mappings need some more attention, there are quite a few issues there.

**Comment by Tantacrul** [comment] 2022-05-11 14:24
@jessjwilliamson - fantastic. Thanks for that!

I've added a priority and I'm now reassigning to the development team. I've also updated the issue description and cleared out all the comments (mainly me) to make the issue easier to understand. Thanks again!

**Comment by boryskuzmenko** [comment] 2022-08-25 14:03
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12735
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by jessjwilliamson** [comment] 2022-08-31 12:41
Hey guys I'm afraid it's still not working. Hard to explain by text so I'm showing it here on video. Sound on!

https://user-images.githubusercontent.com/71656189/187680587-3f93b496-506f-4208-bbe9-8290e513563b.mp4

**Comment by Tantacrul** [comment] 2022-08-31 12:57
I would log the 'Active' / 'Inactive' visual UI issue as a separate bug and mark it with P3 and Community tags.

I'd say some local hero may jump in to fix it separately.

**Comment by jessjwilliamson** [comment] 2022-08-31 13:14
> I would log the 'Active' / 'Inactive' visual UI issue as a separate bug and mark it with P3 and Community tags.
> 
> I'd say some local hero may jump in to fix it separately.

Beat you to it :) https://github.com/musescore/MuseScore/issues/13098

**Comment by jessjwilliamson** [comment] 2022-09-01 17:12
> @jessjwilliamson could you do the same flow with another midi device?
> 
> JFYI Actually, this are need more attention and effort. When I closed this issue I've created three more complicated issues #13028 #13030 #13031

Damn. Now I'm testing on a different device and it works. Hmm. I wonder if it's got to do with old vs new devices? 
Initially I was using a Roland RD-170 which is a keyboard made in the mid 00's. Just tested with a modern keyboard AKAI LPK25 and it works just fine. Why is this happening?

**Comment by Tantacrul** [comment] 2022-09-01 17:35
@boryskuzmenko  / @DmitryArefiev - can you test your devices and say whether this issue is happening for you?

@jessjwilliamson - to confirm: the problem is keyboard specific? So it is still happening with your Roland but not your AKAI?

**Comment by jessjwilliamson** [comment] 2022-09-02 11:49
> @jessjwilliamson - to confirm: the problem is keyboard specific? So it is still happening with your Roland but not your AKAI?

I tried different types of connections, so keyboard direct to USB compare to keyboard to audio interface etc. Roland is still having problems. I've done MIDI mapping on Ableton with Roland and it works fine so it's not my keyboard. the only different is that my Roland has MIDI In and Out ports at the back of the keyboard. My Akai has mini USB. I'm out of ideas what it could be. I looked into MIDI message readers - all looks okay from here.

**Comment by DmitryArefiev** [comment] 2022-09-02 13:17
@Tantacrul @jessjwilliamson My **Arturia KeyLab61 Essential (USB)** works fine on Windows10


https://user-images.githubusercontent.com/90187801/188153989-5257845b-4146-41fc-ac9c-d8e76ba3d825.mp4



The reason for appearing that strange bug could be #13028 (More than one midi parameter can be mapped to one MU parameter).

As I see from Roland RD-170 description it has "_88 Weighted Keys with Touch-Sensitivity hammered action (New)_". Maybe that high quality keyboard has more MIDI messages than usual keyboard during one key press. 

Interesting  to compare MIDI messages during one key press between Roland RD-170 and AKAI LPK25 (using some MIDI monitor app). Or just to fix #13028 and to see how it goes with Roland RD-170

**Comment by jessjwilliamson** [comment] 2022-09-02 13:33
> @Tantacrul @jessjwilliamson My **Arturia KeyLab61 Essential (USB)** works fine on Windows10
> 
>  bandicam.2022-09-02.16-14-03-487.mp4 
> The reason for appearing that strange bug could be #13028 (More than one midi parameter can be mapped to one MU parameter).
> 
> As I see from Roland RD-170 description it has "_88 Weighted Keys with Touch-Sensitivity hammered action (New)_". Maybe that high quality keyboard has more MIDI messages than usual keyboard during one key press.
> 
> Interesting to compare MIDI messages during one key press between Roland RD-170 and AKAI LPK25 (using some MIDI monitor app). Or just to fix #13028 and to see how it goes with Roland RD-170

Ohh.. I have another hammer-weighted keys keyboard I can test with. Will try test that

**Comment by boryskuzmenko** [comment] 2022-09-02 13:42
I'd fix this two issue first https://github.com/musescore/MuseScore/issues/13028
https://github.com/musescore/MuseScore/issues/13030 and see. It really can be the same root issue

**Comment by jessjwilliamson** [comment] 2022-09-02 14:05
Just tried on another hammer-weighted keyboard - Yamaha CLP-411. Also old-fashioned with MIDI in and Out cables only on the back. Also does the same bug. Could be a non USB wire cable issue or something else. Seems all USB connected only keyboard word, just not the old fashioned MIDI in and out cables.

**Comment by jessjwilliamson** [comment] 2022-09-02 14:12
> I'd fix this two issue first #13028 #13030 and see. It really can be the same root issue

13028 attached video doesn't work can you try re-uploading again please :)

**Comment by abariska** [comment] 2022-09-27 09:52
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

**Closed** 2022-09-27 10:00 UTC
Labels: P1

**Comment by Julien441Lab** [comment] 2023-01-02 13:56
Hi, I have the exact same issue using a Novation Launchkey Mini MK3, with OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621. 
Are there any incompatibilities with some keyboards ?

**Comment by SplashChoke** [comment] 2025-04-27 12:33
This issue may have returned. My config: macOS 15.4, Arch.: arm64, MuseScore Studio version (64-bit): 4.5.1-250800846, revision: github-musescore-musescore-603eca8
I have an old [M-Audio Axiom 25](https://www.m-audio.com/legacy/axiom-25.html) connected via USB.
Issues: 
1. Assigning Play to the transport button on the Axiom doesn't latch. While holding it, I also hear notes that are not in the score. This button sends CC117 by default, which is mapped in MU4.5 to start play, but could perhaps also trigger some other functionality.
2. I use the 8 percussion pads to enter drum notation and each time I press a pad (or the corresponding key on the piano keyboard) I hear the note being played twice.

**Comment by DmitryArefiev** [comment] 2025-04-29 17:16
> 1. Assigning Play to the transport button on the Axiom doesn't latch. While holding it, I also hear notes that are not in the score. This button sends CC117 by default, which is mapped in MU4.5 to start play, but could perhaps also trigger some other functionality.

I think this logged here #13030

> 
2. I use the 8 percussion pads to enter drum notation and each time I press a pad (or the **corresponding key on the piano keyboard**) I hear the note being played twice. I've set the MIDI output to ' No Device' to avoid any feedback from MU4.5 to the Axiom and back into MU4.5 but that doesn't change the behavior.

@SplashChoke I **can't reproduce** it with Native Instruments Komplete Kontrol M32 on Mac13.7.2 with regular keys. 
Did you try your midi keyboard in other notation software or DAW?

**Comment by SplashChoke** [comment] 2025-04-29 20:22
Hi @DmitryArefiev,
I tried the method described in #13030, but the preferences look very different in my current version 4.5.1 and I couldn't find the toggle property.
However, while looking through the preferences I resolve the double triggering. I needed to clear the 'Play MIDI input' checkbox in the Note input tab.

![Image](https://github.com/user-attachments/assets/103d001b-a568-40f5-b633-015de48421d5)

**Comment by DmitryArefiev** [comment] 2025-04-30 16:25
> I tried the method described in https://github.com/musescore/MuseScore/issues/13030, but the preferences look very different in my current version 4.5.1 and I couldn't find the toggle property. Where is it located now?

@SplashChoke Correct. It's **not implemented** yet (the bug is still open)

> However, while looking through the preferences I could resolve the double triggering. I needed to clear the 'Play MIDI input' checkbox in the Note input tab. The double triggering didn't occur in GigPerformer.

Good! 

But please add a video recording when 'Play MIDI input' is checked and you have that issue
