### ISSUE TITLE
[MU4 Issue] Playback is laggy and has popping noises when compared to MU3 due to buffer size (Windows)

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#11222] opened 2022-04-17 20:31 UTC
**Describe the bug**
The playback sound in MuseScore 4 is more jittery/laggy/disconnected sounding than it was in MU3. Also, popping noises can be heard.

**To Reproduce**
1. Find a score with many instruments (I used https://musescore.com/pukalo/scores/1506861 in the recording below, but the issue happens with any score and is especially noticeable with percussion ensemble music.)
2. Make two copies of the score. Open one copy in MU3 and the other copy in MU4.
3. Play the MU3 version, then the MU4 version
4. Compare how they sound.

Recording (MU3 first, then MU4): (video is sound only)

https://user-images.githubusercontent.com/91428485/163731096-374638d3-ee7b-4634-a083-cfac81ca2739.mp4

**Expected behavior**
The playback should be similar to MU3 without jittering, popping noises and a laggy feeling.

**Screenshots**
N/A

**Platform information**
 - OS: Windows 11
 - MU4 Private Alpha (EDIT: Still occurs in the nightlies as of 7/27/22)

**Additional context**
I have not edited any sound-related preferences in MU3 or MU4.

**Comment by mattblo** [comment] 2022-04-26 16:34
This problem bothers me every time I open a file from Musescore 3! Always this popping noise in between...

**Comment by Rchatru** [comment] 2022-04-29 01:19
I have exactly the same problem. It happens both with imported files from the previous Musescore 3, and with the files created with this one. 

If you need more information or to do some tests, I'm available to help in any way I can.

**Comment by JezSonic** [comment] 2022-05-04 10:18
well.. same problem here. I hope someone will fix that

**Comment by mattblo** [comment] 2022-06-24 05:30
Shouldn't this be assigned to the Alpha2 as it affects the default playback?

**Comment by mattblo** [comment] 2022-08-08 05:58
In the latest NightlyBuild, the audio buffer can be set.
If I set the highest possible value there (4096), the annoying crackling is over. With 2048 unfortunately not yet. 
The question is whether there should not be a higher buffer value for older hardware, since my notebook is fairly new and has an i7, which should definitely not be too weak for Musescore.

**Comment by mattblo** [comment] 2022-08-08 06:00
Perhaps the default buffer value should also be set much higher, since many users probably don't want to search through the settings to get the sound to sound good.

**Comment by wizofaus** [comment] 2022-09-04 08:09
Can confirm that setting the buffer size to 4096 fixes this problem for me.  Any disadvantage in a higher buffer size @vpereverzev ?

**Comment by Rchatru** [comment] 2022-09-07 20:26
I also had the same problem. As already mentioned, it helped me to change the buffer size setting from 1024 to 2048, as you can see in the audio. I hope it can help someone, because I found the solution by chance.


![Buffer](https://user-images.githubusercontent.com/38190230/188970633-775b5a3d-8fef-402f-87dd-ef23def7b2c6.PNG)


https://user-images.githubusercontent.com/38190230/188969480-bb595d52-f8bc-452d-bd67-9d860155e716.mp4

https://user-images.githubusercontent.com/38190230/188969476-953ec949-69d8-43a8-9dcb-6dc44961aece.mp4

**Comment by vpereverzev** [comment] 2022-09-18 00:40
@GabeS573 @wizofaus @mattblo @Rchatru @JezSonic is everybody having these problems specifically on Windows?

**Comment by cbjeukendrup** [comment] 2022-09-18 00:58
If I set the buffer size very low (32), it seems I can also reproduce it on macOS. But I do notice that I need a much higher buffer size on Windows than on macOS; on Mac, even 128 already seems to work reasonably (for small scores).

**Comment by wizofaus** [comment] 2022-09-18 02:46
Windows for me, yes, but it's fine with 4k buffer size.

**Comment by GabeS573** [comment] 2022-09-18 02:49
I still experience it on Win11, but I'm not able to test any other operating systems. The sound is mostly fine on the largest buffer size.

**Comment by Rchatru** [comment] 2022-09-18 03:26
Correct, it happens to me in Windows 10

**Comment by cbjeukendrup** [comment] 2022-09-18 17:09
By the way, here is an issue that seems related: #12637
(just linking it so that we don't forget to re-check one if the other gets fixed)

**Comment by mattblo** [comment] 2022-09-19 08:33
I also use WIndows 11, but in the latest NightlyBuilds I no longer have this problem. Even with a buffer of 256, the playback is fine!

**Comment by wizofaus** [comment] 2022-09-19 20:47
Just tried latest build (from source, debug build) on Windows 10 and playback is now fine at 1024 buffer size, but not 512 or 256 (256 is esp. weird, seems to repeat lots of notes).
But what's the advantage in using a buffer size below 1024?

**Comment by wizofaus** [comment] 2022-09-19 21:45
Sorry I take that back, it's still not good even at 1024 (it was ok for about 30 seconds but after that started distorting/skipping etc.)
2048 seems fine.

**Comment by Tantacrul** [comment] 2022-10-12 11:17
Closing this as a duplication of https://github.com/musescore/MuseScore/issues/12483

**Closed by Tantacrul** 2022-10-12 11:17 UTC
Labels: P1
