### ISSUE TITLE
[MU4 Issue] Muse Sounds: Tempo in exported file is sometimes too slow, leading to cut off audio at the end of the file and out of sync with non-Muse Sounds instruments

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13938] opened 2022-10-23 19:53 UTC
**Describe the bug**
On Discord, a lot of users have uploaded audio files using Muse Sounds. Many of those files end abruptly, and contain not the whole piece. It sounds like the exported audio is too slow, compared to what you hear during "live" playback inside MuseScore.

Also, there is an example of a score on MuseScore.com where this causes audio to get out of sync with the measure highlight:
https://musescore.com/user/39542633/scores/8861868/s/z1kscJ?share=copy_link
And during the second time of the repeat, the playback goes completely crazy...

**To Reproduce**
1. Suppose system speakers have sample rate _x_
2. Open MuseScore and open a score with Muse Sounds
3. Export audio, with sample rate _y_, where _x_ ≠ _y_
-> the Muse Sounds instruments play too slow, while non-Muse Sounds instruments are okay

So far, I have not been able to reproduce this on macOS, only on Windows.

**Comment by erinic04** [comment] 2022-10-23 21:02
Yeah this score exported at 83 bpm instead of 90 for me:
[Bridge Over Troubled Water.mp3.zip](https://github.com/musescore/MuseScore/files/9847523/Bridge.Over.Troubled.Water.mp3.zip)
[Bridge Over Troubled Water.mscz.zip](https://github.com/musescore/MuseScore/files/9847524/Bridge.Over.Troubled.Water.mscz.zip)
(remove the .zip at the end)

**Comment by erinic04** [comment] 2022-10-24 00:02
Seems to happen with every export I do

**Comment by erinic04** [comment] 2022-10-24 17:32
Will do when I get home from school 👍

**Comment by jeetee** [comment] 2022-10-24 19:56
Random possible correlation thought: Both given tempo relations are around 92% slower; which seems to be also the 44.1kHz to 48kHz relation (91.875%)

**Comment by cbjeukendrup** [comment] 2022-10-24 20:58
> Random possible correlation thought: Both given tempo relations are around 92% slower; which seems to be also the 44.1kHz to 48kHz relation (91.875%)

There are indications that this is the case. @musondanolan's edited post seems to prove this, and also for other people it seems to be like this. Time to try if I can reproduce it myself by playing with my sample rate :)

**Comment by cbjeukendrup** [comment] 2022-10-28 00:07
Copying from https://github.com/musescore/MuseScore/issues/14081#issuecomment-1294203746:

I finally reproduced it! Only on **Windows** though, not yet on macOS.

1. Set system speakers to 48000Hz (for example)
2. Launch MuseScore
3. Select Muse Sounds
4. Export audio at 44100Hz (for example; in any case different from system speakers)
-> audio too slow

**Comment by cbjeukendrup** [comment] 2022-10-28 10:16
Assigning @iamtesch too, since this really seems a Muse Sounds sample rate issue

**Comment by iamtesch** [comment] 2022-10-28 14:42
I believe this will be fixed with a muse sounds update we are planning on pushing later today.  The windows build did not have as many of the recent fixes as the Mac build did at the time of the beta release.  I'll let you know when to retest

**Comment by cbjeukendrup** [comment] 2022-12-09 11:00
This seems to work well for me now on Windows. @erinic04 @musondanolan Could you please re-test this too?

**Comment by vpereverzev** [comment] 2022-12-09 11:21
doesn't occur to me anymore and we've tested audio export with MuseSounds recently A LOT :)

@Tantacrul @bkunda if it's also the case for you, I think we can close that one and re-open if there will be more reports

**Comment by bkunda** [comment] 2022-12-09 11:41
I have not been able to reproduce this issue in all the export testing I've recently done.

**Comment by Tantacrul** [comment] 2022-12-09 12:53
I have not experienced this after a lot of export testing on Windows and MacOS. Closing for now.

**Closed by Tantacrul** 2022-12-09 12:53 UTC
Labels: P1
