### ISSUE TITLE
[MU4 Issue] Sound artifacts on certain notes in Muse Keys 'Grand Piano' soundfont

### ISSUE THREAD

**Issue by jplay1** [musescore/MuseScore#16285] opened 2023-02-08 23:32 UTC
Describe the bug
The notes D5, Eb4, Eb3, and D3 in the Muse Key Grand Piano play with a "popping/crackling" sound artifact.
I found it issued in December already and it's sad to see that nothing happened since the SF is so beautiful ♥

To Reproduce

Open a new score with Grand Piano using Musesounds
add the following notes D5, Eb4, Eb3, D3. You may add other notes to compare and contrast.
Click play.

Hear that the notes specified in the issue will play with a "popping" sound.

Expected behavior
The aforementioned notes should not have a sound artifact to them when they're played.

Screenshots
Mp4 file of it: https://drive.google.com/file/d/1zKC2XmR9KKffT-Gy3v-pOJFBiu9ViHrc/view?usp=share_link

Platform information
OS: Windows 11, Arch.: x64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

Additional context
The volume of the sound artifacts are also affected by the dynamics of the note. D5's sound artifact is the least audible but is noticeable nonetheless.

**Comment by cbjeukendrup** [comment] 2023-02-09 06:51
Duplicate of #15493. 

@jplay1 Please don't deliberately create duplicate issues. It's very annoying and requires us to spend valuable time that could also have been spent fixing the issue.

**Closed** 2023-02-09 06:52 UTC
