### ISSUE TITLE
[MU4 Issue] UI: Timeline panel's scrollbar is click through

### ISSUE THREAD

**Issue by fp22june** [musescore/MuseScore#13000] opened 2022-08-24 14:15 UTC
(Info added by @cbjeukendrup)

**Steps to reproduce**
1. Open a score with multiple staves (4+ recommended)
2. Open the Timeline, and if necessary, undock it and resize it horizontally, so that the scrollbars become visible
3. Try to move the scrollbars

**Expected:** scrollbar moves, follows mouse, and view scrolls accordingly
**Actual:** not the scrollbar reacts, but the view reacts to mouse press as if the scrollbar doesn't exist

**Additional Context**
Happens in Alpha2

**Comment by cbjeukendrup** [comment] 2022-08-30 12:44
It looks like the first issue can be solved with a reasonably small amount of effort. About the second issue, I'm not sure, I don't understand immediately what's causing that. Maybe I'll find it.

**Comment by cbjeukendrup** [comment] 2022-08-30 13:06
@boryskuzmenko I've pushed a fix for the first issue to the PR. I'm doing a quick attempt to find the cause of the second issue, but it looks like it would take more time than it's worth.

**Comment by boryskuzmenko** [comment] 2022-08-30 15:13
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/13003
Except one small bug which was reported separately https://github.com/musescore/MuseScore/issues/13086

**Closed** 2022-08-30 15:16 UTC
