### ISSUE TITLE
[MU4 Issue] Tuning and velocity settings in Properties>General>Playback not yet working 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#10990] opened 2022-03-30 18:22 UTC
**To Reproduce**
1. Create a score and add some notes
2. Select a note and go to Properties>General>Playback
3. Change tuning and velocity values
4. Play the score and pay attention to the changes

**Expected behavior**
Corresponding changes are applied to the score playback when Tuning and velocity settings have been changed

**Screenshots**

https://user-images.githubusercontent.com/101250347/160904664-c24f9698-5cc2-40d5-89de-aeff70f77d86.mov

**Platform information**
 - OS: [macOS]

**Related issues**
#13503
#13550

**Comment by Tantacrul** [comment] 2022-04-27 11:24
I've moved this to P0 because the velocity setting is relied upon by a decent number of users. More will want this due to the new VSTi feature too. Basically, it is non-functional feature right now, which makes it a P0.

**Comment by DaffodilAura** [comment] 2022-07-28 13:47
This issue also affects scores imported from MuseScore 3, see #12582.

**Comment by MarcSabatella** [comment] 2022-07-28 14:48
It's worth mentioning here that velocity only worked for non-single-note-dynamics instruments in MuseScore 3 (well, as of 3.1 when SND was added).  So, worked for piano, not for winds or strings.  This was a major annoyance for many users.  I gather the new playback MU4 architecture doesn't make this same differentiation between SND and non-SND instruments.  But if all instruments are being treated as SND and using the any of the old SND code paths, that could be why velocity isn't working.  And getting it to work might actually allow it to work for *all* instruments, which would be a nice improvement over MU3.

**Comment by MarcSabatella** [comment] 2022-10-13 15:16
@Tantacrul - not sure if this is one that is already on the short list for beta, but it definitely gets my vote.

FWIW, the velocity setting doesn't work on dynamics either (eg, add a dynamic marking, set its velocity - no effect).  So right now there is essentially no way to customize the playback volume of individual passages beyond what is available with the preset dynamic markings.  Not sure if that's actually a separate issue or not.

**Comment by Tantacrul** [comment] 2022-10-13 17:20
Yeah. Don't worry about this one. It is being worked on right now. Incidentally, we are going to simplify the system from MS3.

For example: 

- The start velocity for notes will not be zero. It'll be 64. Zero makes no sense as a starting point
- We will not provide a dynamic override option. It is a large and unnecessary complication

Bear in mind that this is a baby step towards the new system for setting velocity we will be building soon.

**Comment by MarcSabatella** [comment] 2022-10-13 17:58
Glad to hear it's being worked on!

But - the nice thing about starting from an *offset* of 0 is, you can change the offset to 16 and it means, a little louder than the default, whatever that default is.  Then, even if you change the dynamic marking later - and thus, change the default velocity - those notes would still be a little louder than the default.  So as the most common example, you could write a piece for piano, mark the melody notes +16, and then do whatever you wanted with dynamics later and the melody would always remain slightly louder than the accompaniment.

If there is no more "offset" but only "absolute* velocity settings (which is what I assume you mean in talking about changing the default to 64), this won't be possible anymore.  Whatever velocity you specify for the melody will be locked in and thus end up being wrong if you later change the dynamics.  So for that case at least, it would be perceived as a regression.  But hopefully one that will be addressed by the new system eventually.

**Comment by Tantacrul** [comment] 2022-10-13 18:17
The problem is that it is inconsistent with any other system. A velocity setting of 0 should be silent, unless the sampler in question doesn't support velocity.

To raise velocity for a given dynamic, just raise it from 64 to something higher and it will do so relative to whatever dynamic is set. Velocity isn't volume and shouldn't be used as such. The MS3 system is (really no nice way to say this) just wrong.

So the plan is to set up velocity to work correctly now and then provide automation options to allow volume to be continuously edited over time in later releases. That's the right way to do it.

**Comment by Tantacrul** [comment] 2022-10-13 19:11
If one makes the decision to consider velocity as an 'offset', then it is indeed logical. But since that's not how velocity should be specified and also incomprehensible to anyone familiar with how it should be specified.


MS3 has an option called 'velocity' which is set to zero by default. That's the problem.

**Comment by Tantacrul** [comment] 2022-10-13 19:28
Oh, one other thing: dynamic markings should not have velocity settings that clash with note settings. There should be one global velocity setting. It makes more sense for now to attach them to notes. We'll replace that with a proper system shortly.

The fact that there are competing velocities for dynamics AND note is the cause of the major UX weirdness. We shouldn't honour it at all.

**Closed** 2022-11-02 20:37 UTC
Labels: P0

**Comment by MarcSabatella** [comment] 2022-11-11 05:22
Are we expecting this to be working in Muse Sounds?  It doesn't seem to be.  Should I open a new issue?

**Comment by Tantacrul** [comment] 2022-11-11 09:38
No, Muse Sounds will not yet accept velocity settings from MS4. However, once we get to the system we ultimately want, we'll be able to send velocity and expression.

Tuning will come a little later too.
