### ISSUE TITLE
[MU4 Issue] Audio distorted / slowed down - badly affecting playback

### ISSUE THREAD

**Issue by BoBogus** [musescore/MuseScore#12483] opened 2022-07-20 08:32 UTC
**Describe the bug**
Audio during playback on the Musescore 4 nightly builds is distorted and incredibly slowed down.  It doesn't matter if I'm using a default sound or a VST, the problem remains regardless.

**To Reproduce**
1. Create a new score.
2. Add an instrument (I used a clarinet)
3. Input a note by pressing n on the keyboard and clicking on the staff (I put a note in the first measure)
4. Click play.  Playback should be slow and sound should be distorted.

**Expected behavior**
I expected the playback to be normal.

**Screenshots**

https://user-images.githubusercontent.com/96084585/179935323-5e79a9bf-23ca-439e-9e8c-ec3d069ea7bf.mp4

This video screen capture (done with OBS Studio) shows the distorted audio as well as the slowed-down playback (it takes a bit over a second in real time for the playback time to increase by a tenth of a second).  To see the playback time, you'll need to make the video full screen.

**Platform information**
 - OS: Windows 10 Pro, 64-bit

**Additional context**

**Comment by DmitryArefiev** [comment] 2022-07-20 18:16
@BoBogus I can't reproduce it on Win10 with latest master build

Can add some more details please:

Does it occur only in the latest master build (in previous builds it was fine)?
What audio device for playback you have (internal or external)?

**Comment by BoBogus** [comment] 2022-07-20 20:09
> @BoBogus I can't reproduce it on Win10 with latest master build
> 
> Can add some more details please:
> 
> Does it occur only in the latest master build (in previous builds it was fine)? What audio device for playback you have (internal or external)?


The problem is on all of the master builds I've tried.

I'm using Apple wired earbuds when the problem occurs.  If I switch to the computer's built-in speakers, then there is no audio and playback doesn't advance at all.  If the problem is with the program's default audio API, I have no way to change that (see https://github.com/musescore/MuseScore/issues/12484).

**Comment by Tantacrul** [comment] 2022-07-20 21:44
Can we get a bit more info about your sound card?

**Comment by Tantacrul** [comment] 2022-07-20 21:46
And also (I **seriously** doubt this will work, but let's give it a shot), can you also possibly choose 'Help/Reset configuration'?

Lastly, have you tried options in I/O in preferences?
<img width="883" alt="image" src="https://user-images.githubusercontent.com/21022311/180087909-4f1a4d31-781d-4991-b44a-c8ddbca22796.png">

**Comment by BoBogus** [comment] 2022-07-20 22:23
> Can we get a bit more info about your sound card?

Here are all the audio devices that appear under Device Manager:
![Sound Cards](https://user-images.githubusercontent.com/96084585/180092679-2e324cfe-ed38-4ee7-9343-4103288740d3.png)

**Comment by BoBogus** [comment] 2022-07-20 22:24
> And also (I **seriously** doubt this will work, but let's give it a shot), can you also possibly choose 'Help/Reset configuration'?

Yes, I did try that and got nowhere.

> Lastly, have you tried options in I/O in preferences? <img alt="image" width="883" src="https://user-images.githubusercontent.com/21022311/180087909-4f1a4d31-781d-4991-b44a-c8ddbca22796.png">

Yes.  MIDI input and output obviously did nothing, and even choosing the audio output device did nothing.

**Comment by bakajikara** [comment] 2022-07-21 03:19
I have the same problem. In my case, the problem happens only when I connect wired earphones via USB-C.
I can reproduce it on Windows 11 with the latest nightly build and with the oldest nightly build I can get (which I downloaded from [here](https://github.com/musescore/MuseScore/actions/runs/2205701180)).

When I use the computer's built-in speakers, wireless earphones, or wired earphones via 3.5mm phone connector and start playback, the program crashes, which I logged [here](https://github.com/musescore/MuseScore/issues/12496).

**Comment by GabeS573** [comment] 2022-07-28 01:31
I think this is similar or identical to the issues that I am experiencing, #11222 and #12349.

**Comment by isaac0804** [comment] 2022-07-28 12:55
I had a similar issue when trying Musescore 4 on my windows computer for a long long time. The way I resolve the distorted audio issue is to reduce the sample rate of my output device from 96k to 48k or 44.1k. The audio is much better but still, there is some buzzing occurring. I guess this is because of the resample issue. Hope this discovery can help.

OS: Windows 10
Build version: MuseScoreNightly-202207260456-master-95b68a0-x86_64

**Comment by GabeS573** [comment] 2022-07-29 03:20
> I had a similar issue when trying Musescore 4 on my windows computer for a long long time. The way I resolve the distorted audio issue is to reduce the sample rate of my output device from 96k to 48k or 44.1k. The audio is much better but still, there is some buzzing occurring. I guess this is because of the resample issue. Hope this discovery can help.
> 
> OS: Windows 10 Build version: MuseScoreNightly-202207260456-master-95b68a0-x86_64

Unfortunately, the audio device I'm using only has 48k options, as shown below. Switching between DVD and Studio quality does not fix the issue.

![image](https://user-images.githubusercontent.com/91428485/181675803-52a1b6bf-6e4d-48ab-ac92-e55a57433b4d.png)

**Comment by Tantacrul** [comment] 2022-07-29 15:54
I'm elevating this to a P0, due to the number of machines this is affecting. Thanks to everyone so far for the details you've provided. Anyone else who encounters the same problem, please post similar details here to help us narrow things down.

**Comment by GabeS573** [comment] 2022-07-29 16:19
@isaac0804 When you switch to a 48k sample rate, does your audio sound like the second half of the recording in #11222 (only slightly slower than real-time, with popping noises)? My computer ONLY has 48k sample rate options, and while I've never experienced the super slow, distorted sound that @BoBogus did, I always have the slightly slow, popping noise issue. I wonder if the sample rate could be the problem.

**Comment by isaac0804** [comment] 2022-07-29 18:17
Yes, when I switch to 44.1k and 48k sample rate, my audio sound like the second half of the recording in https://github.com/musescore/MuseScore/issues/11222. So far I am also still facing the slightly slow, popping noise issue. This might or might not be caused by the sample rate. But I am sure that changing the sample rate to 96k or higher can cause super slow, distorted audio issue.

**Comment by NinjaNas** [comment] 2022-07-29 19:05
I did some testing on the newest nightly to compare with #11222. (Volume Warning) @Tantacrul @DmitryArefiev 
44k

https://user-images.githubusercontent.com/54213302/181827089-cb4bf201-8555-47ea-aea6-6c2c833add1c.mp4

48k

https://user-images.githubusercontent.com/54213302/181827060-dd605f6d-a5c4-4eea-af2e-22f79c249b2e.mp4

Distortion starts here:

96k

https://user-images.githubusercontent.com/54213302/181827045-12a69f4b-ab53-417f-80e0-b09bfa6ff5d6.mp4



192k

https://user-images.githubusercontent.com/54213302/181827025-d1395c1d-e080-47aa-81d2-32a7c50a2c66.mp4




I am not entirely sure that #10804 was fixed in the new nightly? 192k sounds different (and correct) on the build with #12242
(https://github.com/musescore/MuseScore/actions/runs/2602243717) than the current nightly.

https://user-images.githubusercontent.com/54213302/181824346-63c5b6e5-b2e5-4d5a-8d04-e19d666023cc.mp4

**Comment by cbjeukendrup** [comment] 2022-07-29 19:09
I think we can finally draw the conclusion that the following issues are the same problem:
- #11190
- #11222
- #12349
- #12483 (this issue)

I can now reproduce this on my virtual Windows machine. To summarize, the experience is the following:
the higher the sample rate, 
- the slower the playback (ranging from a barely noticeable slowdown at 48kHz to almost no progression at 192kHz)
- the worse the distortion (ranging from some small lag and popping noises to almost ear-splitting at 192kHz)

(I also noticed that switching the sample rate while MuseScore is running makes playback totally non-functional, but restarting MuseScore fixes it. I think there is already an open PR to fix that.)

**Comment by vpereverzev** [comment] 2022-07-29 20:01
then I have good news for you folks. I'm about to fix [this](https://github.com/musescore/MuseScore/issues/12349) issue, so that I'll reach you guys with request to test some builds

**Closed** 2022-11-23 11:08 UTC
Labels: needs info, P0, needs testing

**Comment by GabeS573** [comment] 2022-11-26 20:00
This issue seems to have reappeared in the new build shared on Discord yesterday. See https://github.com/musescore/MuseScore/issues/14760
