### ISSUE TITLE
[MU4 Issue] MuseScore 4 Application crashes after startup

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14909] opened 2022-12-03 03:44 UTC
So I've recently updated the Muse Sounds and Muse Plugins within the Muse Hub. I then tried opening up a MuseScore file just to hear a big difference, but when I tried to open it, the application crashes. It similarly happens whenever I just open up the application itself.

Is there any way I can fix this huge bug, or will it possibly might not be fixed at all?

**Comment by MarcSabatella** [comment] 2022-12-03 04:27
You need to update MuseScore to the latest build also

**Comment by cbjeukendrup** [comment] 2022-12-03 08:08
Duplicate of #14907. This is due to an incompatibility between the latest Muse Sounds and the version of MuseScore provided by Muse Hub. In the latest nightly build, this problem should be solved already, and very soon a new build of MuseScore will be uploaded to Muse Hub.

**Comment by MarcSabatella** [comment] 2022-12-03 13:56
Muse Sounds work fine in the most recent nightly.  Previously nightly builds have worked fine with Muse Sounds too.

**Closed** 2022-12-06 13:09 UTC
