### ISSUE TITLE
[MU4 Issue] Virtual Keyboard should remember the zoom setting

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#15209] opened 2022-12-16 00:19 UTC
If you hit "p" 
then use CTR + Scroll to zoom out
in order for all 88 keys to fit on the screen,

![1](https://user-images.githubusercontent.com/78870770/207993869-b27a6141-0282-4b1e-83de-d56ca5c97066.JPG)

this zoom setting is not being saved
when toggling "p",
which I think it should.

after toggling "p":

![2](https://user-images.githubusercontent.com/78870770/207993911-2c4e1fe3-0532-46fb-aa97-8005810463e1.JPG)

**Comment by oMrSmith** [comment] 2022-12-16 11:41
Well it does not even remember its size while the program remains running.

**Comment by abariska** [comment] 2022-12-16 16:14
Duplicate of https://github.com/musescore/MuseScore/issues/13883

**Closed by abariska** 2022-12-16 16:14 UTC
