### ISSUE TITLE
Pitch shift on score for electric bass locks tab (prevents moving tabbed notes to alternate string)

### ISSUE THREAD

**Issue by chipshorter** [musescore/MuseScore#19012] opened 2023-08-10 20:05 UTC
### Issue type

UI bug

### Bug description

I have a score for Electric Bass (EADG) instrument that is pitched up 1 octave (8va alta). The tab is automatically pitched up 1 octave too, however it's then no longer possible to move notes to another string. For example one note shown at position 7 on the G string in the tab, but I want it to be tabbed as position 12 on the D string. Normally I'd just drag the note on the tab, but it seems the act of raising the pitch has "locked" the tab and I'm unable to drag it.

### Steps to reproduce

1. Create a score for Electric Bass instrument 
2. Add a few notes
3. Add a linked score (TAB common)
4. Pitch shift the entire score by using the 8va alta option from the pitch palette 
5. Try dragging some of the tabbed notes to higher/lower string

### MuseScore Version

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS 12.6,

**Comment by zacjansheski** [comment] 2023-08-11 14:32
This is a duplicate of https://github.com/musescore/MuseScore/issues/14218

We will refer to that issue log, thank you!

**Closed by zacjansheski** 2023-08-11 14:32 UTC
Labels: UI
