### ISSUE TITLE
[MU4 Issue] Muse Hub - Unable to check for updates

### ISSUE THREAD

**Issue by MalignantCarp** [musescore/MuseScore#14975] opened 2022-12-06 05:50 UTC
**Describe the bug**
So it would appear the update button inside Muse Hub doesn't seem to work for me. I'm not sure if this is due to it using svchost.exe or some other intermediary to access the Internet; I do have both the Muse.exe and Muse.Service.exe full access through my Firewall, so unless it's using some sort of intermediary that is blocked, it should have full access.

**To Reproduce**
1. Run Muse Hub
2. Click on the gear
3. Click updates
4. Receive error "Unable to check for updates: Please make sure your device is connected to the internet."

**Expected behavior**
Muse Hub should check for updates.

**Platform information**
Muse Hub v 0.9.10.559_x64
Windows 10 Pro 64 Bit, Version 21H2 Build 19044.2251.

**Additional context**
I had to uninstall the previous Muse Hub to install the new one (it threw an error when it tried to install over top of the old one), but this was an error I was receiving with the previous version, 0.9.9.515.

**Comment by DominicMaas** [comment] 2022-12-06 17:30
Do you know what error it threw when you tried to install over the old one? This should be supported (although Hub will crash on first startup).

Are you running a VPN by any chance? Or are your network settings set to limited?

**Comment by MalignantCarp** [comment] 2022-12-07 06:50
If memory serves, the error had indicated that it was unable to install the package because a previous version was already installed. I could be misremembering, but I am fairly certain it was something along those lines. I checked the Windows logs and while it does have log entries for the WindowsAppRuntime Installer, unfortunately there is no content to the logs to indicate what went on.

No, no VPN here. Connection is not limited. I should mention, as I believe was mentioned in my other report, with the previous version, the only thing that didn't work was the updater. I successfully downloaded MuseScore (though it didn't install MuseSampler) and Muse Sounds with the previous version, but it failed to check for updates. I allow full network access for both Muse.exe and Muse.Service.exe, so it shouldn't have any issues. The service log file doesn't indicate any issue, it just reports no update is found.

So, for example, the service_log would show this:

-12-05 22:37:21.0607|INFO|Muse.Service.Services.WindowsMuseHubManager|Checking if Muse Hub has any pending updates (current version is 0.9.10.559)...
2022-12-05 22:37:21.0895|INFO|Muse.Service.Services.WindowsMuseHubManager|Found no pending Muse Hub updates!

the client_log would show this:
2022-12-05 22:37:57.6130|INFO|Muse.Client.Common.Services.UpdateManager|Checking for updates...
2022-12-05 22:37:57.6130|INFO|Muse.Client.Common.Services.UpdateManager|Unable to check for updates, as this device is not connected to the internet
2022-12-05 22:37:57.6130|INFO|Muse.Services.WindowsDialogService|Displaying Alert: Unable to check for updates | Please make sure your device is connected to the internet

Unfortunately, I can't seem to get Muse Hub to run tonight at all to see if I can pinpoint any other issue, so I will have to play around with it when I have more time.

**Comment by DominicMaas** [comment] 2022-12-07 18:32
With the new version, I'm using the same "Internet check" code that was used for the updater in the main application content now (which should explain why the updater didn't work for you before, and now both the updater and content do not work). Muse Sampler (should) be installed at the same time you download your first sound/library.

The service log entry is a bit misleading, it's simply checking if another newer version of Muse Hub is installed on the system. The installer runs while Muse Hub is running, and stages the package ready for the user to manually apply the update. Either by restarting their PC, or clicking the "Update" button that appears in Hub.

I'm looking into other methods of doing this instead of using the current internet check API (which isn't super reliable, as in this case, and others reported across the internet) which should fix the problem.

---

How is Muse Hub not running? Does the client not launch at all? Or does it complain about the background service not running?

**Comment by MalignantCarp** [comment] 2022-12-07 19:07
The client wouldn't launch at all. No error messages of any kind. Once I get home tonight I will see if there is anything in the Windows log that might lend a clue as to what the issue is, assuming it hasn't resolved itself in the meantime.

**Comment by MalignantCarp** [comment] 2022-12-08 03:32
> How is Muse Hub not running? Does the client not launch at all? Or does it complain about the background service not running?

Posted a new bug report, as there is an unhandled exception showing in the Windows log. #15032.

**Comment by MalignantCarp** [comment] 2022-12-09 00:16
So, a long time ago I had an issue with the Kindle Reader app not being able to access the network, and it had to do with having the VirtualBox Host-Only Network enabled (once it was disabled, it magically had Internet access; I'm guessing it was trying to use it instead of the proper Ethernet adapter, but who knows?).

I recently installed a new version of VirtualBox and it seems it re-enabled the controller, so once we can get Muse Hub running again past that .NET Runtime Error, I will see if disabling that Host-Only Network fixes this issue.

**Comment by MalignantCarp** [comment] 2022-12-09 00:33
Okay, so if you want to pinpoint this bug, I recommend installing VirtualBox with the VirtualBox Host-Only Network installed. Disabling it seems to make it able to find updates and everything.

**Comment by DominicMaas** [comment] 2022-12-09 00:39
I think I know why, for some reason it's checking the virtual network adapter instead of the one that is actually connected to the internet. 

I'll have to loop through all connected network adapters and make sure at least one has internet access. 

Thanks for finding the root cause.

**Comment by MalignantCarp** [comment] 2022-12-09 00:41
Is there no primary network that could indicate which one to use?

**Comment by DominicMaas** [comment] 2022-12-09 00:43
It's meant to check the default network adapter, but looking online, others have had issues when it just doesn't do that sometimes. 

I believe you can set the default within the old network adapter settings within control panel.

**Comment by DominicMaas** [comment] 2022-12-14 05:36
This should now be fixed in the latest version of Muse Hub (v0.9.12)

**Comment by oktophonie** [comment] 2023-02-22 17:07
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.

**Closed by oktophonie** 2023-02-22 17:07 UTC
Labels: P1
