### ISSUE TITLE
Synths don't work with Musescore Studio 4.3

### ISSUE THREAD

**Issue by Beniegenie** [musescore/MuseScore#22829] opened 2024-05-14 19:56 UTC
### Issue type

General playback bug

### Bug description

When a synth is used, it sounds like a piano

### Steps to reproduce

Go to MuseScore Studio
Open any score that has a synth or create one with a synth
Write any notes

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 11

### Additional context

This worked perfectly fine before MS 4.3

**Comment by DaddyLudwig** [comment] 2024-05-14 20:42
Duplicate of https://github.com/musescore/MuseScore/issues/22757 and will be fixed in 4.3.1 once https://github.com/musescore/MuseScore/pull/22793 is ported

**Comment by Beniegenie** [comment] 2024-05-14 21:24
How do I get to the issues that other people have posted so that I don't keep making duplicates?

**Comment by MarcSabatella** [comment] 2024-05-14 21:31
See the search box at the top of the main Issues page.  By default it will only search open issues, but remove the pre-filled "is:open" text to search closed issues also.

**Closed** 2024-05-14 21:32 UTC
Labels: duplicate, regression, playback
