### ISSUE TITLE
[MU4 Issue] unable to specify fretless electric bass sound

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12770] opened 2022-08-10 21:44 UTC
**Describe the bug**
Although fretless electric bass is listed as an instrument, it does not play using the fretless sound, and no facility is provided to use this sound

**To Reproduce**
1. Create new score
2. Choose Fretless Electric Bass instrumentt
3. Add some notes
4. Play

**Result**

Playback uses a standard fretted electric bass sound

**Expected behavior**

Playback should use the fretless sound

**Platform information**
 - OS: Linux

**Additional context**
This should work right out of the box upon selecting the Fretless Electric Bass instrument, independently of any concern over how one might choose between sounds in the mixer, since a fretless bass *is* a different instrument from a fretted one in a real sense.  But, I do note again, the inability to select sounds in the mixer is by far the single biggest regression in all of MU4 to my mind.  If you add an electric bass, there no way to choose from the various different bass sounds in your SoundFont (eg, picked vs fingered vs slapped).  And picked bass is *not* a different instrument from fingered bass, so it's silly to try to solve this by listing them as separate instrument.

**Comment by Tantacrul** [comment] 2022-08-16 17:52
Confirmed. **Fretless Electric Bass** is simply mapped to the wrong sound. We must have missed it. The sound is **Fretless bass** according to MuseScore 3. Not checked in the soundfont editor (because I haven't got it installed on the machine I'm using right now)

**Comment by MarcSabatella** [comment] 2022-09-30 00:19
FWIW, this is the sound used in my MuseScore Cafe theme music, would be nice to have this working before I try demoing playback.

**Closed** 2022-10-01 18:47 UTC
Labels: P2
