### ISSUE TITLE
Can't change the size of "Segno" and "Coda" symbols

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#24873] opened 2024-09-22 17:22 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. open a score;
2. add a Segno or Coda symbol from "Repeats & Jumps"palette;
3. change size of the symbols via Properties panel.
Expected behaviour: symbols' size changes.
Actual behaviour: nothing happens.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/467324c4-3a64-40cb-928e-eed3dfd237e7

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 10 Pro

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-09-23 02:28
The way to do this has changed.  Since these are symbols placed within text, they don't longer scale with the font size itself, but with the "Musical symbols scale" setting in the text style (see Format / Style / Text style, the repeat left/right styles).

**Comment by oktophonie** [comment] 2024-09-23 05:20
By design, and duplicate of https://github.com/musescore/MuseScore/issues/24330

**Closed by oktophonie** 2024-09-23 05:20 UTC
Labels: by design, UX/interaction

**Comment by FrancRos31** [comment] 2024-09-23 10:36
I understand, but why though the size value in the property panel is still modifiable? Are you thinking of changing it or deleting completely?

![3](https://github.com/user-attachments/assets/2a8e81d4-1e36-49c3-8e55-2459487ca009)

**Comment by oktophonie** [comment] 2024-09-23 11:25
No - text items can contain music symbols from the music font (which are controlled via 'Musical symbols scale'), and also normal text (which is controlled by the font size setting in Style > Text styles for the relevant style, or can also be controlled via Properties, as in your image). What's perhaps missing at the moment is a new setting in Properties to override the Musical symbols scale for a specific item only.
