### ISSUE TITLE
Allow techniques to be assigned to specific voices

### ISSUE THREAD

**Issue by rustykitty** [musescore/MuseScore#25873] opened 2024-12-18 01:07 UTC
### Your idea

Sound flags/playing technique annotations should be able to be applied to specific voices instead of the whole staff.
In MuseScore 3, we had the ability to change one or more voices to a specific channel: (from 3.6.2)
<img width="1066" alt="Screenshot 2024-12-17 at 4 56 37 PM" src="https://github.com/user-attachments/assets/73a1b586-aeab-4a8e-adad-f68a22c09242" />

In MuseScore 4, that ability is now gone, at least on Muse Sounds. 

### Problem to be solved

There exists music where there is pizz. and arco on the same staff happening at the same time; for an example, look at the beginning of Stravinsky's *The Firebird*: 
<img width="733" alt="image" src="https://github.com/user-attachments/assets/2fbcb8ec-7cb2-4b31-a7a7-a2eebc436922" />

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-12-18 07:04
Duplicate of https://github.com/musescore/MuseScore/issues/23368

**Closed by oktophonie** 2024-12-18 07:04 UTC
Labels: feature request
