### ISSUE TITLE
 irregular values crash Musescore, triplets, duplets etc. Urgent!

### ISSUE THREAD

**Issue by Accis94** [musescore/MuseScore#18700] opened 2023-07-19 13:39 UTC
### Issue type

Crash or freeze

### Bug description

the moment I choose an irregular value such like triplet, the program crashes and closes down 

### Steps to reproduce

1. select any note, group of notes, or an empty  measure
2. set triplet in irregular valor

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139983630/4ef969db-bff7-4064-a841-639a78fd5935

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by RomanPudashkin** [comment] 2023-07-19 13:47
It's a duplicate of https://github.com/musescore/MuseScore/issues/18595 and will be fixed in 4.1.1 (which will be released soon). if this crash is blocking your work, you can get 4.1.1 (the latest nightly) here:
https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D

**Comment by Accis94** [comment] 2023-07-19 13:47
The problem only happens using TAB for guitar!

**Closed by RomanPudashkin** 2023-07-19 13:47 UTC
Labels: duplicate, regression, crash
