### ISSUE TITLE
Engraved slurs and fingerings overlap

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#23259] opened 2024-06-15 17:40 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Not sure if technically a bug per se, but it would be an improvement if the default engraving rules respected the aesthetic spacing between slurs and fingerings.  (See attached examples of original score vs. default MuseScore rendering).

### Steps to reproduce

See pictures below

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137847641/7242829a-4361-48b7-ae4a-1a0bbbd7b658)

![image](https://github.com/musescore/MuseScore/assets/137847641/d0d1034e-55a6-453c-b0bb-b3110b1fe934)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by oktophonie** [comment] 2024-06-15 17:45
Duplicate of https://github.com/musescore/MuseScore/issues/15336

**Closed by oktophonie** 2024-06-15 17:45 UTC
Labels: engraving
