### ISSUE TITLE
[MU4 Issue] Muse Sounds accents have a minimum time to play back, causing slowdown and the instrument falling behind temporarily

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14104] opened 2022-10-27 15:47 UTC
**Describe the bug**
Accents in Muse Sounds have a minimum time to play back, so if there are faster accented notes, the playback will get behind temporarily before catching up

**To Reproduce**
1. Create a new score with Muse Sounds
2. Create a passage with fast accented notes
3. Hear that the playback gets behind from the accents

**Expected behavior**
Accents should not slow down the playback

**Screenshots**
<img width="357" alt="Screen Shot 2022-10-27 at 9 46 48 AM" src="https://user-images.githubusercontent.com/21023353/198337251-19cfe244-b522-43c6-87eb-6313c32e6019.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by erinic04** [comment] 2022-10-30 20:29
Also I just realized that this might just be the triplets being broken, not necessarily the accents. Quarter note triplets with the same repeated notes are just extremely broken right now.

**Comment by bkunda** [comment] 2022-12-07 13:29
I agree that there seems to be a problem with some instruments "falling behind" temporarily – likely caused by the amount of time it takes each note to sound properly – and I have thus made some comments about this in a separate, and more applicable issue (see #14051).

I don't, however, think the issue outlined here is necessarily connected to accents, nor tuplets for that matter. There are other issues with accents that I will raise separately. So @erinic04 unless I've missed something (and if I have, it would be helpful if you could supply more info, including video/audio examples), I think it's possibly safe to close this issue for now.

**Closed** 2022-12-07 13:30 UTC
Labels: P2

**Comment by LuisLiszt** [comment] 2022-12-09 14:07
For me MuseKeys doesn't play the accents at all...

**Comment by MarcSabatella** [comment] 2022-12-09 14:14
I think you're right, but that's an unrelated issue, best to open a new one.

**Comment by LuisLiszt** [comment] 2022-12-09 14:45
@MarcSabatella Oh, I didn't create a new issue because I thought it was an obvious problem and it's already being worked on. If that's not the case, I can create a new issue later!
