### ISSUE TITLE
[MU4 Issue] Capo setting in Staff Text ignored in playback

### ISSUE THREAD

**Issue by GeertWil** [musescore/MuseScore#14856] opened 2022-11-30 19:22 UTC
I want to play guitar while playing back my score. I use a capo, so I followed the MU3-handbook that tells me to add staff text and change the capo setting in the staff text properties. First of all the option has a greyed out look like described in #13361, but it is possible to change the setting. The playback pitch is not affected by the changed settings.

**To Reproduce**
1. Select the first note in a score.
2. Add Staff Text like "Capo fret 2"
3. Go to Staff text settings and click on the option Capo settings. (The option is quite grey, but it is possible to change the settings)
4. Check Capo setting and select a fret.
5. Play back the score. The pitch is unchanged.

**Expected behavior**
If for example fret 2 is selected, the score should sound 2 semitones higher than the original.

**Platform information**
Windows. Latest nightly build of MU4.

**Comment by MarcSabatella** [comment] 2022-11-30 19:40
See also https://github.com/musescore/MuseScore/issues/11631

**Comment by GeertWil** [comment] 2022-11-30 19:51
Hi Marc

 �

My issue is a duplicate of yours. 

I hope this will be fixed in version 4.0. For fingerstyle guitarists, this is an important option.

 �

**Comment by RomanPudashkin** [comment] 2022-12-20 09:05
Duplicate of https://github.com/musescore/MuseScore/issues/11631

**Closed by RomanPudashkin** 2022-12-20 09:05 UTC
