### ISSUE TITLE
Justifying system text with rehearsal marks.

### ISSUE THREAD

**Issue by ayyydoc** [musescore/MuseScore#23986] opened 2024-08-11 23:47 UTC
### Your idea

When you have to write system text next to a rehearsal marking, I would love it if the text automatically aligned to each other instead of having to drag the text in the score and each part manually

### Problem to be solved

This would solve inconsistencies in my engraving where sometimes text will be aligned a little differently because I'm eyeballing it. It would also speed up my workflow immensely!

### Prior art

I haven't run into this problem with any other software.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-08-12 06:23
Duplicate of https://github.com/musescore/MuseScore/issues/16891

**Closed by oktophonie** 2024-08-12 06:23 UTC
Labels: feature request
