### ISSUE TITLE
[MU4 Issue] Custom palette acting weird and broke MS4

### ISSUE THREAD

**Issue by Skelbti** [musescore/MuseScore#16053] opened 2023-01-24 21:19 UTC
**Describe the bug**
After creating a custom palette with several symbols I use frequently and placing the palettes on the right side of the screen, the symbols were abnormally large and popped out of their cells. I closed and reopened MS to get a stranger result (_cf._ screeshot)

**To Reproduce**
1. Create a custom palette ;
2. Add some symbol ;
3. Hide and open custom palette ;
4. See error ;
5. Quit MS ;
6. Reopen MS ;
7. See error ;

**Expected behavior**
Create a custom palette and add symbols that behave as in their original palette (good size and visibility).

**Screenshots**
![image](https://user-images.githubusercontent.com/86026713/214418472-f585c995-1253-4a81-8501-5032063a8290.png)

**Platform information**
 - OS: Windows 11

**Additional context**
Palette dock on the right side of the screen.

**Edit: MuseScore is completely broken!**

After submitting this issue, I tried to reset the whole workspace to default but nothing works! I tried to open the master palette to see if the behavior was similar but MS crashes every time. I think I have to reinstall the software completely.
![MuseScore4_cZesLPYzsg](https://user-images.githubusercontent.com/86026713/214423391-a37db6c8-3185-471f-8817-927887af8c71.gif)

When I go to preferences > advanced, the value of `application/paletteScale` is set to `0` instead of `1`. I tried to set it to 1, but nothing changes. If I reopen the advanced preferences the value is still `0`.

I was able to return to normal behavior by setting the value to `2` where I got the symbols large but visible. I then set the value back to `1` and everything seems to be back to normal. However, if I quit and restart MuseScore 4, I come back with the same symbol display error!

**Comment by Skelbti** [comment] 2023-01-24 21:22
It's even worse after resetting the palette to try to recreate the custom palette again:

![MuseScore4_RiAKVCAd6I](https://user-images.githubusercontent.com/86026713/214419189-310645a0-28c8-4c43-828d-bafe390d4fb5.gif)

**Comment by cbjeukendrup** [comment] 2023-07-05 18:28
This looks like a duplicate of https://github.com/musescore/MuseScore/issues/15322, which has been fixed. Could you please check if this still happens in the latest nightly build of MuseScore 4.1? https://musescore.org/en/nightly-builds

**Comment by cbjeukendrup** [comment] 2023-07-09 14:02
That's good to hear! Then I'll close this issue.

**Closed** 2023-07-09 14:03 UTC
Labels: needs info
