### ISSUE TITLE
[MU4 Task] Repeat last bar not executed

### ISSUE THREAD

**Issue by mikosax21** [musescore/MuseScore#14234] opened 2022-11-01 09:34 UTC
In version 4 beta and in the last nightly I downloaded, the 'repeat last bar', 'repeat last 2 bars', etc. signs are not executed. For the 'repeat last measure' sign, this is a regression compared to version 3.6.2

**Comment by Tantacrul** [comment] 2022-11-01 18:02
Oh man. These have stopped working again? Yeah. Just checked on the latest nightly.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/21022311/199305456-4778231b-e49d-4190-a811-3eb4ded44fc8.png">

**Comment by MarcSabatella** [comment] 2022-11-01 18:53
The PR implementing the fix was never merged as far as I know; I don't believe these have worked at all in the past year or so.  As per https://github.com/musescore/MuseScore/issues/10922, it seems there were performance issues with the proposed solution.

**Comment by Tantacrul** [comment] 2022-11-01 21:27
I had a chat with the team. We didn't want to try fixing the multi-measure repeats for 4.0 but I don't think we can release without repeat last bar working. This was just an oversight but I'm glad we caught it. I think a lot of users would be quite upset.

**Comment by Tantacrul** [comment] 2022-11-01 21:28
I don't think there was a 'repeat last 2' or 'repeat last 4' symbol which actually worked in MS3. Correct? It was just **repeat last bar**

**Comment by jeetee** [comment] 2022-11-01 21:32
> I don't think there was a 'repeat last 2' or 'repeat last 4' symbol which actually played back correctly in MS3. Right? It was just **repeat last bar**?

Correct

**Comment by MarcSabatella** [comment] 2022-11-01 21:33
Correct.  It will be very disappointing because this was actually one of the first things implemented for MuseScore 4 and it was working great and many people were looking forward to it.  So it will seem almost like a regression in that sense, but technically, it isn’t.  Having the symbols work for display (as they already do) will still be very welcome though, and the standard workaround of adding an invisible playback staff will tide people over.

**Comment by mikosax21** [comment] 2022-11-01 22:39
To complete :
* repeats 2 and 4 did not work in MS3, indeed.
* The last bar repeat did not work in the 4 Alpha version.

**Closed** 2022-11-09 08:31 UTC
Labels: P0
