### ISSUE TITLE
MuseScore Studio won't recognize workspace customizations (or workspace files).

### ISSUE THREAD

**Issue by ChriiMoral** [musescore/MuseScore#23137] opened 2024-06-07 15:00 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

MuseScore would always remember the layout changes made on a custom workspace. You could find the workspace file and save it elsewhere for backup too.

None of these are the case at the time. Every time I load up MuseScore Studio, the pallets layout, where I've pinned the Properties pane, whatever customizations done to the workspace are undone.

The correct workspace is selected (see screenshot). Changing to the default and then back, does not restore my customizations.

![Screenshot 2024-06-07 at 10 52 40 AM](https://github.com/musescore/MuseScore/assets/63615949/449f5dda-153b-4a9e-9456-de4f179bff7f)

### Steps to reproduce

1. Create a file on MuseScore Studio.
2. Customize the workspace layout.
3. Save the workspace with a unique name.
4. Save file and exit MuseScore Studio.
5. Open MuseScore Studio once more.
6. Either create a new file, or open the recently created file.

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.1-241490902, revision: github-musescore-musescore-026c26b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.3

### Additional context

OS: macOS 14.3, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241490902, revision: github-musescore-musescore-026c26b

**Comment by MarcSabatella** [comment] 2024-06-07 15:10
Do you but chance have multiple instances of MuseScore Studio running when you do this?  if so, customizations in one may be overriding those in another.  In general, though, it should work to create and customize workspaces and have this persist, and does for me.

**Comment by ChriiMoral** [comment] 2024-06-07 15:11
That’s odd. No, I only have one version installed.

**Comment by MarcSabatella** [comment] 2024-06-07 15:21
Sorry, I don’t mean different *installations*, I mean difference *running instances*.  As in, do you have two or more scores open in different windows?  Each is a separate “instance” of MuseScore, and customizations made in one can clobber those made in another.

If you have ensured you have only one instance running while making your customizations and then closing MuseScore Studio,. It could indicate a permissions problem.  Your workspace files should normally be saved to a special hidden folder; I don’t know how to find it on macOS but in Windows it would be under AppData, so maybe you can find the equivalent on your system

**Comment by ChriiMoral** [comment] 2024-06-07 15:25
My bad. I miss read. You did say instance.

Still no. I only work on one file at at time.

I think I know where the workspace file is stored. I believe I found the location for macOS on the handbook. If I find it, I’ll add it here.

But either way, I’m running more than one instance, so I don’t know what could it be.

Let me know if there's any more information you need, to see what I can find (besides the location of the workspace file 🤭).

**Comment by MarcSabatella** [comment] 2024-06-07 15:29
Once you find that location, check that you have proper permissions to write to that folder.

Also, it could be MuseScore Studio is crashing on exit and that is preventing the file from being written.  Try changing workspaces before quitting, which should also force the workspace file to be written.  Then see if after restarting, the workspace is available to deselect and contains your changes.

Also, in the future, better to first ask for help tracking down problems like this on the support forum.  The if something is confirmed to be a bug, it can be reported here.

**Comment by MarcSabatella** [comment] 2024-06-07 15:32
OK with me, but it’s possible someone else may choose to close it until such a timer as a bug is confirmed.

**Comment by ChriiMoral** [comment] 2024-06-07 15:33
No problem. Thanks again for your help so far!

**Comment by ChriiMoral** [comment] 2024-06-07 15:47
> Also, it could be MuseScore Studio is crashing on exit and that is preventing the file from being written.  Try changing workspaces before quitting, which should also force the workspace file to be written.  Then see if after restarting, the workspace is available to deselect and contains your changes.

Yes, I haven't noticed, but MuseScore crashes when I close a file.

**Comment by MarcSabatella** [comment] 2024-06-07 16:02
In that case, the workspace issue is probably just a side effect of the crash.  See https://github.com/musescore/MuseScore/issues/21252 For more on a known issue with crash on exit on macOS on some systems; then you can see if your crash seems to be the same.

Did the suggest to change workspaces first work?  If so, then I think this issue can probably be closed as a duplicate of the existing crash-on-exit issue, unless your crash log shows yours is different.

**Comment by ChriiMoral** [comment] 2024-06-07 16:04
It did actually! I think it should be closed. Thanks again.

**Closed** 2024-06-07 17:28 UTC
Labels: UI, regression
