### ISSUE TITLE
[MU4 Issue] Chord symbols: When a Measure is Selected, Can't turn off playback from cog icon

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14616] opened 2022-11-20 11:44 UTC
**Describe the bug**

At least for MS3 imported files, the "Play chord symbols" indication in the playback controls menu frequently does not reflect the _actual_ playback state of chord symbols in the score.

**To Reproduce**

1. See @MarcSabatella's comment below (Edit @Tantacrul)

**Expected behavior**

Playback / muting of chord symbols should always match the state of "Play chord symbols".

**Platform information**

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223240408, revision: github-musescore-musescore-56b4855

**Comment by Tantacrul** [comment] 2022-11-22 16:47
I can't reproduce this issue. For me the on/off settings work as expected (MacOS).

I'll ask around to see if anyone else is experiencing this. Thanks!

**Comment by MarcSabatella** [comment] 2022-11-23 01:41
@Tantacrul - I can now reproduce this.  The differentiator is whether you use the select-a-measure-to-solo function or not.  If you do, chord symbol playback is forced on regardless of the toolbar, and then it remains on even if you restart playback by clicking a note instead of a measure.  That's the short summary.  If you want detailed steps, here they are:

First, create a new score, Treble Clef template, and add some chord symbols.  Now, check the mixer, and the toolbar.  For me at least, the mixer says chord symbols are not muted, but the toolbar says they are disabled, which is already wrong.

Next, click the rest in the first bar and play the score from the beginning - the chord symbols play.  So the mixer is right; the toolbar is wrong.

Now try toggling the option on via the toolbar.  The mixer still says not muted, so now it and the toolbar agree that the chords should play - and they do in fact play.

Now, turn chord symbols off via the toolbar.  The mixer shows the mute button is disabled, so now the toolbar and mixer agree they shouldn't play.

Here is where it gets interesting.  Click a note or rest and start playback.  The chords don't play, which is correct.  But now, select a *measure*.  Suddenly, the mixer mute button re-enables, and shows "not muted".  So now we're back to where we started - the mixer and toolbar disagree again, and the mixer is right - the chords now play.  Selecting the measure should clearly not have done this, but it did.

You can repeat this cycle as much as you want.  Every time you select a measure, chord symbols get forced back on via the mixer, regardless of the state of the toolbar.

**Comment by Tantacrul** [comment] 2022-11-23 11:22
Thanks @MarcSabatella ! I've updated the title to reflect this.

**Comment by RomanPudashkin** [comment] 2022-12-09 11:36
fixed in https://github.com/musescore/MuseScore/pull/14948

@rgreen5 @MarcSabatella could you please confirm using the latest nightly build?
https://ftp.osuosl.org/pub/musescore-nightlies/

**Comment by MarcSabatella** [comment] 2022-12-09 14:27
Seems good!

One minor glitch not worth worrying about right now, but could be looked at post-release: while turning off chord symbol playback via the cog normally disables the mute button for all chord symbol channels in the mixer (which is good), it actually doesn't do this for any chord symbol channels that are already muted.  I think it's harmless, because either way, the chord symbol isn't going to play (and doesn't).  And actually, if you then press the mute button to turn off the mute, it turns off, *and* the button then disables itself, so all is as it should.  So it's really just a minor UI inconsistency that the mute button doesn't disable itself automatically in this case.

**Closed** 2022-12-12 13:14 UTC
Labels: P1
