### ISSUE TITLE
A slur denoting a long-lasting sound

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20495] opened 2023-12-14 19:53 UTC
### Your idea

I suggest adding a slur to the palette, which prescribes a long-lasting note

### Problem to be solved

This will help musicians identify those notes that sound long

### Prior art

In the Finale music editor, this slur looks like this:
![Снимок экрана (82)](https://github.com/musescore/MuseScore/assets/134041121/3e3f8cda-5c08-4667-8949-4cd6aea06e54)
![Снимок экрана (83)](https://github.com/musescore/MuseScore/assets/134041121/9aa6822e-4668-4eeb-aac1-c287d325cfce)
![Снимок экрана (84)](https://github.com/musescore/MuseScore/assets/134041121/40fc4689-ea3d-490b-80a9-bb13a791cbe4)

**Comment by oktophonie** [comment] 2023-12-14 21:53
Effective duplicate of https://github.com/musescore/MuseScore/issues/16726

**Closed by oktophonie** 2023-12-14 21:53 UTC
Labels: feature request
