### ISSUE TITLE
Create Linked Staffs for Divisi view

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#20820] opened 2024-01-03 15:33 UTC
### Your idea

I often work with pop-choral music involving 
- multiple voices or 
- monophonic chords in Voice 1 
... per staff.

For practicing and also the creation of different part scores for "merged" and "divisi", it would be really helpful to have the opportunity to dynamically merge or divide staffs, so that they are just different views of the same original data (and not copies). 

I think, therefore the `Linked Staff` and also the `Explode`-functionality (which is a great but still quite cumbersome feature) will really come in handy, even though they need some overhaul then.

### Problem to be solved

No copies of same data anymore, but instead merged/divisi view for the same data. Changes that are implemented in one place and will then automatically update in the other views.

### Prior art

- `Linked Staffs` are available, but only with quite limited capabilities, such as different clef (transposing instruments are not available here neither, which would be a good thing to add as well).
- you could create a Linked Staff to make a dynamic duplicate of a staff, then create a part score and under `Instruments`-Tab uncheck "Voice 2" for the first and "Voice 1" for the second linked staff -> unfortunately this does not fill the gaps, where the original staff is unisono and also does not work with monophonic chords (stacked notes in Voice 1).
 
- `Explode`/`Implode` are functionalities that this would probably rely on dynamically in the background

### Additional context

It should be noted that there are the two ways for having multiple notes in one staff: monophonic chords and polyphonic voices. Sometimes it is desired to switch between, what is most desireable:
- having one sub-staff for the main part and the other just for aditional notes leaving gaps for the rest (similar to `explode on multi-voice-staffs` but extended to chords as well -> wherever there are multiple notes stacked on top of each other)
- fill those gaps with a copy of the other voice's notes (similar to how `explode on monophonic staffs` with chords)
- also the merged view should feature options to choose, how to handle unison, monophony (polyphony is clear): display extra voice (with extra stems/beams) OR merge them into chords where possible

**Comment by oktophonie** [comment] 2024-01-03 17:23
This is essentially a duplicate of https://github.com/musescore/MuseScore/issues/15616

**Closed by oktophonie** 2024-01-03 17:23 UTC
Labels: feature request
