### ISSUE TITLE
[MU4 Issue] Adding a 2nd Alto Sax to a Concert Band Score Displaying the incorrect Key Signature

### ISSUE THREAD

**Issue by XRRacer** [musescore/MuseScore#16538] opened 2023-02-24 17:44 UTC
**Describe the bug**
I created a Concert Band Score in Concert F Major.   I began working by adding music to the transposed score layout.  I decided to add a 2nd Alto Sax player.  I clicked on "Add" in the Instruments Panel and chose Alto Sax.  The Key Signature for the added Alto Part is displayed in Concert C Major (Transposed key signature for Alto was A - 3 sharps).  Since this was not correct, I deleted that part and tried clicking on the Arrow to the left of the original Alto Sax part in the Instrument Panel and chose "Add Staff".  This also created an Alto Sax Part displayed in the wrong key.

If I switch the score to display in "Concert Pitch" I see that 2nd Alto Sax part is now in the key of "Concert C Major" while the rest of the score is in Concert F Major.

**To Reproduce**
1. Go to 'I clicked on "Add" in the Instruments Panel and chose Alto Sax'
2. Double Click on 'Alto Sax to add to the score.'
3. Key Signature was incorrect - Showing transposed as A Major

**Expected behavior**
I expected that the Alto Sax part would be added in the correct key of Concert F Major, Transposed Key - D Major

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
Add any other context about the problem h
![Concert Score Screen Shot with added 2nd Alto](https://user-images.githubusercontent.com/126279201/221250919-88d0b56f-717e-48a1-8cb0-6dfd69cc91a5.png)

![Transposed Score Screen Shot without 2nd Alto](https://user-imag
![Transposed Score Screen Shot with added 2nd Alto](https://user-images.githubusercontent.com/126279201/221250903-35e7bbcf-fc9c-4927-8015-baf0c60666c9.png)

![Concert Score Screen Shot without 2nd Alto](https://user-images.githubusercontent.com/126279201/221250888-ae623991-4071-4a50-ada4-19085f8035a4.png)
es.githubusercontent.com/126279201/221250867-14977295-148a-45ca-b372-90075391d283.png)
ere.
[Test.zip](https://github.com/musescore/MuseScore/files/10827271/Test.zip)

**Comment by oktophonie** [comment] 2023-02-24 17:55
Duplicate of https://github.com/musescore/MuseScore/issues/15314 (and fixed in master, though not 4.0.2 I'm afraid). For now you can work around it just by re-applying the F major key signature.

**Closed by oktophonie** 2023-02-24 17:55 UTC

**Comment by XRRacer** [comment] 2023-02-24 18:34
Okay.  Thank you.
