### ISSUE TITLE
Grace note playback is far too rushed

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18699] opened 2023-07-19 11:42 UTC
### Issue type

General playback bug

### Bug description

Playback of acciaccaturas in MS3 was tolerably good. However, in MS4 (using MS Basic), playback of the same grace notes is far too rushed – to the point that the individual notes are scarcely distinguishable.

### Steps to reproduce

1. Open the attached file in MS3 and MS4. 
[playback_grace_notes.zip](https://github.com/musescore/MuseScore/files/12094511/playback_grace_notes.zip)

2. Compare the playback of acciaccaturas in measures 6 and 8 in both cases.

RESULT: Playback in MS3 is acceptably good. In MS4 the same grace notes have a shorter time to complete playback and sound very rushed. The result is not very musical.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by oktophonie** [comment] 2023-07-19 11:44
State that it's a regression in the body of the report, not the title.

**Comment by bluebear94** [comment] 2023-07-22 07:00
Notes:

* this doesn’t affect ornament playback
* `Score::createPlayEvents` is never called when grace notes are added or removed; you have to use a plugin to force MuseScore to recalculate play events for these notes. But somehow, the grace notes still play even when `Score::createPlayEvents` is not called.
* In measure 17 of [this score](https://musescore.com/user/117966/scores/11560198), MuseScore 3 creates the following play events for the chord with the grace notes: 0 – 190‰, 190 – 380‰, and 381 – 969‰. MuseScore 4, when forced to do so with a plugin, creates the play events at 0 – 125‰, 125 – 250‰, and 250 – 962‰.

**Comment by bluebear94** [comment] 2023-07-22 07:31
Update:

In MuseScore 3, a group of acciaccature takes 65 ms or 50% of the parent chord’s duration, whichever is less ([libmscore/rendermidi.cpp](https://github.com/musescore/MuseScore/blob/3.6.2/libmscore/rendermidi.cpp#L2095)).

In MuseScore 4, the “available grace note duration” of a group of *N* acciaccature has a duration of either the duration of *N* 64th notes or 50% of the parent chord’s duration ([src/engraving/playback/renderers/gracechordsrenderer.cpp](https://github.com/musescore/MuseScore/blob/master/src/engraving/playback/renderers/gracechordsrenderer.cpp#L171)) and is further limited by the total duration shown by the grace notes. I’m open to how we want to change this. Personally, I prefer the MuseScore 3 behavior, but I’d like to hear any rationale on why this was changed.

**Comment by DmitryArefiev** [comment] 2024-01-30 12:50
Fixed in #20453

**Closed** 2024-04-18 12:14 UTC
Labels: P2, playback, regression_ms3

**Comment by scorster** [comment] 2024-06-12 04:39
A few questions:

1) Is there agreement on whether acciaccatura "crushed" grace notes move/delay the onset of the parent note? My opinion is that they should not delay the onset of the parent note. Rather I'd want them to start within the tail of the previous beat note or rest. For the record, I did not hear this effect in MS3. I hope this can be accomplished, or at least allowed. 

2) Is there a consensus on  the ideal length of the acciaccatura? 

3 Currently in MS 4.3.1 is any option for attenuating such behaviors, and saving them as a style. If not, Is there intent to allow the user to define their own styles? That would be greatly welcomed and would allow me to design grace notes to sound the way I wish and expect.

4) I'd like similar options for designing mordents, particularly upper mordents? In Celtic music they are used to designate "short rolls" and "long rolls." Rather than getting pre-packaged one-size-fits-all results, I could make them sound as intended—even with swing–if mordent design options and styles exist.

**Comment by scorster** [comment] 2024-06-12 23:56
> [dcorson-ticino-com](https://github.com/dcorson-ticino-com) wrote > *the acciaccatura ends on the beat ... As such, an acciaccatura *does not* delay the start of its parent note*

Agreed. And if an acciaccatura ends "on the beat" (i.e. at the onset of the graced parent note) then it must start before that. But unfortunately Musescore's  acciaccaturas do delay the beat, at least  

Here's a comment in a .org discussion dating back to 2018 (and in that thread it's said that earlier versions of MuseScore did not delay of the onset of an acciaccaturas parent note:

https://musescore.org/en/node/110301#comment-839941

Not sure what you mean by a "normal" grace note. An appoggiatura? If so, yes. It delays the onset of the parent note. 

I don't know if a consensus will ever occur, but grace note playback properties and styles would allow scorists to invoke the sound they intend.

scorster
