### ISSUE TITLE
Inconsistent location (on the right) for "Save" button in "Save score" dialog

### ISSUE THREAD

**Issue by CelloMellowMan** [musescore/MuseScore#17484] opened 2023-05-07 11:45 UTC
### Your idea

Move the "Save" button to make it the left-most button on the Save dialog window when saving and closing a score.
![1](https://user-images.githubusercontent.com/132821555/236675456-eb9cc916-e86a-42f8-bcd4-8924866268ea.png)

### Problem to be solved

(Windows user).  As with most other MuseScore dialog boxes, the default "Save" or "Yes" or "Continue" button is the left-most button if there are several choices ("Cancel" being the right-most). But the main "Save score" dialog window has the "Save" button on the **right**. I really found this strange. I'm so used to looking (and clicking) that left-most button for any affirmative/yes action I'm doing. Thanks.
![2](https://user-images.githubusercontent.com/132821555/236675473-86bcfa1e-227b-47e8-b508-2bffa85cbc57.png)

### Additional context

Windows user.

**Comment by cbjeukendrup** [comment] 2023-05-07 12:38
Duplicate of #10505 (which has a fix in progress!)

**Closed by cbjeukendrup** 2023-05-07 12:38 UTC
Labels: feature request
