### ISSUE TITLE
[MU4 Issue] Tab order in New Score wizard is wonky

### ISSUE THREAD

**Issue by Reedbeta** [musescore/MuseScore#16336] opened 2023-02-12 20:00 UTC
**Describe the bug**
In the New Score wizard, on the "Additional Score Information" page, pressing Tab doesn't cycle through the controls in the dialog in the expected manner. In particular, pressing Tab on one of the text fields doesn't move you to the next text field, but to the Cancel button.

In fact, Tab only cycles through the three sections of the form (the top row of buttons, the text fields, and the bottom row of buttons) and not through the controls within each section. (The arrow keys do allow you to move between the controls in each section.)

**To Reproduce**
1. File -> New
2. Choose some instruments or a template - doesn't matter what
3. Click "Next"
4. Try to move through the form fields using the Tab key.

**Expected behavior**
Tab should cycle through all controls in the form in left-to-right, top-to-bottom order.

**Screenshots**
![image](https://user-images.githubusercontent.com/1578730/218333590-4563b791-8467-4247-ae93-c4e764b7a9ef.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by MarcSabatella** [comment] 2023-02-13 02:28
This is currently by design.  Throughout the UI, MuseScore has moved to a more hierarchical model of F6/Tab/Cursor to avoid forcing users to tab through each and every control.

**Comment by cbjeukendrup** [comment] 2023-02-13 07:40
Duplicate of #12851. Thanks for reporting!

**Closed by cbjeukendrup** 2023-02-13 07:40 UTC
