### ISSUE TITLE
[MU4 Issue] MusicXML import hides instruments incorrectly

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#16135] opened 2023-01-30 11:54 UTC
**Describe the bug**
Attempting to import MusicXML that has been exported from something else, such as Finale Notepad, results in missing instruments in the score (the instruments are there as evidenced by the mixer and the instrument list, they just don't appear in the score).

**To Reproduce**
1. Export something from another program as MusicXML
2. Import it into MuseScore - instruments are missing
3. Examine instrument list panel you see the instruments exist but are hidden

A sample MusicXML file that fails to import:

[Razzle Dazzle (full).xml.gz](https://github.com/musescore/MuseScore/files/10535456/Razzle.Dazzle.full.xml.gz)

There should be full SATB+Piano. Instead you get just the piano in the score, but the full SATB+Piano in the mixer.

**Comment by MarcSabatella** [comment] 2023-01-30 14:43
FWIW, the instruments are present, they are just hidden.  You can display them using the Instruments panel in the left sidebar.  Not clear why - what makes this particular MusicXML file different from others where this works normally.  But to be clear - MusicXML *does* work normally.  So in the future, better to give your issue titles a more specific title, like "missing instruments on import of specific MusicXML file".

You also mentioned a particular MusicXML that exports with errors.  Be sure to open a separate issue for that and attach that particular MusicXML file as well.

**Comment by majenkotech** [comment] 2023-01-30 14:47
It's not this particular XML file. It's *every* XML file I try and import that has been exported from Finale Notepad (the only source of XML files I have that isn't MuseScore, by the way).

And as for the exporting from MuseScore - it's every file I try to export (the same ones that I export fine from MS3) that fail to import.

**Comment by MarcSabatella** [comment] 2023-01-30 14:53
If every file imports from Finale Notepad successfully other than some instruments being hidden by default, great, then no need for additional issues reports.  Probably you are simply hitting upon the same bug over and over.

As for export, again, nonally it works correctly, so if you have a specific file that produces a specific error, you'll need to open a separate issue so it can be investigated.  The thousands of test files all work perfectly, so presumably your scores all have something in common that is causing them to run into the same bug over and over.

**Comment by Jojo-Schmitz** [comment] 2023-01-30 16:13
Possibly related to my #12680 ?

**Comment by lvinken** [comment] 2023-02-14 06:59
In case of the "Razzle Dazzle" file, the issue is caused by the 'staff-details print-object="no"' element. In function MusicXMLParserPass2::staffDetails() it causes the whole staff to be invisible, while in MusicXML this element does not necessary apply to the whole staff. The issue was is MuseScore 4 specific, it was introduced with [commit c6dc78c](https://github.com/musescore/MuseScore/commit/c6dc78c6e0e307cf93aa75864b7be87b8c4b84d1).

Simple example files attached.
[issue_16135.zip](https://github.com/musescore/MuseScore/files/10729592/issue_16135.zip)

Note: in MuseScore 3, individual measures can be set to invisible, which matches with the common use cases of MusicXML's 'staff-details print-object="no"' element, although this was never supported by MuseScore 3's MusicXML importer. In MuseScore 4 this function seems to be missing.

**Comment by MarcSabatella** [comment] 2023-02-14 13:56
@lvinken when you refer to the invisible measure, are you referring to the checkbox in Measure Properties allowing you to hide a measure for a single staff of a multi-staff score?  That's still supported, and still works.

**Comment by lvinken** [comment] 2023-02-14 19:39
Thanks, that was indeed what I was referring to. I had expected the checkbox to be in the measure properties tab (F8) and did not in the measure properties popup (right-click).

**Comment by asattely** [comment] 2023-03-27 20:41
I would like to request some input as to a definitive idea of how to handle this. From what I understood from reading the issue and the proceeding conversation, it seems that if this `<staff-details print-object="no">` tag is in a _measure_, we want to hide the measure. Is this consistent with how we expect MuseScore to deal with that tag within a measure? For reference, the draft PR above demonstrates this behavior on import.

If that's what we want, then we should definitely make sure we are all on the same page with what we expect the behavior to be, considering there's a unit test that clearly expects the staff to be hidden if the first measure of that staff has the `print-object="no"` attribute (https://github.com/musescore/MuseScore/blob/master/src/importexport/musicxml/tests/data/testHiddenStaves.xml).

MusicXML gurus, unite!

**Comment by lvinken** [comment] 2023-03-28 18:25
The MusicXML specification is not explicit on the exact semantics (see https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/staff-details/). Two of the sample files (BrookeWestSample.musicxml and SchbAvMaSample.musicxml) show print-object affects the enclosing measure and all subsequent measures until a print-object with the inverse value is encountered.

**Comment by Jojo-Schmitz** [comment] 2023-05-10 09:37
Seems related to #17398, a problem with **exporting** hidden empty staves, but also discussing an issue on their import, which in turn seems to be a regression vs. Mu3

**Comment by lvinken** [comment] 2023-06-09 19:44
Created a few more test files with hidden measures including screenshots of import into Finale NotePad for reference:
[invisible_measures.zip](https://github.com/musescore/MuseScore/files/11709572/invisible_measures.zip)
I would expect MuseScore's import to match NotePad's.

**Comment by Jojo-Schmitz** [comment] 2023-06-27 14:13
Came up again in https://musescore.org/en/node/351665

Seems Mu3 on those imports does check "Hide empty staves" and does uncheck "Don't hide empty staves in firest system", but Mu4 doed not, instead hides the entire staff throughout ('Closed eye' icon in the instruments tab)

**Comment by Jojo-Schmitz** [comment] 2023-06-27 14:14
Definitley a Mu3 regression

**Comment by MarcSabatella** [comment] 2023-06-27 14:26
FWIW, if the desired behavior is to add the staff but set it to be hidden, we should not set the *instrument* to hidden, but instead set the *staff* to hidden.  And this should apply to *all* imports involved hidden staves/instruments, including import from MU3.  I had long ago submitted a PR to fix that for MU3/MU2/MU1 import that was never merged - https://github.com/musescore/MuseScore/pull/13293.  That code could be adapted and placed somewhere further upstream so all imports get the fix.

**Comment by Jojo-Schmitz** [comment] 2023-06-27 14:31
'Culprit' or trigger is
```xml
<staff-details print-object="no"/>
```

**Comment by Jojo-Schmitz** [comment] 2023-06-27 17:08
Seems 3.x ignores `staff-details` on pass 1 and uses `staffDetails(partId)` in pass 2, but there doesn't handle `print-object`
Mu4 handles this though:
'''ccp
    QString visible = _e.attributes().value("print-object").toString();
    if (visible == "no") {
        _score->staff(staffIdx)->setVisible(false);
```

**Closed** 2023-07-12 18:36 UTC
Labels: regression_ms3
