### ISSUE TITLE
[MU4 Issue] Stems disappear when beams are moved, when scrolling set to vertical, from second page onwards

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#13923] opened 2022-10-23 14:39 UTC
**Describe the bug**
I made a *new* score in MU4.
Beam placement can not be edited. stems disappear. OK on 1st page, but not on 2nd page.
**To Reproduce**
see file. try to alter beam placement

[Beam error in new file in mu4 Edit placement error.zip]

(https://github.com/musescore/MuseScore/files/9846787/Beam.error.in.new.file.in.mu4.Edit.placement.error.zip)

![screenshot 2022-10-23 163742](https://user-images.githubusercontent.com/110895947/197398282-595842b9-862c-4a68-8f2c-9109723d8a73.png)
![screenshot 2022-10-23 163601](https://user-images.githubusercontent.com/110895947/197398284-3704af0e-4687-4a19-a3ce-aef1b9d5ff12.png)

**Platform information**
Windows 11 updated

**Additional context**
see also cross staff problems after import
It is not the import apparently

**Comment by oktophonie** [comment] 2022-10-24 14:51
@mart661331 Please indicate which build you are using.

I _still_ cannot reproduce this in any way. Can anyone else?

**Comment by mart661331** [comment] 2022-10-24 14:54
build 23 october 2022

**Comment by oktophonie** [comment] 2022-10-24 15:06
https://user-images.githubusercontent.com/20604032/197559952-96890f8f-31ec-43b9-a344-c88631738859.mp4

**Comment by mart661331** [comment] 2022-10-24 15:17
and on the 2nd page I presume...

if so, can it be because of having 2 versions on 1 pc?

can there be interference  with settings?

**Comment by mike-spa** [comment] 2022-10-24 15:26
I also cannot reproduce the issue, and it does indeed look like something we fixed a while ago. I think it is safe to close this @Tantacrul  @oktophonie 



> if so, can it be because of having 2 versions on 1 pc?

Yes, as Marc said, it is possible that you are not running the executable you think you are. I would advise, especially on windows, to only use the "portable" installations when you have multiple versions on the same machine. That way it should be safer that you are running the right executable every time.

**Comment by mart661331** [comment] 2022-10-24 15:43
![screenshot](https://user-images.githubusercontent.com/110895947/197568007-13dd93dc-23e5-4800-923c-22590ef54248.png)
No problems with horizontal.

But I use vertical, then the problem exists

**Comment by mike-spa** [comment] 2022-10-24 15:56
> No problems with horizontal.
> 
> But I use vertical, then the problem exists

Oh NOW I can reproduce it. Why on earth the page-scrolling preference would interfere with beam layout is beyond me. But ok thanks I'll look into it 👍

**Comment by mart661331** [comment] 2022-10-24 15:57
I am happy now.  At Last

**Comment by oktophonie** [comment] 2022-10-24 16:03
Now we're getting somewhere!
I am closing the other issue (#13644) as it's essentially the same as this.

**Comment by MarcSabatella** [comment] 2022-10-24 16:23
FWIW, this doesn't surprise me all that much now that I know the trigger.  The last stages of the layout / drawing code and that's where a lot of beaming and cross-staff notation happens in MU3 at least) have always been very sensitive to things like this.  Generally the issue would turn out to be in converting page-relative offsets to canvas-relative ones, and yes, it would be triggered by some combination of page >1, horizontal / vertical scrolling, or by page / continuous view.

**Comment by mike-spa** [comment] 2022-10-24 16:51
Yeah, I slightly panicked because it also looked like it could have been caused by a missing a layout call, and I was afraid it may have been caused by my work on cross-beam spacing. But indeed, it appears to have been just a case of wrongly using canvas- vs page-coordinates. Let's see if the linked PR fixes it.

**Closed** 2022-10-24 17:52 UTC
Labels: P1
