### ISSUE TITLE
[Musicxml Export] - Tablature staff (linked) doesn't export -> import from musescore 4 -> musescore 3 properly in some cases

### ISSUE THREAD

**Issue by mike-hoegeman** [musescore/MuseScore#17481] opened 2023-05-06 20:37 UTC
### Issue type

Other type of issue

### Bug description

i have a score in musescore4 that has a linked tablature staff that i'd like to give to a friend that has musescore 3 ( he has an ancient mac)  if i export it to musicxml it mostly works, but it doesn't preserve the the fingering changes i made in the tablature staff. it seems to just have in there what it makes as default guesses when you first create the score. any suggestions on how to work around that. there doesn't seem to be a way to unlink the staffs before export. i would likely be happy enough to just export the (correct tabs)  only   also. i tried deleting the notation staff but that doesn't work because the tab staff still  acts like it's linked 

the musescore 3 is 3.6.2 btw
musescore 4 is 4.0.2

this musescore 4 score demonstrates the issue
[Variations_for_the_healing_of_Arinushka_no_six.mscz.zip](https://github.com/musescore/MuseScore/files/11413345/Variations_for_the_healing_of_Arinushka_no_six.mscz.zip)

MarcSabatella — Today at 12:30 PM
If the notation staff is deleted, then there is no more linking, so it can't really be that the tab staff is acting like it's linked - more likely it's a limitation of either MuseScore 4 MusicXML export, or MuseScore 3 MusicXML import
I just did a little test, though, and it all worked fine for me, so in order to say more, we'd need to see your score
MarcSabatella — Today at 12:52 PM
I can confirm that for some reason this score isn't working even though the test I created did
So, please open an issue on GitHub and attach the score there for further investigation 

### Steps to reproduce

1. export attached file in musicxml format from musescore 4 ( has linked tablature staffs )
2. import file into musescore 3
3. notice that the tablature in the imported score in musescore 3 has incorrect fret / string values. they are not the ones present in the original  musescore 4 score

### MuseScore Version

the musescore 3 is 3.6.2 musescore 4 is 4.0.2

### Regression

I don't know

### Operating system

macos ventura 13.3.1

**Comment by lvinken** [comment] 2023-05-07 20:38
There are a number of different issues at play here:
- MuseScore (3 and 4) does not export linked regular/tab parts correctly (the "staff-type alternate" is missing, see https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/staff-type-element)
- MuseScore (3 and 4) does not import linked regular/tab parts correctly: the link gets lost
- MuseScore (3 and 4) does not import non-standard staff tuning (fix available in https://github.com/musescore/MuseScore/pull/17490/commits)

**Comment by mike-hoegeman** [comment] 2023-05-07 22:04
So does the commit fix all the issues at play ? Wasn’t sure of your wording. (Just so I know if I should try it. ) Sent from my iPhoneOn May 7, 2023, at 1:38 PM, Leon Vinken ***@***.***> wrote:﻿
There are a number of different issues at play here:

MuseScore (3 and 4) does not export linked regular/tab parts correctly (the "staff-type alternate" is missing, see https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/staff-type-element)
MuseScore (3 and 4) does not import linked regular/tab parts correctly: the link gets lost
MuseScore (3 and 4) does not import non-standard staff tuning (fix available in https://github.com/musescore/MuseScore/pull/17490/commits)

**Comment by lvinken** [comment] 2023-05-08 04:53
PR 17490 only fixes the last of the three issues.

**Comment by bkunda** [comment] 2023-05-08 20:57
For what it's worth, I was able to export the file provided in the issue description as MusicXML and import it into Sibelius more or less correctly (there remains some fiddliness with stave transposition to address, and also the bass stave seems to be inverted in MS4, which Sibelius doesn't pick up – and I'm not even sure how to achieve this is MS4. But these inconsistencies notwithstanding, the fingering is at least not altered like it is when opening in MS3). 

I too tested with other scores, and can confirm export/import is working as expected. So it seems there is something unusual going on in this particular score when bringing it into MS3.

So unless this can be reproduced across other scores, it's not really an issue, but rather a particular problem with this score. 

(That's not to say there isn't an issue lurking deeper behind the scenes here, but in order to be an effective issue that we can act upon, some more thorough troubleshooting would be needed to generalise the problem _before_ it gets raised here). 

Since both Marc and I have been able to successfully export tab and import it into MS3 with correct fingerings (aside from the attached score), I'm going to close this issue for now so it doesn't distract our dev team. I'd also add that the title is incredibly confusing, which isn't helping here. If @mike-hoegeman you are able to reproduce this in other contexts, then I think we'd stand a better chance of identifying an issue that we can address. Meanwhile, there may be other members on our Discord channel or the forum who can help you further troubleshoot your score. I can certainly appreciate how frustrating it is that the fingering isn't being imported correctly!

**Closed by bkunda** 2023-05-08 20:57 UTC
Labels: needs review

**Comment by lvinken** [comment] 2023-05-09 05:11
@bkunda, please see my previous remarks, they describe structural issues. I'll submit separate and specific issues for these (and probably also provide pull requests with fixes).

**Comment by mike-hoegeman** [comment] 2023-05-09 18:42
there is checkbox setting for the tab staff in Staff/Part
properties->Advanced Properties called "Upside down"

that lets you configure the low to high string order to reverse/upside
down. this exists in musescore 3 and 4.
this is used for chapman stick stype instruments and probably others.
i would suspect that this could be setting that is triggering the issue,
since it's different than most score. i should have given that special note
on refelection

i gave you a score that clearly shows the problem as mark verified.
leon also described the issues that are causing it.
given these facts, i fail to see why you would toss this report. i am
disappointed as a subscriber

the issue title
[Musicxml Export] - Tablature staff (linked) doesn't export -> import from
musescore 4 -> musescore 3 properly in some cases

while admittedly stilted seems to describe the problem reasonably. i will
concede it's not a great title :)  not a reason to toss the bug though

**Comment by bkunda** [comment] 2023-05-15 19:14
@mike-hoegeman are you specifically talking about this problem identified by @lvinken?
 > MuseScore (3 and 4) does not export linked regular/tab parts correctly (the "staff-type alternate" is missing, see https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/staff-type-element)

If this indeed remains a problem, and it is reproducible (i.e. does not just affect one score), then it would make sense for it to be raised as a separate issue.

**Comment by mike-hoegeman** [comment] 2023-05-15 19:27
from leon's description only two of the three problems he identified  in
musescore 4 have a fix at the moment

**Comment by mike-hoegeman** [comment] 2023-05-15 19:28
sorry , one of the three

**Comment by mike-hoegeman** [comment] 2023-05-15 19:29
i would suggest talking to Leon. he seems to have a good grasp of the
issues.

**Comment by lvinken** [comment] 2023-05-17 04:36
@bkunda, indeed IMHO the failure to import non-standard staff tuning (fixed in MuseScore 4 by [PR17490](https://github.com/musescore/MuseScore/pull/17490)) was the most important. I am aware of the MuseScore 3 policy and hope Jojo will pick this up in his fork. Until that happens there is no easy way to move tab files with non-standard staff tuning from MuseScore 4 to MuseScore 3.

Yes, the other two issues mentioned in my May 7 reply are indeed structural issues in MuseScore 3 to MuseScore 4, although I expect their impact is smaller. As soon as I find the opportunity I'll submit separate and specific issues for these (and may also provide pull requests with fixes).

**Comment by Jojo-Schmitz** [comment] 2023-05-17 06:40
#17490 has been backported to my branch 3.x about a week ago

**Comment by bkunda** [comment] 2023-05-17 09:47
> As soon as I find the opportunity I'll submit separate and specific issues for these (and may also provide pull requests with fixes).

That's great, thank you @lvinken

**Comment by lvinken** [comment] 2023-05-26 05:48
@bkunda, indeed IMHO the failure to import non-standard staff tuning (fixed in MuseScore 4 by [PR17490](https://github.com/musescore/MuseScore/pull/17490)) was the most important. I am aware of the MuseScore 3 policy and hope Jojo will pick this up in his fork. Until that happens there is no easy way to move tab files with non-standard staff tuning from MuseScore 4 to MuseScore 3.

Yes, the other two issues mentioned in my May 7 reply are indeed structural issues in MuseScore 3 to MuseScore 4, although I expect their impact is smaller. As soon as I find the opportunity I'll submit separate and specific issues for these (and may also provide pull requests with fixes).

**Comment by lvinken** [comment] 2023-05-26 05:49
Submitted [issue 17737](https://github.com/musescore/MuseScore/issues/17737) for MusicXML import and export of a linked staff.

**Comment by Jojo-Schmitz** [comment] 2023-05-26 09:46
I will pick this up for my fork

**Comment by Jojo-Schmitz** [comment] 2023-05-26 10:03
Actually #17490 is already in, since some 2 weeks
