### ISSUE TITLE
[MU4 Issue] Playback completely stops for VSTi when a note is not played, this also affects effects.

### ISSUE THREAD

**Issue by Reloup38** [musescore/MuseScore#16398] opened 2023-02-16 15:56 UTC
**Describe the bug**
When setting an effect for an instrument, the effect is only applied for as long as the notes are played. If you have an instrument with a very short decay (or play staccato notes), but you want to apply a lot of reverb on it, this can lead to very goofy results. The playback will resume once the next note is played, but it's like nothing happened inbetween, and the reverb will just start again from where it stopped.

This has been tested with different VST (JuicySFplayer and DecentSampler) and soundfonts and seems to be tied to the decay value of the samples played.

This bug persists when exported to MP3 (see attached music), and it doesn't happen when the effect is set on the master channel. However, setting an effect on the master channel is not always appropriate.

**To Reproduce**
1. Load a VST
2. Apply an effect on the instrument, such as MuseFX reverb set on max to make the effect obvious.
3. Try to play music written for it that contains for exemple staccato notes and silences
4. Hear error

**Expected behavior**
Effects should behave normally even at the instrument level. For exemple, when mixing musesound and non-musesound instruments, setting the reverb on the master channel means the already wet musesound samples will get drenched, and not setting reverb at all means non-musesound presets will sound dry in comparison.

**Screenshots**
![image](https://user-images.githubusercontent.com/116571960/219418642-6fd7bdf8-31de-4e12-835d-3d8d9f4f8851.png)
[testreverbmp3.zip](https://github.com/musescore/MuseScore/files/10757823/testreverbmp3.zip)

**Platform information**
 - OS: Windows 10

**Comment by abariska** [comment] 2023-02-21 17:23
Confirm. The issue reproduces with any combination of VST instrument and VST fx

**Comment by cbjeukendrup** [comment] 2023-03-04 16:02
Is this maybe related to of a duplicate of #12973?

**Comment by abariska** [comment] 2023-03-05 15:38
**Duplicate** of https://github.com/musescore/MuseScore/issues/12973

**Closed by abariska** 2023-03-05 15:38 UTC
Labels: P1
