### ISSUE TITLE
horizontal frame and system break prevent courtesy keysigs

### ISSUE THREAD

**Issue by SystemsModelling** [musescore/MuseScore#22256] opened 2024-04-07 20:15 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Inserting a horizontal frame 
and entering a break at that frame breaks the stave all right but now there are no courtesy accidentals

Divisi arrows are beyond RH margin of bars.

![image](https://github.com/musescore/MuseScore/assets/20604032/8fe28101-845e-495a-adf4-d346b1910e90)

Entering a break at end bar creates courtesy accidentals, as expected.

![image](https://github.com/musescore/MuseScore/assets/20604032/c2d22798-33b8-47bb-923a-57cfae93cd03)

Suppose we want the divisi arrows to end at the same right hand margin as the rest of the bars?
Instead of entering a system break, inserting a horizontal frame at bar 5 and entering a break at that frame breaks the stave all right but now there are no courtesy accidentals

![image](https://github.com/musescore/MuseScore/assets/20604032/d3a4b508-d552-4ec3-9d7f-fa33073eae51)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by zacjansheski** [comment] 2024-04-09 20:06
@SystemsModelling 

It would be helpful to have a screen capture and/or a musescore file showing what you are trying to do.

You can attach musescore files here by compressing or using .zip

**Comment by SystemsModelling** [comment] 2024-04-10 08:43
@zacjansheski  my original post has a .doc file attached containing several screenshots of different outcomes.

"[Divisi arrows, Hframe, accidentals.docx]"(https://github.com/musescore/MuseScore/files/14898822/Divisi.arrows.Hframe.accidentals.docx)

**Comment by zacjansheski** [comment] 2024-04-10 11:36
Not everyone here can open a .doc file

**Comment by Jojo-Schmitz** [comment] 2024-04-10 11:39
from that docx:

Divisi arrows are beyond RH margin of bars.
![image](https://github.com/musescore/MuseScore/assets/1786669/bafadfca-4d87-4912-a7fa-f67fb134f302)
Entering a break at end bar creates courtesy accidentals, as expected.
![image](https://github.com/musescore/MuseScore/assets/1786669/0777cc33-4fc5-42a2-8200-6b786434394e)
Suppose we want the divisi arrows to end at the same right hand margin as the rest of the bars?
Instead of entering a system break, inserting a horizontal frame at bar 5 and entering a break at that frame breaks the stave all right but now there are no courtesy accidentals
![image](https://github.com/musescore/MuseScore/assets/1786669/afe13949-68d8-4ef3-89aa-a053e27c6942)

**Comment by SystemsModelling** [comment] 2024-04-10 12:46
That's very kind of you Jojo, thank you.
I hadn't thought of a .doc problem,  I just assumed every OS had an app for that.
Would a PDF be better  in order to interleave text and images?
P

**Comment by Jojo-Schmitz** [comment] 2024-04-10 13:10
Even better just use plain text and images

**Comment by XiaoMigros** [comment] 2024-04-11 07:55
I'm wondering what the best way to solve this would be... A toggle in properties for horizontal frames?

**Comment by Jojo-Schmitz** [comment] 2024-04-11 07:57
I don't think that's needed, it should just work, unconditionally, just as if those frames weren't there.

**Comment by XiaoMigros** [comment] 2024-04-11 07:58
Even when the new measure is on the same system?

**Comment by Jojo-Schmitz** [comment] 2024-04-11 08:05
If the user wants control, (s)he should use a section break

**Comment by XiaoMigros** [comment] 2024-04-11 08:11
Section breaks won't work in cases like this...

![grafik](https://github.com/musescore/MuseScore/assets/116587995/9b4bd4b6-c5ac-45ef-891d-852e3d14be56)

**Comment by Jojo-Schmitz** [comment] 2024-04-11 08:20
Ah, indeed not for horizontal frames, I had forgotten about that

**Comment by XiaoMigros** [comment] 2024-04-11 08:21
Yes, system break on a horizontal frame, which is only one of the many use cases

**Comment by Jojo-Schmitz** [comment] 2024-04-11 08:21
But here we're dealing with horizontal frames __and__ system breaks

**Comment by XiaoMigros** [comment] 2024-04-11 08:24
Well, yes. However since there are other instances where different behavior could be wanted, I think a more encompassing solution is best

**Comment by iainhallam** [comment] 2024-04-17 09:49
> Section breaks won't work in cases like this...
> 
> ![grafik](https://private-user-images.githubusercontent.com/116587995/321551195-9b4bd4b6-c5ac-45ef-891d-852e3d14be56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDcwNDYsIm5iZiI6MTcxMzM0Njc0NiwicGF0aCI6Ii8xMTY1ODc5OTUvMzIxNTUxMTk1LTliNGJkNGI2LWM1YWMtNDVlZi04OTFkLTg1MmUzZDE0YmU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QwOTM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWEyZjBhZjNlYjMxOGIzZTMxY2Q3ZjhlODAzZDI5M2E3YzBkYjJkNzdhNmNkYWNhMmM0MDkxYWI0YzZkODU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.as6Q02jMoo33nX4pl9xGJ8CKTxDTvcRnHcQbjMkPdWM)

In this case, it seems like you wouldn't want the courtesy key signature, but by default it wouldn't be generated anyway?

**Comment by sammik** [comment] 2024-04-17 12:45
> I'm wondering what the best way to solve this would be... A toggle in properties for horizontal frames "Display courtesy keysig, timesig, clef in previous measure" ?

I dont think any new option is needed. Option to show / not show courtesy keysig is already included in "normal" key signature.

Problem here is, "previous measure", or "last measure of previous system" is not real measure. So solution would be, to ensure, in creating courtesy keysig, to create them to real measure (skip frames).

Same way, like it does, when frame is at the begining of new system.
![courtesy keysig](https://github.com/musescore/MuseScore/assets/1646034/af128d87-f31b-4a1b-b32f-fd2e6520c1fa)

**Comment by XiaoMigros** [comment] 2024-04-28 20:50
But in cases like this, the user may sometimes want a courtesy and sometimes not. That's why it should be controllable

> ![grafik](https://private-user-images.githubusercontent.com/116587995/321551195-9b4bd4b6-c5ac-45ef-891d-852e3d14be56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzc2NTIsIm5iZiI6MTcxNDMzNzM1MiwicGF0aCI6Ii8xMTY1ODc5OTUvMzIxNTUxMTk1LTliNGJkNGI2LWM1YWMtNDVlZi04OTFkLTg1MmUzZDE0YmU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMDQ5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWM0YTM2OTFmNzQyMDViNGMyNGM5ZTVlNDU0MGY5NTBkYzBlNDUzZDAwMzVhMzdjMzUxNDE2NmM0OTYxNTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K3bfH3boEvIlw-sFHdx0ZV2BdRQokJZmhLXnNNUEius)

**Comment by sammik** [comment] 2024-04-28 21:46
> But in cases like this, the user may sometimes want a courtesy and sometimes not. That's why it should be controllable

I cannot see image

**Comment by Jojo-Schmitz** [comment] 2024-04-28 21:54
Interesting I can either but could earlier

**Comment by XiaoMigros** [comment] 2024-04-28 23:37
fixed

**Comment by sammik** [comment] 2024-04-29 04:58
> Section breaks won't work in cases like this...
> 
> ![grafik](https://private-user-images.githubusercontent.com/116587995/321551195-9b4bd4b6-c5ac-45ef-891d-852e3d14be56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDgwMzgsIm5iZiI6MTcxNDM0NzczOCwicGF0aCI6Ii8xMTY1ODc5OTUvMzIxNTUxMTk1LTliNGJkNGI2LWM1YWMtNDVlZi04OTFkLTg1MmUzZDE0YmU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMzQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTYzNDdiMDk2MGQ1ZjkyYzJlYTkyZjcxMTY0YTA5YWUyODUxMzRmMTg5NGY2ZGM4M2Q5NzVkNjA3Y2JmMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nQWkpZML95iPS5o-3H2PJypMnb_LoLpkGJHbBRBaDEo)

I think, this is different case. I see it as a nice feature request, and original post as a bug.

But if having this nice option, defaults in theese cases should be oposite.

If line break, courtesy keysig should be on, if not line break, courtesy keysig should be off by default. (Of course depending on score style settings too).

**Comment by Jojo-Schmitz** [comment] 2024-04-29 17:36
I wondwer whether it is related to #16530, having the same root cause?

**Comment by Jojo-Schmitz** [comment] 2024-04-29 17:39
Isn't this a duplicate of #19759?

**Comment by sammik** [comment] 2024-11-03 21:31
please, check'n test #25420

**Closed** 2024-12-17 08:34 UTC
Labels: P3, engraving
