### ISSUE TITLE
[MU4 Issue] Grace notes in tab do not align with those in the standard staff

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12439] opened 2022-07-16 10:32 UTC
**Describe the bug**

An issue carried over from MS3. Grace notes in tablature do not line up with the corresponding notes in the paired standard staff (linked or unlinked).

**To Reproduce**

1. Open the attached score of paired staff/tab. 
[specimen_score.zip](https://github.com/musescore/MuseScore/files/9125575/specimen_score.zip)

2. Inspect measures 2, 4, 12, 34, for example

RESULT: The grace notes in the tab staff do not align with the corresponing ones in the paired standard staff. e.g.
![misalignment](https://user-images.githubusercontent.com/87246583/179351109-3d69c482-db32-41d1-b55e-ef36c7d8d2c1.png)

**Expected behavior**

Grace notes in paired staff/tab should be aligned.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2680600421, revision: github-musescore-musescore-315cfb3

**Comment by oktophonie** [comment] 2022-07-18 07:30
It is not necessarily the case that the grace notes should align. Personally I wouldn't want to unnecessarily distort their spacing on the tab stave (making space for items that aren't even there, like accidentals or flags) purely for the sake of alignment. Others will disagree. In general though this issue is not automatically solvable, since in situations where there are simultaneous grace notes on different staves (or even in different voices on one stave) it is not always clear whether, or how, they should align. This comes up from time to time in the forum, e.g. https://musescore.org/en/node/29521

As this is not a regression I will close this, but some fresh consideration will be given to the overall issue in 4.x.

**Closed** 2022-07-18 07:30 UTC
