### ISSUE TITLE
Measure Number on bottom staff only

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24933] opened 2024-09-26 12:11 UTC
### Your idea

Add an option to `Format->Style->Measure numbers` to specify bottom staff only. Perhaps the `All staves` checkbox could become a pulldown `Top staff`/`Bottom staff`/`All staves`.

### Problem to be solved

Many contexts (specifically musical theater) require measure numbers on the bottom of each part and at the bottom of the score. Currently the only workaround is to show them on every staff and then hide them where unwanted.

A nice to have would be automatic treble clef avoidance (by offsetting the number to the right of the clef at system start, as needed.)

### Prior art

Both Finale and Dorico allow this.

### Additional context

I spent considerable effort implementing musical theater measure numbers in a plugin for Finale called "Copyist's Helper". They are their own beast, basically every-measure rehearsal numbers rather than a counter per se, and I understand the requirements pretty well.  I have seen this issue in the forums, but I did not find it already here, so I am adding it. If this is already covered elsewhere, let me know.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-09-26 12:22
Duplicate of https://github.com/musescore/MuseScore/issues/17127
To be addressed as part of https://github.com/musescore/MuseScore/issues/24100 in 4.5

**Closed by oktophonie** 2024-09-26 12:22 UTC
Labels: feature request
