### ISSUE TITLE
Export lyrics to MIDI with -o option

### ISSUE THREAD

**Issue by rdecosta** [musescore/MuseScore#23832] opened 2024-07-30 07:46 UTC
### Your idea

Lyrics aren't natively a part of MIDI but people have been embedding them successfully for decades. The output -o options currently doesn't support this.

### Problem to be solved

Add lyrics into MIDI files created with -o

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment] 2024-07-30 11:16
This turns out to be a duplicate of https://github.com/musescore/MuseScore/issues/15925. But thanks for reaching out!

**Closed by cbjeukendrup** 2024-07-30 11:16 UTC
Labels: feature request
