### ISSUE TITLE
Score corruption with whole note and parts

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19567] opened 2023-09-30 16:52 UTC
### Issue type

File corruption

### Bug description

Musescore shows "This score has become corrupted and contains errors" dialog when entering whole note in certain conditions (described in steps)

### Steps to reproduce

1. Create new score from Treble template
2. Open Piano parts
3. Enter input mode (using N key)
4. Go back to main score
5. Select whole note duration and enter one whole note into first measure
6. Go back to Piano part
7. Enter quarter note using keyboard
8. Measure now is broken and contains only quarter note
9. If you try to save file, "This score has become corrupted and contains errors" dialog appears

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/0c9d721e-29c1-47df-940d-8866b2335aff

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232730304, revision: github-musescore-musescore-5791ea7
Musescore 4.1.1
Musescore 4.0.2

### Regression

I don't know

### Operating system

windows 10

**Comment by mercuree** [comment] 2023-09-30 17:00
autobot script for reproduction
[issue_#19567_autobot.zip](https://github.com/musescore/MuseScore/files/12775168/issue_.19567_autobot.zip)

**Comment by oktophonie** [comment] 2023-10-03 13:24
Duplicate of https://github.com/musescore/MuseScore/issues/18437

**Closed by oktophonie** 2023-10-03 13:24 UTC
Labels: corruption
