### ISSUE TITLE
[MU4 Issue] Brackets are placed outside page margin

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12927] opened 2022-08-19 06:00 UTC
**Describe the bug**
Brackets do not seem to observe the boundary of the page margin.

**To Reproduce**
1. Create a New Score based on template Wind Quintet
2. In properties, enable visibility of the page margins
3. See the result
4. It can be made more obvious when another (for instance a square) bracket is added to some staves

**Expected behavior**
All items should be place inside the page margin.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550012/185552486-e2b1356c-9258-4d12-a56f-36f41f95c11a.png)

**Platform information**
 - OS: Windows 10

**Comment by KlausMikhaelson** [comment] 2022-08-19 07:00
Hello @henkdegroot would like to work on this issue, can I get this assigned to me ?

**Comment by oktophonie** [comment] 2022-08-19 07:11
This is entirely by design; see https://musescore.org/en/node/330793

**Closed** 2022-08-19 07:13 UTC

**Comment by henkdegroot** [comment] 2022-08-19 12:23
Apology for raising the issue.

Thank you for the quick reply and details.

**Comment by RobFog** [comment] 2022-08-19 13:16
> Hello @henkdegroot would like to work on this issue, can I get this assigned to me ?

Hi @KlausMikhaelson, welcome to the community. You might want to join the developers group chats on Discord (https://discord.gg/zpqdPq2F) and issues marked as as "good first issue" (https://github.com/musescore/MuseScore/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) if you haven't yet.
