### ISSUE TITLE
Text displacement in the master palette tempo tab.

### ISSUE THREAD

**Issue by basaigh** [musescore/MuseScore#16669] opened 2023-03-05 23:28 UTC
### Issue type

UI bug

### Bug description

In the tempo tab of the master pallete, when the mouse is moving over the options, the text for accel. through to string. steadily move upwards, this is reset upon closing and reopening the master palette. I have not observed this happening anywhere else.

### Steps to reproduce

Go to View
Click on Master Palette
Click on Tempo
Move your mouse over the text

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/53559772/222992085-7488125f-e6f9-49f8-807d-46815d252e09.mp4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Windows 11

**Comment by RobFog** [comment] 2023-03-05 23:57
This would appear to be a duplicate of #15297?

**Comment by cbjeukendrup** [comment] 2023-03-05 23:57
Indeed, duplicate of https://github.com/musescore/MuseScore/issues/15297 which will be fixed in 4.0.2

**Closed by cbjeukendrup** 2023-03-05 23:57 UTC
Labels: UI

**Comment by basaigh** [comment] 2023-03-06 00:15
I apologise, when I searched for the issue, the is open filter was applied.
