### ISSUE TITLE
No playback for 2nd and next notes of chord in input mode

### ISSUE THREAD

**Issue by shoorick** [musescore/MuseScore#16690] opened 2023-03-07 19:40 UTC
### Issue type

General playback bug

### Bug description

When chords entered in input mode, only first note played but 2nd, 3rd etc are silent. Previous major versions (MuseScore 2 and 3) have all the notes played.

### Steps to reproduce

1. Switch to input mode — press `N`,
2. Enter any note, for example press `C`, hear sound,
3. Make chord — press for example `Alt+3`, see new note but hear silence.

### Screenshots/Screen recordings

_see below_

### MuseScore Version

MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64

### Additional context

MS Basic is used for playback.

Worked well at
OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021370, revision: github-musescore-musescore-3224f34

**Comment by shoorick** [comment] 2023-03-07 19:49
Look at screencast: only lower notes played in input mode:

[screencast_07.03.2023_22:47:57.webm](https://user-images.githubusercontent.com/190892/223536388-d04e2b8e-d4e4-4c74-b019-2a32e965c07c.webm)

**Comment by MarcSabatella** [comment] 2023-03-07 20:05
Thanks for reporting; this is a duplicate of https://github.com/musescore/MuseScore/issues/15028

**Comment by cbjeukendrup** [comment] 2023-03-07 23:12
Closing as duplicate of https://github.com/musescore/MuseScore/issues/15028

**Closed by cbjeukendrup** 2023-03-07 23:12 UTC
Labels: regression, playback
