### ISSUE TITLE
After adding a new note in insert mode, it causes a rhythm error

### ISSUE THREAD

**Issue by YOYOPole** [musescore/MuseScore#25326] opened 2024-10-27 08:13 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

After adding a new note in insert mode, it causes a rhythm error
![视频](https://github.com/user-attachments/assets/cbb6199e-b95d-485f-8e5b-441d04c5e192)
![图片](https://github.com/user-attachments/assets/c057355d-ba3b-4df3-bed7-73474f77d3fa)

### Supporting files, videos and screenshots

![图片](https://github.com/user-attachments/assets/a5233540-f898-4d81-9ac6-0ddb51886625)
![视频](https://github.com/user-attachments/assets/7a8407fd-4361-4f39-af06-a21fc18ccfdb)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3.242971445

### Regression

I was unable to check

### Operating system

Window11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by YOYOPole** [comment] 2024-10-27 09:30
OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

**Comment by MarcSabatella** [comment] 2024-10-27 12:55
Can you explain the error in more detail?  You asked MuseScore to *insert* notes into the measure (as opposed to the usual note entry which replaces), and that indeed adds the necessary number of beats to accommodate it.  Are you saying it inserted a different number of beats than it should have?  Or maybe you were wanting some number of subsequent notes to move later instead?  That is a commonly-requested feature and probably someday there will be a way to do that (with some sort of guess made as to how many notes to move).  But for now, you simply move the notes normally via cut & paste.  Don't use insert mode unless you want the extra beats.

**Comment by YOYOPole** [comment] 2024-10-28 13:23
I’d like to mention another issue in this post: the problem with the transpose function in the toolbar. After selecting transpose, the visible key does not change at all, and it is expected to change synchronously. For example, from C major C D E F G A B to #C major the interface still shows C major, but the notes are correct #C #D #E #F #G #A #B. However, sometimes it will changeously, and sometimes it won‘t, I can’t figure out the situation.                           
![描述图片](https://github.com/user-attachments/assets/49d71ce0-e7d8-4079-a4e1-746ae86e51dc)

**Comment by MarcSabatella** [comment] 2024-10-28 13:54
So the current insert behavior is not a bug, and this issue should be closed.

A feature to automatically guess which notes should be moved and move them for you when inserting is a separate matter, but would need someone to come up with an appropriate design for guessing how many notes to move.  There are existing issues proposing such things - see for example https://github.com/musescore/MuseScore/issues/19513.  So no need to open a new issue for your request.

Regarding transposition, that's not a bug either.  The transpose function will transpose existing key signatures within the selection, but it will add new ones or go outside the selection to add new ones.  if you want to change the key signature, just add it from the palette.

In the future, please ask for help in the official support forum at musescore.org to better understand how to use MuseSciore Studio.  Then if a consensus exists that there is a bug or a new feature to request, you can open new issues here - but one request or bug per issue (don't combine unrelated things in one issue).

**Comment by cbjeukendrup** [comment] 2024-10-28 16:22
Closing as per the comment above. I'd like to echo Marc's advice: please ask on the forums first (https://musescore.org/en/forum/6) before going to GitHub. Thanks!

**Closed by cbjeukendrup** 2024-10-28 16:22 UTC
Labels: UI
