### ISSUE TITLE
Unable to display Mixer on Musescore Studio 4.4.x in Linux

### ISSUE THREAD

**Issue by timevortex161** [musescore/MuseScore#25475] opened 2024-11-10 20:44 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Actual Behavior: 1. go to "View" 2. Click on "Mixer" 3. Mixer Panel does not appear anywhere (even as a separate window). 
Expected Behavior: 1. go to "View" 2. Click
 on "Mixer" 3. Mixer Panel appears above interface
Actual Behavior: 1. Click on "Mixer" at top of ribbon 2. Mixer Panel does not appear anywhere (even as a separate window).
Expected Behavior: 1. Click on "Mixer" at top of ribbon 2. Mixer Panel appears above interface

### Supporting files, videos and screenshots

[Screencast_20241110_153120.webm](https://github.com/user-attachments/assets/5f08407f-737d-47df-b46a-9a0cfafc73ae)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Manjaro Linux 24.1.2

### Additional context

I am using the version of musescore studio from flathub.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-11-11 02:45
Can you reproduce this issue with the official supported AppImage build (download and optionally install from musescore.org)?  There have been other reports of people having similar problems with other unsupported third party builds (see for example https://github.com/musescore/MuseScore/issues/24866), but the official AppImage should work fine.

**Comment by cbjeukendrup** [comment] 2024-11-13 00:37
Closing as duplicate of https://github.com/musescore/MuseScore/issues/24866

**Closed by cbjeukendrup** 2024-11-13 00:37 UTC
Labels: UI, awaiting reply from user
