### ISSUE TITLE
When is the solo contrabass going to be added to muse sounds?

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#24524] opened 2024-09-07 09:36 UTC
This instrument is an essential in chamber ensembles, jazz bands, and contemporary music, it's a surprising fact that the solo contrabass
hasn't been added yet.

**Comment by oktophonie** [comment] 2024-09-07 09:48
Duplicate of https://github.com/musescore/MuseScore/issues/23152, and in any case would be better asked of the Muse Sounds team directly via Muse Hub.

**Closed by oktophonie** 2024-09-07 09:48 UTC
