### ISSUE TITLE
Copy paste repeats/jumps

### ISSUE THREAD

**Issue by bobniqu** [musescore/MuseScore#23357] opened 2024-06-25 12:58 UTC
### Issue type

Other type of issue

### Bug description

I went to copy and paste a few bars from one score to another. The staff text copied, but the Repeats and Jumps entries do not. I had to retype them all back in.

### Steps to reproduce

Open a score with staff text, repeat and jumps, select and hit Ctl.-C. Then paste it into a whole new score. Staff text pastes, Repeat and Jump entries do not.

### MuseScore Version

4.3.2..........831

### Regression

I don't know

### Operating system

Windows 11.

**Comment by zacjansheski** [comment] 2024-06-25 13:58
This is not a bug, this is a long-requested feature request that needs special design.
I am closing this, https://github.com/musescore/MuseScore/issues/15590  covers the feature request

**Closed by zacjansheski** 2024-06-25 13:58 UTC
Labels: needs review
