### ISSUE TITLE
[MU4 Issue] Title for "repeats & jumps" palette is shown using HTML encoding

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11986] opened 2022-06-11 01:30 UTC
**Describe the bug**
The title is shown as "Repeats &amp;amp; jumps" rather than just "Repeats & jumps"

**To Reproduce**
1. Open/create any score
2. Scroll through the list of palettes until you reach "Repeats &amp;amp; jumps"

**Expected behavior**
Should be just "Repeats & jumps"

**Screenshots**

**Platform information**
 - Windows 10
 
**Additional context**

**Comment by HemantAntony** [comment] 2022-06-11 02:42
Duplicate of #11978

**Closed** 2022-06-11 04:07 UTC

**Comment by wizofaus** [comment] 2022-06-14 22:49
It's got worse:

![image](https://user-images.githubusercontent.com/5364225/173702013-730d011e-430a-46b8-ab56-b4f6d1bc1f4e.png)

**Comment by cbjeukendrup** [comment] 2022-06-14 23:15
It should be fixed now. But before it was fixed, indeed, every time that you closed MuseScore after making some edits to the palettes, it would get worse.

**Comment by wizofaus** [comment] 2022-06-14 23:17
Is there an explicit command to reset the palette? Surely reset all preferences to factory defaults should do it?

**Comment by cbjeukendrup** [comment] 2022-06-14 23:19
You can click the '...' button on any palette and click "Reset palette" in the menu.

**Comment by wizofaus** [comment] 2022-06-14 23:27
Ah, I'd only tried the ... in the Palettes dock tab, as I assumed you were resetting all palettes.  So how *do* you reset absolutely everything, including all palettes? Shouldn't reset to factory defaults in preferences do that?
