### ISSUE TITLE
Unable to select multiple parts in Parts dialog

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#23243] opened 2024-06-14 06:21 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

It is not possible to select multiple parts in Parts dialog.

### Steps to reproduce

1. Score with multiple instruments
2. Open Parts dialog
3. Try to select multiple parts (Ctrl + Click, or Shift + click)
4. see - only single part is selected (last clicked, ignoring modifier keys)

### MuseScore Version

master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Mint (Ubuntu 22.04)

**Comment by bkunda** [comment] 2024-06-14 13:09
Unable to reproduce on macOS (14Jun master nightly).

**Comment by oktophonie** [comment] 2024-06-14 13:11
Couldn't reproduce this myself (Artix Linux) either - curious!

**Comment by MarcSabatella** [comment] 2024-06-14 13:20
See also https://github.com/musescore/MuseScore/issues/18456 - apparently it has sometimes worked on some system, never (or least not, not in any released version) worked on others.  On the systems where it does work, it definitely only works using mouse, not using keyboard.  That’s filed separately as https://github.com/musescore/MuseScore/issues/11848

**Comment by zacjansheski** [comment] 2024-06-14 19:15
Let's close this and refer to https://github.com/musescore/MuseScore/issues/11848

**Closed by zacjansheski** 2024-06-14 19:15 UTC
Labels: needs info, regression, UX/interaction, os: linux
