### ISSUE TITLE
Very high/low piano note playback issues

### ISSUE THREAD

**Issue by cdeil** [musescore/MuseScore#25779] opened 2024-12-09 00:23 UTC
### Issue type

General playback bug

### Description with steps to reproduce

Reproducer:

1. Open attached `piano_high_low_notes.mscz`
2. Select MSBasic -> Grand piano and play it (recording attached)
3. Select Muse -> Grand piano and play (recording attached)

This is the example:

<img width="649" alt="Screenshot 2024-12-09 at 01 12 56" src="https://github.com/user-attachments/assets/b8f73aa6-f387-43d5-9a49-b18a6f2047a3">

Observations

With MSBasic -> Grand piano I hear the following issues:
* Note 3 is played as C8 (should be C-1)
* Note 4 is not played (should be C8)
* Note 6 is played as C8 (should be C9)

With Muse -> Grand piano I hear the following issues:
* Note 3 is played ad C8 (should be C-1)
* Note 6 is played as C8 (should be C9)
* Note 8 is not played (should be C0)

See notes below also.

### Supporting files, videos and screenshots

[piano_high_low_notes.mscz.zip](https://github.com/user-attachments/files/18054658/piano_high_low_notes.mscz.zip)

MSBasic Grand Piano recording:

https://github.com/user-attachments/assets/29c1a7e9-eb21-4b95-b4f6-cfac256cc394

Muse Grand Piano recording:

https://github.com/user-attachments/assets/918da54d-1fd9-4c76-8d88-ac6ec770f40b

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 15.1, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

macOS 15 Sequoia

### Additional context

Generally playback within the normal piano range A0 - C8 is fine with both MSBasic and Muse grand piano.

MSBasic has a weird behavior where playing a note below the usual range A0 does generate one very high note C8 if and only if in the playback before there was a very high note already. See recording. This is probably a bug? Notes played shouldn't depend on what was played possibly long before but be more deterministic only depending on last or recent notes?

Muse behavior main issue is that it is silent outside the normal piano range (below A0). That's OK I guess. But then starting with B-1 and below down to C-1 it starts playing again, very high note C8. That's probably a bug where somehow the -1 octave is handled incorrectly and it should be silent there also?

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-12-09 02:51
This looks a bit like a duplicate of https://github.com/musescore/MuseScore/issues/16657

**Closed** 2024-12-10 15:02 UTC
Labels: duplicate, playback

**Comment by cdeil** [comment] 2024-12-11 10:54
What confused me most is that with MS Basic grand piano after playing a note like C-1 the playback is somehow (invisibly) in a buggy state.

In example above: Note 4 is **not** played (should be C8)

The same behavior is there for any other normal range note like e.g. C4 after playing a very low below C0.

@cbjeukendrup - is this covered by your #16657 or a new/separate bug?

**Comment by cbjeukendrup** [comment] 2024-12-13 16:39
I'm not 100% sure, but I added a comment about this to https://github.com/musescore/MuseScore/issues/16657, to be sure it will be looked at. If, when fixing https://github.com/musescore/MuseScore/issues/16657, it turns out that there is a separate problem, we can create a new issue at that moment.
