### ISSUE TITLE
[MU4 Issue] New workspace cannot be selected

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#11987] opened 2022-06-11 04:18 UTC
**Describe the bug**
After creating a workspace, you cannot "select" it

**To Reproduce**
1. Create a workspace
2. After that, click Select in the Create new workspace dialog
3. In the Workspaces dialog, click select again
4. The Workspace will not be selected (or opened)

**Expected behavior**
New workspaces should be opened

**Screenshots**

https://user-images.githubusercontent.com/88136054/173172214-7ca416cd-e55d-4ff9-a326-d4c01cce8943.mp4

**Platform information**
 - OS: Windows 11

**Comment by Tantacrul** [comment] 2022-06-11 17:17
Can't reproduce on MacOS, so it must be a Windows thing? Possibly a Linux thing too.

**Comment by HemantAntony** [comment] 2022-06-12 10:33
I can't seem to reproduce now too. If I am able to do so, I will open this again. I might have done something differently

Closing

**Comment by HemantAntony** [comment] 2022-06-27 07:26
@Tantacrul I updated the issue, can you try to reproduce now with the updated steps?

**Comment by Tantacrul** [comment] 2022-06-27 08:16
Thanks @HemantAntony! So, on the latest nightly (MacOS), I cannot reproduce this. I'll check on Windows later, although it would be great if someone else could also test to see if we can identify the cause.

**Comment by Eism** [comment] 2022-06-27 08:25
Can't reproduce on Windows on the latest nightly and on local build
@HemantAntony Are there any errors in the log?

**Comment by HemantAntony** [comment] 2022-06-27 08:58
@Eism These are the error in the log:
![image](https://user-images.githubusercontent.com/88136054/175901031-e8c67738-497e-4d76-bba5-75e5734f1175.png)

This happens as soon as I click the 'Select'

**Comment by HemantAntony** [comment] 2022-06-27 08:59
Also after you close and then open MuseScore after this, you will be able to select Workspaces

**Comment by Eism** [comment] 2022-06-27 09:23
I think you need to debug and understand at what step the workspace is not created and why.
Because no one can reproduce(and the developers too)

**Comment by HemantAntony** [comment] 2022-06-27 10:19
@Eism I have found out why it isn't working for me. When you open MuseScore, the following folders are there in `C:\Users\heman\AppData\Local\MuseScore\MuseScore4Development`:
![image](https://user-images.githubusercontent.com/88136054/175918882-f45fbd56-28d3-4c23-a1d0-f2630d9a417b.png)

However, when you reset to factory defaults, you delete four of them:
![image](https://user-images.githubusercontent.com/88136054/175918995-e4aaaf78-5d8c-4181-9960-be3887e7165b.png)

But when you open MuseScore for the second time, these folder get automatically created:
![image](https://user-images.githubusercontent.com/88136054/175919096-d51651f7-45a9-4349-a470-8992cef7ceff.png)

So the reason why I am getting the error is because you are trying to open a path containing one of these deleted folders. Hence the file does not open:
![image](https://user-images.githubusercontent.com/88136054/175919573-09da6ffa-098f-4b7d-a165-551c6c111704.png)

**Comment by Eism** [comment] 2022-06-27 11:01
Thanks! I can reproduce this bug
Should be fixed in #11353

**Comment by DmitryArefiev** [comment] 2022-07-04 16:18
Fixed in #11390

**Closed** 2022-07-04 16:20 UTC
Labels: P1
