### ISSUE TITLE
[MU4 Issue] If note or rest selected, key signature from palette is applied only to selected staff

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12331] opened 2022-07-09 17:07 UTC
**Describe the bug**
If a note or rest is selected, or when you are in note input mode, and you click a key signature in the Palettes, it is applied only to the selected staff.

**To Reproduce**
1. Select a note or rest, or enter note input mode
2. Click a key signature in the Palettes
3. It is applied only to the staff containing the selected note or rest, or containing the note input cursor.

**Expected behavior**
It should be applied to all staves. Only when using the Ctrl/Cmd modifier, it should be applied to a single staff.

**Platform information**
 - OS: reported on macOS

**Additional context**
If a full measure is selected, or when dragging a key signature instead of just clicking it, it works as expected.
It does not apply to time signatures, only to key signatures.

**Comment by MarcSabatella** [comment] 2022-07-09 19:31
You probably noticed this, but it's true for MuseScore 3 as well.  While it was originally by design, it's one that nearly everyone agrees was a mistake.  It stemmed from the desire to allow mid-measure key changes, and in that case - if the selected note/rest is not at the start of a measure - it could arguably make sense to make it per-staff.  After all, there is no guarantee the selected segment makes sense on any other staff (it might be in the middle of a whole note).  Or we could just disallow this, and I doubt many would complain.

**Comment by wizofaus** [comment] 2022-07-10 20:15
So what *is* the supported way in v3 to add a key signature part way through a measure so that it applies to all staves? (even if it would require splitting/padding rests etc.)

**Comment by MarcSabatella** [comment] 2022-07-10 20:24
Either add it one staff at a time, or - usually a much saner choice if you really need a mid-measure key change - split the measure then add normally to the second half.  Both methods continue to work in MU4.

Hmm, actually, maybe the smart thing to do if a single note mid-measure is selected when you add the key signature is just go ahead and do the split there, only adding the single-staff mid-measure key signature if you hold Ctrl.

**Comment by wizofaus** [comment] 2022-07-10 20:34
Mid-measure key changes aren't that uncommon!  Having to split measures before adding one (then rejoining afterward) seems more than a bit clunky.

**Comment by MarcSabatella** [comment] 2022-07-10 20:48
I didn't say anything about rejoining - not sure that was ever supported.  You can hide the barline if you want to create the illusion of a single measure.

Splitting measures has always been the supported way of doing pretty much *anything* mid-measure that normally only happens at measure boundaries - system breaks, repeats/voltas/segno/fine/coda, etc.

**Comment by wizofaus** [comment] 2022-07-10 21:31
It would never even occur to me that it was an illusion - there are plenty of times it makes sense to change key signature mid-measure.  The other examples you give there are good reasons why it's problematic to have mid-measure.

**Comment by Tantacrul** [comment] 2022-07-11 10:03
@oktophonie - feels like this one could potentially be for you? Not sure the solution you'd prefer.

I'm bumping to 4.x. For the moment, since it is already an issue with V3.

**Comment by mike-spa** [comment] 2023-06-19 08:58
Resolved in #17237

**Closed by mike-spa** 2023-06-19 08:58 UTC
Labels: P2, UX/interaction
