### ISSUE TITLE
Text starts floating away on mouse-over on Master Palette

### ISSUE THREAD

**Issue by denilsonsa** [musescore/MuseScore#16584] opened 2023-02-28 09:47 UTC
### Issue type

UI bug

### Bug description

After opening the "Master Palette", and selecting "Tempo", moving the mouse over the palette items make their text move upwards. Doesn't seem to happen to any other category.

### Steps to reproduce

1. Freshly installed the [musescore](https://archlinux.org/packages/community/x86_64/musescore/) on [Manjaro Linux](https://software.manjaro.org/package/musescore) (using KDE/Plasma). First time using musescore, so you can assume a mostly empty configuration.
2. Open MuseScore, go through the initial setup wizard, create a new score.
3. Go to View → Master Palette.
4. Select "Tempo".
5. Move the mouse over the items.

Bug: some of items start flying away upwards.

Note: this bug does not happen at the Palettes sidebar, so far I only saw it at the Master Palette dialog.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/121676/221816085-10108dda-4f63-4162-a48e-39fd033afc04.mp4

### MuseScore Version

4.0.1

### Regression

I don't know

### Operating system

Manjaro Linux x86_64

### Additional context

* KDE/Plasma desktop
* Intel HD Graphics 530
* Xorg (NOT wayland)

**Comment by oktophonie** [comment] 2023-02-28 10:26
Duplicate of https://github.com/musescore/MuseScore/issues/15297 (and fixed in 4.0.2)

**Closed by oktophonie** 2023-02-28 10:26 UTC
Labels: UI
