### ISSUE TITLE
[MU4 Issue] Scrolling horizontally with trackpad in mixer causes faders and pan knobs to move

### ISSUE THREAD

**Issue by DonnyCraft1** [musescore/MuseScore#14879] opened 2022-12-01 18:59 UTC
**Describe the bug**
When scrolling horizontally (with two fingers on a trackpad) in the mixer, the faders and knobs sometimes moves if the pointer is hovering over a fader or knob. And thus, the sideways scroll doesn't happen either.

**To Reproduce**
1. Be sure to have sufficient instruments added so that the mixer can scroll horizontally
2. Go to View -> Mixer
3. While hovering over a fader or knob, scroll horizontally with two fingers on a trackpad
5. See error: Fader or knob moves

**Expected behavior**
In all DAWs I can remember using, scrolling while the pointer is hovering faders or knobs, does not affect them. I.e. in Logic Pro, scrolling sideways, and up/down in the mixer, causes the window to move/scroll and does not affect the faders at all. I'm not the one to say what the expected behavior should be. Either it should be like in Logic Pro, where faders are not affected by scrolling at all (you use your mouse to click and drag instead). Alternatively, the faders should only respond to scrolling that's clearly done in the vertical direction.

**Screenshots**
Not necessary

**Platform information**
 - OS: macOS

**Additional context**
OS: macOS 13.0, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072008, revision: github-musescore-musescore-2c34155

**Comment by DonnyCraft1** [comment] 2022-12-01 19:00
I don't have a mouse to further test the behaviour with mouse scrolling. If someone can provide additional info about this, the issue can be generalised to include all types of scrolling.

**Comment by Eism** [comment] 2022-12-01 19:18
Thanks for logging, but it is duplicate of #11128

**Closed by Eism** 2022-12-01 19:18 UTC

**Comment by DonnyCraft1** [comment] 2022-12-01 20:20
I see. Tried to find if it had been logged before, but I didn't find it for some reason.
