### ISSUE TITLE
[MU4 Issue] If the first note of a triplet is tied, the second note of the triplet is swung (musesound playback).

### ISSUE THREAD

**Issue by sikamber** [musescore/MuseScore#14172] opened 2022-10-29 20:12 UTC
**Describe the bug**
If the score plays in a swing rhytm, and a note is tied into the first note in a triplet, the second note in the triplet is delayed. If the swing ratio is 66%, it effectively disappears into the third.

**To Reproduce**
1. Set the rhytm of a section of music to swing.
2. Enter a triplet where the three notes are the same AND the first one is tied to a previous note.
4. Set the playback instrument to a Musesounds instrument (possibly only affects piano)

**Expected behavior**
I expect the second note of the triplet to play with normal triplet timing.

**Screenshots**
In the score below, playback of the the indicated note is delayed:
![image](https://user-images.githubusercontent.com/28673463/198850714-dd4ce4aa-8566-42bc-8bdd-d0e7dc83943c.png)

**Platform information**
 - OS: Windows (Musescore 4 beta)

**Additional context**
- I only have piano musesounds installed, so I can't tell if others are affected. (well, I have choir too, but I can't tell if the note plays of if its just sustain from the previous one).
- The issue does not appear with musescore basic sounds
- The issue does not seem to happen if any of the notes in the triplet are different from the others
- The issue does not seem to happen if the first note in the triplet is not "tied into" (the first triplet in the screenshot above plays fine)

**Comment by Tantacrul** [comment] 2022-11-27 13:46
There have been a lot of improvements to tuplets over the last few days. Some are merged. Some are about to be. Check out this score.

This issue is still present but only on repeats of the same note.
https://www.dropbox.com/s/0ccvj31x6km42dh/Swing_MS_Basic_VS_Muse_Sounds.mscz?dl=0

**Comment by MarcSabatella** [comment] 2023-01-23 04:43
FWIW, a report of this on musescore.org - https://musescore.org/en/node/343075, and I can confirm it's an issue.  In this case, it's MS Basic, and the note gets played staccato.  Same basic combination of triggers - swing, triplets, ties, and repeated notes.

![image](https://user-images.githubusercontent.com/1799936/213966794-41cea3d6-4dd4-4594-b12b-dfdb52564925.png)

First note of the triplet gets cut short.

**Comment by Tantacrul** [comment] 2023-01-23 19:52
@MarcSabatella - this feels like a new issue. I think we should close this one and potentially open another. What do you think?

**Comment by MarcSabatella** [comment] 2023-01-23 20:41
I'm not sure.  I suspect it's the same cause as it seems too much coincidence that both involve swing, ties, triplets, and repeated notes.  But I can't prove it.

In the original example, currently, the first two beats play fine for me in both Muse Sounds and MS Basic, but the second two beats are problematic in both.  In Muse Sounds, the middle note of the triplet is missing the attack and seems strangely quiet as a result.  In MS Basic it is played short.  I would bet this is due to an error in the basic calculation of the swing with respect to the ties and triplets, but it has different symptoms in MS Basic vs Muse Sounds due to the differences in how they treat overlapping repeated notes (in particular, with respect to https://github.com/musescore/MuseScore/issues/13853).

**Comment by Tantacrul** [comment] 2023-01-28 14:22
To summarise: for this issue, the delay is a little hard to hear unless you put it at a slow tempo... but it is definitely there.

This is a setup that makes the problem obvious. The piano delays behind the harpsichord where the notes are blue (Muse Sounds). With MS Basic, there appears to be a small staccato on the blue notes (they don't play their full duration)

<img width="490" alt="image" src="https://user-images.githubusercontent.com/21022311/215271582-cd4a56c4-1e8f-418a-bcdf-02fc225e3df6.png">

**Comment by abariska** [comment] 2023-02-03 11:41
🟢 **FIXED**
Tested on macOS 12

**Closed** 2023-02-03 11:45 UTC
Labels: P1

**Comment by bkunda** [comment] 2023-03-06 10:26
🟢 Re-tested in 4.0.2 on macOS. Remains FIXED.
