### ISSUE TITLE
General purpose toolbar/ribbon missing

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21644] opened 2024-02-22 15:47 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In nearly all Windows applications, as there was in previous versions of museScore, there was a general purpose toolbar of icons for standard common functions such as Save, Print, Undo, etc.

### Steps to reproduce

Simply missing and replaced by File and Edit Menu Options

### MuseScore Version

4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

![Musescore 3 toolbar](https://github.com/musescore/MuseScore/assets/7720669/903528f3-0afb-44a8-b0db-09b109309531)

**Comment by MarcSabatella** [comment] 2024-02-22 15:50
This is by design but as with any design subject to change if there is sufficient interest.  See https://github.com/musescore/MuseScore/issues/18896 which requested this previously.

In the future, please try searching for existing issues on a given topic before open new opes.  Or start a discussion on the Support forum at musescore.org to gather feedback first.

**Comment by zacjansheski** [comment] 2024-02-23 14:26
Closing per comment above

**Closed by zacjansheski** 2024-02-23 14:26 UTC
Labels: regression_ms3, UX/interaction
