### ISSUE TITLE
Muse Hub not installing on Linux Mint 20.3

### ISSUE THREAD

**Issue by musescorebeta1** [musescore/MuseScore#14048] opened 2022-10-26 00:11 UTC
Linux Mint 20.3: Musehub.deb extracts & installs but fails during launch.

**To Reproduce**
extract musehub.deb
install
run app

**Expected behavior**
Musehub app should load

**Screenshots**
n/a

**Platform information**
Linux Mint 20.3

**Additional context**

**Comment by Tantacrul** [comment] 2022-10-27 21:48
Can you provide any more information or a video? Does you get any errors?

**Comment by rgreen5** [comment] 2022-10-28 09:12
Similar to #13909.

**Comment by Tantacrul** [comment] 2022-10-28 09:36
Thanks @rgreen5 

Duplicate of https://github.com/musescore/MuseScore/issues/13909

**Closed by Tantacrul** 2022-10-28 09:36 UTC
