### ISSUE TITLE
[MU4 Issue] Inspector doesn't update when changing property default in Style dialog

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12480] opened 2022-07-19 17:25 UTC
**Describe the bug**
If you edit the default value for a property using the Style dialog, the new value is not reflected in the Inspector, even though the property of the item itself does change.

**To Reproduce**
1. On a score, select an element in the Inspector (for example a note) and find a "styled" property in the Inspector.
2. Open the Style dialog, and find the corresponding style setting.
3. Change this setting. Notice that the item on the score is updated (unless the property of that item was modified of course), but that the Inspector keeps showing the old value. 

**Expected behavior**
If the value of a property of an item is updated, the Inspector should reflect this, even if the update happens because the property is following its corresponding style setting that is updated.

**Screenshots**

https://user-images.githubusercontent.com/48658420/179811844-1fdec3df-310c-419b-9d35-53b60ca23cbc.mov

**Platform information**
 - OS: reported on macOS

**Comment by cbjeukendrup** [comment] 2022-07-19 17:34
There's another closely related bug here:

1. Modify a styled property (for example, set the stem thickness of a note to 0.3sp)
2. while keeping the element selected (so that the Inspector stays unchanged), open the Style dialog
3. modify the value of the corresponding style setting (for example, change the default stem thickness from 0.1sp to 0.8sp)
4. In the Inspector, reset the modified property.
Expected: the property gets the new default (for example, stem thickness becomes 0.8sp)
Actual: the property gets the old default (for example, 0.1sp)

**Comment by wizofaus** [comment] 2022-07-23 03:40
Can't reproduce because a) Format|Style is disabled when a note is selected for me b) most of those properties (e.g. stem thickness) actually showing as blank for me...

**Comment by wizofaus** [comment] 2022-07-23 04:41
Ok I have a fix for this problem, as well as the bug as reported here, and as it happens also for the issue with undo/redo for styles.

Basically now if you change a property value to the current style default by any means, it gets the STYLED flag, meaning that changes to the style default will be reflected.  On the other hand, if a particular element has a property with a certain value that's currently *not* the style default (e.g. 0.2 stem thickness) and you then change the style default to match that value, the STYLED flag is NOT set.  There's no way you can distinguish in the UI between a property value with or without the STYLED flag set (unlike v3), but 95% of the time it really won't matter, and you can always ensure it's set by changing the value then using "reset to default".

**Comment by wizofaus** [comment] 2022-08-01 22:50
@Tantacrul this is the issue I wanted to chat to you about, let me know when you have time.

**Comment by DmitryArefiev** [comment] 2022-09-21 14:42
Fixed in #13083

**Closed** 2022-09-21 19:18 UTC
Labels: P1
