### ISSUE TITLE
Instrument change text does not include transposition.

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#24575] opened 2024-09-09 10:56 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Set up a score with e.g. Bb clarinet
2. Add an instrument change text and select Clarinet in A - using the dropdown to select the transposition
3. Note that the text reads "To clarinet" and not "To A Clarinet".

### Supporting files, videos and screenshots

![Screenshot 2024-09-09 115534](https://github.com/user-attachments/assets/3142a0aa-0cce-4bd1-8260-81c794cffab8)

![Screenshot 2024-09-09 115550](https://github.com/user-attachments/assets/226343cb-19c0-474b-9ce9-f3d537c90ec5)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

I guess that this results from the change to a dropdown to select the transposition rather than using separate entries in the instrument list for each transposition.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by SteveBlower** [comment] 2024-09-24 16:50
Another user has also noted that the long and short instrument names are changed from including the transposition to a generic name without the transposition - e.g.   Clarinet in Bb/Cl. in Bb becomes Clarinet/Cl.

See https://musescore.org/en/node/369301

**Comment by Dima-S-Jr** [comment] 2024-10-28 14:20
Duplicate of #22762

**Comment by zacjansheski** [comment] 2024-11-12 16:21
Closing as duplicate of https://github.com/musescore/MuseScore/issues/22762

**Closed by zacjansheski** 2024-11-12 16:21 UTC
Labels: P2, regression MS3, UX/interaction
