### ISSUE TITLE
Crash on Add Instrument and Move to Top of Staff Stack

### ISSUE THREAD

**Issue by manonash** [musescore/MuseScore#16780] opened 2023-03-13 19:26 UTC
### Issue type

File corruption

### Bug description

Steps to reproduce:
1. Load attached score.
2. Activate the Instruments tab.
3. Add a piano.
4. Move the new piano to the top of the list of instruments.
5. Click [Ok]

Result (in version 4.0.2):
1. The new piano staff gets added, but with no lines.
2. Attempting to quit MU4 results in the dialog asking whether I want to save the changes. Whether I respond with [Save] or [Don't Save], MU4 crashes.
3. If I do save the score, attempting to re-open it (after restarting Musescore) results in a message that it is corrupted. Details of the corruption are shown in the second attachment.

### Screenshots/Screen recordings

![Add Piano Corrupted Score](https://user-images.githubusercontent.com/42229842/224810688-8c3c969b-4144-43d0-a473-499c37a238eb.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

[Add Piano Crash Test.zip](https://github.com/musescore/MuseScore/files/10960982/Add.Piano.Crash.Test.zip)

**Comment by cbjeukendrup** [comment] 2023-03-19 14:32
I found that the steps to reproduce are _slightly_ different:
- when I add a piano, it gets added at the top by default
- when I move the _existing_ piano, which is at the third position, to the top, _then_ I get the described behaviour.

https://user-images.githubusercontent.com/48658420/226182839-90bcf2dd-6e31-4c23-a59c-20746f4b4d49.mov

**Comment by cbjeukendrup** [comment] 2023-03-19 21:57
I also managed to reproduce a similar situation from scratch in a new score, so it's not specific to this score. The steps are:
1. In the New Score dialog:
    1. select "Orchestral" score order (is already selected by default)
    2. add two violins and piano
    3. move the piano to the bottom
    4. Click "Done" to create the score
2. Open the instruments dialog and:
    1. and add another piano. Because of the orchestral score order, this new piano will appear at the top. 
    2. Move the existing piano (which is at the bottom) to the top, above the newly added one
    3. Click OK
    -> immediate crash

https://user-images.githubusercontent.com/48658420/226212079-bb18496d-739c-49d5-b33f-326014728840.mov

**Comment by DmitryArefiev** [comment] 2023-04-10 15:21
Fixed in #16927

**Closed** 2023-04-10 15:29 UTC
Labels: regression, corruption, crash
