### ISSUE TITLE
[MU4 Issue] Multiple instances of system text when re-showing voices

### ISSUE THREAD

**Issue by bmacs001** [musescore/MuseScore#15549] opened 2022-12-24 01:06 UTC
When in a part with multiple voices, when you hide one voice then make it reappear, system elements like tempi and rehearsal marks reoccur for each voice, and are linked to each part's visibility

Reproduce with two voices:
-Create a score with one instrument having two voices
-Add a system element, like a rehearsal mark or a tempo mark
-Go to the part with the instrument with two voices and hide one voice
-Make this voice reappear- there are now two system elements
-Hide either voice- the duplicate element is hidden as well
-Show this voice again- the duplicate element reappears.

This scales to three and four voices as well- hiding one voice and making it reappear seems to create a new instance of the system element attached to the voice

What should happen is that, no matter how many voices are shown in a part, the system elements should only occur once.

MuseScore 4.0.0, MacOS 13.0.1

**Comment by oktophonie** [comment] 2022-12-24 09:03
In what way do you 'hide' the voice?
Can you attach a score, or at least a screenshot?

**Comment by bmacs001** [comment] 2022-12-24 13:49
https://user-images.githubusercontent.com/71397009/209438763-6292e563-82a6-4fb9-ad37-52ca74778189.mov

**Comment by oktophonie** [comment] 2022-12-24 15:13
Thanks for the video!
It appears that this will be fixed by https://github.com/musescore/MuseScore/pull/15389.
As such, I'll close this as a duplicate of https://github.com/musescore/MuseScore/issues/15371.

**Closed by oktophonie** 2022-12-24 15:13 UTC
