### ISSUE TITLE
4.0.2 File crashes when specific Muse Sounds instrument enabled

### ISSUE THREAD

**Issue by Prestopizza** [musescore/MuseScore#17574] opened 2023-05-15 23:24 UTC
### Issue type

Muse Sounds bug

### Bug description

File saved in 3.6.2 with history on earlier versions (as far back as version 1) would not open on 4.0.2. No VSTs but was using Muse Sounds as default. Another user saved the file for me in 4.0.2 with Muse Basic sounds. I was then able to open in 4.0.2.

However, it now crashes when enabling specifically only Muse Sounds tubular bells. All other instruments (string section, brass, woodwinds and timpani) can be changed to Muse Sounds with no isse. When it crashes, the program stays open, just the specific project crashes. If MuseSounds tubular bells are enabled before opening file, file will try to load then crash. Other instruments may have this tosame effect but not tested.

Jojo-Schmitz notes he cannot open original 3.6.2 file in 4.0.2 even though Muse Sounds is not enabled.

Note also this project may be on the larger side at 253kb.

### Steps to reproduce

1. Open file
2. Enable Muse Sounds tubular bells on an instrument
3. Cry

### MuseScore Version

4.0.2

### Regression

Choose option...

### Operating system

Windows 11

**Comment by zacjansheski** [comment] 2023-05-17 22:32
Hello!  Are you willing to share the score file?  If not, is there a way to replicate this issue without the score?

I have taken a few large scores saved in 3.6.2 with chimes/tubular bells through the process described and I was not able to replicate the issue.

**Comment by Prestopizza** [comment] 2023-05-18 11:11
Hey, sorry new to Github and don't know if I can upload the file here, but here is the Musescore forum post where the file is posted in the original question: [https://musescore.org/en/node/349936](url)

**Comment by oktophonie** [comment] 2023-05-18 12:41
To upload a file on GitHub, either put it into a .zip, or just rename the .mscz to .zip.

**Comment by zacjansheski** [comment] 2023-05-18 14:01
I am unable to recreate the issue on Mac OS
Here is the file in question, does the tubular bell issue persist on Windows?

[MS3.6.2File.mscz.zip](https://github.com/musescore/MuseScore/files/11508374/MS3.6.2File.mscz.zip)

**Comment by zacjansheski** [comment] 2023-05-18 22:17
I am unable to open on windows 11

**Comment by cbjeukendrup** [comment] 2023-05-18 22:27
Actually this must be another duplicate of #16642. I'll try to run it in the debugger tomorrow to be really sure.

**Comment by zacjansheski** [comment] 2023-06-02 17:35
Closing now that Muse Sounds has been updated.  Please let us know if the issue persists.

**Closed by zacjansheski** 2023-06-02 17:35 UTC
Labels: needs info, muse sounds
