### ISSUE TITLE
[MU4 Issue] - Play Back Export Normalization Error 

### ISSUE THREAD

**Issue by NoahEmmert** [musescore/MuseScore#15157] opened 2022-12-13 22:16 UTC
Hello I am having a Play back issue when exporting a .mp3 file. 
I am not sure if this is because I have to use the mixer to solve this issue but on the video I have show you it seems not to loud. 
Not sure why everything is not playing back "normalized" on the software everything seems to be not as loud until you export the score. I have been having this issue sense day 1 of MS4. I hope my video can help too. 

Thank you for your time.

Video Evidence: https://youtu.be/RvaAS_PQYZk

**Comment by jeetee** [comment] 2022-12-13 22:31
As mentioned via Discord, this is very much **by design**.

Imagine the following scenario if MuseScore would automatically normalize during live synthesis:
(1) have only your first measure in ppp and nothing else yet. You press play and get blasted at full volume.
(2) You then add something in forte in the 2nd measure and play back again and now your first measure is suddenly a lot more quiet
Most people would find this behavior jarring.

When exporting audio on the other hand, the default action is to also Normalize so that when playing back different audio files a file with a dynamic range of only (p - f) will still sound about as loud on its loudest point as a file with range (ppp - ff). That way you don't have to continuously adjust your speaker volume when playing back a playlist of random songs.

**Comment by MarcSabatella** [comment] 2022-12-13 23:20
Also, applying normalization during live playback isn't really practical - it requires first generating all the audio, then detecting the peak, then adjusting.  If this happened during playback, it could take several minutes of processing before you even press Space to begin.

**Comment by zacjansheski** [comment] 2023-07-24 20:09
Closing as by design (per comments)

**Closed by zacjansheski** 2023-07-24 20:09 UTC
Labels: playback
