### ISSUE TITLE
[MU4 Issue] Very Janky Playback

### ISSUE THREAD

**Issue by ThatBoiTho199** [musescore/MuseScore#12840] opened 2022-08-13 02:57 UTC
**Describe the bug**
Playback has a horrible amount of crackle, fails on Pedal playback, and is overall just janky. Also, the soundfont is MS Basic somehow?

**To Reproduce**
1. Click on a supported file
2. Click on Play

**Expected behavior**
Playback with correct pedal playback, and no crackles.

**Screenshots**
Video available: https://youtu.be/XHSbKSJfySQ

**Platform information**
 - OS: Windows 11 64-bit
 - CPU: Intel Core i3 11th Gen
 - RAM: 4GB

**Comment by KaiVinter** [comment] 2022-08-13 03:17
Can you share a video with the sound?
It works fine for me.
Also, the "MS Basic" was a rename of the "MuseScore_General_HQ" soundfont, so it looks better in the new Mixer.
You should also mention what build of MS4 you tested on. Was it the Alpha 2 or one of the Nightlies after the Alpha?

**Comment by ThatBoiTho199** [comment] 2022-08-13 03:54
It was the Alpha 2, and sure, I can send you a video.

**Comment by KaiVinter** [comment] 2022-08-13 04:31
Please upload the video here so one of the developers can see your issue

**Comment by ThatBoiTho199** [comment] 2022-08-14 01:12
https://youtu.be/XHSbKSJfySQ

video

**Comment by mattblo** [comment] 2022-08-15 05:24
Does it not help to set the buffer size in the I/O settings to a higher value (e.g. 4096)?

**Comment by ThatBoiTho199** [comment] 2022-08-15 15:35
@mattblo Hello, so the I/O settings got rid of all the crackles, but the pedal playback still doesn't work, and I might've forgot to mention this but some notes in chords just, don't play, especially when they're combined with notes from staff, some will just flat out not play, with that sometimes the playback will suddenly be loud and then soft. Thanks for the crackle fix though.

**Comment by MarcSabatella** [comment] 2022-08-15 15:51
The issue with tied notes is known and reported separately in https://github.com/musescore/MuseScore/issues/12767

FWIW, my Windows system also seems to need a higher than default buffer size.

Playback of pedal works for me in some cases not in others.  I will submit a separate issue for that with precise steps to reproduce that problem.

**Comment by Tantacrul** [comment] 2022-08-31 21:03
I think much of what is described here has been described elsewhere, so I'm going to close this, since the issue is too wide and unclear.

As a rule, it is always best to pinpoint a specific problem in every issue, rather than multiple issues. In that way, one person could look at pedals, another at crackling/buffer issues, etc.

**Closed by Tantacrul** 2022-08-31 21:03 UTC
