### ISSUE TITLE
When open parts, Musescore freezes and unexpectedly exits (one score)

### ISSUE THREAD

**Issue by Xenooooooooo** [musescore/MuseScore#25192] opened 2024-10-17 05:41 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open a mscz file of full orchestra ([see comment](https://github.com/musescore/MuseScore/issues/25192#issuecomment-2419076268))
2. click export parts
3. Musescore freezes

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/056ab38c-f5b3-46a4-8ef2-7910562195b1)

https://github.com/user-attachments/assets/a7e4730e-06da-4d0f-8f95-b8d752616bdc

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Doesn't occur in **4.3.2**

### Operating system

Windows 11

### Additional context

It's unable for me to install the previous version of Musescore:
1. The mscz file generated under later version cannot be read under previous version of Musescore;
2. The previous version cannot be installed when a later version is existed

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment] 2024-10-17 09:39
I can't reproduce it.. Please add the score (zip before attaching)

**Comment by Xenooooooooo** [comment] 2024-10-17 09:51
Here is the file:
[jasmine - upload.zip](https://github.com/user-attachments/files/17410011/jasmine.-.upload.zip)

**Comment by Xenooooooooo** [comment] 2024-10-17 09:53
For me, it's still not working, still freezing.

https://github.com/user-attachments/assets/239f18f0-e7f4-4e55-9f56-1c4670d05ba3

**Comment by DmitryArefiev** [comment] 2024-10-17 10:39
Thanks! Now I can reproduce it on my side, in **4.4.0 - 4.4.2**.  But in **4.4.3 nightly builds** the issue **no longer occurs**.

You can use 4.4.3 nightly builds for now (e.g. portable version) to continue working on score, or just wait for 4.4.3 release (it will be out within a few days or next week)

https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds

**Comment by DmitryArefiev** [comment] 2024-10-17 10:40
Fixed in 4.4.3

**Closed** 2024-10-17 10:41 UTC
Labels: P1, regression MS4, crash
