### ISSUE TITLE
[MU4 Issue] instrument change text changes instrument for wrong staff

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#16303] opened 2023-02-10 06:56 UTC
**Describe the bug**
when there are multiple parts changing instrument at the same time, selecing the instrument for the text on a higher staff line will change the instrument for the staff below it instead of the selected staff

**To Reproduce**
1. add instrument change text
2. copy and paste it to another staff at the same bar above or below it
3. select instrument for the text on the upper staff
4. see the instrument is changed for the bottom staff instead of the intended staff

**Platform information**
windows

**Additional context**
also happened in musescore 3

**Comment by Vykoiazon** [comment] 2023-02-10 08:24
copying and pasting instrument change text which has a pre assigned instrument does not automatically change instrument for the staff it is pasted to like it did in musescore 3 so it has to be pasted, then instrument has to be manually chosen again

**Comment by zacjansheski** [comment] 2023-07-14 19:59
I am unable to reproduce this issue.  Closing unless other details are presented.

**Closed by zacjansheski** 2023-07-14 19:59 UTC
