### ISSUE TITLE
[MU4 Issue] Muse Sounds: Note input has significant sound delay, drop-outs and repeats

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13814] opened 2022-10-18 10:11 UTC
**To Reproduce**
1. Enable Muse Sounds
2. Enter notes

https://user-images.githubusercontent.com/90187801/196401910-50be60ac-25b6-4375-a0e6-c98de43dccaf.mp4

The same with MIDI keyboard input

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur with MS Basic

**Comment by DmitryArefiev** [comment] 2022-10-18 10:22
FYI @Tantacrul

**Comment by sammik** [comment] 2022-10-18 10:32
cant reproduce it ;)

**Comment by cbjeukendrup** [comment] 2022-10-18 10:34
@sammik It only happens in scores with at least one track that uses Muse Sounds.

**Comment by sammik** [comment] 2022-10-18 10:42
> @sammik It only happens in scores with at least one track that uses Muse Sounds.

thats it!

sorry for inapropriete spammig joke

**Comment by Tantacrul** [comment] 2022-10-18 10:59
Yes. I had decided not to try and focus on this for Beta but it's the obvious next thing to look at.

**Comment by cbjeukendrup** [comment] 2022-10-30 14:49
Possibly related issue: #14189. Let's leave both open for now, but when one is fixed, we should definitely retest the other.

**Comment by iamtesch** [comment] 2022-11-23 16:50
Can you try to change the metronome sound back to "MS Basic" and see if this resolves the issue?

**Comment by cbjeukendrup** [comment] 2022-11-23 17:01
@iamtesch For me, that seems to work! So if the Metronome track has any Muse Sounds sound selected, note input sound is laggy, but when Metronome uses MS Basic, it works perfectly (even in a score where multiple instruments use Muse Sounds, so it really seems to be something special with the Metronome track).

**Comment by iamtesch** [comment] 2022-11-23 18:19
This seems to be a Windows only issue; we are looking into it.

**Comment by cbjeukendrup** [comment] 2022-11-23 18:24
Hm, it definitely happens for me on macOS as well. (My MuseSampler version is 0.2.4.7, if that's useful info.)

**Comment by Tantacrul** [comment] 2022-12-01 09:42
I think we can close this one, since the fix has been in for a couple of days now and pushed to the Muse Hub.

**Closed by Tantacrul** 2022-12-01 09:42 UTC
Labels: P0
