### ISSUE TITLE
Muse Hub Breaks Filesystem In External Drives (Linux)

### ISSUE THREAD

**Issue by WinFan3672** [musescore/MuseScore#17704] opened 2023-05-23 20:25 UTC
### Issue type

Muse Sounds bug

### Bug description

When setting the directory for Muse Hub's install to an external USB drive or other media that mounts after login, it breaks the filesystem in a really annoying way.

For example, if you set the install directory to "/mnt/media_x/muse-sounds", it would work perfectly. However, when you reboot, /mnt/media_x is located in /mnt_media_x1, and in its old place, /mnt/media_x contains the muse-sounds folder which is at the default state. 

This can break a lot of other applications, as well as the Hub itself, since anything that points to /mnt/media_x is no longer valid. The only way for the user to fix this is to delete /mnt/media_x and move /mnt/media_x1 to /mnt/media_x.

### Steps to reproduce

1. Install MuseScore and Muse Hub on Linux
2. Set the Muse Hub install directory setting to a location in removable media
3. Reboot
4. When you reboot, the installable media will break in the manner described.

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Linux (Specifically Arch)

### Additional context

This issue likely occurs because the Muse Hub service attempts to access the location on startup, before the drive has been mounted, causing an error that is handled by the creation of the directory. This breaks the filesystem in the manner descibed above.

To fix this, the service could either have code edited to handle this or only launch if MuseScore/Muse Hub are launched.

**Comment by oktophonie** [comment] 2023-05-24 13:18
Duplicate of https://github.com/musescore/MuseScore/issues/13981 (or at least very similar)

**Closed by oktophonie** 2023-05-24 13:18 UTC
Labels: needs info, muse sounds
