### ISSUE TITLE
Ornamenting the first note in a tie mutes the second note

### ISSUE THREAD

**Issue by LordQuasi** [musescore/MuseScore#20953] opened 2024-01-11 00:31 UTC
### Issue type

General playback bug

### Steps to reproduce

1. Place a note on an instrument that supports ornamentations (e.g. flute)
2. Go into note input mode with N, select the placed note and press T to add a tied note
3. Go into the ornamentations palette and add an ornamentation to the first note in the tie. Any ornamentation with playback support will create this bug. (i.e. Mordent with upper prefix and Slide do not create this bug)
4. Play back 
5. The tie will not play out

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/110649798/2203a1a7-ccf4-4110-b5ea-760ed040b197

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by zacjansheski** [comment] 2024-01-11 18:17
Similar to https://github.com/musescore/MuseScore/issues/18676

**Comment by bkunda** [comment] 2024-06-06 15:05
I believe this is actually a duplicate of #18676. Certainly, the first example in the demo video there shows the same issue as described here, plus there's a lot of additional detail there that will assist us. 
Thank you for raising this though!

**Closed by bkunda** 2024-06-06 15:05 UTC
Labels: P1, playback, regression_ms3
