### ISSUE TITLE
Chow Matrix instantly crashes MS4

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#21351] opened 2024-02-03 18:54 UTC
### Issue type

VST bug

### Bug description

When selecting Chow Matrix as an effect, MuseScore (4.2.1) instantly crashes.

### Steps to reproduce

1. Install Chow Matrix from the [official site](https://chowdsp.com/products.html)
2. Try to select it as an effect in MuseScore 4.2.1
3. Crash.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 10 Version 2009, Arch.: x86_64

**Comment by RomanPudashkin** [comment] 2024-07-29 09:54
Duplicate of https://github.com/musescore/MuseScore/issues/20341

**Closed by RomanPudashkin** 2024-07-29 09:54 UTC
Labels: crash, VST
