### ISSUE TITLE
[MU4 Issue] Changing Notes to Cue Size in the score does not apply for individual parts, that are already opened

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13572] opened 2022-10-01 21:05 UTC
This forces you to switch to part view
in order to
setup cue notes properly.

**Comment by MarcSabatella** [comment] 2022-10-01 23:21
This is currently by design.  Most layout-related properties are not linked because it can often be necessary to be able to control them independently, and if they were linked, this would become impossible,  Eventually it would be good to have a way to default to linked but then still break the link when required.  That's a very long-standing request.  Anyhow, for now, we have to live with some properties that you might "often" want in sync not being linked, because otherwise, you'd be forced to *always* have them in sync.

**Comment by oMrSmith** [comment] 2022-10-02 09:41
I absolutely comprehend this problematic. My main worry is that setting up cue notes takes so many steps.
Besides that, there is also an inconsistency: If you change notes to cue size in the score and open the part _afterwards_, 
the notes are small in the part too, but not so, if the part is already opened.

**Comment by MarcSabatella** [comment] 2022-10-02 14:12
Yes, someday a native / automatic cue facility/would be great.  I'm just pointing out the current behavior of the layout properties like small and visible with linking is by design and should not be changed  it would break other use cases.

It is also by design that even though changes are not linked after the part is created, the initial value of some properties *are* copied (not linked) from the score when first creating the score.  That's because we do recognize that "most" of the time, you will want that property carried over.  This doesn't break anything, because you can still change them independently after that.  Just a somewhat more convenient default than if we reset all properties on copy.

In general, we try to be smart about which properties get linked and which don't, and of the ones that don't get linked, which get their default value on part creation copied from the score and which do not.

Meanwhile, probably it would be possible to create a plugin to automate much of the work of creating cues.  I wrote one once long ago, but it was before linked parted parts were even a thing.

**Comment by oMrSmith** [comment] 2022-10-02 15:38
> Meanwhile, probably it would be possible to create a plugin to automate much of the work of creating cues.

This would be awesome! The thing is: It took me like three days to learn the basics in muse score and to fall in love with the software. I do wanna switch over but I'm hesitating to write larger scores, which require individual parts, as long as writing cue notes is a bit too laborious. So I think this would be an extremely valuable feature when it comes to parts...

**Comment by oktophonie** [comment] 2023-02-25 13:36
Closed as incorporated into https://github.com/musescore/MuseScore/issues/16544

**Closed by oktophonie** 2023-02-25 13:36 UTC
