### ISSUE TITLE
[MU4 Issue] Can't select or scale an image in a vertical frame

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#16147] opened 2023-01-30 22:29 UTC
### **Various image formats aren't selectable or scalable in a vertical frames**

**The steps I took:**
In MuseScore 4.01:

• I dragged an SVG image from my desktop into a vertical frame. 
• I was UNABLE to scale the image in locked aspect, nor by vertical or horizontal scaling.
• When clicked the image doesn't highlight (in v3 it gains an encompassing rectangle highlight) 
• When clicked the image's two scaling handles don't appear.
• Additionally I can't reposition the SVG with the frame like I can in MuseScore 3.6.2—it's lock in the upper left corner of the frame. So it seems the image fails to selected on Click.

### **Interestingly these issues do not occur with Horizontal frames or Text frames.**

For regression perspective I tested with the same SVG image to a note in MuseScore 3.6.2:

•  I CAN scale it with in locked aspect ratio (the default option)
• When clicked a rectangle surrounds it indicating that it is selected and two scale handles appear.
• I can independently scale it vertically or horizontally unlocking the dimensions in Properties>Image.
• I can also reposition it.

### **The loss of these features are regressions.**

**Expected behavior**
Graphic images should be selectable, moveable and scalable in a vertical frame

**Original forum post**

https://musescore.org/en/node/343810

**Platform information**
 - MacOS Ventura 13.1 / MuseScore 4.01

**Comment by MarcSabatella** [comment] 2023-01-31 00:26
How are you trying to scale?  It's hard to select the image in the first place because it defaults to a stacking order behind the frame.  That's already reported with a fix on the way - see https://github.com/musescore/MuseScore/issues/13664.  But once you do successfully select it, it scales fine for me.

**Comment by scorster** [comment] 2023-01-31 02:29
Yes, as I mentioned "... it seems the image fails to selected on Click." Thanks for point out stacking order as the reason.

**Marc asked >>** *How are you trying to scale?*

I was trying to scale in the normal 3.6.2 fashion, by selecting the image and dragging one of the scaling handles. 

Thanks to the information at the link you posted (see https://github.com/musescore/MuseScore/issues/13664.) I learned that I can reduce the height of the frame to reveal a selectable portion of the image. And thus select and scale it. A good stopgap workaround.

**Comment by MarcSabatella** [comment] 2023-01-31 14:03
So this can be closed as a duplicate, then,

Another workaround, BTW, is to use Alt+Right to select the image.

**Comment by scorster** [comment] 2023-01-31 19:52
> Another workaround, BTW, is to use Alt+Right to select the image.

On MacOS I'm unable to discover any keystroke combination that selects an image stacked behind a frame.

I'm guessing the Mac equivalent to your Alt+Right suggestion is Option+rightArrow. But that has no visible effect. 

Nice if Control/Command-click worked as it does for stacked notes in various voices. Any reason not to allow that? If the user has an inkling that the graphic is somehow behind the frame they'd have a reasonable chance of applying parallel logic for selecting the next deeper object.

**Comment by MarcSabatella** [comment] 2023-01-31 20:19
Alt+Left/Right are the standard keyboard navigation commands; on macOS I assume it's Option+Left/Right.  To navigate through the contents of a frame, select the last element before the frame and press Alt+Right, or the first element after and use Alt+Left.  For some reason simply clicking on the frame itself doesn't work to set up keyboard navigation.

**Comment by MarcSabatella** [comment] 2023-01-31 20:20
Ctrl+click unfortunately does *not* work to select overlapping elements in MU4; it's a known regression.  See https://github.com/musescore/MuseScore/issues/10225

**Comment by cbjeukendrup** [comment] 2023-03-04 19:56
Duplicate of #12934. Will be fixed in 4.0.2.

**Closed by cbjeukendrup** 2023-03-04 19:56 UTC
