### ISSUE TITLE
[MU4 Issue] Playback not working for default "Piano" sound

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11949] opened 2022-06-08 22:31 UTC
**Describe the bug**
Playback doesn't work straight after creating new score using the default Piano sound

**To Reproduce**
1. Create/open a score with just a piano, add some notes if necessary
2. Note that on adding you can't hear the notes sounded
3. Start playback, nothing is audible
4. Wait a while, then try playback again, and it becomes audible (but on closing/reopening score stops again)

**Expected behavior**
Should be able to hear piano sound as expected as soon as score is opened. Works fine for other instruments that I tested.

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Nightly build from Jun 07 2022, also happens when running in debug mode built from latest source as of Jun-09-2022.

**Comment by wizofaus** [comment] 2022-06-08 22:50
BTW it does *sometimes* or at least eventually work, but I could consistently reproduce this several times.

**Comment by Tantacrul** [comment] 2022-06-08 23:46
I have not experienced this kind of delay. On any machine I've tested this one, playback for a single instrument is almost instantaneous.

@DmitryArefiev - have you experienced this at all on any of your machines?

**Comment by shoogle** [comment] 2022-06-10 20:37
I have noticed playback gradually fades in over a few seconds. I'll add more details next time I spot this.

I've also noticed playback broken for certain instruments in multi-staff scores when there isn't a note at bar 1, beat 1. I'll put this in another issue if I can reproduce it.

**Comment by Tantacrul** [comment] 2022-06-11 16:37
@wizofaus is saying piano has literally no sound at all, which I've not heard reported by anyone else. @wizofaus - perhaps you could share the sound card details from your laptop?

**Comment by shoogle** [comment] 2022-06-11 16:46
@wizofaus mentioned it becomes audible after a while though (see item 4 in "To reproduce"), so it might be related to what I experienced with the volume fading in after a few seconds

**Comment by Tantacrul** [comment] 2022-06-11 17:08
My mistake.

**Comment by wizofaus** [comment] 2022-06-11 20:48
![image](https://user-images.githubusercontent.com/5364225/173204329-521e19c5-8115-4116-ba6b-d47ad9f1c4df.png)

That's all I can find, like I said it's a 6-yo ASUS (republic of gamers) laptop, and a reasonably powerful machine. No other apps I have (incl. MuseScore 3) have any issue with sound production.

But the long delay (up to 15 seconds) before the piano sound starts working is absolutely consistent, happens every time I open/create a new score.  The crackles and pops are consistent too, though less obvious with Piano (once it does start working) than other sounds.

**Comment by wizofaus** [comment] 2022-06-14 20:33
BTW, I just tested again with v3 on the same computer - and the problem does happen there too, it's just not nearly as bad because it only happens if you try to enter notes immediately after the app starts up - it takes about 4 seconds or so before playback starts working. After opening/creating subsequent scores there's no additional delays though.  Interestingly it's not specific to piano in v3, it happens for other instruments too.

**Comment by Tantacrul** [comment] 2022-06-14 20:35
Vasily is working on a number of optimisations to loading & audio at the moment. Curious to see if it changes things.

**Comment by wizofaus** [comment] 2022-06-14 20:43
Great to hear, but it may well just be some weird state my system got itself into (it's low on disk space among other issues, and HDDs can slow down with time anyway) - I'm pretty sure I would have noticed if v3 had that behaviour previously, but I don't recall ever noticing it at all.  Unless it's happening for a significant number of other users testing v4 I wouldn't spend excessive time on it.

**Comment by Tantacrul** [comment] 2022-06-14 20:57
Right, well I'll tentatively close this for now until someone else mentions they're having the same issue. As I mentioned, there are a ton of audio fixed coming down the pipe shortly, and our main focus is audio for **4.0** (because it is the most significant change) anyway.

**Closed by Tantacrul** 2022-06-14 20:57 UTC

**Comment by HemantAntony** [comment] 2022-06-27 11:02
@wizofaus @Tantacrul Its your lucky day. I can reproduce this. I never use the Piano much and never paid attention till today

**Comment by HemantAntony** [comment] 2022-06-27 11:08
I'm guessing the reason this occurs is because the mixer hasn't loaded yet. Its slow for some people. I'm guess @Tantacrul 's laptop is a really good one which may be why you can't reproduce it. The following video proves my theory:

https://user-images.githubusercontent.com/88136054/175927844-7c5da629-8cf3-443a-89f0-a541f41374cc.mp4

**Comment by wizofaus** [comment] 2022-06-27 11:25
Yes, it was always related to something taking a while to load - I assume the VSTs? But why does it do it every time you open a score, and why does it take so much longer for Piano vs other instruments?

**Comment by wizofaus** [comment] 2022-09-04 22:33
This is still a problem, for any score containing piano - every time I open or create one even within the same session, it takes ~10 seconds before I hear any sound at all.
