### ISSUE TITLE
Staccato ignored on tied notes

### ISSUE THREAD

**Issue by Thiago-Morais** [musescore/MuseScore#22019] opened 2024-03-21 19:05 UTC
### Issue type

General playback bug

### Bug description

Any staccato on a tied note is ignored regardless of where the staccato is

There would be a "workaround" if you don't use staccato at all on tied notes and just use one short note, however, when you use "Tools/Regroup Rhythm" in a situation where a note must be split into tied notes it breaks the previous staccato.

Therefore either a staccato tied note must be played as a normal single long note with staccato or the Regroup Rhythm must alter the note so that the staccato plays in the same way the previous one did. 
Like using only the first part of the tie and deleting the second part entirely

This happens with Muse Sounds and MS Basic

### Steps to reproduce

1. Use a 12/8 time
2. Fill the measure with staccato quarter notes
3. Apply "Tools/Regroup Rhythm"
4. Listen playback

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/21369746/81fd356b-b55f-4cc7-99c4-9f67ddc0ed49

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, 

### Additional context

[Error - Staccato ignored after regroup rhythm.zip](https://github.com/musescore/MuseScore/files/14705825/Error.-.Staccato.ignored.after.regroup.rhythm.zip)

**Comment by bkunda** [comment] 2024-06-07 07:58
Giving this a P2 because the circumstances in which it occurs are slightly more niche than those to which we've given P1 status.

**Comment by sammik** [comment] 2024-06-07 09:49
Seems to be duplicate of #17130

**Closed** 2024-07-09 10:47 UTC
Labels: P2, duplicate, playback
