### ISSUE TITLE
Opening a second score starts a new session

### ISSUE THREAD

**Issue by Louis-JR** [musescore/MuseScore#18900] opened 2023-08-03 09:05 UTC
### Issue type

Other type of issue

### Bug description

Having to open a second score in a separate tab starts instead a new session.

### Steps to reproduce

1. start MuseScore-4.1.1.232071203-x86_64.AppImage with a score name as argument
2. In the file drop down menu choose open and select another score file

 

### MuseScore Version

OS: Ubuntu 22.04.2 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

(X)Ubuntu 22.04.2

### Additional context

Of course the new session goes through the symptoms described in bug #18899

**Comment by oktophonie** [comment] 2023-08-03 09:42
Duplicate of https://github.com/musescore/MuseScore/issues/11340 etc

**Closed by oktophonie** 2023-08-03 09:42 UTC
Labels: duplicate
