### ISSUE TITLE
[MU4 Issue] MuseSounds doesn't play the whole range of some instruments

### ISSUE THREAD

**Issue by belluzziclaudio** [musescore/MuseScore#14321] opened 2022-11-05 08:54 UTC
**Describe the bug**
When MuseSounds is selected to play an instrument, some notes in the low/high range are not played.

**To Reproduce**
1. Create a new score;
2. Change instrument to English Horn;
3. Enter A5 and A♯5 (concert pitch). The first should appear black and the second yellow;
4. Hear that the MuseSounds English Horn has no playback.

![screenshot](https://user-images.githubusercontent.com/75799089/200111839-4e45eaeb-9832-4613-ae08-ddd7a8c60865.png)

**Expected behavior**
MuseSounds should cover at least all the "black" notes, possibly the "yellow" ones.
Alternatively, the range of some instruments can be changed to match those of MuseSounds.

**Platform information**
 - OS: Linux Mint and Windows 10

**Comment by Vincentwang987** [comment] 2022-11-05 09:02
Pretty sure that is a duplicate of #13894

**Comment by cbjeukendrup** [comment] 2022-11-05 13:50
@belluzziclaudio No need to remove the issue completely, I'll just close it. Thanks for reporting anyway!

**Closed by cbjeukendrup** 2022-11-05 13:50 UTC
