### ISSUE TITLE
Files can't be opened from Finder/Windows Explorer after MuseScore crashes

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#23262] opened 2024-06-16 02:04 UTC
### Issue type

Opening/saving issue

### Bug description

If MuseScore crashes for some reason, and you reopen the file (or any file) from your OS file browser, it will not open.

### Steps to reproduce

1. Open any MuseScore project and make MuseScore crash (e.g. follow [these](https://github.com/musescore/MuseScore/issues/21993) steps), or force-quit MuseScore.
2. Double-click a file from the Finder on Mac or Windows explorer on Windows.
3. The dialog appears asking if you want to restore the previous session. Click No.
4. The file does not open.

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

macOS 12.7.2. Windows 10, as well.

**Comment by MarcSabatella** [comment] 2024-06-16 02:28
What exactly goes wrong when you try?  Are you saying the file is fine when you open it normally but it only doesn’t open when opening from Finder?  Does it open fo e if you answer yes?  Does it open fine the *next* time you try to open the file from Finder - so it’s a temporary failure to try to open it after you answer “no”?

**Comment by Riley-Sullivan** [comment] 2024-06-17 20:36
My apologies if this submission wasn’t clear. The point is that files you can normally open will not if the last session of MuseScore was abruptly aborted. In other words, the “restore last session” dialog essentially hijacks MuseScore.

Imagine this scenario: yesterday MuseScore crashed and then I just went to bed. Today, I double-click a different file on my computer, and it reminds me that MuseScore crashed last night. I click “No”, meaning I don’t care, I just want to discard that session and work on this other file. But it doesn’t open it. It will open normally in the future, but not if MuseScore previously crashed.

My thought is that if you choose not to restore the last crashed session, it should indeed open the file you were attempting to open, though that’s just a suggestion, and I’m aware that the best way to handle all this would likely require discussion among the internal team.

MS3 opened the file whether you chose to restore or not restore. If you chose to restore, both the crashed session and the new file would both open, though since MS4 is now single-instance I would understand if that behavior is no longer ideal. The way it stands though, to me feels a bit wonky.

**Comment by cbjeukendrup** [comment] 2024-06-18 01:47
This seems a duplicate of https://github.com/musescore/MuseScore/issues/15919, is that right?

**Closed** 2024-06-18 13:10 UTC
