### ISSUE TITLE
[MU4 Issue] Text lines can't change text styles

### ISSUE THREAD

**Issue by Haru00007** [musescore/MuseScore#15043] opened 2022-12-08 14:06 UTC
**Describe the bug**
Texts can change text styles, but text lines can't change it.

**To Reproduce**
1, Create new score
2, Add Text line
3, See you can't change text styles (also add text and see you can change text styles)

**Screenshots**
It should look like the image below.

![スクリーンショット 2022-12-08 224450](https://user-images.githubusercontent.com/39019007/206465981-483d1251-710c-4c70-8ae8-c2164203a846.jpg)

**Platform information**
 - OS: Windows 10 22H2 Musescore: latest RC Edition

**Comment by oktophonie** [comment] 2022-12-08 14:18
Duplicate of https://github.com/musescore/MuseScore/issues/13338; see task https://github.com/musescore/MuseScore/issues/14238

**Closed by oktophonie** 2022-12-08 14:18 UTC
