### ISSUE TITLE
Conflict between "hide empty staves" and pitch lines

### ISSUE THREAD

**Issue by marchfra** [musescore/MuseScore#21012] opened 2024-01-14 22:00 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When "hide empty staves" is enabled on an instrument that uses two staves such as piano, if there is a pitch line (8va bassa or 8va alta and such) on the last bar of the previous row, the staff is not correctly hidden

### Steps to reproduce

1. Create a new score with piano as an instrument
2. Insert some notes in the last bar of the lower staff on the first row
3. Insert some notes on the upper staff on the second row
4. Turn on "hide empty staves": now the left-hand staff on the second row should be hidden
5. Insert a line such as "8va bassa" up to and including the last note in the first row: now suddenly the left-hand staff in the second row is visible, though empty

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/73989695/d567ca87-59e3-4606-8090-9eac67bae423)
![image](https://github.com/musescore/MuseScore/assets/73989695/a18f65ed-cc64-4d7f-baff-07e113ea9bb3)
![image](https://github.com/musescore/MuseScore/assets/73989695/9d458c40-379f-466b-be6b-41a5ab97b47d)

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.1.2 (23B92)

**Comment by MarcSabatella** [comment] 2024-01-15 00:42
I assume this is a duplicate of https://github.com/musescore/MuseScore/issues/20782 and thus fixed already for 4.2.1.  I can reproduce in 4.2 but not in the current nightly build using the steps given here.

**Closed** 2024-01-15 09:11 UTC
Labels: engraving, regression_ms3
