### ISSUE TITLE
[MU4 Issue] Playback profile doesn't default to Muse Sounds when Muse Sounds are installed

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14634] opened 2022-11-21 14:26 UTC
**Describe the bug**
Newly created scores are opening with **MuseScore Basic** as the default sound profile, even if one or more Muse Sounds libraries are installed.

**To Reproduce**
1. Ensure at least one Muse Sounds library is installed
2. Create a new score
3. Go to **View** &rarr; **Playback profile**
4. Observe that "MuseScore Basic" is active

**Expected behavior**
When at least one Muse Sounds library has been installed, MuseScore should always create and open scores with the **Muse Sounds** playback profile as *active*.

*Exceptions*
1. The user has previously checked the "Set as default for new scores" option on a previously saved score with MuseScore Basic as the active playback profile (i.e. newly created scores will also be created with MS Basic sounds)
2. The user opens a score that has previously been saved in MuseScore 4 with the MuseScore Basic playback profile (i.e. their preferred playback profile for that score should be retained).

**Platform information**
 - macOS 12.6 (M1)

**Additional context**
@Tantacrul @shoogle FYI

**Comment by Tantacrul** [comment] 2022-11-21 14:29
Thanks @bkunda

**Comment by cbjeukendrup** [comment] 2022-11-21 19:52
In fact a duplicate of #14050. But this one is clearer.

**Closed** 2022-11-26 14:24 UTC
Labels: P0
