### ISSUE TITLE
Multiline text misalignment in Composer field

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#24568] opened 2024-09-08 23:26 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Open a new score, and add multiline text into the Composer text box. I'd expect the two lines to be right aligned, and they are close, but not exact. I often run into this when attributing to a composer and arranger, and the misalignment is sometimes inside the boundary, sometimes outside. The attached score below shows a small effect, but sometimes this is much bigger and the misalignment looks almost as large as a character.

### Supporting files, videos and screenshots

[Misaligned composers.zip](https://github.com/user-attachments/files/16923973/Misaligned.composers.zip)
[Misaligned composers.pdf](https://github.com/user-attachments/files/16923979/Misaligned.composers.pdf)

In this file, created in 4.4.1, the two lines both end in `R`, so these characters should be vertically above each other to match the right-alignment. In my MuseScore Studio, and the exported PDF, the second line's `R` is a little, but noticeably, to the right of the first.

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

I was unable to check

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by iainhallam** [comment] 2024-09-08 23:29
A more noticeable example...
![Misaligned composers](https://github.com/user-attachments/assets/81242a80-847a-49e3-8a38-a7c1bbbc44a0)

**Comment by oktophonie** [comment] 2024-09-09 06:52
Duplicate of https://github.com/musescore/MuseScore/issues/22416

**Closed by oktophonie** 2024-09-09 06:52 UTC
Labels: engraving

**Comment by iainhallam** [comment] 2024-09-09 10:24
Darn it - thought I'd searched enough for this! Sorry.
