### ISSUE TITLE
Can't select an audiodevice

### ISSUE THREAD

**Issue by chang-hs** [musescore/MuseScore#19098] opened 2023-08-19 03:57 UTC
### Issue type

General playback bug

### Bug description

I was using Musescore 3 on an archlinux computer.
Since I upgraded to Musescore4, no sound is generated when I use playback.
I checked the I/O tab in the preference and tried to select my audiodevice that is an USB speaker. However, that device does not appear in the selection.

### Steps to reproduce

1. activate Musescore 4
2. Write a new score or open an existing score file
3. Playback
4. No sound

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Archlinux

**Comment by cbjeukendrup** [comment] 2023-08-20 11:41
Possible duplicate of #11220 / #12649

**Comment by bkunda** [comment] 2023-08-22 13:19
Let's indeed close this as a duplicate (and we can reopen if anything further reveals itself).

**Closed by bkunda** 2023-08-22 13:19 UTC
Labels: playback, regression_ms3
