### ISSUE TITLE
[MU4 Issue] Quatation behaviour at the beginning of verses

### ISSUE THREAD

**Issue by webfischi** [musescore/MuseScore#15408] opened 2022-12-20 00:17 UTC
**Describe the bug**
If you use " for syllables at the beginning or the end of the verse, it's not aligned.

**To Reproduce**
1. Create some music and add some lyrics
2. Add quotation marks to the first syllable
3. Watch the verse number move out

**Expected behavior**
Keep verse numbers in line.

**Screenshots**
![image](https://user-images.githubusercontent.com/22318963/208552403-25203ec2-c8f6-4a9e-9ffb-3c0ea8ecfd66.png)

**Platform information**
 - OS: Windows 11 22H2

**Additional context**
I thought it was on the last syllable as well, but that seems to be only an issue when importing MU3 files.

**Comment by oMrSmith** [comment] 2022-12-20 02:51
duplicate of #15347

**Comment by Eism** [comment] 2022-12-20 11:53
Closing as a duplicate

**Closed by Eism** 2022-12-20 11:53 UTC
