### ISSUE TITLE
[MU4 Issue] Musescore covers auto-hidden taskbar

### ISSUE THREAD

**Issue by 3dWrecker** [musescore/MuseScore#15357] opened 2022-12-19 04:22 UTC
**Describe the bug**
Musescore covers auto-hidden taskbar, making it inaccessible via mouse input.

**To Reproduce**
1. Enable taskbar autohide in Windows 10 settings. (Right-click the taskbar, Tastbar settings > Automatically hide the taskbar in desktop mode > On
2. Open musescore and maximise.

**Expected behavior**
Musescore should maximise to the screen width (assuming the taskbar is located at the top or bottom of the screen) but not the entire screen height. The autohidden taskbar has 2px of height which should still be visible when windows are maximised.

**Platform information**
 - OS: Windows 10 22H2, OS Build 19045.2364

**Additional context**
The wrong system variable (?) seems to be being called for proper window size.

**Comment by 3dWrecker** [comment] 2022-12-19 04:25
Probably related to #15233 and #15356

**Comment by cbjeukendrup** [comment] 2023-01-03 21:37
This seems a duplicate of #10958. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-01-03 21:37 UTC
