### ISSUE TITLE
[MU4 Issue] Assigning a shortcut to "go to top staff" doesn't appear to work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11522] opened 2022-05-04 22:33 UTC
**Describe the bug** (Edited by Martin)

1. When the shortcut is triggered it correctly selects the topmost staff but the view does not scroll up so we can see that selection (it does this in MS3). Because the scrolling does not work, the user cannot tell whether the shortcut has worked correctly.
2. It should be renamed to 'Select the top staff'

**Comment by Tantacrul** [comment] 2022-05-07 19:54
Can you possibly convert this to a set of expected behaviour. It's hard to understand.

Title: It's not working
Description: Well, it _is_ working, etc.

**Comment by quinnouyang** [comment] 2022-05-07 21:31
@Tantacrul I think they're specifying three things:
- It correctly* selects the left-most element of the selected measure (if none selected, then of the entire score in the topmost staff). E.g. Select a note/rest on beat 3 of a 4/4 measure; the shortcut selects the element on beat 1. Or select nothing; the shortcut selects the element on beat 1 on the first staff.
- *Expected behavior is not clear from the title, "Go to top staff." Is "go to the first beat in selected measure" correct?
- When the shortcut selects an element is out of view, the view does not scroll to it. This is desired for "Page: top of first", which brings you to the top of the first page _without selecting the top + left-most element_. I presume we'd want it here too.

**Comment by MarcSabatella** [comment] 2022-05-07 22:05
No, I don’t thinks that it at all.  “Go to top staff” is a command that literally moves the cursor/selection to the top staff of your score.

The main bug here is that if you try to assign a shortcut to this command, it doesn’t work.  The dialog allows you to add the shortcut and hit OK.  But if you try to use the shortcut, nothing happens.

The strange part of the the bug is that the command shows up in the shortcut list at all.  That’s strange because it’s the only command with no default shortcut to appear in the list.  All other commands with no default shortcut are missing from the list - a separate bug submitted a while back and referenced quite a few times recently.

For some reason, the “go to top staff” command seems immune to the bug that prevent shortcutless-commands from appearing in the list, but the command also seems to not work if you do assign it a shortcut.

That’s what I read in the original report, and it’s easily reproducible as described.

**Comment by wizofaus** [comment] 2022-05-08 01:13
My description is as stands, but at least after restarting MuseScore, the shortcut key *does* work (I have observed occasions where you need to restart MuseScore for newly-assigned shortcut keys to start working), it's that the behaviour isn't really what I'd expect (particularly wrt not scrolling the selected note into view).

I agree there are multiple (related) issues here, but personally if I was fixing them I'd do them all together, once there's an agreement as to what the expected behaviour should be.

**Comment by Tantacrul** [comment] 2022-05-08 09:18
- So, when assigning the shortcut for the first time, it doesn't work. Requires restart
- When it selects the measure and beat that it does, you think the page should also scroll to the top so we can see the selection (which seems like a no-brainer to me too).

Is that it? If so, I'll take the shortcut assigning bit and add it to my uber shortcut bug because I'm pretty sure it's relevant to that. Then for this bug, we can simply change it to be about the actual behaviour of the result, once the shortcut has been triggered.

**Comment by wizofaus** [comment] 2022-05-08 09:34
I was unable to replicate the shortcut assignment not working the very first time,  but if Marc observed it then it may well be an issue still and wouldn't surprise me.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Tantacrul** [comment] 2022-05-08 10:06
I've amended the bug to focus on fixing the scrolling. I don't have a suggestion for the correct keybinding. However, I think we should allow shortcuts (in future) to be there but to not automatically be bound to a key.

I couldn't replicate the problem of assigning (on MacOS) but since both you and Marc experienced it, I'd be certain it's part of the overall issue I logged here: #11474

**Comment by MarcSabatella** [comment] 2022-05-08 14:39
I definitely did in the build I am using, but it probably is the same as the ones you are, so it could be something that has changed in the last week or so.  But after restart, it works.  After revert to factory settings, the problem does not reappear.  So definitely elusive.

But I definitely think that the fact that the shortcut continues to show up in the list despite being empty when no other empty shortcuts do is a sign that something is just messed up about this command - like maybe there is a bad value in one of the shortcut definition files that is causing some variable to not be initialized correctly, and that in turn is leading to semi-random results.

**Comment by wizofaus** [comment] 2022-06-19 06:31
I'm also observing an even more serious problem, after assign the shortcut sequence CTRL+ALT+T for this, attempting to use is actually cause the "Text" menu to become selected.  This should only occur for just plain ALT+T.

**Closed** 2022-06-19 09:01 UTC
Labels: P3
