### ISSUE TITLE
[MU4 Issue] Context menu opens in wrong location

### ISSUE THREAD

**Issue by AxelMatstoms** [musescore/MuseScore#15278] opened 2022-12-17 16:01 UTC
**Describe the bug**
When using some window managers, context menus open in the wrong location in the window.
I tested this in [swaywm](https://swaywm.org/), on which the bug did occur, and in [i3wm]https://i3wm.org/l) where the bug did not occur. Submenus such as Add>Text open in front of the parent menu.

**To Reproduce**
1. Open MuseScore in swaywm.
2.  When viewing a score, right click to view context menu, or click any of the top menu buttons (such as File, Format, Tools, etc).
3. Open any submenus.

**Expected behavior**
The right click context menu is supposed extend from where you clicked, and the top menus are supposed to extend from the button that opens them. Submenus are supposed to open to the right of the menu item that opens them.

**Screenshots**
![Screenshot_2022-12-17_16-37-17](https://user-images.githubusercontent.com/20318589/208250298-a80125b0-f757-47b9-a8c4-6f3634bce1a4.png)
![Screenshot_2022-12-17_16-37-47](https://user-images.githubusercontent.com/20318589/208250305-56e75cb5-a067-483f-a1c1-a32f3db096f3.png)

**Platform information**
 - OS: Arch Linux
 - Window manager: Swaywm 1:1.7-10

**Additional context**
Swaywm, being a tiling wm, handles windows slightly differently from regular floating wms.

**Comment by RobFog** [comment] 2022-12-17 16:13
This looks a bit like #13290. #13290 is meant to be fixed by the changes in #15151.

You could try 15151's fixes by using the most recent developmental build from https://musescore.org/en/nightly-builds ?

**Comment by AxelMatstoms** [comment] 2022-12-17 22:19
B

**Comment by AxelMatstoms** [comment] 2022-12-17 22:24
I compiled the master branch, and tried it. Confirmed still not working as expected as of commit cf7e523f72.
I'm not sure this is related to #13290, since it does not work in the latest build, which seems to have resolved #13290.

**Comment by RobFog** [comment] 2022-12-17 22:38
Thanks for checking.

**Comment by Horus645** [comment] 2022-12-18 02:58
I believe this is actually the exact same problem as #15285.

**Comment by AxelMatstoms** [comment] 2022-12-18 19:29
> I believe this is actually the exact same problem as #15285.

I agree. Since these issues are duplicates, one of them should probably be closed. The person who opened #15285 has done some digging, and seems to have found a likely culprit.

**Comment by Eism** [comment] 2022-12-21 10:51
#15151 does not fix this problem, because the changes are only for Windows.

Yes, it's a duplicate of #15285. I will close this one. Thanks for reporting!

**Closed by Eism** 2022-12-21 10:51 UTC
