### ISSUE TITLE
[MU4 Issue] Finger numbers are unreadable in tablature view

### ISSUE THREAD

**Issue by Tamarindo94** [musescore/MuseScore#16239] opened 2023-02-06 17:52 UTC
**Describe the bug**
Finger numbers are unreadable in tablature view if dark theme is enabled: this happens because their color is the same as background. The problem does not happen if lines view is set to "Continuous" instead of "Broken" in "Advanced style properties"

**To Reproduce**
1. Enable dark theme
2. Go to 'Staff/Part properties'
3. Click on 'Advanced style properties'
4. Enable 'Tab 6-str. simple' template; under "Fret marks" tab, click on "Broken" for "Lines are" option
5. See error. Numbers are shown but are unreadable because a background is added of the same color of the number if Lines are set to Broken

**Expected behavior**
Numbers should be readable

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/25021109/217047373-dc941840-5b4c-4ce2-94e9-6fb2c127f8e9.png)

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment] 2023-02-06 18:17
This looks like a duplicate of #11570, which is on our radar. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-02-06 18:17 UTC
