### ISSUE TITLE
MusicXML exporting: swing and straight tempo markings do not fully export.

### ISSUE THREAD

**Issue by JosephBuchholz** [musescore/MuseScore#18752] opened 2023-07-21 18:00 UTC
### Issue type

Other type of issue

### Bug description

Swing and straight tempo markings do not fully export when exporting to MusicXML. Instead just the text is exported:

```
    <measure number="2" width="315.07">
      <direction>
        <direction-type>
          <words default-y="0.24" relative-y="20.00" font-weight="bold" font-size="12">Swing</words>
          </direction-type>
        </direction>
```

should be:

```
    <measure number="2" width="315.07">
      <direction>
        <direction-type>
          <words default-y="0.24" relative-y="20.00" font-weight="bold" font-size="12">Swing</words>
          </direction-type>
          <sound>
            <swing>
              <first>2</first>
              <second>1</second>
              <swing-type>eighth</swing-type>
            </swing>
          </sound>
        </direction>
```

### Steps to reproduce

1. Create a MuseScore project with a Swing element
2. Export to MusicXML
3. Import the MusicXML into MuseScore
4. Listen to the score and note that there is no swing playback

### Screenshots/Screen recordings

Before Export:
![Screenshot 2023-07-21 105530](https://github.com/musescore/MuseScore/assets/70069846/ad96e94d-e14c-45ad-ba17-3bb60c84442c)

After Export:
![Screenshot 2023-07-21 105554](https://github.com/musescore/MuseScore/assets/70069846/e757142a-124b-44e9-892a-0fd9b2c10a64)

![Screenshot 2023-07-21 105713](https://github.com/musescore/MuseScore/assets/70069846/2aea662c-3ebb-4eb3-afa1-cef4061ceb46)
(see that the swing playback is disabled)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 11

### Additional context

The MuseScore and MusicXML files:
[files.zip](https://github.com/musescore/MuseScore/files/12131241/files.zip)

**Comment by mercuree** [comment] 2023-07-21 18:07
Probably duplicate of #17815

**Comment by cbjeukendrup** [comment] 2023-07-21 18:11
Thanks @mercuree! However, since this issue has slightly more details, I'll close the other issue instead. Hope you don't mind!

**Comment by Jojo-Schmitz** [comment] 2023-07-21 18:51
Came up before in https://musescore.org/en/node/268454

**Closed** 2024-03-12 11:59 UTC
Labels: P2, MusicXML
