### ISSUE TITLE
[MU4 Task] Allow side panels to be resized left/right

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16517] opened 2023-02-24 00:54 UTC
The side panels such as Palettes/Instruments/Selection Filter and Properties used to be adjustable in size in MuseScore 3, this no longer is the case thus making it a regression. The side panels take up too much space as it stands making it difficult to work on the score. Undocking is also not a viable option as any attempts to adjust its base position will redock it, and also undocking any of the 3 left panels splits them apart from one another. Also, if you undock with only 1 left panel open, the instance tab gets obscured by the undocked panel unless you put it so far to the right that it obscures the score.

**Comment by MarcSabatella** [comment] 2023-02-24 13:28
This is a duplicate of https://github.com/musescore/MuseScore/issues/11300, which was closed with the intention of reopening after 4.0 was released.  That should probably happen now.

**Closed** 2023-02-24 13:42 UTC
Labels: duplicate
