### ISSUE TITLE
Odd System Break behaviour in tightly stretched layouts

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#20816] opened 2024-01-03 14:22 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When I have use negative stretch to cramp more measures in one staff, it looks just fine. Then I preserve that layout by a manual system break.
But when I re-open the file the automatic system break pushes the former last bar to the next line. When I change the left or right margin by +1 or -1 pt everything is fine again. Then I can change it back again and everything still looks fine.

### Steps to reproduce

1. use any score (I tend to use pop-choral music scores and work in part scores most of the time, but don't know if that is any deal)
2. use negative stretch for a tighter layout -> cramp more bars in the same space
3. when happy fix layout by applying a manual system break
4. save and re-open the score -> the layout is now messed up

### Screenshots/Screen recordings

Before Saving:
![grafik](https://github.com/musescore/MuseScore/assets/12497326/9896e532-4322-4e3c-9ccc-45538924f72e)

After Opening:
![grafik](https://github.com/musescore/MuseScore/assets/12497326/8ab95c6d-24e4-4568-a096-b5f6c23d44d4)

After reducing - or even increasing (!) - the right margin by 1 pt:
![grafik](https://github.com/musescore/MuseScore/assets/12497326/df76105d-3e34-4d12-87a3-1c3358a2c0ad)

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2024-01-03 14:36
Negative stretch probably should not even be possible; not sure that was meant to be supported.  Measure properties won't go below 0, but apparently the Properties panel does.  Probably that should simply be disallowed.

The better way to force more measures to fit than actually do given your style settings and minimum stretch overrides is to use the "keep measures on the same system" layout element.  Or, if this is something you want to do score-wide, simply reduce the spacing ratio and/or minimum note distance in format / style / measure.

That said, layout shouldn't change on save/reload obviously.  It would be useful if you could ZIPO and attach your actual score and give steps to reproduce the problem (eg, say which measure specifically to select and apply stretch to, and what value to apply).

**Comment by oMrSmith** [comment] 2024-01-03 15:11
This happens - also in MU3 - if the horizontal space is _almost_ insufficient. The program recalculates spacing - for example when saving the file - and descides that it's not enough, breaking the system. It is a bug, I think, since the program makes to different descisions but in MU4 there is an easy work around:

![image](https://github.com/musescore/MuseScore/assets/78870770/740afda2-305a-4df2-a741-b01c500e3490)

**Comment by Lenbus** [comment] 2024-01-04 13:11
> Negative stretch probably should not even be possible; not sure that was meant to be supported. Measure properties won't go below 0, but apparently the Properties panel does. Probably that should simply be disallowed.

Okay, thanks for pointing that out. Probably "negative" was just not the correct term in that regard. What I meant with "negative stretch" was pressing the `{`-button to cramp more stuff in the same space by reducing the measure width accordingly.

Maybe for now, doing my workaround (making the layout re-calculate) or using @oMrSmith's method by grouping might be okay. Even though, as @MarcSabatella mentioned, those different results upon two passes of layout calculation should be prevented in later updates.

**Comment by MarcSabatella** [comment] 2024-01-04 13:59
No doubt, if a bug exists where layout changes on save/reload, it should be fixed.  So, again, please attach the score you are having trouble with and give precise steps to reproduce the problem.

**Comment by bkunda** [comment] 2024-01-12 14:44
@oktophonie pls investigate

**Closed** 2024-01-23 13:34 UTC
Labels: needs info, UI, regression_ms3

**Comment by Lenbus** [comment] 2025-02-26 23:44
I use MuseScore 4.4.4 now and this is still an issue (with the same annoying workaround to fix it). 
@MarcSabatella, anything new about the issue adressed here?

**Comment by MarcSabatella** [comment] 2025-02-27 01:22
The biggest new thing is that the hack of reducing stretch to fit more measures hasn’t been necessary for quite a while already, and will be even more pointless when 4.5 released with the new system locks feature.

So there may or may not still be a bug in some cases here, but it’s a feature that shouldn’t be used for this purpose anymore so it shouldn’t seem nearly as much of a problem in practice as it might have been once upon a time.

**Comment by MarcSabatella** [comment] 2025-02-27 01:29
The one other thing I can say is that this issue is closed because there was a fix made a while back that should have solved this specific case.  So if you’re seeing a problem with similar symptoms now, it may have a different cause.  I recommend opening anew issue and attaching the score and steps to reproduce that problem.
