### ISSUE TITLE
Tremolo makes a strange sound at the end of the measure at slow tempos and the notes between the treble and bass clef are not synchronized

### ISSUE THREAD

**Issue by DomantasMi9** [musescore/MuseScore#25325] opened 2024-10-27 08:10 UTC
### Issue type

General playback bug

### Description with steps to reproduce

1. Create a new score.
2. Then put a slow tempo
3. Put some notes and add tremolo to them. It should not make that weird sound at the end of the measure. Also the notes should be synchronized.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/092b0d6e-26c7-48ba-97ce-71cfebdd10bc

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment] 2024-10-29 16:53
Closing as duplicate of https://github.com/musescore/MuseScore/issues/24898

**Closed by zacjansheski** 2024-10-29 16:53 UTC
Labels: needs review, playback
