### ISSUE TITLE
[4.1] App keeps asking to save score even without changes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#18085] opened 2023-06-21 12:39 UTC
### Issue type

Other type of issue

### Bug description

Doesn't matter if it's a local or a cloud file, whenever it's being opened, then close straight away, the asking to save dialog always appears even when no changes has been made. 

### Steps to reproduce

1. Open score
2. Close score straight away without changing anything
3. See dialog (error)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/71656189/38184206-48a1-4659-9f30-604af17f27c5

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

**Comment by Jojo-Schmitz** [comment] 2023-06-21 12:45
Seems to  happen on pre 4.1 files only. And as such is pretty much by design, as the file format has change, so opening older files is considered an import.

**Comment by bkunda** [comment] 2023-06-21 12:58
I don't believe we've ever mentioned explicit changes to the file format in these dialogs, which were primarily focused on engraving changes (of which there are minimal destructive ones in 4.1, hence we haven't updated these dialogs).
For example, this one appears when opening a 3.6 score in 4.1 (@oktophonie FYI)
 
![Screenshot 2023-06-21 145357](https://github.com/musescore/MuseScore/assets/86290556/842b8d9a-511a-4e91-ada6-9d5c2ca52b0c)

But yes, it makes sense that the file will need to be saved again to convert it to 4.1.

**Comment by Jojo-Schmitz** [comment] 2023-06-21 13:01
We'd either need to show that dialog or not consider opening 4.0 scores an import.
3.6 reported pre 3.6 files too BTW

**Comment by jessjwilliamson** [comment] 2023-06-21 13:18
> Not for 4.0 scores opened in 4.1

Yes, hence this issue! :)

**Comment by cbjeukendrup** [comment] 2023-06-21 14:29
@bkunda @oktophonie @jessjwilliamson I can add exactly the same dialog for 4.0 scores as for 3.6 scores right now. But I have a question about the text: for 3.6 we have 
>Please note that the appearance of your score will change due to improvements we have made to default settings for beaming, ties, slurs, system objects and horizontal
spacing.

But what should we put there for 4.0 scores?

**Comment by Jojo-Schmitz** [comment] 2023-06-21 14:35
will change -> may change?

**Comment by bkunda** [comment] 2023-06-23 13:28
Closing as not planned for now

**Closed by bkunda** 2023-06-23 13:28 UTC
Labels: needs review, regression
