### ISSUE TITLE
[MU4 Issue] Delay when opening/closing palette search panel

### ISSUE THREAD

**Issue by farzadsaif** [musescore/MuseScore#16556] opened 2023-02-25 23:10 UTC
There is a delay when opening/closing the search menu under Palettes

1. Go to Palettes
2. Click on the magnifier glass icon
3. Experience delay
4. Press the X icon
5. Experience another delay

**Expected behavior**
Panel opens and closes immediately 

**Screenshots**

**Platform information**
 - OS: macOS Monterey, Linux Mint

**Additional context**
Still an issue on 4.1.0-dev

https://user-images.githubusercontent.com/66146879/221383760-5791ebe0-ea47-41a7-9997-a389e0356f5e.mp4

**Comment by cbjeukendrup** [comment] 2023-02-25 23:13
Duplicate of #12753, which is still on the radar. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-02-25 23:13 UTC

**Comment by farzadsaif** [comment] 2023-02-25 23:15
Hello, thank you for getting back to me. How do I see if an issue has already been reported? I tried searching for "delay" in issues before posting but this was pretty far back so I didn't see it.

**Comment by cbjeukendrup** [comment] 2023-02-25 23:37
Still, searching is pretty much the only option. But don't worry if you miss an existing issue despite searching; sometimes an issue just uses a different wording or is very old. And GitHub's search feature is not hyper advanced...
