### ISSUE TITLE
[MU4 Issue]Computer crashes some times on opening this file.

### ISSUE THREAD

**Issue by RotoSound** [musescore/MuseScore#14934] opened 2022-12-04 21:17 UTC
**Describe the bug**
App crashes every time on opening this file.

**To Reproduce**
1. Open the file.
2. Watch the compputer screen go black.

**Expected behavior**
MU4 should open the file as normal.

**Platform information**
 - OS: Win10

**Additional context**
On my 2nd attempt the screen did not go black but showed an alert "Error on opening file".
[Bachianas MU4 CompCrash.zip](https://github.com/musescore/MuseScore/files/10149489/Bachianas.MU4.CompCrash.zip)

**Comment by Eism** [comment] 2022-12-05 07:40
@RotoSound 
I can't reproduce.
Are you running the latest RC release?

**Comment by RotoSound** [comment] 2022-12-05 09:45
I am using the RC from 3 days ago. Will try with a new RC in 8 hrs from now.

Den mån 5 dec. 2022 08:40Elnur Ismailzada ***@***.***> skrev:

**Comment by RotoSound** [comment] 2022-12-05 18:39
Now with the RC from today I can open the file succesfully. Please erase this post totally since it is not an issue any longer.

**Comment by LuisLiszt** [comment] 2022-12-05 18:40
@RotoSound you can just close the issue.

**Closed** 2022-12-05 19:59 UTC
