### ISSUE TITLE
Drumset Voice crashes Musescore4 and corrupts file.

### ISSUE THREAD

**Issue by JacoqLenz** [musescore/MuseScore#16742] opened 2023-03-11 01:51 UTC
### Issue type

File corruption

### Bug description

I tried to add a shaker to a drumset part and then the program crashed. Now, I cannot open or export my file. To replicate this issue, open a file with a drumset part. Then try to add a shaker or other sound to your drumset vocabulary. It will crash the program and corrupt the file such that MS4 will not be able to open the file ever again. If you open musescore, you can still see the pixilated preview of the first page of the score. However, when you click on the preview the app closes immediately. 

### Steps to reproduce

1. Open a New Score
2. add a drumset part
3. attempt to add a shaker to the drumset vocabulary.
4. watch in horror as the musescore file is corrupted beyond repair, never to be opened again. 

### Screenshots/Screen recordings

<img width="343" alt="Screen Shot 2023-03-09 at 1 29 49 PM" src="https://user-images.githubusercontent.com/127437678/224122357-3371ff87-cfc3-484a-9f63-1b5d047534ef.png">

### MuseScore Version

4.0.1.230121751

### Regression

I don't know

### Operating system

Mac OS 12.6.1

**Comment by cbjeukendrup** [comment] 2023-03-11 14:24
I cannot reproduce this. Could you please upload the corrupted score? (need to wrap it in a ZIP file so that GitHub accepts it)

If you could make a screen recording or video where you reproduce this from scratch, that might also help.

**Comment by JacoqLenz** [comment] 2023-03-12 21:11
[Garden.mscz.zip](https://github.com/musescore/MuseScore/files/10952107/Garden.mscz.zip)

**Comment by cbjeukendrup** [comment] 2023-03-13 18:40
That score is not corrupted, and when I add a drumset part and add a shaker to it, the file doesn't become corrupted either. Are you sure that it is related to that? 

And can you reproduce it yourself? (i.e. follow certain steps to recreate the same corruption)

It is also possible that the corruption was completely unrelated to the drumset/shaker, and instead it was an incident, like those described in #16339. That issue is about certain kinds of corruption that seem to happen completely randomly, without any apparent cause, and therefore impossible to fix. 

If you think that you have experienced a corruption like that, we should close this issue because it is already covered by #16339.

**Comment by zacjansheski** [comment] 2023-05-26 21:15
Closing due to inactivity.

**Closed by zacjansheski** 2023-05-26 21:15 UTC
Labels: needs info, corruption
