### ISSUE TITLE
Conflicting audio access

### ISSUE THREAD

**Issue by krtschil** [musescore/MuseScore#21623] opened 2024-02-21 18:25 UTC
### Issue type

General playback bug

### Bug description

There is a conflict in accessing the audio device: while other apps (like video player, audio player, audio playing in a browser) access the audio device for playing sound, Musescore is unable to playback any score loaded.
The other way, while playback in Musescore is running, no other app can play sounds.

### Steps to reproduce

1. Open a video app, like youtube, VLC and play a video with sound
2. While video is playing start Musescore and load a score
3. Try to start the playback. It does not start at all
4. After stopping other apps playing sound and closing them and after restart of Musescore playack works as expected
5. Looking at the system panel for audio while Musescore is executing the playback Musescore is not listed as an app that currently uses the audio device. This is weird because normally any app that uses the audio device appears on that panel.

It looks like Musescore is trying to access the audio device in a non standard way (it is probably accessing the hardware directly, according to an entry in the log file, which is a no go in my opinion). Other apps do not show these symptoms (I can play several sound sources at the same time) .

### MuseScore Version

OS: TUXEDO OS 2, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Ubuntu 22.04, MuseSounds installed

### Additional context

2024-02-21T19:13:05.112 | ERROR | main_thread     | AudioModule::setupAudioDriver | audio output open failed
2024-02-21T19:13:05.124 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/klaus/.local/share/MuseScore/MuseScore4/shortcuts.xml"): device not open
2024-02-21T19:13:05.124 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/klaus/.local/share/MuseScore/MuseScore4/midi_mappings.xml"): device not open

**Comment by krtschil** [comment] 2024-02-29 23:55
Update: the **flatpak** version does not have this issue. Playback is working fine.

**Comment by MarcSabatella** [comment] 2024-04-15 15:30
I’ve never encountered anything like that using the supported build (AppImage) on Debian.  But maybe you have an option set in your OS to enabled exclusive audio mode?  You could disable that if so.  Probably best to ask for further help diagnosing the issue over on the sforums at MuseScore.org.  When you do so be sure to give additional system info like what audio system you run, and whether you installed the AppImage or are running it from the command line each time.

**Comment by krtschil** [comment] 2024-04-15 16:32
My system (based on Ubuntu 22.04 KDE) seems to use Pipewire as the sound system. It seems to be the successor of PulseAudio.
The symptoms are:

- When any application running is destined to use the sound system (like Firefox in my case), even if not playing anything actually, MuseScore reports that it cannot access the audio system (see error message in the original post). 
- I have to shut down any applications that MIGHT use the audio system before I start MuseScore 
- As soon as MuseScore is running and playing a piece any other application I try to start (Firefox, video player, audio player) and play a sound that is then refused because it seems that MuseScore is exclusively using the audio device.

I have no idea how to configure MuseScore/the OS to NOT use the audio device exclusively. 
When MuseScore is active and doing playback the audio system does not show that this application is using the sound device (as is done by other applications, where I can see that e.g. Firefox is currently using the sound device).
Other applications can use the sound system simultaneously without problems.

By executing "fuser -v /dev/snd/*" I get output that says:

Client #32
        Treiber: PipeWire
        Owner-Modul: 2
        Eigenschaften:
                pipewire.protocol = "protocol-native"
                pipewire.sec.socket = "pipewire-0-manager"
                pipewire.sec.pid = "2282"
                pipewire.sec.uid = "1000"
                pipewire.sec.gid = "1000"
                pipewire.sec.label = "unconfined"
                module.id = "2"
                object.id = "32"
                object.serial = "32"
                application.name = "WirePlumber"
                application.version = "0.5.1"
                wireplumber.daemon = "true"
                wireplumber.profile = "main"
                remote.name = "[pipewire-0-manager,pipewire-0]"
                config.name = "null"
                cpu.max-align = "32" 
....

**Comment by RomanPudashkin** [comment] 2024-04-25 08:28
Looks like a duplicate of https://github.com/musescore/MuseScore/issues/15937

**Closed by RomanPudashkin** 2024-04-25 08:28 UTC
Labels: community, playback, os: linux
