### ISSUE TITLE
[MU4 Issue] [Inspector] Guitar position line (Capo line) is not editable in Properties

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9878] opened 2021-11-25 15:46 UTC
Guitar position line (Line with roman numeral) is not editable in Properties

https://user-images.githubusercontent.com/90187801/143470582-41d6357d-c753-421a-bf16-c69522235bb0.mp4

**Desktop:**
Win/Mac/LinuxMint

**Comment by Jojo-Schmitz** [comment] 2021-11-25 15:52
You mean the Capo line? It doesn't exist anymore in 3.6, got replaced by a staff text line, that former roman numeral now reading "Staff" (and accompanoed by a corresponding system text line), I wonder whether this should happen in master too?
Still it does need to be editable.

**Comment by LovCAPONE** [comment] 2021-11-25 21:33
Since this issue isn't assigned to anyone I'll fix it and make a PR.

**Comment by DmitryArefiev** [comment] 2021-12-06 14:55
I've added Capo line as well. Yes, in MU3 3.6 that line has Staff text indeed. Thanks for investigation! 
Occurs in master

**Comment by bkunda** [comment] 2021-12-14 09:00
I can confirm that staff text lines are not in master at the moment, only "text line" with this icon:

<img width="81" alt="Screenshot 2021-12-14 at 7 57 55 pm" src="https://user-images.githubusercontent.com/86290556/145966114-c6ad26ed-d644-4ae1-9e26-8399c64c3782.png">

I would like to see this revert back to MS3.6 behaviour, with this icon: 

<img width="82" alt="Screenshot 2021-12-14 at 7 58 39 pm" src="https://user-images.githubusercontent.com/86290556/145966226-6ea42227-6c46-4609-b400-2beef2b775d3.png">

The potential function of this symbol extends beyond indicating guitar fret positions. Indeed, if possible I think this issue is important enough to go to alpha if possible (@vpereverzev, @DmitryArefiev). A good amount of guitar music at least cannot be engraved without this working.

**Comment by Jojo-Schmitz** [comment] 2021-12-14 09:18
I beliebe Text line __is__ Staff Text line, and System Textline is missing

**Comment by bkunda** [comment] 2021-12-14 09:34
You're right @Jojo-Schmitz, system text line does indeed appear to be missing. 

I don't have a strong opinion about having both staff text line and a separate one for guitar fret positions, but it seems like we could have both (indeed, perhaps that was the original design, because the fret position icon has evidently been created for MS4. Was this always the case @Tantacrul?)

@DmitryArefiev, would you suggest we re-scope this issue to include reinstating both staff text and system text lines as per MS3.6? Or would these be better raised separately?

**Comment by Jojo-Schmitz** [comment] 2021-12-14 09:42
Since the change of that (Capo) Text line to a Staff text line (and the addition of the System text line), we're getting questions in the forums about where that Capo line went,, so IMHO we should have it in addition to Staff- and System text line.

**Comment by Tantacrul** [comment] 2021-12-14 10:16
Oh dear. I missed the Capo line in my designs. @bkunda - I think it is obvious what the design should be. I'll leave it to you?

**Comment by bkunda** [comment] 2021-12-14 11:51
I'll get onto this pronto!

**Comment by DmitryArefiev** [comment] 2022-01-14 12:50
Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED in #10240

Closing

**Closed** 2022-01-14 12:51 UTC
Labels: P3
