### ISSUE TITLE
Musescore audio seems to have a low pass filter

### ISSUE THREAD

**Issue by fernandomartin777** [musescore/MuseScore#19495] opened 2023-09-23 23:50 UTC
### Issue type

Other type of issue

### Bug description

I always notice that some instruments in Muse Sounds have limited brightness and harmonics. Then lately I compared playing some score with exactly the same soundfonts at MU 3 and MU4 and noticed that they sound significantly brighter in MU3. The playback in MU4 of both, sf2 and muse sounds, seems to have a low pass filter, where the soundfonts and instruments lose a noticeable amount of harmonics and brightness when compared to MU3.

### Steps to reproduce

1 - Open the same score at MU3 and MU4.
2 - Choose a soundfont with a significant bright sound for both.
3 - Play in one after another.
4 - There's a noticeable difference in pĺayback quality as if MU4 was low pass filtered.

### MuseScore Version

Musescore 4.1.1

### Regression

I don't know

### Operating system

Ubuntu 23.04 AppImage

**Comment by cbjeukendrup** [comment] 2023-09-24 12:24
Does this help?
1. Make Aux 1 channel visible: 
    <img width="1050" alt="Scherm­afbeelding 2023-09-24 om 14 22 08" src="https://github.com/musescore/MuseScore/assets/48658420/2c9b1d92-d5e3-4da1-a7f2-e3ef0f55ad6e">
2. Turn off reverb, so that it becomes grey instead of blue:
    <img width="862" alt="Scherm­afbeelding 2023-09-24 om 14 20 47" src="https://github.com/musescore/MuseScore/assets/48658420/5bc6525b-a813-469e-9ea9-be3b5c6f8b7e">

If that helps, then the problem is caused by that reverb algorithm.

**Comment by fernandomartin777** [comment] 2023-09-25 02:07
> Does this help?
> 
>     1. Make Aux 1 channel visible:
>        <img alt="Scherm­afbeelding 2023-09-24 om 14 22 08" width="1050" src="https://user-images.githubusercontent.com/48658420/270163623-2c9b1d92-d5e3-4da1-a7f2-e3ef0f55ad6e.png">
> 
>     2. Turn off reverb, so that it becomes grey instead of blue:
>        <img alt="Scherm­afbeelding 2023-09-24 om 14 20 47" width="862" src="https://user-images.githubusercontent.com/48658420/270163677-5bc6525b-a813-469e-9ea9-be3b5c6f8b7e.png">
> 
> 
> If that helps, then the problem is caused by that reverb algorithm.

Thank you for your quick reply. Unfortunately that doesn't help. Things remain the same. Do you want to reproduce it? 
Create a single staff score in MU 3 with electric guitar as the instrument. Write a monophonic melody on it in the soprano range (concert pitch). Play it in MU 3 and 4 using this soundfont:
[https://www.dropbox.com/scl/fi/yo25ysly5aobfzk3hg36m/06_Guitar_Gibson_Les_Paul.sf2?rlkey=ij2p2z9ashzbco7czq9uju2br&dl=0](url)
The difference is very significant, no matter if reverb is on or off.

**Comment by bkunda** [comment] 2023-09-25 07:57
@RomanPudashkin can you please confirm whether we process audio with low pass filter at any point? Would be good just to get factual clarity on this before working out how to proceed with this issue. Thanks!

**Comment by fernandomartin777** [comment] 2023-09-25 16:48
I really appreciate your willingness to work on this issue. I described that it sounds like a low pass filter, but I don't know if it's some kind of equalization or something else. If you make some significant change, you can tell me, that I'm willing to test it on nightly appimages too.

**Comment by ShibuyaCyana** [comment] 2023-12-02 16:45
![image](https://github.com/musescore/MuseScore/assets/39703247/d5bfa3e4-ca09-4d7a-8edb-6e0610ec1b83)
This is a nice multi-layer sampled sf; in MU3 it's triggering the **2nd** loudest layer by default and you can change that with dynamics, while in MU4 it's triggering the **3rd** layer, and since there's no MIDI velocity support for now, changing dynamics is only affecting playback volume.

If this sounds like the difference you hear, then that's definitely the cause:

https://github.com/musescore/MuseScore/assets/39703247/32549c4f-b93a-4907-b9a1-0eeb6f2fa153

(P.S. this sounds really good indeed, may I ask where I can get more of this? : )

**Comment by fernandomartin777** [comment] 2023-12-07 17:18
> ![image](https://private-user-images.githubusercontent.com/39703247/287461658-d5bfa3e4-ca09-4d7a-8edb-6e0610ec1b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Njk3MDcsIm5iZiI6MTcwMTk2OTQwNywicGF0aCI6Ii8zOTcwMzI0Ny8yODc0NjE2NTgtZDViZmEzZTQtY2EwOS00ZDdhLThlZGItNmUwNjEwZWMxYjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE3MTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MzY1MjM0NzJiNWU1YTVhY2UwMzAzODQ3NjQxYjdjYWM5NzE3MDM1YzFkZDU1YWYxNDc0NWFkZTg0YzJkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_VixyQgjls_cCDywXr7OUYDiN-ndIIVJMFuCkfoV5M) This is a nice multi-layer sampled sf; in MU3 it's triggering the **2nd** loudest layer by default and you can change that with dynamics, while in MU4 it's triggering the **3rd** layer, and since there's no MIDI velocity support for now, changing dynamics is only affecting playback volume.
> 
> If this sounds like the difference you hear, then that's definitely the cause:
> layer.diff.mp4
> 
> (P.S. this sounds really good indeed, may I ask where I can get more of this? : )

Thank you for solving the mistery. However if MU4 is not able to identify dynamic layers in sf2 it kills the realism of several HQ sf2 and leaves ties to muse sounds that is also very unven and unstable across dynamic and melodic ranges.

**Comment by ShibuyaCyana** [comment] 2023-12-07 17:49
> Thank you for solving the mistery. However if MU4 is not able to identify dynamic layers in sf2 it kills the realism of several HQ sf2 and leaves ties to muse sounds that is also very unven and unstable across dynamic and melodic ranges.

Here's an issue for this: #19207
Seems that it was formerly planned to be fixed in 4.2, there was even a pending fix before this issue came up, but didn't make itself into 4.2 or master branch. But good news is MuseSound for electric guitar is coming soon, most likely released with 4.2.

**Comment by cbjeukendrup** [comment] 2023-12-07 18:33
Indeed, https://github.com/musescore/MuseScore/issues/19207 is about the problem that dynamics affect volume instead of velocity. That is the reason that layer-choosing for sound fonts is not working currently. 

We originally wanted to fix that issue for 4.2, but I believe there were some complications, forcing us to bump it in order not to delay the 4.2 release too much. So, 4.3 it is!

Anyway, since the cause of this issue is covered by https://github.com/musescore/MuseScore/issues/19207, would you agree to close this issue?

**Comment by fernandomartin777** [comment] 2023-12-08 01:59
Yes. You can close the issue.

**Closed** 2023-12-08 01:59 UTC
Labels: needs info, needs review
