### ISSUE TITLE
Attempting to drag&drop parentheses on natural sign inserts a new bar instead of the parenthesis

### ISSUE THREAD

**Issue by paulalndwhr** [musescore/MuseScore#22959] opened 2024-05-23 17:49 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

**bar insertion bug**
1. have any natural placed in front of a note
2. attempt to drag&drop a parenthesis on the natural sign
3. observe a new measure inserted infant of the measure containing the natural sign

**nothing happens bug**
1. have any natural placed in front of a note
2. select the natural
3. attempt to place a parenthesis by clicking on the parenthesis form the palette side bar
4. observe that nothing happens

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/109522890/44927424-86ac-469a-bf89-12fc0a4f74f2

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13.x

### Additional context

I would be surprised if this is a MS4 bug and did not work under 4.1 or 4.2 because I feel like I used the drag&drop relatively recently and it worked fine, but I am unsure.
Unfortunately, I cannot find this out myself at the moment.

**Comment by MarcSabatella** [comment] 2024-05-23 21:44
I can't reproduce.  Are you sure you are releasing directly on the natural sign?  Also, does it happen only with drag & drop, or does it also occur when adding the parentheses normally - by selecting the natural siugn then either clicking the palette item or pressing "(" on your keyboard?  For me all three work as expected.

Could be an issue with your specific score as well, so best to ZIP and attach that if you continue to have trouble.

**Comment by paulalndwhr** [comment] 2024-05-24 07:26
The problem occurred independently from the score opened.

Adding from the palette had no effect (no measure added, no parenthesis added to the accidental). Adding with the shortcut had no effect.

This video show my attempts to drag and drop to the accidental very carefully, on a very zoomed-in view.
https://github.com/musescore/MuseScore/assets/109522890/779f1bf5-9eea-417a-941a-146ac3050bf8

Adding the parenthesis by
1. selecting the accidental
2. opening the properties sidebar
3. clicking on the parenthesis there
works fine as expected.

**Comment by MarcSabatella** [comment] 2024-05-24 12:50
Strange, I still can’t reproduce any sort of problem, but maybe it is an issue on macOS only?  Also it appears you have customize your palette (those parentheses would not be on the main portion of the palette normally).  Maybe something went wrong during the customization process.  Try resetting the palette (via its “…” menu) and trying again. Or you might need to try Help / Revert to factory settings.

**Comment by bkunda** [comment] 2024-05-24 13:42
@zacjansheski can you also pls try reproduce this?

**Comment by zacjansheski** [comment] 2024-06-13 20:33
Closing, unable to reproduce.

Feel free to raise a new issue if new evidence arrises

**Closed by zacjansheski** 2024-06-13 20:33 UTC
Labels: needs info, regression_ms3, UX/interaction

**Comment by cbjeukendrup** [comment] 2024-08-20 20:03
For the record, this issue has gotten a second life in https://github.com/musescore/MuseScore/issues/24060, where we found the root cause of it (https://github.com/musescore/MuseScore/issues/24060#issuecomment-2299665318).
