### ISSUE TITLE
[MU4] Changing note positions causes errors in playback. Old note positions still play, even when changed

### ISSUE THREAD

**Issue by OwenV1** [musescore/MuseScore#14302] opened 2022-11-04 00:54 UTC
**Describe the bug**
Repeats causing notes to play incorrectly.

**To Reproduce**
(https://watch.screencastify.com/v/s0AXOHkSpxbqKjJcRaLX)

**Expected behavior**
The original note and all other notes used to go from start to finish will play at the same time..

**Screenshots**
N/A

**Platform information**
Windows

**Additional context**
N/A

**Comment by Tantacrul** [comment] 2022-11-08 17:40
Unable to reproduce. If you could provide a video demonstrating what you mean, that would be really appreciated. I'm going to close for now until we have more info that can help us solve the issue.

**Comment by MarcSabatella** [comment] 2022-11-08 19:59
I can reproduce and see this pretty often, although I've never figured out the steps until just now.  The key seems to be the presence of a repeat somewhere earlier in the score.

https://watch.screencastify.com/v/s0AXOHkSpxbqKjJcRaLX

Seems likely connected to other repeat issues like https://github.com/musescore/MuseScore/issues/13811, but this one is not *within* the repeated section - it's *after* it.

**Comment by Tantacrul** [comment] 2022-11-08 22:51
Would be good to test this when Vasily's latest fixes for repeats is merged.

**Comment by OwenV1** [comment] 2022-11-08 23:27
https://youtu.be/OJ95VJmMdPQ
here's where I first encountered the issue.  It seems to be fixable by toggling Concert Pitch or closing and re-opening the score.

**Comment by DmitryArefiev** [comment] 2022-11-14 15:13
Fixed in #14449

**Closed** 2022-11-14 15:15 UTC
Labels: P2

**Comment by MuriloOSPM** [comment] 2026-05-12 11:42
Which tab is for help/diagnostics/reload playback cache
