### ISSUE TITLE
[MU4 Issue] [Muse Sounds] Muse Sounds becomes disabled since Nov. 2, 2022, nightly build

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14279] opened 2022-11-02 20:08 UTC
**Describe the bug**
Muse Sounds becomes disabled for Nov. 2, 2022, nightly build.

**To Reproduce**
1. Make sure you have an installation of MU4 with Muse Sounds available.
3. Switch to the Nov. 2, 2022, nightly build (MuseScoreNightly-223060426-master-e8ea5b8-x86_64.7z). (I did this by renaming the `C:\Program Files\MuseScore 4` folder to something else and then create a directory junction named `C:\Program Files\MuseScore 4` pointing to the folder containing the decompressed nightly build. This has been working for each nightly build since the beta.)
2. Create a score.
5. Open the mixer and observe that Muse Sounds cannot be selected.
6. Open Playback setup and find that Muse Sounds has a check mark next to it but grayed out.
![image](https://user-images.githubusercontent.com/10248807/199592344-31e87c42-9ba0-4635-99d9-f12f8516bb2a.png)
7. Reinstall Muse Sounds using Muse Hub.
8. Observe that Muse Sounds remains grayed out.

**Expected behavior**
Muse Sounds should continue to be available.

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment] 2022-11-02 23:37
MuseScore now has a check for the MuseSampler version; it requires the latest one. Normally it should be auto-updated by the Muse Hub, but you may need to (re)start the Hub to make this happen.

**Comment by SamYeh** [comment] 2022-11-03 03:18
@cbjeukendrup Thank you. I rebooted my computer, launched Muse Hub to make sure that everything is up to date, and launched MU4 nightly build. The issue did not go away.

![image](https://user-images.githubusercontent.com/10248807/199641327-948c2f4a-4488-4bee-8814-4ce29f932ffa.png)

![image](https://user-images.githubusercontent.com/10248807/199641345-9c34cc5e-8e59-407d-9a78-ebd196027472.png)

**Comment by SamYeh** [comment] 2022-11-03 04:27
![image](https://user-images.githubusercontent.com/10248807/199647563-895c4f3e-49c6-4d7f-9db1-51686dc4ef17.png)

![image](https://user-images.githubusercontent.com/10248807/199647571-b286afb6-281f-4f17-b383-69e189624c75.png)

**Comment by SamYeh** [comment] 2022-11-03 04:36
I worked around the problem by copying `MuseSamplerCoreLib.dll` into MU4's `bin` folder. The DLL was extracted from 'MuseHub/Downloads/Installers/610ee8e7-40e7-4f12-96cf-b3806dc12e7d/MuseSamplerCoreLib.zip'.

**Comment by MarcSabatella** [comment] 2022-11-03 13:02
Similar on Linux.  Last night's build no longer recognizes Muse Sounds.  I re-ran Muse Hub but nothing reported it was updated.  The date on libMuseSamplerCoreLib.so is last night, which is the last time I ran Muse Hub previously.  BTW, I hadn't noticed this before, but the ownership on the file is weird, shows group of 50 ("staff"), user id of 9212824.  Everything else installed by Muse Hub is root/root.  But, changing ownership of the .so doesn't help.

**Comment by MarcSabatella** [comment] 2022-11-03 15:03
I've tried some without success to find a good copy of that file.  At least, I'm hoping it's as simple as that, since it apparently works on Windows.

@Tantacrul - TL;DR - Msue Sounds is unusable in nightlies right now

**Comment by MarcSabatella** [comment] 2022-11-03 18:11
I think in my case at least, the issue is the bad copy of libMuseSamplerCoreLib.so.  On my other Linux machine, I checked and it's the Oct 26 version, and even after updating to current nightly, it works.  So the problem on the first Linux was somehow getting a Nov 2 Muse Sampler - which, BTW, was also about 100K smaller than the Oct 26 version.  Maybe it was just a bad download, but not sure why it downloaded anything at all.

**Comment by iamtesch** [comment] 2022-11-04 13:46
We are working to release a new version of Muse Sampler here that works with the latest Muse Score nightly and upcoming Beta release.  There was a sampler release on Nov 2 that was shortly removed after discovering an incompatibility with an upcoming Muse Score beta release (due to a incorrect version string), but this should be replaced within the next couple of hours.

Unfortunately, we cannot guarantee compatibility with all nightly snapshots, as there may be intermediate changes between the tested releases on the hub.  But we appreciate the early notice of issues here!

**Comment by iamtesch** [comment] 2022-11-04 14:37
Ok, this should be resolved now.  There will be a corresponding hub update as well in a few hours, as this is linked to a separate hub issue with hub version 0.9.8 (which I have disabled for now) during sampler installation.  For now, can you uninstall and reinstall hub from the .deb package, and let me know if the sampler issue still persists on the nightlies or if this is resolved?

**Comment by MarcSabatella** [comment] 2022-11-04 16:29
I had already uninstalled and reinstalled from the .deb, which had fixed things, other than the mysteriously missing Muse Keys sounds.  My Muse Hub is 0.9.8.292.  Unless you're looking for a test to see what happens if I uninstall/reinstall again, I'd just as soon wait for the next update since I'm OK for now.

**Comment by MarcSabatella** [comment] 2022-11-04 20:25
After today's beta update, I was able to access Muse Hub, but it didn't detect any update to sounds.  So I unintalled and reinstalled msue hub, using the new download link.  It currently reports 0.9.9.295.  I'm able to re-download Muse Sounds, but, neither the new "beta 2" (if that's what we're calling it) build of MsueScore 4 nor the most recently nightly can access Muse Sounds at all anymore - they are gone from the mixer, and grayed out in View / Playback setup.

I'm on Linux, and I no longer have a /usr/lib/libMuseSamplerCoreLib.so, so I'm guessing that might be the issue as far as that goes.  Originally it was installed by Muse Hub I believe, but that doesn't seem to have happened today.

**Comment by MarcSabatella** [comment] 2022-11-04 20:35
...and *now* I do have libMuseSamplerCoreLib.so, only after downloading and installing *all* sounds.  I had originally tried just downloading a few, but that didn't do the trick, even after the first batch complete.  So I decided I might as well download the rest.  When *that* completed (woodwinds was last), the library appeared.

And sure enough, Muse Sounds now works in MuseScore, both nightly and beta 2.

**Comment by iamtesch** [comment] 2022-11-05 04:18
Sorry for the issues here -- I'm glad this is resolved now.  This likely was fixed when you downloaded or updated a sound after the hub had finally updated (to fix the bug in downloading the sampler), rather than being triggered by downloading all the sounds, or a coincidence of timing when we got the next sampler update out.  But regardless, this should be fixed for you and other users running into these issues now.

Sorry that this got into a bit of a messy state; we've got a more robust testing procedure now to prevent this from occurring again.  Thanks for your patience here!

Btw, in the future, you can tap the "check for updates" to force a sampler check/update in the background as well.  It won't show any progress indicators, but should download and install if there is an update.

**Closed by iamtesch** 2022-11-05 04:18 UTC
Labels: P1

**Comment by MarcSabatella** [comment] 2022-11-05 15:03
Sounds good.  My other Linux system also was in the same situation so I just left it alone yesterday.  It still was doing nothing even after hitting the check for update button (which I had tried yesterday as well), but downloading one more sound today got it working - the sampler finally installed and Muse Sounds are now accessible on that machine too.

The hub, BTW, still reports 0.9.9.295.  Not sure if that's the most current or if somehow I'm still missing an update.

And having been in the software business, I know install/update issues are the worst, so thanks for being on this!
