### ISSUE TITLE
[MU4 Issue] Pasting music with tuplets causes the tuplet marking to disappear 

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#14120] opened 2022-10-27 23:14 UTC
Sometimes when copying and pasting lines of music that include tuplets, the tuplets marking will disappear. Playback and the notes will still be there, just the lines and text indicating that it is a tuplet disappear.

**To Reproduce**
1. Write a line of music with lots of tuplets (I used half note triplets). 
2. Copy and then paste in a different staves.

**Expected behavior**
I expected the triplet marking to be pasted along with the notes.

*
<img width="2553" alt="Screen Shot 2022-10-27 at 7 13 42 PM" src="https://user-images.githubusercontent.com/103294056/198414941-5b208499-634a-4ace-9528-446fba2a82ea.png">
*Screenshots**

**Platform information**
 - OS: macOS

**Comment by cbjeukendrup** [comment] 2022-10-27 23:22
It looks a lot like this is a duplicate of #13569, which has been fixed meanwhile. Please try the latest "nightly build" (see https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds for how to do that) to confirm that this doesn't happen with those.

**Comment by pgrimes2002** [comment] 2022-10-27 23:33
Ahh thanks. It does work now

**Comment by cbjeukendrup** [comment] 2022-10-27 23:35
Happy to hear that! Let's close this issue in that case :)

**Closed by cbjeukendrup** 2022-10-27 23:35 UTC
