### ISSUE TITLE
Cannot open files which not named in english

### ISSUE THREAD

**Issue by Beafty** [musescore/MuseScore#24346] opened 2024-08-31 17:27 UTC
### Issue type

Opening/saving issue

### Description with steps to reproduce

1.Open File
2.
![image](https://github.com/user-attachments/assets/c5319fd8-12eb-490e-a098-6e1aded1d6d9)

### Supporting files, videos and screenshots

2024-09-01T01:20:43.176 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
2024-09-01T01:20:43.370 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: file-open
2024-09-01T01:20:43.370 | INFO  | main_thread     | ProjectActionsController::openProject | Try open project: url = "file:///D:/闊充箰/鏁㈤棶璺\uE21A湪浣曟柟.mid" , displayNameOverride = "" 
2024-09-01T01:20:46.381 | ERROR | main_thread     | <lambda_2>::operator  | Unable to check for update, error: [1701] 
2024-09-01T01:20:48.815 | WARN  | main_thread     | Qt              | QQmlComponent: Created graphical object was not placed in the graphics scene.
2024-09-01T01:20:49.480 | ERROR | main_thread     | <lambda_2>::operator  | Unable to check for update, error: [1701] 
2024-09-01T01:20:49.905 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: diagnostic-save-diagnostic-files
![image](https://github.com/user-attachments/assets/6e3f684c-b697-448e-a027-1d996be13f6d)
[log generated by musescore4.zip](https://github.com/user-attachments/files/16825519/log.generated.by.musescore4.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0 fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-08-31 22:33
Duplicate of https://github.com/musescore/MuseScore/issues/23811 - fix is underway and arriving soon!

**Closed** 2024-08-31 22:33 UTC
Labels: duplicate, regression MS4
