### ISSUE TITLE
[MU4 Issue] Crash on quit when using Kontakt Player on other VSTe (Mac only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10930] opened 2022-03-28 12:53 UTC
**To Reproduce**
1. Open a score
2. Add Kontakt Player as VSTi
3. Quit with Cmd+Q

https://user-images.githubusercontent.com/90187801/160401863-175120b5-a51a-41c1-9f9b-622e161b9f16.mov

**Platform information**
 macOS 12.2, M1 laptop

**Additional info**

[crash.txt](https://github.com/musescore/MuseScore/files/8364661/crash.txt)

The issue also reproduces with plugins:
- Valhalla
- LABS

**Comment by DmitryArefiev** [comment] 2022-03-29 08:17
@vpereverzev Still occurs in master..

[crash 2.txt](https://github.com/musescore/MuseScore/files/8369380/crash.2.txt)

**Comment by vpereverzev** [comment] 2022-03-29 14:05
MuseScore stops working, asks plugins to release resources, and exits with no error codes. However, it seems like Kontakt is not prepared for the fact that work can stop before the loading of its resources is finished, which it's handling in the background thread. Need to discuss this directly with the Kontakt developers

**Comment by Tantacrul** [comment] 2022-09-20 23:02
Dmitri, is this still happening?

**Comment by DmitryArefiev** [comment] 2022-09-21 12:34
@Tantacrul Yes, still occurs. And also the same think with Valhalla supermassive plugin

**Comment by DmitryArefiev** [comment] 2022-09-21 12:34
@abariska Can you try on your side please?

**Comment by abariska** [comment] 2022-09-21 12:38
Reproducible on my mac. 
On this score 
[Crash_Kontakt_Valhalla.mscz.zip](https://github.com/musescore/MuseScore/files/9616570/Crash_Kontakt_Valhalla.mscz.zip)

**Comment by Tantacrul** [comment] 2022-10-03 13:02
OK, fantastic. I can reproduce with NI Kontakt. Haven't tried the others yet.

**Comment by Tantacrul** [comment] 2022-10-21 11:32
We're having issues with Kontakt VST3, where closing it causes issues on Mac. Apparently, it's a known issue with Kontakt and we don't think its wise to try and attack it for Release. I've increased the severity and moved to 4.x.

**Comment by bkunda** [comment] 2023-01-13 13:45
See also #15853, which may likely just be another case of the present issue.

**Comment by Tantacrul** [comment] 2023-02-06 13:00
Seems to be a duplicate of [#15853](https://github.com/musescore/MuseScore/issues/15853)

**Comment by DmitryArefiev** [comment] 2023-02-16 15:50
Fixed in #16306

**Closed** 2023-02-20 15:25 UTC
Labels: P0

**Comment by DmitryArefiev** [comment] 2023-03-03 14:14
Retested on Mac12.6
