### ISSUE TITLE
guitar has no working "let ring" ("pedal")

### ISSUE THREAD

**Issue by burbanmaya** [musescore/MuseScore#21066] opened 2024-01-18 12:38 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

writing music for the guitar with the muse sounds library, i noticed there is no way to get the guitar to hold multiple notes and if you want to arpeggiate a chord it will only

### Steps to reproduce

1. write a measure of music on the guitar consisting of 4 repeating eighth notes that are each meant to be played on a separate string and held as if a chord
2. select the entire bar of music and add a "let ring" line
3. play the measure back
4. it does not let ring

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/157021437/7d11fb19-82fd-4a61-8771-83b1bd1bba0e)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

issue was encountered using the MuseSounds library.
![guitar hold sample](https://github.com/musescore/MuseScore/assets/157021437/df4abc27-42f9-42ad-8e67-e12cdb4b0e0d)
(i embedded the score as a jpg, just change the format back to mscz)

**Comment by MarcSabatella** [comment] 2024-01-18 14:27
This would seem to be a duplicate of https://github.com/musescore/MuseScore/issues/20993

**Comment by zacjansheski** [comment] 2024-01-18 19:50
Closing as duplicate of https://github.com/musescore/MuseScore/issues/20993

**Closed by zacjansheski** 2024-01-18 19:50 UTC
Labels: regression_ms3, UX/interaction
