### ISSUE TITLE
[MU4 Issue] "Advance cursor" (figured bass/chord symbols) command not working

### ISSUE THREAD

**Issue by Der-Leiermann** [musescore/MuseScore#14916] opened 2022-12-03 15:43 UTC
**Describe the bug**
Edit by @bkunda: 

The shortcuts `Cmd`+`1`...`9` no longer work to advance the cursor by durational value when entering chord symbols or figured bass. This prevents the user from, for example, indicating multiple chords over a sustained note. It also makes navigation more tedious, especially when entering figured bass.

We are fairly certain the current effect on chord symbols in particular is a recent regression ([see discussion below](https://github.com/musescore/MuseScore/issues/14916#issuecomment-1339549369)).

**To Reproduce**
Steps to reproduce the behavior (example here is for figured bass):
1. Enter half note.
2. Select the note and press `Command` + `G`.
3. Enter figure.
4. Press `Command` + `5`.
5. See that the cursor has not advanced

**Expected behavior**
The cursor should have advanced by the value of a quarter note

**Platform information**
 - OS: macOS Ventura 13.0.1 (also tested on macOS 12.6)
 - MuseScore version: Release Candidate 1

**Comment by MarcSabatella** [comment] 2022-12-03 18:56
I can confirm this, but I would add, you really should enter an actual figure between pressing Cmd+G and then changing the duration.  Not sure that would be defined.  But certainly, after entering the figure, Cmd+number should work, and currently does not (well,m Ctrl+number on keyboards other than Mac).

**Comment by sammik** [comment] 2022-12-03 20:45
I can confirm on Linux.

And it is regression from (from 3.6.2, where everything worked) and also from RC0 (where duration worked, but "space" didnt /it started playback/). Here, in RC1 it is oposite ("space" works as "next note", but duration doesnt).

**Comment by Der-Leiermann** [comment] 2022-12-03 21:33
@MarcSabatella Thanks, I updated the steps. Also, apologies for accidentally closing. :)

**Comment by bkunda** [comment] 2022-12-06 14:44
I too can confirm this, but unfortunately I can't check the regression status against an earlier build, because every old build I try to run crashes on my machine when opening! 🤷‍♂️
Anyway, it is a sufficiently bad one in that, without the navigation commands, the user has to rely on the mouse to click on every note for which they wish to add figured bass.

**Comment by MarcSabatella** [comment] 2022-12-06 15:44
No, I was unaware there was a problem until I decided to try to see if I could find a workaround for the figured bass problem, then it dawned on me to try it for chord symbols.

It's the same bug since it's the same command, and probably the same fix will address both.

I can't say exactly when the regression occurred because of course older builds won't run anymore unless I uninstall Muse Sounds.  But I did check with an August build, and it definitely worked then.

**Comment by bkunda** [comment] 2022-12-06 15:48
Ok I might actually re-classify this bug then (and edit the description. @Der-Leiermann hope that's okay – it will keep things nice and streamlined for us!).

**Comment by Tantacrul** [comment] 2022-12-09 17:23
Due to potential risks, we're moving this to Post Release.

**Comment by DmitryArefiev** [comment] 2022-12-28 11:00
Fixed in #15081

**Closed** 2022-12-28 11:06 UTC
Labels: P1
