### ISSUE TITLE
Style Window has extreme latency

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#17120] opened 2023-04-03 08:24 UTC
### Issue type

UI bug

### Bug description

When I try to open the Style Window (which I'd love to be seen reworked a bit), it takes about 5-20 seconds until the window opens. During that time MSC appears to be blocked/crashed. 

### Steps to reproduce

Just open the menu Format -> Style...

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/12497326/229450050-6ca33ec5-bc46-4fc6-85d2-a17403376c2b.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

I have some thoughts for that one, I'd like to share:
- it'd be great, if the window wasn't modal, so that it blocks the entire UI when opened 
   -> the changes are rolled out in the background (which is great), but you can not navigate around the score to see, what has changed in other places than the current view
   -> when MSC plays while style is activated you have to wait unteil the window is closed again in order to stop playback
- Page Settings could be integrated into Style windows as well 
- the options to load/save a style (which is just great) are just inside the format menu (which is okay), but it is not inside the style window itself (where I would search for it in the first place)
- some of the options inside the Style window could be documented/explained a bit better (maybe an "easy" and an "advanced" mode could help to keep a good overview, hiding away information that is just important for the pros)
- it could be integrated into its own panel, just like the inspector/properties panel instead

**Comment by oktophonie** [comment] 2023-04-03 08:26
Duplicate of https://github.com/musescore/MuseScore/issues/13193

**Closed by oktophonie** 2023-04-03 08:26 UTC
Labels: UI, duplicate, regression
