### ISSUE TITLE
[MU4 Issue] Add - Measures, unable to confirm by "Enter", regression

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13180] opened 2022-09-05 17:13 UTC
**Describe the bug**
Unable to confirm Add - Measures dialog right by "Enter". 
User needs to press "Tab" first.

**To Reproduce**
1. Add - Measures
2. Change number of measures to add, or not
3. Press "Enter"
4. Nothing happens

**Expected behavior**
Dialog should be confirmedright by "Enter"

**Screenshots**

https://user-images.githubusercontent.com/1646034/188493674-2cad50cc-98c6-4283-a76b-21162c9f3b42.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
- regression from MU3
- "Esc" works as expected

**Comment by MarcSabatella** [comment] 2022-09-05 17:35
FWIW, I've noticed this or similar about a number of dialogs.  Like the new score wizard after selecting a template, which used to automatically do "next" on the initial pages and then "finish" on the last.  Also Preferences.  And yet other dialogs that have input fields *do* seem to have OK hooked up to the Enter key, like Style, Page Settings, and Transpose.

**Comment by oktophonie** [comment] 2022-09-05 17:36
Likewise. The 'create new time sig' dialog behaves similarly.

**Comment by wizofaus** [comment] 2022-09-05 20:23
I suspect it depends on which ones are QWidget vs QML dialogs?

**Comment by cbjeukendrup** [comment] 2023-01-06 13:12
Duplicate of #12222. And indeed related to QML dialogs in general, where nothing works automatically...

**Closed by cbjeukendrup** 2023-01-06 13:12 UTC
