### ISSUE TITLE
Playback time overlap on other icon

### ISSUE THREAD

**Issue by soiamsoNG** [musescore/MuseScore#22021] opened 2024-03-22 07:49 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Time text overlap on the other icon, no matter English or Chinese translation, docked on the toolbar or undocked 

### Steps to reproduce

1) open musescore

### Screenshots/Screen recordings

dock on the toolbar
![screen_shot](https://github.com/musescore/MuseScore/assets/11811568/0dffb2de-6727-4cf7-a243-9f32cb6ca23e)

undocked
![screen_shot_2](https://github.com/musescore/MuseScore/assets/11811568/2111e752-5fbf-4cf0-97c0-bb463a019a7b)

### MuseScore Version

4.2.1  flathub version

### Regression

I don't know

### Operating system

Fedora 39

### Additional context

locale

LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"

**Comment by Eism** [comment] 2024-03-22 07:54
Duplicate of #21036
Thank you for reporting!

**Closed by Eism** 2024-03-22 07:54 UTC
Labels: UI
