### ISSUE TITLE
[MU4 Issue] Move Cursor in Chord Entry not possible using CTRL+duration option

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#15690] opened 2023-01-02 20:14 UTC
**Describe the bug**
While in Chord Entry mode, you should be able to move the cursor according to a specified duration.
Shortcut combinations exists for this, but do not work. For instance CTRL+5 should move by a quater note.
Seems all duration shortcuts are not working in chord entry.

**To Reproduce**
1. Open a score
2. Start Chord Entry mode (ctrl+K)
3. Enter a Chord Symbol
4. Press CTRL+5 to move the cursor

**Expected behavior**
Cursor should be moveable by specifying the duration using the shortcut defined for that.

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment] 2023-01-02 21:16
This seems a duplicate of https://github.com/musescore/MuseScore/issues/14916, which was recently fixed by https://github.com/musescore/MuseScore/pull/15081 for the latest nightly builds.

**Closed** 2023-01-02 21:16 UTC

**Comment by henkdegroot** [comment] 2023-01-02 21:39
Thanks for this! Apology for the duplicate item, will try to remember to search in closed issues as well.
