### ISSUE TITLE
[MU4] Feedback/Feature addition: Could the left hand pizzicato sign for violin (the +) affect the playback?

### ISSUE THREAD

**Issue by Lighwan** [musescore/MuseScore#14116] opened 2022-10-27 22:49 UTC
Currently you have to spam the score with hidden pizz. and arco markings in order to have alternating bowing and pizzicato.

**Comment by sammik** [comment] 2023-12-26 21:19
duplicate of #16984

**Closed** 2023-12-27 05:59 UTC
Labels: duplicate
