### ISSUE TITLE
"Niente" does not work

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#21686] opened 2024-02-26 08:30 UTC
### Issue type

General playback bug

### Bug description

The volume level does not respond to the dynamic indication "niente" (neither in letter nor in symbolic designation (circle for hairpins))
For reference: "niente" means the complete cessation of sound volume.
https://github.com/musescore/MuseScore/assets/134041121/73d3477a-16fb-44f0-87db-3901385db3d6

### Steps to reproduce

-

### MuseScore Version

OS: Windows 10 VersionMuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment] 2024-02-26 13:08
This is a duplicate of https://github.com/musescore/MuseScore/issues/21096

Please check if anyone has already logged an issue before logging

**Closed by zacjansheski** 2024-02-26 13:08 UTC
Labels: playback
