### ISSUE TITLE
Playback cursor erases crescendo line

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#20608] opened 2023-12-20 20:52 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The dotted lines on dynamic changes (cresc., dim.) disappear once the playback cursor passes over them. They reappear once a) the cursor leaves the current system, b) you click and drag the score around, or c) playback is stopped.

### Steps to reproduce

Write some music that has a "cresc." or "dim." line in it. Play back the section with the dynamic change.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/73259774/4cddff56-c680-4c07-a0ac-94cc8752fca4

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment] 2023-12-20 21:41
Duplicate of [#20560]

**Closed** 2023-12-20 23:48 UTC
Labels: UI, duplicate, regression
