### ISSUE TITLE
Grace Notes Affect the Position of Rests in Vertically Adjacent Empty Measures

### ISSUE THREAD

**Issue by CoolSpy3** [musescore/MuseScore#23797] opened 2024-07-28 01:02 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score with multiple staffs
2. On one part add a note that takes up the entire bar
3. Select the note and press "Add grace note: * after" from the "Grace notes" pallete

**Observed Behavior:**
The whole measure rest in the second staff moves to the left as a result of the addition.

**Expected Behavior:**
The rest should remain centered in the bar.

### Supporting files, videos and screenshots

**Observed Behavior:**
![image](https://github.com/user-attachments/assets/cf1e31ea-54a3-4cc3-921d-20bcfa35ada1)

**Expected Behavior:**
![image](https://github.com/user-attachments/assets/14325c74-b6d0-406c-a821-98348661bc1d)

### What is the latest version of MuseScore Studio where this issue is present?

Nightly Build 4.4.0.242090305 Revision: 73cc000

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 & Ubuntu 22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-07-28 05:43
Duplicate of https://github.com/musescore/MuseScore/issues/20587

**Closed by oktophonie** 2024-07-28 05:43 UTC
Labels: engraving, regression MS3
