### ISSUE TITLE
[TIED NOTES] Tied note is repeated if glissando is attached to it (MS Basic/VST only)

### ISSUE THREAD

**Issue by row454** [musescore/MuseScore#19380] opened 2023-09-12 20:00 UTC
### Issue type

General playback bug

### Bug description

I was trying to use a glissando on the second half of a note, so I split the note into tied notes, which gave the desired glissando start time, however the second tied note was played again, when it should have been sustained from the first half.

### Steps to reproduce

1. Create 2 tied notes
2. Add a glissando on the second tied note
3. The second note is repeated

you can open 
[Untitled score.zip](https://github.com/musescore/MuseScore/files/13892914/Untitled.score.zip) and see https://github.com/musescore/MuseScore/issues/19380#issuecomment-1885605578 for demo

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/56337058/1eb7b03c-7b4c-4128-a05a-7114df3599c1)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No

### Operating system

Windows 10

### Additional context

The last working version I found was 3.5.2. Portamento glissando was added in 3.6, so it likely has something to do with that.

**Comment by DmitryArefiev** [comment] 2023-09-13 13:09
@row454 Can you attach a video (with sound) how it works in 3.5.2 please?

**Comment by DmitryArefiev** [comment] 2024-01-10 19:48
I tested this again and now understand the bug. As it was said in the description:

> the **second tied note was played again**, when it should have been sustained from the first half

Edited the summary.

Also found this happens with **MS Basic** and doesn't occur with MuseSounds


https://github.com/musescore/MuseScore/assets/90187801/4db726bc-91ba-4b92-a581-e25c60e43701

**Comment by DmitryArefiev** [comment] 2024-01-10 19:55
Actually, it's not a regression. The same in 3.5.2 and 3.6.2


https://github.com/musescore/MuseScore/assets/90187801/681d404e-9d74-4460-9e91-89b02a65bf2d

**Comment by MarcSabatella** [comment] 2024-01-16 16:25
Actually, this worked correctly for MS Basic at least in 4.1.1.  For Muse Sounds, it kind of worked but not very well - the initial note was sustained through the gliss:

[Screen recording 2024-01-16 9.21.00 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/72b0176e-dfd0-4c1e-9821-f21619109550)


For 4.2, neither work at all (this is currently 4.2.1 nightly):

[Screen recording 2024-01-16 9.24.49 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/3075217d-3227-4293-aff5-c4981f2882a7)

So there is definitely a 4.2 regression here @bkunda

**Comment by MarcSabatella** [comment] 2024-01-16 16:32
Oh wait, my bad, I think - looks like a fix to the regression was just pushed a couple of hours ago (for a different issue).  I'll still leave the previous comment for the demonstration video just in case.

**Comment by handrews** [comment] 2024-01-24 16:46
Tied glissandos are indeed fixed in 4.2.1!

However, tied, slide-outs/falls/doits are still broken, as shown in [this minimal repro score](https://musescore.com/user/59723386/scores/14084578/s/iurxD_).  If this should be a separate bug, please let me know and I would be happy to file one.

**Comment by MarcSabatella** [comment] 2024-01-24 16:54
There is already an issue for that - see https://github.com/musescore/MuseScore/issues/12971.

**Comment by handrews** [comment] 2024-01-24 16:59
@MarcSabatella Thanks!  I see- I had only searched for "slide-outs" and this is the only issue GitHub's rather weak search capabilities found :-/

**Comment by erinic04** [comment] 2024-02-07 16:58
A very similar issue is that the end note of glissandos are rearticulated as well, so if you have a note tied into a glissando you get 3 separate attacks. One at the start of the note (as is to be expected), one at the start of the glissando, and one upon getting to the arrival note.

**Closed** 2024-12-04 07:28 UTC
Labels: P2, playback
