### ISSUE TITLE
[MU4 Issue] Unwanted text always appears on new score

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#14820] opened 2022-11-29 08:56 UTC
Perhaps this is actually by design, but it's not what I would expect. When I don't include text in the Subtitle and Composer fields of the New Score dialog, the placeholder text still shows up on my new score.

1. Start creating a new score
2. Enter text for the title, but don't enter anything for subtitle or composer
3. Create the score
4. See the text "Subtitle" below the title and "Composer/Arranger" to the right of the page.

**Expected behavior**
I would expect no text to be here, since I didn't enter any.

**Platform information**
 - OS: Windows 10

**Comment by Grillzombie** [comment] 2022-11-29 21:33
Yes, i find this annoying too! (And i'm on Linux)

**Comment by Tantacrul** [comment] 2022-12-05 19:20
Yes, we did this by design. On balance, we thought it better to provide the info, since it's so easy to remove. It's quite hard to find if you're a new user, and if you forget to add it in the first place, the process of adding it is annoying. I'm going to close this issue but I take your point.

**Closed by Tantacrul** 2022-12-05 19:20 UTC
Labels: by design

**Comment by mccoydtromb** [comment] 2022-12-05 19:36
I realise this is closed, so might not get further attention, but how about
giving the user the ability to delete the placeholder text while in the new
score dialog?

**Comment by cbjeukendrup** [comment] 2022-12-05 20:08
@mccoydtromb You can do this already (sort of): just type a character in the text field (in the dialog), so that the placeholder text disappears, and then delete the character again: the placeholder does not return after this.

**Comment by mccoydtromb** [comment] 2022-12-05 20:29
Good workaround, thanks. I hadn't tried that.

**Comment by Jojo-Schmitz** [comment] 2023-05-05 17:19
Why no lyrist then? I don't think a subtitle is more common than a lyricist.

**Comment by willstar** [comment] 2024-09-02 20:06
or...  since in "Project properties" you have the option of entering a "subtitle", show it if it exists, or not if it doesn't - that's where I immediately looked anyway.  In the "Page settings dialogue" having the option to include, or show/hide title elements via check boxes would be nice touch.  Perhaps even with the ability to load a template/style sheet that defines the position of said elements?
