### ISSUE TITLE
Musescore crashes if accidentals are changed in a specific way

### ISSUE THREAD

**Issue by EDNX3** [musescore/MuseScore#16916] opened 2023-03-18 22:31 UTC
### Issue type

Crash or freeze

### Bug description

Everything should be explained in the steps and attached youtube video.

### Steps to reproduce

- Set a key signature that isn't Cmaj/Amin (must have accidentals)
- Enter note input mode and add a note affected by the key signature (for example, if the key was F major you would add a B, which would default to Bb)
- Add some more note(s), then Ctrl+Z back to the note affected by the key signature
- Use arrow keys to change the note
- Musescore will crash

### Screenshots/Screen recordings

Here's a [youtube video](https://youtu.be/HnbSW8ULZbU) demonstrating the issue 

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment] 2023-03-19 09:31
Duplicate of https://github.com/musescore/MuseScore/issues/16437

**Closed by oktophonie** 2023-03-19 09:31 UTC
Labels: crash
