### ISSUE TITLE
Selection Covers an Area Vertically Outside a Selected Measure

### ISSUE THREAD

**Issue by moontan** [musescore/MuseScore#21396] opened 2024-02-07 10:52 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When trying to select a measure, the selection is horizontally in the right position, but vertically either above or below the targeted measure. I don't know the circumstances under which this can be reproduced. There could be a link with an [engraving bug I reported earlier](https://github.com/musescore/MuseScore/issues/21394), since it is the same score.

### Steps to reproduce

Uncertain.

### Screenshots/Screen recordings

https://youtu.be/jKVQAdlwV04

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: macOS 13.6, Arch.: x86_64,

**Comment by oktophonie** [comment] 2024-02-07 11:08
Duplicate of https://github.com/musescore/MuseScore/issues/21261

**Closed by oktophonie** 2024-02-07 11:08 UTC
Labels: UX/interaction
