### ISSUE TITLE
Measure repeat symbol does not play back

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11651] opened 2022-05-16 13:24 UTC
**Describe the bug**

Measure repeat signs do not play back.

**To Reproduce**

1. Open the attached MS3 score. 
[repeat_measure_playback.zip](https://github.com/musescore/MuseScore/files/8700365/repeat_measure_playback.zip)

2. Press "Play".

RESULT: The measures with the repeat measure symbol in them do not play back.

**Expected behavior**

Measure repeat signs should play back. This worked fully in MS2 but became partially broken in MS3 where playback stopped at a repeat barline. See [Repeat measure symbols: no audio on second time playback between repeat barlines](https://musescore.org/en/node/292189).

**Platform information**
 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2329645598, revision: github-musescore-musescore-f99ac48

**Comment by RobFog** [comment] 2022-05-16 15:23
Duplicate of #10922?

**Closed** 2022-05-17 08:41 UTC
