### ISSUE TITLE
Cross Staff Arpeggio Playback

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#19443] opened 2023-09-18 19:32 UTC
### Your idea

As someone who puts a lot of classical music into MuseScore, I run into cross staff arpeggios a lot, be it a Bach toccata or a Haydn piano sonata or a Chopin piece. I would love it if the notation of a cross staff arpeggio would also play back like an arpeggio across both staves.

### Problem to be solved

Currently, I have to do a workaround to get the playback I want, like so:

1. Input notes in voice 1 and put in the cross staff arpeggio notation
2. In the bass staff, put the entire chord that both staves encompass in voice 2
3. Add arpeggio symbol to voice 2
4. Make voice 2 and its arpeggio symbol invisible.
5. Make the voice 1 notes silent

Demonstration of current process for cross staff arpeggio playback:

https://github.com/musescore/MuseScore/assets/6530761/0dcec1a6-82c5-45cb-8c8e-90d399873e8d

And note that, at least in MuseScore 3, if I ran into ties being of different lengths for different parts of the cross staff arpeggio, it would sound all the notes for the length of the longest tie with these first 5 steps and so this workaround would get a lot more complicated in that situation. Indeed, I ran into exactly this issue when putting the ending of the second movement of Haydn's Piano Sonata in D Hob. XVI:37 in MuseScore as one of my examples of a movement ending on a half cadence.

**Comment by rgreen5** [comment] 2023-09-18 21:08
Duplicate of #14362.

**Comment by zacjansheski** [comment] 2023-09-19 12:32
Closing per comment above, thank you!

**Closed by zacjansheski** 2023-09-19 12:32 UTC
Labels: feature request, playback
