### ISSUE TITLE
[MU4 Issue] Crash when moving multiple staves

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#11856] opened 2022-06-01 16:33 UTC
**Describe the bug**
When in the instrument panel staves of two or more instruments are selected, a move or remove of these staves will crash MU4
**To Reproduce**
1. Create a score with e.g. a Piano and Organ.
2. Select the first staff of the Piano.
3. Select a staff of the Organ (Ctrl--Shift-Click on e.g. first staff of the Organ).
4. Click on the "Down" button.
5. MU4 crashes.

**Expected behavior**
One of
1. Select staves are moved or
2. Selection of staves of multiple instruments is blocked or
3. If staves of multiple instruments are selected, moving is disabled.

**Screenshots**
N.a.

**Platform information**
 - Linux

**Additional context**
This issue was found when looking into #10034. The idea is, `Add staff` will create a new staff **after** the selected staff. However, when staves of multiple instruments are selected it is not obvious what is supposed to happen. Is the staff created for the instrument for which `Add staff` is clicked only or will a staff be created after **all** selected staves. 
To solve issue #10034 solution 2 is preferred. With option 3 `Add staff` should be blocked also. Option 1 might require another `Add staff` option (e.g. via the popup menu of a staff).

**Comment by boryskuzmenko** [comment] 2022-06-02 15:43
@njvdberg Could you please provide video of you reproducing this issue? I can't reproduce, but not sure that I understood all right

**Comment by njvdberg** [comment] 2022-06-03 08:26
@boryskuzmenko Never made a video and will see what I can do. But I'm not sure a video will add more information.
The main problem is, I'm able to select staves of **different** instruments as show in the picture below:
![image](https://user-images.githubusercontent.com/48352523/171816731-0a955825-189b-40fb-937a-bc78e193fa43.png)
I managed to make this selection by selecting the treble clef staff of the piano and extend the selection by Ctrl-Shift-Click on the other staves (bass clef stave of the first organ, treble clef and bass clef staff of the second organ).

This might be platform related. I noticed this issue will looking into #10034 and Tantacrul wasn't able to make a similar selection on a Mac (see https://github.com/musescore/MuseScore/issues/10034#issuecomment-1144584730)

Can you this on a Linux system (or did you this already)?

**Comment by njvdberg** [comment] 2022-06-03 08:28
BTW I tested it with the latest Linux nightly build and I'm able to reproduce the issue. Unfortunately I can't test on Mac or Windows since I don't have such systems.

**Comment by boryskuzmenko** [comment] 2022-06-03 12:28
@njvdberg I've been trying to reproduce it on Ubuntu, Win11, macos12 and I can't. So closing

**Comment by boryskuzmenko** [comment] 2022-06-03 12:29
🟡 **Can't reproduce**
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by HemantAntony** [comment] 2022-06-03 12:48
@boryskuzmenko @njvdberg  I can reproduce on Windows 11

https://user-images.githubusercontent.com/88136054/171856816-659ed140-310f-4fd9-99ec-a400a67e22c4.mp4

I think the title can be a bit misleading. I initially had something to do with the position of staves on the canvas. But it had to do with the order

**Comment by boryskuzmenko** [comment] 2022-06-03 20:18
@HemantAntony Thanks! Your video described all :)

**Comment by Tantacrul** [comment] 2022-06-04 15:47
@njvdberg - it shouldn't actually be possible to do what you are able to do. On Mac, for example, it is not possible to select different staves in different instruments at the same time.

I believe it not possible on either Win or Mac.

**Comment by HemantAntony** [comment] 2022-06-04 15:49
Did you select using Ctrl + Shift? That was an edge case that wasn't accounted for. Ctrl select was disabled on purpose

**Comment by Tantacrul** [comment] 2022-06-04 15:51
@HemantAntony - yes you're right. I managed to replicate it on Mac too by using Shift + Cmd

**Comment by boryskuzmenko** [comment] 2022-06-04 15:53
@Tantacrul it's possible if you use Ctrl+Shft. 
Yesterday Roman is already fixed this. Now it's not possible. 
I've already tested but couldn't run his build on Linux so didn't close yet

**Comment by njvdberg** [comment] 2022-06-05 09:56
> Yesterday Roman already fixed this (disabled this combination). Now it's not possible.
> I've already tested but couldn't run his build on Linux so didn't close yet

I tested PR #11882 on Linux and it works as expected. So for me this issue can be closed once the PR is merged.

**Closed** 2022-06-06 09:30 UTC
Labels: P0

**Comment by boryskuzmenko** [comment] 2022-06-06 21:28
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11882
Tested on macOS 12, Win 11
