### ISSUE TITLE
Zoom level in parts set to 0% after reopening file 

### ISSUE THREAD

**Issue by GuitarDude2** [musescore/MuseScore#18953] opened 2023-08-07 13:27 UTC
### Issue type

UI bug

### Bug description

After opening MS4 with a file containing parts these parts open with a zoom level of 0%. 
This happens with files created in MS3 as well as MS4.

### Steps to reproduce

1. Open file containing parts.
2. Select any of the parts.
3. Zoom level is set to 0%
4. After changing the zoom level to desired level everything works fine (just a nuisance)

### Screenshots/Screen recordings

<img width="1728" alt="grafik" src="https://github.com/musescore/MuseScore/assets/141644134/14ee4f95-6616-431e-9f61-e29389459248">

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13.5

**Comment by zacjansheski** [comment] 2023-08-07 14:13
Similar to a previously fixed issue: https://github.com/musescore/MuseScore/issues/17906
I'm not able to reproduce this currently, are there scores from a specific version of MS that cause this to happen?

**Comment by GuitarDude2** [comment] 2023-08-08 05:00
It happens with files that were created in MS3 and MS4.
Github doesn't allow me to upload MS files. But you can find one sample file here: [https://musescore.com/user/20558/scores/11071150](url)
Thanks for your help.

**Comment by zacjansheski** [comment] 2023-08-08 16:53
You can upload MuseScore files to github by compressing or renaming with .zip extension
I am still unable to reproduce with the score on 4.1.1 or Master (MacOS  11.7.9) https://musescore.com/user/20558/scores/11071150

Are you using additional monitors?  Any special scaling settings? Anything that can help us reproduce the issue would be greatly appreciated.

**Comment by zacjansheski** [comment] 2023-08-08 20:14
Possibly related https://github.com/musescore/MuseScore/issues/15591

**Comment by cbjeukendrup** [comment] 2023-08-08 22:37
> Possibly related #15591

In that issue, the Navigator turned out to be causing trouble like this. In the screenshot in this issue, I also see the Navigator opened; maybe it's the cause here too?

**Comment by GuitarDude2** [comment] 2023-08-10 04:48
Hi, I've checked it out. The Navigator really seems to cause this problem. After closing the Navigator the problem disappeared.

**Comment by zacjansheski** [comment] 2023-08-10 12:59
Let's close this and refer to https://github.com/musescore/MuseScore/issues/15591  Thank you!

**Closed by zacjansheski** 2023-08-10 12:59 UTC
Labels: needs info, UI, regression_ms3

**Comment by Jojo-Schmitz** [comment] 2023-12-19 12:16
This one seems back in 4.2, please reopen.

I have Edit > Preferences > Canvas > Default zoom set to Page width.
Works for the main score, but for all parts it is set to 0% (in the lower right corner), but clicong on it does show Page view, this isn't honored though but shows the part(s)very large instead

And before ypou ask: this happens also after a factory reset

**Comment by Jojo-Schmitz** [comment] 2023-12-19 12:18
Oh well, let's continue in #15591
