### ISSUE TITLE
Flexibility for cross-staff chords

### ISSUE THREAD

**Issue by VighneshJadha** [musescore/MuseScore#23196] opened 2024-06-11 15:24 UTC
### Your idea

Musescore studio is lacking cross-staff chords, which have been a part of standard piano music notation for a lot of time. Take for example this case when we have selected only the low Bb.
![image](https://github.com/musescore/MuseScore/assets/110092019/ee01456b-d60a-4e48-9cbb-15e4fce9fea5)
And here is what it does currently, when I keep only that low Bb selected and cross-staff it.
![image](https://github.com/musescore/MuseScore/assets/110092019/4af5a1e6-c608-4bc5-babb-9825fc3c14a5)
This is how it should look like (I used a workaround in this image)
![image](https://github.com/musescore/MuseScore/assets/110092019/c2118f76-0156-4aad-85eb-479cfb6910ff)
Can you do this in v4.4, or at most, v5, please?

### Problem to be solved

Classical music will become much easier to transcribe in Musescore. It appears prominently in classical manuscripts - an example from a Chopin nocturne is attached. 
![image](https://github.com/musescore/MuseScore/assets/110092019/c31ccf7e-0568-49fb-9e54-28f29eb3efe1)

### Additional context

Do this quick! Do it immediately, in Musescore studio 4.4 or before Musescore 5.

**Comment by oktophonie** [comment] 2024-06-11 15:34
Duplicate of https://github.com/musescore/MuseScore/issues/15544

**Closed by oktophonie** 2024-06-11 15:34 UTC
Labels: feature request

**Comment by bkunda** [comment] 2024-06-11 15:47
> Do this quick! Do it immediately, in Musescore studio 4.4 or before Musescore 5.

@VighneshJadha please refrain from making comments like this in this repository. Our development team has a large volume of issues and feature requests on its roadmap, and so there's a lot for us to take into account when planning an improvement's release date. 

Comments like this are both unhelpful and rude, and have no place in this repository.

**Comment by VighneshJadha** [comment] 2024-06-11 15:49
> > Do this quick! Do it immediately, in Musescore studio 4.4 or before Musescore 5.
> 
> @VighneshJadha please refrain from making comments like this in this repository. Our development team has a large volume of issues and feature requests on its roadmap, and so there's a lot for us to take into account when planning an improvement's release date.
> 
> Comments like this are both unhelpful and rude, and have no place in this repository.

I edited it.
