### ISSUE TITLE
Since MuseScore version (64-bit): 4.1.0-230811026, revision: github-musescore-musescore-5f3913c crash on this score

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16976] opened 2023-03-22 18:30 UTC
### Issue type

Crash or freeze

### Bug description

Since MuseScore version (64-bit): 4.1.0-230811026, revision: github-musescore-musescore-5f3913c crash on loading this score

### Steps to reproduce

Open File provided

### Screenshots/Screen recordings

[Pavane Pour Une Infante Défunte.zip](https://github.com/musescore/MuseScore/files/11043570/Pavane.Pour.Une.Infante.Defunte.zip)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-230811026, revision: github-musescore-musescore-5f3913c
Work on : previous Version :  MuseScore version (64-bit): 4.0.2-230810507, revision: github-musescore-musescore-a45b9a5
From nightly load

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64,

**Comment by Gai-Luron** [comment] 2023-03-23 10:41
To reproduce from scratch:

1. Create a new score with MS4 4.0.2
2. Add Measures with two voices, second voice contain rests at beginning of Measure
3. Dupplicate Measure more time with "R" key
4. Remove all rest at beginning of voice 2 in all measures
5. Save Score
6. Load score with 4.1.0
7. Result in score corrupted
8. if you continue anyway, sometime crash, sometime no
9. Anyway you have a message on loading this score and in saving

[test rest issue voice 2.zip](https://github.com/musescore/MuseScore/files/11049766/test.rest.issue.voice.2.zip)

https://user-images.githubusercontent.com/1835871/227178543-adfdc084-5802-47b3-a561-e5c4402d758c.mp4

**Comment by oktophonie** [comment] 2023-03-23 10:43
Duplicate of https://github.com/musescore/MuseScore/issues/16841

**Closed** 2023-03-23 11:22 UTC
Labels: regression, crash

**Comment by Gai-Luron** [comment] 2023-03-23 11:25
Hello,
I correct the first MuseScore File i give you. No more error due to rest at beginning or end of Measure, but MS 4.1.0 continue to crash and now no error displayed before load. I think there is another issue on this score.

Score corrected who crash anyway: 
[Pavane Pour Une Infante Défunte.zip](https://github.com/musescore/MuseScore/files/11050151/Pavane.Pour.Une.Infante.Defunte.zip)

**Comment by Gai-Luron** [comment] 2023-03-23 12:00
Localized issue in one Measure and i don't know Why
[Pavane Pour Une Infante Défunte - TEST - copie.zip](https://github.com/musescore/MuseScore/files/11050473/Pavane.Pour.Une.Infante.Defunte.-.TEST.-.copie.zip)
