### ISSUE TITLE
Can't input natural accidental with Portuguese keyboard

### ISSUE THREAD

**Issue by goncalogato** [musescore/MuseScore#24968] opened 2024-09-29 14:37 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Can't use the keyboard to input a natural sign for a pitch. I think it's because of the Portuguese keyboard layout. I have to use the combination Shift-0 to get the '=' sign which translates to the natural accidental. Thanks!

### Supporting files, videos and screenshots

No files needed.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

MacOS Sequoia

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by goncalogato** [comment] 2024-09-29 14:39
...And '0' is used for rests. So I defined a keyboard shortcut using the '\' key. I think it has no conflicts.

**Comment by Jojo-Schmitz** [comment] 2024-09-29 14:56
Same issue with a German keyboard, jere too `=` is `Shift+0`

**Comment by Jojo-Schmitz** [comment] 2024-09-29 16:13
Different issue, most probably same cause

**Comment by bkunda** [comment] 2024-10-01 13:39
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/24275.

Happy to re-open if I'm wrong though :-)

**Closed by bkunda** 2024-10-01 13:39 UTC
Labels: UX/interaction
