### ISSUE TITLE
Entering Text

### ISSUE THREAD

**Issue by bobniqu** [musescore/MuseScore#23301] opened 2024-06-19 09:27 UTC
### Issue type

Crash or freeze

### Bug description

When select a note and hit Ctl.-T to enter text, enter the text then hit the space bar to go to a next line, MU freezes up on me.

### Steps to reproduce

Select note, hit Ctl.-T enter text, hit space bar to start new line of text. MU freezes.

### MuseScore Version

4.3.2

### Regression

No.

### Operating system

Windows 11.

**Comment by MarcSabatella** [comment] 2024-06-19 13:35
I can't reproduce any such problem, but I'm also confused - Space doesn't go to a new line, it just adds a space.  Did you mean Enter?  if so, then I guess this is probably related to https://github.com/musescore/MuseScore/issues/17006.  Seems to be an issue specifically with having the Windows "Text cursor indicator" accessibility setting turned on.  See if you have that on, and if the hang goes away when you disable it.

**Comment by bkunda** [comment] 2024-06-21 13:24
Closing this as the reproduction steps don't seem to point to a discernible issue.

**Closed by bkunda** 2024-06-21 13:24 UTC
Labels: crash, waiting reply from user
