### ISSUE TITLE
MUSE SOUNDS: Some notes don't play during repeats

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#15030] opened 2022-12-07 22:44 UTC
**Describe the bug**
Strange one. A user just sent me this. It doesn't happen with MS Basic or VST. Just Muse Sounds.

- If I create play the same passage using a horn or clarinet, the 4th note **does** play correctly
- Doesn't work with harp, harpsichord, piano, celesta, etc.

[Here's the file](https://www.dropbox.com/s/m474cctjsc5hwze/Lucia%20stiger%20fram.mscz?dl=0)

<img width="541" alt="image" src="https://user-images.githubusercontent.com/21022311/206312934-7b6fae55-7af3-4d54-bc11-2224d701f8c5.png">

**Comment by krtschil** [comment] 2022-12-08 12:59
That is really strange. 
When I change the pitch of the last note then the last note is played correctly depending on the pitch chosen!
So, some last notes play correctly! 

Played correct:
![grafik](https://user-images.githubusercontent.com/7796440/206451901-ad81ead8-6035-42da-8a6e-67734935a601.png)

Played wrong:
![grafik](https://user-images.githubusercontent.com/7796440/206451792-3eb9c3ee-580f-49cb-8a0b-4d5e2a01193e.png)
and the last note is played as the first note of the next beam!

Removing the repeat shows the same behaviour.

**Comment by cbjeukendrup** [comment] 2023-04-19 13:10
@Tantacrul This looks like a duplicate of #15306. I'll let you decide which one to close.

**Comment by Tantacrul** [comment] 2023-04-19 17:06
@cbjeukendrup - can you do it? I'm away from my machine right now and I trust you!

**Comment by cbjeukendrup** [comment] 2023-04-19 18:06
I'll close this one in that case, because the other is slightly more clear and specific.

**Closed by cbjeukendrup** 2023-04-19 18:06 UTC
Labels: P1
