### ISSUE TITLE
[MU4 Issue] When playing a staff instrument from a MIDI keyboard, notes are prematurely cut off

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14573] opened 2022-11-17 18:29 UTC
**Describe the bug**

 If you click on a staff in normal mode you can play (preview) the staff instrument from a MIDI keyboard. Unfortunately if you hold the note beyond a certain duration the note is prematurely cut off. Tested with the jazz combo template and an Akai LPK25 USB keyboard.

**Expected behavior**

 The duration of the sounding note should always match the key presses.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223210406, revision: github-musescore-musescore-089ce9f

**Comment by cbjeukendrup** [comment] 2022-11-17 18:46
Duplicate of #13381?

**Comment by rgreen5** [comment] 2022-11-18 09:45
Yes, it is.

**Closed** 2022-11-18 09:45 UTC
