### ISSUE TITLE
[MU4 Issue] Windows 10, MuseScore main window opens up behind other applications and can't be switched to in Task Manager

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8963] opened 2021-08-29 23:52 UTC
**Describe the bug**
When launching MuseScore4 (say, from command line), it can appear behind other application windows, doesn't appear in the list of windows you can Alt+Tab to, and "Switch to" is disabled in the Task Manager for that process. Also pop-up menus appear in the task-bar list.

**To Reproduce**
1. Using Windows 10, launch MuseScore4 from a command line window
2. Main Window appears behind command line window
3. Bring up Task Manager, find the MuseScore4 process and right click/access context menu
4. Note that "switch to" is disabled
5. In MuseScore, click on "File" to bring up the menu, note that in Task Bar MuseScore icon shows that multiple top-level windows are open, from there you can actually choose just the File Menu and bring just that to the front without the main application window, but then it appears to show the New Score dialog? Disappears when you move the mouse though.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Tantacrul** [comment] 2022-05-01 13:44
@wizofaus - is this issue still occurring for you?

(Note - I'm not currently in the place where my Win10 machine is, so can't check)

**Comment by jeetee** [comment] 2022-05-02 21:14
Me and two others (@logman22349 and @dragonwithafez on Discord) have attempted reproduction with today's build in a variety of ways on Win10 machines and couldn't reproduce it.

Recommend closing the issue for now.

**Comment by Tantacrul** [comment] 2022-05-02 21:31
Thanks very much guys!

**Closed** 2022-05-02 21:31 UTC

**Comment by wizofaus** [comment] 2022-05-02 22:09
Looks ok now, though "Switch to" isn't even in the context menu any more, and strangely I can't find any other processes for which it is there and is enabled, so maybe that particular concern was a red herring.

**Comment by dragonwithafez** [comment] 2022-05-02 22:15
It's present and enabled for MU3 on my machine. Haven't seen any other processes with it though.
