### ISSUE TITLE
Repeat key improvements

### ISSUE THREAD

**Issue by tygoee** [musescore/MuseScore#25057] opened 2024-10-05 22:49 UTC
### Your idea

I'm occasionally entering repeated chords using the R key to repeat the last note, which is pretty useful. But there are some cases where it currently does nothing while it would be nicer if it could work

### Problem to be solved

Could it change when:

- After entering rests. When having entered a big chord and then placing a rest and pressing R, it doesn't repeat the note before the rest. Could it be possible to use the last note, excluding rests so I don't have to go back and copy-paste it manually?
- When just entering note input mode. If I exited note input mode to add dynamics/fix a mistake/etc. and then press R to repeat the last note, it doesn't do anything. Could that behavior be changed to fetch the previous note when there's no last entered chord?

### Additional context

These scenarios are easily done another way, but it'd save some keystrokes, especially when entering piano parts with repeated chords

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment] 2024-10-06 17:15
> * After entering rests. When having entered a big chord and then placing a rest and pressing R, it doesn't repeat the note before the rest. Could it be possible to use the last note, excluding rests so I don't have to go back and copy-paste it manually?

The disadvantage would be that it introduces an inconsistency: normally, the R key would just repeat the selected thing, regardless of what that is, _but_ if the selected thing is a rest, then it suddenly repeats some earlier note instead of the selected thing. 

But I agree that a "re-enter last used pitch" command would be useful, and I see an opportunity for how this could be implemented without introducing inconsistencies. Recently, there was this request: https://github.com/musescore/MuseScore/issues/25027. That would imply that the note input cursor needs to have a concept of 'current pitch', and pressing 'Enter' enters a note with that pitch. And this current pitch would of course not change when inputting a rest in between. So, the 'Enter' key from that request would basically be equivalent to the "re-enter last used pitch" that you request.

**Comment by tygoee** [comment] 2024-10-06 17:55
Perhaps it will be possible to rename "Repeat selected chord" to "Repeat selected or previous chord".

Adding this also isn't really inconsistent. Currently it checks if there is a selection, and then repeats that selection. If there's no selection or it's a rest, the Repeat command won't do anything (when selecting a notehead rather than a chord)

The command currently already distinguishes a notehead selection and a chord/measure/etc selection (with a blue box surrounding). I think the best way to go about this would be to keep the current behaviour when selecting a chord, and implement this when selecting noteheads and rests.

**Comment by XiaoMigros** [comment] 2024-10-07 07:36
Besides, repeating or adding a rest is always a one-key operation (`0`), whereas with chords it's not.

**Comment by worldwideweary** [comment] 2024-10-10 22:25
Looks to be a duplicate of the March 2023 request @ https://github.com/musescore/MuseScore/issues/16644, which might give an idea to the OP about priority.

**Comment by zacjansheski** [comment] 2024-11-12 16:35
Closing as duplicate of https://github.com/musescore/MuseScore/issues/16644

**Closed by zacjansheski** 2024-11-12 16:35 UTC
Labels: P1, feature request
