### ISSUE TITLE
Violin Trill Should Only Apply to One Note

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25760] opened 2024-12-07 03:42 UTC
### Issue type

General playback bug

### Description with steps to reproduce

When a figure like the following is notated for solo violin:
![image](https://github.com/user-attachments/assets/75303700-1573-44c8-9c29-fa1eb6171715)
The performer will always trill the note on top. If the trill is below:
![image](https://github.com/user-attachments/assets/c57cf5d9-b319-400e-af73-3fd48a77b2aa)
The performer will trill the lower note in the chord.
 Musescore trill both notes. Musescore _should_ be able to trill only one note, even when it is in the same voice as the non-trilled note.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/5b629921-46f3-4656-b1f1-6a2673e5fd6a

[Violin Trill.zip](https://github.com/user-attachments/files/18046103/Violin.Trill.zip)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445   Revision: eb6b367

### Regression

No.

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DaddyLudwig** [comment] 2024-12-07 03:51
This doesn't just apply to violin, same is true with piano music as well, that if there's just the 1 trill above an interval or chord, only the top note is supposed to be trilled. A trill of both notes i.e. a double trill, which I have seen in Beethoven and Liszt, would be indicated with 2 trill markings.

**Comment by Dima-S-Jr** [comment] 2024-12-07 08:18
Also see the [comment](https://github.com/musescore/MuseScore/issues/15816#issuecomment-2038244476)

**Comment by bkunda** [comment] 2024-12-10 15:20
Seems to be a duplicate of https://github.com/musescore/MuseScore/issues/15816

**Closed by bkunda** 2024-12-10 15:20 UTC
Labels: duplicate, playback

**Comment by Dima-S-Jr** [comment] 2024-12-11 11:03
@bkunda, this is more like a future request, not a duplicate. #15816 talks specifically about the trill line and how it affects adjacent voices. 
In this issue, the user suggests (in fact, this is rather not a bug, it is intended by design) to redo the playback of trills so that only the uppermost or lowest note sounds in a chord composed by one voice, if there is one trill (it is not specified whether the trill is a line or just "_tr_", therefore we mean both), which is correct to denote and understand. 
There is also a need to enter double/triple, etc. trills to trill all the notes in the chord (see the comment from @DaddyLudwig).
