### ISSUE TITLE
[MU4 Issue] Missing or incorrect text in dialog from 'Check for language updates' button

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#13096] opened 2022-08-31 12:28 UTC
![image](https://user-images.githubusercontent.com/71656189/187678016-82b4e5a4-7653-4ff4-b5e9-0d5a88e18191.png)

**Comment by cbjeukendrup** [comment] 2022-08-31 12:30
Duplicate of #12823 :)
(And see #12917 for the fix)

**Closed by cbjeukendrup** 2022-08-31 12:30 UTC
