### ISSUE TITLE
Playback on note entry or selection is distorted with sample rate >48kHz

### ISSUE THREAD

**Issue by OctopusProteins** [musescore/MuseScore#17313] opened 2023-04-21 20:31 UTC
### Issue type

Muse Sounds bug

### Bug description

When audio format is set with a sample rate higher than 48khz, playback generated from clicking note heads as well as note entry is stuttering/distorted/crackling. Normal playback is unaffected, and this issue only occurs with Muse Sounds.

### Steps to reproduce

1. Set the system audio format to use a sample rate greater than 48kHz
2. Open Musescore
3. Select/place a note on an instrument using Muse Sounds

### MuseScore Version

Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 11

### Additional context

Additional Context
https://github.com/musescore/MuseScore/issues/12918 fixes a similar issue with normal playback. The same settings described therein also cause issues as described above (see screenshot in https://github.com/musescore/MuseScore/issues/12918)

**Comment by RomanPudashkin** [comment] 2024-07-09 07:16
Closing, as it looks like a duplicate of https://github.com/musescore/MuseScore/issues/18701

**Closed by RomanPudashkin** 2024-07-09 07:16 UTC
Labels: duplicate, muse sounds
