### ISSUE TITLE
palette sidebar

### ISSUE THREAD

**Issue by gerrybass** [musescore/MuseScore#14162] opened 2022-10-29 11:26 UTC
the palette/instruments sidebar cant be minimized by using the cursor

**Comment by MarcSabatella** [comment] 2022-10-29 14:30
If by minimized you mean, change size, this is true, currently by design (someday it is hoped to improve this).  But you can close them via the "..." menus or the View menu (as well as keyboard shortcuts).

**Comment by Tantacrul** [comment] 2022-11-01 12:01
Yes, this will be addressed in later releases.

**Closed by Tantacrul** 2022-11-01 12:01 UTC
