### ISSUE TITLE
[MU4 Issue] Text format in Textbox or Vertical/Horizontal frames

### ISSUE THREAD

**Issue by eg0n1984** [musescore/MuseScore#9028] opened 2021-09-03 16:56 UTC
**Describe the bug**
It's hard to understand how we can format a single or multiple words in a text instead all text. Using inspector menu the format is applied to all text even with few words selected in textbox or frame, the have the expected behavior the user needs to format  to use keyboard shortcuts (like Ctrl+U, Ctrl+I, etc.) 

**To Reproduce**
1. Go to 'Add', 'Frame'
2. Click on 'Vertical Frame'
3. write some text
4. select single words in the text
5. try to apply format (ex. Bold) with GUI interface in Inspector menu

**Expected behavior**
Apply format just to selected text

**Screenshots**
![image](https://user-images.githubusercontent.com/28876087/132041304-5863e14a-cf17-4513-abc2-60df37128d36.png)
1-after apply bold format
![image](https://user-images.githubusercontent.com/28876087/132041399-541c71ed-8215-401f-bcaa-ec4daccf9921.png)
![image](https://user-images.githubusercontent.com/28876087/132041374-6a6a82b3-155b-49bf-95fa-db86e84844a0.png)
2-with shortcut - ctrl+B
![image](https://user-images.githubusercontent.com/28876087/132041543-ba9cdb5a-fb35-4dc3-8d3b-315ecfdde257.png)

**Desktop (please complete the following information):**
 OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021803, revision: github-musescore-musescore-3224f34

**Comment by wizofaus** [comment] 2021-09-03 20:38
This is an 3.6 issue, and it is by design - the inspector only modifies the *whole* object.  You need to use the text editing toolbar at the bottom of the screen to change individually selected characters/words.

In 4.0 it will behave as you expect, except currently it has an even bigger problem - you can't edit text in vertical frames at all! (I think I might have reported this already, or noted it as part of another issue).
Given the way that formatting is applied to individual words etc. has changed significantly between 3.6 and 4.0 I doubt this will get fixed in 3.6.

**Comment by wizofaus** [comment] 2021-09-03 20:41
I can't seem to find any issue where I've commented on editing text in vertical frames, so feel free to modify this issue to be the rather more serious problem that you can't edit text in vertical frames at all in MU4.
Once that's fixed (I'm looking into it) it should work as you expect, whereby bold/italic/underline in the properties panel/inspector will behave the same as Ctrl+B/I/U if individual words/characters are selected.

**Comment by eg0n1984** [comment] 2021-09-03 21:12
Thanks @wizofaus . You are right and it's not an issue.
I'm waiting for first version of MS4 to see the major changes on UX/UI - hope this kind of duplicated tools be improved.

Have a nice weekend and once more grateful by your help.

**Closed** 2021-09-03 21:12 UTC
