### ISSUE TITLE
Horizontal frames vis à vis instrument names

### ISSUE THREAD

**Issue by wfazekas1** [musescore/MuseScore#22626] opened 2024-04-29 16:07 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Often, I would indent a system by creating an horizontal frame--this would display in Ms3.x as:
(Margin)--Frame--Instrument name--bracket/system start

In Ms4, this displays as:
(Margin)--Instrument name, (overlaid with) Frame--Bracket/system start

This creates a huge gap between the instrument name and the bracket. Deleting the horizontal frame and re-creating it does not help. I found I could move the instrument names individually using CTRL->, although I would have to offset the frames to move them out of the way, then return them to position. However, I find that when I close the file and reopen it, the instrument names are back against the margin--even if I have hit CTRL-S before closing.

![image](https://github.com/musescore/MuseScore/assets/20604032/dd0026b7-7a71-4172-9e06-290f0c3f54bf)

before m.17 and m.21 in the attached file.
[Asperges_Me.4.pdf](https://github.com/musescore/MuseScore/files/15151797/Asperges_Me.4.pdf)

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2024-04-29 16:19
Duplicate of https://github.com/musescore/MuseScore/issues/18504

**Closed by oktophonie** 2024-04-29 16:19 UTC
Labels: engraving, regression_ms3

**Comment by Jojo-Schmitz** [comment] 2024-04-29 17:46
And #16530  and #15943
