### ISSUE TITLE
Dynamics markings repeating every bar when MS Basic shaker is present

### ISSUE THREAD

**Issue by JaimeShirazi** [musescore/MuseScore#23297] opened 2024-06-19 05:04 UTC
### Issue type

Muse Sounds bug

### Bug description

I've been having trouble getting this to happen consistently, but it seems directly tied to the general midi shaker in my score. I was using it because I wasn't a fan of the muse sounds shaker, but it's caused some very strange behaviour where dynamics marked in previous bars are sometimes repeating themselves. Every time I would delete the shaker for a bar, the bug would stop happening in that bar.

### Steps to reproduce

I struggle to get this to reliably happen, and this might be an issue that can just occur while working on a file, so I've also attached my score so it can be tested that way.
1. Ensure Muse Percussion and Muse Brass is installed
2. Download the attached zip of the file (or download it from [here](https://drive.google.com/file/d/1Y9kGpu_paEOUFY6vnT3MRaA4axvQtKZH/view?usp=sharing) if you don't want to open a zip on your computer)
[Musescore 4 Playback Issue.zip](https://github.com/user-attachments/files/15895619/Musescore.4.Playback.Issue.zip)
3. Playback the score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/73824309/50d64735-783f-47df-aa9f-648d4a986362

### MuseScore Version

4.3.2.241630831

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I tried to strip back the score I was working on into as simple a demonstration of this issue as I could without getting the bug to stop happening. This also persisted when exporting as an audio file. I've converted the Congas into Taikos since, for whatever reason, there still isn't a Taiko instrument in MuseScore despite there being sounds for them.

**Comment by MarcSabatella** [comment] 2024-06-19 13:29
I am guessing that this is a duplicate of https://github.com/musescore/MuseScore/issues/23242, and the issue is actually the measure repeats, not anything about shaker specifically.

**Comment by zacjansheski** [comment] 2024-06-20 13:44
Yes this is a duplicate of https://github.com/musescore/MuseScore/issues/23242,
Resolved in master by https://github.com/musescore/MuseScore/pull/23274

**Closed by zacjansheski** 2024-06-20 13:44 UTC
Labels: muse sounds
