### ISSUE TITLE
[MuseScore 4] Crash on clicking "Insert special characters" button

### ISSUE THREAD

**Issue by KaelinMistry** [musescore/MuseScore#17458] opened 2023-05-03 23:25 UTC
### Issue type

Crash or freeze

### Bug description

Hi. I was working on a piece and I needed to insert a flat into a staff text to make a pedal diagram for a harp part. However, upon pressing the "Insert special characters" button, MuseScore promptly crashed. I went and tested this on various different scores with staff, system, and expression text, each yielding the same result. I use the default MuseScore fonts (Leland + Edwin).

As a note, I have been using the smaller accidentals (see below), as I personally find them more aesthetically pleasing. 

![Screenshot 2023-05-03 191947](https://user-images.githubusercontent.com/132522100/236072068-2d9cc339-3bbc-494f-8230-9f7b97bba4d1.png)
(I use the accidental on the left.)

### Steps to reproduce

1. Create a new score.
2. Insert a staff/system/expression text.
3. Double click the text to edit it.
4. In the properties panel, press the "Insert special characters" button.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

[MuseScore_230503_184717.log](https://github.com/musescore/MuseScore/files/11391916/MuseScore_230503_184717.log)

**Comment by pspoor1629** [comment] 2023-05-05 14:06
I had the same experience when trying to add a special character to lyrics.

**Comment by zacjansheski** [comment] 2023-05-30 17:07
In the current nightly, I cannot insert special characters in expression text in Windows, but I can insert special characters in staff and system text.

On Mac I am able to do this with staff, system, and expression text

**Comment by zacjansheski** [comment] 2023-06-02 18:01
Closing as I am unable to reproduce in the nightly.

Opened an issue related to expression text. https://github.com/musescore/MuseScore/issues/17834

**Closed by zacjansheski** 2023-06-02 18:01 UTC
Labels: needs info, regression, crash
