### ISSUE TITLE
[MU4 Issue] Inspector position not saved when hide/unhide it

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14165] opened 2022-10-29 13:57 UTC
Dock inspector at right of screen. 
Hide It with F8, then Unhide and it appear to the origin position at left.

In Work, i hide and unhide this Panel frequently. But it's better if it appear at last position.

**Comment by Tantacrul** [comment] 2022-11-01 12:31
Yeah, that's an oversight. Thanks for reporting it!

**Comment by jeetee** [comment] 2022-12-17 14:52
It's not just the Properties panel, this also affects the Instruments and Palettes panels.

Steps:
1. Start from default layout (all three panels tab-docked to the left).
2. Drag the Properties pane to the right.
3. Drag the Instruments pane to the bottom left, so it places itself below the palettes

4. Whichever toggle shortcut you now press will not result in the current layout, but tab panes together again. If you happen to close all panes on one side, they'll show up on the other side instead when restoring them.

**Comment by jeetee** [comment] 2022-12-17 14:56
Just noted this is a duplicate of https://github.com/musescore/MuseScore/issues/11242

**Comment by cbjeukendrup** [comment] 2022-12-17 15:10
Indeed, thanks. Closing as a duplicate.

**Closed by cbjeukendrup** 2022-12-17 15:10 UTC
Labels: P2, community
