### ISSUE TITLE
[MU4 Issue] Add Measure and remove measure in conductor result in corrupted Parts 

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#15447] opened 2022-12-20 16:46 UTC
1. Create a new score with multipart
![image](https://user-images.githubusercontent.com/1835871/208720050-fa42347f-6269-4704-816f-a6f5b83651a8.png)
2. Insert a new Measure
![image](https://user-images.githubusercontent.com/1835871/208720129-c39a048e-d264-4b96-8e03-b9d3ea0e2a9a.png)
3. Result in corrupted part
![image](https://user-images.githubusercontent.com/1835871/208720245-2b83f028-fea7-48e2-963c-6b613ce76ab9.png)
4. Remove Measure in conductor, result in corrupted part too
![image](https://user-images.githubusercontent.com/1835871/208720497-58792f02-4615-40d3-9a54-68193669b7d1.png)

**Comment by RobFog** [comment] 2022-12-20 16:56
This looks similar to #15185

**Comment by Gai-Luron** [comment] 2022-12-20 17:31
Yes, it's similar except that the insertion is done in the conductor. 
But it must be the same bug
Thank's

**Comment by oktophonie** [comment] 2022-12-20 19:22
Duplicate of https://github.com/musescore/MuseScore/issues/15185

**Closed by oktophonie** 2022-12-20 19:22 UTC
