### ISSUE TITLE
MIDI Keyboard: When inputting chords, some notes are not heard or not displayed

### ISSUE THREAD

**Issue by JosephZayoun** [musescore/MuseScore#12261] opened 2022-07-04 13:24 UTC
(Edited by Martin)
**To Reproduce**
See video below:
1. Plug in a MIDI Keyboard
2. When entering chords, some notes are not being picked up. Playback also often misses certain notes.

**Comment by Tantacrul** [comment] 2022-07-08 12:33
Need more information and a way to reproduce it. A video would be even more helpful.

Closing until the issue is updated so we can investigate.

**Comment by JosephZayoun** [comment] 2022-07-08 13:15
https://user-images.githubusercontent.com/103273970/177999138-3f782adb-6bc7-40a9-8829-19ea4a658018.mov

**Comment by Tantacrul** [comment] 2022-07-08 14:13
@jessjwilliamson and @bkunda - could you check to confirm this is happening on Windows / Mac?

**Comment by jessjwilliamson** [comment] 2022-07-08 14:24
I've found no issues here on Mac and Windows. 
But while trying to re-produce this I found a playback issue which I'll create issue elsewhere.

**Comment by DmitryArefiev** [comment] 2022-07-08 16:24
@Tantacrul I noticed that issue on Windows with my USB MIDI Keyboard today, and also I have **ugly thing with stuck notes** (Note Off message doesn't work) which is probably related

https://user-images.githubusercontent.com/90187801/178032113-d27d1f58-b2b3-488c-8e40-89d4b375883e.mp4

**Comment by Tantacrul** [comment] 2022-07-27 18:43
> @Tantacrul I noticed that issue on Windows with my USB MIDI Keyboard today, and also I have **ugly thing with stuck notes** (Note Off message doesn't work) which is probably related
> 
>  bandicam.2022-07-08.19-15-17-044.mp4

@DmitryArefiev - so the issue is that you don't hear the notes in realtime and you press the keys? Do the correct notes appear on the score?

**Comment by bkunda** [comment] 2022-07-28 07:31
I've just worked out how to reproduce this on MacOS: playing chords sequentially (but holding down each note as it's played) allows perfect chord input, but playing multiple notes simultaneously (i.e. a block chord) causes some notes to ring on forever. The correct notes do seem to appear on the score, however.

**Comment by DmitryArefiev** [comment] 2022-07-30 10:01
> > @Tantacrul I noticed that issue on Windows with my USB MIDI Keyboard today, and also I have **ugly thing with stuck notes** (Note Off message doesn't work) which is probably related
> > bandicam.2022-07-08.19-15-17-044.mp4
> 
> @DmitryArefiev - so the issue is that you don't hear the notes in realtime and you press the keys? Do the correct notes appear on the score?

@Tantacrul Correct. I **can reproduce the issue with sound only**. All notes from chord are added fine to score (Windows 10, USB MIDI Keyboard)

**Comment by DmitryArefiev** [comment] 2022-08-04 10:51
@vpereverzev Tested in **latest master** on Win10/Mac12 - the issue **still occurs** on my side

https://user-images.githubusercontent.com/90187801/182829627-493c3cbf-662c-483a-b250-a4fcbd91ad52.mp4

to compare with MU3



https://user-images.githubusercontent.com/90187801/182829683-6d420f2d-ec0c-43fb-9c90-3eaeb6173616.mp4

**Closed** 2022-08-05 13:34 UTC
Labels: P1

**Comment by DmitryArefiev** [comment] 2022-08-05 13:35
Fixed in #12689

(found some issue with delay - will recheck it together with buffer size change)

**Comment by DmitryArefiev** [comment] 2022-08-05 16:34
When tested more deeply, found on Mac that some notes are really don't input from MIDI keyboard (when input big chords) - logged that separately #12694
