### ISSUE TITLE
[MU4 Issue] Crash when changing MIDI device

### ISSUE THREAD

**Issue by Skelbti** [musescore/MuseScore#15518] opened 2022-12-22 17:17 UTC
When I tried to change the MIDI Input in `Preferences > I/O > MIDI input` to `No device` MuseScore 4 crash. Same thing happened when you chose another MIDI input option.

**To Reproduce**
1. Go to `Preferences > I/O > MIDI input`
2. Click on `No device`
3. See that MS4 crash

**Expected behavior**
No crash and no MIDI device selected.

**Screenshots**

https://user-images.githubusercontent.com/86026713/209190117-53d1b4f3-b79c-46de-945a-019ef451eec0.mp4

**Platform information**
 - OS: Windows 11 (22H2)

**Comment by zacjansheski** [comment] 2023-07-31 19:50
I am currently unable to reproduce this, is this still an issue?

**Comment by zacjansheski** [comment] 2023-08-15 20:53
Closing

**Closed by zacjansheski** 2023-08-15 20:53 UTC
Labels: needs info
