### ISSUE TITLE
[MU4 Issue] Spanners (hairpins, voltas, lines...) are reportedly sometimes missing in part scores 

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16096] opened 2023-01-27 10:42 UTC
**Describe the bug**
On musescore.org, there have been a few reports where spanners don't show up in part scores. It is not yet clear what causes this.
- https://musescore.org/en/node/341765
- https://musescore.org/en/node/342954
- https://musescore.org/en/node/343502
- https://musescore.org/en/node/343620

**Comment by cbjeukendrup** [comment] 2023-01-27 10:43
Throwing this into 4.0.2 for now, but if we don't find out soon enough how to reproduce it, I don't think we should consider it a blocker. It seems not _that_ common and there is an easy workaround of copy-pasting.

**Comment by oktophonie** [comment] 2023-01-27 14:27
I've noticed slurs from grace notes occasionally disappearing, too.

**Comment by MarcSabatella** [comment] 2023-01-27 23:33
Supposedly https://musescore.org/en/node/342954#comment-1170167 and the comment following have steps to reproduce.

**Comment by AntoniSchonken** [comment] 2023-01-31 15:03
Is there a best practice way to log and output keystrokes/actions in MS? This problem is affecting me consistently, and I would like to produce proper/useful logs to help identify its source (if possible).

**Comment by bmarwell** [comment] 2023-04-27 12:42
Throwing in: It never has happend to me when opening a single part. But sometimes on large scores when:

1. opening a few single parts
2. Then opening all other parts at once.

* Re-adding voltas to one of the new parts sometimes causes the first few (previously opened) parts to have two same voltas in the same bar.
* Playback and score is unaffacted
* The parts menu now shows scores which shouldn't be there (e.g. their names is just '3' or so).

Maybe this helps in reproducing the issue. I can give you a score where this has happened, but cannot be public.

**Comment by Jojo-Schmitz** [comment] 2023-05-05 10:02
Also reported in https://musescore.org/en/node/345824

**Comment by mike-spa** [comment] 2023-05-16 15:56
I'm sorry, everyone, but this is not a workable issue. Before I (or anyone else) can even try to find the cause, there has to be a _reliable_ way of reproducing it.

Attaching files showing the missing spanners in parts is of no help in this case, because the parts have already been created and (typically) extensively worked on, so it's impossible to back track what happened. And invariably, with _all_ of these files, if I reset the corrupted part, or simply create a new part with the same instrument, everything is displayed correctly, which means that the creation of parts works propertly and, again, we can't know where the problem is. [Also, as a side note: please advise users to regenerate the part, if they find themselves in these situations, and if they can do so without loosing too much work].

We know it's a serious issue that keeps being reported, but please help us out. Anectodal evidence isn't helpful. [Hundreds of random unrelated steps](https://musescore.org/en/node/342954#comment-1170167) even less so. If anyone manages to nail this down to a clear, repeatable set of operations, I'm sure we'll figure it out quickly.

**Comment by bmarwell** [comment] 2023-05-16 20:25
FWIW, I will try to create a [Minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) soon.

**Comment by bkunda** [comment] 2023-06-05 08:26
Closing this for now as it hasn't had any activity for 3 weeks and still seems to not be reproducible. 
Happy to re-open this if it can be reliably reproduced.

**Closed by bkunda** 2023-06-05 08:26 UTC
Labels: needs info, P1, corruption
