### ISSUE TITLE
Copying a note with an attached articulation doesn’t copy the articulation

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22096] opened 2024-03-29 01:29 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Copying a note that has been selected by clicking the notehead doesn't copy any attached articulations.

### Steps to reproduce

1. Make a new score and add a note to a measure.
2. Add a staccato marking to the note.
3. Select the note by clicking on the notehead, copy it, and paste it elsewhere in the score.
4. See error: only the note is pasted and not the attached staccato.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/5118efab-aaa2-4f50-8faf-d8535dc290c7

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

macOS 12.7.2

### Additional context

This didn't work in MuseScore 3 either, not sure about MuseScore 2.

Tested with staccato, tenuto, accent, marcato, staccatissimo, and also tremolo (which is extra strange because it forms a part of the stem of the note).

**Comment by Riley-Sullivan** [comment] 2024-03-29 23:54
Thanks for your reply, Marc.

I should have probably opened this up for discussion in the .org forums, but I was just wondering, in what case would the average user ever want to copy just a chord or note without the articulations? It seems strange for a note with tremolo to not have tremolo when you paste it. This may be by design, but is it a good design? It is, after all, something that was included way back in MS2 days (and maybe earlier), long before people like Martin Keary became involved to decide what really is more intuitive for the new user (not that I'm a new user). Should I have posted this as a feature request?

**Comment by MarcSabatella** [comment] 2024-03-30 00:02
The actual use cases have to do with things like cutting a note out of one chord and pasting onto another that might have different articulations, different lyrics, even different duration.  Sometimes you want to replace what’s there, sometimes keep, sometimes add to (in the case of articulations anyhow).

So the actual behavior has been gradually refined over the years based on many previous forum discussions and user requests.  But I’m not at all convinced that the specific 4.2.1 semantics exactly reflect this community consensus.  I’d look to 3.6.2 to see how it behaves in each of these case.  I have a feeling any changes made since then were more accidental than deliberate, although there could have been some intentional design changes as well.

**Comment by Riley-Sullivan** [comment] 2024-03-30 03:40
Well, one of those use cases does actually fail: copying a notehead and pasting it onto a chord of a different duration. It replaces the existing chord, instead of adding it to the chord.

**Comment by MarcSabatella** [comment] 2024-03-30 13:00
Yes, that's something that I recall used to behave differently and was changed after some discussion, but I don't recall the details.  You might want to start a forum discussion to gather more information on this and see if a consensus exists as to what the desired behaviors are for these various cases and then come and propose something here.

**Comment by zacjansheski** [comment] 2024-04-02 13:25
Closing by design.

If you would like to open a feature request feel free to open a new one.

**Closed by zacjansheski** 2024-04-02 13:25 UTC
Labels: UX/interaction
