### ISSUE TITLE
[MU4 Issue] Soprano Sax sounds strange after adding only one note to the score in a new dynamics

### ISSUE THREAD

**Issue by innerthought** [musescore/MuseScore#14946] opened 2022-12-05 12:16 UTC
**Describe the bug**
Soprano Sax starts sounding different after adding only one note at the end of the score in a new dynamics. 

Latest nightly builts tried: 

MuseScoreNightly-223390304-master-5200cd0-x86_64
 
[EDIT of 2022.12.08] MuseScore-4.0.0.223362132-x86_64.msi (Release Candidate)

**To Reproduce**
1. Create a score in MS4 with a few notes for Soprano Sax in default dynamics 
2. Add at the end of the score a new note in mp dynamics
3. Play it back to hear the difference - some notes are not even heard at all.

**Expected behavior**
The sound in all the notes prior to the new added one should sound still the same as before

**Screenshots**
![sax1](https://user-images.githubusercontent.com/119835219/205634783-67c09886-9c22-4950-bb27-4485bbd6b961.jpg)
![sax2](https://user-images.githubusercontent.com/119835219/205632920-75f980e0-eb91-41a1-867f-47bd1e1d3b53.jpg)

https://user-images.githubusercontent.com/119835219/206424765-6041ccfa-06ed-46f0-a0e5-a320df6c51d6.mp4

**Platform information**
 - OS: Win-10, 64-bit operating system, x64-based processor

**Additional context**
Besides some notes not being played at all, other notes in the new score sound too loud creating a bit of distortion.

[EDIT of 2022.12.08] The score:
[sax_clear.zip](https://github.com/musescore/MuseScore/files/10182361/sax_clear.zip)
[sax_dirty.zip](https://github.com/musescore/MuseScore/files/10182365/sax_dirty.zip)

**Comment by innerthought** [comment] 2022-12-06 13:29
Just installed this build and tried. The problem is still there. I wanted to attach the score ( .mscz extension), but I get the message here 'We don't support that file type". What should I do?

**Comment by MarcSabatella** [comment] 2022-12-06 13:40
Either ZIP the file, or just rename it to end in “.zip”

**Comment by innerthought** [comment] 2022-12-06 14:04
Ah, okay. Thank you! 
So, I am sending two scores: one without the added note ('sax_clear.mscz') and one with it ('sax_dirty.mscz'). The problem is especially evident on the last note of the second and of the sixth measure.
[sax_clear.zip](https://github.com/musescore/MuseScore/files/10167097/sax_clear.zip)
[sax_dirty.zip](https://github.com/musescore/MuseScore/files/10167099/sax_dirty.zip)

**Comment by innerthought** [comment] 2022-12-08 10:36
Just added a video file to the first post.

**Comment by innerthought** [comment] 2023-01-29 11:26
It's been more than one month and a half since I've added the video file explaining the situation. I think "needs info" label should be taken down.

**Comment by innerthought** [comment] 2023-04-03 10:44
How is it done here on GitHub? Does anybody regularly check open issues or once any one is dimmed as not urgent it is then forgotten for good? It's already been more than three months and a half since in response to the given "Needs info" I provided a video clip illustrating clearly what the issue is. However, the  "Needs info" label is still there and no one seems to care not only to take it down, but even to look at the video.

**Comment by cbjeukendrup** [comment] 2023-04-03 11:15
Each issue will get fixed on its turn. However, given the huge amount of issues, that can take a while, obviously.

**Comment by innerthought** [comment] 2023-04-03 11:48
> Each issue will get fixed on its turn. However, given the huge amount of issues, that can take a while, obviously.

-- I see. Thank you for this reply. But can anyone, at least, take the "needs info" label down, otherwise, it looks like no one is going to look into this thread (which is, given the huge amount of issues, totally understandable) till that label is there.

**Comment by MarcSabatella** [comment] 2023-05-16 12:43
I can confirm the notes in question don't play (well they make a quioet sound of air but don't "speak" fully), based on whether the mp is added or not.  Independently of whether those notes play fully or not, definitely changing the dynamic in bar10 should not affect the playback of bar 2!

There have been other reports of similar things - dynamics in one measure affecting playbaclk of earlier measures.  See https://github.com/musescore/MuseScore/issues/15651 and https://github.com/musescore/MuseScore/issues/15070

**Comment by Tantacrul** [comment] 2023-05-16 17:55
Message from Matt:

The next debug steps here would be looking at the "dynamics" events send from MuseScore to MuseSampler, and seeing if/how they change between these two scores.  If they are different at the beginning, I think it is likely an issue with the generation on the MuseScore side, but if not then it is a Sampler issue.

Probably worth us taking a peek when someone has time. I'll chuck it in 4.2 for now. If Matt has time, he'll take a look on the sampler side too. @bkunda @RomanPudashkin

**Comment by bkunda** [comment] 2023-11-09 14:27
Moving this to the 4.3 project for now because we've run out of time for 4.2. 
I don't want it to fall off the radar though (hence keeping it for the next release). 
I can still definitely reproduce this using the latest master.

**Comment by bkunda** [comment] 2024-07-09 01:28
This issue is starting to age now, so I checked it again in the latest nightly (plus the latest version of the Muse Sounds master branch and the latest sampler I could get hold of). I was unable to reproduce this issue: 

https://github.com/musescore/MuseScore/assets/86290556/7df7b13c-b61e-4c76-8884-a6aeb7e325a0

I half suspect that a change to either the sampler or the library itself has perhaps solved this problem at some point. 

I'll close it for now for the sake of issue tidiness, but of course let's open it if it does indeed prove to persist.

**Closed by bkunda** 2024-07-09 01:28 UTC
Labels: P2, playback, muse sounds
