### ISSUE TITLE
Bar number ranges shown beneath multi-measure rests are wildly incorrect (math/character mapping issue?)

### ISSUE THREAD

**Issue by eitanmuir** [musescore/MuseScore#16729] opened 2023-03-10 11:02 UTC
### Issue type

Engraving bug

### Bug description

I have a score (attached) where bar number ranges shown beneath multi-measure rests in parts are wildly incorrect (see screenshot). Looks like it may be caused by some kind of math>string conversion problem or a character mapping issue (hence % symbols)?

I do have a lot of style customisation going on which may be a contributing factor, but even when I reset the fonts the issue persists. Have not tried with other scores yet but will update in comments.

### Steps to reproduce

1. Open any part
2. Go to Style > Measure Numbers
3. Check the box to 'Show measure number ranges at multi-measure rests'
4. Problem :(

### Screenshots/Screen recordings

![Solas - Gong - Bar numbering bug](https://user-images.githubusercontent.com/120774204/224297132-6d29d1f4-6db9-4460-8579-3c84e91d1fa0.JPG)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Windows 10

### Additional context

[Eitan Muir - Solas (full gamelan) [2023-03-10 1751].zip](https://github.com/musescore/MuseScore/files/10941245/Eitan.Muir.-.Solas.full.gamelan.2023-03-10.1751.zip)

Live example in the Gong part.

**Comment by oktophonie** [comment] 2023-03-10 11:10
Duplicate of https://github.com/musescore/MuseScore/issues/15635 (happily fixed in master)

**Closed by oktophonie** 2023-03-10 11:10 UTC
Labels: duplicate, engraving

**Comment by eitanmuir** [comment] 2023-03-11 00:55
> Duplicate of #15635 (happily fixed in master)

Amazing thanks oktophonie! Clearly I used the wrong search keywords before submitting hahah
