### ISSUE TITLE
Menubar menus show up in center of window

### ISSUE THREAD

**Issue by frankvanbever** [musescore/MuseScore#19361] opened 2023-09-11 12:54 UTC
### Issue type

UI bug

### Bug description

The menus that show up when clicking any entry in the menubar are drawn in the center of the application rather than below the menu as one would expect. Submenus are also drawn in the center of the window. I noticed this first in the build included in the Arch repositories but I am also able to reproduce it with the Nightly builds.

### Steps to reproduce

On the nightly:
1. Click on any menu in the menubar

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/1665441/e736040b-afbb-4f8f-bd86-9ba4e3edcf59)
![image](https://github.com/musescore/MuseScore/assets/1665441/418cdb68-9fa3-4f79-885c-81bcedd3e569)

### MuseScore Version

OS: Arch Linux, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232530304, revision: github-musescore-musescore-dc56038

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Arch Linux

### Additional context

Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.5.2-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-5500U CPU @ 2.40GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500
Manufacturer: Dell Inc.
Product Name: XPS 13 9343

**Comment by frankvanbever** [comment] 2023-09-11 13:07
```
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
15:05:03.651 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/fvb/.local/share/MuseScore/MuseScore4Development/logs/MuseScore_230911_150503.log
15:05:03.651 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.2.0-dev, build number 232530304 ===
15:05:03.672 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
15:05:03.672 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
15:05:03.673 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
15:05:03.673 | INFO  | 140437052450496 | IpcServer  | listen: id: "742802f2307b44b3a4df5140ae219ff1" 
15:05:03.697 | WARN  | main_thread | Qt         | EGL not available
15:05:03.796 | INFO  | main_thread | DiagnosticsModule | onInit: success start crash handler
15:05:03.890 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: /home/fvb/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
15:05:03.890 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
15:05:03.892 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so
15:05:03.893 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
15:05:03.894 | WARN  | main_thread | Qt         | QIODevice::read (QFile, "/home/fvb/.local/share/MuseScore/MuseScore4Development/shortcuts.xml"): device not open
15:05:03.895 | WARN  | main_thread | Qt         | QIODevice::read (QFile, "/home/fvb/.local/share/MuseScore/MuseScore4Development/midi_mappings.xml"): device not open
15:05:03.912 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/fvb/.local/share/MuseScore/MuseScore4Development/musescorecom_cred.dat
15:05:03.912 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/fvb/.local/share/MuseScore/MuseScore4Development/audiocom_cred.dat
15:05:04.325 | ERROR | main_thread | PluginsConfiguration | updatePluginsConfiguration: [401] The file does not exist
15:05:05.102 | WARN  | main_thread | Qt         | Dropping not implement for QtQuick on Wayland yet!
15:05:05.121 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.121 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.122 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.122 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.122 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.123 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.123 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.123 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.124 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.124 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.126 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.126 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.127 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.127 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.128 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.128 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:05.129 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

15:05:05.129 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
15:05:06.782 | ERROR | main_thread | UpdateScenario | doCheckForUpdate: Unable to check for update, error: [1701] 
15:05:14.654 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
15:05:21.621 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
```

This might be of interest, especially the warnings:

```
15:05:21.621 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
```
which show up whenever clicking a menu.

**Comment by Eism** [comment] 2023-09-11 13:10
Thank you for report, but it is duplicate of #15285

**Comment by MarcSabatella** [comment] 2023-09-11 13:11
Are you sure this worked in a previous build of 4.x?  The issue with Wayland specifically has been present on all 4.x versions as far as I know - see https://github.com/musescore/MuseScore/issues/15285

**Closed as completed by Eism** 2023-09-11 13:10 UTC
Labels: UI, duplicate, regression MS4

**Comment by frankvanbever** [comment] 2023-09-11 13:22
@MarcSabatella I might've accidentally booted into an X11 session previously but it has worked on my system before. Clearly there's been a lot of investigation that has already gone into #15285 so most likely this is a PEBCAK.

@Eism Sorry for the duplicate report.
