### ISSUE TITLE
[MU4 Issue] Crash when clicking on anything selectable

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#12809] opened 2022-08-11 21:34 UTC
**Describe the bug**
Selecting anything in the score crashes MuseScore.

**To Reproduce**
1. Create or open a score.
2. Select anything (note, rest, measure, text, etc.) via clicking or Ctrl+A or whatever.
3. See error.

**Expected behavior**
The item should be selected.

**Screenshots**
It would not be applicable to add screenshots to help explain my problem.

**Platform information**
 - OS: Windows 10
 - Version: MuseScoreNightly-202208110427-master-5c66b92-x86_64

**Additional context**
I will not add any other context about the problem here.

**Comment by MarcSabatella** [comment] 2022-08-11 22:23
This sounds bad, of course, but I cannot reproduce, and I've never heard any other reports of this.  So it seems likely to be caused in part by something very unique to your own system.  Are you sure it happens with *any* score?  If so, can you choose one at random and post it?  Also describe any unusual display or mouse settings that you might have made in your system.

**Comment by ThePython10110** [comment] 2022-08-11 22:31
It is probably my computer then. And it works with an empty score with just one instrument, so it has nothing to do with the score. This worked fine in an older nightly build, and I haven't changed any settings since... so my computer just doesn't like something in the new version.

OR MAYBE NOT...
Either rebooting or resetting to the default settings fixed it. I foolishly did them both before testing, not one at a time, so I have no idea which.

**Comment by oktophonie** [comment] 2022-08-12 08:37
See https://github.com/musescore/MuseScore/issues/10433 (no way to say if it's the same problem, of course).

**Comment by WDMAsh** [comment] 2022-08-17 23:33
I have the same issue, so while it may be rare, it doesn't seem to be unique to OP's system. 

Initially I thought it might be something in my MS 3.6 scores, so I created a new score from scratch in MS4 (public alpha, 4.0.0). I was able to create the score (no notes yet), and change to the MuseJazz fonts. But as soon as I click a barline (intending to change it to a double barline), crash. Ditto if I click to select a bar. Ditto if I use CTRL-A. 

I rebooted and the problem remains.

I've created a couple of new scores to test this and it happens consistently, so it doesn't seem to be anything in the file. (If it would help, though, I can attach a new empty score.)

System is Windows 10. Display is Dell U2718Q, 3840x2160, 8-bit RGB, 60 Hz, NVIDIA GeForce RTX 2060, 175% scaling. Mouse is a Logitech TrackMan. What other information might be helpful?

**Comment by ThePython10110** [comment] 2022-08-17 23:59
Did you also try resetting to the default settings? It was either that or the reboot (I don't know which) that fixed it for me.

**Comment by WDMAsh** [comment] 2022-08-18 00:15
Just tried resetting to default settings (using Edit > Preferences > Reset preferences). Saved the file, closed and re-opened MS4. Still crashes when I click on something. Also crashes if I try to enter a note; I can select a duration (indeed, it seems I can click in the tools and menus to my heart's content), but when I type the note name (I just tried "C") it crashes.

**Comment by lyrra** [comment] 2022-08-18 03:45
It is a known issue that MU4 can start in a very instable mode if audio isn't working. See this PR https://github.com/musescore/MuseScore/pull/8956  that tries to make MU4 work without any audio: https://github.com/musescore/MuseScore/pull/8956
Would probably also remedy #10433.

**Comment by WDMAsh** [comment] 2022-08-18 14:39
Aha. OK, my problem seems to be related to that. Thank you. I went to Windows settings and changed my audio output device, and MuseScore 4 no longer crashes. Unfortunately, I can't hear anything, but that's because I currently don't have any speakers or headphones connected to that device. But I can click in the score and enter notes.

FWIW, the problematic audio device is Realtek Audio, driver v. 6.0.9205.1. Let me know if I can provide further information that would be useful.

**Comment by Tantacrul** [comment] 2022-08-31 18:38
If we agree the issue is already appropriately covered in other issues / PRs, then I'll close this one.

Let me know if you think there's a reason to keep it open.

**Closed by Tantacrul** 2022-08-31 18:38 UTC
