### ISSUE TITLE
[MU4 Issue] Chord Symbols are played, even when option 'Play Chord Symbols' is NOT checked

### ISSUE THREAD

**Issue by GeertWil** [musescore/MuseScore#14885] opened 2022-12-02 13:31 UTC
**Describe the bug**
On playing back a score the chord symbols are played while the option 'Play Chord Symbols' is not checked. Playback can be stopped by checking and then unchecking the play option.

 - OS: 
 - Windows 11 Pro

**Comment by Tantacrul** [comment] 2022-12-02 14:04
May I ask which build you are testing? I'm using the latest nightly and can't reproduce either of these problems?

Nightlies here: https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D

**Comment by GeertWil** [comment] 2022-12-02 16:52
I tried this with the most recent nightly build. Attached a video.

https://user-images.githubusercontent.com/9659505/205343971-d2006054-dd68-424e-be89-3c71a7dcf37f.mp4

**Comment by Tantacrul** [comment] 2022-12-02 17:03
@DmitryArefiev: can you check on Windows? Can't reproduce on Mac.

@GeertWil - does this happen when you create a new score? If it an issue with an older score, could you share it with us?

(If you'd prefer to share privately: info.tantacrul@gmail.com)

**Comment by GeertWil** [comment] 2022-12-02 17:15
I'm in the progress of upgrading my scores. So all used files are old, but it happens on new files too.
I created a new file, simply added the C major scale in quarter notes and added some chords.
Play back chord symbols is not checked, drone like synth-chords are played.

**Comment by DmitryArefiev** [comment] 2022-12-04 20:42
@Tantacrul I think this is the same as #13271 (duplicate)

**Comment by DmitryArefiev** [comment] 2022-12-04 20:47
Closing as duplicate of #13271

**Closed** 2022-12-04 20:49 UTC
