### ISSUE TITLE
Strange transition between notes on Muse Sounds Oboes

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22785] opened 2024-05-12 08:21 UTC
### Issue type

Muse Sounds bug

### Bug description

There is a strange sound heard between the notes of D-flat 4 and C4 in Muse Sounds oboes.

### Steps to reproduce

1. Create a new score with an oboe. Make sure Muse Sounds is activated.
2. Add a D-flat 4 whole note to the first measure, and a C4 whole note to the second measure.
3. Hit play and hear the error: there is a strange sound heard between the notes.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/2fe57923-47f0-403c-96f3-799f17e8b84f

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

macOS 12.7.2

### Additional context

Appears to only be present on mp and mf dynamics, or no dynamics at all (which I assume uses either mp or mf by default).

It still sounds a bit strange on other dynamic levels (like two C's are playing at the same time), but not to the same degree as with mp or mf.

Not sure what version of Muse Woodwinds I am using, but it is the latest as of May 12, 2024.

**Comment by mmeyn** [comment] 2024-05-13 08:54
Duplicate of #17603

**Closed** 2024-05-13 08:59 UTC
Labels: duplicate
