### ISSUE TITLE
Dynamic preceded by hairpin with dynamic ignored (dynamic added to the end of selected hairpin)

### ISSUE THREAD

**Issue by tecc** [musescore/MuseScore#16381] opened 2023-02-15 17:12 UTC
**Describe the bug**
When a dynamic is preceded by a hairpin with a dynamic, the hairpin's end dynamic "overrides" the specified dynamic.

**To Reproduce**
1. Write some music (without dynamics, for now). Just a bunch of notes will do.
2. Create a hairpin, and select it.
3. Add a dynamic to the hairpin by pressing a dynamic from any palette.
4. Add a dynamic after the hairpin is done, preferably a wildly contrasting one. 
5. Play.

**Expected behavior**
The playback reflects the dynamic for the new note(s).

**Screenshots**
![image](https://user-images.githubusercontent.com/38840234/219081420-3e28f675-64a8-44f1-a227-36ab12fcdf28.png)

https://user-images.githubusercontent.com/38840234/219095845-901d2d40-2e02-43ae-85b0-81d742707dea.mp4

**Platform information**
 - OS: Linux (Ubuntu 22.04)
 - Reproduced in both stable and nightly versions, as well as using MS Basic

**Comment by zacjansheski** [comment] 2023-08-18 19:05
Is this still actual?  I just tried on Ubuntu and didn't reproduce.

**Comment by tecc** [comment] 2023-08-19 01:57
Yes. This is a reproduction on Windows.

https://github.com/musescore/MuseScore/assets/38840234/4f974f29-31d2-42e9-ac04-e2c8ce12e4d6


[This is the MSCZ file (albeit zipped).](https://github.com/musescore/MuseScore/files/12384768/MS4.Bug.Report.Reproduction.zip)

**Comment by zacjansheski** [comment] 2023-08-21 14:49
Ah, I see now, thank you for the mscz file!

**Comment by zacjansheski** [comment] 2023-08-21 14:58
Similar to https://github.com/musescore/MuseScore/issues/18835

**Comment by DmitryArefiev** [comment] 2023-09-08 15:04
Yes, this occurs due to the way how dynamic (f) was added:


https://github.com/musescore/MuseScore/assets/90187801/ccd05bda-583e-4144-827a-01fcbd6764f9

**Comment by DmitryArefiev** [comment] 2023-11-24 11:03
@bkunda I propose to bump this since it's not a regression even to MS3 and there is a **workaround** when adding a dynamic **not to selected hairpin but to the note directly** (as I showed above)

**Comment by tecc** [comment] 2023-11-24 13:18
Sometimes you can't have dynamics on the next note like that.
For example, in this short "thing" I wrote the player is instructed to decrescendo from p to ppp and then play the next phrase/passage with the dynamic ff.
![A few bars demonstrating a decrescendo from p to ppp, then switching to ff.](https://github.com/musescore/MuseScore/assets/38840234/c89829a0-bf7a-4d02-9e54-7fb8f15dc6c6)

The suggested workaround would result in this unreadable mess, which also does not play back correctly.
![A few bars demonstrating a decrescendo from p to some obscure dynamic. The obscure dynamic is in fact a combination of ff and ppp in the same spot](https://github.com/musescore/MuseScore/assets/38840234/7fe189cc-1c2e-4f94-b6e0-965a23dd4956)

**Comment by tecc** [comment] 2023-11-24 13:24
To clarify, I made the example in the previous comment for a clarinet, and there is a semantic difference between "this dynamic **starts** at the beginning of this note's duration" and "this dynamic **ends** at the end of this note's duration". This is also a difference that I would expect playback to represent.

**Comment by oktophonie** [comment] 2023-11-24 13:29
This is precisely one of the main issues to be fixed by https://github.com/musescore/MuseScore/issues/16796

**Comment by Dima12357** [comment] 2024-03-01 19:59
I indicated the same thing in issue #20468

**Comment by bkunda** [comment] 2024-05-17 13:44
@oktophonie pls check for validity.

**Comment by wizofaus** [comment] 2024-06-03 20:56
Does this definitely happen for MS Basic and Muse Sounds? Would it need separate fixes for both? Just looking for things I could offer to help with...

**Comment by wizofaus** [comment] 2024-06-04 08:32
Ok, are we happy with the assumption that if a dynamic is added to the end of a hairpin, then that dynamic should really only occur at the last possible tick of that hairpin, rather on the first tick of any subsequent note? (and therefore if there is another dynamic at that next note, that takes over as the new dynamic)

**Comment by Dima-S-Jr** [comment] 2024-06-04 09:38
> Ok, are we happy with the assumption that if a dynamic is added to the end of a hairpin, then that dynamic should really only occur at the last possible tick of that hairpin, rather on the first tick of any subsequent note? (and therefore if there is another dynamic at that next note, that takes over as the new dynamic)

I agree with you, although it would be nice to hear the opinion of one of the more knowledgeable members of the professional team. However, trying is not torture. You can start, and then we'll see. If there are any misunderstandings, I hope they will help you. Good luck)

**Comment by oktophonie** [comment] 2024-06-04 10:39
@wizofaus I think that's a safe assumption. As of https://github.com/musescore/MuseScore/pull/23046 there is a 'proper' way to achieve this so the end-text-on-hairpin method is no longer to be encouraged, but for the sake of existing scores that use it, fixing the playback so that it matches the behaviour of the new anchors-based style would be a nice thing to have.

**Comment by wizofaus** [comment] 2024-06-07 10:26
Can this be assigned to me, had forgotten about it sorry!

**Comment by wizofaus** [comment] 2024-06-07 11:41
Ok there's a big problem here - MS 4.4 has a regression when adding a dynamic mark to a hairpin. In 4.3 it correctly shows it at the end of the hairpin, before whatever note/rest follows it and clear of any associated dynamic text.  But 4.4 doesn't - it simply shows it at where the next note/rest is, superimposed over any dynamic that happens to be there.  And during the playback generation, there's no way I can see of even telling that the dynamic added to the hairpin actually belongs to it.
So I think that needs to be fixed first... can you confirm @oktophonie

**Comment by wizofaus** [comment] 2024-06-07 12:09
Surprisingly despite the existing issues, a small change to the new HairpinSegment::drop( ) function does seem to fix it:

  `  Fraction endTick = Fraction::fromTicks(hairpin()->tick2().ticks() - 1);`

(previously it didn't do the -1).
The playback sounds OK, and the layout isn't too bad, except that when there is no dynamic on the following note, it's shown in an odd position:
4.3.1:

![image](https://github.com/musescore/MuseScore/assets/5364225/2d8cee10-b0b4-455e-a643-c2b450c9f1ff)

4.4 with above change:

![image](https://github.com/musescore/MuseScore/assets/5364225/30889fc0-b8a8-45fa-922c-4fd0dc5dd6ae)

I haven't looked at 4.3's logic but I suspect it basically shortens the hairpin from its regular enough by just enough to fit the "end" dynamic in.

**Comment by bkunda** [comment] 2024-07-11 14:16
I believe this has now been resolved (can no longer reproduce).

N.B. I only changed the dynamic here because _ppp_ was rendering so softly it was basically inaudible. Otherwise, no positional changes of any objects were made. 

Example shows MS Basic (x2) then Muse Sounds: 

https://github.com/musescore/MuseScore/assets/86290556/7be67c1e-b157-4d92-a735-53162941f687

**Closed by bkunda** 2024-07-11 14:16 UTC
Labels: needs info, P3, playback

**Comment by Dima-S-Jr** [comment] 2024-07-12 08:53
> I believe this has now been resolved (can no longer reproduce).

That's weird. In the test build from 12.07 I was unable to get the expected behavior. Instead, the loudness stopped changing at all according to the text at the end of the hairpin. Maybe I'm doing something wrong?

https://github.com/user-attachments/assets/270868c9-2ea4-464b-a5fb-a262dddfab5b

**Comment by oktophonie** [comment] 2024-07-12 09:53
Adding text to the end of hairpins is not the correct way to achieve what you want and using 'dynamics' in this way is not supported in 4.4.

However, with anchors you can achieve this properly by e.g. selecting a dynamic from the palette while the hairpin is selected (this puts a real dynamic at the end now, not a fake text dynamic) and then shunting it back to the end of the previous duration using Shift+Alt+Left, and then adding a dynamic on the new note:

https://github.com/user-attachments/assets/c0fee987-04a0-467b-a743-33aa52ad8650

However, fun fact, playback still doesn't work right; as this is issue is such a mess (and has been closed anyway) I've filed a clean version [here](https://github.com/musescore/MuseScore/issues/23596).
