### ISSUE TITLE
[MU4 Issue] File > Open doesn’t work until a score has been loaded

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7748] opened 2021-03-18 05:33 UTC
**Describe the bug**
File > Open doesn’t work until a score has been loaded

**To Reproduce**
1. Click on 'File' from the upper menu
2. Click on 'Open'

**Expected behavior**
File folder pop-up should apper allows us to select and open score

**Desktop (please complete the following information):**
MacOS

**Comment by mattmcclinch** [comment] 2021-03-18 16:41
The old title was better. The new title is incorrect and misleading, since there are other ways to open a score from the Home screen. The fact is that most of the time the menu bar is not even visible on MacOS, and even when it is, none of the menus work at all.

**Comment by vshalkevich** [comment] 2021-03-18 19:31
OK. I will keep old title

**Comment by mattmcclinch** [comment] 2021-03-23 03:16
Duplicate of #7692, better described in #7766, and fixed with #7782.

**Closed** 2021-03-23 08:51 UTC
