### ISSUE TITLE
Notes imported with custom velocity from MuseScore 3 do not play in MuseScore 4.0.2

### ISSUE THREAD

**Issue by derde** [musescore/MuseScore#16961] opened 2023-03-21 19:05 UTC
### Issue type

General playback bug

### Bug description

To be more precise, when a chord includes notes with custom velocity, and is imported from MuseScore 3, then the "default" velocity parts do not play in MuseScore 4.0.2.

For a chord that has custom velocity for some notes (specifically "-10"), on import from MuseScore3 to MuseScore4 the note with default velocity (0) gets velocity "64", and does not sound.  Actually, it does play, but very faintly.  Someone the default velocity changed from 0 (representing I think 100+0) to 64, and -10 remains 100-10.    (This issue is not present in the web playback, which honours the velocity settings.)

### Steps to reproduce

Make a file in MuseScore 3 with four notes in a chord
Set the velocity for the lower three notes of a chord to -10
Play it: all four notes play, with the top note slightly louder (default level of 0)

Open the file in MuseScore 4.  Play it.  The top note does not play.  Inspecting the details shows that the note velocity is now "64" (from default of zero).  

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Linux Ubuntu

**Comment by RomanPudashkin** [comment] 2023-09-08 07:16
Duplicate of https://github.com/musescore/MuseScore/issues/14768

**Closed by RomanPudashkin** 2023-09-08 07:16 UTC
Labels: duplicate, playback, regression_ms3
