### ISSUE TITLE
Conversion workflow mscz -> musicxml -> mscz -> mp3 doesn't work anymore

### ISSUE THREAD

**Issue by MortenHe** [musescore/MuseScore#16975] opened 2023-03-22 16:43 UTC
### Issue type

File corruption

### Bug description

For music teaching I create reherasal scores in musescore.
As a help for the pupils. I want to export the scores in different tempos as mp3 files.

I created a small script that takes the mscz files in folder and converts them to musicxml. Then the script updates the tempo tag in the musicxml file and coverts it back to mscz. The final step is to convert the mscz to mp3. All conversion steps use the MuseScore command line tools.

This workflow worked fine in MuseScore 3 but then conversion back from musicxml to mscz fails now (empty file).

If there's a solution I'd be glad. If there's an easier way to achieve this, I'm always open for suggestions.

### Steps to reproduce

1. Open Command Line and navigate to folder with mscz file
2. Convert mscz file to musicxml: MuseScore4.exe .\song1.mscz -o song1.musicxml
3. Update the musicxml file (e.g. changing the tempo with Notepad++)
4. Convert musicxml back to mscz file: MuseScore4.exe .\song1.musicxml -o song1-changed.mscz
5. (Export mp3 from mscz file: MuseScore4.exe .\song1-changed.mscz -o song1-changed.mp3)

Step 4 fails

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10 pro

**Comment by cbjeukendrup** [comment] 2023-03-22 16:53
This looks like a duplicate of https://github.com/musescore/MuseScore/issues/16334, which has been fixed in the master branch, so that fix will be included in the next update. So I'll close this one, but correct me if I'm wrong, then I'll re-open it.

Off topic: converting mscz -> musicxml -> mscz is not the most efficient and reliable way. The mscz file is actually just a ZIP file, that contains a bunch of XML files (where the MSCX files contain the actual score data). So, you might want to adjust your script so that it unzips the ZIP file, makes changes to the contained MSCX file, and zips it back into a MSCZ file, and converts that to MP3.

**Closed by cbjeukendrup** 2023-03-22 16:53 UTC
Labels: regression, corruption

**Comment by MortenHe** [comment] 2023-03-24 11:59
Thanks for your quick reply. I updated my script and i works like a charm. I even don't have to convert it back after updating the xml. I just export the mp3 via command line from the mscx file.

The only problem I'm facing now is the low volume in the generated mp3. In MS3 I had a good volume level. But this seems to be a general issue of MS4, because I also have low volume when exporting mp3 from a regular mscz using the GUI.

Any idea or maybe a new issue?

**Comment by cbjeukendrup** [comment] 2023-03-25 18:02
@MortenHe I think that problem is covered by this issue: #16105
