### ISSUE TITLE
Harp Gliss Lines

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25802] opened 2024-12-11 04:13 UTC
### Your idea

Often passages like this are written for Harp:
![image](https://github.com/user-attachments/assets/1231ab38-0eca-4397-b701-e2d6e7cb0e9f)
There is no real way to write this; the gliss lines often move if any formatting changes happen; and the playback has to be manually created/adjusted. 
Many graphic programs have a way to draw a vector line by selecting endpoints for it:

https://github.com/user-attachments/assets/a62ca01b-c26a-42bf-8221-82040b98b1a2

I suggest that Musescore use this exact principle. The user can simply draw a line with as many points as necessary and the program will automatically treat each point as a note and play the glissando lines between them. (The program will also automatically add the final note, which can of course be adjusted afterward.) Note durations are approximated by a calculation of how long the cursor takes to pass over each line, and an approximation of which "beat" the points already lie on. (Basically how it is read by humans.)

### Problem to be solved

See above.

### Prior art

In Sibelius, this can be done by repositioning pralltriller lines and hiding rests, but it is very tedious, and Musescore cannot even do this, because its pralltriller lines cannot be moved diagonally, and its generic lines cannot be reformatted as wavy.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Dima-S-Jr** [comment] 2024-12-11 07:45
In fact, this is a duplicate of paragraph 5 of #22383

**Closed** 2024-12-11 07:50 UTC
Labels: feature request
