### ISSUE TITLE
Guitar Arpeggio not played correctly 

### ISSUE THREAD

**Issue by DerpyHead** [musescore/MuseScore#18616] opened 2023-07-15 02:11 UTC
### Issue type

General playback bug

### Bug description

When you add an arpeggio to a note on a guitar, the following notes that are the same after that will play a staccato instead. 

### Steps to reproduce

1. Choose guitar as an instrument
2. Add two whole notes with the same note
3. Add arpeggio to the first whole note
4. The second whole note will not be played and it'll play a staccato instead
5. This will occur regardless of whether reverb is turned on and regardless of whatever duration of the notes are.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/55637881/af74369e-e282-4428-9084-aa9d17679501

### MuseScore Version

4.1

### Regression

No.

### Operating system

macOS 13.2.1

### Additional context

<img width="982" alt="Screenshot 2023-07-14 at 7 11 15 PM" src="https://github.com/musescore/MuseScore/assets/55637881/8b949e80-be85-445c-8d63-b8677d3aff14">

**Comment by rgreen5** [comment] 2023-07-15 09:11
Duplicate of #11936?

**Comment by cbjeukendrup** [comment] 2023-07-16 22:36
This looks indeed very much like a duplicate, so I'll close it. Thanks for reporting!

**Closed by cbjeukendrup** 2023-07-16 22:36 UTC
Labels: playback
