### ISSUE TITLE
[MU4 Issue] Line elements (cresc, dim, octave etc.) are not rendered in MU4 parts when score from previous version opened

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14658] opened 2022-11-22 11:25 UTC
**Describe the bug**
The bug is about rendering lines in parts created in MU4 from imported MU3 (e.g.) score
The worst thing in this issue is that if you add a line on the part it also renders in the main score and duplicates
Should note that if adding lines in the main score after importing they render on parts as expected. So the bug relates only old scores

**To Reproduce**
1. Open in MU4 the score 
[MU4 sound issues.mscz.zip](https://github.com/musescore/MuseScore/files/10066765/MU4.sound.issues.mscz.zip)
2. Create a clarinet 1 part
3. Compare this instrument in score and in part 

**Expected behavior**
All line elements created for the instrument in main score are rendered in part 
![abariska 2022-11-22 at 13 13 49](https://user-images.githubusercontent.com/101250347/203300964-c7a003d2-92c3-48d2-9186-5f9426ee5f3c.png)

**Screenshots**
![abariska 2022-11-22 at 13 14 55](https://user-images.githubusercontent.com/101250347/203300943-ddf31887-25aa-495c-b172-8499ff7ff6f3.png)

**Comment by Tantacrul** [comment] 2022-11-23 15:14
@oktophonie - this one seems pretty serious. What do you think?

**Comment by mike-spa** [comment] 2022-11-24 09:04
Can anyone replicate this issue with any other files than the one linked here? Cause I've tried creating files in MU3.6, importing them, opening parts etc., but they all work fine. I am also getting a "corrupted file" error message when I open the file linked here (though it still lets me open it), so I'm starting to think that the issue is specific to this file

**Comment by mike-spa** [comment] 2022-11-24 09:42
Additional context: if you open a part that has _already_ been generated, indeed the lines are missing. However, if you generate a part _from scratch_ (for example, create a new empty part and make Clarinet1 visible, or say open the Flute1 part and show Clarinet1) the lines will be visible. This makes me think that part generation itself is now working fine, but maybe it wasn't when the parts for this file were first generated

**Comment by Tantacrul** [comment] 2022-11-24 10:11
In other words, it was processed in a version of MS4 (up to and including the beta) before we made breaking changes to parts.

**Comment by Tantacrul** [comment] 2022-11-24 10:14
Closing unless someone manages to replicate the problem.

**Closed by Tantacrul** 2022-11-24 10:14 UTC
Labels: P1, engraving
