### ISSUE TITLE
Cannot open certain scores created in 3.6

### ISSUE THREAD

**Issue by GeertWil** [musescore/MuseScore#14592] opened 2022-11-18 16:56 UTC
I cannot open some 3.6 scores in version 4.x. No error messages are shown; Musescore closes automatically after a few seconds. Those file can be opened and played back in version 3.6. without any problem.
I exported the files as MusicXML and as files without compression, but these files cannot be opend in version 4 too.
Is there a log file somewhere that tells me more??
[A Wither Shade Of Pale (Procol Harum) - Arr. Gwm.zip](https://github.com/musescore/MuseScore/files/10043238/A.Wither.Shade.Of.Pale.Procol.Harum.-.Arr.Gwm.zip)

**Comment by cbjeukendrup** [comment] 2022-11-18 19:02
Duplicate of #14593

**Closed by cbjeukendrup** 2022-11-18 19:02 UTC
