### ISSUE TITLE
Hidden element stays hidden in parts after Un-hidden in main score

### ISSUE THREAD

**Issue by wongjack2332** [musescore/MuseScore#17470] opened 2023-05-04 19:55 UTC
When an element (e.g. tempo) is hidden in the main score, the hidden elements can be seen as hidden as well in other parts

However, when the element in the main score is changed to not hidden again, it doesn't show in the new parts

**Comment by oktophonie** [comment] 2023-05-04 20:22
Duplicate of https://github.com/musescore/MuseScore/issues/16544 (part of it, anyway)

**Closed by oktophonie** 2023-05-04 20:22 UTC
Labels: engraving
