### ISSUE TITLE
[MU4 Issue] Tied notes with trill not playing correctly

### ISSUE THREAD

**Issue by lordlouckster** [musescore/MuseScore#15279] opened 2022-12-17 16:43 UTC
**Describe the bug**
When you apply a trill to multiple notes connected by a tie, the first note plays correctly with a trill, but the subsequent notes don't play at all.

**To Reproduce**
1. Create a new score with time signature 4/4.
2. Place two whole notes, connected by a tie.
3. Apply a trill to the first note.
4. Play.

**Expected behavior**
The trill should play for both measures.

**Screenshots**
The trill plays for the first measure, but nothing plays during the second.

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment] 2022-12-17 17:05
Something similar happens with arpeggios instead of trills.

**Comment by MarcSabatella** [comment] 2022-12-17 19:05
I assume this is a duplicate of https://github.com/musescore/MuseScore/issues/14109 and/or https://github.com/musescore/MuseScore/issues/14576

**Comment by Tantacrul** [comment] 2023-05-13 11:41
Duplicate

**Closed by Tantacrul** 2023-05-13 11:41 UTC
