### ISSUE TITLE
Footer Text Size Follows Page Number Text Size When "Page number" metadata Tag Is Used In Footer

### ISSUE THREAD

**Issue by Melodykraaft** [musescore/MuseScore#25691] opened 2024-11-30 17:49 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a new score in  MuseScore Studio 4.4.3 using a footer definition that uses a page number metadata tag (see example).
2. Use the pop-up dialogs in Format|Style...Text styles to set the text size of the footer text to 6pt.
3. Set the Page Number text size to 6pt. 
4. Observe properly formatted footer text (see example)
6. Now change the Page Number text size to 11pt (the default)
7. Observe improperly formatted footer: Not only has the page number changed font height to match that of the page number, but all other text in the footer line containing the metadata tag(s) $p and $P as well. (see example)

### Supporting files, videos and screenshots

<img width="1044" alt="Footer Definition" src="https://github.com/user-attachments/assets/5289808f-11b9-404a-8fa4-348331d8837f">

<img width="1053" alt="Foorter Text Style" src="https://github.com/user-attachments/assets/675d2d9e-a9a7-44b9-8726-90534406dce7">

<img width="1064" alt="Page Number Text Style 6pt" src="https://github.com/user-attachments/assets/055c4e94-3333-4135-aba0-22a5c0ce3313">

<img width="1476" alt="Properly Formatted Footer" src="https://github.com/user-attachments/assets/c92fb59b-bf03-4fbc-9aa4-c08ca2e5c6b3">

<img width="1067" alt="Page Number Text Stlye 11pt" src="https://github.com/user-attachments/assets/1ab3f268-7933-486c-b9b4-905e2d397a01">

<img width="1445" alt="Improperly Formatted Footer After Page Number Font Size Change" src="https://github.com/user-attachments/assets/ebca8661-71cd-450f-9f93-2fb9191591db">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS Safari 17.6

### Additional context

1) It looks like the bad metadata tag value also modifies other attributes of the footer text style. Have tested this with the "bold" attribute
2) A suggested run-through of the attached screenshots would be:
- Footer Defintion(.png etc.)
- Footer Text Style
- Page Number Text Style 6pt
- Properly Formatted Footer
- Page Number Text Style 11pt
- Improperly Formatted Footer After Page Number Font Size Change

3) Thus in order to have the footer definition display as defined, one must set the page number text style height to match. If the footer needs a very small text size (e.g., 6pt), setting the page name to work around this issue results in a displayed page number that is much to small

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-11-30 18:28
Probably a duplicate of #25148

**Closed** 2024-11-30 21:36 UTC
Labels: regression MS4, engraving
