### ISSUE TITLE
Changing measure duration from 2/2 to 1/4 in Measure Properties causes MuseScore to crash

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#24765] opened 2024-09-17 07:26 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Add a 2/2 time signature to an empty measure
2. Right click the measure and go into Measure Properties
3. Adjust actual duration to 1/4
4. Notice that the score crashes

### Supporting files, videos and screenshots

Video of the crash:

https://github.com/user-attachments/assets/3927b892-0b27-4225-a059-77827733f76a

Score in which it happens:

[Violin Sonata in F K 57.mscz.zip](https://github.com/user-attachments/files/17024381/Violin.Sonata.in.F.K.57.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

It's only with Measure Properties that this happens, if you instead do Ctrl + Delete to turn the measure into a 1/4 pickup, it works fine.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by CoolSpy3** [comment] 2024-09-17 08:05
This sounds like a possible duplicate of #24298, which should be fixed in MuseScore 4.4.2.

**Comment by MarcSabatella** [comment] 2024-09-17 13:03
I'm not able to reproduce in 4.4.2 using the given score & steps, so almost certainly a duplicate.

**Comment by bkunda** [comment] 2024-09-17 13:09
Looks like this is a duplicate that has now been addressed. 
Happy to re-open if it proves to persist.

**Closed by bkunda** 2024-09-17 13:09 UTC
Labels: duplicate, regression MS4, crash
