### ISSUE TITLE
Frames not appearing on part scores 

### ISSUE THREAD

**Issue by YoavShilon05** [musescore/MuseScore#20171] opened 2023-11-24 15:02 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The different part scores won't show a Vertical \ Horizontal Frame After inserting one on the main score.

### Steps to reproduce

1. Create a new score (with at least one instrument)
2. Click the '+' icon on the toolbar on top
3. Go to 'Frames' > 'Insert Vertical Frame' ('Insert Horizontal Frame' also works)
4. Create a part score for one of the instruments you have added
5. The Frame added on the main score won't appear on the part score. 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/54374032/05d32670-55b7-4a5e-b099-f8283d08d214

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233280304, revision: github-musescore-musescore-1587787

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by oktophonie** [comment] 2023-11-24 15:09
This is because 'Exclude from parts' (in Properties > Score and part synchronisation) is on by default for frames. Turn it off if you want the frame to appear in all the parts.

**Comment by zacjansheski** [comment] 2023-11-27 15:37
Closing as "by design"

**Closed by zacjansheski** 2023-11-27 15:37 UTC
Labels: regression, engraving
