### ISSUE TITLE
[MU4] The score play from the start, instead of continue after change sound

### ISSUE THREAD

**Issue by minhnnguyen003** [musescore/MuseScore#17666] opened 2023-05-21 11:37 UTC
### Issue type

General playback bug

### Bug description

So I change the sound of an instrument while playback, it then start playing that instrument from the start of the score, instead of continue playing

### Steps to reproduce

1. Play any score
2. Playback
3. Open mixer
4. Change the sound of an instrument (while playing)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/67821012/c0400b18-5f57-4a3d-945d-bfda1866a9ae

### MuseScore Version

4.0.2.230651553

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2023-05-21 12:42
This seems a duplicate of #14902 and https://github.com/musescore/MuseScore/issues/15047. Thanks for reporting!

**Closed by cbjeukendrup** 2023-05-21 12:42 UTC
Labels: playback, regression_ms3
