### ISSUE TITLE
Exporting audio crash. Please help. Can't publish score w/ corresponding MuseSounds audio.

### ISSUE THREAD

**Issue by J12345Z-H** [musescore/MuseScore#15631] opened 2022-12-28 03:56 UTC
Intro and Description:
Hello MuseScore GitHub community. I am experiencing a crash while attempting to publish this movement of my string quartet while exporting the audio. This happens every time. I am using a Chrome OS. 

Reproduce:
Open "File" ~> "Publish to MuseScore.com..." or click "Publish" ~> "Publish to MuseScore.com..." via the banner. Then Iclick "Publish" on the "Publish to MuseScore.com" pop-up. It starts doing a process called "Exporting Audio".
That's about it.

What to expect:
It successfully exports up to about 36 percent before the whole software crashes. 

Thank you!
![Screenshot 2022-12-27 9 54 45 PM](https://user-images.githubusercontent.com/121531597/209754884-d43d1b72-1fd3-4288-8aa9-bd2c23526f8f.png)
![Screenshot 2022-12-27 9 49 30 PM](https://user-images.githubusercontent.com/121531597/209754358-da8c6477-49f9-4f73-9ee2-1deb8c76bd90.png)
["Chromebook" String Quartet 3rd movement.zip](https://github.com/musescore/MuseScore/files/10311994/Chromebook.String.Quartet.3rd.movement.zip) 
or
["Chromebook" String Quartet 3rd movement 2.zip](https://github.com/musescore/MuseScore/files/10312025/Chromebook.String.Quartet.3rd.movement.2.zip)

**Comment by ordylan** [comment] 2022-12-28 14:05
Me too, even crashed 6 times!(About 78%)

**Comment by cbjeukendrup** [comment] 2022-12-28 16:07
Possibly duplicate of #15512, #15419, #15359, #14613
Maybe also #15539, #15252, #15142, #14757, but those are less likely related

**Closed** 2023-01-02 18:38 UTC
