### ISSUE TITLE
[MU4 Issue] Tempo text disappears after editing

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#15678] opened 2023-01-02 00:25 UTC
**Describe the bug**
Tempo texts added from the Tempo palette, like ♩=80 disappear when you delete all the text at once and you add any text, not being clickable but still being selectable with shift + drag

**To Reproduce**
1. Open any score
2. Add a tempo text like ♩=80 (texts like Andante, Lento, etc. are not affected) from the Tempo palette
3. Select all the text, delete it and type anything, you will notice a different font

**Expected behavior**
Tempo text won't disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/68985619/210188300-2920779c-9ff1-487b-b6cf-17decb673911.png)

**Platform information**
 - OS: Windows 11

**Additional context**
- Only happens with tempo texts containing [duration] = [number], texts like andante, allegro and others are not affected.
- You can't see the text but the tempo does get changed to whatever you added from the palette.
- You need to select everything and delete it or select everything and type something, deleting the text character by character won't work.

**Comment by oktophonie** [comment] 2023-01-02 09:23
Closing as duplicate of https://github.com/musescore/MuseScore/issues/12978

**Closed by oktophonie** 2023-01-02 09:23 UTC
