### ISSUE TITLE
Repeat playback not working for DC/DS al fine

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18807] opened 2023-07-26 10:28 UTC
### Issue type

General playback bug

### Bug description

The attached score plays back correctly in MS3 but not in MS 4.1. The **DC al fine** indication should result in playback stopping at the **fine** but it continues beyond this point.

### Steps to reproduce

1. Open the score in MS 3 and check that it plays correctly. 
[repeats.zip](https://github.com/musescore/MuseScore/files/12171216/repeats.zip)

2. Now open the score in MS 4.1 and play it back there.

RESULT: The playback does not stop at the **Fine** sign but continues beyond it. The problem may affect DS al fine as well (but not checked).

### Screenshots/Screen recordings

Short screencast of playback of the attached file in MS 4.1:

https://github.com/musescore/MuseScore/assets/87246583/89661886-76e1-45b7-bc80-e8dfe5e7033e

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by MarcSabatella** [comment] 2023-07-26 15:34
Your video shows the same as what I see/hear - the playback *does* stop, only the visual indicator of the playtback bar continues past the end.  That makes this a duplicate of https://github.com/musescore/MuseScore/issues/15116.  Note this isn't *really* limited to just Fine, you can see a similar effect playing any score to the end - see for instance your previous issue https://github.com/musescore/MuseScore/issues/13683.  I continue to assume this on account of waiting for the reverb to die, but it would of course be great to not providie the misleading visual feedback.

**Comment by zacjansheski** [comment] 2023-07-26 18:38
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/15116

**Closed by zacjansheski** 2023-07-26 18:38 UTC
Labels: playback, regression_ms3
