### ISSUE TITLE
[MU4 Issue] Export Audio process can't be cancelled

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#14147] opened 2022-10-28 16:53 UTC
**Describe the bug**
After selecting the audio format, clicked export to start the export process. First time I exported.
I discovered it was painful slow and thought I better cancel the export however there is no option to stop this process.
Guess I can hard kill the running process in the OS, but would be nicer if it can just be stopped in the GUI as well.

**To Reproduce**
1. Open a score
2. Open the export menu
3. Set the format to WAV audio
4. Select a part
5. Click Export
6. Select the location to store the file
7. And now try to stop the export

**Expected behavior**
An option to stop the export process would really be nice.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550012/198690961-70b147fc-1f24-415f-8623-cf9ccdcd2165.png)

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by Tantacrul** [comment] 2022-11-01 11:46
By design for now. We will add this in 4.x.

**Comment by eitanmuir** [comment] 2023-01-05 02:28
> By design for now due to some technical issues that would cost us a reasonable amount of time, so we delayed the ability to cancel audio export. We will add this in 4.x.

In the mean time, is there any chance of an Export Queue List? If it's easier to implement it would be a decent temporary solution.

Score - exporting [progress bar]
Flute - queued [cancel button]
Clarinet - queued [cancel button]

Where [cancel button] removes the part from the queue

Loving MU4 by the way, just switched from Sibelius and I'm never going back! :)

**Comment by Tantacrul** [comment] 2023-01-13 11:51
Assigning this to the second patch release.

**Comment by Tantacrul** [comment] 2023-01-13 11:51
@jessjwilliamson - could you mockup how the export audio dialog should look, with the cancel button?

**Comment by Tantacrul** [comment] 2023-01-13 12:05
@jessjwilliamson - we probably don't want the minimise, maximise, close buttons at the top there.

**Comment by jessjwilliamson** [comment] 2023-01-13 12:12
@Tantacrul Just updated screenshot comment

**Comment by DmitryArefiev** [comment] 2023-01-20 17:17
Fixed in #15948

**Closed** 2023-02-08 13:18 UTC
Labels: P0

**Comment by DmitryArefiev** [comment] 2023-03-01 16:29
Retested on Win10
