### ISSUE TITLE
[MU4 Issue] Note input lags

### ISSUE THREAD

**Issue by VictorEijkhout** [musescore/MuseScore#15649] opened 2022-12-29 23:10 UTC
Input from computer keyboard: notes sound considerably after their keypress. I/O buffer size is set to 1024 samples. Would a smaller buffer help?

**Comment by RomanPudashkin** [comment] 2024-04-25 09:22
Duplicate of https://github.com/musescore/MuseScore/issues/16112

**Closed by RomanPudashkin** 2024-04-25 09:22 UTC
