### ISSUE TITLE
Crash when changing whole note shortcut 

### ISSUE THREAD

**Issue by GeneralMidi** [musescore/MuseScore#16058] opened 2023-01-25 10:54 UTC
To reproduce.

Open a new blank score. 
Open Preferences - > shortcuts
Type whole into filter box
Double click "set duration: whole note 
Type a and press save. 
Press OK when prompted
Clear filter box by pressing the x
Use the scroll bar at the side to scroll up and down the shortcuts. Scroll in a fast manner. 
Crash. 

Hope you can reproduce.

**Comment by GeneralMidi** [comment] 2023-01-28 13:53
On Windows 10. Can you reproduce?

**Comment by RomanPudashkin** [comment] 2023-01-30 10:05
> On Windows 10. Can you reproduce?

Yes, we can. The fix is coming soon. But I'll close this issue because it's a duplicate of https://github.com/musescore/MuseScore/issues/15171

Thank you!

**Closed by RomanPudashkin** 2023-01-30 10:05 UTC

**Comment by RomanPudashkin** [comment] 2023-01-30 14:58
@GeneralMidi could you try this build?
https://github.com/musescore/MuseScore/actions/runs/4044852104/jobs/6955532137

Does it fix the crash?
