### ISSUE TITLE
[MU4 and Muse Sound Issue] When opening saxophone quartet Muse Sounds allocates 4 tenor saxophones

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#14043] opened 2022-10-25 20:22 UTC
**Describe the bug**
Whether I open a new score for saxophone quartet or open a saxophone quartet written with MU3, Muse Sounds sets tenor to all mixer channels.

**To Reproduce**
1. Create a new score -> "Create from template"
2. Click on 'Chamber Music" then Saxophone Quartet
3. Take a look at the mixer -> all instruments have allocated sound Tenor Saxophone

**Expected behavior**
Soprano, alto, tenor and baritone saxophone are allocated to respective instrument

**Platform information**
 - OS: Linux - Fedora 36  and Ubuntu 22.04

**Comment by sberla365** [comment] 2022-10-26 19:42
The same happens when opening a MU3 saxophone quartet score defaulted to MS Basic and switching to Muse Sounds from View -> Playback Setup

**Comment by sberla365** [comment] 2022-10-31 19:35
Seems fixed with recent Muse Sounds updates

**Comment by sberla365** [comment] 2022-11-01 07:35
It seems partially fixed with recent Muse Sounds updates. Sometimes switching from MS Basic to Muse Sounds in View > Playback Setup only Alto ad Baritone are allocated while tenor and soprano stay on MS Basic

**Comment by zacjansheski** [comment] 2023-06-30 20:10
I am unable to reproduce this on Ubuntu 20.04.6

Closing

**Closed by zacjansheski** 2023-06-30 20:10 UTC
