### ISSUE TITLE
Local save dialog segfaults in nightly build (Linux)

### ISSUE THREAD

**Issue by jgcodes2020** [musescore/MuseScore#20999] opened 2024-01-13 20:23 UTC
### Issue type

Crash or freeze

### Bug description

Exactly as the title says: the save dialog causes a crash on the latest nightly build as of 2024-01-13 3:00 PM EST.

This is *not* the dialog asking you whether you want to save on the cloud or on your computer, it's the dialog that asks you where to save it on your computer.

### Steps to reproduce

1. Factory-reset MuseScore, so that it prompts you whether you want to save to the cloud or save locally upon saving.
2. Open MuseScore.
3. Create a new score.
4. Try to save it locally.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/35639051/6d0f519c-bba0-48a2-8f3e-714b8396930b

### MuseScore Version

OS: Linux 6.6.10-arch1-1, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240130304, revision: github-musescore-musescore-698d070

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

ArcoLinux (rolling-release, Arch-based)

### Additional context

- Desktop environment: KDE Plasma 5.27.10
- Display protocol: Wayland

Here's what the standard error output looks like:
```
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
[72688:72688:20240113,151124.193620:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194180:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194314:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194497:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194567:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194671:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194705:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194740:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194775:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194809:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194842:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194877:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194909:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194944:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.194978:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195012:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195044:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195076:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195107:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195138:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195172:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195203:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195234:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195266:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195298:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195332:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195366:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195397:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195430:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195467:ERROR elf_dynamic_array_reader.h:61] tag not found
[72688:72688:20240113,151124.195644:ERROR elf_dynamic_array_reader.h:61] tag not found
/tmp/.mount_mscore9wM9bL/AppRun: line 26: 72684 Segmentation fault      (core dumped) "${APPDIR}/bin/mscore4portablenightly" "$@"
```

The bug does not occur when setting `QT_QPA_PLATFORM=x11`. On X11, a GTK-styled file dialog pops up and it saves properly; whereas on Wayland, a custom Qt-styled dialog appears.

**Comment by DmitryArefiev** [comment] 2024-03-22 09:14
@jgcodes2020 I can't reproduce on latest builds (4.3 and master), LinuxUbuntu 22.04.4 LTS.

Can you try again on your side please?

**Comment by DmitryArefiev** [comment] 2024-04-11 11:47
No reply.. Closing

**Comment by DmitryArefiev** [comment] 2024-04-11 11:47
@jgcodes2020 Please reopen if still occurs

**Closed** 2024-04-11 11:48 UTC
Labels: P1, regression, crash, os: linux
