### ISSUE TITLE
[MU4 Issue] Added sound on fermata

### ISSUE THREAD

**Issue by DamienDyar** [musescore/MuseScore#14076] opened 2022-10-26 20:09 UTC
**Describe the bug**
opened a previous 3.6 score in MU4 found that short fermata has added sound apparently in the fermata time.

**Expected behavior**
nothing but get a 'pop' sound in soprano register it appears

**Screenshots**
sorry can't do that

**Platform information**
Win11

**Additional context**

**Comment by MarcSabatella** [comment] 2022-10-26 20:20
Can you attach your score (ZIP it first so GitHub will accept it)?  I don't hear anything unusual when I tried this.  Unless, your score is for choir, in which case, I do get blip on any rest, fermata or not.

**Comment by DamienDyar** [comment] 2022-10-27 09:50
[Boireann Cois Mara 170322 orchestration 3 saved to MU4 .zip](https://github.com/musescore/MuseScore/files/9878127/Boireann.Cois.Mara.170322.orchestration.3.saved.to.MU4.zip)
Thanks for reply.
it is a choir score and the details are as follows:
Bar 31 fermata + caesura --- blip/pop appears
Bar 49 no fermata + caesura --- no blip
Bar 65 short fermata + caesura --- no blip
Bar 68 No fermata + caesura --- blip appears
Bars 78-80 no fermata, no caesura --- blip,blip sounds here (? on rests?)
Bar 83 Fermata over Tenor line note E --- this note not sounding 

So not sure what's driving prob fermata or caesura or something else

hope this helps.

**Comment by MarcSabatella** [comment] 2022-10-27 12:53
It's definitely the caesura, at least in bar 31 - remove them and the problem goes away.  I think the problem occurs when a choir note ends right before a silence of any kind - whether a rest or caesura.  But not *every* time that happens, as your bars 49 and 65 show.  Anyhow, I am pretty sure this is indeed the same issue as what I reported earlier - see https://github.com/musescore/MuseScore/issues/14003.  Hiopefully the additional examples help identify the cause of the problem.

**Comment by DamienDyar** [comment] 2022-10-27 14:04
I did try removing the caesura, but the pop sound still occurs.  Tried again just now with same effect.  Seems to me to be independent of the caesura, but your point on note ending before a silence might be apposite. ??

**Comment by DamienDyar** [comment] 2022-10-27 14:07
and that links to something funny going on at bars 78-80 perhaps?

**Comment by MarcSabatella** [comment] 2022-10-27 14:08
Did you remove it from the invisible staves as well?  Try right-clicking one, Select / Similar, then Delete, to remove them all.

**Comment by DamienDyar** [comment] 2022-10-27 14:17
Ah!  yes that got rid of it :)

**Comment by Tantacrul** [comment] 2022-10-27 21:32
I think this is to do with older scores not being interpreted in _quite_ the same way. I quickly tried to replicate the problem in a new score and am unable to hear any pops.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/21022311/198402282-5bb072c7-49c4-41bc-8c85-1d9bc76ca75a.png">

https://www.dropbox.com/s/vozvymshf05ahj0/Pauses_Choir.mscz?dl=0

**Comment by MarcSabatella** [comment] 2022-10-27 21:48
The score in my example in the other issue was created from scratch in MuseScore 4 just within the last couple of weeks, so it is definitely not just older scores.  But I also struggle to reproduce it on command in other scores.  It might relate to specific pitches, or specific rhythms, or specific numbers of things happening at once, not sure.

Here is the link from the other issue:

https://musescore.com/user/2975/scores/8838546/s/5F8ZR6?share=copy_link

You can hear the issue online in the soprano starting at bar 27, although the playback is out of sync with the display, so you're better off downloading it.  The problem remains even if you solo the soprano, so it's very easy to hear in this score.

**Comment by MarcSabatella** [comment] 2022-10-27 21:50
But, supposedly this was fixed earlier today...

**Comment by MarcSabatella** [comment] 2022-10-28 00:24
Unfortunately, while the fix is already deployed and I can verify it works for *my* score, it doesn't work for completely the one attached to this.  Somehow the caesura is triggering the issue differently, I guess, and bar 31 still has the blip.  Not sure who; others spots are better now.  But, this issue should probably remain open.

**Comment by MarcSabatella** [comment] 2022-10-28 03:02
Further update - I can still reproduce this in my score above, but *only* if I change the sound to Altos, Tenors, or Basses (the latter also requiring me to take it down an octave.  So, it seems the recent update fixed the issue for Sopranos only.

**Comment by MarcSabatella** [comment] 2022-10-31 16:56
Worth testing again with today's (yesterday's?) update to Muse Sounds. My scores now play well.

**Comment by Tantacrul** [comment] 2022-10-31 18:40
Yes please! It would be great to close this issue

**Comment by DamienDyar** [comment] 2022-11-01 10:55
I've tried on my score again this am, but still getting some blips.  Is my MU4 updating to overnight fixes automatically or do I have to re-install it each time?

**Comment by MarcSabatella** [comment] 2022-11-01 12:52
If Muse Hub is not already running, you need to re-run it and make sure it downloads the updates.  Click the gear icon at top right then the update button is you don't see it updating automatically.  I'm not sure, but probably it also makes sense to restart MuseScore afterwards.

**Comment by DamienDyar** [comment] 2022-11-01 16:00
Thanks for reply Marc
I've downloaded MU4 to my desktop.  There does not appear to be a gear icon at top right.  In Preferences>Update I've clicked OK but don't see anything nor any dialogue following that.  In any event it makes no difference to the appearance of blips.
Is there a different view with the gear icon?  Or are you working from the online version?

**Comment by DamienDyar** [comment] 2022-11-01 16:15
I've tried a different score, attached, and the blip appears here as well but it's only at rests and not all rests.  So, rests at end of bars 17, 22, 23 have a resonant blip, but there appears to be no blip at bars 30 or 40!

[Love_at_Christmas v5 published 051221.zip](https://github.com/musescore/MuseScore/files/9912113/Love_at_Christmas.v5.published.051221.zip)

**Comment by Tantacrul** [comment] 2022-11-01 17:25
I've just tried this in the latest nightly (with the latest Muse Sounds and can't reproduce any blips on any rests (including the ones you mentioned @DamienDyar).

**Comment by Tantacrul** [comment] 2022-11-01 17:26
And this is the gear Marc is referring to:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/21022311/199298123-cbb4e208-f3b3-4fb2-8303-d237c738f418.png">

**Comment by DamienDyar** [comment] 2022-11-01 21:31
I'm stumped Tantacrul, just reproduced all blips as before - following update and close/reopen programme as recommended.  
(thanks for guidance re HUB)

**Closed** 2023-07-05 16:30 UTC
Labels: muse sounds
