### ISSUE TITLE
[MU4 Task - Feature Request] Good job adding rit. and acel. - yet "a tempo" is missing

### ISSUE THREAD

**Issue by RotoBanana** [musescore/MuseScore#14756] opened 2022-11-25 19:06 UTC
**Task description**
Good job adding rit. and acel. 
**yet "a tempo" is missing.**

More than that, the functionality of the rit. and acel. is pretty limited, and it's 
Perhaps you'll want to take some things from the "Tempo Changes" plugin of Musescore 3, or just add the whole plugin as a feature. Or perhaps add something like the time warp tool from cubase. Since they are more specific in where the composer would like to make his piece slower or faster, in order to add more humanity to the composition.

Thank you so much for finally adding rit. and acel. last time I needed to download Tempo Changes (which is a pretty good plugin), instead of having rit. and acel. at the sidebar.
I'm really happy to see a **free open-source** composition software evolve so much! Keep up the great work!

**Comment by cbjeukendrup** [comment] 2022-11-25 21:55
Duplicate of #14445

Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-25 21:55 UTC
