### ISSUE TITLE
Crash after opening, closing, then reopening the "More" tab of a palette

### ISSUE THREAD

**Issue by jgcodes2020** [musescore/MuseScore#17275] opened 2023-04-19 00:24 UTC
### Issue type

Crash or freeze

### Bug description

A Wayland protocol error occurs when opening, closing, then reopenin

### Steps to reproduce

1. Open MuseScore.
2. Open some score or create a new score.
3. Go to any palette of your choice.
4. Click the "More" tab to show more options.
5. Click on the score to close the "More" tab.
6. Click the "More" tab to open it again.
7. Wayland protocol error.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/35639051/232932729-0a929403-c4ce-44bf-87ce-6b80dda3a7ad.mp4

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

ArcoLinux (rolling)

### Additional context

This is the Wayland error message with `WAYLAND_DEBUG=1`:
```
[2994407.229] wl_display@1.error(xdg_wm_base@25, 3, "xdg_surface must not have a buffer at creation")
```

Relevant system details:
- OS: ArcoLinux (updated Apr. 18, 2023)
- Kernel version: 6.2.11
- CPU: Intel i7-1165G7 (Tiger Lake)
- GPU: Iris Xe Graphics
- Qt version: 6.5.0

**Comment by DmitryArefiev** [comment] 2023-05-04 13:05
I **can't reproduce** it on my **LinuxUbuntu** 22.04.02 LTS

@jgcodes2020 Do you have connected an external monitor? Strange that More window appears very far from palettes..

**Comment by DmitryArefiev** [comment] 2023-05-04 13:07
@MarcSabatella Can you try this on your Linux please? Maybe you experienced with crashes like that? 

Thanks!

**Comment by MarcSabatella** [comment] 2023-05-04 13:25
No issues for me on 4.0.2 or master - the More window opens in the normal place and no crash on multiple opens.  But, the mention of Wayland means, this probably wouldn't apply to me in the same way anyhow, since my Linux system runs as a container within ChromeOS and the display system uses Wayland only indirectly.

**Comment by jgcodes2020** [comment] 2023-05-04 21:23
> I **can't reproduce** it on my **LinuxUbuntu** 22.04.02 LTS
> 
> @jgcodes2020 Do you have connected an external monitor? Strange that More window appears very far from palettes..

I do. I'll check if the bug still happens without that monitor plugged in.

**Comment by zacjansheski** [comment] 2023-06-02 18:05
Closing due to inactivity / lack of reproducibility

**Comment by jgcodes2020** [comment] 2023-06-03 03:08
> > I **can't reproduce** it on my **LinuxUbuntu** 22.04.02 LTS
> > @jgcodes2020 Do you have connected an external monitor? Strange that More window appears very far from palettes..
> 
> I do. I'll check if the bug still happens without that monitor plugged in.

Well apparently it does.

**Comment by jgcodes2020** [comment] 2023-06-23 21:23
Ran into the same crash when I open, close, then open the time signature popup in the new score window. I have a feeling this occurs with every 2nd-level popup, but I can't be sure.

@DmitryArefiev this might be a KDE-specific bug (I assume you're using GNOME?)

**Comment by jgcodes2020** [comment] 2023-11-02 01:46
Looking deeper into this issue, it seems like MuseScore creates an `xdg_toplevel` instead of an `xdg_popup` when summoning the window, which doesn't seem right.

**Comment by cbjeukendrup** [comment] 2023-11-02 15:05
@jgcodes2020 I've created a test build here, that _might_ solve that: https://github.com/cbjeukendrup/MuseScore/actions/runs/6734422129
It will be ready for downloading in ca. 30 minutes from now. Would be great if you could try it out!

**Comment by jgcodes2020** [comment] 2023-11-26 02:51
> @jgcodes2020 I've created a test build here, that _might_ solve that: https://github.com/cbjeukendrup/MuseScore/actions/runs/6734422129 It will be ready for downloading in ca. 30 minutes from now. Would be great if you could try it out!

Just tested it today, it seems like the 'More' popup still shows up in the wrong spot. It also doesn't close when I click outside it.

**Comment by cbjeukendrup** [comment] 2024-01-12 00:33
@jgcodes2020 Could you please try if the crash still occurs in the latest nightly build from https://musescore.org/en/nightly-builds?

If that crashes, then I will submit the fix that I mentioned above, since that is at least an improvement of the situation (and I think there is already a separate issue about the wrong positioning). 
If not, then it was solved in the meantime by something else than my fix.

Thanks in advance!

**Comment by jgcodes2020** [comment] 2024-01-13 20:01
> @jgcodes2020 Could you please try if the crash still occurs in the latest nightly build from https://musescore.org/en/nightly-builds?
> 
> If that crashes, then I will submit the fix that I mentioned above, since that is at least an improvement of the situation (and I think there is already a separate issue about the wrong positioning). If not, then it was solved in the meantime by something else than my fix.
> 
> Thanks in advance!

Alright, just tested, this bug is gone in nightly. There is another dialog-related bug that I'll need to make a separate ticket for though.

**Comment by cbjeukendrup** [comment] 2024-01-13 21:32
Thanks for checking! Then I will close this issue.

**Closed by cbjeukendrup** 2024-01-13 21:32 UTC
Labels: needs info, community, regression, crash, os: linux
