### ISSUE TITLE
[MU4 Issue] Unable to Save Text Styling

### ISSUE THREAD

**Issue by jieshunwang** [musescore/MuseScore#11375] opened 2022-04-26 07:58 UTC
**Describe the bug**
Any changes made to style and size of text (including fingerings, expressions, titles etc.) could not be saved.

**To Reproduce**
1. Open any score.
2. Change the style/size of text.
3. Press save.
4. Close the Score.
5. Reopen the Score.
6. The changes haven't saved.

**Expected behavior**
Any changes made to style and size of text should be saved.

**Screenshots**

**Platform information**
 - OS: Windows 11 Home
 - Version: 21H2
 - OS Build: 22000.613
 - Experience: Windows Feature Experience Pack 1000.22000.613.0

**Additional context**

**Comment by Tantacrul** [comment] 2022-04-28 11:01
I can confirm that some style settings are not being remembered:

1. Bold, Italic, underline and strikethrough are not being remembered / saved
2. Size settings are not being remembered / saved

Basically these options:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/21022311/165738305-f9d08eea-2727-476f-a29e-5419f525ec7f.png">

**Comment by Tantacrul** [comment] 2022-04-28 11:02
Added a P0, since this is core functionality.

**Comment by RomanPudashkin** [comment] 2022-04-30 09:36
@mike-spa 
These changes https://github.com/musescore/MuseScore/pull/11099#discussion_r855332583 also caused this bug. This line resets all custom text styles in the score:
`masterScore->styleChanged()`

@Tantacrul @jieshunwang 
Thanks to @Eism, the bug has already been fixed in the latest master (see https://github.com/musescore/MuseScore/pull/11298/commits/163c60ad98432b9d94653f7f853cfd095a6e6f25). So, please check it again

**Comment by Tantacrul** [comment] 2022-04-30 09:53
Just checked. It is, indeed, fixed. Well done @Eism :)

Fixing bugs almost faster than they can be logged 👯

**Closed by Tantacrul** 2022-04-30 09:53 UTC
Labels: P0
