### ISSUE TITLE
[MU4 Issue]Hello, the program does not run, the blue window appears but after 2 seconds it disappears and the program does not open

### ISSUE THREAD

**Issue by jafergaya** [musescore/MuseScore#16309] opened 2023-02-10 13:30 UTC
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by cbjeukendrup** [comment] 2023-02-11 00:39
This is probably a duplicate of https://github.com/musescore/MuseScore/issues/15235 or https://github.com/musescore/MuseScore/issues/15637 for example. 

You could try downloading the build from https://github.com/musescore/MuseScore/actions/runs/3832162757 (see the download link under "Artifacts"), to check whether that fixes the problem.

**Comment by cbjeukendrup** [comment] 2023-02-17 14:17
Hi! Could you please try if the build from https://github.com/musescore/MuseScore/suites/11044663711/artifacts/561149134 works correctly?

**Comment by jafergaya** [comment] 2023-02-17 19:57
Hello, thanks, I have run from Musescore.exe and I have tried writing a score and it works, what should I do to make Musescore 4.0.1 work?

**Comment by cbjeukendrup** [comment] 2023-02-17 19:59
If this build works, then waiting for 4.0.2 is the solution! It won't be long anymore. In the meantime, you could keep using this test build.

**Comment by jafergaya** [comment] 2023-02-17 20:07
Thank you very much, we will wait

**Closed** 2023-05-09 13:09 UTC
