### ISSUE TITLE
[MU4 Issue] Not enough information about corrupted file

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#15740] opened 2023-01-06 21:15 UTC
When i open a file, i have this message. 

![image](https://user-images.githubusercontent.com/1835871/211100978-aa76bd84-0cd0-4338-9213-7841fb83280f.png)

However the file opens correctly

Musescore 3 gave me Measures where the file was corrupted not MuseScore 4

**Comment by oktophonie** [comment] 2023-01-06 21:21
Duplicate of https://github.com/musescore/MuseScore/issues/11807
To be fixed by https://github.com/musescore/MuseScore/issues/15226

**Closed by oktophonie** 2023-01-06 21:21 UTC
