### ISSUE TITLE
[MU4 Issue] Glissando disappearing in harp part

### ISSUE THREAD

**Issue by GabrielYudenich** [musescore/MuseScore#16270] opened 2023-02-08 06:21 UTC
**Describe the bug**
My harp part the glissandos are disappearing, but in the full score, the glisando are there.

**Screenshots**
The part:
![image](https://user-images.githubusercontent.com/51841352/217450500-f04314f8-3353-4041-b40b-cb00f17e5b3e.png)

The full score (ignore the legato line)
![image](https://user-images.githubusercontent.com/51841352/217450628-5ff3ff71-3c57-4e97-b594-e20a11f01a42.png)

**Platform information**
Windows 10

**Comment by oktophonie** [comment] 2023-02-08 11:31
Duplicate of https://github.com/musescore/MuseScore/issues/16096
However, if you're able to provide a score so we can reproduce it, that is always helpful.

**Closed by oktophonie** 2023-02-08 11:31 UTC
