### ISSUE TITLE
Can't use tab key to switch between input fields when creating a new score

### ISSUE THREAD

**Issue by mduboule** [musescore/MuseScore#21010] opened 2024-01-14 19:36 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Using the mouse works of course, but it would be a nice UX improvement to be able to use the tab key to quickly type all the info.

### Steps to reproduce

1. Create a new score
2. Click 'Next'
3. Try to tab between the different inputs here. For me, I'm only able to select 'Key signature', 'Title' and the 'Done' button. I'd expect to be able to tab through all the different inputs instead.

### MuseScore Version

4.2.0-233521125

### Regression

No.

### Operating system

OS: macOS 14.2, Arch.: x86_64

**Comment by MarcSabatella** [comment] 2024-01-14 21:04
This is currently by design - this dialog uses the hierarchical design found elsewhere as well where Tab moves between control groups but cursor keys move between individual controls.  It's a design subject to change, though - see for instance https://github.com/musescore/MuseScore/issues/20056 and https://github.com/musescore/MuseScore/issues/12851

**Comment by bkunda** [comment] 2024-01-16 14:13
Closing as this issue has already been described elsewhere.

**Closed by bkunda** 2024-01-16 14:13 UTC
Labels: UX/interaction
