### ISSUE TITLE
Bracket / Brace can't be removed with [Delete]; no UNDO possible; leads to crash (Linux only)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11883] opened 2022-06-03 15:41 UTC
**Describe the bug**

Clicking on a bracket and pressing [Del] should delete. But this doesn't work and leads to a crash.

**To Reproduce**

1. Create a guitar staff/tab score.
2. Click on measure one and click on a bracket in the Brackets palette.
3. Click once on the bracket/brace and press [Del]
RESULT: Nothing happens (can crash at this time)
4. Click on the brace/bracket one or more times
RESULT: The program crashes.

**Expected behavior**

Pressing Delete should immediately remove the bracket/brace.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2432394363, revision: github-musescore-musescore-1ff2049
Doesn't occur on **Win** and **Mac**

**Comment by Tantacrul** [comment] 2022-06-06 20:53
Won't reproduce on Mac. (I'm using backspace to delete the bracket and brace, if that's useful to know).

@DmitryArefiev - can you reproduce?

**Comment by RomanPudashkin** [comment] 2022-06-06 21:23
@Tantacrul I can reproduce it

**Comment by DmitryArefiev** [comment] 2022-06-07 13:20
Oh.. @RomanPudashkin told me the secret and now I can reproduce it on all platforms. You need to use trackpad (not a mouse) and delete bracket from context menu

**Comment by DmitryArefiev** [comment] 2022-06-10 12:21
#11917 fixed related bug on Win and Mac with a little bit different steps.

The current issue is still occurs. But it's Linux only issue. I'll modify summary and description a little bit

**Comment by wizofaus** [comment] 2022-06-19 06:51
Was able to crash it running under Visual Studio on Windows. Again related to AccessibleRoot::m_focusedElement pointing to a deleted object, which leads to undefined behaviour.  While there are two PRs already that may prevent this from crashing, they won't prevent undefined behaviour, as neither prevent dereferencing m_focusedElement when it's pointing at a deleted object.

>	MuseScore4.exe!deto::async::AbstractInvoker::invoke(int type, const deto::async::NotifyData & data) Line 30	C++
 	MuseScore4.exe!deto::async::Channel<enum mu::accessibility::IAccessible::State,bool>::send(const mu::accessibility::IAccessible::State & <d_0>, const bool & <d_1>) Line 32	C++
 	MuseScore4.exe!mu::engraving::AccessibleItem::notifyAboutFocus() Line 106	C++
 	MuseScore4.exe!mu::engraving::AccessibleRoot::setFocusedElement(mu::engraving::AccessibleItem * e) Line 61	C++
 	MuseScore4.exe!mu::engraving::EngravingItem::setSelected() Line 2739	C++
 	MuseScore4.exe!mu::engraving::Selection::update() Line 714	C++
 	MuseScore4.exe!mu::engraving::Selection::add() Line 470	C++
 	MuseScore4.exe!mu::engraving::Score::selectSingle() Line 3348	C++
 	MuseScore4.exe!mu::engraving::Score::select() Line 3326	C++
 	MuseScore4.exe!mu::notation::NotationInteraction::doSelect(const std::vector<mu::engraving::EngravingItem *,std::allocator<mu::engraving::EngravingItem *>> & elements, mu::engraving::SelectType type, unsigned __int64 staffIndex) Line 719	C++
 	MuseScore4.exe!mu::notation::NotationInteraction::select(const std::vector<mu::engraving::EngravingItem *,std::allocator<mu::engraving::EngravingItem *>> & elements, mu::engraving::SelectType type, unsigned __int64 staffIndex) Line 669	C++
 	MuseScore4.exe!mu::notation::NotationViewInputController::mousePressEvent(QMouseEvent * event) Line 522	C++
 	MuseScore4.exe!mu::notation::NotationPaintView::mousePressEvent(QMouseEvent * event) Line 906	C++

**Comment by DmitryArefiev** [comment] 2022-08-08 09:25
Fixed in #12697

**Closed** 2022-08-08 09:28 UTC
Labels: P0

**Comment by DmitryArefiev** [comment] 2022-11-21 14:00
@rgreen5 Can you recheck this crash on **Linux Mint** using the build from https://github.com/musescore/MuseScore/actions/runs/3490099320 please?

We have some changes in that PR related to #11883.  I was not able to reproduce the crash on my Linux, but I have only **Ubuntu**.

Thanks you!
