### ISSUE TITLE
Italics in the Header 

### ISSUE THREAD

**Issue by mattbazile** [musescore/MuseScore#24339] opened 2024-08-31 05:44 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

I can no longer get have sections of text in italics in the footer or header. Normally if you enclosed text with <i> and </i>, that text within the footer or header would be italicized. However, ever since I updated to Musescore 4.4, all the scores where I had italicized text within my footer is longer italicized and the italics demarcations show up as part of the text:
  

### Supporting files, videos and screenshots

<img width="654" alt="Screenshot 2024-08-30 at 10 42 09 PM" src="https://github.com/user-attachments/assets/f32051cf-9a53-4ed3-b4d7-236bf354df1d">

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-31 06:22
Duplicate of https://github.com/musescore/MuseScore/issues/24254

**Closed by oktophonie** 2024-08-31 06:22 UTC
Labels: regression MS4, engraving
