### ISSUE TITLE
Bar properties/ Play count and Repeat signs does not work properly in MS4.

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#20383] opened 2023-12-09 11:21 UTC
### Issue type

General playback bug

### Bug description

Hello,  If we increase the "play count" in the bar properties, the right (end) repeat sign does not work properly in MS4. (I haven't tried other signs)

### Steps to reproduce

1- Create a new score.
2- Enter 4 measures of notes
3- put a right repeat sign on the second measure
4- Increasing the number "play count" from "bar properties"

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/35005568/70a794ff-f7f4-4941-a7b2-4108ea8bdff5

### MuseScore Version

4.1.1,   4.2.0-testing

### Regression

I don't know

### Operating system

Windows 10, Linux Mint 21.1 Cinnamon

**Comment by ShibuyaCyana** [comment] 2023-12-09 11:49
For now a pair of repeat sign is needed for it to work:
![image](https://github.com/musescore/MuseScore/assets/39703247/538bb7c8-58c1-45d3-a0c8-d8cfb75cb4c8)
Not sure if this will be treated as a bug, but for now you can add one in bar 1 then make it invisible.

**Comment by Jojo-Schmitz** [comment] 2023-12-09 12:13
I can't reproduce, works for me
And in the above video it works for you too: it plays 3 times

**Comment by orkuun** [comment] 2023-12-09 12:41
Yes, it repeats 3 times but it doesn't play the correct notes.

**Comment by Jojo-Schmitz** [comment] 2023-12-09 12:45
Ah, I see, or rather hear.

**Comment by Jojo-Schmitz** [comment] 2023-12-09 12:46
So it is a duplicate of #15112

**Comment by orkuun** [comment] 2023-12-09 12:50
Opps, sorry I couldn't find it. I'm closed it

**Closed** 2023-12-09 14:37 UTC
Labels: playback
