### ISSUE TITLE
Chord symbols do not display correctly in parts when a custom score style is set

### ISSUE THREAD

**Issue by bmacs001** [musescore/MuseScore#20991] opened 2024-01-12 19:23 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

This is a repeat of issue #19830; unlike the person who posted there, resetting to factory settings did not fix the problem. When a custom style is set in Preferences > Score, either Style or Style for Part, and a custom Styles folder is set, the chord symbol rendering styles are not recognized upon opening a score's parts. No matter if standard or jazz chord rendering or a custom renderer has already been chosen for the part, only a broken version of standard chords will render: for any chord symbol with a suffix like m or dim, the first part of the chord name doesn't appear in a score's parts (including both the note name and whether it's flat or sharp). This is temporarily fixed by changing the chord renderer, but closing and reopening the document doesn't preserve the fix. This only occurs in parts, and does not occur in the full score. The file structure between parts and the full score are identical.

### Steps to reproduce

-Open a factory default version of MS
-In Preferences > Folders, select a new folder for Styles.
-Reopen MS, and allow the folder to populate
-Set a default style in Preferences > Score either in the full score or in parts. Using a file with no content within the Style tag, a file full of tags but with factory default settings, and a file pulled from MS's templates all reproduce the issue
-Create a score, add chord symbols, open the part of the instrument with chord symbols.

Reverting to the default folder (in my case, /Users/(me)/Documents/Styles) does not undo this bug

### Screenshots/Screen recordings

[Screen Recording 2024-01-12 at 14.46.19.zip](https://github.com/musescore/MuseScore/files/13923373/Screen.Recording.2024-01-12.at.14.46.19.zip)

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.2.1

**Comment by MarcSabatella** [comment] 2024-01-12 19:38
I have opened your score in 4.2 and don't see any issue offhand.  All chords I see on both score and parts look normal. 
 What steps should I follow to reproduce the problem after loading your score?  Do I need to select a particular measure of a particular staff or a particular part and add a particular chord, then save and reload again, in order for the problem to appear?  I tried adding another Am chord to the piano staff in the score, save, reload - all is well.

**Comment by bmacs001** [comment] 2024-01-12 19:43
The problem isn't as complex as that, though if it's working fine on your system it might be something screwy with my setup. I've updated the steps to reproduce above. For clarification, I've double checked the file structure and the xml tree is identical between parts that work and parts that don't, so sharing a file likely won't be any help.

**Comment by MarcSabatella** [comment] 2024-01-12 20:29
Based on your video, something is definitely wrong with your installation.  You are sure you did Help / Revert to factory settings, and made no other changes to settings since then?  Based on what I see here, it looks like somehow your parts are using a bad chord description file - like if you had a custom MSS file specified for parts in Edit / Preferences / Score, and that file contained a pointer to a bogus chord description file.

Try the "Help / Revert to factory settings" again, and then uninstall / resintall MuseScore, and see if the problem still persists.

**Comment by MarcSabatella** [comment] 2024-01-12 20:34
This definitely sounds like a missing or damaged or otherwise bad chord description file.  Can you attach the chords_std.xml and chord_jazz.xml files from your application packages?  I don't know enough about macOS internals to tell you exactly how to find them, but I think they would normally be in the styles subfolder.

**Comment by bmacs001** [comment] 2024-01-12 20:44
[Chord xmls.zip](https://github.com/musescore/MuseScore/files/13923899/Chord.xmls.zip)

**Comment by MarcSabatella** [comment] 2024-01-12 21:40
There are tons of Mac users, and I've only seen this reported once or twice.  So almost certainly definitely something unusual about your setup.  If I had to guess, I'd say maybe it has to do with folder permissions, language settings, custom install locations, or something like that.  MuseScore certainly always looks for the chord description file upon score creation, but I'm guessing it's just failing for some unknown reason - and only for parts, not for score, which is what makes me think it is somehow connected to the default settings in Edit / Preferences / Score.

I'd encourage you to ask for help on the official Support forum and include as much detail as you can - not so much about the symptoms, which are clear enough, but about anything possibly unique about your system configuration.

**Comment by bmacs001** [comment] 2024-01-12 22:21
Ok, so you're right, it has something to do with having a custom style file, either in the full score or in the parts. The specifics of the file itself have nothing to do with it; I saved the style at factory default, and styles embedded in the score templates, and it broke there as well.

**Comment by MarcSabatella** [comment] 2024-01-12 22:28
I'm still confused, though.  You confirmed you did the Help / Revert to factory settings, and that you made no other setting changes after that.  Did you mean, you actually exported a custom style file and set that as the style for the score and/or the parts in Edit / Preferences / Score, but that this file contained no actual customizations?  Please, list the *exact* steps to reproduce this problem, starting with:

1. Help / Revert to factory settings
2. ...

**Comment by bmacs001** [comment] 2024-01-12 23:03
I installed a fresh version of MS on a new account and I discovered it was the double whammy of a custom styles file and a designated styles folder. Funny how doing bug checking the right way actually gets to the heart of the issue (sorry about that!)

**Comment by MarcSabatella** [comment] 2024-01-13 00:50
Thanks for the further investigation!  This makes sense; something about how these customizations are set up is leading MuseScore to not be able to find the chords_std.xml file.  I think, though, that changing the style folder is a red herring - I am able to reproduce the problem even when only defining a custom style for parts, no other changes.  Steps as follows:

1. Create a new score with all defaults
2. Format / Save style, save as MU4.mss
3. Edit / Preferences / Score
4. Set the default style for parts to this MU4.mss
5. Quit/restart MuseScore
6. New score, treble template
7. Add chord symbol Am to bar 1
8. Parts, open all

Result: the root of the "Am" chord is missing - you see just "m"

It only happens with the a custom *parts* style - if in step 4 you instead set a score *score* style, there is no bug.  So somehow the code for initializing the part styles isn't successfully the chord description file in cases where a custom style is defined.

My guess then is we just need to call checkChordList() in the "if" block of this code:

https://github.com/musescore/MuseScore/blame/698d0704e9262b0b70d8b84fa1b6e875669a5a62/src/engraving/dom/score.cpp#L179-L185

**Comment by Jojo-Schmitz** [comment] 2024-02-03 11:43
Then #21348 should fix this.

**Comment by Jojo-Schmitz** [comment] 2024-04-06 14:20
@MarcSabatella Actually that doesn't seem to fix the issue, at least not with this score
[ILikeTheFlowersLEAD.zip](https://github.com/musescore/MuseScore/files/14893843/ILikeTheFlowersLEAD.zip)

**Comment by MarcSabatella** [comment] 2024-04-07 15:52
Unfortunately I don't have a current build system and can't try things out on my own right now.  But does my suggestion at least fix the case I specifically described above with the steps to reproduce from scratch?  The score you attached may well have a separate issue.  Also, what if you you do it the way I suggested rather than factoring it out?  This could be order-dependent.

**Comment by Jojo-Schmitz** [comment] 2024-04-07 17:20
Hmm here it is not the root that is missing, but the flats being shown as "266d"
Switching from custom style to normal and back solves it

**Comment by Jojo-Schmitz** [comment] 2024-04-07 17:22
But let me try your scenario, and un-draft the PR if that is fixed...

**Comment by Jojo-Schmitz** [comment] 2024-04-07 17:54
Yes, it fixes that scenario

**Comment by Jojo-Schmitz** [comment] 2024-04-07 18:03
The other is is the one from https://github.com/musescore/MuseScore/issues/16363
Only the score doesn't show any eveidence having been imported from XML

**Comment by MarcSabatella** [comment] 2024-04-08 16:16
Great, then I'd consider the PR a fix for this issue.  The one with the 266d would also happen, from what I understand, any time there was a custom chord symbol description file (XML) embedded within the score.  So, not necessarily about MusicXML import - it's about custom chord symbols definitions.  I think that might include files imported from MuseScore 1 and then re-saved, but I'm not really sure.

**Comment by Jojo-Schmitz** [comment] 2024-04-08 19:28
Yes, IIRC Mu1 scores always contained the full chord descriptions

**Comment by tommy-banana** [comment] 2024-06-02 18:57
I have exact same issue. Having any .mss file set as default for parts - even if the custom style has no changes from default style , breaks chord symbol display. Sorry I didn't find this before opening a new issue!

**Comment by Jojo-Schmitz** [comment] 2024-06-03 14:49
Can you try whether the artifacts from #21348 solve it for you?

**Comment by tommy-banana** [comment] 2024-06-03 16:26
NB I am familiar with Github and coding javascript VSCode...

**Comment by cbjeukendrup** [comment] 2024-06-03 16:28
No worries! We have some documentation here: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests

**Comment by tommy-banana** [comment] 2024-06-03 16:35
Got it . Will give it a try! Exciting!

**Comment by tommy-banana** [comment] 2024-06-03 16:42
Yes bug is fixed! Thankyou and congrats! Should we meet for a drink?

**Closed** 2024-06-22 12:56 UTC
Labels: P2, engraving, regression_ms3
