### ISSUE TITLE
Key signature disappears from standard staff after switching to tab staff and back

### ISSUE THREAD

**Issue by mikekirin** [musescore/MuseScore#18005] opened 2023-06-15 16:30 UTC
### Issue type

Engraving bug

### Bug description

See the title

### Steps to reproduce

1. Open any score with key signature other than C or Am.
2. Change staff type to tab
3. Change staff type back to standard

### Screenshots/Screen recordings

<img width="660" alt="image" src="https://github.com/musescore/MuseScore/assets/16940972/de9dd8dc-c896-4a96-949a-f0e9814fcb22">
<img width="649" alt="image" src="https://github.com/musescore/MuseScore/assets/16940972/71c8ba8d-4e84-4c20-9d4c-66e33d8abbc8">
<img width="609" alt="image" src="https://github.com/musescore/MuseScore/assets/16940972/3d73ca89-25c9-4e12-bda6-f96692e4823c">

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

all

**Comment by sammik** [comment] 2023-06-16 05:33
similar issue reported here #17479

**Comment by abariska** [comment] 2023-06-16 06:02
Duplicate of https://github.com/musescore/MuseScore/issues/17479

**Closed by abariska** 2023-06-16 06:02 UTC
Labels: duplicate, engraving
