### ISSUE TITLE
[MU4 Issue] Staff restarts playback from start position automatically after a change

### ISSUE THREAD

**Issue by pmarx810** [musescore/MuseScore#14902] opened 2022-12-02 23:09 UTC
When I change the sound of a staff during playback, the rest of the parts continue playback, but the changed staff restarts from where the initial starting position was.

1. Have notation present in multiple parts
2. Start playback
3. Change the sound of one part without pausing playback

Expected Behavior:
Changed part continues playback with the rest of the parts

 - OS: Windows 10
 - Dec 2nd Nightly

**Comment by hglr24** [comment] 2023-04-29 23:43
To simplify this issue a bit, you don't even need multiple parts for the issue to present itself. With only one part, changing its `Sound` in the Mixer during playback restarts from the initial playback position while the playback progress marker on the staff continues forward

**Comment by RomanPudashkin** [comment] 2024-04-25 08:33
Looks like this should have been fixed by https://github.com/musescore/MuseScore/pull/20626. @pmarx810 please reopen if you can still reproduce it

**Closed by RomanPudashkin** 2024-04-25 08:33 UTC
Labels: P2, playback
