### ISSUE TITLE
[MU4 Issue] Color Notes - In a chord/interval, instead of changing the color of a singe note, it changes the whole chord/interval

### ISSUE THREAD

**Issue by RotoBanana** [musescore/MuseScore#16113] opened 2023-01-28 16:40 UTC
**Describe the bug**
In a chord/interval, instead of changing the color of a single note, it changes the whole chord/interval.

**To Reproduce**
1. Enable the Color Notes plugin
2. Click on a note, in a chord/interval
3. Click on Appearance
4. Change the color of the note

**Expected behavior**
A single note will change it's color, only.

**Screenshots**
https://user-images.githubusercontent.com/62190339/215278214-dbd06ba9-fb40-4af8-b26b-0b4c0aaa7795.mp4

**Platform information**
 - Windows 10

**Comment by oktophonie** [comment] 2023-01-28 16:42
Duplicate of https://github.com/musescore/MuseScore/issues/11096
Fix in 4.0.2

**Closed by oktophonie** 2023-01-28 16:42 UTC
