### ISSUE TITLE
[MU4 Issue] Play panel incorrect position

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#12628] opened 2022-08-01 11:28 UTC
**Describe the bug**
Parts and Mixer buttons are not centred, and between the play panel and the undo/redo buttons is a big gap. Unless undock then dock again it is then corrected. 

![image](https://user-images.githubusercontent.com/71656189/182138852-f6eaa22e-81aa-4e26-8820-9b1c1b3238bb.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open latest nightly build
2. Open or create new score
3. See error on top right

**Expected behaviour**
Shown in attached video how it should be displayed after I re-docked the play panel

https://user-images.githubusercontent.com/71656189/182138280-2b79e11a-8232-49ba-83dc-a81d37c5b5d1.mp4

**Platform information**
 - OS: Windows (not sure on mac yet)

**Comment by Eism** [comment] 2022-08-01 11:31
duplicate of #12421

**Closed** 2022-08-01 11:31 UTC
Labels: P2
