### ISSUE TITLE
[MU4 Issue] Backspace not working; only deletes last note

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12275] opened 2022-07-05 11:21 UTC
**Describe the bug**
In MS3, backspace will successively delete all notes entered in the current session. However, in the MS4 nightly it is only deleting the last entered note.

**To Reproduce**
1. In note input mode, enter a run of notes
2. Now click [Backspace] repeatedly

RESULT: Only the last note is deleted.

**Expected behavior**

All notes entered in the current session should be able to be deleted (as in MS3).

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2613746296, revision: github-musescore-musescore-b70aa9b

**Comment by MarcSabatella** [comment] 2022-07-05 13:14
This is a duplicate of https://github.com/musescore/MuseScore/issues/9188

Note that as per my comment there, in MU3, Backspace actually just did an Undo - it only happened to look like a deletion if the last thing you was add a note.  Undo is still available of course.  Now, Backspace just does Delete.  Eventually it would be good to finally have a *real* backspace command - delete and move cursor backwards.  But that would be new functionality; it's not what MU3 did/

**Closed** 2022-07-06 11:57 UTC
