### ISSUE TITLE
Concurrent notes playback bugged

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#16675] opened 2023-03-06 11:55 UTC
### Issue type

Muse Sounds bug

### Bug description

Musesounds will not play one pitch multiple times concurrently on one instrument. Affects probably all musesounds instruments. Rhythm seems to matter.

### Steps to reproduce

1. Input one pitch multiple times through different voices or grand staff
2. Play

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/120669196/223102305-63b41864-38da-45f6-a175-b9c1a3078e4a.mp4

https://user-images.githubusercontent.com/120669196/223098521-249370f3-d4bc-404e-b669-27cf81b3fbe2.mp4

https://user-images.githubusercontent.com/120669196/223099849-11cb05fd-c689-4164-a6f0-446645509faf.mp4

### MuseScore Version

4.0.1-230121751

### Regression

Choose option...

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2023-03-06 12:26
This looks like a duplicate of #15306. Thanks for reporting anyway!

**Closed by cbjeukendrup** 2023-03-06 12:26 UTC
Labels: muse sounds
