### ISSUE TITLE
[MU4 Task] [GP] Display slides correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10316] opened 2022-01-19 13:28 UTC
**Task description**
Slides to/from note are shown a bit big and far from note

**Current state:**
![Screenshot 2022-01-19 at 16 26 15](https://user-images.githubusercontent.com/24373905/150139744-79a1072a-547d-4ca7-97c7-0a035f94e70e.png)

**Expected:**
![Screenshot 2022-01-19 at 16 25 55](https://user-images.githubusercontent.com/24373905/150139710-efbd2372-c465-45dd-8427-a26753bb45df.png)

**Comment by oktophonie** [comment] 2022-06-07 12:59
I feel like these slides ought to match the positioning of a glissando line between notes a third apart:
![image](https://user-images.githubusercontent.com/20604032/172385268-0d9c9f37-4347-477c-ade8-3502a7370985.png)

The side of the slide that is attached to the note has a fixed position (and moves if the note is moved); this should match that of the glissando. The 'free' end can be manually adjusted, but by default it should match the equivalent vertical position of a glissando line starting a third away from the destination note. The horizontal distance between the two endpoints should also be shorter (I'd suggest 1.5sp).

**Comment by boryskuzmenko** [comment] 2022-06-16 13:24
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12011
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by alexpavlov96** [comment] 2022-06-17 12:04
Still needs fix for import from guitar pro (remove especially created class "Slide" and use the "ChordLine" for import, but take care of slide for each note in the chord)

**Comment by mike-spa** [comment] 2022-06-17 12:15
> Still needs fix for import from guitar pro (remove especially created class "Slide" and use the "ChordLine" for import, but take care of slide for each note in the chord) - I'm doing it

**Yes**, I knew this would come up at some point, so I'm actually glad you brought it up. I agree that the `Slide` class should be removed and we should just use the `ChordLine`. The main problem with ChordLine is that, as the name suggests, it can only be attached to chords. Why _on earth_ it was done this way, I honestly have no idea, to me it is completely obvious that these kind of lines should be attached to the individual notes. Now the problem is that in our code base probably the most consequential property of each object is its `parent`. Changing the parent of ChordLine from `Chord` to `Note` requires to change almost every single instance that the ChordLine is used. It is a lot of work, but I already have a working branch where I have done some of that, before giving up. So I can take care of this, if that's ok for you

**Comment by mike-spa** [comment] 2022-06-17 12:19
@alexpavlov96  Ah I see now you said you are already working on it, sorry! Let me know what you prefer, and you know where to find me if needed :)

**Comment by boryskuzmenko** [comment] 2022-06-22 16:09
🟢 **Possibility to add a slide for each note in chord is FIXED** in https://github.com/musescore/MuseScore/pull/12088
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by boryskuzmenko** [comment] 2022-06-28 10:48
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12139
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by DmitryArefiev** [comment] 2022-06-30 10:51
> Still needs fix for import from guitar pro (remove especially created class "Slide" and use the "ChordLine" for import, but take care of slide for each note in the chord) - I'm doing it

This fixed in #12139

**Closed** 2022-06-30 11:52 UTC
Labels: P1
