### ISSUE TITLE
[MU4 Issue] Clef collides with time signature

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#15737] opened 2023-01-06 19:13 UTC
**Describe the bug**
If you try to change clef right after time signature, it appears behind signature (look at screenshot)
Works correct in musescore 3.6.2

**To Reproduce**
1. Create a score with time signature
2. Add another clef right after time signature (drag & drop new clef to the rest sign)

**Expected behavior**
Clef should appear after time signature. 

**Screenshots**
![image](https://user-images.githubusercontent.com/919446/211082858-a969ec8f-b45c-42bb-8067-55f35703bd15.png)

real scores example:
![image](https://user-images.githubusercontent.com/919446/211082917-119b4258-69dc-4edb-9e2d-cc36d7af4e59.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by oktophonie** [comment] 2023-01-06 19:35
Closing as duplicate of https://github.com/musescore/MuseScore/issues/14610
This was fixed in https://github.com/musescore/MuseScore/pull/14721 so will work as expected in builds of the master branch, and will be in the next release.

**Closed by oktophonie** 2023-01-06 19:35 UTC
