### ISSUE TITLE
Some third party VST's doesn't detect musescore off - on pedal

### ISSUE THREAD

**Issue by Philip4dk** [musescore/MuseScore#21353] opened 2024-02-04 00:58 UTC
### Your idea

Make the off - on a bit slower for better compatibility with more VST's 

### Problem to be solved

Too fast pedal changes

### Additional context

I'm using pianoteq VST

**Comment by ThePython10110** [comment] 2024-02-11 00:43
I'm pretty sure this also applies to Vital Synth.

**Comment by RomanPudashkin** [comment] 2024-07-29 10:05
Duplicate of https://github.com/musescore/MuseScore/issues/22910

**Closed by RomanPudashkin** 2024-07-29 10:05 UTC
Labels: feature request, needs design, VST
