### ISSUE TITLE
Implement cross-staff chords.

### ISSUE THREAD

**Issue by luis-j** [musescore/MuseScore#19172] opened 2023-08-25 21:40 UTC
### Your idea

Implement cross-staff chords.

### Problem to be solved

MuseScore lacks implementation for cross-staff chords, that have been part of standard piano music notation for at least 200 years (see attached facsimile of the beginning of Chopin's piano sonata nº3); for at least 50 years they have also been used in other context like ensemble music (e.g. Xenakis).
The existing "workaround" is an inconvenient and time-consuming hack that breaks with any modification of the score.

### Prior art

![Captura de pantalla_2023-08-25_17-53-23](https://github.com/musescore/MuseScore/assets/12549684/86cd0f62-2164-47bc-b7c2-1b820a53e5b3)

### Additional context

The request for this basic feature has been recurring over the years, I think it deserves high priority,

**Comment by cbjeukendrup** [comment] 2023-08-25 21:47
Duplicate of https://github.com/musescore/MuseScore/issues/15544

**Closed by cbjeukendrup** 2023-08-25 21:47 UTC
Labels: feature request
