### ISSUE TITLE
Ability to delete scores from the Home tab

### ISSUE THREAD

**Issue by Beniegenie** [musescore/MuseScore#18997] opened 2023-08-09 22:06 UTC
### Your idea

I think it would be a good idea to be able to delete cloud scores with MuseScore 4.

### Problem to be solved

If you delete a cloud score you can still see the score in the program, but you can't use it.
<img width="1280" alt="Screen Shot 2023-08-09 at 6 04 45 PM" src="https://github.com/musescore/MuseScore/assets/136394533/9c7d7e92-4a19-4822-9a96-38caee41ec3f">

### Additional context

The four scores in the middle of the screenshot are all the same score, which is very confusing.

**Comment by cbjeukendrup** [comment] 2023-08-09 22:30
May I interpret this as a duplicate of #13839 (see especially the last comment there)? Or is that not entirely what you mean?

**Comment by Beniegenie** [comment] 2023-08-09 22:46
@cbjeukendrup Similar, but I wasn't not sure if I was able to bring up another issue within this one. The reason I had so many of one score is because I couldn't change the name of a cloud score file. Because that score was an original it was named after the file, and I messed up the capitalization in the name. I also don't like the fact that there are no more files saved to your computer, when you save to the cloud, which, though it's useful for saving computer space, has its issues when you don't have internet. Before, when the files were saved to the computer and the cloud, I was able to rename the file.

**Comment by mmeyn** [comment] 2023-08-10 06:04
In addition to solving the cloud problem described above, it might be nice to remove existing files from the view (without deleting them) like it is f. e. in LibreOffice:
![grafik](https://github.com/musescore/MuseScore/assets/7814361/766126fa-d435-41c3-910f-ea8864c02088)
When hovering over a document in the “last used” view on the LibreOffice start page, there is an X button which doesn’t delete the file but simply removes it from the “last used” list and view.

**Comment by iwoithe** [comment] 2023-08-10 10:21
> In addition to solving the cloud problem described above, it might be nice to remove existing files from the view (without deleting them)

See https://github.com/musescore/MuseScore/issues/11235 and https://github.com/musescore/MuseScore/pull/16507.

**Comment by mmeyn** [comment] 2023-08-10 11:13
Sorry, I was not aware of that. It looks promising :)

**Closed** 2023-08-11 13:08 UTC
Labels: duplicate, feature request
