### ISSUE TITLE
[MU4 Issue] Regression: Insert/Append multiple measures dialog doesn't work as well with Enter key

### ISSUE THREAD

**Issue by WHS241** [musescore/MuseScore#15722] opened 2023-01-05 14:14 UTC
**Describe the bug**
Pressing Enter after specifying how many measures to insert/append does not work as well as MuseScore 3.

**To Reproduce**
1. Select a measure and insert/append multiple measures (Ctrl+Ins, Alt+Shift+B, or via the menu options).
2. Type in a number of measures to insert/append (or leave at 1).
3. Press the Enter key.
4. Nothing happens. Instead, I have to press Tab to switch to the OK button first.

**Expected behavior**
In MuseScore 3 and earlier, pressing the Enter key while still in the number box would have inserted/appended the specified measures and quit the popup, much like clicking on "OK" would.

**Platform information**
 - Linux

**Additional context**
https://musescore.org/en/node/338722

**Comment by cbjeukendrup** [comment] 2023-01-05 15:18
Duplicate of #12222. Thanks for reporting!

**Closed by cbjeukendrup** 2023-01-05 15:18 UTC
