### ISSUE TITLE
[MU4 Issue] SoundFont Over Sustain Issue

### ISSUE THREAD

**Issue by SkyJTx** [musescore/MuseScore#15256] opened 2022-12-17 03:22 UTC
**Describe the bug**
When I choose any SoundFont and start playing, the sound of the instrument becomes overly sustained, especially keyboard instruments like Harpsichord, Piano, and others.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Mixer'
2. Click on 'Sound'
3. Click on 'SoundFont'
4. Click on any 'SoundFont' you choose (keyboard recommend)
5. Play

**Expected behaviour**
It should be played less sustain or become quieter when the note is held. Like in MU3

**Screenshots**
-

**Platform information**
 - OS: Windows 11

**Additional context**
This only happen when I used SoundFont. Muse Sound is fine.

**Comment by zacjansheski** [comment] 2023-07-27 15:22
Is this still actual?  (I am unable to reproduce)

**Comment by zacjansheski** [comment] 2023-08-16 16:39
Closing

**Closed by zacjansheski** 2023-08-16 16:39 UTC
Labels: needs info
