### ISSUE TITLE
[MU4 Issue] Grand staff barlines not connected when inserted in score w/ multiple instruments

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#15006] opened 2022-12-07 04:56 UTC
**Describe the bug**
Instruments that use grand staves (e.g. piano, harp) have their barlines not connected to each other when score has multiple instruments involved.

**To Reproduce**
1. Go to _New Score_.
2. Insert multiple instruments w/ at least one instrument that uses a grand staff
3. Complete score creation as of liking

**Expected behavior**
Grand staff barlines should be conjoined in this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/90231404/206091277-c84b9ba3-82e4-4e8a-82ba-7bf074468f8c.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223410309, revision: github-musescore-musescore-c26899b

**Additional context**
- Otherwise, this doesn't occur when the instruments in question are inserted _after_ the score is created.
- I'm surprised this is not logged yet (or at least, I can't find any logged issues related to this) since I've observed this since the alpha release, but I assume this must be already known. I'll anyhow log this in just in case. Close if duplicate or unnecessary.

**Comment by oktophonie** [comment] 2022-12-07 08:02
Good catch, and an unpleasant regression on 3.6

Weirdly it happens only in some combinations but not others, which is probably how it's escaped notice. This is a simple case where the problem occurs:
![image](https://user-images.githubusercontent.com/20604032/206121357-cb461cae-2185-441f-8800-df4ff92a8743.png)

Whereas this (for example) works fine:
![image](https://user-images.githubusercontent.com/20604032/206121546-43bcebf8-269e-47aa-9d8a-fc72a405f331.png)

**Comment by Tantacrul** [comment] 2022-12-08 17:30
Unfortunately, @vpereverzev says this one is risky to add now, since we don't have any time to test possible repercussions. 

Going to have to move it to Post Release. I'll test it later tonight and it'll get merged to Master a little after if there are no issues.

Sorry!

**Comment by mike-spa** [comment] 2022-12-09 08:31
@Tantacrul @vpereverzev the PR I had previously linked was larger because it also contained another fix I'd previosly done (I had put them together cause they both had to do with brackets and barline extensions). Now I've moved the solution of this to its own separate PR #15067 which is very small. This may not change the judgement of the risk to merge (in fact, we can't tell with 100% certainty if something else didn't depend on the behaviour of those 3 lines of code that were causing this issue). Just thought I'd update you here

**Closed** 2022-12-13 10:01 UTC
Labels: P1

**Comment by cgpqci** [comment] 2022-12-15 01:46
Sorry to comment again, but I think the bug still persists(?)

![image](https://user-images.githubusercontent.com/90231404/207751981-d04b8bbb-4220-470b-9574-06edac5c64e0.png)

I don't know if this issue's meant to be closed for documentation for a post-release fix or the pull request really meant to eradicate this bug, but either how, as you can see, it's still present.

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by mike-spa** [comment] 2022-12-15 08:58
This fix didn't make it into the release, unfortunately, so if you are using the final 4.0 release it is expected that the bug is still there. However, the fix has already been merged into master, which means it will be in the next 4.0.x release, which we are expecting to do very soon (likely few weeks). In fact, would be great if you can check the latest master build (you can download it from the top of the list here https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D) and confirm it is fixed :)

**Comment by cgpqci** [comment] 2022-12-17 08:05
Checked it on the latest nightly and it is indeed fixed. Mistake on my part, then. 😅 Thank you, anyhow!
