### ISSUE TITLE
Incorrect resizing of textboxes

### ISSUE THREAD

**Issue by DominAbbus** [musescore/MuseScore#24608] opened 2024-09-10 08:42 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

New score, Tenor Sax, 4/4, C-major, (sax has 2 sharps)
Select the title (outline highlighted)
At the horizontal position of the 2 sharps, drag down the bottom edge of the title box
The text box enlarges much quicker than the mouse-cursor
Moving the mouse-cursor back up (while still dragging) keeps enlarging the textbox.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/577315b3-5aa4-4a96-a9fc-513eaa1fe3ba

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

The bug seems to be intermittent, But this is one way I found I could reproduce it systematically.
Hope this helps.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment] 2024-09-11 16:53
This looks like a regression between 4.4.0 and 4.4.1

In 4.3.2, you need to select the box to resize
In 4.4.0 you can resize form anywhere but it doesn't jump off the screen
In 4.4.1 text box resizes uncontrollably


https://github.com/user-attachments/assets/4600f143-a0e6-412d-ba84-d23a0e3e522d

**Comment by bkunda** [comment] 2024-09-12 08:47
Moving to 4.4.3 because we've run out of time for 4.4.2. 

It seems this is only reproducible if you attempt to resize the text field from any position other than the grip handle (which is by far the most common thing to do at any rate, and thankfully this still works as expected).

**Comment by Eism** [comment] 2024-09-12 13:11
was broken after these changes https://github.com/musescore/MuseScore/pull/24265/files#diff-7d6c43a2a0b297c944ac7ab8b3fb364815a25bc9cd7f8c132e1f3725cd6bf0b3R720

**Comment by bkunda** [comment] 2024-10-07 09:07
I'm still reproducing this bug reliably on Win. What's most alarming is that resizing via this means does not seem to be undoable. 

I'd say it's still probably a P2 though: the problem can be corrected by manually resizing the text field via the grip handle (so it's not destructive), and the fact that it only reproduces when resizing without the grip handle makes it less likely to occur.

**Closed** 2024-10-09 07:23 UTC
Labels: P2, regression MS4, UX/interaction
