### ISSUE TITLE
[MU4 Issue] Dock button and Note Input button are too far apart

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9682] opened 2021-11-09 16:56 UTC
**Describe the bug**
It's creating fairly big horizontal space. Only needs 2 pixels between the buttons instead of 7

**Expected behavior**
![image](https://user-images.githubusercontent.com/71656189/140969192-5f31f57a-7202-4bda-b4a8-57bad4833ebb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/71656189/140969213-9dc6d72c-9607-40bd-b2b1-6a9a81d2e3c0.png)

**Desktop (please complete the following information):**
 - OS: Mac and Windows

**Comment by cbjeukendrup** [comment] 2021-11-09 17:09
For technical reasons, there is an invisible separator line at the start of the note input bar, which is fine, but the problem is that there is still space allocated for it even though it is invisible. I solved this in PR #7899, but with that solution, the separators were not visible at all anymore with the new docking system (see comment https://github.com/musescore/MuseScore/pull/7899#discussion_r634575473), so that solution got reverted in https://github.com/musescore/MuseScore/commit/f1e9265b3dd45b4c1b444671d1eef97115cd9439#diff-6030549af85ee7469b1a91bec5b6cb2beb010639bc69ea7d6e8b79eabe8e92cdR38.

**Comment by Tantacrul** [comment] 2022-05-05 18:57
I think we should close this. It seems nice as is.

**Closed by Tantacrul** 2022-05-05 18:57 UTC
Labels: P3, UI finesse
