### ISSUE TITLE
Inconsistent voice of tie when switching voice of notes

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#19807] opened 2023-10-23 17:52 UTC
### Issue type

UI bug

### Bug description

When switching voices of the notes of a tie (without the tie itself being selected), the tie is not properly updated.

It *looks* like this doesn't cause any further issues; but it's an inconsistent state. As such, I wouldn't be surprised if it causes file corruption or other problems.

### Steps to reproduce

1. Create two notes in a voice
2. Create a tie between the notes
3. While only the notes (and not the tie) is selected, change their voice (e.g. Ctrl-Alt-2)
4. Check which symbol on screen belongs to which voice

Expected behavior: The tie cannot exist by itself in a voice, therefore it must also be assigned to the new voice.

Actual behavior: The tie still belongs to the old voice, which I don't think makes any sense, as there is no note in that voice.

Note that this issue also occurs when the tie is also selected in Step 3.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/2690845/3165d2d8-b0b4-4046-b671-86eff4150864

### MuseScore Version

OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Debian Bookworm

### Additional context

Cannot provide a project file: Saving and loading fixes the voice assignment.
It seems like it always overrides the voice-assignment with whatever voice the starting note is in.

**Comment by oktophonie** [comment] 2023-10-24 07:19
Duplicate of https://github.com/musescore/MuseScore/issues/18546

**Closed by oktophonie** 2023-10-24 07:19 UTC
Labels: UI
