### ISSUE TITLE
[MU4 Issue] Crash on paste half duration

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11499] opened 2022-05-02 11:52 UTC
**Describe the bug**
Paste half duration can cause crash

**To Reproduce**
1. Create new score, e.g. basic treble clef template
2. Enter a few notes
3. Select the whole score and copy to clipboard
4. Click after the notes previously entered (in an empty measue)
5. Choose "Paste as half duration"
6. MuseScore crashes (if running in debugger, it's a divide by zero at line 128 of fraction.h)

**Expected behavior**
Not a crash

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

Will happen any time you have a full-measure rest in the selection copied to the clipboard.
The duration is of type "measure", which for some reason when converted to a fraction is 0/0, which can't be scaled.

**Comment by wizofaus** [comment] 2022-05-02 12:09
Changing canPasteStaff() in paste.cpp (a function I vaguely recall writing!) to

                auto fract = TDuration(TConv::fromXml(reader.readElementText(), DurationType::V_INVALID)).fraction();
                if (fract.denominator() != 0 && !TDuration(fract * scale).isValid()) {
                    return false;
                }

fixes it but not sure if it's the best fix - does it really make sense for TDuration(DurationType::V_MEASURE).fraction() to return an invalid 0/0 fraction?

**Comment by Tantacrul** [comment] 2022-05-02 13:28
Confirmed. Marked P0, since selecting the whole score and pasting is a likely user case for anyone who knows this feature.

**Comment by donarturo11** [comment] 2022-05-06 07:55
I propose do not close this issue yet because while trying paste entire score in half-value, yet crashes (SIGABRT signal). I'll yet check, where yet is any possibility of division by zero. Finally I'll try totally fix this issue.

**Comment by Tantacrul** [comment] 2022-05-06 08:02
Oh, there's no chance of this one being closed! Don't worry.

**Comment by DmitryArefiev** [comment] 2022-05-16 10:51
@wizofaus @Tantacrul Can you check it again please in master? I can't reproduce it now..

Tested in latest master on Win/Linux/Mac - **no crash**

**Closed** 2022-05-16 16:10 UTC
Labels: P0

**Comment by wizofaus** [comment] 2022-05-16 19:49
What was the PR that fixed it?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
