### ISSUE TITLE
MS4 repeatedly crashes when deleting a particular rest

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#18132] opened 2023-06-23 03:09 UTC
### Issue type

Choose option...

### Bug description

MuseScore 4 crashes when I try to delete a particular rest from the second voice in my score. The problem persists no matter how many times I restart MuseScore.

### Steps to reproduce

In the provided score, go to measure 64, and delete the C# in the second voice on the 'a' of beat 1. Then try to delete the quarter rest that appears in its place. MuseScore will crash.

[MuseScore project](https://github.com/musescore/MuseScore/files/11843550/score.zip)

### Screenshots/Screen recordings

The outcome is the same no matter how many times I reopen the file.

https://github.com/musescore/MuseScore/assets/73259774/da27c02e-d039-40ad-b0fd-55035f493bea

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

### Additional context

A workaround can be achieved by placing a whole rest at the beginning of the measure in the second voice, then deleting it.

**Comment by oktophonie** [comment] 2023-06-23 05:13
Duplicate of https://github.com/musescore/MuseScore/issues/17761, fixed in 4.1

(I wasn't able to test your specific score to make sure, as the contents of your .zip are in fact a PDF rather than a MuseScore file. If you test it yourself in a 4.1 build and find that there is still a problem, do let us know here.)

**Closed by oktophonie** 2023-06-23 05:13 UTC
Labels: duplicate

**Comment by Panogen** [comment] 2023-06-23 23:30
Sorry, I didn't think to check closed issues for a duplicate.
