### ISSUE TITLE
Expanding multibar rests causes a crash

### ISSUE THREAD

**Issue by basaigh** [musescore/MuseScore#21299] opened 2024-01-30 22:07 UTC
### Issue type

Crash or freeze

### Bug description

When expanding a relatively large multibar rest (17 or more bars in my case), MuseScore crashes instantly.
This only appears to occur on scores with music - tested with Muse Orchestra Demo and a personal score - whereas on empty scores it appears to be stable.

### Steps to reproduce

1. Open a pre-populated score.
2. Add bars to the end of the score.
3. Collapse these to a multibar rest if not done automatically.
4. Expand the multibar rest either by pressing M or turning off multibar rests from the style menu (increasing the minimum bars allows for successful expansion).
5. Observe the crash.

#### Steps from Marc (https://github.com/musescore/MuseScore/issues/21299#issuecomment-1918084795):

1. Open [Muse.Orchestra.Demo.zip](https://github.com/musescore/MuseScore/files/14865488/Muse.Orchestra.Demo.zip) or 
[Smoke Test 32.zip](https://github.com/musescore/MuseScore/files/14865519/Smoke.Test.32.zip)
2. Press **Ctrl+B** twenty times to add 20 bars (from @DmitryArefiev: I can repro when adding just 5-7 bars)
3. Press M
4. Press M

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240300304, revision: github-musescore-musescore-6bf6605

### Regression

Yes, this used to work in **MuseScore 4.2.1**

### Operating system

Windows 11

### Additional context

[MuseScore_240130_220456.log](https://github.com/musescore/MuseScore/files/14104853/MuseScore_240130_220456.log)
[MuseScore_240130_220429.log](https://github.com/musescore/MuseScore/files/14104854/MuseScore_240130_220429.log)

**Comment by MarcSabatella** [comment] 2024-01-30 22:23
I cannot reproduce this; can you please ZIP and attach the score itself?

**Comment by basaigh** [comment] 2024-01-30 23:01
[SONATA.zip](https://github.com/musescore/MuseScore/files/14105287/SONATA.zip)
[Muse Orchestra Demo.zip](https://github.com/musescore/MuseScore/files/14105290/Muse.Orchestra.Demo.zip)
These are the two I have seen the issue occur in. I can try and take a screen recording if that would help.

**Comment by MarcSabatella** [comment] 2024-01-30 23:26
OK, I can reproduce using the orchestra demo, with the most recent master nightly, not with 4.2.1, not with other scores.  Open orchestra demo, press Ctrl+B twenty times to add empty bars, press M twice.  The demo stems from an early beta 4.0, and apparently came in via MusicXML import, so that might have somethng to do with it.  But still, it works in 4.2.1, so whatever is wrong seems to have been a recent regression.

**Comment by Eism** [comment] 2024-04-04 06:58
@DmitryArefiev 
Please recheck. I can't reproduce it on 4.3, so probably we should remove it from 4.3 project

**Comment by DmitryArefiev** [comment] 2024-04-04 11:17
@Eism I **can reproduce** it with the steps from Marc's comment above. 
Also, I can reproduce the crash on one of my scores too (in 4.3 and master)

1. Open [Smoke Test 32.zip](https://github.com/musescore/MuseScore/files/14865451/Smoke.Test.32.zip)
2. Press **Ctrl+B** twenty times (to add 20 bars)
3. Press M
4. Press M


https://github.com/musescore/MuseScore/assets/90187801/1ecc30f4-bfbb-4792-986b-5c909c52884e

**Comment by DmitryArefiev** [comment] 2024-04-04 11:18
@MarcSabatella Thanks for the steps! I'll add them to the description

**Comment by DmitryArefiev** [comment] 2024-04-04 15:31
Fixed in #22195

**Closed** 2024-04-04 15:58 UTC
Labels: P1, regression, crash
