### ISSUE TITLE
Light theme accent colour change doesn't cancel in Preferences.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19067] opened 2023-08-16 11:47 UTC
### Issue type

UI bug

### Bug description

This only happens when in light theme. Changing an accent colour then click cancel, does not cancel the action of changing the colour, it seems to make an 'OK' action instead.

### Steps to reproduce

1. Go to Preferences > Appearance
2. Change to Light theme then click OK
3. Go back to Preferences
4. Change accent colour then click CANCEL
5. See error

### Screenshots/Screen recordings

https://www.dropbox.com/scl/fi/fh1ho44senqgpx7nj8v5h/Screen-Recording-2023-08-16-at-12.42.18.mov?rlkey=a1m1g8ru5hdcgh85ttw89vw3r&dl=0

### MuseScore Version

Latest master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS

**Comment by zacjansheski** [comment] 2023-08-18 12:52
Hi @jessjwilliamson , It looks like this has been resolved.  May we close this?

https://github.com/musescore/MuseScore/assets/69917893/9f3ebdc9-dbc1-4b09-991c-d619133ff5c4

**Comment by bkunda** [comment] 2023-08-18 13:24
I can reproduce in 4.1.1.
(Have not yet checked master)

**Comment by jessjwilliamson** [comment] 2023-09-21 10:22
Checked latest master, this is still happening.

**Comment by DmitryArefiev** [comment] 2023-11-10 13:55
Strange.. I **can't reproduce** it either on my setup (m1 laptop, single/dual monitor, macOS 13.6), **4.1.1** and latest **4.2 master**

**Comment by jessjwilliamson** [comment] 2023-11-10 14:17
Weird.. I can still reproduce on latest master 🤔

**Comment by jessjwilliamson** [comment] 2024-05-22 11:30
This seems to be solved in 4.3 :)

**Closed** 2024-05-22 11:29 UTC
Labels: P3, UI, regression
