### ISSUE TITLE
Score preview is distorted for landscape paper format

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#20067] opened 2023-11-17 10:17 UTC
### Issue type

UI bug

### Bug description

In the Home→Score tab the score preview doesn’t respect the aspect ratio of the paper format. This leads to distorted previews for landscape scores like the Adorar_al_nino in the screenshot below (A5 landscape). Portrait scores like the Sonatina (A4 portrait) look better because the preview is in portrait format.

### Steps to reproduce

Have scores in different page sizes and look at Home→Scores.

### Screenshots/Screen recordings

![grafik](https://github.com/musescore/MuseScore/assets/7814361/4a171862-2272-47f7-9ab7-d402ac628bcb)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Manjaro Linux

**Comment by mmeyn** [comment] 2023-11-17 10:21
I just compared the Sonatine preview with the actual score and realised that also that score is distorted a bit. The aspect ratio of the paper formats is 1:√2 and √2:1 but the preview seems to be fixed at something like 9:7.

**Comment by cbjeukendrup** [comment] 2023-11-17 12:08
We might want to consider this a duplicate of #13041

**Closed** 2023-11-17 14:04 UTC
Labels: UI
