### ISSUE TITLE
Ctrl+z not fully undoing an operation, and formatting changing between file closing and opening. 

### ISSUE THREAD

**Issue by JoshuaMcCorkell** [musescore/MuseScore#21016] opened 2024-01-15 02:48 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Sometimes, when I change something, a system will wrap to the next page. When I press ctrl+z, this does not always fully undo the operation. The thing I changed will be undone, but the system will still be on the page that it moved to. In this situation, if you reload MuseScore, it will generally revert back to where it was previously.
May be related to [this issue](https://github.com/musescore/MuseScore/issues/21011).

### Steps to reproduce

Reference File: [Broken Formatting.zip](https://github.com/musescore/MuseScore/files/13935001/Broken.Formatting.zip)

1. Open the attached file (a modified excerpt from the music I was working on when I discovered the bug). 
2. Observe that there are 4 systems on the first page after the 'II' header (6 in total including the 2 at the top).
3. Change something. A lot of different things will trigger the line wrap, but moving one of the notes in the first line after the 'II' horizontally should work.
4. Observe that there are now only 3 systems on the first page after the 'II' header.
5. Press Ctrl+z or Edit > Undo
6. The thing you originally changed will be undone, but the system that got wrapped will still be wrapped.
7. Save
8. Reopen the file, and the score will be back to where it was originally.

Note: If you save the file after step 4 (and before step 5), then pressing ctrl+z _will_ revert the systems back to the original page. 

### Screenshots/Screen recordings

Before:
![image](https://github.com/musescore/MuseScore/assets/99638678/30bcd2f8-17e2-46cc-aa13-d0982db7b185)
After:
![image](https://github.com/musescore/MuseScore/assets/99638678/0ea861fa-f61e-493f-b307-6e6af2afdc14)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

The example file is simplified. I have found this bug on a number of occasions while working on a large file, and in some cases it was more difficult to work around than in this case.

**Comment by MarcSabatella** [comment] 2024-01-15 04:55
I'm not seeing the score.  You need to ZIP it in order to attach here.

One thing to check, as mentioned in the similar linked issue: try double-clicking that initial tempo marking then pressing Esc without making any changes.  I suspect you'll find this produces the same result.  If so, that would indicate the problem is not about undo at at all, but is more likely a matter of the initial layout being incorrect and only being corrected on subsequent edits.  This can occasionally happen if the layout depends on some detail that hasn't been fully determined yet during that initial layout.

**Comment by JoshuaMcCorkell** [comment] 2024-01-15 05:06
My apologies. It have attached it.

Yes, I highly suspect what you have said is correct. Double-clicking the tempo and then pressing Esc worked as you said.

**Comment by mike-spa** [comment] 2024-01-19 08:46
https://github.com/musescore/MuseScore/assets/93707756/9831c221-d988-4a62-9d31-e96dcdf9c583

I can't reproduce the issue, neither by editing and undoing, nor by editing the tempo indication like Marc suggested. Neither in current master nor in 4.2.1. If anyone can, let me know, otherwise I'll close it

**Comment by MarcSabatella** [comment] 2024-01-19 13:50
Interesting, I can no longer reproduce either with this score (although I can for the one in https://github.com/musescore/MuseScore/issues/21011).

**Closed** 2024-01-19 16:28 UTC
Labels: P1, engraving
