### ISSUE TITLE
Selection Box sometimes expands entire height

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#16940] opened 2023-03-20 13:53 UTC
### Issue type

UI bug

### Bug description

**Description:**
Sometimes, whenI try to select a measure (range select), that selection box expands the entire height of the score (see screenshot below), as if only the x-, but not the y-limits of the selection are set properly. 

**Function:**
However function is not affected by that.

### Steps to reproduce

This only occurs from time to time and is hard to reproduce systematically. 
One way I've found, where it occurs quite often:

1. select a bar (single `LClick` in empty space within bar) and copy it to clipboard
2. paste it in the bar below
3. directly try selecting the bar below (sometimes another is okay as well)
  a) empty bar below: selection box expands to infinite height [see screeshot 1]
  b) another non-empty bar: selection box just around lyrics [see screenshot 2]

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/12497326/226361059-3eac500a-93fe-43df-94f2-294ba76e83e0.png)
![grafik](https://user-images.githubusercontent.com/12497326/226360333-48ae4c86-37c6-4836-87a1-413fc1639c1c.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2023-03-20 13:55
Duplicate of #10342. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-03-20 13:55 UTC
Labels: UI, regression
