### ISSUE TITLE
[MU4 Issue] (RC Nightly) Musekeys Grand Piano G2 note has sound artifact

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#15159] opened 2022-12-14 04:05 UTC
**Describe the bug**
The note G2 in the Musesounds Grand Piano has a sound artifact.

**To Reproduce**
1. Open a new score with Grand Piano using Musesounds 
2. Place a G2 note
3. Click Play
4. Hear that G2 regardless of duration or if it's in a chord, will play with a sound artifact.

**Expected behavior**
The note specified above should not play with a sound artifact

**Screenshots**
Screen recording of an example score
https://drive.google.com/file/d/1i-KuLuFwZudmf4GJOxFMTJaMfHSOzqHH/view?usp=sharing

**Platform information**
 - OS: Windows 11, MU4 RC Nightly

**Comment by abariska** [comment] 2022-12-15 15:27
Duplicate of https://github.com/musescore/MuseScore/issues/15148

**Closed** 2022-12-15 15:29 UTC
Labels: P2
