### ISSUE TITLE
Big file crashes again

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#21867] opened 2024-03-09 11:23 UTC
### Issue type

Crash or freeze

### Bug description

[Symphony_No._7_in_c_major.zip](https://github.com/musescore/MuseScore/files/14546075/Symphony_No._7_in_c_major.zip)

### Steps to reproduce

I don't remember if I submitted this score before, but it could be opened in 4.2.0. In later versions it crashes.

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows

**Comment by sammik** [comment] 2024-03-10 00:19
Isn't it duplicate of #21783?

If "tempoline", and not "big file" casuses crash.

**Comment by hhpmusic** [comment] 2024-03-10 00:47
I don't know what causes this, so probably it duplicates that one.

**Comment by oktophonie** [comment] 2024-03-10 16:42
Curiously, I can open this fine in 4.2.1 on Linux and Windows.

**Comment by sammik** [comment] 2024-03-10 20:49
> Curiously, I can open this fine in 4.2.1 on Linux and Windows.

I think, it is not surprising, as "tempoline crash" appeared after 4.2.1.

**Comment by oktophonie** [comment] 2024-03-11 10:22
The issue states that this crash occurs in 4.2.1.
Anyway, the file does cause a crash in master but not in https://github.com/musescore/MuseScore/pull/21808 so I'm closing this as a duplicate.

**Closed by oktophonie** 2024-03-11 10:22 UTC
Labels: needs info, regression, crash
