### ISSUE TITLE
[MU4 Issue] Numpad enter doesn't add line/system break

### ISSUE THREAD

**Issue by HarryAllen1** [musescore/MuseScore#12956] opened 2022-08-22 07:40 UTC
**Describe the bug**
When a line-break needs to be added, the enter-key can be used to add one. However, the numpad enter doesn't add a line break (both with and without num-lock) 

**To Reproduce**
1. Create a new score
2. Select a measure
3. Press numpad enter

**Expected behavior**
A line-break is added

**Platform information**
 - OS: Windows 11, nightly build

**Comment by Jojo-Schmitz** [comment] 2022-09-07 15:13
None of the NumPad keys seems to work, e.g. note entry and entering durations. 
 "+" for tie works though, as does "/" for adding grace notes, Acciaccaturas

**Comment by sammik** [comment] 2022-09-07 16:21
It is the same, as in MU3 (NumPad Enter didnt work in 3.6.2, Linux)

**Comment by Eism** [comment] 2023-01-11 09:27
Enter and Return are different keys. And system break should not be called on Enter if Return is assigned to it.

I can assign Enter for the system break in MU4 and it works.

@DmitryArefiev please test on your machine
If the reassignment of Return to Enter works for you, then let's close this issue.

**Comment by Jojo-Schmitz** [comment] 2023-01-11 09:33
IIRC in Mu3 both, Return and Enter, were assigned to system break

**Comment by Eism** [comment] 2023-01-11 10:10
> IIRC in Mu3 both, Return and Enter, were assigned to system break.
No. Only Return

**Comment by Jojo-Schmitz** [comment] 2023-01-11 10:15
OK, I just double checked and stand corrected ;-)

Still it should though

**Comment by Eism** [comment] 2023-01-11 10:20
So, Is it not a bug? Because the behavior is the same as in MU3

**Comment by Jojo-Schmitz** [comment] 2023-01-11 10:23
The Bug is that you can't make Mu4 using NumPad Enter, trying to do so just exits the dialog.
2nd bug is that it apparently is not possible to __add__ another shortcut, just replaing one for another seems possible

**Comment by Jojo-Schmitz** [comment] 2023-01-11 10:24
All mentioned in #issuecomment-1239684980, 4 months ago...

**Comment by Eism** [comment] 2023-01-11 10:38
The first bug I fixed - see https://github.com/musescore/MuseScore/pull/14715
2nd bug - https://github.com/musescore/MuseScore/issues/13324

**Comment by Jojo-Schmitz** [comment] 2023-01-11 11:03
No, that 2nd bug is not about shortcut sequences (e.g. pressing a, then b, then c), separatend by commas, but about alternative shortcuts, separated be semicolons

**Comment by Eism** [comment] 2023-01-11 11:47
@Jojo-Schmitz see https://github.com/musescore/MuseScore/pull/12347#issuecomment-1184183216

**Comment by Jojo-Schmitz** [comment] 2023-01-11 11:48
So by design. But bad design IMHO, esp. with all the NumPad shortcuts

**Comment by Jojo-Schmitz** [comment] 2023-01-11 11:53
And violated by #12791, which does assign more than one key to a shortcut

**Comment by Tantacrul** [comment] 2023-01-11 14:48
THanks @DmitryArefiev - I did not realise the issue fully. I think you are right. The numpad shortcut should not be assigned automatically. It should just be **possible** to assign it in the first place.


@Jojo-Schmitz 
> So by design. But bad design IMHO, esp. with all the NumPad shortcuts.

The previous shortcut system on MS3 was laughably bad, hard to use and filled with bugs due to inconsistencies. Having a simpler system (one shortcut per action) overwhelmingly improves matters. But of course no change ever results in a 100% approval. The only difference is that in MS4, we'll clear up any existing bugs in a few weeks / months. With MS3, they were allowed to persist for years.

**Comment by Tantacrul** [comment] 2023-01-11 14:51
Because you were one of the only 20 people who had a clue how it worked

**Comment by Jojo-Schmitz** [comment] 2023-01-11 14:53
Not so, I'm pretty activer in the forum andth issue tracker and there too I don't remember any serious issues or problems

Oh well, then hopefully soon I belong to the 20 people that know how they work in Mu4...

**Comment by Tantacrul** [comment] 2023-01-11 14:55
Jojo., in all seriousness, you have been defending rubbish ideas for years. Just sit back, watch and learn.

**Comment by Tantacrul** [comment] 2023-01-11 14:56
Thanks @DmitryArefiev - I did not realise the issue fully. I think you are right. The numpad shortcut should not be assigned automatically. It should just be possible to assign the numpad shortcut in the first place. That should do the trick.

**Comment by DmitryArefiev** [comment] 2023-01-11 18:21
@Tantacrul Thanks for review. Let's close it as by design

**Comment by Tantacrul** [comment] 2023-01-11 18:59
Actually @DmitryArefiev - I think the problem is that you also can't assign the **Enter** button using the numpad to this action. If you try it just closes the dialog. That's the part that still needs to be fixed.

The discussion about sequences and multiple shortcuts has obscured that. I'm going to reopen this and alter the title a little.
Sorry for the confusion.

**Comment by Tantacrul** [comment] 2023-01-11 19:01
> The first bug I fixed - see https://github.com/musescore/MuseScore/pull/14715 (@Eism)

I didn't see this the first time around. This does solve the problem, so you were right Dmitri. Sorry again!

**Closed by Tantacrul** 2023-01-11 19:01 UTC
Labels: P2
