### ISSUE TITLE
[MU4 Issue] VST window size bugs

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9716] opened 2021-11-11 15:57 UTC
**Describe the bug**
The purpose is to demonstrate the behaviour between a standard DAW such as Ableton compared to how Musescore is currently functioning when it comes to opening a window of a VST.

I'm using BBC Orchestra, Spitfire LABS and Kontakt as some of the 3 main/popular VSTs to demonstrate a window bug.
I compare how the behaviour should be by opening the same VSTs by using Ableton first, then use Musescore to show the difference.
The main issue is the white window dialog space surrounding the VST.
Watch the video to see the comparison between VST window behaviours.
Kontakt still appears too small - this relates to this https://github.com/musescore/MuseScore/issues/9228

https://user-images.githubusercontent.com/71656189/141327502-415cb867-91a6-4a55-81cc-4d6cbf2eab47.mp4

https://user-images.githubusercontent.com/71656189/141327530-1adbe5eb-f5ec-4714-b668-01b9b16ccaec.mp4

https://user-images.githubusercontent.com/71656189/141327571-1cea4782-f18d-4cc9-a026-fc44517b6a90.mp4

**Desktop (please complete the following information):**
 - OS: Mac and Windows

**Comment by vpereverzev** [comment] 2021-11-29 09:26
duplicate of #9228

**Closed by vpereverzev** 2021-11-29 09:26 UTC
Labels: P1
