### ISSUE TITLE
[MU4 Issue] Musescore crashes when opening the score

### ISSUE THREAD

**Issue by urbanrieger** [musescore/MuseScore#16235] opened 2023-02-06 15:15 UTC
**Describe the bug**
When I open the score arrached, MS4 crashes.

**To Reproduce**
1. Open the attached score (zipped) in MS4. The score was written in MS4. 
2. Musescore 4 opens and crashes immediatly

**Expected behavior**
Musescore 4 shoud open the score.

**Screenshots**
-

**Platform information**
- Windows 11, MuseScore 4.0.1

**Additional context**
-
[Freude_schoener_GoetterfunkenMS4.zip](https://github.com/musescore/MuseScore/files/10664473/Freude_schoener_GoetterfunkenMS4.zip)

**Comment by cbjeukendrup** [comment] 2023-02-08 22:45
Hi! I fixed the cause of this crash, and then in the fixed version of MuseScore I re-saved the file. Now it also seems to open again in the current version of MuseScore: 
[Freude_schoener_GoetterfunkenMS4 copy.mscz.zip](https://github.com/musescore/MuseScore/files/10690471/Freude_schoener_GoetterfunkenMS4.copy.mscz.zip)

**Comment by urbanrieger** [comment] 2023-02-09 18:05
Great, this community is awesome. Can you somehow explain, what you did to fix ist?

**Comment by cbjeukendrup** [comment] 2023-02-09 18:30
I fixed the crash in the source code, and recompiled MuseScore. (So this is not something that regular users can do themselves.)

You can download the fixed version of MuseScore from https://github.com/musescore/MuseScore/pull/16284, following the instructions at https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#Downloading-Builds-from-Pull-Requests.

**Comment by DmitryArefiev** [comment] 2023-02-10 15:25
Fixed in #16284

**Closed** 2023-02-10 15:26 UTC

**Comment by DmitryArefiev** [comment] 2023-03-02 15:09
Retested on Win10
