### ISSUE TITLE
MuseScore4 and workNumber properti.

### ISSUE THREAD

**Issue by juliff** [musescore/MuseScore#18673] opened 2023-07-17 18:13 UTC
### Issue type

UI bug

### Bug description

In MS4 when you add a custom properti called "workNumber", like old-fashioned MS3, the properti is stored but don't appear anymore.

The properti/value is available if you want use it in, for ex., the footprint's layout.

Notes:
- Bug present in MS 4.0 and MS 4.1
- My natural language is Spanish, sorry my mistakes.

### Steps to reproduce

1) Menu [File\Project properties]
2) [New propertie]
3) Name: "workNumber", value: "anything"
4) [Ok]
5) Enter again in [File\Project properties]
6) The added properti is not visible.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 10, Windows 11

**Comment by cbjeukendrup** [comment] 2023-07-18 02:16
This is a duplicate of #17598, so I'll close it. Will be fixed in a next update!

**Closed by cbjeukendrup** 2023-07-18 02:16 UTC
Labels: UI
