### ISSUE TITLE
The Musesounds Bass Drum ignores all accent and marcato markings at certain dynamics

### ISSUE THREAD

**Issue by MaxMussi** [musescore/MuseScore#22716] opened 2024-05-07 21:46 UTC
### Issue type

Muse Sounds bug

### Bug description

The Musesounds Bass Drum ignores all accent and marcato markings at dynamics ppp, pp, p, mp, mf, ff. However, It respects the accent markings at f and default dynamic.
This issue specifically affects the Musesounds drum, not MSbasic or custom soundfonts.

### Steps to reproduce

1. Create new Score
2. Add Bass Drum
3. Add a few notes
4. Add accents
5. Use the problematic dynamics
6. Observe how the accents will be ignored

### MuseScore Version

MuseScore-4.2.1.240230938-x86_64.AppImage

### Regression

I don't know

### Operating system

Linux Mint 21.3

**Comment by Dima-S-Jr** [comment] 2024-05-07 23:50
Isn't this a duplicate of #21410?
Also related to #21960.

**Comment by zacjansheski** [comment] 2024-05-08 13:39
Closing as duplicate (see above)

**Closed by zacjansheski** 2024-05-08 13:39 UTC
Labels: muse sounds
