### ISSUE TITLE
[MU4 Issue] Instrument Sort order for ROCK is wrong

### ISSUE THREAD

**Issue by odelphi** [musescore/MuseScore#14230] opened 2022-11-01 02:52 UTC
**Describe the bug**
When starting a new score in Version 4, if you want to sort the instruments using the ROCK sort order, it puts the DRUMS at the top.  Drums should always be at the bottom.

**To Reproduce**
1. Start a new score with several instruments including drums
2. Use the ROCK instrument sort order
3. After clicking on the ROCK sort order, the drums will be sorted to the top of the order.  If you use Voice, Voice will be at the top with Drums second.  That is still wrong.

**Expected behavior**
Drums should be sorted to the bottom of the order

**Screenshots**
![Musescore-Rock Sort](https://user-images.githubusercontent.com/52181093/199148114-3a7ecf32-83e1-4f5d-9154-aa90da1d2d38.png)

**Platform information**
 - OS: Microsoft Windows 10

**Comment by gerrybass** [comment] 2022-11-01 09:52
i like to add, when using MS basic for drumset, that the assignment of notes to the drumsound is not right
f.e. low 'a' is not bassdrum etc

perhaps the wrong place, so ignore my comment ;-)

**Comment by MarcSabatella** [comment] 2022-11-01 12:59
Wrong place indeed.  But also, most likely it's a misunderstanding over how drum input works.  See the Handbook section, and if you have further questions, feel free to ask on the forum, or in Discord.

**Comment by odelphi** [comment] 2022-11-01 15:51
Marc, when you say "its a misunderstanding" who is misunderstanding?  ME?  The program?  From the users standpoint, there is no misunderstanding (IMO).  The drumpart should be at the bottom, regardless of how the drum input works.
BTW:  I also think the Trumpet Bb  is also in the wrong place.  It shouldn't be at the bottom.  Maybe, it should come after voice, then piano, then guitar, then drumset.  Or if the guitar is the solopart, the guitar comes after voice.

**Comment by Tantacrul** [comment] 2022-11-01 17:53
I believe this would be trivial to fix. I've assigned to @oktophonie for now...

Worth mentioning that this was the ordering in MS3.6, so it's not a regression.

**Comment by njvdberg** [comment] 2023-05-12 09:36
Seems to be an issue in `orders.xml`, I'll have a look.

**Comment by njvdberg** [comment] 2023-05-12 10:08
From the original issue:

> Drums should be sorted to the bottom of the order

This isn't 100% true, the order should be (or at least, is defined as)

 - Voice
 - Acoustic Guitar
 - Drumset
 - Piano
 - Trumpet in Bb

This because the only defined instrument families in the Rock order are `voices`, `guitar` and `drums`. All other instruments, like the Piano and Trumpet and not defined so they will appear in the `unsorted` section which is at the bottom.

However, there was an issue in `orders.xml` causing the drums (actually, the guitars) to be places at the wrong position. PR for this is coming.

**Comment by njvdberg** [comment] 2023-05-12 10:54
See PR #17541

**Closed** 2023-05-12 11:32 UTC
Labels: P2, community, instruments
