### ISSUE TITLE
Musescore 4 Crashing on Mac

### ISSUE THREAD

**Issue by bobr666** [musescore/MuseScore#16923] opened 2023-03-19 12:53 UTC
### Issue type

Crash or freeze

### Bug description

Started with a problem of trying to add a Terza Volta. I wanted this to show 4 instead of 3. Consistently trying to edit in the properties dialogue caused a crash. However even after getting around this (using a different Volta), I got persistent crashes and file won't open on Mac. (Crashes on opening). However, opening the file on a Windows PC is possible.

I renamed the file to .zip and can open it in 3.6.2 on the Mac. However, it then crashes during playback in 3.6.2

### Steps to reproduce

Try to load file below

### MuseScore Version

4.02

### Regression

I don't know

### Operating system

Mac OS Version 13.2.1 (22D68)

### Additional context

[Hawaii 5-0b.zip](https://github.com/musescore/MuseScore/files/11011032/Hawaii.5-0b.zip)
Sometimes got a 'report to Apple' crash log, but when I try to open it now, Musescore just crashes

**Comment by cbjeukendrup** [comment] 2023-03-19 13:04
This seems related to the crash in https://github.com/musescore/MuseScore/issues/16442.

**Comment by cbjeukendrup** [comment] 2023-03-19 13:10
Since there is already a pending solution for https://github.com/musescore/MuseScore/issues/16442, and I can confirm that this solution also fixes the crash with your score, I think we should close this as a duplicate. Thanks for reporting!

**Closed by cbjeukendrup** 2023-03-19 13:10 UTC
Labels: crash
