### ISSUE TITLE
Courtesy time signatures not disappearing when no unneeded

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15311] opened 2022-12-18 09:23 UTC
**Describe the bug**
Extra time signatures can appear in the middle of a page if that time sig used to be at the start of a new page with a courtesy but after it changes to the middle of the page because of a layout change, the courtesy does not always automatically disappear.

**To Reproduce**
1. make a time sig at the start of a page (defauted to courtesy enabled)
2. do something to move that bar to the middle of a page
3. see the courtesy could still be right beside the time signature

**Expected behavior**
Courtesy time signatures would disappear if that bar is moved to the middle of a page.

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/208290412-1135b186-bbc9-4286-a33e-b749a609f0b6.png)

the 7/8 bar used to be at the start of a page, but now it is not

**Platform information**
windows

**Additional context**
It is very easy to manually fix by clicking the disable courtesy button but then if the bar gets moved again to the start of a page, it will have to be manually enabled again which is easy to miss or forget about.
It would not be a big problem to most people but when there are hundreds of bars and many time signatures per page, it is time consuming to fix all of them. The mistakes could be hard to find if the number size is not made extra large to show repetitions.

**Comment by Vykoiazon** [comment] 2022-12-18 09:28
The most annoying thing about fixing it is that removing an extra courtesy on an early page could free enough space to add another bar to that page, but then the rest of the pages now have a different layout because they have different bars, which can cause more unneeded courtesy time sigs to be there in the middle of pages, so it can cause a chain reaction that has to be slowly fixed one at a time.

**Comment by Vykoiazon** [comment] 2022-12-18 11:01
https://user-images.githubusercontent.com/120861729/208294650-6257cf17-1ae7-4236-abbb-346a2ed47bdf.mp4
this is what happens to those time signatures when courtesy is toggled

**Comment by cbjeukendrup** [comment] 2022-12-18 16:02
I couldn't reproduce this on a new score so far. Could you maybe upload the score where this happens so that we can investigate? 

Or do you know whether there are additional steps to reproduce this on a new score?

**Comment by Vykoiazon** [comment] 2022-12-19 10:03
The scores with the problem were already fixed and I do not know how to break the courtesy again but if I see it, I will post it.

**Comment by Vykoiazon** [comment] 2022-12-24 03:49
I found another file where this happened and saved that bar:

[time sig courtesy mid page.zip](https://github.com/musescore/MuseScore/files/10297939/time.sig.courtesy.mid.page.zip)

**Comment by oktophonie** [comment] 2022-12-24 09:23
I thought the weird beam would be fixed by https://github.com/musescore/MuseScore/pull/15155 but apparently not; I have added this case as an additional required fix.

**Comment by cbjeukendrup** [comment] 2022-12-24 17:07
I finally think I managed to reproduce this:
1. Create new score
2. Add time sig in bar 2
3. Add line break before bar 2
4. Change scale of the courtesy time sig
5. Save the file
→ The courtesy time sig is now written explicitly in the previous bar in the MSCX file (normally it isn't)
6. Reopen the file
7. Remove the line break
→ The issue occurs

When resetting the scale, re-adding the line break, then re-saving/closing-reopening, and removing the line break again, the issue does _not_ fix itself.

@Vykoiazon Does this seem right? Is this approximately what you did to get into this situation?

**Comment by Vykoiazon** [comment] 2022-12-24 21:34
This was only a 2 stave score so there was no reason to change the scale of the signature here but it still happened.

**Comment by Vykoiazon** [comment] 2022-12-26 19:24
![image](https://user-images.githubusercontent.com/120861729/209578206-86dc3e05-acd7-4c23-95f6-88ceff548b21.png)
that time the default clef was also duplicated between the time signatures for unknown reasons

**Closed** 2023-05-01 15:15 UTC
Labels: engraving
