### ISSUE TITLE
[MU4 Issue] Keyboard shortcut to advance chord entry to next measure don't work on MacOS

### ISSUE THREAD

**Issue by jwmatthys** [musescore/MuseScore#15719] opened 2023-01-05 06:08 UTC
**Describe the bug**
When entering chord symbols on MacOS, the default keyboard shortcut cmd + L or R arrow shifts the text entry cursor to the beginning or end of the current chord symbol instead of advancing the chord symbol entry cursor to the next bar.

**To Reproduce**
1. Click on a note in the score
2. Press cmd-K to enter chord entry mode
3. Enter a chord symbol
4. Press cmd + right arrow.

**Expected behavior**
The chord cursor advances to the next measure.

**Platform information**
 - OS: macOS 11.6 - MacBook Pro with Apple M1 chip

**Additional context**

**Comment by MarcSabatella** [comment] 2023-01-09 14:21
@Tantacrul this is one I that comes up pretty often

It works fine in release for me on Linux, but not on master.  I believe it was broken with https://github.com/musescore/MuseScore/pull/15081.

As per my comment there, I really believe we should consider reinstating Tab, if we can make that work for chord symbol edit mode without also breaking the behavior or Tab or Ctrl+Right in normal mode (eg, with a text element selected, Ctrl+Right should nudge it right 1 sp, but Tab of course should move keyboard focus to the status bar).

**Comment by mgoldsf** [comment] 2023-01-21 23:16
I'm having the same issue on my MacBook Air, OS 12.4: When in chord entry mode, these shortcuts do not move the cursor as advertised:
* Move cursor to next measure: Cmd + right arrow
* Move cursor to previous measure: Cmd + left arrow
* Move cursor by duration number: Cmd + 1-9

Also, custom shortcuts that I program for "move to next measure" and "move to previous measure" are equally ineffective.

**Comment by MarcSabatella** [comment] 2023-01-30 18:02
@Tantacrul could a fix for this be considered for 4.0.2?  Issues with chord symbol navigation remain one of the most commonly reported regressions aside from the actual missing features.

The fact that the default shortcut changed from Tab to Ctrl+Right is bad enough for users accustomed to the previous behavior, but combined with the fact that Ctrl+Right simply doesn't work on many systems and also the customization doesn't work on some systems and also Ctrl+number shortcuts don't work - this really makes chord symbol entry difficult.

My suspicion is that @cbjeukendrup 's PR https://github.com/musescore/MuseScore/pull/15081 could be enhanced to fix most of this with relatively little effort.  Right now, it's not suitable for 4.0.2 because it actually breaks Ctrl+Right for those systems where it was previously working, but I am guessing that wouldn't be hard to fix.

**Comment by Tantacrul** [comment] 2023-01-30 18:30
We've already got a fairly bloated 4.0.2 as it is. Trying to keep it lighter so we don't take forever with it.

I've moved this to 4.1 for now. I'll be communicating the 'idea' for 4.1 and beyond soon. We're getting close to done with our planning.

**Comment by MarcSabatella** [comment] 2023-05-01 22:52
As per my comments in https://github.com/musescore/MuseScore/pull/15081, it's actually worse now in current master - ut's not just macOS anymore.  I think I see a reasonable fix and my PR linked above may be it.  If not, I can continue to tweak it.  It will need testing by someone else on a Mac keyboard, though.

**Comment by cbjeukendrup** [comment] 2023-05-10 21:48
@MarcSabatella I've quickly tested your PR on macOS, and it seems to work great! But let's still wait for Dmitry's official testing :)

**Comment by MarcSabatella** [comment] 2023-05-10 21:52
Excellent, thanks!  I know many people had issues with these on macOS previously (before your change), but I don’t know if anyone ever knew why.  so I’m glad to know that the end result here is it seems to be working on at least some Max keyboards.

**Closed** 2023-05-16 12:25 UTC
Labels: P2
