### ISSUE TITLE
Popup appears every time I open MuseScore

### ISSUE THREAD

**Issue by BezierCurves** [musescore/MuseScore#20396] opened 2023-12-10 20:09 UTC
### Issue type

Other type of issue

### Bug description

Every time I open MuseScore on Mac, this popup appears.

### Steps to reproduce

Open MuseScore on Mac.

### Screenshots/Screen recordings

<img width="1440" alt="Screenshot 2023-12-10 at 12 04 02 PM" src="https://github.com/musescore/MuseScore/assets/127568765/70621a52-2e2d-4b5a-b60f-ca9aaf2d3037">

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS 14.1.1, M1 chip

**Comment by jeetee** [comment] 2023-12-10 20:30
It's not a bug as much as a MacOS new feature shown when an App accesses data that is part of a different App (in this case MuseScore accessing Muse Sounds, which are part of Muse Hub).

See #19905

**Comment by cbjeukendrup** [comment] 2023-12-10 21:57
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/19905

**Closed by cbjeukendrup** 2023-12-10 21:57 UTC
Labels: needs review
