### ISSUE TITLE
[MU4 Issue] Note duration incorrect in playback when ties are changed, until save/close/reopen

### ISSUE THREAD

**Issue by macaquedev** [musescore/MuseScore#15914] opened 2023-01-16 13:57 UTC
Steps to reproduce issue (creditto [krtschil](https://github.com/krtschil) for deciphering my initial mess and writing these much clearer instructions)

- Created a new score with a viola
- Added A to 5 measures
- Added the tie to all 5 notes
- Started playback
- The note stopped playing after the second measure although it should be played for all 5 measures
- Saved the file, closed it and opened again: playback was now normal: the note played 5 measures long
- Started all over again (creating a new score)
- Created the note as above and created the ties
- Removed the tie from 3rd to 4th note
- Lowered the note in 4th measure and started playback
- The note A continued to play after measure 3 so two notes were played simultaneously in measure 4+5
- Saving the file and reopening it solved the problem

OS: Ubuntu 22.04
MuseScore 4.0.1

Why is this happening?

--------------------------------------------------------------------------

From @DmitryArefiev : the important notice to reproduce the issue is how to add ties

https://github.com/musescore/MuseScore/assets/90187801/39dbec99-e035-4c52-a141-51b4bd4255ee

**Comment by MarcSabatella** [comment] 2023-01-16 14:52
In order for someone to investigate, please attach your score (ZIp it so GitHub will accept it) and say exactly which measures are giving you trouble.  Also best to submit separate issues for separate problems.

**Comment by macaquedev** [comment] 2023-01-16 15:11
> In order for someone to investigate, please attach your score (ZIp it so GitHub will accept it) and say exactly which measures are giving you trouble.  Also best to submit separate issues for separate problems.

Hi, I've fixed it by removing the ties and adding them back in. But this is a bug that would still need to be fixed as I keep having to untie and add ties back when adding more length to a tied note. What I mean is that if I create a tied note of a certain duration, and then change that duration, it will still playback as the old duration. Turns out it is for all instruments, all dynamics and all articulations. I suppose that's probably enough info, if it isn't I will add more.

**Comment by MarcSabatella** [comment] 2023-01-16 15:48
As mentioned, in order for someone to investigate, you'd need to attach the score - the version with the problem.  As it is, I can't reproduce this from scratch myself.

**Comment by macaquedev** [comment] 2023-01-16 16:04
I understand. The issue is - this is a bug with the program itself. If I send you the score, it will work fine. This bug occurs during workflow. Would you be able to try the steps I suggested please?

**Comment by MarcSabatella** [comment] 2023-01-16 16:18
Are you saying the problem goes away if you save and reload the score, and that's why I won't be able to reproduce the issue if you attach the score?  If so, then please give more specific steps to reproduce the problem.  You mentioned something about changing the duration, but it isn't clear which note you changed, what the original duration, or how you changed it.  So a precise set of steps would be needed.

**Comment by macaquedev** [comment] 2023-01-16 16:31
Yes to your first question.
Doesn't matter which note, dynamic, articulation, instrument or tempo. But for the purposes of this, try creating a new score with a viola part, and add an A that is 5 bars long. Then, remove the tie between bars 3 and 4 and change the second note to a Bb. (You should have a 3 bar long A and a 2 bar long Bb). Now, playback. You should hear that the A keeps on playing for the entire 5 bars, and the Bb comes in on bar 4.

**Comment by krtschil** [comment] 2023-01-16 17:14
I tried the following steps:
- Created a new score with a viola
- Added A to 5 measures
- Added the tie to all 5 notes
- Started playback
- - The note stopped playing after the second measure although it should be played for all 5 measures
- Saved the file, closed it and opened again: playback was now normal: the note played 5 measures long
- Started all over again (creating a new score)
- Created the note as above and created the ties
- Removed the tie from 3rd to 4th note
- Lowered the note in 4th measure and started playback
- The note A continued to play after measure 3 so two notes were played simultaneously in measure 4+5
- Saving the file and reopening it solved the problem

**Comment by MarcSabatella** [comment] 2023-01-16 17:28
OK, then please update the title and the main description to reflect these clear steps.

**Comment by macaquedev** [comment] 2023-01-16 17:31
OK, doing this now.

**Comment by zacjansheski** [comment] 2023-08-10 19:24
For future reference
https://github.com/musescore/MuseScore/assets/69917893/34fb207e-449a-4519-9473-8c60fd2b7008

**Closed** 2023-11-27 11:17 UTC
Labels: P1, playback
