### ISSUE TITLE
[MU4 Issue] From Git Master Build Failed 

### ISSUE THREAD

**Issue by Yann-Kaelig** [musescore/MuseScore#12572] opened 2022-07-27 14:50 UTC
**Describe the bug**
Musescore from Git Master build failed on Linux.

**Platform information**
Operating System: Gentoo Linux 2.8
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.5
Kernel Version: 5.18.14-gentoo-x86_64 (64-bit)
Graphics Platform: X11
Processors: 2 × AMD Phenom(tm) II X2 550 Processor
Memory: 15.6 GiB of RAM

**Additional context**
FAILED: src/framework/draw/CMakeFiles/draw.dir/internal/qfontprovider.cpp.o
FAILED: src/framework/draw/CMakeFiles/draw.dir/internal/fontengineft.cpp.o

[MS4-GitMaster-BuildFailed.txt](https://github.com/musescore/MuseScore/files/9200171/MS4-GitMaster-BuildFailed.txt)

**Comment by cbjeukendrup** [comment] 2022-07-28 12:43
This is probably caused by `-DBUILD_UNITY=OFF`. We do intend to support non-unity build, but all of us do use Unity build, which means that we occasionally forget an #include, causing non-unity builds to break but we don't notice it. For now, could you please try if it works with `-DBUILD_UNITY=ON`?

**Comment by Yann-Kaelig** [comment] 2022-07-28 17:15
Well. To succeed the build I have to generate a Makefile and use cmake with at least -DBUILD_PCH=ON and -DBUILD_UNITY=ON.

My build options for now:

-DBUILD_JACK=ON
-DBUILD_PCH=ON
-DBUILD_UNITY=ON
-DBUILD_SHARED_LIBS=ON
-DBUILD_UNIT_TESTS=OFF
-DDOWNLOAD_SOUNDFONT=OFF
-DSOUNDFONT3=ON
-DTRY_USE_CCACHE=OFF
-DUSE_SYSTEM_FREETYPE=ON

**Comment by Yann-Kaelig** [comment] 2022-07-28 19:57
Well. No sound, no connection to jack-audio. No jack option available in the IO preferences > device output. Looks like the BUILD_JACK option does nothing.

**Comment by cbjeukendrup** [comment] 2023-02-12 02:00
Closing this, because the build failure was solved (you need indeed -DBUILD_PCH=ON and -DBUILD_UNITY=ON, which is the default) and the jack-audio issue is reported in other issues too.

**Closed by cbjeukendrup** 2023-02-12 02:00 UTC
