### ISSUE TITLE
(Critical) Dynamics added to the score are not displaying at all.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8804] opened 2021-08-06 10:18 UTC
### Bug
When applying a dynamic from the properties panel, the do not appear on the score.

**This is a critical issue: we are unable to test aspects of the properties panel because dynamic markings can not be selected**

![image](https://user-images.githubusercontent.com/21022311/128495544-d6f31e1d-820d-4853-9475-68e9f8261504.png)

### Reproduce
1. Select a dynamic marking from the properties panel and apply it to a note in the score
2. Observe that the positioning on the score will change (implying that _something_ has happened) but that the dynamic is not visible

The image below is of a note which has had a 'PPP' dynamic marking applied to it. It does not seem to be the case the the dynamic is 'invisible'. It simply just doesn't seem to be there and can't be selected.

![image](https://user-images.githubusercontent.com/21022311/128496137-c6860b76-aa29-4f32-b2c6-0a4029072041.png)

### Machine Info
 - Mac OS - Catalina

**Comment by RomanPudashkin** [comment] 2021-08-06 10:56
I'm working on this issue

**Comment by RomanPudashkin** [comment] 2021-08-06 12:21
This commit is the reason
https://github.com/musescore/MuseScore/commit/213e3ab66e2063cc35be3f644070e1cbc2f6b279

Those changes broke dynamics
![image](https://user-images.githubusercontent.com/67867444/128509382-f68a3372-2a2c-4af5-9da8-2beec8f7a101.png)

**Comment by RomanPudashkin** [comment] 2021-08-06 12:46
@wizofaus could you help me with this issue? I don't quite understand the purpose of those changes

**Comment by wizofaus** [comment] 2021-08-06 17:23
That should definitely do the same thing though.  And adding dynamics works fine for me,  admittedly I have some other changes on my local repo as I'm trying to fix other stuff related to text elements. I can't actually remember what PR that change was for!

**Comment by wizofaus** [comment] 2021-08-06 17:26
Oh ok that was from 6 or 7 weeks ago.  Adding dynamics hasn't been broken all that time! But logically that change shouldn't affect any behavior,  it was just a cleaner way of writing the same thing.

**Comment by wizofaus** [comment] 2021-08-06 20:44
Ok I was able to determine that there is a slight change in behaviour between the two - in that updateCursorFormat() now gets called which resets the current format info of the TextCursor, and this IS incorrectly changing the font format of the dynamic symbol.  On Windows at least this means it simply shows the dynamic incorrectly italicized, but I guess on other platforms it's possible that because this font doesn't support italic, nothing shows at all.
If so, that's the same issue I'm already working on, as there's quite a few issues that stemmed from that.
However it's fine to put up a PR to revert those lines in the meantime, as my fix will take quite a while.

**Comment by vshalkevich** [comment] 2021-08-18 08:56
Fixed in the latest master branch build.
For example, in this build it is not reproducible for me https://github.com/musescore/MuseScore/actions/runs/1141776540

**Closed by vshalkevich** 2021-08-18 08:56 UTC
Labels: P0
