### ISSUE TITLE
Super long sustain in solo strings where it shouldn't be present

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#20714] opened 2023-12-26 06:59 UTC
### Issue type

General playback bug

### Bug description

So I was working on Beethoven's Op. 4 string quintet, specifically the minuet movement. Everything seemed to be going well, the first 2 movements sound fine, but now I run into this sustain problem. It seems to be that the sudden shift to forte triggers one of the notes in the forte to sustain way longer than it should in Muse Sounds. This is a big issue cause even the long notes shouldn't sustain that long at Beethoven's incredibly fast tempo for this movement(130 to the measure). MS Basic does have a bit of a sustain issue around measure 518 where the swells happen but the dynamic change to forte triggering the sustain seems to be specific to Muse Sounds, if I set it to MS Basic, the forte triggered sustain bug goes away and I'm just left with a sustain bug where the swells are.

### Steps to reproduce

1. Open the score
2. Start playback at measure **450**
3. Play the score with **Muse Sounds** playback 
4. Hear how the forte shift seems to trigger the sustain
5. Switch to **MS Basic**
6. Play starting from measure 450 again
7. Hear how there's no sustain bug until the swell at measure **521**

### Screenshots/Screen recordings

Muse Sounds playback(with the Violas set to +8 and Cello set to +3.3 in the mixer):

https://github.com/musescore/MuseScore/assets/6530761/f59784d8-cc7d-4e71-bf21-235af817ba5e

MS Basic playback:

https://github.com/musescore/MuseScore/assets/6530761/c28ba270-d269-4b35-9a12-551044c714a7

### MuseScore Version

MuseScore 4.2

### Regression

Yes, this used to work in **MuseScore 4.1.1** (can be checked on mxl export>import)

### Operating system

Windows 10

### Additional context

[String Quintet no. 1 in Eb Op. 4.zip](https://github.com/musescore/MuseScore/files/13769362/String.Quintet.no.1.in.Eb.Op.4.zip)

**Comment by DmitryArefiev** [comment] 2023-12-27 13:05
**Muse Sounds** only:

https://github.com/musescore/MuseScore/assets/90187801/f0efbd9f-4442-4ef7-88bd-406bcb8c763f


**Muse Sounds and **MS Basic**: 

https://github.com/musescore/MuseScore/assets/90187801/4125897a-637d-4c23-90d5-7a5fe68a9ebd

@bkunda I added this to **4.2.1** since can't reproduce it in **4.1.1** using mxl export/import (happens in 4.2 using mxl export/import)

**Comment by cbjeukendrup** [comment] 2023-12-28 03:59
It seems that this would be solved by #20644.

**Comment by DmitryArefiev** [comment] 2023-12-28 08:24
> It seems that this would be solved by #20644.

@cbjeukendrup Yes, it looks good in #20644 build

**Comment by DmitryArefiev** [comment] 2024-01-08 16:28
Fixed in #20644

**Closed** 2024-01-09 07:56 UTC
Labels: P1, regression, playback
