### ISSUE TITLE
[MU4 Issue] Diacritics in file name not supported when exporting as sound file

### ISSUE THREAD

**Issue by bartixxowy** [musescore/MuseScore#14782] opened 2022-11-27 13:31 UTC
**Describe the bug**
When you put any foreign letter with diacritics such as "ą", "ę", "ł", "ź" (checked only with PL ones), MuseScore exports two files: one with weird symbols (replacing these diacritics) which can be opened properly and second one broken (proper name but shows error and is 0 bytes).

**To Reproduce**
1. Open any score
2. Click "file" and then "export"
3. Export file as ".mp3"
4. Put any diacritics in the file name
5. Wait until done
6. See two seperate files instead of one (one of them is broken, second one is fine)

**Expected behavior**
MuseScore exports only one file with all diacritics in its name and then app can play this sound file normally without an error.

**Screenshots**
https://user-images.githubusercontent.com/119168368/204137069-9167510f-e2cb-487e-aec1-94a9467e5abe.mp4

**Platform information**
 - OS: Windows 10 64-bit

**Additional context**
- This problem may also affect exporting with any other extenction such as .wav or .pdf - haven't checked that yet.
- I'd like to apologise in advance if this issue was already mentioned earlier - it's my first time working on MU4 GitHub and reporting issues.

**Comment by cbjeukendrup** [comment] 2022-11-27 15:07
This looks like a duplicate of #14173. Thanks for reporting though!

**Closed by cbjeukendrup** 2022-11-27 15:07 UTC
