### ISSUE TITLE
Changing the voice of notes with lyrics attached to them, will delete lyrics

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#25417] opened 2024-11-03 14:22 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1.: Enter some notes
2.: Add some lyrics
3.: Select notes with lyrics and change them to voice 2
4.: See: Lyrics get deleted

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/11dcbb4b-5060-4f9d-b349-35db01ad9514

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-243080308, revision: github-musescore-musescore-ef6b94b

### Regression

No.

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-11-04 08:33
Duplicate of https://github.com/musescore/MuseScore/issues/17092

**Closed by oktophonie** 2024-11-04 08:33 UTC
Labels: UX/interaction
