### ISSUE TITLE
[MU4 Issue] Menu's open in strange locations on 125% scale and 2nd screen

### ISSUE THREAD

**Issue by ootjersb** [musescore/MuseScore#10267] opened 2022-01-14 08:23 UTC
On Windows 11 with scale set to 125% the menu opens in the wrong place. When placing MuseScore on second screen the menu is even shown on the main screen

1. Open Musescore
2. Click on a menu, such as file

Expected behavior
Menu options (like New, Open et cetera) just below File.

![image](https://user-images.githubusercontent.com/33753713/149474996-55beba4f-d833-4d70-b14b-2172181066a5.png)

 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-1696108081, revision: MuseScoreNightly-202201140422-master-9e83219-x86_64

**Comment by DmitryArefiev** [comment] 2022-01-14 16:30
Assigning to @Eism

**Comment by Eism** [comment] 2022-01-18 12:50
@ootjersb
Can you please check PR #10285?

**Comment by ootjersb** [comment] 2022-01-18 20:54
> @ootjersb Can you please check PR #10285?

Not so sure about the process to follow, since I am quite a newbie for this project. I downloaded the artifact from the CI build, and tried it but it did not resolve my problem. Also build myself from PR #10285 code (as a newbie) but same result (of course)

**Comment by ootjersb** [comment] 2022-01-18 20:58
Some additions: I thought my scaling was 125%, but it seems this way:
1. Screen 2: scaling 150%
2. Screen 1: scaling 125%

**Comment by DmitryArefiev** [comment] 2022-01-19 09:45
Hi @ootjersb , I can't reproduce it on Windows 10 (screen 1: 125% , screen 2: 150%).. The menu opens in regular place for me.

Maybe there are some additional steps?

Thanks!

**Comment by ootjersb** [comment] 2022-01-19 16:46
Not so much is needed. 

I had this immediately when opening up MuseScore for the first time and like mention in the original report. My screen orientation is vertical, with a 4k screen as uppermost screen, and a laptop screen 1920x1080 as bottom screen. The bottom screen was then setup as main:
![image](https://user-images.githubusercontent.com/33753713/150175638-b0d9148a-38a4-4292-95e8-bed15599710d.png)

I played around a little. After switching the top screen as main, the situation improved somewhat. Sometimes upon startup the menu's are good, but after moving the window from one screen to the other it becomes a mess. Even so much a mess that the menu can't be opened and the program can't be closed by using the mouse. In this case the menu bar itself is also outside of the title bar, like:
![image](https://user-images.githubusercontent.com/33753713/150174590-e4a777de-5868-4f25-9286-536bd6613895.png)

Also the situation of horizontally aligning the screens does change behavior, and makes it the best. Sometimes even possible of working initially ok, and then after a single move still ok. Also maximize / restore alters the behavior, but as said the least problems when screens are horizontal rather than vertical.

**Comment by ootjersb** [comment] 2022-01-19 17:01
After this I took the nightly build of today, and that version does not have the problem anymore. It seems that something else resolved the issue. It does sometimes have the problem with the menu not appearing in the title bar, but that seems to be different; I think there is a separate issue about that. I am thinking about closing this issue... Just some more testing on a different moment, and if it stays good, then I will close this one.

**Comment by DmitryArefiev** [comment] 2022-01-21 10:33
Glad to hear it! Feel free to close if all good in the master build.

Thank you!

**Comment by cbjeukendrup** [comment] 2023-01-21 17:04
I'll close this because of the long inactivity, and because #13290, which is very similar to this, has been marked as fixed.

@ootjersb If this issue still happens in the latest versions, please let us know.

**Closed by cbjeukendrup** 2023-01-21 17:04 UTC
Labels: P3, community
