### ISSUE TITLE
Even & Odd lyrics styling applying to wrong lyrics

### ISSUE THREAD

**Issue by waltzingbears** [musescore/MuseScore#23974] opened 2024-08-11 05:13 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Have multiple lyric verses
2. Go to Format/Style...
3. Go to Text Styles/Lyrics odd lines
4. Try to set odd lines as bold, notice it sets everything except the first syllable of the even line
5.  If I try to apply the styling to the even lines, only the first syllable gets the styling

Expected behaviour: only the specified lines get the styling.
Maybe similar to https://github.com/musescore/MuseScore/pull/5368?

### Supporting files, videos and screenshots

![Untitled drawing (5)](https://github.com/user-attachments/assets/8f16da26-f3e6-4570-9f8a-8a93e847f488)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-11 05:57
Duplicate of https://github.com/musescore/MuseScore/issues/23846. Fixed in master

**Closed** 2024-08-11 05:57 UTC
Labels: engraving
