### ISSUE TITLE
[MU4 Issue] Crash with RC1

### ISSUE THREAD

**Issue by krtschil** [musescore/MuseScore#14984] opened 2022-12-06 12:46 UTC
I have a problem with one score (s. attached below):
- It takes about 40 seconds for loading the score
- Whether set to MS Basic or Muse Sounds MU 4 crashes when hitting the close button.

Attached: Score and log from console
OS: Linux

**To Reproduce**
1. Open the score
2. Click on X (close the score)
3. MU 4 RC1 crashes
4. MU 4 Nightly crashes as well

**Platform information**
 - OS: Linux
 - 
[muse.txt](https://github.com/musescore/MuseScore/files/10166534/muse.txt)
[The_Inner_Light__Star_Trek.mscz.zip](https://github.com/musescore/MuseScore/files/10166548/The_Inner_Light__Star_Trek.mscz.zip)

**Comment by Tantacrul** [comment] 2022-12-06 12:50
@DmitryArefiev - I can't reproduce on MacOS. Can you reproduce on Linux?

**Comment by krtschil** [comment] 2022-12-06 12:55
I am checking again as this happens with ALL scores at the moment. Try to reboot and check again. Maybe it is a local issue.

**Comment by LuisLiszt** [comment] 2022-12-06 14:29
Can't reproduce it on Windows either...

**Comment by DmitryArefiev** [comment] 2022-12-06 15:11
> @DmitryArefiev - I can't reproduce on MacOS. Can you reproduce on Linux?

Tried on LinuxMint and Ubuntu - all good, no crash

Let's close it now

**Closed** 2022-12-06 15:11 UTC
