### ISSUE TITLE
Metronome Count-in

### ISSUE THREAD

**Issue by RobH1964** [musescore/MuseScore#19193] opened 2023-08-27 23:34 UTC
### Your idea

I would love to see a return of the metronome count-in.  In addition, a two-bar option would be quite useful!

### Problem to be solved

This functionality was taken away in version 4.0; I'm just asking that it be brought back.

**Comment by cbjeukendrup** [comment] 2023-08-28 00:51
This is a duplicate of #9183, so I'll close it. But thanks for reporting anyway!

**Closed by cbjeukendrup** 2023-08-28 00:51 UTC
Labels: feature request
