### ISSUE TITLE
[MU4 Issue] Augmentation dot shortcut doesn't work while editing tablature

### ISSUE THREAD

**Issue by BNTVGL** [musescore/MuseScore#14574] opened 2022-11-17 18:42 UTC
**Describe the bug**
While in note input mode in a tablature, pressing "." to add augmentation dot does not work.

**To Reproduce**
1. Create a new sheet with tablature
2. While in the note input mode, press "." to activate the augmentation dot
3. See that it remains inactive

**Expected behavior**
The augmentation dot should activate 

**Screenshots**

https://user-images.githubusercontent.com/20853843/202531030-6bfe803b-d2d8-47ca-a701-9436dd773c87.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223200405, revision: github-musescore-musescore-4bd88ed

**Additional context**
I am using the Nightly version last modified 2022-11-17 04:27, but I've first noticed this issue when I downloaded the open beta.

**Comment by daijingz** [comment] 2023-03-20 03:35
Can I try to work on this? Seems like it is incomplete still.

**Comment by daijingz** [comment] 2023-03-22 00:24
**My beginning observation**: there is no change in the tablature. Unlike expected behaviours, It doesn't add a note in the given place, and it doesn't have audio displaying (need to have the audio of adding a note). The only existing functionality is the note setting (moving mouse cursors to set up notes)

**My prediction**: two folders have issues: **/framework/audio/** and **/framework/draw/**. I think the first one is responsible for audio display and the second one is responsible for graph rendering.

Let me find the error and fix it

**Comment by deswinteil** [comment] 2023-04-25 03:22
I'm not quite sure how this issue is progressing now,if @daijingz is not solving this problem anymore,Maybe I can try to solve this problem.

**Comment by Jojo-Schmitz** [comment] 2023-04-27 15:25
@deswinteil go for it, @daijingz hasn't come back since some 5 weeks

**Comment by deswinteil** [comment] 2023-04-27 16:26
@Jojo-Schmitz What I first thought was that the keyboard did not respond successfully in the tab spectrum, but I searched for `Qt::Key_Period` in the repo but couldn't find it, so I want to know where the operation of pressing . to toggle the dot is implemented

**Comment by deswinteil** [comment] 2023-04-27 16:32
Ah ,I think I found it, actually it's `pad_dot`

**Comment by deswinteil** [comment] 2023-04-28 00:34
@cbjeukendrup There is a deeper problem, when doing operations on the tab spectrum, the numeric shortcut is setting the taste, not the time value. All the `numeric shortcuts` and` . shortcuts `don't work, which is a conflict that I find difficult to do.

**Comment by rgreen5** [comment] 2023-09-09 13:31
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

Bug still extant in the latest version. Could this be fixed for MS 4.2?

**Comment by cbjeukendrup** [comment] 2023-09-09 13:52
> Could this be fixed for MS 4.2?

You're lucky, it turns out that someone had already contributed a fix that looks good! So that will likely be merged to 4.2.

**Closed** 2023-09-11 17:55 UTC
Labels: good first issue, P2, regression, guitar
