### ISSUE TITLE
Volta brackets cause looping to play the wrong measures.

### ISSUE THREAD

**Issue by infinitejess** [musescore/MuseScore#20388] opened 2023-12-09 22:46 UTC
### Issue type

General playback bug

### Bug description

Looping playback is broken when I use volta brackets. I have a minimal [repro case](https://github.com/musescore/MuseScore/files/13625861/Loop.Repro.zip).

### Steps to reproduce

1. Create a score with a repeating section and at least two different endings.
2. Try to loop playback starting in a measure after the repeats

Expected: playback loops as indicated by the blue arrows.

Actual: an earlier measure plays. In the attached and screenshotted score, I selected one measure at a time and noted what measure actually played:

| Selection | Playback |
| ------ | -------- |
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |
| 4 | 2 |
| 5 | 4 |
| 6 | 2 |

### Screenshots/Screen recordings

![score with playback indicator and looping arrows in different measures](https://github.com/musescore/MuseScore/assets/317879/e8dbd47b-b3c7-42f8-9cef-660d907feeb7)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment] 2023-12-12 15:01
Duplicate of

https://github.com/musescore/MuseScore/issues/16875

**Closed by zacjansheski** 2023-12-12 15:01 UTC
Labels: playback
