### ISSUE TITLE
[MU4 Issue] Disable ability to make panels disappear from re-sizing them

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#15676] opened 2023-01-01 21:22 UTC
**Describe the bug**
You can undock a panel/toolbar and drag to resize it such that it disappears.

**To Reproduce**
1. Undock any panel you like.
2. Resize it so it disappears.

**Expected behavior**
There is a minimum width and/or height so that this does not happen.

**Platform information**
 - OS: Windows 10 64-bit

**Additional context**
It will still display as 'open' (ie checkmarked) in the view panel however.

You can 'get the panel back,' so to speak, by unchecking then rechecking it in the view panel, or closing the score and re-opening it (where I assume the saved workplace re-opens/re-displays the panel.) 

You can also get the panel back by restoring the default layout in the view panel too - forgot to include in video.

https://user-images.githubusercontent.com/102642087/210184886-7866bcf7-82f1-4db0-974c-1cfb148c674c.mp4

**Comment by cbjeukendrup** [comment] 2023-09-07 23:16
I just came across this and realised that it's a duplicate of #10019. Thanks for reporting! (and in the other issue I will refer to the useful video!)

**Closed by cbjeukendrup** 2023-09-07 23:16 UTC
