### ISSUE TITLE
Ghost clef and key signatures are hiding a front part of the score

### ISSUE THREAD

**Issue by spintoai** [musescore/MuseScore#22269] opened 2024-04-08 12:28 UTC
### Issue type

General playback bug

### Bug description

In continuous view, during screen transitions, there are moments where beats are entirely obscured by the ghost clef and key signatures, especially noticeable with longer key signatures (e.g., 6 sharps). Interestingly, this issue did not occur in Musescore3. As a result, I continue to use Musescore3 for displaying scores in continuous view to my students. Could this issue be addressed? It appears to be a problem specific to Musescore4.

### Steps to reproduce

Play any score with long key signature in continuous view -- whenever screen transitions, there will be moments that lyrics (and notes) are hidden. 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/161591394/50f61a18-a9cd-455d-8940-2191ce646fae

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

MacOS 13

**Comment by cbjeukendrup** [comment] 2024-04-08 21:13
Duplicate of #16173 (but you're totally forgiven for not finding that one, because this issue is impossibly difficult to formulate!)

**Closed by cbjeukendrup** 2024-04-08 21:13 UTC
Labels: UI, playback, regression_ms3

**Comment by spintoai** [comment] 2024-04-09 00:56
> Duplicate of #16173 (but you're totally forgiven for not finding that one, because this issue is impossibly difficult to formulate!)

Oh I see. I wasn't aware it was a duplicate, as my search on Google didn't reveal that. It seems this problem was identified over a year ago but still remains unresolved. I'm hopeful for a resolution, given the significance of this issue to me.
