### ISSUE TITLE
3rd Voice Engraving 

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25533] opened 2024-11-16 02:45 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Musescore currently writes the 3rd voice on top of existing voices, when it should be offset. I know that this is a duplicate of #23222 and #24631, but I am mentioning this again as a bug report with the request that it be a first priority fix; it is a ridiculous error that prevents notating great many pieces, especially ones written for organ. 

### Supporting files, videos and screenshots

![17317247641684456139850610784954](https://github.com/user-attachments/assets/165d16d4-55f8-45bc-988a-b9027dede59d)
![17317248819947654132030364663947](https://github.com/user-attachments/assets/7a36bd0e-0759-4e2c-9fb6-049f0a31101d)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445 Revision: eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

An example of where this type of offsetting is absolutely imperative: 
![20241115_213808](https://github.com/user-attachments/assets/de9c3165-0044-4ec7-bac5-f739ff7d0d7b)
(from Chorale pour Grand Orgue, Cesar Franck)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-11-16 05:20
It doesn't "prevent" notating that at all.  You simply need to offset one of the notes, which takes just a couple of clicks (e.g., F2 to put the note in edit mode, then arrow keys as desired).  It's not done by default because there are other cases where you don't want them offset, and it's easier to manually offset them than to manually align them.  Obviously, a feature to automate this process further would be nice, but there are already requests for such a feature.

**Comment by Fourniture** [comment] 2024-11-16 17:30
Then I would suggest that there be an option in "Style" to "Offset 3rd Voice" (along with a distance adjustment box), because manually offsetting the notes is absurd. The user should have to do as little formatting as possible.

**Comment by MarcSabatella** [comment] 2024-11-16 17:52
Yes, that is consistent with what the earlier issue that this is a duplicate of is requesting.  Best to keep any further discussion of how that option might look in that issue and avoid duplicating discussion in multiple places.  But see also https://github.com/musescore/MuseScore/issues/20571 for some previous discussion of the topic and advice on how to proceed in new proposals in this area.

**Closed** 2024-11-16 17:59 UTC
Labels: engraving
