### ISSUE TITLE
[MU4 Issue] I cannot import files which contain a movement divider in MU3 to MU4, it gets stuck on loading

### ISSUE THREAD

**Issue by jlizhiyi** [musescore/MuseScore#14353] opened 2022-11-06 00:31 UTC
**Describe the bug**
Whenever I attempt to open a MU3 file containing a movement divider in MU4, MU4 gets stuck while loading.

**To Reproduce**
1. Create and save a file containing a movement divider in MU3.
2. Run MU4, and try to open that file there.

**Expected behavior**
The MU3 file opens normally in MU4 without crashing.

**Platform information**
 - Windows 11

**Additional context**

**Comment by MarcSabatella** [comment] 2022-11-06 04:21
What do you mean by "movement divider" - a section break, maybe?  I have scores with section breaks that load just fine, so it's probably something else causing the problem.  Best to attach your score (ZIP it first so GitHub will accept it) so it can be investigated.

**Comment by jlizhiyi** [comment] 2022-11-06 14:44
[Viola Concerto - Copy.zip](https://github.com/musescore/MuseScore/files/9946085/Viola.Concerto.-.Copy.zip)

**Comment by MarcSabatella** [comment] 2022-11-06 16:07
I can confirm the attached score is from MU3 and that is contains a section break, and that it does not load into MU4.  It either hangs or crashes.  I have no idea if the section break is related to the inabiltiy to load - other MU3 scores with section breaks load fine.

**Comment by jlizhiyi** [comment] 2022-11-06 18:19
I just removed all figured bass from the file and it loaded fine in MU4!

**Comment by cbjeukendrup** [comment] 2022-11-06 18:45
Nice! And when https://github.com/musescore/MuseScore/pull/14366 is merged, you will be able to load the version _with_ figured bass correctly too!

**Closed** 2022-11-07 08:03 UTC
Labels: P0

**Comment by jlizhiyi** [comment] 2022-11-07 15:10
Cool, so it's fixed?

**Comment by cbjeukendrup** [comment] 2022-11-07 16:43
Yes! You can do two things now: 
- wait until we upload a new beta version to the Muse Hub
- download the latest "nightly build" (actually, you'll have to wait for tomorrow's one, because today's one doesn't include the fix yet). See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds for instructions.
