### ISSUE TITLE
[MU4 Issue] - Arrow keys cause crash

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12835] opened 2022-08-12 20:24 UTC
**Describe the bug**
When attempting to adjust text element within a frame using arrow keys, MU4 crashes. Not sure if this happens with other text elements.

**To Reproduce**
1. Select Lyricist text
2. Use keyboard arrows to move incrementally
3. Program crashes

**Expected behavior**
Text will move incrementally

**Platform information**
 - Windows 11

**Comment by Grillzombie** [comment] 2022-08-13 07:00
No crash on 
OS: Linux Mint 20.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2844416344, revision: github-musescore-musescore-ae252cd

**Comment by MarcSabatella** [comment] 2022-08-13 13:49
Crashes for me on Debian, attempting to move any text element within a frame by clicking then press a cursor key.

**Comment by charlesneimog** [comment] 2022-08-19 01:27
Crash on Windows 11 too (not all times)

**Comment by MarcSabatella** [comment] 2022-08-24 21:32
This crash is no longer 100% reproducible for me.  But, a possibly related crash that is also not totally reproducible: some percentage of the time, up or down arrows will also crash with a *note* selected rather than a *frame text*.  I haven't found specific steps to reproduce, so I'm not opening a new issue yet.  But it happens often enough to be a concern, and I guess it's *possible* the crashes will turn out to be related, as the command to handle the Up and Down keys is - or at least was in MU3 - the same.  So maybe the crash happens in the part of the code responsible for figuring out if we're dealing with text or a note?

**Comment by Tantacrul** [comment] 2022-08-31 21:01
Again, I'm wondering if this is affecting linux worse than mac / pc because I've not managed to reproduce it (yet)

**Comment by MarcSabatella** [comment] 2022-08-31 21:55
I see the crash probably 2-3 times a day when using the up or down keys to transpose a note on Linux, but unfortunately, I can't say what's different about the cases where it happens and the cases where it doesn't.  My sense is that it seems to happens most if it's the very first thing I do upon returning to MuseScore after switching to work on something else for a while.  So, I'll be using MuseScore with no problem, go to type up an email or whatever, then flip back MuseScore, decide to change a note, and it crashes.  That could be a complete red herring, or it *could* be, something to do with loading of soundfonts, and the issue might actually be happening just on clicking the note but I don't see the crash until hitting the cursor key.

But, it just happened on Linux while typing this message, in pretty much exactly that scenario - very thing thing I did upon flipping back to MU4 half way through the above paragraph.  Using last night's build.

I don't use Windows much, but just spend a few minutes playing around with last night's build and haven't seen it crash - yet.

**Comment by MarcSabatella** [comment] 2022-08-31 21:55
Crashing while moving text, though, I don't think I've seen in some time.  It *was* 100% reproducible for me a couple of weeks ago.

**Comment by charlesneimog** [comment] 2022-09-01 14:15
> Again, I'm wondering if this is affecting Linux worse than mac / pc because I've not managed to reproduce it. 

In my test not (I am on PC), if not all the times that I try to change notes using arrows, it crash something like 90%.

**Comment by wizofaus** [comment] 2022-09-03 22:25
Was happening very frequently for me adjusting pitch with either mouse or arrow keys (latest nightly build, Win 11). But now I can't seem to reproduce at all! Very strange/annoying.

**Comment by Tantacrul** [comment] 2022-09-04 07:51
Is there a separate issue about pitches+arrows logged? Can't find one. If not, then it would be great if someone who can reproduce it could log it.

**Comment by wizofaus** [comment] 2022-09-04 08:29
https://github.com/musescore/MuseScore/issues/13159 but those steps didn't reproduce it for me

**Comment by MarcSabatella** [comment] 2022-09-04 18:03
Try the updated steps in that issue.  Dead simple: add note, save, change pitch with arrow key.  Crashes every single time for me on both Linux and Windows.  I added notes about the things that actually prevent the crash - lots of extra things you might be doing that make the change pitch commands *not* crash - but following those exact steps, seems completely reproducible.

**Comment by boryskuzmenko** [comment] 2022-09-05 10:26
Can't reproduce this issue in any way on macOS

**Comment by charlesneimog** [comment] 2022-09-05 13:01
Reproduction of the issue!

Like pointed by Marc Sabatella, **this just occurs after save the score.**



https://user-images.githubusercontent.com/31707161/188455247-be5cc6df-cb1a-47a0-a7d0-fb2e058dc5bb.mp4

**Comment by MarcSabatella** [comment] 2022-09-13 20:55
I don't think any aspect of this is reproducible anymore.

**Comment by Tantacrul** [comment] 2022-09-13 21:10
In that case, I'm going to close this - and if some new problems come to light, we may reopen.

**Closed by Tantacrul** 2022-09-13 21:10 UTC
Labels: P2
