### ISSUE TITLE
[MU4 Issue] Playback Continuity Issue

### ISSUE THREAD

**Issue by SkyJTx** [musescore/MuseScore#15255] opened 2022-12-17 02:54 UTC
**Describe the bug**
A bug is that the playback plays from the start or somewhere else when I change SoundFont.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Mixer'
2. Click on 'Sound'
3. Click on 'SoundFont'
4. Choose any 'SoundFont' that I have
6. See the bug

**Expected behaviour**
It should be continuous like MU3.

**Screenshots**
-

**Platform information**
 - OS: Windows 11

**Additional context**
-

**Comment by Pericival** [comment] 2022-12-17 15:49
This seems similar to https://github.com/musescore/MuseScore/issues/14902 but with only one instrument.

**Comment by cbjeukendrup** [comment] 2022-12-18 03:11
Duplicate of #15244. Thanks for reporting!

**Closed by cbjeukendrup** 2022-12-18 03:11 UTC
