### ISSUE TITLE
Template names in New Score Dialog are not translated

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#16328] opened 2023-02-12 08:03 UTC
I translated the categories and templates in this section into Turkish, they still appear in English.

1. Go to New Score (wizard)- 
3. Create From Template.

we need to see the translated text.

![204106710-63320165-3197-4b3c-943e-8954d959718a](https://user-images.githubusercontent.com/35005568/218299776-9c71ff93-6989-425c-851b-8c4b714f0c01.png)

**Platform information**
 - OS: Windows, Linux

**Additional context**
I wrote earlier in the error number "#13742", but yesterday the error was closed. so I also opened the error again.

**Comment by Jojo-Schmitz** [comment] 2023-05-23 16:29
It isn't really a feature, but a bug, the strings are even on Transifex.
And it is a regression vs. 3.x

**Comment by Jojo-Schmitz** [comment] 2023-05-23 16:54
Hmm, isn't this a duplicate of #14900

**Comment by cbjeukendrup** [comment] 2023-05-23 21:18
Yeah, it is. I'll close it in favour of #14900.

**Closed by cbjeukendrup** 2023-05-23 21:18 UTC
Labels: P2, duplicate, feature request
