### ISSUE TITLE
[MU4 Issue] Closing modified score doesn't prompt if you want to save changes

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8305] opened 2021-06-13 21:15 UTC
**Describe the bug**
Create a new score, add a note (or any other change), then close the score. User is given no warning or opportunity to save changes.

**Expected behavior**
As per MU3, "Save changes to the score 'Untitled' before closing?" should be shown with Yes/Discard/Cancel buttons.

**Desktop (please complete the following information):**
Windows 10, built with MSVC2019

**Comment by cbjeukendrup** [comment] 2021-06-14 12:53
Duplicate of https://github.com/musescore/MuseScore/issues/7660 (but clearer, because that other issue is titled "auto-save", which is the name of a totally different functionality that is also not implemented.)

**Comment by wizofaus** [comment] 2021-06-14 20:36
Ah yes, I saw that one (and assumed it was indeed about auto-save), is there already an actual issue for auto-save not being implemented?

**Comment by RomanPudashkin** [comment] 2021-06-23 14:26
Fixed here:
https://github.com/musescore/MuseScore/pull/8410

**Closed** 2021-06-23 14:26 UTC
