### ISSUE TITLE
[MU4 Issue] Insert multiple measure, push "Enter' after typing number of measure, nothing happen

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14155] opened 2022-10-28 21:02 UTC
Insert multiple Measure : Ctrl+Insert
Type a number of measure to insert
Push "Enter" nothing happen

**Expected behavior**
Validate the insertion as MuseScore 3 do

I need to push "Tab" then push "Enter" (Other Bug, The "Enter" of numpad dont work)

Windows 10, French Keyboard "AZERTY"

**Comment by cbjeukendrup** [comment] 2022-10-28 21:09
This looks like a duplicate of #12222, so let's close this one. Thanks for reporting!

**Closed by cbjeukendrup** 2022-10-28 21:09 UTC
