### ISSUE TITLE
Crash loading specific score

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#17533] opened 2023-05-11 21:20 UTC
### Issue type

Crash or freeze

### Bug description

The attached score crashes on open in current master and has for at least a few days.  Works fine in 4.0.2

[dusk-4-new.zip](https://github.com/musescore/MuseScore/files/11456377/dusk-4-new.zip)

### Steps to reproduce

1. open the attached score
2. crash

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231310304, revision: github-musescore-musescore-60e36f3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

### Additional context

No useful info printed to console.  It's a file that normally takes a few seconds at leas to load for me in 4.02, and the crash happens almost instantly on master.

This score uses Muse Sounds, but I have another version that does not and it crashes too.

**Comment by cbjeukendrup** [comment] 2023-05-11 23:46
I reproduced it in the debugger, and it seems to be the same crash as #17517. So let's close it as a duplicate for now.

**Closed by cbjeukendrup** 2023-05-11 23:46 UTC
Labels: regression, crash
