### ISSUE TITLE
App crash on playback or click on certain elements of specific measures (Linux only+MuseSounds)

### ISSUE THREAD

**Issue by PEM-FR** [musescore/MuseScore#17681] opened 2023-05-22 13:25 UTC
### Issue type

Crash or freeze

### Bug description

Hello, 
I experience this with any version of MS4 on Linux (also tried on nightly 2023-05-21).

Everything was working fine until I decided to copy an oboe set of measures into a flute 2 and a set of violin measures into flute 1.
Not sure which brought the problem or if it is unreleated altogether. But since then, clicking on a note or dynamic (not the crescendos though) makes the app crash everytime, or reaching there with playback makes the app crash randomly.

I am using muse sounds if that matters.

### Steps to reproduce

1. Go to first mesure with notes (69), click on any note, it should crash.
2. Go to measure 68, run playback, it should crash before measure 78 (it is kind of random when playback, not every time)
3. Clicking on crescendo or decrescendo do not seem to make the app crash, everything else should cause the crash

### Screenshots/Screen recordings

[Screencast from 05-22-2023 08:24:26 PM.webm](https://github.com/musescore/MuseScore/assets/623084/67e7e8a6-9664-4f4f-b4a0-6f07a3e6273f)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231420304, revision: github-musescore-musescore-796dc69

### Regression

I don't know

### Operating system

Ubuntu 22.04.2 LTS 64bits, gnome 42.5 Wayland

### Additional context

[Requiem_crash.zip](https://github.com/musescore/MuseScore/files/11531292/Requiem_crash.zip)
[MuseScore_230522_195427.log](https://github.com/musescore/MuseScore/files/11531296/MuseScore_230522_195427.log)

**Comment by DmitryArefiev** [comment] 2023-05-30 16:05
I **can reproduce** it on **LinuxUbuntu 22.04.2LTS** with **MuseSounds**

**Comment by DmitryArefiev** [comment] 2023-05-30 16:07
@PEM-FR Can you reproduce it with MS Basic?

**Comment by PEM-FR** [comment] 2023-05-31 04:57
Hello @DmitryArefiev I tried MS Basic on the file I shared here and it does not crash anymore.
The problem is clearly related to Muse Sounds on Linux

**Comment by DmitryArefiev** [comment] 2023-05-31 09:11
Good. Thank you for checking!

**Comment by PEM-FR** [comment] 2023-06-15 12:04
@DmitryArefiev did you find the issue, do you need more information?

**Comment by PEM-FR** [comment] 2023-07-10 03:24
Hello @DmitryArefiev 
I am just curious if there was any progress on this issue or if it has been planned somewhere in the roadmap :)
Thank you in advance for the check

**Comment by cbjeukendrup** [comment] 2023-07-10 10:34
Since this problem is related to Muse Sounds, this issue will be handled by the Muse Sounds team. So we ourselves don't have any information about progress. But it is certain that it will be fixed at some point :)
Also, since Muse Sounds updates are released independently of MuseScore updates, this can be fixed at any moment and does not necessarily need to wait for a MuseScore release. So if it misses MuseScore 4.1, that doesn't mean it will have to wait for 4.2.

**Comment by PEM-FR** [comment] 2023-07-10 10:40
@cbjeukendrup Thank you for the information.
Is there any way to track the progress of the Muse Sound team? Because we have no alternative on linux other than Muse Sounds, unfortunately. 
Because of that the app crashes, we cannot export to musescore.com, cannot export to mp3 or other unless we drop the bitrate to 32KHz, which, honestly sucks big time.
It's like we have to fallback to MS Basic without all the little things that were possible in 3.6 (which you have to hack it with portable edition and command line in order to avoid the opups opening all the time)

I'm not complaining, just eager to enjoy MS4 with VSTs.
I understand Linux is not top priority, but we are in a kind of "deadlock"

**Closed** 2023-07-14 14:03 UTC
Labels: P1, crash, muse sounds
