### ISSUE TITLE
[MU4 Issue] Spacebar playback always starts from beginning for newly-opened score – ignoring user selection

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12438] opened 2022-07-16 10:11 UTC
**Describe the bug**

Playback _should_ start from the selected note / measure. However, if the score is _newly-opened_ and you click on a note or measure, then press [Spacebar], playback _always_ starts from the beginning of the score.

**To Reproduce**

1. Open attached score. 
[specimen_score.zip](https://github.com/musescore/MuseScore/files/9125541/specimen_score.zip)

2. Click on any note (not at the beginning of the score).
3. Press the [Spacebar].

RESULT: Playback starts from the beginning of the score.

**Expected behavior**

Playback always starts from the selected note or measure.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2680600421, revision: github-musescore-musescore-315cfb3

**Comment by cbjeukendrup** [comment] 2022-07-16 10:24
Duplicate of #11674. Thanks!

**Closed by cbjeukendrup** 2022-07-16 10:24 UTC
