### ISSUE TITLE
MusicXML import ignores custom string data

### ISSUE THREAD

**Issue by brettvachon** [musescore/MuseScore#17185] opened 2023-04-10 10:42 UTC
### Issue type

Other type of issue

### Bug description

I have changed the string data under the Staff/Part properties dialogue for my solo guitar part on Musescore 4. Unfortunatlely this data isn't saved when exporting to MusicXML. If I open this dialogue on the imported MusicXML file, the string data is back to standard tuning.

### Steps to reproduce

1. Create a Guitar with a linked 6 line tablature staff in Musescore 4.
2. Open the staff/part dialogue, click Edit String Data... and change one of the strings to a different note.
3. Export the file to musicXML
4. Open the musicXML file with musescore 4.
5. Click the Edit String Data... dialogue box. The strings are back to standard tuning (E A D G B E)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by lvinken** [comment] 2023-04-25 05:33
Small investigation (using the template for guitar plus tab) shows the problem is on the import side (export looks correct). No regression, same behavior in 3.6.2 and 4.1.0.

**Comment by DmitryArefiev** [comment] 2023-04-28 10:07
> Small investigation (using the template for guitar plus tab) shows the problem is on the import side (export looks correct). No regression, same behavior in 3.6.2 and 4.1.0.

Yes, I tried import to Sibelius, it shows correct numbers on tab stave with modified tuning and MuseScore shows the default guitar tuning when import musicxml file

**Comment by HemantAntony** [comment] 2023-05-07 15:56
@DmitryArefiev I made a fix: #17490 :)

**Comment by DmitryArefiev** [comment] 2023-05-09 11:40
Fixed in #17490

**Closed** 2023-05-09 13:13 UTC
Labels: P3
