### ISSUE TITLE
Slight delay in selecting between note to rest and rest to chord 

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#18792] opened 2023-07-25 03:39 UTC
### Issue type

UI bug

### Bug description

Speed of execution / UI update / Score status update / Sound playback during regular state

### Steps to reproduce

1. Have score with rests and notes in between each other
2. press right arrows or left arrows to navigate between chords and rests (and mouse clicks too) and notice that
3. Between notes/chords, there isn't a delay issue at all. Nor is there when between rests
4. But when going from a rest to a note or a note to a rest, there is a slight delay in the updating of the preferences tab and the selection of the score. Where it also noticeable is the "Sound preview" on the score. (I'm using j and l for left/right here) (Audio is captured also)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/7139517/0a1272d7-13eb-4cfb-a51b-55603ec1645c

The problem seems to be worse going from a *rest* to a *note* rather than a note to rest. 

The cause has something to do with the Properties panel being updated. That is, if I close the properties panel and then perform the same activities, there is a clear distinction: there isn't any noticeable lag:

https://github.com/musescore/MuseScore/assets/7139517/5eab9beb-1919-4e16-b2ed-7011d669168f

Even when it isn't showing, but the tab exists, the lag is there. Would be cool if at least to get the same performance when the tab doesn't have focus.

### MuseScore Version

4.1

### Regression

No.

### Operating system

Lnx XFCE

### Additional context

Something like this has been going on for quite some time (in MS3 also for me) so it is not a regression, but there is room for improvement.

**Comment by bluebear94** [comment] 2024-05-22 16:48
Might be related to #14383.

**Comment by RomanPudashkin** [comment] 2024-07-01 07:12
Duplicate of https://github.com/musescore/MuseScore/issues/14383

**Closed by RomanPudashkin** 2024-07-01 07:12 UTC
Labels: duplicate
