### ISSUE TITLE
[MU4 Issue] Elements often cannot be dragged (if they were previously selected)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10461] opened 2022-02-06 00:11 UTC
As far as I can tell, you cannot change the position of elements by dragging, except sometimes when you can/  Haven't found the pattern yet

1) new score
2) Ctrl+T to add staff text, anything at all
3) now try to drag the text elsewhere
Result: either it drags as expect, or else you are placed into edit mode and dragging isn't possible

I'm sure there is some rule being followed here as to when the click to initiate drag activates edit mode versus actually allowing the drag - maybe it has something to do with how long you wait before moving the mouse, or else it's about where in the text you click, not sure.  But for quite a while I was convinced dragging just plain didn't work at all.  I'm only successful maybe 10-20% of the time.

https://user-images.githubusercontent.com/90187801/162727978-4a84c28c-30e4-4a58-8453-9e276b28a859.mp4

**Comment by rzvxa** [comment] 2022-02-06 20:14
@MarcSabatella Hi, I guess it's happening because the first time you click on the text it's going to drag and also gets selected(color changes), and next time you click on it registers as edit event, is that right?

I'm not sure what is the intended behavior here, i would like to start working on it but need a confirmation from design team or at least a developer whom is informed about these kind of stuffs, i guess it should always drag and goes into edit mode only when you double click on it. Let me know!

**Comment by MarcSabatella** [comment] 2022-02-07 18:58
My expectation until it is explained otherwise is that it works as in MU3 - single click selects, double click edits, drag can be initiated whether the element is current selectly selected or not.

I think what is actually happening is that when not doing a drag,clicking a text element that is already selected puts it in edit mode.  I'm not crazy this as it often causes me to mess up a selection I'm attempting to make, even in 3.6.2 - eg, click one lyric, shift+click another, but I accidentally get thrown into edit mode if the first element was already selected.  But, at least in 3.6.2, starting a *drag* is possible even if the element is already selected - the element doesn't go into edit mode until mouse *up*.

So, I think that's the actual explanation here - edit mode in MU4 is being triggered on mouse *down* instead of mouse *up* for already-selected elements, making drag impossible.   Changing it should fix this.

I can't swear that explains all the cases I say where drag didn't work, but I'll be on the lookout now that I have a better understanding.

**Comment by DmitryArefiev** [comment] 2022-04-11 11:14
That also occurs on my side. The main condition to reproduce is select the object at first and then start dragging.
Added video demo to the description (with comparing how it works in MU3)

**Comment by DmitryArefiev** [comment] 2022-04-12 15:18
Fixed in #11163

**Closed** 2022-04-13 09:51 UTC
Labels: P1
