### ISSUE TITLE
Brass mutes in musesounds don't work if the note has an accent

### ISSUE THREAD

**Issue by PholMC** [musescore/MuseScore#21221] opened 2024-01-25 21:47 UTC
### Issue type

Muse Sounds bug

### Bug description

With brass mutes in musesounds being finally supported since MS 4.2, for some reason, if the part has a mute with the notes being accented, then the muted brass sound doesn't play, instead it just plays the open accented sound. Every instrument in Muse Brass is affected. Somehow the issue persists for solo Trumpet but not for the Trumpet**s**. Trumpets: mute sound goes through but I don't hear an accent. I can't tell if the Tuba is affected as well.

### Steps to reproduce

1. Open this score: 
[Untitled score123.zip](https://github.com/musescore/MuseScore/files/14057965/Untitled.score123.zip)
2. Play with every Muse Brass part there is and listen to each part individually.

To reproduce:
1. Create a score with Horn in F, Trumpet, Trombone (and Bass), and Tuba
2. Mark some quarter notes with and without accents.
3. Put the mute text over the accented notes.
4. Assign musesounds brass to the parts and play.

### Screenshots/Screen recordings

https://www.youtube.com/watch?v=FKueLMRmlUU

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Just thought I should put this here too: Someone probably reported this already but the Muse Brass mutes sound a little too quiet. Particularly, the trumpet mutes. If you guys could crank up the volume, that would be great :)

**Comment by oktophonie** [comment] 2024-01-26 08:30
Duplicate of https://github.com/musescore/MuseScore/issues/20602

**Closed by oktophonie** 2024-01-26 08:30 UTC
Labels: muse sounds
