### ISSUE TITLE
Incorrect playback tempo if the tempo is specified for something other than a quarter note

### ISSUE THREAD

**Issue by georggleixner** [musescore/MuseScore#25042] opened 2024-10-04 14:58 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. create new score
2. in the assistant set the tempo to e.g. _half_ note = 125
3. the playback tempo (which is also shown at the top right) is: _quarter_ note = 125
The BPM entered is always assigned to a _quarter_ note.
When changing the tempo text in the score, the new value is calculated correctly.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/9e095c66-8a18-4163-940f-9084a8c075b2)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment] 2024-10-08 13:01
Closing as duplicate of https://github.com/musescore/MuseScore/issues/14678

**Closed by zacjansheski** 2024-10-08 13:01 UTC
Labels: regression MS3, UX/interaction
