### ISSUE TITLE
[MU4 Issue] Search result shows empty palettes

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7633] opened 2021-03-05 18:09 UTC
**Describe the bug**
Search results even if there is no match - it shows empty palettes

**To Reproduce**
1. Create a score
2. Open "palettes" tab on the left side panel
3. Enter "2" or "ch" or "dd" in a palettes search field

**Expected behavior**
Empty slots and palettes should not be shown if there is no match with letters in search field

**Screenshots**
![image](https://user-images.githubusercontent.com/71372310/110155530-ce35ef00-7df6-11eb-878d-14d484df26bb.png)
![Скриншот 21-12-2020 14 31 20](https://user-images.githubusercontent.com/71372310/110155531-cece8580-7df6-11eb-9086-4154bac86f8b.png)
![Скриншот 21-12-2020 14 33 05](https://user-images.githubusercontent.com/71372310/110155535-cece8580-7df6-11eb-89b8-e1dff764b231.png)

**Desktop (please complete the following information):**
Windows 10 x64, 
MacOS

**Comment by wizofaus** [comment] 2021-06-14 21:23
Can't reproduce:
ch - shows the french violin clef
dd - shows a bunch of palette commands that have "add" in their name
2 - shows a bunch of palette commands that have 2 in their name
xy - shows no palette commands at all as expected

Propose this should be closed as already fixed.

**Comment by wizofaus** [comment] 2021-06-28 10:23
...however it does seem that adding items to the score from any palette in search mode doesn't work...

**Closed** 2021-06-28 11:32 UTC
Labels: P2
