### ISSUE TITLE
[MU4 Issue] Playback partially restarts

### ISSUE THREAD

**Issue by CodeSpoof** [musescore/MuseScore#16121] opened 2023-01-29 05:31 UTC
**Describe the bug**
After changing from Muse Sounds to MS Basic during playback, the changed instrument starts playing from the beginning, while the others just play on.

**To Reproduce**
1. Write score with at least two parts
2. Change one to Muse Sounds
3. Start playback
4. Without stopping change it back to MS Basic

**Expected behavior**
Synchronised playback of all instruments, continueing without reseting to the beginning

**Platform information**
 - OS: Ubuntu 22.04

**Additional context**
Used score: [https://musescore.com/user/30122274/scores/6078560](https://musescore.com/user/30122274/scores/6078560)
Changed (Echoes Synthesizer) to (Muse Sounds -> Muse Harp -> Harp)

**Comment by cbjeukendrup** [comment] 2023-01-29 13:48
This is a duplicate of #14902 and the other issues linked to that one. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-01-29 13:48 UTC
