### ISSUE TITLE
Menu opening on wrong screen when MuseScore is maximized.

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14405] opened 2022-11-08 04:36 UTC
**Describe the bug**
When Musescore is maximized, some menus open on the wrong screen.  I think this might be more of a QML problem than a MuseScore bug, but it is affecting my usage.

**To Reproduce**
I have a multi-monitor setup on my home machine with Musescore open in my center screen and two other screens to either side.  

- Open Musescore and maximize it
- Open a score
- Click on the Add Palettes button
- The add palettes menu appears on my rightmost screen, not the screen running musescore.

**Expected behavior**
The popup menu should appear beneath the Add Palettes button.

**Platform information**
Windows 10

**Comment by blackears** [comment] 2022-11-08 05:35
This also happens when I select drop down menus from the top bar.

**Comment by oktophonie** [comment] 2022-11-08 08:44
Closing as a duplicate of [#13940](https://github.com/musescore/MuseScore/issues/13940) (but thanks for the context that this adds)

**Closed by oktophonie** 2022-11-08 08:44 UTC
