### ISSUE TITLE
Can't open page settings menu

### ISSUE THREAD

**Issue by Alge** [musescore/MuseScore#19804] opened 2023-10-23 11:25 UTC
### Issue type

Choose option...

### Bug description

When trying to open the "page settings" or "style" menu found under "Format", a window pops up for a fraction of a second before disapearing.

I'm using the 4.1.1 appimage. I also tried this in the latest nightly build a couple of days ago with the same behavior.

### Steps to reproduce

Click on "Format" -> "Page settings..."

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Ubuntu 23.04

### Additional context

```
13:21:20.120 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationOpened
13:21:20.122 | ERROR | main_thread | NavigationController | requestActivateByName: not found control with name: , panel: ScoreView, section: NotationView
13:21:20.122 | INFO  | main_thread | NavigationController | requestActivateByName: "has:\nScore\n" 
13:21:20.123 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationFocused
13:21:20.123 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationFocused
13:21:20.123 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: page-settings
13:21:20.132 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxUnknown
13:21:20.139 | DEBUG | main_thread | Score      | startCmd: Score::startCmd(): cmd already active
13:21:20.146 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationFocused
13:21:20.164 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxUnknown
13:21:20.171 | DEBUG | main_thread | Score      | startCmd: Score::startCmd(): cmd already active
13:21:20.174 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxUnknown
13:21:20.176 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationFocused

```

**Comment by cbjeukendrup** [comment] 2023-10-23 11:30
This reminds me of https://github.com/musescore/MuseScore/issues/18608, which was closed as not planned because it turned out to be outside our control. Is it possible that this is a duplicate of this issue, or are you not using Wayland?

**Comment by bkunda** [comment] 2023-10-24 13:15
Will close for now. Happy to reopen if it ends up being materially different from #18608.

**Closed by bkunda** 2023-10-24 13:15 UTC
