### ISSUE TITLE
If you create a new workspace the palettes and their contents are reset to the default ones

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16867] opened 2023-03-16 18:14 UTC
### Issue type

UI bug

### Bug description

If you add new palettes to the default workspace and edit the arrangement and number of their contents you might expect this set-up to be exactly duplicated when you create a new workspace.

However this is not the case. The new workspace is not based on the existing one but starts with the default palettes and contents.

### Steps to reproduce

1. Start with the default palettes and contents.
2. Add some new palettes to the list using the **Add palettes** button
3. Rearrange the order of a few of them
4. Click on the workspace area of the status bar
5. Press **Create new workspace** then **Select** and **Select** to exit the dialog.

ACTUAL RESULT: The new workspace has reverted to the default one.

EXPECTED RESULT: The new workspace should be a duplicate of the existing workspace set-up modified by the options chosen by the user in **Create new workspace** dialog.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64.

**Comment by DmitryArefiev** [comment] 2024-01-22 12:19
Duplicate of #12822

**Closed** 2024-01-22 12:19 UTC
Labels: UI, palettes
