### ISSUE TITLE
When open 3.x scores with custom parts in 4.2, the parts order is wrong and some parts are missing

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19637] opened 2023-10-06 08:46 UTC
### Issue type

Import from 3.x/Parts issue 

### Bug description

@avvvvve found a fresh regression with parts when import 3.x scores to 4.2

### Steps to reproduce

1. Open [orch.zip](https://github.com/musescore/MuseScore/files/12828769/orch.zip) in 4.2 master build (it contains **woodwinds**, **brass** and **strings** group custom parts)
2. Open Parts dialog - **Flutes** is replaced with **woodwinds**, **Horns in F** is replaced with **brass**, **Violin I** is replaced with **strings**

### Screenshots/Screen recordings

in **4.2 master**

![4 2](https://github.com/musescore/MuseScore/assets/90187801/b26c3dfa-0d52-47b8-9d8b-d2337e14b79a)

in **4.1.1 release build** (expected)

![4 1 1](https://github.com/musescore/MuseScore/assets/90187801/46ec442a-5b34-44b2-9937-6b8b6741bf4f)

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

Windows 10

**Comment by sammik** [comment] 2023-10-06 11:54
Well, I am quite sure, it is caused by my #15708 and it is, at least from my side, intended.

This was my thought:
We have old score with some costomised pasrts, like here, 
- missing Violin 1 
- extra strings

We cannot know, if user wanted
1. replace Violin 1 by strings
or
2. remove Violin 1 and add extra strings
or
3. forgot Violin 1 and added extra strings

Before my PR, after import
- user is forced to have both, Violin 1, and strings. It is OK, if 3. were true
- but not OK, if 1., or 2. were true, because Violin 1 was generic = unremovable, and only customised part called strings is removable (so user is forced to or lost customisations, or to have extra unwanted part)

After my PR, after import
1. - OK
2. - OK
3. - user can choose 
a) reset strings part and rename it - will have default Violin I
b) leave it, as it was - user has exactly, what he had in MU3
c) if he really forgot to add Violin 1, he can duplicate strings (to get customised strings version) and than reset generic strings and rename it to Violin I
so resul OK

So I thought, "after PR" would be better, because it covers all possible situations (even if default one may be not intended one sometimes).

**Comment by avvvvve** [comment] 2023-10-06 13:14
Hi @sammik! I'm seeing that in #15707 you wrote

> if name doesn't match, check, wheater Part ("Excerpt") contains only one Instrument "Part". Is yes, use saved Part as generic.

In Dmitry's example, the parts **woodwinds**, **brass**, and **strings** do _not_ contain only one instrument—there are 2-5 instruments in each part—but it appears that they are still saving over the generic slot. This does not seem to be your intended behavior.

If the **strings** part _only_ contained Violin 1, then yes, the generic Violin 1 part should be renamed to 'strings'. But we should not replace the generic single-instrument parts in 4.1 with multi-instrument parts. Instead, the multi-instrument parts should be at the bottom of the parts list.

**Comment by sammik** [comment] 2023-10-06 13:25
> Hi @sammik! I'm seeing that in #15707 you wrote
> 
> > if name doesn't match, check, wheater Part ("Excerpt") contains only one Instrument "Part". Is yes, use saved Part as generic.
> 
> In Dmitry's example, ... there are 2-5 instruments in each part—but it appears that they are still saving over the generic slot. This does not seem to be your intended behavior.
> 

@avvvvve please see [comment](https://github.com/musescore/MuseScore/pull/15708#issuecomment-1673959024), it was extended by second commit.

I thought, if it is possible to have "Violin 1" part containing multiple instruments in MU4, it should be OK to have it also in imported scores.

It was dilema: unrepairable vs repairable error (as described above here)
I choosed later

**Comment by Jojo-Schmitz** [comment] 2023-10-06 13:34
Duplicate of or at least related to #15910

**Comment by sammik** [comment] 2023-10-06 13:42
> Duplicate of or at least related to #15910

@Jojo-Schmitz If I understand, it is a bit oposite. Your issue should be fixed in master, but this issue is side effect of the [fix](https://github.com/musescore/MuseScore/pull/15708).

So yes, related. :)

**Comment by Jojo-Schmitz** [comment] 2023-10-06 13:46
Nope, my issue is not fixed in master

**Comment by sammik** [comment] 2023-10-06 13:48
> > Duplicate of or at least related to #15910
> 
> @Jojo-Schmitz If I understand, it is a bit oposite. Your issue should be fixed in master, but this issue is side effect of the [fix](https://github.com/musescore/MuseScore/pull/15708).
> 
> So yes, related. :)

Oh, and I may be wrong and it may be also related with #13824

**Comment by Jojo-Schmitz** [comment] 2023-10-06 13:49
Actually it is, even with 4.1.1, except for some additional parts, which are gone in master

**Comment by sammik** [comment] 2023-10-06 13:52
> Actually it is, even with 4.1.1, except for some additional parts, which are gone in master

I thought, setting was lost. It seems I was totally wrong about it. 
May be, you could post affected score there.

**Comment by bkunda** [comment] 2023-10-09 12:36
From what I can currently see, it's not so much that the parts are "missing", or even in the wrong order, but rather that they are generic parts that have been overwritten by parts bearing different names and instruments.

It's worth noting that you can achieve exactly this result in an MS4 score. Here's one I just made where the generic flute part has been changed:

<img width="1471" alt="Screenshot 2023-10-09 at 2 26 22 pm" src="https://github.com/musescore/MuseScore/assets/86290556/75f22f0d-7a94-42a7-9b1b-d9bd95c40d96">

The user has this control already in MS4, so I don't think it's such a problem if parts with custom names and instruments made in earlier versions appear as such on import...

..._so long as_ it remains possible to reset these parts to their generic state (as defined by MS4). This means if the user "resets" a generic part that has been overwritten or changed:

- The part name returns to its generic MS4 state (not to what the score creator might have named it in earlier versions of MS)
- Only the default instrument assigned to that generic part is shown
- Any other instruments in that part are hidden

Maintaining the generic parts plays an important role in how the new parts system works. If an ensemble contains a "flute", but it is not possible to open a "flute" part containing only a flute in the Parts dialog, then the system is broken.

It's worth noting that "Reset" parts currently doesn't work properly in MS4 (see https://github.com/musescore/MuseScore/issues/16532 and https://github.com/musescore/MuseScore/issues/19647). These issues will probably need to be fixed in order to properly support this new implementation. 

In the file attached to this issue, it is possible to rename the "woodwinds" part to "flutes", and to hide the oboes, clarinets and bassoons such that it becomes the original "flute" part, which is good. All this should happen simply by "resetting" the part, though. 

We could even consider a "reset all parts" function that covers an entire score in one go.

If it's not possible to do this, however, then I think we should consider reverting https://github.com/musescore/MuseScore/pull/15708, allowing us to maintain this basic behaviour: 
 
- If a part name matches one of MS4's generic part names, then the imported part will overwrite our generic part in order to avoid duplicated parts
- If a part name does not match one of MS4's generic part names, it will not overwrite any generic parts and will appear at the bottom of the list in the parts dialog (since we don’t have any options for re-ordering of parts).

**Comment by bkunda** [comment] 2023-10-11 09:35
Given that the above mentioned issues concerning resetting parts – which I think will be helpful to support the implementation suggested in https://github.com/musescore/MuseScore/pull/15708 – are not in the immediate pipeline for resolution, my suggestion is to revert #15708 for now so we avoid the confusion around generic parts appearing to no longer being available.  

I believe that should resolve this issue. We can then re-consider #15708 once the ability to properly reset parts has been implemented. 

FYI @DmitryArefiev @sammik 
@cbjeukendrup for your action please.

**Comment by cbjeukendrup** [comment] 2023-10-11 14:35
@bkunda You can try the builds from https://github.com/musescore/MuseScore/pull/19683 (when they are ready) to check if reverting https://github.com/musescore/MuseScore/pull/15708 does indeed solve the problem

**Closed** 2023-10-13 23:01 UTC
Labels: P1, regression

**Comment by sammik** [comment] 2023-10-14 08:41
One additional case study:

You can get same (wrong) result even now, after revert.

1. If there are no Violin _I_ and Violin _II_, just Violin and Violin, which is default behaviour in scores pre 3.5, and also could happen even in 3.6.2 
2. If Excerpt name uses same root as parts has **Violin**s (not Strings)


https://github.com/musescore/MuseScore/assets/1646034/77d09b3b-78bd-4475-98f8-28e77a6b91e1

So may be temporary logic should be:
1. Excerpt name machtes exactly part name
2. Excerpt contains only one isntrument
3. Excerpt Has same Name root
(or some combination of 2. and 3.)

@cbjeukendrup @bkunda @DmitryArefiev
