### ISSUE TITLE
Play toolbar icons overlap. 

### ISSUE THREAD

**Issue by lb-d** [musescore/MuseScore#21856] opened 2024-03-07 13:31 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

![Screenshot from 2024-03-07 14-19-29](https://github.com/musescore/MuseScore/assets/40788882/fb6a036c-c722-411c-a103-14ee57b84f8c)

I use the latest musescore from flathub running on Debian 12 using gnome. This happens independent of the window being maximized or not, and of the bar being docked or floating. Other than that the UI works great and I don't see any of this behaviour in other parts of the program, only the play toolbar.

And great job on the UI guys. I love opening musescore because it's such a pretty program.

### Steps to reproduce

Have no idea.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Debian 12

**Comment by MarcSabatella** [comment] 2024-03-07 13:42
Does the problem persist when using the official AppImage build?  Third-party builds often show problems not present in official builds, and others have reported this particular issue with Flatpak before - see https://github.com/musescore/MuseScore/issues/21036, and also https://github.com/flathub/org.musescore.MuseScore/issues/119.

**Comment by lb-d** [comment] 2024-03-08 11:49
Your right, it is a flatpak issue. I downloaded the appimage version and that displays everything correctly. 
I'll see if the gnome guys have some solutions to this and report back if I find anything.

**Comment by Eism** [comment] 2024-03-22 07:56
Duplicate of https://github.com/musescore/MuseScore/issues/21036
Thank you for reporting!

**Closed by Eism** 2024-03-22 07:56 UTC
Labels: UI, community, os: linux
