### ISSUE TITLE
[MU4 Issue]crash when export svg

### ISSUE THREAD

**Issue by enochenoch** [musescore/MuseScore#15138] opened 2022-12-13 00:52 UTC
crash when export svg

**Comment by Eism** [comment] 2022-12-13 07:27
@enochenoch 
Please follow the template when creating an issue and complete at least these fields. 

**To Reproduce**
Steps to reproduce the behavior
**Platform information**

Anyway, I can't reproduce on macOS. Please attach a score on which you have a crash.

**Comment by CarlGao4** [comment] 2022-12-13 08:21
@Eism Maybe this person encountered the same issue as #15142

**Comment by abariska** [comment] 2022-12-15 16:35
Can't reproduce also. macOS and Ubuntu

**Comment by zacjansheski** [comment] 2023-05-26 20:55
Closing due to lack of information and lack of reproducibility.

**Closed by zacjansheski** 2023-05-26 20:55 UTC
Labels: needs info
