### ISSUE TITLE
[MU4 Task] Playing from selected bar

### ISSUE THREAD

**Issue by RafaelLiebermann** [musescore/MuseScore#11481] opened 2022-04-30 19:08 UTC
Just like Muse Score 3 we should be able to start playing when we have a bar selected instead of a note. Currently, when you have a bar selected and hit play it starts from the last note you've selected instead of the begining of the bar.

**Comment by Tantacrul** [comment] 2022-04-30 19:53
Closing because the issue isn't clear. If there is a bug, articulate the bug in the way others are doing.

**Closed** 2022-04-30 19:52 UTC

**Comment by MarcSabatella** [comment] 2022-04-30 20:54
@RafaelLiebermann , I assume you mean that if you select a measure (bar) instead of a note before commencing playback, playback ignores the selection and continues from where it left off.  This is a known bug in the alpha.

The plan is that this will indeed be fixed - the selection will no longer be ignored.  But the behavior will be different than in MuseScore 3.  Instead of playing the full score normally from the selected location, it will play only the selected staff.

**Comment by RafaelLiebermann** [comment] 2022-05-01 08:55
Yeah that's exactly it

**Comment by cbjeukendrup** [comment] 2022-05-01 12:09
Will be fixed in #11322.
