### ISSUE TITLE
 Swap With Clipboard issue

### ISSUE THREAD

**Issue by brettvachon** [musescore/MuseScore#17643] opened 2023-05-19 10:13 UTC
### Issue type

UI bug

### Bug description

The Swap With Clipboard feature shows a strange UI bug and doesn't seem to work properly. Or maybe I am using the option incorrect? 
I assumed it swaps my selection on the staff with the music I had in the clipboard. Instead it makes it impossible to select the staff. 

### Steps to reproduce

1. Create a part with two staves - a piccolo part and a piano part. I chose a 6/8 time signature. Enter four measures of music into each part.
2. Select the piano part by clicking inside the first measure and using shift+select to click the last measure and select all the measures
3. Ctrl+C to copy the selection
4. Select the piccolo part by clicking inside the first measure and using shift+select to click the last measure and select all the measures
5. Choose edit - swap with clipboard
6. I'm assuming now that the original piccolo part is in the clipboard, because the piano part just got pasted. 
7. Select the first measure of the piano part, hold down shift and select the last measure of the piano part to select all the measures.
8. Pressing Ctrl+V does nothing. The selection disappears.
9. I am unable to click inside the measure to select it anymore. Double-clicking just goes to note selection. Even lasso selection does not work.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2023-05-19 10:15
Duplicate of #17000, which has been fixed. The fix will be included in the next update!

**Closed by cbjeukendrup** 2023-05-19 10:15 UTC
Labels: UI
