### ISSUE TITLE
Grace note rendering not correct with two voices

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#20679] opened 2023-12-23 19:48 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

See attached image.  The 16th grace notes in the two voices should be aligned (E-C, F-D) but are rendered in succession, instead of placed on top of each other.  This makes it look incorrectly like 4 grace notes to be played in succession instead of together.  If the second grace note in the second voice is dropped by a step (from D to C), then it renders as would be expected.

### Steps to reproduce

1. Load the attached mscz file.
2. Observe how the grace notes are rendered sequentially instead of aligned on top of each other.

### Screenshots/Screen recordings

![grace note rendering](https://github.com/musescore/MuseScore/assets/137847641/ece002af-531a-4ca5-9a29-e7e945c71a93)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 10 Home 10.0.19045 Build 19045

### Additional context

[grace note rendering.zip](https://github.com/musescore/MuseScore/files/13760073/grace.note.rendering.zip)

**Comment by oktophonie** [comment] 2023-12-23 19:54
duplicate of https://github.com/musescore/MuseScore/issues/15326

**Closed by oktophonie** 2023-12-23 19:54 UTC
Labels: engraving
