### ISSUE TITLE
[Muse Hub]Can't open Muse Hub on Ubuntu 22.10

### ISSUE THREAD

**Issue by yuki0035** [musescore/MuseScore#13955] opened 2022-10-24 04:18 UTC
**Describe the bug**
Cannot open Muse Hub after installing it from the .deb package.Nothing happen after clicking on the Muse Hub icon.

**Platform information**
 Ubuntu 22.10 ''Kinetic Kudu''

**Comment by llui85** [comment] 2022-10-24 05:08
Duplicate of #13909

**Comment by Tantacrul** [comment] 2022-11-10 15:50
Duplicate of https://github.com/musescore/MuseScore/issues/13909

**Closed by Tantacrul** 2022-11-10 15:50 UTC
