### ISSUE TITLE
Add courtesy accidentals to a notes automatically 

### ISSUE THREAD

**Issue by jdfergusson** [musescore/MuseScore#21017] opened 2024-01-15 08:34 UTC
### Your idea

I do quite a lot of typing out old scores into musescore for formatting, and I typically use the keyboard for entry.

Quite often while typing, I want to enter a courtesy accidental, that is a bracketed accidental that is a reminder that the pitch of the note has changed from what was played in the previous bar (or indeed in another part) back to the default pitch given by the current key signature.

At the minute, this is the only operation when I'm typing out a line of music that I have to switch to the mouse to do, and then it's several mouse clicks away. Ideally this:

- Calculates the correct accidental automatically (i.e. work out whether the note is sharp, natural or flat in the given key signature) 
- Adds a bracketed accidental in a single action
- Could then be assigned a keyboard shortcut
- Acts on the either the currently selected note, or the last note that was entered, if you're in note input mode.

I'm aware of the courtesy accidental plugins, but these do not allow for fine-grained control over what you're doing. See [this discussion](https://musescore.org/en/node/358714#comment-1221803) for more information

### Problem to be solved

Adding courtesy accidentals takes too many mouse clicks, and takes mental calculation when it could be done by MuseScore

**Comment by oktophonie** [comment] 2024-01-15 09:09
Duplicate of https://github.com/musescore/MuseScore/issues/12859

**Closed by oktophonie** 2024-01-15 09:09 UTC
Labels: feature request

**Comment by jdfergusson** [comment] 2024-01-16 21:27
I have written this which fulfils my requirements: https://musescore.org/en/project/naive-courtesy-accidental-adder
