### ISSUE TITLE
Some notes don't play during playback (MuseSounds overlapped notes)

### ISSUE THREAD

**Issue by adamglazier** [musescore/MuseScore#18732] opened 2023-07-20 15:20 UTC
### Issue type

Choose option...

### Bug description

I created a very simple piece and entered some notes with the keyboard, but some notes are randomly silent. In the example attached, the 3rd note on the bass line is always silent in my. I wondered if this was an issue of some key I accidentally pressed that silenced the note, so I recreated the sequence again and still have the same problem.

### Steps to reproduce

1. Enter the notes from my sequence
2. Playback the piece

### Screenshots/Screen recordings

[silent note.mscz.zip](https://github.com/musescore/MuseScore/files/12111255/silent.note.mscz.zip)

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Ventura 13.4.1

**Comment by MarcSabatella** [comment] 2023-07-20 18:16
Thanks for reporting this, it's actually a known issue in Muse Sounds only that happens if that same note is currently being sustained in another voice or staff as is the case here.  See https://github.com/musescore/MuseScore/issues/15306

**Comment by DmitryArefiev** [comment] 2023-07-21 09:17
Thanks Marc for adding the info, I see too it's the same 
Closing as duplicate



https://github.com/musescore/MuseScore/assets/90187801/470709c3-b8f4-438d-9530-ee9a12b737c7

**Closed** 2023-07-21 09:18 UTC
Labels: duplicate

**Comment by edwardoneill** [comment] 2023-07-27 11:28
This is a constant issue. Why is it closed?

**Comment by adamglazier** [comment] 2023-07-27 11:36
I’m just not going to use Muse Score anymore due to this issue.

**Comment by RobFog** [comment] 2023-07-27 11:37
This issue was closed as a duplicate of #15306 as mentioned in the two comments above yours by Marc and Dmitry. So I would suggest following #15306.

**Comment by MarcSabatella** [comment] 2023-07-27 13:41
Note also that this is only an issue in Muse Sounds, so no need to give up MuseScore - just switch to a different sound for piano if you need to use this particular type of notation.

But note also that while there are situations where these overlaps can make sense and a human player will understand they need to ignore the original duration and cut it short to restrike the key later, it's usually better to not notate things in a way that requires them to go through that  In your example, really there is no good reason for that first G to have been a half note when it can't actually be sustained for two beats,  A better notation might be to split the chord into two voices, with the E & B in voice one as a half note, and the G in voice 2 as a quarter.  Then it won't similarly confuse human players.  Again, players will generally figure out the intent anyhow, but still, it's best to avoid this situation where possible.
