### ISSUE TITLE
[MU4 Issue] Crash after actions with Mixer (one score)

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12549] opened 2022-07-25 15:45 UTC
**To Reproduce**
1. Open the test score (Mixer should be opened by default)
[The_Avengers_Theme_Song_full_orchestra.mscz.zip](https://github.com/musescore/MuseScore/files/9182694/The_Avengers_Theme_Song_full_orchestra.mscz.zip)

2. Pinch in the score (to decrease zoom)
3. Change the top Mixer side up or down 
4. Close the Mixer (if no effect open Mixer and close again few times)

**Expected behavior**
No crash after any actions with Mixer

**Screenshots**

https://user-images.githubusercontent.com/101250347/180819375-88450562-e415-4a2a-8fb3-405c6250abcb.mov

**Comment by wizofaus** [comment] 2022-07-26 22:10
I get `
![image](https://user-images.githubusercontent.com/5364225/181120934-c5aadc8e-01bd-404b-98fc-65460fa44a3f.png)
`

**Comment by wizofaus** [comment] 2022-07-26 22:20
Ah ok, I got it to happen once - after *resizing* the bottom-docked mixed window by dragging the top border up and down, then closing. But still can't reproduce.

**Comment by DmitryArefiev** [comment] 2024-09-27 15:39
Tested Mac13.6 in **4.4.2** and **4.4.3** builds. Crash **doesn't occur**

**Closed by DmitryArefiev** 2024-09-27 15:39 UTC
Labels: P1
