### ISSUE TITLE
the mixer is in different order that of the score. For an example the score begins with flute 1, and the mixer begins with bass drum instead, flute 1 and 2 are found in the middle of the score (orchestral score)

### ISSUE THREAD

**Issue by JosephZayoun** [musescore/MuseScore#12457] opened 2022-07-18 17:08 UTC
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by JosephZayoun** [comment] 2022-07-18 17:10
Mac user

**Comment by HemantAntony** [comment] 2022-07-18 17:36
This issue is a duplicate of #11320. Also, please don't use a title this long. Just put it in the description

**Closed** 2022-07-18 17:38 UTC
