### ISSUE TITLE
[MU4 Issue] Move MuseScore 4 between multiscreen will get an extra menu bar 

### ISSUE THREAD

**Issue by tony031** [musescore/MuseScore#13190] opened 2022-09-06 05:09 UTC
**Describe the bug**
I have two screens when I move the app across the screen, the app will get an extra line on the menu bar, and the actual menu bar and toolbar should move one line above, locate on the looks empty line, then you have to maximize the window and shrink it back to get it normal...
I don't know if this is a bug or just only happens to me?

p.s. My two screen are different resolution settings

**To Reproduce**
1. Just move the windows across screen

**Platform information**
 - OS: [Windows 10]
![titlebar_02](https://user-images.githubusercontent.com/22543571/188551572-5f7a37dd-3c89-4154-90e2-f62f3513fbba.jpg)

**Comment by Eism** [comment] 2022-09-06 08:25
Duplicate of https://github.com/musescore/MuseScore/issues/9968
Thanks

**Closed by Eism** 2022-09-06 08:25 UTC

**Comment by cbjeukendrup** [comment] 2022-09-06 08:46
This looks like it is exactly the same problem as #9968. Let's close this one as a duplicate of the other. Thanks for reporting!
