### ISSUE TITLE
[MU4 Issue] Changing instrument names is incredibly laggy

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14329] opened 2022-11-05 13:24 UTC
There is a lot of lag when changing the name of an instrument inside the instruments tab. it makes my CPU spike.

- OS: Windows 10
- Specs: RAM: 32,0 GB (31,9 GB usable)
              CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz

**Comment by oktophonie** [comment] 2022-11-07 18:43
The problem here is that the entire score is being reformatted after each keystroke. As such, I'll close this as a duplicate of https://github.com/musescore/MuseScore/issues/13276 (but thanks for this, as another useful example!)

**Closed by oktophonie** 2022-11-07 18:43 UTC
