### ISSUE TITLE
[MU4 Issue] Chords don't seem to play on EP and mallet instruments when transfered from musescore 3

### ISSUE THREAD

**Issue by dyyap** [musescore/MuseScore#12787] opened 2022-08-11 09:39 UTC
**Describe the bug**
When having score from musescore 3, if there is a chord on EP or Mallet instruments it will just play single notes. 

**To Reproduce**
1. Open a score from musescore 3 with EP or mallet
2. Try and play a score
3. If needed make a new score and copy and paste the chord into the new score and it will still play a single note

**Expected behavior**
Play a chord instead of a single note. 

**Platform information**
Windows

**Comment by MarcSabatella** [comment] 2022-08-11 13:14
Can you post the score?  If these chords are tied, this is a known problem that affects all scores, not just ones from MuseScore 3 and not just those instruments.

**Comment by dyyap** [comment] 2022-08-11 17:51
![musescore issue](https://user-images.githubusercontent.com/35153938/184201518-2fef644b-c589-45fb-a107-3ddb8989fe88.PNG)

Yes the chords are tied. Not sure if you wanted the full score file or screen shot

**Comment by MarcSabatella** [comment] 2022-08-11 17:58
Actual score is almost always better, but GitHub doesn't make that easy.  Anyhow, this confirms, it's definitely a duplicate of the known issue involving tied notes in general - see https://github.com/musescore/MuseScore/issues/12767

**Comment by Tantacrul** [comment] 2022-08-31 18:23
I'm closing, since this is a duplicate of the dreaded tie issue. Thanks @dyyap and @MarcSabatella !

**Closed by Tantacrul** 2022-08-31 18:23 UTC
