### ISSUE TITLE
Cannot delete multiple elements using the context menu

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10698] opened 2022-03-01 15:43 UTC
**Describe the bug**
See video. User can not select multiple elements and use the context menu to delete them all. In fact the context menu seems to re-select only one item, which is problematic (and contrary to how MS3 works)

https://user-images.githubusercontent.com/21022311/156199773-4fb96715-c588-461d-a290-a299f4c8c667.mov

@duanjr - I thought I might mention you here, since you have improved a very similar problem in a related area.

**Comment by duanjr** [comment] 2022-03-01 15:59
I will surely try to solve this issue, could it be assigned to me?

**Comment by duanjr** [comment] 2022-03-02 02:07
In musescore3, we allow user to select multiple elements and process them with the context menu.
However, only delete and delete part in cut work as expected, copy, paste and paste part in cut do not work.
Musescore4 may re-select only one item by design to keep the features in the contextmenu intact.
There're several way to improve this problem, we need to select one of them:
1) Disable features except delete when select multiple items.
2) Allow user to select multiple items, but re-select only one item when user try to cut(delete all and copy one) or copy.
3) Implent the full feature to allow user copy, cut and paste multiple items when this can be done.
4) keep it as it is now.

**Comment by duanjr** [comment] 2022-03-02 09:22
This issue happens because Musescore4 has different logic to show context menu.
In Musescore3, whenever we want to show a context menu, we have to select item(s) first. If you select A item and right-click on B item. The context menu still works on A item. In Musescore3, context menu is combined with what you select and has nothing to do with where you right-click.
In musescore4, on the contrary, context menu is combined with where you right-click, and has nothing to do with what you select. You don't need to select item(s) before call context menu. So Musescore 4 just can't show context for multiple items( because you can not right-click them at the same time).
I think Musescore4 work logic is more natural and confident for users.
However, this does not mean there's no issue.
If we only select multiple items in the staves through pressing on shift key, instead of selecting all kinds of items through pressing on ctrl key, we do have an exsiting context menu to process mutiple selected items.
And we can delete multiple items through this menu (which already solves this issue).
This design is better than what we do in musescore3. If user only edit title、signature、etc. He can surely edit them one by one. If user want to copy、cut、delete and paste a huge number notations in the staves, he can press shift and call that existing menu.
Then the real issue comes, though we have an exsiting context menu. Like the defect in musescore3, the copy-paste feature is not implented correctly for mutiple items.
So actually what we need to do is: implent the copy-paste feature correctly in the context menu called by pressing on shift key.

**Comment by duanjr** [comment] 2022-03-03 02:56
> This issue happens because Musescore4 has different logic to show context menu. In Musescore3, whenever we want to show a context menu, we have to select item(s) first. If you select A item and right-click on B item. The context menu still works on A item. In Musescore3, context menu is combined with what you select and has nothing to do with where you right-click. In musescore4, on the contrary, context menu is combined with where you right-click, and has nothing to do with what you select. You don't need to select item(s) before call context menu. So Musescore 4 just can't show context for multiple items( because you can not right-click them at the same time). I think Musescore4 work logic is more natural and convenient for users. However, this does not mean there's no issue. If we only select multiple items in the staves through pressing on shift key, instead of selecting all kinds of items through pressing on ctrl key, we do have an exsiting context menu to process mutiple selected items. And we can delete multiple items through this menu (which already solves this issue). This design is better than what we do in musescore3. If user only edit title、signature、etc. He can surely edit them one by one. If user want to copy、cut、delete and paste a huge number notations in the staves, he can press shift and call that existing menu. Then the real issue comes, though we have an exsiting context menu. Like the defect in musescore3, the copy-paste feature is not implented correctly for mutiple items. So actually what we need to do is: implent the copy-paste feature correctly in the context menu called by pressing on shift key.

hmmm，when I test the copy-paste feature for multiple items in staves, it did not work...(maybe my mistake)
I test it again just now it works as expected.

**Comment by wizofaus** [comment] 2022-03-29 05:53
The current behaviour seems OK to me - if you have a range selected and you right-click on an item inside it, it works as expected. If you have a number of individual items selected you need to hold down CTRL to prevent the right-click from deselecting those items - which is exactly how it works in most other applications.   @Tantacrul

**Comment by Tantacrul** [comment] 2022-03-31 07:22
> 

Is this a new PR you are testing or are you saying the existing behaviour in MS4 is correct?

**Comment by wizofaus** [comment] 2022-03-31 07:29
No, I was referring to the current MS4 behaviour (as seen in the alpha). I think it's generally OK except that holding down ctrl and shift-clicking shouldn't affect the selection.

**Comment by Tantacrul** [comment] 2022-03-31 07:39
I think I should just make sure I'm getting across why I think the kind of stuff I raised in my bug would be useful. To some extent, it's a stepping stone towards having something more broadly capable. See this vid:

https://user-images.githubusercontent.com/21022311/161002834-69daa2e7-842c-416c-9e11-51aa85374de1.mov

**Comment by wizofaus** [comment] 2022-03-31 08:08
I didn't watch your whole video, but you should definitely be able to hold down the CTRL key, (left) click on multiple elements, then while *still* holding down CTRL, right click essentially anywhere, and bring up a context menu with commands that apply to the selected elements.  This behaviour is wrong currently in v4, whereby right-clicking while CTRL key is held down changes what is selected (depending on where you click).  However if you *release* the control key, I do expect the right-click action to deselect previously selected elements, and this behaviour I would say is correct currently, even if it's different to v3.

**Comment by jeetee** [comment] 2022-03-31 08:18
@Tantacrul 
One of the reasons MU3 didn't allow list selection copy-paste is that we never figured out the less obvious use case desires. In the examples you've shown, you made sure to (basically) list-select a range. The MU3 approach for that is to select a range and exclude things from the range selection (which indeed is more cumbersome in a bunch of scenarios).

I'm interested to see how literal we'd take this when the list selection is not single-staff/continuous range.

**Comment by Tantacrul** [comment] 2022-03-31 08:28
> @Tantacrul One of the reasons MU3 didn't allow list selection copy-paste is that we never figured out the less obvious use case desires.

What I can say is that while composing, being able to pick out a few items, without needing to range-select (which can then grab other unwanted items) is something I have to do constantly when writing music. Without it, in MuseScore, I end up perpetually range-selecting, copying, pasting, and then deleting unwanted stuff. Since there doesn't appear to be a disadvantage to allowing users to copy and paste a list selection, I think we should do it.

The older I get, the more I recognise that if there is a feature I use myself (because I'm a very basic mouse + 4 or 5 shortcuts kind of person), it will likely be used by others. It's also the kind of thing a user would never think to complain about because this level of interaction nerdiness is usually something only people like us are interested in 😵‍💫

**Comment by wizofaus** [comment] 2022-03-31 08:39
@Tantacrul to me the clear advantage is in preserving the behaviour of other software users are familiar with. I can't speak for Mac apps, but e.g. in Windows Explorer, if you hold down CTRL and select a few items, then release CTRL, then right-click on another item, it deselects the items.  But if you keep CTRL held down it doesn't.

As for being able to cut/copy a list selection - absolutely, but v3 never supported that either.  The range selection + selection filter usually allows you to do most things, but defining all the possible behaviours in every possible case isn't straightforward - I spent quite a long time trying to figure out how it could be improved in v3.

**Comment by jeetee** [comment] 2022-03-31 08:42
@wizofaus You need the Ctrl there only if you right-click an element outside of the selection. If you right-click an element **within** the selection, then no modifiers are required

**Comment by wizofaus** [comment] 2022-03-31 08:49
@jeetee ah yes, sorry, you're right (again!) - provided you right-click on one of the items/elements that is already selected, regardless of whether CTRL is held down or not, the selection is unchanged.  In that case I suspect we're all in furious agreement about what the behaviour should be.

**Comment by Tantacrul** [comment] 2022-03-31 09:38
> @Tantacrul to me the clear advantage is in preserving the behaviour of other software users are familiar with. 

- I don't see that advantage. Other notation apps use the system I've described and it is clearly more useful. Only preserve useful functions.

> but v3 never supported that either.
And does loads of other dumb things too.

**Comment by Tantacrul** [comment] 2022-03-31 09:41
> @jeetee ah yes, sorry, you're right (again!) - provided you right-click on one of the items/elements that is already selected, regardless of whether CTRL is held down or not, the selection is unchanged. In that case I suspect we're all in furious agreement about what the behaviour should be.

Hmm. I'm just seeing this comment after I posted my last one. Seems we've been talking at cross-purposes a bit. Good, I was a little baffled.

**Comment by DmitryArefiev** [comment] 2022-04-11 17:46
Fixed in #11114

**Closed** 2022-04-11 19:14 UTC
Labels: P2
