### ISSUE TITLE
Playback sped up/slowed down after switching to an audio device with a different sample rate

### ISSUE THREAD

**Issue by Jobvkempen** [musescore/MuseScore#18901] opened 2023-08-03 09:13 UTC
### Issue type

General playback bug

### Bug description

When switching between audio devices with different sample rates, MuseScore doesn't adapt to the changes and holds on to the sample rate it detected upon startup, which causes either a speedup or slowdown of the playback. 

### Steps to reproduce

1. Open a MuseScore project
2. In Windows, switch to a playback device with a different sample rate than the playback device that was active when you opened MuseScore

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/75323947/87461315-0a4f-42e0-a11f-f045873178a3

### MuseScore Version

4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Pro 21H2

### Additional context

In the attached video, I went from a playback device with a 48kHz sample rate to a playback device with a 192kHz sample rate, resulting in a speedup of the playback, but the reverse happens when I do it the other way around.

**Comment by zacjansheski** [comment] 2023-08-04 15:28
Similar to: https://github.com/musescore/MuseScore/issues/18579

**Comment by zacjansheski** [comment] 2023-08-04 15:32
Duplicate of https://github.com/musescore/MuseScore/issues/17877

**Closed by zacjansheski** 2023-08-04 15:32 UTC
Labels: playback
