### ISSUE TITLE
no x noteheads for guitar TAB slash notation, slash notation noteheads could be larger

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21459] opened 2024-02-12 03:46 UTC
### Your idea

It would be nice if a future version of musescore 4 could allow changing noteheads to x to indicate muting in slash notation for guitar tablature, because this is quite typical for electric guitar. At the moment if you try to change it in properties or palettes nothing happens. Also normal slash notation noteheads are quite small, it would be nice to have the option to make them larger.

**Comment by oktophonie** [comment] 2024-02-22 09:31
Duplicate of https://github.com/musescore/MuseScore/issues/19084

**Closed by oktophonie** 2024-02-22 09:31 UTC
Labels: feature request
