### ISSUE TITLE
Musescore crash editing text (Append Vertical Frame)

### ISSUE THREAD

**Issue by nmferreira2** [musescore/MuseScore#20802] opened 2024-01-02 18:12 UTC
### Issue type

Crash or freeze

### Bug description

I add a Append Vertical Frame, I insert the text and the musescore crashes.
I restart the programme and try to edit the text again and it crashes again.

### Steps to reproduce

1. add -> Frame -> Append Vertical Frame
2. click in frame -> Text
3. Paste the text
4. Try to edit the text -> Crashes

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/126064661/94bd3491-0410-4849-8f7a-cb254818eb52)

https://github.com/musescore/MuseScore/assets/126064661/f99b0b41-914a-42ed-b278-92ae879cd77d

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

[log.csv](https://github.com/musescore/MuseScore/files/13812857/log.csv)

**Comment by zacjansheski** [comment] 2024-01-12 19:37
I have not been able to reproduce this crash.

How are you putting text in a vertical frame?  Do you mean you appended a text frame?

Doe this happen on all of your files or just one?  Maybe you can share the MuseScore file so we can reproduce?

**Comment by nmferreira2** [comment] 2024-01-13 19:37
Hi,

The problem occurs when I attempt to edit text within the software. Here are the steps that led to the crash:

1. I access the 'Add' tab and select 'Append Vertical Frame'.
2. I then choose to add text.
3. After pasting my text into the frame, any attempt to edit it (such as removing spaces between phrases) results in an immediate crash of the software.

This issue has been consistent in different files(like in this one that I am sending you), indicating a possible bug in the text editing functionality.

Thank you for your attention to this issue.

Best regards,
Nuno Ferreira

**Comment by MarcSabatella** [comment] 2024-01-13 19:44
I can't reproduce using those steps, but I note your example show a variety of special characters in the text - maybe it's something about the specific text?  Please post the exact text you are pasting.

**Comment by Jojo-Schmitz** [comment] 2024-01-14 10:57
Duplicate of #20716 ?

**Comment by zacjansheski** [comment] 2024-02-28 21:06
If this is a duplicate, than it may have been fixed by https://github.com/musescore/MuseScore/pull/20817
included in 4.2.1

@nmferreira2 do you still have this issue in the latest version?  4.2.1?

**Closed** 2024-06-27 13:53 UTC
Labels: needs info, regression, crash
