### ISSUE TITLE
Ability to override/customise invisibleColor

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#24249] opened 2024-08-28 03:26 UTC
### Your idea

Would like to be able to change the color used to render invisible elements, to allow for different monitors or different background colors etc.

### Problem to be solved

Currently invisibleColor is hardcoded as #808080, and the logic to change the saturation for selected invisible elements (based on the voice color) is also hardcoded.
Even if it were just via DevTools, being able to choose a different engraving/colors/invisibleColor to better suit your choice of ui/canvas/background/color would be handy and straightforward to implement.

### Additional context

I actually find the default very hard to distinguish from visible elements with my monitor. Something like #b0b0b0 works much better.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-08-28 06:27
Duplicate of https://github.com/musescore/MuseScore/issues/24054

**Closed by oktophonie** 2024-08-28 06:27 UTC
Labels: feature request

**Comment by wizofaus** [comment] 2024-08-28 09:26
No way, I searched for that...couldn't find it at all...ah well. Anyway, good.

**Comment by SteveBlower** [comment] 2024-08-28 12:43
colour vs color perhaps?  Blame Webster!
