### ISSUE TITLE
Copy and paste of bars with time signature change does not paste time signature

### ISSUE THREAD

**Issue by brettrp** [musescore/MuseScore#19849] opened 2023-10-28 02:00 UTC
### Issue type

Engraving bug

### Bug description

If you copy and paste multiple bars including a time signature change, the time signature change is not included in the paste. All bars get the time signature already in effect at the point of the paste.

### Steps to reproduce

1. Open the attached score
2. Select bars 1-3 (or bars 1-2) and copy
3. Paste into bar 4
All pasted bars are in 4/4 including the copied bar which was meant to be in 5/4

[time-sig-change.mscz.zip](https://github.com/musescore/MuseScore/files/13194169/time-sig-change.mscz.zip)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/6935280/fa03bc3c-45ae-4559-aea8-d1120ae5ee30

### MuseScore Version

OS: macOS 14.0, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

macOS 14.0

**Comment by DaddyLudwig** [comment] 2023-10-28 02:06
I think that's sort of by design? Cause time signatures are global level objects. And global level objects in general do not copy and paste with the notes, but staff level objects like clefs do. That's how come tempo doesn't paste when you do a copy and paste either unless you select the tempo by itself and then copy. It's always been this way in MuseScore as far as I'm aware.

**Comment by brettrp** [comment] 2023-10-28 02:12
Tempo doesn't change the layout of the notes though. Copying a bar and pasting it and seeing its time signature change -- especially when the change itself was in one of the bars that you copied -- is a bit unexpected (or at least it was to me). And the result is going to be wrong more often than not isn't it?

**Comment by DaddyLudwig** [comment] 2023-10-28 02:47
I mean, I don't generally run into situations where I'm doing a copy and paste across time signature changes, period. For me as a classical music transcriber, generally speaking a) the time signatures span long enough and b) the material is contrasting enough, that I just end up copying and pasting the different time signature material separately for each time signature and dragging and dropping time signatures as I see them.

And I also would think that, at least in my case, if time signatures did copy and paste, it would be super annoying in 1 major case, sonata recapitulations, or any sort of reappearance of A section material in a piece(which is usually the reason I'm copying and pasting in the first place if it's not octave doublings or melodic sequences) and only helpful a minority of the time(mostly in 20th century pieces, where I'd also have to worry about copyright). 

Cause like, okay, imagine that I'm transcribing say a Rondo and it's in 2/4. Okay, I put in the A section material, copy, put in the B section material, paste the A section material, edit if necessary, put in the C section material, etc. As of now, with time signatures not pasting, this is a pretty smooth process. Cause if there is a time signature change, there's often a second one before the A section returns, just 2 drag and drops. Now, if the time signatures did paste, I might get something like this:

2/4, A section, B section, 2/4, A section, C section, etc.

An extra time signature where I don't need it cause there was no change, an annoyance that I have to break the flow by deleting the time signature. At least for me, that's worse than the result of a time signature not getting copied, cause 1 easily fits into my flow with a drag and drop(time signature change not copying) and the other breaks it(time signature copying where unnecessary).

**Comment by brettrp** [comment] 2023-10-28 03:33
So in your case you're concerned that you'd get redundant 2/4 time signatures? If it didn't paste the time signature if it was already the same as the point where you were pasting would that address that?

In my case it's the time signature _change_ that is doing the wrong thing. In the above case, I don't want a redundant extra 4/4 at the point I do the paste (if I understand your case correctly, that's also what you don't want). However, I do want the bar that's in 5/4 to stay that way.

**Comment by DaddyLudwig** [comment] 2023-10-28 03:53
Yeah, that's what I'm concerned about is redundant time signatures. And yeah, I suppose if it didn't paste the time signature where it's the same, but did paste changes in time signatures, that would both solve your issue and prevent me from getting redundant time signatures.

**Comment by oktophonie** [comment] 2023-10-28 14:57
Duplicate of https://github.com/musescore/MuseScore/issues/15590

**Closed by oktophonie** 2023-10-28 14:57 UTC
Labels: engraving
