### ISSUE TITLE
[MU4 Issue] "Palettes" menu search bar lags, crashes

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#16365] opened 2023-02-15 00:59 UTC
**Describe the bug**
The search function at the top of the "palettes" menu is laggy and crashes MU4 frequently.
The search button always takes at least a second, often more, to respond when clicked. This is very annoying and disrupts my workflow. Occasionally, the program will freeze for a while and then crash after you select an item in the palette to be added after searching. I have not found a consistent way to reproduce this crash, but it always seems to happen when I try to select an item too quickly after typing (before MuseScore is "ready"?). When it happens, the text in the search box is usually incomplete (suggesting that I clicked the item before MuseScore had registered all my keystrokes) and the mouse pointer stays frozen on the "I-beam" cursor when hovering over the menu item.

**Platform information**
OS: Windows 11
MuseScore 4.0.1

**Comment by oktophonie** [comment] 2023-02-15 09:37
Duplicate of https://github.com/musescore/MuseScore/issues/12753

**Closed by oktophonie** 2023-02-15 09:37 UTC
