### ISSUE TITLE
Tempo boxes. First Letter is missing after deleting Tempo marks.

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#25121] opened 2024-10-10 19:23 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create file
2. Mark a note or break
3. create a tempo mark (eg. quarter = 80) with shift+option or in panel
4. click on tempo mark
5. delete typos
6. write "Allegro"
7. first Character is not written

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/0de0b74d-3e96-4024-a541-803269f827c2

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.6

### Additional context

No problems after deleting characters of tempo marks written with letters like "Allegro"

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-10-11 13:28
Duplicate of https://github.com/musescore/MuseScore/issues/22840

**Closed by oktophonie** 2024-10-11 13:28 UTC
Labels: regression MS4, engraving, UX/interaction
