### ISSUE TITLE
Metronome mark on new score plays at wrong speed until the text is edited

### ISSUE THREAD

**Issue by dulciepercy** [musescore/MuseScore#24133] opened 2024-08-21 17:19 UTC
### Issue type

General playback bug

### Description with steps to reproduce

1. Create a new score
2. Add any instrument on new score dialog
3. The next screen of the new score dialog has key sig, time sig, and tempo.  Change the time signature to 3/4
4. Click show tempo on score and select dotted minim and enter 80 - so crotchets (quarter note) should play at 240 bpm
5. Click Done to create the score
6. Enter some sample notes for a few bars
7. Click play - for me it plays slowly - I think it's playing a quarter note at the tempo number I've entered, so 80 bpm instead of 240
8. Edit the tempo text to anything and click play - it's the right tempo
9. Edit the tempo again to 80 and you get the tempo you wanted in the first place.

### Supporting files, videos and screenshots

[slow playback.zip](https://github.com/user-attachments/files/16695669/slow.playback.zip)

The attached file plays back for me at crotched about 80 (instead of dotted minim 80) until I edit the text, then it is correct

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242340502, revision: github-musescore-musescore-212d60f

### Regression

No.

### Operating system

Windows 11

### Additional context

Just tried 4.3 and I get the same result.  Think the same thing happened with 4/4.  I can do more testing later.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-08-21 17:21
Thanks for reporting! But it turns out to be a duplicate of https://github.com/musescore/MuseScore/issues/14678.

**Closed by cbjeukendrup** 2024-08-21 17:21 UTC
Labels: playback

**Comment by dulciepercy** [comment] 2024-08-21 17:50
> Thanks for reporting! But it turns out to be a duplicate of #14678.

Cool,  I searched all the wrong words!
