### ISSUE TITLE
Crash when joining measures

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#25257] opened 2024-10-21 08:28 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

Can so far reproduce in two scores.

1. Select any two measures of this score: [Mahler4.mscz.zip](https://github.com/user-attachments/files/17457560/Mahler4.mscz.zip)
2. Go to Tools > Measures > Join selected measures

MSS crashes.

This crash reproduces even when deleting everything in the selected measures.

For another repro example, see [this issue](https://github.com/musescore/MuseScore/issues/25228). Note there that the crash is not limited to the range of bars 39-42 as indicated in the description; it can be reproduced by selecting a variety of other measures as well. 

### Supporting files, videos and screenshots

[Diagnostic files](https://github.com/user-attachments/files/17457620/crash-join-measures_21Oct24.zip)

https://github.com/user-attachments/assets/42da75f8-d1fb-49dd-888d-b4adccf9f49c

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3 RC

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 15.0.1

### Additional context

Does not occur in 4.4.1.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment] 2024-10-21 09:20
@miiizen caused by [this PR](https://github.com/musescore/MuseScore/pull/24623)

**Comment by DmitryArefiev** [comment] 2024-10-23 10:18
Fixed in #25264

**Closed** 2024-10-23 10:48 UTC
Labels: P1, regression MS4, crash
