### ISSUE TITLE
Text displays twice in score after making instruments visible in custom parts

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19060] opened 2023-08-15 16:58 UTC
### Issue type

Engraving bug

### Bug description

Tempo Text displays twice in score after making instruments visible in custom parts

### Steps to reproduce

1. Create a score with tempo text
2. Create a custom part
3. Make parts visible
4. Check score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/2d21e71e-1d44-4e7a-a649-8ca1d9f4dce6

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232270302, revision: github-musescore-musescore-c1a7925

### Regression

Yes, this used to work in a previous version of **MuseScore 4.1.1**

### Operating system

OS: macOS 11.6

**Comment by zacjansheski** [comment] 2023-08-15 17:21
Similar, but not the same as https://github.com/musescore/MuseScore/issues/18231

**Comment by RomanPudashkin** [comment] 2023-08-16 09:38
Caused by https://github.com/musescore/MuseScore/pull/18193/commits/b05b3b3c2d522d044b19306db1df10b5ce3095e1

**Comment by DmitryArefiev** [comment] 2023-08-16 11:49
Fixed in #19065

**Closed** 2023-08-16 11:49 UTC
Labels: P1, regression, engraving
