### ISSUE TITLE
[MU4 Issue] VST window not able to be closed, minimized or moved

### ISSUE THREAD

**Issue by dyyap** [musescore/MuseScore#15101] opened 2022-12-11 04:18 UTC
**Describe the bug**
VST's manipulated by mixer cannot be moved, minimized, or closed preventing the user from accessing the score.

**To Reproduce**
1. Open a score
2. Go to the Mixer and under VST's pick an instrument
3. plugin window is stuck in the middle.

**Expected behavior**
I would like the ability to see my score and to manipulate windows accordingly. 

**Screenshots**
![musescore issue2](https://user-images.githubusercontent.com/35153938/206886166-802ae8e6-39b5-47f2-9718-6368d38e7266.PNG)

**Platform information**
Windows

**Additional context**
I am using BBC spitfire audio, the free one

**Comment by RomanPudashkin** [comment] 2022-12-16 11:47
Duplicate of https://github.com/musescore/MuseScore/issues/15200

**Closed by RomanPudashkin** 2022-12-16 11:47 UTC
