### ISSUE TITLE
Linux Ubuntu Playback broken

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#21749] opened 2024-02-29 11:25 UTC
### Issue type

General playback bug

### Bug description

Playback doesn't work. Pressing space or the arrow key causes the blue line to appear but it won't move, move along or inserting notes causes no sound either. I am using MS Basic and just re-installed it, the video below is a fresh install without modification.

### Steps to reproduce

1. Install Flatpak or Appimage for Linux
2. Insert notes into score
3. Press play
4. Nothing happens

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134429563/9476ef75-d2c6-40de-9046-a7d5992877c1

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Linux Mint 21.3 Edge 

### Additional context

This occurs on my laptop and my desktop on both Flatpak and Appimage. It has been like this for over a year.

**Comment by RustoMCSpit** [comment] 2024-02-29 11:36
Hide this comment. Can the Musescore team handle the [Flatpaks](https://flathub.org/apps/org.musescore.MuseScore) for Muse Score, MuseHub (you'll have to list it as proprietary unless you're planning on changing that), etc.. Leaving it up to random volunteers leads to occasional [viruses](https://www.gamingonlinux.com/2024/02/snap-store-from-canonical-ubuntu-hit-with-another-crypto-scam-app/). If you want me to make another issue about that just tell me and I will.

**Comment by oktophonie** [comment] 2024-02-29 11:38
Closing as duplicate of https://github.com/musescore/MuseScore/issues/11220; see also https://github.com/musescore/MuseScore/issues/15937

**Closed by oktophonie** 2024-02-29 11:38 UTC
Labels: playback
