### ISSUE TITLE
[MU4 Issue] Tupplet Reset

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16535] opened 2023-02-24 15:21 UTC
Hello,
I have Tupplet with Number and Bracket hidden on creation and i want to reset-it Because in this case Tupplets are no selectable. . How i can do that in MS4

![image](https://user-images.githubusercontent.com/1835871/221216354-3173053d-c8cb-40df-bc42-8838ef86b0e6.png)

In MS3, i can do that selecting Tupplet
![image](https://user-images.githubusercontent.com/1835871/221216544-2c3b3413-ff23-460e-a6c6-a27a6a5a49f4.png)

**Comment by MarcSabatella** [comment] 2023-02-24 15:32
A workaround is, delete one note to force the bracket appear, then you can select it.

Of course, there should be a better method than this.  See https://github.com/musescore/MuseScore/issues/15565

In the future, please use the Support forum on msuescore.org when asking for help when using MuseScore.

**Comment by Gai-Luron** [comment] 2023-02-24 15:35
"In the future, please use the Support forum on msuescore.org when asking for help when using MuseScore.""
Ok, you are rigth, but in this case the classification was not easy ti decide in this case. Bug, regression, design or forgot functionnality.
Thank for the workaround

**Comment by oktophonie** [comment] 2023-02-24 16:03
Closing as duplicate of #15565

**Closed by oktophonie** 2023-02-24 16:03 UTC
