### ISSUE TITLE
Microtonal accidentals fail to affect playback through an entire measure

### ISSUE THREAD

**Issue by DaffodilAura** [musescore/MuseScore#22413] opened 2024-04-15 19:51 UTC
### Issue type

General playback bug

### Bug description

So I'm checking out a score in MuseScore 4.2.1, and it seems that quartertone accidentals don't carry their effects through entire measures unlike regular accidentals.  What is expected to happen is that microtonal accidentals behave like regular accidentals not only in playback but also in how they function in general.

### Steps to reproduce

1. Create new score
2. Input several of the same note
3. Add a quartertone or other microtonal accidental to the first of the notes
4. Watch as a natural sign fails to appear on the first of the subsequent notes
5. Listen as the accidental also fails to playback on the subsequent notes.

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

Windows 10

**Comment by Lynzzyr** [comment] 2024-09-17 10:21
Bug also happens when microtonal notes are tied, whether inside the bar or between bars.

**Comment by sammik** [comment] 2024-11-22 14:07
Duplicate of #20616

**Closed** 2024-11-22 15:06 UTC
Labels: P2, playback
