### ISSUE TITLE
[MU4 Issue] Order of options in Save dialog box inconsistent with OS

### ISSUE THREAD

**Issue by fgimian** [musescore/MuseScore#11110] opened 2022-04-06 12:35 UTC
**Describe the bug**
The current dialog box that appears when you are being prompted to save changes shows the buttons in the following order: "Don't save", "Cancel", "Save".  At least on Windows, this is not the order that other apps use and it feels extremely unusual and disorienting.  This was correct in MuseScore 3.

Furthermore, no default option (i.e. "Save") is selected the first time the dialog appears and tabbing through options is not possible.  Again this worked in MuseScore 3.

**To Reproduce**
1. Create a new score in MuseScore and add a few notes
2. Hit Ctrl+W to close the score and observe the Save dialog box
3. Notice that no option is selected, try hitting Tab multiple times and you will only be able to move to "Don't save"
4. Close the dialog and repeat step 2, this time Save will be selected by default but Tab still misbehaves

**Expected behavior**
The buttons should be in the following order (at least on Windows): Save, Don't save and Cancel.  Save should always be selected by default and the Tab key should cycle through all 3 buttons.

**Screenshots**
MuseScore 4 Save dialog box:

![image](https://user-images.githubusercontent.com/1811813/161975637-58bad107-aa62-4205-8d3e-5dd7f641cd1c.png)

MuseScore 3 Save dialog box;

![image](https://user-images.githubusercontent.com/1811813/161976214-47d7dfd6-7d57-4739-8e68-efa33d5b734b.png)

Notepad Save dialog box:

![image](https://user-images.githubusercontent.com/1811813/161975677-4a0518c9-82b8-484c-b24a-ea850d496cf6.png)

VS Code Save dialog box:

![image](https://user-images.githubusercontent.com/1811813/161975689-f1944b96-ebcd-4c9c-90da-eaf03f1d76cc.png)

Microsoft Word Save dialog box:

![image](https://user-images.githubusercontent.com/1811813/161975728-dcceb9d9-707b-4bdc-8011-73313fa39dab.png)

**Platform information**
 - OS: Windows 11

**Additional context**
N/A

**Comment by cbjeukendrup** [comment] 2022-04-06 12:44
Duplicate of #10505. Useful addition though. Still I'll close it, since it will be linked automatically in the original issue. 

Thanks for reporting!

**Closed by cbjeukendrup** 2022-04-06 12:44 UTC

**Comment by cbjeukendrup** [comment] 2022-04-06 12:46
No problem!
