### ISSUE TITLE
MuseScore crashes upon saving

### ISSUE THREAD

**Issue by datario-viz** [musescore/MuseScore#17113] opened 2023-04-02 18:09 UTC
### Issue type

Crash or freeze

### Bug description

Whenever I copy and paste large sections of my score, the app crashes upon saving it. I don't know what is exactly causing this. (Beaming?)

### Steps to reproduce

1. Copy measure 90 to 130
2. Paste them somewhere else
3. Save the score
4. It crashes!

### MuseScore Version

4.0.2.230651546

### Regression

I don't know

### Operating system

macOS 13.2.1

### Additional context

OS: macOS 13.2, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

Score file in context: https://drive.google.com/drive/folders/1aVOQo2TaCwDPhHzerHz2qtacy_Hzq5uh?usp=sharing

**Comment by Jojo-Schmitz** [comment] 2023-04-02 18:17
stems from https://musescore.org/en/node/347628

**Comment by cbjeukendrup** [comment] 2023-04-13 14:56
I _can_ reproduce this with 4.0.2, but _not_ with the latest master builds. So it looks like the problem has been fixed already and the update will be part of the next update. In the meantime, you can grab a "nightly build" from https://musescore.org/en/nightly-builds, to see if it's fixed for you too. Would be great if you could let us know!

**Comment by bkunda** [comment] 2023-05-05 13:32
Also unable to reproduce in latest master builds, so closing for now.

**Closed by bkunda** 2023-05-05 13:32 UTC
Labels: needs testing, crash
