### ISSUE TITLE
[MU4 Issue] No additional active area around the note when selecting a note or adding any element to a note

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10845] opened 2022-03-18 19:09 UTC
**To Reproduce**
1. Open a MuseScore4
2. Try to select any note by clicking close to the note itself 
3. Try to put any element (e.g. slur) to a note
4. Pay attention to the note active area

**Expected behavior**
There is an additional active area (like in MuseScore3) around the note when selecting a note or adding any element to a note

**Screenshots**

https://user-images.githubusercontent.com/101250347/159068523-b85f91a6-177c-4749-a927-bba5515a902b.mov

**Additional context**
As a reference use MuseScore3

**Comment by Tantacrul** [comment] 2022-05-31 16:06
I've taken this off the engraving team and put it in the 'score view' category.

I've also increased the severity because it is a core interaction. Nice spot, @boryskuzmenko!

**Comment by boryskuzmenko** [comment] 2022-06-02 17:56
@Tantacrul @RomanPudashkin Please, take a look. As I see now there are three issues which cause problems like this:
1. Proximity setting described in https://github.com/musescore/MuseScore/issues/11410 
2. Clickable area e.g. for notehead is сircle, not ellipse. So for me it's confusing when from one side of notehead you have 5-10 more pixels around than on another side. 
3. Cursor and the point which you moving by cursor (when e.g. moving an edge of slur to another note) are out of sync after changing a note. This is confusing even more.

**Comment by Tantacrul** [comment] 2022-06-02 18:50
I think there are good reasons for the change to the global proximity setting. However, Noteheads should have a unique rule IMO.

Not to mention, this is a drag operation, so can have different rules under those circumstances. For example, when a user drags an element that is attached to a notehead, we can make the hit area **way** more generous.

**Comment by boryskuzmenko** [comment] 2022-06-06 11:31
Ok! There's pretty clear story with point 1 and not clear with 2 and 3. 
@Tantacrul Please, provide your vision of both. 
Should we try to change elipse clickable area to circle (btw in Sibelius is also elipse, seems like its the font specific)? 
What are the expectations for synchrinizing of cursor with the movable point?

**Comment by Tantacrul** [comment] 2022-06-07 15:30
OK, you know what? This issue is probably caused by the proximity decrease. I think a sensible solution would be to add some extra rules specifically to deal with the case where users are dragging elements onto noteheads. However, this will require lots of work and testing to get right and may open a whole new can of worms.

When I first saw the issue, I assumed it wasn't possible to drag slurs onto noteheads (I somehow missed this in the video). I'm now thinking that we should delay working on this until 4.X, simply because it is a refinement that needs time, testing and input from multiple people.

@RomanPudashkin - I'm going to close this, unless you are currently working it. If so, I'll keep it open.

**Closed by Tantacrul** 2022-06-07 15:30 UTC
