### ISSUE TITLE
Tied chords do not work when arpeggiated

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#16352] opened 2023-02-13 18:33 UTC
In Musescore 4, adding an arpeggio to a chord which has ties causes the ties to behave incorrectly: instead of sustaining the note, the sound cuts off completely at the first beat the chord is tied to. Other chords played on the same beat that are not arpeggiated are not affected.

The graphic hopefully explains what I mean:
![arps](https://user-images.githubusercontent.com/73259774/218543735-2cba9096-4c0b-4215-bd02-2661192a01a0.png)

OS: Windows 11
Musescore ver. 4.0.1

**Comment by Fristover** [comment] 2023-02-13 18:48
Maybe related to #15279 ?

**Comment by Panogen** [comment] 2023-02-13 19:05
Yes, looking at the issue it is definitely a duplicate. I posted here because I got poor support on musecore.org (the one person who replied to my post there acted like it was an intended feature?). Should I close this issue?

**Comment by MarcSabatella** [comment] 2023-02-13 19:11
Yes, close it if a duplicate.

Note that posting first to the community support forum on musescore.org is indeed the best place to post when first trying to ascertain if something is a bug or a misunderstanding or a duplicate of a known issue etc.  And then if something is confirmed as a new bug, then it makes sense to open an issue here.  But there are dozens of new posts every day, so someone things can slip through the cracks.  We're trying to develop a better process for this.

**Closed** 2023-02-14 02:53 UTC
