### ISSUE TITLE
Bend's playback is not working if the bend was applied after a tie

### ISSUE THREAD

**Issue by ingvarskagg** [musescore/MuseScore#25039] opened 2024-10-04 14:11 UTC
### Issue type

General playback bug

### Description with steps to reproduce

Can be reproduced with guitar part where bend is applied to tied note, example: 
[ties-then-bend.mscz.zip](https://github.com/user-attachments/files/17259853/ties-then-bend.mscz.zip)

**Steps to reproduce.**

1. Open the attached score (or any score with tie and bend applied to a note)
2. Listen to the playback of that part

**Actual result:** bend's playback is incorrect - should be bended to D flat

**Expected result:** bend's playback is D flat accordingly to the example's notation

### Supporting files, videos and screenshots

[ties-then-bend.mscz.zip](https://github.com/user-attachments/files/17259837/ties-then-bend.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

No.

### Operating system

macOS 14

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment] 2024-10-04 14:18
Duplicate of https://github.com/musescore/MuseScore/issues/21345

**Closed by RomanPudashkin** 2024-10-04 14:18 UTC
Labels: duplicate
