### ISSUE TITLE
[MU4 Issue] Muse Hub won't relaunch after update

### ISSUE THREAD

**Issue by samsoeder** [musescore/MuseScore#15005] opened 2022-12-07 04:45 UTC
**Describe the bug**
MuseHub launcher froze on updating Musescore 4.  I stopped the update and tried to update MuseHub to fix the problem. MuseHub immedialy closed and will no longer launch. I tried Uninstalling MuseHub, restarting my PC, and reinstalling the launcher from Musehub.com but program still wont launch.

**To Reproduce**
1. Open MuseHub launcher
2. Click "update MuseHub"
3. MuseHub closes. after waiting sometime program wont relaunch even after PC restart
4. Uninstall the app through the windows start menu and manually deleteing MuseHub, Musescore 4, and MuseSampler files
5. restart PC
6. download launcher from MuseHub.com and Install
7. Installer opens and closes after a few seconds
8. After install MuseHub program still wont launch

**Expected behavior**
I expected the MuseHub launcher to reopen after completeing the update.

**Platform information**
 - OS: Windows 10

**Additional context**
I have added 2 log files. one right after I clicked "update MuseHub" and didnt get any result and another log after I reinstalled the program and had the same issue
[before reinstall - current.txt](https://github.com/musescore/MuseScore/files/10172825/before.reinstall.-.current.txt)
[after reinstall - current.txt](https://github.com/musescore/MuseScore/files/10172826/after.reinstall.-.current.txt)

**Comment by DominicMaas** [comment] 2022-12-07 18:19
Does the installer display any errors? Can you please send over the installer log (`%temp%\Muse Installer Temp\Installer.log`)

Also, could you send over the client log as well please (`%localappdata%\Packages\Muse.MuseHub_rb9pth70m6nz6\LocalState\Logs\current.txt`)

**Comment by samsoeder** [comment] 2022-12-07 22:22
[Installer.log](https://github.com/musescore/MuseScore/files/10180459/Installer.log)

The client log folder doesn't have any files inside of it

**Comment by samsoeder** [comment] 2022-12-07 22:23
And the installer did not show any errors. it just closed after a few seconds

**Comment by DominicMaas** [comment] 2022-12-07 22:28
hmmmm, application appears to be crashing very early on, before the logging system is enabled...

Installer log looks good, all required dependencies are present.

A little more complicated, can you attempt to launch Muse Hub (wait for it to crash), then open "Event Viewer", click on "Windows Logs", then "Application".

Looking for anything that is an Error, maybe mentioning an application crash (it should be near the top)

Thanks

**Comment by samsoeder** [comment] 2022-12-07 22:31
Im not seeing any errors in the event viewer. Is there anything specfifc I should be looking for?

**Comment by samsoeder** [comment] 2022-12-07 22:34
I found 2 errors in the event viewer from Musescore 4 that were logged when MuseHub first stopped working

Do you want me to copy and paste the error in plain text or is there another way?

**Comment by DominicMaas** [comment] 2022-12-07 22:45
> Im not seeing any errors in the event viewer. Is there anything specfifc I should be looking for?

I'm not sure really, just any indication of Hub crashing recently (at the time you opened it). But don't worry if there's none, something else might be going on.

> I found 2 errors in the event viewer from Musescore 4 that were logged when MuseHub first stopped working
> Do you want me to copy and paste the error in plain text or is there another way?

Might be worth doing that just in case (I think you can save selected logs within event viewer? , otherwise copy and paste the error into a file and upload that here will be fine as well). 

I think the issue is related to the new Muse Hub update that released a few days ago, not necessarily the crash that occurred before (although it would also be nice to fix that crash as well).

---

When Muse Hub launches and crashes, does the hub icon appear in the system tray (next to the clock) at all? It may also be hiding underneath the arrow.

**Comment by samsoeder** [comment] 2022-12-07 22:58
21h2

**Comment by DominicMaas** [comment] 2022-12-07 23:10
Modern enough... Okay time to try something a bit different.... The following app is built by Microsoft and is a gallery of all controls used in the WinUI framework (which Muse Hub is built using). If this application can install and run successfully, it should help narrow down the issue (or at least cross out an issue). A simple download, run, confirm it runs, and then uninstall is all that is required.

Don't feel pressured to install it if you don't want, we can continue investigating in another way.

https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC

**Comment by DominicMaas** [comment] 2022-12-07 23:12
And as a double check, the version of Muse Hub installed on your system is `0.9.10.559`? You should be able to see it underneath the application settings (right click Muse Hub in the start menu -> "App Settings").

**Comment by samsoeder** [comment] 2022-12-07 23:14
Yes it is the correct version

I installed the app and it launched fine

**Comment by DominicMaas** [comment] 2022-12-07 23:15
As a side effect of installing that app, it may have updated the framework, does Muse Hub launch now?

**Comment by samsoeder** [comment] 2022-12-07 23:17
It does not. I also tried ending the task in the task manager and trying again but it still doesn't launch

**Comment by DominicMaas** [comment] 2022-12-07 23:18
Which task, Muse Hub, or Muse Hub Background Service?

**Comment by samsoeder** [comment] 2022-12-07 23:19
Both. relaunching musehub causes it to resume the task but the application doesnt come up and its not in the system tray either

**Comment by DominicMaas** [comment] 2022-12-07 23:20
How long does "Muse Hub" stay in task manager for? Is it only for a second or so, or a bit longer?

**Comment by samsoeder** [comment] 2022-12-07 23:22
It was staying in the task manager indefinitly but after installing the application it disapears after a few seconds

I checked the log folder and it did not generate a new log after launching it again

**Comment by DominicMaas** [comment] 2022-12-07 23:25
Oh, maybe it's hanging in the background and not crashing? Let me get this straight,

So previously (before installing WinUI), you would click on Muse Hub, and it wouldn't launch (and no icon in the system tray), but the process would be running in Task Manager?

And now, you click on Muse Hub, it doesn't launch, and the application disappears from task manager in a few seconds?

It might be worth checking the Event Log again

**Comment by samsoeder** [comment] 2022-12-07 23:26
Yes

I refreshed the event log but its not showing any new logs

**Comment by DominicMaas** [comment] 2022-12-07 23:33
Are you talking about the folder in `C:\ProgramData\MuseHub` ?

**Comment by samsoeder** [comment] 2022-12-07 23:33
Yes

**Comment by DominicMaas** [comment] 2022-12-07 23:34
Shouldn't affect anything here (since the service is running alright), but better safe than sorry, yup.

**Comment by samsoeder** [comment] 2022-12-07 23:41
I reinstalled it from the link. After opening the installer it ran for about a second and closed. after waiting sometime it didnt reopen. I checked the task manager and the task is staying up

**Comment by DominicMaas** [comment] 2022-12-07 23:42
So the "Muse Hub" task is currently running in task manager and staying there? Can you please send a screenshot? (you can paste images into GitHub using Ctrl+V)

**Comment by samsoeder** [comment] 2022-12-07 23:43
![Screenshot (27)](https://user-images.githubusercontent.com/119996302/206321155-6c149dbd-3515-4ce9-ae79-fd1e9f8f8f49.png)

**Comment by samsoeder** [comment] 2022-12-07 23:50
yes. it appears for half a second

**Comment by samsoeder** [comment] 2022-12-07 23:57
I just have windows defender. It doesn't say anything about any threats. I also checked it yesterday when it first stopped working and the anti virus still didnt say anything

**Comment by DominicMaas** [comment] 2022-12-08 00:01
Well I'm stumped. I'll try obtain an exe of the previous version for you to try later (if that works, means something broke in the new update, and lets me at least try hunt down what change it was).

Thanks for going through all this with me, I'll reply to this issue if I obtain the exe or figure out what the issue could be.

**Comment by DominicMaas** [comment] 2022-12-12 17:44
@samsoeder Can you try installing this, and then try again?

https://aka.ms/windowsappsdk/1.2/1.2.221116.1/windowsappruntimeinstall-x64.exe

**Comment by samsoeder** [comment] 2022-12-12 18:12
I installed the link you sent and reinstalled MuseHub. MuseHub is working now

**Comment by DominicMaas** [comment] 2022-12-12 18:13
Awesome! Looks like there was an issue with a particular version of the Windows App SDK and Windows 10. I'll work on getting the application updated.

**Comment by samsoeder** [comment] 2022-12-12 18:14
MuseHub is showing a update is avaiabile. Do you want me to download that and make sure it is still working correctly?

**Comment by DominicMaas** [comment] 2022-12-12 18:15
Sure thing

**Comment by samsoeder** [comment] 2022-12-12 18:16
It installed correctly. Thanks for the help

**Comment by DominicMaas** [comment] 2022-12-12 18:19
Yay! Interesting problem to try track down! Feel free to close this issue below, will use #15118 for tracking.

**Closed** 2022-12-12 18:19 UTC
