### ISSUE TITLE
[MU4 Issue] Crash with Muse Sounds alto flute and other orchestra instruments

### ISSUE THREAD

**Issue by BoBogus** [musescore/MuseScore#16463] opened 2023-02-21 06:09 UTC
**Describe the bug**
I've been working on a sizeable orchestral piece that uses a full orchestra (the score is attached below).  I created and added to that project several times over the past couple of months with no issues.  However, when I tried to open it again a couple of days ago, the program immediately crashed while loading the sounds.  I restarted the program, restarted the computer, and even uninstalled and reinstalled the program.  The problem still persists.

_Edit:_ It seems that the alto flute is to blame.  See comment below for details.

**To Reproduce**
1. Unknown at this time.  On my PC, open a large score with an alto flute part (like the one attached) was sufficient.
2. The program suddenly closes about halfway through loading in the sounds — it doesn’t even freeze.

**Expected behavior**
I expected the score to open and the sounds to load so I could edit it.

**Screenshots**
Tomorrow, I’ll add a screen recording.

**Platform information**
 - OS: [Windows 10 Pro]
 - Hardware: Intel i7 CPU, 32GB RAM, NVIDIA GeForce RTX 2070 Super graphics card

**Additional context**
I doubt that it’s a corrupted file since this isn’t the only score I've had that happen to — the program also crashes while loading a backup version that I had put in Google Drive well before the problem started, as well as while loading an entirely unrelated full-orchestra score.  All of them are using Muse Sounds (which I'm pretty sure are all up to date).  One thing each relevant score shares in common is a VSTi called ARIA Player, although I can open a score that contains just that one instrument with no issues.  (_Edit:_ More significant is the fact that they all contain the alto flute, which was demonstrated below to be the culprit.)

**Comment by DmitryArefiev** [comment] 2023-02-21 09:59
@BoBogus Can you attach the score please? (it should be zipped before attaching because GitHub doesn't allow mscz files)

And what build are you using?

Thanks!

**Comment by BoBogus** [comment] 2023-02-21 11:07
Oh shoot, I did forget to attach it.  I’m not at my computer right now, so I can’t submit a zip or look at my build right now, but I can send a Google Drive link to one of the scores that crashed it.  The link is https://drive.google.com/file/d/1NChLGpu6UHFaFAHCaHAg4Pl0IBHxdL-l/view?usp=drivesdk .  I’ll reply with build information and a zip tomorrow (when I’m at my computer).

**Comment by DmitryArefiev** [comment] 2023-02-21 12:55
Thanks! I've tried your score [Sinfonia Concertante No. 1, Op 1 (1).zip](https://github.com/musescore/MuseScore/files/10793698/Sinfonia.Concertante.No.1.Op.1.1.zip) but **can't reproduce the crash** on my side (Windows10, latest 4.0.2 build)


https://user-images.githubusercontent.com/90187801/220350346-53bb14be-714f-4185-930b-1331f6dcb962.mp4

**Comment by DmitryArefiev** [comment] 2023-02-21 12:58
Can you try the latest 4.0.2 build? - https://github.com/musescore/MuseScore/actions/runs/4229451252

Also try to check MuseSounds are updated (in MuseHub>Settings)

**Comment by BoBogus** [comment] 2023-02-21 15:54
Ah, I’m pretty sure I am still on 4.0.1.  I’ve used the “Check for updates” button recently but saw nothing about the new build.

**Comment by MarcSabatella** [comment] 2023-02-21 16:26
It's not released; you would need to grab a "nightly" build.  You can grab it from the link provided above, or from musescore.org (Download / Software then scroll down to the nightly development builds section).

**Comment by BoBogus** [comment] 2023-02-21 19:10
I still have that problem in the nightly build for 4.0.2.

**Comment by DmitryArefiev** [comment] 2023-02-22 15:33
>  There, I also have to open it by right-clicking on the score and telling it to open in that program because the function to browse for a file within MuseScore 4.0.2 causes the program to freeze (not an issue in 4.0.1).

Yes, it's fixed today and should be in nightly builds tomorrow #16477

**Comment by BoBogus** [comment] 2023-02-23 20:28
1.  I’ll check on that.
2. As far as I know, that setting applies only to the current score and to new ones.  That means I would need to have one of those scores open in order to make that change.

**Comment by BoBogus** [comment] 2023-02-24 01:04
Also, the "Playback Setup" button is now grayed out.

**Comment by DmitryArefiev** [comment] 2023-03-01 13:13
> As a final test, I'll once again disable Muse Sounds by moving it to a Documents folder, reopen the score using MS Basic, save it to apply MS Basic instrument mappings, then close it and move Muse Sounds back into its correct folder. That way, I can manually reapply Muse Sounds one instrument at a time to see where the problem is.

Not necessary to disable Muse Sounds by moving it to a Documents folder. You can just activate MS Basic in View>Playback Setup and select individual instruments from MuseSounds in Mixer

> Thankfully, I now know I can get around this issue by using a bass flute sound there. However, since the other score that crashed it also contained an alto flute, it seems Musescore really doesn't like that combo (on my machine, at least).

It's strange that you still have a crashes on your side after reinstalling MuseSounds..  Can you attach other scores were crash occurs (I'll try on my side)

Also, can you try Revert to factory settings and reopen score after that (Help>Revert to factory settings)? But please note your settings will be reset to default.

**Comment by Fristover** [comment] 2023-03-01 13:26
I can confirm there was an issue with alto flute crashing some scores, same thing with Bb clarinet, flute 1 and piccolo, all of these should already be fixed on the latest muse woodwinds update though...

**Comment by BoBogus** [comment] 2023-03-07 09:22
> Not necessary to disable Muse Sounds by moving it to a Documents folder. You can just activate MS Basic in View>Playback Setup and select individual instruments from MuseSounds in Mixer

Actually, I couldn't do that because the score wouldn't stay open in a state where that was possible (at least, not in a way that would have applied to that score).

> Also, can you try Revert to factory settings and reopen score after that (Help>Revert to factory settings)? But please note your settings will be reset to default.

That didn't end up being necessary, since all I had to do was pick a different sound and the issue was resolved (unless I reselected the Alto Flute sound).

**Comment by BoBogus** [comment] 2023-03-07 09:29
I initially closed the issue, but then figured it's probably best to let you do that if you believe it has been satisfactorily resolved.

**Comment by DmitryArefiev** [comment] 2023-03-08 15:44
> I initially closed the issue, but then figured it's probably best to let you do that if you believe it has been satisfactorily resolved.

NP, if your issues don't occur on your side anymore you can easily close them by yourself.

Thanks!

**Comment by DmitryArefiev** [comment] 2023-03-08 15:44
Closing

**Closed by DmitryArefiev** 2023-03-08 15:44 UTC
Labels: crash
