### ISSUE TITLE
Coping (CTRL+C) of text does not work properly

### ISSUE THREAD

**Issue by zdenop** [musescore/MuseScore#18839] opened 2023-07-29 08:17 UTC
### Issue type

UI bug

### Bug description

Coping (CTRL+C) of text (e.g. title) and paste it into an external file (e.g. txt) extract also **part of** formatting:
```
<font size="22"/><font face="Edwin"/>My title
```
This problem is with all text items.

IMO copying (CTRL+C) of text should produce plain text or rich text.

### Steps to reproduce

1. Add the title
2. Select a word from the title
3. Press CTRL+C
4. Go to any text editor and pres CTRL+Vthe a 

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/574156/36a4e0ff-b00b-4bc2-b75f-e3c04b0857cc)

![image](https://github.com/musescore/MuseScore/assets/574156/8ceb26ed-af64-43a6-a8e2-9651a3b24b71)

### MuseScore Version

4.1.1.23071203

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2023-07-29 12:24
This seems a duplicate of https://github.com/musescore/MuseScore/issues/16146, which has already been fixed in development builds of the next release, 4.2.

**Closed by cbjeukendrup** 2023-07-29 12:24 UTC
Labels: UI
