### ISSUE TITLE
Weird numpad behavior and not working dotted shortcut

### ISSUE THREAD

**Issue by ProgUn1corn** [musescore/MuseScore#19841] opened 2023-10-27 12:00 UTC
### Issue type

Other type of issue

### Bug description

I'm sorry if there's something similiar, but I haven't found a solution. I use Numpad . to use as a shortcut for dotted note in note input mode, in Musescore 3 it worked flawlessly, however in Musescore 4 I can not toggle the dotted note specifically in note edit mode, but every other numpad shortcuts work. I can toggle it outside note input mode, but this would be a huge pain for me. I write mostly guitar tabs. I'm using English(US) interface and qwerty layout keyboard.

### Steps to reproduce

1. toggle note input mode
2. press . on numpad
3. nothing happened
4. exit note input mode
5. press . on numpad
6. the note is dotted

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/50629932/ed1e6369-cd44-4fb8-a6fc-eeb49ca49bda

### MuseScore Version

4.1.1-232071203

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Version 2009 or later

**Comment by zacjansheski** [comment] 2023-10-27 14:32
I am unable to reproduce
Windows 11, 4.1.1 and Nightly
Logitech Keyboard

https://drive.google.com/file/d/1TEfvCNBaIk4h0KXT19IPwkHxhPECrkoW/view?usp=sharing

**Comment by ProgUn1corn** [comment] 2023-10-27 19:01
> I am unable to reproduce Windows 11, 4.1.1 and Nightly Logitech Keyboard
> 
> https://drive.google.com/file/d/1TEfvCNBaIk4h0KXT19IPwkHxhPECrkoW/view?usp=sharing

I think maybe it's because some specific device has specific definition of keyboard? I don't know about it, but my keys are working normal in other different apps.

Sorry, I've just found that none of the keys is working for the dotted toggle. I tried to set the shortcut to other things like T, it didn't work either. Is there something I need to care with the settings? Again I'm working with a guitar tab, but I have tried it with Piano either.

**Comment by zacjansheski** [comment] 2023-10-27 19:12
I am not reproducing with tab staves either.

Check in Preferences > Shortcuts that you have this definition.  If not you can try to reset it or maybe try a "Revert to Factory Settings"

![Screenshot 2023-10-27 151049](https://github.com/musescore/MuseScore/assets/69917893/f9ff4b97-8d70-42a0-b335-d3d232a255c4)

**Comment by ProgUn1corn** [comment] 2023-10-27 19:15
<img width="501" alt="image" src="https://github.com/musescore/MuseScore/assets/50629932/567d44d2-a124-4049-ad7c-114cd2050ec8">
Yes, I've tried it several times. It's weird that I have installed on different systems, and they strangely behaved the same.

**Comment by ProgUn1corn** [comment] 2023-10-27 19:20
https://github.com/musescore/MuseScore/issues/14574
 
I've found this, it seems like a known problem. Sorry I didn't found this, because I searched for Numpad dot. It seems that turns out dot does not work in tab with 4.1.1 now.

**Comment by zacjansheski** [comment] 2023-10-27 19:37
You can use the nightly build 

https://musescore.org/en/nightly-builds

I will close this as completed

**Closed by zacjansheski** 2023-10-27 19:37 UTC
Labels: needs info, needs review, regression_ms3

**Comment by ProgUn1corn** [comment] 2023-10-27 19:43
Thank you very much. I didn't know there's nightly build to download.

Zac Jansheski ***@***.***> 于2023年10月28日周六 04:37写道：
