### ISSUE TITLE
[MU4 Issue] "Appearance" section of properties tab becomes persistent always-on-top window

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10462] opened 2022-02-06 00:15 UTC
This may well be specific to my system - Linux running within a container in ChromeOS.  I'll be interested to see if it reproduces for others.  But no doubt something strange is going on:

1) select any text element in a score
2) click the Appearance button in the Properties tab
3) switch to another window (eg, not MuseScore)
Result: the Appearance pane continues to appear on top of any other window

For example, here's what I saw when reproducing those steps just now and returning to this very window

![image](https://user-images.githubusercontent.com/1799936/152663279-6f84d9f6-5bee-4545-89bf-e6c1b35a1037.png)

**Comment by rzvxa** [comment] 2022-02-06 20:07
@MarcSabatella Hello, I've tried to reproduce this issue and it didn't happened, as you yourself also said it's probably happening due to your complicated setup i guess some events are getting lost with all the virtualization happening all over the place.
I guess right now we don't have a way to trace this issue (at least i don't have required setup to reproduce it) I'm just posting this comment so that you know it's not happening in windows 10. Let me know if you found any useful information to help tracing it without having a ChromeOS as host machine.

**Comment by Tantacrul** [comment] 2022-05-30 17:17
Not able to reproduce on Mac. Is it still happening for you, Mark?

**Comment by MarcSabatella** [comment] 2022-05-30 17:36
It used to happen always.  Now it happens only occasionally.  Similar for other menus and popups.  It's still a bit wonky but not nearly as bad as before.  Feel free to close if no one else sees this.

FWIW, I would prefer it stay *open* when switching windows, but there's a separate issue about that - https://github.com/musescore/MuseScore/issues/11248, which was specifically about the add palettes popup but the discussions shows it's a general "feature".

**Comment by Tantacrul** [comment] 2022-05-30 17:48
Agreed on your last point. OK, closing for now.

**Closed by Tantacrul** 2022-05-30 17:48 UTC
Labels: P3
