### ISSUE TITLE
[MU4 Issue] Applying augmentation dot to rests before entering

### ISSUE THREAD

**Issue by jieshunwang** [musescore/MuseScore#13620] opened 2022-10-04 22:38 UTC
**Describe the bug**
Applying augmentation dot to a rest before entering the rest does not give a dotted rest.

**To Reproduce**
1. New score
2. Enter into note input mode
3. Select crotchet note
4. Select augmentation dot
5. Press 0 into keyboard
6. A crotchet rest appears on the score

**Expected behavior**
A dotted crotchet rest should appear on the score

**Platform information**
Edition	Windows 11 Home
Version	22H2
Installed on	‎28/‎09/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by sammik** [comment] 2022-10-05 06:44
Duplicate of #11851

**Closed** 2022-10-05 07:49 UTC
