### ISSUE TITLE
[MU4 Issue] Muse Hub noContentError

### ISSUE THREAD

**Issue by MalignantCarp** [musescore/MuseScore#14976] opened 2022-12-06 05:55 UTC
**Describe the bug**
Honestly, a picture is worth a thousand words, so see screenshot below.

**To Reproduce**
1. Run Muse Hub
2. See the error

**Expected behavior**
Muse Hub should load as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/93364935/205829865-202bcabb-c455-4452-bc72-a5b2845842fa.png)

**Platform information**
Muse Hub v 0.9.10.559_x64
Windows 10 Pro 64 Bit, Version 21H2 Build 19044.2251.

**Additional context**
This may be tied to #14975, though perhaps it is now a more pervasive connectivity issue, though again, my Comodo firewall is correctly configured to allow both Muse.exe and Muse.Service.exe full access to the Internet, so unless it is running its network through an intermediary executable, it should be getting content just fine. The previous version I was running (0.9.9.515) displayed as expected.

**Comment by DominicMaas** [comment] 2022-12-06 17:28
These two issues are likely caused by the same root issue (the code used to check if the device is connected to the internet or not), I'll follow up in https://github.com/musescore/MuseScore/issues/14975

**Comment by DominicMaas** [comment] 2022-12-14 05:36
This should now be fixed in the latest version of Muse Hub (v0.9.12)

**Comment by oktophonie** [comment] 2023-02-22 17:07
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.

**Closed by oktophonie** 2023-02-22 17:07 UTC
Labels: P1
