### ISSUE TITLE
[MU4 Issue] Dialog box action button order

### ISSUE THREAD

**Issue by ItsPepperpot** [musescore/MuseScore#15570] opened 2022-12-24 19:28 UTC
**Description**
Not necessarily a bug, more of a question regarding UI/design - on Windows it is standard (implemented in system applications and recommended by Microsoft for dialog boxes) that the order of the buttons on dialog boxes has the "OK/Accept" button on the left hand side of a dialog, and the Cancel button to the right.

However, on Windows, MuseScore 4 has confirmation/primary actions on the right hand side.

Is this a deliberate design choice to have this button order on Windows? Or perhaps a side effect of having cross platform support (I'm aware the button layout is different on other operating systems - macOS, for example, recommends the "OK" button on the rightmost edge).
Apologies if this comes off as me telling you how to design your app - I was mostly curious as to whether it was intentional and if so, what the thought process was 🙂
Thanks.

Relevant Microsoft documentation: https://learn.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box#commit-buttons

Steps to reproduce the behaviour:
To see the save dialog, for example
1. Make changes to a score
2. Press the [X] button on the top bar without saving changes
3. Save dialog appears 

**Screenshots**
Screenshot from MuseScore on Windows:
![image](https://user-images.githubusercontent.com/12785991/209448853-b9454fd3-fa87-4dad-a35d-3e831d0fc154.png)

Example from Microsoft documentation:
![image](https://user-images.githubusercontent.com/12785991/209448878-dc5c9be4-de4e-47f5-b41f-1a7e39efdf76.png)

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment] 2022-12-24 20:16
Thanks for reporting! This is indeed not intended. In the new UI framework and the way we use it, there is no way yet to make the button order platform dependent, but this is being worked on.

Since this issue is a duplicate of #10505, I'll close this one, but thanks for the additional info you've attached here!

**Closed by cbjeukendrup** 2022-12-24 20:16 UTC
