### ISSUE TITLE
Sustain pedal mark failure

### ISSUE THREAD

**Issue by Pakusch** [musescore/MuseScore#20605] opened 2023-12-20 19:19 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

After doing the MS 4.2.0 upgrade I find thet all sustain pedal markings has stopped funcioning. 

### Steps to reproduce

1. Go to any keyboard system
2. White a note
3. Choose sustain pedal and mark
4. Listen back. The not is not prolonged

### MuseScore Version

MS 4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win 11

**Comment by cbjeukendrup** [comment] 2023-12-20 19:45
I cannot reproduce this so far. Is it broken in all scores for you, and even in newly created scores?
If only a specific score is affected, could you please upload that? (Rename it to have `.zip` in the end instead of `.mscz`, so that GitHub allows you to upload it)

**Comment by Pakusch** [comment] 2023-12-20 19:53
I have tested quote a few. None that work. Also new dont work. Neither
remarking old.

ons. 20. des. 2023, 20:45 skrev Casper Jeukendrup ***@***.***

**Comment by Jojo-Schmitz** [comment] 2023-12-20 20:28
Stems from https://musescore.org/en/node/358049, but I've seen a couple more reports of this in the forums

**Comment by MarcSabatella** [comment] 2023-12-21 12:58
Two thoughts:

1 . Maybe these scores are not for piano?  It is already reported and confirmed that pedal no longer works for mallet instruments.  Please, @Pakusch - it it fails for all the scores you have tried, pick one of them and zip & attach it here.

2. Maybe the people for whom it doesn’t work are using Muse Sounds but didn’t get the Muse Sampler update?  It’s already known that a fairy number of people are experiencing Muse Guitar issues (notes playing short / muted) due to Muse Sampler for whatever reason not having updated.  Maybe somehow there is an incompatibility between 4.2 and older Muse Samplers?

**Comment by MarcSabatella** [comment] 2023-12-21 13:41
From MuseScore, Diagnostic / Muse Sampler / Check Muse Sampler

The mallet percussion issue was already filed separately (I’m on phone now or I’d find the link).

**Comment by Jojo-Schmitz** [comment] 2023-12-21 13:42
Thanks.

**Comment by Pakusch** [comment] 2023-12-21 14:07
My experience of the problem was with mallet instruments.


tor. 21. des. 2023, 14:42 skrev Joachim Schmitz ***@***.***>:

**Comment by bkunda** [comment] 2023-12-21 14:57
Great. Then we can confirm this is a duplicate of https://github.com/musescore/MuseScore/issues/20579

**Closed by bkunda** 2023-12-21 14:57 UTC
Labels: needs info, regression, UX/interaction
