### ISSUE TITLE
[MU4 Issue] Can't color chord notes in different colors if they are in the same voice

### ISSUE THREAD

**Issue by vpavlenko** [musescore/MuseScore#14659] opened 2022-11-22 12:04 UTC
**Describe the bug**
Can't color chord notes in different colors if they are in the same voice

**To Reproduce**
1. Enter a chord in voice 1
2. Select one note of a chord and change its color via Properties -> Appearance
3. All three chord notes are colored

**Expected behavior**
Only a selected note changes the color, the other two chord notes remain black (default color)

**Screenshots**
MuseScore 3 behavior: 
<img width="446" alt="Screenshot 2022-11-21 at 15 50 40" src="https://user-images.githubusercontent.com/1491908/203309058-048fb5db-3113-40bc-aa7c-7ea71d0afdc5.png">

<img width="634" alt="Screenshot 2022-11-21 at 15 48 44" src="https://user-images.githubusercontent.com/1491908/203309071-8b0ef9d9-9d40-4926-a03c-e4d9a1fd524d.png">

MuseScore 4 behavior:
<img width="298" alt="Screenshot 2022-11-21 at 15 51 11" src="https://user-images.githubusercontent.com/1491908/203309065-4284f533-9c5e-434e-8eda-14b87678bf32.png">

<img width="616" alt="Screenshot 2022-11-21 at 15 48 26" src="https://user-images.githubusercontent.com/1491908/203309075-c692ab1c-6d8a-400a-bb26-293054f4d833.png">

**Platform information**
macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072008, revision: github-musescore-musescore-2c34155

**Additional context**
Also reported at https://musescore.org/en/node/337091

**Comment by RomanPudashkin** [comment] 2022-11-22 12:29
Duplicate of https://github.com/musescore/MuseScore/issues/11096

**Closed by RomanPudashkin** 2022-11-22 12:29 UTC
