### ISSUE TITLE
Glissando Indication Disappears from Score

### ISSUE THREAD

**Issue by toto-polo** [musescore/MuseScore#23782] opened 2024-07-26 11:04 UTC
### Issue type

Engraving bug (incorrect score rendering)

## Steps to Reproduce:

1. Open Musescore 4.3.2 on macOS Ventura.
2. Create a new score or open an existing one.
3. Add a glissando indication (e.g., "gliss") to a section of the score, particularly using the harp as the instrument.
4. Observe that the glissando indication sometimes disappears from the score.
5. Modify the pitch of the notes or write further in the score.
6. Notice that the glissando indication reappears.

## Actual Behavior:
The glissando indication ("gliss") disappears from the score, but the audio engine still plays the glissando correctly.

## Expected Behavior:
The glissando indication should remain visible in the score at all times, reflecting the actual playback by the audio engine.

## Additional Information:

- This bug has been observed in previous versions of Musescore as well.
- The issue occurs specifically when using the harp as the instrument.
- Musescore version: 4.3.2
- Operating System: macOS Ventura

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4ca2fd43-c5ca-4a41-98dc-d80ca369c0c6

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.3.2-241630832

### Regression

No.

### Operating system

MacOS Ventura 13.6

### Additional context

OS: macOS 13.6, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-07-26 12:11
Duplicate of https://github.com/musescore/MuseScore/issues/21441 and fixed in master.
If you can reproduce this in a nightly build we will reopen.

**Closed by oktophonie** 2024-07-26 12:11 UTC
Labels: engraving
