### ISSUE TITLE
Very Large and Misplaced Automatic Chord Tie Marks

### ISSUE THREAD

**Issue by Mr-Freeze-is-cool** [musescore/MuseScore#20951] opened 2024-01-10 20:57 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Recently I when I have been moving notes in a tied chord Musescore has been creating a tie line that usually connects to a point halfway through the piece and has an enormous size. 

I notice it mostly when there is a larger amount of notes in a chord. This seems to only be an issue in continuous (horizontal) view and not in either of the others. Switching between the views does not change anything in the horizontal view.

Times this happens:
When changing the inversion of the chord (ie. moving one of the chord tones up or down an octave)
Copy and pasting a tied chord (happens when the tie is already in place and when one is created across a bar line)
Moving notes on another part (I have only experienced this once but I moved all the notes on another part down an octave and the issue occurred on that part and a different part)

Ways I have found to temporarily fix it:
Save the file, close and reopen song (This is only a temporary fix and is not always consistent)
Select the enlarged tie mark, delete it, save file, scroll up/down to reset line spacing (This isn't a true fix but it keeps me from having to manually change every tie mark that does this.)

In testing I have found that with a new, blank score the ties will all connect to the middle of measure 36 but in other scores I have seen it connect to other measures, like in the screenshot below where it connects to measure 16. Also I have seen it with smaller (3 note) chords but for new, blank scores I have found that 6 notes works well.

The tie still functions as it should and it seems to isolated to just engraving.

### Steps to reproduce

1. Create a score with 36+ measures (In my testing it does not matter if you start with less and add them or create a score with more than 36)
2. Create a 6+ note chord 
3. Tie that chord across a bar line after measure 36

### Screenshots/Screen recordings

![Screenshot 2024-01-10 141506](https://github.com/musescore/MuseScore/assets/82484077/0737c9f2-b1a2-4f38-9fa2-b6a6a089003a)
![Screenshot 2024-01-10 142015](https://github.com/musescore/MuseScore/assets/82484077/7f3776fb-3b53-49c7-a8c6-da1ae0b6ff71)
![Screenshot 2024-01-10 145240](https://github.com/musescore/MuseScore/assets/82484077/6522dede-c061-422d-ab43-f2032ead726d)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by MarcSabatella** [comment] 2024-01-10 21:09
Presumably a duplicate of https://github.com/musescore/MuseScore/issues/20551, fixed already for 4.2.1

**Closed** 2024-01-10 21:09 UTC
Labels: regression, engraving
