### ISSUE TITLE
[MU4 Issue] Migration changes "Leland" into "Emmentaler"

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#10021] opened 2021-12-08 18:40 UTC
**Describe the bug**
Migration changes `Leland` into `Emmentaler`.

**To Reproduce**
1. Start MU3
2. Create a simple score using `leland` as a font.
3. Save the file.
4. Close MU3
5. Start MU4
6. Open the file which was just created in MU3.
7. When the migration form appears, choose `Keep old style`
8. Check the font in the style editor, it's not `Emmentaler` instead of `Leland`.

**Expected behavior**
In MU4 the font for the score should have `leland`, not `Emmentaler`.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by riaanvn** [comment] 2022-01-11 19:15
Is this a duplicate of https://github.com/musescore/MuseScore/issues/10021 ?

**Comment by njvdberg** [comment] 2022-01-11 19:20
> Is this a duplicate of #10021 ?

No, this **is** #10021 :wink:

**Comment by riaanvn** [comment] 2022-01-11 19:37
Lol, #facepalm/linescrossed. I meant this looks like a duplicate of https://github.com/musescore/MuseScore/issues/9070 (8 Sept '21)

**Comment by oktophonie** [comment] 2022-02-01 10:35
Certainly looks like it :)

**Closed by oktophonie** 2022-02-01 10:35 UTC
