### ISSUE TITLE
Change the default names of dynamic markings in the palette to make them findable via search

### ISSUE THREAD

**Issue by NotSoCommonSense** [musescore/MuseScore#19757] opened 2023-10-17 23:50 UTC
### Your idea

Currently, the default names for dynamics in the palette are pp, p, mf, f, et cetera. Given that the names are single letters, it makes finding them by search very difficult sometimes, as one can, for example, search for 'forte' and the forte marking wont appear, but searching 'f' makes every other marking with the letter F in the name pop up, which is obviously very inconvenient. 

I understand the names can be changed, but this really shouldn't be necessary. 

The names of the dynamics should be the actual names and not just the letters by default.

I really don't think this change would be enormous, but it would help a lot. Also, it isn't obvious that the names of elements can be changed manually.

![Screenshot 2023-10-17 184940](https://github.com/musescore/MuseScore/assets/71298218/4c9791b6-bb48-462a-84d4-aedcf2d52344)

![Screenshot 2023-10-17 185008](https://github.com/musescore/MuseScore/assets/71298218/8939c897-c5d0-40ab-8a0d-0f3103315f62)

### Problem to be solved

Findability of dynamic markings

**Comment by DaddyLudwig** [comment] 2023-10-18 00:44
Duplicate of [https://github.com/musescore/MuseScore/issues/12905](url)

**Comment by DaddyLudwig** [comment] 2023-10-18 00:46
Duplicate of #12905

**Closed** 2023-10-18 06:22 UTC
Labels: feature request
