### ISSUE TITLE
[MU4 Issue] Piano Keyboard - Does Not Dock

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11328] opened 2022-04-25 08:40 UTC
**Describe the bug**
Onscreen keyboard does not dock when selecting Dock function from three dot menu.

**To Reproduce**
1. Select 'View > Piano keyboard'
2. Click on three dot menu in upper right corner of Piano keyboard window
3. From the menu select 'Dock'
4. Nothing happens

**Expected behavior**
Piano keyboard should dock horizontally in bottom section of application window.

**Screenshots**
<img width="1920" alt="Screen Shot 2022-04-25 at 11 39 20 AM" src="https://user-images.githubusercontent.com/30370609/165052635-584ab241-a662-4d9d-a3c7-cb65247e55a6.png">

**Platform information**
 OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment] 2022-04-25 08:47
Note: Was able to get to properly dock after "Revert to Factory Settings" then closing and reopening the app (revert did not automatically close and reopen app or change behavior of docking).

**Comment by lengthwave** [comment] 2022-04-25 11:24
@Tantacrul - FYI

**Comment by cbjeukendrup** [comment] 2022-04-26 19:38
There seems to be one more requirement to reproduce this bug: namely that there is no other horizontal widget currently opened. If there is, the piano keyboard will just dock together with that other widget when opening it for the first time. 

I don't think this issue is really related to the Piano Keyboard; it should theoretically be reproducible with any dock widget. If you select the "Dock" option, the widget will be put back at the place where it was docked for the last time. But if the widget has never been docked anywhere before, that obviously fails, so nothing happens. After you dock the widget to some place, and then undock it again, the "Dock" action will start working from that moment.

I'm not totally sure if it is an expected situation that a dock widget has no last docking position. You'd say that any widget should be docked by default when opening it for the first time, so it should always have a last docking position, which should be remembered when closing and reopening the app. But for some reason, it apparently doesn't always work like that. 

@RomanPudashkin Is it okay if this gets assigned to you? Since you're the master of the docking system :)

**Comment by RomanPudashkin** [comment] 2022-04-26 20:04
@cbjeukendrup 
>Is it okay if this gets assigned to you? Since you're the master of the docking system :)

Yes, I assigned it to myself. Thank you for your investigation!

**Comment by boryskuzmenko** [comment] 2022-08-09 14:04
@lengthwave Could you reproduce it on the last master build?

**Comment by boryskuzmenko** [comment] 2022-08-11 13:10
Can't reproduce. 
@lengthwave Please, reopen if still reproducible for you

**Closed by boryskuzmenko** 2022-08-11 13:10 UTC
Labels: P2, needs testing
