### ISSUE TITLE
[MU4 Issue] Key signatures not properly applied on newly inserted instruments/staves

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#15007] opened 2022-12-07 05:15 UTC
**Describe the bug**
Key signature assigned on score are not applied on staves/instruments inserted after score creation.

**To Reproduce**
1. Create score as of liking
2. Insert an additional stave on an instrument OR insert another instrument after the score is created
3. See error

**Expected behavior**
Assigned key signature should also be applied on newly inserted staves.

**Video Demonstration**

https://user-images.githubusercontent.com/90231404/206094168-dc310cee-4ab9-4e88-8589-b85513493f94.mp4

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223410309, revision: github-musescore-musescore-c26899b

**Comment by oktophonie** [comment] 2022-12-07 07:48
Don't seem to be able to reproduce this one (regardless of whether creating from template or not, adding key sig at score creation stage or after, having concert pitch on or off, etc).

**Comment by MarcSabatella** [comment] 2022-12-07 13:43
The key is probably something having to do with the current status of the top score in the staff.  If it's percussion, or otherwise has a non-standard key signature, that could affect this.  Although I wasn't able to reproduce that way either.

But also, I note that is not the RC build.  Could be a bug fixed already.

**Comment by oktophonie** [comment] 2022-12-07 14:08
I tried this in various builds (RC, latest nightly) and couldn't reproduce it anywhere. The problem sounds suspiciously like https://github.com/musescore/MuseScore/issues/14675 but the PR fixing that issue isn't merged yet so that should have no bearing.

**Comment by cgpqci** [comment] 2022-12-08 05:57
Trying the RC right now. It still occurs.

![image](https://user-images.githubusercontent.com/90231404/206368783-4a21d233-a75a-4442-be05-8f5e9e520e74.png)
![image](https://user-images.githubusercontent.com/90231404/206368819-49e0990f-a8a6-4e66-9a58-14b586248c9f.png)

**Comment by cgpqci** [comment] 2022-12-08 08:41
Did another round of testing.

> The key is probably something having to do with the current status of the top score in the staff. If it's percussion, or otherwise has a non-standard key signature, that could affect this.

Uhh...I think for this one I might come to concur this bug may possibly be caused by transposing instruments. But considering my other previous tests, it seems like it only happens at some extent.

Here's another example where new staves are assigned in Bb major when the score's set in C Major. Perhaps note the presence of the transposing Bb clarinet in the score.

https://user-images.githubusercontent.com/90231404/206395720-6d1ca11e-fee7-47ef-a0b6-e34ac1a9606a.mp4

**Comment by mike-spa** [comment] 2022-12-09 09:00
I believe this problem was fixed in PR #14849, specifically in this commit -> ff302dcfd82531adf9b706d2fbfdbb7af66596ab . The PR was merged to master yesterday, so @cgpqci it'd be great if you could build the latest master (or grab the latest nightly build from the top of the list list [here](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D)) and confirm if the issue is indeed gone. @Tantacrul @vpereverzev if we confirm that the issue is fixed in master (and assuming we want to fix it for release), then we would need merge commit ff302dcfd82531adf9b706d2fbfdbb7af66596ab into RC (atm, it has only been merged into master).

**Comment by cgpqci** [comment] 2022-12-09 09:40
Testing from the latest nightly build, I can confirm the bug seems to be fixed.

**Closed** 2022-12-09 17:30 UTC
Labels: P2
