### ISSUE TITLE
"Wrong rhythm" when change time signature (in fact only missing eight flag)

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#20864] opened 2024-01-07 09:41 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When time signature changes, sometimes flag is missing on eight note, so it looks like incorrect rhythm.

### Steps to reproduce

see video

https://github.com/musescore/MuseScore/assets/1646034/887f3782-ef00-4cf3-8200-fb42def5dcf4

### MuseScore Version

master (4.3)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

It worked even in 4.2

**Comment by oktophonie** [comment] 2024-01-08 14:56
It fixes itself after the next redraw.

**Comment by oktophonie** [comment] 2024-01-12 18:05
Duplicate of https://github.com/musescore/MuseScore/issues/20358

**Closed by oktophonie** 2024-01-12 18:05 UTC
Labels: P1, regression, engraving
