### ISSUE TITLE
[MU4 Issue] Cancelling new score dialog leaves a second top-level MuseScore window open

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8875] opened 2021-08-18 21:00 UTC
Using New Score then cancel when a score is already open leaves a second main application window open (with no score open) running in its own process.
 
**To Reproduce**
1. Open or create a score
2. Navigate to File|New Score
3. Click cancel
4. Second window is opened with no score opened

**Expected behavior**
No extra windows should be shown on "cancel", just return to existing score window.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Eism** [comment] 2021-11-15 09:10
Duplicate of https://github.com/musescore/MuseScore/issues/9631

**Closed by Eism** 2021-11-15 09:10 UTC
Labels: P2
