### ISSUE TITLE
[MU4 Issue] Destination folder is not opened after score export (PDF, mp3, etc.) when 'Open destination folder on export' is enabled 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14421] opened 2022-11-08 13:36 UTC
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Open any score
2. Go to Export dialog and choose PDF 
3. Enable 'Open destination folder on export'
4. Run export

**Expected behavior**
Destination folder is opened after score export (PDF, mp3, etc.) when 'Open destination folder on export' is enabled 

**Screenshots**

https://user-images.githubusercontent.com/101250347/200578621-aa4e155b-6db7-4270-a88a-15b0ce3784da.mp4

**Platform information**
 - OS: macOS

**Comment by DmitryArefiev** [comment] 2022-11-08 14:13
Can reproduce on my side as well (**Mac12.6**) but after second iteration of export:

1. Open any score
2. Go to Export dialog and choose PDF
3. Enable 'Open destination folder on export'
4. Run export - at this stage all fine, Finder opens with a proper location
5. Go to Export dialog again and choose MP3 (or other) 
6. Enable 'Open destination folder on export'
7. Run export - now **Finder appears just for a moment**. It **moved behind MuseScore** window

https://user-images.githubusercontent.com/90187801/200586897-6260a2b5-6a74-4498-bce5-42840fc018a7.mov


**Can't reproduce** on **Windows**

**Comment by Tantacrul** [comment] 2022-11-21 19:12
Ah it works for me on MacOS 12.1

Is it still an issue now?

**Comment by DmitryArefiev** [comment] 2022-11-22 22:17
> Ah it works for me on MacOS 12.1
> 
> Is it still an issue now?

Can't reproduce it as well now..

@abariska Closing for now. Please reopen if it still occurs on your side

**Closed** 2022-11-22 22:18 UTC
Labels: P2
