### ISSUE TITLE
[MU4 Issue] Metronome can't be unmuted from mixer

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14344] opened 2022-11-05 15:25 UTC
Title says it all basically. It's an unnecessary limitation in my opinion. certainly because muting the metronome when enabled is an option  leading to weird scenarios where metronome is enabled but mute and also, you can then unmute it again but it then stays muted but also locked in that state. In that case you're presented with the strange situation where the metronome symbol indicates the metronome being active and the mixer saying it is not.
I'd really like to see it never being locked on mute.

**Comment by zacjansheski** [comment] 2023-07-06 17:37
Similar to https://github.com/musescore/MuseScore/issues/11031

**Comment by RomanPudashkin** [comment] 2024-04-25 07:46
Duplicate of https://github.com/musescore/MuseScore/issues/13283

**Closed by RomanPudashkin** 2024-04-25 07:46 UTC
Labels: P3, feature request, mixer
