### ISSUE TITLE
Crash when deleting note with attached trill line (macOS)

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#23153] opened 2024-06-09 11:07 UTC
### Issue type

Crash or freeze

### Bug description

MuseScore Studio 4.3.1 crashes every time you delete a note that has a trill line attached to it.

### Steps to reproduce

1. Create a new score of any instrument and add a note to any measure.
2. Attach a trill line from the palettes to the note.
3. Make sure the note is selected and hit Delete on your computer keyboard.

### Screenshots/Screen recordings

![Crash](https://github.com/musescore/MuseScore/assets/163907533/1a494a77-234a-4785-a7fd-5a9b91ba33c4)

### MuseScore Version

4.3.1

### Regression

Yes, this used to work in **MuseScore 4.2.1**

### Operating system

macOS 12.7.2

### Additional context

Occurs also on macOS 14.5, but apparently not Windows.

Note that this occurs with trill line, but not a regular trill.

See [this post on .org](https://musescore.org/en/node/364877) for details.

Note that this issue appears to be fixed in the latest 4.4 nightly. It would be a shame though, to have to wait 4 or 5 months to get the fix.

**Comment by Jojo-Schmitz** [comment] 2024-06-09 12:35
Is that 1st measure by chance followed by multimeasure rests? The image doesn't show this, but that 1st m easure is suspiciously long

**Comment by DmitryArefiev** [comment] 2024-06-09 18:44
> Is that 1st measure by chance followed by multimeasure rests? The image doesn't show this, but that 1st m easure is suspiciously long

Nope, it doesn't related to multimeasure rests.  It's because it doesn't occur on Windows, but easy to **reproduce on Mac**:

https://github.com/musescore/MuseScore/assets/90187801/ef27b4a9-16a6-4e9f-998e-c659e038db76

**Comment by DmitryArefiev** [comment] 2024-06-09 18:52
Oh I see now.. 

> Note that this issue appears to be fixed in the latest 4.4 nightly. It would be a shame though, to have to wait 4 or 5 months to get the fix

It's really doesn't occur in master (4.4)

@Riley-Sullivan If log it and the bug is already fixed (in 4.4) you should indicate this in summary

**Comment by DmitryArefiev** [comment] 2024-06-09 18:53
@bkunda It's a candidate for 4.3.2 patch

**Comment by Jojo-Schmitz** [comment] 2024-06-09 19:29
Why then closing the issue?

**Comment by RomanPudashkin** [comment] 2024-06-10 07:10
Looks like the crash has been fixed in master by [this commit](https://github.com/musescore/MuseScore/commit/b78f185e5a1172de60de9406148cdbbbefec93bf)

**Closed** 2024-06-10 14:04 UTC
Labels: P0, regression, crash
