### ISSUE TITLE
[MU4 Issue] Crash when clicking on a note while using a sound card Sound Blaster X4

### ISSUE THREAD

**Issue by Eism** [musescore/MuseScore#10433] opened 2022-02-03 10:33 UTC
**To Reproduce**
1. Connect and select as sound output device Sound Blaster X4
2. Open MuseScore
3. Open project
4. Click on a note
4. See crash

**Expected behavior**
MuseScore should not crash

**Platform information**
 - OS: Windows

**Additional context**
The problem is on connecting AudioClient to the sound card. 

2022-02-03T09:39:38.750 | ERROR | main_thread |            | logError: AUDCLNT_E_UNSUPPORTED_FORMAT
2022-02-03T09:39:38.750 | ERROR | main_thread | AudioModule | onInit: audio output open failed

Most likely incorrect settings when trying to connect to the device

**Comment by Tantacrul** [comment] 2022-05-30 17:11
@Eism - are you still experiencing this crash?

**Comment by RomanPudashkin** [comment] 2022-05-30 17:13
@Tantacrul this crash was reported by @oktophonie (as far as I remember)

**Comment by shuffleQ** [comment] 2022-05-31 17:29
Got the same thing, with a Behringer U-Phoria UMC204HD. Window instantly closes upon anything sound related, ie clicking on a note, or going to DevTools > Audio
Platform is Win 11, tested on the at the time latest nightly, 2022-05-31 04:34

**Comment by Tantacrul** [comment] 2022-05-31 18:29
I'll elevate it to a P0 then, if we're getting it for multiple users.

**Comment by oktophonie** [comment] 2022-06-15 11:53
If a proper fix would be difficult/time-consuming right now, is it at least possible in the interim to fix it so that MuseScore doesn't crash (even if there's no sound)? It's making my testing very difficult.

**Comment by Eism** [comment] 2022-08-23 13:49
@oktophonie @shuffleQ 
Can you check on the nightly build? Is the bug still reproducible?

**Comment by oktophonie** [comment] 2022-08-23 14:43
In latest nightly/master, I seem to have no problems in Windows now.

In Linux (artix) I find that the crash will happen if anything else is using the audio system at the time (a YouTube video playing, etc); if not, it won't, and playback will work fine in MuseScore, but no _other_ applications will play any sound. I'm happy to call that a quirk or my system if nobody else reports similar issues. (Possibly the info in #11220 will be relevant.)

**Comment by Eism** [comment] 2022-08-26 11:34
@oktophonie 
Your bug looks like a bug we recently fixed. Related to midi device(Midi Through) choosing, which MuseScore does not support.
So, please reset the preferences and recheck. Also make sure you are using the correct version(last nightly build)

**Comment by oktophonie** [comment] 2022-08-26 12:09
No change since last time I checked, i..e. it is working fine in Windows now, but on Linux the problem remains; again, that could be some oddity of my system and nothing to do with MuseScore. If nobody else is having any problems at this point, then I guess this is fixed!

**Comment by DmitryArefiev** [comment] 2022-09-29 15:13
@oktophonie @Tantacrul Maybe we can close it now or move to Beta2 since it's Linux only and not often reproduced?

**Comment by lyrra** [comment] 2022-09-29 18:55
PR exist that works around the issue: https://github.com/musescore/MuseScore/pull/8956

**Comment by oktophonie** [comment] 2022-09-30 09:15
@DmitryArefiev fine by me!

**Comment by vpereverzev** [comment] 2022-09-30 09:23
@Tantacrul @oktophonie @DmitryArefiev 
in the latest master the crash shouldn't appear anymore. However, you'll not get any sound, since we still can't open the audio-driver to work with this sound-card, requires separate investigation.

**Comment by DmitryArefiev** [comment] 2022-09-30 13:14
Let's close this one and reopen if will happen again

**Closed** 2022-09-30 13:15 UTC
Labels: P0
