### ISSUE TITLE
[MU4 Issue] Janky Diagnostic Tab

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#16498] opened 2023-02-23 00:49 UTC
**Describe the bug**
For 'Show paths' and 'Show profiler' dialogue boxes -->The top bar (with the 'X' button) doesn't show by default. Sometimes it opens in a new window, sometimes not. ESC key works only when you haven't clicked out of the big dialogue box yet.

**To Reproduce**
1. Diagnostic -> System -> Show paths or Show profiler
2. Notice errors

**Error behaviour**
- The top bar (with the X symbol) doesn't appear by default - it is outside my screen, so it seems like there's no way to click out of the window.
- ESC only works when you haven't clicked something outside the big dialogue box. (Doesn't work even if you click somewhere inside the dialogue box after clicking somewhere else.)
- You can re-size the window for the top bar to appear again 🤔
- Sometimes the big dialog box opens as a separate window (look at taskbar), sometimes not.

**Expected behavior**
No jankiness - window _fits inside my screen_, either opens as a separate window or not, ESC works _always_, as long as I'm focussed on that dialogue box.

**Platform information**
 - OS: Windows 10 64-bit
 - Musescore 4.0.1 (not a nightly, if that matters)

https://user-images.githubusercontent.com/102642087/220797167-cb12bf73-f751-4721-973a-3e5b124861cc.mp4

**Comment by rich777300** [comment] 2023-02-23 01:01
And these dialogue boxes from the diagnostic tab ties into #10597 too...but already logged in there.

**Comment by cbjeukendrup** [comment] 2023-06-18 12:32
This looks like a duplicate of #16702, which has been fixed, so I'll close this issue. Please let me know if I'm mistaken!

**Closed by cbjeukendrup** 2023-06-18 12:32 UTC
