### ISSUE TITLE
[MU4 Issue] Crash when reopening score after deleting staff where system objects would appear

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15472] opened 2022-12-21 13:23 UTC
**To Reproduce**
1. Create a score **from the Symphony orchestra template**
2. Open the "Add/remove instruments" dialog
3. Remove the strings instruments (violins and everything below)
→ The violins staff was namely one of the staves where system objects would be shown
4. Press OK
5. Save the score
→ The mscx now contains:
    ```xml
        <SystemObjects>
          <Instance staffId="0" barNumbers="false"/>
          </SystemObjects>
    ```
6. Reopen the score
→ `systemObjectStaves` now contains a nullptr; see `Read400::readScore400`, especially the lines:
    - `int staffIdx = e.attribute("staffId").toInt() - 1;` and `sysStaves.push_back(staffIdx);`, which puts a `-1` in `sysStaves`
    - `for (int idx : sysStaves) { score->addSystemObjectStaff(score->staff(idx)); }`, which tries to get the staff at index -1, which returns nullptr
8. Save the score again
→ Crash; see `Score::write`, from the line `if (!systemObjectStaves.empty()) {`

**Comment by DmitryArefiev** [comment] 2023-02-24 08:46
@cbjeukendrup I **can't reproduce** the crash  (master, Win10)

**Comment by DmitryArefiev** [comment] 2023-02-24 09:18
Probably it was fixed earlier in #15938

Can reproduce in 4.0.0

**Comment by DmitryArefiev** [comment] 2023-02-24 09:19
Tested in latest **4.0.2 build** on Win10, Mac12, LinuxUbuntu 22.04 - **DOESN'T OCCUR**

Closing

**Closed** 2023-02-24 09:20 UTC
Labels: P1, crash

**Comment by DmitryArefiev** [comment] 2023-03-01 16:03
Retested on Win10
