### ISSUE TITLE
[MU4 Issue] MU 4.0.2-nightly crashed

### ISSUE THREAD

**Issue by aige02** [musescore/MuseScore#16119] opened 2023-01-28 23:57 UTC
What I did using MuseScoreNightly-230270506-4.0.2-3e9f131-x86_64 on Windows 11:
1. Opened score
2. Looked at sax parts in measures 57 and 59.
Note: I've been working around the playback limitations of gliss'es using hidden elements in voice 2. See also measures 46-50.
3. Visited first 4 parts (Alto 1, Alto 2, Tenor 1, Tenor 2) and set zoom to 75%.
4. Still looking at the Tenor 2 part, I think I adjusted the length of the gliss. in measure 58. (After reopening the file, the gliss. appears to be adjusted.)
4. Went back to Tenor 1 part and lengthened gliss. in measure 58. MU crashed.

This is probably related to my crashes reported in [#343461](https://musescore.org/en/node/343461) where the problem appears to be that MU 4.0 corrupts the measure numbering. When I tried to recreate this crash, I noticed that the indicated measure numbers in the score were incorrect, with too many beats in indicated measures. However, the measure were painted correctly. I joined and split measures 2 and 3 which forced renumbering the measures and restored the indicated numbering for the score, but the parts had an extra measure, with 8 beats, after measure 3. I had been experimenting with MuseScoreNightly-230260506-4.0.2-68b18e4-x86_64 and the above version, so the initial measure number problem could have happened in either version, but probably in 68b18e4.

I had been pursuing workarounds for the problem in [#342864: Copying measures with not visible elements may ignore visibility when displaying some elements.](https://musescore.org/en/node/342864) "Copying complicated measures may ignore visibility when displaying some elements". That problem, which was also in 3.6, also affected the implicit copying to parts.

I found that MU 4.0 appears to have an additional problem with parts in that sometimes the part gets nothing, not even the visible elements when copying such a measure in the score.

Originally reported as above in [#343708](https://musescore.org/en/node/343708) with attached file: [Shiny_Stockings.mscz](https://musescore.org/sites/musescore.org/files/2023-01/Shiny_Stockings_1.mscz).

**Comment by DmitryArefiev** [comment] 2023-01-30 08:43
@aige02 I can't reproduce the crash.. Can you try again please? Maybe there are some additional steps

**Comment by aige02** [comment] 2023-01-30 18:18
Between when I created this issue and when I added the above comment, I determined that the measure number problem occurs when MU reads the MSCZ file for any version of my Shiny Stocking score.  I have continued to add to the score and the problem occurs every time I open the score.  This lead to me finding the workaround described in my previous comment.

I think the solution to this issue is to determine why MU cannot read the Shiny Stocking MSCZ file correctly and fix that problem.

**Comment by DmitryArefiev** [comment] 2023-01-31 10:38
@aige02 If the crash doesn't happen anymore we can close the issue.

> I think the solution to this issue is to determine why MU cannot read the Shiny Stocking MSCZ file correctly and fix that problem.

Please log a separate issue with the steps to reproduce if it not leads to crash. For now, it's clear for me what the issue is and how to reproduce it.

Regarding the crash bugs, very important to find the steps which lead to crash each time. In that case developers can easily find the root cause and fix it. Otherwise it's hard to find in the code where the crash occurs.

**Comment by DmitryArefiev** [comment] 2023-01-31 10:59
@aige02 Also, if the crash happens again with that score and it's hard to define the sequence of steps just use our new feature **Save diagnostic files** and attach that zip file here please. Thanks!

https://user-images.githubusercontent.com/90187801/215742231-ce6f8963-064d-45ec-a115-acfb86955653.mp4

**Comment by aige02** [comment] 2023-01-31 23:11
Here are the diagnostic dumps.  [ShinyStockings-corrupt-m8-s19.zip](https://github.com/musescore/MuseScore/files/10550467/ShinyStockings-corrupt-m8-s19.zip)

This particular crash doesn't happen anymore.  If I force the internal renumbering of the measures, 4.0.2 seems fairly stable (doesn't crash).  Without the renumbering, 4.0.2 crashes frequently - as evidenced by 18 DMP files in the zip.  MU 4.0 cannot read my Shiny Stockings without messing up the internal measure numbers.  A new problem has recently arisen - measure 8, staff 19 (drumset) has the first snare hit (quarter note drumset 'A') replace with a whole rest, putting 7 beats in the measure.  Opening the file reports that measure corrupted (no matter how many times I correct it and save it).

Also, for almost all of the logs, the original file has been modified.  In the future, I'll save a copy the latest version and include it with the log file.  (In addition to the 18 DMP files, the ZIP has 23 LOG files.)

Dmitry, I can close this and open a new critical issue about the internal measure number problem causing crashes, or you can take a look at that as a solution for this issue.  (If you open ShinyStockings.mscz with 4.0.2, you will see that, for example, measure 8 has the internal measure number of 5.)  Your choice.

**Comment by aige02** [comment] 2023-02-05 03:44
The original problem appears to have been a corruption that was caused by a problem that has been fixed.  Previously, writing the file to MusicXML did not fix the problem, but using the nightly for 23033, passing the file though MusicXML fixed the problem.

**Comment by aige02** [comment] 2023-02-05 03:51
The original problem appears to have been a corruption that was caused by a problem that has been fixed.  Previously, writing the file to MusicXML did not fix the problem, but using the nightly for 23035, passing the file though MusicXML fixed the problem.

**Closed** 2023-02-05 03:52 UTC

**Comment by DmitryArefiev** [comment] 2023-02-05 17:26
@aige02 Good to hear. Please reopen if the crash occurs again, and thanks for deep investigation!
