### ISSUE TITLE
Crash when trying to save while two projects are open, and when trying to copy and paste within a project (one score)

### ISSUE THREAD

**Issue by samsoeder** [musescore/MuseScore#20572] opened 2023-12-19 20:10 UTC
### Issue type

Crash or freeze

### Bug description

I'm not sure if these crashes are connected or not but I didn't start experiencing the crash while copy and pasting until the first crash happened. 

I had 2 projects open, a large orchestral score using musesounds, and a 2 piano reduction score also using musesounds, When I tried to save one of the projects it would cause that project to crash. The orchestral score crash first, after reopening it, and trying to save the piano reduction, the piano project crashed.

Now whenever I try to copy and paste in the orchestral score it causes a crash, regardless if the other project is open or not. The piano score does not crash when copy and pasting, even if the orchestral score is open. (maybe the orchestral score is corrupted? Musescore has not alerted that the project is corrupted.)

### Steps to reproduce

 (Edited by @DmitryArefiev , also see comments below)

1. Open [Symphonic Dance.zip](https://github.com/musescore/MuseScore/files/13726880/Symphonic.Dance.zip)
2. Hit save

### Screenshots/Screen recordings

I have a video of the crash when copy and pasting. The video is cropped to end right before it crashes to desktop. 

https://github.com/musescore/MuseScore/assets/119996302/bb3dd9c7-339f-496d-8ab2-4ee2349f019e

### MuseScore Version

 MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

OS: Windows 10/Mac13

### Additional context

I have 5 crash logs that start when the first crash happened, and end with the video I recorded.

[MuseScore_231219_130448.log](https://github.com/musescore/MuseScore/files/13719896/MuseScore_231219_130448.log)
[MuseScore_231219_130511.log](https://github.com/musescore/MuseScore/files/13719897/MuseScore_231219_130511.log)
[MuseScore_231219_131343.log](https://github.com/musescore/MuseScore/files/13719898/MuseScore_231219_131343.log)
[MuseScore_231219_132701.log](https://github.com/musescore/MuseScore/files/13719899/MuseScore_231219_132701.log)
[MuseScore_231219_132805.log](https://github.com/musescore/MuseScore/files/13719900/MuseScore_231219_132805.log)

**Comment by DaddyLudwig** [comment] 2023-12-19 20:15
Might be something specific to your scores or your system cause I don’t have issues with either copy and paste or saving with multiple scores open. Windows 10 for me and no crashes.

**Comment by samsoeder** [comment] 2023-12-19 20:20
> Might be something specific to your scores or your system cause I don’t have issues with either copy and paste or saving with multiple scores open. Windows 10 for me and no crashes.

I thought it may have been an issue with running out of system memory. But that doesn't explain why it still crashes with only one project open. I haven't had issues with it crashing in the past, nor other large scores.

**Comment by MarcSabatella** [comment] 2023-12-19 22:51
Please ZIP and attach the score that crashes, along with precise steps to reproduce he problem (what edit you perform after opening the score and before saving).

**Comment by samsoeder** [comment] 2023-12-19 23:05
[Scores.zip](https://github.com/musescore/MuseScore/files/13721148/Scores.zip)



Have both projects open on one screen as windows.

Copy measures from the orchestral score, paste it into the piano score and implode the voices.

Try to save the orchestral score (I didn't make any changes. I just have a habit of constantly saving)

orchestral score crashes

Now anytime I try to copy and paste inside the orchestral score it crashes. (copying any measure and pasting causes a crash)

the crash also happens if you save within the piano score while the orchestral score is open. But I can still copy and paste in the piano score.

**Comment by MarcSabatella** [comment] 2023-12-20 00:17
I can confirm a crash simply trying to save the file "Symphonic Dance".  No multiple socres or editing required, just load the file and save.

Seems to be a regression vs 4.1.1

With 4.2, an assertion failure is printed to console during the *load* (not the save):

17:10:16.544 | ERROR | 138473405146880 | SingleLayout::layoutItem | Not handled: Harmony
17:10:16.549 | ERROR | 138473405146880 | SingleLayout::layoutItem | "ASSERT FAILED!": false, file: ../src/engraving/rendering/single/singlelayout.cpp, line: 222

Not sure if that's relevant or not.  There don't seem to be any chord symbols in the score, though.

**Comment by samsoeder** [comment] 2023-12-20 00:20
Im pretty sure I have never used any chord layout. Maybe its the harp diagrams?

**Comment by MarcSabatella** [comment] 2023-12-20 00:28
The line with the assertion failure is actually about tremolo between notes.; the Harmony error might be a red herring (but an odd one, and perhaps problematic in itself).

But I can confirm if I delete the tremolos, the crash goes away.

**Comment by DmitryArefiev** [comment] 2023-12-23 10:50
Fixed in #20629

**Comment by DmitryArefiev** [comment] 2023-12-23 10:52
@samsoeder Please try build from #20629 (if is all OK on your side as well). 

Thanks!

**Comment by samsoeder** [comment] 2023-12-24 14:51
> @samsoeder Please try build from #20629 (if is all OK on your side as well).
> 
> Thanks!

Sorry. But I'm not sure how to run the latest build of musescore. I just use musehub to install musescore.

**Comment by MarcSabatella** [comment] 2023-12-24 14:57
It's a little complicated if you've never done it before.  But I tested, and it definitely fixes the crash on my system.

**Comment by samsoeder** [comment] 2023-12-24 14:59
Ok. Thank you for the help and all the work you all do. I assume I can close this issue?

**Comment by MarcSabatella** [comment] 2023-12-24 15:04
No, it will be closed automatically when the proposed change is merged into the main program.

**Comment by DmitryArefiev** [comment] 2023-12-27 09:33
Fixed in #20629

**Closed** 2023-12-27 09:32 UTC
Labels: P0, regression, crash

**Comment by DmitryArefiev** [comment] 2023-12-27 09:36
@MarcSabatella Thanks for testing!

@samsoeder The fix should be in the next MuseScore release (and will be available via MuseHub)

But if the bug is blocking you please let us now and I or Mark will provide instructions how to use the current master build with the fix inside

**Comment by Jojo-Schmitz** [comment] 2023-12-27 12:25
Once ported to 4.2.1, that is...
