### ISSUE TITLE
Freeze/Crash adding text frame at start of score 4.4.2

### ISSUE THREAD

**Issue by SystemsModelling** [musescore/MuseScore#24926] opened 2024-09-26 08:19 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

Open attached score. Select first (square) notehead of incipit. Add >  frames > insert text frame.  Freezes, have to use Task Manager to kill. See screenshot of task usage,

### Supporting files, videos and screenshots

<img width="659" alt="Musescore freeze add text frame at start" src="https://github.com/user-attachments/assets/f2507e80-0606-41b2-ba1b-5747f75fbf7f">
[Beatam me dicent transcribed POB - Copy.txt](https://github.com/user-attachments/files/17145216/Beatam.me.dicent.transcribed.POB.-.Copy.txt)
Why can't I upload mscz files? I had to rename it to .txt

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Win 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment] 2024-09-26 08:54
To upload a mscz file here you have to zip it.

**Comment by jeetee** [comment] 2024-09-26 09:47
I see your score has Staff Type Change elements, so I think this might be a duplicate of #24795 and as such likely fixed in current development builds.

**Comment by SystemsModelling** [comment] 2024-09-26 10:22
> To upload a mscz file here you have to zip it.

I renamed it to .zip, thank you!
[Beatam me dicent transcribed POB - Copy.zip](https://github.com/user-attachments/files/17146750/Beatam.me.dicent.transcribed.POB.-.Copy.zip)

**Comment by oktophonie** [comment] 2024-09-26 10:30
Am happy to confirm @jeetee's suspicion that this is indeed fixed - you'll have no problem with nightly builds of 4.4.3 or indeed in the release itself which shouldn't be too far off.

**Closed by oktophonie** 2024-09-26 10:30 UTC
Labels: crash
