### ISSUE TITLE
Copypasting key/time signatures

### ISSUE THREAD

**Issue by ThatOnePianist** [musescore/MuseScore#20957] opened 2024-01-11 11:10 UTC
### Your idea

This is really annoying. When I'm copypasting music, I expect MU to copy everything for me. But if I have a change of key signatures, or, even worse, time signatures, MU just doesn't copy them. This is extremely annoying, as I have to either:
- Copypaste the music before the change of signature, then change the signature, then copypaste the music after the change of signature,
- Change the signature after I copypasted the whole music (which is really messy)

### Problem to be solved

This would save a lot of time to do either of the things mentioned above.

**Comment by oktophonie** [comment] 2024-01-11 11:12
Duplicate of https://github.com/musescore/MuseScore/issues/15590

**Closed by oktophonie** 2024-01-11 11:12 UTC
Labels: feature request
