### ISSUE TITLE
[MU4 Issue] Crash after toggling notehead parentheses following an undo command

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16527] opened 2023-02-24 10:43 UTC
**Describe the bug**
MuseScore crashes when the the ‘Add parentheses to element‘ shortcut is used together with the ‘Notehead parentheses‘ toggle in Properties, following an undo command.

**To Reproduce**

https://user-images.githubusercontent.com/86290556/221156469-e3331dfb-3c0b-4bc3-8736-d804cde0bd7a.mov

**Additional information**
This issue was apparently fixed in [#15152](https://github.com/musescore/MuseScore/issues/15152)
Also occurs in 4.0.1
Ultimately, it would make sense if the interaction between this shortcut and the ‘Notehead parentheses‘ toggle was more robust (i.e. triggering the shortcut changed the toggle in Properties; undoing that shortcut command reverted the toggle in Properties, etc. I suspect some connection here with [#15150](https://github.com/musescore/MuseScore/issues/15150).

**Platform information**
- OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230550503, revision: github-musescore-musescore-172fa52

@oktophonie FYI (This was uncovered while exploring options for #16500)

**Comment by cbjeukendrup** [comment] 2023-02-24 17:01
This crash occurs only on 4.0.2 and not on master, right? (because master contains https://github.com/musescore/MuseScore/issues/15152 while 4.0.2 doesn't)

**Comment by DmitryArefiev** [comment] 2023-02-28 08:34
> This crash occurs only on 4.0.2 and not on master, right? (because master contains #15152 while 4.0.2 doesn't)

Yes, it **looks fine** in **master** and still **crashes** in **4.0.2** (Win10, latest builds)

**Comment by RomanPudashkin** [comment] 2023-02-28 10:08
Duplicate of https://github.com/musescore/MuseScore/issues/15152

**Closed by RomanPudashkin** 2023-02-28 10:08 UTC
Labels: P1, crash
