### ISSUE TITLE
Rhythmic Slash Notation and Articulation are Offset by default

### ISSUE THREAD

**Issue by Nicholas-Wise** [musescore/MuseScore#19125] opened 2023-08-21 23:05 UTC
### Issue type

Engraving bug

### Bug description

articulation on rhythmic slash notation is always offset to the right by default (offset unchanged/still 0.00).
Rhythmic slash notation also appears to be slightly offset to the left. 
This is extremely consistent and the value it's offset by seems to change from quarter note to half note

### Steps to reproduce

Add Articulation to Rhythmic Slash Notation. Very consistent.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/106282447/4c3fa361-9907-4465-aa64-e54c45acbcf1)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later,

**Comment by MarcSabatella** [comment] 2023-08-22 02:17
To be clea, it’s not specific to rhythmic slash notatio. - it’s any note with a slash notehead in which the articulation is stem side.

**Comment by oktophonie** [comment] 2023-08-22 06:56
Duplicate of https://github.com/musescore/MuseScore/issues/18707

**Closed by oktophonie** 2023-08-22 06:56 UTC
Labels: duplicate, engraving, regression_ms3
