### ISSUE TITLE
Cannot use scroll wheel to adjust volume in the mixer

### ISSUE THREAD

**Issue by spoopw** [musescore/MuseScore#25809] opened 2024-12-11 23:44 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

You can no longer use the scroll wheel to change the volume levels in the mixer. It has always worked before

1. Open mixer
2. Hover over volume and scroll 
     - This should change the volume

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/40b4e987-d5e4-4ddc-abc6-2210a72d5f6b)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4-243461245

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Eism** [comment] 2024-12-12 09:09
Thanks for reporting, but it is by design, see https://github.com/musescore/MuseScore/issues/11128 for more info
I'll close this issue

**Closed by Eism** 2024-12-12 09:09 UTC
Labels: regression MS4, UX/interaction
