### ISSUE TITLE
[MU4 Issue] VST - Score doesn't ask to save after I make VST changes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9788] opened 2021-11-18 16:39 UTC
**Describe the bug**
This also goes to same to VST FX.
Any changes to make with VST (Sounds or FX) then close the score, MS4 does not show a dialog if I want to save score or not. When closes it reverts back and cancels changes. This happens either by closing the project by using the project tab, or by closing the whole app. I demonstrate both of these in the video.

https://user-images.githubusercontent.com/71656189/142457467-860497bb-9ed4-4247-bdf1-d99330649f86.mp4

**Expected behavior**
When making any changes including change of VST, a dialog should pop up like this:
![image](https://user-images.githubusercontent.com/71656189/142457409-02a885c0-ef46-4462-9159-4814d5568a36.png)

**Desktop (please complete the following information):**
 - OS: Windows (not sure if same on Mac)

**Comment by cbjeukendrup** [comment] 2021-11-19 08:59
Duplicate of #9469
(more or less)

**Closed** 2022-03-22 15:00 UTC
Labels: P1, duplicate
