### ISSUE TITLE
Palettes>Time signatures/Key signatures>More>Create dialog has locked divider 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23735] opened 2024-07-23 15:17 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open Palettes>Time signatures/Key signatures>More>Create time signature/key signature

![Capture](https://github.com/user-attachments/assets/2b99aa8d-dbc2-421d-b48c-a2b0461d2e27)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/c997d885-07fe-42c0-acda-c900f54b3fea

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Win/Mac

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-07-23 15:24
Duplicate of https://github.com/musescore/MuseScore/issues/22493?

**Comment by DmitryArefiev** [comment] 2024-07-23 15:29
Yeah.. Thanks!

**Closed** 2024-07-23 15:30 UTC
Labels: duplicate
