### ISSUE TITLE
Opening an old Musescore 4.3.2 mscz file crashes MuseScore 4.4

### ISSUE THREAD

**Issue by TobyTwo32** [musescore/MuseScore#23723] opened 2024-07-22 13:14 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open MuseScore 4.4 bin
2. Choose an old mscz file
3. crash 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/fd5c6060-c0ea-4aaf-be96-9aa697e8fa5c

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-07-22 22:22
I can't reproduce.  Can you ZIP and attach one of the scores you are seeing problems with?

**Comment by cbjeukendrup** [comment] 2024-07-22 22:41
Also, are you sure that it is not just a case of https://github.com/musescore/MuseScore/issues/23722 ?

**Comment by TobyTwo32** [comment] 2024-07-22 22:44
@cbjeukendrup @MarcSabatella Yes it is a symptom of the #23722 . My bad.

**Comment by cbjeukendrup** [comment] 2024-07-22 22:54
Ah, no problem, but then I will close it as a duplicate. Thanks!

**Closed by cbjeukendrup** 2024-07-22 22:54 UTC
Labels: regression MS4, crash
