### ISSUE TITLE
[MU4 Issue] keyboard doesn't work in file dialogs 

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13113] opened 2022-09-01 07:18 UTC
**Describe the bug**
In Open file, or Save dialog window doesn't react to keystrokes.

**To Reproduce**
1. Click "Open file"
2. Try to navigate by arrows, or write filename
3. Keyboard is ignored in file dialog (main program is responding)

or

1. Click "Save As"
2. Try to navigate by arrows, or write filename
3. Try to confirm file name by Enter
6. Keyboard isignored in file dialog (You can only write filename, Enter produces "line break" in Score)

**Expected behavior**
In file dialogs keyboard strokes should affect file dialog (not main program)

**Screenshots**

https://user-images.githubusercontent.com/1646034/187854714-7cbc1472-8b78-4baf-96dd-7e7474a77d93.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
may be same problem, as in #12915

**Comment by MarcSabatella** [comment] 2022-09-01 13:31
As far as I know, this is an issue only on Linux, and only when using the native file dialogs, or not using them - not sure which as I still don't totally know the difference.  And was supposedly fixed by a change a couple of months ago.  But I can confirm it's still an issue for me.

See also:

https://github.com/musescore/MuseScore/issues/11859
https://github.com/musescore/MuseScore/issues/10836

**Comment by DmitryArefiev** [comment] 2022-09-01 14:37
Hi @sammik @MarcSabatella , can you try again on latest master build please?

Native dialog doesn't appear for me using master build from https://github.com/musescore/MuseScore/actions/runs/2968922506

Thanks!

**Comment by MarcSabatella** [comment] 2022-09-01 14:52
Is the current nightly build (I just updated an hour ago) the same as "latest master", or was something merged since last night?

For me, the bug definitely still exists - if I hit Ctrl+O, click a file, then hit Enter, that Enter is passed directly to the score (so,it adds a system break if I have something selected).  I tried a revert to factory settings in case I had some older setting enabled to force the other dialog.

I have no idea how to tell the difference between a "native" and "non-native" file dialog just by looking, because really, I use very few Linux apps and they each seem to have different dialogs.  But I don't see any difference in how the dialog has looked any time in the last several months or so.  This is what I see now and have seen as long as I can remember in MU4 builds:

![image](https://user-images.githubusercontent.com/1799936/187945081-191264a3-f650-45a8-907c-e5fc47412d78.png)

**Comment by MarcSabatella** [comment] 2022-09-01 15:22
I've also downlaoded and tested that specific build artifiact, with the same result.  The file dialog looks like the picture above, and hitting Enter continues to affect my score, not close the dialog.

**Comment by DmitryArefiev** [comment] 2022-09-01 15:59
That's strange.. I have another dialog (which should be after fixing #10836):
![Screenshot from 2022-09-01 21-44-51](https://user-images.githubusercontent.com/90187801/187959181-5511655e-f4bf-4973-a249-76e24c587276.png)

Maybe OS version makes a difference. I have **Linux Mint 20.2**

@sammik @MarcSabatella Which OS version do you have on your side?

**Comment by sammik** [comment] 2022-09-01 16:48
Seems to be different file dialog on my side.
![File-dialog](https://user-images.githubusercontent.com/1646034/187968627-d54ed97f-2c8b-454c-9dce-4a6bfc3a05fe.png)

OS: Ubuntu Studio 22.04 (KDE Plasma)

**Comment by Jojo-Schmitz** [comment] 2022-09-01 16:49
Native vs. Qt file dialog?

**Comment by MarcSabatella** [comment] 2022-09-01 18:04
Debian "bullseye" 11.2 for me.  The dialog @DmitryArefiev shows is looks vaguely familiar, like maybe I've seen some program or other use it, but not one I'm really accustomed to.

One other thing about my setup - while most people running Linux have a "window manager" running completely within Linux, my Debian installation runs as a container within ChromeOS, and the window management happens primarily on the ChromeOS side.  This *almost* never actually makes a difference, but could be a factor here.  On the other hand, if that *were* to be a factor, I'd expect it to make it *harder* to access the "native" file dialog.  If MU4 is providing its own dialog, I can't see any reason why my system wouldn't use it.  Unless maybe there is some environment variable overriding the behavior?  The factory reset cleared out my ".ini" file, so there's nothing there that could be responsible.  Also, this system uses Wayland, if that matters.

**Comment by Jojo-Schmitz** [comment] 2022-09-01 18:20
Native File dialogs is the default

**Comment by sammik** [comment] 2022-09-01 18:37
> Native File dialogs is the default Should be in the advanced settings

@Jojo-Schmitz I didnt find this settings in MU4 (nor in Preferences, nor in DevTools)

**Comment by Jojo-Schmitz** [comment] 2022-09-01 18:42
No sure it survived the move from 3 to 4, but is should have

**Comment by Jojo-Schmitz** [comment] 2022-09-02 08:01
No sure it survived the move from 3 to 4, but it should have.

See also https://musescore.org/en/node/151171 and #11240 resp. #12111
And also https://musescore.org/en/node/297613

**Comment by MarcSabatella** [comment] 2022-10-09 16:14
FWIW< this is still an issue for me, so I've been looking into it a little to see if I can find a workaround.  I assume we are using https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html?  According to the description, this attempts to use native dialogs but falls back to QML otherwise.  I suspect some window managers just don't provide a usable native dialog - and in the case of Chromebooks, there really isn't a window manager in the traditional sense.  So falling back to QML may be inevitable sometimes.

Frankly, that's fine by me.  Yes, it has some limitations, but no worse than those in MuseScore 3 - *except* the keyboard issue, which is really a killer for usability.  But - it *does* seem like we can customize the default QML implementation to at least some extent.  From the description "If that also isn't possible, then it will fall back to a QML implementation, DefaultFileDialog.qml. In that case you can customize the appearance by editing this file."  I know nothing about QML and in particular whether that statement means only *appearance* and not *behavior* can be customized, but anyhow, this would make a reasonable workaround.

**Comment by MarcSabatella** [comment] 2022-10-20 15:00
@Eism Thanks for the PR!  And, now I know that setting QT_QPA_PLATFORMTHEME=gtk3 in my own environment actually solves this right away even in current nightly builds.  Now I just need to get used to the new (to me) dialog!

**Comment by Eism** [comment] 2022-10-20 15:27
@MarcSabatella 
Yes, the problem could be solved by adding just one line.
But there is a problem with activating the dialog after the show.
For example, the dialog does not block the program, you can switch to the main window. Also, after re-opening the dialog, it appears behind the main window.

So, another two commits is about fixing this behaviour

**Comment by MarcSabatella** [comment] 2022-10-20 15:37
Nice!  I didn't mean to suggest the others changes weren't useful too - I'm just happy I can be using this already today in current builds.

FWIW, I see what you mean about it not blocking, but I haven't had any problem yet with the dialog not appearing on top.  Of course, I've only been using this technique a few minutes :-)

**Comment by sammik** [comment] 2022-10-20 16:30
Thank You @Eism !

**Comment by Eism** [comment] 2022-10-21 07:55
@sammik 
does this mean that you tested the build and everything is fine with you?

**Comment by MarcSabatella** [comment] 2022-11-05 16:31
Can the PR for this be merged?  I've been using the workaround of manually setting the environment variable, but as mentioned, it's not ideal.

**Comment by DmitryArefiev** [comment] 2022-11-06 20:18
@MarcSabatella I think so. There were some additional issues in previous PR builds but the last one looks good on my Linux.

Did you try this one https://github.com/musescore/MuseScore/actions/runs/3339470803 ?

**Comment by MarcSabatella** [comment] 2022-11-06 21:59
It does work in the sense of displaying the intended dialog without my needing to explciitly set the environment variable, and that dialog does indeed respond to keybaord input correctly.  But it does still seem to be a separate top level window - it shows a separate (generic) icon on my system taskbar, I can still switch back to the main window (which will then hide the dialog), etc.  It does *block* the main window, which is good.  But so does simply setting environment variable.

Anyhow, even if it's not perfect, it's definitely better than the current situation, so I'd be fine with seeing this merged as is for now and revisted later whener there is time.

**Comment by DmitryArefiev** [comment] 2022-11-07 10:59
OK. Thanks for testing! Yes, let's merge it

**Closed** 2022-11-07 11:00 UTC
Labels: P2

**Comment by GabeS573** [comment] 2026-05-24 05:30
Issue has reappeared, see #33532
