### ISSUE TITLE
[MU4 Issue] Removing measures crashes MuseScore 4

### ISSUE THREAD

**Issue by marcelroed** [musescore/MuseScore#15519] opened 2022-12-22 17:23 UTC
**Describe the bug**
I'm working on a score I made in 3.x, and have extended it by adding the primo part to a 4-handed piece.
I am able to add measures, but when I try to delete them with "remove selected range ⌘⌫," Musescore 4 crashes.
I haven't done anything other than basic operations to the score, so this is quite crippling in that I'm not able to remove measures in any other way.

**To reproduce**

Open attached MWE file in MuseScore 4.
Select some of the empty measures toward the end of the score.
Tools > Remove selected range
Musescore crashes

Deleting measures seems to work fine with Musescore files that I create from scratch.

**Expected behavior**
The measures should be gone, and Musescore should not crash.

**Screenshots**
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/13435604/209190819-50d48e0e-a90c-42d3-9dfa-652aa20fb013.png">

**Platform information**
OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

I've included an example
[example.mscz.zip](https://github.com/musescore/MuseScore/files/10289146/example.mscz.zip)

**Comment by Grillzombie** [comment] 2022-12-22 22:11
Same here on OS: Linux Mint 21.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

**Comment by cbjeukendrup** [comment] 2022-12-23 00:09
I can reproduce the crash with this file, but it is probably because the file is corrupted. The corruption might have happened because of measures being added; that's a known case currently, see #15185. Strange though that the corruption is also in the full score (see the last few measures), because I believe that the known corruption would only affect the part scores. So there's more going on.

Probably the best thing you can do right now is creating a new file and copying the not-corrupt-looking measures to that new file. 
Or, if you still have the MS3 file and haven't done a lot in MS4 yet, go back to the MS3 version. 

@Grillzombie Do you mean you can reproduce the issue with the same score, or with a different one?

**Comment by marcelroed** [comment] 2022-12-23 02:30
Is there any reasonable way to check if a measure is corrupt or not? I'm not quite sure what I can copy and not to a new MS4 file. I did the entire Primo part in MS4, so I don't think going back to MS3 is an option.

**Comment by Grillzombie** [comment] 2022-12-23 07:59
@cbjeukendrup
With the score provided from marcelroed

**Comment by oMrSmith** [comment] 2022-12-23 09:56
Should it be allowed to enter measures in parts anyway?

**Comment by cbjeukendrup** [comment] 2022-12-23 20:56
> Is there any reasonable way to check if a measure is corrupt or not? I'm not quite sure what I can copy and not to a new MS4 file. I did the entire Primo part in MS4, so I don't think going back to MS3 is an option.

@marcelroed This functionality is currently missing, but it is added back in #15488. To try it out, you can download the macOS test version here: https://github.com/musescore/MuseScore/actions/runs/3758295289 (bottom of the page)

I already did this for you, and it turns out only measure 62 is problematic. So you can safely copy the other measures to a new file to continue composing.

The big question remains: how has this corruption happened? Did you any actions like inserting measures, changing the time signature after writing notes, or anything that may move notes to different measures etc.?

**Comment by akberg** [comment] 2023-01-11 21:48
Same issue here with a different score. The problem was resolved though: by cutting and re-pasting the part I suspected to corrupt the file.

OS: Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

**Comment by cbjeukendrup** [comment] 2023-01-16 18:52
Since this only happens in corrupted files, and the cause of the corruption should be fixed in 4.0.1, I'm thinking we can close this. However, if anyone sees a _new_ corruption in 4.0.1 or newer, or a crash when deleting measures in _non-corrupted_ scores, please let us know.

**Closed by cbjeukendrup** 2023-01-16 18:52 UTC
Labels: P0

**Comment by DmitryArefiev** [comment] 2023-03-02 14:46
> Since this only happens in corrupted files, and the cause of the corruption should be fixed in 4.0.1, I'm thinking we can close this. However, if anyone sees a _new_ corruption in 4.0.1 or newer, or a crash when deleting measures in _non-corrupted_ scores, please let us know.

@cbjeukendrup This was closed as won't fix, correct?

**Comment by cbjeukendrup** [comment] 2023-03-02 15:14
Yes, that's right. The cause of the crash was a corrupted score, and the cause of the corruption had been fixed in 4.0.1, so it won't happen with other scores.
