### ISSUE TITLE
QWERTZ Keyboard Shortcut 'Whole Note' Broken (German - Standard input source, Mac)

### ISSUE THREAD

**Issue by RDARKNI** [musescore/MuseScore#19033] opened 2023-08-12 00:33 UTC
### Issue type

Other type of issue

### Steps to reproduce

* Set Musescore to English (GB) and set keyboard to "**German - Standard**" on macos
* Restart Musescore
* Go to Preferences > Shortcuts "Set duration: semibreve (whole note)"
* Click "Reset to Default"
* Try to change input note duration to whole note by pressing 7. It doesn't work (at least on my device) for as long as I don't either change the language to German or the keyboard to another language

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS

**Comment by RDARKNI** [comment] 2023-08-12 18:57
Two more things I noticed: 
The issue seems to appear and disappear based on my musescore language settings; when switching the language to German the issue generally disappears (but the behaviour is rather unpredictable). It also works when I set QWERTY as my keyboard

Also, the shortcut 0 to enter a rest does not work with a QWERTZ layout and English language - When I change it to the key 'h' it works in either language.

**Comment by DmitryArefiev** [comment] 2023-08-14 10:32
@RDARKNI Please add a steps to reproduce.

It works for me when I switched to German keyboard layout

**Comment by Jojo-Schmitz** [comment] 2023-08-15 13:43
Doesn't reproduce on Windows 11 either

**Comment by bkunda** [comment] 2023-08-17 13:42
Closing this now as it doesn't seem reproducible. 
@RDARKNI more than happy to re-open if we can find a reliable way to reproduce it.

**Comment by RDARKNI** [comment] 2023-08-18 20:21
The following steps reliably reproduce it on my device: 
- Set Musescore to English (GB) and set keyboard to "German - Standard" on macos 
- Restart Musescore 
- Go to Preferences > Shortcuts "Set duration: semibreve (whole note)" 
- Click "Reset to Default"
- Try to change input note duration to whole note by pressing 7. It doesn't work (at least on my device) for as long as I don't either change the language to German or the keyboard to another language

**Comment by DmitryArefiev** [comment] 2023-08-25 12:25
> The following steps reliably reproduce it on my device:
> 
>     * Set Musescore to English (GB) and set keyboard to "German - Standard" on macos
> 
>     * Restart Musescore
> 
>     * Go to Preferences > Shortcuts "Set duration: semibreve (whole note)"
> 
>     * Click "Reset to Default"
> 
>     * Try to change input note duration to whole note by pressing 7. It doesn't work (at least on my device) for as long as I don't either change the language to German or the keyboard to another language

@RDARKNI Now I **can reproduce** it with these steps. Please add it to the description

**Comment by DmitryArefiev** [comment] 2023-08-25 12:25
The issue **occurs in MS4.0.0** as well, but **doesn't occur in MS3.6.2**

**Comment by DmitryArefiev** [comment] 2023-09-12 08:55
Fixed in #19352

**Closed** 2023-09-12 10:30 UTC
Labels: P2

**Comment by DmitryArefiev** [comment] 2023-09-12 10:58
@RDARKNI Can you check it please? Is everything fine now on your side? Thanks!

You can take this build https://github.com/musescore/MuseScore/actions/runs/6157486585 or next master
