### ISSUE TITLE
Musescore 4 doesn't save my custom palettes

### ISSUE THREAD

**Issue by albrinmelodi** [musescore/MuseScore#21422] opened 2024-02-09 11:14 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When I add custom palettes that I have saved on a folder, they work perfectly but when you close the app they vanish, even if you save your work

### Steps to reproduce

1 you add your custom palette
2 you close the program and open it
3 the palettes are not there and you have to add them again each time

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Mac OS latest

**Comment by MarcSabatella** [comment] 2024-02-09 13:19
This does work in general.  Make sure you don't have multiple windows open when making your customizations, as the different windows might have different palette configurations that clobber each other.  Also make sure MuseScore isn't crashing on exit - that would prevent the customizations from being saved.  If that's happening, you can work around this by changing workspaces to force the save before exit.

**Comment by Fastball2880** [comment] 2024-02-09 15:57
It might be off topic. On previous builds, I was thinking that it was on design where you save your pallete to a certain score and not save it as a global settings.

**Comment by MarcSabatella** [comment] 2024-02-09 16:00
No, MuseScore has never had a feature where palettes were saved into specific scores.  They have always been saved only as part of a workspace or explicitly via the “Save palette” command.

The fact that palette customizations are not synchronized between open windows like preference settings are is indeed unfortunate, but anyhow, currently that’s the main thing you need to look out for.

**Comment by DmitryArefiev** [comment] 2024-06-06 09:38
@albrinmelodi I **can't reproduce** it on latest master (**4.4**) on Mac13.6

Please reopen if it still occurs. And if yes, then also check details in Marc's comment (https://github.com/musescore/MuseScore/issues/21422#issuecomment-1935916223)

**Comment by albrinmelodi** [comment] 2024-06-30 20:42
The problem is still there, and it's not working on any of the latest versions.

**Comment by MarcSabatella** [comment] 2024-06-30 20:45
Did you see my previous comment https://github.com/musescore/MuseScore/issues/21422#issuecomment-1935916223?  Most likely one of those two things is what is going on.  If you need further assistance, please ask for help in the official Support forum at musescore.org.  And then if it turns out you are seeing a problem *not* explained by that comment, and you can find steps to reproduce the problem reliably, then you can come back here and add those steps and the issue can then be reopened.

**Comment by albrinmelodi** [comment] 2024-06-30 20:52
Yes, i followed every step, tried all different configurations, when you have a custom palette, you can save it as a file, and then loading it again. In musescore 4, I add palettes created on musescore 3, and some of them are saved and some not, thanks

**Comment by MarcSabatella** [comment] 2024-06-30 21:16
If you followed the step where you checked to be MuseScore Studio is not crashing on exist and verified it is not, then please post a link here to post you made on the Support forum so we can continue trying to assist you there.

**Comment by DmitryArefiev** [comment] 2024-07-01 13:59
> The problem is still there, and it's not working on any of the latest versions.

@albrinmelodi OK. I'll reopen the bug (but I still can't repro it)

Please attach the video (you can use QuickTime and upload it to GoogleDrive/Dropbox/YouTube etc. it the file is more than 10Mb
)

**Comment by zacjansheski** [comment] 2024-08-21 19:54
Closing, does not reproduce

**Closed by zacjansheski** 2024-08-21 19:54 UTC
Labels: P2, UI, regression MS3, waiting reply from user
