### ISSUE TITLE
Fermata Note being held after assigned duration

### ISSUE THREAD

**Issue by Ahh6483** [musescore/MuseScore#18923] opened 2023-08-04 17:45 UTC
### Issue type

General playback bug

### Bug description

A whole note with a fermata is being help past the barline, almost 2 full measures added on. 

### Steps to reproduce

1. Add whole note in one part (in my case voice) make sure the next measure has no notes in it. 
2. In the second part (in my case piano), add a half note, then 4 eighth notes leading to the next measure. 
3. Add fermatas to beat 1.
4. Playback (Hear error) 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/79336035/8dfafb1a-1835-41cd-a6eb-067d9880e469

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 13.3

**Comment by zacjansheski** [comment] 2023-08-04 18:33
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/15102

**Comment by zacjansheski** [comment] 2023-08-04 18:45
I believe this issue is present in all versions of MuseScore 4.  Is there a version that this worked in? (labeled as 4x regression)

**Closed** 2023-08-04 20:18 UTC
Labels: needs info, regression, playback
