### ISSUE TITLE
Cello limited pitch range

### ISSUE THREAD

**Issue by cello273** [musescore/MuseScore#16959] opened 2023-03-21 16:24 UTC
### Your idea

When I use MuseSounds and MuseFX, the cello has a limited pitch range. The cello section can play F#5 and the solo cello can play G5, but they cannot play higher notes. The notes are written on the score but MuseScore does not play it. The cello can play higher notes like E6 or even A6. With using the harmonics, I think that we can play more higher notes.
Other cellists, what do you think about this ? Which is the extreme higher note of the cello ?

### Problem to be solved

Is there any solution to hear these extreme notes with MuseScore 4, MuseSounds and MuseFX ?
Is it possible to change this limited pitch range in a future version of MuseScore ?

### Additional context

Sorry for the mistakes, English is not my first language.

**Comment by lgmventura** [comment] 2023-03-31 17:59
Not only cello / cellos, but many instruments: double basses, B-flat clarinet, timpani, tuba and so on. They are not even playing high notes withing the basic range. I think they should reach the expert range and go a little beyond or even the full expert range if possible.

**Comment by Fristover** [comment] 2023-08-21 06:35
Another one related to (or duplicate of): #16244 (I hope whoever is in charge of that issue can add these details and corrections into the main thing 😅 )

**Comment by cbjeukendrup** [comment] 2023-08-29 14:40
Combined into #16244

**Closed by cbjeukendrup** 2023-08-29 14:40 UTC
Labels: feature request, muse sounds
