### ISSUE TITLE
Offset 3rd Voice

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#24631] opened 2024-09-11 04:12 UTC
### Your idea

The 3rd Voice should be offset slightly to distinguish it from the first. There appear to be no options to do this in the "Style" settings; only a workaround in properties that must be applied to every note. The first screenshot below shows the problem, the second shows the original music from IMSLP with the 3rd voice offset in measure 5.
![image](https://github.com/user-attachments/assets/35bb042a-722a-42f0-8599-7d48f7315287)
![image](https://github.com/user-attachments/assets/a5e255c2-5adb-4583-b4c2-0c458c36d4df)

### Problem to be solved

Unprofessional Notation

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Dima-S-Jr** [comment] 2024-09-11 07:36
Duplicate of #23222

**Closed** 2024-09-11 07:45 UTC
Labels: duplicate, feature request
