### ISSUE TITLE
Loop playback does not work correctly if repeat used

### ISSUE THREAD

**Issue by pbcromer** [musescore/MuseScore#22849] opened 2024-05-15 21:05 UTC
### Issue type

General playback bug

### Bug description

The "Loop playback" feature for playing scores using MIDI does not work correctly if a repeat sign is present. You can set the loop playback for a measure with a repeat sign and it works the first time. If you try to set the "loop playback" for a different measure outside the measures with the repeat it will set the visual flags, but then playback the previous set of measures (not the new ones selected and indicated by the flags. This can be shown by a small score with 2 measures shown in the screenshot provided.

### Steps to reproduce

1. Create a new score with 2 measures and 1 instrument (use Piano for example).
2. Put any notes in the 1st measure (like 4 A quarter notes in treble/bass for piano).
3. Put any notes in the 2nd measure (like 4 B quarter notes).
Select the 1st measure and click the "Loop playback" button, then play. It should loop correctly over the measure.
Select the 2nd measure and click the "Loop playback" button, then play. It should loop correctly over the 2nd measure.
4. Add a repeat to the 1st measure.
5. Select the 1st measure and click "Loop playback" button, then play. It should loop correctly over the 1st measure.
6. Select the 2nd measure and click "Loop playback" button, then play. It should NOT loop over the 2nd measure, and instead loops over the 1st measure. The flags will indicate the 2nd measure is to be looped, but that is not what is played.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/3230703/af7b3f24-f95f-4bf3-aff2-ce432fbc4cd6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

I don't know

### Operating system

Windows 11

**Comment by RomanPudashkin** [comment] 2024-05-16 06:55
Duplicate of https://github.com/musescore/MuseScore/issues/16875 (and it has been fixed for 4.4)

**Closed by RomanPudashkin** 2024-05-16 06:55 UTC
Labels: duplicate, playback
