### ISSUE TITLE
[MU4 Issue] Extra notes in playback

### ISSUE THREAD

**Issue by Grillzombie** [musescore/MuseScore#10997] opened 2022-03-30 20:43 UTC
I opened a score of mine (from 3.6.2) and played it back, and at certain places there are notes played, which aren't in the score. 
Measures 5, 12, 18, 19, 21.

**To Reproduce**
1. Open attached score
2. Click on playback

**Expected behavior**
No extra notes, which are not in the score should be played.

**Platform information**
 - OS: Linux Mint 20.3 First Alpha-release MS4

[Danse_a_deux.mscz_FILES.zip](https://github.com/musescore/MuseScore/files/8383904/Danse_a_deux.mscz_FILES.zip)

**Comment by DmitryArefiev** [comment] 2022-04-04 16:40
Can reproduce on Windows 10 as well. Thanks for logging!

(Doesn't occur in MU3)

**Comment by DmitryArefiev** [comment] 2022-04-05 18:32
https://user-images.githubusercontent.com/90187801/161825195-3d4d71d0-96f6-431c-abbf-86d2f4a8120b.mp4

(extra notes issue somehow relates to notes in the right hand)

**Comment by Tantacrul** [comment] 2022-06-12 17:46
I've listed to it (MacOS) and heard the same thing.

Well done @DmitryArefiev for figuring out what is causing it. For grand staves, one definitely affects the other sometimes. If I just remove the staccato, it no longer happens.

**Comment by DmitryArefiev** [comment] 2022-07-13 10:51
Tested in **latest master** on Win10, Mac12, LinuxMint 20.2 - **I can't reproduce it anymore. FIXED** 

Closing

@Grillzombie Please reopen if the issue still exists

**Closed by DmitryArefiev** 2022-07-13 10:51 UTC
Labels: P1, needs testing

**Comment by Grillzombie** [comment] 2022-07-13 18:58
All ok now, Thanks!

**Comment by DmitryArefiev** [comment] 2022-07-13 20:31
Thanks!
