### ISSUE TITLE
[MU4 Issue] Musesounds plays a crescendo between dynamics

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#14548] opened 2022-11-16 12:32 UTC
**Describe the bug**
When there are more than one dynamic in a score, Musesounds plays a crescendo right before where the new dynamic is despite the absence of a hairpin or a similar marking.

**To Reproduce**
1. Open a new score preferably with instruments that can play a continuous note like a violin, flute, etc. using Musesounds.
2. Add a few notes.
3. Place varying dynamics on the notes.
4. Upon playback, you can observe that right before the playback reaches to the part with the new dynamic, it crescendos to the new dynamic.

**Expected behavior**
A crescendo or a diminuendo is not to be played between dynamics unless marked accordingly with a hairpin or staff text.

**Screenshots**
Provided is a Gdrive link to an OBS recording of the issue: 
https://drive.google.com/file/d/18sWFsms6wcI3OTeAOh6n-3vHfmdfS8hh/view?usp=sharing
This is an OBS recording of the same score but with MS basic::
https://drive.google.com/file/d/1Z1IeH93-CXTWEJfimME4GIKQRmXmH0hO/view?usp=sharing

**Platform information**
 - OS: Windows 10, MU4 nightly 

**Additional context**
Though I have not documented it going from a loud dynamic to a soft dynamic, the issue happens to it as well. However, as observed in the recording above, the issue is not apparent when there are rests in between.

**Comment by cbjeukendrup** [comment] 2022-11-16 13:23
This is a duplicate of #13902. Thanks for the good report though! It will be linked in the original issue.

**Closed by cbjeukendrup** 2022-11-16 13:23 UTC
