### ISSUE TITLE
[MU4 Issue] Audio desynchronization when changing from MuseSounds to MS Basic

### ISSUE THREAD

**Issue by Tonwhirler** [musescore/MuseScore#15244] opened 2022-12-16 21:59 UTC
**Describe the bug**
The playback doesn't synchronize if the sound font is changed from MuseSounds to MS Basic in the middle of playing a piece.

**To Reproduce**
1. Play music using MuseSounds
2. Switch to MS Basic for a part in the mixer during playback
3. Audio stutters for a moment
4. Audio is now desynchronized for the part/parts which changed font, even when pausing and resuming

Also works:
1. Play music using MuseSounds
2. Pause at any point during playback
3. Change to MS Basic 
4. Resume music
5. Audio playback is delayed for a moment
6. Audio is now desynchronized 

**Platform information**
 - OS: Windows

**Additional context**
Switching back to MuseSounds doesn't fix the desynchronization. I tested switching from Grand Piano and Choir Soprano to MS Basic. Appears to be fixed if audio is played from a specific point rather than resuming.

**Comment by cbjeukendrup** [comment] 2022-12-18 03:12
Maybe the same as https://github.com/musescore/MuseScore/issues/14902

**Comment by cbjeukendrup** [comment] 2022-12-18 03:16
Actually this is also another duplicate of #15047. Thanks for reporting though!

**Closed by cbjeukendrup** 2022-12-18 03:16 UTC
