### ISSUE TITLE
Saving uncompressed isn't working

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#22749] opened 2024-05-10 07:14 UTC
### Issue type

Opening/saving issue

### Bug description

Saving pieces as "Uncompressed MuseScore folder" isn't working.

### Steps to reproduce

1. Open a score
2. Try to save as uncompressed

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.4

**Comment by mathesoncalum** [comment] 2024-05-13 10:27
Struggling to repro this one @rettinghaus - am I missing any repro steps? (see video)

https://github.com/musescore/MuseScore/assets/47119327/73359514-f111-4448-bcbb-261a05bfacdb

**Comment by rettinghaus** [comment] 2024-05-13 11:15
No, but it still doesn't work for me. Weird. I tried (again) different pieces and all result in a `.mscz` file.

**Comment by mathesoncalum** [comment] 2024-05-13 11:24
Strange - @zacjansheski can you investigate?

**Comment by zacjansheski** [comment] 2024-05-13 12:48
I am getting the same issue on Mac OS14.4

Does not occur on Windows 11

**Comment by MarcSabatella** [comment] 2024-05-13 13:13
I think it comes down to the file name chosen.  If you explicitly have MSCZ in the file name, that is what gets written, regardless of the type setting in the dropdown.  So on systems where the file dialog automatically changes the file extension when changing the type, the right thing appears to happen by default.  But if the extension doesn’t change automatically, and you don’t change it yourself, you end up with an MSCZ file written.  At least that is what I think I am seeing on both Linux *and* Windows.

In the video above, it seems the system is set to hide the extensions, but presumably they are being changed automatically.  On my Windows system, the extension *is* shown, and it does *not* change with the dropdown.

**Comment by MarcSabatella** [comment] 2024-05-13 13:19
This seems the same on 4.2.1, BTW.

**Comment by rettinghaus** [comment] 2024-05-13 14:05
I can support @MarcSabatella's theory. If I type in a completely new name it works. So obviously it's just the hidden file extension that doesn't get updated.

**Comment by mathesoncalum** [comment] 2024-05-15 08:20
Spot on @MarcSabatella - I changed my system settings to "show all filename extensions" and can repro now.

After doing some digging I discovered this is actually a duplicate of an ancient bug #11615. It looks like some fixes are actually in the pipeline already, I'll chase these up.

Many thanks!

**Closed by mathesoncalum** 2024-05-15 08:20 UTC
Labels: P2, needs testing, regression
