### ISSUE TITLE
[MU4 Issue] Change tablature to "Stems and beams" causes crash

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12532] opened 2022-07-23 10:49 UTC
**Describe the bug**

In the attached score changing the tablature "Note values" tab from "None" to "Stems and beams" causes the program to hang then crash.

**To Reproduce**

1. Open the attached MS3 file in MS4. 
[staff_properties_crash.zip](https://github.com/musescore/MuseScore/files/9173585/staff_properties_crash.zip)

2. Right click on the tablature staff and select "Staff/Part properties"
3. Select Advanced style properties > Note values and change "Shown as" from "None" to "Stems and beams".
4. Press OK, then OK again.

RESULT: Program hangs then crashes on the Staff/Part properties dialogue.

**Expected behavior**

Dialogue closes as in MS3.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2722421418, revision: github-musescore-musescore-5e7884d

**Comment by cbjeukendrup** [comment] 2023-02-12 02:06
@rgreen5 I can't reproduce the crash using these steps in the latest master. Could you re-test it?

**Comment by rgreen5** [comment] 2023-02-12 10:35
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230430504, revision: github-musescore-musescore-a36e598

Works fine now.

**Comment by cbjeukendrup** [comment] 2023-02-12 12:14
Thanks for checking! Then I'll close it.

**Closed by cbjeukendrup** 2023-02-12 12:14 UTC
Labels: P1
