### ISSUE TITLE
Choir lyrics only respond in sound preview, not playback

### ISSUE THREAD

**Issue by TimBomBom** [musescore/MuseScore#24213] opened 2024-08-26 23:56 UTC
### Issue type

General playback bug

### Description with steps to reproduce

This is still broken on the latest nightly build and 4.4 beta. 
Expected behaviour: Lyrics change syllable during playback. 
Observed behaviour: Lyrics change syllable in preview but not playback

1. Create a score with choir
2. change sound to VOXOS Epic Choir
3. Input notes with lyrics below them
4. The sound is changed when clicking on the individual notes, but playback is always "ahh" sound

I have observed this on the beta release of 4.40: 4.4.0-242351127, revision: github-musescore-musescore-7d55814
and on the latest nightly build: 4.4.0-242390502, revision: github-musescore-musescore-ceea06a

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/970a6519-1d96-41b3-8167-4b66aa7ab4d3

### What is the latest version of MuseScore Studio where this issue is present?

Latest nightly build: 4.4.0-242390502, revision: github-musescore-musescore-ceea06a

### Regression

No.

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

The attached video was filmed on the nightly build, but the exact same behaviour was seen on the [beta](https://musescore.org/en/node/367021)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment] 2024-08-27 13:21
thanks for reporting this. 
Can you also please check this on the latest release? (which just came out today). 
It'd also be helpful to know the sampler version (go to Diagnostic > Muse Sampler > Check Muse Sampler). 
Thank you.

**Comment by LucySuccubus** [comment] 2024-08-27 13:43
Can verify this for the official release version of 4.4. Voxos sings the syllables on note input preview, but sings "Ahh" when actually hitting the play button.

**Comment by TimBomBom** [comment] 2024-08-27 16:21
> thanks for reporting this. Can you also please check this on the latest release? (which just came out today). It'd also be helpful to know the sampler version (go to Diagnostic > Muse Sampler > Check Muse Sampler). Thank you.

Updated musescore through musehub and checked again, same issue. Muse Sampler is on v0.100.1

**Comment by DominicMaas** [comment] 2024-08-27 19:24
> > thanks for reporting this. Can you also please check this on the latest release? (which just came out today). It'd also be helpful to know the sampler version (go to Diagnostic > Muse Sampler > Check Muse Sampler). Thank you.
> 
> Updated musescore through musehub and checked again, same issue. Muse Sampler is on v0.100.1.
> 
> Also idk if its relevant but I frequently get messages in the musehub saying "Muse Sampler Error when installing: copy: The file exists." Not sure if its not updating and thus causing the playback issues or if its harmless. I didn't want to open a whole ticket for it because I'm unsure.

I believe this happens when Muse Hub tries to update sampler, but MuseScore Studio is open (and locking the library). Try closing both MuseScore Studio and Muse Hub (fully, using the system tray icon). Then launch Muse Hub, wait a few minutes, then launch MuseScore Studio and it should have updated.

**Comment by LucySuccubus** [comment] 2024-08-27 20:04
Upon further investigation, it is also found to affect Muse choirs.

**Comment by TimBomBom** [comment] 2024-08-27 20:16
Managed to update muse sampler by following the above instructions to 0.100.2 and issue persists

**Comment by LucySuccubus** [comment] 2024-08-29 02:14
I would like to clarify that this also affects Musechoir.

**Comment by GyorgyL** [comment] 2024-08-29 05:41
Hello, since the update 4.4 the voxos choir(s) is still not doing its full potential

**Comment by FragmentedAudition52** [comment] 2024-08-29 08:12
Further issue: some of the syllables are mismatched in preview. They still don't work in playback, but when viewing in preview "Tis" plays "Frayst" and so on. Others are similarly mismatched. MuseScore Studio V4.4, Muse Sampler V0.100.1.

**Comment by Jojo-Schmitz** [comment] 2024-08-29 08:15
For me MuseSampler reports 0.100.2.314

**Comment by DmitryArefiev** [comment] 2024-08-29 12:04
@TimBomBom @LucySuccubus  @FragmentedAudition52 Can you try this build on your side please? https://github.com/musescore/MuseScore/actions/runs/10612811138

**Closed** 2024-08-29 12:08 UTC
Labels: P0, playback

**Comment by TimBomBom** [comment] 2024-08-29 19:17
It seems to be working for the most part now. It did crash when I tried deleting a tie once tho

**Comment by DmitryArefiev** [comment] 2024-08-30 14:27
Thanks for testing! If you will be able to reproduce the crash again (several times) please log it as a separate issue
