### ISSUE TITLE
[Muse Hub] App autoclose

### ISSUE THREAD

**Issue by juleari** [musescore/MuseScore#14420] opened 2022-11-08 12:25 UTC
**Describe the bug**
The app closes by itself before i could do anything

**To Reproduce**
1. Get MuseScore 4 from here: https://www.musehub.com/ (mac os version)
2. Move app to applications
3. Click to open it
4. It opens for a few seconds and then cancels by itself

**Expected behavior**
The app is working)

**Screenshots**
[screen recording of the last 2 steps](https://vimeo.com/768516994)

**Platform information**
 - macOS Big Sur 11.6

**Additional context**
-

**Comment by cbjeukendrup** [comment] 2022-11-12 22:43
I just realise that this is probably a duplicate of #14311. @juleari Does this crash indeed only happens when you are connected to WiFi?

**Comment by pmarx810** [comment] 2022-12-07 21:45
@cbjeukendrup @iamtesch Is there any estimate of when this will be fixed? I'm away from home and work from my laptop quite a lot, only reason I ask.

**Comment by iamtesch** [comment] 2022-12-07 22:48
We have fixed this locally, and will push out another release soon - planning on Thursday or Friday (12/8-12/9) right now.

**Comment by iamtesch** [comment] 2022-12-15 14:51
Can you confirm if this is fixed now? The latest releases should address the issue

**Comment by pmarx810** [comment] 2022-12-15 19:43
@iamtesch HOORAY! Successfully resolved on my end!

**Comment by iamtesch** [comment] 2022-12-15 23:05
Awesome! Thanks :)

**Closed by iamtesch** 2022-12-15 23:05 UTC
Labels: P0

**Comment by VSTHero** [comment] 2022-12-16 00:16
I switched to Monterey, so can't fully speak to BigSur, but the Monterey issues (lag, lack of icons, inability to select download folder etc. has resolved!)

**Comment by juleari** [comment] 2022-12-16 07:37
Still using the Big Sur and no more crashes. Thank you)
