### ISSUE TITLE
[MU4 Issue] Items under "View | Show" not synced with the properties panel

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#15553] opened 2022-12-24 04:39 UTC
**Describe the bug**
All items under "View | Show" are not synced with the properties panel toggles.

**To Reproduce**
Steps to reproduce the behavior (see video for clarification):
1. Create a new score
3. Go to `View | Show`
4. Click on any of the items
5. Go to the properties panel and see that the respective toggle has not changed
6. Click on the respective toggle and observe that the behaviour is reversed
7. Toggle the item in the `View | Show` menu
8. See that the respective toggle in the properties panel acts correctly now

**Video**

https://user-images.githubusercontent.com/73422868/209421311-b7d7e260-b1b7-481a-9ad4-e6af42ceab2f.mp4

**Expected behavior**

Items under "View | Show" should be synced with the properties panel

**Platform information**
 - Linux (Slackware 15, Xfce 4.16)

**Additional context**

- Build commit: d759f2983173fe513111d4d6ab2ce65334fd1c20

**Comment by cbjeukendrup** [comment] 2023-03-12 18:49
@iwoithe Can you still reproduce this? For me it seems fixed.

**Comment by iwoithe** [comment] 2023-03-13 12:32
> Can you still reproduce this? For me it seems fixed.

I believe this issue is fixed, but there appears to be a new problem with checking/unchecking the `View | Show` options.

https://user-images.githubusercontent.com/73422868/224702074-09607ce7-10f6-4a2f-a957-76a0917e30df.mp4

It should also be noted that all check boxes under `View` seem to work flawlessly.

@cbjeukendrup let me know if you want a separate issue opened for this

**Comment by cbjeukendrup** [comment] 2023-03-13 16:34
Strange enough I cannot reproduce that... Anyway, it would be great if you could open a new issue for that; let's close this one.

**Closed by cbjeukendrup** 2023-03-13 16:34 UTC
Labels: needs testing
