### ISSUE TITLE
Trill always exported to midi as second.

### ISSUE THREAD

**Issue by Johan-v** [musescore/MuseScore#25322] opened 2024-10-26 16:18 UTC
### Issue type

Import/export issue

### Description with steps to reproduce

Create a new score
Insert a note
Insert a trill with interval a fourth (or other then second)
Export midi
The midi trill interval will always be a second.

### Supporting files, videos and screenshots

Empty

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment] 2024-10-29 14:29
Closing as duplicate of https://github.com/musescore/MuseScore/issues/18731

**Closed by zacjansheski** 2024-10-29 14:29 UTC
Labels: MIDI
