### ISSUE TITLE
[MU4 Issue] Tuplet gets deleted after inserting note of said tuplet's duration

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#14504] opened 2022-11-13 07:34 UTC
**Describe the bug**
If a note with duration covering whole tuplet gets inserted to said tuplet, it is ignored and instead gets deleted.

**To Reproduce**
1. Insert a tuplet (_e.g. a triplet over a quarter note/crochet_)
2. Insert a note that should cover whole tuplet's duration (_in the case above, a dotted quarter note/crochet_)
3. See error (_tuplet is ignored, gets deleted, and instead the note covers duration in accordance with the score's assigned meter_)

**Expected behavior**
Note duration should recognize tuplets and should not remove it.

**Video Demostration**
Alongside a comparison with MU3:

https://user-images.githubusercontent.com/90231404/201510779-be9c7ba2-96d2-4406-9737-e78289fe78ad.mp4

**Platform information**
 - OS: Windows 10
 - Version: 4.0.0.223072007

**Comment by oktophonie** [comment] 2022-11-13 09:50
Duplicate of https://github.com/musescore/MuseScore/issues/14151
(Fortunately there's a PR already, so this will be fixed as soon as it's merged)

**Closed by oktophonie** 2022-11-13 09:50 UTC
