### ISSUE TITLE
[MU4 Issue] MuseScore outputs extremely high-pitched, fast audio, no matter the soundfont/Muse Sound.

### ISSUE THREAD

**Issue by blobbycactus** [musescore/MuseScore#14936] opened 2022-12-05 07:23 UTC
**Describe the bug**
MuseScore outputs audio that is extremely high-pitched and extremely fast, no matter the soundfont. Also happens with Muse Sounds.

**To Reproduce**
1. Open score
2. Play score using spacebar

**Expected behavior**
Audio should play with accurate pitches and accurate tempo.

**Screenshots**

**Platform information**
OS: Windows 11 Home, version 21H2
Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223362132, revision: github-musescore-musescore-d050fb0
Realtek Speakers and sound card

**Additional context**
None.

https://user-images.githubusercontent.com/119841066/205576935-6c7b91bb-b747-4860-b25d-f871c5ed62f1.mp4

**Comment by cbjeukendrup** [comment] 2022-12-05 07:30
This is a duplicate of #14921. Thanks for reporting though!

If you have any additional info, please add it as a comment to #14921.

**Closed by cbjeukendrup** 2022-12-05 07:30 UTC
