### ISSUE TITLE
Corrupt score empty after 4.1

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20174] opened 2023-11-24 16:30 UTC
### Issue type

File corruption

### Bug description

https://musescore.com/user/167003/scores/3173891
This score is empty in versions 4.1+

It is corrupt but it does open in 4.0

### Steps to reproduce

1. Download and open this score in current version of MuseScore.  Score is empty.
2. Open in 4.0.2, the score is corrupt, but not empty

### MuseScore Version

4.0.2+

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

**Comment by oktophonie** [comment] 2023-11-24 16:33
Duplicate of https://github.com/musescore/MuseScore/issues/17940

**Closed by oktophonie** 2023-11-24 16:33 UTC
Labels: regression, corruption
