### ISSUE TITLE
MuseSounds Playback stops after exactly 35 minutes and 48 seconds

### ISSUE THREAD

**Issue by caden8822** [musescore/MuseScore#18483] opened 2023-07-08 17:12 UTC
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Create a project with any instrument (with MuseSounds active) that would play for 35 minutes and 48 seconds
2. Place a note before and after 35 minutes and 48 seconds
3. Et voila!

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Microsoft Windows 11 Home

**Comment by metasekk** [comment] 2023-07-09 14:26
This is related to MuseSampler (v.0.3.2). It seems to be solved in MuseScore 4.1 with MuseSampler 0.4.0.25
See #15768

**Comment by cbjeukendrup** [comment] 2023-07-09 22:22
I'll close this as a duplicate of #15768, but thanks for reporting! As said, it is fixed in the latest version of MuseSampler; I'm not sure if this is already available via the normal version of Muse Hub or only via the beta version, but if the latter, it will be available in the normal version in a few days anyway.

**Closed by cbjeukendrup** 2023-07-09 22:22 UTC
Labels: muse sounds
