### ISSUE TITLE
Barlines that are invisible at the intersection with the text

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20835] opened 2024-01-04 23:36 UTC
### Your idea

To prevent the text from merging with the barlines, I suggest making the barlines invisible at the intersections
![Снимок экрана (96)](https://github.com/musescore/MuseScore/assets/134041121/89b25923-7579-4206-9554-fb350ebcaad8)

### Problem to be solved

This way the text will not merge with the barlines and will be more neatly decorated

**Comment by jeetee** [comment] 2024-01-04 23:39
Use the Properties panel with the text selected to give it a rectangular frame and set border and fill color of that frame to white.

**Comment by Dima12357** [comment] 2024-01-05 00:30
> Use the Properties panel with the text selected to give it a rectangular frame and set border and fill color of that frame to white.

Too many manipulations need to be done for this. It would be necessary to make sure that the barlines are **_immediately_** erased when crossing with the text

**Comment by oktophonie** [comment] 2024-01-05 08:42
A general solution will come for this (see https://github.com/musescore/MuseScore/issues/17719)

**Comment by bkunda** [comment] 2024-01-09 14:58
Closing as duplicate of #17719

**Closed by bkunda** 2024-01-09 14:58 UTC
Labels: feature request
