### ISSUE TITLE
[MU4 issue] Playback tempo issue: all metric modulations reset the playback speed to 120 bpm 

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#20199] opened 2023-11-26 10:20 UTC
### Issue type

General playback bug

### Bug description

All metric modulations reset the tempo to to 120 (quarter note) beats per minute.

# Example: eighth note = eighth note

<img width="424" alt="image" src="https://github.com/musescore/MuseScore/assets/109522890/a578aef3-350d-46f3-8228-90a11d775a4b">

Instead of maintaining the tempo, eighth=eighth resets the playback tempo to 120 bpm despite being in _follow written tempo_-mode

### Steps to reproduce

1. write some music in any tempo except 120bpm
1. under _Tempo_, find the metric modulations. place any of them (or in this case an eighth=eighth).
1. observe that the tempo is reset to 120bpm following metric modulation.

- it does not matter whether the metric modulation is in _follow written_ or overwrite mode. Even overwrites are ignored and reset to 120 bpm

Also observe that this bug occurs regardless of time signature changes.

### MuseScore Version

- OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

- also observed on OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

MacOS 13.x (also Linux Mint 20.1, probably independent of the platform)

### Additional context

Also check the issue #15655 where the problem was originally reported.

**Comment by Jojo-Schmitz** [comment] 2023-11-26 11:06
Al the other metric modulation behave the same (bogus) way

**Comment by Jojo-Schmitz** [comment] 2023-11-26 11:07
As such most probably a duplicate of #15655

**Comment by Jojo-Schmitz** [comment] 2023-11-26 11:10
And that other issuer also has a workaround

**Comment by bkunda** [comment] 2023-11-28 14:13
Closing as duplicate of #15655

**Closed by bkunda** 2023-11-28 14:13 UTC
Labels: playback
