### ISSUE TITLE
[MU4 Issue] Offbeat tied notes play on the next beat when swing is enabled

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12768] opened 2022-08-10 21:23 UTC
**Describe the bug**
When swing is enabled, a tied note that is written off the beat won't play until the next beat.

**To Reproduce**
1. Enter the following and hit Play:

![image](https://user-images.githubusercontent.com/1799936/184022714-dfca4e47-a38b-4fe0-8f3e-2fb40aa58574.png)

**Result**

The fourth note plays on beat 3

**Expected behavior**
The note should play on the "&" of 2 - appropriately delayed for swing, but not all the way to the next beat!

**Platform information**
 - OS: Linux

**Additional context**
I initially noticed this with sixteenth note swing

**Comment by Tantacrul** [comment] 2022-08-16 17:46
Confirmed. The tied note doesn't swing because it's tied (another way to think about it is that that last 8th isn't really an 8th because it's a longer duration)

**Comment by Tantacrul** [comment] 2022-08-16 17:55
Marked as P0 due to the impact on core playback.

**Comment by boryskuzmenko** [comment] 2022-08-19 10:47
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12924
Tested on macOS 12, Win 11, Ubuntu 20

**Closed** 2022-08-19 14:04 UTC
Labels: P0
