### ISSUE TITLE
Incorrect display of Nashville numbers with chord inversion

### ISSUE THREAD

**Issue by juancarlangas** [musescore/MuseScore#24490] opened 2024-09-05 22:54 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Write a note
2. Add to it a nashville number
3. Set the chord something like 1/5

### Supporting files, videos and screenshots

When you try to add a Nashville number with chord inversion (IE 1/5), it only shows the first number. The entirely inversion is still registered, but not shown

https://github.com/user-attachments/assets/905e353b-ad99-4d5d-8f35-c190c0c21f4a

### What is the latest version of MuseScore Studio where this issue is present?

OS: Ubuntu 24.04.1 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

Worked in 3.6, broken in all 4.x

### Operating system

Kubuntu 24.04 LTS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-09-06 10:11
Well, it is shown ... but not very helpfully:
![image](https://github.com/user-attachments/assets/8d534513-90e5-4d3b-b9bf-18e51fc43522)
Only seems to be an issue when Chord symbols > Appearance > Style is set to 'Jazz'.

**Comment by MarcSabatella** [comment] 2024-09-06 13:56
Oh, in that case, this is a duplicate of https://github.com/musescore/MuseScore/issues/16220

In that issue, I commented that it was never really intended that the "jazz" style would apply to Nashville numbers in the first place.  It "sort of" worked in MU3 but not really, other cases would present problems as well.

**Comment by zacjansheski** [comment] 2024-09-06 14:39
Closing per comment above

**Closed by zacjansheski** 2024-09-06 14:39 UTC
Labels: P2, duplicate, engraving, regression MS3

**Comment by juancarlangas** [comment] 2024-09-06 20:14
Its real. Thank you very much, my two recently bug issues was already reported, but in both cases i didnt find it as previous issues, so I should improve my searches. Thank you team
