### ISSUE TITLE
Update announcement popup (for new releases) has poor UX / UI

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#16774] opened 2023-03-13 15:58 UTC
### Issue type

UI bug

### Bug description

This is how the current announcement popup for 4.0.2 appears to the user:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/21022311/224755129-09962621-570c-43df-802c-834512f6e386.png">

Problems:

1. The title is weak. '**MuseScore 4.0.2 release**'. It should say '**A new version of MuseScore is available!**'
2. The scrollbar overlaps the text (see image above)
3. Headers in the description have bad formatting (showing three ###). These should use an appropriate text style
4. Text formatting is hard to read. For example the image below shows that bullet points are not indented and line spacing is too consistent, so different points are hard to distinguish from each other (this needs a design fix)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/21022311/224755799-cf072db2-aea1-47c8-83de-ba5a0981bfce.png">

### Steps to reproduce

1. You'll need to install an earlier version of MuseScore to see this announcement.

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

MacOS

**Comment by cbjeukendrup** [comment] 2023-03-13 16:13
By the way... something's not right in this sentence...
<img width="674" alt="Scherm­afbeelding 2023-03-13 om 17 07 02" src="https://user-images.githubusercontent.com/48658420/224759570-d9357cb4-c2cb-4b87-98cb-6fbbfbc7db79.png">

**Comment by bkunda** [comment] 2023-03-13 16:34
Yes it does have poor UX/UI indeed. 

I have reached out directly to @vpereverzev about this. Evidently something in the syntax from which he pulled my release notes (they were drafted in Confluence, surprise, surprise) has not played ball at all when being rendered in MuseScore. Perhaps either MuseScore is not recognising the syntax, or they should have never been copied over in this format in the first place 🤷‍♂️

All of this doesn't address the issue of the scrollbar, though, which is indeed very curious.

The title I will claim personal responsibility for 🙂

**Comment by bkunda** [comment] 2023-03-13 16:37
> By the way... something's not right in this sentence... <img alt="Scherm­afbeelding 2023-03-13 om 17 07 02" width="674" src="https://user-images.githubusercontent.com/48658420/224759570-d9357cb4-c2cb-4b87-98cb-6fbbfbc7db79.png">

oh god, somehow a whole heap of dot points seem to have been collapsed into one (thereby causing most of them to have been deleted somehow).

**Comment by shoogle** [comment] 2023-03-14 12:37
> Problems:
> 1. The title is weak. 'MuseScore 4.0.2 release'. It should say 'A new version of MuseScore is available!'
> 2. The scrollbar overlaps the text (see image above)
> 3. Headers in the description have bad formatting (showing three ###). These should use an appropriate text style
> 4. Text formatting is hard to read. For example the image below shows that bullet points are not indented and line spacing is too consistent, so different points are hard to distinguish from each other (this needs a design fix)

(3) and (4) are caused by MuseScore expecting HTML but receiving Markdown. @vpereverzev might be able to fix this on the server side (i.e. replace the release notes file with HTML) so it looks correct for users who haven't updated yet.

(1) can possibly be fixed on the server side too. If so, 'MuseScore 4.0.2' should be added to the top of the release notes so that users know which version they are getting.

(2) is probably an issue in the code.

I don't think any of this needs design. Designers should at least wait until they see what the dialog looks like with the above issues fixed in the code / on the server.

**Comment by Tantacrul** [comment] 2023-03-14 13:00
To nitpick, I don't think the title needs the version number. But the very top of the description should. That way users see everything they need to see.

**Comment by shoogle** [comment] 2023-03-14 13:38
That's what I'm saying too.

## A new version of MuseScore is available!
__Release notes__
> ### MuseScore 4.0.2
> This patch release contains...

**Comment by Tantacrul** [comment] 2023-03-14 13:59
Works for me!

**Closed** 2023-06-29 08:53 UTC
Labels: P2, UI, needs design
