### ISSUE TITLE
[MU4 Issue] Window doesn't fit the screen completely when 150%

### ISSUE THREAD

**Issue by aaronsendra** [musescore/MuseScore#15201] opened 2022-12-15 16:15 UTC
**Describe the bug**

The MuseScore window does not fit the screen completely when the screen scale configuration is at 150% in Windows 11. It looks like there is a small space between the screen limits and the MuseScore window border. In other cases, like scale at 125% it does not happen.

**Screenshots**

![2022-12-15-17-17-10](https://user-images.githubusercontent.com/46270385/207913018-c2a7f4d6-879f-44ee-96ca-745eb3127361.gif)

**Platform information**

 - OS: Windows 11 22H2 22621.963
 - Screen scale: 150%

**Comment by cbjeukendrup** [comment] 2022-12-15 18:09
This looks like a duplicate of #12786, isn't it?

**Comment by DmitryArefiev** [comment] 2022-12-16 17:05
Fixed in #15151

**Closed** 2022-12-16 17:11 UTC

**Comment by DmitryArefiev** [comment] 2023-03-10 14:34
Retested on Win10 with 4.0.2 RC build - **Doesn't occur**
