### ISSUE TITLE
Global sound switching to sounds from a specific playback expansion

### ISSUE THREAD

**Issue by SiposAttila1995** [musescore/MuseScore#23882] opened 2024-08-03 15:09 UTC
### Your idea

If I use a symphony orchestra template score, and I would like to change every intstrument's sound to a specific playback expansion's sound in the mixer (now that we can have Spitfire Audio, Orchestral Tools, CineSamples playback expansions), I have to do it manually.

It would a be nice if we could switch the sound of **every instruments** to sounds from a specfic library, e.g. CineSamples in a faster way. Because right now - as far as I know - I have to switch the sound track by track in the mixer.

Also would be cool an option to switch back globally to MuseSounds.

### Problem to be solved

It is very time consuming to change the sound of every track on the mixer, instruments by instruments, when I want to change all of the tracks to sounds from a specfic orchestral playback expansion (like Spitfire Audio, Orchestral Tools, CineSamples). 

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Omoriscool** [comment] 2024-08-18 23:48
Cool idea, especially because you can already do this on MuseSounds. On the mixer, try clicking the 3 dots on the right ;).

**Comment by SiposAttila1995** [comment] 2024-08-19 07:07
After clicking the 3 dots, in the Playback Setup option I can see two profiles: MuseScore Basic, Muse Sounds. That's cool. It would be cool extra profiles like Cinesamples, Orchestral Tools, Spitifre Audio.

**Comment by bkunda** [comment] 2024-08-19 13:43
This is definitely a priority for us. Design work has commenced and we'll be hoping to build it in one of the forthcoming releases.
Closing as it's a duplicate of #23719.

**Closed by bkunda** 2024-08-19 13:43 UTC
Labels: feature request
