### ISSUE TITLE
(M4) (MS Basic) Playback is too quiet in comparison to editing volume

### ISSUE THREAD

**Issue by bubblyfluff** [musescore/MuseScore#20122] opened 2023-11-21 05:58 UTC
### Issue type

General playback bug

### Bug description

I just installed MuseScore 4.1.1 (without Muse Hub) and tested it out by creating a new score. But I noticed that, whenever I clicked on or placed a note, it would sound much louder than it would during actual score playback. This makes it difficult to switch between playing the score and editing without constantly changing the volume. I'm using the default MS Basic soundfont.

Without adding any articulation or dynamic markings, playback is always much quieter and harder to hear (even when several notes are being played simultaneously) than individual note editing noises, which are super loud by comparison.

Changing instruments does not seem to affect this... I tried many different ones (all belonging to the MS Basic soundfont) but they all have this annoying audio imbalance.

### Steps to reproduce

1. Create a new score using any MS Basic instrument.
2. Add any note or combination of notes.
3. Play the score. The volume will be much quieter in comparison to the volume produced when clicking on or placing notes.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

EDIT: This may only be an issue with the default soundfont, MS Basic. I haven't downloaded Muse Hub/Muse Sounds so I'm not sure. Also, to my knowledge, MS Basic is the same soundfont used in MS 3. But I never had this issue when using MS Basic in MS 3.

**Comment by FloraCanou** [comment] 2023-11-21 07:03
Duplicate of #15375. 
See also #16698.

**Closed** 2023-11-21 07:04 UTC
Labels: duplicate, playback, regression_ms3
