### ISSUE TITLE
Display of clef/key sig./time sig. in "continuous view ->" interferes with display of score during playback

### ISSUE THREAD

**Issue by sdwarwick** [musescore/MuseScore#22300] opened 2024-04-09 22:25 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

clef/key sig./time sig. is displayed at half-contrast in this view mode. When start time is set on playback control and play is initiated, score changes position so you can see where playback is going to start, however the actual display doesn't actually show the start position, as it is covered up by the clef/key sig./time sig. As the piece starts to play, eventually the timer comes into view.

Need to have clef/key sig./time sig. display impact on start position of score considered in "continuous view ->" mode. Further, position of score should change when start time is set, not just when playback begins. 

### Steps to reproduce

1. open score
2. set to continuous view "->" display mode
3. open window with play controls
4. move play pointer to a place in the score
5. hit the "play" button
6. see that marker that shows current play location doesn't show up immediately, and the part of the score being played is not displayed 

### MuseScore Version

4.2.1

### Regression

Choose option...

### Operating system

windows 10

**Comment by DaddyLudwig** [comment] 2024-04-09 22:32
Seems to be a duplicate of https://github.com/musescore/MuseScore/issues/16173

**Comment by cbjeukendrup** [comment] 2024-04-09 23:51
What a coincidence, two duplicates of that issue in two days!

**Closed by cbjeukendrup** 2024-04-09 23:51 UTC
Labels: UX/interaction
