### ISSUE TITLE
Name of "Home" tab truncated when using Roboto

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#25502] opened 2024-11-13 15:26 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

This happens on my Linux systems (Debian 12 running within a container on Chromebook), both with xcb and wayland.  Any time I am *not* on the Home tab, the name of the Home tab is truncated to "Ho..."

Font is set in Edit / Preferences / Appearance to Roboto 12 pt, which as far as I know is the default for my system.  Changing to another font - even another variant of Roboto like Roboto Medium - works.

Issue started in 4.4, still exists in current master.

### Supporting files, videos and screenshots

![Screenshot 2024-11-13 7 06 01 AM](https://github.com/user-attachments/assets/8423f3e4-16f2-4314-a8c9-c276efb8c1a3)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-243181355, revision: github-musescore-musescore-f2e7f14

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 12

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-11-18 15:36
Reproduced on macOS, by manually selecting the Roboto font; not fixed by Qt 6.8. 
The problem seems to be that we assume that the bold version of a font is always wider than the non-bold version, which seems to be not the case with Roboto. Look at this, in Microsoft Word:
<img width="492" alt="Scherm­afbeelding 2024-11-18 om 16 35 15" src="https://github.com/user-attachments/assets/b8a105ef-891f-42d4-8189-6bc252e500c8">
Fortunately, the fix is probably trivial.

**Comment by MarcSabatella** [comment] 2024-11-18 16:07
Wow, that is crazy - who designs a font like that?  Anyhow, thanks for the investigation & fix!  Meanwhile, I see that Google has since changed from Roboto to Google Sans as their default font for Chromebooks in general, but apparently this hasn't happened for the Linux container - or maybe only for new installations.  But I've gone ahead and switched to Google Sans in MuseScore for now.

**Closed** 2024-11-19 22:29 UTC
Labels: P2, UI, regression MS4
