### ISSUE TITLE
[MU4 Issue] Regression: Impossible to change playback instrument in mixer

### ISSUE THREAD

**Issue by ntninja** [musescore/MuseScore#15657] opened 2022-12-30 23:17 UTC
**Describe the bug**
When choosing an instrument for a score line, MuseScore chooses an OK-sounding default MIDI instrument for playing back notes. For instance, when selecting the mezzosopran and baritone choral “instruments” one gets the default cis female and male *Ohhh…* singing voices respectively.

Unfortunately there is no way anymore to change the MIDI playback instrument anymore as of MuseScore 4.0.0, but this used to exist in MuseScore 3.

**To Reproduce**
1. Create a new music sheet with any MuseScore instrument
2. Open the mixer panel by enabling: Menu → *View* → *Mixer*
3. Observe the lack of option to change the MIDI playback instrument for each MuseScore score line.

**Expected behavior**
The option should exist again like in MuseScore 3 and Rosegarden. (When importing a MusicXML from Rosegarden with custom playback instrument selection, the selection from Rosegarden is retained so its purely a frontend issue.)

**Screenshots**
![Screenshot_20221231_000354](https://user-images.githubusercontent.com/246386/210116982-8d36bca7-96a1-4071-b019-b1af40c82f47.png)

**Platform information**
 - OS: Linux (but really any)

**Additional context**
Also previously reported on MuseScore forms by someone else: https://musescore.org/en/node/340004

**Comment by fredg999** [comment] 2022-12-30 23:37
This is a known issue: https://musescore.org/en/node/334701#Selecting_sounds_within_SoundFonts

Duplicate of #15190.

**Comment by cbjeukendrup** [comment] 2022-12-30 23:52
Closing as a duplicate. Thanks for reporting!

**Closed by cbjeukendrup** 2022-12-30 23:52 UTC
