### ISSUE TITLE
[MU4 Issue] Set footer value, very very slow when score is medium/big

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14346] opened 2022-11-05 17:06 UTC
**Describe the bug**
Set footer value, very very slow when score is medium/big.
Same issue is Musescore 3.6

**To Reproduce**
1. Open a big score
2. Change footer value

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223090408, revision: github-musescore-musescore-2c34155

**Additional context**
Listen to the sound of the keyboard on the video and see the text appear long after

https://user-images.githubusercontent.com/1835871/200132280-940dff3b-6bab-4698-acc9-f93c06b6e0b0.mp4

**Comment by oktophonie** [comment] 2022-11-07 18:31
The problem here is that the entire score is being reformatted after each keystroke. As such, I'll close this as a duplicate of https://github.com/musescore/MuseScore/issues/13276 (but thanks for this, as another useful example!)

**Closed by oktophonie** 2022-11-07 18:31 UTC
