### ISSUE TITLE
clarinet playback has static

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#18539] opened 2023-07-11 20:11 UTC
### Issue type

Muse Sounds bug

### Bug description

There is a static windy sound that covers the pitch at some notes on this instrument.

### Steps to reproduce

1. put the note middle D at mp dynamic (maybe slurred to something)
2. playback to hear if it is covered by noise

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/120861729/88b3af96-4812-4852-8778-c6846cb447ff

### MuseScore Version

4.02

### Regression

I don't know

### Operating system

windows

**Comment by zacjansheski** [comment] 2023-07-14 14:12
Duplicate of https://github.com/musescore/MuseScore/issues/14503

**Closed by zacjansheski** 2023-07-14 14:12 UTC
Labels: needs info, muse sounds
