### ISSUE TITLE
[MU4 Issue] Selection stretches over the page on certain bars

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#13470] opened 2022-09-23 19:44 UTC
**Describe the bug**
Selection stretches over the page on certain bars

**To Reproduce**
1. Insert horizontal frame to separate bars
2. Decrease bar stretch
3. After a certain amount of stretch the selection shoots up in the page only if stems point up. With down stems selection behaves normally

**Expected behavior**
Selection encompasses only the bar instead of stretching all the way up

**Screenshots**
I would love to attach the MU4 file but Github doesn't like it. The issue happens in bar 5 when reducing the stretch

**Platform information**
 - OS: Linux (Fedora 36)

**Additional context**
When selecting the whole passage, everything works well.

It is impressive that an alfa version of the program is already capable of achieving complex layout without crashing. Also, it is super easy to work with MU4, keep up the great work!!
![Screenshot from 2022-09-23 11-35-41](https://user-images.githubusercontent.com/55401477/192045315-0f87690f-63cf-4d08-91b5-bab47145658e.png)
![Screenshot from 2022-09-23 11-37-15](https://user-images.githubusercontent.com/55401477/192045322-2871c85c-47c7-4d15-a40a-a0b7274971d2.png)

**Comment by sberla365** [comment] 2022-09-24 06:37
[Edit] 

It seems that the glitch is dependant on the octave. In another test I have the selection all the way up in the upper octave and all the way down in the lower octave. See screenshots. When in the upper octave, with stems pointing down the selection behaves correctly


![Screenshot from 2022-09-24 08-30-30](https://user-images.githubusercontent.com/55401477/192083644-e12eee1a-e28f-40ed-8980-12ba21bf837b.png)
![Screenshot from 2022-09-24 08-30-58](https://user-images.githubusercontent.com/55401477/192083646-09f6900c-7fbf-4af7-958c-909a58080228.png)
![Screenshot from 2022-09-24 08-36-24](https://user-images.githubusercontent.com/55401477/192083737-126e0f58-7ef7-4e98-8b6d-a2d2b6a83cd8.png)

**Comment by HemantAntony** [comment] 2022-09-24 07:12
Seems to be a duplicate of #10342

**Comment by cbjeukendrup** [comment] 2023-03-04 19:24
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/10342. Thanks for reporting! (And @HemantAntony thanks for spotting!)

**Closed by cbjeukendrup** 2023-03-04 19:24 UTC
