### ISSUE TITLE
[MU4 Issue] Incorrect playback for grace notes on the end of a trill

### ISSUE THREAD

**Issue by Laurelin** [musescore/MuseScore#15120] opened 2022-12-12 07:23 UTC
**Describe the bug**
grace notes added to the end of a trill are played as quarter notes and trilled themselves

**To Reproduce**
Write a whole note
add a full measure line trill
add two grace notes to the end of the note
play it back

**Expected behavior**
Whole note should trill, end right before the and of 4 where two sixteenth notes then play without a trill
specifically, the grace notes should play as notated at the end of the note they are attached to, without a trill.

I'd also expect the trill line to end before the grace notes

**Screenshots**
<img width="222" alt="2022-12-12" src="https://user-images.githubusercontent.com/4733367/206984530-1917bda0-43ba-4a04-822f-8537aca9ed2c.png">

**Platform information**
Windows 11

Musescore nightly 2022-12-11 05:26 | 89M

**Comment by MarcSabatella** [comment] 2022-12-12 13:00
Thanks for the report!  I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/15087

**Comment by Laurelin** [comment] 2022-12-12 21:15
Thanks! #15087 has a very good explanation of how long the grace notes should be played; should I add on to that one the notes about it being inappropriately trilled and the notation bug?

**Comment by LuisLiszt** [comment] 2022-12-13 13:23
@Laurelin your issue here is a mixture of both issues mentioned above by Marc and me. So I think you should close this issue. Of course you can add anything to my issues, if there is something to add. :)

**Comment by oscardssmith** [comment] 2022-12-15 02:59
I think the second part about it trying to trill the grace notes is a separate bug.

**Comment by avvvvve** [comment] 2023-06-20 19:24
Closing, dupe of #15084 (but renaming that issue to the title of this one to be more descriptive)

**Closed by avvvvve** 2023-06-20 19:24 UTC
