### ISSUE TITLE
[MU4 Issue] Hyphen and melisma shortcuts not working when entering lyrics in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12453] opened 2022-07-18 12:34 UTC
**Describe the bug**
Hyphen and melisma shortcuts don't seem to be triggering their expected commands in MacOS.

- `-` advances to next note without inserting a hyphen
- `-` pressed repeatedly creates a melisma mark instead of several hyphens
- `Shift`+`-` (or rather `_`) doesn't do anything

Latest nightly:

https://user-images.githubusercontent.com/86290556/179511182-f8eb0456-c96f-4b13-b6b3-c28b49f383bf.mov

Expected behaviour (MS3.6):

https://user-images.githubusercontent.com/86290556/179511491-bc0debf7-b3f3-4529-b15d-bdf193ed4d68.mov

**Expected behavior**

- `-` should insert a hyphen and advance to the next note
- `-` pressed repeatedly over a number of notes should insert several hyphens
- `Shift`+`-` (or rather `_`) should insert a melisma and advance to the next note

**Platform information**
 - MacOS 12.3.1 (M1)
 - Not reproducible on Windows

**Additional context**
Seems to be a regression since the first alpha release

**Comment by Asmatzaile** [comment] 2022-07-18 22:44
I can reproduce no. 2 in Windows 10. Also when I try `Shift`+`-`, it advances to the next note without doing anything. Furthermore, and related to text input shortcuts, the shortcut for elision, `Ctrl`+`Alt`+`-`, doesn't seem to work anymore (worked in 3.6).

**Comment by bkunda** [comment] 2022-07-19 08:07
Thanks for checking this @Asmatzaile! The elision shortcut is actually new to me – it doesn't seem to appear in the list of shortcuts in MS3.6, but you're right – it absolutely does work! 

@VanSHOE @shoogle @cbjeukendrup another shortcut to add to our list 🙂 

Also @Asmatzaile when you use `Shift`+`-`, does the extender line appear if you press this shortcut more than once (I.e. to create a melisma over multiple notes)?

**Comment by cbjeukendrup** [comment] 2022-07-19 08:48
The reason that the elision shortcut doesn't appear in Preferences, is that it is not implemented as a regular shortcut but in a different way (in textbase.cpp, around line 585).

**Comment by MarcSabatella** [comment] 2022-07-19 13:06
Also, the elision particular shortcut is pretty new, added only for 3.6 I think, and thus not as well documented (if at all).  But the others handled in that same code - Ctrl+Shift+B to enter a flat sign into text, various other Ctrl+Shift combinations for other accidentals and the special dynamics characters - have been around longer.

These "shortcuts" are specific to text editing are were not tied into the regular command interface because, at the time at least, it wasn't feasible implementation-wise to have commands operate on the edited text in this way.  But it is worth noting that significant parts of the text editing code were rewritten a few years ago based on issues with how it interacted (badly) with the undo stack etc.  Could well be that now it might be more reasonable to revisit this if someone wanted to, making these actual commands for which you can custom shortcuts.

Meanwhile, though, the code in textedit.cpp handles ordinary text editing, but lyrics editing is (or was anyhow) handled elsewhere, with different special casing for space, hyphen, and underscore.  I'm not sure where that code lives now, but I know the code handling elision for 3.6 was added separate for regular text and for lyrics, and I guess the second change never got merged for master.  See https://github.com/musescore/MuseScore/pull/7100

**Comment by Asmatzaile** [comment] 2022-07-19 14:38
@bkunda glad to help; regarding your question, the extender line does appear when pressing the shortcut more than once; except when it doesn't; I haven't found reproducible cases, but, sometimes, I had to press it thrice for the line to appear.

@MarcSabatella that's right. Also, the shortcut was documented [here](https://musescore.org/en/handbook/3/text-editing#special-character-shortcuts). :)

**Comment by bkunda** [comment] 2022-07-19 14:42
@Asmatzaile there was some work done on minimum extender line length, which might explain why it now sometimes requires a few taps of the command to get it to appear (see https://github.com/musescore/MuseScore/issues/10441).

**Comment by boryskuzmenko** [comment] 2022-07-28 15:37
🟢 **FIXED** in https://github.com/musescore/MuseScore/actions/runs/2745776706
Tested on macOS 12, Win 11, Ubuntu 20

**Closed** 2022-07-28 15:59 UTC
Labels: P1
