### ISSUE TITLE
Inserting symbol after undo inserts two symbols

### ISSUE THREAD

**Issue by jonarnoldmusic** [musescore/MuseScore#24462] opened 2024-09-05 01:36 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Insert a symbol from the master palette onto an empty measure range (not the full bar rest)
2. Undo (thus selecting the whole measure)
3. Insert a symbol again
4. Two of the symbol appear, one at the beginning of the measure and one at the next

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/39bb18c9-425c-4e2b-af3a-18a337d49ea9

[TwoSymbolsMSCZ.zip](https://github.com/user-attachments/files/16882666/TwoSymbolsMSCZ.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

I discovered this when making incipits since the current workflow is to enter symbols into a measure space and not syntactical beats. I originally referenced it here: https://github.com/musescore/MuseScore/issues/22711#issuecomment-2100753101

Does not occur in 3.6.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mercuree** [comment] 2024-09-05 13:41
related or duplicate of #17718

**Closed** 2024-09-06 11:41 UTC
Labels: regression MS3, UX/interaction
