### ISSUE TITLE
Incorrect message displayed when trying to open a file which is not accessible

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#18025] opened 2023-06-17 09:07 UTC
### Issue type

UI bug

### Bug description

Open a file from the Recent files option, shows an incorrect message when the file no longer exists/is not accesible.

MS checks at startup if the files in the recent list still exists or not. If they no longer exist they are removed from the list.
However if you do not close/restart MS, the file remain in the list and can be clicked.

The message presented to the user in this case is miss leading:
<img width="404" alt="image" src="https://github.com/musescore/MuseScore/assets/13550012/75639b06-4250-4609-8c5a-ab9c9608dfe8">

An easy/quick fix could be to update the message and include information related to a possible missing/inaccessible file.
Alternative options would be refresh the recent list more often or add a proper test for missing/inaccessible files with it's own message.

### Steps to reproduce

Attach an external storage device (i.e. USB drive)
Start MS4
Create a new score and saves this to the external storage device
Close the new score
Remove the external storage device
Now use the shortcut in the recent score list to re-open the file

### Screenshots/Screen recordings

<img width="404" alt="image" src="https://github.com/musescore/MuseScore/assets/13550012/b6c0cdde-fa4a-4143-ba0f-65e676d7f930">

### MuseScore Version

4.0.2 + recent master

### Regression

No.

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-06-17 09:48
Duplicate of https://github.com/musescore/MuseScore/issues/12028

**Closed by oktophonie** 2023-06-17 09:48 UTC
Labels: UI, duplicate

**Comment by henkdegroot** [comment] 2023-06-17 10:14
Apology for the duplicate, I did search but appearantly not good enough.

**Comment by oktophonie** [comment] 2023-06-17 10:15
No apology necessary, the extra context and examples are always useful!
