### ISSUE TITLE
Shortcuts , and . make a < and > instead

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#24177] opened 2024-08-23 18:34 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Have , and . set to tie and toggle dot duration respectively
2. Have < and > set to crescendo hairpin and decrescendo hairpin respectively
3. Try to use , or .
Actual behavior: Creates hairpins
Expected behavior: Creates ties or toggles dot duration

### Supporting files, videos and screenshots

<img width="597" alt="Screenshot 2024-08-23 at 1 26 14 PM" src="https://github.com/user-attachments/assets/353913d7-63a8-459c-a2cc-b89bc79de2e3">
<img width="597" alt="Screenshot 2024-08-23 at 1 26 43 PM" src="https://github.com/user-attachments/assets/51550f0d-7d49-4780-82f1-e6a1f3875898">
<img width="597" alt="Screenshot 2024-08-23 at 1 26 51 PM" src="https://github.com/user-attachments/assets/59931e16-f8e1-4924-99dc-493c3c4a7589">

https://github.com/user-attachments/assets/894125d7-c68d-4e32-93f4-740d4db42011

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.0-242351128, revision: github-musescore-musescore-7d55814

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14, macOS 15 Beta

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-10-09 17:16
It looks like this was already partially fixed in the 4.4.3 nightly builds: now the , and . keys do what they should do. 

The fact that < and > don't work, is caused by the more fundamental problem that the "Edit shortcut" dialog records shortcuts in a character-based way (it sees "<" and ">") while the shortcut invocation controller sees key combinations, i.e. `Shift+,` and `Shift+.`. I'll see if there is a "safe" solution for this that doesn't risk breaking a lot of things.

**Comment by cbjeukendrup** [comment] 2024-10-09 21:28
After more investigation, I think it isn't really fixed, but the reproducibility rather depends on the order in which shortcuts are stored or set.

The explanation from my previous comment is a not quite precise enough. I did more investigation now. Here's a breakdown of how the shortcuts system on macOS works exactly, at the moment:
- On macOS, shortcuts are loaded as follows:
    - Each shortcut in the shortcuts file is expected to consist only of physical basic keys, so to say. Example: `,` is allowed; `Shift+,` too; `<` not.
    - For each such shortcut, we ask some ancient macOS API: "which character would be typed when the user would press this combination of keys on their keyboard?"
    - The answer is recorded in a map, which maps from "character that would be typed" to "physical combination of keys to press"
- When a shortcut is invoked on macOS
    - Qt presents the shortcut event as "character that would be typed". We use the constructed map to determine which "physical combination of keys" would need to be pressed
    - The action that is bound to that "physical combination of keys" gets performed.


And here's what happens in this issue:
- Setting the `,` and `.` shortcuts, and any other character that doesn't involve Shift, works perfectly fine: in these cases, the "character that would be typed" is the same as the "physical combination of keys". So the character-to-keycombination mapping will map `,` to `,`. 
- But then the user enters `<` and `>` as shortcuts. In the shortcuts file, these get stored as `<` and `>`. 
- This is bad, because these are not a "physical combination of keys". These are "characters that would be typed".
- The result of asking macOS which character would be typed is unexpected: it returns `,` and `.`
- So, our mapping will map `,` to `<` and `.` to `>`

Note that `,` is now mapped to `,` but also to `<`. Which of them "wins" seems to vary. 
And `<` is not mapped to anything.

So when you now press `,`, then either a tie will be created correctly, or a hairpin will be created wrongly. 
And when you press `<`, we look in our mapping what `<` should map to, but we find nothing, so no action is performed.

---

There are various ways to solve this situation:
- just always work with "character that would be typed"
    - and adjust the default shortcuts file accordingly
    - but I believe that this would cause problems for users who frequently switch between keyboard layouts: for example, when you switch to Cyrillic, then MuseScore will see Cmd+(the Cyrillic character on the A key) instead of Cmd+A, so all shortcuts involving letters stop working. I believe that this problem was the reason that this whole mapping complication was introduced. 
- When receiving a shortcut event with a character, first look if there is an action for that character; only if not, then look in the map which maps from character to key combination, and check if there is an action for the resulting key combination
    - that would not solve the problem that user-entered shortcuts (which get saved as characters) may wrongly be passed to the macOS API which will give an unexpected answer for those; i.e. `,` would still be mapped to both `,` and `<`, and `<` would still be mapped to nothing. But that would probably not matter: for both `,` and `<` we would not have to look in the map at all, because for both there would be an action already without looking in the map.
- a slightly more refined version of the previous: let the shortcuts file explicitly specify which shortcuts should be treated as characters and which as key combinations. 
    - this would solve the problem of having bad data in the map
    - but all user-entered shortcuts will forever be marked as characters (because when recording shortcuts, Qt only lets us see the typed character, not the physical key combination) which means that user-specified shortcuts won't work across keyboard layouts. This is a disadvantage that the previous solution would not have afaics; or at least, with the previous solution, if you record a shortcut using latin keyboard layout, then you can still invoke it without problems in Cyrillic layout (not the other way around), while with this solution that would not be possible. 
 - we could analyse keyboard layouts to get a better overview of differences and non-differences. Perhaps it turns out that only letter shortcuts would need this special mapping between characters and keys. 

I'm not sure which option would be best and which option would be simplest. Perhaps the second one. Will continue investigating tomorrow. 

A big unknown to me is why we only have this mapping complication on macOS. Does the problem that it is trying to solve not apply to other OSs? Or is it simply not _yet_ on other OSs because it was too complicated to implement on those OSs?
Another big unknown is how anyone has been able to find out how to do this mapping with this ancient macOS API, because on the internet I can hardly find any useful documentation for it.

**Comment by Eism** [comment] 2024-10-10 06:19
the main reason why we added mapping complication on macOS is that if the user changes the layout to a non-english one, then the shortcuts stop working https://github.com/musescore/MuseScore/issues/10854

> The fact that < and > don't work, is caused by the more fundamental problem that the "Edit shortcut" dialog records shortcuts in a character-based way (it sees "<" and ">") while the shortcut invocation controller sees key combinations, i.e. Shift+, and Shift+.

yeah, looks like we need to fix that

**Closed** 2024-10-14 14:29 UTC
Labels: P2, regression MS4, UX/interaction
