### ISSUE TITLE
The "Play" Toggle Affects Entire Measure

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#23071] opened 2024-06-04 03:42 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The play toggle in the properties panel seems to be affecting the entire measure instead of just the boundaries of the user selection. This is a problem because I wish to mute, let's say, only certain notes, and not the entire measure.

Seems like the bug only occurs when using range selection (i.e., using the shift key to select the outer notes).

### Steps to reproduce

1. Put notes in any particular measure
2. Use range selection to select only some of the notes in the measure
3. Toggle 'play' in the properties panel
4. Note entire measure has been affected

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102642087/34c5a38b-c7d8-43ef-9b53-5ddfe2a197dc

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241490900, revision: github-musescore-musescore-026c26b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

(My screen recording was recorded in MuseScore 4.3.0 but I have since confirmed (by updating my app) that the issue persists in 4.3.1 as well)

**Comment by DaddyLudwig** [comment] 2024-06-04 03:55
Seems to be specific to range selections that are within a single measure, cause I just did a range selection across 2 measures to silence some notes and it didn't affect the other notes in either of the 2 measures, just the range selection itself.

**Comment by rich777300** [comment] 2024-06-04 04:03
Seems to be somehow inexplicitly inconsistent

https://github.com/musescore/MuseScore/assets/102642087/788918f3-e05d-4ea9-badd-d9558627c948

**Comment by MarcSabatella** [comment] 2024-06-05 13:35
If I'm not mistaken, the issue is that a range selection that includes one or more beamed notes will end up considering the beam as selected, and then apply any properties to all notes on the beam.  As such, it is likely a duplicate of https://github.com/musescore/MuseScore/issues/21285 which seems to be already addressed for 4.4

**Comment by oktophonie** [comment] 2024-06-06 08:46
Good spot @MarcSabatella!

**Closed by oktophonie** 2024-06-06 08:46 UTC
Labels: P3, regression, UX/interaction
