### ISSUE TITLE
MuseScore 4.1.0 / 4.4.0 AppImage does not launch on Debian/bookworm under Wayland

### ISSUE THREAD

**Issue by jlaine** [musescore/MuseScore#18598] opened 2023-07-14 13:30 UTC
### Issue type

Crash or freeze

### Bug description

Running the `MuseScore-4.1.0.231921359-x86_64.AppImage`  binary on Debian bookworm under wayland crashes immediately. The `MuseScore-4.0.2.230651545-x86_64.AppImage ` binary worked fine.

### Steps to reproduce

Download the official AppImage and try to run it.

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian bookworm

### Additional context

15:25:47.957 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/XXX/.local/share/MuseScore/MuseScore4/logs/MuseScore_230714_152547.log
15:25:47.957 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.1.0, build number 231921359 ===
15:25:47.970 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
15:25:47.970 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
15:25:47.970 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
15:25:47.970 | INFO  | 139927813613248 | IpcServer  | listen: id: "8e2dc1e2f2a7458598fbc6a95fce9f10" 
/tmp/.mount_MuseScRs0jDw/bin/mscore4portable: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags

**Comment by jlaine** [comment] 2023-07-14 14:46
This looks related to https://bugreports.qt.io/browse/QTBUG-114635

**Comment by jlaine** [comment] 2023-07-14 17:43
Looks like this is the PR that changed the behaviour: https://github.com/musescore/MuseScore/pull/13781

**Comment by shoogle** [comment] 2023-07-16 08:13
> The reason the previous release "worked" seems to be that it did not ship with the wayland platform plugin, so it immediately fell back to X11 - not ideal.

Correct. As I said in PR #13781, X11 is more reliable than Wayland so Qt will use X11 by default unless you opt-in by setting `QT_QPA_PLATFORM=wayland`.

If your distribution sets `QT_QPA_PLATFORM=wayland` by default then you might want to try running `unset QT_QPA_PLATFORM` before you run MuseScore.

Let us know if that solves it for you and then we can decide whether to always use X11 until Wayland support has improved.

**Comment by jlaine** [comment] 2023-07-21 15:51
> If your distribution sets `QT_QPA_PLATFORM=wayland` by default then you might want to try running `unset QT_QPA_PLATFORM` before you run MuseScore.

Neither my distribution nor my desktop environment (KDE) set the `QT_QPA_PLATFORM` environment variable.

AFAICT Qt detects it is running under wayland due to the `XDG_SESSION_TYPE` variable being (correctly) set to `wayland`.

So, to fall back to X11 I now need to explicitly set `QT_QPA_PLATFORM=xcb`.

> Let us know if that solves it for you and then we can decide whether to always use X11 until Wayland support has improved.

Just to be clear, this is not a question of reliability or "support improving", this is a packaging error: the combination of libraries shipped with the binary is bound to fail, because you end up using an incompatible mix of system and vendored libraries!

**Comment by MJC-code** [comment] 2023-09-12 21:38
I can confirm this bug also occurs under Debian Unstable, running the KDE desktop with Wayland. The QT_QPA_PLATFORM environment variable is not set. 

It does look as if the linuxdeployqt maintainer has no desire to support Wayland, which is a shame for KDE users, since Wayland looks to be the focus of most of the ongoing developer effort in KDE.

**Comment by theofficialgman** [comment] 2023-12-08 01:05
> This looks similar to https://bugreports.qt.io/browse/QTBUG-114635

I went through those comments and indeed this issue is likely caused by a change wayland side in 1.20+. SDL2 worked around this it seems by adding the symbols to their own binary: https://github.com/libsdl-org/SDL/pull/5092
Ubuntu focal (which is what the appimage is built on) has wayland 1.18 . Not sure if that would fix the runtime error we are seeing or only their build time error.

**Comment by theofficialgman** [comment] 2023-12-08 03:29
As expected, modifying the CI to use jammy (22.04) to build the appimage on (wayland 1.20) does produce a build compatible with my system (ubuntu mantic 23.10)

https://github.com/theofficialgman/MuseScore/actions/runs/7136789032

I don't think that is a very suitable solution for MuseScore though as that would make the build incompatible with many older distros (ubuntu focal, debian bullseye, etc)

**Comment by cbjeukendrup** [comment] 2023-12-10 14:19
@shoogle See #20391, which basically reverts #13781 for 4.2 because apparently it causes too significant other problems.

**Comment by shoogle** [comment] 2023-12-11 13:23
> modifying the CI to use jammy (22.04) [...] does produce a functional native wayland build

We can consider doing that around July 2024, after Ubuntu 24.04 LTS has been released and had a few months to stabilize. It's possible that GitHub will begin deprecating the 20.04 image around that time anyway, [like they did for 18.04](https://github.com/actions/runner-images/issues/6002) (although hopefully with more warning and fewer brownouts this time).


Note that we would build against 22.04 not 24.04, but it's worth waiting for the next LTS anyway so that 20.04 users have the option to skip 22.04 and go straight to 24.04.

**Comment by RomanPudashkin** [comment] 2023-12-15 08:16
Closing, should be fixed by https://github.com/musescore/MuseScore/pull/20391 (in 4.2.0). Please reopen if you can still reproduce it

**Comment by cbjeukendrup** [comment] 2023-12-15 22:46
@RomanPudashkin The fix for this issue was _not_ included in master (4.3), because we want to look for a better fix. The 4.2 fix namely reverts https://github.com/musescore/MuseScore/pull/13781, so brings back the problem that was fixed by that PR. For 4.3, hopefully a way can be found to fix all problems.
So therefore I will reopen this.

**Closed** 2024-05-20 08:40 UTC
Labels: P1, regression, crash, os: linux
