### ISSUE TITLE
[MU4 Task] [GP] Display tapping, slap and pop correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10317] opened 2022-01-19 13:36 UTC
**Task description**
Display tapping, slap, pop.
Show them above the staff

**Comment by boryskuzmenko** [comment] 2022-04-20 19:16
**Reopened**
The issue is partly fixed. Tap, slap, pop marks are placed at the begin of the measure in case when have been assigned to separate notes. Seems like it shouldn't be recognized as a different text type instead of staff text type.
![Capture 2022-04-20_10-07-02_PM](https://user-images.githubusercontent.com/101250347/164305753-68859c0a-25d9-459e-b220-353de5b1b0f4.png)

**Comment by boryskuzmenko** [comment] 2022-04-21 17:18
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

**Closed** 2022-04-21 17:18 UTC
Labels: 3 SP
