### ISSUE TITLE
Empty alert box showed up on quit

### ISSUE THREAD

**Issue by robinwhittleton** [musescore/MuseScore#18026] opened 2023-06-17 17:08 UTC
### Issue type

Other type of issue

### Bug description

I loaded a musicxml file (https://github.com/standardebooks/edward-lear_nonsense-books/blob/3688bb67ddeb0e5f2c56ec0920caab0daf4113fb/images/sheet-music-the-courtship-of-the-yonghy-bonghy-bo.musicxml) into Musescore 4.0.2 on macOS 13.4, then quit using cmd+q. I then received an empty alert box.

### Steps to reproduce

I can’t reproduce beyond the first time, unfortunately.

### Screenshots/Screen recordings

<img width="781" alt="Screenshot 2023-06-17 at 19 05 56" src="https://github.com/musescore/MuseScore/assets/7414/69d17ca7-e5be-46cd-baa9-c76fed440a53">

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

macOS 13.4

**Comment by robinwhittleton** [comment] 2023-06-17 17:08
Feel free to close this if it’s unreproducable.

**Comment by DmitryArefiev** [comment] 2023-07-03 11:29
Can't reproduce it on my Mac 13.4.1 (4.0.2 release build,  4.1 latest nightly build)

Let's close it. Please reopen if you find how to reproduce it again

**Closed by DmitryArefiev** 2023-07-03 11:29 UTC
