### ISSUE TITLE
Crash when change predefined order instruments

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#22958] opened 2024-05-23 16:28 UTC
### Issue type

Crash or freeze

### Bug description

Crash when change predefined order instruments

### Steps to reproduce

- Open Score Provided
- Go to instrument "i" keyboard
- Select another instruments order (Example : Orchestra)
- Click "Ok"
- Crash

### MuseScore Version
MuseSore 4.4.0 Master
MuseScore Studio version (64-bit): 4.4.0-241440305, revision: github-musescore-musescore-fb65d50

### Regression

Yes, this used to work in **MuseScore 4.3.1**

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, 

### Additional context

[crash.zip](https://github.com/musescore/MuseScore/files/15419729/crash.zip)

**Comment by mercuree** [comment] 2024-05-23 18:17
https://github.com/musescore/MuseScore/assets/919446/dfabc00f-e35f-4ed9-9ad2-9eea63838339

Can't reproduce in Musescore 4.3.0

**Comment by DmitryArefiev** [comment] 2024-05-24 09:25
@mercuree  Thanks for details! **Can't reproduce** in  **4.3.1** as well
@Gai-Luron Thanks for logging!

**Comment by mike-spa** [comment] 2024-07-05 11:27
This doesn't crash anymore on master. It probably got fixed in #23431 which had a crash with similar steps, so I'm going to close it.

**Closed by mike-spa** 2024-07-05 11:27 UTC
Labels: P0, regression, crash
