### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by havizvaisal** [musescore/MuseScore#13897] opened 2022-10-23 04:45 UTC
No tuning plugin makes any effect on the tuning of Muse Basic sounds in Musescore 4 Beta, when they did in Musescore 3.6.2.

**To Reproduce**
1. Go to 'Plugins'
2. Click on any tuning plugin
3. Select tuning and click 'apply'
4. Playback is unaffected, continues playing in equal temperament.

**Expected behavior**
A change in the tuning of each note by the specified cents of the tuning selected.

**Platform information**
 - OS: [Linux, Ubuntu 22.04.1 LTS]

**Comment by Tantacrul** [comment] 2022-10-23 10:37
Duplicate of https://github.com/musescore/MuseScore/issues/13896

**Closed** 2022-10-23 10:41 UTC
