### ISSUE TITLE
Notes Sustain instead of stopping on Breath Marks and Caesuras

### ISSUE THREAD

**Issue by joecorporon** [musescore/MuseScore#20719] opened 2023-12-26 20:54 UTC
### Issue type

General playback bug

### Bug description

In a previous Musescore 4 score this worked properly. With the introduction of version 4.2.0 I noticed this bug.

### Steps to reproduce

1. Enter notes into a score including breath marks or caesuras.
2. Set the playback properties to include a pause of .5 or 1 seconds for the breath mark or caesura.
3. Playback the file.

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Endeavour OS (Arch Linux)

### Additional context

All previous versions of Musescore 4 before 4.2.0 will playback properly.

**Comment by MarcSabatella** [comment] 2023-12-26 22:40
Thanks for submitting; this seems to be a duplicate of https://github.com/musescore/MuseScore/issues/20669

**Closed** 2023-12-27 09:20 UTC
Labels: regression, playback
