### ISSUE TITLE
Style Menu - long load

### ISSUE THREAD

**Issue by wjd132** [musescore/MuseScore#17155] opened 2023-04-06 23:42 UTC
### Issue type

UI bug

### Bug description

The Format>Style menu takes several seconds to appear every time I access it. This occurs whether accessed through the ribbon at the top or by right-clicking on the score and selecting "style" from there. I have reset to factory settings; the problem remains.

### Steps to reproduce

Access the style menu via any means (see above)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/130110182/230512659-7ee1e512-d2fa-473b-bc62-8fff2e4af200.mp4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Win 11 (most recent, 22H2 22621.1413)

**Comment by Eism** [comment] 2023-04-07 06:28
Duplicate of #13193
Thanks for reporting!

**Closed by Eism** 2023-04-07 06:29 UTC
Labels: UI, regression

**Comment by wjd132** [comment] 2023-04-07 15:01
Thank you! Sorry to duplicate: I was looking on the Musescore site and didn't see anything related to this issue. I'm new to the Github threads. I'll check here before posting in the future.
