### ISSUE TITLE
"Lyrics even line" style applies only to first entered syllable

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#23846] opened 2024-07-31 03:27 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Make a change to the **Lyrics even lines** text style in Format > Style
2. Enter lyrics into verse 1
3. Enter lyrics into verse 2

Note how only the first entered syllable in verse 2 takes the **Lyrics even lines** text style (verifiable in Properties). 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4cee71b5-bd37-4fe2-99bf-8496d3249df8

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242120301, revision: github-musescore-musescore-70c122e

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.5

### Additional context

Regression occurred between 4.2.1 and 4.3.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-08-05 18:09
Duplicate of #13762

**Closed** 2024-08-06 11:22 UTC
Labels: P1, regression MS4, engraving
