### ISSUE TITLE
Error opening mscz file with Cyrillic name

### ISSUE THREAD

**Issue by VladislavBuyalski** [musescore/MuseScore#24305] opened 2024-08-30 07:01 UTC
### Issue type

Opening/saving issue

### Description with steps to reproduce

1. Create any score.
2. Save to hard drive, specifying any Cyrillic name.
3. Open file from Explorer. The following error occurs: File does not exist or is not accessible at the moment.
4. Open MuseScore Studio and use the key combination CTRL+O to open a previously created score. The file will open normally.
5. Rename the previously created score using Latin.
6. The file will open normally in both ways.

### Supporting files, videos and screenshots

The exact text of the error: Cannot read file D:\РњСѓР·С‹РєР°\РЎРѕС‡РёРЅРµРЅРёСЏ\Р’ СЂР°Р±РѕС‚Рµ\Р . РўР°СЂР°РЅРёРЅ - Р’Р». Р‘СѓСЏР»СЊСЃРєРёР№ - Р’Р°Р»СЊСЃ.mscz This file does not exist or cannot be accessed at the moment.

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 (64 bit)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-30 07:06
Duplicate of https://github.com/musescore/MuseScore/issues/23811

**Closed by oktophonie** 2024-08-30 07:06 UTC
Labels: regression MS4
