### ISSUE TITLE
[MU4 Issue] Text palet contains user selected language and english elements

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12769] opened 2022-08-10 21:26 UTC
**Describe the bug**
When using a different language, in my case Dutch, the Text palet is showing translated items. A very good thing!
However, when I click the More button the English versions of the same element is available.

**To Reproduce**
1. Select another language then English
2. Restart MS4
3. Open an existing or start a New Score
4. Check the Text palet

**Expected behavior**
The english equivalent of the element should not be shown in the more section.

**Screenshots**
Highlighted a few in the image, more exist.
![image](https://user-images.githubusercontent.com/13550012/184022874-4be188f5-042a-4378-ab52-caf575c94927.png)

**Platform information**
 - OS: Windows 10 Dutch

**Additional context**
Using the Alpha2 release

**Comment by cbjeukendrup** [comment] 2022-08-11 16:39
Does resetting the Text palette help in this case?

**Comment by henkdegroot** [comment] 2022-08-11 17:23
Tried that (twice) and did not make a difference

**Comment by henkdegroot** [comment] 2022-08-11 17:50
And also tested with Polski and got the same result.

**Comment by cbjeukendrup** [comment] 2022-10-24 20:04
@henkdegroot Can you still reproduce this? As @DmitryArefiev found while testing #12853, we can't reproduce this anymore in the latest master.

**Comment by henkdegroot** [comment] 2022-10-24 20:35
@cbjeukendrup, issue still exists in Beta...however I just downloaded the Nightly from this morning and cannot reproduce this anymore. So does seem something has fixed. Also happy to see Dutch in the splash screen (instead of Loading...) :)

**Comment by DmitryArefiev** [comment] 2022-10-25 11:17
Tested in latest master on Win10, Mac12, LinuxMint 20.2 - **FIXED**

Closing

**Closed** 2022-10-25 11:18 UTC
Labels: P2
