### ISSUE TITLE
Allow template to preserve more score details than currently possible

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19392] opened 2023-09-13 16:29 UTC
### Issue type

Feature request

### Bug description

For some reason a template does not preserve **Lyricist** text at all in the opening frame. No further tests were done but perhaps there is other information that is not being preserved?

### Steps to reproduce

1. Create a classical guitar score No other info needed.
2. On the score page itself add Lyricist text to the opening frame.
3. Save this score in the user templates folder.
4. Close file
5. Open the New score dialog and choose the newly-created template.

RESULT: The lyricist text has been lost.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by MarcSabatella** [comment] 2023-09-13 17:51
Templates aren't supposed to save content, just formatting.  Information like title, composer, and lyricist is meant to be filled in when you create the new score from the template, in the second page of the wizard.

**Comment by Jojo-Schmitz** [comment] 2023-09-13 18:02
Basically by design and the case ever since

**Comment by rgreen5** [comment] 2023-09-14 09:26
I'm OK to close this.

**Comment by Jojo-Schmitz** [comment] 2023-09-14 09:35
It might be a fair enhancement request.
Similar for images, see a.lso https://musescore.org/de/node/238856

**Comment by rgreen5** [comment] 2023-09-14 15:56
By popular demand I'm reopening as a feature reuest. :-)

**Comment by MarcSabatella** [comment] 2023-09-14 15:59
If you're going to turn this into a feature request, please rewrite the description and describe how the proposed new feature would work.  It's important, of course,e the current functionality not be adversely affected d- content from templates should absolutely *not* make their way into new scores bny default, so you'd want to propose a mechanism for specifying - either when creating the temple or the score - when you want template content included in the score.

**Comment by Jojo-Schmitz** [comment] 2023-09-14 16:07
* Take copyright from template's metadata (if exist)
* Take lyricist from template's metadata (if exist)
* Take composer from template's metadata (if exist)
* Take image from template's title frame (if exist), attach to newly created frame

**Comment by MarcSabatella** [comment] 2023-09-14 17:41
I'm not crazy about that personally, in that it means we need to go out of our way to delete the metadata before saving the template if were don't want this behavior, which 90% of the time we don't.  And yes, putting it in the wizard would allow us to remove it there, but again, that's an unnecessary extra step, and besides, people often skip that second page anyhow, and now you have to delete all this from the score itself.

I think if there is to be a mechanism to have some things from the template copied into the new score, it needs to be opt-in, not opt-out.

**Comment by Jojo-Schmitz** [comment] 2023-09-14 17:54
The regular templates don't have any of these

**Comment by MarcSabatella** [comment] 2023-09-14 18:14
If you mean, none of these are copied from the template to the new score, then yes, that's as it should be.  So I'm saying, if we want some additional template options where some of this info can be copied to the score, it should still default to not doing that.

**Comment by MarcSabatella** [comment] 2023-09-14 18:51
Sorry, I don't follow then.  By "regular template", maybe you mean, the ones that come pre-installed?  I'm not concerned with those.  I'm concerned with the process of creating and using our own (equally "regular") templates - I don't want this to become harder for normal use cases just to save a step for the unusual special situations where you want template info preserved.

**Comment by MarcSabatella** [comment] 2023-09-14 18:57
So, for instance, a button within that second page of the wizard that says "load template metadata" would be one method.  Or, a separate "Save template" dialog (which is a common request just to improve the visibility of the process of creating templates), that has a checkbox to set a special flag within the template to force its metadata to be read when creating new scores.

**Comment by Jojo-Schmitz** [comment] 2023-09-14 18:59
Yes, the built-in ones.
On others I just assume the inclusion copyright, lyricist and composer to be intentional

**Comment by MarcSabatella** [comment] 2023-09-14 19:09
What we have always documented is that you can take any old score you like and save it to your templates folder, and then new scores will be created from it using the structure but not the content, which is how most people would want it most of the time.  People aren't going to want to have to remember to strip away metadata before saving just to avoid every single new score having the same metadata as the template.  Might as well ask them to also delete all measures to avoid having those copied as well...

**Comment by Jojo-Schmitz** [comment] 2023-09-14 19:29
The measures are good for the show, for the thumbnai view of the template. As is the title, so don't copy that.

**Comment by Jojo-Schmitz** [comment] 2023-09-15 07:33
If the copyright, lryicist and composer fields come pre-filld with the template content in the new score wizard, they can get edited, change or removed right there.
An extra dialog of whether this is wanted, either on template save or on score creation, to me seems like over-engineering the issue.

**Comment by oktophonie** [comment] 2023-09-15 10:15
This has now become yet another tedious, rambling exchange that anyone who wants to look at this issue will have to sift through, so I'm going to close this.

@rgreen5 if there really is "popular demand" for this (which I doubt) then open a new issue, specifically as a feature request and, as Marc says, describe how it ought to work.

**Closed by oktophonie** 2023-09-15 10:15 UTC
Labels: feature request
