### ISSUE TITLE
[MU4 Issue] Inserting measures in a part results in completely empty bars, overlapping notes/rests, and other corruption-like behavior

### ISSUE THREAD

**Issue by YottaYocta** [musescore/MuseScore#15185] opened 2022-12-15 02:40 UTC
Inserting measures in a part results in completely empty bars, overlapping notes/rests, and other corruption like behavior

**To Reproduce**
1. Open a new String Orchestra Score
2. Add a piano to the score
3. navigate to piano score
4. add an arbitrary number of notes across a couple measures
5. select a measure in the middle of these notes and insert more than one measure (shift-I)
6. error appears; empty measures, etc. (see title)
7. navigate back to main score; piano measures are still intact

**Expected behavior**
Measures surrounding inserted measures should retain formatting in both the full score and part score; inserted measures should be filled with a rest in the full score and part score

**Screenshots**

https://user-images.githubusercontent.com/62713886/207759065-8cb28e96-d8fe-4e8b-8ba8-4408a7e1581f.mov

Piano (in full score with other parts not visible):
<img width="543" alt="image" src="https://user-images.githubusercontent.com/62713886/207759537-5b2e1eb0-a389-4cba-a281-76d721610058.png">

Piano (in part):
<img width="642" alt="image" src="https://user-images.githubusercontent.com/62713886/207759728-0a8e6765-f3c9-49a5-a38a-14e995a63dd1.png">

**Platform information**
- OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by Eism** [comment] 2022-12-15 09:21
Actually they should be empty
@bkunda Should we mention it in the handbook for [MU4](https://musescore.org/en/handbook/4/adding-and-removing-measures#keyboard-shortcuts) as it was for [MU3](https://musescore.org/en/handbook/3/measure-operations#insert-measure)?

Anyway, there is a problem with drawing empty measures if 'multimeasure rest' is disabled 
@oktophonie FYI

**Comment by bkunda** [comment] 2022-12-16 09:58
> Actually they should be empty @bkunda Should we mention it in the handbook for [MU4](https://musescore.org/en/handbook/4/adding-and-removing-measures#keyboard-shortcuts) as it was for [MU3](https://musescore.org/en/handbook/3/measure-operations#insert-measure)?

You're right @Eism: when inserting a measure, the newly inserted measure should always be empty. If it contained notation, it would have to be an arbitrary operation (i.e. what notation should the bar contain?). This would end up being quite unpredictable. 

I shouldn't think this _needs_ explanation in the handbook, because you can't _insert_ content-containing measures. 

Certainly the main issue here seems to be how those newly-inserted measures are drawn in the parts.

**Comment by YottaYocta** [comment] 2022-12-17 02:52
@Eism sorry about that, I meant that the inserted measures should be empty while keeping the surrounding measures unaffected. I have edited the original issue to reflect this.

**Comment by cbjeukendrup** [comment] 2022-12-17 03:35
After some not very successful debugging, I ended up doing a large Git bisect (quite nostalgic to see all those old bugs again! 😄) 
It turns out that this is caused by f0705a60ae2b34c3241aca710e63d45985e88a57, by @RomanPudashkin. I forgive myself for not discovering that by purely debugging 😅

**Comment by RobFog** [comment] 2022-12-18 10:57
This might deserve a higher priority than P2. Score corruption is a very nasty thing for usability.

**Comment by cbjeukendrup** [comment] 2022-12-18 12:02
> This might deserve a higher priority than P2. Score corruption is a very nasty thing for usability.

@Tantacrul I think this is a good point. Once scores get corrupted, they aren't uncorrupted that easily. So the longer this broken build is out there, the more scores will be corrupted. I'm quite seriously in favour of doing a patch release with my fix for this as soon as possible. But everyone is on a well-deserved holiday now...

**Comment by shoogle** [comment] 2022-12-18 12:10
I don't think everyone is on holiday at the moment. At least they shouldn't be. If they are then we clearly didn't learn our lesson from the 3.0 release 😆

**Comment by DmitryArefiev** [comment] 2023-01-09 14:30
Fixed in #15257

**Closed** 2023-01-09 14:43 UTC
Labels: P2
