### ISSUE TITLE
MS Basic trombone sustains note indefinitely

### ISSUE THREAD

**Issue by rustykitty** [musescore/MuseScore#25907] opened 2024-12-22 15:22 UTC
### Issue type

General playback bug

### Description with steps to reproduce

I created a score with tempo at 138 and in the trombone part I put this (MS Basic):
<img width="611" alt="image" src="https://github.com/user-attachments/assets/84049f8d-83d9-4fe4-b778-b0c4ef937266" />
When I played it back, the F#3 sustained indefinitely. Doesn't matter if there are notes after the F#, it keeps going. 
This doesn't seem to happen without the crescendo, but with the crescendo it happens regardless of the dynamic level. 

### Supporting files, videos and screenshots

OBS causes issues with my audio, so I'll just upload the score and mp3 file in one ZIP.
[trombone bug.zip](https://github.com/user-attachments/files/18222366/trombone.bug.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 15.1, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 15.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-12-24 17:13
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/25831 and https://github.com/musescore/MuseScore/issues/25915

**Closed** 2024-12-27 14:35 UTC
Labels: playback, regression MS3
