### ISSUE TITLE
Grace note effect when staccato is in proximity to non-staccato at fast tempos in Violin 1 Solo (Muse Sounds)

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#17170] opened 2023-04-08 01:59 UTC
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Open Beethoven string quartet score
2. Start playback
3. Hear the grace note effect (Bar 20 is a good example of what I'm meaning by grace note effect, there's staccato in proximity and the slurred legato notes in proximity to the staccato sound like grace note followed by main note when they are supposed to be straight eighths)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/6530761/230698253-d102425b-d1eb-461a-81c6-ca8105245448.mp4

### MuseScore Version

MuseScore 4.0.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

From what I can tell, the staccato notes have to be at most 2 bars away for it to have an effect on the non-staccato notes. And I've only had this happen at fast tempos with eighth notes. Muse Sounds Violin 1 Solo is the only instrument affected by this.

**Comment by DaddyLudwig** [comment] 2023-04-08 02:01
Score
[String Quartet no 4 in C minor Op. 18 no. 4.zip](https://github.com/musescore/MuseScore/files/11182319/String.Quartet.no.4.in.C.minor.Op.18.no.4.zip)

**Comment by Tantacrul** [comment] 2023-07-25 13:29
I suspect this might be a MuseScore 4 playback problem rather than a Muse Sounds issue (although it might be a combination). The grace notes can't really be heard in MS Basic either.

**Comment by zacjansheski** [comment] 2023-09-08 15:17
For future reference:
It is easier to hear with Violin 1 Solo

https://github.com/musescore/MuseScore/assets/69917893/b8f8832a-7047-4d3a-90cc-243e16ec89b1

**Comment by DmitryArefiev** [comment] 2024-06-08 15:55
Seems to be it sounds better than in the initial video

**Comment by DmitryArefiev** [comment] 2024-06-08 15:56
@DaddyLudwig Please recheck it on your end. Make sure you are using Muse Sampler v0.6.3

**Comment by DaddyLudwig** [comment] 2024-06-09 03:13
I don't really hear much of a difference in the grace notes themselves. And I still have the issue where the 2 note slur eighth notes that are generally within a bar or 2 at most of staccato notes sound like a grace note followed by a main note. Particularly noticeable from bar 27 onwards in the video. Like in bar 27, it sounds like a staccato G followed by a grace note Ab and a longer Eb, even though they are all eighth notes, there are no grace notes in that bar.

https://github.com/musescore/MuseScore/assets/6530761/1534fbed-e833-4f1e-8d73-7ff0a3f731a2

**Comment by bkunda** [comment] 2024-06-11 15:24
I think this issue has generated a bit of confusion.

Please see [this summary here](https://www.dropbox.com/scl/fi/empzuixnr33g38e6zd1yk/violin-1-rhythmic-issues.mov?rlkey=jeb6c314d586xjg7zv05dh97b&dl=0) (8mins).

TL/DR:
- It's not an issue concerning grace notes themselves, but rather a rhythmic effect that "kind of" mimics a grace note, but is actually more subtle and intricate than can be described as a"grace note effect"
- The issue is particular to Muse Sounds Violin 1 (Solo)
- It's no longer clear that the presence of staccato articulation marks are definitively relevant.

In sum, this issue seems to be yet another manifestation of the known rhythmic problems relating to Muse Violin 1 (Solo). My sense is that the rhythmic effects being heard are a product of this particular sample library's characteristically slow attack. 

To this end, in order for this to be a helpful issue, we would need a more systematic range of examples where different combinations of articulations are shown across different intervals, and compared at different tempi. Furthermore, different libraries and playback technologies would be compared to make the differences between this library and others much clearer. 

As a general rule, providing lengthy musical examples is less helpful in cases like this than minimal examples that more precisely demonstrate the problem.

I'll be closing this ticket for now because the issues concerning Muse Violin 1 (Solo) are already known and logged elsewhere.

**Closed by bkunda** 2024-06-11 15:24 UTC
Labels: needs info, P1, playback, muse sounds
