### ISSUE TITLE
Glissandos not working properly

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#16893] opened 2023-03-17 23:18 UTC
### Issue type

Other type of issue

### Bug description

Glissandos (and scoops, falls, etc.) are not in a new part created. When a glissando is added after the part is alreadey existent it is correctly shown in both: the main score and the staff score.

### Steps to reproduce

0. write a simple score with 2 staffs
1. add a glissando anywhere
2. create a part - glissando should not be there
3. go back to main score and now add another glissando
4. check in the staff -> the new glissando should be there

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-03-18 09:23
Closing as duplicate of https://github.com/musescore/MuseScore/issues/16096

**Closed by oktophonie** 2023-03-18 09:23 UTC
Labels: duplicate, needs review, regression
