### ISSUE TITLE
VST: Looping causes some VST's to gradually increase in volume 

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10916] opened 2022-03-26 11:13 UTC
**Describe the bug**
This is very possibly related to these issues:(https://github.com/musescore/MuseScore/issues/10974 & #10915). 

In this example, I'm using the free Surge synth. https://surge-synthesizer.github.io/

The problem is that when looping, the surge synth keeps getting louder and louder with each loop.

See video:

https://user-images.githubusercontent.com/21022311/160236842-840aefc3-d2c1-46fc-80c0-f7a78d4f7eed.mov

**Comment by Fince10086** [comment] 2022-03-26 12:48
not only in looping but also happen when select notes
https://user-images.githubusercontent.com/87692117/160240159-3552bed4-887c-4789-b8d7-2983a46829be.mp4

**Comment by jessjwilliamson** [comment] 2022-03-30 11:59
> not only in looping but also happen when select notes
> 
>  2022-03-26.20-46-40.mp4

ohhh ouch :D

**Comment by bkunda** [comment] 2022-05-23 05:48
I've also been able to reproduce this across a range of VSTs. 

I'm going to suggest it is actually a P1, as playing back a score and clicking on any number of notes gradually seems to cause the volume to increase, and eventually clip. The only way to "reset" the playback volume seems to be to quit and re-open MuseScore.

**Comment by Tantacrul** [comment] 2022-05-23 18:46
Agreed. I'm not sure why I marked it a P2. It's a P1 for sure. A 'Hard' P1, if you will :)

**Comment by vpereverzev** [comment] 2022-07-27 13:23
Fixed in #12568

**Closed** 2022-07-27 13:28 UTC
Labels: P1
