### ISSUE TITLE
Saved files become corrupted on opening

### ISSUE THREAD

**Issue by innerthought** [musescore/MuseScore#18087] opened 2023-06-21 13:07 UTC
### Issue type

File corruption

### Bug description

Saved files become corrupted on opening. "Open anyway" doesn't work. I want to stress that all the files were saved and closed during the previous session without any message like "File cannot be saved properly" or "Can't save the file"

### Steps to reproduce

1. got to: either of the files attached
2. then: open it and try to click "Open anyway"
3. then: see that nothing happens. 

[first.mscz.zip](https://github.com/musescore/MuseScore/files/11817803/first.mscz.zip)
[second.mscz.zip](https://github.com/musescore/MuseScore/files/11817804/second.mscz.zip)
[third.mscz.zip](https://github.com/musescore/MuseScore/files/11817806/third.mscz.zip)

With each file, while trying to open it, I firstly get this message:

"This file contains errors that could cause MuseScore to malfunction"

and when I click on "Show details", I get this:

Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0

### MuseScore Version

4.0.2.230651553

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Win-10, 64-bit operating system, x64-based processor

**Comment by Jojo-Schmitz** [comment] 2023-06-21 13:11
Steps to reproduce needed, those you list are stepes to see the issue, but we'd need the steps that lead to those corruptions

Workaround: open the mscz files (or here the zip files) with 7ZIP or WinZIP or the likes and extract the mscx from them. Those often (and here too) to open

**Comment by Jojo-Schmitz** [comment] 2023-06-21 13:15
This issue has been reported time and time again in the forums on musescore.org, but so far nobody has been able to track it down to the root cause

**Comment by innerthought** [comment] 2023-06-21 13:16
> Steps to reproduce needed, those you list are steps to see the issue, but we'd need the steps that lead to those corruptions

-- Those steps are hard to reproduce. I mean you never know when it will happen. Basically it goes this way: 1) you create a score; 2) you edit it; 3) you open it and see that it is corrupted; It doesn't happen all the time, but it does happen from time to time;

> Workaround: open the mscz files (or here the zip files) with 7ZIP or WinZIP or the likes and extract the mscx from them. Those often (and here too) to open

-- I did that. Usually the "audiosettings" file turns out to be empty while it should have some settings specified in it.

**Comment by Jojo-Schmitz** [comment] 2023-06-21 13:19
Yes, I'm fully aware that finding the steps to reproduce is very difficult and maybe even impossible.
But without it is extremly hard, if not impossible, to fix this

**Comment by oktophonie** [comment] 2023-06-21 13:22
Closing, for reasons explained repeatedly.

**Closed by oktophonie** 2023-06-21 13:22 UTC
Labels: regression, corruption
