### ISSUE TITLE
"Based on the Rhythm of the Slashes" mode for Duration of Chord Symbols settings

### ISSUE THREAD

**Issue by s11141827** [musescore/MuseScore#23260] opened 2024-06-15 19:00 UTC
Currently the Duration feature of the Chord playback settings has 3 modes which are "Until the next Chord Symbol", "Until the End of the Measures", and "Until the end of the attached duration", so let's add a 4th mode called "Based on the Rhythm of the Slashes".

_Originally posted by @s11141827 in https://github.com/musescore/MuseScore/issues/16455#issuecomment-2170413775_

**Comment by MarcSabatella** [comment] 2024-06-15 19:39
This is a duplicate of #16455.  Please do not open duplicate issues for features that have already been requested.  it’s one thing if you legitimately didn’t know about the previous issue because it doesn’t show up in a search.  But that was an issue you submitted yourself.  Please stop.  The request is logged.  Some day an experienced programm may volunteer to implement it.  Until then, please stop posting here on GitHub about it.

**Closed** 2024-06-15 19:40 UTC
