### ISSUE TITLE
Crash when changing key signature

### ISSUE THREAD

**Issue by YoYomec** [musescore/MuseScore#17907] opened 2023-06-08 20:48 UTC
### Issue type

Crash or freeze

### Bug description

I have a saxophone alto partition. But there was key signature, and I don't want it, so I ctrl+clic on another armor to change it (without changing the notes), and the crash comes from this.

### Steps to reproduce

1. Create a saxophone alto partition, without changing anything.
2. Normaly, there is a default key signature.
3. Start to write a music
5. Select the bars where is the music
6. Ctrl+Clic on the `E bemol major, C minor` key signature, on the palettes tab
7. Spectate the crash of Musescore

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Excuse my english

**Comment by sammik** [comment] 2023-06-09 07:06
Duplicate of #16983
Fixed in latest master.

**Closed** 2023-06-09 07:07 UTC
Labels: duplicate, crash
