### ISSUE TITLE
Tied whole notes not playing when accented.

### ISSUE THREAD

**Issue by Magnichu** [musescore/MuseScore#18793] opened 2023-07-25 03:42 UTC
### Issue type

Muse Sounds bug

### Bug description

I have a brass chord in my score which consists of all instruments playing two tied whole notes that is accented. When the playback gets to the second whole note, the trumpet drops out. 

### Steps to reproduce

1. Two tied whole notes on the trumpet part
2. Accent
3. Listen on playback

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/140473190/d09548af-20a3-47d1-a1c7-40601e0ad474

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2023-07-25 13:15
I was able to reproduce using the specific score posted in the original forum thread at https://musescore.org/en/node/352577

**Comment by KBRichmo** [comment] 2023-11-15 13:50
[Millennium Celebration.zip](https://github.com/musescore/MuseScore/files/13365497/Millennium.Celebration.zip)

I also have this issue often on my scores. You can find an example in this score from Rehearsal Mark G to the End. Every time the Trumpets have a sustain longer than a measure, the playback cuts out after the first measure.

**Comment by MarcSabatella** [comment] 2023-11-15 21:05
OK, I can reproduce from scratch now, a single whole note D5 tied to another, with accent.  The key seems to be the tempo.  Works up to 133 BPM, fails starting at 134.

![image](https://github.com/musescore/MuseScore/assets/1799936/35246a82-20b6-48fd-a388-f604fda72053)

**Comment by KBRichmo** [comment] 2023-11-15 22:45
So it doesn’t seem to be score specific then? Its reproducible from scratch on all scores?

**Comment by MarcSabatella** [comment] 2023-11-15 23:59
Well, presumably it is limited to scores for trumpet at 134 BPM or above.  But there could be other things that cause it to not happen, which might explain why it seems to have not been reported often.

**Comment by bkunda** [comment] 2024-10-30 10:11
Closing this issue as it is MuseSounds-specific and already has a ticket in the appropriate repo.

**Closed by bkunda** 2024-10-30 10:11 UTC
Labels: muse sounds
