### ISSUE TITLE
[MU4 Issue] Crash after deleting instruments from score with custom part/first generic part (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14475] opened 2022-11-11 12:21 UTC
**To Reproduce**
1. Open [Rodny_moj_kraj_SQ.zip](https://github.com/musescore/MuseScore/files/9990140/Rodny_moj_kraj_SQ.zip)
2. Create new part and open it
3. In Part, show first 3 instruments from top
4. Open **Add or remove instruments** dialog (I shortcut)
5. Delete first 3 instruments from top in score

https://user-images.githubusercontent.com/90187801/201338994-2b4fe177-466d-407c-b38c-4ccf91a02b45.mp4

**Platform information**
macOS, Windows, Linux

**Comment by DmitryArefiev** [comment] 2022-11-11 12:23
@sammik I took your score from #14163, hope you don't mind :)

**Comment by sammik** [comment] 2022-11-11 15:15
It is not related (only) to "custom part".

If You follow steps to reproduce, but remove only two instruments - no crash.

But if You open first generic part, show second violin and than remove first three instruments - crash.

As far as I can tell, it must be:
1. custom part, or first generic part
2. first two instruments shown
3. first three instruments removed

and probably is somehow related to older scores 

https://user-images.githubusercontent.com/1646034/201369358-221c24c9-ad06-495e-859d-30e340dc7c56.mp4

**Comment by DmitryArefiev** [comment] 2022-11-11 15:52
> and probably is somehow related to older scores

Yes, agree.  And thanks for details!

**Comment by sammik** [comment] 2022-11-14 14:24
@DmitryArefiev 
Seems to be fixed on my side too. 
I can't reproduce it anymore.
(Linux)

Thanx

**Closed** 2022-11-17 09:21 UTC
Labels: P1

**Comment by DmitryArefiev** [comment] 2022-11-17 16:03
That's good. Thanks!
