### ISSUE TITLE
Tab notation formatting sometimes get corrupted in linked staves

### ISSUE THREAD

**Issue by akberg** [musescore/MuseScore#22074] opened 2024-03-27 09:56 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When including guitar in a score, I usually make an extra tab-only sheet, using linked staves to synchronize with the score. Sometimes, the engraving of the tab-only sheet gets corrupted (as seen on the screenshots below), with the only way of fixing it being to duplicate the instrument and recreate the part.

Never had an issue with this in MuseScore 3, though I also didn't have the same workflow and routine, so I might not have encountered this situation as often.

### Steps to reproduce

1. Open provided sample project
2. Create a part, adding one guitar, or navigate to the existing guitar parts
3. Make only the linked tabs stave visible
4. Do a few iterations of recreating part, readding instrument, restarting software before it fixes.

### Screenshots/Screen recordings

![Part guitar 2, both visible](https://github.com/musescore/MuseScore/assets/25877966/01770bee-ae90-4de2-8376-ed17cef541ba)
![Part guitar 2, only tab visible](https://github.com/musescore/MuseScore/assets/25877966/2217b84a-76cb-4f40-98f6-70e342f3fb80)
![Part guitar 1, both visible](https://github.com/musescore/MuseScore/assets/25877966/9fd3eece-f1ea-473c-8e5d-b3c34ccebc1e)
![Part guitar 1, only tabs visible](https://github.com/musescore/MuseScore/assets/25877966/12ac8af6-5796-464a-86b4-1c65d16f01f4)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11, Fedora 39, Kubuntu 22.04

### Additional context

[Sample project - Around Here.zip](https://github.com/musescore/MuseScore/files/14771353/Around.Here.zip)
[Diagnostics file around-here-1.zip](https://github.com/musescore/MuseScore/files/14771366/around-here-1.zip)

**Comment by oktophonie** [comment] 2024-04-29 10:26
This appears to be a duplicate of https://github.com/musescore/MuseScore/issues/20773 (which I'm happy say is fixed in 4.3!)

**Closed by oktophonie** 2024-04-29 10:26 UTC
Labels: engraving
