### ISSUE TITLE
Change Slur Direction Very Slow

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#20003] opened 2023-11-12 14:07 UTC
### Issue type

Performance bug

### Bug description

Changing direction of slur take 5s on large score. Other line type like crescendo, repeat line work instantly.
In 4.1 this action take half time.

### Steps to reproduce

Open a big score. Try to change slur direction, this take a while.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1835871/03e77d97-cbff-4bbf-94a1-76ff2ecf8b22

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233150307, revision: github-musescore-musescore-b719b39

### Regression

It was better in 4.1.1

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by bkunda** [comment] 2023-11-14 14:30
@DmitryArefiev pls test for regression

**Comment by DmitryArefiev** [comment] 2023-11-14 16:29
Yes, it looks better in **4.1.1** than in the **4.2 master**

on my machine with **Windows10** and using this score [Big_Score_4.1.0.zip](https://github.com/musescore/MuseScore/files/13351768/Big_Score_4.1.0.zip)
**4.1.1** takes 1.7sec
**4.2** takes **2.3sec**

so it's a **regression** comparing with 4.1.1 but not in half time

**Comment by DmitryArefiev** [comment] 2023-11-14 16:30
@Gai-Luron Can you attach the score please? (if possible)

**Comment by Gai-Luron** [comment] 2023-11-14 18:41
Hello,
You score it's not big enought. I modify it.
[Big_Score Bob 4.1.mscz.zip](https://github.com/musescore/MuseScore/files/13354273/Big_Score.Bob.4.1.mscz.zip)

Here the vidéo 4.1 VS 4.2
https://github.com/musescore/MuseScore/assets/1835871/69e9abb9-2edf-4db2-ad5c-21af93c0c63d

**Comment by DmitryArefiev** [comment] 2023-11-15 16:04
@Gai-Luron Hi! Thanks for the score! I still have the same results (**1.7sec** vs **2.3sec**) but that's not expected of course and should be fixed if possible.

My videos:

4.1.1


https://github.com/musescore/MuseScore/assets/90187801/3c7089e0-99a9-46c4-a49d-a1115e5d393f

4.2


https://github.com/musescore/MuseScore/assets/90187801/bc0bdff9-cc48-484d-8e7c-ceef1b81afe2


My laptop specs:
![Capture](https://github.com/musescore/MuseScore/assets/90187801/7de3e06d-9186-472d-9158-9f211cb9ef95)

**Comment by mike-spa** [comment] 2023-11-21 16:35
@cbjeukendrup @igorkorsukov @oktophonie @miiizen @DmitryArefiev I'm tagging you all cause this is quite important.

1. Yes, I can confirm that the current master is slower than 4.1 on this particular test file. It isn't really about flipping the slur: that is just a way like any other to trigger a relayout of the score. It is the layout process itself which has become slower (just look at the timing of Score::doLayoutRange from the profiler). What worries me a bit is that this file contains literally just notes, hairpins, and slurs, and none of these have been touched since 4.1 afaik. All the "big" engraving work we've done is about stuff that isn't even in this file. This makes me think that it may be the "big refactoring" process of libmscore that has somehow made things a bit slower, even though I wouldn't really know why: things have just been moved around, but should be functionally the same. This needs more investigation. One thing you could do @DmitryArefiev is try to test a few different builds in between 4.1 and now, and see if we can pinpoint a bit more precisely "at which point" things became slower.

2. About triggering the layout, I have found something crazy: changing one property of a single slur (such as flipping direction) triggers a layout OF THE ENTIRE SCORE, because of [this call](https://github.com/musescore/MuseScore/blob/master/src/engraving/dom/slurtie.cpp#L431C1-L431C24) to `triggerLayoutAll()`. This is absolute madness: we're laying out tens of pages because of the change in one slur. I suspect that `triggerLayoutAll` only exists because of legacy and I think it should DISAPPEAR OFF THE FACE OF THE EARTH. I mean, I can't think of a single instance where that would make any sense: the only situation where you should layout the entire score is when you open the file. If an element needs, for any reason, to trigger the layout further than its start/end points, that can be easily done without any need to layout the entire score. Replacing `triggerLayoutAll()` with the normal `triggerLayout()` in `SlurTie::setProperty` obviously fixes the problem, but a) I'd like to do it as part of a larger job where triggerLayoutAll is eliminated completely, b) it doesn't change the proevious point, i.e. that we should investigate why the layout has become slower.

**Comment by cbjeukendrup** [comment] 2023-11-21 23:03
I indeed sometimes think that the libmscore changes might have introduced some overhead; allocating/initialising layout data structs, sanity checks, `switch` instead of virtual methods (actually I'm not too sure what's faster), using setters and getters instead of directly using fields, having to construct a new `PointF` instance instead of changing just the x pos (`rxpos()`)...
I'm not experienced enough to tell whether these things can make a significant difference, but it all adds up and perhaps it's enough to be noticeable.

And of course, every added feature and most fixed bugs have _some_ effect on performance, even when implemented in the most efficient way possible.

**Comment by igorkorsukov** [comment] 2023-11-22 11:04
@mike-spa @cbjeukendrup I will find out, why the layout is running slower

**Comment by igorkorsukov** [comment] 2023-11-22 11:41
For information, on my laptop

4.1.1
```
ProjectActionsController::doOpenProject                     3683.201 ms       1                 3683.201 ms       
ProjectActionsController::loadProject                       3570.083 ms       1                 3570.083 ms       
NotationProject::load                                       3570.057 ms       1                 3570.057 ms       
NotationProject::doLoad                                     3569.705 ms       1                 3569.705 ms       
EngravingProject::loadMscz                                  2749.750 ms       1                 2749.750 ms       
MscLoader::loadMscz                                         2749.737 ms       1                 2749.737 ms       
Score::update                                               705.454 ms        1                 705.454 ms        
Score::doLayoutRange                                        705.448 ms        1                 705.448 ms        
PageLayout::collectPage                                     19.789 ms         35                692.613 ms        
SystemLayout::collectSystem                                 18.094 ms         37                669.490 ms  
```

4.2 (current master)
```
ProjectActionsController::doOpenProject                     2771.210 ms       1                 2771.210 ms       
ProjectActionsController::loadProject                       2677.428 ms       1                 2677.428 ms       
NotationProject::load                                       2677.408 ms       1                 2677.408 ms       
NotationProject::doLoad                                     2677.207 ms       1                 2677.207 ms       
EngravingProject::loadMscz                                  1579.950 ms       1                 1579.950 ms       
MscLoader::loadMscz                                         1579.947 ms       1                 1579.947 ms       
Score::update                                               989.103 ms        1                 989.103 ms        
Score::doLayoutRange                                        989.099 ms        1                 989.099 ms        
ScoreLayout::layoutRange                                    982.031 ms        1                 982.031 ms        
PageLayout::collectPage                                     27.508 ms         35                962.792 ms        
SystemLayout::collectSystem                                 25.324 ms         37                937.002 ms  
```

**Comment by mike-spa** [comment] 2023-11-22 13:05
[#18784](https://github.com/musescore/MuseScore/issues/18784) this one could be related too

**Comment by igorkorsukov** [comment] 2023-11-22 13:36
https://github.com/musescore/MuseScore/pull/20144 some optimisation

**Comment by DmitryArefiev** [comment] 2023-11-22 15:03
Fixed in #20141

**Comment by DmitryArefiev** [comment] 2023-11-22 15:04
@Gai-Luron Please try on your side (if any regressions occur)

**Closed** 2023-11-23 08:16 UTC
Labels: needs info, P1, regression, performance

**Comment by Gai-Luron** [comment] 2023-11-24 21:27
@DmitryArefiev
I tried it and It's seem to solve slur speed and no problem for now
Solve many slow actions 
**exemple:**
- Creating line trill speed
- Repeat Bar using "R" Key is improved
- Copy/Paste measures with notes

Thank you very much

**Comment by DmitryArefiev** [comment] 2023-11-27 14:05
> @DmitryArefiev I tried it and It's seem to solve slur speed and i notice no problem for now Solve many slow actions. it's pleasure **exemple:**
> 
>     * Creating line trill speed
> 
>     * Repeat Bar using "R" Key is improved, (Edit : Not all time, only at begin of score, much slower at the end of a large score)
> 
>     * Copy/Paste measures with notes (Edit : Not all time, only at begin of score, much slower at the end of a large score)
> 
> 
> Thank you very much

@Gai-Luron Oh that's great. Thanks for checking!

Kudos to @mike-spa
