### ISSUE TITLE
The Mixer menu closes with a big black box overlaying the score, if the piano menu is also active

### ISSUE THREAD

**Issue by fsgregs** [musescore/MuseScore#18894] opened 2023-08-02 21:19 UTC
### Issue type

General playback bug

### Bug description

Many folks turn on the Virtual Piano for a score via the "P" keyboard key, and size it so it is docked at the bottom of the score.  (see image 1).

![image](https://github.com/musescore/MuseScore/assets/133777637/28d6f7d5-bdd3-4983-b445-ba0c6e9e7398)

Now, if a user then activates the Mixer menu using the F10 keys, its menu will display over most of the the score and the piano menu both.  The top of the menu will be missing (that is another bug report), but t is not important here.  (see image 2)

![image](https://github.com/musescore/MuseScore/assets/133777637/ca74d3b8-6f4a-4b81-b899-80ed89256f28)

Now, close the Mixer menu using F10.  Notice now that the scene does not return to its previous state.  Instead, the Mixer menu has left behind a huge black box still covering most of the score, but now embedding the Piano menu in it. (see image 3).  To resume work on the score, a user has to locate the top of the big black box and drag it down so the original scene is restored and the Piano menu is back at the bottom.  The program has not properly returned the score to its position before F10 was pressed.  This bug did not occur in MS 3.6.

![image](https://github.com/musescore/MuseScore/assets/133777637/654f5973-1a22-4b20-8147-c119034d3719)

Repeating the above actions results in the same bug reappearing.  The fix you made is not saved.

### Steps to reproduce

1. Open any score
2. Turn on the Virtual Piano using the "P" key on the keyboard
3. Size the piano menu at the bottom of the score to your liking, docked in place
4. Now press the F10 key to turn on the Mixer menu.  It will appear covering most of the score and piano menu.  Its top line (Sound) will be missing (another bug report)
5. Press F10 again to turn off the Mixer menu.  You will be left with a big black box covering most of the score and incorporating the Piano menu.
6. Locate the top of the box and drag it down so that the scene returns to normal
7. Press F10 again as in step 4.  The Mixer menu will reappear but your fix did not take.  The entire problem will repeat.

### Screenshots/Screen recordings

Screenshots appear above

### MuseScore Version

4.1.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by oMrSmith** [comment] 2023-08-02 23:56
Seems like the window, containing the virtual piano, somehow resets, when closing the mixer... Maybe it would also be helpful if the the piano-window would never be higher than the piano itself, to avoid a waste of space by default.

**Comment by oktophonie** [comment] 2023-08-03 07:49
Duplicate of https://github.com/musescore/MuseScore/issues/17634 (your own issue).

**Closed by oktophonie** 2023-08-03 07:49 UTC
Labels: duplicate, regression_ms3
