### ISSUE TITLE
Dragging score items to palette stops working after using "More" option

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22821] opened 2024-05-14 13:02 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The ability to ctrl+shift+drag score items onto the palette stops working after clicking the "More" button on a palette, but can be restored by closing palette then restoring from View menu.

### Steps to reproduce

1. Create a new score, add a text element and change the text
2. Hold down Ctrl+Shift (cmd+shift on Mac) and drag it on to where the text items palette is, confirm that it shows the expected UX to indicate it can be dropped onto the palette, and that a new palette item can be created using the edited text
3. Now click the "More" button in the text items palette, then click away to dismiss again
4. Try step 2 again but note that it is no longer possible to drag items from the score into the palette
5. Close the palette, then reveal again with the View menu (or press F9)
6. Now try step 2 again and most likely it will work as before.
 

### MuseScore Version

4.3

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2024-05-14 13:34
Good work tracking this down, it's been a mystery for a long time!  I can confirm that the More button seems to be the culprit, but there is a little more to it.  It's not the act of *opening* the More section that triggers the bug, it's the act of *closing* it, but *only* if you close it by clicking outside of it - if you close it by clicking the More button again, all remains well.

**Comment by wizofaus** [comment] 2024-05-17 00:14
BTW there's another subtly-related issue, perhaps more a feature request, but I would think you should be able to update custom palette items by dragging on top of them, but currently it causes the existing one to move out of the way! (which I understand is useful if you did want to insert a new one, so I suppose it might need a different key combination or something. Though for me, I'd be happy with having insert be triggered by dragging close to the border between two existing palette items). 

Either way I'm happy to look into this bug if this code isn't being worked on by anyone else @cbjeukendrup

**Comment by cbjeukendrup** [comment] 2024-05-17 13:49
@wizofaus I think that would indeed deserve a separate feature request. 

@mathesoncalum Were you planning to work on this, or can @wizofaus take this one?

**Comment by mathesoncalum** [comment] 2024-05-17 13:58
Nope this is my first time seeing this - go ahead @wizofaus!

**Comment by wizofaus** [comment] 2024-05-31 02:14
Definitely something in the QML code, I can see how if it somehow believes the More popup is still open, this would happen but I can't for the life me to figure out why it believes this or how to fix it. I find QML very very awkward to work with, I can't debug it at all, or even get any diagnostic output using console.log or alert or anything. So I might just have to leave this with someone that knows their way around QML and/or QtCreator. @mathesoncalum

**Comment by wizofaus** [comment] 2024-05-31 02:42
Took way too long to figure this out, I just don't know how to debug QML code using Visual Studio and QtCreator is a mystery to me (when I tried using it it was unusably slow at recompiling for a start).

**Closed** 2024-06-06 07:02 UTC
Labels: P2, regression_ms3, UX/interaction
