### ISSUE TITLE
Staff spacers are invisible

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20088] opened 2023-11-18 22:47 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

If you apply any of the staff spacers from the Layout palette, they are invisible. Initially you can see just the end handle, but after exiting the handle they cannot be located again.

### Steps to reproduce

1. Click on an initial system measure
2. Click on a staff spacer in the Layout palette

**Actual Result**: Only the end handle is visible
**Expected result:** The whole spacer should be visible at all times.

3. After adjusting the handle, exit

**Actual Result**: The whole spacer becomes invisible and can't be located
**Expected result:** The whole spacer should be visible at all times.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233220304, revision: github-musescore-musescore-53d463f

### Regression

Yes. This worked in 4.1.1.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by cbjeukendrup** [comment] 2023-11-18 23:10
Duplicate of https://github.com/musescore/MuseScore/issues/19963 ?

**Closed** 2023-11-19 01:02 UTC
Labels: duplicate
