### ISSUE TITLE
Grace note spacing issues

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#24728] opened 2024-09-15 00:15 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Load the attached score
2. Note that the grace notes don't quite line up between Voice 1 and 2 (a bit weird, but ok...)
3. Select the very first grace in V1 and shift it down to an E
4. Expected: grace notes should still be aligned sensibly
5. Actual: V2 grace notes are shown all to the left of the V1 grace notes

### Supporting files, videos and screenshots

https://musescore.com/user/7209246/scores/20644738/s/XKuEiJ

After move:

![image](https://github.com/user-attachments/assets/2fe37e66-7149-44b5-8fb7-f3acb9d87cc0)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

Seems only ledger lines are used to determine horizontal spacing of grace notes - UNLESS one of them shares a pitch with a primary note later in the measure, even in a different voice.
For reference re ledger lines (and in this case even across different staves):

![image](https://github.com/user-attachments/assets/6b0597fc-6786-4f2b-875e-4aab66963636)

 
### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-09-15 05:53
Duplicate of https://github.com/musescore/MuseScore/issues/15326

**Closed by oktophonie** 2024-09-15 05:53 UTC
Labels: engraving

**Comment by wizofaus** [comment] 2024-09-15 08:39
Actually that link was wrong too, anyway good to know it's a known issue even if it's a bit surprising it's been deprioritised that long.
