### ISSUE TITLE
Windows Master - Opening second score is zoomed in

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19542] opened 2023-09-27 17:01 UTC
### Issue type

UI bug

### Bug description

In the current master, when I have a score open and I open another score, the second score is zoomed in.

### Steps to reproduce

1. Open a score
2. Open another score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/39c1af1b-a8bd-4c11-9d7f-dced48c6dbce

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232700304, revision: github-musescore-musescore-bc08cec

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-09-29 13:07
Duplicate of https://github.com/musescore/MuseScore/issues/15591

**Closed** 2023-09-29 13:07 UTC
Labels: P2, UI, regression
