### ISSUE TITLE
[MU4 Issue] Icons overlapping

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#7624] opened 2021-03-04 19:42 UTC
**Describe the bug**
The ‘wrench’ icon on the very right hand side is overlapping another icon

**To Reproduce**
1. Start drag "Note input bar" dock panel
2. See overlapping

**Expected behavior**
Icons should be placed sequentially, without overlapping 

**Screenshots**
![image](https://user-images.githubusercontent.com/57620349/110020304-14754a80-7d32-11eb-81b1-b7b3fc5c0c67.png)
https://user-images.githubusercontent.com/57620349/110020488-45ee1600-7d32-11eb-9ccb-ffb6942bda33.mov

**Desktop (please complete the following information):**
 - OS: Win10 x64

**Comment by vshalkevich** [comment] 2021-03-23 10:56
closed as duplicate of #7775

**Closed** 2021-03-23 10:57 UTC
