### ISSUE TITLE
Invisible cresc. line diappears when the start text is out of view

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#20736] opened 2023-12-28 03:25 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

1. Add cresc. (or dim.) line to the score
2. **Uncheck the "Show line" checkbox**
3. Scroll until the cresc. text is out of view
4. The line disappears

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139459177/7aae9e6b-3180-43d1-a6b1-140b0b911afd

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-233610505, revision: github-musescore-musescore-a84a215

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

This is similar to #20560, but only occurs when the line is set to invisible and has not been fixed in the latest 4.2.1 nightly.

**Comment by oktophonie** [comment] 2023-12-29 15:16
Duplicate of https://github.com/musescore/MuseScore/issues/20661

**Closed by oktophonie** 2023-12-29 15:16 UTC
Labels: needs info, regression, engraving
