### ISSUE TITLE
Playback is faster and has electrical sounds

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#17101] opened 2023-04-01 09:46 UTC
### Issue type

General playback bug

### Bug description

I don't know how the bug happened. At first I thought my headphones or sound card broke since the playback had the sound of electrical interference, but then I checked other scores and listened to YouTube with no issues. After closing the score and reloading it it went back to normal. Listen to the screen recording.

### Steps to reproduce

I don't know.

### Screenshots/Screen recordings

warning: sounds terrible. lower your volume

https://user-images.githubusercontent.com/120669196/229278744-0f41dc20-320d-47b4-8258-ba83efe6fcc2.mp4

### MuseScore Version

4.0.2-230651553

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

**Comment by zacjansheski** [comment] 2023-08-24 20:15
Although that is concerning, no other similar reports have come in and we are unable to reproduce.  Closing.

**Closed by zacjansheski** 2023-08-24 20:15 UTC
Labels: playback
