### ISSUE TITLE
[MU4 Issue] Lyrics - unable to delete hyphen; regression from MU3

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13200] opened 2022-09-06 14:02 UTC
**Describe the bug**
It is not possible to delete hyphen in Lyrics

**To Reproduce**
1. Enter "lyrics mode" (Ctrl + L)
2. Write some text
3. Create hyphen (-)
4. Try to remove it (Shift+space; space) or some other way

**Expected behavior**
When going to previous syllabe with hyphen, pressing "space" should replace "hyphen" (-) with "next sylabe" ( )

**Screenshots**
MU4 - bug:

https://user-images.githubusercontent.com/1646034/188654897-f8a0c39a-19ff-4601-90f6-2f3cf32300f6.mp4

MU3 - Works:

https://user-images.githubusercontent.com/1646034/188655017-f2b9850c-2aa8-408d-9762-791d77ca6509.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Regression from MU3

**Comment by wizofaus** [comment] 2022-09-07 01:24
Would definitely expect backspace to work, not sure about space though?

**Comment by wizofaus** [comment] 2022-09-07 01:59
Ok, so the problem here is that both "right arrow" AND "space" map to "next-text-element", so there's no way of distinguishing he two.

**Comment by MarcSabatella** [comment] 2022-10-16 16:41
@Tantacrul another regression that hasn't yet been prioritized.  To be clear: the expectation is that if you've entered "see-saw" as two syllables with a hyphen, then go back to "see" and hit Space, this is supposed to remove the hyphen.  The very clumsy workaround now is to leave lyrics edit mode and delete the "see", then re-add it.

The idea of using backspace on the "saw" to do the same is interesting, but it's not something that has existed before.

Not sure if changing the command labels as per the linked PR from @wizofaus is still viable, and I have no opinion on what the command should be called.  But one way or another, this would be an important fix.

**Comment by Tantacrul** [comment] 2022-10-16 16:56
Thanks @MarcSabatella / @sammik !

**Comment by cbjeukendrup** [comment] 2022-10-16 20:02
@Tantacrul there is already a PR from Wizofaus: #13216. I just reviewed it, it's almost ready to be merged.

**Comment by MarcSabatella** [comment] 2022-10-29 18:49
@Tantacrul - aside from making vocal scores painful in general, this would be an important accessibility fix, since there is no obvious feedback that the space bar has failed to remove the hyphen,

**Comment by DmitryArefiev** [comment] 2022-12-02 15:24
Fixed in #14892

**Closed** 2022-12-02 16:08 UTC
Labels: P2
