### ISSUE TITLE
[MU4 Issue] "Restore session?" dialog position is not center of screen

### ISSUE THREAD

**Issue by schoettl** [musescore/MuseScore#11699] opened 2022-05-19 18:37 UTC
**Describe the bug**
The "restore session?" dialog after a MuseScore crash seems to be centered around the screen position 0,0. That is, only part of the right "Yes" button is visible. Other dialogs like Help/About and Open/Save dialogs are centered correctly.

**To Reproduce**
1. Open MuseScore and open a score file
2. Let MuseScore crash somehow (or kill the process with `killall -9 musescore` or so)
3. Check the position of the restore dialog.

**Expected behavior**
Should be centered on screen.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1301843/169375269-968abd8c-5a95-4a0b-841d-fee135f93484.png)
This shows the top-left corner of my left-most primary X screen.

**Platform information**
- Arch Linux with Xmonad window manager. All dialogs are floating correctly (not tiled).
- I have multiple screens connected! Cannot test currently how it works with only one
- Latest dev version from today.

**Comment by Tantacrul** [comment] 2022-05-19 19:02
I'm marking this as a P3 for now because with multiple windows, it's a solvable problem (but definitely not desirable). However, if anyone can reproduce this for other cases, I'll raise the P level.

Thanks! Nice catch :)

**Comment by cbjeukendrup** [comment] 2022-05-23 08:48
@schoettl I'm unable to reproduce this issue myself, but it should probably be fixed in #11720. Could you please try the test builds from that PR? (They should be ready in 20 minutes from now.)

**Comment by schoettl** [comment] 2022-05-23 09:09
Thanks for your efforts!

PS: I checked out our PR and built myself. See PR.

**Closed** 2022-07-13 07:59 UTC
Labels: P3, community

**Comment by cbjeukendrup** [comment] 2022-09-29 22:04
@schoettl This issue was actually not really fixed, was it?

Anyway, I've a second attempt here: #13542
Would be nice if you could check it out!
