### ISSUE TITLE
Select individual notes in chords

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#24302] opened 2024-08-30 01:24 UTC
### Your idea

An addition to the Select or Select > More... UI to select only the top, 2nd, 4rd, etc. or bottom notes in a chord.

### Problem to be solved

Relatively often I need to act on only some of the notes in a chord, and at present it's only available via a QML plugin or clicking each note individually.

### Prior art

Sibelius has a fairly extensive system for selecting notes in chords, or individual players.

### Additional context

Migrated from https://musescore.org/en/node/309579.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by TimBomBom** [comment] 2024-08-30 04:03
You can do this already I believe by holding Alt + up/down keys

**Comment by oktophonie** [comment] 2024-08-30 05:11
Duplicate of https://github.com/musescore/MuseScore/issues/21091, will be addressed by https://github.com/musescore/MuseScore/issues/23817

**Closed by oktophonie** 2024-08-30 05:11 UTC
Labels: feature request

**Comment by iainhallam** [comment] 2024-08-30 09:57
How did I miss that in my searching of issues?!

**Comment by oktophonie** [comment] 2024-08-30 10:00
Easily done, I manage it all the time!
