### ISSUE TITLE
When entering lyrics, hyphen key does not work with certain keyboard layouts

### ISSUE THREAD

**Issue by PaperClipsAndTrombones** [musescore/MuseScore#21387] opened 2024-02-06 23:38 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

I use a custom keyboard layout called French Canadian Dvorak whose files can be found [here](https://sites.google.com/site/dvorakcanadienfrancais). When entering lyrics with this layout, the hyphen key does not work at all. Interestingly, the underscore key, which is on the same key as hyphen but shifted, works perfectly fine. I works fine with regular english Dvorak. I don't know if any other layouts are affected.

### Steps to reproduce

1. Use an affected keyboard layout (eg. French Canadian Dvorak)
2. Enter lyrics mode
3. Try to use the hyphen key

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment] 2024-02-07 08:58
Duplicate of #16314

**Closed** 2024-02-09 14:39 UTC
Labels: regression_ms3, UX/interaction
