### ISSUE TITLE
[MU4 Issue] Multi-stave system notes playing in one stave prevent them from being played in another stave

### ISSUE THREAD

**Issue by akberg** [musescore/MuseScore#15776] opened 2023-01-09 13:13 UTC
**Describe the bug**
Unsure if it is a bug or a feature, when a note is being played but is already playing in another connected stave, it is ignored. Suspecting a new MIDI ON command is ignored when the note is already on, when actually the note should be quickly turned off and back on to restart the envelope. 

**To Reproduce**
1. Create e.g. a piano score like one of the below screenshots.
2. Play

**Expected behavior**
Expected the all the notes to be played (as was in MS3), the bass line arpeggio in example 1, the tris and the the accented arpeggio in example 2.

**Screenshots**
Example 1, minimal example:
![minimal example](https://user-images.githubusercontent.com/25877966/211313200-46dfc99d-7185-4412-8b79-06d3909b6c3f.png)
Example 2, real-world example:
![real-world example](https://user-images.githubusercontent.com/25877966/211314429-d2930575-9ad2-4921-aad0-d24a48941a7b.png)

**Platform information**
 - OS: Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

**Additional context**
Apologies if this issue should preferably be reported on musescore.org, but the login doesn't seem to be working for the last couple of weeks.

**Comment by cbjeukendrup** [comment] 2023-01-09 13:39
Looks like a duplicate of https://github.com/musescore/MuseScore/issues/15306. Thanks for reporting though!

**Closed by cbjeukendrup** 2023-01-09 13:39 UTC

**Comment by akberg** [comment] 2023-01-09 14:45
Right, sorry, didn't notice that one while searching. Keep it up!
