### ISSUE TITLE
Part extraction- all violin parts are the same- not extracting the different parts

### ISSUE THREAD

**Issue by UHE1** [musescore/MuseScore#17240] opened 2023-04-14 13:41 UTC
### Issue type

Other type of issue

### Bug description

There are a few pieces that when I try to extract different parts to download and print- it gives duplicates of one part. Is this an error that can be fixed on the end of the person that uploaded the files (the people seem to be aware of the issue and respond to downloaders with instruction to just download the part as usual- not seeming to understand that it is not downloading correctly as it does on most other pieces)? Or is it a musescore system error? other?

For example:
1. In this piece- when printing or downloading the violin parts- all three links pull up the violin 1 part (not violin 2 or violin 3). https://musescore.com/user/125171/scores/5078866

2. In this piece- when printing or downloading the violin parts- both links open the violin 1 part (not violin 2). https://musescore.com/user/2425171/scores/3806881#

Thank you for your help!

### Steps to reproduce

1. Go to https://musescore.com/user/125171/scores/5078866
2. Click "download"
3. Click "PDF"
4. Click the 2nd or 3rd "Violin" that is listed.  It should pull up the 2nd or 3rd line of the score respectively (2nd or 3rd violin)- but all three links pull up the top line of the score

### MuseScore Version

2023

### Regression

I don't know

### Operating system

Mac ventura 13.1

### Additional context

This extraction works fine in most other songs- just not on the link above or this link: https://musescore.com/user/2425171/scores/3806881#

**Comment by bkunda** [comment] 2023-05-09 14:35
I think I've been able to reproduce this one now. 
My investigation has led me to the conclusion that musescore.com cannot parse individual parts if they all have the same instrument name. 

To reproduce: 

1. Create a new score with multiple different instruments (I used the string quartet template)
2. Change the instrument names in stave/part properties so that at least two of the staves have the same instrument name
3. Publish to musescore.com
4. Download the PDFs of the parts: those with the same instrument name will show the same content (in my case, I had renamed the violins and viola all "violin", and all extracted with the content from violin 1). 

@shoogle if this is indeed what's happening, I wonder if it is a musescore.com issue, or if there is anything we can do about it on our end? Your input on this would be helpful!

**Comment by shoogle** [comment] 2023-05-09 23:28
The problem seems to be that the website displays instrument names rather than part names in the PDF Download dialog. Also, it probably saves the part PDFs with the instrument name instead of the part name, hence when multiple instruments have the same name only one part's PDF is actually saved.

To reproduce:

1. Download file [TestPartNames.mscz.zip](https://github.com/musescore/MuseScore/files/11436726/TestPartNames.mscz.zip), which contains:
   - 3 instruments (all called 'Flute')
   - 3 parts/excerpts (called 'Part 1', 'Part 2' and 'Part 3')
2. Rename the file to remove the `.zip` extension.
3. Upload it to MuseScore.com via any method.
4. On the online score page, click Download > PDF.

You'll see this dialog:

![image](https://github.com/musescore/MuseScore/assets/11011881/94bfbb93-00d9-4b4c-a50c-193bf3940842)

The PDF downloaded for each flute is identical.

Instead, the parts should be labelled 'Part 1', 'Part 2', 'Part 3' to match what they are called in the Parts dialog in MuseScore 4, and the PDF downloaded should be different for each of them.

**Developers:** The correct part names are available via the `--score-parts` and `--score-parts-pdf` command line options.

```Bash
mscore --score-parts-pdf TestPartNames.mscz | sed -E 's|"[A-Za-z0-9+/]{100,}=*"|"BASE64DATA"|g' | jq
```

```JSON
{
  "parts": [
    "Part 1",
    "Part 2",
    "Part 3"
  ],
  "partsBin": [
    "BASE64DATA",
    "BASE64DATA",
    "BASE64DATA"
  ],
  "score": "./TestPartNames.pdf",
  "scoreBin": "BASE64DATA",
  "scoreFullBin": "BASE64DATA",
  "scoreFullPostfix": "-Score_and_parts.pdf"
}
```

I'll pass this on to the web team.

**Comment by bkunda** [comment] 2023-05-10 10:54
As this is a musescore.com issue, and not a MuseScore app issue, I think we can close this for now (especially as @shoogle is raising the issue with the web team).

**Closed by bkunda** 2023-05-10 10:54 UTC
Labels: needs review
