### ISSUE TITLE
Breaks between pedal markings no longer work

### ISSUE THREAD

**Issue by MqcCheeze** [musescore/MuseScore#24318] opened 2024-08-30 11:44 UTC
### Issue type

Import/export issue

### Description with steps to reproduce

After the 4.4 update on Musescore, pedal markings are aweful to edit after exporting to MIDI, you can no longer select all the pedal events and instantly edit their delay. Yes you can shorten the end of the previous pedal event to get a similar effect but it now causes me to have to go through every single one individually. I do not want to do this on a 30 minute MIDI. I'm going to have to now open the mcsz in Musescore 3 evo, export to midi, copy the pedal data over to the midi just to get better pedalling.

1. Create a piece with pedal markings (example below)
2. Export to midi
3. Try to increase the gap between pedal in a DAW or other software to better emulate stepping off and back on
4. You now have to manually create a new event instead of modifying the time of which the pedal is off and on

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/ef70653d-65da-4fe5-8ec6-5d82f346961e)

https://github.com/user-attachments/assets/13bb809a-8cc2-4a91-acad-02b3be97e1ca

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-30 11:45
Duplicate of https://github.com/musescore/MuseScore/issues/24290; already fixed

**Comment by MqcCheeze** [comment] 2024-08-30 11:48
I'm sure this is a side affect along side this issue here

https://github.com/musescore/MuseScore/issues/24273

**Comment by RomanPudashkin** [comment] 2024-08-30 16:27
@MqcCheeze unfortunately, these are 2 independent bugs. But here's the good news: I have a fix. Please test it: https://github.com/musescore/MuseScore/pull/24328

**Comment by MqcCheeze** [comment] 2024-08-30 16:57
@RomanPudashkin is there a build of it? or do I have to download the source and run it through there?

**Comment by RomanPudashkin** [comment] 2024-08-30 17:14
@MqcCheeze you can download it here:
https://github.com/musescore/MuseScore/actions/runs/10635993999/artifacts/1875631032

**Comment by MqcCheeze** [comment] 2024-08-31 10:37
@RomanPudashkin thank you, it works now, I'll use this for now, will the fix be added into the 4.4.1 update officially or a later version?

**Comment by RomanPudashkin** [comment] 2024-08-31 15:40
Yes, this issue will be fixed in 4.4.1

**Closed by RomanPudashkin** 2024-08-31 15:40 UTC
Labels: regression MS4, MIDI
