### ISSUE TITLE
Niente dynamic doesn't playback at all

### ISSUE THREAD

**Issue by TobyTwo32** [musescore/MuseScore#23774] opened 2024-07-25 19:35 UTC
### Issue type

General playback bug

### Description with steps to reproduce

This happens both in premium libraries and free musesounds.

1. Open any score either solo, orchestral
2. Choose either paid premium libraries or free muse sounds
3. Write from niente and/or to niente.
4. plays as mf

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/d4c5a491-8e71-44d1-81fe-3fc549286ae8

[Niente playback.zip](https://github.com/user-attachments/files/16382938/Niente.playback.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Dima-S-Jr** [comment] 2024-08-18 06:27
Isn't this a duplicate of #21096?

**Closed** 2024-08-21 08:48 UTC
Labels: duplicate
