### ISSUE TITLE
Large Time Signature

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25461] opened 2024-11-07 23:07 UTC
### Your idea

It is necessary, when creating a score for a conductor, to provide them with the option of a large time signature for greater visibility.

### Problem to be solved

Musescore 4 cannot do this. There is a plugin, but this is a request for a dedicated feature.

### Additional context

There are two types of large time signature, shown below: simple large, and "Hollywood Style", where it extends down the whole choir. It would be good to offer both options.
![image](https://github.com/user-attachments/assets/fb60e3ec-75e5-44dd-914e-0f83c246cd55)
![image](https://github.com/user-attachments/assets/7f1ffdf4-10ef-43fe-bcd5-1090e0b7d2c0)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-11-08 07:41
Duplicate of https://github.com/musescore/MuseScore/issues/20480

**Closed by oktophonie** 2024-11-08 07:41 UTC
Labels: feature request
