### ISSUE TITLE
Playback in the style of "mute"

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#20615] opened 2023-12-21 00:38 UTC
### Issue type

Muse Sounds bug

### Bug description

"Muse Sound" does not support playback in the "mute" style

### Steps to reproduce

-

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

Windows 11

**Comment by bkunda** [comment] 2023-12-21 10:27
@Dima12357 can you please be a bit more specific with your description? 
Which instruments and mute elements in particular are you referring to? 
Please note, we already have #14191 open in relation to brass instruments.

**Comment by Dima12357** [comment] 2023-12-21 15:53
> @Dima12357 can you please be a bit more specific with your description? Which instruments and mute elements in particular are you referring to? Please note, we already have #14191 open in relation to brass instruments.

None of the Muse sounds can sound like "mute". Only MS Basic sounds can sound like "mute". And then there is some nuance. In strings, "mute" sounds like pizzicato, and this applies only to MS Basic. Muse Sound does not change the sound to "mute" in any way.

**Comment by MarcSabatella** [comment] 2023-12-21 19:39
What does Diagnostic / Muse Sampler / Check Muse Sampler report?  If it’s 0.5 or greater, mutes should work fine with trumpet, horn, and trombone.

**Comment by Dima12357** [comment] 2023-12-21 21:38
> What does Diagnostic / Muse Sampler / Check Muse Sampler report? If it’s 0.5 or greater, mutes should work fine with trumpet, horn, and trombone. If you find otherwise, please ZIP and attach your score and say which notes are not playing as they should for you.
> 
> If your Muse Sampler is not 0.5 or later, please update it with Muse Hub.

Yes, I updated the library and the brass started playing as "mute". But for some reason, the trumpets sound too quiet, and the violins still do not see and do not sound like "mute".

**Comment by MarcSabatella** [comment] 2023-12-22 03:00
Indeed, a few others feel the muted brass sounds are, subjectively speaking, quieter than they expect.  It's not clear this is a bug though - seems more of a difference of opinion.  And in any case, it's not what your issue says - it says the sounds don't work at all.

It's true that mute isn't currently supported for all instruments; just the instruments it was designed to work for.  So, not a bug so much as a feature request, for mute to eventually be supported for more instruments.

For strings, mutes aren't even remotely similar to pizzicato - it's a device that just dampens the vibration somewhat and creates a slightly less resonant sound.  See for instance [this video](https://www.youtube.com/watch?v=BC-GJ0wOBhU) to learn what violin mutes are and what they sound like.

**Comment by cbjeukendrup** [comment] 2024-12-05 00:02
Closing; it looks like either this may have been fully resolved already by now, or, if not, it should be reported via Muse Hub itself.

**Closed by cbjeukendrup** 2024-12-05 00:02 UTC
Labels: needs info, muse sounds
