### ISSUE TITLE
Bad arpeggio spacing with accidentals

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#22004] opened 2024-03-21 00:35 UTC
### Issue type

Choose option...

### Bug description

Sometimes, accidentals will push an arpeggio so far left that it all but collides with the previous note. The issue occurs if there are at least 2-5 accidentals on the arpeggiated chord, depending on how big the original spacing is. The spacing algorithm should be adjusted to give more left-hand space to arpeggios in these scenarios.

### Steps to reproduce

Input any note, then input a chord directly following that note, such that at least two accidentals are visible on the chord. Add any arpeggio from the "Arpeggios & glissandi" palette. The arpeggio now collides with the note in front.

### Screenshots/Screen recordings

Example of the spacing in MS4:
![image](https://github.com/musescore/MuseScore/assets/73259774/e08078d5-d2ee-467f-b8a2-d388d7e0dabe)
The arpeggio spacing was fine in MS3:
![image](https://github.com/musescore/MuseScore/assets/73259774/2f572aa8-d5bc-427c-9277-918acffd7f01)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

The arpeggio in measure 9 of the attached score collides with the stem of the previous note; the spacing algorithm should adjust the leading space to prevent this.
[3-20-24.zip](https://github.com/musescore/MuseScore/files/14676175/3-20-24.zip)

**Comment by bluebear94** [comment] 2024-04-15 02:44
This at least seems to look less bad on the current `master` (ca6e8a8):

![image](https://github.com/musescore/MuseScore/assets/2975203/1e2338ae-adb1-4eca-8db8-c1c4e6ba2cd6)

**Comment by oktophonie** [comment] 2024-05-14 14:50
Duplicate of https://github.com/musescore/MuseScore/issues/21145 (and now fixed)

**Closed by oktophonie** 2024-05-14 14:50 UTC
Labels: P2, engraving, regression_ms3
