### ISSUE TITLE
[MU4 ISSUE] ENGRAVING ISSUE: Clef and Time Signature Intersect When Added by Clicking the Palette Items

### ISSUE THREAD

**Issue by ludovikbechard** [musescore/MuseScore#14644] opened 2022-11-21 22:50 UTC
**Describe the bug**
Changing the clef **after** adding a time signature cause them to intersect.

To Reproduce

1. Create a new score;
2. Select the rest in bar 2;
3. Add a new time signature to bar 2 by clicking it in the palette (dragging it does not seem to cause the issue);
4. Select the deselected rest in bar 2;
5. Add a new clef by clicking it in the palette.

PS: The order of operation is important to generate the bug.

Expected behavior
The clef and the time signature should not intersect.

Exceptions
None

Platform information

Linux Ubuntu 22.04 (With XFCE)

Additional context
This is a regression and should (probably) be addressed before 4.0

**Comment by cbjeukendrup** [comment] 2022-11-21 23:40
This looks very much like a duplicate of #14610. Could you please check that and close this issue if it's indeed a duplicate? Thanks!

**Comment by oktophonie** [comment] 2022-11-22 07:28
This is indeed a duplicate, but thanks for the report!

**Closed by oktophonie** 2022-11-22 07:28 UTC

**Comment by ludovikbechard** [comment] 2022-11-22 15:33
Sorry for duplicating: the original issue totally went under my radar!
