### ISSUE TITLE
Musescore crashes (exit suddenly and unexpectedly) when earphone plugging and unplugging

### ISSUE THREAD

**Issue by 0x391F** [musescore/MuseScore#22142] opened 2024-04-02 08:25 UTC
### Issue type

Crash or freeze

### Steps to reproduce

Note: on my compter, earphone is the only audio output device. 

Case A:
1. Start Musescore. 
2. Plugging and unplugging earphone, repeat several times. 
3. Bug happens. 

Case B:
1. Make sure earphone is unplugged. 
2. Launch MuseScore. 
3. Plug the earphone. 
4. Bug happens. 

### MuseScore Version

4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10 Enterprise LTSC 2021 x64 (21H2)

**Comment by zacjansheski** [comment] 2024-04-02 12:45
Duplicate of https://github.com/musescore/MuseScore/issues/17836

**Closed by zacjansheski** 2024-04-02 12:45 UTC
Labels: crash
