### ISSUE TITLE
[MU4 Issue] Instrument with more than two staves can't have automatic bracing and barline connecting over all staves

### ISSUE THREAD

**Issue by Howard-C** [musescore/MuseScore#10034] opened 2021-12-10 04:41 UTC
**Describe the bug**
Instrument with more than two staves can't have automatic bracing and barline connecting over all staves.

**To Reproduce**
1. Create a new score and add a piano. Add a third stave to the piano. Still, only 2 staves are braced and the barlines connected.

**Expected behavior**
All 3 staves should be braced and have their barlines connected.

**Screenshots**
![image](https://user-images.githubusercontent.com/46259489/145518246-09c01980-1004-483e-9a20-fc49b0936a35.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by oktophonie** [comment] 2021-12-10 07:06
For the organ this is the usual standard bracketing: two manuals staves bracketed and barred though, pedal stave separate.

**Comment by Howard-C** [comment] 2021-12-10 07:14
> For the organ this is the usual standard bracketing: two manuals staves bracketed and barred though, pedal stave separate.

I see, does piano or others with more than two staves also have this style of bracketing?

**Comment by oktophonie** [comment] 2021-12-10 07:19
No, piano (etc.) on more than two staves would be barred/bracketed together, though I don't think there's any instrument you can create in the New Score Wizard that has 3+ staves initially (or is there?)

**Comment by Howard-C** [comment] 2021-12-10 08:05
> No, piano (etc.) on more than two staves would be barred/bracketed together, though I don't think there's any instrument you can create in the New Score Wizard that has 3+ staves initially (or is there?)

No, but if I add a third stave later in the Instruments panel, shouldn't the stave be grouped together as well? If I add extra staves to say saxophone, the staves would be grouped together by both a normal bracket and a square bracket. It seems the issue only exists with curly brackets, or braces.

**Comment by oktophonie** [comment] 2021-12-10 08:06
You're right, if you add a third stave the barlines and brace should extend to the new stave.

**Comment by njvdberg** [comment] 2021-12-10 13:13
Same issue as #9210.

**Comment by njvdberg** [comment] 2022-01-20 20:39
Unfortunately this isn't the same issue as #9210. Will be solved by another PR.

**Comment by njvdberg** [comment] 2022-01-20 20:50
@oktophonie An organ has three staves from which the upper two are grouped by a brace:
![Screenshot_20220120_214520](https://user-images.githubusercontent.com/48352523/150419411-694710d2-c61e-43e3-8287-408f93d04125.png)
How about adding a staff, should the upper n-1 staves be grouped by a brace, like
![Screenshot_20220120_214720](https://user-images.githubusercontent.com/48352523/150419683-9fdbc33d-beb6-4631-b648-4686bb0937a7.png)
Or keep just the brace at was (in this case, only the 2 upper staves):
![Screenshot_20220120_214834](https://user-images.githubusercontent.com/48352523/150419863-bfe7f2d2-0dee-4b4a-a2c8-c09b408dbc9c.png)

Or even worse, that to do when one staves is removed, what braces must be generated in these cases?

**Comment by oktophonie** [comment] 2022-01-21 11:13
Probably we can't have logic to cover every eventuality (that is, the user will likely need to manually adjust in some cases.)
I'd say it's a safe assumption that there will be only one pedal stave, so the upper n-1 staves should have a brace and be barred through. In other words, there should be only one unbraced stave at the bottom for pedals (assuming one is present to begin with) when extra staves are added.

When staves are removed, well, if we know that the user specifically deletes the bottom (pedal) stave, then we should do exactly that, and all remaining staves will then share a brace/barlines. If any other stave is removed, we adjust the braces/barlines so that the bottom one remains unbraced.

Organists may want to weigh in with examples to the contrary!

**Comment by jeetee** [comment] 2022-01-21 12:20
Definitely go with brace n-1 if you have to decide something.
I have not ever come across an organ with more than 1 pedal board, nor would there be a need for more than one pedal stave (oh the logistic horror in imagining playing such a thing!).

More than two staves for the manuals isn't common, but not unused either. I've come across up to 4 staves for the manuals occasionally, in which case they share a single brace.
For the 3-stave manual notation you see both the common brace as well as the "soloist" notation:
![image](https://user-images.githubusercontent.com/895153/150525207-bd4cab47-e71b-49ff-b202-e0bd881b95ad.png)
Where the triple braced notation is more used as a method used for successive registration jumps without the need to write them as instructions every time, the soloist notation then is used for... well, integrating a "solo" (usually with one of the reed pipe stops such as Krumhorn/Oboe/Clarinet) which may or may not be performed by the organist or an actual different instrumentalist.

**Comment by njvdberg** [comment] 2022-02-10 16:20
Solved by PR #10526

**Comment by njvdberg** [comment] 2022-02-11 20:26
@DmitryArefiev Oops, I guess this is "n-1"/"n" discussion above which I missed in the implementation :worried:
I'll update #10526 for this.

**Comment by njvdberg** [comment] 2022-02-12 19:14
@DmitryArefiev I had a closer look and for the piano you are right. But what should be the expected behavior for the organ.
The issue is, added staves are always added as the last staff. For the organ this means, unless the pedal staff is delete by the user already, adding an extra pedal staff which is most unlikely what a user wants.

Now I'm not sure how to solve this since there are several options:
1. Add the newly created staff at the brace. This works fine for all non organ keyboards. Also , the behavior of the organs will be different from other instruments with multiple staves (like the piano).
2. Change the behavior of adding staves so, in case of an instrument which has grouped staves by a brace, add the staff at the end of the braced group. For the organ this means the staff is not created as the last staff, below the pedal, but before the first pedal staff. In this case the new staff can easily be added in the braced group.
3. Instead of adding the new staff at the end of the instrument, added it **before** the selected staff in case a staff is selected and at the **bottom** if no staff is selected. Now the user has full control where the new staff is added at an simple algorithm can decide whether the new staff should grouped or not.
4. Leave the behavior as it is now and let the user extend the brace and bar line spans after added a new staff.

@oktophonie Do you have any idea what the best solution should be?

**Comment by oktophonie** [comment] 2022-02-12 19:23
4 would be easiest I suppose ;)

3 sounds nice and provides more flexibility for this procedure in general, though I worry that it might cause behaviour that feels unpredictable. I imagine @Tantacrul will have a view here. I wonder if it would be better for the new stave to always appear _after_ the selected stave(s), or if nothing is selected (or the whole instrument is selected) then it is added at the bottom. That doesn't give an easy way to add a stave to the _top_ of the group, but one could always add one below the top stave then drag it up.

**Comment by Tantacrul** [comment] 2022-02-12 20:53
I can't immediately think why it would be bad to automatically place a newly created stave **above** a selected stave but I can't imagine if it would cause weird issues elsewhere... or just be quite undiscoverable. I can't help but think that no matter which way you do it, loads of folk would still end up dragging them to where they need to be.

That said, I think this proposal (mentioned above) is a no-brainer:

- If the selected instrument consists of more than one stave which are both within a brace (and there are no staves that are outside of the brace (eg. piano)), then newly added staves should also appear inside the brace and the barlines should be extended accordingly. It doesn't solve the organ problem but it would be much better for piano, which is our most popular instrument. It would also avoid people having to figure out how to extend barlines, which is scary!

- I also like the suggestion that if the user selects a stave which is already within a brace and then creates a new stave, it will also be braced (whether or not it appears above or below). Then the same would be true for staves that aren't within a brace.

- And then we could possibly apply some unique logic for certain edge cases? Or is that just hackery?

**Comment by Tantacrul** [comment] 2022-02-12 20:57
@njvdberg's option 3 does not seem weird to me. I think that would feel OK. can't be sure... but it'd be worth a try,

**Comment by njvdberg** [comment] 2022-02-13 09:03
@oktophonie Option 4 is certainly the easiest  and of course the one I prefer :smile: 
There is one simple reason I propose the add the new staff in option 3 **above** the selected staff. When adding the new staff **below** the selected staff, there are 2 ways to add the staff at the end (select the last staff or don't select any staff, in which case the staff is added to the end). But there is not way to at the staff at the top.

@Tantacrul There is one tricky thing is option 3.
To add an extra manual staff, the user has to select any manual staff otherwise the new staff will be added at the bottom and won't be braced.
This could be solved by adding new staves always
1. if _no staff is selected_, below the **last staff of the braced group**.
2. if a _staff is selected_, below the **selected staff**.

Now by default a manual staff is added and the user has to do some extra if a new pedal staff is added. However, I expect adding a new pedal staff is expected not that common as adding a new manual staff.
For other braced instruments (piano, accordion,... ) new staves are always added to the brace, unless the user separated a staff oft the brace already.
If we go for this proposal, staves will be added **below** the selected staff and not, as in the original option 3, **above**. This sound also a little more natural to me.

**Comment by Tantacrul** [comment] 2022-02-13 10:10
@njvdberg - sounds good!

**Comment by njvdberg** [comment] 2022-02-14 07:40
I'll give a go, watch this space :smile:

**Comment by Tantacrul** [comment] 2022-05-27 15:57
@njvdberg - How are things looking?

**Comment by Tantacrul** [comment] 2022-05-27 15:59
I'm moving this to 4.x. If it happens to get fixed early, we'll include in 4.0.

Otherwise, we'll reopen this after 4.0 is out.

**Comment by Tantacrul** [comment] 2022-06-02 08:20
Thanks for the explanation. Interestingly, I am not able to do this on my Mac. (Will check Windows later) but I can at least comment now.

1. We intended to prevent users from selecting different staves in different instruments precisely because it would produce weird results (and crashes) when users tried to move them up or down. So this should be disabled. I can still select a range of staves for one instrument, which I think makes sense.
<img width="296" alt="image" src="https://user-images.githubusercontent.com/21022311/171586281-53acca76-0394-4b83-9e43-3fd60531c065.png">

2. It was definitely never intended for the 'Add staff' button to create more than one staff at a time. So the results you are encountering (where more than one stave is created) are definitely not desired.

Completely agree with what you think is the desired behaviour.

**Comment by Tantacrul** [comment] 2022-06-02 08:22
@njvdberg - should I reopen this and target at Beta if you are working on it?

**Comment by njvdberg** [comment] 2022-06-02 09:19
@Tantacrul Thanks, this explanation makes sense and is something I was hoping for :smiley:. It gives me enough to continue on this.
> should I reopen this and target at Beta if you are working on it?

I'm working on it so please, reopen it.

BTW, it seems to me it best to disable `Add staff` when here is more than one staff selected.

**Comment by boryskuzmenko** [comment] 2022-06-03 12:31
Only thing that is still not clear for me: is it expected that I can select staves on different instruments by clicking on them with ctrl+shft (cmnd+shft)? @tantacrul

**Comment by Tantacrul** [comment] 2022-06-03 12:38
> Only thing that is still not clear for me: is it expected that I can select staves on different instruments by clicking on them with ctrl+shft (cmnd+shft)? @Tantacrul

They should be able to multi-select the instruments themselves, but not **just** the staves of multiple instruments.

So.. this is fine:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/21022311/171855132-79cbf032-1525-4e52-9e5d-7a6b2aad9a61.png">

But I should not be able to use any modifier to select the second stave in this image:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/21022311/171855271-ad4ec4ca-22c1-451b-a010-4b61b1d78a81.png">

This is actually exactly how it works on my Mac right now.

**Comment by njvdberg** [comment] 2022-06-14 09:33
Update of PR #10526 solves also the issue with braces and bracket span in case of instruments with multiple staves like pianos and organs.

If **no** staff is selected and `Add staff` is clicked, a new staff is added at the **bottom** of the instrument. If there is a staff selected, a new staff added **above** the selected staff.

Whether the new staff is include within a brace and bar line span depends on whether the "reference" staff is include or not.
This "reference" staff is the last staff of the instrument if not staff is selected or the selected staff. If this "reference" staff is include the new staff will be also.
This means for the piano the the new staff is always included in brace and barline span. For instruments with a pedal staff, new staves are included unless the pedal staff is selected or no staff is selected.

A special case is if all except one staves are already removed and a new staff is added. In this case the first staff of the instrument template is used for deciding whether a brace and barline span has to be created.

**Comment by Tantacrul** [comment] 2022-06-16 13:08
- I think new staves should not be created above either. Now that I see it, it just means that in most cases, the user will then need to drag the stave below. (Guitar + Tab in particular). The current rule (always create below) seem more broadly sensible. I think this should be fixed in https://github.com/musescore/MuseScore/pull/10526 (if that is where it was introduced)

- The grand stave issue could possibly be split off into a P2 (aimed at Beta 2, I'd say).

**Comment by njvdberg** [comment] 2022-06-17 08:37
- Regarding adding new staves **above** the selected staff we had some discussions (see above) but I agree with @DmitryArefiev it can feel strange, I have have no problem to change it. If we all think it is better to create staves **below** the selected staves, it will be done.
- I though I checked all case but apparently I missed one, good catch. Will be solved.

**Comment by Tantacrul** [comment] 2022-06-17 09:07
Yes, I remember the discussions about staves appearing **above**. I didn't consider it properly, I think :)

**Comment by njvdberg** [comment] 2022-06-20 15:29
Updated PR now:
1) Add staves always **below** the selected (if any staff is selected, other it will be appended at the end).
2) Move braces at the removed staff to the next staff unless the span becomes 1.

**Comment by njvdberg** [comment] 2022-06-20 15:31
When testing this issue (and PR) I was running into some other strange behavior in case staves are added **and** the a part for this instrument exists. I'll investigate further and create a dedicated issue for this.

**Closed** 2022-07-04 08:45 UTC
Labels: P2
