### ISSUE TITLE
MuseScore crashes on quit on macOS; crash log mentions libqtlabsplatformplugin.dylib

### ISSUE THREAD

**Issue by plamuk** [musescore/MuseScore#21252] opened 2024-01-27 23:29 UTC
### Issue type

Crash

### Bug description

It's happening with multiple scores. I attached an example score here, but the uploader doesn't recognize the .mscz file type. The file is greyed out so I can't choose it. I appended .pdf to the file name so I could select and upload it, you should just be able to delete the .pdf extension and have the working Musescore file. 

[Invitation-analysisv3.mscz.pdf](https://github.com/musescore/MuseScore/files/14074284/Invitation-analysisv3.mscz.pdf)

### Steps to reproduce

1) Open the attached score in Musescore
2) Make an edit
3) Save the score
4) Close the score
5) Quit Musescore - 90 % of the time it will crash while closing Musecore. See attached samples and video snippet.

(from @DmitryArefiev: see https://github.com/musescore/MuseScore/issues/21252#issuecomment-1997693011 to reproduce the issue) 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/16111434/e1a442f0-e294-4a16-83e1-a4e449da5275

### MuseScore Version

OS: macOS 14.3, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Choose option...

### Operating system

macOS Sonoma 14.3

### Additional context

[Crash dump.pdf](https://github.com/musescore/MuseScore/files/14074295/Crash.dump.pdf)

**Comment by cbjeukendrup** [comment] 2024-01-28 00:15
Judging from the crash report, this is in fact the same crash as #20809, but let's use this issue and close #20809, since this issue is cleaner. 

As noted in #20809, this crash was [reported](https://github.com/musescore/MuseScore/issues/18572) and [fixed](https://github.com/musescore/MuseScore/pull/18593) earlier for Linux, but that fix caused problems on macOS. So we'll have to look for a different fix for macOS.

**Comment by GuitarDude2** [comment] 2024-01-28 12:50
[Crash Report.txt](https://github.com/musescore/MuseScore/files/14076065/Crash.Report.txt)
It keeps happening to me everytime as well (since 4.1 and now also in 4.2). Maybe the attached crash report helps with the analysis. Cheers

**Comment by cbjeukendrup** [comment] 2024-01-28 13:01
Thanks, that is indeed related to the same crash. I think we basically have all info we need, except that we still can't reproduce it ourselves, so once we have a potential fix we'll need someone's help to test it.

For other people who encounter a crash on quit: if you see `libqtlabsplatformplugin.dylib` mentioned a few times in the crash report, then it's the same crash as this one, so you can just wait for this issue to be resolved :)
Otherwise, it may be a different one, in which case I recommend to open a new issue.

**Comment by plamuk** [comment] 2024-01-28 23:11
> we still can't reproduce it ourselves, so once we have a potential fix we'll need someone's help to test it.

Happy to help.

**Comment by BLongMusic** [comment] 2024-02-03 01:33
I also have this same crash. It occurs nearly every time I use musescore, so if you need help to test, I could give it a go.

**Comment by plamuk** [comment] 2024-02-20 20:59
Update - it is now crashing every time I open any score and then quit the app. No edits or saves needed, the crash is triggered when I quit MuseScore. Definitely reproducible on my rig, 100% of the time.

**Comment by BBM360-MusicSchool** [comment] 2024-02-28 18:03
Same behavior here, 100% crashes on quit (not on closing files)
MacBook Pro M3 Pro - Sonoma 14.2.1
MuseScore 14.2.1

**Comment by wimjanse** [comment] 2024-03-06 19:59
Same issue, 100% crashes on MacMini M3, MacStudio M1 and MacBook Pro M3. All running on Sonoma 14.3.1 and Musescore 4.2.1.

**Comment by cbjeukendrup** [comment] 2024-03-10 02:10
It would be interesting to check this in the latest `master` nightly builds (https://musescore.org/en/nightly-builds). These are namely created using Qt 6, as opposed to current versions of MuseScore, which were built with Qt 5.

**Comment by plamuk** [comment] 2024-03-10 02:59
Thanks, opened one of my scores, added a few notes to it, saved it and closed the score. So far so good. Exited the app and it immediately crashed. Here's the first part of the crash dump, can send or upload the whole thing if it's useful.
- Dave
-------------------------------------Translated Report (Full Report Below)-------------------------------------
Process:               mscore [54236]Path:                  /Applications/MuseScore 4.3.0.240690507 Nightly.app/Contents/MacOS/mscoreIdentifier:            org.musescore.MuseScoreVersion:               4.3.0 (240690507)Code Type:             X86-64 (Translated)Parent Process:        launchd [1]User ID:               501
Date/Time:             2024-03-09 18:55:47.2773 -0800OS Version:            macOS 14.3.1 (23D60)Report Version:        12Anonymous UUID:        5523BCAC-C94C-1B79-410A-D4EB0CB46B45
Sleep/Wake UUID:       5A4B5273-B3DE-4D6F-86AF-5BBD02BE4BCC
Time Awake Since Boot: 1000000 secondsTime Since Wake:       8069 seconds
System Integrity Protection: enabled
Notes:PC register does not match crashing frame (0x0 vs 0x13BF9DC44)
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000000cException Codes:       0x0000000000000001, 0x000000000000000c
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11Terminating Process:   exc handler [54236]
VM Region Info: 0xc is not in any region.  Bytes before following region: 140722869977076      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL      UNUSED SPACE AT START--->        mapped file              7ffc98ad4000-7ffcc1884000 [653.7M] r-x/r-x SM=COW  ...t_id=d7859667
Error Formulating Crash Report:PC register does not match crashing frame (0x0 vs 0x13BF9DC44)
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread0   libqtlabsplatformplugin.dylib         0x13bf9dc44 0x13bf88000 + 891561   libqtlabsplatformplugin.dylib         0x13bf9dbc4 0x13bf88000 + 890282   libqtlabsplatformplugin.dylib         0x13bf9c4de 0x13bf88000 + 831663   libqtlabsplatformplugin.dylib         0x13bf96016 0x13bf88000 + 573664   QtCore                                0x11966a15f QObjectPrivate::deleteChildren() + 2875   QtCore                                0x119669ed3 QObject::~QObject() + 20036   libqtlabsplatformplugin.dylib         0x13bf96316 0x13bf88000 + 581347   QtCore                                0x11966a15f QObjectPrivate::deleteChildren() + 2878   QtCore                                0x119669ed3 QObject::~QObject() + 20039   QtQuick                               0x1145cafce QQuickItem::~QQuickItem() + 86210  QtQuick                               0x11475d766 0x1144b7000 + 277898211  QtCore                                0x11966a15f QObjectPrivate::deleteChildren() + 28712  QtCore                                0x119669ed3 QObject::~QObject() + 200313  QtGui                                 0x1185b21c4 QWindow::~QWindow() + 10014  QtQuick                               0x1145f422f QQuickWindow::~QQuickWindow() + 108715  libqtquicktemplates2plugin.dylib        0x13beca876 0x13be9b000 + 19467816  QtQml                                 0x1151c6aa9 QQmlApplicationEngine::~QQmlApplicationEngine() + 20117  mscore                                0x1054a3516 mu::ui::UiEngine::quit() + 3818  mscore                                0x10431d235 mu::app::App::run(int, char**) + 646919  mscore                                0x104309c65 main + 232520  dyld                                  0x207c93386 start + 1942
    On Saturday, March 9, 2024 at 06:10:46 PM PST, Casper Jeukendrup ***@***.***> wrote:  
 
 


It would be interesting to check this in the latest master nightly builds (https://musescore.org/en/nightly-builds). These are namely created using Qt 6, as opposed to current versions of MuseScore, which were built with Qt 5.

**Comment by cbjeukendrup** [comment] 2024-03-10 03:13
But that's a 4.3 nightly build, which is indeed expected to produce the same results as 4.2.1. Make sure to download one that doesn't have "4.3" in the name but only "master".

**Comment by plamuk** [comment] 2024-03-10 03:24
Aha! The master version doesn't crash!  At least not with two scores that I tried which in 4.2.1 consistently resulted in a crash on app close.  Well done 
    On Saturday, March 9, 2024 at 07:13:25 PM PST, Casper Jeukendrup ***@***.***> wrote:  
 
 


But that's a 4.3 nightly build, which is indeed expected to produce the same results as 4.2.1. Make sure to download one that doesn't have "4.3" in the name but only "master".

**Comment by Eism** [comment] 2024-03-14 15:14
I investigated this issue

Initially, I couldn't reproduce the problem, but later found a way to reproduce it almost 100% (see screen recording). Before closing the program, you need to open and close as many menus as possible. The main problem I see here is that we create and delete menus each time a menu is opened. Consequently, if this is done too many times, some objects fail to destroy, resulting in a crash.

I can't reproduce the crash using the solution for Linux. In the PR for the Linux solution #18593, I see mention of issues for macOS, but I don't encounter them on my machine. I suggest retesting again.

An interesting point is that I can't reproduce the crash on the master branch with either Qt5 or Qt6, but it consistently occurs on 4.3. I couldn't find what changed, but I still suggest using the Linux solutions for macOS and also in the master branch.

I will be glad if you all check that the problem has been fixed for 4.3 here #21936

https://github.com/musescore/MuseScore/assets/10116828/4d637c3b-5bf5-4c6b-b961-5399d8fd3818

**Comment by cbjeukendrup** [comment] 2024-03-15 01:39
> I will be glad if you all check that the problem has been fixed for 4.3 here #21936

If anyone isn't sure how to do this, here are instructions for downloading and running such test builds: 
[How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests)

**Comment by scorster** [comment] 2024-05-07 18:51
MuseScore Studio 4.3 crashes on Quit. 
Mac OS 13.5.2; MacBook Air M2, 24GB RAM, 2TB SSD.

OS: macOS 13.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

For the record, installation of MuseScore Studio and MuseHub is a confusing and disconcerting experience.

**Comment by DmitryArefiev** [comment] 2024-05-08 10:53
@scorster Please attach info from OS crash reporter (copy text and paste it to text file)

**Comment by cadiz2** [comment] 2024-05-08 16:59
One more, see: https://musescore.org/fr/node/363811 (and its pdf file)

**Comment by scorster** [comment] 2024-05-09 02:07
> [@scorster](https://github.com/scorster) Please attach info from OS crash reporter window (copy text and paste it to text file)

I'll posts a report, when I can. 

Until now MuseScore Studio has crashed *every* time I Quit. But now when I want it to ...

**Comment by DmitryArefiev** [comment] 2024-05-09 11:32
> One more, see: https://musescore.org/fr/node/363811 (and its attached pdf file)

Thanks!

@Eism Can you check please? [20240508_incident_fermeture_MUSESCORE.pdf](https://github.com/musescore/MuseScore/files/15261629/20240508_incident_fermeture_MUSESCORE.pdf) If it's the same crash or not

**Comment by Eism** [comment] 2024-05-09 11:41
Yes, the dump shows that it crashes when quitting and the output is similar to the previous one
But I can't reproduce

**Comment by BLongMusic** [comment] 2024-05-12 03:04
Attached is a copy of one of my crash reports on my iMac, Sonoma 14.2.1,
MuseScoreStudio 4.3.

The crash occurs when closing MuseScoreStudio and appears the same as in
MuseScore 4.2.

Bob Long

**Comment by cbjeukendrup** [comment] 2024-05-12 09:51
It seems that because you replied via email, the attachment doesn't appear on GitHub. Please retry sending it by commenting directly on GitHub instead of via email. Thanks!

**Comment by BLongMusic** [comment] 2024-05-13 01:27
Attaching a copy of my crash reports on iMac, Sonoma 14.2.1, MuseScoreStudio 4.3.
Crash occurs every time I close the program. I have not seen any crash during use of the program.
[mscore-2024-05-10-175043.pdf](https://github.com/musescore/MuseScore/files/15288363/mscore-2024-05-10-175043.pdf)

**Comment by cbjeukendrup** [comment] 2024-05-13 10:38
Thanks! That's indeed the same crash as the original one reported here. Hopefully we'll find a solution soon.

**Comment by cadiz2** [comment] 2024-05-21 12:53
Also: https://musescore.org/en/node/364356

**Comment by cbjeukendrup** [comment] 2024-06-03 17:38
(just a quick notification that I have retitled this issue, in case anyone has to find it)

**Comment by wizofe** [comment] 2024-06-06 11:17
I have the same crash every time I am closing it as well. If you need any help with reproducing it, reports etc ping me.

**Comment by Eism** [comment] 2024-06-06 12:13
@wizofe 
Please record a video of how you reproduce the crash and attach diagnostic files.

**Comment by Eism** [comment] 2024-07-04 19:32
oh, I found another way to reproduce a crash with a similar output: open preferences and press Cmd+Q

**Comment by jsmcx** [comment] 2024-07-07 15:39
I have no problem reproducing the crash on exit - has happened consistently ever since I started using the app >1 year ago, and still happens every single time I quit the app. Issue persists in current version (OS: macOS 13.6, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2)

**Comment by Eism** [comment] 2024-07-08 06:36
Ok, the crash with the preference dialog is not reproducible on the latest master, but on 4.3 it is reproducible. It seems the problem has been fixed

@jsmcx Please try to reproduce the crash on[ this version](https://github.com/musescore/MuseScore/actions/runs/9832821891/artifacts/1676038123) (latest master). If you can reproduce the crash, please send the diagnostic files again and it will also be very cool if you record a video of how you reproduce the crash

**Comment by jsmcx** [comment] 2024-07-08 12:08
@Eism The latest master seems to fix the issue. Great news!

**Comment by Eism** [comment] 2024-07-16 06:16
I will close this PR as resolved. Feel free to re-open if you still encounter crashes

**Closed by Eism** 2024-07-16 06:16 UTC
Labels: P0, crash
