### ISSUE TITLE
Incorrect arpeggio playback

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20479] opened 2023-12-14 14:55 UTC
### Issue type

General playback bug

### Bug description

If you extend the arpeggio to the chord to the lower staff, then when playing in the arpeggio style, only the upper chord will sound (on the first staff). The bottom chord in the arpeggio style will not sound.

### Steps to reproduce

I added an arpeggio to the chord located on the treble clef staff. then I pulled the arpeggio up to the bottom of the staff with the shift+↓ key combination

### Screenshots/Screen recordings

![Снимок экрана (72)](https://github.com/musescore/MuseScore/assets/134041121/41dc09bf-bbf8-4400-b492-09833672049f)
[arpeggio.zip](https://github.com/musescore/MuseScore/files/13674787/arpeggio.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-12-14 15:04
Duplicate of https://github.com/musescore/MuseScore/issues/14362

**Closed by oktophonie** 2023-12-14 15:04 UTC
Labels: playback
