### ISSUE TITLE
[MU4 Issue] Toolbars section should be blocked if all it`s options blocked

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7684] opened 2021-03-06 05:43 UTC
**Describe the bug**
Toolbar section can be opened when there are no available options

**To Reproduce**
1. Launch MU4
2. Click on 'View'
3. Observe "Toolbars" option

**Expected behavior**
Toolbar section should be blocked if all it`s options blocked

**Screenshots**

![image](https://user-images.githubusercontent.com/71372310/110196764-c35f7680-7e57-11eb-8e44-8568cb618adc.png)

**Desktop (please complete the following information):**
Windows

**Comment by RobFog** [comment] 2021-04-26 16:00
"it`s" → its

**Comment by Tantacrul** [comment] 2022-04-30 11:21
Ancient.

**Comment by HemantAntony** [comment] 2022-04-30 11:22
This issue still occurs

**Comment by Tantacrul** [comment] 2022-04-30 11:46
It seems to be behaving as expected. Options that should be blocked are blocked.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/21022311/166104167-1eafed9d-502d-427b-b7ed-bfaaeeadb876.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/21022311/166104172-372beacf-89f7-4442-950f-76317d25f329.png">

**Comment by Tantacrul** [comment] 2022-04-30 11:47
What else should toolbars do other than nothing in this instance?

<img width="649" alt="image" src="https://user-images.githubusercontent.com/21022311/166104208-1ced1f0f-e744-4e08-8a79-dab12d11335d.png">

**Comment by HemantAntony** [comment] 2022-04-30 11:51
@Tantacrul  You should not be able open Toolbars since all of its child items are disabled.

It misleads users into thinking that you can click on items inside that menu. So the button Toolbars itself should be disabled. If you want to see the intended behaviour, I have a PR for this issue.

**Comment by Tantacrul** [comment] 2022-04-30 11:54
I see. Man, oh, man. OK, since there is a PR ready for it, can you link it here?

**Comment by HemantAntony** [comment] 2022-04-30 11:56
@Tantacrul #10656

**Comment by Tantacrul** [comment] 2022-04-30 12:06
OK, tested. Closing for good this time.

**Closed by Tantacrul** 2022-04-30 12:06 UTC
Labels: P3
