### ISSUE TITLE
[MU4 Issue] Enter does not close Insert Measure dialog

### ISSUE THREAD

**Issue by Reedbeta** [musescore/MuseScore#16341] opened 2023-02-13 00:21 UTC
**Describe the bug**
The Enter key cannot be used to confirm and close the Insert Measure dialog box after typing in the number of measures. This breaks keyboard flow.

May also apply to other dialogs; the Insert Measure one was just the place where I noticed it.

**To Reproduce**
1. In a score, press Alt+Shift+B (or go to Add -> Measures -> Insert at end of score). The dialog box opens.
2. Type in a number in the text box.
3. Press Enter. The text box loses focus, but the dialog does not close.

**Expected behavior**
Pressing Enter should act like clicking the OK button in dialogs.

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by RobFog** [comment] 2023-02-13 00:43
Yeah, this issue is very annoying. I thought it had been reported before but I can't find an older issue about this.

**Comment by cbjeukendrup** [comment] 2023-02-13 07:37
Duplicate of #12222. Thanks for reporting!

**Closed by cbjeukendrup** 2023-02-13 07:37 UTC
