### ISSUE TITLE
MuseScore for Mac Exports PDF Files Incorrectly

### ISSUE THREAD

**Issue by whydavewhy** [musescore/MuseScore#17330] opened 2023-04-23 20:25 UTC
### Issue type

UI bug

### Bug description

- MuseScore Version: 4.0.2
- Late 2016 MacBook Pro running macOS 12.6.5
- PDF Viewer app: Apple “Preview” version 11.0 (1033.4)

MuseScore for Mac does not export to PDF files with the original formatting of the MuseScore document. I have never been able to get this feature to work correctly with MuseScore 3 or MuseScore 4 on a Mac. (NOTE: MuseScore 4 for Windows exports PDF files perfectly on a PC.)

For example, I have a single page of music set to Page View in MuseScore 4. I moved the song title up higher on the page, and made the margins smaller, to fit the entire part on one page. See the screen shot example of “Just the Way You Are (MuseScore 4 Version)," attached below, in the 'Screenshots' section. 

Next, I export the page to PDF format, using MuseScore 4's export function... 

File / Export / Select parts to export: 'Alto Saxophone' / Format: 'PDF File' / 'Each part to a separate file' / <Export>.

The problem occurs at this point, because the PDF version does not retain the title height or the margin settings, causing the staves to extend to a second page. See the screen shot example of “Just the Way You Are (Mac PDF Version)," attached below, in the 'Screenshots' section. As I mentioned above, this problem does not occur when doing a PDF export in MuseScore for Windows, because in that version, the title height and margin settings are retained in the PDF document.

So when doing PDF exports from MuseScore 4 for Windows, all the settings transfer to the “Acrobat Reader” program correctly; however, when doing PDF exports from MuseScore 4 for Mac, the title height and margin settings DO NOT transfer to the Apple “Preview” app correctly.

### Steps to reproduce

1. Unfortunately, this website does not support attaching MuseScore 4 .mscz files, to reproduce MuseScore 4 issues; so there is no way to send you the file to reproduce the problem; all I can do is attach a screenshot of this MuseScore 4 example. See the screen shot example of “Just the Way You Are (MuseScore 4 Version)," attached below, in the 'Screenshots' section. If you DID have this actual MuseScore 4 file, then to reproduce the problem you would need to go to a Mac computer, and open the file in MuseScore 4 for Mac.
2. Observe that the entire part fits on one page (due to raised title height, and shortened side margins).
3. Export the file to PDF format, by doing the following: File / Export / Select parts to export: 'Alto Saxophone' / Format: 'PDF File' / 'Each part to a separate file' / <Export>.
4. Observe that the edits to title height and margin shortening are not retained, causing the staves to extend to a second page on the PDF version. See the screen shot example of “Just the Way You Are (Mac PDF Version)," attached below, in the 'Screenshots' section.
5. Now try the same thing on a PC computer, running Windows;  once again, if you DID have this actual MuseScore 4 file, then to reproduce the problem you would need to go to a PC computer, and open the attached file in MuseScore 4 for Windows.
6. Observe that the entire part fits on one page (due to raised title height, and shortened side margins).
7. Export the file to PDF format, by doing the following: File / Export / Select parts to export: 'Alto Saxophone' / Format: 'PDF File' / 'Each part to a separate file' / <Export>.
8. Observe that the edits to title height and margin shortening are retained, and the part remains on one page; so the PDF version in Windows is identical to the original MuseScore version.
9. (It is really frustrating, that a website used for reporting MuseScore 4 bugs, does not support attachment of MuseScore 4 files, to reproduce the problem.)

### Screenshots/Screen recordings

[Just the Way You Are (MuseScore 4 Version).pdf](https://github.com/musescore/MuseScore/files/11304796/Just.the.Way.You.Are.MuseScore.4.Version.pdf)

[Just the Way You Are (Mac PDF Version).pdf](https://github.com/musescore/MuseScore/files/11304798/Just.the.Way.You.Are.Mac.PDF.Version.pdf)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

macOS 12.6.5

**Comment by Jojo-Schmitz** [comment] 2023-04-23 20:30
Stems from https://musescore.org/en/node/348481, sample score there

**Comment by MarcSabatella** [comment] 2023-04-23 21:15
As far as I can tell, this isn't an Windows vs macOS difference, it's just a score vs part difference.  You are *formatting* to score, but exporting the port.  It should be no surprise if the score formatting doesn't appear in the exported part, because formatting is always independent between score and parts, by design.

If you want to edit the formatting of the individual parts, you need to do that while viewing the actual parts, not the score.  Of course, this particular score has only a single part, but that doesn't matter- part and score formatting are separate.

BTW, to attach a score here, just rename it to end in .zip, or actually zip it.

**Comment by cbjeukendrup** [comment] 2023-04-23 22:56
I think Marc is right: on my Mac, I get the following results:
- File > Export > "Main score": gives exactly what the main score looks like in MuseScore
- File > Export > "Alto Saxophone": gives exactly what the Alto Saxophone part look like in MuseScore

You are probably confused by the word "Main score", since this file contains only one instrument and the "Main score" is actually formatted as if it is a part score for the Alto Sax. 

The reason that it's called "Main score" there, is that this _does_ make sense for files with multiple instruments: then you have a main score that contains all instruments, and beside that you have part scores that contain one instrument each. 

But when there is only one instrument, the "main score" (which is what you have been working in) and the part score for that instrument have identical content, so it might be a little bit confusing. 

So, when you want to export the score you have been working in, you should choose "main score" in the export dialog. And if you want to access that part score called "Alto saxophone" in MuseScore, you can access it via the Parts dialog; you will see that in this part, the layout is like what's exported when you select "Alto saxophone" in the export dialog. 

I hope this makes it clearer! I'll close this issue because there does not seem to be a bug, but feel free to ask further questions, and we can reopen it if it still turns out that something is really not working correctly.

**Closed by cbjeukendrup** 2023-04-23 22:56 UTC
Labels: UI

**Comment by whydavewhy** [comment] 2023-04-24 02:34
Hi Marc,

That was the problem. When I chose ’Select parts to export: Alto Saxophone', the PDF file did not retain the edited settings, but when I chose ’Select parts to export: Main Score’, the PDF file retained the edits, and looked exactly like the original. Glad to hear it is not a bug. Thanks for solving this mystery!

David

**Comment by whydavewhy** [comment] 2023-04-24 02:35
Hi Casper,

Yes, that was the problem. When I chose ’Select parts to export: Alto Saxophone', the PDF file did not retain the edited settings, but when I chose ’Select parts to export: Main Score’, the PDF file retained the edits, and looked exactly like the original. Glad to hear it is not a bug. Thanks!

David

**Comment by shishkin** [comment] 2024-05-21 11:34
I had the same issue as @whydavewhy and was also puzzled by ignored page settings. I only work with single part scores and this "design" of MuseScore is extremely confusing in that case. I get it that conductor's score may be formatted differently to accommodate higher information density, but why would you want to format each part differently?

Anyways, the page settings dialog has a button "Apply to all parts". What confused me even more is that this button absolutely did not apply my main score page settings on all parts. Only after opening the individual score part and editing its page settings separately was I able to export the part as intended.

**Comment by MarcSabatella** [comment] 2024-05-21 12:26
Normally, you don't want every part differently, and that's why the default is to format them all the same.  But it's important to have the *ability* to format some parts differently.  Some, for instance, might need slightly smaller staff size in order to fit on a given number of pages.  But on the other hand, it would be relatively unusual to want to apply the *score* setting to parts, since the score often has smaller staff size (and often smaller margins, and sometimes a larger paper size) than any of the parts.

Anyhow, if you have further questions on how to use MuseScore, please ask on the Support forum at musescore.org.
