### ISSUE TITLE
The sound is jammed with a random rapid change in pitch

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22795] opened 2024-05-13 11:25 UTC
### Issue type

Muse Sounds bug

### Bug description

see the title

### Steps to reproduce

Use the up/down keys to quickly randomly change the pitch by pressing these keys

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/2cbc849e-954b-4883-8482-14b5adeefa95

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Muse Sampler Version

0.6.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by RomanPudashkin** [comment] 2024-08-22 11:48
This looks like a duplicate of https://github.com/musescore/MuseScore/issues/22639, which has already been fixed. Please re-test it on 4.4

**Comment by Dima-S-Jr** [comment] 2024-08-31 06:45
I checked (MuseScore Studio version 4.4.0, Muse Sampler version 0.100.2, OS — Windows 11), the bug no longer occurs.

**Closed** 2024-08-31 15:45 UTC
Labels: P1, playback, muse sounds
