### ISSUE TITLE
Stopped horn in F bug 

### ISSUE THREAD

**Issue by macaquedev** [musescore/MuseScore#24628] opened 2024-09-10 23:16 UTC
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Horn in F, musesounds (I have musescore 4.4.1 installed), mf volume, concert B4 (B above middle C on piano, sounding pitch), when stopped (with a plus over the notehead), it sounds buzzy and horrible....see supporting video

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/640571c4-3ed5-41cb-9e8e-69e63921b290

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by LucySuccubus** [comment] 2024-09-11 15:34
The concert B4 on the excerpt seems to be distorted. Upon further testing, I can reproduce this with Musescore Studio 4.4.1, Musesampler 0.100.2, with Musebrass 0.4.4 (Horn in F). I have also found out the issue extends to concert Bb4. Both notes are distorted, with the distortion sounding like a faint note a semitone apart is playing simultaneously with the stopped note.

**Comment by bkunda** [comment] 2024-09-20 14:19
Closing as this will be addressed by the Muse Sounds team.

**Closed by bkunda** 2024-09-20 14:19 UTC
Labels: muse sounds

**Comment by macaquedev** [comment] 2024-09-20 17:57
@bkunda You seem to have given this the tag "won't fix" though? What's up with that....

**Comment by oktophonie** [comment] 2024-09-20 18:05
Because it's for the Muse Sounds team to fix, not something to fix in MuseScore.
As he literally just said in his comment.

**Comment by Fristover** [comment] 2024-09-20 18:08
Extra tip, bugs like this one can now be reported directly in the new Muse Hub via the "Report a Problem" button, might want to consider that next time.

![image](https://github.com/user-attachments/assets/1b1d0922-8c37-432d-b630-f87769b7db89)

**Comment by macaquedev** [comment] 2024-09-20 18:13
@oktophonie no need to be condescending please - I did not know whether issues raised here about MuseSounds actually get to the MuseSounds team and how this happens.

@Fristover thanks, that's perfect. should I report this issue there or not?

**Comment by Fristover** [comment] 2024-09-20 18:17
No, since this issue got closed they probably got informed about this already (or will be pretty soon).

**Comment by macaquedev** [comment] 2024-09-20 18:18
thanks :)
