### ISSUE TITLE
Shift key stops MIDI input progressing to next note

### ISSUE THREAD

**Issue by brettrp** [musescore/MuseScore#19906] opened 2023-11-01 23:52 UTC
### Issue type

UI bug

### Bug description

If you hit the shift key (and release it) or use a keyboard shortcut with the shift key (e.g. to turn on an accidental shift-= for "#") and then enter MIDI notes, all subsequent MIDI notes are entered as a chord. This persists even if you hit shift again, until you exit note input mode.

This does not happen if you use the mouse to click the "#" icon -- only if you use the keyboard shortcut.

It appears that the shift key is sticky with MIDI input - is this by design?

(The accidental controls do not otherwise affect MIDI input at all.)

### Steps to reproduce

1. Open a new score
2. Enter note input mode
3. Enter sharp mode using the keyboard shortcut (e.g. SHIFT-=)
4. Play a series of notes on a MIDI keyboard

All the notes are entered as a chord

5. Exit sharp mode
6. Continue to enter notes

The notes continue to be added to the same chord

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/6935280/1396a8f3-2c0f-4ee1-ac2c-4730113243eb

### MuseScore Version

OS: macOS 14.0, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS 14.0

### Additional context

See https://musescore.org/en/node/284062#comment-1213322 for some discussion about interaction of accidentals and MIDI

**Comment by zacjansheski** [comment] 2023-11-02 21:10
This only has to do with the shift key.  The other accidental "shortcuts" do not have that effect.  Pressing the shift key will start stacking notes until you progress forward with the arrow key, this might actually be by design.

https://github.com/musescore/MuseScore/assets/69917893/cf0fd683-2117-41e6-b1c2-386e386a005c

**Comment by brettrp** [comment] 2023-11-02 21:22
You're right that it's in fact the shift key. If you hit shift it causes subsequent MIDI notes to stack. And there is no way out of it other than exiting note input mode.

But the shift key shouldn't be sticky should it? Is that really by design? (It's not how stacking notes from the computer keyboard works.)

**Comment by bkunda** [comment] 2023-11-03 14:17
Closing as this appears to be by design. 
If we want different behaviour for this particular use case, we can consider that separately as a feature request.

**Closed by bkunda** 2023-11-03 14:17 UTC
Labels: UI

**Comment by brettrp** [comment] 2023-11-03 23:02
@bkunda While SHIFT -> consecutive MIDI notes looks like it might be by design, I'm not so sure about SHIFT-<keyboard shortcut> having the same effect. Should I file that (SHIFT as part of a keyboard shortcut causes chord entry) as a separate bug?
