### ISSUE TITLE
[MU4 Issue] Box following note goes in reverse

### ISSUE THREAD

**Issue by TestingPlant** [musescore/MuseScore#13158] opened 2022-09-04 01:56 UTC
**Describe the bug**

The box following the note being played (see below picture) goes in reverse.
![image](https://user-images.githubusercontent.com/44930139/188293573-8fb4b3de-3678-4c0f-b608-62ef212bef40.png)

**To Reproduce**
1. Create a score with two flutes
2. Set up the score like this:  ![image](https://user-images.githubusercontent.com/44930139/188293610-129f52f6-c978-416e-8c24-8e24043a1fb9.png)
3. Press the play button

**Expected behavior**

The box should keep going forward.

**Video**

https://user-images.githubusercontent.com/44930139/188293693-0c0e51e0-5d01-4d38-b2d3-7b186e9dbb6d.mp4

**Platform information**
 - OS: Arch Linux

**Comment by cbjeukendrup** [comment] 2022-09-04 12:07
In MuseScore 3 I can indeed reproduce, in MuseScore 4 I can't. So it looks like this is fixed in MS4!

(Please keep in mind that this issue tracker here on GitHub is focused on issues that occur in MS4. So if you encounter an issue in MS3, please check if it also occurs in MS4 before logging it here. You can try "nightly builds" of MuseScore 4 at https://ftp.osuosl.org/pub/musescore-nightlies/.)

**Closed by cbjeukendrup** 2022-09-04 12:07 UTC
