### ISSUE TITLE
Volume spikes slightly suddenly when dynamic is decrescendo-ed to niente on strings(?) 

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#22812] opened 2024-05-14 07:54 UTC
### Issue type

Muse Sounds bug

### Steps to reproduce

1.  place a dynamic on a note
2.  place an n on another note after the note with a dynamic
3.  then select both notes and place in between, a decrescendo.
4.  no grammar in this explanation so far :)(:

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 10

**Comment by Dima-S-Jr** [comment] 2024-09-05 14:04
I want to repeat once again that this bug is inherent not only in Muse Sounds, but also in MS Basic. But I noticed a certain feature: if niente is assigned to some last tied note (i.e. not a rest) and the hairpin is adjacent to niente, then in this case, as in Muse Sounds and in MS Basic, the last tied note will sound, but before the loudness has time to drop to niente. Take a look at how it works: 

https://github.com/user-attachments/assets/d5820379-1c66-439b-abf6-77f19e062db8

But if niente is assigned after a note (i.e. a rest), then in this case everything will sound fine in MS Basic, but in Muse Sounds you will have to hear a short accent at the end. Take a look at this (and observe the loudness scale): 

https://github.com/user-attachments/assets/9c393489-7ff0-4b25-8557-b288b68bcfb7

Obviously, niente should not be assigned to the note, but to the rest/tick that follows the note, this would be the correct scheme of how niente should work. For what is the point of assigning niente to a note if it would end up being exactly the same as if there were no note? (take a look at the example below)
![Снимок экрана (546)](https://github.com/user-attachments/assets/593f9a96-d1bb-4086-adb5-955427cbd8ef)

However, even in this scenario, the note should not sound in principle if it is assigned a niente. @RomanPudashkin, isn't it time to finally resolve this issue? All you need is that the notes assigned to niente do not sound.

**Comment by cbjeukendrup** [comment] 2024-09-08 02:27
> All you need is that the notes assigned to niente do not sound.

If only it were as easy as that... 
But I created a fix here: https://github.com/musescore/MuseScore/pull/24544

**Comment by UncleRed0899** [comment] 2024-09-10 02:25
Hello, all. I've found a way **Around** this issue... it does not "fix" it, technically speaking, but the playback reflects what the _Al Niente_ marking _**Should**_ sound like, when written. 

if you place a Niente dynamic, for any note, at the end of any decrescendo mark, click the Niente marking, open the "Properties"  menu, and de-select "Play", it will no longer spike the volume of the instrument playback whenever the track bar reaches the dynamic. 

Additionally, the Decrescendo, having been placed before "Play" was disabled, will make the playback respond as if it is reducing the volume to an "Al niente" marking, as intended. I'll demonstrate in a quick screen recording video here (unpack the .ZIP file to view the video, as it's greater than 10MB and I could not add it to the thread):
[Uploading Bug-workaround-example.zip…]()

**Closed** 2024-09-22 00:06 UTC
Labels: P2, playback
