### ISSUE TITLE
[MU4 Task] Musescore 4 closed itself when too much information had to be read and played by the software

### ISSUE THREAD

**Issue by SShinyMH** [musescore/MuseScore#14266] opened 2022-11-02 12:22 UTC
Hello! I would like to point out a problem which I hope is personal.
Indeed, wanting to rework my orchestral scores from Musescore 3 on Musescore 4, I could notice that Musescore 4 closed itself when too much information had to be read and played by the software. Whether it is for Kontakt or MuseSound VSTs, the problem persists.
I don't know if the information was found on GitHub or on this forum but I wanted to share this information.

Translated with www.DeepL.com/Translator (free version)

**Comment by MarcSabatella** [comment] 2022-11-02 13:16
Hello!  In order for someone to investigate, you would need to attach your score and give steps to reproduce the problem.  You can ZIP your score before attaching it so that GitHub will accept it.

**Comment by SShinyMH** [comment] 2022-11-03 11:06
Hello Marc !

Here the score !
[Orchestral Score.zip](https://github.com/musescore/MuseScore/files/9927675/Orchestral.Score.zip)


Step 1 : Open the score in Musescore 4
Step 2 : Replace the basic sound with MuseSound
Step 3 : Play the score (At some point, when too many instruments play together musescore will crash)

(I try to increase the buffer size to 2048 but the problem continues to persist).

If you have any question, do not hesitate to contact me !

**Comment by SShinyMH** [comment] 2022-11-08 15:20
Hello again,

After reinstalling MuseHub, Musescore 4 and Muse Sound the problem persists. 
Unfortunately, the video file to show the problem is too big for Github. So I sent it to you through a WeTransfer link:

- https://we.tl/t-fOB3ajo5EW

In this file you have the video showing the problem as well as the screenshot showing that I have switched to the version indicated by Tentacrul which is: 2c34155. 

Thanking you in advance for all the effort you put into MuseScore 4.
ps : Thank you a lot Tentacrul for your feedback on my score :)

**Comment by Tantacrul** [comment] 2022-11-08 16:01
Interesting. Can I ask whether it always crashes somewhere in-between those repeat marking? I'm wondering if the repeats might be the culprit. If so, you could try:

- Play the parts that don't have the repeats
- Remove the repeats and play from the start again

---

Also (just to satisfy my curiosity), how is the playback performing when you set the buffer to 1024?

**Comment by SShinyMH** [comment] 2022-11-08 16:39
I set the buffer to 1024 with the repeat bars, result: MuseScore crash

After removing the repeat bars (still with a buffer of 1024) Musescore crashes on the first repeat instead of the second this time.

To answer your curiosity, when I set the buffer to 1024 the sounds "crack"

Here is a new WeTransfer link for the example: 

- https://we.tl/t-mqnpSADnj9

**Comment by Tantacrul** [comment] 2022-11-08 16:46
OK, so if you just remove **all voltas** and **all repeats**, then save the score (as a different version), then reopen it again, does it still crash?

**Comment by Tantacrul** [comment] 2022-11-08 16:47
At this stage, I'm reasonably confident the problem is repeats and voltas. We have a general issue with them that is affecting most repeat-related symbols and playback.

**Comment by SShinyMH** [comment] 2022-11-08 17:13
Sorry Tentacrul but I don't understand what "Voltas" means ?

**Comment by DaddyLudwig** [comment] 2022-11-08 17:14
Like first and second endings, that’s a way that they are often referred to, especially outside of classical music circles.

**Comment by SShinyMH** [comment] 2022-11-08 17:22
Oh, you mean the takeover alternatives?
![téléchargement (2)](https://user-images.githubusercontent.com/117281024/200632889-bbd5b396-00ca-4b14-8a15-ba668ec963e4.jpg)

**Comment by Tantacrul** [comment] 2022-11-08 18:11
Yes, exactly. I just want to hear how it all plays back when anything related to repeats or playback alterations are removed.

**Comment by SShinyMH** [comment] 2022-11-08 18:19
Same things, without repetitions marks and voltas

- https://we.tl/t-Xf7V1FaPRE

I just realized that the score stutters when the tutti is played, but i don't think this things is about the main problem

**Comment by RomanPudashkin** [comment] 2024-07-09 07:21
Closing as the description is too vague, so the issue is unfixable. But no worries, we're working on some optimizations, so that 4.4 will consume much less memory / CPU

**Closed by RomanPudashkin** 2024-07-09 07:21 UTC
Labels: P1
