### ISSUE TITLE
Auto-scroll in Continuous view jumps too far (and hides content)

### ISSUE THREAD

**Issue by apacha** [musescore/MuseScore#23581] opened 2024-07-11 12:56 UTC
### Your idea

Jump only so far, that you can still read all the content in continuous view.

### Problem to be solved

Described in detail here: https://musescore.org/en/node/354283

### Additional context

I was hoping that this will be solved with the new smooth panning, but that feature is something completely different and actually not usable for me and doesn't solve the underlying problem.
Related to: https://github.com/musescore/MuseScore/issues/19210

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment] 2024-07-11 21:03
Duplicate of https://github.com/musescore/MuseScore/issues/16173 (but you're totally forgiven for not finding that one!)

**Closed by cbjeukendrup** 2024-07-11 21:03 UTC
Labels: feature request
