### ISSUE TITLE
Tooltip strings not in Transifex

### ISSUE THREAD

**Issue by Magnus26** [musescore/MuseScore#22923] opened 2024-05-21 08:35 UTC
### Issue type

Other type of issue

### Bug description

The tooltip strings for the fretboard diagrams in the MuseScore Studio palette are currently not in Transifex although there is a need to translate them.

### Steps to reproduce

1. Open a score and then the Fretboard diagrams palette.
2. Put the mouse pointer arrow on a diagram for the tooltip to appear.

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Q4OS

**Comment by Jojo-Schmitz** [comment] 2024-05-21 08:51
Code starts at https://github.com/musescore/MuseScore/blob/55945e815ac97f4db942760175480d1e6bf3703a/src/palette/internal/palettecreator.cpp#L1765

**Comment by Magnus26** [comment] 2024-05-22 04:55
The string situation is the same for "Grace notes" as for "Fretboard diagrams".

**Comment by Jojo-Schmitz** [comment] 2024-05-22 09:22
The latter is a regression vs Mu3, the former a day one issue

**Comment by Jojo-Schmitz** [comment] 2024-05-22 09:23
Assign to me, I'll be working on it

**Comment by Jojo-Schmitz** [comment] 2024-05-23 18:05
Actually I don't see the issue with the tooltips of the Grace notes palette:
![image](https://github.com/musescore/MuseScore/assets/1786669/2286042c-e3b1-4ceb-b971-01c09e51a047)

**Comment by Jojo-Schmitz** [comment] 2024-05-23 18:17
@Magnus26 check the strings in Transifex starting with "Add grace note:", https://app.transifex.com/musescore/musescore/translate/#sv_SE/$/434015825?q=text%3A'add+grace+note'
You even translated them yourself, a couple days ago

**Comment by Magnus26** [comment] 2024-05-23 18:53
> @Magnus26 check the strings in Transifex starting with "Add grace note:", https://app.transifex.com/musescore/musescore/translate/#sv_SE/$/434015825?q=text%3A'add+grace+note' You even translated them yourself, a couple days ago

Can you see those translations of mine when you run MuseScore Studio with Svenska (traditionell)?

**Comment by Magnus26** [comment] 2024-05-24 04:15
For me it is like in the following attached image with the latest language update:

![Screenshot_20240524_060957](https://github.com/musescore/MuseScore/assets/93758048/0b46de48-e2d3-43ee-8b4d-7cbfb9e97202)

**Comment by Jojo-Schmitz** [comment] 2024-05-24 05:05
These strings _are_ on Transifex.
Use the ... Menu to reset the palette

**Comment by Magnus26** [comment] 2024-05-24 05:15
Yes, the Grace note tooltip strings are in Transifex, but they are not visible in MuseScore Studio on my computer.

Do you mean the menu opened with the three dots in the tab Paletter to the right of the title of the tab?

**Comment by Jojo-Schmitz** [comment] 2024-05-24 05:24
Yes

**Comment by Jojo-Schmitz** [comment] 2024-05-24 05:29
The palette tooltip don't update with language change and/or translation updates, not even after a restart, a bug in the need of a GitHub issue on its own

**Comment by Magnus26** [comment] 2024-05-24 05:37
> Yes, the one is the Grace palette

OK, the three dots to the right of the palette title Prydnadsnoter, yes that worked so now I see my translations.

Will you submit that bug report?

**Comment by Jojo-Schmitz** [comment] 2024-05-24 07:41
See #22960, it is only the Grace notes palette...

**Comment by Jojo-Schmitz** [comment] 2024-05-24 08:52
No, it is bigger than that (check the new issue for details

**Closed** 2024-06-06 14:22 UTC
Labels: strings, community, good second issue, palettes

**Comment by cbjeukendrup** [comment] 2024-06-06 14:25
This has been resolved in the source code in #22938, but the strings will not appear on Transifex until we push the 4.4 strings. (and we won't do that yet, because that would imply that 4.3 strings are removed and thus that "Check for languages updates" in 4.3 wouldn't work anymore).
