### ISSUE TITLE
Crashes/Freezing constantly

### ISSUE THREAD

**Issue by flyingrabbitgb** [musescore/MuseScore#15217] opened 2022-12-16 06:17 UTC
This has been happening for a while, since the RC and a couple of nightlies before that. Virtually every action causes MS4 to freeze, requiring an exit using Task Manager. Usually it happens from the Project Manager, either trying to create a new project or open an existing one. I then open a new instance of MS4, which (usually) allows me to create the project or open one. Editing the file tends to be okay, but again freezes up when trying to save the file.

I've tried completely uninstalling, removing all traces of MS4 including in AppData (Roaming and Local), and completely cleaning out the registry of any references to MS4. Nothing seems to work. As mentioned, this has been going on for a few builds now, whereas during the alpha and early beta things worked beautifully. This started happening right around the time when the update to MuseSounds had an issue with MS4, and hasn't worked since.

System is a Windows 10 (latest updates), i7 7700k, 32GB RAM, 6BG 1060 graphics and running off an SSD. I've attached logs from the last couple of times I tried to open MS4.

[MuseScore_221216_053948.txt](https://github.com/musescore/MuseScore/files/10243126/MuseScore_221216_053948.txt)
[MuseScore_221216_054028.txt](https://github.com/musescore/MuseScore/files/10243127/MuseScore_221216_054028.txt)

**Comment by flyingrabbitgb** [comment] 2022-12-16 17:14
Interesting...just reinstalled and strangely, this time I left it on my primary monitor. First test of opening a file then doing a Save As seemed to work. Moved to my secondary monitor and tried the same thing...freeze!

**Comment by EagleSplash** [comment] 2022-12-16 23:34
I'm having a similar problem, caused by using MS4 on a second monitor.  This seems to be the same issue that was described in another post:  [MU4 Issue] Creating new score opens a new window outside the screen area #13635

The previously reported issue was closed and labeled as fixed a couple of months ago, but I'm seeing the same symptoms with the new "officially released" MS4

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621
NOTE: Information above is from MS4, it is NOT CORRECT - I am actually running Windows 11 Version 22H2.


Running MS4 on my primary screen, things all work fine - though the screen is too small to work efficiently in MS4.

Running MS4 on my second screen, the modal dialog windows pop up off the screen and lock action on the main window.  This happens for LOTS of interactions:
- Add or Remove Instruments
- New Score - Choose Instruments
- Do You Want to Save Changes Before Closing Window

You can get to the off-screen modal dialog windows by pressing Alt+Spacebar, the window context menu appears in the corner of the screen and you can select Move. Then drag the off-screen window using the cursor keys or the mouse somewhere on the screen and continue using MS4 until the next modal window pops up and starts this problem all over again.

**Comment by madviolinist** [comment] 2022-12-28 00:40
I have been having similar issues. Using Windows 11 Home (Version 22H2, OS Build 22621.963) on a Acer Nitro 5, using a 24" monitor on second screen to the right of the laptop. MuseScore version (64 bit) 4.0.0.223472200 Rev 5485621
(Copy from MS4 About "OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621"

When on primary monitor (laptop screen), dialog windows appear as expected. When operating Musescore on the Secondary monitor - the following interactions are not visible:

Add Instruments
File -> Save (on a new score)
File -> Save a copy...
File -> Save as...
File -> Save to cloud
File -> Publish to Musescore.com
File -> Export
File -> Project Properties
File -> Parts
Edit -> Preferences
View -> Playback setup
Help -> Check for update
Help -> About
Help -> About MusicXML
Help -> Revert to Factory Settings
Diagnostic -> Muse Sampler-> Check Muse Sampler

Page and Style Settings do work from the properties tab, as well as from the Format Menu.

Using the Alt+Spacebar show the dialogs opening off screen to the right of the external monitor. Changing screen so that it is to the left of the primary monitor allows dialogs to display as normal. Making the secondary monitor the primary monitor did not change the behaviour. Showing only on monitor 2 (external monitor) has dialogs behave as expected.

Strangely... after going through this process of changing monitors display settings, it started behaving as expected. Closed Musescore 4 and opened it again to confirm - and it worked as expected. 
I suspect that the change to secondary monitor as the Primary monitor, and then changing to show only on monitor 2/clone displays, and then back to extend made Musescore see the second monitor as the primary monitor and behave correctly.
Closing Musescore and returning the laptop screen to being the main monitor before reloading MS4 - loads on laptop monitor, dragging it to secondary monitor dialogs do not operate as expected.

I suspect Musescore needs to load on the Primary screen. By making the monitor you want to work on the primary monitor, dialogs appear to work correctly and as expected.

@EagleSplash - can you confirm from your end - try making your second screen the main monitor, and then loading MS4

**Comment by EagleSplash** [comment] 2023-01-03 17:35
Per madviolinist's notes above, I made my external monitor my "main display" and my laptop monitor a second extended display.  This temporarily solves the modal window off-screen problem and isn't hard to do, though I wouldn't call it a true fix for the underlying bug.  Unlike madviolinist's report, I have to make this change to display settings every time I want to run MS4.  Switching the laptop screen back to main display causes the MS4 problem to come back.

I have noticed that when I put MS4 on the external monitor while it is designated as second/extended and click in the upper right corner to expand the window to full screen, MS4 doesn't actually fill the screen - there is an 1/8" gap on all 4 sides of the window.  This gap does NOT happen on the laptop screen when it is designated as the second/extended monitor.

I have also noticed that when I run MS4 on my laptop screen while it is designated as second/extended, the modal windows show up on the screen - they are not drawn off screen.  When the laptop screen is designated as second/extended, the modal windows display in a different location than when the laptop screen is designated as the main display...  they move down and left.

My two screens have different resolutions, scaling, and aspect ratio, making me wonder if that might be related to this problem.
Laptop Screen
- Resolution = 3840 x 2400 (Recommended)
- Scale = 300% (Recommended)

External Monitor
- Resolution = 3840 x 1600 (Recommended)
- Scale = 125%  (windows recommends 100%, I tested 100% and it did NOT change MS4 behavior.)



Full directions for anyone else who wants to test this temporary fix:
1) Right click on the desktop and select "Display Settings"
2) Click on the second monitor (the light gray box marked "2")
3) Check the box for "Make this my main display" as shown in attached screen shot.  
4) Start MS4 program


![Screenshot 2023-01-03 114553](https://user-images.githubusercontent.com/18221228/210402124-b278d00c-9168-4abb-9c95-003d9d1976e3.png)

**Comment by zacjansheski** [comment] 2023-07-27 16:21
Can I get confirmation that this is still actual in the latest release?
A brief summary and crash reports would also be helpful for developers.
Thank you!
I am unable to reproduce crashing on Windows 11 with 2 monitors

**Comment by EagleSplash** [comment] 2023-08-04 04:38
I just updated versions before checking on this.  All of the modal dialog windows listed above are now working correctly for me.  They work correctly on both my primary and secondary monitor.

The issue with the 1/8" gap on all 4 sides of the window that I mentioned earlier is also fixed on my end.

Big THANKS! to anyone who helped make this happen.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by cbjeukendrup** [comment] 2023-08-06 12:26
@flyingrabbitgb Could you please let us know if this issue is resolved for you too in the latest version (4.1.1)?

**Comment by zacjansheski** [comment] 2023-09-04 15:35
Closing, no response

**Closed by zacjansheski** 2023-09-04 15:35 UTC
Labels: crash
