### ISSUE TITLE
Splitting and joining measure causes slurs to break and causes crash (one score)

### ISSUE THREAD

**Issue by Nazaretto** [musescore/MuseScore#22558] opened 2024-04-24 18:18 UTC
### Issue type

Crash or freeze

### Bug description

If you try to split measure on slur and press Command+Z whole app crashes. If you try to join measure before the slur – it breaks the slur, and after you press Command+Z it causes crash as well. This happens to all my files created from scratch. It makes impossible to finish already started work.

### Steps to reproduce

1. Create few bars of sheet with slurs.
2. Try to split the bar.
3. Press Command+Z.

----------------------------
From @DmitryArefiev: Easy way to reproduce the crash
1. Open [Bug example 2.mscz.zip](https://github.com/musescore/MuseScore/files/15098705/Bug.example.2.mscz.zip)
2. Add slur to measure 2
3. Split measure 2
4. Undo ([see comment](https://github.com/musescore/MuseScore/issues/22558#issuecomment-2076738092))

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

macOS 13.5.1

### Additional context

[Bug example 2.mscz.zip](https://github.com/musescore/MuseScore/files/15098705/Bug.example.2.mscz.zip)

**Comment by DmitryArefiev** [comment] 2024-04-25 09:17
> This happens to all my files created from scratch.

@Nazaretto Strange.. I can't reproduce it from scratch, only with your score. 

https://github.com/musescore/MuseScore/assets/90187801/baecc057-7d07-42d8-a633-b6cea97eebe8

**Comment by mike-spa** [comment] 2024-07-08 10:31
The slur has nothing to do with the crash: I can reproduce the crash in his file just from splitting measure and reverting (i.e. without entering the slur)

**Comment by DmitryArefiev** [comment] 2024-07-10 10:09
Fixed in #23511

**Closed** 2024-07-10 13:08 UTC
Labels: P1, regression, crash
