### ISSUE TITLE
[MU4 Issue] Mnemonic ampersands still appear in MacOS

### ISSUE THREAD

**Issue by hodori0719** [musescore/MuseScore#12537] opened 2022-07-23 14:26 UTC
**Describe the bug**
Mnemonic access ampersands still appear in various menus throughout MU4 on MacOS.

- [ ] In shortcuts
- [x] In palettes
- [x] In Instruments names (Inspector) Fixed in https://github.com/musescore/MuseScore/pull/12670

**To Reproduce**
1. Go to MuseScore > Preferences > Shortcuts
2. Find "&Close" or any other action that has ampersand attached.

Also visible in Layout palette > Insert &Horizontal/&Vertical/&Text Frame

**Expected behavior**
Ampersand should be hidden from display.

**Platform information**
macOS, Not tested on other platforms

**Comment by shoogle** [comment] 2022-07-24 23:19
Note that #12414 switches to using action _descriptions_ in Preferences > Shortcuts instead of action _titles_. The descriptions do not contain ampersand (`&`) characters. However. this bug would still need to be fixed in the Palettes.

**Comment by Eism** [comment] 2022-07-25 11:43
@hodori0719 @shoogle 
can't reproduce in the Palettes

**Comment by hodori0719** [comment] 2022-07-26 03:27
@Eism see attached
![image](https://user-images.githubusercontent.com/5251669/180916716-8447417a-d7ba-4812-89e8-575a0aededf3.png)

**Comment by hodori0719** [comment] 2022-07-26 03:28
Doesn't seem to happen anywhere else in the palettes, though I haven't checked the advanced ones.

**Comment by shoogle** [comment] 2022-07-26 05:07
It seems that it's only the palette cells that use icons rather than drawn elements. In [palettecreator.cpp](https://github.com/musescore/MuseScore/blob/95b68a0e6a27c8355b150f695b92613aa9e5a364/src/palette/internal/palettecreator.cpp#L551-L560), `"Staff spacer fixed down"` is created from scratch, whereas the vertical frame element borrows an icon and title from the UiAction `"insert-vbox"`.

But the name in the palettes should just be `"Vertical frame"`, not `"Insert vertical frame"`, so it would probably best to give all of the cells an explicit name rather than reusing the action title for some of them.

**Comment by Eism** [comment] 2022-07-26 06:18
fixed in the Palettes

**Closed** 2022-08-18 12:12 UTC
Labels: P2

**Comment by boryskuzmenko** [comment] 2022-08-18 12:34
**FIXED** except:
https://github.com/musescore/MuseScore/issues/12922
https://github.com/musescore/MuseScore/issues/12921
