### ISSUE TITLE
Part Score doubles system text and symbols

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#17025] opened 2023-03-27 14:48 UTC
### Issue type

Choose option...

### Bug description

In a new part score, somehow Rehearsal marks and tempo text etc. show up doubled (stacked onto each other). This happens when I do not enable the upper most staff as first, or when I rearrange the staffs so that another one becomes the upper one.

### Steps to reproduce

See above. Only tested for formerly imported MusicXML.

As a workaround you can just select the item, press Ctrl+X to cut and Ctrl+V to paste, but this is quite tedious...

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/12497326/227975768-a6ddd8fa-36ec-4bfb-9fec-cd885caf3c84.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2023-03-27 15:02
Duplicate of https://github.com/musescore/MuseScore/issues/15371
(fixed in master)

**Closed by oktophonie** 2023-03-27 15:02 UTC
Labels: regression, engraving
