### ISSUE TITLE
[MU4 Issue] Playback jumps to the beginning of the score after reaching the end of playback, even after selecting score elements.

### ISSUE THREAD

**Issue by KleinkMusic** [musescore/MuseScore#15587] opened 2022-12-25 17:52 UTC
**Describe the bug**
Whenever a score is played to the finish, and then elements mid-score are selected, the playback jumps to the very beginning anyway.

**To Reproduce**
1. Open any score
2. Let score play until the end (you don't have to let the whole score play, just let it reach the end.)
3. Select any elements that you might want to hear in the middle of the score.
4. Press play
5. See error (Score starting from the very beginning)

**Expected behavior**
Playback should just start at selected elements.

**Screenshots**

https://user-images.githubusercontent.com/104653161/209477711-4deb37cf-688b-4266-9005-ffc395c156b1.mp4

**Platform information**
Microsoft Windows 10

**Comment by MarcSabatella** [comment] 2022-12-25 18:18
Thanks for posting; this is already reported as https://github.com/musescore/MuseScore/issues/15228

**Comment by cbjeukendrup** [comment] 2022-12-25 18:23
Closing as a duplicate of #15228.

**Closed by cbjeukendrup** 2022-12-25 18:23 UTC
