### ISSUE TITLE
PM beeing applied to next note

### ISSUE THREAD

**Issue by xlaech** [musescore/MuseScore#17620] opened 2023-05-18 09:17 UTC
### Issue type

General playback bug

### Bug description

When adding Palm Mute to notes the PM is always played back for one extra note. This is especially annoying if you compose patterns with a lot of alternating PM/non-PM patterns since then everything keeps beeing palm muted.

From [Muse Score Tracker](https://musescore.org/en/node/340693#comment-1190609)
_"Is this beeing worked on? It makes playback for compositions that use a lot of Palm Muting very annoying. Attached please find an example to showcase the problem. I encounter this problem on 2 different mac versions with 4.0.2."_

### Steps to reproduce

1. Add N notes
2. Add palm mute to K < N notes
3. Playback slow an realize, that PM is applied K+1 notes

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

macOS 12.06

### Additional context

I created an example project to show this linked in the old issue tracker: https://musescore.org/sites/musescore.org/files/2023-05/Broken%20PM.mscz

I also uploaded it to the musescore cloud: https://musescore.com/user/64348498/scores/10890730

**Comment by oktophonie** [comment] 2023-05-18 09:41
Duplicate of https://github.com/musescore/MuseScore/issues/15865

**Closed by oktophonie** 2023-05-18 09:41 UTC
Labels: duplicate, playback
