### ISSUE TITLE
Invisible dynamics are not played at all

### ISSUE THREAD

**Issue by aafifi21** [musescore/MuseScore#24103] opened 2024-08-19 18:06 UTC
### Issue type

General playback bug

### Description with steps to reproduce

1. type a short musical passage.
2. start with a soft dynamic, such as p.
3. include crescendo to the note at the end.
4. end with any dynamics louder than original, such as mp, f, ff, etc.
5. make said dynamic invisible.
6. you can also do the opposite.
7. Actual behaviour: Visible dynamics play much louder than invisible ones.
8. Expected behaviour: Invisible dynamics should sound the same as visible ones.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b32cf2a5-a266-4d5b-9e7c-0745917dbc46

https://github.com/user-attachments/assets/49f86074-a676-45ba-9b95-d9196449e71c

[Dynamics Test (4.4.0.242320503).mscz.zip](https://github.com/user-attachments/files/16663708/Dynamics.Test.4.4.0.242320503.mscz.zip)

Attached is the zip file of the score, along with screen recordings comparing both MS Basic and MuseSounds.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242320503 Nightly

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS Sonoma 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-19 18:13
Duplicate of https://github.com/musescore/MuseScore/issues/24093, already fixed

**Closed by oktophonie** 2024-08-19 18:13 UTC
Labels: playback, regression nightly
