### ISSUE TITLE
[MU4 Issue] Installing Sounds on an external SSD does not work

### ISSUE THREAD

**Issue by fynndesign** [musescore/MuseScore#13985] opened 2022-10-24 16:12 UTC
**Describe the bug**
Whilst I was able to set a different folder to install the Muse Sounds in, it does not work to install them on an external HD/SSD.  OSX forces Apps to ask to be allowed to access certain folders or drives. That does not happen when I install MuseHub, nor does it happen, when I select and external SSD as install location. Unless that is not solved, I won't be able to use the new sounds. And no, installing them on the internal SSD is no option. It's too small and nearly full, hence the external SSD, where I install all my sounds on.

**To Reproduce**
Select an external HD or SSD as install location in MuseHub on a Mac.

**Expected behavior**
MuseHub should install the sounds on a selected folder of the selected SSD

**Screenshots**

**Platform information**
 latest OSX

**Additional context**

**Comment by iamtesch** [comment] 2022-11-08 18:40
Can you check whether this is still an issue on the latest update?  We have fixed some issues surrounding setting the folder on mac, although I'm not sure if this is addressed yet or not.

Thanks!

**Comment by Tantacrul** [comment] 2022-11-10 15:57
Duplicate of https://github.com/musescore/MuseScore/issues/13981

@fynndesign - it would be great if you could test to see if this is happening, as @iamtesch mentioned above.

**Closed by Tantacrul** 2022-11-10 15:57 UTC
