### ISSUE TITLE
Program crashes due to WASAPI Audio Client Error

### ISSUE THREAD

**Issue by RmGkAppDev** [musescore/MuseScore#16575] opened 2023-02-27 19:37 UTC
### Issue type

Crash or freeze

### Bug description

When opening MuseScore, it crashes.
The error on the logs are as follows:
2023-02-27T21:09:05.249 | ERROR | 18988 | WasapiAudioClient | setStateAndNotify: 
2023-02-27T21:09:05.249 | ERROR | 18988 | WasapiAudioClient | setStateAndNotify: 
2023-02-27T21:09:05.249 | ERROR | 8784 | WasapiAudioClient | setStateAndNotify: 

The full log is attached here: [MuseScore_230227_210904.log](https://github.com/musescore/MuseScore/files/10843296/MuseScore_230227_210904.log)

### Steps to reproduce

1. Open MuseScore.
2. If you're lucky enough, WASAPI will crash MuseScore.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Log file attached here too: [MuseScore_230227_210904.log](https://github.com/musescore/MuseScore/files/10843322/MuseScore_230227_210904.log)

Specs:
- Asus Prime X570-P
- CPU: AMD Ryzen 7 3700X 8-Core Processor
- SSD 1024GB (1TB)
- Memory - 64GB DDR4 2400 MHz
- OS: Windows 11 (Home Edition)
- GPU: NVidia 3080 RTX XC3 Ultra
- Sound Card: Focusrite Scarlet 4i4
- Keyboard: Steelseries APEX 350 (Gaming Keyboard)
- Keyboard: Steelseries RIVAL 600 (Gaming Mouse)

Also have Sibelius, Cubase, and ASIO-4ALL installed on my computer, alongside many others.

LAST VERSION THAT WORKED:
This is a bit complicated since I can build MuseScore right now and it will work fine, using your tutorial.
Also, back in April of 2021 MuseScore nightly build stopped working for me, and now they do work.

My uneducated guess is that the errors have something to do with how you compile MuseScore since this is the only factor I could think of that I can change and would make any difference at all.

**Comment by cbjeukendrup** [comment] 2023-02-27 20:58
The way we compile MuseScore is in fact just using CMake... and there aren't many possibilities for discrepancies. The only relevant difference that I can think of right now, is the SDK version. It's unclear to me what SDK version is used on GitHub CI, but which version have you installed on your machine?

**Comment by Tantacrul** [comment] 2023-02-28 09:51
@cbjeukendrup - I'm unclear if this should be added as a required fix for 4.0.2 or not? If it should be can you add it?

**Comment by cbjeukendrup** [comment] 2023-02-28 11:21
I don't think we should make it a requirement anymore, simply because the chance that we can find the problem within a reasonable amount of time is very small (no-one of us can even reproduce it). And the previous fix for this problem has already fixed it for a lot of people, so the situation has already improved a lot.

**Comment by cbjeukendrup** [comment] 2023-02-28 11:27
@RmGkAppDev Just to be sure that wasapi is really the cause: do you have any VST plugins on your computer? Maybe those are the cause of the crash. That might also explain that you don't have the crash in your self-built version: by default, it does not build VST support. 

Also, if it's true that the last version that worked is from April 2021, then it can't be wasapi, because wasapi was introduced _much_ later, like November 2022. 

If it's indeed caused by VST plugins, then after each crash, the problematic VST plugin is disabled, so if you try often enough, the crash should stop happening.

**Comment by RmGkAppDev** [comment] 2023-02-28 12:23
> @RmGkAppDev Just to be sure that wasapi is really the cause: do you have any VST plugins on your computer? Maybe those are the cause of the crash. That might also explain that you don't have the crash in your self-built version: by default, it does not build VST support. 
> 
> Also, if it's true that the last version that worked is from April 2021, then it can't be wasapi, because wasapi was introduced _much_ later, like November 2022. 
> 
> If it's indeed caused by VST plugins, then after each crash, the problematic VST plugin is disabled, so if you try often enough, the crash should stop happening.

Well, it could be. I will update soon

**Comment by RmGkAppDev** [comment] 2023-03-01 19:24
Well, you're right! it was the vst3!

**Closed** 2023-03-01 19:24 UTC
Labels: regression, crash
