### ISSUE TITLE
Feature request: Toggle for behaviour of on-screen/MIDI keyboard regarding transposing instruments

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15594] opened 2022-12-26 00:24 UTC
**Task description**
For the behaviour of on-screen/MIDI keyboard regarding transposing instruments (when the score is in transposing pitch), there are two options:
1. When playing C, notate C (in transposing pitch), so it will sound like something different
2. When playing C, notate something different, so it will sound like C (effectively happens when switching the score to concert pitch)

Currently, MuseScore only really supports option 1, but there was a request for the option to toggle this behaviour (while keeping the score notated in transposing pitch).

**Workaround**
To get option 2, temporarily switch the score to concert pitch.

**Design idea**
We could show this setting in both of the following two places:
- In the menu of the '...' button in the piano keyboard window
- In a new section in Preferences > Note Input

**Comment by bkunda** [comment] 2024-01-08 15:59
I've just had a separate request for this. This is something that could fall under the umbrella of general-note-input-interaction-improvements that we might tackle for one of the releases this year. 
@avvvvve @Tantacrul FYI.

**Comment by Tantacrul** [comment] 2024-01-08 21:54
Needs a little design but should be a nice little one to queue up for the community - or we do it a bit later in the year

**Comment by davidfaianunes** [comment] 2024-04-23 12:39
Hi! I've been working on fixing issue #21900 - "Note highlighting on the piano keyboard ignores ottava." - and came across the problem regarding keyboard-view while transposing instruments. Could you assign this feature request to me? I'm thinking of adding a toggle to switch between sounding and notated pitches.

**Comment by wizofaus** [comment] 2024-08-29 23:16
BTW if you're unable to continue with this @davidfaianunes I could have a look, but it needs some sort of UX/UI to toggle on off - if someone can provide an icon and a location for it I'm happy to do the rest.

**Comment by cbjeukendrup** [comment] 2024-09-02 23:09
@wizofaus Maybe it could be a toggle in Preferences > Note input. Good idea to make the changes apply to hardware MIDI keyboards too. Applying it to the computer keyboard as well may also make sense, but perhaps that should be a next step for a separate PR.

**Comment by wizofaus** [comment] 2024-09-03 00:07
I'm not convinced it's a preference per se - that implies some users would nearly always work in one mode, while others would nearly always work in the other. But I can definitely see myself wanting to flip between them depending on where I'm getting the notes from (e.g. the sounding pitches as they exist in mind, or written pitches that I'm reading off another score).

**Comment by avvvvve** [comment] 2024-09-04 19:41
To summarize, a three-parter would be nice here:

- A preference in note input
- A toggle in the piano keyboard window (that is synced to the preference)
- A shortcut to toggle both

The preference should affect note input via hardware/software MIDI devices AND entry via the in-app "Piano keyboard". I agree that making this affect keyboard letter entry can come later.

See preliminary designs below - kept the labels relatively concise but could do another pass on them!

### Preferences mockup

![image](https://github.com/user-attachments/assets/c0ac03e7-6ee9-4157-9851-38da0ff14655)

### Piano panel mockup

**Option 1**
Context menu (takes 2 clicks, but can show the user the shortcut if we set a default one)

**Option 2**
In-panel toggle (takes 1 click, but perhaps it doesn't need to be this prominent)

<img width="883" alt="image" src="https://github.com/user-attachments/assets/df07dfe0-22ba-4b4f-b67a-bc7bd77e41fc">

**Comment by wizofaus** [comment] 2024-09-04 19:51
Do we have existing examples of shortcuts that toggle preferences though? 
Just yesterday I found myself wanting to toggle between the two modes for voice assignment when adding dynamics - couldn't see how to assign a shortcut to that.

**Comment by avvvvve** [comment] 2024-09-04 20:42
I don't think we do, but that doesn't mean we can't! (though will wait for a dev to correct me on that)

**Comment by wizofaus** [comment] 2024-09-04 20:49
It still doesn't feel like a "preference" to me I guess, which presumably will affect all scores in all musescore instances, now and forever. Vs a toggle which is specific to the current session, that might not even be saved if I restart the app. I.e. it's more like having "note input mode" on/off than a preference.

**Comment by wizofaus** [comment] 2024-09-04 21:52
There are commands like "pan", "countin", "mini-on", "metronome" etc. that actually toggle what are stored as preferences (in notationConfiguration() oddly, despite them being playback options), though it doesn't look like any of them appear in the Preferences dialog as such.

**Comment by avvvvve** [comment] 2024-09-04 23:01
We cannot assume that all users _wouldn't_ want this setting saved from session to session. Some might always want to write in concert pitch via an external MIDI keyboard.

This setting also cannot _only_ be accessible via the piano keyboard panel because it affects MIDI input too, and I don't think that users who use external MIDI keyboards will think to go there. And there isn't an obvious MIDI panel where this belongs either.

I'll think more on whether there is another sensible place to put this, but I really think it belongs in preferences at the least. Maaaaybe we could make the concert pitch toggle in the bottom bar have two child settings: one for the notation and one for entry.

**Comment by wizofaus** [comment] 2024-09-05 00:42
Totally agree it shouldn't be on the on-screen piano keyboard panel, I never even use that!
I don't mind it being in preferences, as long as it can be toggled easily with a shortcut key, which would require extra code to support (but it's not hard).

**Comment by cbjeukendrup** [comment] 2024-09-17 22:01
See https://github.com/musescore/MuseScore/pull/24784, which revives the old PR for this issue, but doesn't yet implement the suggested preferences option. @avvvvve I think I would prefer having two options "Use notated pitch" / "Use sounding pitch" as in that PR, rather than a single checkbox, because with the two options you can really see what you're choosing between. What do you think about that?

**Comment by rpatters1** [comment] 2024-09-17 23:54
Figured out how to test them all. The boolean is needed on all of them.

**Comment by rpatters1** [comment] 2024-09-18 01:57
I am the one who has revived this issue with #24784. That branch is currently working as I believe we would expect it to, except for the UI. Check it out if you wish. The setting is designed to persist across invocations of MuseScore.

The current UI is inherited from #22991 and is menu options on the virtual keyboard panel. I am in agreement with the consensus that the virtual keyboard panel is likely not used by quite a large number of users, so hiding the option there seems counter productive.

The UI requirements would seem to be:
- Option should be found in a place that might occur to most users.
- Option should be togglable by a keyboard macro.

I can probably knock out the UI in a few hours. (Less, with luck, but luck rarely happens.) But I need a design. The options would seem to be:

- An addition to a preferences panel (as mocked up above). Can this be easily accessed by a keyboard macro?
- Menu options on some menu that's logical and easily found. These certainly can be accessed by a keyboard macro.

A further question is: should computer keyboard entry behave the same way? Right now, if use playback pitch is selected, typing an A on the computer keyboard still puts an A in the trumpet part but shows a G on the virtual piano keyboard. That does not seem right, and I am going to see what it takes to address it.

**Comment by wizofaus** [comment] 2024-09-18 06:38
If it's a preference there'd need to be a separate command to toggle it that a shortcut can be assigned to.
And yeah, I'd say it's definitely expected that the virtual piano keyboard playback shows the same key you'd click on to enter that same note, though personally I'm not entirely sure of the main purpose of having that keyboard show notes as they're played back - there's even a case that it should always show sounding pitches if it's supposed to indicate what you'd play on a real piano to obtain the same notes... In future we might have a virtual trumpet or clarinet or French horn etc that showed how to finger the sounding pitch...

**Comment by rpatters1** [comment] 2024-09-18 10:54
What about moving the menu options from the virtual piano keyboard to the Note-entry mode menu? (The pencil icon on the note/rest strip.)

To be clear, when I said "computer keyboard" I mean the alphabetical keyboard that you type text with. Should entering an "A" from the keyboard enter a "B" on the trumpet part when this mode is enabled. I'm pretty sure it does not in Finale, though I will check. I will also see what Dorico does.

**Comment by rpatters1** [comment] 2024-09-18 11:38
FWIW, adding this feature to alpha-keyboard input looks complicated and risky. Finale does not support it for alpha-keyboard but Dorico does.

BTW, I like Dorico's terse menu options. If they appeared under the "Enable MIDI Input" option, it could be:

```
Enable MIDI input
Input Pitch >
   Written pitch
   Sounding pitch
---
Play repeats
Play chord symbols
```
etc.

That would have the advantage of showing that the feature was specifically MIDI related (with virtual keyboard palette as a bonus).

**Comment by wizofaus** [comment] 2024-09-19 01:59
It's definitely *more* useful for MIDI keyboard input (mainly due to association - because a piano itself is always non-transposing then I always expect an "A" played on a piano to produce an "A" sound - even if I happen to be writing music for a transposing instrument.  But maybe some people have MIDI clarinets or trumpets and feel quite differently about that!), but I would tend to think it's better if there was just a global option "input sounding pitches" that applies to both MIDI input and computer keyboard input.

**Comment by rpatters1** [comment] 2024-09-19 02:34
It's more useful on MIDI for a very practical reason. I can't convey just how annoying it is to be entering a trumpet part and hear a major 2nd clash on every note. (The keyboard is playing, e.g., G, but the trumpet is echoing back concert F.) Even if I turn off the echo, it disrupts the creative process aurally to switch keys for every transposing instrument.

In principal, I agree that the alpha keyboard should work the same way. The problem is (as I said), I don't know the code well enough to understand the ramifications of making a change in `Score::cmdAddPitch` (beyond passing in a boolean parameter that represents the option). If someone wants to suggest a surgical change, I am open to it. Otherwise, I suggest we not let the perfect be the enemy of the good. The urgent requirement is for MIDI input.

**Comment by wizofaus** [comment] 2024-09-19 05:21
But that's a different issue entirely! Why do you even have your keyboard sound on?  And if you do, then you'd want to want turn off MuseScore playback on note entry, which I believe there's a separate feature request for and has already been worked on.
You wouldn't want those major 2nds if you were entering trumpet or clarinet music while transcribing off an existing (already transposed) part already either, even though in that case you would want the played-back note to transposed down from the played note.

**Comment by rpatters1** [comment] 2024-09-19 11:35
It is much more convenient in my setup to leave the keyboard sound on, and hearing the correct pitch echoed back is excellent aural feedback that I haven't fat-fingered the note entry. Of course I know the options that are available to me: please don't treat me as if I don't. I have spent the several hours that I have spent implementing this one to enable me to work the way I work most efficiently.

**Closed** 2024-10-04 19:05 UTC
Labels: community, feature request, needs design
