### ISSUE TITLE
[Muse Sounds] Piano skipping notes or playing in wrong order

### ISSUE THREAD

**Issue by ethantrithon** [musescore/MuseScore#20136] opened 2023-11-21 18:21 UTC
### Issue type

Muse Sounds bug

### Bug description

Sometimes when using Muse Sounds' pianos (tested with Grand Piano and Soft Piano), the playback will skip some notes, or play them in the wrong order.

Example: [MuseScoreFiles.zip](https://github.com/musescore/MuseScore/files/13429658/MuseScoreFiles.zip) contains two of my arrangements (the SS Anne theme from Pokémon and the title theme from Ocarina of Time).

In the SS Anne theme, bar 5 has a note skipped, and bar 9 has notes in the wrong order.
In the OoT title theme, the run in bar 20 is skipping a lot of notes, and then in bar 21 it plays them *after* the other chords.

This problem doesn't happen when playing back with the MS Basic Soundfont.

Exact Musescore revision (copied from "about musescore"): `OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-, revision: github-musescore-musescore-`

### Steps to reproduce

* Open either file
* ensure Muse Keys' Grand Piano is selected
* press Play

Expected Behavior: Correct playback of the score
Actual Behavior: Weird sound issues

### Screenshots/Screen recordings

The highlighted notes fail to play back correctly

![SS Anne Screenshot](https://github.com/musescore/MuseScore/assets/37771915/a79cb921-c368-4a82-9207-54e62ae96921)
![OoT Screenshot](https://github.com/musescore/MuseScore/assets/37771915/1da5323c-25de-47d7-993b-8e12b906ea5a)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Arch Linux, MacOS Ventura, Windows 10

**Comment by MarcSabatella** [comment] 2023-11-21 18:56
This is yet another duplicate of https://github.com/musescore/MuseScore/issues/15306

@bkunda This issue was originally reported during the beta (see for instance https://github.com/musescore/MuseScore/issues/13853) where it also affected MS Basic.  It was fixed for MS Basic but never for Muse Sounds.  It's a very serious bug that gets reported quite often here, in the forums, social media, etc.  It would be *really* nice if someone could look at this (in #15306 presumably).

**Closed** 2024-02-08 13:31 UTC
Labels: duplicate, muse sounds
