### ISSUE TITLE
Changing time signature deletes formatting

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#23677] opened 2024-07-19 03:18 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

(See attached video).
1. Open the attached file (time signature formatting bug.mscz).
2. Select measure 6
3. Select the 5/4 time signature from the palette.
4. Observe the System breaks are deleted.
5. Also observe that what was formerly measure 35 has now become measure 29 (measures were deleted).

Notes.
If a different time signature is chosen instead of 5/4, such as 3/8, 6/8, 3/4 this problem will occur.
If the same time signature is chosen (i.e. 4/4) this problem doesn't occur.

Also note:
If one presses CTRL+Z to undo and if the measure remains selected, the problem doesn't occur again.  However, if you deselect the measure, and repeat the steps, it occurs.

Occurs on MuseScore Studio 4.3.2 but also occurs on latest nightly build below:
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242000306, revision: github-musescore-musescore-8e3b4f2

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/bf923c6c-49af-47e1-a486-d1517b71fc08

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Additional context

[time signature formatting bug.zip](https://github.com/user-attachments/files/16301605/time.signature.formatting.bug.zip)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by sammik** [comment] 2024-07-19 06:01
kind of duplicate of #15726 

also it is kind of by design (when you change 4/4 to 5/4 bars ends at different points /notes/)

**Closed** 2024-07-19 06:46 UTC
Labels: by design, duplicate, UX/interaction
