### ISSUE TITLE
[MU4 Issue] Bad rendition of custom slurs in imported MS3 files

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13906] opened 2022-10-23 09:47 UTC
**Describe the bug**

Open the attached MS3 file in MS3 and MS4. 
[ms3_custom_slurs.zip](https://github.com/musescore/MuseScore/files/9846163/ms3_custom_slurs.zip)

 Note the custom slur in MS3 on the second to last note in MM 1 and 2. It has become misshapen in MS4:

Passage in MS3:
![ms3_slurs](https://user-images.githubusercontent.com/87246583/197385239-d6d02759-97f5-49e4-8004-0b10d9b0da70.png)

Same passage in MS4:

![ms4_slurs](https://user-images.githubusercontent.com/87246583/197385260-9cfa5fda-426e-4926-aae6-ba77ecc64c62.png)

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

See also #13560.

**Comment by oktophonie** [comment] 2022-10-24 08:43
Duplicate of #13560, will be fixed by #13597.

**Closed by oktophonie** 2022-10-24 08:43 UTC
Labels: P1
