### ISSUE TITLE
[MU4 Issue] Style Dialog Takes Almost 20 Seconds to Open

### ISSUE THREAD

**Issue by hmturnbull** [musescore/MuseScore#15716] opened 2023-01-05 01:30 UTC
**Describe the bug**
In MuseScore 4.0, every time I click to open the Style dialog, it freezes for somewhere between 15 and 25 seconds before it opens.

**To Reproduce**
1. Go to 'Format -> Style...'
2. MuseScore freezes for around twenty seconds before the dialog opens.

**Expected behavior**
The Style dialog should appear pretty much instantly, as it did in version 3.6.2.548021803

**Video**

https://user-images.githubusercontent.com/52052397/210681934-d73ea78e-02eb-4d72-bd2f-f5e1e9da4c28.mp4

**Platform information**
- OS: Windows 10 Pro (64-bit), 19045.2364
- MuseScore version (64-bit): 4.0.0-223472200
  - revision: github-musescore-musescore-5485621

**Additional context**
This bug made it take a dreadfully long time to update my existing scores to MuseScore 4's (much improved) engraving style.

**Comment by oktophonie** [comment] 2023-01-05 11:56
Duplicate of https://github.com/musescore/MuseScore/issues/13193
(but yes, very annoying)

**Closed by oktophonie** 2023-01-05 11:56 UTC
