### ISSUE TITLE
[MU4 Issue] shift selecting a few notes selects everything within that note length

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14345] opened 2022-11-05 15:32 UTC
it's impossible to select only a few notes while holding shift.
Whenever I select more than one note when holding shift, automatically everything within the selected note's length gets selected. This makes copying only a portion of a chord or only one voice, when more than one is present in the same place, impossible. It would be so much nicer if one were allowed to copy a selection smaller than everything within the selected note's length. It would make voicing across instruments a lot easier. You could write the chord fully in a piano stave and then copy the necessary notes to the wanted instruments.

**Comment by MarcSabatella** [comment] 2022-11-05 16:14
This is by design - Shift creates a range selection, which by definition includes all content from a given start point to a given end point.  If you wish to exclude a particular voice fro the range selection, see View / Selection Filter

**Comment by Grim-O** [comment] 2022-11-05 16:31
I get that it is by design but I'm questioning if it's the right design choice. It limits flexibility and ease of use massively. Also, "from a given start point to a given end point" isn't even correct. e.g.: selecting the bottom 2 notes in a chord with 3 notes this way also selects the top note.

**Comment by MarcSabatella** [comment] 2022-11-05 16:46
Certainly, the whole notion of range selection could be revisited someday.  But for now, I'm just pointing out how to actually accomplish what you are trying to do.

When I said "from a given start point to a given end point", the definition of point is "staff & time position".  So, everything a given time position and staff that you specify as start point to a given time position and staff that you specify as end point  Indeed, that's all that a range selection is - those four pieces of information.  Staff staff, start time; end staff, end time.

**Comment by Tantacrul** [comment] 2022-11-21 16:31
It's worth mentioning that there are two types of 'multiple' selection:

Holding CTRL (Win) or COMMAND (Mac). Using this, you can select multiple elements.
Holding Shift: as described above

I think these two different options make it perfectly possible to do most of what you want.

They even work together. You can Shift-select elements and then CTRL-select to de-select anything unwanted.

I'm not sure this is something we'll change soon - and if we do it most likely won't solve this issue, so I'm going to close it.

**Closed by Tantacrul** 2022-11-21 16:31 UTC
