### ISSUE TITLE
[MU4 Issue] Chord symbols in transposed instruments do not play back properly transposed

### ISSUE THREAD

**Issue by WDMAsh** [musescore/MuseScore#13014] opened 2022-08-25 13:53 UTC
**Describe the bug**
Chord symbols in transposed instruments do not play back properly transposed.

**To Reproduce**
1. Create a score containing at least one non-transposing instrument, and at least one transposing instrument. My sample score uses piano and Bb trumpet.
2. Put chord symbols, appropriately transposed, in both instruments (in the same measures).
3. Play back score.

**Expected behavior**
The chords in the non-transposing and transposing instruments should sound the same.

**Platform information**
Windows 10
MuseScore 4.0 MuseScoreNightly-202208240453-master-3ee3c7e-x86_64

[MuseScore 4 chord transposition test score.zip](https://github.com/musescore/MuseScore/files/9425262/MuseScore.4.chord.transposition.test.score.zip)

**Comment by WDMAsh** [comment] 2022-09-09 12:36
**ADDENDUM**
This bug only occurs if Format > Score > Display in concert pitch is not ticked.

It is still happening with MuseScoreNightly-202209080453-master-7f4a1f9-x86_64

**Comment by Jojo-Schmitz** [comment] 2023-01-18 20:47
Isn't this a duplicate of the meanwhile fixed and closed #14487 ?

**Comment by cbjeukendrup** [comment] 2023-01-18 22:12
Looks very much like it. I'll close it then, but @WDMAsh if this still happens 4.0.1, we can reopen it.

**Closed by cbjeukendrup** 2023-01-18 22:12 UTC

**Comment by WDMAsh** [comment] 2023-01-19 02:37
@cbjeukendrup -- Confirmed, it's working properly for me in MuseScore 4.0.1. Thanks very much!

(And apologies for duplicating #14487 )

**Comment by Jojo-Schmitz** [comment] 2023-01-19 09:00
No need to apologize, #14487 is a duplicate of your ieeue here, came 3 months later.

The problem I see is: this issue (which is a serious regression) got reported back in August last year but not being actioned at all. Even #14487 had been reported in November already, still 4.0.0 got released with this bug.
