### ISSUE TITLE
Alto and Tenor Saxophone do not transpose chords properly in their Part view

### ISSUE THREAD

**Issue by MoltenReplica** [musescore/MuseScore#17079] opened 2023-03-30 18:06 UTC
### Issue type

Engraving bug

### Bug description

Chords in Alto and Tenor Saxophone Parts do not transpose correctly, despite appearing correct in the Main Score view.

For example, in this score I show parts for horns and rhythm section in concert pitch. 
![image](https://user-images.githubusercontent.com/123436120/228921377-ef036051-fb14-4d22-9c09-1609f4f0a11f.png)

Here's the same section with concert pitch turned off. All parts appear to transpose correctly and playback sounds as expected.
![image](https://user-images.githubusercontent.com/123436120/228921539-941ee4db-ba09-4375-8b35-837dcef0a476.png)

Looking at the trumpet part, we can see the correct transposition applied.
![image](https://user-images.githubusercontent.com/123436120/228921971-1c4b7c84-727f-490f-aab7-337d79e2b606.png)

However, in the tenor part, the chords are shown as concert pitch.
![image](https://user-images.githubusercontent.com/123436120/228922564-4a6eaa29-ebfd-4a79-a01d-0b982a49bc3a.png)

The alto saxophone also has chords shown in concert pitch, despite being transposed correctly on the main score.
![image](https://user-images.githubusercontent.com/123436120/228922920-4f6b0ab6-dfed-4406-9d0c-213bd64797c3.png)

Enabling concert pitch on a part causes the chords to be wrong.
![image](https://user-images.githubusercontent.com/123436120/228922728-db76dd26-25d4-4de5-bcbb-d7c20d5a9efe.png)

I've attached the score I've been experiencing this issue with here. 
[Dracula's_Castle_DRAGONZ_V3.zip](https://github.com/musescore/MuseScore/files/11114608/Dracula.s_Castle_DRAGONZ_V3.zip)

### Steps to reproduce

1. Create a score with alto or tenor saxophone
2. Add chord symbols to the part
3. View the part outside of the main score view

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

**Comment by oktophonie** [comment] 2023-03-31 09:46
Was this score originally created in 4.0.2 or in an earlier version? There were some issues with transposition in 4.0/4.0.1 which have been fixed by 4.0.2.
Unfortunately, a score with transposition errors of this sort won't be magically fixed when opened in 4.0.2; however, the parts can be corrected by regenerating them (in the File > Parts dialog). When I do that for the saxophones in this score, everything seems to be correct, but I'd be glad if you could confirm this. Unfortunately it does mean that any customisations made to the parts will be lost and will have to be redone.

**Comment by MoltenReplica** [comment] 2023-08-26 09:26
Sorry for the late reply. This score was originally created in a version of MuseScore 3.

**Comment by cbjeukendrup** [comment] 2024-03-24 23:24
This seems a duplicate of #19834, which has been fixed recently. If you re-enter the affected chords using the latest "master" nightly build from https://musescore.org/en/nightly-builds then it should work correctly. 
If it still doesn't work in the nightly build, we can reopen this issue.

**Closed by cbjeukendrup** 2024-03-24 23:24 UTC
Labels: engraving, regression_ms3
