### ISSUE TITLE
Window Menus open window-centered instead of at mouse position, often following freeze + crash

### ISSUE THREAD

**Issue by bmarwell** [musescore/MuseScore#24175] opened 2024-08-23 17:50 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Click on any menu, e.g. File, Edit or maybe even a "select instrument" menu from the mixer
2. The Menu opens screen-centered
3. Submenus will also open screen-centered, making mouse-navigation nearly impossible.

This is often followed by a freeze and crash.

This bug might appear on newer versions of Ubuntu as well, but as an Arch Linux user, I am prone to experience this earlier 😄 

### Supporting files, videos and screenshots

(sorry for not including the mouse cursor)

1.: Normal Screen

![2024-08-23T074101_screenshot](https://github.com/user-attachments/assets/d44caf9d-9042-4f21-9fdd-b8151e8dfa05)

2.: File Menu

![2024-08-23T074143_screenshot](https://github.com/user-attachments/assets/bcd676ae-d791-49ca-986c-5097619f5177)

3.: Select Instrument Menu from Mixer

![2024-08-23T074219_screenshot](https://github.com/user-attachments/assets/a08e8fd8-03b5-430e-a022-4e0e05fcb5c1)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Arch Linux, Endeavour OS

### Additional context

Happens when installed from: https://archlinux.org/packages/extra/x86_64/musescore/

The AppImage works fine.

Before closing this as "not our release", please consider that I compiled this package against the most recent Qt packages and therefore this bug might appear in future versions of Ubuntu / AppImage combinations. I want to prevent future users from running into this issue and give you a chance to fix it before it happens for other users.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-08-23 18:31
That's a known limitation of running 4.3.2 on Wayland, which is but one of the reasons that mode is disabled in the official builds.  But even in those unsupported third-party builds that didn't correctly disable it, you can force-disable it by setting QT_QPA_PLATFORM=xcb.

But no matter, this is fixed already for 4.4, due out in a matter of days, with a release candidate available for testing over in musescore.org (see the Announcements forum).

**Comment by cbjeukendrup** [comment] 2024-08-23 20:50
Indeed, as Marc says, this was a limitation but has been fixed with 4.4. You can download the RC at https://musescore.org/en/node/367322, and enable Wayland by setting the `QT_QPA_PLATFORM=wayland` environment variable. 

(Duplicate of #15285)

**Closed by cbjeukendrup** 2024-08-23 20:50 UTC
Labels: UI

**Comment by bmarwell** [comment] 2024-08-24 20:07
Hey, thanks for the quick info! Can't stress how much I appreciate those on-point information.
Thanks for pointing me to the 4.4 release and how to fix it on my existing installation, that is SO much appreciated!!
