### ISSUE TITLE
[MU4 Issue] Incorrect tremolo duration

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14176] opened 2022-10-30 02:44 UTC
**Describe the bug**
Notes with tremolo are played incorrectly.

**To Reproduce**
1. Apply tremolo to a note. Example (violins section):
![Screenshot 2022-10-29 194037](https://user-images.githubusercontent.com/10248807/198860095-0261d052-2a9b-4aff-a418-2d79d0181f88.png)
2. Play it. It's played incorrectly as four 4th notes.

**Expected behavior**
The example above should be played as sixteen 16th notes.

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment] 2022-10-30 12:43
Duplicate of #13913. Thanks for reporting!

**Closed by cbjeukendrup** 2022-10-30 12:43 UTC
