### ISSUE TITLE
Harp pedal dialogue window remains if double clicked

### ISSUE THREAD

**Issue by basaigh** [musescore/MuseScore#22604] opened 2024-04-27 19:06 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

After double clicking a harp pedial diagram, the background of the dialogue box does not disappear as expected.

### Steps to reproduce

1. Add a harp pedal diagram
2. Double click it
3. Try to click away and observe that the background box remains

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/53559772/dcc3f18f-d207-4bfb-9be5-bec81c9614b6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241101557, revision: github-musescore-musescore-49f06da

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2024-04-28 11:34
Putting this in the 4.3 project, since it would be a regression on 4.2.1 and I have a fix ready

**Comment by DmitryArefiev** [comment] 2024-04-30 11:21
Fixed in #22609

**Closed** 2024-04-30 11:25 UTC
Labels: UI, regression
