### ISSUE TITLE
Multi-measure repeats do not number properly

### ISSUE THREAD

**Issue by eduardo-svg** [musescore/MuseScore#16635] opened 2023-03-03 01:28 UTC
### Issue type

Engraving bug

### Bug description

Multi-measure repeats break the measure numbers.

Changing a measure to "always show" measure numbers in measure properties can fix this for one measure, and it seems to stay fixed after changing back to "auto".

Changing measure numbers to every measure in the style settings does not fix it.

### Steps to reproduce

1. Insert a multi-measure repeat
2. The number on the first measure of the next system following that multi-measure rest will be smaller than it should be. Only of the measures in the multi measure rest is counted properly and the rest are skipped.

### Screenshots/Screen recordings

![Screenshot 2023-03-02 at 7 25 09 PM](https://user-images.githubusercontent.com/59342442/222608109-f6d3901b-f11a-4ca9-9b2d-4759da2a186d.png)

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

macOS 13.1

**Comment by oktophonie** [comment] 2023-03-03 07:57
Duplicate of https://github.com/musescore/MuseScore/issues/16354 (fixed in master)

**Closed by oktophonie** 2023-03-03 07:57 UTC
Labels: duplicate, regression, engraving
