### ISSUE TITLE
Enter note "N" mode on "Drumset" cause crash

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19588] opened 2023-10-02 15:38 UTC
### Issue type

Crash or freeze

### Bug description

Enter note "N" mode on "Drumset" cause crash

### Steps to reproduce

1 Create Score "Drumset"
2 Enter "N" mode
3 Crash

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by zacjansheski** [comment] 2023-10-02 16:45
Hello, this is a duplicate of https://github.com/musescore/MuseScore/issues/19516

Closing and referring to that, thank you!

**Closed by zacjansheski** 2023-10-02 16:45 UTC
Labels: regression, crash
