### ISSUE TITLE
[MU4 Issue] Musescore crashes when current audio device gets disconnected

### ISSUE THREAD

**Issue by athibaul** [musescore/MuseScore#15182] opened 2022-12-15 01:27 UTC
**Describe the bug**
I'm getting crashes of Musescore 4.0.0 on Windows 10 when disconnecting the Bluetooth speaker to which Musescore is currently sending audio.

**To Reproduce**
1. Connect a bluetooth speaker
2. Open Musescore (no need to open a score)
3. Go to the Preferences and make sure the currently selected device is the bluetooth speaker
4. Turn off the bluetooth speaker
5. Musescore crashes

**Expected behavior**
Musescore doesn't crash (and possibly warns the user that there was a problem with the audio device)

**Platform information**
 - OS: Windows 10

**Additional context**
I'm using a Bose Revolve Soundlink as the external bluetooth speaker, but I suspect any audio device which can be disconnected would do.

**Comment by Eism** [comment] 2022-12-15 09:24
Thanks for reporting!
Duplicate of #15029

**Closed by Eism** 2022-12-15 09:24 UTC
