### ISSUE TITLE
[MU4 Issue] "Replace instrument" doesn't work as expected when used after "Change instrument" event added

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11929] opened 2022-06-08 10:58 UTC
Edited by @Tantacrul 

**Describe the bug**
From "staff/part properties" dialog, "replace instrument" only works on a measure where a 'Change Instrument' event is placed.

**See video**

https://user-images.githubusercontent.com/21022311/172718085-9d7d2b45-ef85-42bd-b67a-2beb39bce826.mov

**To Reproduce**
1. Create a new score (default template, treble clef/piano)
2. Adding "Change Instrument" event in measure 2, for "Horn in F"
3. Select any measure after measure 3, then right click and select "staff/part properties"
4. Now click "Replace instrument" and choose a Flute
5. Note that nothing happens
6. However if you change to a Flute on measure 2 (where the instrument change was set), it does work correctly.

--

Also note that if you select any measure after measure 2 and choose a Bassoon, it applies a clef change to the whole instrument but nothing else.

**Expected behavior**
The same as 'replace instrument' in MS3

**Comment by Tantacrul** [comment] 2022-06-08 13:02
I'm not getting this issue on MacOS. As long as I make the 'Replace' change on the measure where the original instrument change was, it updates correctly and replaces the name. However, if I chose any later measure, then replacing the instrument doesn't result in any change, which I think is a bug... but not a very bad one. @DmitryArefiev - can you check?

https://user-images.githubusercontent.com/21022311/172622791-c0e504d6-a67f-4bf7-8a00-1fd811b2830c.mov

**Comment by MarcSabatella** [comment] 2022-06-08 14:58
I missed this new issue and responded in the previous one - see https://github.com/musescore/MuseScore/issues/8587#issuecomment-1150025682.  Bottom line, everything works perfectly for me, sometimes.  Sometimes not.  It hadn't occurred to me the difference was which measure I selected to start Staff/Part Properties, but a quick test shows this does indeed seem to be true.

**Comment by Tantacrul** [comment] 2022-06-08 20:25
The only trouble is that it doesn't change the instrument for the whole score for me. If I don't choose the measure where the instrument change occurred, it just seems to do nothing instead.

**Comment by wizofaus** [comment] 2022-06-08 20:52
Re-tested and yes, sorry, I am seeing what you're seeing - if done on a measure *after* the change instrument event, nothing happens. If done on the actual measure it sort of works as expected, but also changes the *clef* for the whole score, which isn't expected, and when I tried with two measures selected, it didn't change the "To xxxx" text either.  Then it crashed on clicking on a clef...

**Comment by wizofaus** [comment] 2022-06-08 21:14
Somewhat related, there's an issue with key signature changes for "Change Instrument" events too: https://github.com/musescore/MuseScore/issues/11946, may make sense to fix together.

**Comment by wizofaus** [comment] 2022-06-08 22:16
BTW another related oddity - you can click OK in the Select instrument dialog without selecting anything which leaves you with the new instrument having no name and just "To" instruction in the score.

**Comment by wizofaus** [comment] 2022-08-01 20:56
Is this still something we plan to fix for v4.0? Happy to look at it. @Tantacrul

**Comment by Tantacrul** [comment] 2022-08-01 21:41
This issue is not happening in the latest nightly, which I just tested now. Not only does it change to the flute, the text updates too. If you can confirm you are happy, perhaps we should close this one?

**Comment by Tantacrul** [comment] 2022-08-28 17:57
I tested this again and the issue is still happening as reported. However, I think we should go a little bit further than V3 if we're going to fix this. In V3, when changing the horn to a Flute, it still says 'To Horn'.

In the video, when you change the instrument to a Flute (on any bar on or after an instrument change), the text should also update to say 'to flute', with appropriate key changes too.

@wizofaus - by all means have a go!

**Comment by wizofaus** [comment] 2022-08-28 19:51
Not a lot of spare time currently unfortunately!

**Comment by RomanPudashkin** [comment] 2022-12-12 13:23
fixed in https://github.com/musescore/MuseScore/pull/14804

@wizofaus please reopen the issue if you can still reproduce the bug

**Closed by RomanPudashkin** 2022-12-12 13:23 UTC
Labels: P2
