### ISSUE TITLE
[notation issue] grace note slur extending too far after deleting bars

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15410] opened 2022-12-20 00:48 UTC
**Describe the bug**
the grace slur loses its endpoint after bars before it are deleted,
pressing undo does not fix the slur placement, it has to be manually redone

**To Reproduce**
1. put a slur on a grace note after bar 1
2. delete the bars before that
3. see the slur gets extended too far

**Screenshots**
https://user-images.githubusercontent.com/120861729/208555413-03292ade-5933-48e2-9de9-26ea57bc2a5b.mp4

**Platform information**
windows

**Comment by Vykoiazon** [comment] 2022-12-23 00:56
[grace note problem.zip](https://github.com/musescore/MuseScore/files/10291253/grace.note.problem.zip)

**Comment by mike-spa** [comment] 2022-12-23 09:44
The problem is present on the release build (@oktophonie tested it as well) but it has been fixed on master. Be sure to grab the build labelled "master" ftom the nightlies when testing the latest development.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/93707756/209312668-81bbdf09-9e46-465e-a9fd-62dddd2cec53.png">

**Closed by mike-spa** 2022-12-23 09:44 UTC
Labels: P2
