### ISSUE TITLE
Musescore Memory Leak When Hiding a Vocal Part with 2 Voices in the Instruments Side Panel

### ISSUE THREAD

**Issue by callumjohnspiller** [musescore/MuseScore#24502] opened 2024-09-06 13:54 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Go to existing score with a vocal part with 2 voices throughout
2. Click the eye button in the left hand panel
3. Await the spinning wheel of doom and your system running out of memory

### Supporting files, videos and screenshots

<img width="412" alt="Screenshot 2024-09-06 at 14 48 08" src="https://github.com/user-attachments/assets/32e02253-a9a6-48bd-a236-1218abe85543">
[Screen Recording 2024-09-06 at 14.49.49.zip](https://github.com/user-attachments/files/16908950/Screen.Recording.2024-09-06.at.14.49.49.zip)

[diagnostic.zip](https://github.com/user-attachments/files/16908966/diagnostic.zip)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.1-242490810

### Regression

I was unable to check

### Operating system

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by callumjohnspiller** [comment] 2024-09-06 13:56
If I delete all the notes on the part, this problem is resolved, though the program still hangs slightly when hiding the part

**Comment by RomanPudashkin** [comment] 2024-09-06 13:58
Duplicate of https://github.com/musescore/MuseScore/issues/24431. But we already have a fix, you try it out:
https://github.com/musescore/MuseScore/actions/runs/10726246723/artifacts/1897956050

**Closed by RomanPudashkin** 2024-09-06 13:58 UTC
Labels: crash

**Comment by callumjohnspiller** [comment] 2024-09-06 14:01
> Duplicate of #24431. But we already have a fix, you can try it out: https://github.com/musescore/MuseScore/actions/runs/10726246723/artifacts/1897956050

Awesome, thanks! Must have missed this when looking at older issues :)
