### ISSUE TITLE
Hebrew language wrong translation

### ISSUE THREAD

**Issue by avibb444** [musescore/MuseScore#24900] opened 2024-09-24 08:08 UTC
### Issue type

Other type of issue

### Description with steps to reproduce

Installing version 4.4.2 on windows 11 Pro Education 23H2, system language hebrew, Musescore language Hebrew
Opening Settings show Hebrew
![musescore-1](https://github.com/user-attachments/assets/cd1285d7-62d7-4b40-901f-289ed48c4ed0)
already part of menus displayed in Arabic
Check for language updates, closing musescore, opening again
creating new document
![musescore-2](https://github.com/user-attachments/assets/6f9d068b-34d2-462f-8a0a-16d7a9cd2042)
all menus in arabic as well
Please correct this bug, we use this software for Government Exams

### Supporting files, videos and screenshots

2024-09-24T10:41:18.859 | INFO  | main_thread     | GlobalModule::onPreInit | log path: C:/Users/admin/AppData/Local/MuseScore/MuseScore4/logs/MuseScore_240924_104118.log
2024-09-24T10:41:18.859 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore 4.3.2, build number 241630831 ===
2024-09-24T10:41:18.888 | ERROR | main_thread     | LanguagesService::setCurrentLanguage | Error loading translator "C:/Program Files/MuseScore 4//locale/qt_he.qm" 
2024-09-24T10:41:18.892 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
2024-09-24T10:41:18.892 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
2024-09-24T10:41:18.893 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
2024-09-24T10:41:18.893 | INFO  | 2532            | <lambda_f5da7718a123e8d2b82e0508660fd079>::operator  | id: "cf3b964c403d4427a11ab06bd9b36af4" 
2024-09-24T10:41:19.413 | INFO  | main_thread     | DiagnosticsModule::onInit | success start crash handler
2024-09-24T10:41:19.523 | INFO  | main_thread     | WasapiAudioDriver::open | WASAPI: trying to open the audio end-point with the following sample rate - 44100
2024-09-24T10:41:19.523 | INFO  | main_thread     | WasapiAudioDriver::open | WASAPI: trying to open the audio end-point with the following samples per channel number - 1024
2024-09-24T10:41:19.524 | ERROR | 2268            | WasapiAudioClient::setStateAndNotify | ERROR: -2147024894 The system cannot find the file specified.
2024-09-24T10:41:19.524 | ERROR | main_thread     | WasapiAudioDriver::open | WASAPI: error open the device , trying to use closest supported format
2024-09-24T10:41:19.525 | ERROR | 2268            | WasapiAudioClient::setStateAndNotify | ERROR: -2147024894 The system cannot find the file specified.
2024-09-24T10:41:19.525 | ERROR | main_thread     | AudioModule::setupAudioDriver | audio output open failed
2024-09-24T10:41:19.525 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: C:/Users/admin/AppData/Local\MuseSampler\lib\MuseSamplerCoreLib.dll
2024-09-24T10:41:19.525 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
2024-09-24T10:41:19.526 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: MuseSamplerCoreLib.dll
2024-09-24T10:41:19.526 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
2024-09-24T10:41:19.611 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: C:/Users/admin/AppData/Local/MuseScore/MuseScore4/musescorecom_cred.dat
2024-09-24T10:41:19.611 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: C:/Users/admin/AppData/Local/MuseScore/MuseScore4/audiocom_cred.dat
2024-09-24T10:41:19.814 | ERROR | main_thread     | PluginsConfiguration::updatePluginsConfiguration | [401] הקובץ אינו קיים
2024-09-24T10:41:20.364 | WARN  | main_thread     | Qt              | QQmlApplicationEngine failed to load component
2024-09-24T10:41:20.364 | ERROR | main_thread     | <lambda_50de235aca691b1a6fc9211a568e635a>::operator  | error: qrc:/qml/platform/win/Main.qml:30:1: Type AppWindow unavailable

2024-09-24T10:41:20.364 | ERROR | main_thread     | <lambda_50de235aca691b1a6fc9211a568e635a>::operator  | error: qrc:/qml/AppWindow.qml:29:1: Type ApplicationWindow unavailable

2024-09-24T10:41:20.364 | ERROR | main_thread     | <lambda_50de235aca691b1a6fc9211a568e635a>::operator  | error: file:///C:/Program Files/MuseScore 4/qml/QtQuick/Controls.2/Fusion/ApplicationWindow.qml:41:1: plugin cannot be loaded for module "QtQuick.Controls.Fusion.impl": התוסף 'C:/Program Files/MuseScore 4/qml/QtQuick/Controls/Fusion/impl/qtquickcontrols2fusionstyleimplplugin.dll' משתמש בספריית Qt שאינה תואמת (6.2.0) [release]

2024-09-24T10:41:20.364 | WARN  | main_thread     | Qt              | qrc:/qml/platform/win/Main.qml:30:1: Type AppWindow unavailable
2024-09-24T10:41:20.364 | WARN  | main_thread     | Qt              | qrc:/qml/AppWindow.qml:29:1: Type ApplicationWindow unavailable
2024-09-24T10:41:20.364 | WARN  | main_thread     | Qt              | file:///C:/Program Files/MuseScore 4/qml/QtQuick/Controls.2/Fusion/ApplicationWindow.qml:41:1: plugin cannot be loaded for module "QtQuick.Controls.Fusion.impl": התוסף 'C:/Program Files/MuseScore 4/qml/QtQuick/Controls/Fusion/impl/qtquickcontrols2fusionstyleimplplugin.dll' משתמש בספריית Qt שאינה תואמת (6.2.0) [release]
2024-09-24T10:41:20.364 | ERROR | main_thread     | <lambda_cd4143d40f98de7a4038d3f55aa4ac10>::operator  | failed Qml load

2024-09-24T10:41:20.366 | INFO  | main_thread     | Profiler        | 

Main thread. Top 150 by sum time (total count: 28)
Function                                                    Call time         Call count        Sum time          
SoundFontRepository::loadSoundFonts                         88.289 ms         1                 88.289 ms         
InstrumentsRepository::load                                 45.476 ms         1                 45.476 ms         
LanguagesService::init                                      24.484 ms         1                 24.484 ms         
LanguagesService::setCurrentLanguage                        19.649 ms         1                 19.649 ms         
ShortcutsRegister::reload                                   8.307 ms          1                 8.307 ms          
ShortcutsRegister::readFromFile                             3.530 ms          2                 7.060 ms          
InstrumentsRepository::loadStringTuningsPresets             4.617 ms          1                 4.617 ms          
LanguagesService::loadLanguages                             4.555 ms          1                 4.555 ms          
ShortcutsRegister::mergeShortcuts                           0.552 ms          1                 0.552 ms          
ShortcutsRegister::expandStandardKeys                       0.242 ms          2                 0.485 ms          
SymNames::loadNameToSymIdHash                               0.361 ms          1                 0.361 ms          
AbstractCloudService::init                                  0.176 ms          2                 0.351 ms          
NotationActionController::init                              0.329 ms          1                 0.329 ms          
UiActionsRegister::updateShortcutsAll                       0.189 ms          1                 0.189 ms          
AbstractCloudService::readTokens                            0.083 ms          2                 0.166 ms          
ShortcutsRegister::makeUnique                               0.154 ms          1                 0.154 ms          
UiConfiguration::readThemes                                 0.098 ms          1                 0.098 ms          
UiActionsRegister::updateCheckedAll                         0.084 ms          1                 0.084 ms          
RegisterAudioPluginsScenario::init                          0.066 ms          1                 0.066 ms          
PluginsConfiguration::readPluginsConfiguration              0.055 ms          1                 0.055 ms          
KnownAudioPluginsRegister::load                             0.051 ms          1                 0.051 ms          
UiActionsRegister::updateEnabledAll                         0.017 ms          1                 0.017 ms          
InstrumentsRepository::loadMuseInstruments                  0.006 ms          1                 0.006 ms          
SlurSegment::avoidCollisions                                0.001 ms          6                 0.005 ms          
RecentFilesController::init                                 0.005 ms          1                 0.005 ms          
Workspace::rawData                                          0.001 ms          4                 0.004 ms          
UiContextResolver::currentUiContext                         0.003 ms          1                 0.003 ms          
ProjectAutoSaver::update                                    0.002 ms          1                 0.002 ms          

Other threads. Top 150 by sum time (total count: 1)
Function                                                    Call time         Call count        Sum time          
SynthResolver::resolveAvailableResources                    0.411 ms          1                 0.411 ms          

2024-09-24T10:41:20.366 | INFO  | main_thread     | App::run        | activeThreadCount: 0
2024-09-24T10:41:20.383 | WARN  | main_thread     | WinMidiInPort::stop | already stoped
2024-09-24T10:41:20.422 | INFO  | main_thread     | main            | Goodbye!! code: -1

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 Pro education

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Albergarri788** [comment] 2024-09-24 08:55
You have the option to contribute to the translation into Hebrew in Transifex by yourself

**Comment by avibb444** [comment] 2024-09-24 09:31
it is not the wrong translation it is a BUG in software that displays part of UI in wrong language. Nothing to do with wrong translation FYI

**Comment by RomanPudashkin** [comment] 2024-09-24 09:36
Duplicate of https://github.com/musescore/MuseScore/issues/24287

**Closed by RomanPudashkin** 2024-09-24 09:36 UTC
Labels: needs review, regression MS4
