### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by LMGMMel** [musescore/MuseScore#13777] opened 2022-10-15 15:07 UTC
**Describe the bug**
For every file I open, Musescore 4 reopens itself: it doesn't show all the open files in one workplace. 

**To Reproduce**
1. Go to 'Open new file'
2. Click on whichever file and repeat this twice
3. See error

**Expected behavior**
All files are shown in the same workplace (see screenshot from MuseScore 3)

<img width="1080" alt="Schermafbeelding 2022-10-15 om 17 06 34" src="https://user-images.githubusercontent.com/115885386/195993613-ded7983e-c219-4bbf-845e-48871834156c.png">

**Screenshots**
<img width="1077" alt="Schermafbeelding 2022-10-15 om 17 04 22" src="https://user-images.githubusercontent.com/115885386/195993515-1747ed1a-c082-484d-8d02-850b6a842a33.png">

**Platform information**
macOS

**Comment by HemantAntony** [comment] 2022-10-15 15:12
This is by design. With MU4, you can't have two files in a single instance

**Comment by LMGMMel** [comment] 2022-10-15 15:17
Can you explain me why you chose to design it like this exactly? I really liked the feature which enabled me to switch between different files quickly.

**Comment by HemantAntony** [comment] 2022-10-15 15:18
I'm not 100% sure why, But one major reason was to enable compatibility with VSTs. You couldn't do that in the old design

**Comment by cbjeukendrup** [comment] 2022-10-15 16:12
Yeah. This is currently rather a technical limitation than a deliberate design choice. I still hope that we can overcome it in the future.

Since this issue is essentially a duplicate of #12647, let's close it.

**Closed by cbjeukendrup** 2022-10-15 16:12 UTC

**Comment by MarcSabatella** [comment] 2022-10-15 16:46
You can switch between files quickly in MU4 using Alt+Tab, just as you would for switching between files in any other application that opens multiple windows.  Or for switching between multiple applications, for that matter.  At least, Alt+Tab is the shortcut in Windows and most Linux systems.  I assume macOS has something similar, perhaps Cmd+Tab.

**Comment by HemantAntony** [comment] 2022-10-15 16:49
You can also snap both windows side by side
