### ISSUE TITLE
[MU4 Issue] Only bottom note of tied chords play

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12767] opened 2022-08-10 21:18 UTC
**Describe the bug**
If two chords are tied together, only the bottom note plays

**To Reproduce**
1. Note input mode, enter a quarter chord C-E-G
2. Press R to repeat it
3. Press "+" to tie it to another repetition
4. Press Play
6. See error - only the "C" plays for the tied chord

**Expected behavior**
The full chord should play

**Screenshots**

![image](https://user-images.githubusercontent.com/1799936/184022052-a699fa53-3d46-46b2-85ae-aeb2a754c44a.png)

**Platform information**
 - OS: Linux

**Additional context**
See also https://github.com/musescore/MuseScore/issues/12613; my issue may or may not be a duplicate

**Comment by Tantacrul** [comment] 2022-08-15 16:17
Nice spot, Marc. This one has raised its head a few times in different guises. We're gradually squashing them all. I'm almost certain this is a regression because I recall it working very recently.

**Comment by vpereverzev** [comment] 2022-08-15 21:00
@Eism please check the tick range we're getting via notifications

**Comment by DmitryArefiev** [comment] 2022-08-18 10:16
Fixed in #12908

**Closed** 2022-08-19 09:39 UTC
Labels: P0
