### ISSUE TITLE
[MU4 Issue] Muse Sounds acts weird after a repeat

### ISSUE THREAD

**Issue by yoavshati** [musescore/MuseScore#14257] opened 2022-11-01 20:25 UTC
Using the barline repeat signs with Muse Sounds Winds (could be more general, I didn't check) causes playback weirdness such as random note clusters when there aren't even any written notes in the measure, transposition (I wrote for flute and oboe in thirds and it sounded like seconds), and stuttering.
The stuttering stayed even after deleting the repeat and restarting MuseScore

**To Reproduce**
1. Add some notes
2. Add repeat sign
3. Play using Muse Sounds

**Expected behavior**
The music play as if the repeats were unrolled

**Platform information**
 - OS: Windows 10

**Comment by MarcSabatella** [comment] 2022-11-01 20:43
There are a number of reports of this, so I'd consider this a duplicate of, for example, https://github.com/musescore/MuseScore/issues/13811

**Comment by Tantacrul** [comment] 2022-11-01 21:36
Duplicate of https://github.com/musescore/MuseScore/issues/13811

**Closed by Tantacrul** 2022-11-01 21:36 UTC
