### ISSUE TITLE
[MU4 Issue] Unable to open multiple different scores in the same MU instance + crashing

### ISSUE THREAD

**Issue by Kkyehh** [musescore/MuseScore#15286] opened 2022-12-17 20:26 UTC
**Describe the bug**
When opening or creating a score, instead of opening a new tab in the current instance, a new instance of MuseScore 4 is launched. This also occasionally causes the former instance to crash.

**To Reproduce**
1. Open a score
2. Open another score or create a new score
3. Sometimes, the former instance will close unexpectedly.
4. The new score will open in a new MU4 instance instead of in a new tab. If the former instance closed, the new instance will show the "last session closed unexpectedly" dialog

**Expected behavior**
It should have opened the score in a new tab, similar to parts and similar to how it works in MU3.

**Platform information**
 - OS: Win 11

**Comment by MarcSabatella** [comment] 2022-12-17 20:45
The new instance is deliberate.  The crash obviously is not.  In order for people to investigate, we would need you to attach the specific score causing the crash, and then rename this issue to focus on the actual issue - the crash.

**Comment by jeetee** [comment] 2022-12-18 10:38
Duplicate of https://github.com/musescore/MuseScore/issues/11340 for the multi-instance report.

"Needs Info" for the crash

**Comment by oktophonie** [comment] 2023-02-22 12:44
Closing as lacking info

**Closed by oktophonie** 2023-02-22 12:44 UTC
Labels: needs info
