### ISSUE TITLE
Adding glissando to grace note causes score to crash/close...

### ISSUE THREAD

**Issue by apbreaux** [musescore/MuseScore#22067] opened 2024-03-26 17:36 UTC
### Issue type

Crash or freeze

### Bug description

I've run into something that's not happened before - I added a grace note to an existing note, and then tried adding a glissando to the grace note, and my song crashed.

### Steps to reproduce

I was able to recreate this in a new score. Here's what I did:
1) Create New Score, Solo, Guitar + TAB.
2) Insert notes as shown in previous jpg. There are two parts: the C-quarter is Voice 2; the G-eighth, E-eighth, and D-eighth are Voice 1.
3) Insert 16th Grace notes for the G and E.
4) If you add a glissando (Slide out up) to the G and E of the Part 1 grace notes, without moving them, they work fine. However, if you move either of them, even a half-step, the score crashes once you try to add a glissando. I tried this with one other Glissando type (Slide in above) and got the same result.
<img width="96" alt="Screenshot 2024-03-26 075047" src="https://github.com/musescore/MuseScore/assets/153532580/59ed0e5f-1112-4a39-8d41-8a303b7118c7">

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment] 2024-03-26 17:42
Duplicate of https://github.com/musescore/MuseScore/issues/21563

**Closed by oktophonie** 2024-03-26 17:42 UTC
Labels: crash

**Comment by cadiz2** [comment] 2024-03-26 17:45
Described forum, see the conditions: https://musescore.org/en/node/362257#comment-1234939
