### ISSUE TITLE
[MU4 Task] Text font searchability in Properties for Text

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16520] opened 2023-02-24 01:32 UTC
For some reason, you can no longer search for a text font while editing text in Properties, it's only the drop-down menu now. A regression from MuseScore 3 and prior versions for seemingly no reason at all. Funny enough, you can still do this in Format>Style>Text Styles, but for some reason not in the Properties panel for individual text.

**Comment by octopols** [comment] 2023-02-24 08:40
An editable combobox should fix the problem but I'm not sure if we can change it's visual appearance to exactly match the rest of the UI. It would also be a nice feature to see what a font looks like while selecting a font.

**Comment by MarcSabatella** [comment] 2023-02-24 13:24
By "search for", do you mean the ability to type into the list to select?  If so, this is a duplicate of https://github.com/musescore/MuseScore/issues/16508

**Closed** 2023-02-24 13:42 UTC
Labels: duplicate

**Comment by ArsenJazzPiano** [comment] 2023-02-24 15:34
> By "search for", do you mean the ability to type into the list to select? If so, this is a duplicate of #16508 

Yes, I do mean that, as was the case (and introduced) in MuseScore 3. Though looking at the duplicate issue, it seems like that user is saying something else, but maybe that's just the wording and me misinterpreting. It should have the regression label on it at the very least.
