### ISSUE TITLE
Export to PDF:  Noteheads, Clefs, Time signatures are not displayed correctly (too small)

### ISSUE THREAD

**Issue by Christian150373** [musescore/MuseScore#23655] opened 2024-07-17 16:02 UTC
### Issue type

Import/export issue

### Description with steps to reproduce

Go to Export
Format: PDF file
Resolution: 360 dpi

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/88d74ce6-ba31-4d7a-b8c4-395963fcfd6f)
[Diagnostic.zip](https://github.com/user-attachments/files/16269141/Diagnostic.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241990305, revision: github-musescore-musescore-3b83778

### Regression

Yes, this used to work in a previous version of MuseScore (4.3.2)

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-07-29 15:17
Definitely a problem in Windows, but cannot reproduce in Linux! (as of 29 July nightlies)
Don't know about MacOS.

**Comment by cbjeukendrup** [comment] 2024-07-29 15:22
On macOS it looks fine with the latest nightly.

**Comment by igorkorsukov** [comment] 2024-07-30 14:36
fixed by https://github.com/musescore/MuseScore/pull/23834

**Closed by igorkorsukov** 2024-07-30 14:36 UTC
Labels: P0, os: windows, regression nightly
