### ISSUE TITLE
[MU4 Issue] Ctrl+Scroll is too aggressive on X11 with both mousewheel and touchpad

### ISSUE THREAD

**Issue by crispyricepc** [musescore/MuseScore#11198] opened 2022-04-14 13:09 UTC
Zooming in and out using the scroll wheel causes it to step 1000s of % at a time

**To Reproduce**
1. Open a score in any page view mode
2. Press <kbd>Ctrl</kbd>+Scroll in or out using either touchpad or scroll wheel
3. Observe the percentage change

**Expected behavior**
The view should zoom to the next level; i.e. from 100% to 125%

**Video Attached**

![demo](https://user-images.githubusercontent.com/16229426/163397084-aafcad7d-8d69-4264-9ce1-27635d4b4d2d.gif)

**Platform information**
 - OS: Linux
 - Desktop Environment: GNOME 42 (X11)
     - Also confirmed to be present on multiple machines using X11 with various versions of GNOME

**Comment by llui85** [comment] 2022-04-15 02:17
That's odd. I can't reproduce this on my end:

https://user-images.githubusercontent.com/47158068/163507266-849df4f7-e11b-407f-a65a-bb1843e4b43d.mov

`Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux`, `GNOME 3.38.5, Wayland`

**Comment by s1m0n-github** [comment] 2022-04-19 09:04
I can't reproduce this issue as well
https://user-images.githubusercontent.com/98892639/163969135-75cae7cc-f7c1-44dc-a2c0-2d5eb18b0161.mp4
`Linux 5.17.2-1-default #1 SMP  x86_64 GNU/Linux`, `GNOME 42, Wayland, openSUSE Tumbleweed`

**Comment by crispyricepc** [comment] 2022-04-19 10:00
I couldn't test with anything other than mouse + X11 on my NVIDIA desktop due to Wayland issues with the GPU drivers, but I just got my new laptop out which can run more extensive tests.

I can reproduce what @s1m0n-github is experiencing with my wayland laptop. Native wayland seems to be broken for now (I'll open another issue), so I tested with XOrg, XWayland with both touchpad and mouse. In general, XOrg is too aggressive with both the touchpad and mouse

**First test:** On XWayland (GNOME 41 wayland compositor)

https://user-images.githubusercontent.com/16229426/163978928-68026d3b-c18e-4d1c-98b7-988f9399b1a6.mp4

**Second test:** On XOrg (GNOME 41 Mutter)

https://user-images.githubusercontent.com/16229426/163979027-2cc7914a-b694-410e-af5f-1bf8db7e67bd.mp4

The second video is clearly showing much larger steps between Ctrl+Mousewheel and Ctrl+Two-finger touch

I don't think this warrants an urgent fix, since I would guess most linux users have migrated to wayland compositors, but it's *massively* annoying for anyone stuck on X11 due to their window manager of choice or graphics drivers not supporting wayland yet.

**Comment by iwoithe** [comment] 2022-04-23 11:09
I have the zooming issue on X11 as well (XFCE 4.16). A work around for this issue is go to Preferences -> Canvas and change `Mouse zoom precision` to 16 (which is the highest possible value). Zooming is still not as fine as I'd like, but it's much more workable.

**Comment by Gobbel2000** [comment] 2022-04-24 13:15
There is a fix for this issue at #10346. I haven't actually tested that with a touchpad but it most likely makes that work as expected too.

**Comment by Tantacrul** [comment] 2022-06-20 18:00
Curious to know whether this is an issue still. I see an old PR which hasn't yet been merged (although I've no idea whether it is mergable)

**Comment by oktophonie** [comment] 2022-06-20 19:51
Can confirm I experience this still, for one (single step of Ctrl+mousewheel goes straight from 100% to 1600%)

**Comment by MiguelGuthridge** [comment] 2022-06-30 15:33
Just checked on the latest nightly build, and it's still very much happening for me

**Comment by Jojo-Schmitz** [comment] 2022-07-15 19:10
A fix for that is in #10346, but for the 3.x branch. Needs to get ported to master

**Comment by bmarwell** [comment] 2022-07-15 20:12
> Curious to know whether this is an issue still. I see an old PR which hasn't yet been merged (although I've no idea whether it is mergable)

Hi Martin (@Tantacrul) – yes, this horrible UX bug is still a thing in the latest nightly.

The reason is well explained [on the forums on musescore.org](https://musescore.org/en/node/324840). The update of some xinput lib will change mouse sensitivity behaviour. Workaround is to downgrade a lib. `sudo downgrade xf86-input-libinput` on Arch Linux or Manjaro will do the trick. All other dists will follow the moment they update xf86-input-libinput v1.2.0 (or so).

I will cite @Gobbel2000 from that thread:

> I am getting the same issue on Arch Linux and have found out the culprit is the package xf86-input-libinput. On 2021-09-19 it was updated from 1.1.0 to 1.2.0 which sparks the problem. This is also why only rolling release distros are affected as of now, most distros won't have this update for a while.

So, that said, Ubuntu Jammy ships [xserver-xorg-input-libinput v1.2.1](https://packages.ubuntu.com/jammy/xserver-xorg-input-libinput). I'd expect more users affected by now.

Downgrading is a horrible, but doable fix on Arch/Manjaro. But it is close to impossible with Ubuntu and Debian as Package dependencies would not allow installation of older versions.

I will try to test the fix with MuseScore 4 master and report the results here.

**Comment by RomanPudashkin** [comment] 2022-07-18 08:35
This fix has been merged: https://github.com/musescore/MuseScore/pull/10346

Please check the problem again and reopen the issue if it is still present. Thank you!

**Closed by RomanPudashkin** 2022-07-18 08:35 UTC
Labels: P2
