### ISSUE TITLE
When deleting a grace note which is connected to a slur, the slur will still stay in the same position.

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#22836] opened 2024-05-15 08:02 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When deleting a grace note which is connected to a slur, the slur will still stay in the same position. Even with the whole series of grace notes deleted, the slur will still stay in the same position, only being deleted if you manually delete it.

### Steps to reproduce

1. Add a note and add 2 or more grace notes.
2. Add a slur to first and last grace note.
3. Delete the grace notes and the slur will still stay in the same position.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/169224604/dc48702d-9e53-4de0-abc6-2ee9feded2ba)

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment] 2024-05-15 08:16
Duplicate of https://github.com/musescore/MuseScore/issues/22563, fixed in master

**Closed by oktophonie** 2024-05-15 08:16 UTC
Labels: engraving, UX/interaction
