### ISSUE TITLE
[MU4 Issue] Theremin instrument doesn't make sound.

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#13235] opened 2022-09-07 23:31 UTC
**Describe the bug**
The Theremin instrument doesn't make sound.

**To Reproduce**
1. Create a Theremin instrument.
2. Add some notes.
3. Play them, and observe MuseScore's complete silence.
4. As a comparison, switch to, say, a piano instrument.
5. Observe MuseScore's normal sound.

**Expected behavior**
Sound from the Theremin instrument.

**Screenshots**
It would not be applicable to add screenshots to help explain your problem.

**Platform information**
 - OS: Windows 10
 - Version: Alpha 2

**Additional context**
I will not add any other context about the problem here.

**Comment by wizofaus** [comment] 2022-09-08 05:46
Is it switched on?  Are you sure you have your hands in the right position?  (j/k...)

**Comment by Jojo-Schmitz** [comment] 2022-09-08 07:56
The definition of Theremin is in https://github.com/musescore/MuseScore/blob/7f4a1f9f187f4d9cb31196e3a081089433b6d673/share/instruments/instruments.xml#L10905-L10927 and namely the sound is that of an Ocarina https://github.com/musescore/MuseScore/blob/7f4a1f9f187f4d9cb31196e3a081089433b6d673/share/instruments/instruments.xml#L10922
This is the same in MU3.
Yet I can confirm that in MU4 it doesn't sound, while in MU3 it does.
I guess it has to do with the soundfont?

**Comment by RomanPudashkin** [comment] 2022-11-18 10:57
Duplicate of https://github.com/musescore/MuseScore/issues/14527

**Closed by RomanPudashkin** 2022-11-18 10:57 UTC
