### ISSUE TITLE
Unable to open files with special characters like Chinese characters

### ISSUE THREAD

**Issue by CJJ-amateur-programmer** [musescore/MuseScore#24289] opened 2024-08-29 11:31 UTC
### Issue type

Opening/saving issue

### Description with steps to reproduce

1. Download (from https://musescore.org/zh-hans/download/musescore.msi) and install MuseScore v4.4.0.242390800 on Windows 11. 
2. Launch MuseScore, and create a new music score sheet. 
3. Save the sheet as "未命名乐谱.mscz". 
4. Quit MuseScore, then double-click on "未命名乐谱.mscz" to open it with MuseScore. Then an error will occur, as is shown in the following "Supporting files, videos and screenshots" area. 
5. However, if I drag the file into MuseScore window, or navigate to "File - Open" then select the file, nothing will be wrong. 
I've tried to re-run the installer to repair, but no luck! I uninstalled the latest version and roll back to v4.3.2, and this bug disappeared. 

### Supporting files, videos and screenshots

![ERROR](https://github.com/user-attachments/assets/3b086de6-12fd-4c22-87dc-b61537957b1c)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-08-29 11:38
Duplicate of #23811

**Comment by CJJ-amateur-programmer** [comment] 2024-08-29 11:49
> Duplicate of #23811

Quite sorry for that. I found it wrong with the latest version only, so I just checked for similar bugs reported within 3 days, with no result.

**Closed** 2024-08-29 11:52 UTC
Labels: regression MS4
