### ISSUE TITLE
[MU4 Issue] Crashing and corrupting files, sometimes specifically when using a tie

### ISSUE THREAD

**Issue by JordanTMM** [musescore/MuseScore#15490] opened 2022-12-21 20:51 UTC
**Describe the bug*
MuseScore constantly crashing and corrupting files, sometimes specifically when using a tie

**Expected behavior**
MuseScore should not crash when doing tasks 

**Platform information**
 - OS: Windows 11, MuseScore 4

**Comment by MarcSabatella** [comment] 2022-12-21 21:46
In order for people to investigate, you woulld need to attach your score (ZIP it or rename to end in ".zip" first) and give precise steps to reproduce the problem.

**Comment by Tantacrul** [comment] 2023-01-10 12:18
Agreed. We are tackling corruption issues now. If you could provide the score, that would be essential for us to investigate @JordanTMM 

Please also provide a video of the circumstances where you added the tie (or a screenshot) with more information. That would be really useful!

**Comment by cbjeukendrup** [comment] 2023-02-12 19:24
Since we haven't received any response on this, and most likely the cause of the corruptions (that were most likely the cause of this crash) has been fixed in 4.0.1, I will close this now.

**Closed by cbjeukendrup** 2023-02-12 19:24 UTC
Labels: needs info
