### ISSUE TITLE
musescore 4.4 on windows - error in rendering

### ISSUE THREAD

**Issue by sdwarwick** [musescore/MuseScore#22369] opened 2024-04-12 20:30 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Please see pictures included - After compiling locally following documented procedure, it appears that the rendering of all the musescore objects are offset from the window definition provided to Windows. The mouse doesn't work correctly either. you have to point above the actual menu item to highlight an option.

![muscscore](https://github.com/musescore/MuseScore/assets/7736675/27b60aae-2439-4764-89c0-1c267183527b)

![musescore_1](https://github.com/musescore/MuseScore/assets/7736675/c6adbf0f-54db-4557-808f-2a630a9069c7)

![musescore_2](https://github.com/musescore/MuseScore/assets/7736675/b81b3f1c-73ca-4ae7-a52a-52e9da89ef84)

note positions of the 4's are out of the box

![musescore_3](https://github.com/musescore/MuseScore/assets/7736675/78fdb614-7c7e-4d48-8c69-c4de68a9dd2d)

note that no gutter displayed, which includes information about what is currently selected

tried to get help on forum,  nothing suggested helped.

### Steps to reproduce

1. build and install musescore from a local git repository using either cmake -P  or msvc_build.bat
2. run musescore from install/bin directory
3. create new score 
4. see resulting display

### MuseScore Version

4.4 master 

### Regression

I don't know

### Operating system

windows 10

### Additional context

git version id  49b114b

**Comment by sdwarwick** [comment] 2024-04-13 19:11
I re-compiled musescore master,  replacing the following:
```
app.cpp:

    /*QCoreApplication::setAttribute(Qt::AA_UseOpenGLES);*/
    QCoreApplication::setAttribute(Qt::AA_UseSoftwareOpenGL);
```

This fixed the problem.    

I checked my display devices, found the following:
1.  Intel HD Graphics 4000 - openGL version 4.0.0 
2.  NVIDIA Quadro K1000M - opengl version 4.5.0 NVIDIA 372.95

This appears to be the same problem as:
[MU4 Issue] Transparent app border on Windows #8270 

Need further information as to what might need to be changed to solve this problem correctly in MuseScore

**Comment by sdwarwick** [comment] 2024-04-14 16:49
have also determined that commenting out the line:
```
/*QCoreApplication::setAttribute(Qt::AA_UseOpenGLES);*/
```
and setting the following environment variable also works:
```
 $env:QT_OPENGL = 'software'
```

**Comment by cbjeukendrup** [comment] 2024-04-18 14:46
Thanks for that resource. 

So basically the one problem here is that the content is visually offset w.r.t. the actual window; therefore, the mouse doesn't work correctly and the bottom bar falls below the border of the window.
There might be a connection to #8270, #22052 and #9968. Some of those have been fixed by apparently only partly.

The code in src/appshell/internal/platform/win/winframelesswindowcontroller.cpp might be relevant.

**Comment by sdwarwick** [comment] 2024-04-18 18:13
Have found that removing both of these references to OPENGL fixes this problem:

```
#ifdef Q_OS_WIN
    // NOTE: There are some problems with rendering the application window on some integrated graphics processors
    //       see https://github.com/musescore/MuseScore/issues/8270

	/*QCoreApplication::setAttribute(Qt::AA_UseOpenGLES);*/

      if (!qEnvironmentVariableIsSet("QT_OPENGL_BUGLIST")) {
        qputenv("QT_OPENGL_BUGLIST", ":/resources/win_opengl_buglist.json");
    }
#endif
```
and
```
#ifndef MU_QT5_COMPAT
    // Necessary for QQuickWidget, but potentially suboptimal for performance.
    // Remove as soon as possible.
   
    // QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);
#endif
```

not sure if there are other implications if this is done, but it is a solution.

**Comment by cbjeukendrup** [comment] 2024-04-19 00:36
Good work!

Unfortunately, that comment about QQuickWidget is still actual as far as I know; without that line, the app crashes when opening the Format > Style dialog, which makes use of QQuickWidget. 
There are two things we can do:
- find a way to embed QML into the EditStyle dialog without using QQuickWidget 
- rebuild the whole EditStyle dialog in QML. 

Ultimately, we want the second option, but that is a _lot_ of work, so we'd rather combine it with a redesign (instead of recreating the current design in QML now and then doing it yet again later when the redesign comes). So the second option is not feasible in the short term. Hopefully the first option is possible.

**Comment by sdwarwick** [comment] 2024-04-19 01:01
Is the problem only seen with that widget or more generally?
________________________________

**Comment by cbjeukendrup** [comment] 2024-04-19 06:19
Yes, currently `EditStyle` is the only place where we use QQuickWidget; however it's used multiple times within that dialog.

**Comment by sdwarwick** [comment] 2024-04-19 14:46
am seeing different behavior - Format -> Style actually is working for many of the settings  ( this is even using the 6.2.4 version of Qt) , however there are some that DO crash the program.   I'd be looking more closely at those to see what might be breaking them.     I'd start with using a newer version of Qt,  perhaps 6.7  to see if there are any problems that have been fixed on their end,  and then look closer at the specific settings that are causing the crash.   Thoughts?

**Comment by cbjeukendrup** [comment] 2024-04-19 19:10
Indeed, it crashes only on certain pages of EditStyle; namely exactly those that contain a QQuickWidget :)

Since the Qt documentation states explicitly that QQuickWidget is only functional with OpenGL, which is not the default anymore in Qt 6, it's quite certain that it just won't work, also not with a higher version of Qt. 
To be sure, I tried to try it out in my Qt 6.7 branch, but couldn't, because with Qt 6.7 the app won't even run at all, because some very obscure QML error (it doesn't know anymore what `QtObject` and `Component` are!). Time to try if it works with Qt 6.6, I guess...

**Comment by cbjeukendrup** [comment] 2024-04-25 10:47
Update: I later found that QQuickWidget _is_ supported again when not using OpenGL in Qt 6.5. Compare these:
https://doc.qt.io/qt-6.5/qquickwidget.html#performance-considerations
https://doc.qt.io/qt-6.2/qquickwidget.html#performance-considerations

So updating to Qt 6.5 would allow us to remove `QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);` which fixes this issue.
There are two things against updating to Qt 6.5: 
1. OS compatibility. Qt 6.5 drops support for macOS 10.14 so 10.15 becomes the minimum. This turns out to be a bit of a non-issue, because it seems that all Macs that can be updated to 10.14 can also be updated to 10.15, so there shouldn't be any Macs in the world that are stuck on 10.14. I'm not sure about the situation on other OSs though.
2. Bugs. Some things are mysteriously broken in qt 6.5. Most notably, the toolbars are not appearing. There is not a single indication of why this might be the case.

**Comment by cbjeukendrup** [comment] 2024-07-01 11:07
@sdwarwick Could you check if this was working correctly in MuseScore 4.3, and thus whether it would be a regression in 4.4? We'll need that info to determine how to prioritise this.

Switching to Qt 6.5 seems not a viable option right now, because it has significant inexplainable bugs and we're getting a bit too close to the 4.4 release date to do anything experimental. So for now, we'll have to try to avoid the usage of QQuickWidget, so that we can still remove that offending `setGraphicsApi` call.

**Comment by sdwarwick** [comment] 2024-07-01 15:03
Format -> Style seems to be working,  I tried a complete compile of the latest version and was able to make changes in some of the style settings.

The footer, window offset and mouse movement are still broken.

[cid:3ba8f966-a841-4d1d-a8d5-45c36fd8401b]



________________________________

**Comment by cbjeukendrup** [comment] 2024-07-01 15:06
My question was rather: did the window offset issue (and mouse movement issue and bottom bar issue, which are consequences of that) already occur in MuseScore 4.3, or is it a new problem in 4.4?

**Comment by sdwarwick** [comment] 2024-07-01 15:49
The current release version,  which I just downloaded, marked

OS: Windows 10 Version 2009 or later, Arch.: x86_64,
Muse Score Studio version (64-bit): 4.3.2-241630831, revision:
github-musescore-musescore-22b46f2

Does NOT show the problem.

The current source version downloaded from github and compiled locally DOES  show the problem.


________________________________

**Comment by cbjeukendrup** [comment] 2024-07-02 23:12
@sdwarwick Could you please try if https://github.com/musescore/MuseScore/pull/23438 does indeed solve the problem and that the format > style dialog still works correctly?

**Comment by sdwarwick** [comment] 2024-07-03 12:53
This PR DOES fix the problem with both the footer and style rendering!


________________________________

**Closed** 2024-07-05 15:21 UTC
Labels: needs info, P1, UI
