### ISSUE TITLE
Deleting a tie from a long tied note does not affect playback

### ISSUE THREAD

**Issue by ChristianLoizou** [musescore/MuseScore#19969] opened 2023-11-07 21:10 UTC
### Issue type

General playback bug

### Bug description

When creating a sustained note lasting 4 semibreves **using the 9-key** on the keyboard, and then deleting notes / ties from that note, playback is not affected and still plays the note at 4-semibreve length.

### Steps to reproduce

1. Create a long tied note: place a note on the stave, select it and press the 9-key to make a note four semibreves long.
2. Click the third semibreve and delete it. Optionally delete the fourth semibreve.
3. Click playback.

### MuseScore Version

64-bit: 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Choose option...

### Operating system

OS: macOS 13.5

### Additional context

OS: macOS 13.5
Arch.: x86_64
MuseScore version (64-bit): 4.1.1-232071203
revision: github-musescore-musescore-e4d1ddf

**Comment by MarcSabatella** [comment] 2023-11-07 21:16
I believe this is another duplicate of https://github.com/musescore/MuseScore/issues/15914

Seems to be a temporary glitch that fixes itself on the next edit that regenerates the playback info, or on save/reload.

**Closed** 2023-11-08 07:16 UTC
Labels: playback
