### ISSUE TITLE
[MU4 Issue] Musescore crashing when opening a project

### ISSUE THREAD

**Issue by BryanIsntDead** [musescore/MuseScore#16248] opened 2023-02-07 02:27 UTC
**Describe the bug**
Upon opening the attatched mscz file, MU 3 & 4 instantly crash with no warning.

**To Reproduce**
I don't know how to recreate the corrupted file, but just opening it in MU 3 & 4 instantly crashes the app.

**Expected behavior**
MU3 would normally say the file is corrupted, which it doesn't. I know MU4 doesn't do that as of now, but I don't think it would normally just close with no warning.

**Platform information**
 - Windows

**Additional context**
I really want to know if there is a way to make the file openable again because I spent a lot of time making this, and theres a lot I want to do with it. Thank you
[Upload.zip](https://github.com/musescore/MuseScore/files/10670951/Upload.zip)

**Comment by cbjeukendrup** [comment] 2023-02-08 22:44
Hi! I fixed the cause of this crash, and then in the fixed version of MuseScore I re-saved the file. Now it also seems to open again in the current version of MuseScore: 
[Give us this day 1 copy.mscz.zip](https://github.com/musescore/MuseScore/files/10690466/Give.us.this.day.1.copy.mscz.zip)

**Comment by BryanIsntDead** [comment] 2023-02-09 03:01
> Hi! I fixed the cause of this crash, and then in the fixed version of MuseScore I re-saved the file. Now it also seems to open again in the current version of MuseScore: [Give us this day 1 copy.mscz.zip](https://github.com/musescore/MuseScore/files/10690466/Give.us.this.day.1.copy.mscz.zip)

Thank you so much! I've worked at trying to get this back for weeks now!

**Comment by DmitryArefiev** [comment] 2023-02-10 15:25
Fixed in #16284

**Closed** 2023-02-10 15:26 UTC
Labels: P1

**Comment by DmitryArefiev** [comment] 2023-03-03 12:41
Retested on Win10
