### ISSUE TITLE
Relative volumes of drum kit instruments are lost in imported MS3 files

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18876] opened 2023-08-01 21:00 UTC
### Issue type

Other type of issue

### Bug description

If you import an MS3 drum kit score into MS4 the volume balance between instruments is altered. In particular the hihats, rides and other cymbals are much louder than they were in in MS3.

Two possibilities for the diference are:

* Note velocities are not being faithfully duplicated when MS3 files are opened in MS4. The latter possibility may have been covered by #17865 / https://github.com/musescore/MuseScore/issues/14768
* The percussion samples in MS4 are different in some way from MS3 (even though both appear to be the "Standard" drum set).

### Steps to reproduce

1. Open the attached file in MS3 and listen back to the short drum section on repeat. 
[ms3_std.zip](https://github.com/musescore/MuseScore/files/12233978/ms3_std.zip)
2. Do the same in MS4.

ACTUAL RESULT: The rides/hihats sound much louder in relation to the Bass drum in MS4 than in MS3.
EXPECTED RESULT: Relative levels should be approx. the same in both cases.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by RomanPudashkin** [comment] 2023-09-08 07:24
Duplicate of https://github.com/musescore/MuseScore/issues/14768

**Closed by RomanPudashkin** 2023-09-08 07:24 UTC
Labels: duplicate, needs review, regression_ms3
