### ISSUE TITLE
Assertion '__n < this->size()' failed

### ISSUE THREAD

**Issue by tobip** [musescore/MuseScore#20792] opened 2024-01-01 19:31 UTC
### Issue type

Crash or freeze

### Bug description

This bug happens at random times, either on start of musescore or at random actions in the musescore window. When actively working in musescore it crashes probably once per minute.

     /usr/include/c++/13.2.1/array:211: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = mu::engraving::PropertyValue; long unsigned int _Nm = 1433; const_reference = const mu::engraving::PropertyValue&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
     [1]    7535 IOT instruction (core dumped)  mscore

### Steps to reproduce

1. start musescore
2. crash happens

or
1. start musescore
2. open saved document
4. crash happens

or
1. start musescore
2. open document
3. add notes
6. crash happens

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Manjaro Linux

**Comment by MarcSabatella** [comment] 2024-01-01 21:14
Is this using the official AppImage, or a third-party build of some kind  The latter are often problematic.

If it's happening with the official AppImage, please try to see if you can find more precise steps to reproduce the problem.  If it happens with some specific score, please ZIP and attach it.

**Comment by tobip** [comment] 2024-01-01 21:24
Installation was from the official Arch packages: https://archlinux.org/packages/extra/x86_64/musescore/
Crash happens with any score or sometimes even before the gui is loaded.

**Comment by Jojo-Schmitz** [comment] 2024-01-01 21:26
Then report it to the Arch folks

**Comment by MarcSabatella** [comment] 2024-01-01 22:10
But please also let us know if happens the official AppImage.  If so, then we'd also need more detail about your system to understand why it crashes on yours but not others.

If it only happens with third-party builds like the ones the Arch folks create, that's something they'd have to figure out and fix in their build.

**Comment by tobip** [comment] 2024-01-02 08:01
The AppImage won't start on my system because of another problem:

```
kf.windowsystem: Could not find any platform plugin
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, xcb.

/tmp/.mount_MuseScPlbpwY/AppRun: line 26: 15776 Aborted                 (core dumped) "${APPDIR}/bin/mscore4portable" "$@"
```

**Comment by sammik** [comment] 2024-01-02 09:39
> But please also let us know if happens the official AppImage. If so, then we'd also need more detail about your system to understand why it crashes on yours but not others.

But I think, assertion fails dont happen in "production" AppImages, only in development builds. Am I wrong?

**Comment by Jojo-Schmitz** [comment] 2024-01-02 09:48
If it is in MuseScore code, but this looks like being in the C++ runtime

**Comment by MarcSabatella** [comment] 2024-01-02 14:06
You should be able to run the AppImage by setting QT_QPA_PLATFORM more appropriately for your particular setup.  If you need help, please ask on the official Support forum on musescore.org and provide more details on your environment.

**Comment by tobip** [comment] 2024-01-02 15:31
> You should be able to run the AppImage by setting QT_QPA_PLATFORM more appropriately for your particular setup. If you need help, please ask on the official Support forum on musescore.org and provide more details on your environment.

Thanks for the hint!
Indeed the AppImage seems to work fine, I will report to archlinux then.

**Comment by thesamesam** [comment] 2024-01-22 06:31
This assertion requires `-D_GLIBCXX_ASSERTIONS` or it won't fire.

**Comment by cbjeukendrup** [comment] 2024-09-11 23:18
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/20878

**Closed by cbjeukendrup** 2024-09-11 23:18 UTC
Labels: crash
