### ISSUE TITLE
[MU4 Issue] Tuplets produce strange lagging between notes (overlapping notes)

### ISSUE THREAD

**Issue by alago197** [musescore/MuseScore#14559] opened 2022-11-16 22:37 UTC
[sample1.zip](https://github.com/musescore/MuseScore/files/10026210/sample1.zip)
Using recent MuseSounds (Strings) library and a recent nightly (MuseScore version (64-bit): 4.0.0-223170414, revision: github-musescore-musescore-7b85777 , downloaded on November 13), everytime I use any kind of tuplet in a score, and even with slow tempo (see attached score), the instrument produces strange lagging sounds from notes in the tuplet.

Also reproduced on the original MU4 Beta2 download available from the announcement.

In the attached sample, I put alternating measures (using tuplets/not using tuplets).

**Expected behavior**
This should not happen (the lagging due to the tuplet)

**Screenshots**
See attached zip (sample1 score and mp3 export)

**Platform information**
OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, 

MuseSampler library:  0.2.4,  MuseSound Strings downloaded from MuseHub on November, 10.

**Additional context**

**Comment by cbjeukendrup** [comment] 2022-11-16 22:52
Also happens with MS Basic, so a playback events rendering issue rather than a Muse Sounds issue

**Comment by cbjeukendrup** [comment] 2022-11-16 22:54
Actually this looks very similar to #14220; maybe it's even a duplicate. Could you please check that one out?

**Comment by cbjeukendrup** [comment] 2022-11-16 23:03
Duplicate of #14220

**Closed by cbjeukendrup** 2022-11-16 23:03 UTC

**Comment by Tantacrul** [comment] 2022-11-25 15:55
Great example by the way. Thanks!

**Comment by alago197** [comment] 2022-11-25 19:06
> Great example by the way. Thanks!

My pleasure! Btw., what is (and sounds) really great, is your MuseSounds creature. Congrats!
