### ISSUE TITLE
Hotkeys ("t", delete) no longer work

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#25321] opened 2024-10-26 14:50 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

**Current behavior:**
"T" does not work in either context:

A) Regular edit mode:
1. place two adjacent notes of the same pitch
2. select the first, then type "t"

B) Note entry (step-time):
1. enter a note
2. type the duration of the next note
3. type "t" and enter the next note to create a note with the selected time value, tied to the first.

Similarly, the "delete" hotkey does not appear to work in any key combination.

### Supporting files, videos and screenshots

can't post a report without a supporting file:
[hotkey tie and delete.mscz.zip](https://github.com/user-attachments/files/17531000/hotkey.tie.and.delete.mscz.zip)

I haven't deleted the extra measures XD

### What is the latest version of MuseScore Studio where this issue is present?

 4.4.3-242971445, revision: eb6b367  (current release)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 12.6

### Additional context

Worked as recently as nightly  4.4.3-242830405 revision: ca149b1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment] 2024-10-26 15:02
See https://musescore.org/en/node/370765, https://musescore.org/en/node/370763#comment-1264795 and https://musescore.org/en/node/370763#comment-1264802.

**Comment by MarcSabatella** [comment] 2024-10-26 15:05
FWIW, the nightly builds use different preference settings than release builds, so I wouldn't necessarily read too much into the fact that a given nightly build worked differently - it was presumably working off a different shortcuts definition file.  It's not totally clear how widespread this is or if it was working as expected at 4.4.2.

**Comment by RhinoHaggis** [comment] 2024-10-26 15:09
argh sorry it's a duplicate.  I searched for "tie" and "hotkey" (?) in all issues open or closed.

This is the first time it's hit me.  Didn't personally have problems in 4.4.2.  I'm happy to reset prefs thanks for the workaround

**Comment by MarcSabatella** [comment] 2024-10-26 15:18
I dont' think it is a duplicate - the other reports I know of are on the forums or on social media.

There is https://github.com/musescore/MuseScore/issues/25314 regarding the diatonic transposition commands, but nothing else on GitHub regarding "T" for ties.

Shouldn't be a need to reset all preferences - I would think just resetting the affected shortcuts would do it.

**Comment by SteveBlower** [comment] 2024-10-26 15:52
There have been many reports of a missing T shortcut on the Forum.  It seems to affect only MACs.  Some seem to fix themselves e.g. https://musescore.org/en/node/370763#comment-1264807.  I have not yet seen on the Forum what the state of the Add tied note is for the users that are reporting this as most of them go for resetting preferences before reporting back.

**Comment by RhinoHaggis** [comment] 2024-10-26 16:21
Uh oh.  I also can no longer create accents by holding down a letter. 

 Normally (on a Mac) if you press and hold (e.g.) "e", you get an enumerated list of accent options rather than a string of eeeees.   For a long time this was wonky in Musescore: 
**Old Behavior:** you get a string of e's, then the accent dialogue, pick your accent, delete unwanted e's.

But it recently (4.2 or 3??) got fixed to
**New Behavior:** you get only ONE extra e.

**New New behavior:** lots of e's no dialogue at all.  (haven't used a version including nightlies that had this problem until the 4.4.3 release)

**Comment by DaveCos29** [comment] 2024-10-26 17:10
I'm having the same problem with the Delete key.  The larger one does work but I never use that because of where it's situated on the Mac keyboard.  I tried re-assigning but to no avail. This is on the commercial release of 4.4.3 not a nightly build
![image](https://github.com/user-attachments/assets/3b18fb42-267d-49a2-98c2-9af8a3cd3b8b)

**Comment by RhinoHaggis** [comment] 2024-10-26 21:13
I use keyboard shortcuts aggressively so I'll do some targeted experiments and report any other keys that don't respond to the "reset prefs" workaround.

**Comment by FrancRos31** [comment] 2024-10-26 21:22
@RhinoHaggis, you can check the open reports about shortcut and see if the bugs still occur in 4.4.3. 
Also, If there wasn't an italian word for it, I would have asked to the devs to make "hotkeys" the default, LOL.

**Comment by RhinoHaggis** [comment] 2024-10-27 15:05
well I'm using 4.4.3 so I think that question is answered.

**Comment by DaveCos29** [comment] 2024-10-27 15:13
I just tried it in the last 4.4.2 nightly build and the Delete key works fine.  It's something with 4.4.3 and for me, in Mac Sonoma on a Mac Mini M2 chip.  Some friends on Sequoia say theirs works fine but I'm not eager to jump to the new Mac OS so soon after its release

**Comment by RhinoHaggis** [comment] 2024-10-27 15:19
same experience here.  4.3 and forward only.  I have an older mac, OS Monterey.  So far, I haven't been pushed out of the window of "equivalent experience". 🤞  It seems like there still ought to be a bug somewhere in the code, unless the OSX compiler was updated before 4.3.  One thing about being at the end of an OS revision, I know it's not an update at my end that changed the behavior 😅

**Comment by DaveCos29** [comment] 2024-10-27 15:23
I realized that the 0 key on the number pad works pretty nicely and the same as the delete key for all intents and purposes.  I might try to use that more.  I'm left handed so usually my right hand is on the midi keyboard entering pitches while the left is on the number keys above the alpha keys to enter durations.  I mouse left handed too so I have avoided using the number pad up until today but I can see a lot of benefits to adopting this methodology.  

Worse case scenario, I will upate to Sequoia and hopefully it doesn't break my other trillion plug ins.

**Comment by RhinoHaggis** [comment] 2024-10-27 15:30
It took some methodical practice but I'm glad i learned to switch hands. For piano, I do note entry with whatever hand is written in the piano score, and keyboard entry with the other. The benefits are minor, but occasionally useful.

Isn't numbered 0 supposed to be insert, and .  delete?  XD

**Comment by cbjeukendrup** [comment] 2024-10-27 15:31
Interesting thought that this may be macOS-version-dependent. I'm on Sequoia and indeed can't reproduce this. I still have one (much) older Mac so I'm going to try tonight if I can reproduce it on that one. 

But it would be weird if this is the case. 4.4.2 was compiled on macOS 14.6.1, and 4.4.3 on macOS 14.7, both using Xcode 15.4 with the macOS 14.5 SDK. So you'd think that shouldn't make a big difference...

**Comment by DaveCos29** [comment] 2024-10-27 15:36
> It took some methodical practice but I'm glad i learned to switch hands. For piano, I do note entry with whatever hand is written in the piano score, and keyboard entry with the other. The benefits are minor, but occasionally useful.
> 
> Isn't numbered 0 supposed to be insert, and . delete? XD

the "." functions as a dotted duration on my system.

**Comment by DaveCos29** [comment] 2024-10-27 15:39
Okay so in a bizarre turn of events, I decided to re-assign the shortkey 0 key on the num pad on my Mac Magic keyboard to DELETE and guess what?  It fixed the delete key.  WEIRD!  But hey, I'm happy.

**Comment by DaveCos29** [comment] 2024-10-27 16:04
okay even more bizarre.  I reverted back to default for the Delete and NOW it works fine.  Whatever process I did fixed it.... 
Weird......

**Comment by RhinoHaggis** [comment] 2024-10-27 16:09
This did not work for me. :(  I think Num0 however is not delete, but "enter rest".  With a note selected it replaces it with a rest of the same value, mimicking delete.  But it won't delete text or rests in a second voice etc.

**Comment by DaveCos29** [comment] 2024-10-27 16:15
> This did not work for me. :( I think Num0 however is not delete, but "enter rest". With a note selected it replaces it with a rest of the same value, mimicking delete. But it won't delete text or rests in a second voice etc.

I think when I re-assigned the num pad 0, it fixed whatever logjam there was in the delete key (to be clear, the delete I am referring to is the one next to End above the arrow keys, not the larger Delete key).  It did work for me in terms of deleting highlighted events and clearing bars (not deleting them but clearing them).  That is what my small Delete key used to do up until 4.4.3 update from a couple days ago.  So now it's back to normal.  

I have found this in the past too.  I will have to clear and then re-assign a shortcut then revert to default and it clears up any issues.  The T = Tie shortcut also didn't work but all I did was to clear the shortcut, and assign using the T key again and it worked.

**Comment by RhinoHaggis** [comment] 2024-10-27 16:17
For me the effect was opposite.  Clearing and reassigning caused them to stop working altogether, and I had to reset preferences to get T and Backspace back.

**Comment by DaveCos29** [comment] 2024-10-27 16:18
oh wow!

**Comment by RhinoHaggis** [comment] 2024-10-27 16:22
we may have different experience with numberpad because I'm using a windows keyboard.  The functionality is partially crippled by that fact. For example number and scroll lock don't work at all, and some keys map strange values.  Num0 is not -for example- recognized as Num0, but as plain 0.  Mercifully the little delete key maps correctly.  Well. Before it stopped working.

**Comment by DaveCos29** [comment] 2024-10-27 16:24
oh yeah I'm sure that makes a difference.  I was tempted to use the wired
apple keyboard but I doubt that would have anything different from the
wireless magic keyboard in black.

**Comment by danielroseman** [comment] 2024-10-29 08:14
I have just encountered the bug with T not working after upgrading to 4.4.3 on a Mac running Sequoia OS 15.0.1.

I can confirm that the shortcut was correctly showing in the preferences: 
![image](https://github.com/user-attachments/assets/0052e345-8b3c-4125-89c4-e02ea30bfbfb)

Resetting preferences fixed the problem.

**Comment by zacjansheski** [comment] 2024-10-29 17:08
I have tried on two different macbooks, Sonoma and Big Sur and I have not reproduced an issue with "t"

Perhaps someone who can reproduce this issue can also check if https://github.com/musescore/MuseScore/pull/25273 resolves it?

**Comment by DaveCos29** [comment] 2024-11-01 00:23
I upgraded to Sequoia and now the delete key doesn't work again and my fix from the weekend doesn't work either.

**Comment by Jojo-Schmitz** [comment] 2024-11-05 11:59
This comes up multuple times a day, IMHO this warrants a 4.4.4

**Comment by cbjeukendrup** [comment] 2024-11-05 13:19
If only we could reproduce it... it may be useful to receive diagnostic files from someone who can reproduce it (Diagnostic > Save diagnostic files…)

**Comment by Jojo-Schmitz** [comment] 2024-11-09 10:24
Came up again in https://musescore.org/en/node/371449

**Comment by stuartizon** [comment] 2024-11-10 18:16
Both T and delete are broken for me too. Attaching diagnostics here.
OS: macOS 15.0, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

[Diagnostics.zip](https://github.com/user-attachments/files/17692517/Diagnostics.zip)

**Comment by cbjeukendrup** [comment] 2024-11-13 00:56
Thanks for the diagnostics file! 
That gives us at least _some_ steps to reproduce: download and unzip the diagnostics file, then in MuseScore, go to Preferences > Keyboard shortcuts, click Import, then select the shortcuts.xml file from the diagnostics ZIP. By doing so, I can confirm that this seems fixed by https://github.com/musescore/MuseScore/pull/25273.

**Comment by DaveCos29** [comment] 2024-11-13 13:31
Sorry Casper, yeah.  My bad.  Not sure what steps to take to resolve the
Delete key problem however. I'm not a programmer by nature (just a simple
composer) so some of the programming talk is over my head.

**Closed** 2024-11-15 14:31 UTC
Labels: needs info, regression MS4, UX/interaction

**Comment by cbjeukendrup** [comment] 2024-11-15 16:27
@DaveCos29 The easiest way to try out the fix, is if you _tomorrow_ go to https://musescore.org/en/nightly-builds, and download the latest _4.4.4_ nightly build for your OS. Alternatively, you can wait until the 4.4.4 update is released, which will most likely happen within a week.

**Comment by DaveCos29** [comment] 2024-11-15 16:37
Thanks for the tip! I will wait until the official release next week.
Thanks again!
