### ISSUE TITLE
[MU4 Issue] Half note (minim) single-note tremolos are all twice as long in duration as they should be

### ISSUE THREAD

**Issue by jlizhiyi** [musescore/MuseScore#14354] opened 2022-11-06 00:35 UTC
**Describe the bug**
See title. Single-stroke tremolo half notes are playing quarter notes, double-stroke tremolo half notes are playing eighth notes, etc. contrary to conventional music notation.

**To Reproduce**
1. Place a half note
2. Add any single-note tremolo to the half note

**Expected behavior**
Single-stroke tremolo should play eighth notes, double-stroke should play 16th notes, etc.

**Screenshots**

**Platform information**
 - OS: Windows 11

**Additional context**
This bug occurred on a file imported from MU3. These tremolos play correctly in MU3.

**Comment by cbjeukendrup** [comment] 2022-11-06 11:33
If this happens with Muse Sounds only, then it is a duplicate of #13913, so I'll close this issue for now.

If this also happens with MS Basic soundfont, please let us know. 

Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-06 11:33 UTC
