### ISSUE TITLE
[MU4 Issue] Playback doesn't start from selected bars, only notes.

### ISSUE THREAD

**Issue by FTGCocolandia** [musescore/MuseScore#11034] opened 2022-03-31 15:52 UTC
**Describe the bug**
In Musescore 3 you can select a bar and when you hit play it will start from beat 1 of that bar. 
In Musescore 4 playback only starts from a note, not a bar.

**To Reproduce**
1. Select a note.
2. Press Play.
3. Select a bar.
4. Press play.

The playback keeps starting from the note you selected before, not the last selected bar.

**Expected behavior**
Playback should start from the bar you selected last.

**Screenshots**
Musescore 3 behaviour:

https://user-images.githubusercontent.com/91145640/161097100-d97a8d14-6ce4-4c57-990c-6c0d50d0615b.mp4

Musescore 4 behaviour:

https://user-images.githubusercontent.com/91145640/161097142-6f0edb03-4e21-4563-a3c3-294f0ed7ae5f.mp4

**Platform information**
 - OS: Windows 10

**Additional context**
None.

**Comment by cbjeukendrup** [comment] 2022-03-31 16:23
Duplicate of / related to #10732 

Thanks for reporting!

**Closed as completed by cbjeukendrup** 2022-03-31 16:23 UTC
