### ISSUE TITLE
[MU4 Issue] Unrelated elements in parts are moving to different position

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#16005] opened 2023-01-22 08:59 UTC
**Describe the bug**
The attached score started as a download from musescore.com (older MS version) and has been open in MS4.
After opening, I have reset all element positions and reset the styles to default.
I did not like the parts, so wanted to remove these from the score. I had to unzip the musescore file to be able to do this and re-zip it.
I then added a few more instruments and made some updates, and now want to work on the parts.
I generated all parts and have to make some corrections. 
One correction to make is the position of the rest in voice 3 placed in measures where there is a glissando.
In the demo here, I select the Repiano part and, in measure 9, move the rest down by clicking the down arrow key (after selecting the rest by clicking with the mouse).
The two accidentals in measure 20 now suddenly move up.
Similar in measure 57 when moving the rest down, the accidental in measure 62 is moving.

![Elements-moving](https://user-images.githubusercontent.com/13550012/213907630-8b3e9b58-f17c-4a9a-9cd6-08b4a58b379a.gif)

 Something weird seems to be happening with the measure number in the status bar as well. For instance, when I select measure 20 the status bar shows it is measure 6 starting at beat 9. While this measure is the 7th (if you count the multi-measure rests as 1).
![image](https://user-images.githubusercontent.com/13550012/213907745-e0bb8cee-e02c-4d9a-8645-93771bee7ac4.png)

**To Reproduce**
1. Open attached score
2. Select the Repiano part
3. Click the rest in measure 9 (first measure after the first multi-measure)
4. Press down arrow key
5. See result

**Expected behavior**
Elements should not move when they are not related.

**Attachment**
MS file renamed to .zip
[Megalovania - test - with parts.zip](https://github.com/musescore/MuseScore/files/10474035/Megalovania.-.test.-.with.parts.zip)

**Platform information**
 - OS: Windows 11, MS4 4.0.1

**Comment by oktophonie** [comment] 2023-01-22 09:56
Duplicate of https://github.com/musescore/MuseScore/issues/15475, fixed by https://github.com/musescore/MuseScore/pull/15516 (in master)

**Closed by oktophonie** 2023-01-22 09:56 UTC

**Comment by henkdegroot** [comment] 2023-01-22 10:36
Apology, I should have tested using latest master as well. Indeed fixed in that.
