### ISSUE TITLE
Aux-sends Reverb: CPU cores spike to 100% after Playback goes to silence (4.1-Dev Nightly 20230618) 

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#18037] opened 2023-06-18 21:03 UTC
### Issue type

General playback bug

### Bug description

Problem:

With new built-in Aux-Sends Reverb enabled, after the initial playback goes to "silent" for about 30 seconds, 2 CPU cores spike to 100%.

Environment:

*  Ubuntu 22.04LTS/64-bit, SSD, 8-core i7-3rd gen Dell Latitude Laptop (ancient)
*  MuseScore 4.1-dev Nightly 20230618 (MuseScoreNightly-231690309-master-b79c97b-x86_64.AppImage)
*  MSBasic Only (no MuseSound, MuseHub not installed) 
*  Marc Sabatella "MS3 soundfonts" are installed but not activated/used

### Steps to reproduce

Steps to Reproduce:

1. Install and run Linux CPU monitor tool of choice (e.g., htop)
2. Start Musescore Nightly 4.1-Dev
3. Load the test score (attached)
4. Verify Aux-Sends Reverb buttons are "on"
5. Observe that CPU load is nominal
6. Hit the play button, music will start
7. Start your stop watch T=0.0sec
8. Continue to play into blank measures OR until end of score OR pause the playback
8. About T+30 seconds of silence, 2 CPU cores will spike to 100%

Repeat steps 1-9 except Aux-Sends Reverb disabled (step 4) - CPU remains nominal.

Other observations

*  After the initial playback, "silent audio" will cause Reverb going unstable, and the CPU spikes to overload after 30 seconds.
*  Stopping playback continues to peg 2 CPU cores at 100%
*  Rewinding to start of score continues to peg 2 CPU cores at 100%
*  Playing back the audible measures again, will temporarily restore CPU core back to nominal, until 30 seconds of silence thereafter.

### Screenshots/Screen recordings

[CPU-Overload-Test.zip](https://github.com/musescore/MuseScore/files/11782596/CPU-Overload-Test.zip)

### MuseScore Version

MuseScoreNightly-231690309-master-b79c97b-x86_64.AppImage

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by DmitryArefiev** [comment] 2023-06-23 12:02
I **can reproduce** it on my **LinuxUbuntu 22.04**. 
I have spike from **~9** to **~28** and it also **remains after playback stops**
![Screenshot from 2023-06-23 14-54-57](https://github.com/musescore/MuseScore/assets/90187801/eadad2de-4799-4cdd-9923-3f9315aae608)
![Screenshot from 2023-06-23 14-55-18](https://github.com/musescore/MuseScore/assets/90187801/9e1019bd-5986-4719-a025-e7109b6e7729)

Can't reproduce it on Win10/Mac13

**Comment by MarcSabatella** [comment] 2023-06-23 13:14
I hadn't tested with/without reverb to confirm that's the problem, but I had also noticed excessive CPU use even when idle using recent builds.  I'm not sure about the current status of 4.1 on Linux; latest announcement on Discord says not ready yet because of an issue - is this it?

**Comment by oktophonie** [comment] 2023-06-23 13:17
No.

**Comment by MarcSabatella** [comment] 2023-06-23 16:12
I can confirm the CPU spike issue.  During playback CPU usage goes up as expected.  When playback stops, CPU usage goes back down, as expected.  But then after a period of 10-30 seconds, suddenly without nthing else going on, CPU suddenly goes back up.  Usage stays up until I close the score.  And if I repeat the experiment but first disable the aux send reverb (I did that in the channels for the instruments themselves) this does not happen.

**Comment by RomanPudashkin** [comment] 2023-06-26 12:29
@ShawTakeuchi @MarcSabatella please try this fix. Thanks!
https://github.com/musescore/MuseScore/pull/18186

**Comment by MarcSabatella** [comment] 2023-06-26 13:41
Unfortunately I can't test that fix without the fix to the build issue that prevents me from being able to start.  But once that is merged, then I could test a new build of this PR against the updated master.

**Closed** 2023-06-28 12:54 UTC
Labels: P1, playback
