### ISSUE TITLE
Abnormal loudness mismatch (when Play repeats unchecked)

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22862] opened 2024-05-16 12:54 UTC
### Issue type

General playback bug

### Bug description

A very strange unjustified loudness change during playback.

### Steps to reproduce

I cannot describe exactly when and under what circumstances this happens. You'd better watch the video attached below.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/2010d67b-6d8a-4134-aefb-a3fa125790c4

https://github.com/musescore/MuseScore/assets/134041121/7792b806-842f-4161-9460-5848598d7863

[Can-can.mscz](https://drive.google.com/file/d/11_pnfATrncIZejxdRI-wIYhRQhN5romr/view?usp=drive_link)

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in MuseScore 4.0.2

### Operating system

Windows 11

### Additional context

This happens not only with brass wind instruments (as shown in the video), but with all instruments.

**Comment by Dima-S-Jr** [comment] 2024-05-16 17:39
Please check if this problem is reproducible for you 
[Can-can.mscz](https://drive.google.com/file/d/11_pnfATrncIZejxdRI-wIYhRQhN5romr/view?usp=drive_link)

**Comment by bkunda** [comment] 2024-05-17 13:33
@zacjansheski pls check for reproducibility.

**Comment by DmitryArefiev** [comment] 2024-05-21 13:25
@Dima-S-Jr Weird issue.. But I **can't reproduce** it on my end (4.3, Windows10):



Uploading bandicam 2024-05-21 16-17-26-671 (2).mp4…

**Comment by Dima-S-Jr** [comment] 2024-05-21 13:43
> @Dima-S-Jr Weird issue.. But I **can't reproduce** it on my end (4.3, Windows10):
> 
>  bandicam.2024-05-21.16-17-26-671.2.mp4

@DmitryArefiev, I just checked it out. Yes, it doesn't work if there is a check mark next to "Play repeats". Try to remove the check mark from there. It works for me. 
[can-can (rev.)](https://drive.google.com/file/d/1qqoFnZnjKNssJZkXQDJWyQxk90mrIfkd/view?usp=sharing)

**Comment by Dima-S-Jr** [comment] 2024-05-21 14:29
This is a regression from **4.1.0**

**Comment by DmitryArefiev** [comment] 2024-07-18 10:16
Looks like it was logged before as #21152 

@Dima-S-Jr I close this as duplicate so not have 2 similar issues (but will mention your case in #21152  to double check it after fix)
Thanks for logging!

**Closed by DmitryArefiev** 2024-07-18 10:16 UTC
Labels: P2, regression MS4, playback

**Comment by DmitryArefiev** [comment] 2024-07-19 11:21
Fixed in #23671
