### ISSUE TITLE
Muse Sounds Microtonal playback has issues at 50 cents

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#19413] opened 2023-09-15 17:43 UTC
### Issue type

Muse Sounds bug

### Bug description

See video. Microtonal playback is working now but 50 cents sounds as 100 cents. Other cent settings sound correct.

### Steps to reproduce

Watch video:
https://www.dropbox.com/scl/fi/vya8zzjl6v0wc8m5nsf3y/Microtonal_Issues_2.mov?rlkey=jtjrocsg5nfuotxcg0as16zud&dl=0

### MuseScore Version

4.1

### Regression

No.

### Operating system

MacOS

**Comment by Tantacrul** [comment] 2023-09-15 17:44
Pretty sure this is on the Muse Sounds team. Working with @iamtesch to help test it.

**Comment by DaffodilAura** [comment] 2023-09-21 16:50
In taking stock of what's happening with #19471, I think I have an idea as to part of the cause of this issue.  MuseSounds apparently interprets detuned notes relative to the note that's closest, so, for example, a C that's tuned to 50.94 cents sharp will be interpreted as a C# that's been tuned 49.06 cents flat, so, since notes that have been detuned exactly 50 cents are equally far from both adjacent pitches, the system that's been put in place for Microtonality, doesn't know what to do, and so it defaults to an earlier behavior.

**Comment by DmitryArefiev** [comment] 2023-11-22 10:38
**Can't reproduce** it now (4.2 master, Win/Mac)

**Closed** 2023-11-22 10:39 UTC
Labels: P1, playback, muse sounds

**Comment by Tantacrul** [comment] 2023-11-22 11:57
Yes, a MuseSampler update has been pushed after I tested it. This issue should be gone now. Thanks @DmitryArefiev!

I forgot to address this myself.
