### ISSUE TITLE
[MU4 Issue] Indentation shouldn't be applied to pre-3.6 score that already have horizontal frames at the start of the first system

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7817] opened 2021-03-29 22:53 UTC
**Describe the bug**
Indentation shouldn't be applied to pre-3.6 score that already have horizontal frames at the start of the first system

**To Reproduce**
1. Create a score with horizontal frames at the start in MuseScore 3.5.2 or below
2. Open this score in MuseScore 4

**Expected behavior**
Indentation shouldn't be applied to pre-3.6 score that already have horizontal frames at the start of the first system

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Windows 10

**Additional context**

**Comment by wizofaus** [comment] 2021-07-10 20:46
Could you possibly attach a score that reproduces this @vshalkevich - don't think I have enough disk space to install v3.5!

**Comment by Tantacrul** [comment] 2022-04-30 11:23
Closing, since I can't replicate the issue.

**Closed by Tantacrul** 2022-04-30 11:23 UTC
Labels: P2
