### ISSUE TITLE
Octave Transposing Clefs

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25757] opened 2024-12-07 00:58 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

According to _Music Notation: Preparing Scores and Parts_ by Matthew Nicholl and Richard Grudzinski (Berklee Press),
>"In the concert [pitch] score, all parts appear exactly how they sound except instruments that transpose at the octave, such as bass and guitar. These instruments are always shown at written rather than sounding pitch. So, in both transposed or concert score, the guitar, bass, glockenspeil [sic], and piccolo parts are written the same way."

Musescore, however, writes these in 8va-type clefs when "concert pitch" is selected. This should be corrected.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/ca56e899-7340-47bd-a97d-ff27d02b0e6f)
![image](https://github.com/user-attachments/assets/f790b455-fd82-478d-946e-fcf437b2cf79)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445   Revision: eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

Issue #21765 deals with this problem, but does not mention the standard practice.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Dima-S-Jr** [comment] 2024-12-07 08:06
1. I do not advise you to mention any notation manuals at all. This is useless for professionals, because they are guided by different views (see the [comment](https://github.com/musescore/MuseScore/issues/22175#issuecomment-2061069031)). Although, of course, it is better to stick to some well-established base, but just about that - below.
2. I don't quite agree with Matthew Nicholl and Richard Grudzinski. I know other authors who claim the opposite. The essence of the concert score is to show how the instruments are notated in actual pitch. The absence of octave-transposed clefs refutes this, because they do not show the octave transposition of the instrument. Yes, you _can_ omit octave-transposed keys, but then at the beginning of the score (if the score is concert) You should write about it, for example: 
"Score written at actual pitch with the exception of the following instruments: 
(a) piccolo, xylophone, and harp harmonics sound one octave higher than written; 
(b) glockenspiel sounds two octaves higher than written; 
(c) contrabass clarinet, contrabassoon, and double bass sound one octave 
lower than written."

**Comment by oktophonie** [comment] 2024-12-07 08:19
Basically a duplicate of https://github.com/musescore/MuseScore/issues/21765 anyway (see also https://github.com/musescore/MuseScore/issues/25357)

**Closed by oktophonie** 2024-12-07 08:19 UTC
Labels: engraving
