### ISSUE TITLE
Inconsistent behavior when adding note to create chord across bar line

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#16977] opened 2023-03-22 19:47 UTC
### Issue type

UI bug

### Bug description

Let's say there already is a note at a specific time (x-position). Clicking above/below it creates a new note. Yay, great!

However, if the existing note crosses the bar line, the existing note is *replaced*. That's a bit confusing.

In fact, I still don't really know how entering notes is supposed to work for this case. I thought clicking just adds notes? How can I add a note here?

### Steps to reproduce

1. Open a new blank partiture in MS4, the only instrument being a flute (most other instruments probably also work)
2. Click the eight-note-interval selector in the toolbar, then press "g" on the keyboard to enter a "G"
3. Click the quarter-note-interval selector in the toolbar, then press "a" on the keyboard four times (Checkpoint: the last note should now cross the bar line; this is where the screencapture below starts)
4. Using the mouse, click atop the first "A", to create an additional "C"
5. Using the mouse, click atop the second "A", to create an additional "C"
6. Using the mouse, click atop the third "A", to create an additional "C"
7. Using the mouse, click atop the fourth "A", to create an additional "C"

Expected behavior: The first, second, third, and fourth mouseclicks atop "A" behave the same way; ideally adding an additional "C".

Actual behavior: The first, second, and third mouseclick behave as expected, but the fourth click *replaces* the existing note.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/2690845/227018903-8b2dfdcd-7d66-497a-b4b5-4ff84ee02bda.mp4

### MuseScore Version

OS: Debian GNU/Linux bookworm/sid, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Debian

**Comment by cbjeukendrup** [comment] 2023-03-22 23:19
Isn't this a duplicate of #16317?

**Closed** 2023-03-23 00:23 UTC
Labels: UI
