### ISSUE TITLE
[MU4 Issue] Crash when declining update then using search bar in New Score dialog

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#15870] opened 2023-01-14 03:51 UTC
**Describe the bug**
If the New Score dialog is shown and MuseScore prompts you to update and you select either "Remind me later" or "Skip this version," then proceed to type something in the Choose Instruments search bar, MuseScore crashes.

**To Reproduce**
1. Open MuseScore 4.0.0. When prompted to update, select "Remind me later."
2. Open an existing score
3. Press CTRL + N to create a new score
4. A new window opens, and the Select Instruments dialog opens. A few seconds later, the prompt to update appears again.
5. Click "Remind me later" or "Skip this version."
6. Immediately type something into the search bar (on the Choose Instruments page). Musescore crashes.

**Expected behavior**
MuseScore doesn't crash.

**Platform information**
 - OS: Windows 11, Windows 10
 - Version: 4.0.0 (so that the prompt is shown to update to 4.0.1)

**Comment by DaddyLudwig** [comment] 2023-01-14 04:16
I don’t get the crash on Windows 10, also MuseScore 4.0.0

**Comment by GabeS573** [comment] 2023-01-14 05:04
> I don’t get the crash on Windows 10, also MuseScore 4.0.0, unless I search for an instrument with the search bar that is, if I just click to find the instrument, everything works fine.

@DaddyLudwig Just to clarify, does it crash for you also when declining the update, then immediately typing in the search bar?

**Comment by DaddyLudwig** [comment] 2023-01-14 06:54
Yes, that's what I did when I edited it to include "unless I search for an instrument with the search bar". If I don't use the search bar at all, it doesn't crash on me.

**Comment by GabeS573** [comment] 2023-01-14 07:06
Sorry, it wasn't entirely clear to me at first. I'll update the description to reflect this.

I'd do more testing, but I'm not sure how to get the update dialog to show up again after I clicked the "Skip this update" option.

**Comment by GabeS573** [comment] 2023-03-13 23:47
This happened again in 4.0.1, when the prompt to update to 4.0.2 is shown.

**Comment by Eism** [comment] 2023-06-28 10:36
I cannot reproduce it in [the latest build for 4.1]( https://github.com/musescore/MuseScore/actions/runs/5391362948), but I can reproduce it in 4.0.2 (by enabling checkForUpdateTestingMode in DevTools->Settings). However, I believe that showing the update dialog in a new instance at startup isn't correct, so I have disabled this behavior. see #18241

@GabeS573 @DaddyLudwig could you please check [the latest build for 4.1]( https://github.com/musescore/MuseScore/actions/runs/5391362948)? enable checkForUpdateTestingMode in DevTools->Settings for getting information about fake releases, but please don't update to fake release

**Comment by DmitryArefiev** [comment] 2023-06-30 14:49
Should be fixed in #18241

**Closed** 2023-07-03 09:10 UTC
Labels: P1, crash
