### ISSUE TITLE
Crash when opening score with empty <noteheadScheme>

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#21248] opened 2024-01-27 14:33 UTC
### Issue type

Crash or freeze

### Bug description

Musescore can't open file and crashes if it contains `<noteheadScheme></noteheadScheme>` within `<StaffTypeChange>`
I couldn't reproduce this empty state from scratch.
Broken score was reported [here](https://musescore.org/en/node/359805)
Broken file (remove .zip before opening):
[Systèmes Sextolet V3.mscz.zip](https://github.com/musescore/MuseScore/files/14072600/Systemes.Sextolet.V3.mscz.zip)

### Steps to reproduce

1. Open file [Systèmes Sextolet V3.mscz.zip](https://github.com/musescore/MuseScore/files/14072600/Systemes.Sextolet.V3.mscz.zip) (remove .zip before opening)
2. Crash

### MuseScore Version

Musescore 4.1.1, 4.2.0, 4.2.1,
MuseScore version (64-bit): 4.3.0-240260304, revision: github-musescore-musescore-75a9232

### Regression

I don't know

### Operating system

windows 10

**Comment by zacjansheski** [comment] 2024-01-30 15:48
Not really a crash, just can't open

<img width="485" alt="Screenshot 2024-01-30 at 10 48 40 AM" src="https://github.com/musescore/MuseScore/assets/69917893/d666b29e-8525-497d-b4c0-701ac84b7fdb">

**Comment by zacjansheski** [comment] 2024-01-30 15:54
Not sure if there is anything useful in the logs.
Since we don't have a way to reproduce from scratch this will not be a high priority for now

[OpenCrash.zip](https://github.com/musescore/MuseScore/files/14100820/OpenCrash.zip)

**Comment by mercuree** [comment] 2024-01-31 01:08
I figured out that in the same place there are other impossible values which can't be set through user interface.
I wonder if this is some kind of memory corruption. 
Since it happened with Musescore 4.1.1, You might consider closing this issue.
```xml          
<StaffType group="pitched">
  <name>ా'ࠀ稧ߺ쀀溙笋ߺ</name> <!-- looks like broken bytes, should be perc1Line -->
  <lines>1</lines>
  <lineDistance>0</lineDistance>
  <yoffset>280</yoffset>  <!-- impossible value, max value is 20sp -->
  <mag>0</mag>  <!-- impossible value, minimum Scale is 20% -->
  <stepOffset>1</stepOffset>
  <clef>0</clef>
  <color>#41000040</color> <!-- impossible value for color -->
  <noteheadScheme></noteheadScheme>
  <ledgerlines>0</ledgerlines>
  </StaffType>
</StaffTypeChange>
```

**Comment by zacjansheski** [comment] 2024-01-31 20:20
Closing per comment above

**Closed by zacjansheski** 2024-01-31 20:20 UTC
Labels: P2, crash
