### ISSUE TITLE
Melisma

### ISSUE THREAD

**Issue by btab33** [musescore/MuseScore#17469] opened 2023-05-04 18:27 UTC
### Issue type

UI bug

### Bug description

With my (French) PC keyboard, it's impossible, with the methods explained in Handbook 4: 
(1) to draw lyrics melismas between notes 
(2) to apply an underscore in lyrics as a special character 

### Steps to reproduce

1. Pressing _ (underscore) from the end of a syllable doesn't apply a melisma
2. Pressing Ctrl+Shift+_ doesn't apply an underscore special character

### MuseScore Version

4.02

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

French keyboard

**Comment by MarcSabatella** [comment] 2023-05-04 18:37
I guess this is a duplicate of https://github.com/musescore/MuseScore/issues/16492

**Comment by oktophonie** [comment] 2023-05-04 19:14
Do you?

**Closed** 2023-05-04 19:14 UTC
Labels: UI, duplicate, regression_ms3
