### ISSUE TITLE
Inconsistant slurring/portimento in Musesound strings.  Out of tune notes.

### ISSUE THREAD

**Issue by dcorson-ticino-com** [musescore/MuseScore#22950] opened 2024-05-23 08:57 UTC
### Issue type

Muse Sounds bug

### Bug description

- Using the Musesounds solo strings for a string quartet not possible as the resulting sounds from playing the same notes are very different.  Although the v1 and vc sound very well when using the expressive sound flag.  This sound flag is not available for v2 and va.  
- Viola solo has extreme portimento which makes it completely unusable.
- Musesounds v2 Db3 sounds like two instruments playing together out of tune, see example.
- At dynamic levels mp and below using the sound flag expressive v1 and vc sound like sotto voce, not simply quiet playing.
Please see the attached example.

### Steps to reproduce

Please see the attached example.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241421429, revision: github-musescore-musescore-2544ca1
musesampler,MuseSampler I,0.6.3.196
c242d818-4654-41f6-8659-a8d0f5c9232b,Muse Strings I,0.4.12.0

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241421429, revision: github-musescore-musescore-2544ca1

### Regression

I don't know

### Operating system

Win10

### Additional context

[CompareVnVa.zip](https://github.com/musescore/MuseScore/files/15414282/CompareVnVa.zip)

**Comment by Dima-S-Jr** [comment] 2024-05-23 10:06
This problem is related to the fact that all (as I understand it) bowed string instruments are played in the legato style. See also #22140.

**Comment by bkunda** [comment] 2024-05-24 13:48
Closing as this issue has been discussed repeatedly elsewhere. The current portamento behaviour is by design.

**Closed by bkunda** 2024-05-24 13:48 UTC
Labels: by design, muse sounds

**Comment by adavismusic89** [comment] 2024-05-24 13:56
Since it is by design, it makes it correct?

**Comment by dcorson-ticino-com** [comment] 2024-05-24 15:03
And it is by design that the viola and violin 2 have no *expressive* sound flag so they sound completely different with totally different articulation behaviour ?
