### ISSUE TITLE
Chord symbol in main score at concert pitch corrupts transposed part

### ISSUE THREAD

**Issue by joeberkovitz** [musescore/MuseScore#22000] opened 2024-03-20 16:03 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Once a part for a transposing instrument has been opened for viewing, if chord symbols are entered in the main score _and its concert pitch setting differs from that of the part_, the chord symbols are incorporated in the part **exactly as entered in the main score** (instead of using the part's transposition setting). This becomes a persistent corruption in the document with different chords displayed in part and score  _even when concert pitch is subsequently set the same way_.

Note that chords entered in concert pitch _prior to the initial viewing of a transposed part_ are not affected by this bug: they are transposed correctly when the part is first viewed.

Possibly this could also be considered a file corruption problem since the problem persists across saving.

### Steps to reproduce

1. Create New Score
2. Add Bb Clarinet Instrument
3.  Enable **Concert Pitch** rendering in main score (checkbox at right of bottom bar)
4. Add a chord symbol **C7** to measure 1
5. Click **Parts** at top of screen and open the Clarinet part. Concert pitch for the part will be off, and measure 1 will show **D7** (correctly transposed pitch).
6. Return to main score by clicking its tab.
7. Add an identical chord symbol **C7** to measure 2
8. Return to the Clarinet Part. Measure 2 now shows **C7** (concert pitch).
At this point both main score and part have inconsistent representations; the two chords are identical in the main score but appear different in the part no matter whether concert pitch is turned on or off.

### MuseScore Version

OS: macOS 13.0, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240770506, revision: github-musescore-musescore-86a75b1

### Regression

No.

### Operating system

MacOS 13.0.1

**Comment by joeberkovitz** [comment] 2024-03-21 15:41
Note that this bug also copies incorrect chord symbols from a transposed part back into the main score with the wrong root tone. Consequently, attempting to correct wrong chords in the part then produces wrong chords in the main score, leading to a jumble of incorrect chords.

**Comment by lgvr123** [comment] 2024-03-22 18:00
I already observed that too. I just made that quick demo.
![Chords vs  Concert Pitch](https://github.com/musescore/MuseScore/assets/50494/3624d5dd-1992-4df4-8e38-7b60fcfa1ad3)

**Comment by cbjeukendrup** [comment] 2024-03-24 23:21
This looks like a duplicate of #19834, which has been fixed recently. You can try out the fix in the latest "master" nightly build: https://musescore.org/en/nightly-builds
If the problem re-occurs, we can reopen this issue.

**Closed by cbjeukendrup** 2024-03-24 23:21 UTC
Labels: needs info, engraving

**Comment by joeberkovitz** [comment] 2024-03-25 12:40
Agreed, this is working in nightly. When I tested I was using a 4.3.0 build, I'll be careful to use master in the future for verifying bugs.
