### ISSUE TITLE
Mouse Input Conflict With Alpha Keyboard Input

### ISSUE THREAD

**Issue by RonRude** [musescore/MuseScore#11047] opened 2022-04-01 01:44 UTC
Mouse note input conflicts with alpha keyboard input, therefore a bug, not a feature request.
When in alpha input users typically enter notes with letters (A, B, C etc), and navigate with arrows, or, make a note active with the mouse.
If mouse input is simultaneously active, then activating an existing note results in an unwanted note being inserted. Exacerbating is that there is no way to select a note using the mouse. It is further desirable that MIDI keyboard note entry should be able to be turned off, so that the user can audition notes without them being entered.
Proposed solution:
Have three entry methods with checkboxes (tickboxes)
A - Alpha computer keyboard. A mouse click activates a given pre-entered note. Shadow not not present.
T - Tracking (mouse, trackpad, tablet). A click enters a note. A Shift click activates a note. Shadow note present.
M - MIDI - physical music keyboard or other instrument - playing a note on the music keyboard enters that note. Shadow note not present.

Regardless of the combination, the shadow note should only be present if T is ticked.

Relates to [MU4 Issue] Mouse-keyboard toggle button #10628 from Linux user on MU3

To Reproduce
1. Enter four crotchet notes: A, B, C, D
2. Choose minim duration, and click on the A to select it.
3. A minim is entered, possibly on the wrong staff line

**Expected behaviour**
User wants to be able to select a note with the mouse.

 - OS: [e.g. macOS but it's expected that the issue is cross-platform]

**Comment by GabeS573** [comment] 2022-04-01 03:44
The current functionality matches MuseScore 3, so I think it is by design that mouse, keyboard, and MIDI input are all active at once. That would make this a feature request and not a bug.

https://musescore.org/en/handbook/3/note-input#basic-note-entry

**Comment by cbjeukendrup** [comment] 2022-04-01 08:32
I'd like to point out that midi input can be enabled/disabled at any time, using the playback toolbar (both MU3 and MU4).

**Comment by HemantAntony** [comment] 2022-04-01 10:05
This issue does not have a name

**Comment by RonRude** [comment] 2022-04-01 10:22
Thanks, Hemant. I've put one in now.

**Comment by rgreen5** [comment] 2022-04-01 10:42
This is neither a bug nor a design flaw. All modes of input are _supposed_ to be active at the same time; you need to be able to freely switch between alpha keyboard / mouse / MIDI keyboard according to need. Certain things are possible in **note input** mode, other in **normal** mode; with experience you learn to effortlessly switch between the two according to the task in hand.

**Comment by RonRude** [comment] 2022-04-01 11:15
Firstly, cbjeukendrup has pointed out that MIDI input can be disabled from the playback toolbar. My opinion is that it's great that it's there, but it would be better situated as an option alongside mouse input and alpha input. So the question then revolves around the remaining two, mouse and alpha. rgreen, you made a very important point - you should be able to freely switch between modes. But that's just the problem. An alpha user wants to switch to mouse, but only when selecting. The rest of the time they enter by alpha. But if they want to edit a note that's perhaps 50 bars away, they don't want to navigate there by using Cmd(Ctrl) left arrow. That would be most inconvenient. They want to simply select it with the mouse. But you can't, because mouse input overides, and superimposes an unwanted note. The only way a user can select a note is by pressing N to cancel Note Input Mode and return to Normal Mode. Then select the note, and then press N again to return to Note Input mode. That's two extra keystrokes, and is unwieldy and counter-intuitive.  Most scorewriter users want to intuitively select a note with the mouse, then enter notes with the keyboard. To make MuseScore more efficient and more intuitive, my proposition is that mouse, alpha and MIDI input should be checkable, so that a user can have the mode they want. Critical to my suggestion is that for alpha mode, the mouse selects, and for Mouse Input mode, a Shiftclick selects. Then, the user never has to leave their preferred mode. You wouldn't have to hop back and forth to Normal mode just to select objects.

**Comment by jeetee** [comment] 2022-04-01 13:09
As a keyboard user I don't agree with your assessment of when I'd be using a mouse.

That being aside; note that a keyboard user (at least in MS3) also can't select things without leaving note input mode (try Shift+Right in note input mode, it doesn't create a range selection).
As a keyboard user, I don't need the mouse to edit a note 50 bars away; I can either Ctrl+F to it if I happen to know something in the vincinity without leaving note input mode, or I press "Esc" to leave the mode. Then again, I might very well scrollwheel to that location and do the first input with the mouse, then continue with the keyboard.

While I get the desire to select things without leaving note input mode as to set a next input position, it'd _personally_ lose more time by having to switch between mouse and keyboard entry all the time (because I do use them intertwined now) than the occasional exit & reposition flow.
Then again, my usual workflows don't call for much repositioning of input location, so the proposed change might just not be aimed at my workflow and benefit others instead.

**Comment by MarcSabatella** [comment] 2022-04-01 13:32
Scrolling then using the mouse to enter the first note is indeed probably the most efficient method of changing note input location to something 50 bars away.  Personally, I'm much more likely to leave and re-enter note input mode, though, since doing so is pretty much second nature given MuseScore is built around this distinction.  So I wouldn't be thinking of that as a last resort.  It's something you would normally do often (say, multiple times a minute) during the normal course of score editing anyhow.

It's certainly possible to create designs that lessen the need for these two separate modes, but merely disabling mouse entry during note input doesn't really accomplish this to any great extent.  Sure, this sort of randomly jumping about the score while editing becomes slightly easier, but that's a relatively uncommon operation.  You still need to leave note input mode to do many of the sorts of things you do over and over and over - like anything sort of copy/paste or other operations involving range selections.  Not just because mouse click enters notes, but because the current design just doesn't really support these operations.

So to me, if there is to be a redesign around any of this, it should really deal with the big picture here and not just clutter the UI with more controls designed to fix one particular corner case (jumping 50 measures away and continuing note input) while leaving the basic problem essentially unchanged.  That's my opinion, anyhow.

BTW, I'm not understanding the expected result in the original case of entering some notes then changing duration and then clicking one of the already-entered notes.  If the goal was to simply change the duration of that already-entered note, this wasn't going to happen anyhow, whether mouse selects of enters.  A way to change duration of already entered notes from within note input mode would be nice, but it's not really related to this.  It does, however, relate to my comment about the distinction between note input snd normal mode being pretty baked in currently.

**Comment by rgreen5** [comment] 2022-04-01 13:51
> "An alpha user wants to switch to mouse, but only when selecting. The rest of the time they enter by alpha."

It depends on the user. I have often used both alpha keyboard _and_ mouse in note input mode.

>But if they want to edit a note that's perhaps 50 bars away, they don't want to navigate there by using Cmd(Ctrl) left arrow. That would be most inconvenient.

So you switch to normal mode first, navigate to the note, then click on it. With experience, switching between modes is a very fast and efficient way of working.

**Comment by MarcSabatella** [comment] 2022-04-01 14:25
Another thing - if you are navigating 50 measures away to "edit" a note, chances are, you don't want to be in note input mode when you get there.  Whether the goal is to change its duration or its pitch, you are better off being in normal mode anyhow.  Really, it's only to start entering entirely new notes in the new location that you might want to remain in note input mode.  And in that case, the trick of simply entering the *first* such new note by mouse is pretty clever, really.

Again, though, overall, no doubt there is room for improvement in the whole design of the relationship between note input and normal mode.  I just think that if that is to happen, it should really be with the overall workflow in mind and not just adding buttons to patch individual cases.

**Comment by RonRude** [comment] 2022-04-01 14:27
JT, you’re right. You can’t select ranges from within Note Input mode. But this is precisely what I’m questioning. I’m suggesting that you shouldn’t need an extra mode, “Normal Mode” to select notes or ranges.
You should be able to select objects from within alpha keyboard mode, or from within mouse mode. Hopping between mouse and keyboard mode would also not be necessary. In my proposal, you could have both, by checking both boxes. In this scenario, you would select notes and ranges by shift clicking. Only in alpha keyboard entry, would you select by regular clicking.
To have an extra mode - Normal mode, adds an unnecessary layer. To argue that one gets used to it is not valid. You can become accustomed to any handicap, like hand cranking to start the car, or having a ball and chain on your foot. Eventually it feels normal, but it's not ideal.
MarcSabatella, the goal was not to change the duration but to select the note. But I understand that in the existing setup, I would have to leave Note Input Mode and go to Normal Mode to do that.
You are right, Marc.  Switching back and forth is baked in. But that doesn’t mean that it’s efficient.
rgreen, in my proposal, you would be able to have both alpha and mouse at the same time. You just wouldn’t need to constantly hop out to Normal Mode. You’d NEVER have to change mode. You’d choose the mode or combination of modes that suits your style, and you’d stay there. When you say that switching between modes is a fast and efficient way of working, I’d say that it’s not. I’d say that it’s more efficient not to have to switch modes but be in one mode or combination of modes where you have a way of entering notes, selecting notes and selecting ranges.

**Comment by Tantacrul** [comment] 2022-06-07 15:39
If this is indeed matches existing MS3 behaviour, I'm closing the issue, since we are finished with feature improvements for this version.

Unless I'm mistaken and there's a bug somewhere in all this conversation?

**Closed by Tantacrul** 2022-06-07 15:39 UTC
Labels: P3
