### ISSUE TITLE
Add Tooltip to Home/Scores tab to read full score titles

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#17962] opened 2023-06-13 11:44 UTC
### Your idea

It would be great to be able to read full score titles on the home/scores tab, ideally with the help of a tooltip.

### Problem to be solved

When opening many files with similar names, it can be difficult or impossible to tell which file is the correct one to open.

**Comment by cbjeukendrup** [comment] 2023-06-13 16:42
Duplicate of #15695. Thanks anyway!

**Closed** 2023-06-13 16:42 UTC
Labels: feature request
