### ISSUE TITLE
template translations don't work 

### ISSUE THREAD

**Issue by Yanko64** [musescore/MuseScore#18082] opened 2023-06-21 06:50 UTC
### Issue type

Other type of issue

### Bug description

when creating new scores in a translated version of Musescore and choosing "create from template", the templates' names aren't being translated by the app, even though they are translated in Transifex

### Steps to reproduce

1. choose a different language than English and restart
2. click on "new score"
3. choose "create from template" (in the translated language) 

the template names should not be translated

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/65133734/8719450e-5810-4afb-a5bb-1dbd5708372d)

I'm using the program in Hebrew, as you can see by the few translated bits

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231710728, revision: github-musescore-musescore-4915f1d

### Regression

Choose option...

### Operating system

Windows 10

### Additional context

this has been true for at least the past 6 months, and to my knowledge it is a known issue, but I haven't seen it reported here
it was reported on the musescore issue tracker
https://musescore.org/en/node/343131

**Comment by Jojo-Schmitz** [comment] 2023-06-21 09:05
Duplicate of #13742, which allegedly got fixed

**Comment by cbjeukendrup** [comment] 2023-06-21 12:00
Closing as duplicate

**Closed by cbjeukendrup** 2023-06-21 12:00 UTC
Labels: needs review
