### ISSUE TITLE
[MU4 Issue] Piano keyboard does not show the notes being played

### ISSUE THREAD

**Issue by Lemon-miaow** [musescore/MuseScore#15794] opened 2023-01-10 09:48 UTC
**Describe the bug**
The piano keyboard in Musescore 4 does not show the current note being played as it did in Musescore 3.

**To Reproduce**
1. Go to any sheet and write down a few notes
2. Open the Piano Keyboard (Keyboard shortcut "P")
3. After playing can see that the piano keyboard in Musescore 4 does not show the notes currently being played as in Musescore 

**Expected behavior**
The keyboard can display the notes being played in real time during playback, like the keyboard in the MU3

**Screenshots**
MU3:![MU3](https://user-images.githubusercontent.com/61692393/211510021-7b26b0aa-abc7-42c1-aa26-4e9ca7eec49b.png)
MU4:![MU4](https://user-images.githubusercontent.com/61692393/211508944-ddac19ff-d0fa-422e-8557-538b1709806a.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, 
   MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Additional context**
Is this an intentional change or a bug?

**Comment by cbjeukendrup** [comment] 2023-01-11 20:45
> Is this an intentional change or a bug?

I wouldn't call it an intentional change, but rather a conscious one. It is because of the new playback engine, and the implementation from MS3 was not viable to be preserved. This feature will need to be re-implemented in a completely different way, which takes time, and there are other things we need to do too that take priority over this.

**Comment by Lemon-miaow** [comment] 2023-01-12 08:02
Thanks for your reply.

**Comment by MarsAstro** [comment] 2023-02-19 15:44
Anyone working on this, or planning on working on it in the near future?

**Comment by cbjeukendrup** [comment] 2023-03-04 15:39
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/14428. 

@MarsAstro I don't think this will be solved in the very near future, since there are other tasks with higher priority.

**Closed by cbjeukendrup** 2023-03-04 15:39 UTC

**Comment by cbjeukendrup** [comment] 2023-04-14 17:20
Because there are at least 1000 issues that are even more important than this. (Note that the feature requested in this issue has zero functional value; it's purely a visual nice-to-have.)

**Comment by Jojo-Schmitz** [comment] 2023-04-14 17:25
But primarily because it is a duplicate...

**Comment by githubwbp1988** [comment] 2025-06-11 03:43
Reference : Show playing notes on the piano keyboard during playback #28073
link: https://github.com/musescore/MuseScore/pull/28073

I implemented this feature by reading sheet music through code, and the results are better than the current implementation. However, due to the extensive code changes and my reluctance to fully adhere to the official coding style guidelines, the "Check: Codestyle / codestyle (pull_request)" check failed. Since this implementation is constantly rebased onto the latest master branch, it should maintain all original features from the official version.

Previously, I considered visually differentiating notes from different instruments on the keyboard. However, given the limited display space on the keyboard and the complexity of handling not only basic piano scores but also accompaniment scores and two-piano scores, this approach would lead to convoluted logic and is not feasible. Instead, the keyboard can effectively reflect the current clef and key signature from the sheet music in real-time which is very useful skill for composers/pianists   with visualization.


https://github.com/user-attachments/assets/295e8c1e-1009-4926-9c6e-783822909221



windows: https://github.com/musescore/MuseScore/actions/runs/15573971888?pr=28073
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/64e1955f-2757-41d0-8067-09c7d9e6aef7" />

mac: https://github.com/musescore/MuseScore/actions/runs/15573971898?pr=28073
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/e087bb10-89fb-42a7-b0d8-0e704ae887b6" />

linux: https://github.com/musescore/MuseScore/actions/runs/15573971914?pr=28073
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/c83c1f0b-b5e4-440e-a784-590688ce2709" />

**Comment by Jojo-Schmitz** [comment] 2025-06-11 09:17
Your 'reluctance to fully adhere to the official coding style guidelines' certainly prevents your PR from getting merged.

The other PR can't get merged due to conflicts, so needs a rebase
