### ISSUE TITLE
[MU4 Issue] Can't type tablature numbers

### ISSUE THREAD

**Issue by Koopa1018** [musescore/MuseScore#16366] opened 2023-02-15 08:54 UTC
**Describe the bug**
Since upgrading to MuseScore 4, I can no longer type numbers into guitar TAB staves. If I try, the note duration is set instead.

Curiously, this even happens if I try entering via numpad--even though duration entry via numpad is broken in normal staves!

**To Reproduce**
1. Create score with a tablature staff (I'm using a guitar for this).
2. Add note to TAB staff.
3. With note selected, attempt to type a fret number.

**Expected behavior**
Can set a note's fret number directly by typing said number.

**Screenshots**
N/A

**Platform information**
 - OS: Windows 10

**Additional context**
Attempted on a score upgraded from MuseScore 3, but already saved and closed several times in MS4.

**Comment by MarcSabatella** [comment] 2023-02-15 14:45
This works fine for me.  What keyboard layout do you have, and what language settings in your OS?  Does the problem persist if you do Help / Revert to factory settings?

BTW, I'm not really understanding your step 2.  Typing a number *is* how you add a note to the tab staff.  Are you attempting to first click to enter the note?  That isn't necessary (and wasn't in MuseScore 3 either), but it should work and does for me.  Still, if that/s what you are doing, try skipping that to see if it helps.

**Comment by Koopa1018** [comment] 2023-02-18 07:00
...huh.
That is really weird. It seems to have stopped happening since I restarted the computer.

**Comment by Koopa1018** [comment] 2023-02-22 01:21
Ah, my bad. I suppose my repro steps don't match the problem.
...incidentally, the problem seems to have gone away after a restart. D'oh 🤦‍♂️

**Comment by cbjeukendrup** [comment] 2023-03-12 17:54
I'll close this, since no one could reproduce it and the problem seems to have fixed itself. However, @Koopa1018, if it happens again, please post a comment here, and then we will reopen it.

**Closed by cbjeukendrup** 2023-03-12 17:54 UTC
