### ISSUE TITLE
[MU4 Issue] unable to tick "Auto spacing" in migration dialog for 2.0.2 file. Option should be removed.

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13824] opened 2022-10-18 16:48 UTC
**Describe the bug**
Opening 2.0.2 file, migration dialog appears, but it is not possible to tick "Auto spacing"

**To Reproduce**
Steps to reproduce the behaviour:
1. Open 2.0.2 file
2. Try to tick "Auto spacing"

**Expected behaviour**
The auto spacing option should no longer be available. Let's just remove it (it defaults to being on, like all other scores)

**Screenshots**

https://user-images.githubusercontent.com/1646034/196492935-d9f042e0-eb60-47a8-bc16-fab46e0bd7c0.mp4

**Platform information**
 - OS: [reported on Linux and MacOS]

**Comment by MarcSabatella** [comment] 2022-10-18 17:50
I am not sure what that box is even supposed to mean.  Does it refer to automatic placement (aka autoplace)?

I'll put it out there that there are almost no cases where disabling autoplace would produce reasonable results.  There's just no way MuseScore 4 (or 3) can completely reproduce all the quirks of the MuseScore 2 layout algorithm, so you will likely end up with a worse mess than leaving it on.

MuseScore 3 offers the option of not checking that box, but as far as I can tell, it has no effect whatsoever.  Automatic placement is always enabled.  I don't see any point in having MuseScore 4 provide a way to disable it on import.

**Comment by Tantacrul** [comment] 2022-10-18 21:55
Agreed (with consultation from @oktophonie).

Can we just remove the option? I'll update the issue to reflect this.

**Comment by MarcSabatella** [comment] 2022-10-18 21:59
Unless it does something useful that I’m not aware of I’dd be very happy to see it go away.  I suppose maybe it might relate to vertical justification rather than autoplace?  Even if so, I see no reason to expose that in the dialog.

**Comment by sammik** [comment] 2022-10-19 12:44
"Auto spacing" (aka autoplace) should be on by default, but it is not always. Have no idea,what it depends on.

But I found, **other options are also blocked from ticking / unticking**.

Also 3.2.3 files.

https://user-images.githubusercontent.com/1646034/196693818-881f0a80-bb57-48ed-9f55-e11a9156a1d5.mp4

It is regression. In Alpha it worked.

So I would recommend to update bug description to cover **actual problem - non accesible tickers**.

**Comment by MarcSabatella** [comment] 2022-10-19 17:58
I meant, I can't see that you did anything to "check" whether it was enabled, not that you didn't "check" the box itself.  Can you attach the score you believe has it disabled?  Again, the option did nothing in MU3 either as far as I know - autoplace is always enabled regardless of the status of that checkbox, in every score I've tried.  The way to check to see if autoplace is enabled or not is in 3.0 simply click an element and see if the autoplace chekbox is enabled and checked in the Inspector.  If the box is enabled but not checked, it means autoplace was disabled for that specific element.  If the checkbox is disabled, it means autoplace was disabled globally.  In MU4, I don't think there is a way to check the global state, but, you can define a shrotcut for the "toggle autoplace globally" command and then execute the command.  Should be obvious enough looking at the score when it's on and when it's off.

**Comment by Tantacrul** [comment] 2022-10-19 17:59
@MarcSabatella - the issue is much simpler than you think it is. The box simply can't be checked - regardless of whether you'd want it to be or not. You click on it and it does nothing.

**Comment by MarcSabatella** [comment] 2022-10-19 18:07
I get that; I'm just advocating that the option be removed.  The *other* checkboxes should be fixed :-)

**Comment by Tantacrul** [comment] 2022-10-19 18:08
I think we've all agreed the option should be removed?

**Comment by sammik** [comment] 2022-10-19 18:32
Well, I am not big fan of removing it, but it doesnt metter. If someone has strongly customised score, may be dissapointed, that cant open it unchanged. But it is not a big problem, as simple undo after migrating reverts it. So OK, remove it.

What I try to say is, to be 100% sure, that option is always **checked** (even if we hide / remove it).
Because now, it should be always **checked** by default, but sometimes it is not. Its not score wise.
First time, I run fresh new install, option is checked. After closing app and opening it again, same score has this option unchecked (because is in "recent scores history", or what ever strange reason). As you can see in score, it is bit different each time (Tempo marking has different position), see:

https://user-images.githubusercontent.com/1646034/196774865-f0918fe3-894d-4421-96dc-e722a9270e10.mp4

**Comment by Tantacrul** [comment] 2022-10-19 18:38
We want to get rid of it because we can't honour the settings from MS2 really anymore.

For that reason, if a person wants  their score to look like the Musescore two version, they need to stick to MS2.

This is true regardless of whether we get rid of the option or not. The engraving is too fundamentally different now.

**Closed** 2022-10-21 09:50 UTC
Labels: P2
