### ISSUE TITLE
Symbol text loses spaces every time the file is reopened

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15629] opened 2022-12-28 03:18 UTC
**Describe the bug**
text with symbols and spaces between the symbols loses the spaces after saving and reopening the file

**To Reproduce**
1. add text with symbols with spaces between them then save
2. close and reopen the file in musescore
3. see the spaces are gone and it has to be respaced

**Expected behavior**
the spacing should remain the same so it looks the same as when it was saved

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/209751857-c966f75e-42ac-47c8-8bdf-dff136c119a3.png)

**Platform information**
windows

**Comment by mike-spa** [comment] 2023-02-10 11:26
Ok, I've spent a long time on this. Here's what's happening. When a text like this is entered (two quarter notes symbols, separated by some spaces)
<img width="299" alt="image" src="https://user-images.githubusercontent.com/93707756/218074587-d14f0f67-305e-4425-a12b-8554d14236a9.png">
this is what is written to the file
<img width="502" alt="image" src="https://user-images.githubusercontent.com/93707756/218074838-ce50911c-f50e-4f6e-a4ed-a6aed76a9d51.png">
The symbols are encoded as html tags, and in between them is blank space. The problem is that the xml reader which parses our file is designed to ignore blanks in-between tags (and it _has_ to be that way), so those spaces aren't recognized as a string of text, but just as a blank, and they are ignored. Things I've already tried:

- removing the ignore whitespace condition from [here](https://github.com/musescore/MuseScore/blob/master/src/engraving/rw/xmlreader.cpp#L226-L228) (doesn't work)
- removing the ignore whitespace condition from [here](https://github.com/musescore/MuseScore/blob/master/src/engraving/rw/xmlreader.cpp#L193-L197) (also doesn't work)

As far as I can tell (and unless I'm missing something very obvious) the problem goes deep into the very core of the xml parser, specifically [here](https://github.com/musescore/MuseScore/blob/master/src/framework/global/serialization/xmlstreamreader.cpp#L148) and [here](https://github.com/musescore/MuseScore/blob/master/src/framework/global/serialization/xmlstreamreader.cpp#L121). And, since the xml reader is not even ours but from a third party, I'm not even sure we _can_ fix this. (And, by the way, the problem happens identically also in Musescore 3.6).

One way around the problem is to use the "special space" character (basically, just type ctrl+space instead of space). This will work correctly and will be retained after save-reload.

I see only two options to fix this for real.
- We somehow try to hack the xml parser to read blank strings in these cases (but that could be very dangerous, cause ignoring blanks is kind of fundamental for parsing correctly).
- We hack the other way around, i.e. enforce that when editing text in the score the space bar doesn't produce the "normal" space character but the "special" space (what is now produced with ctrl+space).

However, this issue is so niche and the workaround so simple that I'm tempted to say "just use ctrl+space in that case" and close it. @cbjeukendrup can you let me know what you think?

**Comment by cbjeukendrup** [comment] 2023-02-10 12:23
@mike-spa Your investigation makes sense to me. The workaround is indeed so easy that we don't need to fix this urgently. On the other hand, it's still quite clearly a bug, so I think it would be preferable to fix it _someday_. The "hack" of writing "special" spaces seems the best candidate to me.

**Closed** 2023-06-12 09:52 UTC
Labels: P2
