### ISSUE TITLE
16th through stem rolls on Musesound Timpani do not honor dynamic hairpins, cresc/dim text

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#21060] opened 2024-01-18 04:30 UTC
### Issue type

Muse Sounds bug

### Bug description

On notes marked with a "16th through stem tremolo," the Musesounds Timpani does not crescendo/decrescendo to the new dynamic when there are hairpins or cresc/dim text. 

### Steps to reproduce

1. Open a new score with Timpani
2. Input notes
3. Put a "16th through stem tremolo" on the first note, and add a dynamic.
4. Add a different dynamic on the next note.
5. Add a hairpin or cresc/dim text in between the notes.
6. Click Play
7. Observe that no cresc/desc happens.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102687285/92bbb4bd-ca52-472a-98a3-b2d8c37926dd

Here's an OBS recording of the reproduction of this issue.

### MuseScore Version

Musescore 4.2.0

### Regression

No.

### Operating system

Windows 11

### Additional context

This does not affect MS Basic.
Upon further testing, I also noticed the same issue happens with notes having Eight through stems. Notes with 32nd and 64th through stems behave normally.

**Comment by DaddyLudwig** [comment] 2024-01-18 05:11
Same thing happens with trills as well, that dynamics and hairpins aren't honored for timpani. Example from a Beethoven symphony. It only sounds like it's doing a diminuendo cause there are 2 trills playing(as a workaround for trill lines not working past the first note with ties). But each measure of the trill stays the same dynamic level throughout, it doesn't diminuendo within the measure, only between measures. I know the trill is an old notation practice, but it's one of the ways I emulate the Breitkopf editions I generally use for my sheet music when I'm transcribing Beethoven.

Full orchestra first and then timpani soloed so you can hear what's happening more clearly.

https://github.com/musescore/MuseScore/assets/6530761/baa037a3-66f2-4797-a8e1-f0e77e21d4f7

**Comment by zacjansheski** [comment] 2024-01-18 14:14
Duplicate of https://github.com/musescore/MuseScore/issues/19095

Let's close this and refer to that.

**Closed by zacjansheski** 2024-01-18 14:14 UTC
Labels: muse sounds
