### ISSUE TITLE
[MU4 Issue] Placing an inverted mordent places a normal mordent instead

### ISSUE THREAD

**Issue by galoomba1** [musescore/MuseScore#15489] opened 2022-12-21 20:09 UTC
**Describe the bug**
Placing an inverted mordent on a note places a normal mordent instead. Existing inverted mordents (made in earlier versions) work, but copying and pasting them also places a normal mordent.

**To Reproduce**
1. Place a note
2. In the Ornaments panel in the palette, add an inverted mordent (labeled just Mordent in the palette) to the note.
3. Observe that the mordent looks and plays identically to the normal mordent (labeled Short trill in the palette).

**Expected behavior**
An inverted mordent is added to the note. If the note is A, it plays A-G-A.

**Actual behavior**
A normal mordent is added to the note. If the note is A, it plays A-B-A.

**Platform information**
 - OS: Windows 10

**Comment by spacegaier** [comment] 2022-12-22 22:47
I cannot reproduce that. The inverted mordent / pralltrill corretly goes up where as the mordent correctly goes down for me.

The exact version I tried: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by galoomba1** [comment] 2022-12-24 00:53
Seems like it only happens with files from MU3. If I make a new score it works as expected.

**Comment by zacjansheski** [comment] 2023-08-08 19:27
I am unable to reproduce this using scores from MU3, closing.

**Closed by zacjansheski** 2023-08-08 19:27 UTC
