### ISSUE TITLE
Qt 6.5+: menu bar and top-left toolbar are missing

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#24097] opened 2024-08-19 12:47 UTC
### Issue type

Other type of issue

### Description with steps to reproduce

In development builds made with Qt 6.5 or later, the top-left toolbar (Home/Score/Publish) is missing. 
Additionally, on OSs without a system-wide menu bar, the menu bar at the top of the window appears as a blank strip. 

Although we won't move away from Qt 6.2 in the near future because of macOS compatibility, it would be good to fix this problem, because
- eventually, we'll have to update anyway
- Linux packagers want to create unofficial distro-specific MuseScore packages against the latest version of Qt, i.e. 6.7.2 at the time of writing, so they suffer from this problem.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/5f586282-6eea-4411-95ee-25c7463acb04)
(from https://github.com/musescore/MuseScore/issues/23980#issuecomment-2282881609)

### What is the latest version of MuseScore Studio where this issue is present?

self-built from master with Qt 6.5+

### Regression

No.

### Operating system

\*

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by kbloom** [comment] 2024-08-21 13:29
I inspected this in GammaRay, and appMenuBar had a height of 0. Changing the height in GammaRay to 20 made it visible.

**Comment by kbloom** [comment] 2024-08-21 13:41
I didn't see anything obvious in GammaRay when I inspected the top-left toolbar.

**Comment by darix** [comment] 2024-08-28 13:56
will there be a patch fix without upgrading Qt to resolve this?

**Comment by kbloom** [comment] 2024-08-28 14:48
Some more investigation in AppMenuBar: it appears that

```
Component.onCompleted: {
  appMenuModel.load()
}
```
doesn't get run until I change the height of the AppMenuBar to be non-zero, so the ListView in AppMenuBar.qml can't get a non-zero height from its children, because the children haven't been loaded. Chicken and egg.

**Comment by kbloom** [comment] 2024-08-28 16:06
I wonder if this commit in Qt is related. https://github.com/qt/qtdeclarative/commit/492dc98a288763d3d026e9557ffadc018cede350

**Comment by darix** [comment] 2024-08-29 02:02
```
04:01:18.566 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

04:01:18.566 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
```

is that related maybe?

**Comment by darix** [comment] 2024-08-29 10:48
is the mixer working for you?

**Comment by darix** [comment] 2024-08-29 13:28
Fix confirmed ... but I guess this also gets hit by https://blog.broulik.de/2024/08/a-fresh-perspective-on-things/

if you click "files" menu and then move the cursor right the new menus open at the start of the menu bar. :)

so now I am wondering ... is there more places where a similar fix to this is needed? like e.g. the mixer isnt working here.

**Comment by kbloom** [comment] 2024-08-29 14:17
You could probably grep the codebase to find other issues similar to this.

Looks like we should investigate all of the following:

```
$ grep -r 'height:.*contentItem' *                                                        
src/framework/extensions/qml/Muse/Extensions/ExtensionViewer.qml:    height: builder.contentItem ? builder.contentItem.implicitHeight : 600
src/appshell/qml/platform/AppMenuBar.qml:    height: contentItem.childrenRect.height
src/appshell/qml/MainToolBar.qml:        height: contentItem.childrenRect.height
$ grep -r 'width:.*contentItem' *
src/project/qml/MuseScore/Project/SaveToCloudDialog.qml:                    width: contentItem.width
src/framework/extensions/qml/Muse/Extensions/ExtensionViewer.qml:    width: builder.contentItem ? builder.contentItem.implicitWidth : 800
src/playback/qml/MuseScore/Playback/internal/MixerPanelSection.qml:            width: contentItem.childrenRect.width
src/appshell/qml/MainToolBar.qml:        width: contentItem.childrenRect.width
src/instrumentsscene/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:                width: treeView.contentItem.width
```

The mixer is definitely on the list.

I can try to write a PR for this tomorrow if nobody gets to it first. If you want to beat me to it, you sidestep the menu positioning problem by testing on X11. I don't think this is a Wayland-specific bug.

**Comment by hamkg** [comment] 2024-08-29 15:40
Just confirming that Votginator's patch fixes the missing menu bar issue when building on slackware-current (and running X11).

**Comment by kbloom** [comment] 2024-08-30 14:59
I've got PR #24326 for the menu bar and the main toolbar, but trying to make a similar fix in MixerPanelSection doesn't fix the mixer. I'm not sure what's wrong with the mixer.

**Comment by kbloom** [comment] 2024-08-30 15:40
Regarding the mixer, I also couldn't get some other panels to open, like the piano keyboard.

**Comment by kbloom** [comment] 2024-08-30 15:44
When I tried opening the Navigator, it didn't show any mini-pages until I also opened Braille, at which point Braille doesn't show anything, but the Navigator does.

When I close and reopen Palette, the re-opened palette is empty.

**Comment by kbloom** [comment] 2024-08-30 15:53
In short, can you file a separate bug about all of the docks.

**Comment by cbjeukendrup** [comment] 2024-09-01 21:25
Speaking of docks: in combination with updating to the latest Qt, we should perhaps also update to the latest KDDockWidgets. That's going to be non-trivial, because we would have to update from 1.5-ish to 2.1 which is a major version update, and also because we're using some private KDDockWidgets headers in order to get the exact behaviour we want.

**Comment by orivej** [comment] 2024-09-22 08:27
> Speaking of docks: in combination with updating to the latest Qt, we should perhaps also update to the latest KDDockWidgets. That's going to be non-trivial, because we would have to update from 1.5-ish to 2.1 which is a major version update, and also because we're using some private KDDockWidgets headers in order to get the exact behaviour we want.

I've investigated one problem with the docks on Qt 6.7.2 - they do not open once the last tab is closed -  it turned that KDDockWidgets 1 (including the latest 1.7) are designed to restore them incompatibly with the way Qt 6.5+ works.

When MuseScore calls `setVisible(true)` in `DockBase::open` to show a previously closed dock widget those panel was also closed, the expected call chain to recreate the panel (frame) is this:
```
muse::dock::DockWindowActionsController::toggleOpened
muse::dock::DockWindow::toggleDock
muse::dock::DockBase::open
KDDockWidgets::QWidgetAdapter::show
QQuickItem::setVisible
QQuickItemPrivate::setVisible
QQuickItemPrivate::setEffectiveVisibleRecur
QQuickItemPrivate::itemChange
KDDockWidgets::QWidgetAdapter::itemChange
KDDockWidgets::DockWidgetQuick::event
KDDockWidgets::DockWidgetBase::onShown
KDDockWidgets::DockWidgetBase::Private::maybeRestoreToPreviousPosition
KDDockWidgets::DockWidgetBase::Private::restoreToPreviousPosition
LayoutWidget::restorePlaceholder
DefaultWidgetFactory::createFrame
```

**Comment by orivej** [comment] 2024-09-22 08:31
> Speaking of docks: in combination with updating to the latest Qt, we should perhaps also update to the latest KDDockWidgets. That's going to be non-trivial, because we would have to update from 1.5-ish to 2.1 which is a major version update, and also because we're using some private KDDockWidgets headers in order to get the exact behaviour we want.

I've investigated one problem with the docks on Qt 6.7.2 - they do not open once the last tab is closed -  it turned that KDDockWidgets 1 (including the latest 1.7) are designed to restore them incompatibly with the way Qt 6.5+ works.

When MuseScore calls `setVisible(true)` in `DockBase::open` to show a previously closed dock widget those panel was also closed, the expected call chain to recreate the panel (frame) is this:
```
muse::dock::DockWindowActionsController::toggleOpened
muse::dock::DockWindow::toggleDock
muse::dock::DockBase::open
KDDockWidgets::QWidgetAdapter::show
QQuickItem::setVisible
QQuickItemPrivate::setVisible
QQuickItemPrivate::setEffectiveVisibleRecur
QQuickItemPrivate::itemChange
KDDockWidgets::QWidgetAdapter::itemChange
KDDockWidgets::DockWidgetQuick::event
KDDockWidgets::DockWidgetBase::onShown
KDDockWidgets::DockWidgetBase::Private::maybeRestoreToPreviousPosition
KDDockWidgets::DockWidgetBase::Private::restoreToPreviousPosition
LayoutWidget::restorePlaceholder
DefaultWidgetFactory::createFrame
```

However, since https://github.com/qt/qtdeclarative/commit/d1b9a4cacfb966cf0a37983d8f8044f3aedf5de3 the chain ends at `QQuickItem::setVisible` since in Qt 6.5 and later it does nothing on an item without a parent (and a dock without a panel has none).

KDDockWidgets have redesigned this in https://github.com/KDAB/KDDockWidgets/commit/764385de9f9dd88c2685e42ef65e1daaaca3d679 which went into the 2.0.0 release.

**Comment by orivej** [comment] 2024-09-22 08:45
If I revert https://github.com/qt/qtdeclarative/commit/d1b9a4cacfb966cf0a37983d8f8044f3aedf5de3, the closed docks are opened back again, and the only remaining issue that I see is that the mixer dock is almost blank (only channel strip separators are visible) until I switch to a different dock in the same tab and back (e.g. by pressing 'p' twice to open and close piano keyboard)

**Comment by orivej** [comment] 2024-09-22 09:14
If I revert https://github.com/qt/qtdeclarative/commit/d1b9a4cacfb966cf0a37983d8f8044f3aedf5de3, the closed docks are opened back again, and the only remaining issues that I see (after #24326 is merged):

1. The mixer dock is almost blank (only channel strip separators are visible) until I switch to a different dock in the same panel and back (e.g. by pressing 'p' twice to open and close piano keyboard).

2. The navigator dock is a white rectangle the first time it is opened (as long as it was closed when the MuseScore has opened the score) until it is redrawn, e.g. until I pan the view of the score or resize the window.

**Closed** 2024-10-03 08:23 UTC
Labels: community, dev, tech debt, Qt-next
