### ISSUE TITLE
[MU4 Issue] [GP] Dead notes  ('X' noteheads) are not showing in Tab in MS4 (regression from MS3)

### ISSUE THREAD

**Issue by Payne81** [musescore/MuseScore#8601] opened 2021-07-13 06:37 UTC
There is an urgent need for ghost note notation&&rendermidi.

(Martin edit) see my comment below for more detail.

**Comment by steven-omaha** [comment] 2022-01-13 18:23
I just ran into this. The best I can currently achieve is this (5 string bass). I can mark the note in the regular staff as ghost note, but not in the tab.

![screen01](https://user-images.githubusercontent.com/35634100/149387151-def7cca4-5bfb-4a8f-a7d0-74c972f0c7e2.png)

**Comment by Tantacrul** [comment] 2022-04-30 17:47
I can confirm that when changing a notehead to an 'X' in MuseScore 3, this did the same in Tab.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/21022311/166116529-a1ceb9b5-5826-49ca-8dc1-82dadb22271e.png">

In MuseScore 4, when choosing an 'X' in the inspector or from 'Noteheads' in palettes, tab should have an 'x' too

<img width="301" alt="image" src="https://user-images.githubusercontent.com/21022311/166116581-8d10c168-dd76-4308-8dd8-3dbd48eb9668.png">

<img width="297" alt="image" src="https://user-images.githubusercontent.com/21022311/166116592-d046769b-ab81-4f82-888c-cc96fb1eb851.png">

**Comment by Tantacrul** [comment] 2022-04-30 17:49
Thanks @Payne81 !

**Comment by boryskuzmenko** [comment] 2022-05-02 16:15
@Tantacrul I can't reproduce your result in MU3, note in TAB doesn't become ghost(dead) after changing the standard notation note.
![Capture 2022-05-02_07-14-53_PM](https://user-images.githubusercontent.com/101250347/166268686-da0c4b2d-bd8b-4a85-aa53-41385d924767.png)


 At the time we should separate ghost and dead notes. See how it implemented in GP:
![Capture 2022-05-02_07-09-14_PM](https://user-images.githubusercontent.com/101250347/166268020-ddbd8d66-9e71-4b76-bd31-fe54521be7b5.png)
 As I understood right this issue is about dead notes. Correct me if I'm wrong

**Comment by Tantacrul** [comment] 2022-05-02 17:14
@boryskuzmenko - actually you understand me perfectly. MS4 **does not** show dead notes in tab and my bug is that it **should**.

MS3 does it
GP does it

**Comment by alexpavlov96** [comment] 2022-05-15 12:25
@boryskuzmenko there is 2 regressions from MU3:
- Not possible to change cross notehead IN BOTH NOTATIONS after opening gp file 
- Parenthesis instead of cross in tab notation in tab notation

and 1 thing that will be fixed which didn't work also in MU3:
- Not possible to change cross notehead IN TAB NOTATION after opening gp file

**Comment by abariska** [comment] 2022-09-28 10:02
🟢 **FIXED**

**Closed** 2022-09-28 10:05 UTC
Labels: P1
