### ISSUE TITLE
[MU4 Issue] Undocked playback bar cannot be scrubbed

### ISSUE THREAD

**Issue by billycookin** [musescore/MuseScore#13100] opened 2022-08-31 14:08 UTC
**Describe the bug**
When I undock the playback bar, I cannot scrub through playback of the score using the mouse. Clicking and dragging the current time indicator merely moves the playback interface around the screen.

**To Reproduce**
1. Open a new or existing score
2. Undock the playback interface
3. Begin playback
4. Click on the current time indicator, and try to drag it to a new timestamp. Interface is moved instead. 
5. Attempt to click on new time position on bar. Current time indicator does not reposition.

**Expected behavior**
I thought that the new playback bar allowed click-and-drag scrubbing through playback, and also click-to-select a time.

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment] 2022-08-31 14:17
This looks like a duplicate of #12817, which has been fixed after the alpha 2 release. You could try the latest nightly build from https://ftp.osuosl.org/pub/musescore-nightlies/, which should include the fix. Please reopen if the issue still occurs in those builds.

**Closed by cbjeukendrup** 2022-08-31 14:17 UTC
