### ISSUE TITLE
[MU4 Issue] [Assert crash] Crash on exporting to music xml

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12117] opened 2022-06-21 14:32 UTC
**Describe the bug**
Exporting to MusicXML crashes MuseScore

**To Reproduce**
1. Create a score with a piano
2. Go to export dialog
3. Switch to MusicXML export
4. Export, MuseScore crashes

**Expected behavior**
MuseScore is not supposed to crash

**Screenshots**
**I will add screenshots after a bit of time**

**Platform information**
 - OS: Windows 11

**Comment by HemantAntony** [comment] 2022-06-21 14:47
You should not be able to reproduce without being in Debug mode. So I don't think this will affect regular users. But still worth testing just in case

**Comment by wizofaus** [comment] 2022-06-21 22:21
Can't reproduce, running MSVC on Win 10 with latest source.

**Comment by cbjeukendrup** [comment] 2022-06-21 22:33
You can only reproduce it if the "All layout" option is checked in the export dialog.

**Comment by wizofaus** [comment] 2022-06-21 22:46
Nope, tried that...

**Closed** 2022-06-22 06:00 UTC
Labels: P0
