### ISSUE TITLE
All notes change to the specified dynamics, even if played before the change and held during it 

### ISSUE THREAD

**Issue by MqcCheeze** [musescore/MuseScore#22605] opened 2024-04-27 21:48 UTC
### Issue type

General playback bug

### Bug description

All notes change dynamics even if they are initially played before the dynamic change. E.g. below, I have used pedal to sustain the low bass notes however its dynamics change with the next note. See image.

Slightly obscure but for anyone who has this issue it could get frustrating.

This does not affect MIDI when exported as it will play as normal.

### Steps to reproduce

See image

1. Notes with one dynamic
2. Place different dynamic after the note has started to play, but during its length / while pedal is used
3. Playback

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/87596784/8aede510-b342-45c7-8836-8b305d853d53)

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment] 2024-04-27 22:53
Seems related to (if not a duplicate of) #13877 and #20950.

**Comment by DmitryArefiev** [comment] 2024-06-27 15:06
Fixed in #22953


https://github.com/musescore/MuseScore/assets/90187801/b1aa550c-eb19-4ec7-80be-50590f42daf4

**Closed** 2024-06-28 11:08 UTC
Labels: playback
