### ISSUE TITLE
Part names incorrect in file names and content of PDF exports of individual parts

### ISSUE THREAD

**Issue by skdonnelly** [musescore/MuseScore#23464] opened 2024-07-04 04:57 UTC
### Issue type

Import/export issue

### Steps to reproduce

1. create score with two Tenor Saxophone parts
2. name one of them Tenor Saxophone 1 and the other Tenor Saxophone 2 in the Properties > Staff/Part properties dialog per the image
3. export PDF files of the two parts
Issues:
1. instead of the proper part names, the file names will contain "Tenor_Saxophone" and "Tenor_Saxophone_(1)"
2. In the top left corner of the PDF parts, one of them will have the text "Tenor Saxophone" and "Tenor Saxophone (1)"

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/26123297/b5dcc23e-284d-4942-adc0-516cdced1005)
![image](https://github.com/musescore/MuseScore/assets/26123297/44ef31d8-1077-4025-a2ca-273b6ec98237)

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by cbjeukendrup** [comment] 2024-07-04 11:47
Afaics, this is by design. Those names in the Staff/Part Properties dialog are the _instrument_ names. 

The names used for exporting parts are those in the Parts dialog (accessed via the `File` menu or the button in the top center of the window). 

However, because of the wording of the Staff/Part Properties dialog, your confusion is completely understandable. We will get rid of that dialog and replace it with something better.

**Comment by skdonnelly** [comment] 2024-07-04 22:12
There is no way to access Parts from the File menu, which may be a bug in itself? Everything that is a toolbar button should be accessible from the menus as well. It should be in the View menu as Mixer is for consistency. 

Changing the names in the Parts dialog did result in the correct names being included in the PDF exports so that is good. 

If I click on one of the instrument names in the score, go to the properties tab, and click "Staff/part properties", I then see a section labelled "Part properties" with the long instrument name, so it is clearly identified as a "Part" property. Yet I have to change it in the "Parts" dialog instead/as well. It should be clarified that one only appears on the staff (should be called "Staff display name" or something, while the other is used in the file name and export.

**Comment by cbjeukendrup** [comment] 2024-07-05 00:42
The problem here is that the word "part" has two meanings:
1. abbreviation of "part score", i.e. a score that shows only one instrument (or rather, only one "part", but here it is "part" in the second meaning)
2. an instance of an instrument, i.e. a player

This is an eternal source of confusion, and a very unfortunate fact of at least the English language. Dorico gracefully avoids this problem by not using the word at all, and instead using the abstract terms "Layout" and "Player" respectively. However, at least the term "Layout" is so abstract that nobody will understand that it means "Part score", so that's also not ideal.

**Comment by bkunda** [comment] 2024-07-05 13:15
Closing because this isn't a bug. 
However we can appreciate the confusion caused by the terminology in the stave/parts dialog. This dialog is ultimately going to be a candidate for an overhaul, so we'll improve the UI copy of it then. 
Thanks!

**Closed by bkunda** 2024-07-05 13:15 UTC
Labels: by design
