### ISSUE TITLE
Crashes every time I click on a certain measure or playback reaches that bar

### ISSUE THREAD

**Issue by mutetoot** [musescore/MuseScore#17297] opened 2023-04-20 10:03 UTC
### Issue type

Crash or freeze

### Bug description

Every time I click on a note in one of the staves at a certain measure of my piece, the software automatically closes. It also closes as soon as the playback reaches that bar

### Steps to reproduce

1. open the zip file
2. click on 'trying to stop it crashing'
3. go to measure 65 and press play or
4. go to measure 67 and click on any of the notes

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

[Crash report.zip](https://github.com/musescore/MuseScore/files/11284923/Crash.report.zip)

**Comment by Jojo-Schmitz** [comment] 2023-04-20 10:05
Stems from https://musescore.org/en/node/348352, sample score also available from there

**Comment by PEM-FR** [comment] 2023-04-22 15:58
I experience the same thing with Nightly Master Linux and one of my scores. 
Everything was working fine until I decided to copy an oboe set of measures into a flute 2 and a set of violin measures into flute 1.
Not sure hich brought the problem or if it is unreleated altogether. But since then, clikinga note or dynamic (not the crescendos though), reaching there with playback makes the app crash.

**Comment by bkunda** [comment] 2023-05-03 14:35
Unable to reproduce on macOS.
@cbjeukendrup do you suspect this is specifically related to Muse Sounds?

**Comment by cbjeukendrup** [comment] 2023-05-04 16:44
Yes, according to the Windows debugger, the problem is in `MuseSamplerCoreLib`.

**Comment by bkunda** [comment] 2023-05-09 13:30
Ok thanks for confirming @cbjeukendrup.
@iamtesch assigning P1 as it is evidently a crash.

**Comment by cbjeukendrup** [comment] 2023-05-18 20:54
This crash had the same stack trace as #16642, and in both cases the Tubular Bells are involved, so I think we can close this as a duplicate.

**Closed by cbjeukendrup** 2023-05-18 20:54 UTC
Labels: P1, crash, muse sounds, regression_ms3

**Comment by PEM-FR** [comment] 2023-05-21 04:27
I still have the problem on one of my scores...
THOUGH there has been some progress as playback no longer crashes musescore, clicking on anything inside this specific measure (except creschendo sign) makes the app crash.

Should I open a new Issue or how can I help provide more data to fix this?

**Comment by cbjeukendrup** [comment] 2023-05-21 13:43
This issue is a duplicate of #16642, so therefore it is closed. But #16642 itself is still open, awaiting a fix from the Muse Sounds team. So I'd wait until that issue is fixed, and then re-check if that has also fixed the crash for you. If not, then you can open a new issue, but let's wait for the fix for #16642 first.

**Comment by PEM-FR** [comment] 2023-05-22 04:07
@cbjeukendrup I understand, though my problem is unrelated to tubular bells (I do not have any in this specific score). Is this something more general, I could check if the same conditions are met as the ones explained in the other issue though.

**Comment by cbjeukendrup** [comment] 2023-05-22 09:37
@PEM-FR In that case, it would be great if you could open a new issue and include the specific score there.
