### ISSUE TITLE
[MU4 Issue] Tempo text in Master Palette is flying out of the screen

### ISSUE THREAD

**Issue by Skelbti** [musescore/MuseScore#15990] opened 2023-01-20 16:57 UTC
**Describe the bug**
MuseScore 4.0.1 is configured in French. When I go to the Master Palette and select "Tempo" and then hover my mouse over the text options, several texts move up as soon as I move the mouse until they disappear at the top of the window.

**To Reproduce**
1. Go to 'Master Palette'
2. Click on 'Tempo'
3. Hover on tempo text options

**Expected behavior**
No mouvement of the text

**Screenshots**
![MuseScore4_epCmdD9NIj](https://user-images.githubusercontent.com/86026713/213756203-ffa12700-a509-4b20-88d5-78cc797998aa.gif)

**Platform information**
 - OS: Windows 11 22H2

**Additional context**
MuseScore is in French.

**Comment by MarcSabatella** [comment] 2023-01-20 17:47
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/15297, and there is a pending fix.

**Closed** 2023-01-20 18:46 UTC
