### ISSUE TITLE
MIDI Keyboard Loopback in Audition State (while Input Mode OFF) - Redesign Fixed Note Length Loopback Limitation

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#19179] opened 2023-08-26 17:23 UTC
### Your idea

For directly composing on Musescore using MIDI controller/keyboard, it is productive to play-by-hands several candidate musical phrases before placing MS4 into Input Mode for score note entry.  Under MS3 this was a very productive workflow.  With MS4 each note "audition-play" loopback is fixed length duration with maximum 999ms, making this awkward, esp. for piano composers writing complex arpeggiations. 

This occurs with all audio sources: 1) MSBasic, 2) 3rd party SF2 soundfonts, 3) MuseSounds and 4) 3rd party VSTs

*  Loss of productivity for composers (but less of an issue for Transcribers)
*  Major show-stopper for using MS4 with Synthewizer VSTs!!

Recommendations:

*  In "audition state" MIDI keyboard loop-back should be a pass-through (not limited to fixed note on-off note length) [Regression MS3]
*  Also add options to allow pass-through for piano pedal, and other CCs (including Mod Wheel) [New Feature Request]

### Problem to be solved

Composing with VST Synthesizers require adjusting large number of synth parameters such as oscillators, routing/effects, cutoff filters, LFOs, ADSR and lots of CC controls.  This is not possible with current 999ms max and fixed note length limitations. 

### Prior art

Pass through seems normal for another notation software, and of course, all DAWs.

### Additional context

MS 4.1.1

Tested with Windows and Linux MS 4.1.1.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by cbjeukendrup** [comment] 2023-08-26 21:42
The fixed note duration issue is a duplicate of #13381. That has been scheduled for 4.2 with high priority, so fingers crossed :)

For the pedal / CC feature request, I'd recommend to open a new dedicated feature request.

**Closed by cbjeukendrup** 2023-08-26 21:42 UTC
Labels: feature request

**Comment by ShawTakeuchi** [comment] 2023-08-26 21:59
Apologies - I didn't use the correct set of search terms!  Will file a new feature request, thanks!

**Comment by cbjeukendrup** [comment] 2023-08-26 23:01
> Apologies - I didn't use the correct set of search terms!

Don't worry; it can happen to everyone. I also had some trouble finding the other issue, even while I know that it existed! 

I wish GitHub had an AI feature that points out potential duplicate issues while you're writing a new one. You'd say that should be easily possible these days...
