### ISSUE TITLE
Wayland scaling broken due to missing wayland libs in Appimage

### ISSUE THREAD

**Issue by MTRNord** [musescore/MuseScore#21528] opened 2024-02-14 21:56 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The scaling on wayland is now tiny as xwayland musescore doesnt respect scaling values anymore.

This likely is a regression due to #20391 and makes it unusable in 4.2.x for me as I am not going to bring a magnifying glass to my pc to read ANY text.

### Steps to reproduce

1. Setup a wayland PC (fedora silverblue kde here)
2. Run the 4.2.x appimage

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/1374914/42545ee3-d0e2-41e8-a008-ffb27198018a)

### MuseScore Version

OS: Fedora Linux 39.20240213.0 (Kinoite), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Fedora Silverblue 39

**Comment by JeffRocchio** [comment] 2024-06-11 17:53
fwiw - I also just ran into this problem with yesterday's upgrade of my linux PC (to fedora 40, KDE spin) and finally accepting for myself the migration to Wayland. Even with the KDE setting '`Legacy Applications (X11): Scaled by the system`' checked the window UI elements are too small. They definitely don't scale up to the normal sizes in all my other apps. *Without* that setting checked the UI elements are too small even for a magnifying glass.

The text as rendered in Musescore is also a bit fuzzy.

Screenshot attached comparing Musescore appearance to 'standard' apps on Wayland:
![Musescore4-in-Wayland](https://github.com/musescore/MuseScore/assets/26509192/0b856147-e54b-45a9-b526-2df2d1062445)


Based on the lack of comments and activity since MTRNord posted this back in Feb it doesn't look too hopeful for us Linux/Wayland users. But at least this is in the issue log, so hope springs eternal!

**Comment by JeffRocchio** [comment] 2024-08-24 20:43
Somewhat fixed. The RC 4.4 appimage runs fine, the fuzziness is gone, so def it is using Wayland. However, the UI elements are still considerably smaller than all my other 'Wayland Compliant' apps. Tho at least it is usable
![MS4_WaylandScaling_Comparison-2](https://github.com/user-attachments/assets/5ac0ed87-5830-4d50-a65c-4bd6d6cafa8e)
![MS4_WaylandScaling_Comparison](https://github.com/user-attachments/assets/e862ab85-ffed-46f8-b612-901a71eaf702)
. New screenshot attached for comparison.

**Comment by MarcSabatella** [comment] 2024-08-24 22:33
That doesn’t happen for me - scaling is pretty much perfect, unlike under xcb where everything is too small.  But, does QT_SCALE_FACTOR fix it?  Also, is it just the text, or is the score itself also too small?  Viewed at 100% zoom, should be life sized.

**Comment by cbjeukendrup** [comment] 2024-08-24 22:40
The relative size of the UI components looks about right; the note input toolbar is nearly as tall as the tab bar in FireFox, which matches what I see on macOS.
MuseScore's font is perhaps relatively small indeed. That's also about the same on macOS, I've never really noticed that. Must be by design, because the designers are looking at macOS (and Windows) all day. 
But you can adjust it to better match your system via Preferences > Appearance. The default is 12px. Might be interesting know what's the default in Kate, for comparison.

Anyway, it looks like the scaling issue itself is fixed, so I'll close this issue. Feel free to open a new request for a bigger default font size if you think that the current default is really too small.

**Closed by cbjeukendrup** 2024-08-24 22:40 UTC
Labels: UI, community, regression MS4, os: linux, waiting reply from user

**Comment by JeffRocchio** [comment] 2024-08-25 03:09
> But you can adjust it to better match your system via Preferences > Appearance. The default is 12px. Might be interesting know what's the default in Kate, for comparison.

I didn't even know there was that setting option in 'Appearance.' That works for everything except the top menu bar text. So that's good enough to be workable for me. The menubar text size tho seems odd as I would think that, in principle, that would be governed by the windowing system - in my case KDE and QT widgets. So why wouldn't it exactly match all the standard KDE apps? <- _That's a rhetorical question_.

Kate's UI font is simply the standard KDE system font - Kate doesn't have an option to change the UI font (tho one can set the font for the text you are editing - in my case I have it set to Noto Sans, 11 pts).

fwiw, I'm using 4k monitors, scaled to 125%.  In KDE settings I have Toolbar and menu fonts set to Noto Sans, 11 pt. I have to set Musescore Appearance font to 14 pt to get the rough equivalent appearance to all my others apps.

In any event - thanks for now getting Musescore Wayland compatable!

**Comment by JeffRocchio** [comment] 2024-08-25 03:12
> is it just the text, or is the score itself also too small?

The content portion of the window was always OK size wise, and still is. All my sizing issues have concerned only the UI elements. The score window also responds perfectly to the standard Ctrl-Scrollwheel action to resize it on the fly.

**Comment by cbjeukendrup** [comment] 2024-08-25 21:59
We do take the font family from the system, but not the font size; the way to do that would be something like `QFontDatabase::systemFont(QFontDatabase::GeneralFont).pixelSize()`, but that seems to return -1. Everything is implemented using custom QML components, so that explains why it doesn't automatically follow the KDE settings. Implementing things ourselves gives us some guarantee that they look as intended, but of course has the disadvantage of potentially not fitting well with the OS. It's always a bit of a dilemma.

**Comment by JeffRocchio** [comment] 2024-08-26 20:40
> Everything is implemented using custom QML components, so that explains why it doesn't automatically follow the KDE settings.

Ah, understood. I appreciate the explanation Casper. 

[I do have strong opinions about customizing elements that, in my mind, are meant to be common elements of the platform's windowing system, which for me I do consider the look, style, and feel of the window's menu bar to be one of those...but such opinions probably best kept to myself  : )  ]

**Comment by cbjeukendrup** [comment] 2024-08-26 20:57
Adding at least the _option_ to use a 'native' menubar is absolutely not unthinkable. The question is, though, is that something we should spend our time on right now, or at some point in the future when MuseScore is more feature-complete. But if someone wants to contribute a PR to implement such an option, we're happy to consider that. 

(For OSs that use a system-wide menubar (not only macOS), MuseScore does integrate with that menubar, using https://doc.qt.io/qt-6/qml-qt-labs-platform-menubar.html. But it doesn't look like that is going to help much for implementing a native in-window menubar.)
