### ISSUE TITLE
When playing arpeggios on the organ, the sound may not stop depending on the notes and tempo.

### ISSUE THREAD

**Issue by ker38c** [musescore/MuseScore#20815] opened 2024-01-03 11:23 UTC
### Issue type

General playback bug

### Bug description

Depending on the number of notes played at the same time in an arpeggio and the tempo, a note may continue to play until the same note is played.

I also use MuseScore 3.3.4, but this problem does not seem to occur.

### Steps to reproduce

1. Create a new score with the instrument as the organ.
2. Set the tempo as the dotted quarter note = 150.
3. Set arpeggios on four quarter notes.
4. Play the score.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/128274907/690dc37b-2fa1-4ddc-9c74-f24c8982ef50

### MuseScore Version

4.2.0-233521124

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by zacjansheski** [comment] 2024-02-28 20:48
Looks like this is actually a more recent regression that coccured between 4.1.1 and 4.2

https://github.com/musescore/MuseScore/assets/69917893/28580340-5965-4c30-9ff8-fd979f1a7fe2

**Comment by DmitryArefiev** [comment] 2024-03-19 14:34
Fixed in #21983

**Closed** 2024-03-26 08:18 UTC
Labels: P1, regression, playback
