### ISSUE TITLE
Measure numbers are placed closer to the notes and staff than articulation markings and dynamics

### ISSUE THREAD

**Issue by onnogli** [musescore/MuseScore#21681] opened 2024-02-25 23:17 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

With large measure numbers and articulation markers/dynamics, they are placed incorrectly. Someone may try to give all the parts measure numbers for every measure as that's easy to do on a computer but will result in music that's hard to read.

### Steps to reproduce

1. Make measure numbers for every measure
2. Add an articulation or a hairpin that goes through the first beat of the measure.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/103379965/1e84d390-14f1-4a82-a89c-d8944220d0ac)
![image](https://github.com/musescore/MuseScore/assets/103379965/8b6be2c8-bc01-43cd-9ef1-15aa6fd65449)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937

### Regression

No.

### Operating system

Windows 10

**Comment by oktophonie** [comment] 2024-02-26 11:43
Duplicate of https://github.com/musescore/MuseScore/issues/12955

**Closed by oktophonie** 2024-02-26 11:43 UTC
Labels: engraving
