### ISSUE TITLE
incorrect neon extentions attempt to get used on arm64

### ISSUE THREAD

**Issue by theofficialgman** [musescore/MuseScore#18497] opened 2023-07-10 04:59 UTC
### Issue type

Other type of issue

### Bug description

build issue:

https://github.com/musescore/MuseScore/blob/master/src/framework/audio/internal/fx/reverb/simdtypes_neon.h and other related files

https://github.com/theofficialgman/MuseScore/actions/runs/5503837646/jobs/10029430456#step:7:9650

### Steps to reproduce

see ARM64 CI run https://github.com/theofficialgman/MuseScore/actions/runs/5503837646/jobs/10029430456#step:7:9650

```
/MuseScore/src/framework/audio/internal/fx/reverb/simdtypes_neon.h: In constructor 'mu::audio::fx::simd::float_x4::float_x4(float, float, float, float)':
/MuseScore/src/framework/audio/internal/fx/reverb/simdtypes_neon.h:69:30: error: cannot convert '<brace-enclosed initializer list>' to 'float32x4_t' {aka '__vector(4) float'} in assignment
         s = { v0, v1, v2, v3 };
                              ^
In file included from /MuseScore/build.release/src/framework/audio/CMakeFiles/audio.dir/Unity/unity_3_cxx.cxx:11:
/MuseScore/src/framework/audio/internal/fx/reverb/reverbprocessor.cpp: In member function 'void mu::audio::fx::ReverbProcessor::calculateTailParams()':
/MuseScore/src/framework/audio/internal/fx/reverb/reverbprocessor.cpp:414:32: error: no match for 'operator[]' (operand types are 'mu::audio::fx::simd::float_x4' and 'int')
         d->damping_cf1_x4[x].a1[y] = cf1.a1;
```

these are arm32 intrinsics unless I am missing something they aren't available on aarch64

CC @vpereverzev since you authored this

### MuseScore Version

master branch

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux ARM64

**Comment by cbjeukendrup** [comment] 2023-07-10 10:36
Duplicate of #18353. See also my comment/question at the bottom of that thread; maybe you can help?

**Closed by cbjeukendrup** 2023-07-10 10:36 UTC
Labels: needs review, regression
