### ISSUE TITLE
Multi staccato dots too close to notehead/line (below only)

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#24810] opened 2024-09-18 21:48 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

**Current behavior**
Multi staccato (Tremolo panel:  ..   ...  .... )  render too close to the notehead/line when below (see image below).

1. add notes.
2. apply multi staccato
3. flip to "below"

**Expected**
Da usual spacing

### Supporting files, videos and screenshots

![multi staccato](https://github.com/user-attachments/assets/2aeb58f3-6ce6-49a2-8dde-bca37169ac03)
You can see that the staccato marks below are about to commit unholy acts with other symbols.

[multi staccato.mscz.zip](https://github.com/user-attachments/files/17050588/multi.staccato.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2-242570931, revision: 3130f97

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OsX 12.6

### Additional context

Looks fine in 4.3.  Might have bene ok in previous versions of 4.4.  I'll check a score I exported to .pdf under the previous revision and I'll report back.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-09-19 05:51
Duplicate of https://github.com/musescore/MuseScore/issues/20106
(also they aren't really staccatos)

**Closed by oktophonie** 2024-09-19 05:51 UTC
Labels: regression MS4, engraving

**Comment by RhinoHaggis** [comment] 2024-09-19 21:41
sorry, I did  a duplicate search :( .
This is identically multi-staccato notation.  (there are more multi-articulations in the symbol palette). What are they meant to be?

**Comment by oktophonie** [comment] 2024-09-20 05:37
https://w3c.github.io/smufl/latest/tables/tremolos.html
In Bravura, the reference, the dots are slightly larger than staccato dots. (In Leland, too.)

**Comment by RhinoHaggis** [comment] 2024-09-20 05:45
Ahhhhh so they are! This is very interesting!  I've only encountered multi-dot notation in handwritten scores.  I'm almost certain I was looking at multi-articulation each time (one of the scores did it with tenutos and accents as well)... but now that I know this I will have to go back and check.

Considering how much time the viola spends doing boom chucks and tremolos, I'm almost offended that I never encountered this notation playing in the local symphony as a kid 😂

**Comment by oktophonie** [comment] 2024-09-20 06:00
I'm fairly sure that, in almost all cases, staccato _is_ what's meant when you see it in a score. These SMuFL symbols look so similar that it's no surprise people take them for the same thing and try to (ab)use them as such!

Certainly we should have the ability to add multiple staccatos (or other articulation) to tremolos, etc, which would then follow the usual rules for placement, along with some options like how you want to centre or space them. That would be its own feature request.
