### ISSUE TITLE
[MU4 Issue] Attempt to duplicate element result in program freezing/crashing (Linux only)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13364] opened 2022-09-15 10:43 UTC
**Describe the bug**
Ctrl+Shift plus drag is an established way to duplicate certain elements. However if you try to use it on "non-applicable" elements you get a program freeze and often a crash. It also freezes the system for a while.

**To Reproduce**

1. Open the attached specimen score. 
[duplicate_crash.zip](https://github.com/musescore/MuseScore/files/9574417/duplicate_crash.zip)

2. Press Ctrl+Shift then attemt to drag the dynamic to a new note.

RESULT: As soon as you click on the dynamic you get a Program freeze/crash. This is repeated with other elements as well.

**Expected behavior**

Shift+Ctrl and drag should not cause a freeze or crash. Shouldn't the operation be applicable to all elements?

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3057830928, revision: github-musescore-musescore-5765547

**Comment by wizofaus** [comment] 2022-09-16 22:32
Can't reproduce on windows with latest nightly build

**Comment by DmitryArefiev** [comment] 2022-10-20 14:04
I **can reproduce** it but only on **Linux** (Ubuntu 22.04 LTS). 

The crash doesn't occur on **Mac12** or **Win10**

**Comment by DmitryArefiev** [comment] 2022-12-08 15:28
Fixed in #15041

**Closed** 2022-12-08 15:30 UTC
Labels: P1
