### ISSUE TITLE
[MU4 Issue] Corrupted .mscz Score File causing MuseScore 4 to Crash

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#15723] opened 2023-01-05 16:21 UTC
So I've recently downloaded an orchestral transcription score, which I believe came from MuseScore v3. After when I saved the file through MuseScore 4, I tried re-opening it, and I get a message saying that the score has been corrupted for some stupid reason.

But once I've ignored the message, the file which has a mixup of Muse Sounds and third party VSTs from DecentSampler were half way loading fine, but after it finishes loading, the whole application crashed.

Is it because I'm using too many VSTs, plugins, and increased the buffer size way too much?

I have a Zip file of the score right here:
[Merry-Go-Round of Life MSCZ File.zip](https://github.com/musescore/MuseScore/files/10353793/Merry-Go-Round.of.Life.MSCZ.File.zip)

**Comment by MarcSabatella** [comment] 2023-01-05 16:31
This score is indeed corrupt, but it opens withut crashing for me.  So the crash probably is related to some VST on your system.

If you are saying this corruption happened to an otherwise uncorrupted score you imported from MuseScore 3, then in order for people to investigate, you would need to post the *uncorrupted* version, and give precise steps to reproduce the corruption - eg, what editing you did between the time you opened the score and when you saved it.  It will help if you can spend some time narrowing it down to ther minimanl steps that still produce the corruption.

**Comment by RomanPudashkin** [comment] 2023-01-10 13:56
> So I've recently downloaded an orchestral transcription score, which I believe came from MuseScore v3

@cunningar0807 please attach this score. We can't reproduce this corruption on other scores. Thank you!

**Comment by Tantacrul** [comment] 2023-02-01 16:31
@RomanPudashkin - am I right in thinking these corruptions have been fixed in the first patch? If not, please reopen.

**Closed by Tantacrul** 2023-02-01 16:31 UTC
Labels: needs info, P1

**Comment by RomanPudashkin** [comment] 2023-02-01 16:37
> am I right in thinking these corruptions have been fixed in the first patch?

Yes, most likely

**Comment by cbjeukendrup** [comment] 2023-02-12 19:51
Actually, as seen in the attached score in the original comment, this corruption is _different_ from the ones that were fixed in 4.0.1. This corruption namely seems to be caused by triplets in voice 2 getting lost. However, since this issue has never come up before, and we can't reproduce the crash, we can't do anything about it, so I wouldn't mind if we don't reopen this.
