### ISSUE TITLE
Crash if you try to save a score after adding a ritardo marking

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14401] opened 2022-11-07 22:47 UTC
**Describe the bug**
Musescore 4 is crashing if I try to save a score after adding a ritardo marking.

**To Reproduce**
Create new score.
Enter some notes.
Save.
Select a measure in your score.
Open the Tempo palette and click on "rit_ _"
Try to save your score.

**Expected behavior**
Score saves without crashing.

**Platform information**
Windows 10

**Comment by blackears** [comment] 2022-11-08 00:56
This only seems to be happening with the version of the code I compiled from source.  Not having this issue with the current beta testing release.

**Comment by RomanPudashkin** [comment] 2022-11-21 17:25
I can't reproduce this crash on win 10. @blackears could you check it on the last master?

**Comment by Tantacrul** [comment] 2022-11-21 19:01
Seconded. Would be good to know if you are still getting this.

**Comment by blackears** [comment] 2022-11-21 19:33
Looks like the problem is due to something I added in my branch.  When I compile  the master branch alone, it works.  

Not sure what's causing it.  Seems to be in the QML.  I have no idea how my changes would affect saving the file.

**Comment by blackears** [comment] 2022-11-21 19:53
Just had another look.  The only thing I'm doing to the QML is adding a new component to NotationPage.qml.  Why would that cause problems saving this symbol?  I can save scores without ritardando without crashes.

**Comment by Tantacrul** [comment] 2022-11-21 21:06
OK, well, I think we can possibly close the issue then, since it seems you are aware of the source of the problem. Let me know if you disagree.

**Closed by Tantacrul** 2022-11-21 21:06 UTC
