### ISSUE TITLE
Polychords for the next version?

### ISSUE THREAD

**Issue by erickisos** [musescore/MuseScore#10872] opened 2022-03-23 02:48 UTC
Hey folks, afaik we can't create polychords by default in MS3, do we have plans to add this in the next version? 

If not, do you think that it would be valuable?

**Comment by Jojo-Schmitz** [comment] 2022-03-23 07:31
Looking at https://en.wikipedia.org/wiki/Polychord I don't see anything MuseScore can't do?

**Comment by Marr11317** [comment] 2022-03-23 17:21
Agreed, it's so common in bigband scores, so a standard way would be preferable.

**Comment by MarcSabatella** [comment] 2022-03-23 17:58
Is it that common, though?  I've played or directed literally thousands of big band charts, and can think of only about half a dozen that used polychord notation.  I have seen more that use the vertically stacked layout for ordinary slash chords, though.  So part of the problem is defining a way to disentangle these concepts - the layout versus the actual semantics.

**Comment by Marr11317** [comment] 2022-03-24 02:24
I do mean polychord notation, as in your first measure above. I've definetely played a lot less big band charts than you have, but I've seen polychords in at least a dozen. But I guess you're right, the focus should not be on that for now in MS4.

**Comment by bkunda** [comment] 2022-04-05 11:21
I have actually started a major redesign of the chord symbols system, which would in principle be able to accommodate different styles (preset and customisable) that can be easily interchangeable. I'm sure there would be a place for this within the new system.

I can't say when exactly the new system will be developed, but it won't be in time for MS4. As such, I'll make a note of this request and close the issue for now. Thanks so much for raising it!

**Closed by bkunda** 2022-04-05 11:21 UTC
