### ISSUE TITLE
Double barline are not joined when imported from XML

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#20699] opened 2023-12-25 10:55 UTC
### Issue type

Import/export issue

### Bug description

Double barline are not joined when imported from XML

### Steps to reproduce

1. Create a score with multiple part.
2. Join barline
3. Export to XML file
4. Close MuseScore
5. Reopen MuseScore
6. Import XML 

Double Barline are not join in 4.2.
Same Bug on Master too
Work in MuseScore 3

This is an import issue because same issue occur from file exported with MakeMusic Finale

### Screenshots/Screen recordings

This score was exported To XML
![image](https://github.com/musescore/MuseScore/assets/1835871/2946ae77-0d48-41c4-830f-bcb5cf94fe7a)

This score was imported from previous exported file XML
![image](https://github.com/musescore/MuseScore/assets/1835871/954ed1d2-4d4e-4d22-ac8c-2f599f6b341e)

Sameissur with end Bar
![image](https://github.com/musescore/MuseScore/assets/1835871/7d7aa662-5e63-4a94-a743-e5c8ee0bf509)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Choose option...

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by rettinghaus** [comment] 2024-01-09 12:38
All barlines except single and repetition barlines are affected.

![image](https://github.com/musescore/MuseScore/assets/7693447/ccc17787-9d39-49bd-af7a-0eabbfa463e5)

**Comment by lvinken** [comment] 2024-02-06 05:19
Working on it ...

**Comment by lvinken** [comment] 2024-02-13 18:36
The issue is caused by commit https://github.com/musescore/MuseScore/commit/cfbbea815739705d4f9338efb2ec2737314163ed ([iveshenry18](https://github.com/musescore/MuseScore/commits?author=iveshenry18) committed on May 28, 2021), ported to 4.2 as commit https://github.com/musescore/MuseScore/commit/e6586f6f3ad17471d4be78b09e79486412e4a689 ([mike-spa](https://github.com/musescore/MuseScore/commits?author=mike-spa) committed on Nov 16, 2023).

If you want I can provide a fix, but I would like feedback by [mike-spa] first, as I do not know why this change was made and I may have overlooked something.

**Closed** 2024-05-17 07:49 UTC
Labels: P2, regression_ms3, MusicXML
