### ISSUE TITLE
Line with arrowhead ends

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#20705] opened 2023-12-25 17:20 UTC
### Your idea

Allow lines to have arrowhead at their ends.

![image](https://github.com/musescore/MuseScore/assets/70313425/697c1e6d-5028-47fa-a886-f8a4d25c98c6)
![image](https://github.com/musescore/MuseScore/assets/70313425/4278fc60-7218-4403-93f8-a32d2a641a2e)
![image](https://github.com/musescore/MuseScore/assets/70313425/2ecfbdb3-e2b7-4932-af7f-e86b0f078a68)
![image](https://github.com/musescore/MuseScore/assets/70313425/1d8d0675-5a8f-46e4-8414-e1df8bcab28e)

### Problem to be solved

Will be useful in contemporary notation:

- Voice passed to another stave.
- Indeterminate number of repeats within a fixed duration.
- Gradual changes in technique, etc.
- Other general annotations.

**Comment by oktophonie** [comment] 2023-12-25 17:30
Duplicate of https://github.com/musescore/MuseScore/issues/15168

**Closed by oktophonie** 2023-12-25 17:30 UTC
Labels: feature request
