### ISSUE TITLE
[MU4 Issue] Instrument change between instruments in the same key (not C) cause incorrect key signatures

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#14705] opened 2022-11-24 01:21 UTC
**Describe the bug**
Adding an instrument change between instruments in the same key (not concert C) cause incorrect key signatures to be added to that instrument (but not others in the score).

**To Reproduce**
1. Create a new score with a Bb Clarinet and a Piano.
2. Midway through the score, add an Instrument Change to Bb Trumpet.
3. Even though these instruments are in the same key, MuseScore adds a different key signature to the trumpet part -- while also not altering the key of the piano part.

**Expected behavior**
Changing from one Bb instrument to another shouldn't change the key signature.

**Screenshots**
![image](https://user-images.githubusercontent.com/91428485/203673062-988c9268-6c42-4667-90ed-0bd713cd78aa.png)

**Platform information**
 - OS: Windows 11

**Additional context**
The incorrect key signature can simply be deleted, but it's possible that users not familiar with the keys certain instruments are written in (e.g. alto sax) may not notice the discrepancy.

**Comment by sammik** [comment] 2022-11-24 07:57
Happens in MU 3.6.2 too

**Comment by Tantacrul** [comment] 2022-11-28 11:32
Duplicate of https://github.com/musescore/MuseScore/issues/14722

Which I have placed in our **release** project. Thanks!

**Closed by Tantacrul** 2022-11-28 11:32 UTC
Labels: P1
