### ISSUE TITLE
[MU4 Issue] Continuous view distortes page layout

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14336] opened 2022-11-05 14:27 UTC
When working in Continuous View (Horizontal), the page gets vertically condensed to the point where staves get very close to each other and stave text starts to overlap. This becomes more and more of an annoyance the bussier a score gets. I see no reason why there is a limitation on the vertical size of the page and certainly not why it seems to be smaller than the actual page view. For the sake of ease of use, it would make sense to me if there were no constraints on verticality in this continuous mode. It is after all only when a score needs to be printed that proper layout comes into play and that's only a problem for the page view as that is the one being printed.
![Screenshot (6)](https://user-images.githubusercontent.com/115939617/200124605-3459bebb-4182-4c9e-9639-538dff1e9c4a.png)
![Screenshot (7)](https://user-images.githubusercontent.com/115939617/200124662-cdd3f090-feab-4e49-82b1-55ce4a899626.png)

**Comment by MarcSabatella** [comment] 2022-11-05 16:23
MuseScore *should* be adding space as needed in continuous view, no overlaps, and there should be no limit on the vertical size.  If you have a score where this isn't happening, please attach it (ZIP it so GitHub will accept it) so it can be investigated

If you wish more space in general for the staves while the score is empty, you can increase the minimum staff distance in Format / Style / Page.  But probably there should be a higher minimum used in continuous view, or an automatic vertical "stretch" added.

**Comment by Grim-O** [comment] 2022-11-05 16:29
it's not just in 1 score, it's in any score

**Comment by MarcSabatella** [comment] 2022-11-05 16:43
It works fine for me in my score - all staves are always shown.  So if you're seeing an in multiple scores, probablythey have something in common not present in my score.  Anyhow, if it happens in multiple scores, should be easy to choose one to attach.

Again, it's not a bug that the default space is small, although i agree it could be expanded.  It's a bug if there are overlaps, and it's a bug if they don't actually fit on the "page" when in continuous view.  Those are the problems I cannot reproduce, so we'd need a sample score in order to investigate.

**Comment by Grim-O** [comment] 2022-11-05 17:12
[Continuous view squashed.zip](https://github.com/musescore/MuseScore/files/9944356/Continuous.view.squashed.zip)
I hope this helps. It happens by default.

**Comment by MarcSabatella** [comment] 2022-11-05 18:21
I don't see any overlap, nor do I see anything being cut off becuase there isn't enough vertical space.  If you add notes, you will see the space expand automaticaly.

So it's exactly as I said - the default minimum staff space is being honored, and if you want more space, you can simply increase that setting.

And yes, I do agree that by default, MuseScore should automatically apply additional stretch so empty scores don't look a little odd.  But, again, there is no overlap, and there is no limitation on the vertical size of the page.  MuseScore will always avoid overlap, and it will always expand to make sure everything fits.  Again, if you have a score that shows overlap, or shows things not fitting because of a limit on vertical space, that's what we'd need to see an example of.  you men an issue that happened "the busier a score gets".  So maybe there is something specvific about the your busy score that is triggering a problem I can't reproduce.  If so, please attach *that* score.  But if it's just a matter of the default minimum staff space being low, no need to attach another score.  Only if you are seeing actual overlaps, or actual cases of something not fitting on the "page".

**Comment by Grim-O** [comment] 2022-11-05 19:20
I think I figured out what was wrong. in style, page, there's a setting limiting the vertical stave sizes I had enabled. disabling that fixes the continuous view problems but creates weird layouts in page view. at least now I know that option exists and I can switch between the 2.

**Comment by MarcSabatella** [comment] 2022-11-05 20:24
I'm not sure what you mean by "limiting the vertical stave sizes", but the only style setting that should be capable of creating overlaps is settings a negative "min vertical distance" in Format / Style / Score.  So it would still be interesting to see your score in order to understand what you mean.  If there is a problem, we want to be able to reproduce it so it can be fixed.

**Comment by Grim-O** [comment] 2022-11-05 20:44
I looked up the proper name. it's in format/style/page "enable vertical justification of staves". this features makes my continuous view unable to extend vertically and thus forces those overlaps

**Comment by MarcSabatella** [comment] 2022-11-05 21:02
Again, that shouldn’t happen, and doesn’t for me.  We’d really like to be able to help, but once more, I order to do so, we need to see a score that demonstrated the problem.

**Comment by Grim-O** [comment] 2022-11-05 21:09
[Continuous view squashed (2).zip](https://github.com/musescore/MuseScore/files/9944711/Continuous.view.squashed.2.zip)
This is the easiest way I can show it. I hope it helps

**Comment by MarcSabatella** [comment] 2022-11-05 23:27
Did you attach the wrong file?  This is still the same empty score as before - no overlaps, no problems with anything not fitting because of lack of vertical space.  You mentioned a problem with a "busy" score, I assuemd that meant, one that actually had notes in it?  Again, if there sis an actual bug, I'd love to see how to reproduce it so it can hopefully be fixed.

**Comment by Grim-O** [comment] 2022-11-05 23:39
it's not empty? there's a clear overlap of octave and pedal lines in the tuba and trombone staves

**Comment by MarcSabatella** [comment] 2022-11-06 01:35
As I said, I think attached the wrong file.  It’s just another copy of the same empty score as the last.  Please try again.

**Comment by MarcSabatella** [comment] 2022-11-06 04:31
Oh, I just noticed, you're right, not *completely* empty.  I can confirm the overlapping lines here.  Best to report that as a separate issue.  They don't just overlap between staves; they also don't avoid notes above/below the staff to which they are attached.

**Comment by Tantacrul** [comment] 2022-11-21 16:11
I think we a have agreed for a while that continuous view needs some extra love when it comes to making sure collisions are avoided. @oktophonie is certainly aware of it. I'm going to close this issue since I don't think it can be directly addressed any time soon. If anyone disagrees, perhaps we jus create a new issue where the specific overlapping is pointed out.

**Closed by Tantacrul** 2022-11-21 16:11 UTC
