### ISSUE TITLE
Musescore 4.4 breaks pizzicato in existing file

### ISSUE THREAD

**Issue by RichardJECooke** [musescore/MuseScore#24342] opened 2024-08-31 10:56 UTC
### Issue type

General playback bug

### Description with steps to reproduce

Play attached file in Musescore 4.4. The basses are now playing arco not pizzicato. They were playing pizz previously, as per staff text instruction.

This is on Ubuntu btw, Musescore from appimage.

[2024-07-15.zip](https://github.com/user-attachments/files/16824454/2024-07-15.zip)

### Supporting files, videos and screenshots

-

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 24.04

### Additional context

-

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by adavismusic89** [comment] 2024-08-31 14:53
This is also occurring on the MacOS version.

**Comment by adavismusic89** [comment] 2024-09-03 19:28
May I ask why this is not being considered something that should be included in MS 4.4.1?

**Comment by MarcSabatella** [comment] 2024-09-03 20:10
I can confirm the bug on Linux, but I *think* it's actually just one example of a more general issue that was has been mentioned a few times before: sound flags in general are not functioning correctly in Linux.  Supposedly this is because it's still on the older Muse Sampler.  See https://github.com/musescore/MuseScore/issues/24224

That wouldn't explain it not working on macOS, but since you saying you are using MS Basic on that system, that *would* explain it - sound flags are not a thing for soundfonts.  In any case, you don't need sound flags for pizz, just use the predefined marking on the Text palette (a "playing technique annotation".  That should work on both MS Basic and Muse Sounds.

I'm not totally convinced that the Linux issue is just about the sound flags in general, though, because the choir sound flags *are* working.  But maybe it has to do with the versions of the sounds.  On my system at least, the string sounds report as "beta", and maybe those need the updated sampler.

**Comment by adavismusic89** [comment] 2024-09-03 21:23
I am using the Text palette to switch from Arco to pizz and the sound is not changing for MS Basic sounds.

**Comment by MarcSabatella** [comment] 2024-09-03 22:00
Again, sound flags don't work for MS Basic - that much is to be expected.  The score you attached here uses sound flags, and those are known to not work reliably on Linux right now.  Hopefully that is fixed when we get the Muse Sampler update.

But on MS Basic. sound flags are not supporte.d  They don't exist - there is no way to create one.  The correct way to switch to pizz is to use the predefined "pizz." text on the palette, which is not a staff text with a sound flag - it's a "playing technique annotation" (as you can see by checking the status bar.

If you have a score where you are using the "pizz." text and it is not triggering pizzicato playback with MS Basic, that's a separate unrelated bug.  But I c annot reproduce it.  If you are sure you are seeing that, please open a new issue and attach that score.

**Comment by RomanPudashkin** [comment] 2024-09-04 15:03
@RichardJECooke this issue is a duplicate of https://github.com/musescore/MuseScore/issues/24224 (but less obvious). And it has already been fixed in 4.4.1 (you can download the latest nightly to try)

**Closed by RomanPudashkin** 2024-09-04 15:03 UTC
Labels: regression MS4, playback
