### ISSUE TITLE
[MU4 Issue] "Program" and "Programme" both used in EN-US

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#12334] opened 2022-07-10 21:29 UTC
**Describe the bug**
In the sidebar of the Preferences menu (Edit > Preferences...), there is a sub-tab under General which is correctly named **"Program Start."** However, the actual Program Start menu is headered **"Programme Start."**

**Expected behavior**
The usual spelling in EN-US is "Program."

**Screenshots**
![image](https://user-images.githubusercontent.com/91428485/178162597-715d86f3-17d8-4ed1-80ca-bda39f6a9a31.png)

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment] 2022-07-10 23:02
This is a duplicate of #12172. Thanks for reporting though!

**Closed by cbjeukendrup** 2022-07-10 23:02 UTC
