### ISSUE TITLE
[MU4 Issue] Applying shortcut "V" (hide) gives a different result than unchecking "Properties: Visible" for notes

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13114] opened 2022-09-01 09:15 UTC
**Describe the bug**
There has been a change in behaviour from MS3 to MS4. In MS4, if you select a note, unchecking the "Visible" box (Properties) hides _all_ notes and stems in the same voice at that point in the score. But keyboard "V" only hides the notehead.

Is this by design or a bug?

**Expected result**

Both operations should hide the notehead only.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2968922506, revision: github-musescore-musescore-88bdf50

**Comment by HemantAntony** [comment] 2022-09-01 09:21
Related, but not a duplicate of #11740

**Comment by RomanPudashkin** [comment] 2022-12-01 08:02
Duplicate of https://github.com/musescore/MuseScore/issues/11740

**Closed by RomanPudashkin** 2022-12-01 08:02 UTC
