### ISSUE TITLE
[MU4 Issue] If Add button tooltip appears, it removes selection when choosing multiple instruments (Add instruments window)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12862] opened 2022-08-15 10:30 UTC
**To Reproduce**

https://user-images.githubusercontent.com/90187801/184619941-227c12ea-8ba7-4799-8c31-8cd5d6ca7675.mp4

**Platform information**
macOS, Windows, Linux

**Comment by Tantacrul** [comment] 2022-10-08 14:49
Arg, Yeah, that's really stupid. I'd almost put this in Beta 1.

**Comment by cbjeukendrup** [comment] 2023-08-06 11:43
I can't reproduce this anymore. @DmitryArefiev Could you please check if we can close this?

**Closed** 2023-08-08 14:45 UTC
Labels: P2, community, needs testing
