### ISSUE TITLE
[MU4 Issue] Crashes when unplugging earphones

### ISSUE THREAD

**Issue by PunnyBunny** [musescore/MuseScore#15774] opened 2023-01-09 04:20 UTC
**Describe the bug**
Musescore 4 crashes when I unplug my earphones while playing the passage.
Earphones are plugged in the 3.5mm hole.

**To Reproduce**
1. Start musescore 4 with earphones plugged in.
2. Play something.
3. Unplug the earphones.
4. It crashes.

**Expected behavior**
The audio switches to speaker of the computer.

**Platform information**
 - OS: Windows

**Comment by Eism** [comment] 2023-01-09 07:53
Duplicate of https://github.com/musescore/MuseScore/issues/15029
Thanks for reporting!

**Closed by Eism** 2023-01-09 07:53 UTC
