### ISSUE TITLE
Chord symbol bug

### ISSUE THREAD

**Issue by ahs613** [musescore/MuseScore#19439] opened 2023-09-18 17:36 UTC
### Issue type

UI bug

### Bug description

 I downloaded 4.1.1.232071203 revision e4d1ddf. On a Mac with OS 13.5.2, Command-K (⌘K) no longer creates a text box for a chord symbol. Instead, it creates cross-hairs with coordinates. The only way to enter a chord symbol now is from the menus (Add > Text > Chord symbol), even though ⌘K is still listed as a way to do this from the keyboard. 

### Steps to reproduce

Click on a note
Press ⌘K
The field for entering a chord symbol doesn't appear at all

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/145369209/284f09d9-abf9-477e-ada5-e243fccc6301

### MuseScore Version

4.1.1.232071203 revision e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Mac OS 13.5.2

### Additional context

⌘K may have worked in 4.0.2 and definitely worked in 3.6.2. But after installing 4.1.1, it doesn't work even if I go back to the earlier versions of the app.

**Comment by MarcSabatella** [comment] 2023-09-18 17:43
That cross-hair is not a MuseScore feature.  It appears some other utility on your system has usurped this shortcut and made it unavailable to applications.  Either disable that other application, or customize the chord symbol shortcut in MuseScore to be something else (see Edit / Preferences / Shortcuts).

**Comment by zacjansheski** [comment] 2023-09-18 18:38
Closing as system specific/not reproducible.  Please see Marc's comment for troubleshooting.

**Closed by zacjansheski** 2023-09-18 18:38 UTC
Labels: needs info, UI, regression_ms3

**Comment by cbjeukendrup** [comment] 2023-09-19 16:08
That looks like the screenshot tool of macOS; check System Preferences > Keyboard > Keyboard shortcuts > Screen shots (or something like that, I don't know what's it called in English) to see if you (accidentally?) customised the shortcut to Cmd+K.
