### ISSUE TITLE
[MU4 Issue] MuseSounds Strings: 16th Tremolo Through Stem Will Playback As 8th-Note Tremolo

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#14492] opened 2022-11-12 10:34 UTC
**Bug description / reproduction instruction**
- Select any bowed string instrument with the MuseSounds sound font activated through the mixer
- Write a note with 16th tremolo through the stem
- hear eight notes in the playback and export instead of 16th notes
- it does not happen if the basic sound font is active 

<img width="947" alt="Bildschirmfoto 2022-11-12 um 11 28 40" src="https://user-images.githubusercontent.com/109522890/201470123-22bd67bc-b341-4ccf-8709-debbd42751bd.png">

- please check the attached .zip archive for the score and an .mp3 file of the bug: 

[MuseSounds-Strings-16th-tremolo-bug.zip](https://github.com/musescore/MuseScore/files/9994757/MuseSounds-Strings-16th-tremolo-bug.zip)

**Expected behavior**
- Should instead play 16th tremolo

**Platform information**
- OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289913152, revision: github-musescore-musescore-1ac395a

**Comment by cbjeukendrup** [comment] 2022-11-12 22:13
This is a duplicate of #13913. Thanks for reporting!

**Closed by cbjeukendrup** 2022-11-12 22:13 UTC
