### ISSUE TITLE
[MU4 Issue] Beams incorrectly joined between beats containing sixteenths

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11657] opened 2022-05-17 02:53 UTC
The usual rules of notation as followed by MuseScore for simple meter say that if sixteenth are present in a beat, that beat should not be beamed to other beats.  That is what the beam grouping for the 4/4 time signature shows, and how MU3 works.  MU4 however, breaks this rule when creating scores from the predefined templates.  Apparently, if the first beat *starts* with an eighth note, it allows the beat to be beamed to the next beat even if there are sixteenth present later.  You have to break the beam into the second beat manually to get the correct beaming.  So:

![image](https://user-images.githubusercontent.com/1799936/168718583-6fdf408f-6cdb-4162-8e1e-adf8269a850d.png)

MU3 gives the correct result by default, and so does MU4 *if* you use "choose instruments" instead of a template.  I'm not sure if *all* of the templates are broken, but at least the ones I tried (including "treble staff") are.

So to reproduce:

1) new score from treble staff template
2) first measure, note input mode
3) 4 . C 3 D 4 E F

Result: all notes beamed together as shown above

**Comment by oktophonie** [comment] 2022-05-17 09:40
I cannot reproduce this one; can anyone else?
#11608 does touch some relevant code but it's not merged yet! (and in any case is intended to fix problems just like this, though mostly pertaining to tuplets)

**Comment by MarcSabatella** [comment] 2022-05-17 12:44
New info: for me it works as expected if creating a score via “choose instruments”, but fails as shown when creating the score from a template.  So far I’ve found treble staff, grand staff, string quartet, and barbershop quartet all fail in the same way.

**Comment by oktophonie** [comment] 2022-06-21 13:01
So, what I've found is that if I start with a _template_ (I was trying String Quartet) and input the dotted rhythm, I get this:
![image](https://user-images.githubusercontent.com/20604032/174804851-dd5942ee-ab79-4174-ad49-2620eda7c13e.png)
(I input the rhythm as four 8ths, then dotted the first)

However! if I trigger a re-render, it then becomes this, which is what we want:
![image](https://user-images.githubusercontent.com/20604032/174804983-1663b37b-c53e-40b8-89e6-4594cf9363bf.png)

So it seems the beam is being broken when the 16th appears in the group, but for some reason the re-render doesn't show it until you do something to trigger it. And, curiously (as Marc describes), if I input this rhythm in a score created via 'Choose Instruments', the beam breaks immediately, as expected. So I'm not sure why template files behave differently, but they do.

**Comment by oktophonie** [comment] 2022-06-21 16:32
That was removed from all the templates in #11811.

**Comment by wizofaus** [comment] 2022-06-21 23:55
I can't reproduce having a "re-render" trigger a beam split, what exactly did you try? Closing and re-opening does the trick though.

**Comment by oktophonie** [comment] 2022-06-22 06:14
Add a time sig in the second bar, put a system break in the middle of the first system. etc.

**Comment by wizofaus** [comment] 2022-06-22 07:23
Time sig trick works, thanks.  Not having much luck figuring out where the issue, but it seems to be how notes are added to the beam as children, rather anything in the layout() logic.

**Comment by wizofaus** [comment] 2022-06-22 07:38
Narrowed it down to 
`TimeSig* ts = stf->timeSig(measure->tick());` returning null when entering into new score from template. Normally it returns the expected time signature.

**Comment by wizofaus** [comment] 2022-06-22 08:34
Changing `measure->deleteLater()` to `measure->clearElements()` in `clearMeasures()` (MasterNotation.cpp) seems to do the trick...not sure really in what cases clearMeasures() is really needed at all, if I have a template with notes etc. in it, maybe I want them there!

**Comment by asattely** [comment] 2022-08-03 18:47
So, after a bit of research, the problem seems to be here: https://github.com/musescore/MuseScore/blob/214026b361f45bc8a14efa571230d5636a0824f8/src/engraving/libmscore/segment.cpp#L227

Which is called when the segments in the measures that are deleted later that @wizofaus identified delete all their segments. When creating a score from a template it marks all the measures for deletion and adds a brand new set of 32 measures (including the correct time signature). However, when a TimeSig segment is removed, it removes the TimeSig from the map without checking to see if there is still a TimeSig segment there. Therefore, there is a TimeSig segment, but it is not included in the staff's timesig map.

**Closed** 2022-08-04 10:23 UTC
