### ISSUE TITLE
MIDI Note Input - Yamaha MX88

### ISSUE THREAD

**Issue by MusicalIdea1** [musescore/MuseScore#18609] opened 2023-07-14 18:07 UTC
### Issue type

Other type of issue

### Bug description

When inserting notes using the MIDI feature on my keyboard (Yamaha MX88), Musescore 4 doesn't continually advance to the following beat/duration when the key is released. As demonstrated in the video, the Musescore 4 MIDI feature only allows me to insert a few notes before it is either reluctant to move to the following beat/duration, therefore, resulting in a cluster of notes, or the feature just completely stops working as demonstrated in the last portion of the video. When inserting chords, the MIDI feature doesn't always enter the entire chord. It seems that only a few notes are registered at a time. When relaunching Musescore 4, it fixes the issue only for about a minute (maybe less than a minute) before the issue reoccurs. This issue occurred in all Musescore 4 versions. In Musescore 3, there are no issues regarding MIDI input.

### Steps to reproduce

1. Launch Musescore 4
2. Choose any score and instrument 
3. Choose MIDI device if necessary
4. Buffer Size remains at 1024
5. MIDI Input remains at Port 1
6. No MIDI out is selected
7. "Produce MIDI 2.0 output" feature remains unselected
8. Press "N" to insert notes
9. Play any pitches on your MIDI keyboard fast or slowly
10. Play any chord using the MIDI keyboard

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139575955/2fc90850-21aa-4b58-a489-8d48e6f0d6a1

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS Ventura 13.4

**Comment by bkunda** [comment] 2023-07-18 08:47
Hi @MusicalIdea1,
We are unable to reproduce this with keyboards our team uses for testing, so I wonder if it might be an issue with your particular keyboard? 
How old is your keyboard? Perhaps there's a velocity curve setting (or similar) on your keyboard that's causing this problem in MuseScore? Does a factory reset on the keyboard make any difference? Do you have access to any other keyboards to compare it with? 
The only way we can really get to the bottom of this ourselves is for someone on our team to obtain the same device to troubleshoot and address any problems that may come up, so if you are able to help us with further troubleshooting, that would be great – otherwise it might be some time before we can look at this specific keyboard.

**Comment by DmitryArefiev** [comment] 2023-12-30 20:13
@MusicalIdea1  Please try build from #20568 (https://github.com/musescore/MuseScore/actions/runs/7274008016)

**Comment by MusicalIdea1** [comment] 2023-12-31 19:17
Hi, @DmitryArefiev 

The build's MIDI input via the MX88 works very well. No issues at all. Thanks for solving this so soon.

**Comment by DmitryArefiev** [comment] 2024-01-01 19:33
@MusicalIdea1 Great! Thanks for checking! 

Can you also check the bug on 4.2.1 build please? (if it was solved before the PR) https://github.com/musescore/MuseScore/actions/runs/7375066173

**Comment by MusicalIdea1** [comment] 2024-01-01 22:20
@DmitryArefiev Unfortunately, the bug is still there in the 4.2.1 build.

**Comment by DmitryArefiev** [comment] 2024-01-02 21:23
@MusicalIdea1 Great! That means the issue was fixed in #20568

**Comment by MusicalIdea1** [comment] 2024-01-02 22:39
@DmitryArefiev Awesome! Thanks again.

**Closed** 2024-01-08 13:50 UTC
Labels: P2, regression_ms3
