### ISSUE TITLE
Recent nightlies crash

### ISSUE THREAD

**Issue by Zephereth** [musescore/MuseScore#23896] opened 2024-08-05 02:36 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Download one of the recent nightlies from the last few days.
2. Change an instrument sound to one of the new Musehub sounds, I.E. Berlin Brass.
3. Instant crash. (for me)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/826d9db9-f9b2-452f-afba-358d92998c3e

### What is the latest version of MuseScore Studio where this issue is present?

Nightly MU4_24170305

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I am using Nightly 242110305 and it doesn't crash when using these new sounds.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment] 2024-08-06 13:33
Does this occur for you with any Muse Sounds library, or only paid ones?

**Comment by bkunda** [comment] 2024-08-06 13:33
Also can you please share your sampler version number (go to Diagnostic > Check musesampler)?

**Comment by MovableFormula** [comment] 2024-08-06 14:11
> Does this occur for you with any Muse Sounds library, or only paid ones?

I can chime in and say it works fine with the free library and only crashes with the paid ones. Sampler version I’m using is 0.100.0.261

**Comment by Zephereth** [comment] 2024-08-06 14:20
> Does this occur for you with any Muse Sounds library, or only paid ones?

As MovableFormula said, it's only with the paid ones.

> Also can you please share your sampler version number (go to Diagnostic > Check musesampler)?

I can't check this information right now as I'm away from home, but I believe it may have been the version posted on the discord when first testing the new sampler:  https://github.com/musescore/MuseScore/actions/runs/9969308796/artifacts/1709471472 
I'll send a new comment once I know for sure.

**Comment by MovableFormula** [comment] 2024-08-06 14:23
I’ll also add that this seems to be the same issue as the one the sampler test had. The nightlies around that time worked just fine, seems like something might’ve gone wrong somewhat recently.

**Comment by bkunda** [comment] 2024-08-07 15:39
Seems like a duplicate of [this issue](https://github.com/musescore/MuseScore/issues/23722), which has now been resolved on the sampler end. 

Will reopen if the problem persists after the sampler update is pushed to production.

**Closed by bkunda** 2024-08-07 15:39 UTC
Labels: needs info, P0, regression MS4, crash, waiting reply from user
