### ISSUE TITLE
Continuous View not showing barlines or stavlines, quite laggy

### ISSUE THREAD

**Issue by jegmanu** [musescore/MuseScore#11178] opened 2022-04-13 12:26 UTC
**Expected behavior**
A continuous view of the score, similar to MS 3.6

**Platform information**
 - OS: Windows

**Additional context**
Three instruments, standard fonts, layout etc.

**Comment by RomanPudashkin** [comment] 2022-04-13 12:35
The description of the issue is very vague. Do you mean this problem?
https://github.com/musescore/MuseScore/issues/10973

It has already been fixed in the main branch

**Closed** 2022-04-13 14:34 UTC

**Comment by jegmanu** [comment] 2022-04-15 14:22
Ah, yes, exactly. Thanks!
