### ISSUE TITLE
[MU4 Issue] Can't select an image inside a vertical frame by clicking on it

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13664] opened 2022-10-08 10:49 UTC
You can't select an image inside a vertical frame by clicking on it
(like you can in MU3 without a problem)
unless the image exceeds the borders of the frame.

Steps to reproduce:
- add vertical frame
- add image, smaller than the vertical frame, to vertical frame
- try to click on image to select it

**Comment by sammik** [comment] 2022-10-08 11:30
You can, but you need to Ctrl + Drag over

https://user-images.githubusercontent.com/1646034/194705252-966258ea-1883-442c-bdc8-d57682c7f9f1.mp4

**Comment by oMrSmith** [comment] 2022-10-08 11:43
I see. But this would be a step back compared to MU3.
Also even after selecting with control drag 
the handles to resize the image are not shown.

**Comment by MarcSabatella** [comment] 2022-10-08 13:34
This is actually a duplicate of https://github.com/musescore/MuseScore/issues/12934.  It certainly isn't *intended* you should have to drag-select or use the other workaround suggested in the other issue (sending the frame to the back).  But until the z-order issue is addressed (either by changing the default for images, or for frames, or special-casing this), those are the workarounds.

**Comment by oMrSmith** [comment] 2022-10-08 13:43
> It certainly isn't _intended_

That's good to hear! So it's a matter of time (and effort).

**Comment by cbjeukendrup** [comment] 2023-03-04 19:55
Duplicate of #12934. Will be fixed in 4.0.2.

**Closed by cbjeukendrup** 2023-03-04 19:55 UTC

**Comment by oMrSmith** [comment] 2023-03-04 19:56
> Will be fixed in 4.0.2.

Cool!

**Comment by aPersonWhoHasViolins** [comment] 2024-07-20 06:25
I just made an account to comment on this. The problem wasn't solved in my Musescore studio 4.3.2 version. I couldn't just press CTRL and drag to select it, it does not let me do this. By the way, The text font _Franklin Gothic Medium Cond_ doesn't show correctly in the website.

**Comment by sammik** [comment] 2024-07-20 06:57
> The problem wasn't solved in my Musescore studio 4.3.2 version. I couldn't just press CTRL and drag to select it

I can normaly select image (just clicking on it is enough).

Could You please attach affected file (you need to rename "mscz" to "zip" to be able attach it here.

**Comment by aPersonWhoHasViolins** [comment] 2024-07-20 10:22
By the way it is a arragement of something, I'm not sure if it is legal to do that without the original musician's permission. I've seen a lot of remixes on Youtube.
https://musescore.com/user/78284011/scores/19798705/s/3ihjGL
<img width="263" alt="Screenshot 2024-07-20 181348" src="https://github.com/user-attachments/assets/dbf3e0e3-05c1-4825-966c-2662aa82ffe8">
supposed to be like this
<img width="233" alt="Screenshot 2024-07-20 181429" src="https://github.com/user-attachments/assets/80ce6f31-29dd-4ac2-94e2-90b95c6f7ba0">
It looks terrible in the website

**Comment by sammik** [comment] 2024-07-21 13:43
Please, attach file here.

**Comment by aPersonWhoHasViolins** [comment] 2024-07-24 12:22
I see, I misunderstood! Uhh, wait how do I...It's here
Github says "We don’t support that file type."
Honestly, I think I'll take a while to fidn a way to rename or something I don't know

**Comment by oktophonie** [comment] 2024-07-24 12:29
Just put the file into a .zip, or, the even lazier option, rename it from .mscz to .zip.

**Comment by aPersonWhoHasViolins** [comment] 2024-07-24 12:40
It won't work.

**Comment by sammik** [comment] 2024-07-24 12:57
May be upload it somewhere a post a link here?

**Comment by aPersonWhoHasViolins** [comment] 2024-07-25 06:32
'k wait a minute.
