### ISSUE TITLE
Untranslatable label in MuseScore 4.3

### ISSUE THREAD

**Issue by Dawei-Zhu1** [musescore/MuseScore#22587] opened 2024-04-26 06:19 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

There are some labels that fail in displaying translations.

### Steps to reproduce

1. Go to MuseScore 4.3
2. Update translation
3. Restart
4. Check the palette

### Screenshots/Screen recordings

<img width="305" alt="image" src="https://github.com/musescore/MuseScore/assets/144910267/32b17786-b6e2-4ff0-a451-4fa1445a142e">

### MuseScore Version

4.3.0-241101558

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.4

### Additional context

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241101558, revision: github-musescore-musescore-49f06da

**Comment by Jojo-Schmitz** [comment] 2024-04-26 06:35
Try Help > Revert to factory settings
Actually this is a duplicate of #20766

**Closed** 2024-04-26 06:56 UTC
Labels: UI, duplicate, regression
