### ISSUE TITLE
Move Single Note to Staff Above/Below

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25794] opened 2024-12-10 04:41 UTC
### Your idea

This is a very unique, very messy measure of a piano part for an orchestral piece:
![image](https://github.com/user-attachments/assets/841f0608-eb56-497e-85e0-16be591ce451)
Musescore is making correctly notating this difficult. I would like to change the upper staff to treble clef and move the C5 to the staff above, but if I select Cross Staff Beaming -> Move to Staff Above, it moves both the C5 and the A2:
![image](https://github.com/user-attachments/assets/81afced5-94b0-4eae-ab53-9e992a89071f)
The best I can do is shown in additional context, but to be clear, my request is this: **Please make move to staff above/below apply to only one note.** 
There is another example from Reubke's Sonata in C minor where this is also very necessary.
![image](https://github.com/user-attachments/assets/41543b97-eb6c-4b6f-a2f0-77d8254b8ffd)

### Problem to be solved

See above.

### Additional context

Correct notation:
![image](https://github.com/user-attachments/assets/c5ad93c2-a0b2-497f-9a2e-4f4bfdf42cf0)
The Reubke piece was notated by writing the upper notes on the upper staff, and then lengthening the stems of the lower notes until they reached the upper staff. Normally Musescore does not allow you to do this, but it seems a bug made this possible...
I didn't file a bug report because I did not have enough information, but I am mentioning it here in case someone wants to look into it. I think perhaps Musescore should allow connecting stems between staves in addition to the feature request above.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-12-10 06:53
Duplicate of https://github.com/musescore/MuseScore/issues/15544

**Closed by oktophonie** 2024-12-10 06:53 UTC
Labels: feature request
