### ISSUE TITLE
Loop playback not working correctly (score with repeats)

### ISSUE THREAD

**Issue by Pazukulele** [musescore/MuseScore#20623] opened 2023-12-21 12:19 UTC
### Issue type

General playback bug

### Bug description

Under MS 4.2.0, even if the entire melody is selected correctly, the repeat starts too early in the loop playback -- the end of the melody is not reached even in the first pass.

### Steps to reproduce

1. mark melody
2. select loop playback

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.2

**Comment by Jojo-Schmitz** [comment] 2023-12-21 12:41
Stems from https://musescore.org/de/node/358099

**Comment by XiaoMigros** [comment] 2023-12-21 13:44
Is this a duplicate of #16875?

**Comment by bkunda** [comment] 2023-12-21 14:38
Can you please attach a score/video to help us debug?
I am unable to reproduce this on macOS.

**Comment by Pazukulele** [comment] 2023-12-21 20:22
Screenshot video:
https://github.com/musescore/MuseScore/assets/11582280/34e90d4f-e012-487c-9828-02687a27a295

Score:
[Licht_das_sich_den_Hirten_zeigt.pdf](https://github.com/musescore/MuseScore/files/13745949/Licht_das_sich_den_Hirten_zeigt.pdf)

**Comment by Jojo-Schmitz** [comment] 2023-12-21 21:20
That's not the score that is needed, just a picture of it

**Comment by XiaoMigros** [comment] 2023-12-21 21:21
Seems like it is indeed a duplicate of #16875

**Closed** 2023-12-22 15:12 UTC
Labels: needs info, playback, regression_ms3
