### ISSUE TITLE
Exporting Parts to PDF resets formatting

### ISSUE THREAD

**Issue by orionn2024** [musescore/MuseScore#21229] opened 2024-01-26 09:39 UTC
### Issue type

Import/export issue

### Bug description

I'm writing for Piano and ContraBass.  Exporting the Bass part separately to PDF results in a different format than the display of that part separately without the Piano..  For example, Section Breaks are ignored in the PDF and the part is condensed and not convenient to read.  The PDF should be the same as the display.  The Piano part PDF is the same.  Maybe that's because the Piano is the top part ?!

### Steps to reproduce

Write a score with Piano (top) and Contrabass (under Piano)
Add Section breaks
Export Contrabass part to PDF

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

**Comment by bkunda** [comment] 2024-01-26 14:11
I'm unable to reproduce this on macOS. 
Perhaps you can send us the score (and PDFs) you are working with so we can try investigate further?

**Comment by lgvr123** [comment] 2024-01-26 14:19
> I'm unable to reproduce this on macOS.

Neither too I on Windows10

**Comment by cbjeukendrup** [comment] 2024-01-27 00:54
There might be a misunderstanding here. Perhaps you are looking at the full score all the time, but hiding instruments from it to make it look like a part score. This is not the usual workflow: the usual workflow is to leave all instruments visible in the full score, and then use the "Parts" button at the top of the window to access the part scores for all individual instruments. The music seen in these part scores is synchronised with the full score, but the layout can be edited independently.
When selecting parts in the export dialog, this refers to those part scores that can be accessed via the "Parts" button.

So, the expected functionality is:
- When selecting the "Main score" option in the Export dialog, the resulting PDF file should look like how the full score looks currently on the screen inside MuseScore
- When selecting a part score in the Export dialog, the resulting PDF file should look like how that part score looks in MuseScore.

Could you please try if that's indeed what's happening for you?

**Comment by orionn2024** [comment] 2024-01-27 13:59
Hello Casper,
That's indeed the case, my bad.
Thx very much for highlighting this !
Ori

‫בתאריך שבת, 27 בינו׳ 2024 ב-2:54 מאת ‪Casper Jeukendrup‬‏ <‪
***@***.***‬‏>:‬

**Comment by cbjeukendrup** [comment] 2024-01-27 14:45
Happy to hear that it helped! Let's consider this issue resolved in that case, but feel free to let us know if you encounter any further problems.

**Closed by cbjeukendrup** 2024-01-27 14:45 UTC
Labels: needs info

**Comment by orionn2024** [comment] 2024-01-27 21:29
Hello Casper,
If I may consult with you, is there a way to insert a vertical frame only
to 1 part, so it doesn't affect the formatting of others ?
Thx,
Ori


‫בתאריך שבת, 27 בינו׳ 2024 ב-16:45 מאת ‪Casper Jeukendrup‬‏ <‪
***@***.***‬‏>:‬

**Comment by cbjeukendrup** [comment] 2024-01-27 22:11
To achieve this, you can do the following: 
1. add the frame (which will temporarily add it in other parts too)
2. select it
3. in the Properties panel, a "Score and part synchronisation" section should appear; in this section, enable the "Exclude from parts" option.
    <img width="300" alt="Scherm­afbeelding 2024-01-27 om 23 11 33" src="https://github.com/musescore/MuseScore/assets/48658420/938fbd03-d1d0-4bc5-b1b0-b2034887e1c8">

**Comment by orionn2024** [comment] 2024-01-28 06:44
Hi Casper,
Thx, but this excludes it from all parts.  I want it to appear in 1 of the
parts.
Ori


‫בתאריך יום א׳, 28 בינו׳ 2024 ב-0:12 מאת ‪Casper Jeukendrup‬‏ <‪
***@***.***‬‏>:‬

**Comment by cbjeukendrup** [comment] 2024-01-28 12:34
The checkbox excludes it from all scores/parts except the one you are currently viewing. If you're currently viewing the full score, then it will be excluded from all parts. If you're currently viewing the part where you want the frame to appear, then it will keep the frame in that part and exclude it from all others, also from the full score.
If you want the frame to appear in the full score and one part score, you'll have to add one frame to the full score and exclude that from all parts, and one frame to the part score, and exclude that from all other parts.
