### ISSUE TITLE
Transpose does not work. The app tries to open the transposition dialogue but fails.

### ISSUE THREAD

**Issue by lruzicka** [musescore/MuseScore#17440] opened 2023-05-02 13:05 UTC
### Issue type

UI bug

### Bug description

Whenever I try to transpose some notation, the application tries to open the transposition dialogue but fails to do so. I can only see a black rectangle blink in the middle of the canvas. Therefore, it is impossible to use transposition.

### Steps to reproduce

1. Select some notation.
2. Click on Tools - Transpose.
3. The dialogue never appears.

### Screenshots/Screen recordings

[Situation is captured here.](https://imgur.com/a/V4ez4eG)

### MuseScore Version

MuseScore-4.0.2.230651545

### Regression

I don't know

### Operating system

Fedora Linux 38 on Wayland. 

### Additional context

Using the official appImage.

**Comment by cbjeukendrup** [comment] 2023-09-03 16:02
I think this is a duplicate of #18608. It has turned out that this is not something we can do anything about; see the latest comments on that issue for a possible solution.

**Closed by cbjeukendrup** 2023-09-03 16:02 UTC
Labels: UI
