### ISSUE TITLE
system dividers collide with bar numbers

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#17425] opened 2023-05-01 17:49 UTC
### Issue type

Engraving bug

### Bug description

if there is not a lot of space between systems, the autoplaced divider can overlap bar numbers

### Steps to reproduce

1. make a page with multiple close systems on top of each other
2. add system dividers

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/120861729/235500290-58d981ca-f941-4646-b4c7-204d8f049ffb.png)

### MuseScore Version

4.02

### Regression

I don't know

### Operating system

windows

**Comment by oMrSmith** [comment] 2023-05-02 23:46
This is a duplicate of #14966 and
#15213 .

**Closed** 2023-05-03 08:58 UTC
Labels: duplicate, engraving
