### ISSUE TITLE
Musescore Studio stuck downloading in MuseHub; no progress and unable to cancel

### ISSUE THREAD

**Issue by TimBomBom** [musescore/MuseScore#23179] opened 2024-06-10 19:42 UTC
### Issue type

Other type of issue

### Bug description

so after MS4 updated to Musescore studio (4.3), I haven't been able to open it via MuseHub. When I open MH, it begins downloading Musescore but never makes any progress. I can't cancel the download or open Musescore while it's doing this. I am able to open MS through its desktop shortcut or whatever, but musehub is broken. I have tried reinstalling musehub multiple times, but it didn't help.

### Steps to reproduce

Unsure exactly. Open MuseHub, observe stuck on downloading.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/84190142/40caf520-619d-48b4-af1b-a86f9e8bc4a2)

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.1-241490900

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Enterprise

### Additional context

It still worked directly after upgrading to MS Studio when 4.3 was first released, but some time in between then and now, it no longer functions

**Comment by irwir** [comment] 2024-06-10 21:07
Hard to tell if my experience is related to this issue, but downloading v4.3 and v4.3.1 in Firefox without MuseHub was very slow and had to be retried several times before getting a complete file.

**Comment by dcorson-ticino-com** [comment] 2024-06-10 23:01
MuseHub is a disaster area, my download for 4.3.1 took more than 12 hours, but it did finish.
I only found out because I went away for the day and forgot to turn off the computer.

**Comment by TimBomBom** [comment] 2024-06-30 20:59
Just writing to update that it's still broken

**Comment by geoholbert** [comment] 2024-07-06 15:54
I was instructed to delete and reinstall MuseScore 4 & MuseHub to solve the infinite loop "Downloading MuseScore Studio".
Unfortunately, the "Downloading MuseScore Studio" infinite loop appears to be back.  Maybe if I leave the computer on a few days, the actual download will complete...?  This bug report is over a month old and no comments regarding resolution...?

**Comment by dcorson-ticino-com** [comment] 2024-07-06 16:46
In the meantime MuseHub download of Musescore Studio appears to not be working at all.
Use the update from the Musescore Studio Help menu or download from the Musescore.org site.
Unfortunately the people from MuseHub seem to think that silence is the best communication.  
We don't even know if they know there is a problem.

**Comment by geoholbert** [comment] 2024-07-06 19:43
Thank you for your help.  At least I was able to uninstall MuseHub and successfully install MuseScore 4.  Unfortunately, MuseScore 4 still has a serious playback issue on my Windows 11 Pro 64-bit Dell PC system, but at least I can still create scores and print them even if I can't play them...

**Comment by MarcSabatella** [comment] 2024-07-06 19:46
For help with playback issues, please ask in the Support forum at MuseScore.org.  Depending on what the issue is, it’s probably something simple like needing to change buffer size or sample rate.  So when you do ask on the support forum, be sure to give more details.

**Comment by dcorson-ticino-com** [comment] 2024-07-06 19:47
You may want to keep MuseHub, but only use it for the Musesounds updates.  It works for that and you can configure it to only update the sounds.  As far as I know there is no other way to get the sounds.

**Comment by LcBeyer** [comment] 2024-07-07 00:21
To cancel the download, turn off automatic updates for apps and refresh the "Updates" area. You can update MuseScore Studio within the app itself. Muse Hub will still be stuck thinking there's an update, but you'll be able to launch the most current version of the app from the Hub and still have access to Muse Sounds.

That's the solution that worked for me, anyway. Hopefully it'll get you by until this issue can be resolved.

**Comment by geoholbert** [comment] 2024-07-07 13:11
Thank you very much for your continuing help and suggestions.  I don't plan to reinstall MuseHub until their issues are fixed or until the playback issue I am currently experiencing is fixed.  So having MuseSounds unavailable without MuseHub is not a problem for me.  I reported the playback difficulties some months ago (along with others) and the blame was put on the sampling rate of my Bose PC speaker system which has only one sampling rate available, there are no other choices.  The Bose speakers work fine with all my other Music applications on the PC as well as with my Home Theater applications.  The Bose were compatible with MuseScore 4.2 and earlier, so something changed with MuseScore that eliminate playback capability for myself and others.  At least, as I said earlier, I can still input and print scores, so that will have to do until MuseScore decides to address the playback issue(s)...

Again, thank you for your advice and efforts...

--George

**Comment by DominicMaas** [comment] 2024-07-07 20:40
Essentially I narrowed this down to:

Musescore was downloaded outside of Muse Hub originally (or updated within Musescore) as a user install. Muse Hub then attempts to update Musescore by uninstalling the old version of Musescore, and then installing the new version of Musescore.

Muse Hub fails to uninstall Musescore (as the process runs as SYSTEM, because it installs system wide, and it cannot find the MSI), which puts it in a weird state and the update fails.

So potential ways to fix this: 
- Uninstalling Musescore and restarting Muse Hub -> then install Musescore through Muse Hub should fix the issue. 
- Disable automatic updates in Muse Hub, this should prevent the auto download from occuring
- Wait for the next version of Muse Hub (Soon TM), the install process has been tweaked so it doesn't uninstall the old version, and everything is run per-user.

I think people have also had issues with two Musescore installs appearing, hopefully that'll be fixed in the next version of Muse Hub as well.

**Comment by geoholbert** [comment] 2024-07-11 15:41
Once again, I followed your instructions below with no success.  After uninstalling everything MuseScore, I installed MuseHub (successfully) and then tried to install MuseScore Studio from MuseHub.  This results in an infinite lop and MuseScore is never installed.  After uninstalling MuseHub and rebooting, I installed MuseScore 4.3.2 successfully.  That enables me to create and edit scores, but the playback issue(s) still prevent me from hearing them.

Thank you again for your help and I look forward to future releases of MuseHub and MuseScore Studio in the hope that my issues will be resolved...

--George

**Comment by DominicMaas** [comment] 2024-07-26 03:58
The latest version of Muse Hub (v2) is available for download and should fix this.

**Comment by geoholbert** [comment] 2024-07-26 11:44
Thank you for keeping me up-to=-date.  I have installed Muse Hub (v2) successfully.  I still have my playback issue, perhaps I should uninstall MuseScore Studio and then put it back utilizing Muse Hub?

**Comment by zacjansheski** [comment] 2024-09-05 14:49
Closing as fixed in V2

**Closed by zacjansheski** 2024-09-05 14:49 UTC
Labels: P1, needs review, regression MS4, Muse Hub
