### ISSUE TITLE
[MU4 Issue] UI slow to respond when selecting notes etc.

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8440] opened 2021-06-28 03:54 UTC
**Describe the bug**
When selecting any part of the score containing notes, Mu4 is quite unresponsive, taking up to 700 or 800msec to repaint and show what's just been selected. Worse, when using palette to add items like "Staff Text" to multiple notes, it can take 10+ seconds to update.

**To Reproduce**
1. Create a new score
2. Add a note
3. Click on an empty measure - notice it shows as selected immediately
4. Click on a note - there's a noticeable delay before it shows as selected
5. Add 7 or 8 notes, select them and use palette to add "Staff Text" - can take 10+ seconds to update!

**Expected behavior**
UI should update immediately after selecting (or adding elements etc.)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
This is largely due to the selectionChanged callback installed by the InspectorListModel, and specifically the time it takes to do endInsertRows(), which can be over 700 ms.  I haven't figured out any way just marking the model as "dirty" at this point and only rebuilding it when necessary, but presumably it's possible.
Some of the other callbacks triggered when selecting a note a bit slow too, possibly including the one installed by NotationNoteInput but I didn't really investigate much further than that.

Visual Studio profiling output also confirms the slowness is in QAbstractItemModel::endInsertRows, and in particular when any of the sub-models are NotationSettingsProxyModel.

**Comment by wizofaus** [comment] 2021-07-02 01:57
BTW this can be improved at least for the case of adding to a large number of selected elements from the palette by ensuring we don't trigger the selectionChanged event for each added element. Essentially we can just trigger it once at the end, similar to how I changed it for dropChanged.

**Comment by igorkorsukov** [comment] 2021-11-24 12:43
@DmitryArefiev 
* Add 7 or 8 notes, select them and use palette to add "Staff Text" - can take 10+ seconds to update!  - This is fixed in the PR https://github.com/musescore/MuseScore/pull/9854

Issue about selection needs actualization, I can't reproduce it.

**Closed** 2021-11-25 07:58 UTC
Labels: P1

**Comment by DmitryArefiev** [comment] 2021-11-26 19:05
Tested on master build (Win10, Mac11, LinuxMint 20) - CAN'T REPRODUCE NOW
