### ISSUE TITLE
Selection filter should not be enabled by default when users first launch MuseScore 4.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11310] opened 2022-04-22 21:37 UTC
**Describe the bug**
Recently, the selection filter became enabled by default and tabbed with the other panels. 

We shouldn't do this. It's a niche panel with limited usefulness and should be kept off unless the user really needs it. It is also less crucial now that our properties panel allows you to edit specific types of object without having to deselect every other type of object.

In addition, the interface looks cluttered with the selection filter enabled and will introduce another layer of complexity for new users. Let's put it back where it belongs!

**Comment by cbjeukendrup** [comment] 2022-04-23 11:54
This seems to be caused by commit 616c462c5c86167cd9412c8f7f7c50c310e6d482.

**Comment by DmitryArefiev** [comment] 2022-04-27 10:22
Fixed in #11409

**Closed** 2022-04-27 11:08 UTC
Labels: good first issue, P2, community
