### ISSUE TITLE
[MU4 Issue] Copy/Paste keyboard shortcuts do not work with "Dvorak - QWERTY Cmd" Keyboard layout (Mac)

### ISSUE THREAD

**Issue by aburdiss** [musescore/MuseScore#16515] opened 2023-02-24 00:29 UTC
**Describe the bug**
With the Dvorak - QWERTY Cmd keyboard layout on Mac, I am unable to use "Cmd + C" and "Cmd + V" on any score. With this keyboard layout, normal typing uses the Dvorak layout, but all keys use their QWERTY position when you hold "Command" (to make common keyboard shortcuts like cmd+c, cmd+v not require two hands).

**To Reproduce**
1. Set keyboard layout on MacOS to Dvorak - Qwerty Command.
2. Open any existing score in MuseScore 4, or open a new score.
3. Attempt to use "Command + C" and "Command + V" to copy and paste a measure with notes.
4. See error (nothing happens)

**Expected behavior**
Entire measures would copy and paste in the same way it works on the QWERTY keyboard layout

**Platform information**
 - OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Additional context**
This works as expected in MuseScore 3, and has been a problem since MuseScore 4 released.

I believe what may be happening is that MuseScore is trying to use the Dvorak keyboard layouts with the Command key as well, but only in some cases. I also keep opening new scores when trying to add Lyrics with "Cmd + L" (L is where the "N" key is in the Dvorak layout), but pressing "Cmd + P" (where L is on Dvorak layout) opens a Print Dialogue.

**Comment by bkunda** [comment] 2023-02-24 11:47
@aburdiss I'm unable to reproduce this in the latest nightly.

Can I just check I'm following your ‘steps to reproduce' correctly?

This was the keyboard layout I used: 

<img width="242" alt="Screenshot 2023-02-24 at 12 45 01 pm" src="https://user-images.githubusercontent.com/86290556/221171508-61455101-b013-4b4f-a0be-f6f5a442c488.png">

And here's the copy+paste command: 

https://user-images.githubusercontent.com/86290556/221171565-dd56f34d-9f53-4c2c-b345-419d2b5f1754.mov

If you can still reproduce this in the latest nightly, perhaps you could upload a short video too so we can better see what's happening on your end? Thank you!

**Comment by aburdiss** [comment] 2023-02-25 15:00
That's the correct keyboard layout! I downloaded and installed the latest nightly, and I am no longer able to consistently reproduce the issue like I can on the stable release. It happened on the nightly the first time after I opened it, but it has worked consistently for the last half hour no matter what I try.

As for the steps, everything looks correct with what you are doing.

Please let me know if there's anything else I can help with on my end with this. Thanks for taking a look into this!

**Comment by zacjansheski** [comment] 2023-05-26 21:11
Closing as resolved.

**Closed by zacjansheski** 2023-05-26 21:11 UTC
Labels: needs info
