### ISSUE TITLE
[MU4 Issue] Inserting measure(s) at the start of a score pushes the key signature forward and creates extra clefs

### ISSUE THREAD

**Issue by Riisus** [musescore/MuseScore#13917] opened 2022-10-23 12:57 UTC
**Describe the bug**
Inserting any number of measures before the first measure of a score creates extra clefs after the created measures. The key signature is placed in the measure after the inserted measures, instead of remaining in the new first measure.

**To Reproduce**
1. Open a score in MS4 with a key signature with accidentals at the beginning of a score.
2. Select the first measure of the score
3. Insert any number of measures -> properties -> insert measures ->using the shortcut Ins (1 measure) or Ctrl + Ins (multiple measures). (Alternatively select any measure -> properties -> insert measures -> _x_ at start of score) 

**Expected behavior**
A new measure is created at the beginning of the score. Key signature remains at the new, inserted first measure of the score and no new clefs are created.

**Screenshots**
![image](https://user-images.githubusercontent.com/116495080/197392873-0d1f80cc-18fc-4a56-b6ac-0d36e001dfef.png) Example of a score
![image](https://user-images.githubusercontent.com/116495080/197393046-ad38c590-b65a-43d4-973b-c5f621f80a27.png)
state of the score after inserting 2 measures at the start.

**Platform information**
 - OS: Windows 10, MS4 Beta

**Comment by Tantacrul** [comment] 2022-10-23 13:17
@oktophonie @mike-spa @asattely - let me know if this one is in your wheelhouse!

**Comment by asattely** [comment] 2022-10-24 21:31
I can't seem to reproduce this one with either the beta or current master. @Riisus, would it be possible to provide an example score that exhibits this behavior?

**Comment by Riisus** [comment] 2022-10-25 12:57
I don't have access to my PC until a couple days from now and the exact file I did this on doesn't exist anymore, but I'm going to install the beta on my Macbook this evening though I will try to reproduce it and get back to you in a few hours.

**Comment by asattely** [comment] 2022-10-27 19:45
I see, able to reproduce it with that score. I'll dig into it and see what's going on.

**Comment by asattely** [comment] 2022-10-28 13:50
It does seem to be something involving this score, and particularly, the chord changes part. At this time we're trying to focus on things that are reproduceable from a new score (as the master branch / beta is constantly changing), so I'm going to close this one as unable to reproduce, but if you encounter this same problem on a new score, please document the steps to recreate this situation and we'll reopen it!

**Closed** 2022-10-28 13:50 UTC
Labels: P2
