### ISSUE TITLE
Repeats producing very strange audio artefacts (Possibly a sample rate problem)

### ISSUE THREAD

**Issue by Reloup38** [musescore/MuseScore#14196] opened 2022-10-30 19:47 UTC
**Describe the bug**
The repeat playback in the score attached is completely messed up, even if the sounds are MS Basic

**To Reproduce**
1. Open my score, similar scores should work the same
2. Assign the Violin I (Solo) sound to the part
3. Playback or export as mp3
The files are in the zip

**Expected behavior**
The repeat shouldn't be messed up and the playback shouldn't miss notes even at fast speed

**Platform information**
 - OS: Windows 7, speakers are set at 48 000 Hz
 
[circle of fifths.zip](https://github.com/musescore/MuseScore/files/9896710/circle.of.fifths.zip)

**Comment by Tantacrul** [comment] 2022-11-01 12:28
Thanks for providing the mp3. That's really useful. Could you possibly try setting your speakers to 44,000 Hz and testing again?

I'm unable to reproduce the repeats problem on the latest nightly... but this may be related to issues that have been reported when people are using different sample rates, so I'd like to eliminate that as the possible culprit.

You can get the latest nightly here: https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-x86_64.7z

**Comment by Tantacrul** [comment] 2022-11-01 12:30
I've removed the part about fast playback because that has been reported in various other issues already. The repeat problem is a new one though. Thanks!

**Comment by Reloup38** [comment] 2022-11-01 13:29
@Tantacrul i tried the latest nightly and was unable to reproduce the bug too, seems like it somehow got fixed !

**Comment by Tantacrul** [comment] 2022-11-01 17:32
Yeah. That is quite weird. We have some theories (and we're making changes that would solve those theoretical problems anyway). So, I'm going to close this for now.

**Closed by Tantacrul** 2022-11-01 17:32 UTC
Labels: P1
