### ISSUE TITLE
Audio Device Preference does not save (Windows)

### ISSUE THREAD

**Issue by heisluft** [musescore/MuseScore#17289] opened 2023-04-19 21:51 UTC
### Issue type

General playback bug

### Bug description

The title basically says everything. Audio Device Preference either is not saved or is reverted at every startup, without me changing my Audio Setup in any way in between. I attached a log from a startup after supposedly changing the setting.  Audio Device Selection Works Flawlessly in MU3.

### Steps to reproduce

1. Open MU 4 and click preferences
2. Navigate to I/O Tab
3. Change Audio Device Setting, Click OK
4. Restart MU
5. Observe Setting being defaulted

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in **Musescore 4.0.1** and now is broken

### Operating system

Windows 10

### Additional context

[MuseScore_230419_234643.log](https://github.com/musescore/MuseScore/files/11277840/MuseScore_230419_234643.log)

**Comment by switerom** [comment] 2023-04-21 11:43
I tried to reproduce your bug. And I found that after restarting I can't even select second device. So in order to do that you need to select beforehand first device and only after that second.

**Comment by DmitryArefiev** [comment] 2023-06-06 14:08
Fixed in #17770

**Comment by DmitryArefiev** [comment] 2023-06-06 15:02
Related issue to switching audio devices #17877 (is not caused by #17770)

**Closed** 2023-06-06 16:32 UTC
Labels: P1, regression, playback
