### ISSUE TITLE
"Align verse numbers" does not take quotes into account

### ISSUE THREAD

**Issue by bmarwell** [musescore/MuseScore#21283] opened 2024-01-29 22:19 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When entering lyrics, verse numbers should be aligned. However, lyrics starting with citations and/or active speech (as common in chorales), will not work: Any kind of quotation marks will make the alignment not work.

### Steps to reproduce

1. Enter multiple verses of lyrics
2. Let any verse start with one of there characters: `»`, `"`, `“`, `„`, `‘`, `›`, etc.

### Screenshots/Screen recordings

![2024-01-29T231638_screenshot](https://github.com/musescore/MuseScore/assets/1413391/5e765d4c-b0e2-4e63-822b-3578403ecfed)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Linux (Manjaro)

**Comment by oktophonie** [comment] 2024-01-30 09:14
Duplicate of https://github.com/musescore/MuseScore/issues/15347

**Closed by oktophonie** 2024-01-30 09:14 UTC
Labels: engraving
