### ISSUE TITLE
Window and Cursor behaviour in 4.4.1 (window header is broken, Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24580] opened 2024-09-09 12:52 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

https://musescore.org/en/node/368201

> On operating MS 4.4.1 for the first time I am getting some crazy behaviour with my screen - the system is unoperable because **half the buttons are missing in full screen** mode and in order to effect a button **I have to click a centimetre above it**. The only way of exiting was to CTRL ALT DEL.
> 
> Also, when I did manage to play through a score the progress mark was a note or so behind the music. But that's a minor issue in the grand scheme of things.
> Windows 10 by the way. No problems with previous version of MS.

### Supporting files, videos and screenshots

> You will see that there is a margin above the commands, and it is as if the musescore stuff has "slipped down" the screen. So when I click on View for example, nothing happens, but if I click slightly above View, the button responds.
> All my other computer facilities behave as normal:

![Capture_0](https://github.com/user-attachments/assets/2a5e5f61-945b-4285-88db-58f0099642aa)

> Also attached is the result of maximising the MS window - there appears to be a transparent top edge, and I have to click above the buttons (inside the transparent area!) to get a response:

![Capture full](https://github.com/user-attachments/assets/979d381b-1646-4968-b861-62d8d7061390)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment] 2024-09-09 14:40
Previous instances of this problem:
- https://github.com/musescore/MuseScore/issues/22369 (occurred after switching to Qt 6; was fixed by removing `QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL)`)
- https://github.com/musescore/MuseScore/issues/8270 (occurred even with Qt 5; was fixed by adding `QCoreApplication::setAttribute(Qt::AA_UseOpenGLES);` (which does nothing anymore in Qt 6) and `QT_OPENGL_BUGLIST`)

**Comment by cbjeukendrup** [comment] 2024-09-09 14:41
Diagnostic files from the author of that .org forum post: 
[DIagnostic zip file.zip](https://github.com/user-attachments/files/16932211/DIagnostic.zip.file.zip)

**Comment by bkunda** [comment] 2024-09-10 11:04
This doesn't seem to be a regression to nightly if it is in fact broken in the current release build (4.4.1). 

The "regression nightly" label should be used for "works correctly in the latest released version and is broken in the nightly builds", so unless I'm misunderstanding something, it would appear this issue is a "regression MS4" because it the functionality is in fact broken in the latest released version, right?

**Comment by bkunda** [comment] 2024-10-07 08:36
@DmitryArefiev are you still able to reproduce this since the update to Qt 6.2.9?
I cannot reproduce it on my end.

**Comment by DmitryArefiev** [comment] 2024-10-07 08:45
@bkunda Nope.. But I was not able to reproduce it on previous Qt version too

**Comment by bkunda** [comment] 2024-10-07 09:24
According to the [original reporter](https://musescore.org/en/user/432981), their problem seems to have been resolved. 
Seeing as how we can't reproduce this, I'll close it for now. Let's reopen though if further reports confirm the problem persists.

**Closed by bkunda** 2024-10-07 09:24 UTC
Labels: needs info, P1, UI, regression MS4, os: windows

**Comment by cbjeukendrup** [comment] 2024-10-07 11:17
Well they "fixed" it by buying a new computer. So this issue is basically _not_ fixed, and I highly doubt that the Qt update will have solved it. But it's clear that this issue only affects some old/broken graphics drivers, so we can decide to assume that it's not widespread enough to invest time in trying to fix it.
