### ISSUE TITLE
There is a playback problem with switching instruments on the same staff

### ISSUE THREAD

**Issue by brenostoliveira** [musescore/MuseScore#25160] opened 2024-10-14 12:49 UTC
### Issue type

General playback bug

### Description with steps to reproduce

When there are several instrument changes on the same staff, musescore stops playing some instruments.
This usually happens in percussion lines, as I use this function a lot. I didn't test it with melodic instruments, so I don't know if this also happens with these staves.
But the instrument simply goes silent. To be able to hear it, I need to create a completely new staff to only reproduce that instrument and hide the staff from the score.

### Supporting files, videos and screenshots

[Orquestra .zip](https://github.com/user-attachments/files/17365540/Orquestra.zip)

I have attached the zip file.
The reproduction failure occurs in the snare drum in measure 159. And in the bass drum in measure 188.
But I need to warn you that I created extra lines that are hidden so that I could reproduce these instruments.

https://github.com/user-attachments/assets/8709cba5-bfa0-46e1-8f9b-4677529549fe

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2 

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment] 2024-10-14 13:01
Please be sure to ZIP and attach the score that exhibits this behavior, and say which measure to select in order to reproduce the problem.

**Comment by brenostoliveira** [comment] 2024-10-14 14:45
> Please be sure to ZIP and attach the score that exhibits this behavior, and say which measure to select in order to reproduce the problem.

[Orquestra .zip](https://github.com/user-attachments/files/17365540/Orquestra.zip)

Forgiveness. I have attached the zip file.
The reproduction failure occurs in the snare drum in measure 159. And in the bass drum in measure 188.
But I need to warn you that I created extra lines that are hidden so that I could reproduce these instruments.

**Comment by MarcSabatella** [comment] 2024-10-14 15:02
I can confirm that when soloing the staff ibn question by selecting a measure on it, measure 159 does not play, but it does play normally (or at least, when other staves are muted - too hard to hear otherwise).  Kind of seems like somehow to the select-to-solo mechanism gets confused with the instrument changed, but it works elsewhere, so I don't really know.

**Comment by zacjansheski** [comment] 2024-10-15 18:28
That's quite a score!

I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/23746

Previous soundflag information is carried over the instrument change.  The instrument is still audible without the selection because it is doubled in an invisible snare

https://github.com/user-attachments/assets/12785bda-cdcc-460f-9223-8af830cc91fa

**Comment by zacjansheski** [comment] 2024-10-15 18:42
Closing as duplicate

**Closed by zacjansheski** 2024-10-15 18:42 UTC
Labels: needs review, playback

**Comment by MarcSabatella** [comment] 2024-10-15 18:56
Aha!  In that case, workaround is to add another staff text there and explicitly set the soundflag.

**Comment by brenostoliveira** [comment] 2024-10-16 00:42
You saved my day. Thank you gentlemens. And congratulations for your great work. 😀
I'm newbie here on github. I'm still learnig how to report some bugs. In this case, I couldn't find anyone else reporting the same problem.
