### ISSUE TITLE
[MU4 Issue] [Inspector] Unable to move dot or beam independently using offset X/Y options in Properties

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16142] opened 2023-01-30 17:26 UTC
https://user-images.githubusercontent.com/90187801/215549456-a70bed79-8741-493c-b999-adc6348fdef2.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MS3**

**Comment by oktophonie** [comment] 2023-01-30 18:49
The issue with the dot will be fixed by https://github.com/musescore/MuseScore/issues/16124
Not the flag (but I'm not sure whether that's maybe by design)

**Closed** 2023-01-31 07:16 UTC
Labels: by design, P1
