### ISSUE TITLE
[MU4 Issue] Mouse-keyboard toggle button

### ISSUE THREAD

**Issue by Tiko7454** [musescore/MuseScore#10628] opened 2022-02-21 13:32 UTC
**Describe the bug**
Mouse-keyboard toggle button issue

**To Reproduce**
When note insert is on keyboard writing mode, any pushed button activates mouse note inserting mode

**Expected behavior**
Stays in keyboard writing mode

**Platform information**
 - OS: Arch Linux

**Comment by DmitryArefiev** [comment] 2022-04-13 12:56
@Tiko7454 Hi! Can add a detailed steps to reproduce (or video). I'm not sure if that's a bug..

Thank you!

**Comment by Tantacrul** [comment] 2022-05-30 18:20
Closing due to mysteriousness.

**Closed by Tantacrul** 2022-05-30 18:20 UTC

**Comment by MarcSabatella** [comment] 2022-05-30 19:58
FWIW, my guess is this was a request that we get moderately often - to be able to disable mouse clicks while in note input mode.  I think it comes mostly from people who don't know about the scroll wheel or PgUp/PgDn other means of navigation and whose only means of moving about is dragging the canvas.  They get annoyed that attempting to drag the canvas while in note input mode enters a note instead.

There's definitely room for rethinking how note input modes work on any number of levels of course, but certainly, no reason to have this issue open for 4.0 if my guess is correct - it's clearly a longer term design question.
