### ISSUE TITLE
Chord symbol plays when playback is started when it shouldn't do so

### ISSUE THREAD

**Issue by rithvik-doshi** [musescore/MuseScore#21009] opened 2024-01-14 19:00 UTC
### Issue type

General playback bug

### Bug description

Upon opening Musescore, playback with chord symbols works as expected (using basic VST). However, eventually whenever I start a score playback by pressing play, the Chords.Piano instrument plays one of the chords in the score, and then playback resumes as expected. This is disrupting as one can't hear certain pitches under the sound of the chords. I don't remember this working on Musescore 4.x, and I think in some versions of 3.x it is also apparent.

### Steps to reproduce

1. Start MuseScore and open the attached file with the versioning as described in additional context
2. As you work through the score and add chords and play and pause playback, this bug should become apparent.
[Song_Song.mscz.zip](https://github.com/musescore/MuseScore/files/13932765/Song_Song.mscz.zip)

### MuseScore Version

4.2

### Regression

No.

### Operating system

macOS Ventura 13.1

### Additional context

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

**Comment by bkunda** [comment] 2024-01-16 14:13
@zacjansheski pls investigate

**Comment by MarcSabatella** [comment] 2024-01-16 14:37
I can confirm this happens.  It's debatable as to whether it's desirable or not.  Consider a simple example like this:

![image](https://github.com/musescore/MuseScore/assets/1799936/081cf959-17d6-4258-b985-4e7c6ca0f28f)

Here, if playback starts in bar two, it's nice that both the tied note and the chord from the previous bar get played.  In MU3 and earlier, that didn't happen, and it was actually a very common request (more so regarding the tied note than the chord symbol).

On the other hand, sometimes you'll have a part that only has chords for a portion of the score - an 8-bar solo section within a big band arrangement, for instance.  Or a piece where the accompaniment is written out in full for portions, but chord symbols and slashes are used in other portions.  Now, if you play one of the written out sections, the last chord symbol plays even though it may have no relevance at all:

![image](https://github.com/musescore/MuseScore/assets/1799936/f27e00b6-9e41-41ce-8f08-1ef1f777f0ee)

If you start playback in bar 3, you definitely *don't* want to hear the G7 chord .  You can get this result manually by adding an explicit (possibly invisible) "N.C." after the part with the chord symbols.

Ideally there could be some more clever system for figuring out which chord symbols to restrike by default and to give the user control.

It's probably safer to not restrike the chord as not hearing a chord you want is not as bad as hearing one you don't.

**Comment by zacjansheski** [comment] 2024-01-16 19:10
I think this is a duplicate of https://github.com/musescore/MuseScore/issues/16712
Does changing the chord instruments in the mixer to MS basic fix the problem for you?


https://github.com/musescore/MuseScore/assets/69917893/66a9d0d6-89b7-4193-9ddc-b115833a1798

**Comment by MarcSabatella** [comment] 2024-01-16 19:38
Yes, MS Basic "fixes" both the chord symbol and the tie.

To me, we should always play the tie but probably not the chord.

**Comment by zacjansheski** [comment] 2024-01-16 19:58
Closing as duplicate of https://github.com/musescore/MuseScore/issues/16712

**Closed by zacjansheski** 2024-01-16 19:58 UTC
Labels: needs info, playback
