### ISSUE TITLE
Add the option to not show a score from the list of the last modified 

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#24487] opened 2024-09-05 20:52 UTC
### Your idea

There should be the possibility of deleting each score from the list of the last modified by doing right click on the mouse.

![1](https://github.com/user-attachments/assets/f78143f7-4551-4138-b22d-a844a9747037)

### Problem to be solved

Once you finish a project you can make space in the history for a new one.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment] 2024-09-05 20:58
Duplicate of https://github.com/musescore/MuseScore/issues/11235

**Closed by oktophonie** 2024-09-05 20:58 UTC
Labels: feature request
