### ISSUE TITLE
[MU4 Issue] Muse sounds: Wrong instrument mapping when creating scores from templates

### ISSUE THREAD

**Issue by murimk** [musescore/MuseScore#14786] opened 2022-11-27 14:22 UTC
**Describe the bug**
When creating a score from a template, many instruments are incorrectly mapped to the wrong Muse Sound instrument. The Bb Clarinet instrument is a good example, it seems to always be mapped to Clarinet in Eb from Muse Sounds

**To Reproduce**
1. Create any score containing a Bb clarinet using the "create from template" function (like symphony orchestra), making sure Muse Sounds is set to default
2. See in the mixer that any instance of the instrument "Bb Clarinet" is mapped to "Clarinet in Eb" from Muse Sounds 

**Expected behavior**
"Bb Clarinet" should be mapped to "Clarinet in Bb"

**Platform information**
 - OS: Windows
 
**Additional context**
This concerns many other instruments from many templates, but the clarinet seems to consistently be problematic. Other examples are, under the template "symphony orchestra":
- both flutes 1 and 2 is mapped to "flute 1" (should be differentiated)
- Bb Trumpet 1 and 2 is mapped to "trumpets" (should be "trumpet")
- Trombone 1 and 2 is mapped to "trombones a3" (should be "trombone")

There are many similar problems from other templates, listing all of them as separate issues seems overkill

**Comment by Fristover** [comment] 2022-11-27 14:37
Duplicate of #13898

**Comment by cbjeukendrup** [comment] 2022-11-27 15:03
Thanks for reporting though!

**Closed by cbjeukendrup** 2022-11-27 15:03 UTC
