### ISSUE TITLE
Add measures dialogue: [Return] has no effect; need to click "OK" to update score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#21882] opened 2024-03-11 09:54 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

A minor issue but, possibly, an easy fix. If you open the Add measures dialog  (from Add menu, Properties toolbar or Alt+Shift+B), then enter a number of measures and press [Return], nothing happens. In fact you have to click OK to update the number of measures in the score.

I would have expected a [Return] to have the same affect as clicking OK.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by cbjeukendrup** [comment] 2024-03-11 11:55
Duplicate of https://github.com/musescore/MuseScore/issues/12222 :)

**Closed as not planned by cbjeukendrup** 2024-03-11 11:55 UTC
Labels: duplicate, UX/interaction
