### ISSUE TITLE
[MU4 Issue] MIDI Mapping not latching for the “Play" action 

### ISSUE THREAD

**Issue by edconnor** [musescore/MuseScore#12951] opened 2022-08-21 22:19 UTC
**Describe the bug**
The MIDI key or control for the "Play" action must be held continuously for Playback to continue.

**To Reproduce**
1.  Preferences > MIDI mappings.
2. Click the “Play” action.
3. Click “Assign MIDI mapping…”.
4. Press any piano key on your MIDI keyboard to make the assignment. In my case I used the lowest key on my keyboard.
    The MIDI mapping appears to be assigned correctly in the “Waiting…” textbox.
5. Click “Add”.
6. Click “OK” to exit the Preferences dialog.
7.  Now press the piano key that is assigned to the “Play” action.
8. Note how playback starts when you press the piano key, but as soon as you release it, playback stops.

**Expected behavior**
Playback should continue when you release the piano key or MIDI control.

**Platform information**
 - OS: macOS Monterey, Version 12.5.1
 - Roland FP 90 digital piano.
 - MuseScoreNightly-latest-x86_64 8/20/2022
 
**Additional context**
 I also tried mapping the Sostenuto pedal on my digital piano. Same issue, as soon as I released the pedal, playback stopped.

**Comment by Eism** [comment] 2022-08-23 10:39
Duplicate of https://github.com/musescore/MuseScore/issues/11480. Thanks for reporting!

**Closed by Eism** 2022-08-23 10:39 UTC

**Comment by edconnor** [comment] 2022-08-23 20:56
You're welcome. I love ver. 4. You guys are doing a great job!
