### ISSUE TITLE
Can't put more than one "Open" fingering per chord

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#24236] opened 2024-08-27 15:40 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

It is not possible to put more than one "Open" fingering symbol on a chord (you can do it, of course, using the LH or RH fingerings). So it is not possible to produce the following guitar notation, for example:

![open_fingering](https://github.com/user-attachments/assets/03860b89-efb1-47b4-be8d-478f16d70bbc)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-08-27 15:47
Duplicate of https://github.com/musescore/MuseScore/issues/20919

**Closed by oktophonie** 2024-08-27 15:47 UTC
Labels: UX/interaction
