### ISSUE TITLE
[MU4 Issue] Changing key signature stops playback 

### ISSUE THREAD

**Issue by ChrisMuellersCode** [musescore/MuseScore#16479] opened 2023-02-21 17:19 UTC
**Describe the bug**
When I change the key signature in the attached score, the playback stops from a semingly unrelated bar for a few bars. 

**To Reproduce**
1. Download [MU4_PoC_-_Final_Project_A - Player friendly version.zip](https://github.com/musescore/MuseScore/files/10795844/MU4_PoC_-_Final_Project_A.-.Player.friendly.version.zip)
2. Rename .zip to .mscz
3. Open file in MU4
4. Verify in Mixer, that Musesounds -> Keys -> Grand Piano is indeed the selected sound for piano
6. Change Key signature in bar 1 to C Major / A Minor
7. Play from any bar previously to bar 17
8. Notice that playback stops from bar 17 to bar 20 (including) on the first time but plays until the end during the repeast
9. Saving and closing the file "re-enables" playback after re-opening the file. The Error occurs again when following steps 6 and 7 again

**Expected behavior**
The playback does not stop. 

**Screenshots**
none 

**Platform information**

- OS: Windows 10 Home, 21H2, OS Build: 19044.2486
- CPU: 12th Gen Intel(R) Core(TM) i9-12900K 3.20 GHz
- Ram: 64GB
- SSD for OS and Musescore: Samsung SSD 980 PRO 2TB
- MIDI Keyboard: M-Audio Oxygen Pro Mini
- Audio: Focusrite Scarlett 2i4 (1st gen)
- GPU (for what its worth): 2047MB NVIDIA GeForce RTX 3080 (Palit Microsystems)

**Additional context**
- The file was initially created with MuseScore 3.6.2 and then converted to MU4.
- It seems to NOT make a difference to what key signature the key is changed for the issue to occur.

**Comment by bkunda** [comment] 2023-02-24 12:09
@RomanPudashkin here's a video recording so you can quickly see what the issue is about: 

https://user-images.githubusercontent.com/86290556/221175331-8a86d13f-4dbe-4f7f-94bc-de2543afeee4.mov

FWIW, I was able to reproduce the issue using MS Basic, not just MuseSounds. 

As far as I'm aware, this is an issue specific to @ChrisMuellersCode's particular score (unless anyone knows of something similar having been raised elsewhere?)

**Comment by ChrisMuellersCode** [comment] 2023-03-03 15:22
> As far as I'm aware, this is an issue specific to @ChrisMuellersCode's particular score (unless anyone knows of something similar having been raised elsewhere?)

I tried to reproduce this issue with a new score that I wrote and migrated from MS3.6.2 but I am unable to reproduce it that way. So while the issue still does happen in the score I attached with the report, it indeed seems that it has something to do with this specific score. Priority wise this is a very very low thing to me (like the very bottom of a backlog low).

**Comment by bkunda** [comment] 2023-03-17 09:37
@ChrisMuellersCode Indeed it does sound like an issue with that specific score, in which case if you'd like to request help for it we would recommend asking for support either in the [#support](https://discord.com/channels/818804595450445834/818804809784229898) channel on our Discord server, or on the [musescore.org forum](https://musescore.org/en/forum/6). 
I'm going to close this issue for now as we use Github for reproducible bug reports (not individual support requests).
Many thanks!

**Closed by bkunda** 2023-03-17 09:37 UTC
Labels: needs review
