### ISSUE TITLE
[MU4 Issue] Colouring doesnt work on note stems/flags

### ISSUE THREAD

**Issue by amsuu** [musescore/MuseScore#16539] opened 2023-02-24 18:05 UTC
**Describe the bug**
All note stems AND note flags on "small" notes (<1/4) ignore the "Color" property.

**To Reproduce**
1. Open a new score
2. Insert quarter, and eighth or smaller notes anywhere
3. Select all and `Properties panel > Appearance > Color [select a colour]` 

**Expected behavior**
All elements get coloured.

**Screenshots**
![image](https://user-images.githubusercontent.com/102627400/221255445-c605c0e4-ded3-41b9-b3f6-cb71a3832c1c.png)
*(all elements in this bar are "coloured")*

**Platform information**
 - OS: Windows 10
 - Musescore V: 4.0.1

**Additional context**
*Side note: this also happens with tablature*

**Comment by oktophonie** [comment] 2023-02-24 18:14
Duplicate of https://github.com/musescore/MuseScore/issues/15433
(Will be fixed in 4.0.2!)

**Closed by oktophonie** 2023-02-24 18:14 UTC
