### ISSUE TITLE
Section break interfering with repeats during playback

### ISSUE THREAD

**Issue by Cebalrai81** [musescore/MuseScore#22221] opened 2024-04-05 14:13 UTC
### Issue type

General playback bug

### Bug description

When using section breaks at repeats, the playback will stop as it should on the last repeat, but also on all other repeats. Ideally a mechanism should be able to detect when it is the last repeat and activate the section iff so.

### Steps to reproduce

1. Notate a simple passage with a repeat at the double barline. 
2. Place Section break on barline.
3. Playback until repeat.
4. Playback will pause for a couple of seconds on both the 1st and 2nd repeats 

### MuseScore Version

4.2.1.240230937

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Happens using both muse sounds and MS basic

**Comment by Jojo-Schmitz** [comment] 2024-04-05 14:19
I'm pretty sure this is a duplicate, but am to lazy to search for it

**Comment by zacjansheski** [comment] 2024-04-05 14:34
duplicate of https://github.com/musescore/MuseScore/issues/14262

**Closed by zacjansheski** 2024-04-05 14:34 UTC
Labels: playback
