### ISSUE TITLE
Playback does repeats and jumps wrong

### ISSUE THREAD

**Issue by KellyJSox** [musescore/MuseScore#19444] opened 2023-09-18 22:26 UTC
### Issue type

General playback bug

### Bug description

A link to the score is in the "Additional context" section.

Musescore is not playing the second or third voltas, it jumps to Coda before it sees “To Coda” in the second volta, it repeats the section called “Verses 1-2” a third time, never plays the third volta, repeats Verse 3, and then ends.

This is how I want it to play back:
1. Play “Intro.”
2. Play “Refrain” and first volta (“1-2”).
3. Jump to and play “Verses 1-2.”
4. Jump back to Segno. Repeat “Refrain” and first volta.
5. Jump to and repeat “Verses 1-2.”
6. Jump back to Segno. Repeat “Refrain.” Play second volta (“3”).
7. Jump to Coda and play “Verse 3.”
8. Jump back to Segno. Repeat “Refrain.” Play third volta (“Final”).
9. End.

This is how it actually plays back:
1. Plays “Intro.”
2. Plays “Refrain” and first volta (“1-2”).
3. Jumps to and plays “Verses 1-2.”
4. Jumps back to Segno. Repeats “Refrain” and first volta.
5. Jumps to and repeats “Verses 1-2.”
**Here it should repeat the Refrain and play the second volta. It doesn’t.**
6. Jumps to Coda and plays “Verse 3.”
7. Jumps back to Segno. Repeats “Refrain” and first volta (a third time).
**Here it should play the third volta and end. It doesn’t.**
8. Jumps to and repeats “Verses 1-2.”
9. Continues to Coda and repeats “Verse 3.”
10. Ends.

### Steps to reproduce

1. I created a new score and entered the notes, lyrics, system and staff text, and tempo.
2. I dragged and dropped volta brackets from the “Lines” palette, extended the bracket on the third volta, and entered what I think are the appropriate numbers in the Repeat list for each one. I did the same with a second set of volta brackets above the keyboard staves.
3. I dragged and dropped the Segno, Coda, “D.S.,” “To Coda,” “D.S. al Fine,” and “Fine” from the “Repeats & jumps” palette. I used staff text to duplicate those markings above the keyboard staves.
4. To playback, I click on the first note of the first voice at the beginning of the score. I hit the spacebar to begin playback.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/145394351/e1e033b6-4fa2-4806-8a37-9035211c9c2a

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

For some reason, .mscz files can't be uploaded here. So I uploaded it here: [https://musescore.com/user/32595665/scores/12246520/s/Ls5a7g?share=copy_link](url)

**Comment by jeetee** [comment] 2023-09-19 07:14
Not a bug in MuseScore, but a misunderstanding on your end as to how jumps and volta interact. Voltas apply to **normal repeats** and there is no repeat barline to be found in your score. In addition to that: Jumps do not increase the repeat/playback counter, but they may reset it (either to 1 or to the "last" normal repeat).

Please refer to the handbook on how to use volta and jumps and feel free to open up a topic in the support forum on .org with your score attached if you'd like help in correcting it.

**Comment by zacjansheski** [comment] 2023-09-19 13:29
Closing, please see above comment, thank you.

**Closed by zacjansheski** 2023-09-19 13:29 UTC
Labels: needs info, playback
