### ISSUE TITLE
[MU4 Issue] Instrument sounds play from start point if changed while playing

### ISSUE THREAD

**Issue by TheJoeCoder** [musescore/MuseScore#15445] opened 2022-12-20 16:25 UTC
**Describe the bug**
While playing, if an instrument sound is changed from a Muse Sounds instrument to another instrument, the new sound begins from the start of the play region instead of the current cursor position.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create or open a score
2. Open the mixer and change an instrument's sound to a Muse Sounds instrument.
3. Press play
4. Change the instrument sound to a different one
5. Listen

**Expected behaviour**
The sound should change and the new instrument sound should start at the correct time.

**Screenshots**
Video demo: https://www.youtube.com/watch?v=dgp7-elXQbM

**Platform information**
 - OS: Windows 11 Pro Version 21H2
 - OS as reported by MuseScore: Windows 10 Version 2009
 - Arch.: x86_64
 - MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-548562

**Additional context**
This **only** happens when changing from Muse Sounds to any other instrument sound. Changing from MS Basic or VST Plugins to other sounds behaves as expected (i.e. resumes from the point of the cursor at the time of switching, with all the other instruments).

The VST Plugin I used was Helm (https://tytel.org/helm/).

I have tried the following:
 - Muse Sounds instrument to other Muse Sounds instrument - Unexpected behaviour (0:24-0:52 in video)
 - Muse Sounds instrument to MS Basic - Unexpected behaviour (0:52-1:09 in video)
 - Muse Sounds instrument to VST Plugin - Unexpected behaviour (1:22-1:30 in video)
 - MS Basic to Muse Sounds instrument - Bug not present (1:09-1:22 in video)
 - MS Basic to VST Plugin - Bug not present (not in video)
 - VST Plugin to MS Basic - Bug not present (not in video)
 - VST Plugin to Muse Sounds instrument - Bug not present (not in video)

**Comment by cbjeukendrup** [comment] 2022-12-22 01:59
Actually a duplicate of #15047, but contains useful information!

**Comment by DmitryArefiev** [comment] 2024-01-08 10:05
Fixed in #20626

**Closed** 2024-01-08 10:05 UTC
