### ISSUE TITLE
Dragging multiple notes around no longer possible

### ISSUE THREAD

**Issue by s1m0n-github** [musescore/MuseScore#20870] opened 2024-01-07 16:02 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In MuseScore 4.2 it is no longer possible (compared to MuseScore 4.1) to drag multiple notes for diatonic harmonization etc.

### Steps to reproduce

1. Write multiple notes into one stave
2. Select multiple notes
3. Try to drag them up or down
4. See that only one of them gets dragged around and the rest will be unselected

### Screenshots/Screen recordings

[Bildschirmaufnahme 2024-01-07 16 59 48.webm](https://github.com/musescore/MuseScore/assets/98892639/b619ecb2-f97a-4cd9-8f27-bdeaed363198)

### MuseScore Version

4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Mint 21.2

**Comment by MarcSabatella** [comment] 2024-01-07 19:10
Thanks for reporting - this is a duplicate of https://github.com/musescore/MuseScore/issues/20606

Meanwhile, diatonic transposition with the usual keyboard shortcuts Alt+Shift+Up/Down works as always.

**Comment by s1m0n-github** [comment] 2024-01-07 19:54
Didn't see the mentioned issue, also good to have a workaround/keyboard shortcut at hand

**Comment by cbjeukendrup** [comment] 2024-01-07 20:21
Closing as duplicate

**Closed by cbjeukendrup** 2024-01-07 20:21 UTC
Labels: regression, UX/interaction
