### ISSUE TITLE
[notation issue] grace note beam collides with regular beam

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15527] opened 2022-12-23 02:48 UTC
**Describe the bug**
grace notes under a beam can allow their own beam to collide with the line on top

**To Reproduce**
1. add eighth notes
3. put some grace notes between them
4. see if the beams collide

**Expected behavior**
the grace notes can get shorter stems or the regular beam can move up

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/209260815-9d2ff55d-45b4-4797-ae86-66b7d04a0dd8.png)

**Comment by oktophonie** [comment] 2022-12-23 07:07
Closing as duplicate of https://github.com/musescore/MuseScore/issues/11013

**Closed by oktophonie** 2022-12-23 07:07 UTC
