### ISSUE TITLE
Performance Drop/Freeze when input too large Values (9999) in Time Signatures Dialog

### ISSUE THREAD

**Issue by selloa** [musescore/MuseScore#23697] opened 2024-07-20 15:39 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Go to Paletts
2. Go to Time Signatures
3. Hit "More"
4. In the Time signatures dialog enter a high value in the very first input box at the top (e.g 9999)
5. In  my case there is an immediate Performance Drop / Freeze. Im guessing this is due to the software trying to render the graphics.

Suggestion:
Warn the user if the number with a dialog to proceed with caution, when entering very high numbers, before letting the software render the images in real time

In my case, I just **accidentally put in a digit too many**, and that basically overflowed/froze the software.

I am running 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Supporting files, videos and screenshots

[see comment](https://github.com/musescore/MuseScore/issues/23697#issuecomment-2245490237)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

The same in **MS3.6.2**

### Operating system

Win11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment] 2024-07-23 13:45
@DmitryArefiev pls check in master

**Comment by DmitryArefiev** [comment] 2024-07-23 14:58
@bkunda The same result in master and in 3.6.2. 
The crash problem is the user can input (accidentally) a very high value (e.g 9999). The **fix** can be to **limit** that value to **99**

https://github.com/user-attachments/assets/5f802670-a0ea-4988-a006-7dd9fe061de2

**Comment by Jojo-Schmitz** [comment] 2024-07-23 15:12
That's more of a workaround than a fix
The problem seems to be the view that tries to visualize the beaming

**Comment by cbjeukendrup** [comment] 2024-07-23 15:34
If we decide to impose a limit, 999 might be more suitable than 99, because time signatures with a numerator >100 definitely exist. They are not common, but wherever possible we should also support the less common things.

Also, instead of updating the preview as the user types, we should maybe do that only when the user finishes typing. We made similar changes to the Style dialog and Properties panel.

**Comment by zacjansheski** [comment] 2024-11-08 03:47
Closing as a duplicate of
https://github.com/musescore/MuseScore/issues/12970

We will consolidate the issue on that report moving forward

**Closed by zacjansheski** 2024-11-08 03:47 UTC
Labels: P2, crash
