### ISSUE TITLE
Change Instrument conditionally shows wrong key signature and clef [MU4 Issue]

### ISSUE THREAD

**Issue by geckosonic** [musescore/MuseScore#12800] opened 2022-08-11 19:11 UTC
For Alto Sax, which is Eb, choosing Change Instrument to Bari Sax (also Eb) results in an incorrect key signature

**To Reproduce**
-- with Concert Pitch = Unchecked --
1. Select a measure in an Alto Sax part
2. Click on  Change Instrument
3. Select  Baritone Sax
4. See error, an incorrect Key Signature  (which is different from the existing one) and clef

**Expected behavior**
Both instruments are Eb, there should be no Key signature change, and the clef should be bass

**Screenshots**

The problem
![Clef Error](https://user-images.githubusercontent.com/94875170/184219573-d226f6dc-18c4-42a4-8ca1-a07ed5368e3c.jpg)

The correct result see ***below
![correct inst key](https://user-images.githubusercontent.com/94875170/184220007-9efd6310-9da5-4001-89a0-921e6738e4ba.jpg)

**Platform information**
Mac OS  11.6.7  (Big Sur)

**Additional context**
***This error DOES NOT occur if Concert PItch is checked prior to the operation.

**Comment by sammik** [comment] 2022-08-12 12:35
Clef is, as far, as I know correct. (Bariton sax is written in treble clef).
But keysig seems to be wrong.

**Comment by sammik** [comment] 2022-08-13 22:31
I tested it a bit.
Clef is also problem, see:
![change_instrument_bug](https://user-images.githubusercontent.com/1646034/184513652-41fb3de9-c043-4880-b323-540883f35dc9.png)
![change_instrument_bug_treble](https://user-images.githubusercontent.com/1646034/184514464-8a00e273-8323-4b4e-8957-7c34f2da39ac.png)

It always behave, as there were untransposed instrument in treble clef in the part.

If I am right, problem is, that `part->instrument(tickStart)` doesnt return correct instrument. 
(Weired is, that `part->instrument()` returns correct one)

That is why not correct clef is checked
https://github.com/musescore/MuseScore/blob/93c9b7326afb5e08ff93385a7f034e06caebd7de/src/engraving/libmscore/instrchange.cpp#L97 
nor transposition
https://github.com/musescore/MuseScore/blob/93c9b7326afb5e08ff93385a7f034e06caebd7de/src/engraving/libmscore/instrchange.cpp#L93

**Comment by Tantacrul** [comment] 2022-09-01 18:00
As much as I'd like to see this fixed, it is present already in MS3, so not a regression. Moving to 4.x and will reopen when we get 4.0 out.

**Closed** 2022-09-01 18:01 UTC
Labels: P1

**Comment by geckosonic** [comment] 2023-06-13 19:16
This makes no sense.

4.1 is not the released version.

4.0.2 is. 

How can you say something is fixed in the future?

**Comment by oktophonie** [comment] 2023-06-13 19:19
Good point, what would I know?
Meanwhile, try downloading a build of 4.1 and see for yourself.

**Comment by geckosonic** [comment] 2023-06-13 19:41
Thank you . I just did verify it in  4.1.0-231640302

As someone who has been in SW development, I am not used this process of closing am end user bug report prior to am official release. 

I have been trying to get this fixed since V 3.

I hope you would be able to imagine that might cause confusion.  

For the future, I get it.

**Comment by MarcSabatella** [comment] 2023-06-13 22:58
For the record, even in 3.6.2, this worked correctly when adding the instrument change from the menu, just not from the palette.  But even for the palette, this is actually already fixed in 4.0 as far as I can tell.  See https://github.com/musescore/MuseScore/pull/14804.  Unless there is subtle difference in the steps for this issue compared to the other marked as closed in that PR.  I can't reproduce any problem with the specific steps given above in 4.0.2 however.

**Comment by geckosonic** [comment] 2023-06-13 23:05
As I reported the  wrong clef changed when adding a specific instrument and in that case specifically.

**Comment by MarcSabatella** [comment] 2023-06-13 23:15
I see - in 4.0.2, you already do get the correct clef and key - but, neither is actually needed in this specific case, since they haven't changed.  In 4.1, MuseScore is smart enough to skip the unneeded clef and key change.

So, the original bug where it was the *wrong* key was fixed long ago, but the fact that a key appeared at all even though it hadn't changed was still an issue that is fixed in 4.1.
