### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by Pakilasakild** [musescore/MuseScore#24535] opened 2024-09-07 19:22 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

No clue how to reproduce, has happened to me once before, but it got fixed after about a year. In the video you can hear how everything sounds, audio settings are on default. The bug occurs in every score I have.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e2fa8aa2-d44c-4717-9a27-fce432abdef2

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment] 2024-09-07 19:31
Please attach your diagnostic files (Diagnostic -> Save diagnostic files)

**Comment by RomanPudashkin** [comment] 2024-09-07 19:35
Also, is this happening in 4.3.2? You can download it here: 
https://github.com/musescore/MuseScore/releases/tag/v4.3.2

**Comment by Pakilasakild** [comment] 2024-09-07 19:47
[diagnostics.zip](https://github.com/user-attachments/files/16919736/diagnostics.zip)

**Comment by Pakilasakild** [comment] 2024-09-07 19:51
This is the sound in 4.3.2 at first it was okay but just very sped up, like 4x, and then it started sounding like 4.4.x

**Comment by Pakilasakild** [comment] 2024-09-07 19:52
https://github.com/user-attachments/assets/9530edc6-bcf7-4ef0-92c8-b242218241d5

**Comment by RomanPudashkin** [comment] 2024-09-07 19:57
As far as I can tell by looking at the diagnostic files, MuseScore can't run normally because your system is using 8-channel audio. Unfortunately, we currently only support 2-channel audio, and this is a well known issue: https://github.com/musescore/MuseScore/issues/17648

**Comment by RomanPudashkin** [comment] 2024-09-07 20:15
You can try changing the current configuration to Stereo in the Speaker setup dialog. Here's what it would look like:
![image](https://github.com/user-attachments/assets/fcc245e4-c160-4265-9bfa-2042c567eaac)

**Comment by Pakilasakild** [comment] 2024-09-07 20:40
![image_2024-09-07_234028222](https://github.com/user-attachments/assets/39efcf86-391a-4cc1-8e0a-600656851bc0)

**Comment by Pakilasakild** [comment] 2024-09-07 20:41
My device is the PRO X 2 LIGHTSPEED Is there any way to enable 2 channel sound or am I done for..?

**Comment by MarcSabatella** [comment] 2024-09-09 13:34
You might try checking in the support forums for that device.  I would think any device providing >2 channels would also have *some* way of setting it to be normal stereo.

**Comment by RomanPudashkin** [comment] 2024-09-11 08:39
I'm going to close this as a duplicate of https://github.com/musescore/MuseScore/issues/17648. However, we're going to fix it in 4.4.3

**Closed by RomanPudashkin** 2024-09-11 08:39 UTC
Labels: duplicate
