### ISSUE TITLE
Pop up windows not opening

### ISSUE THREAD

**Issue by rubenslawski** [musescore/MuseScore#18852] opened 2023-07-30 21:53 UTC
### Issue type

UI bug

### Bug description

When I try to open any kind of setting which involves a new window, a black window pops up for a very short amount of time and then disappears again. One example is the page settings bit this applies to every single instance of a new window opening.

### Steps to reproduce

1. click on the formating option in the menu bar
2. click on page settings (german: Seiteneinstellung)

### MuseScore Version

4.1.1 (appimage) & current flatpak version

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 23.04 & Debian 12 (on wayland and x11)

**Comment by cbjeukendrup** [comment] 2023-07-30 23:29
This looks very much like a duplicate of #18608. Interesting that it apparently even happens on Ubuntu.

**Comment by Eism** [comment] 2023-07-31 06:25
yes, duplicate of https://github.com/musescore/MuseScore/issues/18608

**Closed by Eism** 2023-07-31 06:25 UTC
Labels: UI, regression
