### ISSUE TITLE
[Inspector & Palettes] All jumps are non functional

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9282] opened 2021-09-25 10:23 UTC
**See video for example**

https://user-images.githubusercontent.com/21022311/134768042-0351299c-68d2-4553-a798-25af7affc346.mp4

@DmitryArefiev - I think you may need to provide additional advice for this particular bug, since the musical conventions might be tricky to understand.
@Tantacrul  - Found https://musescore.org/en/handbook/3/repeats-and-jumps It should help

**Comment by jeetee** [comment] 2022-01-26 22:44
Same root cause as #9185 
We never process the play repeats setting, which means the score is always played back to front ignoring all repeats, jumps and voltas

**Comment by DmitryArefiev** [comment] 2022-03-29 20:16
Tested in master build on Win10, Mac12, LinuxMint 20.2 - **FIXED**

Works fine on [jumps.zip](https://github.com/musescore/MuseScore/files/8374739/jumps.zip)

Closing

**Closed** 2022-03-29 20:16 UTC
Labels: P0
