### ISSUE TITLE
Broken Beams

### ISSUE THREAD

**Issue by ronnyAndDee** [musescore/MuseScore#15841] opened 2023-01-12 16:52 UTC
**Describe the bug**
Migrating 3.6.2 score to 4.0.  Beams are broken, notes are disconnected.

**To Reproduce**
open the  3.6.2 score, open  4.0 score and compare results

**Expected behavior**
Comparing the 3.6.2 score is correct and concise.  Compare to 4.0 score will show the beams are a mess.

**Screenshots**
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/96542953/212129600-ced35ff2-ab90-40da-b9fb-2f5888d7c0c6.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]
macOS 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/96542953/212129805-a9247fc1-6843-46cc-9d9c-67784da7f168.png">

**Additional context**

**Comment by MarcSabatella** [comment] 2023-01-12 17:09
I don't see the score (you need to ZIP it or rename it in order to attach), but I'm guessing this is due to conflicting customized stem directions and as such is probably a duplicate of https://github.com/musescore/MuseScore/issues/15166.

Workaround is to reset the conflict stem directions.  Eg, If you have two notes beamed together, you shouldn't have one set to stem up and the other to stem down.  MU3 was more forgiving of this sort of thing, and hopefully MU4 will also be enhanced to do so, but meanwhile, better to just fix the stem directions in the score.

**Comment by ronnyAndDee** [comment] 2023-01-12 17:19
oh ok Mark.  tried to upload but didn't realize had to be a .zip instead of the actual .mscz.  2 files: 3.6.2 and 4.0
[Archive.zip](https://github.com/musescore/MuseScore/files/10404194/Archive.zip)

**Comment by ronnyAndDee** [comment] 2023-01-12 17:27
Mark,
made corrections to the 3.6.2 file, opened  with 4.0,  and still not correct.

**Comment by RobFog** [comment] 2023-01-12 18:44
Yes, seen as it's drum notation it must be a duplicate of #15166.

**Comment by MarcSabatella** [comment] 2023-01-12 19:00
Not sure how you did the rest, but you didn't get everything.  Simplest way to get more is to Ctrl+A to select all, then Ctrl+R to reset.  There might be other things adjustments you want to keep, so you could use "View / Selection filter" to exclude articulations, for instance.  Or select them all when done and set them to above explicitly in Properties.

**Closed** 2023-01-12 21:50 UTC

**Comment by ronnyAndDee** [comment] 2023-01-14 17:25
Aaah Perfect Mark.  works like a charm!!
