### ISSUE TITLE
[MU4 Issue] Stem disappearing when tweaking beam height.

### ISSUE THREAD

**Issue by Coxev** [musescore/MuseScore#15384] opened 2022-12-19 15:34 UTC
**Describe the bug**
When tweaking the height of a beam linked to two beamed notes (eighth note, 16th...) and also linked to a silence, the stem from the second note disappear.

**To Reproduce**
1. Enter two beamed notes (eighth note, 16th...).
2. Join the beam from these notes to a silence placed after those notes.
3. Change the beam height.
4. Beam disappearing.

**Expected behavior**
The stem should stay linked to the beam, even if I change the height of this beam.

**Screenshots**
![image](https://user-images.githubusercontent.com/39700491/208461866-f0498390-c20c-4d43-8181-f7014db4fc8d.png)

**Platform information**
 - OS: Windows

**Comment by oktophonie** [comment] 2022-12-20 14:31
Duplicate of https://github.com/musescore/MuseScore/issues/15401

**Closed by oktophonie** 2022-12-20 14:31 UTC
