### ISSUE TITLE
Dragging dynamics or expression text moves end of adjoining hairpin even when snapping is turned off

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#24263] opened 2024-08-28 13:11 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create a hairpin with dynamics and/or expression text at either end
2. Select the hairpin and turn off 'Snap to previous' and 'Snap to next' in properties
3. Drag the dynamics/expression text left and right; the ends of the hairpin follow the horizontal movement, but they shouldn't

Dragging the dynamics or expression _vertically_ works fine (the hairpin does not follow). Also, using Shift+left/right to move dynamics works fine (the hairpin endpoint stays where it is) - it is only when dragging with the mouse, or nudging with the left/right cursor keys without Shift, that the problem arises. Unfortunately this does not help with the expression text case, as they cannot currently be moved with Shift+left/right.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/eb4f9c84-5700-440f-961a-0d2d85c86b09
(in this example, snapping has been turned off for both ends of the hairpin)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux/any

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment] 2024-08-28 13:12
Duplicate of #24262 ?

**Comment by oktophonie** [comment] 2024-08-28 13:24
Thanks, GitHub, for posting it twice!

**Closed** 2024-09-11 08:32 UTC
Labels: P1, UX/interaction
