### ISSUE TITLE
choosing option to open a new window, or open as a tabbed window

### ISSUE THREAD

**Issue by H-MLim** [musescore/MuseScore#23398] opened 2024-06-28 14:14 UTC
### Your idea

when I make a new file, or load a file, MS4 forces to open the new window. I saw it was intentional (according to here: https://musescore.org/en/node/336366) but sometimes it really bothers me. and if it's intentional, I can't understand then why the tab window is inside the program. (I also prefer simply clicking the tab to pressing two keys - Alt+Tabbing)

### Problem to be solved

I want to open my file into the same window.

### Additional context

![image](https://github.com/musescore/MuseScore/assets/68152553/51cfb171-e3d1-46ed-8e84-77985c85da16)

**Comment by oktophonie** [comment] 2024-06-28 14:23
Duplicate of https://github.com/musescore/MuseScore/issues/12647 etc

**Closed by oktophonie** 2024-06-28 14:23 UTC
Labels: feature request
