### ISSUE TITLE
Muse sounds sectional strings legato is horrible.

### ISSUE THREAD

**Issue by AZEntertainment** [musescore/MuseScore#17706] opened 2023-05-23 22:28 UTC
### Issue type

Muse Sounds bug

### Bug description

I was performing Beethoven and my own pieces with muse sounds. And the string legato was just too delayed and slow. And the legato is not even noticeable on passages it can handle. And when the fast legato triggers, it sounds like it's cutting between the notes. Which is definitely not how fast legato sounds.

### Steps to reproduce

1. Open musescore 4
2. Open a new score or any score
3. Open any Muse sounds sectional strings.
4. Write a slightly fast legato passage.

### MuseScore Version

4.02

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by bkunda** [comment] 2023-05-24 13:14
Duplicate of https://github.com/musescore/MuseScore/issues/14524.

**Closed by bkunda** 2023-05-24 13:14 UTC
Labels: muse sounds
