### ISSUE TITLE
[MU4 Issue] Improper repeat pattern for two-measure repeats

### ISSUE THREAD

**Issue by scohenjanes5** [musescore/MuseScore#15710] opened 2023-01-04 17:56 UTC
**Describe the bug**
Two-measure repeats play only the previous measure, then silence. If this motif is itself repeated, the second bar of silence of the first repeat is propagated to the following repeats.

Using capital letters to denote explicitly written bars and lowercase to denote bars played by the repeat: 
AB b(Silence) (Silence)(Silence)

**To Reproduce**

Play the example attached, or just drag the 2-measure repeat to the measure directly following the two measures you wish to repeat. In the attached example, I did this twice, so the first two bars are expected to play a total of three times.

**Expected behavior**
The first two bars should play in their AB pattern a total of three times: AB ab ab.

**Screenshots**
![image](https://user-images.githubusercontent.com/101665992/210617784-40dd7210-4d6e-4878-b75a-a50f6bca8676.png)

**Platform information**
 - OS: [Windows 11]

**Additional context**
[Example.zip](https://github.com/musescore/MuseScore/files/10346262/Example.zip)

**Comment by cbjeukendrup** [comment] 2023-01-04 18:00
Duplicate of #10922. Thanks for reporting though, and thanks for the example!

**Closed by cbjeukendrup** 2023-01-04 18:00 UTC
