### ISSUE TITLE
[MU4 Issue] Pedal line with asterisk does not extend to the end of a note's duration

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#15883] opened 2023-01-14 22:10 UTC
**Describe the bug**
The old style pedal marking with an asterisk is notated correctly only when it covers a single measure, otherwise the asterisk is placed too close to the last note under the pedal line. 

**To Reproduce**
1. Select a range of notes to pedal that's not a single measure.
2. Click on the pedal icon in the palette.

**Expected behavior**
Asterisk is placed before the next note after the end of the pedal line. 

**Screenshots**
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/3182625/212499169-2d8de842-93ae-4305-af23-d029633562f4.png">

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Additional context**
Other pedal markings display fine.

**Comment by oktophonie** [comment] 2023-01-14 22:18
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/9975

**Closed by oktophonie** 2023-01-14 22:18 UTC
