### ISSUE TITLE
[MU4 Issue] View > "Show invisible" actually hides invisible things (implementation is backwards)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7821] opened 2021-03-30 01:43 UTC
**Describe the bug**
View > "Show invisible" actually hides invisible things (implementation is backwards)

**To Reproduce**
1. Create a score with unprintable items
2. Go to "View" on the upper Menu bar
3. Click on "Show invisible"

**Expected behavior**
Should show invisible items if "Show invisible" checkbox tick and hide them if not tick

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**
This might be helpful with invisible parts:
https://musescore.org/en/node/115796 - Show formatting ('show invisible' in a text app)

**Comment by wizofaus** [comment] 2021-07-10 23:33
Can't reproduce or see any reason it might be different on MacOS. Can you confirm @vshalkevich and close if no longer an issue.

**Comment by cbjeukendrup** [comment] 2021-07-11 10:45
Seems fixed on macOS too, so let's close it.

**Closed** 2021-07-11 10:49 UTC
Labels: P2
