### ISSUE TITLE
Changing instrument mid-playback causes music to restart but tracking header continues from where it was

### ISSUE THREAD

**Issue by five-over-four** [musescore/MuseScore#20593] opened 2023-12-20 11:55 UTC
### Issue type

General playback bug

### Bug description

Let's say I have 16 bars of music and I put the playback cursor at bar 8 and press play. Now If I change the instrument of the currently playing track, the music will restart at bar 8, but the blue tracking line will continue from where it was without moving back to bar 8. The music will also stop a little prematurely, before reaching the end.

The amount of music that is cut off seems to be roughly based on the amount of bar-time that has passed since originally pressing play. Ie. 8 bars of music, change instrument at bar 4, you'd have _roughly_ 8 bars of playback total. It doesn't seem exact- some rounding happening, maybe.

### Steps to reproduce

1. Create a new file with one staff of music and add 8 bars of any notes.
2. Start playback at the beginning and change the instrument of the playing track midway through.

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment] 2023-12-20 17:39
Duplicate of https://github.com/musescore/MuseScore/issues/15445 / https://github.com/musescore/MuseScore/issues/15047 ?

**Comment by DmitryArefiev** [comment] 2024-01-08 10:05
Fixed in #20626

**Closed** 2024-01-08 10:05 UTC
Labels: playback
