### ISSUE TITLE
[MU4 Issue] Elements are "moving" in display without touching them when using page view

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#16004] opened 2023-01-22 08:34 UTC
**Describe the bug**
The attached score is a downloaded score from musescore.com which I imported into MS4.
I manually removed all parts from it by extracting the MS file and deleting the parts and re-zip the file (did not realize MS4 does not allow to delete parts).
I started adding some instruments and now spot this weird behaviour in the GUI.
At measure 9 (and some other measures) there are number of glissandos. When the file is opened in Page View, it shows the glissandos at measure 9.
![image](https://user-images.githubusercontent.com/13550012/213906904-20a92efb-ef78-4165-ac36-4e6e2c9fc242.png)
During editting these glissandos somehow are visually moving to measure 1.
In this score, double click the Composer to edit and add an extra space.
![image](https://user-images.githubusercontent.com/13550012/213906985-726d6e84-dc9b-41dc-942f-0ffc0dd6c553.png)
This only seem to effect the display, as when you save the file and open it again the position of the glissando is reset to measure 9.

**To Reproduce**
1. Open attached score
2. Ensure you have page view enabled
3. Edit the Composer text
4. See result

**Expected behavior**
Position of the glissandos should remain the same.

**Platform information**
 - OS: Windows 11, MS4 4.0.1

** Attached score
File renamed to .zip.
[Megalovania - test.zip](https://github.com/musescore/MuseScore/files/10474006/Megalovania.-.test.zip)

**Comment by oktophonie** [comment] 2023-01-22 09:43
Duplicate of https://github.com/musescore/MuseScore/issues/15316 (have made this a 4.0.2 issue)
Will be fixed by https://github.com/musescore/MuseScore/pull/15476

**Closed by oktophonie** 2023-01-22 09:43 UTC
