### ISSUE TITLE
Augmentation dot is not rendered after changing notehead scheme

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24708] opened 2024-09-13 23:47 UTC
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Enter note with augmentation dot
2. Go to Staff/Part properties -> Advanced style properties
3. Change notehead scheme to any other than "normal" -> Ok
4. Augmentation dot disappeared

This is a regression since MS 4.4.0. It works in MS 4.3.2
[Report on musescore.org](https://musescore.org/en/node/368280)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/831706d5-7db6-4a12-86f1-7e44ae858ab1

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-242570304, revision: github-musescore-musescore-d7a9ce4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment] 2024-09-14 06:31
Duplicate of https://github.com/musescore/MuseScore/issues/24610

**Closed by oktophonie** 2024-09-14 06:31 UTC
Labels: regression MS4, engraving
