### ISSUE TITLE
copy pasting long notes to another beat glitches tie location

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#19971] opened 2023-11-08 06:15 UTC
### Issue type

Engraving bug

### Bug description

when something like two half notes tied together gets copy pasted to another bar but starting on the offbeat, the new tie becomes as long as the page horizontally instead of the distance between notes

### Steps to reproduce

1. in 4/4 meter, create a dotted whole note (which ties to the next bar)
2. copy the two tied notes and paste them in another bar but one eighth rest after the downbeat (or any offbeat)
3. see the new tie goes too far left

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/013aa6b4-b2fc-47b7-b337-48c4f6e44668)

![image](https://github.com/musescore/MuseScore/assets/120861729/73475082-0388-4424-b88d-e64faf284210)

### MuseScore Version

4.1.1-232071203

### Regression

No.

### Operating system

windows 11

**Comment by oktophonie** [comment] 2023-11-17 15:34
Duplicate of https://github.com/musescore/MuseScore/issues/19081 (now fixed in master)

**Closed by oktophonie** 2023-11-17 15:34 UTC
Labels: P2, duplicate, engraving
