### ISSUE TITLE
[MU4 Issue] Score extremely zoomed in when opened

### ISSUE THREAD

**Issue by lordlouckster** [musescore/MuseScore#15591] opened 2022-12-25 21:29 UTC
**Describe the bug**
Sometimes, when you open a score, it opens extremely (but not maximally) zoomed in from the top left corner.

**To Reproduce**
1. Open a score. This should open correctly.
2. Open another score using "Open" in the window of the aforementioned score.
3. The score opens zoomed in.

**Expected behavior**
The score should open like the first score when following the steps.

**Platform information**
 - OS: Windows 10

**Additional context**
This issue can be mitigated by reverting to factory settings, but it may or may not occur again, and once it occurs, it won't go away until you revert to factory settings.

**Comment by cbjeukendrup** [comment] 2022-12-26 00:40
When it happens again, could you please check what Preferences > Canvas > Default Zoom says? Or have you already checked that and didn't it say anything special? 

I've no luck reproducing this so far...

**Comment by anonymous7002** [comment] 2022-12-26 09:48
Default Zoom didn't say anything special. A risk factor of this bug seems to be a jaggy scrollbar.

**Comment by anonymous7002** [comment] 2023-01-10 16:55
I've reproduced it a couple of times, and the presymptoms seem to be opening the navigator, which causes the scrollbar to stutter under certain circumstances, possibly including additional load from background applications.

**Comment by cbjeukendrup** [comment] 2023-01-10 22:47
Ah! The navigator! That might be it indeed. I'll take another look to reproduce it!

**Comment by Jojo-Schmitz** [comment] 2023-01-27 20:53
See https://musescore.org/en/node/343693 for some more hints when this happens and when it doesn't

**Comment by MarcSabatella** [comment] 2023-05-01 15:57
Just came up again in https://musescore.org/en/comment/reply/node/348567.  Oddly, the *first* score opened in any given session is normal, but opening a second instance shows the problem.  That's the case in the video from the OP in that thread, also on my system.

**Comment by cbjeukendrup** [comment] 2023-07-04 22:22
@lordlouckster Does this still happen in the MuseScore 4.1 nightly builds? https://musescore.org/en/nightly-builds

**Comment by mercuree** [comment] 2023-07-15 00:03
Still can reproduce 0% zoom with opened navigator
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-231952157, revision: github-musescore-musescore-3817022

**Comment by Jojo-Schmitz** [comment] 2023-12-19 12:18
I still can reproduce too, even in 4.2.0, in all parts, but not in the main score

**Comment by dcorson-ticino-com** [comment] 2024-01-18 12:25
This is apparently provoked by the Navigator.
W/o Navigator all is well, with the Navigator parts are displayed wrong. 
I have Preferences>Canvas>Default Zoom set to 100%, but my parts always open to zoom 0 according to the drop-down in the lower right corner. The displayed part is, however, is at somewhere between zoom of 200 and 300 (255?). I can set the zooms of the parts to 100% and they display correctly, but after saving, closing MU and opening again all is back to 0. The score is behaving, it is just the parts with this problem.  

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: [eb8d33c](https://github.com/musescore/musescore/commit/eb8d33c)

**Comment by cbjeukendrup** [comment] 2024-05-30 12:38
Closing as superseded by https://github.com/musescore/MuseScore/issues/23033. That one is actually a duplicate, but is much clearer and doesn't have a long comment history yet, so I'll close this one instead.

**Closed by cbjeukendrup** 2024-05-30 12:38 UTC
Labels: P2, UI, regression
