### ISSUE TITLE
[MU4 Issue] VST - Window dialog sizing glitches (125%, 150%, 175%, 200% scaling on Windows)

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9893] opened 2021-11-26 13:18 UTC
**Describe the bug**
Both VST and VSTi are having issues with the window dialog sizing.
Mostly Windows is having more faulties than MacOS

I have made a spreadsheet to document each free VST plugin on both OS and report what their results are:
https://docs.google.com/spreadsheets/d/1_QkLy5Q_ZnIn_jbn7w2NNnyo8mYgfu7Im9L3xjCwRps/edit#gid=0

Most common faults are:
- Too much extra white space
- Cut-off space [(Kontakt and Sforzando)](https://github.com/musescore/MuseScore/issues/9228)
- VST too big or too small
- Top part is cut off (MacOS)

![image](https://user-images.githubusercontent.com/71656189/143586148-ef8b04b4-5c53-4ddc-95eb-c0beaecf210a.png)
![image](https://user-images.githubusercontent.com/71656189/143586178-72394eea-b866-4f77-a531-8a9160104d85.png)
![image](https://user-images.githubusercontent.com/71656189/143586251-b7cb3da1-e296-49ad-b670-eedb58ba3290.png)
![image](https://user-images.githubusercontent.com/71656189/143586945-baeda262-b88e-474f-9bc9-fc0fe51a1c25.png)
![image](https://user-images.githubusercontent.com/71656189/143589094-b059d424-991b-4451-8e0a-bb950c526a92.png)

**Comment by mattblo** [comment] 2022-02-04 07:13
@jessjwilliamson You mention the Melda plugins here and write that they are working. (In the spreadsheet)
However, I can only open the Melda plugins in the instrument channels, not in the master channel. Is this error known or already listed somewhere?

**Comment by jessjwilliamson** [comment] 2022-02-04 13:15
> @jessjwilliamson You mention the Melda plugins here and write that they are working. (In the spreadsheet) However, I can only open the Melda plugins in the instrument channels, not in the master channel. Is this error known or already listed somewhere?

You are right, I will bring up this issue that master is not handling plugins as well as instrument channels

**Comment by jessjwilliamson** [comment] 2022-02-17 12:01
@RomanPudashkin @DmitryArefiev Hi guys, This is me testing the LABS and BBC Orchestra (they are both under same company Spitfire). This is bizarre on Windows (Mac is completely fine!) I can't even move the dialog or close it, it appears stuck unless I force quit.

https://user-images.githubusercontent.com/71656189/154477684-2db6dcc1-c862-46cc-b2dd-fdc597facce6.mp4

**Comment by jessjwilliamson** [comment] 2022-02-17 12:11
@RomanPudashkin @DmitryArefiev Testing Kontakt, Mac OS is fine with the window layout, but this is how Windows shows. Kontakt appears too small and has extra space. However, BOTH OS has a horribly broken playback causing a buzzing sound (or non at all like this recording) which can be visibly seen the mixer volume is clipping.

https://user-images.githubusercontent.com/71656189/154479138-62eef604-07c8-45bb-b4ee-9bdfea02c96d.mp4

**Comment by jessjwilliamson** [comment] 2022-03-29 10:04
> @RomanPudashkin @DmitryArefiev Hi guys, This is me testing the LABS and BBC Orchestra (they are both under same company Spitfire). This is bizarre on Windows (Mac is completely fine!) I can't even move the dialog or close it, it appears stuck unless I force quit.
> 
>  2022-02-17.11-58-49.mp4

@DmitryArefiev Can you kindly test on Vasily's latest build (as of 29th March) that this is still happening on Windows? It's still happening to me, I can't even resize the VSTs windows anymore by click and drag the edge.

**Comment by mattblo** [comment] 2022-03-29 10:32
> It's still happening to me, I can't even resize the VSTs windows anymore by click and drag the edge.

I can confirm this in the last nightly builds.
VST windows now open in a reasonable size, but cannot be resized. 
I also noticed that the Melda plugins open in a very small window with almost no UI the second time they are opened (1. add plugin and close window 2. open plugin again).

**Comment by boryskuzmenko** [comment] 2022-03-29 11:40
No resize issues on MacOS. JFYI

**Comment by jessjwilliamson** [comment] 2022-03-29 11:47
> No resize issues on MacOS. JFYI

Yes, Windows only

**Comment by jessjwilliamson** [comment] 2022-03-29 18:19
> @jessjwilliamson Here is mine
> 
>  bandicam.2022-03-29.18-45-11-893.mp4 
> I think the problem is in DPI scaling on Windows..
> 
> Can you try please on 100% (Display settings>Scale and layout)?

Ahhhhh, my 100% of course it works.. because I have 4k screen it looks MASSIVE. 
I usually work on 200% scaling so this is a bug that should be fixed for users that uses different scaling.. I understand this is complex but well done @DmitryArefiev for figuring that out!
![image](https://user-images.githubusercontent.com/71656189/160678556-8395ebf6-f8bd-49d1-ba09-83ec111ed6cf.png)

**Comment by Tantacrul** [comment] 2022-05-08 10:50
@jessjwilliamson - do other DAW's scale VSTs properly when you change the scaling in Windows? Is it MuseScore only that's doing it?

**Comment by jessjwilliamson** [comment] 2022-05-09 12:29
> @jessjwilliamson - do other DAW's scale VSTs properly when you change the scaling in Windows? Is it MuseScore only that's doing it?

Absolutely fine on other DAW's. Just Musescore. This is still irritating me to this day!!

**Comment by jessjwilliamson** [comment] 2022-08-04 15:52
Just to update with better explanation about this issue on screen recording. 
For me at least, VSTs are pretty much unusable when on 200% scaling so I have to switch to 100% when I need to use them. Pretty much anything other than 100% there is a window problem with VSTs. I have 4k screen so I HAVE to work on 200% scaling. This could be problematic for users who aren't able to use 100% scaling. Here's what I mean:

https://user-images.githubusercontent.com/71656189/182890590-a9847930-d57f-453f-9f9e-bc5ebe575efe.mp4

**Comment by DmitryArefiev** [comment] 2022-08-05 14:04
The issue becomes more common because it also occurs on 125% now (after fractional scaling implementation)

**Comment by jessjwilliamson** [comment] 2022-08-05 14:10
> The issue becomes more common because it also occurs on 125% now (after fractional scaling implementation)

Also 175% :)

**Comment by DmitryArefiev** [comment] 2022-10-03 13:43
Fixed in #13554

**Comment by jessjwilliamson** [comment] 2022-10-04 08:51
Good to see the outside grey areas seem to be gone - however if I'm in a high scaling and load a VST that is too big, there is no way to move it out of the way. I can't click on anything or drag the outside to resize the dialog. I think the click and drag corner or side USED to work now it isn't anymore.
![image](https://user-images.githubusercontent.com/71656189/193776749-b8b83e0f-bf12-460e-9f36-438c62c0e2aa.png)

**Comment by jessjwilliamson** [comment] 2022-10-04 08:53
Just tried even higher scaling - 150% unfortunately the grey space on the right does appear here :( 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/71656189/193777301-7b9030ee-99a6-4b78-bf74-cfcbb97d96f7.png">

**Comment by DmitryArefiev** [comment] 2022-10-04 16:00
@jessjwilliamson The last case did you try on this build? https://github.com/musescore/MuseScore/actions/runs/3160100119

(from #13554)

**Comment by Tantacrul** [comment] 2022-10-04 16:20
@DmitryArefiev - are you seeing a different result?

**Comment by DmitryArefiev** [comment] 2022-10-04 17:16
@Tantacrul @jessjwilliamson I'm trying now on my Windows laptop with FullHD display on 150%.
I also have too much wide BBC SO window but it dissapears after re-enabling that plugin again. Thats strange.
But I don't have a grey space from the right


https://user-images.githubusercontent.com/90187801/193883992-5b390652-42c5-4a06-8d74-67d1076cb042.mp4

**Comment by DmitryArefiev** [comment] 2022-10-04 17:43
The initial testing was on my Lenovo laptop with **QHD** display on 125,150% (with Kontakt and other plugins).
Now I installed BBC and LABS plugin to see how they behave on that machine.

What I see now the **most ugly issue with too much extra white/grey space is fixed**. Roman says PR #13554 is fixing exactly that problem.

I think other issues regarding window size should be logged separately.
For example like the issue with BBC orchestra window (doesn't occur with LABS):




https://user-images.githubusercontent.com/90187801/193889346-972c9cd6-daa8-41c4-ab69-a5b5d4a7f951.mp4

**Comment by Tantacrul** [comment] 2022-10-04 17:46
Sounds good @DmitryArefiev. Thanks!

**Closed** 2022-10-06 09:21 UTC
Labels: P1
