### ISSUE TITLE
Font size settings for tempo changes.

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22581] opened 2024-04-25 19:09 UTC
### Your idea

Please add a font size option for changing the tempo to the properties

### Problem to be solved

This will make it easier for users to adjust the font size of the tempo change. At the moment, to change the font size, you need to open the score style settings and find the tempo change properties in a large list. 

Why do I need to change the font size of the tempo at all, you ask? In a score consisting of a considerable number of instruments, the tempo designation, written automatically in a standard font size, may seem almost imperceptible. But that shouldn't be the case. The font size of the tempo should be adjusted depending on the density and size of the score. And I suggest making Musescore automatically adjust the font size of the tempo.

### Additional context

For some reason, font size settings are only available in the properties of the non-changing tempo. This is strange.

**Comment by XiaoMigros** [comment] 2024-04-25 22:21
Duplicate of #14238

**Closed** 2024-04-25 22:38 UTC
Labels: feature request
