### ISSUE TITLE
Musescore Wayland open menus places at the center of the screen

### ISSUE THREAD

**Issue by iWisp360** [musescore/MuseScore#21794] opened 2024-03-03 17:46 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

1- Open musescore with native wayland: QT_QPA_PLATFORM=wayland musescore
2- Click on any menu of the menu bar

### Screenshots/Screen recordings

![Screenshot_20240303_124205](https://github.com/musescore/MuseScore/assets/114373500/15a720ac-2bed-405c-95e3-76c6fa4ae140)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Archlinux

**Comment by iWisp360** [comment] 2024-03-03 17:49
https://github.com/musescore/MuseScore/assets/114373500/93c20854-c393-4545-b488-94d88f45fe21

**Comment by cbjeukendrup** [comment] 2024-03-03 21:26
Duplicate of #15285, except that this is about context menus and the other is about top menus. But since both are implemented basically the same way, the underlying cause is the same.

**Closed by cbjeukendrup** 2024-03-03 21:26 UTC
Labels: UI
