### ISSUE TITLE
4.4 doesn’t open other scores + error missing Plugins/config.json

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#22682] opened 2024-05-05 01:03 UTC
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When I am in a score and try to open a saved score without closing the current score, the other score doesn’t open.  Just the new instance is created.  An error message of failed to read config data, err: [406] An error occurred when reading from the file, file: /home/me/Documents/MuseScore Studio/Plugins/config.json shows in the terminal. Possibly related. 

### Steps to reproduce

Open new score.  Save.  Close.  Open new score.  Save.  Go to file open and open prior score.  Score doesn’t open correctly. 

Another error between switching is ExtensionsLoader::manifestPaths | failed scan files, err: [406] The file does not exist.  

### MuseScore Version

4.4 Master from today

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 24.04

**Comment by bkunda** [comment] 2024-05-07 13:18
@cbjeukendrup can you please see if you can assist here? Thank you!

**Comment by TeeDeeY** [comment] 2024-05-07 17:21
Let me download the latest build and see if I can reproduce it there.

**Comment by TeeDeeY** [comment] 2024-05-07 18:38
Checked in 22.04 and 24.04.  In both, the nightly master build, when looking at an open score and then opening a second score, instead of the second score opening, the main screen shows up.  Video shortly.

**Comment by TeeDeeY** [comment] 2024-05-07 18:51
[
[Screencast from 2024-05-07 11-26-27.webm](https://github.com/musescore/MuseScore/assets/159660491/3aadf8c3-0e48-4317-80b0-6e246fa4034a)
](url)

**Comment by TeeDeeY** [comment] 2024-05-07 20:02
Today’s master nightly also has a problem when a score is open.  Select “Instruments” tab.  Click on the gear symbol.  Up pops the option to “Replace instrument”.  Pressing that bar doesn’t do anything.  The master from last month performed as normal.

**Comment by cbjeukendrup** [comment] 2024-05-12 01:59
> Today’s master nightly also has a problem when a score is open. Select “Instruments” tab. Click on the gear symbol. Up pops the option to “Replace instrument”. Pressing that bar doesn’t do anything. The master from last month performed as normal.

I think that will be fixed by #22681.

> Checked in 22.04 and 24.04. In both, the nightly master build (just downloaded), when looking at an open score and then opening a second score, instead of the second score opening, the main screen shows up. Video shortly.

I found the problem (it was caused by recent changes) and created a fix here: https://github.com/musescore/MuseScore/pull/22778

> error missing Plugins/config.json

I think that's probably normal; there's quite a bunch of error messages that just mean that a user settings file doesn't exist because the user has never changed the settings in question yet, and I think that this is another case of that. If you do find problems around plugins, please open a new issue about that, so that we can keep this issue focused on the "opening second scores" problem.

**Closed** 2024-05-12 02:15 UTC
Labels: needs info, regression, UX/interaction
