### ISSUE TITLE
[MU4 Issue] Playback Loop Feature Not Working 

### ISSUE THREAD

**Issue by Ahh6483** [musescore/MuseScore#16069] opened 2023-01-25 20:58 UTC
**Describe the bug**
Playback loop feature not working as intended with scores with more than one instrument. Playback loops wrong measures. 

**To Reproduce**
1. Open Score.
2. Select measure(s) you'd like to loop.
3. Click on 'Loop Playback'
4. Click 'Play'
5. See error

**Expected behavior**
Expected to loop selected measures, not any others. 

**Screenshots**

https://user-images.githubusercontent.com/79336035/214688939-c4677d20-ff61-4e6f-80b1-39aea458f4d7.mov

**Platform information**
 - OS: macOS

**Additional context**
New MS4 Score.

**Comment by zacjansheski** [comment] 2023-05-30 19:01
I am not able to reproduce this exactly, selecting/starting playback on a bar outside of the loop does end the loop so it is understandable if it does not function as expected (we will certainly work on improving in the future)

I would like to re-scope this issue to "Loop no longer active after selecting outside of loop". Unless there is a larger issue here I am not aware of.

https://github.com/musescore/MuseScore/assets/69917893/a1d82cc1-05cf-4651-a315-a089aea3546b

**Comment by zacjansheski** [comment] 2023-06-07 17:09
Closing this issue, loop functionality has improved.

**Closed by zacjansheski** 2023-06-07 17:09 UTC
