### ISSUE TITLE
disappearing dots on banjo tablature

### ISSUE THREAD

**Issue by wartonbega** [musescore/MuseScore#21781] opened 2024-03-02 15:50 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When the sheet is being played, dots from dotted notes disappears. They reappears when the playing stops
![Enregistrement de l’écran 2024-03-02 à 16 40 56](https://github.com/musescore/MuseScore/assets/66480904/438e630b-c3df-4324-80b0-978849bce0bc)
I haven't tested other instrument, or other rythmes than quarter notes.

### Steps to reproduce

1. Start a new tablature (banjo f.e.)
2. Write a few dotted quarter note (for the bug to be visible)
3. Play it 

### Screenshots/Screen recordings

![Enregistrement de l’écran 2024-03-02 à 16 40 56](https://github.com/musescore/MuseScore/assets/66480904/f8b32c69-0546-418d-9001-af9807a7fcd7)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937

### Regression

I don't know

### Operating system

macOS 12.6

**Comment by Jojo-Schmitz** [comment] 2024-03-03 10:01
Looks familiar, probably a duplicate

**Comment by Jojo-Schmitz** [comment] 2024-03-03 10:03
Found it: #19036

**Comment by cadiz2** [comment] 2024-03-03 11:33
It's not a duplicate. Tested with OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240630505, revision: github-musescore-musescore-b25a6bc
and this visual bug is always active.

**Comment by oktophonie** [comment] 2024-03-03 11:36
It's closer to https://github.com/musescore/MuseScore/issues/20562 (and there was at least one other similar issue)

**Comment by cadiz2** [comment] 2024-03-03 11:46
In fact, it's a duplicate of: https://github.com/musescore/MuseScore/issues/21120

**Closed** 2024-03-03 20:02 UTC
Labels: UI
