### ISSUE TITLE
Assert error with open Style dialog

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#25438] opened 2024-11-05 17:00 UTC
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open a new file from a fresh start of MuseScore (`-F` command line option). I selected one instrument, Flute, but I don't think it matters.
2. Open the Style dialog and wait.
3. After a few seconds it crashes with an assert.

### Supporting files, videos and screenshots

The assert happens at line `555` of `interactiveprovider.cpp` in `InteractiveProvider::topWindow`.

<img width="442" alt="Screen Shot 2024-11-05 at 10 59 08 AM" src="https://github.com/user-attachments/assets/bad459f5-4822-4c51-8551-1befee74b40b">

### What is the latest version of MuseScore Studio where this issue is present?

Current development environment.

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 12.7.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by rpatters1** [comment] 2024-11-05 17:09
I just got the same thing on the Create Time Sig dialog. It may affect any dialog box.

**Comment by cbjeukendrup** [comment] 2024-11-05 21:17
See also https://github.com/musescore/MuseScore/issues/24668 (your own, actually 🙂) and https://github.com/musescore/MuseScore/issues/17869

**Comment by rpatters1** [comment] 2024-11-05 22:42
Lol, I thought it seemed familiar. But I also thought it had been fixed.

**Comment by bkunda** [comment] 2024-11-08 14:30
Closing as it seems to be a duplicate of (or at least adequately covered by) #24668.

**Closed by bkunda** 2024-11-08 14:30 UTC
Labels: regression MS4, crash

**Comment by rpatters1** [comment] 2024-11-08 15:19
I'm fine with closing this one, but the reason I opened it is that the crash with the Style dialog is new behavior since a fairly recent PR. It also makes testing on the dev branch quite difficult, which it was not up until a week or 10 days ago.
