### ISSUE TITLE
Midi export: note length of grace note / appoggiatura inaccurate

### ISSUE THREAD

**Issue by sclsj** [musescore/MuseScore#22111] opened 2024-03-29 21:16 UTC
### Issue type

Import/export issue

### Bug description

This is a WIP score; I exported all to midi and imported it into Logic and did some processing/panning/etc a few months ago. Now when I made a lot of progress on the vocal and want to check how it sounds in Logic, the note lengths are inaccurate. I didn't change the first section at all so this might be a regression or the score is corrupted.

### Steps to reproduce

1. Open the file [fictional_blue.mscz.zip](https://github.com/musescore/MuseScore/files/14808614/fictional_blue.mscz.zip)
2. Export the vocal as midi [fiction blue vocal export midi problem.zip](https://github.com/musescore/MuseScore/files/14808622/fiction.blue.vocal.export.midi.problem.zip)
3. Examine the midi in an editor

### MuseScore Version

4.2.1 (lastest)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 12

### Additional context

[Fiction Blue vocal in Logic Pro exported from MuseScore a few months ago potentially modified in logic.mid.zip](https://github.com/musescore/MuseScore/files/14808631/Fiction.Blue.vocal.in.Logic.Pro.exported.from.MuseScore.a.few.months.ago.potentially.modified.in.logic.mid.zip)

**Comment by bluebear94** [comment] 2024-04-13 05:52
Might be related to #18699; the code for playback within MuseScore and for MIDI export are different.

**Comment by DmitryArefiev** [comment] 2024-05-14 09:40
> Might be related to #18699; the code for playback within MuseScore and for MIDI export are different.

Nope, it was broken earlier..  (see https://github.com/musescore/MuseScore/issues/22669#issuecomment-2109741145)

**Comment by DmitryArefiev** [comment] 2024-05-14 09:41
Closing as duplicate of #22669 

Thanks for logging!

**Closed** 2024-05-14 09:42 UTC
