### ISSUE TITLE
MS4 Crashes when I select Kontakt Player 7

### ISSUE THREAD

**Issue by datario-viz** [musescore/MuseScore#21777] opened 2024-03-01 20:24 UTC
### Issue type

Crash or freeze

### Bug description

Whenever I set my sounds for my instruments to Kontakt player 7, it crashes.

### Steps to reproduce

1. Open **any** musescore file
2. Go to mixer
3. Change sound to Kontakt player 7
4. Crashes after a few seconds

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 14.3.1

### Additional context

Kontakt player 7 from native instruments

**Comment by zacjansheski** [comment] 2024-03-05 19:11
I can't reproduce this on Windows with Kontakt 7

Could you please share diagnostic files?

**Comment by datario-viz** [comment] 2024-03-05 19:24
[diag1.zip](https://github.com/musescore/MuseScore/files/14500268/diag1.zip)

Hi, here is the diagnostic files

**Comment by zacjansheski** [comment] 2024-03-05 19:27
@RomanPudashkin Please take a look at the diagnostic files

**Comment by DmitryArefiev** [comment] 2024-03-06 16:10
It could be the same as #21372

@datario-viz What is your Kontakt version?

**Comment by DmitryArefiev** [comment] 2024-03-06 20:53
Thanks! Yes, it's  the same crash as #21372 and macOS only

For now, you can use Kontakt 6

**Comment by DmitryArefiev** [comment] 2024-03-06 20:54
Closing as dupe of #21372

**Closed** 2024-03-06 20:54 UTC
Labels: needs info, crash
