### ISSUE TITLE
'Tuning' plugins don't work in MU4 Beta

### ISSUE THREAD

**Issue by havizvaisal** [musescore/MuseScore#13896] opened 2022-10-23 04:45 UTC
No tuning plugin makes any effect on the tuning of Muse Basic sounds in Musescore 4 Beta, when they did in Musescore 3.6.2.

**To Reproduce**
1. Go to 'Plugins'
2. Click on any tuning plugin
3. Select tuning and click 'apply'
4. Playback is unaffected, continues playing in equal temperament.

**Expected behavior**
A change in the tuning of each note by the specified cents of the tuning selected.

**Platform information**
 - OS: [Linux, Ubuntu 22.04.1 LTS]

**Comment by erinic04** [comment] 2022-10-23 05:00
retuning in general is broken right now

**Comment by Tantacrul** [comment] 2022-10-23 09:03
I imagine this is related to the fact our outstanding issue where tuning options in the inspector are not yet plugged in.

**Comment by cbjeukendrup** [comment] 2022-10-23 15:54
> I imagine this is related to the fact our outstanding issue where tuning options in the inspector are not yet plugged in.

The problem is not in the Inspector, but in the playback rendering itself. That is why it currently doesn't work for plugins either.

**Comment by vpereverzev** [comment] 2022-10-24 00:37
> I imagine this is related to the fact our outstanding issue where tuning options in the inspector are not yet plugged in.

Yeah, more or less duplicate of #10990

**Comment by vpereverzev** [comment] 2022-11-02 20:38
@havizvaisal please check on the next nightly

**Closed** 2022-11-02 20:37 UTC
Labels: P2

**Comment by Xtarich** [comment] 2022-11-04 05:14
@vpereverzev I'm afraid the tuning plugins still don't work for me. I'm using the latest nightly on Windows 10.
