### ISSUE TITLE
[MU4 Issue] Scaling in Windows is not incremental

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9929] opened 2021-11-30 13:05 UTC
**Describe the bug**
Changing the display scaling in Windows results in only two levels of scaling in MuseScore (effectively, a small and a large scaling level).

This is especially pronounced when using MS on a large monitor with an extended display configuration (although the more I look into it, the less I'm convinced that connecting an external monitor might be the real cause of this problem). 

Basically, scaling options on a large external display result in MuseScore being displayed either somewhat large, or very small. 

This video attempts to show what happens when the scaling is adjusted: 

https://user-images.githubusercontent.com/86290556/144052213-950c3a2b-f407-4eee-8334-31a543acc347.mp4

**Expected behavior**
Scaling should be incremental in 25% intervals, as per other apps (see MS Word example in above video).

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**
Possibly related to #9263 
Also a problem in MS3.6 (see above video)

**Comment by DmitryArefiev** [comment] 2021-12-29 08:12
Tested #9956 on Win10, laptop with **FullHD** display  - now MU also changes scaling when switching to **125%**

**Comment by DmitryArefiev** [comment] 2021-12-29 08:14
@bkunda Would be good to check this on a large display and Win11 as well. Thanks!

**Comment by bkunda** [comment] 2022-01-06 07:01
@DmitryArefiev I've checked this on my system and scaling now appears wonderfully incremental. Fixed from my end 🙂

**Comment by DmitryArefiev** [comment] 2022-01-13 10:38
Hi @bkunda, Can you check it on your Windows again please? 
On my **Win10** and latest **master build** I don't see a **different between 100% and 125%** in app size. Maybe something was broken or just something wrong in my environment..

Thanks!

**Comment by bkunda** [comment] 2022-01-13 12:12
Yeah I'm also having a problem here now. 
There seems to be a slight resizing of the app window between 100% and 125%, but no change in the topbar, toolbar or sidebar sizes. Then there is a huge jump in size from 125% to 150%. 
This is the case for the both monitors (laptop and external monitor).

**Comment by DmitryArefiev** [comment] 2022-01-14 15:52
@bkunda Thanks for checking! Let's reopen this.

**Comment by DmitryArefiev** [comment] 2022-01-14 16:29
The same issue #10267 was opened recently.. Let's close the initial bug #9929 :)

**Comment by bkunda** [comment] 2022-01-17 05:24
Issue now raised in #10267

**Comment by DmitryArefiev** [comment] 2022-01-19 15:27
Since  it's hard to reproduce #10267 (the issue about File menu placement on 125%) let's reopen the current issue #9929 to fix incremental bug on 125%

**Comment by DmitryArefiev** [comment] 2022-02-08 13:17
@bkunda Hi, can you check this in Windows build from #10285?

On my side, the score looks a bit blurry on 125% and 150% (Win10)

Thanks!

**Comment by bkunda** [comment] 2022-02-09 06:37
@DmitryArefiev it seems pretty clear on my 4k monitor, and the scaling now appears to work correctly.
There is some fuzziness when I move the app to my native laptop display, but no more fuzziness than usual (I think this has more to do with my crappy Asus laptop monitor than anything else 😅).

**Comment by DmitryArefiev** [comment] 2022-02-11 14:35
Thanks for checking!

Probably that occurs only on FullHD displays. I've connected an external full HD monitor to my laptop and still have that blurry thing on 125/150.

**Comment by Marr11317** [comment] 2022-04-22 22:38
This issue occurs on my side too, with windows 11, by default. Musescore is way too small when opened for the first time with 125% scaling (default).

It might be because of HiDPI displays or something, but currently the top toolbar is only 25 px high, wich feels very small.

**Comment by Marr11317** [comment] 2022-04-22 22:41
After measurement: the top toolbar text seems to have a height of 12px in mu4, compared to 15px in mu3

**Comment by Marr11317** [comment] 2022-04-22 22:45
At 150% it gets Huge:
![image](https://user-images.githubusercontent.com/35939574/164814064-8174d5de-37dc-4d76-b657-cf152512c646.png)

There seems to be no difference between 100% and 125%

**Comment by DmitryArefiev** [comment] 2022-06-28 10:08
Fixed in #10285

But also a bug with score blurring appears now (I will log it separately)

**Closed** 2022-06-28 10:09 UTC
Labels: P1
