### ISSUE TITLE
Adding an offset to the first bar number does not affect the bar numbers in the next systems

### ISSUE THREAD

**Issue by dovfa** [musescore/MuseScore#21081] opened 2024-01-18 21:07 UTC
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When you renumber the first bar in your score to have a number other than 1, e.g., 5, the next bars in the first system are renumbered correctly. But the bars in the next systems keep their previous number.

### Steps to reproduce

1. Open any score with more that one system
2. Note that the first bar in your score shows its number as 1. The first bar in the second system has a different number, say N.
3. Right click on the first bar. In **Measure properties=> Add to measure number**, write 4.
4. The first bar in the first system has now number 5.
**Expected**: The number of the first bar in the second system is now N+4
**Actual**: The number of the first bar in the second system remains N.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/157066720/e9b7f0f8-6916-4048-b8a0-c438c1aa6ea9

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment] 2024-01-18 21:11
This seems to be already fixed for the upcoming 4.2.1 release, presumably as part of the same fix as for https://github.com/musescore/MuseScore/issues/20768

**Comment by oktophonie** [comment] 2024-01-19 13:05
Duplicate of https://github.com/musescore/MuseScore/issues/21047 and https://github.com/musescore/MuseScore/issues/20768

**Closed by oktophonie** 2024-01-19 13:05 UTC
Labels: UI, duplicate
