### ISSUE TITLE
Toggle tempo text duplication

### ISSUE THREAD

**Issue by dpMusicman** [musescore/MuseScore#25006] opened 2024-10-02 01:23 UTC
### Your idea

Create a toggle in the Style menu to duplicate the tempo text lower down in the score, as is already possible with orchestral templates.

### Problem to be solved

The inability to manually control tempo text duplication in scores, instead having to rely on templates

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Dima-S-Jr** [comment] 2024-10-02 06:33
Duplicate of #24100

**Comment by oktophonie** [comment] 2024-10-02 07:43
UI for is this intended for 4.5 (finally).

**Closed by oktophonie** 2024-10-02 07:43 UTC
Labels: feature request
