### ISSUE TITLE
[MU4 Issue] Cloud saved scores on multi-device

### ISSUE THREAD

**Issue by RrOoSsSsOo** [musescore/MuseScore#15584] opened 2022-12-25 11:03 UTC
**Describe the bug**
If you install MuseScore 4 on multiple device and you save a score on the cloud you can't open them from another device, despite all device are logged with same MuseScore.com account.

**To Reproduce**
1. Device 1: Log-in to MuseScore.com account
2. Device 1: Create and save a score on cloud
3. Device 2: Log-in to (the same) MuseScore.com account
4. Device 2: You can't open the score created in Device 1 and saved to cloud

**Expected behavior**
An automatic routine that ,on MU4 start-up phase, updates (download/sync) cloud scores automatically (consider all scores, created from any device).
Or the presence of a "Cloud sync" button on Home > Scores.

**Platform information**
 - OS: Windows, Linux [macOS not tested]

**Comment by cbjeukendrup** [comment] 2022-12-25 11:50
This is a duplicate of #15453; see that issue to track our progress. 

Thanks for reporting anyway!

**Closed by cbjeukendrup** 2022-12-25 11:50 UTC
